### ISSUE TITLE
Not able to set value for XCUIElementTypeSlider iOS simulator with Appium v1.6.5-beta

### ISSUE THREAD

**Issue by arrk-shch** [appium/appium#8264]
## The problem

Not able to set value for XCUIElementTypeSlider iOS simulator
The slider is not moving at all.

## Environment

* Appium version (or git revision) that exhibits the issue: Appium v1.6.5-beta
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: IOS 10.12
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iPhone 6s iOS 10.2
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe:

## Details

Please check the log & Code To Reproduce. I tries with setValue as well as setKeys

## Link to Appium logs
Below is log:
**With setValue :**
[HTTP] --> POST /wd/hub/session/b37d6009-af9f-4d22-a96a-7b5d98eaa550/appium/element/F059D5CF-6CF6-4A32-9378-DED79636CA95/value {"id":"F059D5CF-6CF6-4A32-9378-DED79636CA95","value":"1%"}
[debug] [MJSONWP] Calling AppiumDriver.setValueImmediate() with args: ["1%","F059D5CF-6CF6-4A32-9378-DED79636CA95","b37d6009-af9f-4d22-a96a-7b5d98eaa550"]
[debug] [XCUITest] Executing command 'setValueImmediate'
[XCUITest] There is currently no way to bypass typing using XCUITest. Setting value through keyboard
[debug] [JSONWP Proxy] Proxying [POST /element/F059D5CF-6CF6-4A32-9378-DED79636CA95/value] to [POST http://localhost:8100/session/38BBCD46-A20A-402A-9E35-C4E72B3259A8/element/F059D5CF-6CF6-4A32-9378-DED79636CA95/value] with body: {"value":["1","%"]}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"38BBCD46-A20A-402A-9E35-C4E72B3259A8","status":0}
[debug] [MJSONWP] Responding to client with driver.setValueImmediate() result: null

**With sendKeys :**
[debug] [MJSONWP] Calling AppiumDriver.setValueImmediate() with args: ["1%","1979EDF1-66D8-4505-8724-628B4E14DFD8","330a9116-83bc-4307-ad50-f912e086027a"]
[debug] [XCUITest] Executing command 'setValueImmediate'
[XCUITest] There is currently no way to bypass typing using XCUITest. Setting value through keyboard

[HTTP] --> POST /wd/hub/session/07cbc44c-1942-4256-955e-45c102a7a153/element/8FF6EF14-27AC-4ACD-B5A0-6B61F99514E3/value {"id":"8FF6EF14-27AC-4ACD-B5A0-6B61F99514E3","value":["1.0"]}
[debug] [MJSONWP] Calling AppiumDriver.setValue() with args: [["1.0"],"8FF6EF14-27AC-4ACD-B5A0-6B61F99514E3","07cbc44c-1942-4256-955e-45c102a7a153"]
[debug] [XCUITest] Executing command 'setValue'
[debug] [JSONWP Proxy] Proxying [POST /element/8FF6EF14-27AC-4ACD-B5A0-6B61F99514E3/value] to [POST http://localhost:8100/session/13423419-132D-4803-83F9-86FC2EE0A1C0/element/8FF6EF14-27AC-4ACD-B5A0-6B61F99514E3/value] with body: {"value":["1",".","0"]}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"13423419-132D-4803-83F9-86FC2EE0A1C0","status":0}
[debug] [MJSONWP] Responding to client with driver.setValue() result: null

## Code To Reproduce Issue [ Good To Have ]
Tried with both setValue & sendKeys
public void setSliderValue(By locator){
	MobileElement iosElement=(MobileElement) wd.findElement(locator);
	iosElement.setValue("1%");
}

public void setSliderValue(By locator){
	MobileElement iosElement=(MobileElement) wd.findElement(locator);
	iosElement.sendKeys("1.0");
}

**Comment by mykola-mokhnach** [comment]
This is the code responsible for setting slider position in WDA:

```objc
  if (element.elementType == XCUIElementTypeSlider) {
    CGFloat sliderValue = textToType.floatValue;
    if (sliderValue < 0.0 || sliderValue > 1.0 ) {
      return FBResponseWithErrorFormat(@"Value of slider should be in 0..1 range");
    }
    [element adjustToNormalizedSliderPosition:sliderValue];
    return FBResponseWithOK();
  }
```

As you can see only values in range [0.0, 1.0] are supported. Also, the matched element itself should have type _XCUIElementTypeSlider_

**Comment by arrk-shch** [comment]
Thanks for quick reply.
I have tried with "0.1" but still its not working for me.
Log:
[HTTP] --> POST /wd/hub/session/d4933c59-5663-4f9e-94e7-a14e0b4ceecc/element/4C0CF4B7-189F-4616-AD53-84319C80554D/value {"id":"4C0CF4B7-189F-4616-AD53-84319C80554D","value":["0.1"]}
[debug] [MJSONWP] Calling AppiumDriver.setValue() with args: [["0.1"],"4C0CF4B7-189F-4616-AD53-84319C80554D","d4933c59-5663-4f9e-94e7-a14e0b4ceecc"]
[debug] [XCUITest] Executing command 'setValue'
[debug] [JSONWP Proxy] Proxying [POST /element/4C0CF4B7-189F-4616-AD53-84319C80554D/value] to [POST http://localhost:8100/session/79767FBA-4463-43C2-A5F7-569586268BF7/element/4C0CF4B7-189F-4616-AD53-84319C80554D/value] with body: {"value":["0",".","1"]}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"79767FBA-4463-43C2-A5F7-569586268BF7","status":0}
[debug] [MJSONWP] Responding to client with driver.setValue() result: null

**Comment by mykola-mokhnach** [comment]
Make sure the located element is of type _XCUIElementTypeSlider_ (element.getAttribute("type") should be equal "XCUIElementTypeSlider"). If it is then report the issue directly to https://github.com/facebook/WebDriverAgent/issues

**Comment by dpgraham** [comment]
I think this is related to https://github.com/facebook/WebDriverAgent/commit/d5694557113d6f875457472c7bb0501e21155ec5

**Comment by mykola-mokhnach** [comment]
@dpgraham The code in WDA is correct from XCTest's [point of view](http://masilotti.com/ui-testing-cheat-sheet/). And this is most likely an Apple bug then if it does not work as expected. However you may try to perform drag gesture on the slider to workaround the problem.

**Comment by jlipps** [comment]
Closing since this appears to be an apple bug. Maybe app-dependent? I loaded up an app w/ Appium Desktop and successfully changed a slider using sendKeys to my heart's content.
