### ISSUE TITLE
I cannot run same test on multiple devices at the same time

### ISSUE THREAD

**Issue by alexander-poulikakos** [appium/appium#8265]
## The problem

I want to run same test on multiple devices at the same time. When starting the test at the same time The test runs well on deviceX, but hangs for deviceY. It's hanging in this call: ` new IOSDriver<>(server.getUrl(), caps);` (see complete code below). When running the tests on one device at the time it works well.

I use two Appium Servers, one per device. It seems like when the first one finishes and stops, it also stops the other server.

When looking at the appium log for deviceX:

```
2017-04-11 15:13:42:261 - info: [debug] [Instruments] Sending SIGTERM
```

then in deviceY log it seems as something is shutdown at the same time.
```
2017-04-11 15:13:43:122 - info: [debug] [Instruments] [INST] 2017-04-11 15:13:43 +0000 Error: Script threw an uncaught JavaScript error: JSON Parse error: Unexpected EOF on line 2698 of bootstrap-a49901b8d5460b1f.js
2017-04-11 15:13:43:246 - info: [debug] [Instruments] [INST] 2017-04-11 15:13:43 +0000 Stopped: Script was stopped by the user
2017-04-11 15:13:43:355 - info: [debug] [Instruments] [INST STDERR] 2017-04-11 17:13:43.354 instruments[28691:44947591] Attempting to change event horizon while disengage
2017-04-11 15:13:44:080 - info: [debug] [Instruments] [INST STDERR] Instruments Trace Error : *** -[NSFileManager subpathsOfDirectoryAtPath:error:]: path is nil
```

See complete DeviceX/Y logs below. And the Java code used to reproduce this.

I'm using java_client 5.0.0-BETA06

## Environment

* Appium version (or git revision) that exhibits the issue:
`v1.6.4`

* Desktop OS/version used to run Appium:
`MAC 10.12.3`

* Node.js version (unless using Appium.app|exe):
`v7.5.0`

* Appium CLI or Appium.app|exe:
Appium CLI

## Link to Appium logs

DeviceX 
https://gist.github.com/alexander-poulikakos/bc2c0681dc1993a90fb6ed88edb3e6dc

DeviceY
https://gist.github.com/alexander-poulikakos/3685cc1230069bbfe86806a50743eb77

## Code To Reproduce Issue [ Good To Have ]

```java

package _play;

import java.io.File;
import java.nio.file.Paths;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.remote.DesiredCapabilities;

import io.appium.java_client.ios.IOSDriver;
import io.appium.java_client.ios.IOSElement;
import io.appium.java_client.service.local.AppiumDriverLocalService;
import io.appium.java_client.service.local.AppiumServiceBuilder;

public class _MultipleDevice {

	public static void main(String[] args) throws Throwable {
		ExecutorService exec = Executors.newFixedThreadPool(5);
		exec.execute(() -> run(caps1()));
		exec.execute(() -> run(caps2()));

		exec.shutdown();
		System.out.println("*******END! " + exec.awaitTermination(30, TimeUnit.MINUTES));
	}

	static void run(DesiredCapabilities caps) {
		Map<String, String> env = new HashMap<>(System.getenv());
		env.put("PATH", "/usr/local/bin:" + System.getenv("PATH"));

		String udid = (String) caps.getCapability("udid");
		File logFile = Paths.get(System.getProperty("user.home"))
				.resolve("temp/appium")
				.resolve(udid + ".log")
				.toFile();
		AppiumDriverLocalService server = new AppiumServiceBuilder()
				.withIPAddress("127.0.0.1")
				.withLogFile(logFile)
				.withEnvironment(env)
				.withArgument(() -> "--log-timestamp")
				.usingAnyFreePort()
				.build();
		server.start();

		IOSDriver<IOSElement> driver;
		driver = new IOSDriver<>(server.getUrl(), caps); // <-- Hangs here !!!
		driver.getOrientation();
		driver.closeApp();
		server.stop();
		System.out.println("******** Server Stopped: " + caps.getCapability("udid"));
	}

	static DesiredCapabilities caps1() {
		DesiredCapabilities caps = caps();
		caps.setCapability("platformVersion", "8.2");
		caps.setCapability("udid", "e58e849abaa5cae1bab087793dde47f03d439231");
		return caps;
	}

	static DesiredCapabilities caps2() {
		DesiredCapabilities caps = caps();
		caps.setCapability("platformVersion", "9.2");
		caps.setCapability("udid", "73e0249e89baa62aedcb0372afe7048debf492a6");
		return caps;
	}

	static DesiredCapabilities caps() {
		DesiredCapabilities caps = new DesiredCapabilities();
		caps.setCapability("app", "/path/to/my.app");
		caps.setCapability("bundleId", "com.my.bundle.id");
		caps.setCapability("fullReset", true);
		caps.setCapability("deviceName", "IPhone");
		return caps;
	}
}

```

**Comment by mykola-mokhnach** [comment]
Check https://github.com/saikrishna321/AppiumTestDistribution

Appium server itself does not neither test nor officially supports parallel execution.

**Comment by alexander-poulikakos** [comment]
> Appium server itself does not neither test nor officially supports parallel execution.

As I understand it, it should be possible to test on two devices at the same time, if two appium server is used. One per devices. then the tests should run independent of each other. Is this not the case? I'm not suggesting to run tests in parallell on same appium server.

**Comment by saikrishna321** [comment]
@alexander-poulikakos 

>it should be possible to test on two devices at the same time, if two appium server is used

Yes, that's how AppiumTestDistribution works

**Comment by alexander-poulikakos** [comment]
> Yes, that's how AppiumTestDistribution works

So, am I doing anything wrong or different in my code above, compared with AppiumTestDistribution? I'll have a look at AppiumTestDistribution.

Seems like when ServerX is shutdown, there is an uncaught JavaScript error on ServerY, which causes 
this call to hang:  `new IOSDriver<>(server.getUrl(), caps);` 

`
[Instruments] [INST] 2017-04-11 15:13:43 +0000 Error: Script threw an uncaught JavaScript error: JSON Parse error: Unexpected EOF on line 2698 of bootstrap-a49901b8d5460b1f.js
`

I'll go ahead and have a look

**Comment by alexander-poulikakos** [comment]
Adding a unique tmp log directory for each device seems to have solved the problem.

Modified piece of code (compared with code in first post)
```java
		String tmpDir = null;
		try {
			tmpDir = Files.createTempDirectory("appium").toAbsolutePath().toString();
		} catch (IOException e) {
			// TODO Handle error!
			throw new IllegalStateException(e);
		}

		String udid = (String) caps.getCapability("udid");
		File logFile = Paths.get(System.getProperty("user.home"))
				.resolve("temp/appium")
				.resolve(udid + ".log")
				.toFile();
		AppiumDriverLocalService server = new AppiumServiceBuilder()
				.withIPAddress("127.0.0.1")
				.withLogFile(logFile)
				.withEnvironment(env)
				.withArgument(() -> "--tmp", tmpDir) // <-- NEW LINE
				.withArgument(() -> "--log-timestamp")
				.usingAnyFreePort()
				.build();
		// TODO Delete tmpDir when server is stopped?
```

**Comment by alexander-poulikakos** [comment]
I was wrong. It does not work due to this: #7373
