### ISSUE TITLE
iOS driver ios-webkit-debug-proxy "unit" tests need to be made into unit tests

### ISSUE THREAD

**Issue by imurchie** [appium/appium#8266]
The [ios-webkit-debug-proxy tests](https://github.com/appium/appium-ios-driver/blob/master/test/unit/iwdp-specs.js) actually invoke i-w-d-p and send network calls. Ack!

**Comment by dpgraham** [comment]
Can I just move them over to e2e tests? I would still like to have tests that actually run the IWDP.

**Comment by imurchie** [comment]
Yes, you can.

Two things about https://github.com/appium/appium-ios-driver/blob/master/test/unit/iwdp-specs.js#L36-L40 though:

1. The call to `request` (https://github.com/appium/appium-ios-driver/blob/master/test/unit/iwdp-specs.js#L39) needs to be `await`ed or else it doesn't work as expected.
2. You need to make sure that iwdp is not already running somewhere else, for these tests to work correctly (that's how it came to my attention, because I had it running else where and I ended up with  the log (`Unhandled rejection AssertionError: expected promise to be rejected but it was fulfilled with '<html><head><title>i(am)Phone</title></head><body>Inspectable pages for <a title="a77841db006fb1762fee0bb6a2477b2b3e1cfa7f">i(am)Phone</a>:<p><ol>\n</ol></body></html>'` though the test passed).

**Comment by dpgraham** [comment]
PR made. This is good example of why you should write tests that fail first.
