### ISSUE TITLE
Error: Could not match line:      (SIMULATOR  UDID) (Shutdown)

### ISSUE THREAD

**Issue by pmck91** [appium/appium#8268]
## The problem

Unable to start driver with the following caps:
{
  "caps": {
    "platformName": "iOS",
    "platformVersion": 10.2,
    "deviceName": "102Air2",
    "app": "./my.app",
    "automationName": "xcuitest",
    "noReset": true,
    "sendKeyStrategy": "setValue",
    "newCommandTimeout": 300
  }
}

## Environment

* Appium 1.6.3
* appium_lib Ruby 2.2.2
* iOS 10.2
* xcode 8.3

## Link to Appium logs

[Appium Logs](https://gist.github.com/pmck91/97af164f2902554c6644a77bcc0a9076)

## Code To Reproduce Issue [ Good To Have ]

driver = Appium::Driver.new(caps)
driver.start_driver

**Comment by mykola-mokhnach** [comment]
What is the output of

```
xcrun simctl list
```

command?

**Comment by pmck91** [comment]
== Device Types ==
iPhone 4s (com.apple.CoreSimulator.SimDeviceType.iPhone-4s)
iPhone 5 (com.apple.CoreSimulator.SimDeviceType.iPhone-5)
iPhone 5s (com.apple.CoreSimulator.SimDeviceType.iPhone-5s)
iPhone 6 (com.apple.CoreSimulator.SimDeviceType.iPhone-6)
iPhone 6 Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-6-Plus)
iPhone 6s (com.apple.CoreSimulator.SimDeviceType.iPhone-6s)
iPhone 6s Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-6s-Plus)
iPhone 7 (com.apple.CoreSimulator.SimDeviceType.iPhone-7)
iPhone 7 Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-7-Plus)
iPhone SE (com.apple.CoreSimulator.SimDeviceType.iPhone-SE)
iPad 2 (com.apple.CoreSimulator.SimDeviceType.iPad-2)
iPad Retina (com.apple.CoreSimulator.SimDeviceType.iPad-Retina)
iPad Air (com.apple.CoreSimulator.SimDeviceType.iPad-Air)
iPad Air 2 (com.apple.CoreSimulator.SimDeviceType.iPad-Air-2)
iPad Pro (9.7-inch) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro--9-7-inch-)
iPad Pro (12.9-inch) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro)
Apple TV 1080p (com.apple.CoreSimulator.SimDeviceType.Apple-TV-1080p)
Apple Watch - 38mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-38mm)
Apple Watch - 42mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-42mm)
Apple Watch Series 2 - 38mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-2-38mm)
Apple Watch Series 2 - 42mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-2-42mm)
== Runtimes ==
iOS 9.3 (9.3 - 13E233) (com.apple.CoreSimulator.SimRuntime.iOS-9-3)
iOS 10.0 (10.0 - 14A345) (com.apple.CoreSimulator.SimRuntime.iOS-10-0)
iOS 10.1 (10.1 - 14B72) (com.apple.CoreSimulator.SimRuntime.iOS-10-1)
iOS 10.2 (10.2 - 14C89) (com.apple.CoreSimulator.SimRuntime.iOS-10-2)
iOS 10.3 (10.3 - 14E269) (com.apple.CoreSimulator.SimRuntime.iOS-10-3)
tvOS 10.2 (10.2 - 14W260) (com.apple.CoreSimulator.SimRuntime.tvOS-10-2)
watchOS 3.2 (3.2 - 14V243) (com.apple.CoreSimulator.SimRuntime.watchOS-3-2)
== Devices ==
-- iOS 9.3 --
-- iOS 10.0 --
-- iOS 10.1 --
-- iOS 10.2 --
     (BE4CA299-5A2D-4FD2-8973-DBCCEC436755) (Shutdown)
     (342489AA-9AE4-45DD-BB52-72C2775C740C) (Shutdown)
     (55554CFE-3387-4259-A94E-921884C174AB) (Shutdown)
    102Air2 (DFADBD2D-9947-4DFD-95A4-051BABA721BF) (Shutdown)
-- iOS 10.3 --
    103Air2 (3E18F705-D262-4162-AC23-06592F2D407D) (Booted)
-- tvOS 10.2 --
-- watchOS 3.2 --
    Apple Watch - 38mm (B3EC774B-A558-4171-99AC-95C44442004C) (Shutdown)
    Apple Watch - 42mm (BD8B25A3-37EC-438A-9FF3-F8ED01552A5F) (Shutdown)
    Apple Watch Series 2 - 38mm (051E9E57-56BF-4D18-993D-0CA0E71D3B37) (Shutdown)
    Apple Watch Series 2 - 42mm (DE05752D-5077-475F-9F9F-3E7D8800039A) (Shutdown)

**Comment by mykola-mokhnach** [comment]
change **platformVersion** value to '10.2'. it must be a string

**Comment by mykola-mokhnach** [comment]
either remove or rename devices with empty names under 10.2 platform version

**Comment by pmck91** [comment]
no luck with either option

**Comment by mykola-mokhnach** [comment]
how the log looks now?

**Comment by pmck91** [comment]
I spoke too soon. It looks like the issue was being caused by the unnamed sims. Cheers Ill close now.
