### ISSUE TITLE
Can't navigate to a website

### ISSUE THREAD

**Issue by h3dkandi** [appium/appium#8269]
## The problem

Making iOS Safari to change  url doesn't seem to work.

## Environment

* Appium version (or git revision) that exhibits the issue: Appium v1.6.3 (REV d8427c47060a09b4194252c5ba83c7e7722080d9)
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS
* Node.js version (unless using Appium.app|exe): v 7.4.0
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

I had to update Appium due to the latest Xcode version and now my tests can't navigate to the needed website when testing on iOS Safari.
In the logs you can see it tries to do setUrl() to <webSite> and then it waits for an element "inputLogin".
Could it be that I have to update some other dependency for example ios_webkit_debug_proxy wich is 1.7.1 or something else.

## Link to Appium logs

Appium [log](https://gist.github.com/h3dkandi/faaca93754e1be48402ad9f57a4e3497)

## Code To Reproduce Issue [ Good To Have ]
Partial code from my automated tests. (Sleep() is a custom function)

```
driver.Navigate().GoToUrl(baseURL + "document.asp?alias=smlogin");
driver.Sleep(3 * 1000);
WebDriverWait _wait = new WebDriverWait(driver, TimeSpan.FromSeconds(180));
_wait.Until(d => d.FindElement(By.Id("inputLogin")));
```

**Comment by mykola-mokhnach** [comment]
Try Appium 1.6.4
Also, there is a new **startIWDP** capability, which should start the proxy automatically.

**Comment by h3dkandi** [comment]
How do I try Appium 1.6.4? My appium is from git and I updated it like 8 days ago. Isn't that near latest?

**Comment by h3dkandi** [comment]
I found the problem. It is me :/. I was playing with backups and it seems that the packages.json had changes in it which would fail my git pull. I didn't notice that in the automatic appium update script that I was using. So my appium was not updated correctly.
