### ISSUE TITLE
Appium Scripts integration with Jenkins

### ISSUE THREAD

**Issue by UserAutomation** [appium/appium#8270]
## The problem
I am writing my Test Cases using maven project in Intelij IDE framework. I want to run them through jenkins whenever i push a change in git repository. At this moment when i try to build a new jenkins job the scripts fails at the point where driver tries to establish a connection with local host The error is 

setUp(scenarios.AppiumTest)  Time elapsed: 1.207 sec  <<< FAILURE!
org.openqa.selenium.WebDriverException: org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:4723 [/127.0.0.1] failed: Connection refused (Connection refused)
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: 'localhost.localdomain', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-327.36.2.el7.x86_64', java.version: '1.8.0_112'

other than that i have some questions: 

1. Do i need to start appium server by terminal or can i start it in software form ?
2. Can i run my scripts from jenkins without running appium ?
3. Do i need to change app path too ?
4. Do i need to start emulator too manually? 

I tried to modify the desired capabilities but really cant get a fruitful result.
i am so confuse about all this process. 
For next step i want to run tests on saucelabs using jenkins via git repository. Any help would be appreciated.

**Comment by mathias21** [comment]
Hi @UserAutomation 

It looks like you need to understand some specific topics related with Appium before going too deep. Let me try to answer your questions by order:

> Do i need to start Appium server by terminal or can i start it in software form ?
If you run your tests in a different machine (Jenkins one), this one must have the specific port available and you need to start server in it. You can also start servers somewhere else but you need to be sure these servers will be reachable by IP/URL (this should be resolved by DNS) and PORT.
You can start servers in any way you want, but server must be available and reachable from test running machine.

> Can i run my scripts from jenkins without running appium ?
If you want to run tests using Appium, how are you not running Appium? I believe you meant Appium server, so the answer is NO. You always need a server to reach device/emulator.

> Do i need to change app path too ?
Right now this question is irrelevant, but app must be available in any machine where you want to run your tests. App path must point to where the app is placed.

> Do i need to start emulator too manually?
Unless you can automate that task, emulator must be available and must be visible for ADB. Not sure about IOS though.


Please make sure every time you want to reach a device, a proper server is instantiated and running. While server is not UP, tests will fail as they won't be able to reach device.

I would definitely suggest you to first get the knowledge in local to run your tests and only then try a transition to the cloud.

**Comment by UserAutomation** [comment]
Thank you so much for your detailed reply @mathias21.

one more thing that i want to ask. I am running appium server by appium & command and it runs my scripts perfectly. 

But when i try to run them from jenkins job it fails at the time of connection establishing even though server is running. 

Any words on that ?

**Comment by mathias21** [comment]
Are you running this Jenkins job in a different machine where server is started? if yes, then you need to specify, when getting the driver, this new machine ip (127.0.0.1:4723 this is from local machine, so the one where tests are being run). If not then it might be a problem with port already used.

**Comment by mykola-mokhnach** [comment]
Please move this topic to Appium forum. This is the place for issues only
