### ISSUE TITLE
ios device can't find offscreen element 

### ISSUE THREAD

**Issue by derunewige** [appium/appium#8271]
## The problem

I have working tests running on simulator which are all good. Now I try to run them on a real device.
Everything seems to be good, but one case where I want to click on an element which is offscreen.
On simulator I find the element via Accessibility ID, scroll to it and click it.
Running on real device Appium is not able to find the element. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4-beta2 AND 1.6.5-beta
* Desktop OS/version used to run Appium:  macOS 10.12.4
* Node.js version (unless using Appium.app|exe): 6.9.1
* Mobile platform/version under test: iOS 10.3
* Real device or emulator/simulator: real device iPhone6
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs

https://gist.github.com/derunewige/ea1731871bcd2aa8cd2f8e45bc1efcd4#file-gistfile1-txt

## Code To Reproduce Issue [ Good To Have ]

```
private static By devSettings = MobileBy.AccessibilityId("offcanvas.devSettings.identifier");
this.wait = new WebDriverWait(driver, 10);
wait.until(ExpectedConditions.presenceOfElementLocated(devSettings));
IOSElement elem = driver.findElement(devSettings);
if (!elem.isDisplayed()) {
   driver.performTouchAction(new IOSTouchAction(driver).press(0, 0).moveTo(elem).release());
}
elem.click();
```

**Comment by vjmaiky** [comment]
public static void refreshEmailListUntilEmailIsDisplayed(String subject) {
		int retry = 0;
		while (retry < 20) {
			try {
				WebElement we = null;
				we = AppiumDriverInstance.getInstance().findElementById(subject);
				if (we.isDisplayed()) {
					break;
				}
			} catch (Throwable e) {
				swipe_DownWithTouch();
			}
			retry++;
		}
	}

**Comment by vjmaiky** [comment]
i use that kind of thing as workaround

**Comment by mykola-mokhnach** [comment]
I don't see any issues in the log. Try[ other gestures](https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios-xctest-mobile-gestures.md) to reach the invisible element.

**Comment by imurchie** [comment]
Can you try scrolling using (syntax for your language will vary on the execute part):
```
IOSElement elem = driver.findElement(devSettings);
driver.execute('mobile: scroll', {element: elem, toVisible: true});
```

**Comment by derunewige** [comment]
Okay, it works after swiping down, and then searching for the element. 
It is just unexpected behaviour for me because usually Appium finds everything, doesn't matter if visible or not, and then I scroll to it. 

Thank you for your help!!
