### ISSUE TITLE
I find a button but "it is not displayed" and can't click it

### ISSUE THREAD

**Issue by darthvader04** [appium/appium#8274]
## The problem

It seems my script is able to locate an element, but it can't click/tap it.

Apparently, my script finds a button using the ID. But when I try to click it, I can't. I actually printed the "element.isDisplayed()" and I got "false" in the result. I printed also "element.getLocation()" and I got "(0,0)". I think this is an issue because it seems that I'm not locating the element, but I'm not getting any error. However, when I use a value for the ID that I know that doesn't exist in my page, I actually get the "No Such Element", "Can't find element 'element' by id", etc..

## Environment

* Appium version: 1.5.3
* Desktop OS/version used to run Appium: MAC OS X 10.11.6 El Capitan
* Node.js version: Using the Appium app. But just in case, Node V 7.7.4
* Mobile platform/version under test: Android 5.0
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium App

## Details

Not sure if this is related but just to let you know:

*When I open the app to be tested, I need to change the context to WEBVIEW, I can find my elements and work with them.
*Within the app, I need to open another view, so, I change the windowHandle and this is when the problem comes. In this new View is where I'm having the issue.
*Before to make the change of windowHandle, I make again a change in the Context.

1.- Change context to WEBVIEW.
2.- Open the other View.
3.- Change context to WEBVIEW.
4.- Change WindowHandle.

## Link to Appium logs

As I mentioned before, when I look for the correct value of the ID, I don't get any error. My scripts end with exit code 0 and no Logs.

## Code To Reproduce Issue [ Good To Have ]

WebElement nextButton = driver.findElement(By.id("NextButton"));
System.out.println(nextButton.isDisplayed() + "  " + nextButton.getLocation());

**Comment by mykola-mokhnach** [comment]
Do you observe the same issue in 1.6.4?

**Comment by darthvader04** [comment]
@mykola-mokhnach Not sure if I'm doing well. When I open the "About Appium", I get version 1.0.0, but when I start the server, I get 1.6.4. However, I got the same result as mentioned before.

**Comment by darthvader04** [comment]
I don't know where the mistake is, but, the problem was that appium was recognizing two buttons by each ID:

`List<WebElement> buttons = driver.findElements(By.xpath("//button"));
for(WebElement e : buttons){
        System.out.println(e.getAttribute("id"));
}`

skipButton
skipButton
nextButton
nextButton
and so on

Then, I only did this:

`WebElement nButton = null;
  List<WebElement> buttons = driver.findElements(By.id(wichButton));
  for(WebElement e : buttons){
       if(e.isDisplayed())
           nButton = e;
  }`

I don't know if this issue(recognizing 2 buttons by each id) is from appium or from ionic, or it is normal.
