### ISSUE TITLE
Android-Nougat: Unable to switch to Airplane mode (Appium 1.6.5 Beta)

### ISSUE THREAD

**Issue by mayureshshirodkar** [appium/appium#8275]
## The problem
Unable to switch to offline mode using the setConnection(Connection.AIRPLANE);
Or switch back to the Online mode.  
There is an error in the logs for kill command.
This issue worked fine for me on Android 6.0.1.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5 Beta
* Last Appium version that did not exhibit the issue (if applicable): 1.6.4
* Desktop OS/version used to run Appium: MACOS 10.12.4
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Android 7.0
* Real device or emulator/simulator: Moto G4
* Appium CLI or Appium.app|exe: CLI

## Details
Error:
Stderr: '/system/bin/sh: kill: 16173: Operation not permitted'; Code: '1'

## Link to Appium logs

[Airplane.txt](https://github.com/appium/appium/files/930436/Airplane.txt)

## Code To Reproduce Issue [ Good To Have ]

((AndroidDriver) Setup.getInstance().getWebDriver()).setConnection(Connection.AIRPLANE);

**Comment by mykola-mokhnach** [comment]
This is OS limitation that we cannot workaround in Appium. There is no way to control Airplane mode since Android 7

**Comment by mayureshshirodkar** [comment]
@mykola-mokhnach  Will switching to uiautomator2 help with this?

**Comment by mykola-mokhnach** [comment]
Nothing helps. The only thing you can do is to turn on/off Wi-Fi

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/network_connection.md

**Comment by mayureshshirodkar** [comment]
@mykola-mokhnach i can switch on Wi-Fi using the -getWebDriver().setConnection(Connection.WIFI);

But how do i turn off the wifi programmatically, Since airplane mode will not work for Android 7 and higher. I wasn't able to find enough documentation on this.

**Comment by mykola-mokhnach** [comment]
Does it work if you just set the value to Connection.NONE?

**Comment by mayureshshirodkar** [comment]
@mykola-mokhnach  So i tried setting the Connection.NONE. But it throws an error and doesn't turn off wifi.
**Appium version**: 1.6.6 beta3
**io.appium.settings version:**2.1
Here are the logs:
https://gist.github.com/mayureshshirodkar/9e7d4288bee2d33f2333986f491863c3

I even tried setting wifi off with this command manually, but din't work.
adb shell am broadcast -a io.appium.settings.wifi --es setstatus disable

This were the logs:
08-01 18:13:13.005 10046 10046 E ExtendedServiceUtils: Failed to load libdashplayer.so : dlopen failed: library "libdashplayer.so" not found
08-01 18:13:13.009 10046 10046 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 2000 <<<<<<
08-01 18:13:13.013 10046 10046 D AndroidRuntime: CheckJNI is OFF
08-01 18:13:13.077 10046 10046 D ICU     : No timezone override file found: /data/misc/zoneinfo/current/icu/icu_tzdata.dat
08-01 18:13:13.110 10046 10046 I Radio-JNI: register_android_hardware_Radio DONE
08-01 18:13:13.127 10046 10046 D AndroidRuntime: Calling main entry com.android.commands.am.Am
08-01 18:13:13.139 10046 10046 D AndroidRuntime: Shutting down VM

**Comment by mykola-mokhnach** [comment]
This might be a bug in UIA2 then. Please report as a separate issue
