### ISSUE TITLE
[MJSONWP] Encountered internal error running command: Error: Unable to start WebDriverAgent session: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8100

### ISSUE THREAD

**Issue by Shahunks** [appium/appium#8277]
[XCUITest] Unable to connect to running WebDriverAgent: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8100

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MAC
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/Shahunks/a73696442a7ff7b083c3cd4dd72f63f1

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
This error means that WDA didn't start on the device and Appium cannot connect to it. Try to build WDA manually from xcode to make sure it can be started on simulator.
Also, there is a known bug, which prevents running WDA on simulator if Mac OS version is 10.12.4+ and Xcode version is older than 8.3

**Comment by Shahunks** [comment]
@mykola-mokhnach - i tried running WDA manually from xcode and it started on simulator, i even ran a integration app successfully. 
my os version is 10.12.2
my xcode version is 8.3.2
btw when i ran from appium desktop i am still facing the same issue. 
can you please help me ?

**Comment by mykola-mokhnach** [comment]
Set **showXcodeLog** capability to _true_, check Appium log and find the record where it creates xcodebuild log. Please attach this log the ticket.

**Comment by Shahunks** [comment]
here is the log - https://gist.github.com/Shahunks/ffc76f3ca4ca852bc09033caf862d087

**Comment by mykola-mokhnach** [comment]
It looks like Xcode is broken on this machine, because xcodebuild execution returns the control to Appium app too early. Try on some other machine

**Comment by Shahunks** [comment]
@mykola-mokhnach in other machine i am getting this - https://gist.github.com/Shahunks/491806ecd03a3d5dd6920b184a4ce817

**Comment by mykola-mokhnach** [comment]
This looks better, except it failed to execute application under test

> [JSONWP Proxy] Got response with status 200: {"value":"Failed to launch com.zapty.teamworkQC application","sessionId":"E548833A-D66F-4039-8A41-6BB3C41081CB","status":13}

but this is not an Appium problem for sure

**Comment by Shahunks** [comment]
i restarted the device too. but still same issue. should i try a real device ?

**Comment by Shahunks** [comment]
@mykola-mokhnach - can you please suggest me a workaround

**Comment by mykola-mokhnach** [comment]
Fix your application?

**Comment by Shahunks** [comment]
you mean- the problem is in my app, i will have tell dev team to fix it then ? 🐙

**Comment by mykola-mokhnach** [comment]
this is what I see looking at the log: Appium started, WDA started, application under test - not started

**Comment by Shahunks** [comment]
In the simulator i can see the app opening and immediately closing :( and then this 
[JSONWP Proxy] Got response with status 200: {"value":"Failed to launch com.zapty.teamworkQC application","sessionId":"E548833A-D66F-4039-8A41-6BB3C41081CB","status":13}

**Comment by Shahunks** [comment]
@mykola-mokhnach i got this now on real device
[XCUITest] Unable to connect to running WebDriverAgent: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8100
[XCUITest] Getting status of WebDriverAgent on device timed out. Continuing
[BaseDriver] Event 'wdaSessionAttempted' logged at 1492698270615 (19:54:30 GMT+0530 (IST))

**Comment by mykola-mokhnach** [comment]
Closing the issue as non Appium-related
