### ISSUE TITLE
Popup blocker still occurs even when setting 'safariAllowPopups' capability 

### ISSUE THREAD

**Issue by ilantc** [appium/appium#8280]
## The problem

When running a simple script that is supposed to open a new window in safari browser, I can't get through the popup blocker. The capabilities that are supposed to disable to popup blocker seem to not work for me.

## Environment

* Appium version that exhibits the issue: 1.6.3
* Desktop OS/version used to run Appium: iOS 10.0
* Mobile platform/version under test: iPhone 6 simulator
* Real device or emulator/simulator: simulator
* Here is a link to the sauceLabs session https://saucelabs.com/beta/tests/459caa2ffb0941558c2429e8b7a057da/commands#5

## Code To Reproduce Issue
```
var webdriver = require('selenium-webdriver'),
    By = webdriver.By,
    username = 'u',
    accessKey = 'k',
    driver;
 
var caps = {
    "browserName": "Safari",
    "appiumVersion": "1.6.3",
    "deviceName": "iPhone 6 Simulator",
    "deviceOrientation": "portrait",
    "platformVersion": "10.0",
    "platformName": "iOS",
    "safariAllowPopups": true,
    "safariOpenLinksInBackground": true,
    "autoAcceptAlerts": true,
    "unexpectedAlertBehaviour": "accept"
}
caps['username'] = username;
caps['accessKey'] = accessKey;


driver = new webdriver.Builder().
  withCapabilities(caps).
  usingServer("http://" + username + ":" + accessKey +
              "@ondemand.saucelabs.com:80/wd/hub").
  build();
  var url = "http://the-internet.herokuapp.com/redirector"
  driver.get(url);
  driver.findElement(By.css("[target='_blank']")).click();
  driver.quit();
```

**Comment by dpgraham** [comment]
This may be related to: https://github.com/appium/appium/issues/5832

This seems to be an ongoing issue.

**Comment by jenniferneale** [comment]
Any update on this?

**Comment by milesHero** [comment]
Any update on this please?

**Comment by Jvwalsh** [comment]
Also interested in any updates on this

**Comment by YmerejRedienhcs** [comment]
I'm encountering this issue also, I think, using webdriver.io (wdio) to drive a desktop safari (version 13).  I click a link that normally causes a sign-in window to pop up, but the window appears to be suppressed when driven by webdriver.

**Comment by mykola-mokhnach** [comment]
Should be working now
