### ISSUE TITLE
Determining the OS Version using the JAVA

### ISSUE THREAD

**Issue by pavanbachu0604** [appium/appium#8285]
Hello 

I am part of project where we are using the Android and iOS (different versions of OS). I was curious if there is any any I could determine the OS version and type using Java before the start of my runs ?
Thanks

**Comment by mykola-mokhnach** [comment]
How this question is related to Appium?

**Comment by pavanbachu0604** [comment]
Well I am using Appium to start the testing, if we are using the iOS device need to use iOSFindBy() as annotation so need to differentiate it effectively

________________________________

**Comment by dpgraham** [comment]
When you start an Appium session, you need to specify the platformName in your desired capabilities.

I recommend using environment variables. Something like

```java
...
if (System.getenv("APPIUM_PLATFORM_NAME") === "iPhone) 
  desiredCapabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "iPhone");
...
if (System.getenv("APPIUM_PLATFORM_NAME") === "iPhone) 
  iosFindBy();
...
```
