### ISSUE TITLE
can not get XCUIElementTypeOther's name of XCUIElementTypePickerWheel 

### ISSUE THREAD

**Issue by Liaojiahao** [appium/appium#8286]
## The problem

![screen shot 2017-04-20 at 10 54 36 am](https://cloud.githubusercontent.com/assets/7369640/25212166/7968048c-25bb-11e7-85a7-1d750eb5f304.png)

why can't get XCUIElementTypeOther's name of XCUIElementTypePickerWheel ? I am new to this
hope can help me  thank you very much

## Environment

* Desktop OS 1.6.4 for mac

**Comment by mykola-mokhnach** [comment]
We only show what XCTest returns to us. Please report the issue to Apple if you think there's a bug.
