### ISSUE TITLE
Appium desktop launching simulator but not showing XML

### ISSUE THREAD

**Issue by richashri87** [appium/appium#8287]
## The problem

When I am opening Appium desktop,mentioning the desired capability and starting the session.
It is only showing the mobile screen, not showing the window with xml ( that is required to get the xpath).

## Environment

* Appium version: 1.6.4
* Desktop OS/version used to run Appium: 10.11.6
* Node.js version: 7.7.4
* Mobile platform/version under test: 10.2
* Real device or emulator/simulator: Real Device, iPhone7
* Appium CLI or Appium.app|exe: I have installed Appium using the command as : npm install –g appium@1.6.4

## Link to Appium logs
<img width="620" alt="screen shot 2017-04-19 at 8 26 51 pm" src="https://cloud.githubusercontent.com/assets/13135890/25215835/66e6e2e0-25bd-11e7-82e7-1e3df9a79573.png">

**Comment by saikrishna321** [comment]
Please provide the server logs from desktop ?

**Comment by richashri87** [comment]
[AppiumLogs.docx](https://github.com/appium/appium/files/940794/AppiumLogs.docx)

**Comment by mykola-mokhnach** [comment]
1. Increase the value of **newCommandTimeout**
2. Use [Real Device setup tutorial](https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md) to configure Appium for real devices

**Comment by richashri87** [comment]
when I am running this command, I am get to know that package.json is not available

npm install --verbose
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/Cellar/node/7.7.4/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'install',
npm verb cli   '--verbose' ]
npm info using npm@4.5.0
npm info using node@v7.7.4
npm verb config Skipping project config: /Users/xxxx/.npmrc. (matches userconfig)
npm info lifecycle undefined~preinstall: undefined
npm verb correctMkdir /Users/xxxx/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /Users/xxxx/.npm/_locks/staging-1b5eecdce8d94329.lock for /Users/richa.b.shrivastava/node_modules/.staging
npm verb unlock done using /Users/xxxx/.npm/_locks/staging-1b5eecdce8d94329.lock for /Users/xxxx/node_modules/.staging
npm info linkStuff !invalid#1
npm verb linkBins !invalid#1
npm verb linkMans !invalid#1
npm info lifecycle undefined~install: undefined
npm info lifecycle undefined~postinstall: undefined
npm info lifecycle undefined~prepublish: undefined
npm info lifecycle undefined~prepare: undefined
npm WARN enoent ENOENT: no such file or directory, open '/Users/xxxx/package.json'
npm verb enoent This is most likely not a problem with npm itself
npm verb enoent and is related to npm not being able to find a file.
npm verb enoent 
npm WARN xxxx No description
npm WARN xxxx No repository field.
npm WARN xxxx No README data
npm WARN xxxx No license field.
npm verb exit [ 0, true ]
npm info ok

**Comment by richashri87** [comment]
@mykola-mokhnach I have already done setup for real device. Actually Appium setup is done and I am able to run sample test with my app. But I need some tool to inspect element that is why I installed appium desktop. So I just need to know how to do inspect element in Appium 1.6.4

**Comment by mykola-mokhnach** [comment]
Then simply provide the same capabilities to Appium Desktop, that you have set in your code.

**Comment by richashri87** [comment]
@mykola-mokhnach Appium Desktop is opening the device on macbook monitor but not giving the XML tags to determine the xpath.

**Comment by richashri87** [comment]
@saikrishna321 thanks a lot for helping.

I was not building the webDriverAgent project provided by Appium Desktop. So Just go till the Appium Desktop location installed on your machine and find the WebDriverAgent project under that and build that project in Xcode with developer certificate.
