### ISSUE TITLE
Why switch to WebView, then click does not take effect 

### ISSUE THREAD

**Issue by wanglexin** [appium/appium#8288]
driver.switch_to.context('WEBVIEW_com.tencent.mm:tools')
print(driver.contexts)
driver.implicitly_wait(10)
driver.find_element_by_xpath("//*[@id='combo']/li[1]").click()

Calling the click event in NATIVE_APP can take effect, when I switch to WEBVIEW to find the Xpath element, but the click event is not valid

**Comment by mykola-mokhnach** [comment]
Please fill out the issue reporting form and provide all the necessary logs first

**Comment by wanglexin** [comment]
> info: Welcome to Appium v1.4.16 (REV ae6877eff263066b26328d457bd285c0cc62430d)
> info: Appium REST http interface listener started on 127.0.0.1:4723
> info: [debug] Non-default server args: {"address":"127.0.0.1","logNoColors":true,"deviceName":"91QEBNT359LV","platformName":"Android","platformVersion":"22","automationName":"Appium"}
> info: Console LogLevel: debug
> info: --> POST /wd/hub/session {"capabilities":{"firstMatch":[],"alwaysMatch":{},"platformName":"Android","platformVersion":"5.1","deviceName":"91QEBNT359LV","appPackage":"com.tencent.mm","appActivity":".ui.LauncherUI","chromeOptions":{"androidProcess":"com.tencent.mm:tools"}},"desiredCapabilities":{"platformName":"Android","platformVersion":"5.1","deviceName":"91QEBNT359LV","appPackage":"com.tencent.mm","appActivity":".ui.LauncherUI","chromeOptions":{"androidProcess":"com.tencent.mm:tools"}}}
> info: Client User-Agent string: Python http auth
> info: [debug] The following desired capabilities were provided, but not recognized by appium. They will be passed on to any other services running on this server. : chromeOptions
> info: [debug] Didn't get app but did get Android package, will attempt to launch it on the device
> info: [debug] Creating new appium session 4dd43361-79b1-448c-8415-122b6d102fd4
> info: Starting android appium
> info: [debug] Getting Java version
> info: Java version is: 1.8.0_121
> info: [debug] Checking whether adb is present
> info: [debug] Using adb from D:\Program Files\android-sdk-windows\platform-tools\adb.exe
> warn: No app capability, can't parse package/activity
> info: [debug] Using fast reset? true
> info: [debug] Preparing device for session
> info: [debug] Not checking whether app is present since we are assuming it's already on the device
> info: Retrieving device
> info: [debug] Trying to find a connected android device
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: "D:\Program Files\android-sdk-windows\platform-tools\adb.exe" devices
> info: [debug] 1 device(s) connected
> info: Found device 91QEBNT359LV
> info: [debug] Setting device id to 91QEBNT359LV
> info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
> info: [debug] executing cmd: "D:\Program Files\android-sdk-windows\platform-tools\adb.exe" -s 91QEBNT359LV wait-for-device
> info: [debug] executing cmd: "D:\Program Files\android-sdk-windows\platform-tools\adb.exe" -s 91QEBNT359LV shell "echo 'ready'"
> info: [debug] Starting logcat capture
> info: [debug] Getting device API level
> info: [debug] executing cmd: "D:\Program Files\android-sdk-windows\platform-tools\adb.exe" -s 91QEBNT359LV shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 22
> info: Device API level is: 22
> info: [debug] Extracting strings for language: default
> info: [debug] Apk doesn't exist locally
> info: [debug] Could not get strings, but it looks like we had an old strings file anyway, so ignoring
> info: [debug] executing cmd: "D:\Program Files\android-sdk-windows\platform-tools\adb.exe" -s 91QEBNT359LV shell "rm -rf /data/local/tmp/strings.json"
> info: [debug] Not uninstalling app since server not started with --full-reset
> info: [debug] Skipping install since we launched with a package instead of an app path
> info: [debug] Forwarding system:4724 to device:4724
> info: [debug] executing cmd: "D:\Program Files\android-sdk-windows\platform-tools\adb.exe" -s 91QEBNT359LV forward tcp:4724 tcp:4724
> info: [debug] Pushing appium bootstrap to device...
> info: [debug] executing cmd: "D:\Program Files\android-sdk-windows\platform-tools\adb.exe" -s 91QEBNT359LV push "D:\\Program Files (x86)\\Appium\\node_modules\\appium\\build\\android_bootstrap\\AppiumBootstrap.jar" /data/local/tmp/
> info: [debug] Pushing settings apk to device...
> info: [debug] executing cmd: "D:\Program Files\android-sdk-windows\platform-tools\adb.exe" -s 91QEBNT359LV install "D:\Program Files (x86)\Appium\node_modules\appium\build\settings_apk\settings_apk-debug.apk"
> info: [debug] Pushing unlock helper app to device...
> info: [debug] executing cmd: "D:\Program Files\android-sdk-windows\platform-tools\adb.exe" -s 91QEBNT359LV install "D:\Program Files (x86)\Appium\node_modules\appium\build\unlock_apk\unlock_apk-debug.apk"
> info: Starting App
> info: [debug] Attempting to kill all 'uiautomator' processes
> info: [debug] Getting all processes with 'uiautomator'
> info: [debug] executing cmd: "D:\Program Files\android-sdk-windows\platform-tools\adb.exe" -s 91QEBNT359LV shell "ps 'uiautomator'"
> info: [debug] No matching processes found
> info: [debug] Running bootstrap
> info: [debug] spawning: D:\Program Files\android-sdk-windows\platform-tools\adb.exe -s 91QEBNT359LV shell uiautomator runtest AppiumBootstrap.jar -c io.appium.android.bootstrap.Bootstrap -e pkg com.tencent.mm -e disableAndroidWatchers false
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
> info: [debug] [UIAUTOMATOR STDOUT] io.appium.android.bootstrap.Bootstrap:
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 1
> info: [debug] [BOOTSTRAP] [debug] Socket opened on port 4724
> info: [debug] [BOOTSTRAP] [debug] Appium Socket Server Ready
> info: [debug] [BOOTSTRAP] [debug] Loading json...
> info: [debug] [BOOTSTRAP] [debug] Registered crash watchers.
> info: [debug] Waking up device if it's not alive
> info: [debug] Pushing command to appium work queue: ["wake",{}]
> info: [debug] [BOOTSTRAP] [debug] Client connected
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"wake","params":{}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: wake
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":true}
> info: [debug] executing cmd: "D:\Program Files\android-sdk-windows\platform-tools\adb.exe" -s 91QEBNT359LV shell "dumpsys window"
> info: [debug] Screen already unlocked, continuing.
> info: [debug] Pushing command to appium work queue: ["getDataDir",{}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"getDataDir","params":{}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: getDataDir
> info: [debug] dataDir set to: /data/local/tmp
> info: [debug] Pushing command to appium work queue: ["compressedLayoutHierarchy",{"compressLayout":false}]
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":"\/data\/local\/tmp"}
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"compressedLayoutHierarchy","params":{"compressLayout":false}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: compressedLayoutHierarchy
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":false}
> info: [debug] Getting device API level
> info: [debug] executing cmd: "D:\Program Files\android-sdk-windows\platform-tools\adb.exe" -s 91QEBNT359LV shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 22
> info: [debug] executing cmd: "D:\Program Files\android-sdk-windows\platform-tools\adb.exe" -s 91QEBNT359LV shell "am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n com.tencent.mm/.ui.LauncherUI"
> info: [debug] Waiting for pkg "com.tencent.mm" and activity ".ui.LauncherUI" to be focused
> info: [debug] Getting focused package and activity
> info: [debug] executing cmd: "D:\Program Files\android-sdk-windows\platform-tools\adb.exe" -s 91QEBNT359LV shell "dumpsys window windows"
> info: [debug] executing cmd: "D:\Program Files\android-sdk-windows\platform-tools\adb.exe" -s 91QEBNT359LV shell "getprop ro.build.version.release"
> info: [debug] Device is at release version 5.1
> info: [debug] Device launched! Ready for commands
> info: [debug] Setting command timeout to the default of 60 secs
> info: [debug] Appium session started with sessionId 4dd43361-79b1-448c-8415-122b6d102fd4
> info: <-- POST /wd/hub/session 303 4356.605 ms - 74 
> info: --> GET /wd/hub/session/4dd43361-79b1-448c-8415-122b6d102fd4 {}
> info: [debug] Responding to client with success: {"status":0,"value":{"platform":"LINUX","browserName":"Android","platformVersion":"5.1","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"platformName":"Android","platformVersion":"5.1","deviceName":"91QEBNT359LV","appPackage":"com.tencent.mm","appActivity":".ui.LauncherUI","chromeOptions":{"androidProcess":"com.tencent.mm:tools"}},"platformName":"Android","deviceName":"91QEBNT359LV","appPackage":"com.tencent.mm","appActivity":".ui.LauncherUI","chromeOptions":{"androidProcess":"com.tencent.mm:tools"}},"sessionId":"4dd43361-79b1-448c-8415-122b6d102fd4"}
> info: <-- GET /wd/hub/session/4dd43361-79b1-448c-8415-122b6d102fd4 200 3.412 ms - 695 {"status":0,"value":{"platform":"LINUX","browserName":"Android","platformVersion":"5.1","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"platformName":"Android","platformVersion":"5.1","deviceName":"91QEBNT359LV","appPackage":"com.tencent.mm","appActivity":".ui.LauncherUI","chromeOptions":{"androidProcess":"com.tencent.mm:tools"}},"platformName":"Android","deviceName":"91QEBNT359LV","appPackage":"com.tencent.mm","appActivity":".ui.LauncherUI","chromeOptions":{"androidProcess":"com.tencent.mm:tools"}},"sessionId":"4dd43361-79b1-448c-8415-122b6d102fd4"}
> info: --> POST /wd/hub/session/4dd43361-79b1-448c-8415-122b6d102fd4/element {"using":"name","value":"鎴?,"sessionId":"4dd43361-79b1-448c-8415-122b6d102fd4"}
> warn: [DEPRECATED] The name locator strategy has been deprecated and will be removed.  Please use the accessibility id locator strategy instead.
> info: [debug] Waiting up to 0ms for condition
> info: [debug] Pushing command to appium work queue: ["find",{"strategy":"name","selector":"鎴?,"context":"","multiple":false}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"name","selector":"鎴?,"context":"","multiple":false}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: find
> info: [debug] [BOOTSTRAP] [debug] Finding 鎴?using NAME with the contextId:  multiple: false
> info: [debug] [BOOTSTRAP] [debug] Using: UiSelector[DESCRIPTION=鎴? INSTANCE=0]
> info: [debug] [BOOTSTRAP] [debug] Using: UiSelector[TEXT=鎴? INSTANCE=0]
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":{"ELEMENT":"1"}}
> info: [debug] Responding to client with success: {"status":0,"value":{"ELEMENT":"1"},"sessionId":"4dd43361-79b1-448c-8415-122b6d102fd4"}
> info: <-- POST /wd/hub/session/4dd43361-79b1-448c-8415-122b6d102fd4/element 200 91.283 ms - 87 {"status":0,"value":{"ELEMENT":"1"},"sessionId":"4dd43361-79b1-448c-8415-122b6d102fd4"}
> info: --> POST /wd/hub/session/4dd43361-79b1-448c-8415-122b6d102fd4/element/1/click {"id":"1","sessionId":"4dd43361-79b1-448c-8415-122b6d102fd4"}
> info: [debug] Pushing command to appium work queue: ["element:click",{"elementId":"1"}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:click","params":{"elementId":"1"}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: click
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":true}
> info: [debug] Responding to client with success: {"status":0,"value":true,"sessionId":"4dd43361-79b1-448c-8415-122b6d102fd4"}
> info: <-- POST /wd/hub/session/4dd43361-79b1-448c-8415-122b6d102fd4/element/1/click 200 196.352 ms - 76 {"status":0,"value":true,"sessionId":"4dd43361-79b1-448c-8415-122b6d102fd4"}
> info: --> POST /wd/hub/session/4dd43361-79b1-448c-8415-122b6d102fd4/element {"using":"name","value":"鐩稿唽","sessionId":"4dd43361-79b1-448c-8415-122b6d102fd4"}
> info: [debug] Waiting up to 0ms for condition
> info: [debug] Pushing command to appium work queue: ["find",{"strategy":"name","selector":"鐩稿唽","context":"","multiple":false}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"name","selector":"鐩稿唽","context":"","multiple":false}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: find
> info: [debug] [BOOTSTRAP] [debug] Finding 鐩稿唽 using NAME with the contextId:  multiple: false
> info: [debug] [BOOTSTRAP] [debug] Using: UiSelector[DESCRIPTION=鐩稿唽, INSTANCE=0]
> info: [debug] [BOOTSTRAP] [debug] Using: UiSelector[TEXT=鐩稿唽, INSTANCE=0]
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":{"ELEMENT":"2"}}
> info: [debug] Responding to client with success: {"status":0,"value":{"ELEMENT":"2"},"sessionId":"4dd43361-79b1-448c-8415-122b6d102fd4"}
> info: <-- POST /wd/hub/session/4dd43361-79b1-448c-8415-122b6d102fd4/element 200 871.087 ms - 87 {"status":0,"value":{"ELEMENT":"2"},"sessionId":"4dd43361-79b1-448c-8415-122b6d102fd4"}
> info: --> POST /wd/hub/session/4dd43361-79b1-448c-8415-122b6d102fd4/element/2/click {"id":"2","sessionId":"4dd43361-79b1-448c-8415-122b6d102fd4"}
> info: [debug] Pushing command to appium work queue: ["element:click",{"elementId":"2"}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:click","params":{"elementId":"2"}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: click
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":true}
> info: [debug] Responding to client with success: {"status":0,"value":true,"sessionId":"4dd43361-79b1-448c-8415-122b6d102fd4"}
> info: <-- POST /wd/hub/session/4dd43361-79b1-448c-8415-122b6d102fd4/element/2/click 200 650.501 ms - 76 {"status":0,"value":true,"sessionId":"4dd43361-79b1-448c-8415-122b6d102fd4"}
> info: --> GET /wd/hub/session/4dd43361-79b1-448c-8415-122b6d102fd4/context {}
> info: [debug] Responding to client with success: {"status":0,"value":"NATIVE_APP","sessionId":"4dd43361-79b1-448c-8415-122b6d102fd4"}
> info: <-- GET /wd/hub/session/4dd43361-79b1-448c-8415-122b6d102fd4/context 200 2.657 ms - 84 {"status":0,"value":"NATIVE_APP","sessionId":"4dd43361-79b1-448c-8415-122b6d102fd4"}
> info: --> POST /wd/hub/session/4dd43361-79b1-448c-8415-122b6d102fd4/element {"using":"xpath","value":"//*[contains(@text,'51shaoxi')]","sessionId":"4dd43361-79b1-448c-8415-122b6d102fd4"}
> info: [debug] Waiting up to 0ms for condition
> info: [debug] Pushing command to appium work queue: ["find",{"strategy":"xpath","selector":"//*[contains(@text,'51shaoxi')]","context":"","multiple":false}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"//*[contains(@text,'51shaoxi')]","context":"","multiple":false}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: find
> info: [debug] [BOOTSTRAP] [debug] Finding //*[contains(@text,'51shaoxi')] using XPATH with the contextId:  multiple: false
> info: [debug] [BOOTSTRAP] [debug] Using: UiSelector[CLASS=android.widget.TextView, INSTANCE=6]
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":{"ELEMENT":"3"}}
> info: [debug] Responding to client with success: {"status":0,"value":{"ELEMENT":"3"},"sessionId":"4dd43361-79b1-448c-8415-122b6d102fd4"}
> info: <-- POST /wd/hub/session/4dd43361-79b1-448c-8415-122b6d102fd4/element 200 655.428 ms - 87 {"status":0,"value":{"ELEMENT":"3"},"sessionId":"4dd43361-79b1-448c-8415-122b6d102fd4"}
> info: --> POST /wd/hub/session/4dd43361-79b1-448c-8415-122b6d102fd4/element/3/click {"id":"3","sessionId":"4dd43361-79b1-448c-8415-122b6d102fd4"}
> info: [debug] Pushing command to appium work queue: ["element:click",{"elementId":"3"}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:click","params":{"elementId":"3"}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: click
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":true}
> info: [debug] Responding to client with success: {"status":0,"value":true,"sessionId":"4dd43361-79b1-448c-8415-122b6d102fd4"}
> info: <-- POST /wd/hub/session/4dd43361-79b1-448c-8415-122b6d102fd4/element/3/click 200 623.141 ms - 76 {"status":0,"value":true,"sessionId":"4dd43361-79b1-448c-8415-122b6d102fd4"}
> info: --> POST /wd/hub/session/4dd43361-79b1-448c-8415-122b6d102fd4/element {"using":"xpath","value":"//*[contains(@text,'898602')]","sessionId":"4dd43361-79b1-448c-8415-122b6d102fd4"}
> info: [debug] Waiting up to 0ms for condition
> info: [debug] Pushing command to appium work queue: ["find",{"strategy":"xpath","selector":"//*[contains(@text,'898602')]","context":"","multiple":false}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"//*[contains(@text,'898602')]","context":"","multiple":false}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: find
> info: [debug] [BOOTSTRAP] [debug] Finding //*[contains(@text,'898602')] using XPATH with the contextId:  multiple: false
> info: [debug] [BOOTSTRAP] [debug] Using: UiSelector[CLASS=android.widget.TextView, INSTANCE=1]
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":{"ELEMENT":"4"}}
> info: [debug] Responding to client with success: {"status":0,"value":{"ELEMENT":"4"},"sessionId":"4dd43361-79b1-448c-8415-122b6d102fd4"}
> info: <-- POST /wd/hub/session/4dd43361-79b1-448c-8415-122b6d102fd4/element 200 97.124 ms - 87 {"status":0,"value":{"ELEMENT":"4"},"sessionId":"4dd43361-79b1-448c-8415-122b6d102fd4"}
> info: --> POST /wd/hub/session/4dd43361-79b1-448c-8415-122b6d102fd4/element/4/click {"id":"4","sessionId":"4dd43361-79b1-448c-8415-122b6d102fd4"}
> info: [debug] Pushing command to appium work queue: ["element:click",{"elementId":"4"}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:click","params":{"elementId":"4"}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: click
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":true}
> info: [debug] Responding to client with success: {"status":0,"value":true,"sessionId":"4dd43361-79b1-448c-8415-122b6d102fd4"}
> info: <-- POST /wd/hub/session/4dd43361-79b1-448c-8415-122b6d102fd4/element/4/click 200 1473.027 ms - 76 {"status":0,"value":true,"sessionId":"4dd43361-79b1-448c-8415-122b6d102fd4"}
> info: --> POST /wd/hub/session/4dd43361-79b1-448c-8415-122b6d102fd4/context {"name":"WEBVIEW_com.tencent.mm:tools","sessionId":"4dd43361-79b1-448c-8415-122b6d102fd4"}
> info: [debug] Getting a list of available webviews
> info: [debug] executing cmd: "D:\Program Files\android-sdk-windows\platform-tools\adb.exe" -s 91QEBNT359LV shell "cat /proc/net/unix"
> info: [debug] WEBVIEW_16875 mapped to pid 16875
> info: [debug] Getting process name for webview
> info: [debug] executing cmd: "D:\Program Files\android-sdk-windows\platform-tools\adb.exe" -s 91QEBNT359LV shell "ps"
> info: [debug] WEBVIEW_17036 mapped to pid 17036
> info: [debug] Getting process name for webview
> info: [debug] executing cmd: "D:\Program Files\android-sdk-windows\platform-tools\adb.exe" -s 91QEBNT359LV shell "ps"
> info: [debug] Parsed pid: 16875 pkg: com.tencent.mm:appbrand0
> info: [debug] from: u0_a506,16875,395,2104404,85512,ffffffff,00000000,S,com.tencent.mm:appbrand0
> info: [debug] returning process name: com.tencent.mm:appbrand0
> info: [debug] Parsed pid: 17036 pkg: com.tencent.mm:tools
> info: [debug] from: u0_a506,17036,395,2359660,187148,ffffffff,00000000,S,com.tencent.mm:tools
> info: [debug] returning process name: com.tencent.mm:tools
> info: [debug] Available contexts: 
> info: [debug] ["WEBVIEW_com.tencent.mm:appbrand0","WEBVIEW_com.tencent.mm:tools"]
> info: [debug] Available contexts: NATIVE_APP,WEBVIEW_com.tencent.mm:appbrand0,WEBVIEW_com.tencent.mm:tools
> info: [debug] Connecting to chrome-backed webview
> info: Chromedriver: Changed state to 'starting'
> info: Chromedriver: Set chromedriver binary as: D:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\chromedriver\win\chromedriver.exe
> info: Chromedriver: Killing any old chromedrivers, running: FOR /F "usebackq tokens=5" %a in (`netstat -nao ^| findstr /R /C:"9515 "`) do (FOR /F "usebackq" %b in (`TASKLIST /FI "PID eq %a" ^| findstr /I chromedriver.exe`) do (IF NOT %b=="" TASKKILL /F /PID %a))
> info: Chromedriver: No old chromedrivers seemed to exist
> info: Chromedriver: Spawning chromedriver with: D:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\chromedriver\win\chromedriver.exe --url-base=wd/hub --port=9515
> info: Chromedriver: [STDOUT] Starting ChromeDriver 2.18.343845 (73dd713ba7fbfb73cbb514e62641d8c96a94682a) on port 9515
> Only local connections are allowed.
> info: JSONWP Proxy: Proxying [GET /status] to [GET http://127.0.0.1:9515/wd/hub/status] with no body
> info: JSONWP Proxy: Got response with status 200: "{\"sessionId\":\"\",\"status\":0,\"value\":{\"build\":{\"version\":\"alpha\"},\"os\":{\"arch\":\"x86_64\",\"name\":\"Windows NT\",\"version\":\"10.0\"}}}"
> info: JSONWP Proxy: Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.tencent.mm","androidUseRunningApp":true,"androidProcess":"com.tencent.mm:tools","androidDeviceSerial":"91QEBNT359LV"}}}
> info: JSONWP Proxy: Got response with status 200: {"sessionId":"48ebed21638a7eeec08d65670b45a561","status":13,"value":{"message":"unknown error: Device 91QEBNT359LV is not online\n  (Driver info: chromedriver=2.18.343845 (73dd713ba7fbfb73cbb514e62...
> info: JSONWP Proxy: Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.tencent.mm","androidUseRunningApp":true,"androidProcess":"com.tencent.mm:tools","androidDeviceSerial":"91QEBNT359LV"}}}
> info: JSONWP Proxy: Got response with status 200: {"sessionId":"8e07b2d68da1171542ec29398cf12909","status":0,"value":{"acceptSslCerts":true,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"browserName":"chrome","chrome":{},"cssSel...
> info: Chromedriver: Changed state to 'online'
> info: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"4dd43361-79b1-448c-8415-122b6d102fd4"}
> info: <-- POST /wd/hub/session/4dd43361-79b1-448c-8415-122b6d102fd4/context 200 2617.523 ms - 76 {"status":0,"value":null,"sessionId":"4dd43361-79b1-448c-8415-122b6d102fd4"}
> info: --> GET /wd/hub/session/4dd43361-79b1-448c-8415-122b6d102fd4/contexts {}
> info: [debug] Getting a list of available webviews
> info: [debug] executing cmd: "D:\Program Files\android-sdk-windows\platform-tools\adb.exe" -s 91QEBNT359LV shell "cat /proc/net/unix"
> info: [debug] WEBVIEW_16875 mapped to pid 16875
> info: [debug] Getting process name for webview
> info: [debug] executing cmd: "D:\Program Files\android-sdk-windows\platform-tools\adb.exe" -s 91QEBNT359LV shell "ps"
> info: [debug] WEBVIEW_17036 mapped to pid 17036
> info: [debug] Getting process name for webview
> info: [debug] executing cmd: "D:\Program Files\android-sdk-windows\platform-tools\adb.exe" -s 91QEBNT359LV shell "ps"
> info: [debug] Parsed pid: 17036 pkg: com.tencent.mm:tools
> info: [debug] from: u0_a506,17036,395,2360924,187292,ffffffff,00000000,S,com.tencent.mm:tools
> info: [debug] returning process name: com.tencent.mm:tools
> info: [debug] Parsed pid: 16875 pkg: com.tencent.mm:appbrand0
> info: [debug] from: u0_a506,16875,395,2104404,85512,ffffffff,00000000,S,com.tencent.mm:appbrand0
> info: [debug] returning process name: com.tencent.mm:appbrand0
> info: [debug] Available contexts: NATIVE_APP,WEBVIEW_com.tencent.mm:appbrand0,WEBVIEW_com.tencent.mm:tools
> info: [debug] ["WEBVIEW_com.tencent.mm:tools","WEBVIEW_com.tencent.mm:appbrand0"]
> info: [debug] Available contexts: NATIVE_APP,WEBVIEW_com.tencent.mm:tools,WEBVIEW_com.tencent.mm:appbrand0
> info: [debug] Responding to client with success: {"status":0,"value":["NATIVE_APP","WEBVIEW_com.tencent.mm:tools","WEBVIEW_com.tencent.mm:appbrand0"],"sessionId":"4dd43361-79b1-448c-8415-122b6d102fd4"}
> info: <-- GET /wd/hub/session/4dd43361-79b1-448c-8415-122b6d102fd4/contexts 200 221.131 ms - 152 {"status":0,"value":["NATIVE_APP","WEBVIEW_com.tencent.mm:tools","WEBVIEW_com.tencent.mm:appbrand0"],"sessionId":"4dd43361-79b1-448c-8415-122b6d102fd4"}
> info: --> GET /wd/hub/session/4dd43361-79b1-448c-8415-122b6d102fd4/source {}
> info: JSONWP Proxy: Proxying [GET /wd/hub/session/4dd43361-79b1-448c-8415-122b6d102fd4/source] to [GET http://127.0.0.1:9515/wd/hub/session/8e07b2d68da1171542ec29398cf12909/source] with body: {}
> info: JSONWP Proxy: Got response with status 200: {"sessionId":"8e07b2d68da1171542ec29398cf12909","status":0,"value":"<!DOCTYPE html><html xmlns=\"http://www.w3.org/1999/xhtml\"><head>\n  <meta charset=\"UTF-8\" />\n  <meta name=\"viewport\" conte...
> info: JSONWP Proxy: Replacing sessionId 8e07b2d68da1171542ec29398cf12909 with 4dd43361-79b1-448c-8415-122b6d102fd4
> info: <-- GET /wd/hub/session/4dd43361-79b1-448c-8415-122b6d102fd4/source 200 63.374 ms - 34150 
> info: --> POST /wd/hub/session/4dd43361-79b1-448c-8415-122b6d102fd4/timeouts/implicit_wait {"ms":10000,"sessionId":"4dd43361-79b1-448c-8415-122b6d102fd4"}
> info: JSONWP Proxy: Proxying [POST /wd/hub/session/4dd43361-79b1-448c-8415-122b6d102fd4/timeouts/implicit_wait] to [POST http://127.0.0.1:9515/wd/hub/session/8e07b2d68da1171542ec29398cf12909/timeouts/implicit_wait] with body: {"ms":10000,"sessionId":"4dd43361-79b1-448c-8415-122b6d102fd4"}
> info: JSONWP Proxy: Got response with status 200: {"sessionId":"8e07b2d68da1171542ec29398cf12909","status":0,"value":null}
> info: JSONWP Proxy: Replacing sessionId 8e07b2d68da1171542ec29398cf12909 with 4dd43361-79b1-448c-8415-122b6d102fd4
> info: <-- POST /wd/hub/session/4dd43361-79b1-448c-8415-122b6d102fd4/timeouts/implicit_wait 200 2.784 ms - 76 
> info: --> POST /wd/hub/session/4dd43361-79b1-448c-8415-122b6d102fd4/element {"using":"xpath","value":"//*[@id='combo']/li[1]","sessionId":"4dd43361-79b1-448c-8415-122b6d102fd4"}
> info: JSONWP Proxy: Proxying [POST /wd/hub/session/4dd43361-79b1-448c-8415-122b6d102fd4/element] to [POST http://127.0.0.1:9515/wd/hub/session/8e07b2d68da1171542ec29398cf12909/element] with body: {"using":"xpath","value":"//*[@id='combo']/li[1]","sessionId":"4dd43361-79b1-448c-8415-122b6d102fd4"}
> info: JSONWP Proxy: Got response with status 200: {"sessionId":"8e07b2d68da1171542ec29398cf12909","status":0,"value":{"ELEMENT":"0.8623908391391202-1"}}
> info: JSONWP Proxy: Replacing sessionId 8e07b2d68da1171542ec29398cf12909 with 4dd43361-79b1-448c-8415-122b6d102fd4
> info: <-- POST /wd/hub/session/4dd43361-79b1-448c-8415-122b6d102fd4/element 200 87.285 ms - 106 
> info: --> POST /wd/hub/session/4dd43361-79b1-448c-8415-122b6d102fd4/element/0.8623908391391202-1/click {"id":"0.8623908391391202-1","sessionId":"4dd43361-79b1-448c-8415-122b6d102fd4"}
> info: JSONWP Proxy: Proxying [POST /wd/hub/session/4dd43361-79b1-448c-8415-122b6d102fd4/element/0.8623908391391202-1/click] to [POST http://127.0.0.1:9515/wd/hub/session/8e07b2d68da1171542ec29398cf12909/element/0.8623908391391202-1/click] with body: {"id":"0.8623908391391202-1","sessionId":"4dd43361-79b1-448c-8415-122b6d102fd4"}
> info: JSONWP Proxy: Got response with status 200: {"sessionId":"8e07b2d68da1171542ec29398cf12909","status":0,"value":null}
> info: JSONWP Proxy: Replacing sessionId 8e07b2d68da1171542ec29398cf12909 with 4dd43361-79b1-448c-8415-122b6d102fd4
> info: <-- POST /wd/hub/session/4dd43361-79b1-448c-8415-122b6d102fd4/element/0.8623908391391202-1/click 200 189.588 ms - 76 
> Killed Node Server.
> Appium server process ended

**Comment by mykola-mokhnach** [comment]
Appium 1.4.16 is very old and is not supported anymore. Please try Appium 1.6.4-stable

**Comment by wanglexin** [comment]
thank you very much,I'll try to upgrade the appium version
