### ISSUE TITLE
[UiAutomator2] Unable to set Network connection to WIFI

### ISSUE THREAD

**Issue by mayureshshirodkar** [appium/appium#8289]
## The problem

I am unable to set network connection for Android on uiautomator2.
Tried this on Android Nougat and Android 6.0.

Also with uiautomator1 setting WIFI connection to off is not possible hence used uiautomator2

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5 beta
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: OS10.12.4
* Mobile platform/version under test: 7.0 and 6.0.1
* Real device or emulator/simulator: Moto G4 and HTC E8
* Appium CLI or Appium.app|exe: CLI

## Details

Referred to https://github.com/appium/appium/issues/6615 which mentioned that the issue is fixed for uiautomator2.
Error:
org.apache.commons.lang.NotImplementedException: Setting Network Connection to: NONE :is not implemented

## Link to Appium logs

https://gist.github.com/aad3c4af8e6adc13b601aada9eba7686.git

## Code To Reproduce Issue [ Good To Have ]

((AndroidDriver) Setup.getInstance().getWebDriver()).setConnection(Connection.NONE);

**Comment by vjmaiky** [comment]
https://github.com/appium/appium/issues/8267#event-1046945532

**Comment by vjmaiky** [comment]
get laterst version and try again

**Comment by mayureshshirodkar** [comment]
Thanks let me check this.

**Comment by mykola-mokhnach** [comment]
Closed as duplicate
