### ISSUE TITLE
[MJSONWP] Encountered internal error running command: Error: Error while executing atom: Remote debugger is not connected

### ISSUE THREAD

**Issue by skumar1122** [appium/appium#8291]
## The problem

Unable to run multiple iOS Automation tests on same device.
(happening once in 5 times for same tests)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5-beta
* Node.js version (unless using Appium.app|exe): v7.8.0
* Mobile platform/version under test: 10.3.1
* Real device or emulator/simulator: iPhone6
* Xcode: 8.3.2
* Mac: 10.12.4 

## Details
I have updated libimobiledevice with --HEAD and IWDP 
And I have successfully build the WDA , it was success and I ran test on iPhone6 device first time with no issues but if i run multiple tests it complaints about "Debugger is not connected each time" , please check appium logs below.

Please suggest me if I am missing something ?

## Link to Appium logs

Appium Logs : https://gist.github.com/skumar1122/dd4d167fe7acf064993f2526dd1fb8fe
My console logs:https://gist.github.com/skumar1122/69378f9a1c21a6b2e224eecb50d8b3b1

**Comment by mykola-mokhnach** [comment]
Might be related to https://github.com/appium/appium/issues/8083

It would be more stable to run tests on Simulator instead
