### ISSUE TITLE
[iOS] Unable to switch to a second webview

### ISSUE THREAD

**Issue by netd-eric** [appium/appium#8292]
## The problem

In my testing app there are two webviews webviewA and webviewB. When launching the app it's only webviewA is presented, after few actions webviewB is presented and webviewA is deactivated.
I am trying to switch context to webviewB it works but cannot get the elements inside of that.
I tried same case in Android it works seamlessly. 

## Environment

* Appium 1.6.4
* macOS Sierra 10.12.4
* Node.js v7.7.4
* iOS 10.2.1
* iPhone
* Appium CLI

## Details

I use following python code to switch to webviewB

```python
self.driver.switch_to.context('WEBVIEW_1')
# now is switched to webview A
self.do_some_actions()
# after some actions when the screen is showing webview B
self.driver.switch_to.context('NATIVE_APP')
self.driver.switch_to.context('WEBVIEW_1')
# now is switched to webview B
self.driver.find_element_by_id('htmlid')
# throw error...
```

## Link to Appium logs
https://gist.github.com/netd-eric/daf1d9a624a35238810eb124d91615d5

**Comment by imurchie** [comment]
Webkit does not seem to be finding the second webview.

But in the meantime, the timeout error can be fixed by getting the latest Appium (`npm uninstall -g appium && npm install -g appium@beta`) and trying to use the `webkitResponseTimeout` capability, set to some number of milliseconds (default is 5000), which is the time to wait for Webkit to return results.

**Comment by netd-eric** [comment]
unfortunately it didn't work. I guess the problem is Appium was targeting the first webview when the app had get into the second webview. Anyway can make Appium to re-detect the new second webview?

**Comment by netd-eric** [comment]
Eventually I found that will work just set the app running in background before switching to the second webview

```python 
self.driver.background_app(10)
# now it gets two webviews: ['NATIVE_APP', 'WEBVIEW_1', 'WEBVIEW_2']
self.driver.switch_to.context(self.driver.contexts[-1])
```
not sure that's problem caused by web driver agent or appium
