### ISSUE TITLE
Android : complete content-desc of a WebView element is not displayed/returned

### ISSUE THREAD

**Issue by poorvikamahesh** [appium/appium#8293]
Hello,

When I try to return the content-desc attribute if a WebView element in an Android device, the complete display is not returned.
Even when we inspect the element using Appium-desktop, only the partial display text is visible as content-desc or accessibility id.

Appium version - 1.6.4
Android Version - 6.0.1

Please refer the screen shot below.
<img width="1431" alt="screen shot 2017-04-20 at 3 57 03 pm" src="https://cloud.githubusercontent.com/assets/10269471/25226501/d632bd2a-25e2-11e7-8c3c-309f0f92a247.png">

**Comment by poorvikamahesh** [comment]
The xml returned for that element is as below -
`<android.view.View index="2" text="" class="android.view.View" package="com.philips.sleepmapper.root" **content-desc="This video provides an overview of PAP therapy fo"** checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[298,2150][700,1184]" resource-id="Description 5" instance="42"/>
</android.view.View>`

**Comment by dpgraham** [comment]
Sorry for the late reply on this.

If this is what's reported by the source XML, then I don't think it's an Appium problem.

Where you able to locate elements using that content-desc? It looks to me like UIAutomator clips overly long content descriptions down to 50 characters.

If this is still an issue, I'll re-open.
