### ISSUE TITLE
Android Hybrid Apps - ISSUE - Appium returns different attributes of the same element on 2 devices (devices with same manufacturer and same Android version) 

### ISSUE THREAD

**Issue by poorvikamahesh** [appium/appium#8294]
Hello,

HAD RAISED THIS ISSUE PREVIOUSLY, BUT IT WAS TAGGED AS QUESTION AND GOT NO SOLUTION/REPLY ON THIS

THIS IS NOT A QUESTION

THIS IS A GENUINE ISSUE WE ARE FACING AND ARE BLOCKED BECAUSE OF THIS.

We have a hybrid application which we are trying to automate. Initially we had a Nexus 5 Android 6.0.1 device and completed writing our scripts and running on the same device.

We recently changed our device to another Nexus 5 (Android 6.0.1) but all our scripts failed. When we inspected, we noticed that the attributes of many elements are different.

For example, as we see in the screenshot, the resource ID is missing for the Forgot Password button in the new device

This is the case with other devices as well. Sometimes the element xpath changes from one device to another, though the Android Version, Appium Version, Application / web content version is the same.

Kindly help

![one](https://cloud.githubusercontent.com/assets/10269471/25226826/eb0f9cbc-25e3-11e7-97f8-623f3c60d189.png)
<img width="1440" alt="two" src="https://cloud.githubusercontent.com/assets/10269471/25226827/eb1109c6-25e3-11e7-8e40-663a7fe01049.png">

**Comment by HemantTrivedi** [comment]
@poorvikamahesh 
Did you try with creating custom xpath with content description attribute

**Comment by poorvikamahesh** [comment]
@HemantTrivedi, our application supports 5 languages and the cont-desc changes for every language.
That is not a feasible solution for us

**Comment by HemantTrivedi** [comment]
@poorvikamahesh . But you can try with index attribute right . That would be same in all cases

**Comment by poorvikamahesh** [comment]
@HemantTrivedi 
Thanks for the suggestion but we cannot use index everywhere
Also, the index is not constant either.
The above is a simple example but few other pages, the xpath changes i.e. the tree structure of the element changes. That is why we are not able to use xpath either. And based on the location of the element in the tree structure, the index changes

**Comment by dpgraham** [comment]
This isn't something that Appium has control over. The source XML is reported by Android UI Automator. Any discrepancies between the two are due to differences in how UI Automator reports the source.

**Comment by vikramvi** [comment]
@poorvikamahesh you can try with relative xpath using **package** attribute, as I see it is shown in both devices. It has to work http://stackoverflow.com/questions/27183353/what-is-the-difference-between-absolute-and-relative-xpaths-which-is-preferred

To keep it simple try **arc** approach on different devices, which will save time

**Comment by poorvikamahesh** [comment]
@vikramvi There are n-number of elements with the same "package" attribute.

The xpath changes i.e. the tree structure of the element changes. That is why we are not able to use xpath either. And based on the location of the element in the tree structure, the index changes

**Comment by mgochoa** [comment]
Nothing else on this? I Have the same troubles

**Comment by dpgraham** [comment]
I'm closing this as a non Appium issue. If the XML is different on different devices, this is due to UIAutomator (https://google.github.io/android-testing-support-library/docs/uiautomator/) reporting different XML.

If you have inconsistencies with locators, you'll need to talk to your developers to have them set a resource-id on the elements you're trying to locate.
