### ISSUE TITLE
Unable to launch tests on iOS 10.3.1: Got "Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65"

### ISSUE THREAD

**Issue by xshuRoadie** [appium/appium#8297]
## The problem
On Appium 1.6.4 / 10.3.1 / XCode 8.3.2 I keep getting "Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65" error.  From the log what I can tell is we are having a hard time building WebDriverAgentRunner-Runner.app 

I have pointed capability "xcodeConfigFile" to my xcodeconfig which has the team id and code sign id. They work well with Appium 1.6.1. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Last Appium version that did not exhibit the issue (if applicable): 1.6.1
* Desktop OS/version used to run Appium: macOS Sierra Version 10.12.4(16E195)
* Node.js version (unless using Appium.app|exe): 3.10.8
* Mobile platform/version under test: iOS 10.3.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Link to Appium logs
https://gist.github.com/xshuRoadie/15ba9ef4ebfedaa748356f6bd3472ffa

**Comment by imurchie** [comment]
Can you run with Xcode logging on (set 'showXcodeLog' capability to 'true')
and repost the logs? That should show the reason for the failure.

**Comment by xshuRoadie** [comment]
@imurchie Just updated the gist with that capability On. https://gist.github.com/xshuRoadie/15ba9ef4ebfedaa748356f6bd3472ffa

**Comment by xshuRoadie** [comment]
Update: It works! Just open WebDriverAgent proj from 1.6.4 in XCode and re-sign target WebDriverAgentRunner.
