### ISSUE TITLE
Unable to set_value or click on one View

### ISSUE THREAD

**Issue by mwalla210** [appium/appium#8299]
## The problem

Inspector for Appium GUI incorrectly highlights Google Sign On process in React Native application, tap unresponsive, and Appium-Python-Client is unable to `set_value()` for parts of process.

## Environment

* Desktop OS/version used to run Appium: Mac 10.12.4
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Nexus 5X running 6.0.0
* Application type: React Native app
* Appium CLI or Appium.app|exe: Appium (1.0.0) & Appium-Python-Client (0.24)

## Details

Unable to send text to EditText box in Android or execute a click on a button (same page). These boxes are part of the Google Sign In process (two pages: one for email & next button, one for password & sign in button). **This issue is not experienced on iOS for the same process.**

Possibly related - GUI highlighting in Inspector is incorrect/missing for Password EditText, Sign In button, and Forgot Password View (on _just_ this page). The Inspector is unsuccessful on tap for "Sign in" button & "Forgot my password" view.

![screen shot 2017-04-20 at 11 49 35 am](https://cloud.githubusercontent.com/assets/18332047/25239949/94b521c6-25bf-11e7-9544-9719f8958257.png)
![screen shot 2017-04-20 at 11 49 44 am](https://cloud.githubusercontent.com/assets/18332047/25239950/94b62d14-25bf-11e7-836a-e3cc7bc71494.png)

Using Python/Appium-Python-Client, script is able to (see below for code)
* Script an entry into the Email EditText (prior screen)
* Click the "Next" button (prior screen)

```
# Enter email
email = self.driver.find_element_by_accessibility_id("Email or phone")
self.assertEqual(email.get_attribute("name").strip(), "Email or phone")
self.driver.set_value(email, emailstr)
button = self.driver.find_element_by_xpath("//android.view.View[4]/android.widget.Button[1]")
self.assertEqual(button.get_attribute("name").strip(), "Next")
button.click()
self.driver.implicitly_wait(60)
```

It _fails_ on:
* Script an entry into the Password EditText (no text entered into field and nothing printed)
  * It is _finding_ the EditText (see verification in code)
* Click the "Sign in" button
  * It is _finding_ the button (see verification in code) but `click()` execution does nothing

```
# Enter password
pw = driver.find_element_by_xpath("//*[1]//*[1]//*[1]//*[1]//*[1]//*[1]//*[1]//*[2]//*[1]//*[1]//*[4]//*[3]")
print("Find password box succeeded")
pw.set_text(d["tassl_test_password"])
#driver.set_value(pw, d["tassl_test_password"])
print("Password: " + pw.get_attribute("text"))
```
My logs will show the following after execution:
```
Find password box succeeded
Password: 
```
Click "Sign in"
```
button = self.driver.find_element_by_accessibility_id("Sign in")
button.click()
```

## Link to Appium logs

Sample of trying to enter password (hidden) & click "Sign in" in Appium.app Inspector
https://gist.github.com/mwalla210/f38f943c5be65981780ebd94d71eb75c

**Comment by bennid** [comment]
I believe I have seen something similar with appium 1.6.4 and a WebView on Android5.0 (nexus 6p emulator).  I see that we find the EditText field, but when we try to click in it, the area around the field is highlighted, instead of the text being entered into it.  Will try to repro with appium 1.6.3

**Comment by mwalla210** [comment]
Still experiencing this issue, and it's causing a real problem - I can't automate through the log in process for the application. 
```
# Enter password
        time.sleep(5)
        websource = str(driver.page_source.encode('ascii', 'ignore'))
        print(websource)
        elements = driver.find_elements_by_class_name("android.widget.EditText")
        elements[1].click()
        elements[1].set_text(d["tassl_test_password"])

        # Click Sign In
        elements = driver.find_elements_by_class_name("android.widget.Button")
        print(len(elements))
        driver.find_element_by_accessibility_id("Sign in").click()
```
The above code "succeeds" in that it throws no errors, but the password field is never highlighted, no text is entered, and the button is not clicked (assuming I would see an error message due to hitting sign in without entering password). The app just stops at this screen, while continuing on with the script. 
I am now on Appium Desktop 1.0.2-beta.2, Appium CLI 1.6.4, with a genymotion simulator as above.

@mykola-mokhnach you added a label to this more than a month ago, with no response or further action.
@bennid did you have any success with testing this issue?

**Comment by dpgraham** [comment]
Sorry for not replying.

Are you still experiencing this issue? I'm guessing this is a WebView. Have you tried checking the contexts and seeing if you can set context to webview?

**Comment by mwalla210** [comment]
No such context is available error when attempting to switch contexts at that stage. 
I believe Google actually restricted the use of Webviews for Android for security purposes. As mentioned, the Google process is two step:
- Page 1: email/phone and next button (automation succeeds here)
- Page 2: password and next button (automation fails here)

**Comment by dpgraham** [comment]
Can you try printing out a list of the `contexts` and paste it here?

**Comment by mwalla210** [comment]
Normally when I can switch to a webview, I see the following printed for contexts:
`[u'NATIVE_APP', u'WEBVIEW_com.android.browser', u'WEBVIEW_com.tassl.android']`
However, at this time, when I print contexts, the only ones are:
`[u'NATIVE_APP', u'WEBVIEW_com.android.browser']`

**Comment by jlipps** [comment]
@mwalla210 the only supported way to work with WebView contents is via the context API, which uses Chromedriver to establish full control over the webview. Appium Desktop is not a tool designed to be used for webviews (instead just use Chrome's inspector and attach to the webview). If the webview can't be found, that's another problem. Can it be found by Chrome's inspector completely outside of Appium?

**Comment by mwalla210** [comment]
@jlipps As mentioned above, I do not believe this _is_ a Webview - Google has restricted Webview usage for Android and we had to convert off of a Webview. Thus it makes sense that a Webview context is unavailable.
_However_ my main issue is that I am able to automate half of this process using Appium - I can do page 1 (email) of a two page process, but not page 2 (password/sign in button).

**Comment by jlipps** [comment]
@mwalla210 you have this in your test code:

```
        elements = driver.find_elements_by_class_name("android.widget.EditText")
        elements[1].click()
```

Are you sure that that is the password box? Why pick the 1th element rather than the 0th? Is there a unique way of finding that element? My wondering is whether you're actually finding some other text field. Or maybe a race condition while the new view is sliding in.

**Comment by mykola-mokhnach** [comment]
Closed as inactive
