### ISSUE TITLE
[Android] Appium Inspector Screenshot is Blank with No Elements Displayed 

### ISSUE THREAD

**Issue by mojojojo94** [appium/appium#8301]
## The problem

When appium inspector launches, the refresh wheel keeps loading and preview image is blank.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.5.3
* Last Appium version that did not exhibit the issue (if applicable): n/a
* Desktop OS/version used to run Appium: Mac OS Sierra
* Node.js version (unless using Appium.app|exe): Appium.app
* Mobile platform/version under test: Android, API Level 22 and 19
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: Appium.app

## Details

I set the appium gui app to launch the android virtual device whenever I click the 'launch' button then the 'appium inspector' button.

My avd launches fine and then my app launches on the avd.
Then the appium inspector launches, but the preview image is blank and there are no elements, also the refresh button has a loading wheel that keeps loading for 5-10 minutes.

## Link to Appium logs

Didn't find anything weird or error like in the logs, I can post them if asked.

## Code To Reproduce Issue [ Good To Have ]

these are the capabilities I have set:

capabilities.setCapability("appPackage", "com.appname.mobile.android");
capabilities.setCapability("appActivity", "com.appname.mobile.android.ui.RootActivity");
capabilities.setCapability(MobileCapabilityType.APP, "<my app path>");
capabilities.setCapability("deviceName", "AndroidTestDevice");
capabilities.setCapability("avd", "AndroidTestDevice");
driver = new AndroidDriver<WebElement>(new URL("http://127.0.0.1:4724/wd/hub"), capabilities);

Am I missing some capabilities or something?

**Comment by mykola-mokhnach** [comment]
This inspector is not supported anymore. Use https://github.com/appium/appium-desktop/releases instead
