### ISSUE TITLE
Doesn't launch the app.

### ISSUE THREAD

**Issue by nanshet** [appium/appium#8303]
Hi,

I tried executing same test case which successfully executed in previous v. of appium 1.5.3 dmg but it failed in new appium desktop v.1.6.4 dmg. Doesn't launch the app.
Here are the logs:

[XCUITest] Using WDA agent: '/Applications/Appium2.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[XCUITest] Carthage not found. Install using `brew install carthage`
[XCUITest] Running WebDriverAgent bootstrap script to install dependencies
[XCUITest] Fetching dependencies
[XCUITest] Please make sure that you have Carthage installed (https://github.com/Carthage/Carthage)
[XCUITest] Note: We are expecting that carthage installed in /usr/local/bin/
[BaseDriver] Event 'wdaStartFailed' logged at 1492759550924 (12:55:50 GMT+0530 (IST))
[XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: Command 'Scripts/bootstrap.sh -d' exited with code 1

If you can help to resolve this issue .

**Comment by mykola-mokhnach** [comment]
> [XCUITest] Carthage not found. Install using brew install carthage

I suppose the log tries to help you in a pretty clear form

**Comment by nanshet** [comment]
Logs after installing cartharge:

"Updating Homebrew...
Warning: carthage-0.20.1 already installed, it's just not linked."

Help me in this

**Comment by imurchie** [comment]
Homebrew ought to give you instructions on how to do the linking. Try running `brew doctor`.
