### ISSUE TITLE
[question] run uiautomator2 unit test failed

### ISSUE THREAD

**Issue by Carlgege** [appium/appium#8304]
## The problem

start uiautomator2 server by the command:
`adb shell am instrument -w io.appium.uiautomator2.server.test/android.support.test.runner.AndroidJUnitRunner`
error happened after i try to run unit test
`adb shell am instrument -w io.appium.uiautomator2.e2etest.test/android.support.test.runner.AndroidJUnitRunner`

and result is:
`INSTRUMENTATION_RESULT: shortMsg=java.lang.IllegalStateException
INSTRUMENTATION_RESULT: longMsg=java.lang.IllegalStateException: Cannot call dis
connect() while connecting!
INSTRUMENTATION_CODE: 0`

## Environment

Appium 1.6.3
Real device

## Question

How to debug the uiautomator2 server? The doc of appium-uiautomator2-server is too simple.

Thanks a lot.

**Comment by sravanmedarapu** [comment]
@Carlgege, Can you share `adb logcat`(clear logcat using `adb logcat -c` before execution)?

**Comment by Carlgege** [comment]
@sravanmedarapu ,
`04-24 09:42:38.659 D/TestExecutor( 5985): Adding listener android.support.test.internal.runner.listener.LogRunListener
04-24 09:42:38.659 D/TestExecutor( 5985): Adding listener android.support.test.internal.runner.listener.InstrumentationResultPrinter
04-24 09:42:38.660 D/TestExecutor( 5985): Adding listener android.support.test.internal.runner.listener.ActivityFinisherRunListener
04-24 09:42:38.691 I/TestRunner( 5985): run started: 1 tests
04-24 09:42:38.708 I/TestRunner( 5985): failed: io.appium.uiautomator2.unittest.test.HandlersTest
04-24 09:42:38.708 I/TestRunner( 5985): ----- begin exception -----
04-24 09:42:38.709 I/TestRunner( 5985): java.lang.IllegalStateException: UiAutomationService android.accessibilityservice.IAccessibilityServiceClient$Stub$Proxy@8ecd5a7already registered!
04-24 09:42:38.709 I/TestRunner( 5985):         at android.os.Parcel.readException(Parcel.java:1616)
04-24 09:42:38.709 I/TestRunner( 5985):         at android.os.Parcel.readException(Parcel.java:1561)
04-24 09:42:38.709 I/TestRunner( 5985):         at android.app.IUiAutomationConnection$Stub$Proxy.connect(IUiAutomationConnection.java:236)
04-24 09:42:38.709 I/TestRunner( 5985):         at android.app.UiAutomation.connect(UiAutomation.java:197)
04-24 09:42:38.709 I/TestRunner( 5985):         at android.app.Instrumentation.getUiAutomation(Instrumentation.java:1964)
04-24 09:42:38.709 I/TestRunner( 5985):         at android.support.test.uiautomator.UiDevice.<init>(UiDevice.java:105)
04-24 09:42:38.709 I/TestRunner( 5985):         at android.support.test.uiautomator.UiDevice.getInstance(UiDevice.java:269)
04-24 09:42:38.709 I/TestRunner( 5985):         at io.appium.uiautomator2.utils.Device.getUiDevice(Device.java:21)
04-24 09:42:38.709 I/TestRunner( 5985):         at io.appium.uiautomator2.unittest.test.HandlersTest.beforeStartServer(HandlersTest.java:99)
04-24 09:42:38.709 I/TestRunner( 5985):         at java.lang.reflect.Method.invoke(Native Method)
04-24 09:42:38.709 I/TestRunner( 5985):         at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
04-24 09:42:38.709 I/TestRunner( 5985):         at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
04-24 09:42:38.709 I/TestRunner( 5985):         at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
04-24 09:42:38.709 I/TestRunner( 5985):         at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
04-24 09:42:38.709 I/TestRunner( 5985):         at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
04-24 09:42:38.709 I/TestRunner( 5985):         at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
04-24 09:42:38.709 I/TestRunner( 5985):         at org.junit.runners.Suite.runChild(Suite.java:128)
04-24 09:42:38.709 I/TestRunner( 5985):         at org.junit.runners.Suite.runChild(Suite.java:27)
04-24 09:42:38.709 I/TestRunner( 5985):         at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
04-24 09:42:38.709 I/TestRunner( 5985):         at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
04-24 09:42:38.709 I/TestRunner( 5985):         at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
04-24 09:42:38.709 I/TestRunner( 5985):         at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
04-24 09:42:38.709 I/TestRunner( 5985):         at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
04-24 09:42:38.709 I/TestRunner( 5985):         at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
04-24 09:42:38.709 I/TestRunner( 5985):         at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
04-24 09:42:38.709 I/TestRunner( 5985):         at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
04-24 09:42:38.709 I/TestRunner( 5985):         at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)
04-24 09:42:38.709 I/TestRunner( 5985):         at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)
04-24 09:42:38.709 I/TestRunner( 5985):         at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1985)
04-24 09:42:38.709 I/TestRunner( 5985): ----- end exception -----
04-24 09:42:38.710 I/TestRunner( 5985): failed: Test mechanism
04-24 09:42:38.710 I/TestRunner( 5985): ----- begin exception -----
04-24 09:42:38.711 I/TestRunner( 5985): java.lang.NullPointerException: Attempt to invoke virtual method 'void android.os.Bundle.putString(java.lang.String, java.lang.String)' on a null object reference
04-24 09:42:38.711 I/TestRunner( 5985):         at android.support.test.internal.runner.listener.InstrumentationResultPrinter.reportFailure(InstrumentationResultPrinter.java:177)
04-24 09:42:38.711 I/TestRunner( 5985):         at android.support.test.internal.runner.listener.InstrumentationResultPrinter.testFailure(InstrumentationResultPrinter.java:167)
04-24 09:42:38.711 I/TestRunner( 5985):         at org.junit.runner.notification.SynchronizedRunListener.testFailure(SynchronizedRunListener.java:63)
04-24 09:42:38.711 I/TestRunner( 5985):         at org.junit.runner.notification.RunNotifier$4.notifyListener(RunNotifier.java:142)
04-24 09:42:38.711 I/TestRunner( 5985):         at org.junit.runner.notification.RunNotifier$SafeNotifier.run(RunNotifier.java:72)
04-24 09:42:38.711 I/TestRunner( 5985):         at org.junit.runner.notification.RunNotifier.fireTestFailures(RunNotifier.java:138)
04-24 09:42:38.711 I/TestRunner( 5985):         at org.junit.runner.notification.RunNotifier.fireTestFailure(RunNotifier.java:132)
04-24 09:42:38.711 I/TestRunner( 5985):         at org.junit.internal.runners.model.EachTestNotifier.addFailure(EachTestNotifier.java:23)
04-24 09:42:38.711 I/TestRunner( 5985):         at org.junit.internal.runners.model.EachTestNotifier.addMultipleFailureException(EachTestNotifier.java:29)
04-24 09:42:38.711 I/TestRunner( 5985):         at org.junit.internal.runners.model.EachTestNotifier.addFailure(EachTestNotifier.java:21)
04-24 09:42:38.711 I/TestRunner( 5985):         at org.junit.runners.ParentRunner.run(ParentRunner.java:369)
04-24 09:42:38.711 I/TestRunner( 5985):         at org.junit.runners.Suite.runChild(Suite.java:128)
04-24 09:42:38.711 I/TestRunner( 5985):         at org.junit.runners.Suite.runChild(Suite.java:27)
04-24 09:42:38.711 I/TestRunner( 5985):         at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
04-24 09:42:38.711 I/TestRunner( 5985):         at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
04-24 09:42:38.711 I/TestRunner( 5985):         at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
04-24 09:42:38.711 I/TestRunner( 5985):         at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
04-24 09:42:38.711 I/TestRunner( 5985):         at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
04-24 09:42:38.711 I/TestRunner( 5985):         at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
04-24 09:42:38.711 I/TestRunner( 5985):         at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
04-24 09:42:38.711 I/TestRunner( 5985):         at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
04-24 09:42:38.711 I/TestRunner( 5985):         at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)
04-24 09:42:38.711 I/TestRunner( 5985):         at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)
04-24 09:42:38.711 I/TestRunner( 5985):         at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1985)
04-24 09:42:38.711 I/TestRunner( 5985): ----- end exception -----
04-24 09:42:38.711 I/TestRunner( 5985): failed: io.appium.uiautomator2.unittest.test.HandlersTest
04-24 09:42:38.711 I/TestRunner( 5985): ----- begin exception -----
04-24 09:42:38.711 I/TestRunner( 5985): java.lang.IllegalArgumentException: unexpected url: /wd/hub/session/:sessionId
04-24 09:42:38.711 I/TestRunner( 5985):         at com.squareup.okhttp.Request$Builder.url(Request.java:163)
04-24 09:42:38.711 I/TestRunner( 5985):         at io.appium.uiautomator2.unittest.test.TestHelper.delete(TestHelper.java:78)
04-24 09:42:38.711 I/TestRunner( 5985):         at io.appium.uiautomator2.unittest.test.TestUtil.deleteSession(TestUtil.java:579)
04-24 09:42:38.711 I/TestRunner( 5985):         at io.appium.uiautomator2.unittest.test.HandlersTest.stopSever(HandlersTest.java:114)
04-24 09:42:38.711 I/TestRunner( 5985):         at java.lang.reflect.Method.invoke(Native Method)
04-24 09:42:38.711 I/TestRunner( 5985):         at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
04-24 09:42:38.711 I/TestRunner( 5985):         at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
04-24 09:42:38.711 I/TestRunner( 5985):         at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
04-24 09:42:38.711 I/TestRunner( 5985):         at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
04-24 09:42:38.711 I/TestRunner( 5985):         at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
04-24 09:42:38.711 I/TestRunner( 5985):         at org.junit.runners.Suite.runChild(Suite.java:128)
04-24 09:42:38.711 I/TestRunner( 5985):         at org.junit.runners.Suite.runChild(Suite.java:27)
04-24 09:42:38.711 I/TestRunner( 5985):         at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
04-24 09:42:38.711 I/TestRunner( 5985):         at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
04-24 09:42:38.711 I/TestRunner( 5985):         at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
04-24 09:42:38.711 I/TestRunner( 5985):         at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
04-24 09:42:38.711 I/TestRunner( 5985):         at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
04-24 09:42:38.711 I/TestRunner( 5985):         at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
04-24 09:42:38.711 I/TestRunner( 5985):         at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
04-24 09:42:38.711 I/TestRunner( 5985):         at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
04-24 09:42:38.711 I/TestRunner( 5985):         at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)
04-24 09:42:38.711 I/TestRunner( 5985):         at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)
04-24 09:42:38.711 I/TestRunner( 5985):         at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1985)
04-24 09:42:38.711 I/TestRunner( 5985): ----- end exception -----
04-24 09:42:38.712 I/TestRunner( 5985): failed: Test mechanism
04-24 09:42:38.712 I/TestRunner( 5985): ----- begin exception -----
04-24 09:42:38.712 I/TestRunner( 5985): java.lang.NullPointerException: Attempt to invoke virtual method 'void android.os.Bundle.putString(java.lang.String, java.lang.String)' on a null object reference
04-24 09:42:38.712 I/TestRunner( 5985):         at android.support.test.internal.runner.listener.InstrumentationResultPrinter.reportFailure(InstrumentationResultPrinter.java:177)
04-24 09:42:38.712 I/TestRunner( 5985):         at android.support.test.internal.runner.listener.InstrumentationResultPrinter.testFailure(InstrumentationResultPrinter.java:167)
04-24 09:42:38.712 I/TestRunner( 5985):         at org.junit.runner.notification.SynchronizedRunListener.testFailure(SynchronizedRunListener.java:63)
04-24 09:42:38.712 I/TestRunner( 5985):         at org.junit.runner.notification.RunNotifier$4.notifyListener(RunNotifier.java:142)
04-24 09:42:38.712 I/TestRunner( 5985):         at org.junit.runner.notification.RunNotifier$SafeNotifier.run(RunNotifier.java:72)
04-24 09:42:38.712 I/TestRunner( 5985):         at org.junit.runner.notification.RunNotifier.fireTestFailures(RunNotifier.java:138)
04-24 09:42:38.712 I/TestRunner( 5985):         at org.junit.runner.notification.RunNotifier.fireTestFailure(RunNotifier.java:132)
04-24 09:42:38.712 I/TestRunner( 5985):         at org.junit.internal.runners.model.EachTestNotifier.addFailure(EachTestNotifier.java:23)
04-24 09:42:38.712 I/TestRunner( 5985):         at org.junit.internal.runners.model.EachTestNotifier.addMultipleFailureException(EachTestNotifier.java:29)
04-24 09:42:38.712 I/TestRunner( 5985):         at org.junit.internal.runners.model.EachTestNotifier.addFailure(EachTestNotifier.java:21)
04-24 09:42:38.712 I/TestRunner( 5985):         at org.junit.runners.ParentRunner.run(ParentRunner.java:369)
04-24 09:42:38.712 I/TestRunner( 5985):         at org.junit.runners.Suite.runChild(Suite.java:128)
04-24 09:42:38.712 I/TestRunner( 5985):         at org.junit.runners.Suite.runChild(Suite.java:27)
04-24 09:42:38.712 I/TestRunner( 5985):         at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
04-24 09:42:38.712 I/TestRunner( 5985):         at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
04-24 09:42:38.712 I/TestRunner( 5985):         at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
04-24 09:42:38.712 I/TestRunner( 5985):         at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
04-24 09:42:38.712 I/TestRunner( 5985):         at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
04-24 09:42:38.712 I/TestRunner( 5985):         at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
04-24 09:42:38.712 I/TestRunner( 5985):         at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
04-24 09:42:38.712 I/TestRunner( 5985):         at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
04-24 09:42:38.712 I/TestRunner( 5985):         at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)
04-24 09:42:38.712 I/TestRunner( 5985):         at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)
04-24 09:42:38.712 I/TestRunner( 5985):         at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1985)
04-24 09:42:38.712 I/TestRunner( 5985): ----- end exception -----
04-24 09:42:38.713 I/TestRunner( 5985): run finished: 0 tests, 4 failed, 0 ignored`
`04-24 09:42:41.727 W/InfraTrack( 5985): Analytics post: AndroidJUnitRunner failed.
04-24 09:42:41.727 W/InfraTrack( 5985): java.net.SocketTimeoutException: failed to connect to www.google-analytics.com/192.168.93.219 (port 80) after 3000ms
04-24 09:42:41.727 W/InfraTrack( 5985):         at libcore.io.IoBridge.connectErrno(IoBridge.java:169)
04-24 09:42:41.727 W/InfraTrack( 5985):         at libcore.io.IoBridge.connect(IoBridge.java:122)
04-24 09:42:41.727 W/InfraTrack( 5985):         at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
04-24 09:42:41.727 W/InfraTrack( 5985):         at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:452)
04-24 09:42:41.727 W/InfraTrack( 5985):         at java.net.Socket.connect(Socket.java:884)
04-24 09:42:41.727 W/InfraTrack( 5985):         at com.android.okhttp.internal.Platform.connectSocket(Platform.java:117)
04-24 09:42:41.727 W/InfraTrack( 5985):         at com.android.okhttp.internal.http.SocketConnector.connectRawSocket(SocketConnector.java:160)
04-24 09:42:41.727 W/InfraTrack( 5985):         at com.android.okhttp.internal.http.SocketConnector.connectCleartext(SocketConnector.java:67)
04-24 09:42:41.727 W/InfraTrack( 5985):         at com.android.okhttp.Connection.connect(Connection.java:152)
04-24 09:42:41.727 W/InfraTrack( 5985):         at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:185)
04-24 09:42:41.727 W/InfraTrack( 5985):         at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
04-24 09:42:41.727 W/InfraTrack( 5985):         at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:341)
04-24 09:42:41.727 W/InfraTrack( 5985):         at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
04-24 09:42:41.727 W/InfraTrack( 5985):         at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
04-24 09:42:41.727 W/InfraTrack( 5985):         at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:453)
04-24 09:42:41.727 W/InfraTrack( 5985):         at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:123)
04-24 09:42:41.727 W/InfraTrack( 5985):         at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:265)
04-24 09:42:41.727 W/InfraTrack( 5985):         at android.support.test.internal.runner.tracker.AnalyticsBasedUsageTracker.sendUsages(AnalyticsBasedUsageTracker.java:254)
04-24 09:42:41.727 W/InfraTrack( 5985):         at android.support.test.runner.UsageTrackerFacilitator.sendUsages(UsageTrackerFacilitator.java:69)
04-24 09:42:41.727 W/InfraTrack( 5985):         at android.support.test.runner.AndroidJUnitRunner.finish(AndroidJUnitRunner.java:278)
04-24 09:42:41.727 W/InfraTrack( 5985):         at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:271)
04-24 09:42:41.727 W/InfraTrack( 5985):         at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1985)
04-24 09:42:41.728 I/MonitoringInstrumentation( 5985): waitForActivitiesToComplete() took: 1ms
--------- beginning of crash
04-24 09:42:41.728 E/AndroidRuntime( 5985): FATAL EXCEPTION: Instr: android.support.test.runner.AndroidJUnitRunner
04-24 09:42:41.728 E/AndroidRuntime( 5985): Process: io.appium.uiautomator2.e2etest, PID: 5985
04-24 09:42:41.728 E/AndroidRuntime( 5985): java.lang.IllegalStateException: Cannot call disconnect() while connecting!
04-24 09:42:41.728 E/AndroidRuntime( 5985):     at android.app.UiAutomation.disconnect(UiAutomation.java:234)
04-24 09:42:41.728 E/AndroidRuntime( 5985):     at android.app.Instrumentation.finish(Instrumentation.java:206)
04-24 09:42:41.728 E/AndroidRuntime( 5985):     at android.support.test.runner.MonitoringInstrumentation.finish(MonitoringInstrumentation.java:277)
04-24 09:42:41.728 E/AndroidRuntime( 5985):     at android.support.test.runner.AndroidJUnitRunner.finish(AndroidJUnitRunner.java:282)
04-24 09:42:41.728 E/AndroidRuntime( 5985):     at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:271)
04-24 09:42:41.728 E/AndroidRuntime( 5985):     at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1985)
04-24 09:42:41.729 E/ActivityManager( 1392): App crashed! Process: io.appium.uiautomator2.e2etest
04-24 09:42:41.730 I/MonitoringInstrumentation( 5985): Activities that are still in CREATED to STOPPED: 0
04-24 09:42:41.730 W/ActivityManager( 1392): Error in app io.appium.uiautomator2.e2etest running instrumentation ComponentInfo{io.appium.uiautomator2.e2etest.test/android.support.test.runner.AndroidJUnitRunner}:
04-24 09:42:41.730 W/ActivityManager( 1392):   java.lang.IllegalStateException
04-24 09:42:41.730 W/ActivityManager( 1392):   java.lang.IllegalStateException: Cannot call disconnect() while connecting!
04-24 09:42:41.732 I/ActivityManager( 1392): Force stopping io.appium.uiautomator2.e2etest appid=10129 user=0: finished inst
04-24 09:42:41.733 I/ActivityManager( 1392): Killing 5985:io.appium.uiautomator2.e2etest/u0a129 (adj 0): stop io.appium.uiautomator2.e2etest`

**Comment by dpgraham** [comment]
Is this still an issue?
