### ISSUE TITLE
Need Capability/Feature to specify the Android user profile for driver initialisation/App Launch Activity

### ISSUE THREAD

**Issue by vinodbenure** [appium/appium#8305]
## The problem

For Android OS Version 5.0 and above, An Android device can have multiple user profiles (For eg. Android For Work). However, When Appium driver is initialised , appium driver by default points to the default user profile and there is no way in Appium to mention which user profile to pick before driver initialisation.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Last Appium version that did not exhibit the issue (if applicable):NA
* Desktop OS/version used to run Appium: Windows 7
* Node.js version (unless using Appium.app|exe): 6.9.4
* Mobile platform/version under test: Android 6.0
* Real device or emulator/simulator: Real Device (Nexus 5)
* Appium CLI or Appium.app|exe: Appium CLI

## Details

When Appium driver is initialised , appium driver by default points to the default user and there is no way in Appium to mention which user profile to pick before driver initialisation.

For e.g. If there are two users (user A[default user] and user B). If a user wants to initialise  driver for an app installed in the user profile B then currently there is no way to select the user B or any other user.

We can get a list of available profiles in the device using below command:
**`adb shell pm list users`**

However, We can mention the user if we need to launch the app through command line as below:
**`adb shell am start --user USER_PROFILE_VALUE_IN_INT -n com.package./ActivityName`**

_But, When the present appium tries to launch the app or tries to initialise the app, it does not pass the **--user** parameter as above mentioned. Due to this appium driver always points to the default user profile._

If we can find a way to mention user profile name then we can easily get access to app which is installed any user profile.

## Link to Appium logs

You can clearly see in the logs that appium does not mention user profile name while launching the app

[Link to Logs](https://gist.github.com/vinodbenure/aad575fabec4de4cba6915a8fbbe6b95)

**Comment by mykola-mokhnach** [comment]
Thanks for the suggestion @vinodbenure. However, you could create a PR yourself. We will be happy to review it.

**Comment by dpgraham** [comment]
This sounds pretty sensible to me. I don't think the Appium core team will be able to get around to this any time in the near future but if @vinodbenure or anyone else in the community wants to tackle this, then we'd be happy to accept a pull request for this. It doesn't like it would be too difficult to implement.

**Comment by jlipps** [comment]
Hi @vinodbenure the appium team would be happy to help walk you through a PR. Please take whatever idea you have and start the PR process and we will help make sure it is good.

**Comment by mykola-mokhnach** [comment]
Closed as fixed
