### ISSUE TITLE
Can't type text wich contains more than 1 space

### ISSUE THREAD

**Issue by crazyk2** [appium/appium#8306]
## The problem
Try to type text like `space space space`
`        ((MobileElement)element).setValue("space space space");
`
Logs
[log](https://gist.github.com/crazyk2/39f084b7cf93806709c99d8b3d3f7a29#file-gistfile1-txt-L8)

It's equal adb command:
`adb shell input text space%space space`

## Environment
* java client 5.0.0-BETA7
* Appium server version: 1.6.4
* Node.js version: 7.5.0
* Mobile platform/version under test: Android 4.4.2
* Real device or emulator/simulator: HTC Desire 820G dual sim

## Details
I realize that my post query calls this [code](https://github.com/appium/appium-android-driver/blob/d615b15319f00181a053664f5ed6f68338a9fd2b/lib/commands/element.js#L70)
and then calls [this code](https://github.com/appium/appium-adb/blob/master/lib/tools/adb-commands.js#L217)

We need escape all spec symbols.

There need to change from
```
text = text
          .replace('\\', '\\\\')
          .replace('(', '\(')
          .replace(')', '\)')
          .replace('<', '\<')
          .replace('>', '\>')
          .replace('|', '\|')
          .replace(';', '\;')
          .replace('&', '\&')
          .replace('*', '\*')
          .replace('~', '\~')
          .replace('"', '\"')
          .replace("'", "\'")
          .replace(' ', '%s');
```

to 
```
text = text
          .replace('/\\/g', '\\\\')
          .replace('/(/g', '\(')
          .replace('/)/g', '\)')
          .replace('/</g', '\<')
          .replace('/>/g', '\>')
          .replace('/|/g', '\|')
          .replace('/;/g', '\;')
          .replace('/&/g', '\&')
          .replace('/*/g', '\*')
          .replace('/~/g', '\~')
          .replace('/"/g', '\"')
          .replace("/'/g", "\'")
          .replace('/ /g', '%s');
```
to replace those symbols globally.

**Comment by crazyk2** [comment]
@mykola-mokhnach Hi, see above

**Comment by mykola-mokhnach** [comment]
Thanks for the report. I believe you can fix the problem yourself. Just create a PR. We will be happy to review it.

https://github.com/appium/appium/tree/master/docs/en/contributing-to-appium

**Comment by mykola-mokhnach** [comment]
The PR has been merged to master. Closing as fixed.
