### ISSUE TITLE
[Android] Appium Inspector Screenshot is Blank with No Elements Displayed, Loading Wheel Spins for a Long Time[Updated]

### ISSUE THREAD

**Issue by mojojojo94** [appium/appium#8308]
## The problem
[Update] posted this yesterday, collaborator close it saying they don't support appium 1.5.3.  I got the latest appium 1.6.4 app for mac desktop and the problem still persist where the inspector is stuck on "gathering initial app source"

When appium inspector launches, the refresh wheel keeps loading and preview image is blank.
<img width="1083" alt="screen shot 2017-04-21 at 10 13 30 am" src="https://cloud.githubusercontent.com/assets/15100526/25285035/813e4e96-267e-11e7-80d2-6a2b19d42c22.png">
## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Last Appium version that did not exhibit the issue (if applicable): n/a
* Desktop OS/version used to run Appium: Mac OS Sierra
* Node.js version (unless using Appium.app|exe): Appium.app
* Mobile platform/version under test: Android, API Level 22
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: Appium.app

## Details

I set the appium gui app to launch the android virtual device whenever I click the 'launch' button then the 'appium inspector' button.

My avd launches fine and then my app launches on the avd.
Then the appium inspector launches, but the preview image is blank and there are no elements, also the refresh button has a loading wheel that keeps loading forever.
## Link to Appium logs

https://gist.github.com/mojojojo94/eb5eb6d1c592cde01264871335e919fd

## Code To Reproduce Issue [ Good To Have ]

these are the capabilities I have set:

{
  "app": "myAppFilePath.apk",
  "deviceName": "AndroidTestDevice",
  "avd": "AndroidTestDevice",
  "appPackage": "com.myApp.mobile.android",
  "appActivity": "com.myApp.mobile.android.ui.RootActivity",
  "platformName": "Android",
  "platformVersion": "5.1"
}

Am I missing some capabilities like NATIVE_APP or something?
What might cause the inspector to not gather app UI?
It might be the reason why the inspector is not showing element or a preview image.
Any help would greatly be appreciated.

**Comment by mykola-mokhnach** [comment]
Please attach full log anyway

**Comment by mojojojo94** [comment]
Ok, I'll attach the log.

**Comment by mojojojo94** [comment]
Added log.

**Comment by mykola-mokhnach** [comment]
It looks like Appium freezes while trying to get the source of the webview. Are there any errors the output of **logcat** command?

**Comment by mojojojo94** [comment]
`[Logcat] Starting logcat capture` is the only one I could find.

**Comment by mykola-mokhnach** [comment]
Use [XDA tutorial](https://forum.xda-developers.com/showthread.php?t=1726238) to find more info about how to collect logcat output

**Comment by hungtruongquoc** [comment]
@mojojojo94 Did you find out the root cause?

**Comment by mojojojo94** [comment]
@hungtruongquoc think I updated to new appium version, anyway sorry for replying in such a later manner. Issue resolved itself.

**Comment by Kowsalyadevi2003** [comment]
I do also get the same problem even after updating appium new version. 

In my case, page loads at the logo and the image captured with appium inspector. But i need to wait until the lodo loads and login screen appears. 

any help?

**Comment by nknezevic** [comment]
@Kowsalyadevi2003 try to put application in the background, then open it again and press refresh on Appium inspector. It should work, I had same problem. Also, you can add method in your tests to do the same thing automatically, until better solution is found
