### ISSUE TITLE
Copy Paste is not possible for filepath data type in desired capabilities.

### ISSUE THREAD

**Issue by rrpradip** [appium/appium#8309]
## The problem

Copy Paste is not possible for filepath data type in desired capabilities.

## Environment

Appium v1.6.4
Apple Mac
## Details
Copy Paste is not possible for filepath data type in desired capabilities.

**Comment by mykola-mokhnach** [comment]
Can you please provide more detailed issue description with screenshots/code examples?

**Comment by dpgraham** [comment]
I'm guessing you're talking about Appium Desktop.

You can use the 'text' type instead and pass in a filepath or URL.

**Comment by dpgraham** [comment]
Closing this issue. Will re-open if that doesn't answer your question.
