### ISSUE TITLE
Unable to find an element using XPATH with XCUI on IOS 10 and above

### ISSUE THREAD

**Issue by gkvappium** [appium/appium#8311]
I recently upgraded all the IOS elements so as to support XCUI. There are few elements in the app that has only XPATH and there is no other means for me to recognise the element (Never had any problem with UIA). Find element fails when I pass the value or the entire XPATH. Basically I just want to click the cell.

TimeoutException: Message: 
E             Page element of type 'Button' with locator ('xpath', '//XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeScrollView[2]/XCUIElementTypeOther[1]/XCUIElementTypeTable[1]/XCUIElementTypeCell[1]/XCUIElementTypeStaticText[1]') not found or is not visible after 10 seconds 

Also with one more element, I have the value and pass it something like this. But this doesn't seem to work. This is the element  "//XCUIElementTypeTextField[@value='Profile Name']"

@mykola-mokhnach @imurchie  : Is there any problem with value on 1.6.4 beta or with XPATH in general for XCUI. I use XPATH only when there is no other means of element identification

**Comment by mykola-mokhnach** [comment]
Try Appium 1.6.4-stable
Do not to use xpath locators, since they are slow. Most locators can be replaced with predicates.

If there are no errors/tracebacks in logs then this is unlikely an Appium issue. There must a problem with your locator. 

Please reopen the issue report only if you see any unusual output in the Appium log otherwise move the topic into Appium forum.

**Comment by gkvappium** [comment]
Hi @mykola-mokhnach ,

If you don't mind , could you please point me to some resources available to work with predicates using appium-python webdriver and xpath? I couldn't find much when it comes to predicates/xpath combination. I am aware of the fact that using xpath bogs down the execution considerably. But I have no other option for element identification in some cases and I don't think the dev team would add/modify any attributes.

Thanks

**Comment by mykola-mokhnach** [comment]
https://github.com/facebook/WebDriverAgent/wiki/Queries

**Comment by mykola-mokhnach** [comment]
Regarding location in Python client - no idea, I only use Java client. You can to ask this in the corresponding project, but not here
