### ISSUE TITLE
ADB times out after uncertain amount of test runs [BUG?][Question][uiautomator2]

### ISSUE THREAD

**Issue by NagyRobertt** [appium/appium#8312]
## The problem

Noticed this problem in our nightly test runs. After a few successful test runs i get the following time out issue: (https://gist.github.com/NagyRobertt/2620f3da4df7ddcd1c693cbe7fc4f2c2). After the issue appears every test fails with this problem. When i try to run the tests in the morning manually it is working again...

Between every test i kill and restart the appium server. I don't know if that can cause any complication?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Desktop OS/version used to run Appium: MAC OS Sierra 10.12.1
* Node.js version (unless using Appium.app|exe): 6.9.1
* Mobile platform/version under test: Android 6.0.1, 7.0
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs

https://gist.github.com/NagyRobertt/2620f3da4df7ddcd1c693cbe7fc4f2c2

**Comment by mykola-mokhnach** [comment]
Can be a bug in ADB itself... Do you see anything suspicious in "adb logcat" output when this happens?

**Comment by NagyRobertt** [comment]
Here is the logcat during the error: https://gist.github.com/NagyRobertt/9f45d2d6f59a7b9352c61c249b78beaf

Not sure if useful. When the issue appears, even the logcat hangs. i tried the adb command where the appium log drops the timeout error. It took the adb like 5-10 minutes to get the version of the android.

**Comment by mykola-mokhnach** [comment]
Then, probably, it makes sense not only to restart ADB, but the device under test itself after many tests were executed. We do it every night in our lab, for example.

**Comment by NagyRobertt** [comment]
Thanks for your responses. This is clearly not a appium related problem. Closing the incident.
