### ISSUE TITLE
Appium desktop by appium v1.6.4 Mac Sierra and IOS 10.3 got Error "EnotFound"

### ISSUE THREAD

**Issue by Netardent** [appium/appium#8314]
## The problem
I tried to install and Test by Appium Desktop on Mac osx version Xcode 8.3 and IOS 10.3. So i have installed Appium 1.6.4 and I've installed node and all pre requirement which need for Appium.

![1](https://cloud.githubusercontent.com/assets/9458718/25333374/2dff86d6-28ff-11e7-8a13-f93a960aa7a4.png)

Here is Appium Doctor output which have no error for IOS test!

![2](https://cloud.githubusercontent.com/assets/9458718/25333375/307a9fae-28ff-11e7-9657-0ca31a32c97d.png)

The output of Appium desktop, ENotFound Error.

## Environment

* Appium version (or git revision) that exhibits the issue:1.6.4
* Last Appium version that did not exhibit the issue (if applicable):1.6.3
* Desktop OS/version used to run Appium:MAC Os Sierra
* Node.js version (unless using Appium.app|exe):7.9.0
* Real device or emulator/simulator:IOS 10.3 Simulator
* Appium CLI or Appium.app|exe:Appium Desktop

## Link to Appium logs
No log in appium log page

**Comment by mykola-mokhnach** [comment]
Can you attach appium log as well?

**Comment by Netardent** [comment]
There is no log in Appium log!!
![3](https://cloud.githubusercontent.com/assets/9458718/25336631/9d832072-290d-11e7-9ff9-3c6abe45aa1f.png)

**Comment by mykola-mokhnach** [comment]
@imurchie Probably, we just need a better error description for the cases like this one ? %)

**Comment by imurchie** [comment]
Probably. I have no idea what the desktop app might be trying to do. The error does not come up if I enter a non-existent app, which is the only idea I have. @dpgraham might know better.

**Comment by dpgraham** [comment]
@Netardent Did you drag the Appium Desktop DMG into the Applications folder and then run it from there? Or are you trying to run it from the dmg directly?

**Comment by Netardent** [comment]
Dear all thank you for answering....

Sorry about the delay to your kindness, No i have dragged it and install it, Same as all other .dmg file and i opened it from application, i installed all requirement and prerequirement which mentioned in:

1. https://github.com/appium/appium/blob/master/docs/en/appium-setup/running-on-osx.md#authorizing-ios-on-the-computer
2. https://github.com/appium/appium/blob/master/docs/en/appium-setup/real-devices-ios.md
3. https://www.youtube.com/watch?v=IOSUBda2-g4
4. https://www.youtube.com/watch?v=D5MF3ZLds0Q
5. https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/caps.md

i've done all 5 approach to check i do properly :)
I checked Appium-Doctor which does not have any problem and i attached it to my first Issue and i have no idea why my .ipa not work and the simulator not work properly!

Thank you.

**Comment by dpgraham** [comment]
Can you try testing another app?

You can test apps that are native to the phone by providing the bundleId (e.g. `com.apple.calculator `)

**Comment by jlipps** [comment]
@Netardent that is a strange error, it should be better. But meanwhile some other problems I see with your caps:

- should be `platformName` not `PlatformName`
- you can't run .ipa files with the simulator (need to be `.app` files, built for the sim)

Also, have you actually opened up Xcode manually and ensured that it runs? Sometimes after an update you have to open it up manually and it needs to download something.

**Comment by Netardent** [comment]
Dear @jlipps  thank you for your answer, i want to install my .app on iPhone i want to test the application on  black box testing, i don't have any code of app file i just have .ipa file!
So i need to test my .ipa file on real device. how can i do it? please help me.

Dear @dpgraham thank you for your help,
my problem is this! i don't have any build code and i'm black box, doe it need any bundle for WebDriverAgent? i just want to run my app by robot framework-AppiumLibrary but first i want to install my .ipa file on simulator then get the Xpath of objects on real device, does i need any WebDriverAgent?

**Comment by dpgraham** [comment]
Sorry for not getting back to you @Netardent. Were you ever able to resolve this issue?

**Comment by jlipps** [comment]
Closing since it is not possible to take an .ipa and run on the simulator.

**Comment by kamranzaib** [comment]
you're running this on objective instead of local host check the top bars where it says local host / sauce labs/ etc

**Comment by yiyiguzhou** [comment]
you  need parse host file localhost=127.0.0.1

**Comment by sitanshu-zymr** [comment]
Where @yiyiguzhou ? Can you explain more here? I am still facing error one issue...
