### ISSUE TITLE
Network enable/disable issue

### ISSUE THREAD

**Issue by selvakumar-ideas2it** [appium/appium#8315]
## The problem

I need to enable and disable network in IOS real device (10.3) and the network API does not work with IOS is there any other alternative way to do this thing, I also have the same problem with android 7 real devices(Nougat)

## Environment

* Appium version 1.6.4:
*Mac os 10.12(sierra)
* Node.js version (7.9.0)
* Mobile IOS 10 and android 7
* Real device

**Comment by mykola-mokhnach** [comment]
Unfortunately neither Appium nor Appium provide any instruments to control network connection state for iOS. I saw people do [something like this](https://github.com/appium/java-client/issues/419) by opening Control Center with swipe and clicking Wi-Fi button
