### ISSUE TITLE
Get safari console log 

### ISSUE THREAD

**Issue by shapovalovei** [appium/appium#8316]
Please help me. 
After test fail I need get browser (safari) console log. 
For Android I found solution: `adb logcat | grep -i "console"`

Maybe iOS-webkit-debug-proxy have some API ? Or something else?

**Comment by mykola-mokhnach** [comment]
Maybe these are also added into system log, like on Android?

**Comment by shapovalovei** [comment]
@mykola-mokhnach I didn't find browser logs in "system log"
Maybe you know some debugger for this ?

**Comment by POlITIC** [comment]
question to the audience: Is it even possible?

**Comment by dpgraham** [comment]
I don't know of any such thing. @jlipps or @imurchie do either of you know?

**Comment by jlipps** [comment]
I think you'd have to write your own remote debug client to get the logs. And you can only have one connection at a time, which Appium is using. So no, I'm going to close this as not possible for the moment. You _could_ monkeypatch `console.log` using `executeScript` to do something more visible, however.
