### ISSUE TITLE
Are there still know issues with Sierra and Appium - Seeing no Appium logs 

### ISSUE THREAD

**Issue by nkroy** [appium/appium#8319]
## The problem

Is there a know problem with Mac OS X sierra and Appium 1.0 

## Environment

Mac OS X Sierra - 10.12.13
Intelli J Idea CE - 2017.1.1
Appium Desktop client - 1.0.0
Xcode 8.2.1
iOS Simulator - iPhone 6 running 9.3 version

## Details
So i started by install appium a few weeks back when the desktop client was not introduced yet  appium doctor shows everything set up correctly if i look at it now
info AppiumDoctor Appium Doctor v.1.4.2
info AppiumDoctor ### Diagnostic starting ###
info AppiumDoctor  ✔ The Node.js binary was found at: /usr/local/bin/node
info AppiumDoctor  ✔ Node version is 6.10.2
info AppiumDoctor  ✔ Xcode is installed at: /Applications/Xcode.app/Contents/Developer
info AppiumDoctor  ✔ Xcode Command Line Tools are installed.
info AppiumDoctor  ✔ DevToolsSecurity is enabled.
info AppiumDoctor  ✔ The Authorization DB is set up properly.
info AppiumDoctor  ✔ Carthage was found at: /usr/local/bin/carthage
info AppiumDoctor  ✔ HOME is set to: /Users/abc
info AppiumDoctor  ✔ ANDROID_HOME is set to: /Users/abc/android-sdks/
info AppiumDoctor  ✔ JAVA_HOME is set to: /Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home
info AppiumDoctor  ✔ adb exists at: /Users/abc/android-sdks/platform-tools/adb
info AppiumDoctor  ✔ android exists at: /Users/abc/android-sdks/tools/android
info AppiumDoctor  ✔ emulator exists at: /Users/abc/android-sdks/tools/emulator
info AppiumDoctor  ✔ Bin directory of $JAVA_HOME is set
info AppiumDoctor ### Diagnostic completed, no fix needed. ###
info AppiumDoctor 
info AppiumDoctor Everything looks good, bye!
info AppiumDoctor 

I wanted to checkout the desktop client and started playing with it . Got the capabilities set up and could bring the simulator to come up just fine 

<img width="650" alt="screen shot 2017-04-24 at 10 59 13 pm" src="https://cloud.githubusercontent.com/assets/1840442/25370765/b0e6566e-2941-11e7-9053-3ecbdcdd3130.png">

Wrote a small program using Intelli J 2017 
```java
Package testPackage;

import io.appium.java_client.AppiumDriver;
import io.appium.java_client.ios.IOSDriver;
import org.openqa.selenium.remote.DesiredCapabilities;

import java.net.URL;

public class IOSTest {

public static void main(String args[]){

    DesiredCapabilities cap = new DesiredCapabilities();
    cap.setCapability("platformName", "iOS");
    cap.setCapability("deviceName", "iPhone 6");
    cap.setCapability("platformVersion", "9.3");
    cap.setCapability("automationName", "XCUITest");
    cap.setCapability("app", "/Users/xxx/Desktop/abc.app");

    try {

        IOSDriver myDriver = new IOSDriver(new URL("http://0.0.0.0:4273"), cap);

        ((AppiumDriver) myDriver).context("NATIVE_APP");

    } catch(Exception e){
        
    }

}
}
```
What could i be doing wrong ?? i was expecting it will bring the simulator up but i see nothing happening No log . 

Is that a bug

**Comment by mykola-mokhnach** [comment]
No log most likely means that the client cannot connect to the server. Make sure the server is running and listening on the given port number (for example using netstat utility), try to change server IP address to 127.0.0.1, etc.

**Comment by mykola-mokhnach** [comment]
Also, there is known bug in XCTest, which prevents WDA to start properly on Simulator if MacOS version is 10.12.4+ and Xcode is older than 8.3

**Comment by nkroy** [comment]
Mac OS version in 10.12.3 so hoping thats not an issue . I have tried changing server addresses with no luck . It says appium server is running . Is there another way to check ?

**Comment by mykola-mokhnach** [comment]
have you checked the netstat output?

**Comment by imurchie** [comment]
Is there any client error? Perhaps print out what the exception thrown is?

**Comment by nkroy** [comment]
Netstat output shows me this which tells me that appium server is listening to that port
lsof -n -i4TCP:4723 
COMMAND  PID  USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
Appium  1669 xxx   63u  IPv4 0x324a6642386186c7      0t0  TCP *:4723 (LISTEN)

**Comment by nkroy** [comment]
No client error .. Really scratching my head now

**Comment by nkroy** [comment]
I run both Xcode and Android studio on my machines and for some reason now i cant bring the AVD manager up and bring the android simulator up either ( Not sure if its related . Xcode works fine though  ) . Thinking If its some kind of memory issue .But my appium script above should have bought up the simulator i would have imagined

**Comment by nkroy** [comment]
Running command line javac this is what i see

 javac IOSTest.java 
IOSTest.java:3: error: package io.appium.java_client does not exist
import io.appium.java_client.AppiumDriver;
                            ^
IOSTest.java:4: error: package io.appium.java_client.ios does not exist
import io.appium.java_client.ios.IOSDriver;
                                ^
IOSTest.java:5: error: package org.openqa.selenium.remote does not exist
import org.openqa.selenium.remote.DesiredCapabilities;
                                 ^
IOSTest.java:17: error: cannot find symbol
        DesiredCapabilities cap = new DesiredCapabilities();
        ^

**Comment by mykola-mokhnach** [comment]
Try on some other machine.
Also, you can try Appium CLI installed with npm.

**Comment by nkroy** [comment]
Tried on Appium CLI - Same issue

**Comment by dpgraham** [comment]
Is this still an issue @nkroy?

**Comment by nkroy** [comment]
You can close it
