### ISSUE TITLE
Issue with get_attribute returning bool using UIAutomator2

### ISSUE THREAD

**Issue by devstrat** [appium/appium#8321]
## The problem

I was playing a bit around getting element attributes with **uiautomator2** and noticed a strange thing: 
according to https://w3c.github.io/webdriver/webdriver-spec.html#get-element-attribute 
get_attribute should return:

> The Get Element Attribute command will return the attribute of a web element.
> ...
> 6. Let result be the result of the first matching condition:
> - If name is a boolean attribute
> "true" (**string**) if the element has the attribute, otherwise null.
> 
> - Otherwise
> The result of getting an attribute by name name.

However, on my setup I'm getting a bool value instead, which causes python webdriver bindings to crash since it expects a string according to w3c. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* AutomationName: uiautomator2
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Mac OS 10.12.4
* Node.js version (unless using Appium.app|exe): 7.9.0
* Mobile platform/version under test: Android 7.1
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: Appium Desktop

## Details

In my case I was getting the value of attribute 'enabled' which can be achieved in a different way ( element.is_enabled()) and it will provide the correct result), however this behavior is still a bit odd.
https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/remote/webelement.py#L144

## Link to Appium logs
Appium log entry:
https://gist.github.com/devstrat/c3bf0903f9ff09fba06a0a5c1ccb7c04

Python Webdriver handling error:
https://gist.github.com/devstrat/355e25bcd1e13f04d0c8198167690792

Webelement I was working with:
https://gist.github.com/devstrat/afa4893635c173423a890630e3894702

**Comment by mykola-mokhnach** [comment]
Thanks for the report @devstrat 
I believe you can fix the problem yourself. This is the project: https://github.com/appium/appium-uiautomator2-server

**Comment by sravanmedarapu** [comment]
Using appium-uiautomator2-driver v0.3.3 should fix this.
