### ISSUE TITLE
Xcode 8.3.2 (iOS 10.3) tests that call runAppInBackground(int) throw an exception

### ISSUE THREAD

**Issue by antonys1** [appium/appium#8323]
## The problem

After updating to Xcode 8.3.2 (iOS 10.3) and Appium 1.6.4, tests that call `runAppInBackground(int)` throw an exception.

## Environment

* Appium version (or git revision) that exhibits the issue: **1.6.4**
* Last Appium version that did not exhibit the issue (if applicable): **1.6.1**
* Desktop OS/version used to run Appium: **macOS 10.12.4**
* Node.js version (unless using Appium.app|exe): **7.5.0**
* Mobile platform/version under test: **iOS 10.3**
* Real device or emulator/simulator: **iOS 10.3 Simulator**
* Appium CLI or Appium.app|exe: **CLI**

## Details
Java exception:
```
at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:40)
at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
at io.appium.java_client.AppiumDriver.runAppInBackground(AppiumDriver.java:290)
```

## Link to Appium logs

https://gist.github.com/antonys1/7a697ad817d6109a625ba59e434c8383

## Code To Reproduce Issue [ Good To Have ]

Where `driver` is an `AppiumDriver` calling `driver.runAppInBackground(2);` will background the app and then throw an exception.

**Comment by mykola-mokhnach** [comment]
> [debug] [JSONWP Proxy] Got response with status 200: {"value":"Error Domain=com.facebook.WebDriverAgent Code=1 \"Failed to find scrollable visible parent with 2 visible children\" UserInfo={NSLocalizedDescription=Failed to find scrollable visible parent with 2 visible children}","sessionId":"98821523-723A-4DE9-AFCD-80B9D9896BF4","status":13}

This is a WDA bug, that Appium has nothing to do with. Please report directly to https://github.com/facebook/WebDriverAgent/issues

**Comment by antonys1** [comment]
@mykola-mokhnach This [post](https://discuss.appium.io/t/runappinbackground-is-not-working-in-1-6-4-beta/15493/2) says you made a [fix](https://github.com/appium/java-client/pull/593) and goes on to suggest that in order to test it I would need to update from the current stable Java Client v4.1.2 to [v5.0.0-BETA6](https://github.com/appium/java-client/releases/tag/v5.0.0-BETA6).

If this is correct then you should update the issue template to include whether a language specific client library was used and if so what version.

**Comment by mykola-mokhnach** [comment]
The call is backward compatible, it just shows a deprecation warning. The error that you experience has nothing to do with my changes there.

**Comment by antonys1** [comment]
OK I've reported the issue directly to WDA https://github.com/facebook/WebDriverAgent/issues/553
