### ISSUE TITLE
clear() sometimes calls popum menu

### ISSUE THREAD

**Issue by crazyk2** [appium/appium#8324]
## The problem
When I want to clear and type new subject of email in field I have a trouble. 
It is reproduced sometimes. I use UIAutomator2 engine.
See screenshot

![null-01](https://cloud.githubusercontent.com/assets/12140191/25389586/b39b6cee-29d9-11e7-806d-26b9a8fb688c.png)

## Environment

* java client 5.0.0-BETA7
* Appium server version: 1.6.4
* Node.js version: 7.5.0
* Mobile platform/version under test: Android 4.4.2
* Real device or emulator/simulator: HTC Desire 820G dual sim

## Link to Appium logs

[Appium logs](https://gist.github.com/crazyk2/6b3cd51e5c9bb1ed617909f96fd01445#file-gistfile1-txt-L17)

## Code To Reproduce Issue
`subject.clear()` where `WebElement subject;`

it calls

```
 public void clear() {
    execute(DriverCommand.CLEAR_ELEMENT, ImmutableMap.of("id", id));
  };
```

I will try to find answer.

**Comment by mykola-mokhnach** [comment]
If there is a problem then it must be somewhere there:

https://github.com/appium/appium-uiautomator2-server/blob/062433b8400baf240d48a96732661a4abf929b48/app/src/main/java/io/appium/uiautomator2/handler/Clear.java

**Comment by crazyk2** [comment]
This is chain of calls
[1](https://github.com/appium/appium-uiautomator2-driver/blob/94cc883a88b0b9e8123c8c0a498f47a040c254b8/lib/commands/element.js#L58)
[2](https://github.com/appium/appium-uiautomator2-driver/blob/94cc883a88b0b9e8123c8c0a498f47a040c254b8/lib/uiautomator2.js#L2)
[3](https://github.com/appium/appium-base-driver/blob/master/lib/jsonwp-proxy/proxy.js#L150)
[4](https://github.com/appium/appium-base-driver/blob/master/lib/jsonwp-proxy/proxy.js#L101)
No, I suggest  [here](https://github.com/appium/appium-uiautomator2-server/blob/84dfac17fd86d957c4cfd7c62005db7bc3540d65/app/src/main/java/io/appium/uiautomator2/handler/Click.java#L22)

**Comment by mykola-mokhnach** [comment]
My god feeling says the problem has nothing to do with Appium, but rather with your application under test. It has an active event listener for onFocus action. I would try to disable this menu in it current implementation for automation runs in order to make the execution stable.

**Comment by crazyk2** [comment]
@mykola-mokhnach 
Well, I gonna look at App code. But I have a question.
Where I can see these log messages [1](https://github.com/appium/appium-uiautomator2-server/blob/84dfac17fd86d957c4cfd7c62005db7bc3540d65/app/src/main/java/io/appium/uiautomator2/handler/Click.java#L34) and [2](https://github.com/appium/appium-uiautomator2-server/blob/84dfac17fd86d957c4cfd7c62005db7bc3540d65/app/src/main/java/io/appium/uiautomator2/handler/Click.java#L42). Or how can I do it?

**Comment by mykola-mokhnach** [comment]
These are written directly into adb logcat output (the device/emulator log).

**Comment by crazyk2** [comment]
But with command 
```
adb logcat > ./tmp
cat ./tmp | grep  'Click'
cat ./tmp | grep tap
```
I can see nothing

**Comment by crazyk2** [comment]
I found steps to reproduce this behavior.
1.  Input incorrect word, for example, `miooo`
2.  Input `space`, then system underline your word as incorrect
3.  Click on your word
4.  Profit

I generate random string in my tests and faced with this behavior

I hope this issue will help somebody.

And I wanna ask you @mykola-mokhnach, do you now how switch off it maybe in the settings  or kind of capability like `resetKeyboard` (`do-not-suggest`)

**Comment by mykola-mokhnach** [comment]
I think Appium does not have any built-in instruments to handle that, because each manufacturer has his own "plugins", which are set differently. 
In our automated tests we just disable all the keyboard features, like autocompletion, manually in Settings before adding them to the lab.
