### ISSUE TITLE
No sim found

### ISSUE THREAD

**Issue by githubliuqi** [appium/appium#8332]
## The problem

I tested on iphone using appium 1.6.4 , when I ran the python script ,I got this error:
No sim found with udid caef69bfacbf3c342c61621d7b4527eba9671d3e, "caef69bfacbf3c342c61621d7b4527eba9671d3e" is my iphone udid. when I used appium1.5.3,it also occurred.

## Environment

* Appium version (or git revision) that exhibits the issue:1.6.4(or 1.5.3)
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:Mac 10.11.2 
* Node.js version (unless using Appium.app|exe):v6.10.2
* Mobile platform/version under test:iPhone5 (iOS9.1)
* Real device or emulator/simulator:real device 
* Appium CLI or Appium.app|exe:  Appium.app

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

[iOS] Checking whether our device string is supported
[iOSSim] Retrieving device name string for Xcode version 7.3
[iOSSim] Getting device string from options: {"deviceName":"iPhone 5","platformVersion":"9.1","forceIphone":false,"forceIpad":false}
[iOSSim] Final device string is 'iPhone 5 (9.1)'
[iOS] iOS sim UDID is caef69bfacbf3c342c61621d7b4527eba9671d3e
[MJSONWP] Encountered internal error running command: Error: No sim found with udid caef69bfacbf3c342c61621d7b4527eba9671d3e

## Code To Reproduce Issue [ Good To Have ]

#coding=utf-8
import sys
import os

from appium import webdriver

desired_caps = {}
desired_caps['platformName'] = 'iOS' 
desired_caps['platformVersion'] = '9.1'
desired_caps['deviceName'] = 'iPhone 5'
desired_caps['app'] = 'safe.Test'

driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)

#driver.find_element_by_name("1").click()
driver.find_element_by_name("button").click()
driver.quit()

**Comment by mykola-mokhnach** [comment]
Set the **udid** property instead of **deviceName** if you want to test on a real device
Closed as non Appium-related issue
