### ISSUE TITLE
Unsupported locator strategy: accessibility id

### ISSUE THREAD

**Issue by hustlerism** [appium/appium#8333]
## The problem

Currently testing a hybrid app on Android. Error occured after debug it with JUnit.

> org.openqa.selenium.WebDriverException: unknown error: Unsupported locator strategy: accessibility id

` driver.findElementByAccessibilityId("Accept").click();`

## Environment

* Latest Appium Desktop
* Windows 10
* Android/6.0.1
* Real Device/Nexus 5:
* Appium.app|exe:

**Comment by ochubey** [comment]
Hi
What do You see when running System.out.println(driver.getContext()); before mentioned click?
Could it be WebView?

**Comment by hustlerism** [comment]
Hi,

It is webview. Is this the problem?

**Comment by mykola-mokhnach** [comment]
@hustlerism Yes, location by accessibility ids is only supported inside native context. closed as non Appium-related issue
