### ISSUE TITLE
Adding uiautomator2 capability results in session creataion error and appium log shows JAVA_HOME not set even though it is already set.

### ISSUE THREAD

**Issue by Zenerax** [appium/appium#8335]
**## Description**

Adding "uiautomator2" capability to create a new AndroidDriver fails with SessionNotCreatedException while targeting test automation to Android 7.0 devices.
  All the dependencies are updated with the latest builds as stated in the Environment section below.

**## Environment**

* java client build version or git revision if you use some shapshot: 5.0.0-BETA7
* Appium server version or git revision if you use some shapshot: 1.6.4
* Appium-Android-Driver: 1.17.2
* Desktop OS/version used to run Appium if necessary: CentOS
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: 6.9.1
* Mobile platform/version under test: LG G5, Samsung S6, Samsung S7 with Android 7.0
* Real device or emulator/simulator: real devices

**## Details**

I have been experiencing problem where test scripts fail to locate mobile elements on Android 7.0 devices with Appium 1.6.4 and below along with uiautomator.
To resolve the issue, uiautomator2 is being tried with my test scripts by adding "uiautomator2" capability to create a new AndroidDriver which fails with 
 SessionNotCreatedException while targeting test automation to Android 7.0 devices.  
 
All the dependencies are updated with the latest builds as stated in the Environment section above and dependencies are refreshed building the test.

Looking at Appium error log, it seems that some path is set to null or sometimes JAVA_HOME is not set, even though when I check the environment variable, it is correctly set and Appium Doctor shows no error as shown below.  Can you please take a look and what should be done to resolve the issue?  I think the Appum wants to see the JAVA_HOME set at run time somehow differently even though it already set.  Can someone help me with the guidance to resolve the issue?

               Appium-doctor log:

[xyz@localhost ~]$ appium-doctor
info AppiumDoctor Appium Doctor v.1.4.2
info AppiumDoctor ### Diagnostic starting ###
info AppiumDoctor  ✔ The Node.js binary was found at: /usr/bin/node
info AppiumDoctor  ✔ Node version is 6.7.0
info AppiumDoctor  ✔ ANDROID_HOME is set to: /opt/android-sdk-linux
info AppiumDoctor  ✔ JAVA_HOME is set to: /usr/java/jdk1.8.0_77
info AppiumDoctor  ✔ adb exists at: /opt/android-sdk-linux/platform-tools/adb
info AppiumDoctor  ✔ android exists at: /opt/android-sdk-linux/tools/android
info AppiumDoctor  ✔ emulator exists at: /opt/android-sdk-linux/tools/emulator
info AppiumDoctor  ✔ Bin directory of $JAVA_HOME is set
info AppiumDoctor ### Diagnostic completed, no fix needed. ###
info AppiumDoctor
info AppiumDoctor Everything looks good, bye!
info AppiumDoctor

**## Code To Reproduce Issue:**
               DesiredCapabilities cap;
               cap.setCapability(MobileCapabilityType.PLATFORM_NAME, MobilePlatform.ANDROID);
               cap.setCapability(MobileCapabilityType.DEVICE_NAME, androidDevice);   
               cap.setCapability(MobileCapabilityType.AUTOMATION_NAME, "uiautomator2");
               driver = new AndroidDriver<MobileElement>(appiumServerURL, cap);

**## Ecxeption stacktraces:**
org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. desired capabilities = Capabilities [{newCommandTimeout=600, automationName=uiautomator2, browserName=Chrome, platformName=Android, deviceName=Android Device}], required capabilities = Capabilities [{}]
               Build info: version: '3.3.1', revision: '5234b32', time: '2017-03-10 09:04:52 -0800'
               System info: host: 'localhost.localdomain', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-327.36.1.el7.x86_64', java.version: '1.8.0_77'
               Driver info: driver.version: AndroidDriver
                              at io.appium.java_client.remote.AppiumProtocolHandShake.lambda$1(AppiumProtocolHandShake.java:96)
                              at java.util.Optional.orElseThrow(Optional.java:290)
                              at io.appium.java_client.remote.AppiumProtocolHandShake.createSession(AppiumProtocolHandShake.java:96)
                              at io.appium.java_client.remote.AppiumCommandExecutor.doExecute(AppiumCommandExecutor.java:111)
                              at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:162)
                              at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:604)
                              at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
                              at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
                              at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
                              at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:244)
                              at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
                              at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
                              at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:38)
                              at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:88)
                              at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:112)
                              at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:73)
                              at com…….getDriver(WebDriverFactory.java:45)
                              …
                              …

**Comment by mykola-mokhnach** [comment]
This looks more like java client issue rather than Appium issue. Please report to https://github.com/appium/java-client/issues

**Comment by Zenerax** [comment]
Thank you!  I will repost it as a Java client issue.

**Comment by SteffyVarghese1** [comment]
Hi ,
I am still facing an issue with the adding the uiautomator2. Please find the below appium logs.

**#Appium  Logs:**

[Appium] Welcome to Appium v1.8.0-beta3
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"appPackage":"uk.co.o2.android.ask.enterprise","a
ppActivity":"com.tuenti.messenger.ui.activity.MainActivity","app":"C:\\Users\\va
rghes1\\MobileAppAutomationFramework\\mobileappautomation\\App\\app-o2UK-allsdk-
enterprise-9.13.8.apk","noReset":true,"platformVersion":"7.0","automationName":"
uiautomator2","autoGrantPermissions":"true","udid":"04157df45ba4c40b","platformN
ame":"Android","deviceName":"Android Device"},"requiredCapabilities":{},"capabil
ities":{"desiredCapabilities":{"appPackage":"uk.co.o2.android.ask.enterprise","a
ppActivity":"com.tuenti.messenger.ui.activity.MainActivity","app":"C:\\Users\\va
rghes1\\MobileAppAutomationFramework\\mobileappautomation\\App\\app-o2UK-allsdk-
enterprise-9.13.8.apk","noReset":true,"platformVersion":"7.0","automationName":"
uiautomator2","autoGrantPermissions":"true","udid":"04157df45ba4c40b","platformN
ame":"Android","deviceName":"Android Device"},"requiredCapabilities":{},"alwaysM
atch":{"platformName":"Android"},"firstMatch":[
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"appPackage"
:"uk.co.o2.android.ask.enterprise","appActivity":"com.tuenti.messenger.ui.activi
ty.MainActivity","app":"C:\\Users\\varghes1\\MobileAppAutomationFramework\\mobil
eappautomation\\App\\app-o2UK-allsdk-enterprise-9.13.8.apk","noReset":true,"plat
formVersion":"7.0","automationName":"uiautomator2","autoGrantPermissions":"true"
,"udid":"04157df45ba4c40b","platformName":"Android","deviceName":"Android Device
"},{},{"desiredCapabilities":{"appPackage":"uk.co.o2.android.ask.enterprise","ap
pActivity":"com.tuenti.messenger.ui.activity.MainActivity","app":"C:\\Users\\var
ghes1\\MobileAppAutomationFramework\\mobileappautomation\\App\\app-o2UK-allsdk-e
nterprise-9.13.8.apk","noReset":true,"platformVersion":"7.0","automationName":"u
iautomator2","autoGrantPermissions":"true","udid":"04157df45ba4c40b","platformNa
me":"Android","deviceName":"Android Device"},"requiredCapabilities":{},"alwaysMa
tch":{"platformName":"Android"},"firstMatch":[]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1521634567762 (12:16:
07 GMT+0000 (GMT Standard Time))
[Appium] Could not parse W3C capabilities: 'deviceName' can't be blank. Falling
back to JSONWP protocol.
[Appium] Creating new AndroidUiautomator2Driver (v1.5.0) session
[Appium] Capabilities:
[Appium]   appPackage: uk.co.o2.android.ask.enterprise
[Appium]   appActivity: com.tuenti.messenger.ui.activity.MainActivity
[Appium]   app: C:\Users\varghes1\MobileAppAutomationFramework\mobileappautomati
on\App\app-o2UK-allsdk-enterprise-9.13.8.apk
[Appium]   noReset: true
[Appium]   platformVersion: 7.0
[Appium]   automationName: uiautomator2
[Appium]   autoGrantPermissions: true
[Appium]   udid: 04157df45ba4c40b
[Appium]   platformName: Android
[Appium]   deviceName: Android Device
[debug] [BaseDriver] Creating session with MJSONWP desired capabilities: {"appPa
ckage":"uk.co.o2.and...
[BaseDriver] Capability 'autoGrantPermissions' changed from string to boolean. T
his may cause unexpected behavior
[BaseDriver] Session created with session id: 9d043c03-91c3-483c-bbad-e029e11a18
93
[BaseDriver] Using local app 'C:\Users\varghes1\MobileAppAutomationFramework\mob
ileappautomation\App\app-o2UK-allsdk-enterprise-9.13.8.apk'
[debug] [UiAutomator2] Checking whether app is actually present
[debug] [AndroidDriver] Getting Java version
[AndroidDriver] Java version is: 1.8.0_161
[ADB] Checking whether adb is present
[ADB] Found 3 'build-tools' folders under 'C:\Users\varghes1\AppData\Local\Andro
id\Sdk' (newest first):
[ADB]     C:/Users/varghes1/AppData/Local/Android/Sdk/build-tools/27.0.3
[ADB]     C:/Users/varghes1/AppData/Local/Android/Sdk/build-tools/27.0.1
[ADB]     C:/Users/varghes1/AppData/Local/Android/Sdk/build-tools/26.0.2
[ADB] Using adb.exe from C:\Users\varghes1\AppData\Local\Android\Sdk\platform-to
ols\adb.exe
[AndroidDriver] Retrieving device list
[debug] [ADB] Trying to find a connected android device
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[AndroidDriver] Using device: 04157df45ba4c40b
[ADB] Checking whether adb is present
[ADB] Using adb.exe from C:\Users\varghes1\AppData\Local\Android\Sdk\platform-to
ols\adb.exe
[debug] [ADB] Setting device id to 04157df45ba4c40b
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\varghes1\AppData\Local\Android\Sdk\platform-tool
s\adb.exe' with args: ["-P",5037,"-s","04157df45ba4c40b","shell","getprop","ro.b
uild.version.sdk"]
[debug] [ADB] Current device property 'ro.build.version.sdk': 24
[debug] [ADB] Device API level: 24
[ADB] Getting device platform version
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\varghes1\AppData\Local\Android\Sdk\platform-tool
s\adb.exe' with args: ["-P",5037,"-s","04157df45ba4c40b","shell","getprop","ro.b
uild.version.release"]
[debug] [ADB] Current device property 'ro.build.version.release': 7.0
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\varghes1\AppData\Local\Android\Sdk\platform-tool
s\adb.exe' with args: ["-P",5037,"-s","04157df45ba4c40b","shell","wm","size"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\varghes1\AppData\Local\Android\Sdk\platform-tool
s\adb.exe' with args: ["-P",5037,"-s","04157df45ba4c40b","shell","wm","density"]

[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\varghes1\AppData\Local\Android\Sdk\platform-tool
s\adb.exe' with args: ["-P",5037,"-s","04157df45ba4c40b","shell","getprop","ro.p
roduct.model"]
[debug] [ADB] Current device property 'ro.product.model': SM-G925F
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\varghes1\AppData\Local\Android\Sdk\platform-tool
s\adb.exe' with args: ["-P",5037,"-s","04157df45ba4c40b","shell","getprop","ro.p
roduct.manufacturer"]
[debug] [ADB] Current device property 'ro.product.manufacturer': samsung
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\varghes1\AppData\Local\Android\Sdk\platform-tool
s\adb.exe' with args: ["-P",5037,"-s","04157df45ba4c40b","shell","am","force-sto
p","io.appium.uiautomator2.server"]
[debug] [ADB] Checking app cert for C:\Users\varghes1\AppData\Roaming\npm\node_m
odules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-s
erver-v1.3.0.apk
[ADB] Using apksigner.bat from C:\Users\varghes1\AppData\Local\Android\Sdk\build
-tools\27.0.3\apksigner.bat
[ADB] Using apksigner.bat from C:\Users\varghes1\AppData\Local\Android\Sdk\build
-tools\27.0.3\apksigner.bat
[debug] [ADB] Patching 'C:\Users\varghes1\AppData\Local\Android\Sdk\build-tools\
27.0.3\apksigner.bat' for Windows...
[debug] [ADB] Starting patched 'C:\Users\varghes1\AppData\Local\Temp\2018221-501
2-1ye532.sxlzd\apksigner.bat' with args 'verify,--print-certs,C:\Users\varghes1\
AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-server\
apks\appium-uiautomator2-server-v1.3.0.apk'
[debug] [ADB] 'C:\Users\varghes1\AppData\Roaming\npm\node_modules\appium\node_mo
dules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v1.3.0.apk' is
not signed with debug cert.
[ADB] Using apksigner.bat from C:\Users\varghes1\AppData\Local\Android\Sdk\build
-tools\27.0.3\apksigner.bat
[debug] [ADB] Zip-aligning 'C:\Users\varghes1\AppData\Roaming\npm\node_modules\a
ppium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v1
.3.0.apk'
[ADB] Checking whether zipalign is present
[ADB] Using zipalign.exe from C:\Users\varghes1\AppData\Local\Android\Sdk\build-
tools\27.0.3\zipalign.exe
[ADB] Error: zipAlignApk failed. Original error: Command 'C\:\\Users\\varghes1\\
AppData\\Local\\Android\\Sdk\\build-tools\\27.0.3\\zipalign.exe -f 4 C\:\\Users\
\varghes1\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-uia
utomator2-server\\apks\\appium-uiautomator2-server-v1.3.0.apk C\:\\Users\\varghe
s1\\AppData\\Local\\Temp\\2018221-5012-1q3rkai.oqgqf\\appium.tmp' exited with co
de 1. Stdout: ''; Stderr: ''
[ADB]     at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:78:13)
[ADB]     at ADB.callee$0$0$ (../../../lib/tools/apk-signing.js:173:9)
[ADB]     at tryCatch (C:\Users\varghes1\AppData\Roaming\npm\node_modules\appium
\node_modules\babel-runtime\regenerator\runtime.js:67:40)
[ADB]     at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\varghes1\A
ppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\ru
ntime.js:315:22)
[ADB]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next]
 (C:\Users\varghes1\AppData\Roaming\npm\node_modules\appium\node_modules\babel-r
untime\regenerator\runtime.js:100:21)
[ADB]     at GeneratorFunctionPrototype.invoke (C:\Users\varghes1\AppData\Roamin
g\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:
37)
[ADB]     at <anonymous>
[debug] [ADB] Signing 'C:\Users\varghes1\AppData\Roaming\npm\node_modules\appium
\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v1.3.0.
apk' with default cert
[ADB] Using apksigner.bat from C:\Users\varghes1\AppData\Local\Android\Sdk\build
-tools\27.0.3\apksigner.bat
[debug] [ADB] Patching 'C:\Users\varghes1\AppData\Local\Android\Sdk\build-tools\
27.0.3\apksigner.bat' for Windows...
[debug] [ADB] Starting patched 'C:\Users\varghes1\AppData\Local\Temp\2018221-501
2-9agc1.rzd63f\apksigner.bat' with args 'sign,--key,C:\Users\varghes1\AppData\Ro
aming\npm\node_modules\appium\node_modules\appium-adb\keys\testkey.pk8,--cert,C:
\Users\varghes1\AppData\Roaming\npm\node_modules\appium\node_modules\appium-adb\
keys\testkey.x509.pem,C:\Users\varghes1\AppData\Roaming\npm\node_modules\appium\
node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v1.3.0.a
pk'
[debug] [ADB] Zip-aligning 'C:\Users\varghes1\AppData\Roaming\npm\node_modules\a
ppium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v1
.3.0.apk'
[ADB] Checking whether zipalign is present
[ADB] Using zipalign.exe from C:\Users\varghes1\AppData\Local\Android\Sdk\build-
tools\27.0.3\zipalign.exe
[ADB] Error: zipAlignApk failed. Original error: Command 'C\:\\Users\\varghes1\\
AppData\\Local\\Android\\Sdk\\build-tools\\27.0.3\\zipalign.exe -f 4 C\:\\Users\
\varghes1\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-uia
utomator2-server\\apks\\appium-uiautomator2-server-v1.3.0.apk C\:\\Users\\varghe
s1\\AppData\\Local\\Temp\\2018221-5012-3el63u.lvpt1\\appium.tmp' exited with cod
e 1. Stdout: ''; Stderr: ''
[ADB]     at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:78:13)
[ADB]     at ADB.callee$0$0$ (../../../lib/tools/apk-signing.js:173:9)
[ADB]     at tryCatch (C:\Users\varghes1\AppData\Roaming\npm\node_modules\appium
\node_modules\babel-runtime\regenerator\runtime.js:67:40)
[ADB]     at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\varghes1\A
ppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\ru
ntime.js:315:22)
[ADB]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next]
 (C:\Users\varghes1\AppData\Roaming\npm\node_modules\appium\node_modules\babel-r
untime\regenerator\runtime.js:100:21)
[ADB]     at GeneratorFunctionPrototype.invoke (C:\Users\varghes1\AppData\Roamin
g\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:
37)
[ADB]     at <anonymous>
[debug] [UiAutomator2] Deleting UiAutomator2 session
[debug] [UiAutomator2] Deleting UiAutomator2 server session
[UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error
 was: Error: Trying to proxy a session command without session id
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\varghes1\AppData\Local\Android\Sdk\platform-tool
s\adb.exe' with args: ["-P",5037,"-s","04157df45ba4c40b","shell","am","force-sto
p","uk.co.o2.android.ask.enterprise"]
[debug] [ADB] Removing forwarded port socket connection: 8200
[debug] [ADB] Running 'C:\Users\varghes1\AppData\Local\Android\Sdk\platform-tool
s\adb.exe' with args: ["-P",5037,"-s","04157df45ba4c40b","forward","--remove","t
cp:8200"]
[debug] [ADB] Running 'C:\Users\varghes1\AppData\Local\Android\Sdk\platform-tool
s\adb.exe' with args: ["-P",5037,"-s","04157df45ba4c40b","forward","--remove","t
cp:8200"]
[UiAutomator2] Unable to remove port forward 'Error executing adbExec. Original
error: 'Command 'C\:\\Users\\varghes1\\AppData\\Local\\Android\\Sdk\\platform-to
ols\\adb.exe -P 5037 -s 04157df45ba4c40b forward --remove tcp\:8200' exited with
 code 1'; Stderr: 'error: listener 'tcp:8200' not found'; Code: '1''
[MJSONWP] Encountered internal error running command: Error: zipAlignApk failed.
 Original error: Command 'C\:\\Users\\varghes1\\AppData\\Local\\Android\\Sdk\\bu
ild-tools\\27.0.3\\zipalign.exe -f 4 C\:\\Users\\varghes1\\AppData\\Roaming\\npm
\\node_modules\\appium\\node_modules\\appium-uiautomator2-server\\apks\\appium-u
iautomator2-server-v1.3.0.apk C\:\\Users\\varghes1\\AppData\\Local\\Temp\\201822
1-5012-3el63u.lvpt1\\appium.tmp' exited with code 1. Stdout: ''; Stderr: ''
[MJSONWP]     at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:78:13)

[MJSONWP]     at ADB.callee$0$0$ (../../../lib/tools/apk-signing.js:173:9)
[MJSONWP]     at tryCatch (C:\Users\varghes1\AppData\Roaming\npm\node_modules\ap
pium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
[MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\varghe
s1\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerato
r\runtime.js:315:22)
[MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as n
ext] (C:\Users\varghes1\AppData\Roaming\npm\node_modules\appium\node_modules\bab
el-runtime\regenerator\runtime.js:100:21)
[MJSONWP]     at GeneratorFunctionPrototype.invoke (C:\Users\varghes1\AppData\Ro
aming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:
136:37)
[MJSONWP]     at <anonymous>
[HTTP] <-- POST /wd/hub/session 500 6814 ms - 608
[HTTP]

===================================================================
Code:

        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability("automationName","uiautomator2");
        capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "Android Device");
        //capabilities.setCapability("app", file.getAbsoluteFile());
        capabilities.setCapability("udid", "04157df45ba4c40b");
        capabilities.setCapability("platformName", "Android");
        capabilities.setCapability("platformVersion", "7.0");
        capabilities.setCapability("appPackage", "uk.co.o2.android.ask.enterprise");
        capabilities.setCapability("appActivity", "com.tuenti.messenger.ui.activity.MainActivity");
        capabilities.setCapability("noReset", true);
        capabilities.setCapability("autoGrantPermissions", "true");
        capabilities.setCapability("app", file.getAbsoluteFile());


        driver = new AndroidDriver<MobileElement>(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
    }
