### ISSUE TITLE
Is there any place where i can see real time versions of appium?

### ISSUE THREAD

**Issue by vjmaiky** [appium/appium#8336]
Is there any place where i can see real time versions of appium?

Ex: Last stable (1.6.4), new betas (1.6.4 beta 5), etc.

I searched for it but could not find it.

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium/releases
This is only for stable. 
All releases are visible in console:

```
npm info appium
```

**Comment by vjmaiky** [comment]
Thanks!!!
