### ISSUE TITLE
sendKeys doesn't work with accents

### ISSUE THREAD

**Issue by asvdw** [appium/appium#8338]
## The problem

Java command `myElement.sendKeys("Hello");` works as expected.
But using an accent in given text (`myElement.sendKeys("Héllo");`), input is cleared but not filled again (still empty). 

As I know it's not possible to use driver.sendKeyCode with accents characters, so it's not a workaround (but maybe the reason ?)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4, 1.6.3
* Desktop OS/version used to run Appium: OSX
* Node.js version (unless using Appium.app|exe): Appium Desktop 1.0.0
* Mobile platform/version under test: Android 5.1.1 / 5.0
* Real device or emulator/simulator: android emulator / real device Huawei ALE-L21
* Appium CLI or Appium.app|exe: Appium Desktop 1.0.0

Than you

**Comment by mykola-mokhnach** [comment]
Unicode input a pain with Android. Try to play with **unicodeKeyboard** capability

**Comment by asvdw** [comment]
just saw the doc... https://appium.readthedocs.io/en/stable/en/writing-running-appium/unicode/

Adding desiredCapability "unicodeKeyboard", "true" does the job.

thank you for your so quick help

**Comment by sahilcsgroup** [comment]
I tried this way but it just type ? at the place of é. I have a screenshot of this. Please anyone help me out with this.

![capture](https://cloud.githubusercontent.com/assets/16078970/26043604/0ce0d082-395c-11e7-841a-4ce0ca697bac.JPG)
