### ISSUE TITLE
Appium not detecting Environmental Variables

### ISSUE THREAD

**Issue by karthik619** [appium/appium#8340]
## The problem

After Successfully installing Andriod Studio v2.3.1 and setup Environmental variables. Appium continuously failing to detect the variables path. Tested by replacing the Android SDK location in different drives. Please help me .

## Environment

* Appium version: 1.6.4
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: win 10 x64
* Node.js version (unless using Appium.app|exe):  v6.10.2
* Mobile platform/version under test: Andriod Studio v2.3.1 (Emulator v 7.1.1)
* Real device or emulator/simulator:  Emulator
* Appium CLI or Appium.app|exe:

## Details

At first the Problem occurred when i'm trying to invoke a native app in android. 

here are the Logs,when i run the code in Eclipse

## Link to Appium logs

[debug] [AndroidDriver] Shutting down Android driver
[debug] [AndroidDriver] Called deleteSession but bootstrap wasn't active
[debug] [Logcat] Stopping logcat capture
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'D:\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","am","force-stop","io.appium.unlock"]
[debug] [AndroidDriver] Not cleaning generated files. Add `clearSystemFiles` capability if wanted.
[MJSONWP] Encountered internal error running command: Error: packageAndLaunchActivityFromManifest failed. Original error: Could not find aapt Please set the ANDROID_HOME environment variable with the Android SDK root directory path.
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at ADB.callee$0$0$ (../../../lib/tools/android-manifest.js:88:9)
    at tryCatch (C:\Users\saika\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\saika\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\saika\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\saika\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:109:7)
[HTTP] <-- POST /wd/hub/session 500 6787 ms - 308

## Link to Appium logs

info AppiumDoctor Appium Doctor v.1.4.2
info AppiumDoctor ### Diagnostic starting ###
info AppiumDoctor  ✔ The Node.js binary was found at: C:\Program Files\nodejs\node.exe
info AppiumDoctor  ✔ Node version is 6.10.2
WARN AppiumDoctor  ✖ ANDROID_HOME is NOT set!
info AppiumDoctor  ✔ JAVA_HOME is set to: C:\Program Files\Java\jdk1.8.0_131
WARN AppiumDoctor  ✖ adb could not be found because ANDROID_HOME is NOT set!
WARN AppiumDoctor  ✖ android could not be found because ANDROID_HOME is NOT set!
WARN AppiumDoctor  ✖ emulator could not be found because ANDROID_HOME is NOT set!
info AppiumDoctor  ✔ Bin directory of %JAVA_HOME% is set
info AppiumDoctor ### Diagnostic completed, 4 fixes needed. ###
info AppiumDoctor
info AppiumDoctor ### Manual Fixes Needed ###
info AppiumDoctor The configuration cannot be automatically fixed, please do the following first:
WARN AppiumDoctor - Manually configure ANDROID_HOME.
WARN AppiumDoctor - Manually configure ANDROID_HOME and run appium-doctor again.
info AppiumDoctor ###
info AppiumDoctor
info AppiumDoctor Bye! Run appium-doctor again when all manual fixes have been applied!
info AppiumDoctor

**Comment by mykola-mokhnach** [comment]
How this is related to Appium?
Do you want one to teach you how to set system environment variables? Correct?

**Comment by karthik619** [comment]
all have set according to the way it has. But, still appium-doctor is not detecting . So, this is how it related to Appium. @mykola-mokhnach

**Comment by mykola-mokhnach** [comment]
it is easy to check. Execute 

```
env | grep ANDROID_HOME
```

in the same terminal window where Appium doctor is executed and make sure the output is not empty

**Comment by karthik619** [comment]
@mykola-mokhnach 
I'm Getting like this
![1](https://cloud.githubusercontent.com/assets/28125836/25599886/4e9e1c76-2ea5-11e7-8a3a-b0eb4608a97c.PNG)

**Comment by mykola-mokhnach** [comment]
https://www.google.com/search?q=windows+set+environment+variables

**Comment by mykola-mokhnach** [comment]
Closed as non Appium-related
