### ISSUE TITLE
I am not able to find out if the webview [Textual ad] in the iOS app is scrollable. 

### ISSUE THREAD

**Issue by PrabhatPandey** [appium/appium#8342]
## The problem
So this webview is inside a view and I would like to check if the webview is scrollable with respect to the view in which it resides. 

is there any thing like this which exists in the appium ?

**Comment by mykola-mokhnach** [comment]
The description is totally unclear. Please describe it in more details, provide screenshots, page source listings etc?

In case this is only a question and you haven't even tried it then you never know until you try. Each situation is unique.
