### ISSUE TITLE
 org.openqa.selenium.SessionNotCreatedException: A new session could not be created. (Original error: A new session could not be created. (Original error: session not created exception from unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"11107.1","isDefault":true},"id":1,"name":"","origin":"://"} -error occurs when I try to open a url on google chrome browser using APPIUM

### ISSUE THREAD

**Issue by HarishCS** [appium/appium#8344]
## The problem

I am trying to launch gmail URL using google chrome browser on a mobile device using APPIUM, when I run my selenium script from eclipse I get the error mentioned above.

## Environment

* Appium Version: 1.4.16.1
* JDK Version: 1.8
* Selenium Stand Alone Server: 2.53.1
* Java Client 4.12
* Real Device
*Operating: Windows 10

## Details

Below is my Code:
package com.gmail.open;

import java.net.MalformedURLException;
import java.net.URL;

import org.openqa.selenium.remote.DesiredCapabilities;

import io.appium.java_client.AppiumDriver;
import io.appium.java_client.android.AndroidDriver;

public class SampleCode {
	
	  public static AppiumDriver driver = null;
      public static DesiredCapabilities desc = null;

	public static void main(String[] args) throws MalformedURLException, InterruptedException {
          desc = new DesiredCapabilities();
          desc.setCapability("automationName","Appium");
          desc.setCapability("platformName", "Android");
          desc.setCapability("platformVersion", "5.0");
          desc.setCapability("deviceName", "Lenovo K50a40");
          desc.setCapability("browserName", "Chrome");
          desc.setCapability("appPackage", "com.android.chrome");
          desc.setCapability("appActivity", "com.google.android.apps.chrome.Main");
          
          URL url = new URL("http://127.0.0.1:4723/wd/hub");
          driver = new AndroidDriver(url, desc);    
          driver.get("https://www.gmail.com");
          Thread.sleep(10000);
          driver.close();

	}

}

## Link to Appium logs

> Checking if an update is available
> Update available to new version 1.4.16.1
> Launching Appium server with command: C:\Program Files (x86)\Appium\node.exe lib\server\main.js --address 127.0.0.1 --port 4723 --browser-name Chrome --platform-name Android --platform-version 21 --automation-name Appium --log-no-color
> warn: Appium support for versions of node < 0.12 has been deprecated and will be removed in a future version. Please upgrade!
> info: Welcome to Appium v1.4.13 (REV c75d8adcb66a75818a542fe1891a34260c21f76a)
> info: Appium REST http interface listener started on 127.0.0.1:4723
> info: [debug] Non-default server args: {"address":"127.0.0.1","logNoColors":true,"platformName":"Android","platformVersion":"21","automationName":"Appium","browserName":"Chrome"}
> info: Console LogLevel: debug
> info: --> POST /wd/hub/session {"desiredCapabilities":{"appPackage":"com.android.chrome","appActivity":"com.google.android.apps.chrome.Main","platformVersion":"5.0","automationName":"Appium","browserName":"Chrome","platformName":"Android","deviceName":"Lenovo K50a40"}}
> info: Client User-Agent string: Apache-HttpClient/4.5.1 (Java/1.8.0_131)
> info: Set mode: Proxying straight through to Chromedriver
> info: [debug] Looks like we want chrome on android
> info: [debug] Creating new appium session d08d6afd-93ae-41af-b7ab-a357fde8b819
> info: [debug] Checking whether adb is present
> info: [debug] Using adb from C:\Users\admin\AppData\Local\Android\android-sdk\platform-tools\adb.exe
> info: [debug] Using fast reset? true
> info: [debug] Preparing device for session
> info: [debug] Not checking whether app is present since we are assuming it's already on the device
> info: Retrieving device
> info: [debug] Trying to find a connected android device
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: C:\Users\admin\AppData\Local\Android\android-sdk\platform-tools\adb.exe devices
> info: [debug] 0 device(s) connected
> info: [debug] Could not find devices, restarting adb server...
> info: [debug] executing cmd: C:\Users\admin\AppData\Local\Android\android-sdk\platform-tools\adb.exe kill-server
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: C:\Users\admin\AppData\Local\Android\android-sdk\platform-tools\adb.exe devices
> info: [debug] 0 device(s) connected
> info: [debug] Could not find devices, restarting adb server...
> info: [debug] executing cmd: C:\Users\admin\AppData\Local\Android\android-sdk\platform-tools\adb.exe kill-server
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: C:\Users\admin\AppData\Local\Android\android-sdk\platform-tools\adb.exe devices
> info: [debug] 0 device(s) connected
> info: [debug] Could not find devices, restarting adb server...
> info: [debug] executing cmd: C:\Users\admin\AppData\Local\Android\android-sdk\platform-tools\adb.exe kill-server
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: C:\Users\admin\AppData\Local\Android\android-sdk\platform-tools\adb.exe devices
> info: [debug] 0 device(s) connected
> info: [debug] Could not find devices, restarting adb server...
> info: [debug] executing cmd: C:\Users\admin\AppData\Local\Android\android-sdk\platform-tools\adb.exe kill-server
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: C:\Users\admin\AppData\Local\Android\android-sdk\platform-tools\adb.exe devices
> info: [debug] 1 device(s) connected
> info: Found device IFS8QOZ5O769MNMZ
> info: [debug] Setting device id to IFS8QOZ5O769MNMZ
> info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
> info: [debug] executing cmd: C:\Users\admin\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s IFS8QOZ5O769MNMZ wait-for-device
> info: [debug] executing cmd: C:\Users\admin\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s IFS8QOZ5O769MNMZ shell "echo 'ready'"
> info: [debug] Starting logcat capture
> info: [debug] Pushing unlock helper app to device...
> info: [debug] executing cmd: C:\Users\admin\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s IFS8QOZ5O769MNMZ install "C:\Program Files (x86)\Appium\node_modules\appium\build\unlock_apk\unlock_apk-debug.apk"
> info: [debug] executing cmd: C:\Users\admin\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s IFS8QOZ5O769MNMZ shell "dumpsys window"
> info: Unlocking screen
> info: [debug] Screen is locked, trying to unlock
> info: [debug] Getting device API level
> info: [debug] executing cmd: C:\Users\admin\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s IFS8QOZ5O769MNMZ shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 21
> info: [debug] executing cmd: C:\Users\admin\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s IFS8QOZ5O769MNMZ shell "am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n io.appium.unlock/.Unlock"
> info: [debug] executing cmd: C:\Users\admin\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s IFS8QOZ5O769MNMZ shell "dumpsys window"
> info: [debug] Screen is locked, trying to unlock
> info: [debug] Getting device API level
> info: [debug] executing cmd: C:\Users\admin\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s IFS8QOZ5O769MNMZ shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 21
> info: [debug] executing cmd: C:\Users\admin\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s IFS8QOZ5O769MNMZ shell "am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n io.appium.unlock/.Unlock"
> info: [debug] executing cmd: C:\Users\admin\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s IFS8QOZ5O769MNMZ shell "dumpsys window"
> info: [debug] Screen is locked, trying to unlock
> info: [debug] Getting device API level
> info: [debug] executing cmd: C:\Users\admin\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s IFS8QOZ5O769MNMZ shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 21
> info: [debug] executing cmd: C:\Users\admin\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s IFS8QOZ5O769MNMZ shell "am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n io.appium.unlock/.Unlock"
> info: [debug] executing cmd: C:\Users\admin\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s IFS8QOZ5O769MNMZ shell "dumpsys window"
> info: [debug] Screen is unlocked, continuing
> info: [debug] Forwarding system:4724 to device:4724
> info: [debug] executing cmd: C:\Users\admin\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s IFS8QOZ5O769MNMZ forward tcp:4724 tcp:4724
> info: [debug] Pushing appium bootstrap to device...
> info: [debug] executing cmd: C:\Users\admin\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s IFS8QOZ5O769MNMZ push "C:\\Program Files (x86)\\Appium\\node_modules\\appium\\build\\android_bootstrap\\AppiumBootstrap.jar" /data/local/tmp/
> info: Starting App
> info: [debug] Attempting to kill all 'uiautomator' processes
> info: [debug] Getting all processes with 'uiautomator'
> info: [debug] executing cmd: C:\Users\admin\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s IFS8QOZ5O769MNMZ shell "ps 'uiautomator'"
> info: [debug] No matching processes found
> info: [debug] Running bootstrap
> info: [debug] spawning: C:\Users\admin\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s IFS8QOZ5O769MNMZ shell uiautomator runtest AppiumBootstrap.jar -c io.appium.android.bootstrap.Bootstrap -e pkg com.android.chrome -e disableAndroidWatchers false
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
> info: [debug] [UIAUTOMATOR STDOUT] io.appium.android.bootstrap.Bootstrap:
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 1
> info: [debug] [BOOTSTRAP] [debug] Socket opened on port 4724
> info: [debug] [BOOTSTRAP] [debug] Appium Socket Server Ready
> info: [debug] [BOOTSTRAP] [debug] Loading json...
> info: [debug] Pushing command to appium work queue: ["getDataDir",{}]
> info: [debug] [BOOTSTRAP] [debug] Registered crash watchers.
> info: [debug] [BOOTSTRAP] [debug] Client connected
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"getDataDir","params":{}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: getDataDir
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":"\/data\/local\/tmp"}
> info: [debug] dataDir set to: /data/local/tmp
> info: Chromedriver: Changed state to 'starting'
> info: Chromedriver: Set chromedriver binary as: C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\chromedriver\win\chromedriver.exe
> info: Chromedriver: Killing any old chromedrivers, running: FOR /F "usebackq tokens=5" %a in (`netstat -nao ^| findstr /R /C:"9515 "`) do (FOR /F "usebackq" %b in (`TASKLIST /FI "PID eq %a" ^| findstr /I chromedriver.exe`) do (IF NOT %b=="" TASKKILL /F /PID %a))
> info: Chromedriver: No old chromedrivers seemed to exist
> info: Chromedriver: Spawning chromedriver with: C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\chromedriver\win\chromedriver.exe --url-base=wd/hub --port=9515
> info: Chromedriver: [STDOUT] Starting ChromeDriver 2.18.343845 (73dd713ba7fbfb73cbb514e62641d8c96a94682a) on port 9515
> Only local connections are allowed.
> info: JSONWP Proxy: Proxying [GET /status] to [GET http://127.0.0.1:9515/wd/hub/status] with no body
> info: JSONWP Proxy: Got response with status 200: {"sessionId":"","status":0,"value":{"build":{"version":"alpha"},"os":{"arch":"x86_64","name":"Windows NT","version":"10.0"}}}
> info: JSONWP Proxy: Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.chrome","androidDeviceSerial":"IFS8QOZ5O769MNMZ"}}}
> info: [debug] [BOOTSTRAP] [debug] Emitting system alert message
> info: [debug] Emitting alert message...
> info: JSONWP Proxy: Got response with status 200: {"sessionId":"041f686c0232147b1318877ceaca44ac","status":33,"value":{"message":"session not created exception\nfrom unknown error: Runtime.executionContextCreated has invalid 'context': {\"auxData\":{...
> info: JSONWP Proxy: Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.chrome","androidDeviceSerial":"IFS8QOZ5O769MNMZ"}}}
> info: JSONWP Proxy: Got response with status 200: {"sessionId":"4ed49b7eb92047420a342b311c146ee8","status":33,"value":{"message":"session not created exception\nfrom unknown error: Runtime.executionContextCreated has invalid 'context': {\"auxData\":{...
> info: JSONWP Proxy: Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.chrome","androidDeviceSerial":"IFS8QOZ5O769MNMZ"}}}
> info: JSONWP Proxy: Got response with status 200: {"sessionId":"8574d0876f79bb199c37230e5006d816","status":33,"value":{"message":"session not created exception\nfrom unknown error: Runtime.executionContextCreated has invalid 'context': {\"auxData\":{...
> info: JSONWP Proxy: Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.chrome","androidDeviceSerial":"IFS8QOZ5O769MNMZ"}}}
> info: JSONWP Proxy: Got response with status 200: {"sessionId":"ee35249646aaa64502d22e4ebcda3bc3","status":33,"value":{"message":"session not created exception\nfrom unknown error: Runtime.executionContextCreated has invalid 'context': {\"auxData\":{...
> info: Chromedriver: Changed state to 'stopped'
> error: Chromedriver: Chromedriver exited unexpectedly with code null, signal SIGTERM
> error: Chromedriver: Error: A new session could not be created. (Original error: session not created exception
> from unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"11107.1","isDefault":true},"id":1,"name":"","origin":"://"}
>   (Session info: chrome=58.0.3029.83)
>   (Driver info: chromedriver=2.18.343845 (73dd713ba7fbfb73cbb514e62641d8c96a94682a),platform=Windows NT 10.0 x86_64))
>     at JWProxy.command$ (lib/proxy.js:149:15)
>     at tryCatch (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\babel-runtime\regenerator\runtime.js:67:40)
>     at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\babel-runtime\regenerator\runtime.js:294:22)
>     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\babel-runtime\regenerator\runtime.js:100:21)
>     at GeneratorFunctionPrototype.invoke (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\babel-runtime\regenerator\runtime.js:136:37)
>     at GeneratorFunctionPrototype.b (domain.js:183:18)
>     at lib$es6$promise$$internal$$tryCatch (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\es6-promise\dist\es6-promise.js:331:16)
>     at lib$es6$promise$$internal$$invokeCallback (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\es6-promise\dist\es6-promise.js:343:17)
>     at lib$es6$promise$$internal$$publish (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\es6-promise\dist\es6-promise.js:314:11)
>     at Object.lib$es6$promise$asap$$flush [as _onImmediate] (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\es6-promise\dist\es6-promise.js:125:9)
>     at processImmediate [as _immediateCallback] (timers.js:330:15)
>  { [Error: A new session could not be created. (Original error: session not created exception
> from unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"11107.1","isDefault":true},"id":1,"name":"","origin":"://"}
>   (Session info: chrome=58.0.3029.83)
>   (Driver info: chromedriver=2.18.343845 (73dd713ba7fbfb73cbb514e62641d8c96a94682a),platform=Windows NT 10.0 x86_64))]
>   status: 33,
>   value: { message: 'session not created exception\nfrom unknown error: Runtime.executionContextCreated has invalid \'context\': {"auxData":{"frameId":"11107.1","isDefault":true},"id":1,"name":"","origin":"://"}\n  (Session info: chrome=58.0.3029.83)\n  (Driver info: chromedriver=2.18.343845 (73dd713ba7fbfb73cbb514e62641d8c96a94682a),platform=Windows NT 10.0 x86_64)' },
>   httpCode: 200 }
> info: Chromedriver stopped unexpectedly on us, shutting down then calling back up with the on-die callback
> error: Failed to start an Appium session, err was: Error: A new session could not be created. (Original error: session not created exception
> from unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"11107.1","isDefault":true},"id":1,"name":"","origin":"://"}
>   (Session info: chrome=58.0.3029.83)
>   (Driver info: chromedriver=2.18.343845 (73dd713ba7fbfb73cbb514e62641d8c96a94682a),platform=Windows NT 10.0 x86_64))
> info: [debug] Cleaning up appium session
> info: [debug] Error: A new session could not be created. (Original error: session not created exception
> from unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"11107.1","isDefault":true},"id":1,"name":"","origin":"://"}
>   (Session info: chrome=58.0.3029.83)
>   (Driver info: chromedriver=2.18.343845 (73dd713ba7fbfb73cbb514e62641d8c96a94682a),platform=Windows NT 10.0 x86_64))
>     at JWProxy.command$ (lib/proxy.js:149:15)
>     at tryCatch (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\babel-runtime\regenerator\runtime.js:67:40)
>     at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\babel-runtime\regenerator\runtime.js:294:22)
>     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\babel-runtime\regenerator\runtime.js:100:21)
>     at GeneratorFunctionPrototype.invoke (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\babel-runtime\regenerator\runtime.js:136:37)
>     at GeneratorFunctionPrototype.b (domain.js:183:18)
>     at lib$es6$promise$$internal$$tryCatch (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\es6-promise\dist\es6-promise.js:331:16)
>     at lib$es6$promise$$internal$$invokeCallback (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\es6-promise\dist\es6-promise.js:343:17)
>     at lib$es6$promise$$internal$$publish (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\es6-promise\dist\es6-promise.js:314:11)
>     at Object.lib$es6$promise$asap$$flush [as _onImmediate] (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\es6-promise\dist\es6-promise.js:125:9)
>     at processImmediate [as _immediateCallback] (timers.js:330:15)
> info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: A new session could not be created. (Original error: session not created exception\nfrom unknown error: Runtime.executionContextCreated has invalid 'context': {\"auxData\":{\"frameId\":\"11107.1\",\"isDefault\":true},\"id\":1,\"name\":\"\",\"origin\":\"://\"}\n  (Session info: chrome=58.0.3029.83)\n  (Driver info: chromedriver=2.18.343845 (73dd713ba7fbfb73cbb514e62641d8c96a94682a),platform=Windows NT 10.0 x86_64)))","status":33,"value":{"message":"session not created exception\nfrom unknown error: Runtime.executionContextCreated has invalid 'context': {\"auxData\":{\"frameId\":\"11107.1\",\"isDefault\":true},\"id\":1,\"name\":\"\",\"origin\":\"://\"}\n  (Session info: chrome=58.0.3029.83)\n  (Driver info: chromedriver=2.18.343845 (73dd713ba7fbfb73cbb514e62641d8c96a94682a),platform=Windows NT 10.0 x86_64)"},"httpCode":200,"origValue":"A new session could not be created. (Original error: session not created exception\nfrom unknown error: Runtime.executionContextCreated has invalid 'context': {\"auxData\":{\"frameId\":\"11107.1\",\"isDefault\":true},\"id\":1,\"name\":\"\",\"origin\":\"://\"}\n  (Session info: chrome=58.0.3029.83)\n  (Driver info: chromedriver=2.18.343845 (73dd713ba7fbfb73cbb514e62641d8c96a94682a),platform=Windows NT 10.0 x86_64))"},"sessionId":null}
> info: <-- POST /wd/hub/session 500 74371.155 ms - 1369 
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"shutdown"}
> info: [debug] [BOOTSTRAP] [debug] Got command of type SHUTDOWN
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":"OK, shutting down"}
> info: [debug] [UIAUTOMATOR STDOUT] [CDS]close[4724]
> info: [debug] [BOOTSTRAP] [debug] Closed client connection
> info: [debug] Sent shutdown command, waiting for UiAutomator to stop...
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=.
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 0
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
> info: [debug] [UIAUTOMATOR STDOUT] Test results for WatcherResultPrinter=.
> info: [debug] [UIAUTOMATOR STDOUT] Time: 41.509
> info: [debug] [UIAUTOMATOR STDOUT] OK (1 test)
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: -1
> info: [debug] UiAutomator shut down normally
> info: [debug] executing cmd: C:\Users\admin\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s IFS8QOZ5O769MNMZ shell "am force-stop com.android.chrome"
> info: [debug] Stopping logcat capture
> info: [debug] Logcat terminated with code null, signal SIGTERM
> info: [debug] Cleaning up appium session

**Comment by HarishCS** [comment]
Forgot to mention I am using Eclipse neon, kindly help me in this regard

**Comment by HarishCS** [comment]
Few more details:
Chrome for Android Version is 58.0.3
Mobile Android Version 5.0

**Comment by mykola-mokhnach** [comment]
1. Appium 1.4 is outdated and is not supported anymore. Use 1.6.4 instead.
2. Do not provide appPackage and appActivity capabilities if browserName is set

**Comment by HarishCS** [comment]
Awesome thanks a lot upgraded Appium to 1.6.4 issue got resolved thanks a ton
