### ISSUE TITLE
[debug] [XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: Unable to start iproxy. Is it installed?

### ISSUE THREAD

**Issue by Akshay64** [appium/appium#8346]
macs-iMac-2:~ QA$ appium

[Appium] Welcome to Appium v1.6.4 (REV 3d622f85544cc4a72a66989c2c85849d8b054295)

[Appium] Appium REST http interface listener started on 0.0.0.0:4723

[HTTP] --> POST /wd/hub/session {"capabilities":[{"desiredCapabilities":{"app":"/Users/QA/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/IntegrationApp.app","appiumVersion":"1.6.4","platformVersion":"10.1.1","automationName":"XCuiTest","udid":"d47b5604615996af4d711a68ee4f4752b2e9618b","platformName":"iOS","startIWDP":true,"deviceName":"iPhone"}},{"requiredCapabilities":{}}],"desiredCapabilities":{"app":"/Users/QA/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/IntegrationApp.app","appiumVersion":"1.6.4","platformVersion":"10.1.1","automationName":"XCuiTest","udid":"d47b5604615996af4d711a68ee4f4752b2e9618b","platformName":"iOS","startIWDP":true,"deviceName":"iPhone"},"requiredCapabilities":{}}

[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/QA/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/IntegrationApp.app","appiumVersion":"1.6.4","platformVersion":"10.1.1","automationName":"XCuiTest","udid":"d47b5604615996af4d711a68ee4f4752b2e9618b","platformName":"iOS","startIWDP":true,"deviceName":"iPhone"},{},[{"desiredCapabilities":{"app":"/Users/QA/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/IntegrationApp.app","appiumVersion":"1.6.4","platformVersion":"10.1.1","automationName":"XCuiTest","udid":"d47b5604615996af4d711a68ee4f4752b2e9618b","platformName":"iOS","startIWDP":true,"deviceName":"iPhone"}},{"requiredCapabilities":{}}],null,null]

[debug] [BaseDriver] Event 'newSessionRequested' logged at 1493395699203 (21:38:19 GMT+0530 (IST))

[Appium] Creating new XCUITestDriver (v2.27.2) session

[Appium] Capabilities:

[Appium]   app: '/Users/QA/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/IntegrationApp.app'

[Appium]   appiumVersion: '1.6.4'

[Appium]   platformVersion: '10.1.1'

[Appium]   automationName: 'XCuiTest'

[Appium]   udid: 'd47b5604615996af4d711a68ee4f4752b2e9618b'

[Appium]   platformName: 'iOS'

[Appium]   startIWDP: true

[Appium]   deviceName: 'iPhone'

[debug] [XCUITest] XCUITestDriver version: 2.27.2

[BaseDriver] The following capabilities were provided, but are not recognized by appium: appiumVersion.

[BaseDriver] Session created with session id: e2c0ace7-72af-4daa-ac51-049216b3c8e1

[debug] [XCUITest] Xcode version set to '8.2.1' (tools v8.3.2.0.1.1492020469)

[debug] [XCUITest] iOS SDK Version set to '10.2'

[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1493395701183 (21:38:21 GMT+0530 (IST))

[debug] [XCUITest] Available devices: d47b5604615996af4d711a68ee4f4752b2e9618b

[debug] [XCUITest] Creating iDevice object with udid 'd47b5604615996af4d711a68ee4f4752b2e9618b'

[XCUITest] Determining device to run tests on: udid: 'd47b5604615996af4d711a68ee4f4752b2e9618b', real device: true

[BaseDriver] Using local app '/Users/QA/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/IntegrationApp.app'

[debug] [BaseDriver] Event 'appConfigured' logged at 1493395702385 (21:38:22 GMT+0530 (IST))

[debug] [XCUITest] Checking whether app '/Users/QA/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/IntegrationApp.app' is actually present on file system

[debug] [XCUITest] App is present

[debug] [iOS] Getting bundle ID from app '/Users/QA/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/IntegrationApp.app': 'com.facebook.IntegrationAApps'

[debug] [BaseDriver] Event 'resetStarted' logged at 1493395702408 (21:38:22 GMT+0530 (IST))

[debug] [XCUITest] Reset: running ios real device reset flow

[debug] [BaseDriver] Event 'resetComplete' logged at 1493395702410 (21:38:22 GMT+0530 (IST))

[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog

[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'

[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1493395702689 (21:38:22 GMT+0530 (IST))

[XCUITest] Setting up real device

[debug] [XCUITest] Installing '/Users/QA/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/IntegrationApp.app' on device with UUID 'd47b5604615996af4d711a68ee4f4752b2e9618b'...

[debug] [XCUITest] The app has been installed successfully.

[debug] [BaseDriver] Event 'appInstalled' logged at 1493395706229 (21:38:26 GMT+0530 (IST))

[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1493395706232 (21:38:26 GMT+0530 (IST))

[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'

[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'

[XCUITest] Launching WebDriverAgent on the device

[debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'

[debug] [XCUITest] Killing hanging processes

[debug] [XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=d47b5604615996af4d711a68ee4f4752b2e9618b -configuration Debug IPHONEOS_DEPLOYMENT_TARGET=10.1' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'

[debug] [XCUITest] Output from xcodebuild will not be logged

[debug] [XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB

[XCUITest] Error starting iproxy: 'Command 'iproxy' not found. Is it installed?'

[debug] [BaseDriver] Event 'wdaStartFailed' logged at 1493395706480 (21:38:26 GMT+0530 (IST))

[debug] [XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: Unable to start iproxy. Is it installed?

[debug] [XCUITest] Quitting and uninstalling WebDriverAgent, then retrying

[XCUITest] Shutting down sub-processes

[XCUITest] Shutting down iproxy process (pid undefined)

[debug] [XCUITest] Removing WDA application from device

[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1493395716908 (21:38:36 GMT+0530 (IST))

[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'

[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'

[XCUITest] Launching WebDriverAgent on the device

[debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'

[debug] [XCUITest] Killing hanging processes

[debug] [XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=d47b5604615996af4d711a68ee4f4752b2e9618b -configuration Debug IPHONEOS_DEPLOYMENT_TARGET=10.1' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'

[debug] [XCUITest] Output from xcodebuild will not be logged

[debug] [XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB

[XCUITest] Error starting iproxy: 'Command 'iproxy' not found. Is it installed?'

[debug] [BaseDriver] Event 'wdaStartFailed' logged at 1493395717019 (21:38:37 GMT+0530 (IST))

[debug] [XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: Unable to start iproxy. Is it installed?

[debug] [XCUITest] Quitting and uninstalling WebDriverAgent, then retrying

[XCUITest] Shutting down sub-processes

[XCUITest] Shutting down iproxy process (pid undefined)

[debug] [XCUITest] Removing WDA application from device

[XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: Unable to start iproxy. Is it installed?

    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:374:15)

    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)

    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)

    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)

    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)

    at process._tickCallback (internal/process/next_tick.js:109:7)

 Error: Unable to launch WebDriverAgent because of xcodebuild failure: Unable to start iproxy. Is it installed?

    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:374:15)

    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)

    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)

    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)

    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)

    at process._tickCallback (internal/process/next_tick.js:109:7)

[debug] [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.

[debug] [iOSLog] Stopping iOS log capture

[MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: Unable to start iproxy. Is it installed?

    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:374:15)

    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)

    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)

    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)

    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)

    at process._tickCallback (internal/process/next_tick.js:109:7)

[HTTP] <-- POST /wd/hub/session 500 28146 ms - 240 

[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/QA/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/IntegrationApp.app","appiumVersion":"1.6.4","platformVersion":"10.1.1","automationName":"XCuiTest","udid":"d47b5604615996af4d711a68ee4f4752b2e9618b","platformName":"iOS","startIWDP":true,"deviceName":"iPhone"},"requiredCapabilities":{}}

[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/QA/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/IntegrationApp.app","appiumVersion":"1.6.4","platformVersion":"10.1.1","automationName":"XCuiTest","udid":"d47b5604615996af4d711a68ee4f4752b2e9618b","platformName":"iOS","startIWDP":true,"deviceName":"iPhone"},{},null,null,null]

[debug] [BaseDriver] Event 'newSessionRequested' logged at 1493395727396 (21:38:47 GMT+0530 (IST))

[Appium] Creating new XCUITestDriver (v2.27.2) session

[Appium] Capabilities:

[Appium]   app: '/Users/QA/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/IntegrationApp.app'

[Appium]   appiumVersion: '1.6.4'

[Appium]   platformVersion: '10.1.1'

[Appium]   automationName: 'XCuiTest'

[Appium]   udid: 'd47b5604615996af4d711a68ee4f4752b2e9618b'

[Appium]   platformName: 'iOS'

[Appium]   startIWDP: true

[Appium]   deviceName: 'iPhone'

[debug] [XCUITest] XCUITestDriver version: 2.27.2

[BaseDriver] The following capabilities were provided, but are not recognized by appium: appiumVersion.

[BaseDriver] Session created with session id: 7e7d3eab-2b57-44a9-a7b4-fd2e57aa6823

[debug] [XCUITest] Xcode version set to '8.2.1' (tools v8.3.2.0.1.1492020469)

[debug] [XCUITest] iOS SDK Version set to '10.2'

[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1493395727444 (21:38:47 GMT+0530 (IST))

[debug] [XCUITest] Available devices: d47b5604615996af4d711a68ee4f4752b2e9618b

[debug] [XCUITest] Creating iDevice object with udid 'd47b5604615996af4d711a68ee4f4752b2e9618b'

[XCUITest] Determining device to run tests on: udid: 'd47b5604615996af4d711a68ee4f4752b2e9618b', real device: true

[BaseDriver] Using local app '/Users/QA/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/IntegrationApp.app'

[debug] [BaseDriver] Event 'appConfigured' logged at 1493395727569 (21:38:47 GMT+0530 (IST))

[debug] [XCUITest] Checking whether app '/Users/QA/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/IntegrationApp.app' is actually present on file system

[debug] [XCUITest] App is present

[debug] [iOS] Getting bundle ID from app '/Users/QA/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/IntegrationApp.app': 'com.facebook.IntegrationAApps'

[debug] [BaseDriver] Event 'resetStarted' logged at 1493395727571 (21:38:47 GMT+0530 (IST))

[debug] [XCUITest] Reset: running ios real device reset flow

[debug] [BaseDriver] Event 'resetComplete' logged at 1493395727572 (21:38:47 GMT+0530 (IST))

[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog

[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'

[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1493395727673 (21:38:47 GMT+0530 (IST))

[XCUITest] Setting up real device

[debug] [XCUITest] Reset requested. Removing app with id 'com.facebook.IntegrationAApps' from the device

[debug] [XCUITest] Installing '/Users/QA/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/IntegrationApp.app' on device with UUID 'd47b5604615996af4d711a68ee4f4752b2e9618b'...

[debug] [XCUITest] The app has been installed successfully.

[debug] [BaseDriver] Event 'appInstalled' logged at 1493395731675 (21:38:51 GMT+0530 (IST))

[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1493395731682 (21:38:51 GMT+0530 (IST))

[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'

[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'

[XCUITest] Launching WebDriverAgent on the device

[debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'

[debug] [XCUITest] Killing hanging processes

[debug] [XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=d47b5604615996af4d711a68ee4f4752b2e9618b -configuration Debug IPHONEOS_DEPLOYMENT_TARGET=10.1' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'

[debug] [XCUITest] Output from xcodebuild will not be logged

[debug] [XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB

[XCUITest] Error starting iproxy: 'Command 'iproxy' not found. Is it installed?'

[debug] [BaseDriver] Event 'wdaStartFailed' logged at 1493395731854 (21:38:51 GMT+0530 (IST))

[debug] [XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: Unable to start iproxy. Is it installed?

[debug] [XCUITest] Quitting and uninstalling WebDriverAgent, then retrying

[XCUITest] Shutting down sub-processes

[XCUITest] Shutting down iproxy process (pid undefined)

[debug] [XCUITest] Removing WDA application from device

[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1493395742231 (21:39:02 GMT+0530 (IST))

[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'

[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'

[XCUITest] Launching WebDriverAgent on the device

[debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'

[debug] [XCUITest] Killing hanging processes

[debug] [XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=d47b5604615996af4d711a68ee4f4752b2e9618b -configuration Debug IPHONEOS_DEPLOYMENT_TARGET=10.1' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'

[debug] [XCUITest] Output from xcodebuild will not be logged

[debug] [XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB

[XCUITest] Error starting iproxy: 'Command 'iproxy' not found. Is it installed?'

[debug] [BaseDriver] Event 'wdaStartFailed' logged at 1493395742348 (21:39:02 GMT+0530 (IST))

[debug] [XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: Unable to start iproxy. Is it installed?

[debug] [XCUITest] Quitting and uninstalling WebDriverAgent, then retrying

[XCUITest] Shutting down sub-processes

[XCUITest] Shutting down iproxy process (pid undefined)

[debug] [XCUITest] Removing WDA application from device

[XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: Unable to start iproxy. Is it installed?

    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:374:15)

    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)

    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)

    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)

    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)

    at process._tickCallback (internal/process/next_tick.js:109:7)

 Error: Unable to launch WebDriverAgent because of xcodebuild failure: Unable to start iproxy. Is it installed?

    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:374:15)

    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)

    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)

    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)

    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)

    at process._tickCallback (internal/process/next_tick.js:109:7)

[debug] [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.

[debug] [iOSLog] Stopping iOS log capture

[MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: Unable to start iproxy. Is it installed?

    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:374:15)

    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)

    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)

    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)

    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)

    at process._tickCallback (internal/process/next_tick.js:109:7)

[HTTP] <-- POST /wd/hub/session 500 25224 ms - 240 

[HTTP] --> POST /wd/hub/session {"capabilities":[{"desiredCapabilities":{"app":"/Users/QA/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/IntegrationApp.app","appiumVersion":"1.6.4","platformVersion":"10.1.1","automationName":"XCuiTest","udid":"d47b5604615996af4d711a68ee4f4752b2e9618b","platformName":"iOS","startIWDP":true,"deviceName":"iPhone"}},{"requiredCapabilities":{}}]}

[debug] [MJSONWP] Bad parameters: BadParametersError: Parameters were incorrect. We wanted {"required":["desiredCapabilities"],"optional":["requiredCapabilities","capabilities","sessionId","id"]} and you sent ["capabilities"]

[HTTP] <-- POST /wd/hub/session 400 2 ms - 171

**Comment by Akshay64** [comment]
Anybody please help.

**Comment by imurchie** [comment]
Do you have `iproxy` installed?

**Comment by Akshay64** [comment]
Dont know about this much..how to install it?

**Comment by imurchie** [comment]
https://github.com/appium/appium/blob/master/docs/en/appium-setup/real-devices-ios.md#required-software

**Comment by Akshay64** [comment]
Yes i have followed this steps. Is there any way to check whethere iproxy is properly installed or not? One more observation is that when I build the webdriver agent through terminal (using command mentioned in setup doc) it successfully installs webdriver agent on the device.

**Comment by imurchie** [comment]
The `iproxy` is used to communicate with WebDriverAgent on the device once it is installed.

If WebDriverAgent is running on the device you can try 
```
$ iproxy 8100 8100 <device udid>
```
And it ought to connect.

**Comment by buildsmobiuso** [comment]
Ok. will do that. One more question can i signed xcodebuild for the webdriver agent using free apple developer certificate [I am using the free one] or do i need to upgrade it to the paid one?

**Comment by Akshay64** [comment]
Ok thanks. I will check it. One quick question, do i need paid Apple ID account to sign the webdriver agent? I am using the free account.

**Comment by imurchie** [comment]
Free account is fine. You might run into problems generating a provisioning profile/certificate for the default bundle identifier. 

The information is here: https://github.com/appium/appium/blob/master/docs/en/appium-setup/real-devices-ios.md

**Comment by siggerzz** [comment]
I had this problem and spent weeks trying to get it working. I ended up just using a different Macbook at the office and it worked first time. Really interested to know what the solution is though!

**Comment by Akshay64** [comment]
Yeah..finally got solution for this..you need to install libimobiledevice package dependencies first.. then it will work :) 
@imurchie thanks for the support !

**Comment by siggerzz** [comment]
@Akshay64 Damn it, I must've re-installed Appium + dependencies like 5 times, ha. Ah well! Glad you got it sorted!

**Comment by menyp** [comment]
I am facing this issue on the appium latest version on one macbook while on the other it works fine.

I have tried to reinstall the libimobiledevice however the issue remains.

Any help will be most appreciated!!!

**Comment by imurchie** [comment]
@menyp How are you starting Appium? What resources does it have? In the same shell can you start iproxy manually?

**Comment by menyp** [comment]
@imurchie  I am starting the Appium via terminal or via appium desktop app & the bug remains.
- Can you PLS elaborate what is the iproxy & how do I start it manually? 
- What do you mean by "What resources does it have"?

Thanks for the help!

**Comment by imurchie** [comment]
@menyp I mean does it have access to the PATH environment? Can it run things that are on the PATH? 

iproxy is a program that comes with libimobiledevice. It needs to be runnable from within the Appium server. If you run Appium from the terminal, you should be able to type `iproxy` and get something printed like `usage: iproxy LOCAL_TCP_PORT DEVICE_TCP_PORT [UDID]`.

**Comment by menyp** [comment]
@imurchie Seems you are right, when I run the iproxy command in the terminal I get "MTLIT1031041:~ meny.peled$ iproxy-bash: iproxy: command not found.

While when I run this command on the mac that the tests run without any issue I get the usage: iproxy LOCAL_TCP_PORT DEVICE_TCP_PORT [UDID] as mentioned.

Can you point how to fix it?

**Comment by imurchie** [comment]
Is there any output when you install `libimobiledevice`?

**Comment by menyp** [comment]
MTLIT1031041:~ meny.peled$ brew install libimobiledevice --HEAD
==> Cloning https://git.libimobiledevice.org/libimobiledevice.git
Updating /Users/meny.peled/Library/Caches/Homebrew/libimobiledevice--git
==> Checking out branch master
==> ./autogen.sh
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/libimobiledevice/HEAD-5a85432_2 --without-cython
==> make install
🍺  /usr/local/Cellar/libimobiledevice/HEAD-5a85432_2: 67 files, 1012.3KB, built in 52 seconds
MTLIT1031041:~ meny.peled$

**Comment by imurchie** [comment]
And then it is still not available? This seems like a brew issue. Is the path to Homebrew-installed applications on the PATH on the machine?

**Comment by menyp** [comment]
What do you mean?
If you mean the .bash_profile then this is the content:

[ -f /usr/local/homebrew-now/etc/bashrc ] && source /usr/local/homebrew-now/etc/bashrc
export PATH=$PATH:/usr/local/bin
export PATH=$PATH:/Applications/apache-maven-3.5.0/bin

**Comment by menyp** [comment]
I think I just fixed it.
Once I ran brew doctor I saw the below warnings.
So after I link it the iproxy command shows the "iproxy LOCAL_TCP_PORT DEVICE_TCP_PORT [UDID] "as mentioned.
Now I will check if the initial error "Unable to start iproxy. Is it installed?" remains when I run the code on real device.
==============================================

Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  libplist
  libtasn1
  libusb
  libzip
  usbmuxd

**Comment by menyp** [comment]
Yes, the code runs smoothly now without the iporxy error.

@imurchie Thanks you very much for the help & the patience!

Once you figure that something is wrong with the brew I ran the brew doctor & fixing it.

Cheers!

**Comment by imurchie** [comment]
Excellent! I'm glad it's working.
