### ISSUE TITLE
Appium and XCodeBuild bombing after upgrading from El Capitan/XCode 8.2.1 to Sierra/XCode 8.3.2

### ISSUE THREAD

**Issue by kirksl** [appium/appium#8347]
## The problem

My real devices recently updated to iOS 10.3.  To support 10.3 I had to update my Mac/XCode from El Capitan/XCode 8.2.1 to Sierra/XCode 8.3.2.

Before upgrading my Appium 1.6.4 environment was functioning perfectly with the ability to build and sign WebDriverAgent, launch, inspect and test apps on my real connected devices.  After upgrading to Sierra Appium and xcodebuild are bombing with the errors(REAL_DEVICE_UDID refers to a real udid of mine):

xcodebuild
error: unable to find a destination matching the provided destination specifier: { id:REAL_DEVICE_UDID }
unsupported device specifier option.  the device "my mac" does not support the following options: id

appium
[mjsonwp] encountered internal error running command: error: unknown device or simulator udid: 'REAL_DEVICE_UDID' at XCUITestDriver.determineDevice$

screenshot of errors
http://2.1m.yt/zPMsyeV.png

I initially thought maybe Sierra wasn't detecting my real device's over USB, but I am seeing them in System Information - Hardware - USB (or) by running system_profiler SPUSBDataType.

Combing through others issues i'm not finding a resolution.  Any ideas???

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4 (XCUITestDriver v2.27.2)
* Last Appium version that did not exhibit the issue (if applicable): 1.6.4 on El Capitan/XCode 8.2.1
* Desktop OS/version used to run Appium: OSX Sierra
* Node.js version (unless using Appium.app|exe): Appium Desktop 1.6.4
* Mobile platform/version under test: iPod iOS 10.3
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium Desktop 1.6.4

**Comment by mykola-mokhnach** [comment]
Have you tried to build WDA manually from Xcode?

**Comment by kirksl** [comment]
I have and it succeeds (after going through all of the below of course).  One thing interesting going on here.  No apps (photos, itunes, xcode) are seeing my devices over USB, only System Information and system_profiler.

goto appium-xcuitest-driver/webdriveragent folder
brew install carthage
brew link carthage
bash Scripts/bootstrap.sh -d
mkdir resources
cd resources
mkdir webdriveragent.bundle
build webdriveragent.xcodeproj in xcode
succeeds

**Comment by mykola-mokhnach** [comment]
you can only build or build and install WDA though Xcode? If Xcode does not see the device in UI mode then xcodebuild will not see it as well.

**Comment by imurchie** [comment]
Upgrade to the _latest_ Xcode. Xcode 8.2 technically does not know anything about iOS 10.3

**Comment by kirksl** [comment]
Thanks for the help guys.  @imurchie I tried the latest 8.3.x XCode and still couldn't see the device in XCode.  I think my Mac has been bit by this issue.
https://forums.developer.apple.com/thread/65232

Rolled back to El Capitan and my environment is working again.  I saved a snapshot of Sierra if any other suggestions might resolve matters.
