### ISSUE TITLE
Running appium automation script from command line

### ISSUE THREAD

**Issue by sanjay1984** [appium/appium#8350]
Hi All,

I am trying to run my appium script from command line.(Not maven project)

My structure of the project is like this:
Under One package I have one class DriverInitial where two annotations are their @BeforeClass and @AfterClass

and in another package, I have defined all the objects using @AndroidFindBy in one class and I am making the object of this class in main class where only 1 annotation @Test is there.

When I am running from eclipse it's working but from the command line it's not working I am getting this:

[TestNG] Running:
C:\Users\sanjay\workspace\automation\testng.xml

Apr 29, 2017 10:48:07 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS

===============================================
Suite
Total tests run: 1, Failures: 1, Skips: 0
===============================================

## Environment

* Appium version -  Appium v1.6.5-beta
* Last Appium version that did not exhibit the issue (if applicable):NO
* Desktop OS/version used to run Appium: Windows 10 Pro 64 bit
* Node.js version (unless using Appium.app|exe): v6.10.1
* Mobile platform/version under test: Android 7.0
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI

**TestNG report** 

Boutiqaat java.lang.NoSuchMethodError: org.openqa.selenium.support.ui.FluentWait.until(Lcom/google/common/base/Function;)Ljava/lang/Object;
	at io.appium.java_client.pagefactory.AppiumElementLocator.waitFor(AppiumElementLocator.java:91)
	at io.appium.java_client.pagefactory.AppiumElementLocator.findElement(AppiumElementLocator.java:112)
	at io.appium.java_client.pagefactory.interceptors.InterceptorOfASingleElement.intercept(InterceptorOfASingleElement.java:61)
	at io.appium.java_client.android.AndroidElement$$EnhancerByCGLIB$$c0b591f0.click(<generated>)
	at automation1.Checkout2.homeview(Checkout2.java:59)
	at Final.FinalTest.Boutiqaat(FinalTest.java:16)
... Removed 23 stack frames
l.

In appium logs I am not getting any error while running I am getting 200.

I tried so many workarounds but no luck.

Regards,
Sanjay

**Comment by mykola-mokhnach** [comment]
Please report the issue to https://github.com/appium/java-client

It looks like you need to update google guava library in your pom file.
