### ISSUE TITLE
Run E2E tests on Android device from official Ionic Unit Testing Example

### ISSUE THREAD

**Issue by hadrien-toma** [appium/appium#8351]
## The problem
Doesn't reach to run E2E tests with Protractor and Appium on Android device from the official Ionic Unit Testing Example.

## Environment
* Appium version that exhibits the issue: **1.6.4**
* Desktop OS/version used to run Appium:
  * **Linux 3.19.0-32-generic ~14.04.1-Ubuntu SMP Thu Oct 22 09:41:40 UTC 2015 x86_64 GNU/Linux**
  * **DISTRIB_ID=LinuxMint**
  * **DISTRIB_RELEASE=17.3**
  * **DISTRIB_CODENAME=rosa**
  * **DISTRIB_DESCRIPTION="Linux Mint 17.3 Rosa"**
* Node.js version: **v7.9.0**
* NPM version: **4.2.0**
* Protractor version: **5.1.1**
* Ionic version: **2.2.3**
* Mobile platform/version under test: **Android 6.0**
* Real device or emulator/simulator: **Real device**
  * Model number: **K6000 Pro**
  * Android version: **6.0**
  * Kernel version: **3.18.19+ OUKITEL**
  * Manufacturer: **MediaTek**
  * idVendor: **0e8d**
* Appium CLI or Appium.app|exe: **Appium CLI**

## Link to Appium logs
[Here](https://gist.github.com/hadrien-toma/cdd531fe35fbf51e425648dbcee0bf05) is the GIST.

## Link to Protractor logs
[Here](https://gist.github.com/hadrien-toma/dad2ec7ed0ab26e286bed6b9d74b177f) is the GIST.

## Linked issues
I also opened an improvement suggestion, [here](https://github.com/driftyco/ionic-unit-testing-example/issues/30), concerning this feature in the [Ionic Unit Testing Example](https://github.com/driftyco/ionic-unit-testing-example).

#### Commands
```
git clone https://github.com/driftyco/ionic-unit-testing-example.git
cd ionic-unit-testing-example
npm install
```

#### Commands
```
ionic serve
npm run e2e
```

#### Result
```
> test-test@0.0.1 e2e /home/hadrien-toma/dev/ionic/ionic-unit-testing-example
> webdriver-manager update --standalone false --gecko false; protractor ./test-config/protractor.conf.js

[09:17:40] I/update - chromedriver: file exists /home/hadrien-toma/dev/ionic/ionic-unit-testing-example/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.29.zip
[09:17:40] I/update - chromedriver: unzipping chromedriver_2.29.zip
[09:17:40] I/update - chromedriver: setting permissions to 0755 for /home/hadrien-toma/dev/ionic/ionic-unit-testing-example/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.29
[09:17:40] I/update - chromedriver: chromedriver_2.29 up to date
(node:23209) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[09:17:41] I/launcher - Running 1 instances of WebDriver
[09:17:41] I/direct - Using ChromeDriver directly...
Spec started

  App

    default screen
      ✓ should have a title saying Page One

Executed 1 of 1 spec SUCCESS in 2 secs.
[09:17:45] I/launcher - 0 instance(s) of WebDriver still running
[09:17:45] I/launcher - chrome #01 passed
```

### 3. Check that the APK is successfully generated and working
```
ionic platform add android
ionic run android
```
All is working as expected on device.

#### Command:
```
appium-doctor --dev
```

#### Result
```
info AppiumDoctor Appium Doctor v.1.4.2
info AppiumDoctor ### Diagnostic starting ###
info AppiumDoctor  ✔ The Node.js binary was found at: /usr/bin/node
info AppiumDoctor  ✔ Node version is 7.9.0
info AppiumDoctor  ✔ ANDROID_HOME is set to: /usr/local/android/android-sdk-linux
info AppiumDoctor  ✔ JAVA_HOME is set to: /usr/local/java/jdk1.8.0_91
info AppiumDoctor  ✔ adb exists at: /usr/local/android/android-sdk-linux/platform-tools/adb
info AppiumDoctor  ✔ android exists at: /usr/local/android/android-sdk-linux/tools/android
info AppiumDoctor  ✔ emulator exists at: /usr/local/android/android-sdk-linux/tools/emulator
info AppiumDoctor  ✔ Bin directory of $JAVA_HOME is set
info AppiumDoctor  ✔ mvn was found at /usr/bin/mvn
info AppiumDoctor  ✔ ant was found at /usr/local/android/apache-ant-1.10.1/bin/ant
info AppiumDoctor  ✔ adb was found at /usr/bin/adb
info AppiumDoctor  ✔ android-16 was found at: /usr/local/android/android-sdk-linux/platforms/android-16
info AppiumDoctor  ✔ android-19 was found at: /usr/local/android/android-sdk-linux/platforms/android-19
info AppiumDoctor ### Diagnostic completed, no fix needed. ###
info AppiumDoctor 
info AppiumDoctor Everything looks good, bye!
info AppiumDoctor
```

#### Command:
```
appium-doctor --android
```

#### Result
```
appium-doctor --android
info AppiumDoctor Appium Doctor v.1.4.2
info AppiumDoctor ### Diagnostic starting ###
info AppiumDoctor  ✔ The Node.js binary was found at: /usr/bin/node
info AppiumDoctor  ✔ Node version is 7.9.0
info AppiumDoctor  ✔ ANDROID_HOME is set to: /usr/local/android/android-sdk-linux
info AppiumDoctor  ✔ JAVA_HOME is set to: /usr/local/java/jdk1.8.0_91
info AppiumDoctor  ✔ adb exists at: /usr/local/android/android-sdk-linux/platform-tools/adb
info AppiumDoctor  ✔ android exists at: /usr/local/android/android-sdk-linux/tools/android
info AppiumDoctor  ✔ emulator exists at: /usr/local/android/android-sdk-linux/tools/emulator
info AppiumDoctor  ✔ Bin directory of $JAVA_HOME is set
info AppiumDoctor ### Diagnostic completed, no fix needed. ###
info AppiumDoctor 
info AppiumDoctor Everything looks good, bye!
info AppiumDoctor
```

#### `test-config/protractor.conf.js`
```
exports.config = {
  seleniumAddress: 'http://localhost:4723/wd/hub',
  allScriptsTimeout: 100000,
  specs: [
    './e2e/**/*.e2e-spec.ts'
  ],
  capabilities: {
    browserName: "",
    platformName: 'Android',
    platformVersion: '6.0',
    autoWebview: true,
    deviceName: 'Android 6.0',
    app: '/home/hadrien-toma/dev/ionic/ionic-unit-testing-example/platforms/android/build/outputs/apk/android-debug.apk'
  },

  jasmineNodeOpts: {
    showColors: true,
    defaultTimeoutInterval: 30000
  },

  baseUrl: 'http://10.0.2.2:8000', // I also tried : 'http://192.168.1.21:8100' where Ionic is serving the application over the local network. The Android phone is also connected to this network (with Wi-Fi) and successfully access the served application via Chrome browser.

  useAllAngular2AppRoots: true,
  beforeLaunch: function() {
    require('ts-node').register({
      project: 'e2e'
    });
  },

  onPrepare: function() {
    var wd = require('wd'),
      protractor = require('protractor'),
      wdBridge = require('wd-bridge')(protractor, wd);
      wdBridge.initFromProtractor(exports.config);
  }
};
```

### 7. Run E2E on real device
Running `appium` in a terminal A and `protractor ./test-config/protractor.conf.js` in a terminal B gives me the following:
##### Command
```
appium
```

##### Result
[Here](https://gist.github.com/hadrien-toma/cdd531fe35fbf51e425648dbcee0bf05).

##### Command
```
protractor ./test-config/protractor.conf.js
```

##### Result
[Here](https://gist.github.com/hadrien-toma/dad2ec7ed0ab26e286bed6b9d74b177f).

#### Android device
The application is launched and seems to be loaded successfully (but slowly). It finally leaves when the error is thrown.

## Notes
I also tried to explicitly specify a newer `chromedriver` to Appium with : `appium --chromedriver-executable ./test-config/chromedriver` but that throws the same error, replacing:
* `chromedriver=2.28.455506` by `chromedriver=2.29.461571`
* `Chrome version must be >= 55.0.2883.0` by `Chrome version must be >= 56.0.2884.0`.

**Comment by imurchie** [comment]
You need to downgrade the version of Chromedriver being used. Your device has too low a Chrome version. They are available here: https://chromedriver.storage.googleapis.com/index.html

Once downloaded and unzipped, a new version can be tried in Appium by specifying the full path with the `--chromedriver-executable` server flag (e.g., `appium --chromedriver-executable /path/to/chromedriver`)

**Comment by hadrien-toma** [comment]
Thank you! I tried with newer versions as I explained in the Notes section but not with older ones. Can you explain me how can I know the version of `chromedriver` is the one I need?

**Comment by imurchie** [comment]
Unfortunately, no. Chromedriver updates change what their minimum version is. They don't, as far as I can tell, document it. :( It's just a matter of trial and error.

**Comment by hadrien-toma** [comment]
Alright, thank you anyway!

**Comment by iagovelasco** [comment]
I have the same problem

**Comment by asifiqbal100** [comment]
try the same solution
