### ISSUE TITLE
Appium IOS time out finding the element when API call return large number of data set

### ISSUE THREAD

**Issue by SanjayDhami** [appium/appium#8353]
## Environment

* Appium version 1.6.4
* Mobile platform/version under test:
* Real device or emulator/simulator: Both
* Appium CLI or Appium.app|exe:

## Details

IOS appium driver takes very very long time to find the element Whenever i click the link in the app that returns large set of data, 

i am guessing this issue is because the API return large data set and appium ios driver is taking long time to parse and get the desired element from the DOM.

Android works fine because appium android only know what is present in the current screen regardless what api returns but iOS know every element even not displayed in the screen.

## Link to Appium logs

[Xcode] 2017-04-26 17:18:21.811 XCTRunner[2724:2785096] Enqueue Failure: UI Testing Failure - Failure getting snapshot Error Domain=XCTestManagerErrorDomain Code=9 "Error -25204 getting snapshot for element {pid=2730}" UserInfo={NSLocalizedDescription=Error -25204 getting snapshot for element {pid=2730}} 0 1

[Xcode] 2017-04-26 17:18:21.929 XCTRunner[2724:2772514] Enqueue Failure: UI Testing Failure - (null) /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 35 1
[Xcode] 2017-04-26 17:18:21.932 XCTRunner[2724:2772514] Failed to invoke libxml2>xmlTextWriterStartElement. Error code: -1
[Xcode] 2017-04-26 17:18:21.932 XCTRunner[2724:2772514] Failed to generate XML presentation of a screen element

And i realize that when API call return the less number of data set its pretty quick to get the element.
Any Suggestion / idea to solve this issue

**Comment by imurchie** [comment]
My main suggestion would be to find a different selector? Xpath is slow in general because it is ill-fitted to the domain.

**Comment by SanjayDhami** [comment]
i am using accessibility identifier , the problem is large data set to parse

**Comment by mykola-mokhnach** [comment]
Try 1.6.5-beta. There were some fixes in WDA to workaround such issues. In general this might happen if application resources contain characters which are not allowed in XML.

**Comment by SanjayDhami** [comment]
I updated appium but still no luck. could you please explain me what "if application resources contain characters which are not allowed in XML." means .

Appreciate your help.
Thank you

**Comment by mykola-mokhnach** [comment]
If it still fails then your problem should be a different one. We had something similar when we were using [NSMutableAttributedString class in the source code](https://github.com/facebook/WebDriverAgent/issues/402)
Anyway, this is XCTest issue and it has nothing to do with Appium itself. You could report it to https://github.com/facebook/WebDriverAgent/issues 
Closing the issue as non Appium-related.
