### ISSUE TITLE
Feature Request: Add support for image uploading

### ISSUE THREAD

**Issue by VivaLosDoyers** [appium/appium#8355]
I have a remote Appium server that runs iOS and Android tests. For the emulators/simulators of both platforms, I need to copy a set of images to them to be used in our testing.

With local Appium, this can be done with xcrun for iOS 
`xcrun simctl addphoto '#{device}' #{path}`

and adb for Android
`adb push #{local_image_path} /sdcard/Pictures/testapp`

But when appium is running on a remote server, neither of those commands seem to be doable (unless I'm hugely mistaken!). For Android, we solved this by using push_file from the Ruby lib, and that works great. But for iOS, that doesn't seem possible to use push_file.

It would be really nice to be able to issue an xcrun command on a remote Appium server.

**Comment by imurchie** [comment]
Adding support for uploading images is doable. I do not think we will be allowing _ad hoc_ `xcrun` commands to be run, though.

**Comment by mykola-mokhnach** [comment]
Added support for iOS simulator. On Android it was already possible via push_file Selenium API.
Unfortunately, there is no way to upload a file into the real iOS device for now.

**Comment by atomar09** [comment]
Can you please provide an example how to use this?
What I need to do if I need to upload a file from iOS simulator?

**Comment by Bhuvanavd** [comment]
Hi,

Using Appium 1.8.1 with java client 6.1, I was not able to upload the file using xcrun command.  I think xcrun commands are no longer supported.
@mykola-mokhnach, @imurchie  please can you let know the command to be used to upload a file onto iOS 11 simulator.

Changelog says support is been provided --> Add command to upload media to simulator.

**Comment by yadavsvmx** [comment]
is the support for attaching the image from gallery added in Appium now ?

**Comment by sandeepmaaram** [comment]
Hey for Android after pushing the file to device, how you are passing that path.

In my case we have Webview, in that upload document feature is there. Now the problem is, I am able to push the file to device but not able to send that path to webview?

Please can anyone help me on this. Thanks in advance.
