### ISSUE TITLE
Command 'java -version' exited with code 2

### ISSUE THREAD

**Issue by LayneHuang** [appium/appium#8356]
## The problem

after use appium-doctor check the environment setting ( no problem , info AppiumDoctor Everything looks good, bye!), and try to run TestSample in python,but failure.

## Environment

* Appium version (or git revision) that exhibits the issue: 
  1.6.4
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
Mac mini , MacOs 10.12.2
* Node.js version (unless using Appium.app|exe):
6.10.2
* Mobile platform/version under test:
 Android 6.1.0
* Real device or emulator/simulator:
Real device
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
This rather look like a problem with your local machine configuration. Please attach all the necessary logs and code samples and reopen the issue if you think it is somehow related to Appium.

**Comment by LayneHuang** [comment]
Question modified.
