### ISSUE TITLE
Connect to 127.0.0.1:4723 [/127.0.0.1] failed: Connection refused (Connection refused)

### ISSUE THREAD

**Issue by UserAutomation** [appium/appium#8357]
## The problem
I am trying to run appium server through java code. i am using Mac OS. After running the code appium server starts successfully but on capabilities when it tries to connect to localhost IP Address it fails. if i start appium manually through terminal and then run the code it works perfectly. i have looked into many tutorial but coudnt get any success. Tried all the different ports too.

Here is the code: 
CommandLine command = new CommandLine("/Applications/Appium.app/Contents/Resources/node/bin/node");
        command.addArgument("/Applications/Appium.app/Contents/Resources/node_modules/appium/bin/appium.js", false);
        command.addArgument("--address", false);
        command.addArgument("127.0.0.1");
        command.addArgument("--port", false);
        command.addArgument("4723");
        command.addArgument("--bootstrap-port", false);
        command.addArgument("4724");
        
        //command.addArgument("--full-reset", false);
        //command.addArgument("--session-override", true);
        DefaultExecuteResultHandler resultHandler = new DefaultExecuteResultHandler();
        DefaultExecutor executor = new DefaultExecutor();
        executor.setExitValue(1);
        try {
            executor.execute(command, resultHandler);
            Thread.sleep(5000);
            System.out.println("Appium server started.");
        } catch (IOException e) {
            e.printStackTrace();
}

For Capabilities:

DesiredCapabilities capabilities = new DesiredCapabilities();

        //common capabilities

        capabilities.setCapability("appium-version", "1.6.4");
        capabilities.setCapability("platformName", "Android");

        //capabilities for Emulator
        capabilities.setCapability("platformVersion", "7.1.1");
        capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "Nexus 7");
        capabilities.setCapability("app", "/Users/tvs00023/Desktop/KwizzAdd.apk");

        driver = new AndroidDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);

The error is : 
org.openqa.selenium.WebDriverException: org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:4723 [/127.0.0.1] failed: Connection refused (Connection refused)
Build info: version: '3.3.1', revision: '5234b32', time: '2017-03-10 09:04:52 -0800'

caused by: org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:4723 [/127.0.0.1] failed: Connection refused (Connection refused)

Can anybody help me out in this ?

**Comment by mykola-mokhnach** [comment]
Connection refused error means that the server is not  (yet) running on the requested address.

**Comment by rkn411** [comment]
thats y it is not running we understood that its not running from logs but how to start it

**Comment by SrinivasanTarget** [comment]
Hey @UserAutomation Check [this](https://github.com/appium/java-client/blob/master/src/test/java/io/appium/java_client/ios/AppXCUITTest.java#L19) out to run appium server programatically. Incase if you still hit the issue please reopen with complete error logs in form of gist.

**Comment by sandhya448** [comment]
hi @SrinivasanTarget the above link is not available anymore. i am facing the above issue.. could you please check the link or comment the solution

**Comment by imurchie** [comment]
https://github.com/appium/java-client/blob/master/src/test/java/io/appium/java_client/ios/AppIOSTest.java
