### ISSUE TITLE
Android devices getting disconnected after 3-4 test scripts when executed in a Batch

### ISSUE THREAD

**Issue by erkhemraj** [appium/appium#8358]
I am using Android device in a batch run of around 35 test scripts. This batch uses 3 android devices of different android versions. At times the batch goes through without any issues but sometimes one of the android devices gets disconnected in between of the automated batch of scripts. 

## Environment
Appium: 1.4.16
Windows 8.1
Mobile Platform: 6.1
Real Device
Java Version : 1.7.0_21
Starting the Appium server with AppiumDriverLocalService.

## Below are the Appium logs

[36minfo[39m: JSONWP Proxy: Proxying [GET /url] to [GET http://127.0.0.1:9515/wd/hub/session/93cbe38de9f91c0f15a6d3e2e58149c8/url] with no body
[36minfo[39m: JSONWP Proxy: Got response with status 200: "{\"sessionId\":\"93cbe38de9f91c0f15a6d3e2e58149c8\",\"status\":0,\"value\":\"file:///android_asset/www/index.html\"}"
[36minfo[39m: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"75e44f95-144d-42d0-9a5e-0b6b1d820634"}
[36minfo[39m: [37m<-- POST /wd/hub/session/75e44f95-144d-42d0-9a5e-0b6b1d820634/context [39m[32m200[39m[90m 260.080 ms - 76[39m [90m{"status":0,"value":null,"sessionId":"75e44f95-144d-42d0-9a5e-0b6b1d820634"}[39m
[36minfo[39m: [37m-->[39m [37mPOST[39m [37m/wd/hub/session/75e44f95-144d-42d0-9a5e-0b6b1d820634/element[39m [90m{"using":"xpath","value":"//*[@class='button-content' and contains(text(),'OK')]"}[39m
[36minfo[39m: JSONWP Proxy: Proxying [POST /wd/hub/session/75e44f95-144d-42d0-9a5e-0b6b1d820634/element] to [POST http://127.0.0.1:9515/wd/hub/session/93cbe38de9f91c0f15a6d3e2e58149c8/element] with body: {"using":"xpath","value":"//*[@class='button-content' and contains(text(),'OK')]"}
[36minfo[39m: [debug] [BOOTSTRAP] [debug] Emitting system alert message
[36minfo[39m: [debug] Emitting alert message...
[36minfo[39m: JSONWP Proxy: Got response with status 200: {"sessionId":"93cbe38de9f91c0f15a6d3e2e58149c8","status":7,"value":{"message":"no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//*[@class='button-content' and contai...
[36minfo[39m: JSONWP Proxy: Replacing sessionId 93cbe38de9f91c0f15a6d3e2e58149c8 with 75e44f95-144d-42d0-9a5e-0b6b1d820634
[36minfo[39m: [37m<-- POST /wd/hub/session/75e44f95-144d-42d0-9a5e-0b6b1d820634/element [39m[32m200[39m[90m 146.125 ms - 384[39m [90m[39m
[36minfo[39m: [37m-->[39m [37mPOST[39m [37m/wd/hub/session/75e44f95-144d-42d0-9a5e-0b6b1d820634/element[39m [90m{"using":"xpath","value":"//*[@class='button-content' and contains(text(),'OK')]"}[39m
[36minfo[39m: JSONWP Proxy: Proxying [POST /wd/hub/session/75e44f95-144d-42d0-9a5e-0b6b1d820634/element] to [POST http://127.0.0.1:9515/wd/hub/session/93cbe38de9f91c0f15a6d3e2e58149c8/element] with body: {"using":"xpath","value":"//*[@class='button-content' and contains(text(),'OK')]"}
[36minfo[39m: JSONWP Proxy: Got response with status 200: {"sessionId":"93cbe38de9f91c0f15a6d3e2e58149c8","status":7,"value":{"message":"no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//*[@class='button-content' and contai...
[36minfo[39m: JSONWP Proxy: Replacing sessionId 93cbe38de9f91c0f15a6d3e2e58149c8 with 75e44f95-144d-42d0-9a5e-0b6b1d820634
[36minfo[39m: [37m<-- POST /wd/hub/session/75e44f95-144d-42d0-9a5e-0b6b1d820634/element [39m[32m200[39m[90m 112.304 ms - 384[39m [90m[39m
[36minfo[39m: [37m-->[39m [37mPOST[39m [37m/wd/hub/session/75e44f95-144d-42d0-9a5e-0b6b1d820634/element[39m [90m{"using":"xpath","value":"//*[@class='button-content' and contains(text(),'OK')]"}[39m
[36minfo[39m: JSONWP Proxy: Proxying [POST /wd/hub/session/75e44f95-144d-42d0-9a5e-0b6b1d820634/element] to [POST http://127.0.0.1:9515/wd/hub/session/93cbe38de9f91c0f15a6d3e2e58149c8/element] with body: {"using":"xpath","value":"//*[@class='button-content' and contains(text(),'OK')]"}
[36minfo[39m: JSONWP Proxy: Got response with status 200: {"sessionId":"93cbe38de9f91c0f15a6d3e2e58149c8","status":7,"value":{"message":"no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//*[@class='button-content' and contai...
[36minfo[39m: JSONWP Proxy: Replacing sessionId 93cbe38de9f91c0f15a6d3e2e58149c8 with 75e44f95-144d-42d0-9a5e-0b6b1d820634
[36minfo[39m: [37m<-- POST /wd/hub/session/75e44f95-144d-42d0-9a5e-0b6b1d820634/element [39m[32m200[39m[90m 237.416 ms - 384[39m [90m[39m
[36minfo[39m: [37m-->[39m [37mPOST[39m [37m/wd/hub/session/75e44f95-144d-42d0-9a5e-0b6b1d820634/element[39m [90m{"using":"xpath","value":"//*[@class='button-content' and contains(text(),'OK')]"}[39m
[36minfo[39m: JSONWP Proxy: Proxying [POST /wd/hub/session/75e44f95-144d-42d0-9a5e-0b6b1d820634/element] to [POST http://127.0.0.1:9515/wd/hub/session/93cbe38de9f91c0f15a6d3e2e58149c8/element] with body: {"using":"xpath","value":"//*[@class='button-content' and contains(text(),'OK')]"}
[36minfo[39m: JSONWP Proxy: Got response with status 200: {"sessionId":"93cbe38de9f91c0f15a6d3e2e58149c8","status":7,"value":{"message":"no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//*[@class='button-content' and contai...
[36minfo[39m: JSONWP Proxy: Replacing sessionId 93cbe38de9f91c0f15a6d3e2e58149c8 with 75e44f95-144d-42d0-9a5e-0b6b1d820634
[36minfo[39m: [37m<-- POST /wd/hub/session/75e44f95-144d-42d0-9a5e-0b6b1d820634/element [39m[32m200[39m[90m 166.567 ms - 384[39m [90m[39m
[36minfo[39m: [37m-->[39m [37mPOST[39m [37m/wd/hub/session/75e44f95-144d-42d0-9a5e-0b6b1d820634/element[39m [90m{"using":"xpath","value":"//*[@class='button-content' and contains(text(),'OK')]"}[39m
[36minfo[39m: JSONWP Proxy: Proxying [POST /wd/hub/session/75e44f95-144d-42d0-9a5e-0b6b1d820634/element] to [POST http://127.0.0.1:9515/wd/hub/session/93cbe38de9f91c0f15a6d3e2e58149c8/element] with body: {"using":"xpath","value":"//*[@class='button-content' and contains(text(),'OK')]"}
[36minfo[39m: JSONWP Proxy: Got response with status 200: {"sessionId":"93cbe38de9f91c0f15a6d3e2e58149c8","status":7,"value":{"message":"no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//*[@class='button-content' and contai...
[36minfo[39m: JSONWP Proxy: Replacing sessionId 93cbe38de9f91c0f15a6d3e2e58149c8 with 75e44f95-144d-42d0-9a5e-0b6b1d820634
[36minfo[39m: [37m<-- POST /wd/hub/session/75e44f95-144d-42d0-9a5e-0b6b1d820634/element [39m[32m200[39m[90m 236.596 ms - 384[39m [90m[39m
[36minfo[39m: [37m-->[39m [37mPOST[39m [37m/wd/hub/session/75e44f95-144d-42d0-9a5e-0b6b1d820634/element[39m [90m{"using":"xpath","value":"//*[@class='button-content' and contains(text(),'OK')]"}[39m
[36minfo[39m: JSONWP Proxy: Proxying [POST /wd/hub/session/75e44f95-144d-42d0-9a5e-0b6b1d820634/element] to [POST http://127.0.0.1:9515/wd/hub/session/93cbe38de9f91c0f15a6d3e2e58149c8/element] with body: {"using":"xpath","value":"//*[@class='button-content' and contains(text(),'OK')]"}
[36minfo[39m: JSONWP Proxy: Got response with status 200: {"sessionId":"93cbe38de9f91c0f15a6d3e2e58149c8","status":7,"value":{"message":"no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//*[@class='button-content' and contai...
[36minfo[39m: JSONWP Proxy: Replacing sessionId 93cbe38de9f91c0f15a6d3e2e58149c8 with 75e44f95-144d-42d0-9a5e-0b6b1d820634
[36minfo[39m: [37m<-- POST /wd/hub/session/75e44f95-144d-42d0-9a5e-0b6b1d820634/element [39m[32m200[39m[90m 115.026 ms - 384[39m [90m[39m
[36minfo[39m: [37m-->[39m [37mPOST[39m [37m/wd/hub/session/75e44f95-144d-42d0-9a5e-0b6b1d820634/element[39m [90m{"using":"xpath","value":"//*[@class='button-content' and contains(text(),'OK')]"}[39m
[36minfo[39m: JSONWP Proxy: Proxying [POST /wd/hub/session/75e44f95-144d-42d0-9a5e-0b6b1d820634/element] to [POST http://127.0.0.1:9515/wd/hub/session/93cbe38de9f91c0f15a6d3e2e58149c8/element] with body: {"using":"xpath","value":"//*[@class='button-content' and contains(text(),'OK')]"}
[36minfo[39m: Chromedriver: [STDERR] [8.134][SEVERE]: Unable to receive message from renderer
[36minfo[39m: [debug] Logcat terminated with code 0, signal null
[36minfo[39m: [debug] UiAutomator exited
[36minfo[39m: [debug] executing cmd: E:\android\platform-tools\adb.exe -s LGH8183c30b1b8 shell "echo 'ping'"
[36minfo[39m: [debug] Error: Command failed: C:\windows\system32\cmd.exe /s /c "E:\android\platform-tools\adb.exe -s LGH8183c30b1b8 shell "echo 'ping'""
error: device 'LGH8183c30b1b8' not found

[36minfo[39m: [debug] Stopping logcat capture
[36minfo[39m: [debug] Logcat already stopped
[36minfo[39m: [debug] executing cmd: E:\android\platform-tools\adb.exe -s LGH8183c30b1b8 kill-server
[36minfo[39m: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
[36minfo[39m: [debug] executing cmd: E:\android\platform-tools\adb.exe -s LGH8183c30b1b8 wait-for-device
[36minfo[39m: JSONWP Proxy: Got response with status 200: {"sessionId":"93cbe38de9f91c0f15a6d3e2e58149c8","status":0,"value":null}
[36minfo[39m: JSONWP Proxy: Replacing sessionId 93cbe38de9f91c0f15a6d3e2e58149c8 with 75e44f95-144d-42d0-9a5e-0b6b1d820634
[36minfo[39m: [37m<-- POST /wd/hub/session/75e44f95-144d-42d0-9a5e-0b6b1d820634/element [39m[32m200[39m[90m 2041.196 ms - 76[39m [90m[39m
[36minfo[39m: [37m-->[39m [37mPOST[39m [37m/wd/hub/session/75e44f95-144d-42d0-9a5e-0b6b1d820634/context[39m [90m{"name":"NATIVE_APP"}[39m
[36minfo[39m: [debug] Getting a list of available webviews
[36minfo[39m: [debug] executing cmd: E:\android\platform-tools\adb.exe -s LGH8183c30b1b8 shell "cat /proc/net/unix"
[36minfo[39m: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"75e44f95-144d-42d0-9a5e-0b6b1d820634"}
[36minfo[39m: [37m<-- POST /wd/hub/session/75e44f95-144d-42d0-9a5e-0b6b1d820634/context [39m[32m200[39m[90m 50.627 ms - 76[39m [90m{"status":0,"value":null,"sessionId":"75e44f95-144d-42d0-9a5e-0b6b1d820634"}[39m
[36minfo[39m: [37m-->[39m [37mGET[39m [37m/wd/hub/session/75e44f95-144d-42d0-9a5e-0b6b1d820634/contexts[39m [90m{}[39m
[36minfo[39m: [debug] Getting a list of available webviews
[36minfo[39m: [debug] executing cmd: E:\android\platform-tools\adb.exe -s LGH8183c30b1b8 shell "cat /proc/net/unix"
[36minfo[39m: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command. (Original error: Command failed: C:\\windows\\system32\\cmd.exe /s /c \"E:\\android\\platform-tools\\adb.exe -s LGH8183c30b1b8 shell \"cat /proc/net/unix\"\"\nerror: device 'LGH8183c30b1b8' not found\r\n)","killed":false,"code":1,"signal":null,"cmd":"C:\\windows\\system32\\cmd.exe /s /c \"E:\\android\\platform-tools\\adb.exe -s LGH8183c30b1b8 shell \"cat /proc/net/unix\"\"","origValue":"Command failed: C:\\windows\\system32\\cmd.exe /s /c \"E:\\android\\platform-tools\\adb.exe -s LGH8183c30b1b8 shell \"cat /proc/net/unix\"\"\nerror: device 'LGH8183c30b1b8' not found\r\n"},"sessionId":"75e44f95-144d-42d0-9a5e-0b6b1d820634"}
[36minfo[39m: [37m<-- GET /wd/hub/session/75e44f95-144d-42d0-9a5e-0b6b1d820634/contexts [39m[31m500[39m[90m 48.459 ms - 731[39m [90m[39m
[36minfo[39m: [37m-->[39m [37mPOST[39m [37m/wd/hub/session/75e44f95-144d-42d0-9a5e-0b6b1d820634/context[39m [90m{"name":"NATIVE_APP"}[39m
[36minfo[39m: [debug] Getting a list of available webviews
[36minfo[39m: [debug] executing cmd: E:\android\platform-tools\adb.exe -s LGH8183c30b1b8 shell "cat /proc/net/unix"
[36minfo[39m: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"75e44f95-144d-42d0-9a5e-0b6b1d820634"}
[36minfo[39m: [37m<-- POST /wd/hub/session/75e44f95-144d-42d0-9a5e-0b6b1d820634/context [39m[32m200[39m[90m 51.500 ms - 76[39m [90m{"status":0,"value":null,"sessionId":"75e44f95-144d-42d0-9a5e-0b6b1d820634"}[39m
[36minfo[39m: [37m-->[39m [37mGET[39m [37m/wd/hub/session/75e44f95-144d-42d0-9a5e-0b6b1d820634/contexts[39m [90m{}[39m
[36minfo[39m: [debug] Getting a list of available webviews
[36minfo[39m: [debug] executing cmd: E:\android\platform-tools\adb.exe -s LGH8183c30b1b8 shell "cat /proc/net/unix"
[36minfo[39m: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command. (Original error: Command failed: C:\\windows\\system32\\cmd.exe /s /c \"E:\\android\\platform-tools\\adb.exe -s LGH8183c30b1b8 shell \"cat /proc/net/unix\"\"\nerror: device 'LGH8183c30b1b8' not found\r\n)","killed":false,"code":1,"signal":null,"cmd":"C:\\windows\\system32\\cmd.exe /s /c \"E:\\android\\platform-tools\\adb.exe -s LGH8183c30b1b8 shell \"cat /proc/net/unix\"\"","origValue":"Command failed: C:\\windows\\system32\\cmd.exe /s /c \"E:\\android\\platform-tools\\adb.exe -s LGH8183c30b1b8 shell \"cat /proc/net/unix\"\"\nerror: device 'LGH8183c30b1b8' not found\r\n"},"sessionId":"75e44f95-144d-42d0-9a5e-0b6b1d820634"}
[36minfo[39m: [37m<-- GET /wd/hub/session/75e44f95-144d-42d0-9a5e-0b6b1d820634/contexts [39m[31m500[39m[90m 49.584 ms - 731[39m [90m[39m
[36minfo[39m: [37m-->[39m [37mPOST[39m [37m/wd/hub/session/75e44f95-144d-42d0-9a5e-0b6b1d820634/context[39m [90m{"name":"NATIVE_APP"}[39m
[36minfo[39m: [debug] Getting a list of available webviews
[36minfo[39m: [debug] executing cmd: E:\android\platform-tools\adb.exe -s LGH8183c30b1b8 shell "cat /proc/net/unix"
[36minfo[39m: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"75e44f95-144d-42d0-9a5e-0b6b1d820634"}
[36minfo[39m: [37m<-- POST /wd/hub/session/75e44f95-144d-42d0-9a5e-0b6b1d820634/context [39m[32m200[39m[90m 51.933 ms - 76[39m [90m{"status":0,"value":null,"sessionId":"75e44f95-144d-42d0-9a5e-0b6b1d820634"}[39m
[36minfo[39m: [37m-->[39m [37mGET[39m [37m/wd/hub/session/75e44f95-144d-42d0-9a5e-0b6b1d820634/screenshot[39m [90m{}[39m
[36minfo[39m: [debug] executing cmd: E:\android\platform-tools\adb.exe -s LGH8183c30b1b8 shell "/system/bin/rm /data/local/tmp/screenshot.png; /system/bin/screencap -p /data/local/tmp/screenshot.png "
[36minfo[39m: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command. (Original error: Command failed: C:\\windows\\system32\\cmd.exe /s /c \"E:\\android\\platform-tools\\adb.exe -s LGH8183c30b1b8 shell \"/system/bin/rm /data/local/tmp/screenshot.png; /system/bin/screencap -p /data/local/tmp/screenshot.png \"\"\nerror: device 'LGH8183c30b1b8' not found\r\n)","killed":false,"code":1,"signal":null,"cmd":"C:\\windows\\system32\\cmd.exe /s /c \"E:\\android\\platform-tools\\adb.exe -s LGH8183c30b1b8 shell \"/system/bin/rm /data/local/tmp/screenshot.png; /system/bin/screencap -p /data/local/tmp/screenshot.png \"\"","origValue":"Command failed: C:\\windows\\system32\\cmd.exe /s /c \"E:\\android\\platform-tools\\adb.exe -s LGH8183c30b1b8 shell \"/system/bin/rm /data/local/tmp/screenshot.png; /system/bin/screencap -p /data/local/tmp/screenshot.png \"\"\nerror: device 'LGH8183c30b1b8' not found\r\n"},"sessionId":"75e44f95-144d-42d0-9a5e-0b6b1d820634"}
[36minfo[39m: [37m<-- GET /wd/hub/session/75e44f95-144d-42d0-9a5e-0b6b1d820634/screenshot [39m[31m500[39m[90m 50.368 ms - 986[39m [90m[39m
[36minfo[39m: Welcome to Appium v1.4.16 (REV ae6877eff263066b26328d457bd285c0cc62430d)
[36minfo[39m: Appium REST http interface listener started on 127.0.0.20:4743
[36minfo[39m: [debug] Non-default server args: {"udid":"LGH8183c30b1b8","address":"127.0.0.20","port":4743,"sessionOverride":true}
[36minfo[39m: Console LogLevel: debug
[36minfo[39m: [37m-->[39m [37mGET[39m [37m/wd/hub/status[39m [90m{}[39m
[36minfo[39m: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}}}
[36minfo[39m: [37m<-- GET /wd/hub/status [39m[32m200[39m[90m 4.770 ms - 105[39m [90m{"status":0,"value":{"build":{"version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}}}[39m
[36minfo[39m: [37m-->[39m [37mPOST[39m [37m/wd/hub/session[39m [90m{"desiredCapabilities":{"newCommandTimeout":2500,"platformVersion":6,"autoAcceptAlerts":true,"app":"E:\\NexGenSVN\\STA\\Selenium_Automation_Framework/src/config/NextGen/app/ucamobile_android_v7_3_GA-219_Automation.apk","deviceName":"LGH8183c30b1b8","platformName":"Android","appActivity":".wrapper","Density":640,"appPackage":"XX.XX.com","noReset":true}}[39m
[36minfo[39m: Client User-Agent string: Apache-HttpClient/4.3.4 (java 1.5)
[36minfo[39m: [debug] The following desired capabilities were provided, but not recognized by appium. They will be passed on to any other services running on this server. : Density
[36minfo[39m: [debug] Using local app from desired caps: E:\NexGenSVN\STA\Selenium_Automation_Framework\src\config\NextGen\app\ucamobile_android_v7_3_GA-219_Automation.apk
[36minfo[39m: [debug] Creating new appium session 69e39960-4df9-4b7d-a648-ee741cc0697d
[36minfo[39m: Starting android appium
[36minfo[39m: [debug] Getting Java version
[36minfo[39m: Java version is: 1.7.0_21
[36minfo[39m: [debug] Checking whether adb is present
[36minfo[39m: [debug] Using adb from E:\android\platform-tools\adb.exe
[36minfo[39m: [debug] Using fast reset? false
[36minfo[39m: [debug] Preparing device for session
[36minfo[39m: [debug] Checking whether app is actually present
[36minfo[39m: Retrieving device
[36minfo[39m: [debug] Trying to find a connected android device
[36minfo[39m: [debug] Getting connected devices...
[36minfo[39m: [debug] executing cmd: E:\android\platform-tools\adb.exe devices
[36minfo[39m: [debug] 2 device(s) connected
[36minfo[39m: [debug] Sent shutdown command, waiting for UiAutomator to stop...
[33mwarn[39m: UiAutomator did not shut down fast enough, calling it gone
[36minfo[39m: [debug] Cleaning up android objects
[36minfo[39m: [debug] Cleaning up appium session
[31merror[39m: Failed to start an Appium session, err was: Error: Device LGH8183c30b1b8 was not in the list of connected devices
[36minfo[39m: [debug] Error: Device LGH8183c30b1b8 was not in the list of connected devices
    at [object Object].<anonymous> (C:\Program Files (x86)\Appium\node_modules\appium\lib\devices\android\android-common.js:405:19)
    at [object Object].<anonymous> (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-adb\lib\adb.js:621:9)
    at [object Object].<anonymous> (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-adb\lib\adb.js:853:7)
    at [object Object].<anonymous> (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-adb\lib\adb.js:180:9)
    at ChildProcess.exithandler (child_process.js:742:7)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1016:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1088:5)
[36minfo[39m: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Device LGH8183c30b1b8 was not in the list of connected devices)","origValue":"Device LGH8183c30b1b8 was not in the list of connected devices"},"sessionId":null}
[36minfo[39m: [37m<-- POST /wd/hub/session [39m[31m500[39m[90m 7179.901 ms - 246[39m [90m[39m

Below are the capabilities I am using:
DesiredCapabilities capabilities = new DesiredCapabilities(); //Creating an object for Desired Capabilities
capabilities.setCapability("deviceName", platformInfoObject.PlatformID); //Udid of Android Device.
capabilities.setCapability("newCommandTimeout", 2500);             // How long (in seconds) Appium will wait for a new command before ending the session
capabilities.setCapability("noReset", true);                       //Don’t reset app state after every sessions
capabilities.setCapability("platformName", platformInfoObject.PlatformName); //Platform Name (OS)
capabilities.setCapability("platformVersion", platformInfoObject.PlatformVersion); //OS Version 
capabilities.setCapability("appPackage", platformInfoObject.AppPackage);  //App package 
capabilities.setCapability("appActivity", platformInfoObject.AppActivity); //App Activity
capabilities.setCapability("autoAcceptAlerts", true);                 //Accepts Alerts
capabilities.setCapability("Density", platformInfoObject.PlatformDensity);  //Density of Android Device
capabilities.setCapability("app", System.getProperty("user.dir")+"/src/config/NextGen/app/"+platformInfoObject.AppPath); // App path 
driver = new AndroidDriver<WebElement>(new URL("http://"+platformInfoObject.ServerURL+":"+platformInfoObject.ServerPortNumber+"/wd/hub"), capabilities);  //Initializing the Appium Android Driver.

**Comment by mykola-mokhnach** [comment]
Please attach the log as a gist - it is impossible to read it.

Regarding device disconnects - it has nothing to do with Appium itself. The issue might happen because of memory leaks on the device itself or performance bugs in adb implementation. Therefore we reboot all our real devices in the lab by schedule to workaround such issues.

**Comment by erkhemraj** [comment]
I have added the logs through gist. Please have a look on them as there might be something which we are doing wrong by looking into the logs.

**Comment by mykola-mokhnach** [comment]
The log does not contain any explicit errors. The conclusion is the same - try to reboot the devices from time to time.

**Comment by erkhemraj** [comment]
okay thank you very much.
