### ISSUE TITLE
Unable to tap alert buttons with XCUITests on iOS10

### ISSUE THREAD

**Issue by felyppers** [appium/appium#8361]
## The problem

Currently adjusting my ios9 (xcode7) test suite to run on ios10 (xcode8). I cannot tap iOS native alerts. For instance, my app have IAP (in-app purchases) and for this an ITunes Sign Up alert is shown. In iOS9 devices I tap the "Use an Existing Apple ID" button using .click function, use .send_keys to enter login and passwork and .click again to tap OK. Using XCUITests I'm able to use send_keys, but I can't tap the elements of "Use an Existing Apple ID" and "OK". I tried using .click, .tap, precise_tap, performing a complete touch action (Appium::TouchAction.new.tap(element: element).perform) and even changing contexts with driver.within_context. I'm able to find the elements, but not able to tap them.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Desktop OS/version used to run Appium: MacOS Sierra 10.12
* Node.js version (unless using Appium.app|exe): 7.4
* Mobile platform/version under test: iOS 10
* Real device or emulator/simulator: iPhone 6S
* Appium CLI or Appium.app|exe: Appium CLI
* Library Language: Ruby

## Code To Reproduce Issue [ Good To Have ]

Once the alert is visible on the screen I get the element with:
`btn = find_element :name, 'Use Existing Apple ID'`

Then tried all of these:
```
1. btn.click
2. btn.tap
3. Appium::TouchAction.new.tap(element: btn).perform
4. Precise tap (varies depending on the device orientation and screen size
5. $appium_driver.within_context('NATIVE_APP') do
    > ANY OF THE PREVIOUS OPTIONS <
  end
```

**Comment by mykola-mokhnach** [comment]
Try driver.switchTo().alert().accept() / dismiss()

**Comment by felyppers** [comment]
Thanks for the quick response @mykola-mokhnach.
Tried as well, switchTo is a java function, in ruby we use within_context.
Also, this alert have several options, that might be a reason for accept/dismiss not work here. THe options are:
- Use Existing Apple ID
- Sign in with a new Apple ID
- Cancel

**Comment by mykola-mokhnach** [comment]
Actually, WDA's alert/* API has the _name_ parameter, which supports explicit setting of alert button names. However, this is not supported by Appium API. @imurchie is there a way to add this parameter somewhere into existing API calls?

As a workaround you can try to call WDA API directly using curl. See https://github.com/facebook/WebDriverAgent/wiki/Queries for more details.

**Comment by felyppers** [comment]
I'll take a look into this and give you a feedback asap. Thanks again!

**Comment by imurchie** [comment]
There is no easy way, no. The APi is from Selenium, and so not very malleable.

**Comment by mykola-mokhnach** [comment]
@imurchie I could create **mobile:** wrapper over this WDA call - this will be the fastest way to deliver this functionality to the clients.

**Comment by imurchie** [comment]
Sure.

**Comment by felyppers** [comment]
I was able to interact with some elements using CURL, however the sign in alert is still untouchable. Using precise tap seems to be working now (don't know why). Hope this helps someone:
`Appium::TouchAction.new.tap(:x => x_position, :y => y_position).release.perform`

**Comment by mykola-mokhnach** [comment]
@felyppers please check ["mobile: alert" endpoint](https://github.com/appium/appium/pull/8368/files), which has been recently merged into 1.6.5-beta

**Comment by satyakirti26** [comment]
how can i get .Text of any pop up alert to match in my script if alert is displayed or not. i am unable to identify and locate any alert message in iOS appium. But I have successfully written and handled alert messages in android apps with appium.

**Comment by seshusangeetha** [comment]
Hi, I too tried using the default alert handling methods and using the text or other identifiers (XCUITest elements) for the alert but nothing is working. Even the basic driver.switch_to.alert() is not working and throwing the error "Could not connect to a valid app after 20 tries." I am using ios11 with Xcode 9 and Appium 1.7.2 with java
