### ISSUE TITLE
Do you have a plan to implement `getPerformance` related feature for uiautomator2?

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium#8362]
## The problem

This is a just question for uiautomator2.

Do you have a plan to implement `getPerformance` related feature for uiautomator2?

- Spec: [appium-base-driver](https://github.com/appium/appium-base-driver/blob/9d1b2cedaed93f01383766217614bc3fc46f6e3e/lib/mjsonwp/routes.js#L308-L313)
- uiautomaro1
    - [getPerformanceDataTypes](https://github.com/appium/appium-android-driver/search?utf8=✓&q=getPerformanceDataTypes&type=) for example
- uiautomator2
    - none for now

---

In my test suites, I haven't used this feature to monitor performances.
So, I have no strong opinions for implementing this feature for uiautomato2.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: Mac OS X 10.12.4
* Node.js version (unless using Appium.app|exe): v6.9.5
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: ruby_lib

**Comment by imurchie** [comment]
All of that is just pulled from adb, so it should be possible to just add it to the new driver.

**Comment by KazuCocoa** [comment]
thanks!

**Comment by SrinivasanTarget** [comment]
#3641

**Comment by KazuCocoa** [comment]
I've set the command to no-proxy and checked it works with `ruby_lib` test set.
So, I close this issue.

https://github.com/appium/appium-uiautomator2-driver/pull/104
