### ISSUE TITLE
Failed to create WDA session - appium GUI v 1.0.0

### ISSUE THREAD

**Issue by VaishinaviRajaraman** [appium/appium#8363]
I have installed appium GUI v 1.0.0 yesterday and I am trying to start a new session. It fails, since it cannot create WDA session.
Log below:

[Appium] Welcome to Appium v1.6.4
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/private/tmp/Bett3ruat.app","autoAcceptAlerts":true,"deviceName":"iPhone 6s","fullReset":false,"noReset":true,"platformName":"iOS","platformVersion":"10.3","showXcodeLog":true,"newCommandTimeout":0,"connectHardwareKeyboard":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/private/tmp/Bett3ruat.app","autoAcceptAlerts":true,"deviceName":"iPhone 6s","fullReset":false,"noReset":true,"platformName":"iOS","platformVersion":"10.3","showXcodeLog":true,"newCommandTimeout":0,"connectHardwareKeyboard":true},null,null,null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1493788465697 (15:14:25 GMT+1000 (AEST))
[Appium] Requested iOS support with version >= 10, using XCUITest driver instead of UIAutomation-based driver, since the latter is unsupported on iOS 10 and up.
[Appium] Creating new XCUITestDriver (v2.27.2) session
[Appium] Capabilities:
[Appium]   app: '/private/tmp/Bett3ruat.app'
[Appium]   autoAcceptAlerts: true
[Appium]   deviceName: 'iPhone 6s'
[Appium]   fullReset: false
[Appium]   noReset: true
[Appium]   platformName: 'iOS'
[Appium]   platformVersion: '10.3'
[Appium]   showXcodeLog: true
[Appium]   newCommandTimeout: 0
[Appium]   connectHardwareKeyboard: true
[XCUITest] XCUITestDriver version: 2.27.2
[XCUITest] The capabilities 'autoAcceptAlerts' and 'autoDismissAlerts' do not work for XCUITest-based tests. Please adjust your alert handling accordingly.
[BaseDriver] Session created with session id: a632fa26-7a46-47e5-8507-30bfcbf8d5de
[XCUITest] Xcode version set to '8.3.2' (tools v8.3.2.0.1.1492020469)
[XCUITest] iOS SDK Version set to '10.3'
[BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1493788465854 (15:14:25 GMT+1000 (AEST))
[iOSSim] Constructing iOS simulator for Xcode version 8.3.2 with udid '6E70CE66-8C94-4D85-B384-F6B418E2BD6E'
[XCUITest] Determining device to run tests on: udid: '6E70CE66-8C94-4D85-B384-F6B418E2BD6E', real device: false
[BaseDriver] Using local app '/private/tmp/Bett3ruat.app'
[BaseDriver] Event 'appConfigured' logged at 1493788466033 (15:14:26 GMT+1000 (AEST))
[XCUITest] Checking whether app '/private/tmp/Bett3ruat.app' is actually present on file system
[XCUITest] App is present
[iOS] Getting bundle ID from app '/private/tmp/Bett3ruat.app': 'au.com.amp.bett3r.UAT'
[XCUITest] Setting 'connectHardwareKeyboard' Simulator option to 'on'
[BaseDriver] Event 'resetStarted' logged at 1493788466038 (15:14:26 GMT+1000 (AEST))
[XCUITest] Reset: noReset is on. Leaving simulator as is
[BaseDriver] Event 'resetComplete' logged at 1493788466039 (15:14:26 GMT+1000 (AEST))
[iOSLog] Starting iOS 10.3 simulator log capture
[iOSLog] System log path: /Users/Vaishu/Library/Logs/CoreSimulator/6E70CE66-8C94-4D85-B384-F6B418E2BD6E/system.log
[BaseDriver] Event 'logCaptureStarted' logged at 1493788466143 (15:14:26 GMT+1000 (AEST))
[XCUITest] Setting up simulator
[iOS] No reason to set locale
[iOS] No iOS / app preferences to set
[XCUITest] App 'au.com.amp.bett3r.UAT' is already installed. No need to reinstall.
[XCUITest] Simulator with udid '6E70CE66-8C94-4D85-B384-F6B418E2BD6E' already booted
[BaseDriver] Event 'simStarted' logged at 1493788466310 (15:14:26 GMT+1000 (AEST))
[BaseDriver] Event 'appInstalled' logged at 1493788466310 (15:14:26 GMT+1000 (AEST))
[BaseDriver] Event 'wdaStartAttempted' logged at 1493788466312 (15:14:26 GMT+1000 (AEST))
[XCUITest] Using WDA path: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[XCUITest] Carthage found: '/usr/local/bin/carthage'
[XCUITest] Killing hanging processes
[XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=6E70CE66-8C94-4D85-B384-F6B418E2BD6E -configuration Debug IPHONEOS_DEPLOYMENT_TARGET=10.3' in directory '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Output from xcodebuild will be logged
[Xcode] Build settings from command line:
[Xcode] 
[XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[Xcode]     IPHONEOS_DEPLOYMENT_TARGET = 10.3
[Xcode] 
[Xcode] 
[Xcode] 2017-05-03 15:14:26.943 xcodebuild[7191:215364] [MT] DVTAssertions: ASSERTION FAILURE in /Library/Caches/com.apple.xbs/Sources/DVTFrameworks/DVTFrameworks-12153/DVTFoundation/MacroExpansion/DVTMacroDefinitionConditionSet.mm:154
[Xcode] Details:  stringRep should be a non-empty string, but it's an empty string
[Xcode] Object:   
[Xcode] Method:   +conditionSetFromStringRepresentation:getBaseMacroName:error:
[Xcode] Thread:   {number = 1, name = main}
[Xcode] Hints: 
[Xcode] 
[Xcode] Backtrace:
[Xcode]   0   -[DVTAssertionHandler handleFailureInMethod:object:fileName:lineNumber:assertionSignature:messageFormat:arguments:] (in DVTFoundation)
[Xcode]   1   _DVTAssertionHandler (in DVTFoundation)
[Xcode]   2   _DVTAssertionFailureHandler (in DVTFoundation)
[Xcode]   3   +[DVTMacroDefinitionConditionSet conditionSetFromStringRepresentation:getBaseMacroName:error:] (in DVTFoundation)
[Xcode]   4   -[DVTMacroDefinitionTable(XCMacroExpansionExtensions) _xc_setValue:forMacroName:errorHandler:] (in DevToolsCore)
[Xcode]   5   __108-[DVTMacroDefinitionTable(XCMacroExpansionExtensions) xc_setMacroNamesAndValuesFromDictionary:errorHandler:]_block_invoke (in DevToolsCore)
[Xcode]   6   __65-[__NSDictionaryI enumerateKeysAndObjectsWithOptions:usingBlock:]_block_invoke (in CoreFoundation)
[Xcode]   7   -[__NSDictionaryI enumerateKeysAndObjectsWithOptions:usingBlock:] (in CoreFoundation)
[Xcode]   8   -[DVTMacroDefinitionTable(XCMacroExpansionExtensions) xc_setMacroNamesAndValuesFromDictionary:errorHandler:] (in DevToolsCore)
[Xcode]   9   -[NSProcessInfo(XCMacroExpansionExtensions) xc_cachedEnvironmentAsMacroDefinitionTable] (in DevToolsCore)
[Xcode]  10   -[PBXTarget createMacroExpansionScopeWithBuildParameters:] (in DevToolsCore)
[Xcode]  11   -[PBXTarget cachedMacroExpansionScopeForBuildParameters:] (in DevToolsCore)
[Xcode]  12   -[PBXTarget expandedValueForString:forBuildParameters:] (in DevToolsCore)
[Xcode]  13   -[PBXNativeTarget fullProductNameForBuildParameters:] (in DevToolsCore)
[Xcode]  14   -[PBXNativeTarget fullProductNameForConfigurationNamed:] (in DevToolsCore)
[Xcode]  15   -[PBXTarget fullProductName] (in DevToolsCore)
[Xcode]  16   -[PBXReference setProducingTarget:] (in DevToolsCore)
[Xcode]  17   -[PBXTarget awakeFromPListUnarchiver:] (in DevToolsCore)
[Xcode]  18   -[PBXNativeTarget awakeFromPListUnarchiver:] (in DevToolsCore)
[Xcode]  19   -[NSArray makeObjectsPerformSelector:withObject:] (in CoreFoundation)
[Xcode]  20   -[PBXPListUnarchiver decodeRootObject] (in DevToolsCore)
[Xcode]  21   +[PBXProject projectWithFile:errorHandler:readOnly:] (in DevToolsCore)
[Xcode]  22   -[Xcode3Project initWithFilePath:extension:workspace:options:error:] (in DevToolsCore)
[Xcode]  23   __82+[IDEContainer _retainedContainerAtFilePath:fileDataType:workspace:options:error:]_block_invoke_2 (in IDEFoundation)
[Xcode]  24   _dispatch_client_callout (in libdispatch.dylib)
[Xcode]  25   _dispatch_barrier_sync_f_invoke (in libdispatch.dylib)
[Xcode]  26   DVTDispatchBarrierSync (in DVTFoundation)
[Xcode]  27   -[DVTDispatchLock performLockedBlock:] (in DVTFoundation)
[Xcode]  28   __82+[IDEContainer _retainedContainerAtFilePath:fileDataType:workspace:options:error:]_block_invoke (in IDEFoundation)
[Xcode]  29   __58-[DVTModelObjectGraph performBlockCoalescingModelChanges:]_block_invoke (in DVTFoundation)
[Xcode]  30   -[DVTModelGraphTransactionScope performTransaction:] (in DVTFoundation)
[Xcode]  31   -[DVTModelObjectGraph performBlockCoalescingModelChanges:] (in DVTFoundation)
[Xcode]  32   +[IDEContainer _retainedContainerAtFilePath:fileDataType:workspace:options:error:] (in IDEFoundation)
[Xcode]  33   +[IDEContainer retainedContainerAtFilePath:fileDataType:workspace:error:] (in IDEFoundation)
[Xcode]  34   -[IDEWorkspace _configureWrappedWorkspaceWithError:] (in IDEFoundation)
[Xcode]  35   __82+[IDEContainer _retainedContainerAtFilePath:fileDataType:workspace:options:error:]_block_invoke (in IDEFoundation)
[Xcode]  36   +[IDEContainer _retainedContainerAtFilePath:fileDataType:workspace:options:error:] (in IDEFoundation)
[Xcode]  37   +[IDEContainer retainedWrappedWorkspaceForContainerAtFilePath:fileDataType:error:] (in IDEFoundation)
[Xcode]  38   -[Xcode3CommandLineBuildTool _resolveInputOptionsWithTimingSection:] (in Xcode3Core)
[Xcode]  39   -[Xcode3CommandLineBuildTool run] (in Xcode3Core)
[Xcode]  40  0x000000010b84c2af (in xcodebuild)
[Xcode]  41   start (in libdyld.dylib)
[Xcode] 
[XCUITest] xcodebuild exited with code 'null' and signal 'SIGABRT'
[BaseDriver] Event 'wdaSessionAttempted' logged at 1493788467384 (15:14:27 GMT+1000 (AEST))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[XCUITest] Failed to create WDA session. Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1493788468391 (15:14:28 GMT+1000 (AEST))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[XCUITest] Failed to create WDA session. Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1493788469397 (15:14:29 GMT+1000 (AEST))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[XCUITest] Failed to create WDA session. Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1493788470404 (15:14:30 GMT+1000 (AEST))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[XCUITest] Failed to create WDA session. Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1493788471414 (15:14:31 GMT+1000 (AEST))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[XCUITest] Failed to create WDA session. Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1493788472423 (15:14:32 GMT+1000 (AEST))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[XCUITest] Failed to create WDA session. Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1493788473430 (15:14:33 GMT+1000 (AEST))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[XCUITest] Failed to create WDA session. Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1493788474438 (15:14:34 GMT+1000 (AEST))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[XCUITest] Failed to create WDA session. Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1493788475442 (15:14:35 GMT+1000 (AEST))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[XCUITest] Failed to create WDA session. Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1493788476448 (15:14:36 GMT+1000 (AEST))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[XCUITest] Failed to create WDA session. Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1493788477455 (15:14:37 GMT+1000 (AEST))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[XCUITest] Failed to create WDA session. Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1493788478460 (15:14:38 GMT+1000 (AEST))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[XCUITest] Failed to create WDA session. Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1493788479465 (15:14:39 GMT+1000 (AEST))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[XCUITest] Failed to create WDA session. Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1493788480472 (15:14:40 GMT+1000 (AEST))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[XCUITest] Failed to create WDA session. Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1493788481482 (15:14:41 GMT+1000 (AEST))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[XCUITest] Failed to create WDA session. Retrying...
[XCUITest] Unable to start WebDriverAgent session: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8100
[XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[XCUITest] Removing WDA application from device
[BaseDriver] Event 'wdaStartAttempted' logged at 1493788492572 (15:14:52 GMT+1000 (AEST))
[XCUITest] Using WDA path: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[XCUITest] Carthage found: '/usr/local/bin/carthage'
[XCUITest] Killing hanging processes
[XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=6E70CE66-8C94-4D85-B384-F6B418E2BD6E -configuration Debug IPHONEOS_DEPLOYMENT_TARGET=10.3' in directory '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Output from xcodebuild will be logged
[Xcode] Build settings from command line:
[Xcode]     IPHONEOS_DEPLOYMENT_TARGET = 10.3
[Xcode] 
[XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[Xcode] 
[Xcode] 
[Xcode] 2017-05-03 15:14:53.205 xcodebuild[7214:216403] [MT] DVTAssertions: ASSERTION FAILURE in /Library/Caches/com.apple.xbs/Sources/DVTFrameworks/DVTFrameworks-12153/DVTFoundation/MacroExpansion/DVTMacroDefinitionConditionSet.mm:154
[Xcode] Details:  stringRep should be a non-empty string, but it's an empty string
[Xcode] Object:   
[Xcode] Method:   +conditionSetFromStringRepresentation:getBaseMacroName:error:
[Xcode] Thread:   {number = 1, name = main}
[Xcode] Hints: 
[Xcode] 
[Xcode] Backtrace:
[Xcode]   0   -[DVTAssertionHandler handleFailureInMethod:object:fileName:lineNumber:assertionSignature:messageFormat:arguments:] (in DVTFoundation)
[Xcode]   1   _DVTAssertionHandler (in DVTFoundation)
[Xcode]   2   _DVTAssertionFailureHandler (in DVTFoundation)
[Xcode]   3   +[DVTMacroDefinitionConditionSet conditionSetFromStringRepresentation:getBaseMacroName:error:] (in DVTFoundation)
[Xcode]   4   -[DVTMacroDefinitionTable(XCMacroExpansionExtensions) _xc_setValue:forMacroName:errorHandler:] (in DevToolsCore)
[Xcode]   5   __108-[DVTMacroDefinitionTable(XCMacroExpansionExtensions) xc_setMacroNamesAndValuesFromDictionary:errorHandler:]_block_invoke (in DevToolsCore)
[Xcode]   6   __65-[__NSDictionaryI enumerateKeysAndObjectsWithOptions:usingBlock:]_block_invoke (in CoreFoundation)
[Xcode]   7   -[__NSDictionaryI enumerateKeysAndObjectsWithOptions:usingBlock:] (in CoreFoundation)
[Xcode]   8   -[DVTMacroDefinitionTable(XCMacroExpansionExtensions) xc_setMacroNamesAndValuesFromDictionary:errorHandler:] (in DevToolsCore)
[Xcode]   9   -[NSProcessInfo(XCMacroExpansionExtensions) xc_cachedEnvironmentAsMacroDefinitionTable] (in DevToolsCore)
[Xcode]  10   -[PBXTarget createMacroExpansionScopeWithBuildParameters:] (in DevToolsCore)
[Xcode]  11   -[PBXTarget cachedMacroExpansionScopeForBuildParameters:] (in DevToolsCore)
[Xcode]  12   -[PBXTarget expandedValueForString:forBuildParameters:] (in DevToolsCore)
[Xcode]  13   -[PBXNativeTarget fullProductNameForBuildParameters:] (in DevToolsCore)
[Xcode]  14   -[PBXNativeTarget fullProductNameForConfigurationNamed:] (in DevToolsCore)
[Xcode]  15   -[PBXTarget fullProductName] (in DevToolsCore)
[Xcode]  16   -[PBXReference setProducingTarget:] (in DevToolsCore)
[Xcode]  17   -[PBXTarget awakeFromPListUnarchiver:] (in DevToolsCore)
[Xcode]  18   -[PBXNativeTarget awakeFromPListUnarchiver:] (in DevToolsCore)
[Xcode]  19   -[NSArray makeObjectsPerformSelector:withObject:] (in CoreFoundation)
[Xcode]  20   -[PBXPListUnarchiver decodeRootObject] (in DevToolsCore)
[Xcode]  21   +[PBXProject projectWithFile:errorHandler:readOnly:] (in DevToolsCore)
[Xcode]  22   -[Xcode3Project initWithFilePath:extension:workspace:options:error:] (in DevToolsCore)
[Xcode]  23   __82+[IDEContainer _retainedContainerAtFilePath:fileDataType:workspace:options:error:]_block_invoke_2 (in IDEFoundation)
[Xcode]  24   _dispatch_client_callout (in libdispatch.dylib)
[Xcode]  25   _dispatch_barrier_sync_f_invoke (in libdispatch.dylib)
[Xcode]  26   DVTDispatchBarrierSync (in DVTFoundation)
[Xcode]  27   -[DVTDispatchLock performLockedBlock:] (in DVTFoundation)
[Xcode]  28   __82+[IDEContainer _retainedContainerAtFilePath:fileDataType:workspace:options:error:]_block_invoke (in IDEFoundation)
[Xcode]  29   __58-[DVTModelObjectGraph performBlockCoalescingModelChanges:]_block_invoke (in DVTFoundation)
[Xcode]  30   -[DVTModelGraphTransactionScope performTransaction:] (in DVTFoundation)
[Xcode]  31   -[DVTModelObjectGraph performBlockCoalescingModelChanges:] (in DVTFoundation)
[Xcode]  32   +[IDEContainer _retainedContainerAtFilePath:fileDataType:workspace:options:error:] (in IDEFoundation)
[Xcode]  33   +[IDEContainer retainedContainerAtFilePath:fileDataType:workspace:error:] (in IDEFoundation)
[Xcode]  34   -[IDEWorkspace _configureWrappedWorkspaceWithError:] (in IDEFoundation)
[Xcode]  35   __82+[IDEContainer _retainedContainerAtFilePath:fileDataType:workspace:options:error:]_block_invoke (in IDEFoundation)
[Xcode]  36   +[IDEContainer _retainedContainerAtFilePath:fileDataType:workspace:options:error:] (in IDEFoundation)
[Xcode]  37   +[IDEContainer retainedWrappedWorkspaceForContainerAtFilePath:fileDataType:error:] (in IDEFoundation)
[Xcode]  38   -[Xcode3CommandLineBuildTool _resolveInputOptionsWithTimingSection:] (in Xcode3Core)
[Xcode]  39   -[Xcode3CommandLineBuildTool run] (in Xcode3Core)
[Xcode]  40  0x0000000108f012af (in xcodebuild)
[Xcode]  41   start (in libdyld.dylib)
[Xcode] 
[XCUITest] xcodebuild exited with code 'null' and signal 'SIGABRT'
[BaseDriver] Event 'wdaSessionAttempted' logged at 1493788493626 (15:14:53 GMT+1000 (AEST))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[XCUITest] Failed to create WDA session. Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1493788494636 (15:14:54 GMT+1000 (AEST))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[XCUITest] Failed to create WDA session. Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1493788495641 (15:14:55 GMT+1000 (AEST))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[XCUITest] Failed to create WDA session. Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1493788496646 (15:14:56 GMT+1000 (AEST))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[XCUITest] Failed to create WDA session. Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1493788497652 (15:14:57 GMT+1000 (AEST))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[XCUITest] Failed to create WDA session. Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1493788498657 (15:14:58 GMT+1000 (AEST))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[XCUITest] Failed to create WDA session. Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1493788499666 (15:14:59 GMT+1000 (AEST))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[XCUITest] Failed to create WDA session. Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1493788500672 (15:15:00 GMT+1000 (AEST))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[XCUITest] Failed to create WDA session. Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1493788501677 (15:15:01 GMT+1000 (AEST))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[XCUITest] Failed to create WDA session. Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1493788502685 (15:15:02 GMT+1000 (AEST))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[XCUITest] Failed to create WDA session. Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1493788503697 (15:15:03 GMT+1000 (AEST))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[XCUITest] Failed to create WDA session. Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1493788504704 (15:15:04 GMT+1000 (AEST))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[XCUITest] Failed to create WDA session. Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1493788505709 (15:15:05 GMT+1000 (AEST))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[XCUITest] Failed to create WDA session. Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1493788506719 (15:15:06 GMT+1000 (AEST))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[XCUITest] Failed to create WDA session. Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1493788507723 (15:15:07 GMT+1000 (AEST))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[XCUITest] Failed to create WDA session. Retrying...
[XCUITest] Unable to start WebDriverAgent session: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8100
[XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[XCUITest] Removing WDA application from device
[XCUITest] Error: Unable to start WebDriverAgent session: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8100
    at XCUITestDriver.quitAndUninstall$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:374:15)
    at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
 Error: Unable to start WebDriverAgent session: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8100
    at XCUITestDriver.quitAndUninstall$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:374:15)
    at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: Unable to start WebDriverAgent session: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8100
    at XCUITestDriver.quitAndUninstall$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:374:15)
    at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session 500 53448 ms - 277 

If anyone of you have encountered above issue and have managed to get it working, could you please comment on how to fix it? 

Thanks in advance,
Vaishu

**Comment by mykola-mokhnach** [comment]
It looks like Xcode is broken on the machine. Either try to reinstall/upgrade Xcode or take another machine. Closing as not Appium-related
