### ISSUE TITLE
Unable to use driver.execute_script 'mobile: tap' in Ruby while testing on Android native app

### ISSUE THREAD

**Issue by santafebound** [appium/appium#8365]
## The problem

I'm unable to use the ``driver.execute_script 'mobile: tap'`` command in my Ruby script while testing a native Android application via apk format. I'm using Appium 1.6.4. Is this command not being supported anymore and if not, what is the alternative?

## Environment

```
    'appium-version'=> '1.6.4',
    'platformName'=> 'Android',
    'platformVersion'=> '6.0',
    'deviceName'=> '10.0.0.2:5555',
    'device' => 'android',
    'app' => 'C:/tindermation-apk/tinder.apk',
    'app-package' => 'com.tinder',
    'app-activity' => 'com.tinder.activities.ActivitySplashLoading_'
```

## Link to Appium logs

https://gist.github.com/santafebound/283652d4f5a9624964b6abb6576dc0d8

## Details / Code To Reproduce Issue [ Good To Have ]

Full code available here: https://github.com/santafebound/tindermation

I'm using Ruby. I believe the error is thrown at:

```ruby
def login_button
  sleep 1
  driver.execute_script 'mobile: tap', :x => 539, :y => 1464, :fingers => 1, :tapCount => 1, :duration => 0.5
  sleep 1
end
```

I believe it is the tap command that is no longer supported on my version of Appium (1.6.4). I'm using Android Developer Options to show the X,Y coordinates of my taps and selected a location that corresponds to a button I want to press but it doesn't work. At this stage I am able to open Tinder's main login screen but the tap is not executed and then Appium crashes. What could be going wrong?

**Comment by mykola-mokhnach** [comment]
Use TouchAction interface instead

**Comment by santafebound** [comment]
Thanks. Got it running it with ``Appium::TouchAction.new.tap( x: 539, y:1464, count: 3).release.perform``.
