### ISSUE TITLE
Appium not launching to a webpage on google chrome emulator

### ISSUE THREAD

**Issue by jassid1** [appium/appium#8371]
Hi,

Im struggling to launch to a website using eclipse appium and android virtual device. It opens the browser but doesnt navigate to the page i want it to. The URL address bar just says data;,

Any help would be appreciated been stuck on this for a while now.

Thank you.

**Comment by mykola-mokhnach** [comment]
Please fill out the default reporting form and attach all the necessary logs. Then reopen the issue

**Comment by jassid1** [comment]
How do i re open?

**Comment by jassid1** [comment]
re opened @mykola-mokhnach #8371
