### ISSUE TITLE
Appium not launching to a webpage on google chrome emulator #8371

### ISSUE THREAD

**Issue by jassid1** [appium/appium#8372]
## The problem

Im struggling to launch to a website using eclipse appium and android virtual device. It opens the browser but doesnt navigate to the page i want it to. The URL address bar just says data;,

When i eventually leave it, it just tries to run again. 

## Environment

* Appium version: 1.6.4
* Desktop OS/version used to run Appium: Windows 10 64bit
* Node.js version (unless using Appium.app|exe): Using Appium.exe
* Mobile platform/version under test: Tried this on android 6.0 (with and without google api x86 architecure.
* emulator/simulator: Android Studio
* Appium.app|exe:

## Link to Appium logs

https://gist.github.com/jassid1/041c303737ecb544c19b4126a5be8629

## Code To Reproduce Issue [ Good To Have ]

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.remote.CapabilityType;
import org.openqa.selenium.remote.DesiredCapabilities;

import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.android.AndroidElement;
import io.appium.java_client.remote.MobileCapabilityType;
import io.appium.java_client.remote.MobilePlatform;

public class RealDeviceChrome {
	
	@Test
	public void test() throws MalformedURLException, InterruptedException {

		DesiredCapabilities cap=new DesiredCapabilities();
		
		cap.setCapability(CapabilityType.PLATFORM,MobilePlatform.ANDROID);
		cap.setCapability(MobileCapabilityType.DEVICE_NAME, "Nexus5X1");
		cap.setCapability(MobileCapabilityType.BROWSER_NAME, "Chrome");
		cap.setCapability("appPackage", "com.android.chrome");
		cap.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, "100");
		
		AndroidDriver<AndroidElement> driver=new AndroidDriver<AndroidElement>(new URL("http://127.0.0.1:4723/wd/hub"),cap );
		
		driver.get("https://www.google.co.uk/");
		
	}
}

**Comment by jassid1** [comment]
#8372

**Comment by mykola-mokhnach** [comment]
the link to appium logs is broken

**Comment by jassid1** [comment]
@mykola-mokhnach  try now.

**Comment by mykola-mokhnach** [comment]
It looks like another chromedriver instance is still running and locks the port. Try to kill it manually.

**Comment by jassid1** [comment]
@mykola-mokhnach this only happens when i leave it though? ive tried restarting my system and started running this from fresh and same thing happens. At the first instance i get no error it just seems to hang. Sorry kind of new to this all.

**Comment by jassid1** [comment]
<img width="231" alt="capture" src="https://cloud.githubusercontent.com/assets/28344815/25698520/187ef106-30b7-11e7-93bc-dc717ef72ab0.PNG">

**Comment by mykola-mokhnach** [comment]
Can you attach the log from the first run (when it hangs)

**Comment by jassid1** [comment]
Sure,

https://gist.github.com/jassid1/5619713df1a87a59b25454993d23dfb4

**Comment by mykola-mokhnach** [comment]
It might be the version of chromedriver and the actual webview bundled to the emulator are not compatible. This is the reason why the driver freezes

**Comment by jassid1** [comment]
Ok, which version of chrome driver do you recommend? or is just a case of trial and error?

**Comment by mykola-mokhnach** [comment]
I assume google should provide the versions compatibility list somewhere. As you can see in the log the version of chromedriver used by your Appium build is 2.29

**Comment by jassid1** [comment]
ok so i tried chrome driver 2.28 with google.apk version 51.0.2704.81 (x86) still no luck :(

Even tried it with chrome driver 2.25 and nothing. (sigh)

There is no issue with my coding right?

completely put that in wrong issue.

**Comment by jassid1** [comment]
[adb logcat.txt](https://github.com/appium/appium/files/976093/adb.logcat.txt)


adb log cat from cmd

**Comment by mykola-mokhnach** [comment]
I see many stracktraces in the report. Try, probably, with some other emulator/on the other machine

**Comment by jassid1** [comment]
tried this with genymotion too does the exact same....

**Comment by mykola-mokhnach** [comment]
try to remove appPackage capability

**Comment by jassid1** [comment]
nope that didnt help either. it seems like its just waiting for a URL. but nothing happens frustrating.

**Comment by mykola-mokhnach** [comment]
Also I think you need to provide **avd** capability to set emulator name. deviceName is used to set real device names

**Comment by jassid1** [comment]
Ok, which method would i use for my code to pass that AVD capability ? Thank you

**Comment by dpgraham** [comment]
Closing this. If you're still experiencing this issue I can

**Comment by ramasharma** [comment]
Hi,
I am trying to launching the chrome browser on emulator.It is launching the chrome but not passing the url. I am using the following
Chrome apk>> com.android.chrome_65.0.3325.109-332510902_minAPI24(armeabi-v7a)(nodpi)_apkmirror.com (2).apk
Chrome Driver>>2.37
Appium >>1.7.2
Emulator Detail
target>>Android 7.0
Plateform>>7.0
Apilevel>>24
Cpu/Abi>>armeabi-v7a

I have placed the latest Chrome Driver>>2.37 in the path C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\chromedriver\win

First i was facing the same issue on real device.But When i had installed latest appium there this issuse is solved .But on emulator still facing the issue url is not passing into browser.

**Comment by ramasharma** [comment]
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\rasharma>appium -a 127.0.0.13 -p 5000
[Appium] Welcome to Appium v1.7.2
[Appium] Non-default server args:
[Appium]   address: 127.0.0.13
[Appium]   port: 5000
[Appium] Appium REST http interface listener started on 127.0.0.13:5000
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"browserName":"Chrome","
deviceName":"Android Emulator","platform":"ANDROID","platformName":"Android","ve
rsion":"7.0"},"capabilities":{"desiredCapabilities":{"browserName":"Chrome","dev
iceName":"Android Emulator","platform":"ANDROID","platformName":"Android","versi
on":"7.0"},"firstMatch":[{"browserName":"Chrome","platformName":"android"}]}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"browserName
":"Chrome","deviceName":"Android Emulator","platform":"ANDROID","platformName":"
Android","version":"7.0"},null,{"desiredCapabilities":{"browserName":"Chrome","d
eviceName":"Android Emulator","platform":"ANDROID","platformName":"Android","ver
sion":"7.0"},"firstMatch":[{"browserName":"Chrome","platformName":"android"}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1522832320397 (14:28:
40 GMT+0530 (India Standard Time))
[Appium] Merged W3C capabilities {"desiredCapabilities":{"browserName":"Chrome",
... into desiredCapabilities object {"browserName":"Chrome","deviceName":"Androi
d E...
[Appium] Creating new AndroidDriver (v1.37.0) session
[Appium] Capabilities:
[Appium]   browserName: Chrome
[Appium]   deviceName: Android Emulator
[Appium]   platform: ANDROID
[Appium]   platformName: android
[Appium]   version: 7.0
[BaseDriver] The following capabilities were provided, but are not recognized by
 appium: platform, version.
[BaseDriver] Session created with session id: 71a37be1-8255-4e88-8a67-914183960c
d4
[debug] [AndroidDriver] Getting Java version
[AndroidDriver] Java version is: 1.8.0_161
[AndroidDriver] We're going to run a Chrome-based session
[AndroidDriver] Chrome-type package and activity are com.android.chrome and com.
google.android.apps.chrome.Main
[ADB] Checking whether adb is present
[ADB] Using adb.exe from D:\Softwares\android-sdk_r24.4.1-windows\android-sdk-wi
ndows\platform-tools\adb.exe
[AndroidDriver] Retrieving device list
[debug] [ADB] Trying to find a connected android device
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[AndroidDriver] Using device: emulator-5554
[ADB] Checking whether adb is present
[debug] [ADB] Setting device id to emulator-5554
[AndroidDriver] App file was not listed, instead we're going to run com.android.
chrome directly on the device
[debug] [AndroidDriver] Checking whether package is present on the device
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'D:\Softwares\android-sdk_r24.4.1-windows\android-sdk-wind
ows\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","
pm","list","packages","com.android.chrome"]
[AndroidDriver] Starting Android session
[debug] [ADB] Running 'D:\Softwares\android-sdk_r24.4.1-windows\android-sdk-wind
ows\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","wait-for
-device"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'D:\Softwares\android-sdk_r24.4.1-windows\android-sdk-wind
ows\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","
echo","ping"]
[AndroidDriver] setDeviceLanguageCountry requires language or country.
[AndroidDriver] Got language: 'null' and country: 'null'
[debug] [Logcat] Starting logcat capture
[debug] [AndroidDriver] Pushing settings apk to device...
[debug] [ADB] Getting install status for io.appium.settings
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'D:\Softwares\android-sdk_r24.4.1-windows\android-sdk-wind
ows\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","
pm","list","packages","io.appium.settings"]
[debug] [ADB] App is installed
[debug] [ADB] Getting package info for io.appium.settings
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'D:\Softwares\android-sdk_r24.4.1-windows\android-sdk-wind
ows\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","
dumpsys","package","io.appium.settings"]
[ADB] Checking whether aapt is present
[ADB] Using aapt.exe from D:\Softwares\android-sdk_r24.4.1-windows\android-sdk-w
indows\build-tools\28.0.0-preview\aapt.exe
[debug] [ADB] The installed 'io.appium.settings' package does not require upgrad
e (5 >= 5)
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'D:\Softwares\android-sdk_r24.4.1-windows\android-sdk-wind
ows\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","
getprop","ro.build.version.sdk"]
[debug] [ADB] Current device property 'ro.build.version.sdk': 24
[debug] [ADB] Device API level: 24
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'D:\Softwares\android-sdk_r24.4.1-windows\android-sdk-wind
ows\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","
dumpsys","package","io.appium.settings"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'D:\Softwares\android-sdk_r24.4.1-windows\android-sdk-wind
ows\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","
pm","dump","io.appium.settings"]
[debug] [ADB] Got the following command chunks to execute: pm,grant,io.appium.se
ttings,android.permission.WRITE_SETTINGS,;,pm,grant,io.appium.settings,android.p
ermission.ACCESS_MOCK_LOCATION,;
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'D:\Softwares\android-sdk_r24.4.1-windows\android-sdk-wind
ows\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","
pm","grant","io.appium.settings","android.permission.WRITE_SETTINGS",";","pm","g
rant","io.appium.settings","android.permission.ACCESS_MOCK_LOCATION",";"]
[debug] [ADB] Running 'D:\Softwares\android-sdk_r24.4.1-windows\android-sdk-wind
ows\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","
pm","grant","io.appium.settings","android.permission.WRITE_SETTINGS",";","pm","g
rant","io.appium.settings","android.permission.ACCESS_MOCK_LOCATION",";"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'D:\Softwares\android-sdk_r24.4.1-windows\android-sdk-wind
ows\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","
ps"]
[debug] [ADB] Device API level: 24
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'D:\Softwares\android-sdk_r24.4.1-windows\android-sdk-wind
ows\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","
appops","set","io.appium.settings","android:mock_location","allow"]
[debug] [AndroidDriver] Pushing unlock helper app to device...
[debug] [ADB] Getting install status for io.appium.unlock
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'D:\Softwares\android-sdk_r24.4.1-windows\android-sdk-wind
ows\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","
pm","list","packages","io.appium.unlock"]
[debug] [ADB] App is installed
[debug] [ADB] Getting package info for io.appium.unlock
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'D:\Softwares\android-sdk_r24.4.1-windows\android-sdk-wind
ows\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","
dumpsys","package","io.appium.unlock"]
[ADB] Checking whether aapt is present
[debug] [ADB] The installed 'io.appium.unlock' package does not require upgrade
(2 >= 2)
[ADB] Getting device platform version
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'D:\Softwares\android-sdk_r24.4.1-windows\android-sdk-wind
ows\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","
getprop","ro.build.version.release"]
[debug] [ADB] Current device property 'ro.build.version.release': 7.0
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'D:\Softwares\android-sdk_r24.4.1-windows\android-sdk-wind
ows\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","
wm","size"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'D:\Softwares\android-sdk_r24.4.1-windows\android-sdk-wind
ows\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","
getprop","ro.product.model"]
[debug] [ADB] Current device property 'ro.product.model': sdk_phone_armv7
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'D:\Softwares\android-sdk_r24.4.1-windows\android-sdk-wind
ows\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","
getprop","ro.product.manufacturer"]
[debug] [ADB] Current device property 'ro.product.manufacturer': unknown
[AndroidDriver] No app sent in, not parsing package/activity
[debug] [AndroidDriver] No app capability. Assuming it is already on the device
[debug] [AndroidDriver] Running fast reset (stop and clear)
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'D:\Softwares\android-sdk_r24.4.1-windows\android-sdk-wind
ows\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","
am","force-stop","com.android.chrome"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'D:\Softwares\android-sdk_r24.4.1-windows\android-sdk-wind
ows\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","
pm","clear","com.android.chrome"]
[debug] [AndroidBootstrap] Watching for bootstrap disconnect
[debug] [ADB] Forwarding system: 4724 to device: 4724
[debug] [ADB] Running 'D:\Softwares\android-sdk_r24.4.1-windows\android-sdk-wind
ows\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","forward"
,"tcp:4724","tcp:4724"]
[debug] [UiAutomator] Starting UiAutomator
[debug] [UiAutomator] Moving to state 'starting'
[debug] [UiAutomator] Parsing uiautomator jar
[debug] [UiAutomator] Found jar name: 'AppiumBootstrap.jar'
[debug] [ADB] Running 'D:\Softwares\android-sdk_r24.4.1-windows\android-sdk-wind
ows\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","push","C
:\\Users\\rasharma\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\a
ppium-android-bootstrap\\bootstrap\\bin\\AppiumBootstrap.jar","/data/local/tmp/"
]
[debug] [ADB] Attempting to kill all uiautomator processes
[debug] [ADB] Getting all processes with uiautomator
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'D:\Softwares\android-sdk_r24.4.1-windows\android-sdk-wind
ows\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","
ps"]
[ADB] No uiautomator process found to kill, continuing...
[debug] [UiAutomator] Starting UIAutomator
[debug] [ADB] Creating ADB subprocess with args: ["-P",5037,"-s","emulator-5554"
,"shell","uiautomator","runtest","AppiumBootstrap.jar","-c","io.appium.android.b
ootstrap.Bootstrap","-e","pkg","com.android.chrome","-e","disableAndroidWatchers
",false,"-e","acceptSslCerts",false]
[debug] [UiAutomator] Moving to state 'online'
[AndroidBootstrap] Android bootstrap socket is now connected
[debug] [ADB] Getting connected devices...
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Loading json...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'D:\Softwares\android-sdk_r24.4.1-windows\android-sdk-wind
ows\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","
dumpsys","window"]
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Registered crash watchers.
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Client connected
[AndroidDriver] Screen already unlocked, doing nothing
[AndroidDriver] Starting a chrome-based browser session
[debug] [AndroidDriver] A port was not given, using random port: 8000
[debug] [Chromedriver] Changed state to 'starting'
[Chromedriver] Set chromedriver binary as: C:\Users\rasharma\AppData\Roaming\npm
\node_modules\appium\node_modules\appium-chromedriver\chromedriver\win\chromedri
ver.exe
[debug] [Chromedriver] Killing any old chromedrivers, running: FOR /F "usebackq
tokens=5" %a in (`netstat -nao ^| findstr /R /C:"8000 "`) do (FOR /F "usebackq"
%b in (`TASKLIST /FI "PID eq %a" ^| findstr /I chromedriver.exe`) do (IF NOT %b=
="" TASKKILL /F /PID %a))
[Chromedriver] No old chromedrivers seemed to exist
[debug] [Chromedriver] Cleaning any old adb forwarded port socket connections
[debug] [ADB] List forwarding ports
[debug] [ADB] Running 'D:\Softwares\android-sdk_r24.4.1-windows\android-sdk-wind
ows\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","forward"
,"--list"]
[Chromedriver] Spawning chromedriver with: C:\Users\rasharma\AppData\Roaming\npm
\node_modules\appium\node_modules\appium-chromedriver\chromedriver\win\chromedri
ver.exe --url-base=wd/hub --port=8000 --adb-port=5037 --verbose
[debug] [Chromedriver] Chromedriver version: '2.33.506120'
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8000/wd/h
ub/status] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"\",\"stat
us\":0,\"value\":{\"build\":{\"version\":\"alpha\"},\"os\":{\"arch\":\"x86_64\",
\"name\":\"Windows NT\",\"version\":\"6.1.7601 SP1\"}}}"
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8000/w
d/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPacka
ge":"com.android.chrome","androidDeviceSerial":"emulator-5554"}}}

**Comment by neerajlad** [comment]
Hi

I am trying to start Android mWeb automation on Chrome but throwing error:

Appium : 1.7.2
Chrome Browser version : 65.0.3325.109
Java_Client : 5.0.4

**Note: Chrome version <65  our mWeb script is working fine.** 

Error:

[debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"48340ba35616eda2789e33369529be0b\",\"status\":13,\"value\":{\"message\":\"unknown error: Failed to run adb command, is the adb server running?\\n  (Session info: chrome=65.0.3325.109)\\n  (Driver info: chromedriver=2.33.506106 (8a06c39c4582fbfbab6966dbb1c38a9173bfb1a2),platform=Mac OS X 10.13.2 x86_64)\"}}"

[Chromedriver] Error: An unknown server-side error occurred while processing the command. (Original error: unknown error: Failed to run adb command, is the adb server running?

  (Session info: chrome=65.0.3325.109)

  (Driver info: chromedriver=2.33.506106 (8a06c39c4582fbfbab6966dbb1c38a9173bfb1a2),platform=Mac OS X 10.13.2 x86_64))

    at JWProxy.command$ (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:176:15)

    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)

    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)

    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)

    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)

    at <anonymous>

 { Error: An unknown server-side error occurred while processing the command. (Original error: unknown error: Failed to run adb command, is the adb server running?

  (Session info: chrome=65.0.3325.109)

  (Driver info: chromedriver=2.33.506106 (8a06c39c4582fbfbab6966dbb1c38a9173bfb1a2),platform=Mac OS X 10.13.2 x86_64))

    at JWProxy.command$ (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:176:15)

    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)

    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)

    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)

    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)

    at <anonymous>

  status: 13,

  value: 

   { message: 'unknown error: Failed to run adb command, is the adb server running?\n  (Session info: chrome=65.0.3325.109)\n  (Driver info: chromedriver=2.33.506106 (8a06c39c4582fbfbab6966dbb1c38a9173bfb1a2),platform=Mac OS X 10.13.2 x86_64)' },

  httpCode: 200 }
