### ISSUE TITLE
unable to run the app in simulators 

### ISSUE THREAD

**Issue by Manikanta29** [appium/appium#8374]
## The problem

Able to run the app on real devices. But, in simulators, not able to run the same app. when I run the Integration app its working good in simulators. 

## Environment

* Appium version:1.6.4@beta 2
* Mobile platform/version under test: IOS 10.3
* Real device or emulator/simulator: Iphone Emulator
* Xcode: 8.3.2

## Link to Appium logs
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/manikantav/Documents/workspace_New/app.ipa","buldleId":"com.abc.xyz","noReset":"false","realDeviceLogger":"/usr/local/lib/node_modules/deviceconsole/deviceconsole","platformVersion":"10.3","automationName":"XCUITEST","platformName":"iOS","deviceName":"iPhone 6","launchTimeout":500000}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/manikantav/Documents/workspace_New/app.ipa","buldleId":"com.abc.xyz","noReset":"false","realDeviceLogger":"/usr/local/lib/node_modules/deviceconsole/deviceconsole","platformVersion":"10.3","automationName":"XCUITEST","platformName":"iOS","deviceName":"iPhone 6","launchTimeout":500000},null,null,null,null]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1493893294152 (15:51:34 GMT+0530 (IST))
[Appium] Creating new XCUITestDriver (v2.27.1) session
[Appium] Capabilities:
[Appium]   app: '/Users/manikantav/Documents/workspace_New/app.ipa'
[Appium]   buldleId: 'com.abc.xyz'
[Appium]   noReset: 'false'
[Appium]   realDeviceLogger: '/usr/local/lib/node_modules/deviceconsole/deviceconsole'
[Appium]   platformVersion: '10.3'
[Appium]   automationName: 'XCUITEST'
[Appium]   platformName: 'iOS'
[Appium]   deviceName: 'iPhone 6'
[Appium]   launchTimeout: 500000
[debug] [XCUITest] XCUITestDriver version: 2.27.1
[BaseDriver] Capability 'noReset' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] The following capabilities were provided, but are not recognized by appium: buldleId, realDeviceLogger.
[BaseDriver] Session created with session id: 26b63cdc-7c88-46e4-8fb6-2ddfaa196af8
[debug] [XCUITest] Xcode version set to '8.3.2' (tools v8.3.2.0.1.1492020469)
[debug] [XCUITest] iOS SDK Version set to '10.3'
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1493893296579 (15:51:36 GMT+0530 (IST))
[iOSSim] Constructing iOS simulator for Xcode version 8.3.2 with udid '75BB43CC-DF70-43C2-B360-2CFE03AB0418'
[XCUITest] Determining device to run tests on: udid: '75BB43CC-DF70-43C2-B360-2CFE03AB0418', real device: false
[BaseDriver] Using local app '/Users/manikantav/Documents/workspace_New/app.ipa'
[debug] [BaseDriver] Copying local zip to tmp dir
[debug] [BaseDriver] Unzipping /var/folders/8t/147j7y0j0c3gc14728jmcvmm0000gp/T/201744-24155-sa0blz.3h7vu3ow29/appium-app.zip
[debug] [BaseDriver] Testing zip archive: /var/folders/8t/147j7y0j0c3gc14728jmcvmm0000gp/T/201744-24155-sa0blz.3h7vu3ow29/appium-app.zip
[BaseDriver] Unzipped local app to '/var/folders/8t/147j7y0j0c3gc14728jmcvmm0000gp/T/201744-24155-sa0blz.3h7vu3ow29/Payload/ClaimReporter.app'
[debug] [BaseDriver] Event 'appConfigured' logged at 1493893302551 (15:51:42 GMT+0530 (IST))
[debug] [XCUITest] Checking whether app '/var/folders/8t/147j7y0j0c3gc14728jmcvmm0000gp/T/201744-24155-sa0blz.3h7vu3ow29/Payload/ClaimReporter.app' is actually present on file system
[debug] [XCUITest] App is present
[debug] [iOS] Getting bundle ID from app '/var/folders/8t/147j7y0j0c3gc14728jmcvmm0000gp/T/201744-24155-sa0blz.3h7vu3ow29/Payload/ClaimReporter.app': 'com.GallagherBassett.firstconnect.test'
[debug] [BaseDriver] Event 'resetStarted' logged at 1493893302577 (15:51:42 GMT+0530 (IST))
[XCUITest] Not scrubbing third party app in anticipation of uninstall
[debug] [BaseDriver] Event 'resetComplete' logged at 1493893302796 (15:51:42 GMT+0530 (IST))
[debug] [iOSLog] Starting iOS 10.3 simulator log capture
[debug] [iOSLog] System log path: /Users/manikantav/Library/Logs/CoreSimulator/75BB43CC-DF70-43C2-B360-2CFE03AB0418/system.log
[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1493893303018 (15:51:43 GMT+0530 (IST))
[XCUITest] Setting up simulator
[debug] [iOS] No reason to set locale
[debug] [iOS] No iOS / app preferences to set
[debug] [XCUITest] Reset requested. Removing app with id 'com.GallagherBassett.firstconnect.test' from the device
[XCUITest] Simulator with udid '75BB43CC-DF70-43C2-B360-2CFE03AB0418' already booted
[debug] [BaseDriver] Event 'simStarted' logged at 1493893303441 (15:51:43 GMT+0530 (IST))
[debug] [XCUITest] Installing /var/folders/8t/147j7y0j0c3gc14728jmcvmm0000gp/T/201744-24155-sa0blz.3h7vu3ow29/Payload/ClaimReporter.app on Simulator with UUID '75BB43CC-DF70-43C2-B360-2CFE03AB0418'...
[debug] [XCUITest] The app has been installed successfully.
[debug] [BaseDriver] Event 'appInstalled' logged at 1493893315873 (15:51:55 GMT+0530 (IST))
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1493893315877 (15:51:55 GMT+0530 (IST))
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'
[debug] [XCUITest] Killing hanging processes
[debug] [XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=75BB43CC-DF70-43C2-B360-2CFE03AB0418 -configuration Debug IPHONEOS_DEPLOYMENT_TARGET=10.3' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[debug] [XCUITest] Output from xcodebuild will not be logged
[debug] [XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [XCUITest] Log file for xcodebuild test: /Users/manikantav/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/A15C1CDC-B85B-4EC1-A452-3A59D34F67EB/Session-WebDriverAgentRunner-2017-05-04_155209-MxECCX.log
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"state\" : \"success\",\n    \"os\" : {\n      \"name\" : \"iOS\",\n      \"version\" : \"10.3\"\n    },\n    \"ios\" : {\n      \"simulatorVersion\" : \"10.3\",\n      \"ip\" : \"172.17.2.103\"\n    },\n    \"build\" : {\n      \"time\" : \"May  1 2017 20:52:34\"\n    }\n  },\n  \"sessionId\" : \"BDB58CBB-B71D-4555-AE08-DBAEA4CC17A5\",\n  \"status\" : 0\n}"
[debug] [XCUITest] WebDriverAgent running on ip '172.17.2.103'
[debug] [XCUITest] WebDriverAgent successfully started after 22159ms
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1493893338374 (15:52:18 GMT+0530 (IST))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.GallagherBassett.firstconnect.test","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":true,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[debug] [JSONWP Proxy] Got response with status 200: {"value":"Failed to launch com.GallagherBassett.firstconnect.test application","sessionId":"BDB58CBB-B71D-4555-AE08-DBAEA4CC17A5","status":13}
[debug] [XCUITest] Failed to create WDA session. Retrying...
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1493893581542 (15:56:21 GMT+0530 (IST))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.GallagherBassett.firstconnect.test","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":true,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}

**Comment by mykola-mokhnach** [comment]
Do you try to install the same package on real device and on simulator?

**Comment by Manikanta29** [comment]
@mykola-mokhnach 

Yes, the same package working fine on the real device. I commented the UDID and edit the device name as  "iPhone 6"  simulator and running the code. 

cap.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone 6");
//cap.setCapability(MobileCapabilityType.UDID, "XXXXXXXXXXXX");

**Comment by mykola-mokhnach** [comment]
Closed as non Appium-related issue. Simulator requires separate build flavour.
