### ISSUE TITLE
Appium can't get session info from running WDA on iOS device

### ISSUE THREAD

**Issue by Schwabeneder** [appium/appium#8376]
## The problem

When I start the Appium Server and try to get a session to test an iOS application on a real device, I get an error: "Error: Unable to start WebDriverAgent session: Unexpected token < in JSON at position 0". I did quite some research and I am sure the WDA is up and running fine on the device, but somehow the Appium Server does not get a suitable response for [GET http://localhost:8100/status]

## Environment

* Appium version: 1.6.4
* Desktop OS/version used to run Appium: 10.12.3
* Node.js version: 6.10.2
* Mobile platform/version under test: 10.2
* Real device or emulator/simulator: Real Device
* xcode: 8.3.2

## Details

Appium is starting up with no difficulties and everything seems find, there is no error, but Appium seems to be waiting for a response of WDA in vain:

[Appium] Welcome to Appium v1.6.4
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/softwaretest_2/Desktop/IPA/TestingApp.ipa","automationName":"XCUITest","bundleId":"com.ottobock.vienna.TestingApp","deviceName":"OB iPad Air 2","keychainPassword":"1234","keychainPath":"/Users/softwaretest_2/Desktop/MyKeychain.keychain","launchTimeout":"120000","platformName":"iOS","platformVersion":"10.2","showIOSLog":"false","udid":"ad9d9ee861f59e9b166b7b8020f0e76925f6a816","updatedWDABundleId":"io.appium.WebDriverAgentRunner","xcodeConfigFile":"/Users/softwaretest_2/Desktop/AppiumIosFiles/xconfig.xcconfig","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/softwaretest_2/Desktop/IPA/TestingApp.ipa","automationName":"XCUITest","bundleId":"com.ottobock.vienna.TestingApp","deviceName":"OB iPad Air 2","keychainPassword":"1234","keychainPath":"/Users/softwaretest_2/Desktop/MyKeychain.keychain","launchTimeout":"120000","platformName":"iOS","platformVersion":"10.2","showIOSLog":"false","udid":"ad9d9ee861f59e9b166b7b8020f0e76925f6a816","updatedWDABundleId":"io.appium.WebDriverAgentRunner","xcodeConfigFile":"/Users/softwaretest_2/Desktop/AppiumIosFiles/xconfig.xcconfig","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null,null,null]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1493887470902 (10:44:30 GMT+0200 (CEST))
[Appium] Creating new XCUITestDriver (v2.27.2) session
[Appium] Capabilities:
[Appium]   app: '/Users/softwaretest_2/Desktop/IPA/TestingApp.ipa'
[Appium]   automationName: 'XCUITest'
[Appium]   bundleId: 'com.xyz.vienna.TestingApp'
[Appium]   deviceName: 'OB iPad Air 2'
[Appium]   keychainPassword: '1234'
[Appium]   keychainPath: '/Users/softwaretest_2/Desktop/MyKeychain.keychain'
[Appium]   launchTimeout: '120000'
[Appium]   platformName: 'iOS'
[Appium]   platformVersion: '10.2'
[Appium]   showIOSLog: 'false'
[Appium]   udid: 'ad9d9ee861f59e9b166b7b8020f0e76925f6a816'
[Appium]   updatedWDABundleId: 'io.appium.WebDriverAgentRunner'
[Appium]   xcodeConfigFile: '/Users/softwaretest_2/Desktop/AppiumIosFiles/xconfig.xcconfig'
[Appium]   newCommandTimeout: 0
[Appium]   connectHardwareKeyboard: true
[debug] [XCUITest] XCUITestDriver version: 2.27.2
[BaseDriver] Capability 'showIOSLog' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] Session created with session id: 64fd4f9f-99e9-4890-b72a-879d7d875a65
[debug] [XCUITest] Xcode version set to '8.3.2' (tools v8.3.2.0.1.1492020469)
[debug] [XCUITest] iOS SDK Version set to '10.3'
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1493887470986 (10:44:30 GMT+0200 (CEST))
[debug] [XCUITest] Available devices: ad9d9ee861f59e9b166b7b8020f0e76925f6a816
[debug] [XCUITest] Creating iDevice object with udid 'ad9d9ee861f59e9b166b7b8020f0e76925f6a816'
[XCUITest] Determining device to run tests on: udid: 'ad9d9ee861f59e9b166b7b8020f0e76925f6a816', real device: true
[BaseDriver] Using local app '/Users/softwaretest_2/Desktop/IPA/TestingApp.ipa'
[debug] [BaseDriver] Copying local zip to tmp dir
[debug] [BaseDriver] Unzipping /var/folders/6v/j04fz8x542104cv1w1gq21ph0000gp/T/201744-1090-he4289.42hmxfajor/appium-app.zip
[debug] [BaseDriver] Testing zip archive: /var/folders/6v/j04fz8x542104cv1w1gq21ph0000gp/T/201744-1090-he4289.42hmxfajor/appium-app.zip
[BaseDriver] Unzipped local app to '/var/folders/6v/j04fz8x542104cv1w1gq21ph0000gp/T/201744-1090-he4289.42hmxfajor/Payload/OBUiTestingApp.app'
[debug] [BaseDriver] Event 'appConfigured' logged at 1493887471262 (10:44:31 GMT+0200 (CEST))
[debug] [XCUITest] Checking whether app '/var/folders/6v/j04fz8x542104cv1w1gq21ph0000gp/T/201744-1090-he4289.42hmxfajor/Payload/OBUiTestingApp.app' is actually present on file system
[debug] [XCUITest] App is present
[debug] [BaseDriver] Event 'resetStarted' logged at 1493887471265 (10:44:31 GMT+0200 (CEST))
[debug] [XCUITest] Reset: running ios real device reset flow
[debug] [BaseDriver] Event 'resetComplete' logged at 1493887471266 (10:44:31 GMT+0200 (CEST))
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1493887471378 (10:44:31 GMT+0200 (CEST))
[XCUITest] Setting up real device
[debug] [XCUITest] Reset requested. Removing app with id 'com.xyz.vienna.TestingApp' from the device
[debug] [XCUITest] Installing '/var/folders/6v/j04fz8x542104cv1w1gq21ph0000gp/T/201744-1090-he4289.42hmxfajor/Payload/TestingApp.app' on device with UUID 'ad9d9ee861f59e9b166b7b8020f0e76925f6a816'...
[debug] [XCUITest] The app has been installed successfully.
[debug] [BaseDriver] Event 'appInstalled' logged at 1493887472716 (10:44:32 GMT+0200 (CEST))
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1493887472718 (10:44:32 GMT+0200 (CEST))
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'
[debug] [XCUITest] Successfully updated '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj/project.pbxproj' with bundle id 'io.appium.WebDriverAgentRunner'
[debug] [XCUITest] Killing hanging processes
[debug] [XCUITest] Setting security for iOS device
[debug] [XCUITest] Using Xcode configuration file: '/Users/softwaretest_2/Desktop/AppiumIosFiles/xconfig.xcconfig'
[debug] [XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=ad9d9ee861f59e9b166b7b8020f0e76925f6a816 -configuration Debug IPHONEOS_DEPLOYMENT_TARGET=10.2 -xcconfig /Users/softwaretest_2/Desktop/AppiumIosFiles/xconfig.xcconfig' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[debug] [XCUITest] Output from xcodebuild will not be logged
[debug] [XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[debug] [XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [XCUITest] Log file for xcodebuild test: /Users/softwaretest_2/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/D9693BE6-7975-40E6-8528-C25499BE2A18/Session-WebDriverAgentRunner-2017-05-04_104438-riXtB0.log
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
...
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [XCUITest] Log file for xcodebuild test: /Users/softwaretest_2/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/D9693BE6-7975-40E6-8528-C25499BE2A18/Session-WebDriverAgentRunner-2017-05-04_104541-FXJcNO.log
[debug] [XCUITest] Unable to connect to running WebDriverAgent: Unexpected token < in JSON at position 0
[XCUITest] Getting status of WebDriverAgent on device timed out. Continuing
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1493887542187 (10:45:42 GMT+0200 (CEST))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [XCUITest] Failed to create WDA session. Retrying...
...

I am sure the WDA is perfectly up and running at the time on the device, because I see the WDA starting up (short black screen on device) and after that when I try to call `http://localhost:8100/status` "by hand" (using postman) I get the expected result 

> {
  "value": {
    "state": "success",
    "os": {
      "name": "iOS",
      "version": "10.2.1"
    },
    "ios": {
      "simulatorVersion": "10.2.1",
      "ip": null
    },
    "build": {
      "time": "Apr 27 2017 15:09:01"
    }
  },
  "sessionId": "182CF6C5-52CC-44F6-BBF6-73F8408ECED2",
  "status": 0
}

I can even open a connection by hand using [POST http://localhost:8100/session]
and the following capabilities in the body

> {"desiredCapabilities":
> {
>   "bundleId": "com.xyz.vienna.TestingApp",
>   "platformName": "iOS",
>   "platformVersion": "10.2",
>   "deviceName": "OB iPad Air 2",
>   "automationName": "XCUITest",
>   "udid": "ad9d9ee861f59e9b166b7b8020f0e76925f6a816",
>   "updatedWDABundleId": "io.appium.WebDriverAgentRunner",
>   "keychainPath": "/Users/softwaretest_2/Desktop/MyKeychain.keychain",
>   "keychainPassword": "password",
>   "xcodeConfigFile": "/Users/softwaretest_2/Desktop/AppiumIosFiles/xconfig.xcconfig",
>   "launchTimeout": "120000",
>   "showIOSLog": "false"
> }}

which starts the application and returns like expected

> {
>   "value": {
>     "sessionId": "EF41545F-820C-4ABE-A177-6A1AEAC4CA17",
>     "capabilities": {
>       "device": "ipad",
>       "browserName": "TestingApp",
>       "sdkVersion": "10.2.1",
>       "CFBundleIdentifier": "com.xyz.vienna.TestingApp"
>     }
>   },
>   "sessionId": "EF41545F-820C-4ABE-A177-6A1AEAC4CA17",
>   "status": 0
> }

I really don't know how to continue.
 
## Link to Appium logs

gist seems to be down, I will add logs when it is available for me

**Comment by mykola-mokhnach** [comment]
We don't connect to WDA directly if it is running on a real device, but rather use iproxy. It would be interesting to see the xcodebuild log.

**Comment by Schwabeneder** [comment]
Xcode logs:
[debug] [XCUITest] Output from xcodebuild will be logged
[debug] [XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[Xcode] Build settings from command line:
[Xcode]     IPHONEOS_DEPLOYMENT_TARGET = 10.2
[Xcode] 
[Xcode] Build settings from configuration file '/Users/softwaretest_2/Desktop/AppiumIosFiles/xconfig.xcconfig':
[Xcode]     CODE_SIGN_IDENTITY = iPhone Developer
[Xcode]     DEVELOPMENT_TEAM = HS75UL7UV8
[Xcode] 
[Xcode] 
[debug] [XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[Xcode] 2017-05-04 13:03:50.560 xcodebuild[2975:49838]  DeveloperPortal: Using pre-existing current store at URL (file:///Users/softwaretest_2/Library/Developer/Xcode/DeveloperPortal%208.3.2.db).
[Xcode] 
[Xcode] === BUILD TARGET WebDriverAgentLib OF PROJECT WebDriverAgent WITH CONFIGURATION Debug ===
[Xcode] 
[Xcode] 
[Xcode] Check dependencies
[Xcode] 
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[Xcode] 
[Xcode] 
[Xcode] === BUILD TARGET WebDriverAgentRunner OF PROJECT WebDriverAgent WITH CONFIGURATION Debug ===
[Xcode] 
[Xcode] 
[Xcode] Check dependencies
[Xcode] 
[Xcode] 
[Xcode] ** TEST BUILD SUCCEEDED **
[Xcode] 
[Xcode] 
[debug] [XCUITest] Log file for xcodebuild test: /Users/softwaretest_2/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/9C73FAD6-984C-415F-AABA-E07B2F893C6C/Session-WebDriverAgentRunner-2017-05-04_130350-q2pq1c.log
[Xcode] 2017-05-04 13:03:50.833 xcodebuild[2975:49889]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
[Xcode] /Users/softwaretest_2/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/9C73FAD6-984C-415F-AABA-E07B2F893C6C/Session-WebDriverAgentRunner-2017-05-04_130350-q2pq1c.log
[Xcode] 
[Xcode] 2017-05-04 13:03:50.834 xcodebuild[2975:49836] [MT] IDETestOperationsObserverDebug: (95FB2DEB-1897-4311-9050-F3306E0B3B0D) Beginning test session WebDriverAgentRunner-95FB2DEB-1897-4311-9050-F3306E0B3B0D at 2017-05-04 13:03:50.834 with Xcode 8E2002 on target <DVTiOSDevice: 0x7f9b173035b0> {
[Xcode] 		deviceSerialNumber:         DMPSVBBAHG5F
[Xcode] 		identifier:                 ad9d9ee861f59e9b166b7b8020f0e76925f6a816
[Xcode] 		deviceClass:                iPad
[Xcode] 		deviceName:                 OB iPad Air 2
[Xcode] 		deviceIdentifier:           ad9d9ee861f59e9b166b7b8020f0e76925f6a816
[Xcode] 		productVersion:             10.2.1
[Xcode] 		buildVersion:               14D27
[Xcode] 		deviceSoftwareVersion:      10.2.1 (14D27)
[Xcode] 		deviceArchitecture:         arm64
[Xcode] 		deviceTotalCapacity:        27919773696
[Xcode] 		deviceAvailableCapacity:    21500231680
[Xcode] 		deviceIsTransient:          NO
[Xcode] 		ignored:                    NO
[Xcode] 		deviceIsBusy:               NO
[Xcode] 		deviceIsActivated:          YES
[Xcode] 		deviceActivationState:      Activated
[Xcode] 		isPasscodeLocked:           NO
[Xcode] 		deviceType:                 <DVTDeviceType:0x7f9b16ab30b0 Xcode.DeviceType.iPhone>
[Xcode] 		supportedDeviceFamilies:    (
[Xcode]     1,
[Xcode]     2
[Xcode] )
[Xcode] 		applications:              (null)
[Xcode] 		provisioningProfiles:      (null)
[Xcode] 		activityProgress:          -2
[Xcode] 		activityTitle:             
[Xcode] 		hasInternalSupport:        NO
[Xcode] 		isSupportedOS:             YES
[Xcode] 		developerDiskMountError:   (null)
[Xcode] (null)
[Xcode] 	bootArgs:                  <unavailable>
[Xcode] 		} (10.2.1 (14D27))
[Xcode] 
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[Xcode] writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/6v/j04fz8x542104cv1w1gq21ph0000gp/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/171e6f3cc9eb72666d58e9b0ee7cefcf/ad9d9ee861f59e9b166b7b8020f0e76925f6a816/ManifestCache.plist
[Xcode]

**Comment by mykola-mokhnach** [comment]
xcodebuild log is stored into separate files. You can see their locations in the corresponding log records, like this one:

> [debug] [XCUITest] Log file for xcodebuild test: /Users/softwaretest_2/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/D9693BE6-7975-40E6-8528-C25499BE2A18/Session-WebDriverAgentRunner-2017-05-04_104438-riXtB0.log

**Comment by Schwabeneder** [comment]
Here the log file
[Session-WebDriverAgentRunner-2017-05-04_104438-riXtB0.log.txt](https://github.com/appium/appium/files/976049/Session-WebDriverAgentRunner-2017-05-04_104438-riXtB0.log.txt)

**Comment by imurchie** [comment]
This is an issue with a proxy that doesn't allow connections. If you, while the test is running, try curling to the url it will output what is happening.

**Comment by imurchie** [comment]
https://github.com/appium/appium/issues/7014

**Comment by Schwabeneder** [comment]
thanks for your fast and accurate help, it was the company proxy, configuring no_proxy
`export no_proxy="localhost,127.0.0.1,localaddress,.localdomain.com"` helped
