### ISSUE TITLE
Android: Setup crashes on Appium 1.6.5 beta

### ISSUE THREAD

**Issue by vjmaiky** [appium/appium#8377]
## The problem

Setup crashes on Appium 1.6.5 beta

## Environment

* Appium 1.6.5 beta
* Last Appium version that did not exhibit the issue (if applicable): 1.6.4
* Node.js version (unless using Appium.app|exe): 6.9.1
* Mobile platform/version under test: Android
* Real device or emulator/simulator: simulator

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
https://gist.github.com/vjmaiky/fdfb94511a534deeaccca1dc96ac536d

## Code To Reproduce Issue [ Good To Have ]
        File appDir = new File("src/test/java");
     File app = new File(appDir, "Today Calendar_com.underwood.calendar_beta.apk");

        capabilities.setCapability("device", "Simulator");
        capabilities.setCapability("deviceName", "Nexus 5");
        capabilities.setCapability("platformName", "Android");
        capabilities.setCapability("automationName", "Appium");
        capabilities.setCapability("platformVersion", "6.0.1");
        capabilities.setCapability("newCommandTimeout", 120);
        capabilities.setCapability("udid", "192.168.92.101:5555");
        capabilities.setCapability("fullReset", true);
       capabilities.setCapability("appActivity", "com.android.calendar.AllInOneActivity");
        capabilities.setCapability("appPackage", "com.underwood.calendar_beta");
        capabilities.setCapability("app", app.getAbsolutePath());
//        capabilities.setCapability("automationName", "uiautomator2");

        <dependency>
            <groupId>io.appium</groupId>
            <artifactId>java-client</artifactId>
            <version>5.0.0-BETA6</version>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>3.3.1</version>
            <scope>compile</scope>
        </dependency>

On 1.6.4 worked without capabilities.setCapability("automationName", "uiautomator2"); with that capability was some bug regarding permissions. Now on 1.6.5 beta is not working at all...

**Comment by mykola-mokhnach** [comment]
This looks like Window-specific bug, since the path to the apk does not look good:
> [debug] [ADB] Running 'D:\Automation\sdk\platform-tools\adb.exe' with args: ["-P
",5037,"-s","192.168.92.101:5555","shell","pm","install","-r","\\data\\local\\tm
p\\77f64ea16e3ee9ea90ed964a12102fe9.apk"]

**Comment by mykola-mokhnach** [comment]
@jlipps FYI

**Comment by mykola-mokhnach** [comment]
@sravanmedarapu FYI

**Comment by imurchie** [comment]
That should be there. We pushed it.
```
[debug] [ADB] Running 'D:\Automation\sdk\platform-tools\adb.exe' with args: ["-P
",5037,"-s","192.168.92.101:5555","push","D:\\Automation\\workspace\\NewAndroidT
est\\src\\test\\java\\Emma-prodautomation.apk","\\data\\local\\tmp\\77f64ea16e3e
e9ea90ed964a12102fe9.apk"]
```

**Comment by vjmaiky** [comment]
issue is no longer reproducible; cab be closed; thanks
