### ISSUE TITLE
XCUITest: If use capabilities fullReset = true and method launchApp, app will be reset every launch during session

### ISSUE THREAD

**Issue by hepilt** [appium/appium#8378]
## The problem

If I use capabilities "fullReset": true and method launchApp, app will be re-installed every launch after close. Is this correct behavior? How can I to avoid it?

## Environment

* Appium version: 1.6.4
* Desktop OS/version used to run Appium: MacOS 10.11.6
* Node.js version: v7.9.0
* Mobile platform/version under test: iOs 10.2.1
* Real device or emulator/simulator: Real Device
* xcode: 8.2.1

## Link to Appium logs

[HTTP] --> POST /wd/hub/session/0f8562c5-5942-4c56-8b5b-af00260ff4ca/appium/app/launch {}
[MJSONWP] Calling AppiumDriver.launchApp() with args: ["0f8562c5-5942-4c56-8b5b-af00260ff4ca"]
[XCUITest] Executing command 'launchApp'
[XCUITest] iOS SDK Version set to '10.2'
[BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1493899185254 (14:59:45 GMT+0300 (MSK))
[XCUITest] Available devices: 8447c7f53f040568c8d83ed0069a7411643ba865
[XCUITest] Creating iDevice object with udid '8447c7f53f040568c8d83ed0069a7411643ba865'
[XCUITest] Determining device to run tests on: udid: '8447c7f53f040568c8d83ed0069a7411643ba865', real device: true
[BaseDriver] Using local app '/var/folders/6g/g251_rrn00q25v01v50w5p_8sxw8m5/T/201744-22299-1gjkxqm.a7fhvt2o6r/Payload/Test.app'
[BaseDriver] Event 'appConfigured' logged at 1493899185522 (14:59:45 GMT+0300 (MSK))
[XCUITest] Checking whether app '/var/folders/6g/g251_rrn00q25v01v50w5p_8sxw8m5/T/201744-22299-1gjkxqm.a7fhvt2o6r/Payload/Test.app' is actually present on file system
[XCUITest] App is present
[BaseDriver] Event 'resetStarted' logged at 1493899185523 (14:59:45 GMT+0300 (MSK))
[XCUITest] Reset: running ios real device reset flow
[XCUITest] Reset: fullReset requested. Will try to uninstall the app 'com.test.Test'.
[XCUITest] Reset: removed 'com.test.Test'
[BaseDriver] Event 'resetComplete' logged at 1493899186724 (14:59:46 GMT+0300 (MSK))
[iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[BaseDriver] Event 'logCaptureStarted' logged at 1493899187038 (14:59:47 GMT+0300 (MSK))
[XCUITest] Setting up real device
[XCUITest] Installing '/var/folders/6g/g251_rrn00q25v01v50w5p_8sxw8m5/T/201744-22299-1gjkxqm.a7fhvt2o6r/Payload/Test.app' on device with UUID '8447c7f53f040568c8d83ed0069a7411643ba865'...
[XCUITest] The app has been installed successfully.
[BaseDriver] Event 'appInstalled' logged at 1493899209617 (15:00:09 GMT+0300 (MSK))
[BaseDriver] Event 'wdaStartAttempted' logged at 1493899209619 (15:00:09 GMT+0300 (MSK))

**Comment by mykola-mokhnach** [comment]
Yes the behaviour is correct. 

> How can I to avoid it?

Depending on what you want to achieve.

**Comment by hepilt** [comment]
@mykola-mokhnach I want to reset app only after session initiation.

**Comment by mykola-mokhnach** [comment]
you cannot terminate the app without terminating the driver. This is how the stuff works

**Comment by hepilt** [comment]
@mykola-mokhnach I did it by using closeApp, but then to launch app I use launchApp and app will be re-installed. I do not terminating driver session.

**Comment by hepilt** [comment]
up
