### ISSUE TITLE
Appium Server parallel Execution on mac  

### ISSUE THREAD

**Issue by Elangopalakrishnan** [appium/appium#8379]
## Issue:

How to kill/Stop particular appium server which is running one particular port.

## Environment

* Appium version (or git revision) that exhibits the issue: Appium 1.6.4
* Desktop OS/version used to run Appium: macOS Seirra 10.12.2 
* Mobile platform/version under test: iOS Real Device and Simulator
* Real device or emulator/simulator: iOS Simulators and iOS Real Device version 10.2.1

## Details

I'm running 2 appium server in different port numbers fro two different devices.

1st Appium server:

It is for iOS Simulator, Port is 4727 , 

2nd Appium server:

It is for iOS Real Device like iPhone, Port is 4725.

Two different server is running as expected and can execute the test cases.
But After execution i need to stop the appium sever otherwise it will run longer.
So i need to stop particular port's appium server.

For example , if i finished test run in 4727 port appium server means , i need to stop that particular appium server only, do not stop all appium server.

now i'm using terminal command to kill appium server:
**killAll -c node**

when i run this, it will stop all appium server, Is there any terminal command available to stop particular appium server?

Thanks in Advance!
Elango

**Comment by mykola-mokhnach** [comment]
There is **fuser** command line utility, which allows to print process ids listening on the particular port
