### ISSUE TITLE
Appium fails on resume after sending app to the background if Launch Mode is single task and a second activity is on top when suspending

### ISSUE THREAD

**Issue by jvillacorta** [appium/appium#8380]
## The problem

Sending app that uses a single task as launch mode (_android:launchMode="singleTask">_) into the background causes Appium to fail when resuming the app if a different activity was on top when the app was suspended.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4 and 1.6.3
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: OSX 10.12.4
* Node.js version (unless using Appium.app|exe): v7.6.0
* Mobile platform/version under test: Android 6.0
* Real device or emulator/simulator: Nexus 5
* Appium CLI or Appium.app|exe: Appium CLI and Appium Desktop

## Details

My test case involves suspending the app while an activity is on top of the main app activity, on resume I need to verify how the dismissal of the activity due to the singleTask property was handled by our SDK (Object of test) 

Appium is expecting the same activity that was on top on suspend to be on top on resume which will not be the case for a single task application.

## Link to Appium logs

https://gist.github.com/jvillacorta/ae758f6662215d6bc7baa9e1614bb849#file-appium-log

## Code To Reproduce Issue

driver.background_app(1)

**Comment by mykola-mokhnach** [comment]
The logic there is simple - we remember the current activity, emulate clicking of Home button and then launch the previously remembered activity. Do you have better ideas on how to improve this logic?

**Comment by mykola-mokhnach** [comment]
I also remember there was a bug there what the app was forcefully restarted before being restored. It is fixed in Appium 1.6.5-beta.

**Comment by jvillacorta** [comment]
In my case allowing to specify an activity to wait for can be helpful and more flexible for other test cases.  Default value could be the last activity on top.

**Comment by dpgraham** [comment]
I don't think the core team will have time to implement a feature like that but we could possibly accept a pull request.
