### ISSUE TITLE
Could not start the session with Appium 1.6.4 on Android.

### ISSUE THREAD

**Issue by bigulya90** [appium/appium#8382]
## The problem

I am running my test cases and Appium just launches my apk, and fails with error: 
~~~~
WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Error occured while starting App. Original error: <apk name> never started. 
~~~~

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Last Appium version that did not exhibit the issue (if applicable):1.5.3
* Desktop OS/version used to run Appium: macOS Sierra 10.12.1
* Node.js version (unless using Appium.app|exe): v6.10.2
* Mobile platform/version under test: Android M
* Real device or emulator/simulator: real device = Note5 N920A
* Appium CLI or Appium.app|exe: 

## Details
I am not able to run any test cases. I just upgrade my Appium from 1.5.3 to 1.6.4 and it stop working. I was running successfully same tests on 1.5.3 with same device. 

## Link to Appium logs
https://www.dropbox.com/s/wuq7aflh81l0gsy/appium_log.txt?dl=0

**Comment by mykola-mokhnach** [comment]
Set the name of the main activity as **appActivity** capability

**Comment by bigulya90** [comment]
works. Thanks.
