### ISSUE TITLE
[XCUITest] Failed to create WDA session. Retrying...

### ISSUE THREAD

**Issue by Akapylechka** [appium/appium#8383]
## The problem

Try Launch Appium inspector, but app doesn't open (Tries to open, but closes)
Logs loops on create WDA session. 
## Environment

* Appium version (or git revision) that exhibits the issue: 1.0.0
* Last Appium version that did not exhibit the issue (if applicable): -
* Desktop OS/version used to run Appium: 10.12.4
* Node.js version (unless using Appium.app|exe): 
* Mobile platform/version under test: iOS 10.3
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: app

## Details

My first attempts with Appium: Please forgive and understand))

## Link to Appium logs

https://gist.github.com/Akapylechka/27f006777d947727596e9b553475e832

**Comment by dpgraham** [comment]
Have you reviewed the documentation?

https://github.com/appium/appium/blob/master/docs/en/appium-setup/running-on-osx.md

**Comment by Akapylechka** [comment]
Yes, of course) Seems to be doing everything right

**Comment by imurchie** [comment]
Are you trying to run on a simulator? Is the app built for a simulator? It looks like an `ipa`, which generally is not built to be able to run.

Appium has installed the app. Can you manually open it?

**Comment by Akapylechka** [comment]
Facepalm, sorry, just with android there was no problem

**Comment by imurchie** [comment]
Apple seems to go out of its way to make it difficult. :(

**Comment by dpgraham** [comment]
@imurchie Maybe we should check the extensions of iOS Apps and log a warning if they're using an ipa with an iOS Simulator?

**Comment by dongguader** [comment]
I ran into the same issue after macOS's 10.12.4 update.
