### ISSUE TITLE
sendkeys () not working properly 

### ISSUE THREAD

**Issue by vijaykumarkk92** [appium/appium#8385]
hi 

i am trying to send some values to a text view field of an android application ( ex: abcdefgh@gmail.com) but  on a real device/phone i can observe only few characters are printing(ex: abdfg@gm... like this), missing with many characters 

i am using 
appium ,nodejs are latest version's
java 1.8.0_91
 android device(micromax) 5.1 version

but these issue is not there when i use micromax version 5.0 and  appium ,nodejs are latest version's
java 1.8.0_91

waiting for a reply which solves this issue

**Comment by mykola-mokhnach** [comment]
Please fill out the issue reporting form, provide Appium log, screenshots and code examples. then reopen the issue

**Comment by Aby-pal** [comment]
I am facing the same issue as sendkeys skip some characters of an input String. Some times entered a character twice and skipped others. It is happening dynamically, any character can be miss in each new run. Any suggestion would be helpful. Thanks.
Appium:- v1.12.1
