### ISSUE TITLE
Press method of TouchAction class not working with Uiautomator2

### ISSUE THREAD

**Issue by vermad** [appium/appium#8387]
## The problem

We had to implement the toast message text verification, so switched to uiautomator2 and that works fine, but a new issue emerged and now our previously working code to perform swipe operations using press method of touchaction class is no longer working since moved to uiautomator2.

## Environment

* Appium version : 1.6.4
* Desktop OS/version used to run Appium: Mac OSX Yosemite
* Node.js version : v7.10.0
* Mobile platform/version under test: Android Marshmallow (6.0)
* Real device or emulator/simulator: Both

## Link to Appium logs
https://gist.github.com/vermad/97004078b843e08c9914ce7672cd0971

## Code To Reproduce Issue [ Good To Have ]

@AndroidFindBy(id = "com.test.mobile.ui:id/reg_email")
public MobileElement sampleMobileElement;

swipe(sampleMobileElement,UP);

public void swipe(MobileElement element, Direction direction) {

		Dimension size = element.getSize();
		Point eLocation = element.getLocation();
		int eRight = size.getWidth() - 1;
		int eBottem = size.getHeight() - 1;
		int eLeft = eLocation.getX() + 1;
		int eTop = eLocation.getY() + 1;

		try {
			TouchAction tAction = new TouchAction(getMobileDriver());
			switch (direction) {
			case DOWN:
				tAction.press(element, eLeft, eTop).waitAction(pressTime).moveTo(0, eBottem - 1).release().perform();
				break;
			case UP:
				tAction.press(element, eLeft, eBottem).waitAction(pressTime).moveTo(0, -eTop - 1).release().perform();
				break;
			case LEFT:
				tAction.press(element, eRight, eBottem).waitAction(pressTime).moveTo(-eLeft - 1, 0).release().perform();
				break;
			case RIGHT:
				tAction.press(element, eLeft, eBottem).waitAction(pressTime).moveTo(eRight - 1, 0).release().perform();
				break;
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

**Comment by mykola-mokhnach** [comment]
Don't you think that 1000000 ms to wait is a bit too much?

**Comment by vermad** [comment]
Sorry Folks, My Bad. I am closing up the issue, as observed getMobileDriver that we are using is the wrapper for AndroidDriver but this was type casted with AppiumDriver and that's what the issue was. We've replaced it with AndroidDriver and this thing starts working fine.
