### ISSUE TITLE
Could not get logs on iOS physical device

### ISSUE THREAD

**Issue by patw0929** [appium/appium#8388]
## The problem

I'm try to print logs by `.log('syslog')` on iPhone 6s physical device, but it always print `[]` empty array. But at the same time & same code, when I execute it on iPhone 6s **simulator**, it works. Any idea? Thank you.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Last Appium version that did not exhibit the issue (if applicable): n/a
* Desktop OS/version used to run Appium: macOS Sierra 10.12.4
* Node.js version (unless using Appium.app|exe): v7.2.1
* Mobile platform/version under test: Physical device is iOS 10.3.1, simulator one is 10.3
* Real device or emulator/simulator: Both
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs

https://gist.github.com/patw0929/f27efe3248c9874ef423725a9fedb0f0

**Comment by mykola-mokhnach** [comment]
1. Did you set the **realDeviceLogger** capability?
2. There was a bug in log collection, which has been fixed not so long ago. Try Appium 1.6.5-beta to make sure the stuff works as expected.

**Comment by imurchie** [comment]
Yes. Until 1.6.5-beta if your device had a different time (specifically, an earlier time) than the Appium server, it would not find the logs at all.

**Comment by patw0929** [comment]
Hey guys, thanks for help!
I already upgraded to `appium 1.6.5-beta`, and using the `deviceconsole` as `realDeviceLogger`.
But the log is still printed as empty array only on my physical device.

The appium logs updated here:
https://gist.github.com/patw0929/f27efe3248c9874ef423725a9fedb0f0#file-physical-1-6-5-beta

**Comment by mykola-mokhnach** [comment]
Have you checked whether any log records are received if deviceconsole is just executed from the Terminal?

**Comment by patw0929** [comment]
Yes, the `deviceconsole` could print the specific log as expected when I'm testing the physical device, but not print that log when testing on simulator device. 🤔

**Comment by mykola-mokhnach** [comment]
This is expected. This utility only collects logs for real devices
What if you change the path in capabilities to /usr/local/lib/node_modules/deviceconsole/deviceconsole?

**Comment by patw0929** [comment]
I changed the `realDeviceLogger` to  `/Users/patw/.nvm/versions/node/v7.2.1/lib/node_modules/deviceconsole/deviceconsole` (I'm using the nvm, and install the `deviceconsole` with `-g`), but the situation is the same as before.

**Comment by mykola-mokhnach** [comment]
Try to install **idevicesyslog** utility from **libimobiledevice** package (HEAD version should be installed) and see how it works then. The **realDeviceLogger** has been deprecated since 1.6.5 so you can remove it. And please attach full Appium log if it didn't work.

**Comment by patw0929** [comment]
Wow, it works! @mykola-mokhnach, thanks a lot!

I installed the `libimobiledevice` of `1.2.0` version before, but now the HEAD version works good.
(`brew install --HEAD libimobiledevice`)

**Comment by mykola-mokhnach** [comment]
I'm happy to help
