### ISSUE TITLE
 Failed to start an Appium session info: [debug] Error: com.example.android.contactmanager/.ContactManager never st arted. Current: com.example.android.contactmanager/.ContactManager,

### ISSUE THREAD

**Issue by LiuQhahah** [appium/appium#8391]
**how to solve?**

info: Welcome to Appium v1.4.16 (REV ae6877eff263066b26328d457bd285c0cc62430d)
info: Appium REST http interface listener started on 0.0.0.0:4723
info: [debug] Non-default server args: {"sessionOverride":true}
info: Console LogLevel: debug
info: --> POST /wd/hub/session {"capabilities":{"alwaysMatch":{"platformVersion"
:"6.0","appPackage":"com.example.android.contactmanager","platformName":"Android
","appActivity":".ContactManager","deviceName":"LEY7A07010003928"},"firstMatch":
[]},"desiredCapabilities":{"platformVersion":"6.0","appPackage":"com.example.and
roid.contactmanager","platformName":"Android","appActivity":".ContactManager","d
eviceName":"LEY7A07010003928"}}
info: Client User-Agent string: Python http auth
info: [debug] Didn't get app but did get Android package, will attempt to launch
 it on the device
info: [debug] Creating new appium session eb34071b-5484-4a96-acb8-0807a9f7bf49
info: Starting android appium
info: [debug] Getting Java version
info: Java version is: 1.8.0_111
info: [debug] Checking whether adb is present
info: [debug] Using adb from D:\Android\sdk\platform-tools\adb.exe
warn: No app capability, can't parse package/activity
info: [debug] Using fast reset? true
info: [debug] Preparing device for session
info: [debug] Not checking whether app is present since we are assuming it's alr
eady on the device
info: Retrieving device
info: [debug] Trying to find a connected android device
info: [debug] Getting connected devices...
info: [debug] executing cmd: D:\Android\sdk\platform-tools\adb.exe devices
info: [debug] 1 device(s) connected
info: Found device LEY7A07010003928
info: [debug] Setting device id to LEY7A07010003928
info: [debug] Waiting for device to be ready and to respond to shell commands (t
imeout = 5)
info: [debug] executing cmd: D:\Android\sdk\platform-tools\adb.exe -s LEY7A07010
003928 wait-for-device
info: [debug] executing cmd: D:\Android\sdk\platform-tools\adb.exe -s LEY7A07010
003928 shell "echo 'ready'"
info: [debug] Starting logcat capture
info: [debug] Getting device API level
info: [debug] executing cmd: D:\Android\sdk\platform-tools\adb.exe -s LEY7A07010
003928 shell "getprop ro.build.version.sdk"
info: [debug] Device is at API Level 23
info: Device API level is: 23
info: [debug] Extracting strings for language: default
info: [debug] Apk doesn't exist locally
info: [debug] Could not get strings, but it looks like we had an old strings fil
e anyway, so ignoring
info: [debug] executing cmd: D:\Android\sdk\platform-tools\adb.exe -s LEY7A07010
003928 shell "rm -rf /data/local/tmp/strings.json"
info: [debug] Not uninstalling app since server not started with --full-reset
info: [debug] Skipping install since we launched with a package instead of an ap
p path
info: [debug] Forwarding system:4724 to device:4724
info: [debug] executing cmd: D:\Android\sdk\platform-tools\adb.exe -s LEY7A07010
003928 forward tcp:4724 tcp:4724
info: [debug] Pushing appium bootstrap to device...
info: [debug] executing cmd: D:\Android\sdk\platform-tools\adb.exe -s LEY7A07010
003928 push "D:\\Program_File\\Appium\\node_modules\\appium\\build\\android_boot
strap\\AppiumBootstrap.jar" /data/local/tmp/
info: [debug] Pushing settings apk to device...
info: [debug] executing cmd: D:\Android\sdk\platform-tools\adb.exe -s LEY7A07010
003928 install "D:\Program_File\Appium\node_modules\appium\build\settings_apk\se
ttings_apk-debug.apk"
info: [debug] Pushing unlock helper app to device...
info: [debug] executing cmd: D:\Android\sdk\platform-tools\adb.exe -s LEY7A07010
003928 install "D:\Program_File\Appium\node_modules\appium\build\unlock_apk\unlo
ck_apk-debug.apk"
info: Starting App
info: [debug] Attempting to kill all 'uiautomator' processes
info: [debug] Getting all processes with 'uiautomator'
info: [debug] executing cmd: D:\Android\sdk\platform-tools\adb.exe -s LEY7A07010
003928 shell "ps 'uiautomator'"
info: [debug] No matching processes found
info: [debug] Running bootstrap
info: [debug] spawning: D:\Android\sdk\platform-tools\adb.exe -s LEY7A0701000392
8 shell uiautomator runtest AppiumBootstrap.jar -c io.appium.android.bootstrap.B
ootstrap -e pkg com.example.android.contactmanager -e disableAndroidWatchers fal
se
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
info: [debug] [UIAUTOMATOR STDOUT] io.appium.android.bootstrap.Bootstrap:
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRun
ner
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.andro
id.bootstrap.Bootstrap
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 1
info: [debug] [BOOTSTRAP] [debug] Socket opened on port 4724
info: [debug] [BOOTSTRAP] [debug] Appium Socket Server Ready
info: [debug] [BOOTSTRAP] [debug] Loading json...
info: [debug] [BOOTSTRAP] [debug] Registered crash watchers.
info: [debug] Waking up device if it's not alive
info: [debug] Pushing command to appium work queue: ["wake",{}]
info: [debug] [BOOTSTRAP] [debug] Client connected
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action"
:"wake","params":{}}
info: [debug] executing cmd: D:\Android\sdk\platform-tools\adb.exe -s LEY7A07010
003928 shell "dumpsys window"
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: wake
info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":true}
info: [debug] Screen already unlocked, continuing.
info: [debug] Pushing command to appium work queue: ["getDataDir",{}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action"
:"getDataDir","params":{}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: getDataDir
info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":"\/data\
/local\/tmp"}
info: [debug] dataDir set to: /data/local/tmp
info: [debug] Pushing command to appium work queue: ["compressedLayoutHierarchy"
,{"compressLayout":false}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action"
:"compressedLayoutHierarchy","params":{"compressLayout":false}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: compressedLayoutHierarchy
info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":false}
info: [debug] Getting device API level
info: [debug] executing cmd: D:\Android\sdk\platform-tools\adb.exe -s LEY7A07010
003928 shell "getprop ro.build.version.sdk"
info: [debug] Device is at API Level 23
info: [debug] executing cmd: D:\Android\sdk\platform-tools\adb.exe -s LEY7A07010
003928 shell "am start -S -a android.intent.action.MAIN -c android.intent.catego
ry.LAUNCHER -f 0x10200000 -n com.example.android.contactmanager/.ContactManager"

info: [debug] Waiting for pkg "com.example.android.contactmanager" and activity
".ContactManager" to be focused
info: [debug] Getting focused package and activity
info: [debug] executing cmd: D:\Android\sdk\platform-tools\adb.exe -s LEY7A07010
003928 shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing cmd: D:\Android\sdk\platform-tools\adb.exe -s LEY7A07010
003928 shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing cmd: D:\Android\sdk\platform-tools\adb.exe -s LEY7A07010
003928 shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing cmd: D:\Android\sdk\platform-tools\adb.exe -s LEY7A07010
003928 shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing cmd: D:\Android\sdk\platform-tools\adb.exe -s LEY7A07010
003928 shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing cmd: D:\Android\sdk\platform-tools\adb.exe -s LEY7A07010
003928 shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing cmd: D:\Android\sdk\platform-tools\adb.exe -s LEY7A07010
003928 shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing cmd: D:\Android\sdk\platform-tools\adb.exe -s LEY7A07010
003928 shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing cmd: D:\Android\sdk\platform-tools\adb.exe -s LEY7A07010
003928 shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing cmd: D:\Android\sdk\platform-tools\adb.exe -s LEY7A07010
003928 shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing cmd: D:\Android\sdk\platform-tools\adb.exe -s LEY7A07010
003928 shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing cmd: D:\Android\sdk\platform-tools\adb.exe -s LEY7A07010
003928 shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing cmd: D:\Android\sdk\platform-tools\adb.exe -s LEY7A07010
003928 shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing cmd: D:\Android\sdk\platform-tools\adb.exe -s LEY7A07010
003928 shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing cmd: D:\Android\sdk\platform-tools\adb.exe -s LEY7A07010
003928 shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing cmd: D:\Android\sdk\platform-tools\adb.exe -s LEY7A07010
003928 shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing cmd: D:\Android\sdk\platform-tools\adb.exe -s LEY7A07010
003928 shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing cmd: D:\Android\sdk\platform-tools\adb.exe -s LEY7A07010
003928 shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing cmd: D:\Android\sdk\platform-tools\adb.exe -s LEY7A07010
003928 shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing cmd: D:\Android\sdk\platform-tools\adb.exe -s LEY7A07010
003928 shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing cmd: D:\Android\sdk\platform-tools\adb.exe -s LEY7A07010
003928 shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing cmd: D:\Android\sdk\platform-tools\adb.exe -s LEY7A07010
003928 shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing cmd: D:\Android\sdk\platform-tools\adb.exe -s LEY7A07010
003928 shell "dumpsys window windows"
error: com.example.android.contactmanager/.ContactManager never started. Current
: com.example.android.contactmanager/.ContactManager,
info: [debug] Stopping logcat capture
info: [debug] Logcat terminated with code null, signal SIGTERM
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"shutdown"}
info: [debug] [BOOTSTRAP] [debug] Got command of type SHUTDOWN
info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":"OK, shu
tting down"}
info: [debug] Sent shutdown command, waiting for UiAutomator to stop...
info: [debug] [BOOTSTRAP] [debug] Closed client connection
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=.
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRun
ner
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.andro
id.bootstrap.Bootstrap
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 0
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
info: [debug] [UIAUTOMATOR STDOUT] Test results for WatcherResultPrinter=.
info: [debug] [UIAUTOMATOR STDOUT] Time: 22.077
info: [debug] [UIAUTOMATOR STDOUT] OK (1 test)
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: -1
info: [debug] UiAutomator shut down normally
info: [debug] Cleaning up android objects
info: [debug] Cleaning up appium session
error: Failed to start an Appium session, err was: Error: com.example.android.co
ntactmanager/.ContactManager never started. Current: com.example.android.contact
manager/.ContactManager,
info: [debug] Error: com.example.android.contactmanager/.ContactManager never st
arted. Current: com.example.android.contactmanager/.ContactManager,
    at [object Object].<anonymous> (D:\Program_File\Appium\node_modules\appium\n
ode_modules\appium-adb\lib\adb.js:1314:12)
    at [object Object].<anonymous> (D:\Program_File\Appium\node_modules\appium\n
ode_modules\appium-adb\lib\adb.js:1258:7)
    at [object Object].<anonymous> (D:\Program_File\Appium\node_modules\appium\n
ode_modules\appium-adb\lib\adb.js:180:9)
    at ChildProcess.exithandler (child_process.js:204:7)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"
A new session could not be created. (Original error: com.example.android.contact
manager/.ContactManager never started. Current: com.example.android.contactmanag
er/.ContactManager,)","origValue":"com.example.android.contactmanager/.ContactMa
nager never started. Current: com.example.android.contactmanager/.ContactManager
,"},"sessionId":null}
info: <-- POST /wd/hub/session 500 28703.972 ms - 374

**Comment by mykola-mokhnach** [comment]
Appium 1.4 is outdated and is not supported anymore. Please use 1.6.4
