### ISSUE TITLE
is iPhone 5s incompatible device for XCTest?

### ISSUE THREAD

**Issue by mayureshshirodkar** [appium/appium#8393]
## The problem

I am having 2 phones iPhone 5s(10.3.1) and iPhone 6(10.2.1).
Running command : 
xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=<udid>' test

Works fine on iPhone 6:
<script src="https://gist.github.com/mayureshshirodkar/c8d33b58b65fc1c3c49425aac68e6571.js"></script>

But throws error on iPhone 5s:
<script src="https://gist.github.com/mayureshshirodkar/47310689183f07264bc964e02ae7f24c.js"></script>

So are iPhone 5s devices not supported?
referencing the link to https://github.com/appium/appium/issues/7690
## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5 Beta
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: OS 10.12.4
* Mobile platform/version under test: 10.3.1,10.2.1
* Real device or emulator/simulator: iPhone 5S, iPhone 6
* Appium CLI or Appium.app|exe:

**Comment by mykola-mokhnach** [comment]
This is rather a question to Apple. From my experience it works, but not for long - it is necessary to reboot the device after several WDA reinstalls. iPhone 6 needs reboot as well, but way [less frequently](https://github.com/appium/appium/issues/8083)
