### ISSUE TITLE
[ WARN ] Keyword 'Capture Page Screenshot' could not be run on failure: No application is open

### ISSUE THREAD

**Issue by shivajighadge** [appium/appium#8394]
## The problem

[ WARN ] Keyword 'Capture Page Screenshot' could not be run on failure: No application is open

## Environment

* Appium version (or git revision) that exhibits the issue: 1.4.16.1
* Last Appium version that did not exhibit the issue (if applicable): No
* Desktop OS/version used to run Appium: Windows10 
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Naught 7.0
* Real device or emulator/simulator: Moto G4+, android emulator (android studio)
* Appium CLI or Appium.app|exe: 

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
Test Test Log
Generated
20170507 19:38:47 GMT+05:30
10 minutes 50 seconds ago
REPORT
Test Statistics
Total Statistics
Total
Pass
Fail
Elapsed
Pass / Fail
Critical Tests 
1
0
1
00:00:10

All Tests 
1
0
1
00:00:10

Statistics by Tag
Total
Pass
Fail
Elapsed
Pass / Fail
No Tags

Statistics by Suite
Total
Pass
Fail
Elapsed
Pass / Fail
Test 
1
0
1
00:00:10

Test Execution Errors
20170507 19:38:47.774 
WARN
Keyword 'Capture Page Screenshot' could not be run on failure: No application is open

Test Execution Log
00:00:09.914
SUITE Test 

Full Name:
Test
Source:
C:\Python27\Scripts\test.robot
Start / End / Elapsed:
20170507 19:38:37.876 / 20170507 19:38:47.790 / 00:00:09.914
Status:
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
00:00:09.789
TEST TC1 

Full Name:
Test.TC1
Start / End / Elapsed:
20170507 19:38:38.001 / 20170507 19:38:47.790 / 00:00:09.789
Status:
FAIL (critical)
Message:
WebDriverException: Message: A new session could not be created. (Original error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "C:\Users\shivaji\AppData\Local\Android\sdk\platforms\platform-tools\adb.exe -s ZY223GMFLK install "C:\Program Files (x86)\Appium\node_modules\appium\build\settings_apk\settings_apk-debug.apk""
Failed to install C:\Program Files (x86)\Appium\node_modules\appium\build\settings_apk\settings_apk-debug.apk: Failure [INSTALL_FAILED_ALREADY_EXISTS: Attempt to re-install io.appium.settings without first uninstalling.]
)
00:00:09.773
KEYWORD AppiumLibrary . Open Application http://localhost:4723/wd/hub, platformName=Android, deviceName=ZY223GMFLK, appPackage=com.android.calculator, appActivity=Calculator 

Documentation:
Opens a new application to given Appium server.
Start / End / Elapsed:
20170507 19:38:38.001 / 20170507 19:38:47.774 / 00:00:09.773
00:00:00.015
KEYWORD AppiumLibrary . Capture Page Screenshot 

Documentation:
Takes a screenshot of the current page and embeds it into the log.
Start / End / Elapsed:
20170507 19:38:47.759 / 20170507 19:38:47.774 / 00:00:00.015
19:38:47.774
FAIL
No application is open

19:38:47.774
WARN
Keyword 'Capture Page Screenshot' could not be run on failure: No application is open

19:38:47.774
FAIL
WebDriverException: Message: A new session could not be created. (Original error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "C:\Users\shivaji\AppData\Local\Android\sdk\platforms\platform-tools\adb.exe -s ZY223GMFLK install "C:\Program Files (x86)\Appium\node_modules\appium\build\settings_apk\settings_apk-debug.apk""
Failed to install C:\Program Files (x86)\Appium\node_modules\appium\build\settings_apk\settings_apk-debug.apk: Failure [INSTALL_FAILED_ALREADY_EXISTS: Attempt to re-install io.appium.settings without first uninstalling.]
)
Logs : 

## Code To Reproduce Issue [ Good To Have ]

*** Settings ***
Library           AppiumLibrary

*** Test Cases ***
TC1
    Open Application    http://localhost:4723/wd/hub    platformName=Android    deviceName=ZY223GMFLK    appPackage=com.android.calculator    appActivity=Calculator

TC2
    [Documentation]    This test case is to test calculator
    [Setup]
    [Template]
    [Timeout]
    [Teardown]

**Comment by mykola-mokhnach** [comment]
1. Uninstall Appium Settings and Appium Unlock applications
2. Attach full Appium log
