### ISSUE TITLE
Unnecessary lock/wait in appium-uiautomator2-server

### ISSUE THREAD

**Issue by mstrelex** [appium/appium#8397]
Hi,

In **getRootAccessibilityNode** method in **XPathFinder** class,
What this line (235) is required for ?
`Device.waitForIdle(timeoutMillis);`

In some apps (Android's clock stopwatch) it cause an unnecessary lock for 10 second, slowing the automation. Is there any way to disable this waiting ? 

Thanks.

**Comment by mykola-mokhnach** [comment]
@sravanmedarapu please assist

**Comment by sravanmedarapu** [comment]
Google UiAutomator2 API [getAccessibilityRootNode()](https://github.com/appium/appium-uiautomator2-server/blob/master/app/src/main/java/io/appium/uiautomator2/model/XPathFinder.java#L238) throws exception when the current view is not in idle state, to mimic this we are [waiting](https://github.com/appium/appium-uiautomator2-server/blob/master/app/src/main/java/io/appium/uiautomator2/model/XPathFinder.java#L234) for AUT to get idle state. 

To answer your question about disabling, there is no option exposed currently and should be doable easily but It might introduce more issues.
