### ISSUE TITLE
Error: unknown error: unable to discover open pages

### ISSUE THREAD

**Issue by xiaoqi7s** [appium/appium#8398]
## The problem

my app have webview,when I switch to webview occured Error: unknown error: unable to discover open pages。

## Environment

* Appium version (or git revision) that exhibits the issue: appium 1.6.4
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: win7
* Node.js version (unless using Appium.app|exe): v7.4.0
* Mobile platform/version under test: android 5.0.1
* Real device or emulator/simulator:oppoA53
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

[](url)

[debug] [AndroidDriver] WEBVIEW_22889 mapped to pid 22889
[debug] [AndroidDriver] Getting process name for webview
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'D:\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s"
,"51d80ed8","shell","ps"]
[debug] [AndroidDriver] Parsed pid: 22889 pkg: com.wlqq!
[debug] [AndroidDriver] from: u0_a250,22889,559,1820888,129872,ffffffff,00000000
,S,com.wlqq
[debug] [AndroidDriver] returning process name: com.wlqq
[debug] [AndroidDriver] Found webviews: ["WEBVIEW_com.wlqq"]
[debug] [AndroidDriver] Available contexts: ["NATIVE_APP","WEBVIEW_com.wlqq"]
[debug] [MJSONWP] Responding to client with driver.getContexts() result: ["NATIV
E_APP","WEBVIEW_com.wlqq"]
[HTTP] <-- GET /wd/hub/session/fa44680a-7db3-4fce-861d-201885032f87/contexts 200
 313 ms - 105
[HTTP] --> POST /wd/hub/session/fa44680a-7db3-4fce-861d-201885032f87/context {"s
essionId":"fa44680a-7db3-4fce-861d-201885032f87","name":"WEBVIEW_com.wlqq"}
[debug] [MJSONWP] Calling AppiumDriver.setContext() with args: ["WEBVIEW_com.wlq
q","fa44680a-7db3-4fce-861d-201885032f87"]
[debug] [AndroidDriver] Getting a list of available webviews
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'D:\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s"
,"51d80ed8","shell","cat","/proc/net/unix"]
[debug] [AndroidDriver] WEBVIEW_22889 mapped to pid 22889
[debug] [AndroidDriver] Getting process name for webview
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'D:\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s"
,"51d80ed8","shell","ps"]
[debug] [AndroidDriver] Parsed pid: 22889 pkg: com.wlqq!
[debug] [AndroidDriver] from: u0_a250,22889,559,1810900,133944,ffffffff,00000000
,R,com.wlqq
[debug] [AndroidDriver] returning process name: com.wlqq
[debug] [AndroidDriver] Found webviews: ["WEBVIEW_com.wlqq"]
[debug] [AndroidDriver] Available contexts: ["NATIVE_APP","WEBVIEW_com.wlqq"]
[debug] [AndroidDriver] Connecting to chrome-backed webview context 'WEBVIEW_com
.wlqq'
[debug] [AndroidDriver] A port was not given, using random port: 8000
[debug] [Chromedriver] Changed state to 'starting'
[Chromedriver] Set chromedriver binary as: C:\Users\hcb\AppData\Roaming\npm\node
_modules\appium\node_modules\.2.11.2@appium-chromedriver\chromedriver\win\chrome
driver.exe
[Chromedriver] Killing any old chromedrivers, running: FOR /F "usebackq tokens=5
" %a in (`netstat -nao ^| findstr /R /C:"8000 "`) do (FOR /F "usebackq" %b in (`
TASKLIST /FI "PID eq %a" ^| findstr /I chromedriver.exe`) do (IF NOT %b=="" TASK
KILL /F /PID %a))
[Chromedriver] No old chromedrivers seemed to exist
[Chromedriver] Spawning chromedriver with: C:\Users\hcb\AppData\Roaming\npm\node
_modules\appium\node_modules\.2.11.2@appium-chromedriver\chromedriver\win\chrome
driver.exe --url-base=wd/hub --port=8000 --adb-port=5037
[Chromedriver] [STDOUT] Starting ChromeDriver 2.26.436362 (5476ec6bf7ccbada1734a
0cdec7d570bb042aa30) on port 8000
Only local connections are allowed.
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8000/wd/h
ub/status] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"\",\"stat
us\":0,\"value\":{\"build\":{\"version\":\"alpha\"},\"os\":{\"arch\":\"x86_64\",
\"name\":\"Windows NT\",\"version\":\"6.1.7601 SP1\"}}}"
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8000/w
d/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPacka
ge":"com.wlqq","androidActivity":"com.wlqq.activity.HomeActivity","androidUseRun
ningApp":true,"androidDeviceSerial":"51d80ed8"}}}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"498a9b8194677
30e3bf4841014f2e94d","status":13,"value":{"message":"unknown error: unable to di
scover open pages\n  (Driver info: chromedriver=2.26.436362 (5476ec6bf7ccbada173
4a0cdec7d570bb042aa30),platform=Windows NT 6.1.7601 SP1 x86_64)"}}
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8000/w
d/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPacka
ge":"com.wlqq","androidActivity":"com.wlqq.activity.HomeActivity","androidUseRun
ningApp":true,"androidDeviceSerial":"51d80ed8"}}}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"11351e36167d8
23deb82d4604a5f6f31","status":13,"value":{"message":"unknown error: unable to di
scover open pages\n  (Driver info: chromedriver=2.26.436362 (5476ec6bf7ccbada173
4a0cdec7d570bb042aa30),platform=Windows NT 6.1.7601 SP1 x86_64)"}}
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8000/w
d/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPacka
ge":"com.wlqq","androidActivity":"com.wlqq.activity.HomeActivity","androidUseRun
ningApp":true,"androidDeviceSerial":"51d80ed8"}}}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"219d3a18f4676
f2103fe2b74bcbf927b","status":13,"value":{"message":"unknown error: unable to di
scover open pages\n  (Driver info: chromedriver=2.26.436362 (5476ec6bf7ccbada173
4a0cdec7d570bb042aa30),platform=Windows NT 6.1.7601 SP1 x86_64)"}}

[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"5f9993cda96b3
7da8b43dc0bfc8a619e","status":13,"value":{"message":"unknown error: unable to di
scover open pages\n  (Driver info: chromedriver=2.26.436362 (5476ec6bf7ccbada173
4a0cdec7d570bb042aa30),platform=Windows NT 6.1.7601 SP1 x86_64)"}}
[Chromedriver] Chromedriver exited unexpectedly with code null, signal SIGTERM
[debug] [Chromedriver] Changed state to 'stopped'
[Chromedriver] Error: unknown error: unable to discover open pages
  (Driver info: chromedriver=2.26.436362 (5476ec6bf7ccbada1734a0cdec7d570bb042aa
30),platform=Windows NT 6.1.7601 SP1 x86_64)
    at Chromedriver.callee$2$0$ (../../lib/chromedriver.js:176:15)
    at tryCatch (C:\Users\hcb\AppData\Roaming\npm\node_modules\appium\node_modul
es\.5.8.24@babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\hcb\AppData\Roam
ing\npm\node_modules\appium\node_modules\.5.8.24@babel-runtime\regenerator\runti
me.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\U
sers\hcb\AppData\Roaming\npm\node_modules\appium\node_modules\.5.8.24@babel-runt
ime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\hcb\AppData\Roaming\npm\node_
modules\appium\node_modules\.5.8.24@babel-runtime\regenerator\runtime.js:136:37)

 Error: unknown error: unable to discover open pages
  (Driver info: chromedriver=2.26.436362 (5476ec6bf7ccbada1734a0cdec7d570bb042aa
30),platform=Windows NT 6.1.7601 SP1 x86_64)
    at Chromedriver.callee$2$0$ (../../lib/chromedriver.js:176:15)
    at tryCatch (C:\Users\hcb\AppData\Roaming\npm\node_modules\appium\node_modul
es\.5.8.24@babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\hcb\AppData\Roam
ing\npm\node_modules\appium\node_modules\.5.8.24@babel-runtime\regenerator\runti
me.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\U
sers\hcb\AppData\Roaming\npm\node_modules\appium\node_modules\.5.8.24@babel-runt
ime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\hcb\AppData\Roaming\npm\node_
modules\appium\node_modules\.5.8.24@babel-runtime\regenerator\runtime.js:136:37)

[MJSONWP] Encountered internal error running command: Error: unknown error: unab
le to discover open pages
  (Driver info: chromedriver=2.26.436362 (5476ec6bf7ccbada1734a0cdec7d570bb042aa
30),platform=Windows NT 6.1.7601 SP1 x86_64)
    at Chromedriver.callee$2$0$ (../../lib/chromedriver.js:176:15)
    at tryCatch (C:\Users\hcb\AppData\Roaming\npm\node_modules\appium\node_modul
es\.5.8.24@babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\hcb\AppData\Roam
ing\npm\node_modules\appium\node_modules\.5.8.24@babel-runtime\regenerator\runti
me.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\U
sers\hcb\AppData\Roaming\npm\node_modules\appium\node_modules\.5.8.24@babel-runt
ime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\hcb\AppData\Roaming\npm\node_
modules\appium\node_modules\.5.8.24@babel-runtime\regenerator\runtime.js:136:37)

[HTTP] <-- POST /wd/hub/session/fa44680a-7db3-4fce-861d-201885032f87/context 500
 244486 ms - 341
[HTTP] --> GET /wd/hub/session/fa44680a-7db3-4fce-861d-201885032f87/screenshot {
}
[debug] [MJSONWP] Calling AppiumDriver.getScreenshot() with args: ["fa44680a-7db
3-4fce-861d-201885032f87"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'D:\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s"
,"51d80ed8","shell","/system/bin/rm","/data/local/tmp/screenshot.png;","/system/
bin/screencap","-p","/data/local/tmp/screenshot.png"]
[debug] [ADB] Running 'D:\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s"
,"51d80ed8","pull","/data/local/tmp/screenshot.png","C:\\Users\\hcb\\AppData\\Lo
cal\\Temp\\appium11748-6300-jgf0gh.lnzujif6r.png"]
[debug] [ADB] Device API level: 22
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected

**Comment by mykola-mokhnach** [comment]
This is chromedriver issue and it has nothing to do with Appium. Please use Google or Chromedriver issues tracker.

https://www.google.de/search?client=safari&rls=en&q=unknown+error:+unable+to+discover+open+pages&ie=UTF-8&oe=UTF-8&gfe_rd=cr&ei=Xi8QWYqACJTc8AewoIv4BA
