### ISSUE TITLE
Save Passwords options in Google Chrome Settings are getting reset after automated execution in Mobile Chrome

### ISSUE THREAD

**Issue by Soumya1987** [appium/appium#8399]
Save Passwords options in Google Chrome Settings are getting reset after automated execution in Mobile Chrome

## Environment

* Appium version (or git revision) that exhibits the issue: Appium v1.6.4
* Desktop OS/version used to run Appium: Windows 10 Enterprise
* Node.js version (unless using Appium.app|exe): Using Appium Desktop
* Mobile platform/version under test: Nexus 6P, Android 6.0.1
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium.app|exe

## Code To Reproduce Issue [ Good To Have ]
DesiredCapabilities cap = new DesiredCapabilities();
cap.setCapability("browserName", "Chrome");
cap.setCapability("deviceName","Nexus 6P");
cap.setCapability("platformVersion", "6.0.1");
cap.setCapability("platformName","Android");
cap.setCapability("unicodeKeyboard", true);
cap.setCapability("resetKeyboard", true);
cap.setCapability("deviceorientation", "orientation:'PORTRAIT'");	
cap.setCapability("noReset", true);	
			  
try {
driver= new AppiumDriver<AndroidElement>(new URL("http://127.0.0.1:4723/wd/hub"),cap);
} catch (Exception e) {
e.printStackTrace();
}

Please let me know if you require any further information..

**Comment by mykola-mokhnach** [comment]
Browser settings should be set as **chromeOptions** capability. Everything, what is inside of the browser, has nothing to do with Appium itself.

**Comment by Soumya1987** [comment]
When I am performing the exact same operations manually then Chrome in Android is working fine. But after performing the same steps in automation using Appium, I find that Save Passwords options in Google Chrome Settings are getting reset. Shouldn't that be an issue with Appium??

**Comment by KazuCocoa** [comment]
As _androidUseRunningApp: (Optional) Attach to an already-running app instead of launching the app with a clear data directory._ in http://chromedriver.chromium.org/getting-started/getting-started---android , I could attach to a chrome running on Android. But in this case, we should launch chrome browser by hand. (Or launch it via adb from out side appium.)

```
         "goog:chromeOptions" => {
            androidPackage: 'com.android.chrome',
            androidUseRunningApp: true
          },
          noReset: true
```

Without `androidUseRunningApp`, chrome launch with cleaning the local data.

**Comment by mykola-mokhnach** [comment]
The solution provided by @KazuCocoa should work with appium@beta. There is the known [bug](https://bugs.chromium.org/p/chromedriver/issues/detail?id=2369) in Chromedriver below 2.39, although I don't think we can do much about it from Appium side.

Closed as fixed
