### ISSUE TITLE
Appium issue : Condition unmet after 60264 ms. Timing out.

### ISSUE THREAD

**Issue by pradyumna92** [appium/appium#8402]
I'm Unable to launch the IOS emulator from Appium
Xcode:7.3.1
Appium :1.5.3

Appium Logs

Launching Appium with command: export NEW_KEY="NEW_VALUE"; '/Applications/Appium.app/Contents/Resources/node/bin/node' appium/build/lib/main.js --address "127.0.0.1" --debug-log-spacing --platform-version "9.3" --platform-name "iOS" --device-name "iPhone 6s" --locale "en_US"

[Appium] Welcome to Appium v1.5.3

[Appium] Non-default server args:

[Appium]   address: '127.0.0.1'

[Appium]   debugLogSpacing: true
[Appium]   platformName: 'iOS'
[Appium]   platformVersion: '9.3'
[Appium]   deviceName: 'iPhone 6s'
[Appium]   locale: 'en_US'

[Appium] Deprecated server args:
[Appium]   --platform-name => --default-capabilities '{"platformName":"iOS"}'
[Appium]   --platform-version => --default-capabilities '{"platformVersion":"9.3"}'
[Appium]   --device-name => --default-capabilities '{"deviceName":"iPhone 6s"}'
[Appium]   --locale => --default-capabilities '{"locale":"en_US"}'
[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:

[Appium]   platformName: 'iOS'

[Appium]   platformVersion: '9.3'
[Appium]   deviceName: 'iPhone 6s'
[Appium]   locale: 'en_US'

[Appium] Appium REST http interface listener started on 127.0.0.1:4723

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[HTTP] <-- GET /wd/hub/status 200 46 ms - 83 

[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/test/Library/Developer/Xcode/DerivedData/New-eurqlousktuaasfwucrmxauxlswo/Build/Products/Debug-iphonesimulator/New.app","appium-version":"1.5.3","platformName":"iOS","deviceName":"iPhone 6s","platformVersion":"9.3"}}

[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/test/Librar...

[Appium] Creating new IosDriver session
[Appium] Capabilities:
[Appium]   app: '/Users/test/Library/Developer/Xcode/DerivedData/New-eurqlousktuaasfwucrmxauxlswo/Build/Products/Debug-iphonesimulator/New.app'
[Appium]   appium-version: '1.5.3'
[Appium]   platformName: 'iOS'
[Appium]   deviceName: 'iPhone 6s'
[Appium]   platformVersion: '9.3'
[Appium]   locale: 'en_US'

[BaseDriver] The following capabilities were provided, but are not recognized by appium: appium-version.

[BaseDriver] Session created with session id: d604d27b-362f-45d1-8f1f-fd6794af358d

[debug] [iOS] Not auto-detecting udid.

[BaseDriver] Using local app '/Users/test/Library/Developer/Xcode/DerivedData/New-eurqlousktuaasfwucrmxauxlswo/Build/Products/Debug-iphonesimulator/New.app'

[debug] [iOS] Removing any remaining instruments sockets

[debug] [iOS] Cleaned up instruments socket /var/folders/6d/sm4yh6yx7r97y3m64g9j2kkr0000gn/T/instruments_sock

[debug] [iOS] Setting Xcode version

[debug] [iOS] Xcode version set to 7.3.1

[debug] [iOS] Setting iOS SDK Version

[debug] [iOS] iOS SDK Version set to 9.3
[debug] [iOS] Checking whether instruments supports our device string
[debug] [Instruments] Getting list of devices instruments supports

[debug] [Instruments] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[debug] [Instruments] Available devices: Apple TV 1080p (9.2) [A7BA0738-E855-4350-8ED2-9E6323878CFE] (Simulator),iPad 2 (9.3) [2FA5ADB1-E72F-445F-9E3D-408B3878F8FD] (Simulator),iPad Air (9.3) [DE772E3B-14F2-462B-99EC-60961024C817] (Simulator),iPad Air 2 (9.3) [227E37A4-1FDF-4B44-8360-179D1AB1D90F] (Simulator),iPad Pro (9.3) [E5DD868E-1E33-4C45-9577-8A458E794391] (Simulator),iPad Retina (9.3) [1DAA0FE7-AA69-48B9-AC2F-FC53D39F2060] (Simulator),iPhone 4s (9.3) [63495122-784C-491F-B9C0-4F4D87934BAD] (Simulator),iPhone 5 (9.3) [389A2873-7197-452C-9348-B7F3BDF469DB] (Simulator),iPhone 5s (2.2) [6AF7695A-EBAA-4CA9-A01F-C7D4679AACB5] (Simulator),iPhone 5s (9.3) [2D482D71-267A-4F57-99EA-9AE4D13C4F50] (Simulator),iPhone 6 (9.3) [8D0C3EE7-1CF6-4506-AB29-977E96AB71C5] (Simulator),iPhone 6 Plus (9.3) [157F4364-AB40-40EF-B7DC-A2520EF928B3] (Simulator),iPhone 6s (9.3) [DDADB293-8F1E-416E-95E0-6CF015C6B212] (Simulator),iPhone 6s (9.3) + Apple Watch - 38mm (2.2) [E39E4B18-8290-482C-B263-E98571CC918D] (Simulator),iPhone 6s Plus (9.3) [001C9DFF-E3DB-4AB8-8052-810EB5D913D5] (Simulator),iPhone 6s Plus (9.3) + Apple Watch - 42mm (2.2) [87D6E2B1-C595-4314-938E-A0B0BB499104] (Simulator)

[iOSSim] Retrieving device name string for Xcode version 7.3.1

[debug] [iOSSim] Getting device string from options: {"deviceName":"iPhone 6s","platformVersion":"9.3","forceIphone":false,"forceIpad":false}
[debug] [iOSSim] Fixing device. Changed from 'iPhone 6s' to 'iPhone 6s (9.3) ['
[debug] [iOSSim] Final device string is 'iPhone 6s (9.3) ['
[debug] [iOS] iOS sim UDID is DDADB293-8F1E-416E-95E0-6CF015C6B212

[iOSSim] Constructing iOS simulator for Xcode version 7.3.1

[debug] [iOS] No language specified. Using default strings

[debug] [iOS] Strings file not found. Looking in 'en.lproj' directory
[iOS] Could not file localizable strings file 'Localizable.strings'!
[debug] [ios-app-utils] Getting bundle ID from app

[iOS] Extracted bundleID: com.appium.New from app: /Users/test/Library/Developer/Xcode/DerivedData/New-eurqlousktuaasfwucrmxauxlswo/Build/Products/Debug-iphonesimulator/New.app
[debug] [iOS] Creating instruments
[debug] [UIAuto] Preparing bootstrap code
[debug] [UIAuto] Dynamic bootstrap dir: /Users/test/Library/Application Support/appium/bootstrap

[debug] [UIAuto] Dynamic env: {"nodePath":"/Applications/Appium.app/Contents/Resources/node/bin/node","commandProxyClientPath":"/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js","instrumentsSock":"/var/folders/6d/sm4yh6yx7r97y3m64g9j2kkr0000gn/T/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"autoDismissAlerts":false,"sendKeyStrategy":"oneByOne"}

[debug] [UIAuto] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
...

[debug] [UIAuto] Dynamic bootstrap path: /Users/test/Library/Application Support/appium/bootstrap/bootstrap-8fbcc6a1c42b5ab2.js

[debug] [UIAuto] Reusing dynamic bootstrap: /Users/test/Library/Application Support/appium/bootstrap/bootstrap-8fbcc6a1c42b5ab2.js
[debug] [iOS] User specified default device, letting instruments launch it
[debug] [iOS] Running ios sim reset flow
[debug] [iOS] Killing the simulator
[debug] [iOSSim] Killing all iOS Simulators

[HTTP] --> GET /wd/hub/status {}
[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[iOSSim] The following devices are not in the correct state:

[iOSSim]     Simulator not shut down: iPad Pro (undefined, udid: 12.9 inch) is still in state '301f0ece-207e-4e14-9cff-d377ca9f551b'

[HTTP] <-- POST /wd/hub/session 500 63472 ms - 180 

[MJSONWP] Encountered internal error running command: Error: Condition unmet after 60264 ms. Timing out.
    at spin$ (lib/asyncbox.js:118:13)
    at tryCatch (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/asyncbox/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/asyncbox/node_modules/babel-runtime/regenerator/runtime.js:294:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/asyncbox/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/asyncbox/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/asyncbox/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:89:39)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/asyncbox/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:100:28
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status - - ms - - 

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[HTTP] <-- GET /wd/hub/status - - ms - - 

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 15 ms - 83 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[HTTP] <-- GET /wd/hub/status 200 25 ms - 83 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 18 ms - 83 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 19 ms - 83 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 17 ms - 83 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 20 ms - 83 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 18 ms - 83 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 24 ms - 83 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 16 ms - 83 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 16 ms - 83 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 16 ms - 83 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[HTTP] <-- GET /wd/hub/status 200 14 ms - 83 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 17 ms - 83 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 13 ms - 83 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 16 ms - 83 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 13 ms - 83 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 16 ms - 83 
[HTTP] --> GET /wd/hub/status {}
[MJSONWP] Calling AppiumDriver.getStatus() with args: []
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 13 ms - 83 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 27 ms - 83 
[HTTP] --> GET /wd/hub/status {}
[MJSONWP] Calling AppiumDriver.getStatus() with args: []
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 16 ms - 83 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] --> GET /wd/hub/status {}
[MJSONWP] Calling AppiumDriver.getStatus() with args: []
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 81 ms - 83 
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 87 ms - 83 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] --> GET /wd/hub/status {}
[MJSONWP] Calling AppiumDriver.getStatus() with args: []
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 81 ms - 83 
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 63 ms - 83 

**Capabilities**
                capabilities.setCapability("appium-version","1.5.3");
		capabilities.setCapability("platformName", "iOS Simulator");
		capabilities.setCapability("platformVersion", "9.3");
		capabilities.setCapability("deviceName", "iPhone 6s");
		capabilities.setCapability("app", "/Users****.app");

Could someone help me resolve this issue

**Comment by imurchie** [comment]
Please move to Appium 1.6.4 (the latest). Much has been fixed.
