### ISSUE TITLE
Unable to rotate device to Landscape mode using Appium 1.6.4

### ISSUE THREAD

**Issue by shanthi2016** [appium/appium#8404]
When trying to rotate device to landscape mode the simulator rotates only 90 degrees not complete landscape mode on iOS 10.3 simulator using Appium 1.6.4, but the same code works for 1.5.3

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Last Appium version that did not exhibit the issue (if applicable): 1.5.3
* Desktop OS/version used to run Appium: Mac OS 10.12
* Node.js version (unless using Appium.app|exe): 6.10.2
* Mobile platform/version under test: 10.3
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: Appium.app

## Details

Tried with below code for device rotation:

driver.rotate(ScreenOrientation.LANDSCAPE);
AND
((Rotatable) driver).rotate(ScreenOrientation.LANDSCAPE);

## Link to Appium logs

https://gist.github.com/shanthi2016/5a912654243935f59923736f9851f818

**Comment by mykola-mokhnach** [comment]
Known XCTest bug. Please report to Apple.
