### ISSUE TITLE
Not able to start appium 1.6.4: DTDeviceKit: Could not start house arrest service for app identifier com.apple.test.WebDriverAgentRunner-Runner [Error Domain=com.apple.dtdevicekit Code=-402653093 "Too many instances of this service are already running." UserInfo={NSLocalizedFailureReason=Too many instances of this service are already running.,

### ISSUE THREAD

**Issue by abh7nav** [appium/appium#8406]
## The problem
I have installed appium 1.6.4 and configured WebDriverAgent project but on launching appium desktop or old appium GUI, it is giving error.

https://gist.github.com/abh7nav/f0813230c3ef1ed8b5a01f1ee0ac4031

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Last Appium version that did not exhibit the issue (if applicable): 1.6.3
* Desktop OS/version used to run Appium: MacOS Sieraa
* Node.js version (unless using Appium.app|exe): 7.4
* Mobile platform/version under test: ios 10.3.1
* Real device or emulator/simulator: Real
* Appium CLI or Appium.app|exe: CLI

## Details

I tried running below command but it is also giving error:
`xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=<Device_UDID> -configuration Debug`

Following is the output of above command
https://gist.github.com/abh7nav/8b796440721705b4fcb362053de3ffd7

## Link to Appium logs
https://gist.github.com/abh7nav/8b796440721705b4fcb362053de3ffd7

https://gist.github.com/abh7nav/f0813230c3ef1ed8b5a01f1ee0ac4031

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
This is known XCTest/WDA issue, which cannot be fixed on Appium side.
Rebooting the device should help. Try **not** to reinstall WDA on the device by using **useNewWDA** capability
Closed as duplicate.

**Comment by abh7nav** [comment]
@mykola-mokhnach Thanks. Rebooting the device helped me start appium but there is one issue with appium desktop. Do you mind looking at that:
https://github.com/appium/appium-desktop/issues/175
