### ISSUE TITLE
How to install .app file into IOS simulator

### ISSUE THREAD

**Issue by pradyumna92** [appium/appium#8408]
I have tried installing .app file into IOS simulator ,but could not accomplish it successfully.
I have put my .app in below path
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/Applications/myapp.app

I'm able to see the app on Simulator but once i try to open the app manually/automatically from simulator its getting closed automatically

Xcode version:7.3.2
 tried using below Command line
xcrun simctl install booted /my apppath/YourProject.app
**Error**
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle

**Comment by mykola-mokhnach** [comment]
Please use Apiium forum to ask questions
