### ISSUE TITLE
Can we install .app/.ipa files on IOS simulator?

### ISSUE THREAD

**Issue by pradyumna92** [appium/appium#8410]
## The problem

We have .app files and we need to install them on IOS simulator, can this be done?

If Yes, please suggest the steps

So far we have tried to install app via terminal using

xcrun simctl install booted /Apppath/Myapp.app.

Also tried to put the .app file in below path?

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/Applications/Myapp.app

We could see the application on Iphone simulator, as soon as the application is launched, it is getting closed automatically within a second.

Could someone help me out of this?

**Comment by imurchie** [comment]
Is the application built for the simulator?

**Comment by pradyumna92** [comment]
Thanks for the quick response..
No

**Comment by imurchie** [comment]
It needs to be. Doesn't matter what sim, but it cannot be built for a real
device if it is going to be run on a sim.

**Comment by mykola-mokhnach** [comment]
```bash
xcrun simctl install --help
```

**Comment by narendra-chandratre** [comment]
xcrun simctl install <device_id> <app_path>
