### ISSUE TITLE
Unable to find hybird app webview on real iOS devices, despite working on iOS/Android Simulator

### ISSUE THREAD

**Issue by siggerzz** [appium/appium#8411]
## The problem
I'm trying to get Appium tests to run on a real iOS device. My tests run successfully on Android/iOS Simulators, as well as Android real device, but doesn't seem to work on iOS real devices.

I've tried using an .IPA file from Testflight, as well as from XCode and i'm seeing the same result on both.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: MacOS - 10.12.3
* Node.js version (unless using Appium.app|exe): 6.10.3
* Mobile platform/version under test: iPhone 6s / iOS 10.3.1
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: CLI

## Details

**Capabilities:**

deviceName: 'iPhone 7 Plus'
deviceOrientation: 'portrait'
platformName: 'iOS'
platformVersion: '10.3'
environment: 'Local'
autoWebview: true
startIWDP: true
realDeviceLogger: '/usr/local/lib/node_modules/deviceconsole/deviceconsole'

Also, if I launch iOS Debug proxy manually via CLI, with both my iOS Simulator and real device on the homescreen of my hybrid app, with the following setup

Simulator - Port 9222
Real Device Port 9223

If I run the below command, I get a response on my iOS Simulator, but not the real device.
curl -get localhost:port/json

## Link to Appium logs

[Appium Log](https://gist.github.com/siggerzz/5dc62e1482df1928416e1768706e24db)

## Code To Reproduce Issue [ Good To Have ]

Unfortunately I can't provide this.

**Comment by dpgraham** [comment]
@imurchie @jlipps Do either of you have any thoughts on this one?

**Comment by siggerzz** [comment]
Any update on this? Still haven't managed to get around this 😞

**Comment by yaphatak** [comment]
can you do following  and see if that helps?
`brew uninstall ios-webkit-debug-proxy
brew uninstall libimobiledevice
brew update
brew install libimobiledevice --HEAD
brew install ios-webkit-debug-proxy`

**Comment by siggerzz** [comment]
@yaphatak I managed to fix the issue, however your suggestion wasn't the fix. I got a new IPA build from my companies development team and I seems to be working now 😄. They put a fix in where our app would sometimes hang on launch, so I'm not sure if that was the fix, or whether it's because the app was built via XCode rather than from Testflight.

Do you happen to know if Appium supports testflight apps?

**Comment by dpgraham** [comment]
If you can install your app via Xcode onto a real device then Appium can do it too. So I assume you can yes.
