### ISSUE TITLE
Intermittent Not a JSON response error running locally on iOS simulator

### ISSUE THREAD

**Issue by mantisbayne** [appium/appium#8413]
## The problem

Since updating to iOS 10.3, I have been seeing my tests (which I only have set up to run locally at the moment) failing sometimes with the error `Not JSON response`

## Environment

* Appium version (or git revision) that exhibits the issue: v 1.6.4
* Desktop OS/version used to run Appium: macOS Sierra (just got the new Macbook) 10.12.3
* Node.js version (unless using Appium.app|exe):  v6.10.3
* Mobile platform/version under test:
```javascript
capabilities = {
  browserName: '',
  platformName: 'iOS',
  platformVersion: '10.3',
  deviceName: 'iPhone 7',
  automationName: 'XCUITest',
  app: undefined, // will be set later
};
```
* Real device or emulator/simulator: emulator/simulator
* Appium CLI or Appium.app|exe: CLI

## Details

This happens intermittently, seems to happen when installing the app is a bit slow or I don't have the simulator already open.  I thought it might be a corporate proxy issue, but setting no_proxy in my .bash_profile did not solve the issue.   It looks like the test is running before the application is fully installed and launched, so it's possibly a problem with how I'm handling asynchronous processes in my code.

## Link to Appium logs

Fail logs: https://gist.github.com/mantisbayne/eebc8f865714c1f124215fd5fcf32362

When the test fails, I see this HTTP request, which is clearly not valid, because it lacks a session ID in the URL:

```bash
[HTTP] --> POST /wd/hub/session/elements {"using":"class name","value":"XCUIElementTypeButton"}
[debug] [HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- POST /wd/hub/session/elements 404 4 ms - 66
```

## Code To Reproduce Issue (example code, can't reveal actual code, sorry)

Init session:
```javascript
  public async initSession() {
    driver = wd.promiseChainRemote(serverConfig);
    await this.driver.init(capabilities)
      .setImplicitWaitTimeout(60000);
    return driver;
  }
```
Test file  init session
```javascript
  beforeAll((done) => {
    driver.initSession()
      .then(() => {
        done();
      });
  });
```

**Comment by mykola-mokhnach** [comment]
This looks like you are asynchronously execute some lookup while the driver is still being initialized.

**Comment by mantisbayne** [comment]
yes, agreed.  do you know how to insert a wait for the app to be deployed in appium tests in js?

**Comment by imurchie** [comment]
When does the call to get the elements happen? I would think that the fragment you show should work.

**Comment by mantisbayne** [comment]
Here's what my test code looks like on a basic level, which is where the call happens (this is a simple test I'm just playing around with to get everything working before we start developing the actual application)

```javascript
  it('should have an element', async () => {
    const button = await this.driver.elementsByClassName('class name','XCUIElementTypeButton');
    button.then(async (buttons) => {
        const button = buttons[0];
        const isDisplayed = await button.isDisplayed();
        expect(isDisplayed).toBe(true);
      });
  });
```

The error pretty consistently occurs if I don't have the simulator already open and it boots, or if install is taking a bit longer. If I run the test with the simulator already open, it passes.  Let me know what you think.

**Comment by mykola-mokhnach** [comment]
Probably, you need to await **this.driver** somewhere above

**Comment by mantisbayne** [comment]
That's already included in my code.  Any other suggestions?

**Comment by imurchie** [comment]
Can you try keeping things consistent? Rather than switching between promise-based and async/await-based styles:
```js
async function initSession (serverConfig, capabilities) {
  let driver = wd.promiseChainRemote(serverConfig);
  await driver.init(capabilities);
  await driver.setImplicitWaitTimeout(60000);
  return driver;
}

let driver;
beforeAll(async function () {
  driver = await initSession(serverConfig, capabilities);
});

it('should have an element', async () => {
  const button = await this.driver.elementsByClassName('class name', 'XCUIElementTypeButton');
  const button = buttons[0];
  const isDisplayed = await button.isDisplayed();
  expect(isDisplayed).toBe(true);
});
```

**Comment by mantisbayne** [comment]
I refactored to use only async/await styles, and I still see the error intermittently on iOS 10.3 with the simulator.  Seems to be a race condition. Any other ideas?

**Comment by imurchie** [comment]
Not in the abstract, no. :( If you are able, you can send me the code privately (isaac at saucelabs dot com) and I will have a look. If you can't, I understand, but I also don't know how to advise further.

**Comment by mantisbayne** [comment]
Ok, I will look into whether I can do that or not.  It's probably environment-specific, but I don't know.  Thanks!

**Comment by imurchie** [comment]
Ok. Even if it's not runnable, something might be visibly wrong.

**Comment by mantisbayne** [comment]
This appears to be an issue with Jasmine, which is what I'm using as a framework so that we have consistency across our application.  Jasmine has the DEFAULT_TIMEOUT_INTERVAL, which was timing out in my beforeAll hook when the app installation was slow.  Afaik, this is what was causing element location to be called prematurely

**Comment by kamok** [comment]
I'm using mocha and I have the same problem. Did you switch to mocha?

The problem with mocha is I'm using jasmine in my unit tests and it's giving me some type clashes with the `describe` and `it` keywords. 

If you've solved it, can you explain?
