### ISSUE TITLE
 [ADB] Incorrect package and activity.

### ISSUE THREAD

**Issue by afiliptsov** [appium/appium#8414]
When i am setting up 
com.t1.t1.SplashActivity.com - It Complains about Main Activity.
 When i switch to - t1.t1.MainActivity  -it Complains about Splash activity
In any case it complains about one of those parameters, if i pass both of them, it will complain about second parameter/

Desired Capabilities:
```
      cap.setPlatform(Platform.ANDROID);
            cap.setCapability("noReset","true");
            cap.setCapability("newCommandTimeout", "450");
            cap.setCapability(MobileCapabilityType.DEVICE_NAME,"NJPFFAING");
            cap.setCapability(MobileCapabilityType.APP,"/Users/anton/Documents/AndroidApp/app2.apk");
            AndroidDriver driver = new AndroidDriver(new URL("http://127.0.0.1:4723/wd/hub"),cap);
            cap.setCapability("appPackage", "com.t1.t1");
            cap.setCapability("appActivity", "t1.t1.MainActivity");
            cap.setCapability("appWaitActivity", "com.t1.t1.SplashActivity");
```

I already tried all options. Switching them. Adding both in App Activity. 
When i add both in App Activity i am getting 

[ADB] Found package: 'com.t1.t1' and fully qualified activity name : 'com.t1.t1.MainActivity'
[ADB] Incorrect package and activity. Retrying.
[ADB] Getting focused package and activity
[ADB] Getting connected devices...
[ADB] 1 device(s) connected

```
cap.setCapability("appActivity", "com.t1.t1.SplashActivity,com.t1.t1.MainActivity");
            cap.setCapability("appWaitActivity", "com.t1.t1.SplashActivity");
```

**Comment by mykola-mokhnach** [comment]
Since Appium 1.6.5-beta it is possible to use wildcard ('*') character in activity names. Try it.

**Comment by JaniJegoroff** [comment]
Do you need to define `appActivity` - how about only defining `appWaitActivity`?
```
appWaitActivity = "com.t1.t1.SplashActivity, com.t1.t1.MainActivity"
```
