### ISSUE TITLE
Using MDN NavigationTimeAPI and getting error 501

### ISSUE THREAD

**Issue by pavanbachu0604** [appium/appium#8415]
As a part of Business Requirement, we need to calculate the load times. Mozilla has provided something called[ Navigation Time API](https://dzone.com/articles/improving-site-performance-0) . When I am trying to run on Mobile I am getting "Method not implemented Error". Need to solve this ASAP

**CODE TO REPRODUCE**
JavascriptExecutor js = (JavascriptExecutor) driver;
double loadEventEnd = (Long) js.executeScript("return window.performance.timing.loadEventStart;");

Please find the [GIST](https://gist.github.com/pavanbachu0604/0762b74759e88b76fb344c61c6316bc0)

**Comment by mykola-mokhnach** [comment]
How Mozilla's API is related to Apple and Appium itself? It is not even a part of Selenium standard.

**Comment by dpgraham** [comment]
It looks like you're calling it from a Native context. Try either prepending your script with `mobile:` or switching to the WebView context by setting `autoWebView=true`.

See this code snippet here for reference:
```js
// XCUITestDriver -- lib/commands/execute.js
extensions.execute = async function (script, args) {
  if (!script.match(/^mobile\:/) && !this.isWebContext()) {
    throw new errors.NotImplementedError();
  }

  return await iosExecute.call(this, script, args);
};
```

**Comment by dpgraham** [comment]
Let me know if that _doesn't_ fix it and I'll re-open the ticket.
