### ISSUE TITLE
iOS 10 support - Signing the WebDriver Agent

### ISSUE THREAD

**Issue by avrahamShutterFly** [appium/appium#8418]
## The problem

 The Signing the WebDriver Agent works well for several times, but after that the  "Signing the WebDriver Agent" fails and I got 65 Signing Error. it is not happen to me before.

iOS 10 
Xcode 8.2.1
java neon 1.8
## Environment

* Appium version 1.6.5-beta
* Last Appium version 1.6.4
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: 6
* Appium CLI or Appium.app|exe:

**Comment by mayureshshirodkar** [comment]
What real device are you using? Could you restart the device and check if you having the issue?

**Comment by avrahamShutterFly** [comment]
Thanks mayureshshirodkar for your quick response. 
I try to restart my device and steel the error come after several times. 
more than that i try on different iOS devices and steel get this 65 Signing Error..

**Comment by tfcardoso** [comment]
@avrahamShutterFly If it works couple times after a device restart and then stops working, you probably hitting this: https://github.com/appium/appium/issues/7063

**Comment by mykola-mokhnach** [comment]
This problem is not related to Appium itself. Try to open WebAgentDriver project manually in Xcode, build and deploy it to your device. fF you cannot do it from Xcode then Appium will not be able to sign the project as well

**Comment by avrahamShutterFly** [comment]
@mykola-mokhnach I did it manually in Xcode, and steel after couple times there is a 65 Signing Error.
@avrahamShutterFly It is not the log that I got, my log error is about  "65 Signing Error" and not about socket..

**Comment by dpgraham** [comment]
Closing this as non-related to Appium.
