### ISSUE TITLE
Cannot create session with only 'browserName' - PHP

### ISSUE THREAD

**Issue by Tzafra** [appium/appium#8419]
## The problem

Probably a problem with the PHP appium client, since that is what I'm using.  My intention is to test a mobile site, not a native app.
When I attempt to create a test case for mobile browser that includes only `browserName` but not `app`, `appPackage`, or `appActivity`, I get the following error: 
"The desired capabilities must include either an app, appPackage, or browserName."

This happens when my code is like this:
```
class NxMobileBrowserTest extends PHPUnit_Extensions_AppiumTestCase
{
    public static $browsers = array(
        array(
            'port' => 4723,
            'host' => APPIUM_IP,
            'desiredCapabilities' => array(
                "browserName" => 'Chrome',
                'platformName' => 'android',
                'platformVersion' => '6.0.1',
                'deviceName' => 'Nexus 5',
            )
        )
    );

public function testStuff()
    {
        $this->url('http://www.example.com');
        $element = $this->byTag('p');
        $this->asserNotNull($element);
    }
}
```

It worked for me only when I added in 
```
'appPackage' => 'com.android.chrome',
'appActivity' => 'com.google.android.apps.chrome.Main'
```
essentially bypassing the `browserName` by automating the Chrome app instead.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Last Appium version that did not exhibit the issue (if applicable): unknown
* Desktop OS/version used to run Appium: Windows 10 Pro
* Node.js version (unless using Appium.app|exe): 4.8.2
* Mobile platform/version under test: Android 6.0.1
* Real device or emulator/simulator: Real device (though it never gets that far)
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs

https://gist.github.com/Tzafra/28e651c661fd71ff75c4342ea72385ff

**Comment by mykola-mokhnach** [comment]
> [Appium] Capabilities:
> [Appium]   browserName: ''

This is what I can see in the log, which means the server does not receive the value, which is passed from the client. I'm not sure why this is happening, since PHP is something from a far galaxy for me. But it seems like the **browserName** capability name in your code is enclosed in double quotes while other capability names have single quotes. Does it make any diff?

**Comment by Tzafra** [comment]
In PHP it makes no difference, and I actually tried it both ways to be sure.  No difference.

**Comment by mykola-mokhnach** [comment]
Then it might be an issue in PHP client [itself](https://github.com/appium/php-client/issues). BTW the NodeJS version you use is too old. Try to upgrade it to version 7.

**Comment by dpgraham** [comment]
This looks like a bug to me. I'll test it out and confirm.

**Comment by dpgraham** [comment]
@Tzafra Can you try this?

```php
public static $browsers = array(
        array(
            'port' => 4723,
            'host' => APPIUM_IP,
            "browserName" => 'Chrome',
            'desiredCapabilities' => array(
                'platformName' => 'android',
                'platformVersion' => '6.0.1',
                'deviceName' => 'Nexus 5',
            )
        )
    );
```

It seems that the desiredCapabilities.browserName is overridden by the browserName provided in the main parameters which I think is the likely cause.

Here is the snippet of code in the client which is causing this to happen:

```php
public function session(array $parameters)
    {
        echo '!!!!!' + $paramaters['browserName'];
        $seleniumServerUrl = PHPUnit_Extensions_Selenium2TestCase_URL::fromHostAndPort($parameters['host'], $parameters['port']);
        $driver = new PHPUnit_Extensions_AppiumTestCase_Driver($seleniumServerUrl, $parameters['seleniumServerRequestsTimeout']);
        $capabilities = array_merge($parameters['desiredCapabilities'],
                                    array(
                                        'browserName' => $parameters['browserName']
                                    ));
        $session = $driver->startSession($capabilities, $parameters['browserUrl']);
        return $session;
    }
```

If that doesn't fix it, let me know and I'll re-open this issue. 

I don't know that we'll have time to publish a fix for this.

**Comment by Tzafra** [comment]
Sorry this took me a while to get back to.  That worked perfectly.  I see that in the docs example `BrowserName` was actually in the outer array, but the Appium error requested it as part of the `desiredCapabilities` so that was where I thought it would go...

**Comment by dpgraham** [comment]
Yeah, `browserName` is a desired capability. I'm not sure why they require it in the outer array.
