### ISSUE TITLE
Do you provide paid/priority support?

### ISSUE THREAD

**Issue by poorvikamahesh** [appium/appium#8420]
Hello,

Just wanted to know if Appium provides priority/paid support for organisations?
 
Thanks and Regards,
Poorvika

**Comment by dpgraham** [comment]
Appium is under the JSFoundation (https://js.foundation/), which is an open-source software foundation, which, to my knowledge, doesn't provide any sort of support plans for it's products. 

A support plan would have to be through a 3rd party which, to my knowledge, there are no such providers.

**Comment by poorvikamahesh** [comment]
@dpgraham 
Thanks
