### ISSUE TITLE
Uiatuomator2 expects xSpeed in flick_element

### ISSUE THREAD

**Issue by ole-vegard** [appium/appium#8421]
## The problem

In the Python implementation, I get `missing xSpeed` when using `uiatuomator2`. The error does not occur when not specifying uiautomator2

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Android 7.0
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: exe ( started from cmd )
```
├─┬ appium-uiautomator2-driver@0.3.3
│ ├─┬ appium-adb@2.20.0
│ ├─┬ appium-android-driver@1.19.1
│ │ ├─┬ appium-android-bootstrap@2.9.1
│ │ │ ├── appium-uiautomator@1.1.1
│ │ ├── appium-android-ime@2.0.0
│ │ ├─┬ appium-chromedriver@2.11.2
│ │ │ ├─┬ appium-support@2.8.2
│ │ ├─┬ appium-support@2.8.2
│ │ ├── appium-unlock@0.1.1
│ │ ├── io.appium.settings@2.2.1
│ ├─┬ appium-base-driver@2.8.0
│ │ ├─┬ appium-support@2.8.2
│ ├─┬ appium-support@2.6.0
│ ├── appium-uiautomator2-server@0.1.5
```
## Details
From https://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/interactions/touch/TouchActions.html#flick-int-int-

We have  :
```
flick takes `xSpeed, ySpeed`
```
and 
```
flick (element) takes `WebElement, xOffset, yOffset, speed`
```

However. when I use
```
flick_element(self, on_element, xoffset, yoffset, speed):
```

in the Python implementation, I get "missing xSpeed". As a temporary fix, I added `xSpeed` and `ySpeed` parameters in `flick_element` in  `/selenium/webdriver/common/touch_actions.py`, which makes it work. 

It also seems like it still works if I remove  `WebElement`, `xOffset` and `yOffset` so probably this is `uiatomator2` interpreting this as the first of the two functions above. Which makes sense since it sends  `Command.FLICK` along with the parameters of the second function :

```
 self._actions.append(lambda: self._driver.execute(
            Command.FLICK, {
                'element': on_element.id,
                'xoffset': int(xoffset),
                'yoffset': int(yoffset),
                'speed': int(speed)}))
```

## Link to Appium logs

Appium server log:
https://gist.github.com/ole-vegard/a9a64b162f4bb9d412ad5a4b8361d888

Cmd output:
https://gist.github.com/ole-vegard/1e5afc3c64663cf87a5fa80b741e28cd

## Code To Reproduce Issue
https://gist.github.com/ole-vegard/1e5afc3c64663cf87a5fa80b741e28cd

**Comment by mykola-mokhnach** [comment]
You are welcome to create a PR to Python client and fix the problem

**Comment by dpgraham** [comment]
I second @mykola-mokhnach on this.

It sounds like you have a fix for this and we'd be happy to review a PR and if it looks good we can merge it into the client codebase.

**Comment by ole-vegard** [comment]
So I should fix it in the python bindings, rather than making uiautomator handle arguments formatted in different ways?

**Comment by ole-vegard** [comment]
@dpgraham @mykola-mokhnach Any input on the question above?

**Comment by dpgraham** [comment]
@ole-vegard I just checked https://github.com/appium/appium-uiautomator2-server/blob/5aaa508cfa27c4f22716b707e81c480313937f7a/app/src/main/java/io/appium/uiautomator2/handler/Flick.java and it shows

```java
final Integer xSpeed = Integer.parseInt(payload.getString("xSpeed"));
final Integer ySpeed = Integer.parseInt(payload.getString("ySpeed"));
```

We may want to make it case insensitive, but I don't think we'd want to strip out other characters.
