### ISSUE TITLE
Appium update to 1.6.5 beta fails at the appium-windows-driver@0.4.1 install script 'node install-npm.js'.

### ISSUE THREAD

**Issue by padmakarsrinivas** [appium/appium#8422]
system:~ user$ sudo npm install -g appium@beta
npm WARN engine appium@1.6.5-beta: wanted: {"node":">=4","npm":">=3"} (current: {"node":"4.4.0","npm":"2.14.20"})
npm WARN engine punycode@2.1.0: wanted: {"node":">=6"} (current: {"node":"4.4.0","npm":"2.14.20"})
npm WARN engine punycode@2.1.0: wanted: {"node":">=6"} (current: {"node":"4.4.0","npm":"2.14.20"})
npm WARN deprecated babel-core@5.8.24: Babel 5 is no longer being maintained. Upgrade to Babel 6.
npm WARN peerDependencies The peer dependency request@^2.34 included from request-promise will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency request@^2.34 included from request-promise-core will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
 
> appium-windows-driver@0.4.1 install /usr/local/lib/node_modules/appium/node_modules/appium-windows-driver
> node install-npm.js

module.js:327
    throw err;
    ^

Error: Cannot find module 'core-js/library/fn/symbol'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/core-js/symbol.js:1:93)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated line-numbers@0.2.0: Copy its ~20 LOC directly into your code instead.
 
> appium-chromedriver@2.11.2 install /usr/local/lib/node_modules/appium/node_modules/appium-android-driver/node_modules/appium-chromedriver
> node install-npm.js

Error trying to install Chromedriver binary. Waiting and trying again. Cannot find module '../modules/web.dom.iterable'
Error trying to install Chromedriver binary. Waiting and trying again. Cannot find module '../modules/web.dom.iterable'
Error trying to install Chromedriver binary. Waiting and trying again. Cannot find module '../modules/web.dom.iterable'
Error trying to install Chromedriver binary. Waiting and trying again. Cannot find module '../modules/web.dom.iterable'
Error trying to install Chromedriver binary. Waiting and trying again. Cannot find module '../modules/web.dom.iterable'
Error trying to install Chromedriver binary. Waiting and trying again. Cannot find module '../modules/web.dom.iterable'
Error trying to install Chromedriver binary. Waiting and trying again. Cannot find module '../modules/web.dom.iterable'
Error trying to install Chromedriver binary. Waiting and trying again. Cannot find module '../modules/web.dom.iterable'
Error trying to install Chromedriver binary. Waiting and trying again. Cannot find module '../modules/web.dom.iterable'
Error trying to install Chromedriver binary. Waiting and trying again. Cannot find module '../modules/web.dom.iterable'
Error trying to install Chromedriver binary. Waiting and trying again. Cannot find module '../modules/web.dom.iterable'
Error trying to install Chromedriver binary. Waiting and trying again. Cannot find module '../modules/web.dom.iterable'
Error trying to install Chromedriver binary. Waiting and trying again. Cannot find module '../modules/web.dom.iterable'
Error trying to install Chromedriver binary. Waiting and trying again. Cannot find module '../modules/web.dom.iterable'
Error trying to install Chromedriver binary. Waiting and trying again. Cannot find module '../modules/web.dom.iterable'
Error trying to install Chromedriver binary. Waiting and trying again. Cannot find module '../modules/web.dom.iterable'
Error trying to install Chromedriver binary. Waiting and trying again. Cannot find module '../modules/web.dom.iterable'
info Chromedriver Install Installing Chromedriver version '2.28' for platform 'mac' and architecture '64'
info Chromedriver Install Opening temp file to write chromedriver_mac64 to...
info Chromedriver Install Downloading https://chromedriver.storage.googleapis.com/2.28/chromedriver_mac64.zip...
info Chromedriver Install Writing binary content to /usr/local/lib/node_modules/appium/node_modules/appium-android-driver/node_modules/appium-chromedriver/2017410-3175-1ccihlc/chromedriver_mac64.zip...
info Chromedriver Install Extracting /usr/local/lib/node_modules/appium/node_modules/appium-android-driver/node_modules/appium-chromedriver/2017410-3175-1ccihlc/chromedriver_mac64.zip to /usr/local/lib/node_modules/appium/node_modules/appium-android-driver/node_modules/appium-chromedriver/2017410-3175-1ccihlc/chromedriver_mac64
info Chromedriver Install Creating /usr/local/lib/node_modules/appium/node_modules/appium-android-driver/node_modules/appium-chromedriver/chromedriver/mac...
info Chromedriver Install Copying unzipped binary, reading from /usr/local/lib/node_modules/appium/node_modules/appium-android-driver/node_modules/appium-chromedriver/2017410-3175-1ccihlc/chromedriver_mac64/chromedriver...
info Chromedriver Install Writing to /usr/local/lib/node_modules/appium/node_modules/appium-android-driver/node_modules/appium-chromedriver/chromedriver/mac/chromedriver...
info Chromedriver Install /usr/local/lib/node_modules/appium/node_modules/appium-android-driver/node_modules/appium-chromedriver/chromedriver/mac/chromedriver successfully put in place

> fsevents@1.1.1 install /usr/local/lib/node_modules/appium/node_modules/fsevents
> node install

[fsevents] Success: "/usr/local/lib/node_modules/appium/node_modules/fsevents/lib/binding/Release/node-v46-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> appium-selendroid-driver@1.6.1 install /usr/local/lib/node_modules/appium/node_modules/appium-selendroid-driver
> node ./bin/install.js

dbug AndroidDriver Getting Java version
info AndroidDriver Java version is: 1.8.0_74
info Selendroid Ensuring /usr/local/lib/node_modules/appium/node_modules/appium-selendroid-driver/selendroid/download exists
info Selendroid Downloading Selendroid standalone server version 0.17.0 from http://repo1.maven.org/maven2/io/selendroid/selendroid-standalone/0.17.0/selendroid-standalone-0.17.0-with-dependencies.jar --> /usr/local/lib/node_modules/appium/node_modules/appium-selendroid-driver/selendroid/download/selendroid-server-7cf7163ac47f1c46eff95b62f78b58c1dabdec534acc6632da3784739f6e9d82.jar
info Selendroid Writing binary content to /usr/local/lib/node_modules/appium/node_modules/appium-selendroid-driver/selendroid/download/selendroid-server.jar.tmp
info Selendroid Selendroid standalone server downloaded
info Selendroid Determining AndroidManifest location
info Selendroid Determining server apk location
info Selendroid Extracting manifest and apk to /usr/local/lib/node_modules/appium/node_modules/appium-selendroid-driver/selendroid/download
info Selendroid Copying manifest and apk to /usr/local/lib/node_modules/appium/node_modules/appium-selendroid-driver/selendroid
info Selendroid Cleaning up temp files
info Selendroid Fixing AndroidManifest icon bug

> appium-uiautomator2-driver@0.3.3 install /usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-driver
> node ./bin/install.js

dbug AndroidDriver Getting Java version
info AndroidDriver Java version is: 1.8.0_74
info UiAutomator2 downloading UiAutomator2 Server APK v0.1.5 : https://github.com/appium/appium-uiautomator2-server/releases/download/v0.1.5/appium-uiautomator2-server-v0.1.5.apk
info UiAutomator2 downloading UiAutomator2 Server test APK v0.1.5 : https://github.com/appium/appium-uiautomator2-server/releases/download/v0.1.5/appium-uiautomator2-server-debug-androidTest.apk
info UiAutomator2 UiAutomator2 Server APKs downloaded
npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "appium@beta"
npm ERR! node v4.4.0
npm ERR! npm  v2.14.20
npm ERR! code ELIFECYCLE

npm ERR! appium-windows-driver@0.4.1 install: `node install-npm.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the appium-windows-driver@0.4.1 install script 'node install-npm.js'.
npm ERR! This is most likely a problem with the appium-windows-driver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install-npm.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs appium-windows-driver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls appium-windows-driver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

**Comment by mykola-mokhnach** [comment]
Update nodejs and npm to the most recent version and try again

**Comment by padmakarsrinivas** [comment]
@mykola-mokhnach  thanks for the help solved the problem by updating the nodejs and npm.
