### ISSUE TITLE
"[ADB] Incorrect package and activity. Retrying." after using runAppInBackground()

### ISSUE THREAD

**Issue by Corji** [appium/appium#8423]
## The problem
For a specific test case i have to close and reopen the app in the same activity without resetting anything. The command driver.runAppInBackground(5) works well and the right screen appears after 5 seconds. But afterwarts the appium server says that the package and activity are incorrect

`[ADB] Incorrect package and activity. Retrying.
[ADB] Getting focused package and activity
[ADB] Getting connected devices...
[ADB] 1 device(s) connected.`

## Environment

* Appium version: 1.0.0
* Desktop OS/version used to run Appium: Windows 7
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Android 6.0.1
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium Desktop

## Details

I tryed to close the Application with the home button then open the application with the application icon on the screen or with driver.startActivity(). Both ways results on the homescreen of the application and not on that one i was before.

**Comment by mykola-mokhnach** [comment]
There is a known bug there, which was fixed in Appium 1.6.5-beta

**Comment by Corji** [comment]
And how i can get this version? I cant find any version for Appium Desktop or windows :(

**Comment by mykola-mokhnach** [comment]
It's only available via npm:

```
npm install -g appium@1.6.5-beta
```

**Comment by Corji** [comment]
Is there a plan to merge this into Appium Desktop?

**Comment by Corji** [comment]
I tried it now with 1.6.5-beta, got the same issue... Do you have a link to the existing issue? I dont think this is corrected yet.

**Comment by Corji** [comment]
Ok, randomly on my seccond attempt it worked -.-

**Comment by igalep** [comment]
I'm using 1.6.5 stable ver , but getting the same result as described.

The app goes to background and then return , but the next step fails on : 
```
"org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Error occured while starting App. Original error: com.citi.privatebank.inview.login.LoginActivity or com.citi.privatebank.inview.client.uatAutomation.debug.com.citi.privatebank.inview.login.LoginActivity never started (WARNING: The server did not provide any stacktrace information)
"
```

Any Ideas ?
Thanks

**Comment by BankUserJay** [comment]
I am facing issue(Incorrect Package and Activity), with Appium Version 1.6.5, 1.6.6beta4 and 1.7.1 and Android version 6.0 - 8.0.1.
Tried with appActivity, appWaitActivity but it didn't work. Please suggest on this issue Mykola Mokhnach.

**Comment by estefafdez** [comment]
As BankUserJay commented, I have the same issue with appium version 1.7.1. The unusual thing is that I can see the app launched and the first activity there but appium does not recognize it. Any other solution please?

**Comment by rpjesivac** [comment]
I am/was also seeing this error with v1.7.1.. restarting device did help and now I am not seeing this error anymore (for now)

**Comment by Corji** [comment]
I havent had this error since then. Im using appium 1.7.1.

**Comment by Roscian1Frank** [comment]
` Running 'C:\apps\Sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","03157df32843862c","shell","dumpsys","window","windows"]
[debug] [ADB] Found package: 'com.connectib.centremk' and fully qualified activity name : 'com.connectib.centremk.mobile.LandingActivity'
[debug] [ADB] Incorrect package and activity. Retrying.
[ADB] Error: Error occured while starting App. Original error: 'com.connectib.centremk.mobile.HomeNavDrawerActivity' never started
    at Object.wrappedLogger.errorAndThrow (C:\Users\Roscian Frank\AppData\Roaming\npm\node_modules\appium\node_modules\appium-support\lib\logging.js:69:13)
    at ADB.callee$0$0$ (C:\Users\Roscian Frank\AppData\Roaming\npm\node_modules\appium\node_modules\appium-adb\lib\tools\apk-utils.js:101:9)
    at tryCatch (C:\Users\Roscian Frank\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\Roscian Frank\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\Roscian Frank\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\Roscian Frank\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at <anonymous>
 Error: Error occured while starting App. Original error: 'com.connectib.centremk.mobile.HomeNavDrawerActivity' never started
    at Object.wrappedLogger.errorAndThrow (C:\Users\Roscian Frank\AppData\Roaming\npm\node_modules\appium\node_modules\appium-support\lib\logging.js:69:13)
    at ADB.callee$0$0$ (C:\Users\Roscian Frank\AppData\Roaming\npm\node_modules\appium\node_modules\appium-adb\lib\tools\apk-utils.js:101:9)
    at tryCatch (C:\Users\Roscian Frank\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\Roscian Frank\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\Roscian Frank\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\Roscian Frank\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at <anonymous>`


Having the same issue Please help

**Comment by irfanpace** [comment]
[debug] [ADB] Incorrect package and activity. Retrying.
[debug] [ADB] Getting focused package and activity

Console:
An unknown server-side error occurred while processing the command. Original error: Cannot start the 'com.karwatechnologies.karwataxi' application. Original error: 'com.karwatechnologies.karwataxi.activities.LauncherActivity' or 'com.karwatechnologies.karwataxi.com.karwatechnologies.karwataxi.activities.LauncherActivity' never started

**Comment by irfanpace** [comment]
Appium Error:
[debug] [ADB] Found package: 'com.karwatechnologies.karwataxi' and fully qualified activity name : 'com.karwatechnologies.karwataxi.activities.OnBoardingActivity'
[debug] [ADB] Incorrect package and activity. Retrying.
[debug] [ADB] Getting focused package and activity
[debug] [ADB] Running 'C:\Users\mirfan\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZY223CHKZH shell dumpsys window windows'
[debug] [ADB] Incorrect package and activity. Retrying.
[debug] [ADB] Getting focused package and activity

Console:
An unknown server-side error occurred while processing the command. Original error: Cannot start the 'com.karwatechnologies.karwataxi' application. Original error: 'com.karwatechnologies.karwataxi.activities.LauncherActivity' or 'com.karwatechnologies.karwataxi.com.karwatechnologies.karwataxi.activities.LauncherActivity' never started

I have tried with 1.3, 1.6.2, 1.6.5 beta version, having the same error.

Please suggest me on this

**Comment by Roscian1Frank** [comment]
@irfanpace 
Use one of the found activity 
Found package: 'com.karwatechnologies.karwataxi' and fully qualified activity name : 'com.karwatechnologies.karwataxi.activities.OnBoardingActivity'

**Comment by Roscian1Frank** [comment]
@nagarjunay 
try adding `capabilities.setCapability("autoGrantPermissions",true);`
And then  wait for correct activity with `capabilities.setCapability("appWaitActivity","Your activity")`
