### ISSUE TITLE
Not finding the -tests.jar file in the target folder built through maven

### ISSUE THREAD

**Issue by vinyasjain77** [appium/appium#8424]
## The problem

I am trying to run my project on Device farm. Hence I am using maven build tool using pom.xml file. I have added all the required dependencies, plugins in pom.xml and zip.xml. But on building the application the -tests.jar file is missing. Due to which I am not able to add my zip-dependency.zip file in device farm. I am running a mobile automation test

## Environment

* Appium version (or git revision) that exhibits the issue:1.6.3

* Desktop OS/version used to run Appium: 10.12.1

* Mobile platform/version under test: iOS

**Comment by mykola-mokhnach** [comment]
Can you explain how this is related to Appium server?

**Comment by dpgraham** [comment]
I'm going to close this for now. If you can demonstrate that it's an Appium issue, I'll re-open it.
