### ISSUE TITLE
Appium Exception

### ISSUE THREAD

**Issue by Elangopalakrishnan** [appium/appium#8425]
## Appium Exception Handling

I need to handle the Appium Exception in my framework, i searched internet about appium exceptions but was not able to find out, it shows selenium webdriver exceptions only,

is there any specific exceptions which are belongs to appium driver ?
Please tell me links or what are the exception types in appium.

## Environment

* Appium version (or git revision) that exhibits the issue:1.6.4
* Desktop OS/version used to run Appium: iOS Device from windows c# 
* Mobile platform/version under test: iOS Devices
* Real device or emulator/simulator: Both

## Details

I'am using the codedui framework in c# selenium , and testing the iOS Devices.

I need to handle the Appium Exception in my framework, i searched internet about appium exceptions but was not able to find out, it shows selenium web driver exceptions only,
Please tell me appium exception list or what are the exceptions you have faced !

Thanks in advance!
Elango

**Comment by mykola-mokhnach** [comment]
![vna3vw](https://cloud.githubusercontent.com/assets/7767781/25943308/c24db00e-363f-11e7-8e9b-fe2692511796.jpg)

**Comment by imurchie** [comment]
Appium exposes the same errors as Selenium. They are specified here: https://github.com/appium/appium-base-driver/blob/master/lib/mjsonwp/errors.js
