### ISSUE TITLE
Is it possible to check the iOS test application update?

### ISSUE THREAD

**Issue by Akapylechka** [appium/appium#8427]
## The problem
I wanted to update the application without deleting it to check the correct migration. How can this be done? I'm using Junit for test, If it's important.

## Environment

Appium version (or git revision) that exhibits the issue: 1.0.0
Last Appium version that did not exhibit the issue (if applicable): -
Desktop OS/version used to run Appium: 10.12.4
Node.js version (unless using Appium.app|exe):
Mobile platform/version under test: iOS 9.3-10.3
Real device or emulator/simulator: simulator
Appium CLI or Appium.app|exe: app

**Comment by mykola-mokhnach** [comment]
Appium has **noReset**, which allows to start the driver without touching the app if it is installed. The install itself could be performed by running 

```
xcrun simctl install ...
```

please use Appium forum to ask questions - this is the place for issues
