### ISSUE TITLE
Submit() Form

### ISSUE THREAD

**Issue by KatGr** [appium/appium#8428]
## The problem

Hello,
I try to test a Search-Function, which is implemented by a form. 
As I don't have any button to submit the input, there has to be another way.
Unfortunately I didn't find any solutions in the internet. Some suggested submit() but it didn't work. Can anybody help me?

My Code:

```
it("should Search Inventory List", function(){
  return driver
  .elementByXPath('//*[1]//*[1]//*[1]//*[3]//*[1]//*[1]//*[1]//*[3]').type('176').submit().sleep(1000)
});
```

## Environment

* Appium version: 1.6.4
*  Running on Mac
* Node.js version : 7.5.0
* Testin on iOS (XCode)

##Logs

![screen shot 2017-05-11 at 12 16 34](https://cloud.githubusercontent.com/assets/26592218/25944465/c025899c-3643-11e7-8a12-f706ecad7421.png)

**Comment by mykola-mokhnach** [comment]
This is not related to Appium issues. Please use Appium forum for questions.
