### ISSUE TITLE
Appium Inspector showing the app objects hierarchy in landscape but the image to the left is in portrait 

### ISSUE THREAD

**Issue by dmcdonaldshopkeep** [appium/appium#8429]
## The problem

Whenever I open the Appium inspector the object hierarchy is correct but the image to the left is not correct it is shown in portrait , this makes find elements extremely difficult. This also happens with the independently downloaded Appium inspector. Is there anyway I can readjust the image to the left (see attached screenshot)

## Environment

- Appium Desktop 
- iOS 10.2 simulator built using Xcode 8.2.1 

<img width="1075" alt="screen shot 2017-05-11 at 11 22 46" src="https://cloud.githubusercontent.com/assets/12693556/25945163/d59093cc-363d-11e7-9e17-3b857b2e92db.png">

**Comment by mykola-mokhnach** [comment]
This is known XCTest bug. Please report to Apple
