### ISSUE TITLE
uiautomator2 - Can not enter text into password fields

### ISSUE THREAD

**Issue by vanangelov** [appium/appium#8430]
## The problem

When using uiautomator2, entering text into password fields fails

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Desktop OS/version used to run Appium: Mac OS Sierra 10.12.4
* Node.js version (unless using Appium.app|exe): Using appium-desktop
* Mobile platform/version under test: Android (tested on 5.1 and 7.1.1)
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: appium-desktop 1.0

## Details

I have recently tried to switch to using uiautomator2 to workaround another problem that I am having with Android 7 (see https://github.com/appium/appium/issues/7775). Unfortunately with uiautomator2 I can not type into password text fields (tested both on Android 5.1 and 7.1.1 emulators):

```
@AndroidFindBy(id="login_password")
public WebElement passwordField;

....

passwordField.sendKeys(password);
```
sendKeys seems to pass successfully as the test continues after this point, however nothing is actually entered into the field. I tried various things like clicking the field first, clearing it, etc. but nothing helped.

## Link to Appium logs

https://gist.github.com/vanangelov/980d2cc782e7fcb8704a75e2a13e2af7

**Comment by imurchie** [comment]
Sorry for the delay. This works with the latest version, on both emulators and real devices.

**Comment by webmagit** [comment]
Hi @imurchie - would there be a quick way I can get appium to point to the latest uiautomator2 so I can get your fix? Thanks!
