### ISSUE TITLE
@#[line:0,col:undefined] [xmldom error]	element parse error: TypeError: source.indexOf is not a function

### ISSUE THREAD

**Issue by stephenws** [appium/appium#8434]
## The problem

I am trying to inspect element using Appium- inspector but as soon as when i hit inspector.html in browser i got error in appium log 
@#[line:0,col:undefined]
[xmldom error]	element parse error: TypeError: source.indexOf is not a function 

and inspector.html url shows Error " Appium source at http://localhost:4723/wd/hub/session/1c8f1c1e-d547-42e3-a7b7-9354d58c346d/source cannot be received after 10 seconds timeout. Click this message to retry."

and could not capture screen to inspect element

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: 10.12.4
* Node.js version (unless using Appium.app|exe):v6.10.1
* Mobile platform/version under test: iOS 10.0.1
* Real device or emulator/simulator:Real Device
* Appium CLI or Appium.app|exe: CLI

## Details

1 I have added breakpoint in my Automation script
2. Now Start my automation script , script starts exceuting and it stops on Login screen as per my breakpoint added
3 now i hit file:///Users/Mukesh/Downloads/Appium-iOS-Inspector-master/iOS%20Inspector.html Url to inspect element from screen
4 But after hitting URL i below message in my appium terminal and it goes continues.
@#[line:0,col:undefined]
[xmldom error]	element parse error: TypeError: source.indexOf is not a function 
5. And in Url i got message" Appium source at http://localhost:4723/wd/hub/session/1c8f1c1e-d547-42e3-a7b7-9354d58c346d/source cannot be received after 10 seconds timeout. Click this message to retry."
but could not  capture screen .
[Logs.zip](https://github.com/appium/appium/files/993401/Logs.zip)

**Comment by mykola-mokhnach** [comment]
Remove WebDriverAgent application manually from the device and try again

**Comment by stephenws** [comment]
Hi @mykola-mokhnach i have tried bot not working

**Comment by mykola-mokhnach** [comment]
This error usually means you have incompatible versions of WDA and Appium server. Try to find out why these leftovers are still there

**Comment by stephenws** [comment]
It was working till 2 days ago but suddenly not working today, surprise! 
can you tell me brief what to do?please @mykola-mokhnach

**Comment by imurchie** [comment]
Removing the DerivedData folder might be useful too. I would specify where it is, but I won't open a zip file (post logs as a [gist](https://gist.github.com) as requested and we can see).

**Comment by stephenws** [comment]
Hi @imurchie I have uploaded log file as gist, please review
https://gist.github.com/stephenws/db88031d8a9e3ab6c141055cfb115f69

**Comment by imurchie** [comment]
* Remove WebDriverAgent-Runner from the device.
* `rm -rf /Users/Mukesh/Library/Developer/Xcode/DerivedData/WebDriverAgent-*`
* Rerun.

**Comment by stephenws** [comment]
Hi @imurchie i have done same changes that mentioned above, but still getting same Issue
I am uploading latest log file at gist please review
https://gist.github.com/stephenws/07e23778798d34116bb1bc04505501ef

**Comment by stephenws** [comment]
Hi Isaac, @imurchie any lead on the above issue?
I am stuck on this

**Comment by stephenws** [comment]
I have reinstall appium 1.6.4 , It works
