### ISSUE TITLE
Tap with duration (longPress) broken between python-client and appium-xcuitest-driver

### ISSUE THREAD

**Issue by cindysongzi** [appium/appium#8436]
The problem
I have encountered this problem as well. I run on python 3.5, appium 1.6.5-beta:
TouchAction(driver).long_press(el=None, x=ori_x,y=ori_y).move_to(x=end_x, y=end_y).wait(hold_time).release().perform()

Error
selenium.common.exceptions.WebDriverException: Message: Support for longPress(options={"x":716.5,"y":569,"duration":1000})-moveTo(options={"x":-4.5,"y":18})-wait(options={"ms":1000})-release(options={}) gesture is not implemented. Try to use "mobile: *" interface to workaround the issue. Only these gestures are supported:
doubleTap: doubletap
tap(options={"count":2})
tap: tap
tap-release
press-release
longPress: longpress
longpress-release
press-wait-release
drag: press-wait-moveTo-release
longpress-moveTo-release
scroll: press-moveTo-release

Environment
* Mac OS X 10.12.4
* Appium 1.6.5-beta
* Appium-Python-Client: 0.24
* Real device or emulator/simulator: iPad Air 2
* Simulator Version: 10.2

**Comment by mykola-mokhnach** [comment]
Already replied in https://github.com/appium/appium/issues/8405#issuecomment-301005973
Closed as not an Appium problem
