### ISSUE TITLE
iOS/WDA: unhandled endpoint touchAndHold if trying to use the tap-method

### ISSUE THREAD

**Issue by n-jooy** [appium/appium#8440]
## The problem

I am not able to run my iOS tests properly (or let's say "at all") anymore since we've updated our build (and local) machines to Sierra + Xcode 8.3.2. My first guess was that it will be fixed if I update from Appium 1.6.3 to 1.6.4 - however this did not do the job :(

The problem seems to be that whenever I try to use the method "tap", like e.g. `element.tap(1, 1);` I get a response from the appium server that "touchAndHold" is an unhandled endpoint (see attached gist). So it is not recognized by Appium / the WebDriverAgent. Not sure if this is an Appium or a WebDriverAgent issue though. 

The actual result if trying to tap something using the method mentioned above is a cancellation of my test run. What I tried is using `element.click();` instead of the tap method - surprinsingly this actually works like expected. Probably it is not mapped to the same touch action as the tap method. But I am not willing to replace every tap method in my code - it should work in the same way no matter if using tap/click ;) 

Is anyone else facing this issue, too? Maybe I did something wrong and there is a simple solution for that...

## Environment

* Appium version (CLI): 1.6.4 
* Xcode version: 8.3.2
* Desktop OS/version used to run Appium: Mac OS Sierra 10.12.4
* Node.js version: v5.9.0
* device, OS: iPhone 7, iOS 10.3.1

## Link to Appium logs
created a gist with the relevant appium log part: 
https://gist.github.com/n-jooy/756b44c4939316aca1db054b31d18b3f

**Comment by mykola-mokhnach** [comment]
This looks like a bug. Try _mobile: touchAndHold_ action as a workaround

**Comment by mykola-mokhnach** [comment]
I've double checked the code - should be ok. It might be you have some leftovers from the previous installation. Make sure you cleared the Xcode cache in DerivedData and the WDA executable from the device
