### ISSUE TITLE
WebDriverAgent opens the default URL (Appium.io) but sometimes not opening the actual URL

### ISSUE THREAD

**Issue by mare1012** [appium/appium#8441]
## The problem

After WebDriverAgent launching the default URL (Appium.io) the actual URL (https://www.google.com) sometimes isn't loading or showing on the iPhone , but i get the status 200 at the end. If i keep trying to run the script, which the actual URL should be called, i get the status 500.

## Environment

* Appium: 1.6.4
* Desktop OS: macOS Sierra Version 10.12.4
* Node.js version: v7.10.0
* Real device
* Appium CLI

## Details

i'm using python as a programming languange to test mobile safari on iPhone 6s (10.3.1) and XCUITest 2.72.2.  The test should call the URL (https://www.google.com), but it works only several times. The method i'm using for calling the URL is driver.get("https://www.google.com). And the driver is the localhost with the same port like appium server.

## Link to Appium logs

this log-file: URL sometimes loading sometimes not, but get status 200
https://gist.github.com/mare1012/14d0fd21389ef90f681346dcab9a8132

this log-file: After trying a few time status 500 will be shown
https://gist.github.com/mare1012/8e6201e4c1b681b3fdbff531436dfdd1

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
have you tried to set **safariInitialUrl** capability?

**Comment by mare1012** [comment]
Hallo @mykola-mokhnach thanks for your quick response.
yes i tried it already, but still get the same issue.  the difference what i see, google.com will be opened at first with this capability, but i can't see if the other google-URL will be called or not. And then status 500 will be shown (driver not closed) or safari sometimes didn't call the URL (browser not refreshing). If i didn't set safariInitialUrl, at least i can see that URL (google,com) is loading. That is what i think

**Comment by mare1012** [comment]
Any update on this?

**Comment by imurchie** [comment]
Does this issue still persist?

**Comment by mare1012** [comment]
this issue does still persist

**Comment by SilverMO8** [comment]
No update on how to fix?

**Comment by nunof** [comment]
+1

**Comment by imurchie** [comment]
A tonne has been updated between then and now. Please post logs (as a link to a [gist](https://gist.github.com) in order to have any hope in getting it fixed.

**Comment by mykola-mokhnach** [comment]
Closed as inactive. In case there still any problems with that then feel free to describe a new issue report

**Comment by michaelseno** [comment]
hi @mykola-mokhnach I would like to know if this issue is already fixed. I am experiencing the same issue:
Appium version: 1.13.0
Mobile iOS version: 12.1

Behavior: when trying to launch mobile safari, it launch Safari browser but will directly go to `appium.io` site and it will not continue. its still in the `init()` stage. i've tried using the  `safariInitialUrl` and pointed to `about:blank` or any other sites but still the same, it will open the initial url but cannot continue from there. Please let me know if you need more information. Thanks
