### ISSUE TITLE
Appium server is crashing and not able to start itself when using command "avm use 1.6.3"

### ISSUE THREAD

**Issue by anilwithrrs** [appium/appium#8442]
Appium version : 1.6.3
avm version : 0.1.2
node version : v6.10.3
npm version : 4.2.0

Below are the logs from appium server on startup ,

command used to trigger appium server is : **avm use 1.6.3**
[Appium] Welcome to Appium v1.6.3
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"iOS","app":"/Users/anilkumar04/Library/Developer/CoreSimulator/Devices/BFE9301C-1787-4E23-BF07-ECD26A39E55A/data/Containers/Bundle/Application/B07E5911-BE3B-4FC8-ADEF-CDD7EF0E91AB/Lido_mPilot.app","platformVersion":"10.2","deviceName":"iPad Air 2","noReset":true,"clearSystemFiles":true,"preventWDAAttachments":true,"autoAcceptAlerts":true}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformName":"iOS","app":"/Users/anilkumar04/Library/Developer/CoreSimulator/Devices/BFE9301C-1787-4E23-BF07-ECD26A39E55A/data/Containers/Bundle/Application/B07E5911-BE3B-4FC8-ADEF-CDD7EF0E91AB/Lido_mPilot.app","platformVersion":"10.2","deviceName":"iPad Air 2","noReset":true,"clearSystemFiles":true,"preventWDAAttachments":true,"autoAcceptAlerts":true},null,null,null,null]
[Appium] Requested iOS support with version >= 10, using XCUITest driver instead of UIAutomation-based driver, since the latter is unsupported on iOS 10 and up.
[Appium] Creating new XCUITestDriver session
[Appium] Capabilities:
[Appium]   platformName: 'iOS'
[Appium]   app: '/Users/anilkumar04/Library/Developer/CoreSimulator/Devices/BFE9301C-1787-4E23-BF07-ECD26A39E55A/data/Containers/Bundle/Application/B07E5911-BE3B-4FC8-ADEF-CDD7EF0E91AB/Lido_mPilot.app'
[Appium]   platformVersion: '10.2'
[Appium]   deviceName: 'iPad Air 2'
[Appium]   noReset: true
[Appium]   clearSystemFiles: true
[Appium]   preventWDAAttachments: true
[Appium]   autoAcceptAlerts: true
[debug] [XCUITest] XCUITestDriver version: 2.4.2
[BaseDriver] Session created with session id: e9bcb2fb-8cc6-4021-9e8c-136114fbdfcc
[debug] [XCUITest] Xcode version set to '8.2.1'
[debug] [XCUITest] iOS SDK Version set to '10.2'
[iOSSim] Constructing iOS simulator for Xcode version 8.2.1 with udid 'BFE9301C-1787-4E23-BF07-ECD26A39E55A'
[XCUITest] Determining device to run tests on: udid: 'BFE9301C-1787-4E23-BF07-ECD26A39E55A', real device: false
[BaseDriver] Using local app '/Users/anilkumar04/Library/Developer/CoreSimulator/Devices/BFE9301C-1787-4E23-BF07-ECD26A39E55A/data/Containers/Bundle/Application/B07E5911-BE3B-4FC8-ADEF-CDD7EF0E91AB/Lido_mPilot.app'
[debug] [XCUITest] Checking whether app '/Users/anilkumar04/Library/Developer/CoreSimulator/Devices/BFE9301C-1787-4E23-BF07-ECD26A39E55A/data/Containers/Bundle/Application/B07E5911-BE3B-4FC8-ADEF-CDD7EF0E91AB/Lido_mPilot.app' is actually present
[debug] [XCUITest] App is present
[debug] [ios-app-utils] Getting bundle ID from app '/Users/anilkumar04/Library/Developer/CoreSimulator/Devices/BFE9301C-1787-4E23-BF07-ECD26A39E55A/data/Containers/Bundle/Application/B07E5911-BE3B-4FC8-ADEF-CDD7EF0E91AB/Lido_mPilot.app': 'com.lhsystems.mpilot.development'
[debug] [iOSLog] Starting iOS 10.2 simulator log capture
[debug] [iOSLog] System log path: /Users/anilkumar04/Library/Logs/CoreSimulator/BFE9301C-1787-4E23-BF07-ECD26A39E55A/system.log
[XCUITest] Setting up simulator
[debug] [iOS] No reason to set locale
[debug] [iOS] No iOS / app preferences to set
[XCUITest] Simulator with udid 'BFE9301C-1787-4E23-BF07-ECD26A39E55A' not booted. Booting up now
[debug] [iOSSim] Killing all iOS Simulators
[iOSSim] Starting simulator with command: open -Fn /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app --args -CurrentDeviceUDID BFE9301C-1787-4E23-BF07-ECD26A39E55A
[iOSSim] Simulator log at '/Users/anilkumar04/Library/Logs/CoreSimulator/BFE9301C-1787-4E23-BF07-ECD26A39E55A/system.log'
[iOSSim] Tailing simulator logs until we encounter the string "com.apple.springboard"
[iOSSim] We will time out after 60000ms
[debug] [iOSSim] Waiting an extra 10000ms for the simulator to really finish booting
[debug] [iOSSim] Done waiting extra time for simulator
[iOSSim] Simulator booted in 17209ms
[debug] [XCUITest] Installing app '/Users/anilkumar04/Library/Developer/CoreSimulator/Devices/BFE9301C-1787-4E23-BF07-ECD26A39E55A/data/Containers/Bundle/Application/B07E5911-BE3B-4FC8-ADEF-CDD7EF0E91AB/Lido_mPilot.app' on device
[XCUITest] Using WDA path: '/usr/local/avm/versions/1.6.3/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/avm/versions/1.6.3/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: /usr/local/bin/carthage
[debug] [XCUITest] Running WebDriverAgent bootstrap script to install dependencies
[XCUITest] Error: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1
    at ChildProcess.<anonymous> (../../lib/teen_process.js:66:19)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
 { Error: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1
    at ChildProcess.<anonymous> (../../lib/teen_process.js:66:19)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  stdout: '\u001b[1mFetching dependencies\n*** Fetching peertalk\n*** Checking out peertalk at "v1.0"\n*** Fetching peertalk\n',
  stderr: 'A shell task (/usr/bin/env git fetch --prune --quiet https://github.com/marekcirkos/peertalk.git refs/tags/*:refs/tags/* +refs/heads/*:refs/heads/*) failed with exit code 128:\nfatal: could not read Username for \'https://github.com\': terminal prompts disabled\n\n',
  code: 1 }
[XCUITest] Shutting down sub-processes
[debug] [XCUITest] Reset not set, not ending sim
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1
    at ChildProcess.<anonymous> (../../lib/teen_process.js:66:19)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
[HTTP] <-- POST /wd/hub/session 500 29174 ms - 199

**Comment by mykola-mokhnach** [comment]
> stdout: '\u001b[1mFetching dependencies\n*** Fetching peertalk\n*** Checking out peertalk at "v1.0"\n*** Fetching peertalk\n',
stderr: 'A shell task (/usr/bin/env git fetch --prune --quiet https://github.com/marekcirkos/peertalk.git refs/tags/:refs/tags/ +refs/heads/:refs/heads/) failed with exit code 128:\nfatal: could not read Username for 'https://github.com': terminal prompts disabled\n\n',
code: 1 }

I assume you need to find out how to workaround this carthage error

**Comment by anilwithrrs** [comment]
could you please suggest over this issue , i am using carthage version => 0.22.0.

**Comment by arifmasood** [comment]
@anilwithrrs were you able to find the solution ?
I am trying to setup Appium desktop and I also get peertalk repo access errors while running following command ( ./Scripts/bootstrap.sh -d )..

It seems that this repo is no more public?
git clone --bare --quiet https://github.com/marekcirkos/peertalk.git

**Comment by imurchie** [comment]
Yes. Unfortunately it was removed. Older versions of Appium will not work.

Use the latest Appium version.

**Comment by arifmasood** [comment]
thanks for update @imurchie .. so with the new appium 1.6.4 .. we will not need to do the manual configuration steps as described on this page ??
https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md
    mkdir -p Resources/WebDriverAgent.bundle
    ./Scripts/bootstrap.sh -d

**Comment by imurchie** [comment]
You shouldn't need to do that, no. Appium runs that when necessary. There is still one dependency downloaded then, but not the one that is no longer available.
