### ISSUE TITLE
Appium Server Failed to start on AWS

### ISSUE THREAD

**Issue by andreiaionitoaiesv** [appium/appium#8443]
## The problem

I'm using Appium with python client. I'm running tests on AWS Device farm. Every time when the second tests starts, the appium server is failing to start. I think the issue might be that the UIAutomator server did not start or did not close in the previous session. Any ideas / workarounds ?

## Environment

* Appium version 1.6.3
* IPhone 6s, iOS v.10.3.1

Appium Logs:
https://gist.github.com/andreiaionitoaiesv/a200e4c7b5008b62254372afba3bd470
Logcat:
https://gist.github.com/andreiaionitoaiesv/d5f2ff6bc8750ed76711fb416ba1e434

**Comment by mykola-mokhnach** [comment]
It looks like the name of the activity _com.MyApp.test/.activities.SecondActivity_ you provided as capability is either incorrect or the app does not start at all. It just fails because of the timeout

**Comment by andreiaionitoaiesv** [comment]
I do not provide any activity since AWS will overide any desired_caps I send. So seems that is a timeout. Any ideas about a workaround for this, eventually in the AWS context?

**Comment by andreiaionitoaiesv** [comment]
Thanks found issue. Default activity of the app is not Login.
