### ISSUE TITLE
Question: Work with toast message on Android

### ISSUE THREAD

**Issue by HoratiuMoldovan** [appium/appium#8444]
## The problem

Regarding this discussion: https://discuss.appium.io/t/verifying-toast/3676/35  
related to toast messages, it is taken into consideration to be found a solution for Android in the near future?

**Comment by mykola-mokhnach** [comment]
This has already been [discussed](https://github.com/appium/appium/issues/8284) here

**Comment by dpgraham** [comment]
Closed as duplicate
