### ISSUE TITLE
Can't get environment variable working

### ISSUE THREAD

**Issue by jcavar** [appium/appium#8445]
## The problem

We are trying to use DYLD_PRINT_STATISTICS environment variable in our scenarios be we can't get it working. We are successfully sending launch arguments but environment is causing us issues.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS
* Node.js version (unless using Appium.app|exe): v7.9.0
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: Appium CLI

## Details

We spent quite a lot of time trying different combinations like putting `env` inside of `processArguments`, outside of it, prefixing `SIMCTL_CHILD_`, ... It seems like right way to pass it should be:
```
"processArguments": {"args": [], "env": {"DYLD_PRINT_STATISTICS": 1}}
```

If this flag is successfully applied, logs should contain something like this:
```
Total pre-main time: 1.1 seconds (100.0%)
         dylib loading time: 372.25 milliseconds (31.4%)
        rebase/binding time: 646.09 milliseconds (54.6%)
            ObjC setup time:  79.70 milliseconds (6.7%)
           initializer time:  85.07 milliseconds (7.1%)
           slowest intializers :
               libSystem.dylib :   3.25 milliseconds (0.2%)
```

Are we missing something here or it is Appium issue?

**Comment by mykola-mokhnach** [comment]
This is how it is implemented in Appium:

```javascript
    let args = processArguments ? processArguments.args : [];
    let env = processArguments ? processArguments.env : {};

    let shouldWaitForQuiescence = util.hasValue(this.opts.waitForQuiescence) ? this.opts.waitForQuiescence : true;
    let maxTypingFrequency = util.hasValue(this.opts.maxTypingFrequency) ? this.opts.maxTypingFrequency : 60;
    let shouldUseSingletonTestManager = util.hasValue(this.opts.shouldUseSingletonTestManager) ? this.opts.shouldUseSingletonTestManager : true;
    let shouldUseTestManagerForVisibilityDetection = false;
    if (util.hasValue(this.opts.simpleIsVisibleCheck)) {
      shouldUseTestManagerForVisibilityDetection = this.opts.simpleIsVisibleCheck;
    }
    if ((this.opts.platformVersion || '').indexOf('9') === 0) {
      shouldUseTestManagerForVisibilityDetection = true;
    }

    let desired = {
      desiredCapabilities: {
        bundleId,
        arguments: args,
        environment: env,
        shouldWaitForQuiescence,
        shouldUseTestManagerForVisibilityDetection,
        maxTypingFrequency,
        shouldUseSingletonTestManager,
      }
    };

    await this.proxyCommand('/session', 'POST', desired);
```

And this is WDA client

```objc
  app.launchEnvironment = (NSDictionary <NSString *, NSString *> *)requirements[@"environment"] ?: @{};
  [app launch];
```

So your way of passing env looks reasonable. The only note here, that the client expect both key and value to be of type string, so try setting it to "YES" instead of 1.

**Comment by jcavar** [comment]
Thanks for quick reply. It seems that it still doesn't work, neither of "YES" or "1"

**Comment by jcavar** [comment]
If relevant this is command that is sent to WDA
```
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.novastonemedia.finance.dev","arguments":["something"],"environment":{"DYLD_PRINT_STATISTICS":"YES"},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
```

**Comment by SergiyBeno** [comment]
@jcavar hope this can help somehow http://masilotti.com/ui-testing-stub-network-data/#working-with-launchenvironment

**Comment by jcavar** [comment]
It seems that this is not Appium bug in the end. Command that Appium sends to WebDriver looks ok, and I debugged WebDriver part and it seems that launchEnvironment is set correctly and passed to app, but logs are not show for some reason. This may be related to log type or something, not sure ...

**Comment by jcavar** [comment]
Just in case someone has the same problem:
The issue was that statistics are printed to stderr, which is console when debugger is attached and I don't know what when debugger is not attached. So our solution was to redirect stderr to our logs file:
`freopen(redirectLogPath, "a+", stderr);`

**Comment by sukeshmlr** [comment]
@jcavar  From which method are you redirecting the log? I am doing it from main still this does not get redirected to log file. Can you help?

**Comment by jcavar** [comment]
@sukeshmlr this is what we do:

```
void __attribute__ ((constructor)) premain() {
    // Redirect logs only if console is not attached
    if (!isatty(STDERR_FILENO)) {
        const char *redirect_log_path_char = [redirectLogPath cStringUsingEncoding:NSUTF8StringEncoding];
        NSLog(@"----Redirect stderr Path-----");
        NSLog(@"%s", redirect_log_path_char);
        NSLog(@"----Redirect stderr Path-----");
        freopen(redirect_log_path_char, "a+", stderr);
    }
}
```

**Comment by sukeshmlr** [comment]
@jcavar Thanks a lot! This is of great help.

**Comment by BoazWarshawsky** [comment]
Thanks jcavar, your solution solved my problem.

**Comment by fabioalmeida** [comment]
Thank you so much @jcavar, great solution! 👍
