### ISSUE TITLE
appium version takes too long

### ISSUE THREAD

**Issue by gedaiu** [appium/appium#8447]
## The problem

Getting the appium version takes 4 seconds... I am expecting that this command should work instantly
```
time appium -v
1.6.4

real	0m4.794s
user	0m3.789s
sys	0m0.329s
```

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Desktop OS/version used to run Appium: MacOs
* Node.js version (unless using Appium.app|exe): v7.10.0

**Comment by dpgraham** [comment]
That is a little slow, but I don't know that we need to fix it. It wouldn't impact anything.

**Comment by gedaiu** [comment]
@dpgraham it impacts a system that I have to monitor some servers that have appium installed... I can make a PR if anyone can help me to understand the cause

**Comment by dpgraham** [comment]
The file `lib/parser.js` parses command line arguments using an npm library called `argparse` and that file is imported by `lib/main.js`

One of the default behaviours of `argparse` is that it makes the -v flag print the version. I don't know if it's the library itself that is slow or if that appium is doing unnecessary work prior to logging the version number.

**Comment by gedaiu** [comment]
Thanks! I will look into it today

**Comment by imurchie** [comment]
The reason for the slowness is the way Node works. It loads all the dependencies and compiles the initial code, which is a slow process. There is really no way around this using the Appium program itself. It would be possible, though, to just read the `package.json`, and that could be added as an npm script.
