### ISSUE TITLE
get nil when call `mobile:` commands

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium#8449]
## The problem

from: https://github.com/appium/ruby_lib/issues/578

## Environment

* Appium version (or git revision) that exhibits the issue: fd19391aa1c4789eeb999dfaccb2edcda64e906f (master)
* Last Appium version that did not exhibit the issue (if applicable): no
* Desktop OS/version used to run Appium: Mac OS 10.12.4
* Node.js version (unless using Appium.app|exe): 6.9.5
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: CLI(ruby_lib)

## Details

https://github.com/appium/ruby_lib/tree/master/ios_tests

When ruby_lib calls `mobie:` commands, then Appium server returns null.
The following is `{"script":"mobile: alert","args":[{"action":"getButtons"}]}` case after https://github.com/appium/ruby_lib/blob/master/ios_tests/lib/ios/specs/ios/xcuitest_gestures.rb#L85 .

```
[JSONWP Proxy] Replacing sessionId 05869B62-C559-43AD-A343-BAACAAE00CBB with d4f5f7b9-3ec9-4d18-a586-11e7df8e39b9
[HTTP] <-- GET /wd/hub/session/d4f5f7b9-3ec9-4d18-a586-11e7df8e39b9/element/2515804C-15C3-4E5E-A585-37027652878B/attribute/name 200 168 ms - 80
[HTTP] --> POST /wd/hub/session/d4f5f7b9-3ec9-4d18-a586-11e7df8e39b9/execute {"script":"mobile: alert","args":[{"action":"getButtons"}]}
[debug] [MJSONWP] Calling AppiumDriver.execute() with args: ["mobile: alert",[{"action":"getButtons"}],"d4f5f7b9-3ec9-4d18-a586-11e7df8e39b9"]
[debug] [XCUITest] Executing command 'execute'
[debug] [JSONWP Proxy] Proxying [GET /wda/alert/buttons] to [GET http://localhost:8100/session/05869B62-C559-43AD-A343-BAACAAE00CBB/wda/alert/buttons] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : [\n    \"OK\"\n  ],\n  \"sessionId\" : \"05869B62-C559-43AD-A343-BAACAAE00CBB\",\n  \"status\" : 0\n}"
[debug] [MJSONWP] Responding to client with driver.execute() result: null
[HTTP] <-- POST /wd/hub/session/d4f5f7b9-3ec9-4d18-a586-11e7df8e39b9/execute 200 269 ms - 76
```

## Link to Appium logs

the above is.

## Code To Reproduce Issue [ Good To Have ]

Can get body's value, ["OK"] in the above case.

**Comment by KazuCocoa** [comment]
cc: @mykola-mokhnach

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium-xcuitest-driver/pull/440

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-xcuitest-driver/pull/440 has merged.
Thanks 😄
