### ISSUE TITLE
Can not turn off the WIFI

### ISSUE THREAD

**Issue by DavidGangel** [appium/appium#8450]
## The problem
Can not turn off the WIFI on Android device by this call:
((HasNetworkConnection) getDriver()).setConnection(Connection.NONE);

This assertion is "lying":
assertEquals(Connection.NONE, driver.getConnection());

When you run the test on a real device the assertion just passes through however the wifi of the device remains ON.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3, 1.6.4
* Desktop OS/version used to run Appium: Linux
* Node.js version (unless using Appium.app|exe): 6.10.2
* Mobile platform/version under test: Android 4.4.2
* Real device or emulator/simulator: Real device, LG Optimus G, Samsung Galaxy S2
* Appium CLI or Appium.app|exe: Java client lib

See the relevant part of the log:
```
[debug] [ADB] Running '/home/gangeld/Android/Sdk/platform-tools/adb' with args: ["-P",5037,"-s","LGE975db18707c","forward","tcp:4724","tcp:4724"]
[debug] [UiAutomator] Starting UiAutomator
[debug] [UiAutomator] Moving to state 'starting'
[debug] [UiAutomator] Parsing uiautomator jar
[debug] [UiAutomator] Found jar name: 'AppiumBootstrap.jar'
[debug] [ADB] Running '/home/gangeld/Android/Sdk/platform-tools/adb' with args: ["-P",5037,"-s","LGE975db18707c","push","/usr/.npm-global/lib/node_modules/appium/node_modules/appium-android-bootstrap/boots$
[debug] [ADB] Attempting to kill all uiautomator processes
[debug] [ADB] Getting all processes with uiautomator
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/home/gangeld/Android/Sdk/platform-tools/adb' with args: ["-P",5037,"-s","LGE975db18707c","shell","ps"]
[ADB] No uiautomator process found to kill, continuing...
[debug] [UiAutomator] Starting UIAutomator
[debug] [ADB] Creating ADB subprocess with args: ["-P",5037,"-s","LGE975db18707c","shell","uiautomator","runtest","AppiumBootstrap.jar","-c","io.appium.android.bootstrap.Bootstrap","-e","pkg","com.tel.$
[debug] [UiAutomator] Moving to state 'online'
[AndroidBootstrap] Android bootstrap socket is now connected
[debug] [AndroidBootstrap] Watching for bootstrap disconnect
[debug] [AndroidBootstrap] Ignoring bootstrap disconnect
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/home/gangeld/Android/Sdk/platform-tools/adb' with args: ["-P",5037,"-s","LGE975db18707c","shell","am","broadcast","-a","io.appium.settings.wifi","--es","setstatus","disable"]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] json loading complete.
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Registered crash watchers.
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Client connected
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/home/gangeld/Android/Sdk/platform-tools/adb' with args: ["-P",5037,"-s","LGE975db18707c","shell","am","broadcast","-a","io.appium.settings.data_connection","--es","setstatus","disab$
[debug] [Logcat] Stopping logcat capture
[debug] [ADB] Restarting adb
[debug] [ADB] Running '/home/gangeld/Android/Sdk/platform-tools/adb' with args: ["-P",5037,"-s","LGE975db18707c","wait-for-device"]
[debug] [UiAutomator] Moving to state 'stopped'
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/home/gangeld/Android/Sdk/platform-tools/adb' with args: ["-P",5037,"-s","LGE975db18707c","shell","echo","ping"]
[debug] [Logcat] Starting logcat capture
[debug] [ADB] Forwarding system: 4724 to device: 4724
[debug] [ADB] Running '/home/gangeld/Android/Sdk/platform-tools/adb' with args: ["-P",5037,"-s","LGE975db18707c","forward","tcp:4724","tcp:4724"]
[debug] [UiAutomator] Starting UiAutomator
[debug] [UiAutomator] Moving to state 'starting'
[debug] [UiAutomator] Parsing uiautomator jar
```

**Comment by mykola-mokhnach** [comment]
It would be good to have Appium log

**Comment by DavidGangel** [comment]
Added to the description.

**Comment by mykola-mokhnach** [comment]
does it disable wifi on the phone if you execute

```
adb shell am broadcast -a io.appium.settings.data_connection --es setstatus disable
```

from the command line?

**Comment by DavidGangel** [comment]
No, Wifi stays ON.

**Comment by mykola-mokhnach** [comment]
1. Check the version of Appium Settings app on the phone. It should be 2.1 or later
2. Get the adb logcat output after this command has been executed - it might contain useful information

**Comment by DavidGangel** [comment]
@mykola-mokhnach the version is 1.0

How can this be upgraded to the latest?

**Comment by mykola-mokhnach** [comment]
It is usually installed together with Appium. Uninstall Appium Settings app from your device manually and make sure you run Appium 1.6.4 or higher.

**Comment by DavidGangel** [comment]
@mykola-mokhnach 
Now I have 2.1 at my device.
When I run the command the WIFI still stays ON.
Log attached:
[log.txt](https://github.com/appium/appium/files/1007080/log.txt)

**Comment by mykola-mokhnach** [comment]
I don't see any errors in logs. Try to enable airplane mode as a workaround. If you still need only wifi to be enabled disabled then you can debug the app on your phone yourself. Here is the source  code:https://github.com/appium/io.appium.settings

**Comment by DavidGangel** [comment]
@mykola-mokhnach this ticket is about turning OFF the Wifi.
If this is not working then it's a valid issue and needs to be fixed.
The airplaine mode is not a workaround as it does not turns off the wifi.- This is another ticket actually.

So at the moment there is NO way to disconnect from the Wifi with appium.

**Comment by mykola-mokhnach** [comment]
Also try with Appium 1.6.5-beta. It contains the most recent version of Appium settings app
