### ISSUE TITLE
Desired Capabilities orientation setting to LANDSCAPE doesn't work running on iPad Air 2 Simulator

### ISSUE THREAD

**Issue by cindysongzi** [appium/appium#8451]
## The problem
Desired Capabilities orientation setting to LANDSCAPE doesn't work running on iPad Air 2 Simulator

## Environment
* Appium versio: 1.6.5-beta
* Mac os Sierra version: 10.12.4
* Simulator: iPad Air 2, 10.2

## Details
iPad Air 2 simulator stays PORTRAIT even with desired_caps("orientation" = 'LANDSCAPE'). 
I need the simulator stay LANDSCAPE, because my app doesn't rotate automatically according to simulator's orientation.

**Comment by mykola-mokhnach** [comment]
This is known XCTest bug. Please report to Apple.

**Comment by cindysongzi** [comment]
@mykola-mokhnach Thank you.
