### ISSUE TITLE
XCUITest / iOS10.3.1 - isDisplayed() returns false for actually displayed elements

### ISSUE THREAD

**Issue by vanangelov** [appium/appium#8453]
## The problem

Appium always returns false when I check the for the visibility of the hamburger menu button in our app. I can successfully click the same button.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Desktop OS/version used to run Appium: Mac OS Sierra 10.12.4
* Node.js version (unless using Appium.app|exe): Using appium-desktop
* Mobile platform/version under test: iOS 10.3.1
* Real device or emulator/simulator: Real iPhone 6s 
* Appium CLI or Appium.app|exe: appium-desktop 1.0

## Details

I tried also `wait.until(visibilityOf(hamburgerButton))` - this failed as the button seemingly never becomes visible. Here is how the button looks within the app:

![image](https://cloud.githubusercontent.com/assets/8036774/26048790/417f4990-3961-11e7-8c6a-6987dfbdee63.png)

## Link to Appium logs

https://gist.github.com/vanangelov/329bbcf234f971a74a7b57cff156c89b

## Code To Reproduce Issue

``` 
    @iOSFindBy(accessibility = "menu")
    MobileElement hamburgerButton;
    ...
    System.out.println(hamburgerButton.isDisplayed());
    hamburgerButton.click();

```

**Comment by mykola-mokhnach** [comment]
Try to set **simpleIsVisibleCheck**  capability to _false_. Report this issue to https://github.com/facebook/WebDriverAgent/issues if this still does not help.
