### ISSUE TITLE
Appium-android-driver real deviceName return the device udid

### ISSUE THREAD

**Issue by miaddsilva** [appium/appium#8454]
## The problem

When I request all the device "capabilities" used for a test, the deviceName value that I get is the udid of the device.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Ubuntu 16.04
* Node.js version (unless using Appium.app|exe): 6.9.5
* Mobile platform/version under test: any Android
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: CLI

## Details
When I do a test to any android device I would like to have all device attributes used for that test. I noticed the deviceName that Appium response is in fact the udid. I look up to your appium-android-driver and noticed that the lib/driver.js on startAndroidSession you have the deviceName as this.adb.curDeviceId.  My question is if is it intended to be like this, the udid as the real deviceName? If not I can provide a PR.

```javascript
async startAndroidSession () {
    log.info(`Starting Android session`);
    // set up the device to run on (real or emulator, etc)
    this.defaultIME = await helpers.initDevice(this.adb, this.opts);

    // set actual device name, udid, platform version, screen size, model and manufacturer details
    this.caps.deviceName = this.adb.curDeviceId;
    this.caps.deviceUDID = this.opts.udid;
    this.caps.platformVersion = await this.adb.getPlatformVersion();
    this.caps.deviceScreenSize = await this.adb.getScreenSize();
    this.caps.deviceModel = await this.adb.getModel();
    this.caps.deviceManufacturer = await this.adb.getManufacturer();
```

## Link to Appium logs

[debug] [Chromedriver] Changed state to 'online'
[Appium] New AndroidDriver session created successfully, session e925eec0-3498-4621-8655-600ff352cd47 added to master session list
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1494416175630 (12:36:15 GMT+0100 (WEST))
[debug] [MJSONWP] Responding to client with driver.createSession() result: {"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"browserName":"Chrome","platformName":"Android","deviceName":"A0001","udid":"81cc7d9"},"browserName":"Chrome","platformName":"Android","deviceName":"81cc7d9","udid":"81cc7d9","deviceUDID":"81cc7d9","platformVersion":"6.0.1","deviceScreenSize":"1080x1920","deviceModel":"A0001","deviceManufacturer":"OnePlus"}
[HTTP] <-- POST /wd/hub/session 200 22423 ms - 586 

## Code To Reproduce Issue
```
 DesiredCapabilities capability = new DesiredCapabilities();

 capability.setCapability(MobileCapabilityType.PLATFORM_NAME, "Android");
 capability.setCapability(MobileCapabilityType.BROWSER_NAME, "Chrome");
 capability.setCapability(MobileCapabilityType.DEVICE_NAME, "A0001");
capability.setCapability("udid", "81cc7d9");
  WebDriver driver;
   driver = new AndroidDriver<MobileElement>(new URL("http://127.0.0.1:4723/wd/hub"), capability);
 System.out.println(((RemoteWebDriver)driver).getCapabilities());
```
The output that I get is:

Capabilities 

```
[{
    deviceScreenSize = 1080 x1920,
    networkConnectionEnabled = true,
    warnings = {},
    databaseEnabled = false,
    deviceName = 81 cc7d9,
    platform = LINUX,
    deviceUDID = 81 cc7d9,
    desired = {
        browserName = Chrome,
        platformName = Android,
        udid = 81 cc7d9,
        deviceName = A0001
    },
    platformVersion = 6.0 .1,
    webStorageEnabled = false,
    locationContextEnabled = false,
    takesScreenshot = true,
    browserName = Chrome,
    javascriptEnabled = true,
    deviceModel = A0001,
    platformName = Android,
    udid = 81 cc7d9,
    deviceManufacturer = OnePlus
}]
```

**Comment by dpgraham** [comment]
I could be wrong, but I think that when you're testing with a real device it goes with 'udid' as the 'deviceName'.

@imurchie @jlipps Can one of you confirm this?
