### ISSUE TITLE
Appium 1.6.4 sometimes input the wrong text

### ISSUE THREAD

**Issue by ghost** [appium/appium#8455]
## The problem

Appium 1.6.4 sometimes input the wrong text

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: not use desktop version of appium
* Node.js version (unless using Appium.app|exe): 6.10.2
* Mobile platform/version under test: android 6

## Details
input title "MiLive" to start broadcast,but the audience got title "MLive" on the mainpage ，sometimes，it is "MiLivee". i don't know why╮(￣▽￣")╭

##Appium Logs:

Starting test: Waliliveuitest.直播.普通直播.直播标题
20170515 17:20:31.675 :  INFO : ${title} = MiLive
20170515 17:20:31.676 :  INFO :     [MainThread] start_normal_broadcast(broadcast_type=0, title=MiLive, tag=None, password=None, share_list=None) - <Login>
20170515 17:20:39.551 :  INFO :     [MainThread]   cannot find the widget (type=TextView text=None id=com.wali.live:id/begin_btn)
20170515 17:20:43.209 :  INFO :     [MainThread]   the widget(type=TextView text=None id=com.wali.live:id/begin_btn) does not exist
20170515 17:20:43.209 :  INFO :     [MainThread]   Current Activity is not VideoLiveActivity, the widget (type=TextView text=None id=com.wali.live:id/begin_btn) is not exist
20170515 17:20:43.209 :  INFO :     [MainThread]   Start switch to home page!
20170515 17:20:44.251 :  INFO :     [MainThread]   the widget(type=RelativeLayout text=None id=com.wali.live:id/home_main_btn) is exist
20170515 17:20:44.251 :  INFO :     [MainThread]   Current page is already in MainPage!
20170515 17:20:44.251 :  INFO :     [MainThread]   Switch path is [<res.AndroidWidget.AndroidWidget object at 0x031CF4B0>, <res.AndroidWidget.AndroidWidget object at 0x031C3310>]
20170515 17:20:46.474 :  INFO :     [MainThread]   click widget(type=ImageView text=None id=com.wali.live:id/home_live_btn)
20170515 17:20:47.290 :  INFO :     [MainThread]   the widget(type=TextView text=None id=com.wali.live:id/begin_btn) is exist
20170515 17:20:47.291 :  INFO :     [MainThread]   Current Activity is VideoLiveActivity
20170515 17:20:47.291 :  INFO :     [MainThread]   Switch to VideoLiveActivity successful
20170515 17:20:47.291 :  INFO :     [MainThread]   select broadcast type is normal
20170515 17:20:47.489 :  INFO :     [MainThread]   click widget(type=TextView text=None id=com.wali.live:id/camera_title)
20170515 17:20:56.178 :  INFO :     [MainThread]   input MiLive to widget(type=EditText text=None id=com.wali.live:id/title_input)
20170515 17:20:56.178 :  INFO :     [MainThread]   set tag is None
20170515 17:21:02.711 :  INFO :     [MainThread]   cannot find the widget (type=TextView text=\xe7\x9b\xb4\xe6\x92\xad\xe6\xa0\x87\xe7\xad\xbe id=com.wali.live:id/tag_tv)
20170515 17:21:11.833 :  INFO :     [MainThread]   cannot find the widget (type=TextView text=None id=com.wali.live:id/tag_tv)
20170515 17:21:14.909 :  INFO :     [MainThread]   the widget(type=TextView text=None id=com.wali.live:id/tag_tv) does not exist
20170515 17:21:22.003 :  INFO :     [MainThread]   click widget(type=TextView text=None id=com.wali.live:id/room_type_public)
20170515 17:21:23.092 :  INFO :     [MainThread]   click widget(type=TextView text=None id=com.wali.live:id/begin_btn)
20170515 17:21:28.351 :  INFO :     [MainThread]   the widget(type=ImageView text=None id=com.wali.live:id/close_btn) is exist
20170515 17:21:28.351 :  INFO :     [MainThread]   Start normal broadcast successful
20170515 17:21:28.353 :  INFO :     [MainThread] get_anchor_information(live_id=29788257) - <Login>
20170515 17:21:29.094 :  INFO :     [MainThread]   the widget(type=TextView text=\xe7\x9b\xb4\xe6\x92\xad id=com.wali.live:id/home_main_tv) is exist
20170515 17:21:29.095 :  INFO :     [MainThread]   Current Activity is LiveMainActivity
20170515 17:21:29.095 :  INFO :     [MainThread]   Current Activity LiveMainActivity is already in front
20170515 17:21:29.511 :  INFO :     [MainThread]   click widget(type=TextView text=None id=com.wali.live:id/search_btn)
20170515 17:21:44.014 :  INFO :     [MainThread]   input 29788257 to widget(type=EditText text=None id=com.wali.live:id/search_input_edit_text)
20170515 17:21:45.121 :  INFO :     [MainThread]   click widget(type=TextView text=None id=com.wali.live:id/search_btn)
20170515 17:21:46.610 :  INFO :     [MainThread]   click widget(type=TextView text=\xe7\x9b\xb4\xe6\x92\xad\xe8\xb4\xa6\xe5\x8f\xb7\xef\xbc\x9a29788257 id=None)
20170515 17:21:47.397 :  INFO :     [MainThread]   widget(type=TextView text=None id=com.wali.live:id/my_nick) text=ilovemi
20170515 17:21:53.636 :  INFO :     [MainThread]   cannot find the widget (type=TextView text=None id=com.wali.live:id/level_tv)
20170515 17:22:00.083 :  INFO :     [MainThread]   widget(type=TextView text=None id=com.wali.live:id/live_times_tv) text=119
20170515 17:22:00.350 :  INFO :     [MainThread]   widget(type=TextView text=None id=com.wali.live:id/live_ticket_tv) text=0
20170515 17:22:00.609 :  INFO :     [MainThread]   widget(type=TextView text=None id=com.wali.live:id/follow_count_tv) text=8
20170515 17:22:00.763 :  INFO :     [MainThread]   widget(type=TextView text=None id=com.wali.live:id/fans_count_tv) text=7
20170515 17:22:07.106 :  INFO :     [MainThread]   cannot find the widget (type=TextView text=None id=com.wali.live:id/my_singature_tv)
20170515 17:22:13.901 :  INFO :     [MainThread]   widget(type=TextView text=None id=com.wali.live:id/hint_sent_diamond_count_tv) text=\xe9\x80\x81\xe5\x87\xba 0\xe9\x92\xbb
20170515 17:22:14.010 :  INFO :     [MainThread]   widget(type=TextView text=None id=com.wali.live:id/my_id_tv) text=\xe7\x9b\xb4\xe6\x92\xad\xe5\x8f\xb7\xe7\xa0\x81:29788257
20170515 17:22:14.580 :  INFO :     [MainThread]   the widget(type=TextView text=None id=com.wali.live:id/right_text_btn) is exist
20170515 17:22:14.722 :  INFO :     [MainThread]   the widget(type=TextView text=\xe6\xad\xa3\xe5\x9c\xa8\xe7\x9b\xb4\xe6\x92\xad id=com.wali.live:id/live_hint_tv) is exist
20170515 17:22:14.722 :  INFO :     [MainThread]   swipe_to_up() - <AndroidCommon>
20170515 17:22:16.522 :  INFO :     [MainThread]   widget(type=TextView text=None id=com.wali.live:id/title_hint) text=MLive
20170515 17:22:16.523 :  INFO :     [MainThread]   swipe_to_down() - <AndroidCommon>
20170515 17:22:16.947 :  INFO :     [MainThread]   return {'broadcast_title': u'MLive', 'broadcast_status': True, 'broadcast_type': '\xe6\x99\xae\xe9\x80\x9a\xe7\x9b\xb4\xe6\x92\xad'} {'tickets': u'0', 'sendDiamond': 0, 'fans': u'7', 'level': None, 'follow': u'8', 'sign': None, 'nickname': u'ilovemi', 'id': '29788257', 'times': u'119'}
20170515 17:22:16.947 :  INFO : &{anchor_info} = { tickets=0 | broadcast_title=MLive | broadcast_status=True | sendDiamond=0 | level=None | fans=7 | sign=None | broadcast_type=\xe6\x99\xae\xe9\x80\x9a\xe7\x9b\xb4\xe6\x92\xad | follow=8 | times=119 |...
20170515 17:22:16.949 :  FAIL : MLive != MiLive
20170515 17:22:16.950 :  INFO :     [MainThread] stop_broadcast() - <Login>
20170515 17:22:19.940 :  INFO :     [MainThread]   click widget(type=ImageView text=None id=com.wali.live:id/close_btn)
20170515 17:22:20.961 :  INFO :     [MainThread]   click widget(type=TextView text=\xe7\xa1\xae\xe5\xae\x9a id=com.wali.live:id/button1)
20170515 17:22:26.998 :  INFO :     [MainThread]   cannot find the widget (type=ImageView text=None id=com.wali.live:id/close_btn)
20170515 17:22:29.426 :  INFO :     [MainThread]   Stop broadcast successful

**Comment by mykola-mokhnach** [comment]
it might be the autocomplete feature on the phone changes the text

**Comment by tadesushilgithub** [comment]
I am also facing the same issue.

**Comment by huangzhen1xiaomi** [comment]
i get the same problem on my side. please have it fixed. we are using appium as our main UI automation framework. we are waiting to see it worked well.

**Comment by TomHappy** [comment]
i got the similar problem on some mobile phone,and i found its the Security Input Function of keyboard caused the problem, after i closed the security function of keyboard, it works well. Maybe you should check your device about the settings of keyboard

**Comment by ThenBreeze** [comment]
it is using appium android input manager for uinicode, how can i close the security function of keyboard?╮(￣▽￣")╭

**Comment by lehungcuong** [comment]
I want to open keyboard to check somethings. How to open it, because in appium, it has been hidden

**Comment by kirksl** [comment]
@imurchie why was this closed?  Is there a workaround or new release that fixed this?  I just tested this today.  Same device, same automation.  1.6 3 works perfect 100% of the time.  1.6.4, 1.6.5 consistently enter data I didn't request into fields, sometimes deleting the garbage text, sometimes not.

**Comment by imurchie** [comment]
It was closed because nothing had happened on it in a while, and there was no reproducible case.

We would love to be able to fix, but right now there is no information to go on.

**Comment by kirksl** [comment]
Let me know what you need to help you debug.

Here is a link to a test just run showing how the login password field gets rogue input that the test did not specify and how the scan vin input is additionally inserting words from the predictive text section of the keyboard in front of the vin: 2C3CCAAG1GH212485

For this test I have validation code that deletes all characters in the field and retries if the inserted text does not match what the text tried to put into it.

https://app.testobject.com/#/share/42072eec-0a9a-4aca-af90-96d867d39da5/appium

**Comment by kirksl** [comment]
@imurchie I've pulled the link for now as it's an internally developed app not for release yet.  Please let me know if you can take a look at this and I can provide a testobject.com link preferably through pm.
