### ISSUE TITLE
scrollIntoView doesn't work with Android

### ISSUE THREAD

**Issue by TomHappy** [appium/appium#8456]
## The problem

my android app has a long scrollable view,i try to use driver.findElementByAndroidUIAutomator(using) to scroll to a element on it,but the scrollable view Scroll back and forth,
so i could never get the element i want to
## Environment

* Appium version (or git revision) that exhibits the issue: v1.6.4
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe): v6.10.3
* Mobile platform/version under test: Android 5.1.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:

## Details

if the element is not far away the current screen(e.g.only need swipe 1 time to see it), uiautomator could find it.if the element is very far away the current screen（e.g.need swipe 5 times to see it）, uiautomator could not find it.It seems that uiautomator could not swipe to the bottom of the scrollable view

## Link to Appium logs

org.openqa.selenium.NoSuchElementException: Can't locate an element by this strategy: Locator map: 
- native content: "By.AndroidUIAutomator: new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().text("mytext"))" 

## Code To Reproduce Issue [ Good To Have ]
@WithTimeout(time = 50,unit = TimeUnit.SECONDS)
@AndroidFindBy(uiAutomator = "new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().text(\"mytext\"))")
AndroidElement a123;

a123.click();

**Comment by kcinman11358** [comment]
try this
                    return driver.FindElement(MobileBy.AndroidUIAutomator("new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().textMatches(\"" + myText + "\").instance(0))"));

**Comment by TomHappy** [comment]
@kcinman11358 Thank your advice, but i got the same results,it swipe up one time ,than swipe down one time, and enter the loop

**Comment by kcinman11358** [comment]
Here is my full implementation. It's worked for me those situations. Just make sure that your ClassName is correct

if (BuildInfo.platform == "Android")
            {
                //Sleep needed in the cases of navigating away from a screen and coming back to. This gives the driver a chance to catch up.
                Thread.Sleep(700);
                try
                {
                    //UiSelector arguments must only call "scrollIntoView" method or methods on UIScrollable whcih return UiScrollable or UiObject objects
                    return driver.FindElement(MobileBy.AndroidUIAutomator("new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().textMatches(\"" + selector + "\").instance(0))"));
                }
                catch
                {
                    //Added because sometimes Android doesn't scroll all the way
                    IWebElement frame = driver.FindElements(By.ClassName("android.widget.ListView")).ElementAt(0);
                    int startx = frame.Location.X + (frame.Size.Width / 2);
                    int starty = frame.Location.Y + ((frame.Size.Height / 2) - 5);
                    int endx = startx;
                    int endy = starty -100;
                    driver.Swipe(startx, starty, endx, endy, 400);


                    return driver.FindElement(MobileBy.AndroidUIAutomator("new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().textMatches(\"" + selector + "\").instance(0))"));
                }
            }

**Comment by TomHappy** [comment]
Thats a good idea!

**Comment by balakrishnan-adappt** [comment]
its not works for me, still the issue exists. UiAutomator scrolls in one direction and after few scroll it scrolling towards opposite direction.

**Comment by kvinay729** [comment]
Did anyone succeed in scrolling on long scroll view.
