### ISSUE TITLE
when using appium desktop to inspect my Hybrid app in android, not getting the full source

### ISSUE THREAD

**Issue by Shahunks** [appium/appium#8460]
## The problem

when using appium desktop to inspect my Hybrid app in android, not getting the full source.
when the mouse is hovered on particular element , the full screen is highlighted. and its says parser error.

## Environment

* Appium version (or git revision) that exhibits the issue:1.6.4
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:MAC
* Node.js version (unless using Appium.app|exe):6.10.1
* Mobile platform/version under test: android 6.0
* Real device or emulator/simulator:emulator
* Appium CLI or Appium.app|exe:

![screen shot 2017-05-16 at 12 14 48 pm](https://cloud.githubusercontent.com/assets/25055088/26093076/de01bb6a-3a31-11e7-8198-cda6c0766bad.png)

**Comment by mykola-mokhnach** [comment]
It's hard to say anything without logs/screenshots

**Comment by Shahunks** [comment]
here is the log and screen shot

**Comment by Shahunks** [comment]
log- 
![screen shot 2017-05-16 at 5 46 23 pm](https://cloud.githubusercontent.com/assets/25055088/26105506/d6877932-3a5f-11e7-99e5-ccfe3c91d367.png)
https://gist.github.com/Shahunks/76635a28a3eacdaa7f06d153a55660c8
 the whole screen is selected not each message in the inbox

**Comment by dpgraham** [comment]
Unfortunately we don't capture WebView markup in Appium Inspector.

My recommendation is that you look into remote debugging of WebViews using Chrome devtools to inspect the contents of your WebView.
