### ISSUE TITLE
[AndroidDriver] Unable to grant permissions requested

### ISSUE THREAD

**Issue by arhsim** [appium/appium#8461]
## The problem
after setting up capabilities autoGrantPermissions: 'True', still application is asking for grant permission in every run.
## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows 7
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Android 6.1
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium-desktop v1.0.1

## Details

Using Robotframework using AppiumLibrary

snip from appium log :
[AndroidDriver] Unable to grant permissions requested. Original error: Error executing adbExec. Original error: 'Command 'E\:\\Android\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 04157df42d4cb030 shell pm grant com.orange.es.orangetv android.permission.INTERNET \; pm grant com.orange.es.orangetv android.permission.READ_PHONE_STATE \; pm grant com.orange.es.orangetv android.permission.ACCESS_WIFI_STATE \; pm grant com.orange.es.orangetv android.permission.CHANGE_WIFI_STATE \; pm grant com.orange.es.orangetv android.permission.ACCESS_NETWORK_STATE \; pm grant com.orange.es.orangetv android.permission.READ_LOGS \; pm grant com.orange.es.orangetv android.permission.READ_CALENDAR \; pm grant com.orange.es.orangetv android.permission.WRITE_CALENDAR \; pm grant com.orange.es.orangetv android.permission.BATTERY_STATS \; pm grant com.orange.es.orangetv android.permission.WRITE_EXTERNAL_STORAGE \; pm grant com.orange.es.orangetv android.permission.BLUETOOTH \; pm grant com.orange.es.orangetv android.permission.CHANGE_WIFI_MULTICAST_STATE \; pm grant com.orange.es.orangetv android.permission.BLUETOOTH_ADMIN \; pm grant com.orange.es.orangetv android.permission.WAKE_LOCK \; pm grant com.orange.es.orangetv android.permission.READ_EXTERNAL_STORAGE \;' exited with code 4294967295'; Stderr: 'error: bad service name length (1045)'; Code: '4294967295'

## Link to Appium logs

https://gist.github.com/arhsim/3faa6eaaab8f9e9f0cf5140f7be9c964

## Code To Reproduce Issue [ Good To Have ]

    Open Application    http://127.0.0.1:4723/wd/hub    platformName=${platform}    deviceName=${device}    platformVersion=6.0.1    udid=04157df42d4cb030    appPackage=com.orange.es.orangetv
    ...    appActivity=com.noriginmedia.tv.screens.MainActivity    autoGrantPermissions=True    noReset=False

**Comment by mykola-mokhnach** [comment]
i'll fix this

**Comment by mykola-mokhnach** [comment]
The fix has been merged and is available in Appium 1.6.5-beta
