### ISSUE TITLE
Appium installation through npm is not successful due to chromedriver error

### ISSUE THREAD

**Issue by DevaVG** [appium/appium#8462]
## The problem

npm install -g appium does not have successful installation and throws below error in details

## Environment

node v6.10.3
npm  v3.10.10
Windows 10

## Details

C:\Users\ext_veldev\AppData\Roaming\npm\node_modules\appium\build\lib\main.js

> appium-chromedriver@2.11.0 install C:\Users\ext_veldev\AppData\Roaming\npm\node_modules\appium\node_modules\appium-chromedriver
> node install-npm.js

info Chromedriver Install Installing Chromedriver version '2.28' for platform 'win' and architecture '32'
info Chromedriver Install Opening temp file to write chromedriver_win32 to...
info Chromedriver Install Downloading https://chromedriver.storage.googleapis.com/2.28/chromedriver_win32.zip...
RequestError: Error: self signed certificate in certificate chain
    at new RequestError (C:\Users\ext_veldev\AppData\Roaming\npm\node_modules\appium\node_modules\request-promise\lib\errors.js:11:15)
    at Request.RP$callback [as _callback] (C:\Users\ext_veldev\AppData\Roaming\npm\node_modules\appium\node_modules\request-promise\lib\rp.js:60:32)
    at self.callback (C:\Users\ext_veldev\AppData\Roaming\npm\node_modules\appium\node_modules\request\request.js:188:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (C:\Users\ext_veldev\AppData\Roaming\npm\node_modules\appium\node_modules\request\request.js:884:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1277:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
C:\Users\ext_veldev\AppData\Roaming\npm
`-- (empty)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.x (node_modules\appium\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "appium"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! appium-chromedriver@2.11.0 install: `node install-npm.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the appium-chromedriver@2.11.0 install script 'node install-npm.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the appium-chromedriver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install-npm.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs appium-chromedriver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls appium-chromedriver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\ext_veldev\npm-debug.log
npm ERR! code 1

**Comment by mykola-mokhnach** [comment]
Usually such errors happen because of corporate proxies and has nothing to do to Appium itself

**Comment by DevaVG** [comment]
I have no problems in installing other npm installation. Would you have some suggestion to overcome this?

**Comment by mohanrajmcad** [comment]
Try the step mentioned in the custom binary url section

https://github.com/appium/appium-chromedriver/blob/master/README.md#custom-binaries-url

**Comment by dpgraham** [comment]
@DevaVG The appium-chromedriver npm-install script pulls down the binary through 'https://chromedriver.storage.googleapis.com', which is separate from NPM. Your firewall/proxy is probably blocking that.

Try following the document that @mohanrajmcad linked to.

**Comment by DevaVG** [comment]
@mohanrajmcad and @dpgraham , Thanks for those and now i able to install successfully.

**Comment by MemoryReload** [comment]
@mohanrajmcad  After a mass of failure, You saved my ass. Thks!

**Comment by nccho** [comment]
In my case, the company was blocked by a firewall.

**Comment by MemoryReload** [comment]
@nccho  The Great Firewall, isn't it?  : )
