### ISSUE TITLE
Invalid timeout 'script'

### ISSUE THREAD

**Issue by Tallyb** [appium/appium#8465]
## The problem
Cannot run android tests due to: 
Error: WebDriverError: An unknown server-side error occurred while processing the command. Original error: Invalid timeout 'script'

## Environment
OSX 10.12.4
Appium 1.6.4 (with Appium UI) 
Node 6.10.1
Emulator: nexus 6p API 25

## Details
The problem occurs due to the following lines: 
https://github.com/appium/appium-base-driver/blob/master/lib/basedriver/commands/timeout.js#L13
The timeouts 'script' is supported in iOS timeouts, but not in base or android.
webdriver.io supports the 'script'. see here: http://webdriver.io/api/protocol/timeouts.html

## Link to Appium logs
https://gist.github.com/Tallyb/e90a0cbf94a144399972999debf9b745

## Code To Reproduce Issue [ Good To Have ]
this is protractor config: 
```
{
        seleniumAddress: 'http://localhost:4723/wd/hub',
        capabilities: {
            platformName: 'android',
            platformVersion: '7.1',
            deviceName: 'Nexus 6P',
            browserName: '',
            //autoWebview: true,
            app: <app package name>
            //autoWebviewTimeout: 4000
        },
        specs,
        useAllAngular2AppRoots: true,
        jasmineNodeOpts: {
            showColors: true,
            defaultTimeoutInterval: 300000
        },
        onPrepare: function() {
            var wd = require('wd'),
                protractor = require('protractor'),
                wdBridge = require('wd-bridge')(protractor, wd);

            wdBridge.initFromProtractor(exports.config);
        }
```

**Comment by dpgraham** [comment]
`scripts` is only supported on iOS

Can I see your client code snippet that's causing it to fail?

**Comment by Tallyb** [comment]
I am using protractor that is sending the command as part of the configuration. 
I believe it comes from here: https://github.com/angular/protractor/blob/c525ca6b277a6a8fea43632ae493c13999cddc94/lib/runner.ts#L281
Funny that they send a command supported by iOS but not by Android. Maybe they are in disagreement with the company developing android... 
I should close and refer to the protractor repo, but let me know what you think.

**Comment by dpgraham** [comment]
So Protractor is for web and not native Android. I think Web supports timeout and that's why protractor uses that.

Are you developing a WebView app? If yes, the issue is that you need to change the context to the WebView from the native context. There's a capability called `autoWebView` that you can set to true that automatically sets the context to your webview.

**Comment by Tallyb** [comment]
yes, it is a webview app (Crodova). autoWebView does not work due to Crosswalk. How do you set the webview otherwise?

**Comment by dpgraham** [comment]
If you have access to the WDIO session object you can manually change the 'context' from native to webview.

Here's the documentation: http://webdriver.io/api/mobile/contexts.html
