### ISSUE TITLE
Android WebTest fails on Parallel run 

### ISSUE THREAD

**Issue by saikrishna321** [appium/appium#8466]
When triggering android webtest on parallel threads specifying different chromeDriver ports, appium kills  the other chromedriver instance which kills UIAutomator

https://gist.github.com/saikrishna321/64315bab2c3c38b30207de5e422a02db

I see that we are calling killall explicitly  
https://github.com/appium/appium-chromedriver/blob/master/lib/chromedriver.js#L221

**Comment by SrinivasanTarget** [comment]
@jlipps @imurchie Can we hide this behind a ```desiredCapability``` ? Thoughts please.

**Comment by SrinivasanTarget** [comment]
@triager please label: Android

**Comment by saikrishna321** [comment]
@jlipps ping .. any help on this

**Comment by jlipps** [comment]
@saikrishna321 I don't see us calling killall--that line is only killing chromedrivers which are running on the specified port. is the port logic wrong somehow?

**Comment by saikrishna321** [comment]
@jlipps sorry my bad, your right we are killing running chromdrivers. But when triggered in parallel 
>UiAutomator exited unexpectedly with code 0, signal null i get this error what could the issue. 

Instance for second thread is not triggered. I'm specifying different chromedriver ports on start of server. I can make sure it was working fine on v 1.5.X

**Comment by saikrishna321** [comment]
closing as works fine with 1.6.6bet2
