### ISSUE TITLE
Intermittent issue: Appium unable to launch app in iOS and gets stuck, works well after restarting Mac machine

### ISSUE THREAD

**Issue by qual** [appium/appium#8468]
## The problem

- Appium is not able to launch iOS app, does some processing for web driver agent and gets stuck at following line: [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.qual.UIKitCatalog","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}

## Environment
* Appium version (or git revision) that exhibits the issue: Appium 1.6.4 (Desktop)
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS Sierra 10.12.4
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS 10.3
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: Appium Desktop (1.0.0) Appium server 1.6.4

## Details

- This issue occurs intermittently.
- It vanishes after restarting Mac machine
- One thing I noticed that:  simulator was already launched in this case
 

## Link to Appium logs
https://gist.github.com/qual/b348fd28eaf4f114a9559dee3cc8b593/revisions

## Code To Reproduce Issue [ Good To Have ]
capabilities.setCapability("platformName", "iOS");
capabilities.setCapability("deviceName", "iPhone");
capabilities.setCapability("udid", "1A195AB0-3341-436C-9A0D-37098205255D");
capabilities.setCapability("automationName", "XCUITest");
capabilities.setCapability("newCommandTimeOut", 1000);
System.out.println(capabilities);
capabilities.setCapability("bundleId", "com.qual.UIKitCatalog");
driver = new IOSDriver<MobileElement>(new URL("http://192.168.25.119:4723/wd/hub"), capabilities);
driver.findElementByAccessibilityId("UIKitCatalog").click();

**Comment by qual** [comment]
@mykola-mokhnach, @imurchie any update ?

**Comment by mykola-mokhnach** [comment]
The link to  appium log is corrupted.
I assume you'd want to set **noReset** capability to _true_ if only bundle id is provided.

**Comment by qual** [comment]
Here is the updated link:
https://gist.github.com/qual/b348fd28eaf4f114a9559dee3cc8b593/revisions

**Comment by mykola-mokhnach** [comment]
> +[JSONWP Proxy] Got response with status 200: {"value":"Failed to launch com.qual.UIKitCatalog application","sessionId":"0CD17261-B26F-45AF-B953-2A45E2DC3A81","status":13}

This error happens if WDA cannot find the app with given id on the simulator or it is installed, but cannot start even if executed manually.

**Comment by qual** [comment]
I verified that app was present in the simulator for sure. Also I was able to launch it manually as well. I just restarted the machine and it started working well.

**Comment by mykola-mokhnach** [comment]
Try to set **showXcodeLog** capability to true and then check the log from Xcode to see why WDA cannot start the app
