### ISSUE TITLE
Appium 1.4.16.1 showing error in windows 7 when click start node server

### ISSUE THREAD

**Issue by sreenu9** [appium/appium#8469]
> Launching Appium server with command: D:\Appium\node.exe lib\server\main.js --address 127.0.0.1 --port 4723 --no-reset --pre-launch --platform-name Android --platform-version 23 --automation-name Appium --log-no-color
> module.js:338
>     throw err;
>           ^
> Error: Cannot find module 'sprintf-js'
>     at Function.Module._resolveFilename (module.js:336:15)
>     at Function.Module._load (module.js:278:25)
>     at Module.require (module.js:365:17)
>     at require (module.js:384:17)
>     at Object.<anonymous> (D:\Appium\node_modules\appium\node_modules\argparse\lib\argument_parser.js:15:15)
>     at Module._compile (module.js:460:26)
>     at Object.Module._extensions..js (module.js:478:10)
>     at Module.load (module.js:355:32)
>     at Function.Module._load (module.js:310:12)
>     at Module.require (module.js:365:17)
> 
> 
> Appium server process ended

**Comment by mykola-mokhnach** [comment]
Appium 1.4 is old  and is not supported. Please use 1.6.4

**Comment by sreenu9** [comment]
but iam still facing issue once click on start node server

**Comment by sreenu9** [comment]
Launching Appium server with command: D:\Appium\node.exe lib\server\main.js --address 127.0.0.1 --port 4723 --no-reset --pre-launch --platform-name Android --platform-version 23 --automation-name Appium --log-no-color
module.js:338
throw err;
^
Error: Cannot find module 'sprintf-js'
at Function.Module._resolveFilename (module.js:336:15)
at Function.Module._load (module.js:278:25)
at Module.require (module.js:365:17)
at require (module.js:384:17)
at Object. (D:\Appium\node_modules\appium\node_modules\argparse\lib\argument_parser.js:15:15)
at Module._compile (module.js:460:26)
at Object.Module._extensions..js (module.js:478:10)
at Module.load (module.js:355:32)
at Function.Module._load (module.js:310:12)
at Module.require (module.js:365:17)

Appium server process ended
