### ISSUE TITLE
Scrolling to element in iOS using XCUITest not possible

### ISSUE THREAD

**Issue by oscheller1** [appium/appium#8471]
## The problem
Can not scroll to an element using XCUITest automation.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5-beta
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS
* Node.js version (unless using Appium.app|exe): 7.8.0
* Mobile platform/version under test: iOS 9.3 - 10.3
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: CLI

## Details

We've tried all the scrolling mechanisms that can be found using google search. Touch actions, and execute script. We didn't find any reliable way to scroll to an element in iOS. 
What's the current best practice to scroll to elements that are not displayed? (i.e. `element` is found, but `element.is_displayed()` is `False`.)

**Comment by mykola-mokhnach** [comment]
Have you tried any of [these](https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios-xctest-mobile-gestures.md) gestures?

**Comment by oscheller1** [comment]
Thank you for linking that documentation. We actually misused the execute_script method.

For everyone, the correct usage works as follows: Find the container which should be scrolled in using `driver.find_element_by_*`, then use that container element as "element" in the `execute_script` method. To find a child element inside the container, "predicateString" must be set to a predicate that identifies the child. 
```
self.driver.execute_script('mobile: scroll', {"element": table, "predicateString": "label == 'Option Validation'" })
```

Once again, thank you @mykola-mokhnach for helping out quickly, as always. It's much appreciated

**Comment by oscheller1** [comment]
Follow up question. Providing `"label == 'abc'"` works fine as a predicate, whereas `"name == 'some_id''` doesn't work. The appium server prints this error:

```
Calling AppiumDriver.execute() with args: ["mobile: scroll",[{"predicateString":"name == 'settings_debugging_option_validation'","element":{"ELEMENT":"1E83769D-5121-402E-900E-C803B07D79CC","element-6066-11e4-a52e-4f735466cecf":"1E83769D-5121-402E-900E-C803B07D79CC"}}],"d0b46a3a-66de-46ae-98c9-c91cbd314c46"]
[debug] [XCUITest] Executing command 'execute'
[debug] [JSONWP Proxy] Proxying [POST /wda/element/1E83769D-5121-402E-900E-C803B07D79CC/scroll] to [POST http://localhost:8100/session/BFC1CD73-11EF-4A86-81EA-0C7B9292AD36/wda/element/1E83769D-5121-402E-900E-C803B07D79CC/scroll] with body: {"predicateString":"name == 'settings_debugging_option_validation'"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":"[<XCElementSnapshot 0x7ffad6a18130> valueForUndefinedKey:]: this class is not key value coding-compliant for the key name.\n\n(\n\t0   CoreFoundation                      0x0000000107a6dd85 __exceptionPreprocess + 165\n\t1   libobjc.A.dylib                     0x00000001074e1deb objc_exception_throw + 48\n\t2   CoreFoundation                      0x0000000107a6d9c9 -[NSException raise] + 9\n\t3   Foundation                          0x000000010713f144 -[NSObject(NSKeyValueCoding) valueForUndefinedKey:] + 226\n\t4   Foundation                          0x0000000107095167 -[NSObject(NSKeyValueCoding) valueForKey:] + 280\n\t5   Foundation                          0x00000001070cfa55 -[NSFunctionExpression expressionValueWithObject:context:] + 1096\n\t6   Foundation                          0x00000001070cf532 -[NSComparisonPredicate evaluateWithObject:substitutionVariables:] + 243\n\t7   Foundation                          0x00000001070cf3d0 _filterObjectsUsingPredicate + 398\n\t8   Foundation          ...
[HTTP] <-- POST /wd/hub/session/d0b46a3a-66de-46ae-98c9-c91cbd314c46/execute 500 375 ms - 6654
```

**Comment by mykola-mokhnach** [comment]
The error has nothing to do with Appium. Please report to https://github.com/facebook/WebDriverAgent/issues

**Comment by sebinjqburst** [comment]
@mykola-mokhnach Hi,
I am unable to scroll to element even though I tried many methods. Could you please suggest me any working code that can be used to scroll to an element in an iOS application in landscape mode?
Thanks in advance.
