### ISSUE TITLE
Appium 1.6.4 Beta Hangs while running Automation

### ISSUE THREAD

**Issue by VenkateshPS** [appium/appium#8472]
## The problem

Appium 1.6.4 Beta Hangs while running Automation

## Environment

* Appium 1.6.4 Beta
* Last Appium version that did not exhibit the issue (if applicable):
* Mac OS sierra  version 10.12.3
* v7.5.0
* iPhone 6 iOS 10.2
* Real device 
* Appium CLI 

## Details

The hang was noticed after 30 minutes of run.
## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

<script src="https://gist.github.com/VenkateshPS/40c0d35ee8ea90606d7b417b817e5860.js"></script>

## Code To Reproduce Issue [ Good To Have ]

I am just running normal usability tests on my App, and the hang happens at random points.
e.g input password/Username .

**Comment by mykola-mokhnach** [comment]
Please fix the link to GIST

**Comment by mykola-mokhnach** [comment]
The freeze problem is usually related to https://github.com/facebook/WebDriverAgent/issues/372
It is recommended to check the device logs

**Comment by VenkateshPS** [comment]
https://gist.github.com/VenkateshPS/40c0d35ee8ea90606d7b417b817e5860

**Comment by mykola-mokhnach** [comment]
in your case it seems it is frozen at setValue call. Update to Appium 1.6.5-beta and play with custom value for **maxTypingFrequency** capability. See https://github.com/facebook/WebDriverAgent/issues/476 for the reference

Closed as non-Appium related issue
