### ISSUE TITLE
General question regarding Automator2 capability

### ISSUE THREAD

**Issue by parkwart** [appium/appium#8474]
## The problem

I read through the documentation and several issues regarding uiautomator2 and Android 7.
So I guess the solution to make Appium runing on Android 7 ist to set the capablity "automationName" to "uiautomator2" on client side.

What are your plans regarding that? Should it stay this way that the programmer decides which "automationName" will be used? Or will Appium support an internal decision which "automationName" is used?

In the current official documentain i only found the paragraph reagarding Android < 4.4 (selendroid).

Long story short:
Do I have the implement this behaviour or will it be included in an upcoming Appium release? Because I would expect that "automationName" : "appium" whould do the trick.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

-

## Link to Appium logs

-

## Code To Reproduce Issue [ Good To Have ]

-

**Comment by dpgraham** [comment]
@parkwart See this issue for discussion of Appium v2.0 https://github.com/appium/appium/issues/7175. This will give you an overview of what Appium will look like with regards to how drivers/automations are managed.
