### ISSUE TITLE
selectPickerWheelValue  method is not supported still

### ISSUE THREAD

**Issue by Siddh010** [appium/appium#8475]
## The problem

SelectPickerWheelValue  method is not working still 

Error message displayed as
Only scroll,swipe,pinch,doubleTap,twoFingerTap,touchAndHold,tap,dragFromToForDuration commands are supported.

 https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios-xctest-mobile-gestures.md

## Environment

* Appium version :1.6.4

## Details
https://github.com/appium/appium/issues/8059

## Link to Appium logs

org.openqa.selenium.UnsupportedCommandException: Unknown mobile command "selectPickerWheelValue". Only scroll,swipe,pinch,doubleTap,twoFingerTap,touchAndHold,tap,dragFromToForDuration commands are supported. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 140 milliseconds
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: 'C07R10GSG1HV', ip: '10.217.224.159', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_91'
Driver info: io.appium.java_client.ios.IOSDriver

## Code To Reproduce Issue [ Good To Have ]

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
It's only available in Appium 1.6.5-beta

**Comment by nvhoang56123** [comment]
Please kindly advise. I currently on 1.6.5

> Nguyens-MBP-2:~ nguyenvuhoang$ appium -v
> 1.6.5

But getting error 

> [HTTP] --> POST /wd/hub/session/61d2e236-ebbc-4f97-942e-069bd307deb9/execute {"script":"mobile: selectPickerWheelValue","args":[{"offset":0.15,"order":"next","element":"1AD01251-AD27-48F7-8F69-F11D77C117F5"}]}
> [debug] [MJSONWP] Calling AppiumDriver.execute() with args: ["mobile: selectPickerWheelValue",[{"offset":0.15,"order":"next","element":"1AD01251-AD27-48F7-8F69-F11D77C117F5"}],"61d2e236-ebbc-4f97-942e-069bd307deb9"]
> [debug] [XCUITest] Executing command 'execute'
> [debug] [JSONWP Proxy] Proxying [POST /wda/pickerwheel/1AD01251-AD27-48F7-8F69-F11D77C117F5/select] to [POST http://localhost:8100/session/3F47898B-C6D1-43F2-B88E-BF4CDBAC1012/wda/pickerwheel/1AD01251-AD27-48F7-8F69-F11D77C117F5/select] with body: {"order":"next","offset":0.15}
> [debug] [JSONWP Proxy] Got response with status 200: {"value":"Unhandled endpoint: /session/3F47898B-C6D1-43F2-B88E-BF4CDBAC1012/wda/pickerwheel/1AD01251-AD27-48F7-8F69-F11D77C117F5/select -- http://localhost:8100/ with parameters {\n    wildcards =     (\n        \"session/3F47898B-C6D1-43F2-B88E-BF4CDBAC1012/wda/pickerwheel/1AD01251-AD27-48F7-8F69-F11D77C117F5/select\"\n    );\n}","sessionId":"3F47898B-C6D1-43F2-B88E-BF4CDBAC1012","status":1}

Java code i use

```
List<IOSElement> wheels = driver.findElements(MobileBy.className("XCUIElementTypePickerWheel"));
JavascriptExecutor js = (JavascriptExecutor) driver;
Map<String, Object> params = new HashMap<>();
params.put("order", "next");
params.put("offset", 0.15);
params.put("element", ((RemoteWebElement) wheels.get(0)).getId());
```

**Comment by suganeby** [comment]
@Siddh010
Have you tried appium 1.6.5? Is SelectPickerWheelValue method working?

**Comment by Siddh010** [comment]
Hi 

I tried with with SelectPickerWheelValue   method  using appium 1.6.5.    To change value in data picker it is taking around 4 min still.

Please see the log 

[debug] [MJSONWP] Calling AppiumDriver.execute() with args: ["mobile: selectPickerWheelValue",[{"offset":0.15,"order":"next","element":"793ABFDE-B678-4269-8546-BA7528DE2EED"}],"4d2d2623-21c6-4d04-b38d-66f3b7d69e0e"]
[debug] [XCUITest] Executing command 'execute'
[debug] [JSONWP Proxy] Proxying [POST /wda/pickerwheel/793ABFDE-B678-4269-8546-BA7528DE2EED/select] to [POST http://localhost:8100/session/9EAD10BD-131A-4AA9-843C-2FDE5A0D700B/wda/pickerwheel/793ABFDE-B678-4269-8546-BA7528DE2EED/select] with body: {"order":"next","offset":0.15}

[debug] [JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"9EAD10BD-131A-4AA9-843C-2FDE5A0D700B","status":0}
[debug] [MJSONWP] Responding to client with driver.execute() result: {}
[HTTP] <-- POST /wd/hub/session/4d2d2623-21c6-4d04-b38d-66f3b7d69e0e/execute 200 **362561 ms - 74**

**Comment by suganeby** [comment]
@Siddh010
So SelectPickerWheelValue method doesn't set value directly? It goes step by step right?
