### ISSUE TITLE
Appium 1.6.3 for iOS automation: Exception: "Command 'bootstrap.sh' exited with code 1"

### ISSUE THREAD

**Issue by Siko91** [appium/appium#8477]
## The problem

When starting an appium server & session on a new mac mini, an error get's thrown:
It looks like that:

InvalidOperationException : 
An unknown server-side error occurred while processing the command. Original error: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1 

Command : newSession 

## Environment

* Appium version : **1.6.3 (installed with NPM)**
* Last Appium : **same 1.6.3 (but on a different mac)**
* Desktop OS/version used to run Appium: **OS X 10.12.4** 
* Node.js version: **v6.10.2**
* Mobile platform/version under test: **failed both with iOS 10.3 and iOS 10.1**
* Real device or emulator/simulator: **Simulator**
* Appium CLI or Appium.app|exe: **CLI**

## Details
.

## Link to Appium logs
[click here for logs...](https://pastebin.com/85yabpXA)

## Code To Reproduce Issue [ Good To Have ]
.

**Comment by imurchie** [comment]
Unfortunately, one of the upstream dependencies that older versions of Appium relied upon has been removed by its owner @marekcirkos. There is not much that can be done. Please upgrade to the latest version of Appium, which does not have that dependency.
