### ISSUE TITLE
[MJSONWP] Encountered internal error running command: Error: Error: not opened

### ISSUE THREAD

**Issue by kkuehl** [appium/appium#8480]
## The problem

XCode 8.0 and a real ios 9.3.5. When the webdriver is instructed to get a page, I get the crash in the linked gist.
The Webdriver gets properly pushed to the phone and the URL even correctly opens on the device. Followed by an immediate and reproducible crash.

## Environment

* Appium version (or git revision) that exhibits the issue:
appium 1.6.4
* Last Appium version that did not exhibit the issue (if applicable):
N/A
* Desktop OS/version used to run Appium:
10.12.3
* Node.js version (unless using Appium.app|exe):
v7.7.2
* Mobile platform/version under test:
ios 9.3.5
* Real device or emulator/simulator:
Real Device
* Appium CLI or Appium.app|exe:
cli

## Details
This only happens on ios 9.3.5, 10.0.2 and 8.4.1 work correctly
If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
https://gist.github.com/kkuehl/3d35d96236b7aeaa8ce4137790ba76c2
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by dpgraham** [comment]
Can you provide the full logs so that we can see what happened before the error occurred?

**Comment by kkuehl** [comment]
https://gist.github.com/kkuehl/3dd014f200ca1a3cc237d0f429b018fa

**Comment by mykola-mokhnach** [comment]
Try to set **startIWDP** capability to _true_

**Comment by kkuehl** [comment]
Upgraded to 1.6.5 beta to use startIWDP.
Normally I need to specify -f and specify /usr/local/lib/node_modules/chrome-devtools-frontend/front_end/inspector.html 

New log:
https://gist.github.com/kkuehl/950c7bd0652ebffc9b71466d96553195

stderr reported
2017-05-18 11:05:49,115 - ERROR - The proxy service is unavailable

lsof shows it running
lsof -i ":27753"
COMMAND     PID USER   FD   TYPE            DEVICE SIZE/OFF NODE NAME
ios_webki 31356 asdf    4u  IPv4 0x99899cc3c49bdfb      0t0  TCP *:27753 (LISTEN)

**Comment by kkuehl** [comment]
New debug logs.
https://gist.github.com/kkuehl/18f56a047fee23c5b0a0cf06e69094c0

**Comment by mykola-mokhnach** [comment]
Closed as obsolete
