### ISSUE TITLE
Encountered internal error running command: Error: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1

### ISSUE THREAD

**Issue by Sabya73** [appium/appium#8483]
[Appium] Welcome to Appium v1.6.1
[Appium] Non-default server args:
[Appium] udid: 'cf7821d2c86a9906d18e0cc5f1037801c4f37c56'
[Appium] Deprecated server args:
[Appium] -U,--udid => --default-capabilities '{"udid":"cf7821d2c86a9906d18e0cc5f1037801c4f37c56"}'
[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
[Appium] udid: 'cf7821d2c86a9906d18e0cc5f1037801c4f37c56'
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> GET /wd/hub/status {}
[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.1","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 17 ms - 83
[HTTP] --> GET /wd/hub/sessions {}
[debug] [MJSONWP] Calling AppiumDriver.getSessions() with args: []
[debug] [MJSONWP] Responding to client with driver.getSessions() result: []
[HTTP] <-- GET /wd/hub/sessions 200 2 ms - 40
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"iOS","newCommandTimeout":"7200","app":"/Users/administrator/Downloads/RingGo.ipa","platformVersion":"10.3.1 ","udid":"cf7821d2c86a9906d18e0cc5f1037801c4f37c56","deviceName":"iPhone 7 ","automationName":"Appium"}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformName":"iOS","newCommandTimeout":"7200","app":"/Users/administrator/Downloads/RingGo.ipa","platformVersion":"10.3.1 ","udid":"cf7821d2c86a9906d18e0cc5f1037801c4f37c56","deviceName":"iPhone 7 ","automationName":"Appium"},null,null,null,null]
[Appium] Requested iOS support with version >= 10, using XCUITest driver instead of UIAutomation-based driver, since the latter is unsupported on iOS 10 and up.
[Appium] Creating new XCUITestDriver session
[Appium] Capabilities:
[Appium] platformName: 'iOS'
[Appium] newCommandTimeout: '7200'
[Appium] app: '/Users/administrator/Downloads/RingGo.ipa'
[Appium] platformVersion: '10.3.1 '
[Appium] udid: 'cf7821d2c86a9906d18e0cc5f1037801c4f37c56'
[Appium] deviceName: 'iPhone 7 '
[Appium] automationName: 'Appium'
[debug] [XCUITest] XCUITestDriver version: 2.2.0
[BaseDriver] Capability 'newCommandTimeout' changed from string ('7200') to integer (7200). This may cause unexpected behavior
[BaseDriver] Session created with session id: 09592a2b-c46a-4a9b-876f-3a51ba1488b3
[debug] [XCUITest] Xcode version set to '8.3.2'
[debug] [XCUITest] iOS SDK Version set to '10.3'
[debug] [XCUITest] Available devices: cf7821d2c86a9906d18e0cc5f1037801c4f37c56
[debug] [XCUITest] Creating iDevice object with udid cf7821d2c86a9906d18e0cc5f1037801c4f37c56
[XCUITest] Determining device to run tests on: udid: 'cf7821d2c86a9906d18e0cc5f1037801c4f37c56', real device: true
[BaseDriver] Using local app '/Users/administrator/Downloads/RingGo.ipa'
[debug] [BaseDriver] Copying local zip to tmp dir
[debug] [BaseDriver] Unzipping /var/folders/jj/4c15b0w52cd3qqf9y_r7llzr0000gn/T/2017417-4827-1d9r48s.91away8pvi/appium-app.zip
[debug] [BaseDriver] Testing zip archive: /var/folders/jj/4c15b0w52cd3qqf9y_r7llzr0000gn/T/2017417-4827-1d9r48s.91away8pvi/appium-app.zip
[BaseDriver] Unzipped local app to '/var/folders/jj/4c15b0w52cd3qqf9y_r7llzr0000gn/T/2017417-4827-1d9r48s.91away8pvi/Payload/RingGo.app'
[debug] [XCUITest] Checking whether app '/var/folders/jj/4c15b0w52cd3qqf9y_r7llzr0000gn/T/2017417-4827-1d9r48s.91away8pvi/Payload/RingGo.app' is actually present
[debug] [XCUITest] App is present
[debug] [ios-app-utils] Getting bundle ID from app '/var/folders/jj/4c15b0w52cd3qqf9y_r7llzr0000gn/T/2017417-4827-1d9r48s.91away8pvi/Payload/RingGo.app': 'com.ctt.co.uk.ringgo'
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[XCUITest] Setting up real device
[debug] [XCUITest] App is already installed.
[debug] [XCUITest] Full reset not requested. No need to install.
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: /usr/local/bin/carthage
[debug] [XCUITest] Running WebDriverAgent bootstrap script to install dependencies
[XCUITest] Error: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1
at ChildProcess. (../../lib/teen_process.js:66:19)
at emitTwo (events.js:106:13)
at ChildProcess.emit (events.js:194:7)
at maybeClose (internal/child_process.js:899:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
{ Error: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1
at ChildProcess. (../../lib/teen_process.js:66:19)
at emitTwo (events.js:106:13)
at ChildProcess.emit (events.js:194:7)
at maybeClose (internal/child_process.js:899:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
stdout: '\u001b[1mFetching dependencies\n*** Cloning KissXML\n*** Cloning peertalk\n*** Checking out KissXML at "5.0.5"\n*** Cloning KissXML\n',
stderr: 'A shell task (/usr/bin/env git clone --bare --quiet https://github.com/marekcirkos/KissXML.git /Users/administrator/Library/Caches/org.carthage.CarthageKit/dependencies/KissXML) failed with exit code 128:\nfatal: could not read Username for 'https://github.com': terminal prompts disabled\n\n',
code: 1 }
[XCUITest] Shutting down sub-processes
[debug] [XCUITest] Running ios real device reset flow
[debug] [XCUITest] Resetting simulator
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1
at ChildProcess. (../../lib/teen_process.js:66:19)
at emitTwo (events.js:106:13)
at ChildProcess.emit (events.js:194:7)
at maybeClose (internal/child_process.js:899:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
[HTTP] <-- POST /wd/hub/session 500 4446 ms - 199

**Comment by Sabya73** [comment]
@imurchie Could you able to help out with this.

**Comment by mykola-mokhnach** [comment]
You must update to Appium 1.6.4 to make it working
