### ISSUE TITLE
Appium 1.0.1 : No certificate matching ‘xxxxxxx’ for team 'xxxxxxx': Select a different signing certificate for CODE_SIGN_IDENTITY

### ISSUE THREAD

**Issue by SantoshVenkataswamy** [appium/appium#8484]
## The problem

Getting 
Message “No certificate matching ‘xxxxxxx’ for team 'xxxxxxx': Select a different signing certificate for CODE_SIGN_IDENTITY, a team that matches your selected certificate, or switch to automatic provisioning”  
When I try to launch UIKitCatalog.app from Appium Desktop 1.0.1 on actual iPhone 7 device.

## Environment

* Appium version (or git revision) that exhibits the issue: Desktop 10.1
* Desktop OS/version used to run Appium: Mac Mini 10.12.4
* Mobile platform/version under test: 10.3
* Real device or emulator/simulator: Real Device iPhone 7
* Appium CLI or Appium.app|exe: Appium Desktop UI

## Details

I am trying to run UIKitCatalog on actual iPhone 7 device.
 
I am able to deploy UIKitCatalog on actual iPhone 7 device and generate UIKitCatalog.app using XCode with Apple Developer id (team id and iPhone developer id) provided by my company. 

However, when I try to launch UIKitCatalog from Appium Desktop 1.0.1 on actual iPhone 7 device, I am getting 
Message “No certificate matching ‘xxxxxxx’ for team 'xxxxxxx': Select a different signing certificate for CODE_SIGN_IDENTITY, a team that matches your selected certificate, or switch to automatic provisioning”. 
Error: 
Error writing xctestrun file: Error Domain=NSCocoaErrorDomain Code=4 "The folder “WebDriverAgentRunner_iphoneos10.3-arm64.xctestrun” doesn’t exist." UserInfo={NSFilePath=/Users/sim2isc/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products/WebDriverAgentRunner_iphoneos10.3-arm64.xctestrun, NSUserStringVariant=Folder, NSUnderlyingError=0x7f8631f59000 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}

## Link to Appium logs

https://gist.github.com/SantoshVenkataswamy/5182cb15f072ee4b8ee113e557894014

**Comment by mykola-mokhnach** [comment]
This is code signature error. Do you follow https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md while setting up the device?

**Comment by SantoshVenkataswamy** [comment]
@mykola-mokhnach Thank you for sending the link. I did followed it for device configuration. Company provided Certificate associated developer id has expired. This might be the reason. I will get it done and try again.
