### ISSUE TITLE
iOS -Exception when using set_network_connection

### ISSUE THREAD

**Issue by andreiaionitoaiesv** [appium/appium#8486]
## The problem

When I try to change to airplane mode, I receive a WebDriver exception and the server stops. I use set_network_connection in a Python client.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS Sierra 10.12.4
* Node.js version (unless using Appium.app|exe): 7.5.0
* Mobile platform/version under test: iOS 9.3.5
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Exception:
https://gist.github.com/andreiaionitoaiesv/9836166b6c4dbfa1c03a3e7aaf3c8f23

**Comment by mykola-mokhnach** [comment]
Unfortunately there is no way to change network state for iOS in Appium. The API you used is only supported in Android
