### ISSUE TITLE
Android O support

### ISSUE THREAD

**Issue by vrunoa** [appium/appium#8487]
## The problem

Failing to start tests using Android O

## Environment

* Appium version (or git revision) that exhibits the issue: *1.6.4*
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: *OSX 10.12.4*
* Node.js version (unless using Appium.app|exe): *v6.4.0*
* Mobile platform/version under test: *Android O*
* Real device or emulator/simulator: *Emulator*
* Appium CLI or Appium.app|exe: 

## Details

Seems to be failing try to set up mock locations.
```Encountered internal error running command: Error: Error executing adbExec. Original error: 'Command '/Users/vruno/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell appops set io.appium.settings android\:mock_location allow' exited with code 255'; Stderr: 'Error: No UID for io.appium.settings in user 0'; Code: '255'```. 
I dont think we need to run this for emulators. 

## Link to Appium logs
https://gist.github.com/vrunoa/3e8fde6e76bf5529a1535641ee5c0601

## Code To Reproduce Issue [ Good To Have ]

Run a simple test on the new Android O release.

**Comment by imurchie** [comment]
Strange. I just ran a preliminary set of tests and all was well.

**Comment by vrunoa** [comment]
Im using the latest adb
```
adb version
Android Debug Bridge version 1.0.39
Revision 3db08f2c6889-android
```
and the latest revision of the emulator

**Comment by imurchie** [comment]
```
$ adb version
Android Debug Bridge version 1.0.39
Revision 3db08f2c6889-android
Installed as /Users/isaac/Library/Android/sdk/platform-tools/adb
```

**Comment by imurchie** [comment]
I successfully ran the whole `appium-android-driver` suite against an O emulator. So I guess there is something that needs to be added to the tests, to cover this situation.

**Comment by mykola-mokhnach** [comment]
Pushed a fix https://github.com/appium/appium-android-driver/pull/239

**Comment by mykola-mokhnach** [comment]
There is anyway no need to execute this command since appium settings helper is not installed if avd capability is set

**Comment by dpgraham** [comment]
Are there still any Android O issues or can I close this?

**Comment by vrunoa** [comment]
@dpgraham i'm still getting this issue, I just try it again with appium@1.6.6-beta

**Comment by l0gg3r** [comment]
Having the same issue

Using 
- Appium 1.6.6-beta2
- OSX 10.12.5
- Node v8.1.0
- Java 1.8.0_121

`[MJSONWP] Encountered internal error running command: Error: Error executing adbExec. Original error: 'Command '/Users/davidsahakyan/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell appops set io.appium.settings android\:mock_location allow' exited with code 255'; Stderr: 'Error: No UID for io.appium.settings in user 0'; Code: '255'
    at ADB.execFunc$ (../../../lib/tools/system-calls.js:228:13)
    at tryCatch (/Users/davidsahakyan/Downloads/appium-1.6.6-beta.2/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/davidsahakyan/Downloads/appium-1.6.6-beta.2/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Users/davidsahakyan/Downloads/appium-1.6.6-beta.2/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/davidsahakyan/Downloads/appium-1.6.6-beta.2/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
[HTTP] <-- POST /wd/hub/session 500 19889 ms - 432 `

**Comment by dpgraham** [comment]
@l0gg3r Can you provide the line prior to `at ADB.execFunc$ (../../../lib/tools/system-calls.js:228:13)`

**Comment by amedvedjev** [comment]
Device: Emulator with Android O
OSX: 10.12.4
Appium v1.6.6-beta.2 (updated 3 days ago)
Node v7.1.0
Capabilities: ANDROID_UIAUTOMATOR2

no problem :-)

**Comment by vrunoa** [comment]
I confirm tests are working on Android O with `appium@v1.6.6-beta.2`, both uiautomator2 and appium automations.

**Comment by jlipps** [comment]
no new reports of failures here, going to consider this one done.

**Comment by jbruckne** [comment]
Are you guys testing switching to a WebView context? Our team is still having an issue, specifically on Android O, not being able to switch to a WebView context. I've already filed an issue for it but shouldn't that be included in Android O support?

**Comment by vrunoa** [comment]
@jbruckne I just ran a quick tests and i'm also seeing issues to change contexts. Can you link the issue you created ?

**Comment by jbruckne** [comment]
https://github.com/appium/appium/issues/8958
