### ISSUE TITLE
Xcodebuild exited code 65 and signal null

### ISSUE THREAD

**Issue by harmaro** [appium/appium#8488]
## The problem

Need to automate mobile app for iOS devices.
Using Appium Desktop, which installs the mobileapp on simulator. Tries to launch WDA agent twice and is unable to do so. Error thrown : Xcodebuild exited code 65 and signal null

## Environment

Appium version : v1.6.4
Node.js version : v6.10.3
Mobile platform/version under test: iOS10.12
Simulator: iPhone 6

## Details
Steps tried/ re-tried (everything in this forum ) for this issue:
installed brew 
installed node
npm install -g Appium 
npm install wd
install Appium desktop from latest releases (http://github.com/appium...) and placed it under applications folder
Appium doctor used to verify the environment , everything looked ok
brew install Carthage ( placed at : location /usr/local/bin/carthage)
brew install ideviceinstaller 
npm install -g iso-deploy
npm install -g authorize-ios
sudo authorize-ios
npm uninstall appium-xcuitest-driver
npm install appium-xcuitest-driver

Steps:
Goto Applications > launch Appium server > create new session > set capabilities > start session> simulator launches > app installed >WDA tries to launch twice > error in logs "Xcodebuild exited code 65 and signal null"

## Link to Appium logs
https://gist.github.com/harmaro/168ffcd4f5ccac4684ccb980d5c538e5

**Comment by imurchie** [comment]
Without the logs it is not possible to make any suggestions.

**Comment by harmaro** [comment]
Attached Appium server log. Kindly review my query. 
WDA logs already attached with original ticket.
[AppServer.txt](https://github.com/appium/appium/files/1017813/AppServer.txt)

Addition to  "The Problem" statement:
Need to automate mobile app for iOS devices. Using "Appium Desktop" to identify UI elements on simulator. When new session is started with "Appium Desktop" it fails to launch the app with UI inspector. Note: app gets installed though.

**Comment by harmaro** [comment]
Any resolution for this thread?

**Comment by imurchie** [comment]
The original logs are empty.

Can you either run the xcodebuild command manually
```
cd /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent

xcodebuild build-for-testing test-without-building -project /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=DBFFE154-AE8B-4460-BB8D-78B181A42341 -configuration Debug IPHONEOS_DEPLOYMENT_TARGET=10.3
```
Or turn on xcode logging (using the` showXcodeLog` capability, set to `true`). And either determine the problem from the additional logging, or post the results as a link to a [gist](https://gist.github.com).

**Comment by lohitsb** [comment]
I am also facing **"xcodebuild exited with code '65' and signal 'null'**

One more thing, when i build and run the "WebDriverAgentRunner" app, it is installed as "IntegrationApp", is the core or something went wrong?


I have attached the logs for your reference. Please help on the same.
[iOS_Failed.docx](https://github.com/appium/appium/files/1105300/iOS_Failed.docx)
[with_xcodeLog.docx](https://github.com/appium/appium/files/1105329/with_xcodeLog.docx)

**Comment by imurchie** [comment]
Closing as duplicate. See https://github.com/appium/appium/blob/master/docs/en/appium-setup/real-devices-ios.md
