### ISSUE TITLE
Error while executing atom: operation timed out, while testing Safari on iOS 10

### ISSUE THREAD

**Issue by mare1012** [appium/appium#8489]
## The problem

Hi,

I'm running a test (login) for iOS. sometimes my script is working but sometimes it doesn't. the error says that operation time out. I already tried like the comment from this issue https://github.com/appium/appium/issues/7977 to add the new capability webkitResponseTimeout, but it doesn't work.

## Environment

* Appium: v1.6.5-beta
* Desktop OS: macOS Sierra Version 10.12.4
* Node.js version: v7.10.0
* Real device: iPhone 6s 10.3.1

## Link to Appium logs
here is my log-file
https://gist.github.com/mare1012/12e0579adf08dd1a9d19b0c78e9240bb

## My desired capabilities
```
> desired_caps = {
>      'platformName': 'ios',
>      'platformVersion':'10.3',
>      'deviceName':'iPhone 6s',
>      'automationName':'XCUITest',
>      'browserName': 'Safari',
>      'startIWDP':True,
>      'webkitResponseTimeout': 50000,
>      'safariInitialUrl':'https://web.de',
>      'xcodeOrgId':'XXXXXXXXXX',
>      'xcodeSigningId':'iPhone Developer',
>      'udid': 'a974f15a5f89f6a6b6a8338ae086e7aa9a380699',
>      'autoWebView': True,
>      'newCommandTimeout': 3000,
>      'clearSystemFiles': True
> }
```

**Comment by imurchie** [comment]
Unfortunately this is Appium sending the command to the ios webkit debug proxy, and it not returning in a timely manner. There is not a lot that can be done. 

Is there something going on on the page that might make JavaScript execution flakey?

**Comment by mare1012** [comment]
Hallo @imurchie , thanks for your answer.

i don't know exactly, if there is something going on on that page that make JavaScript execution flakey or not. Because it works fine,  if i test the script on Android devices

on that page i want to test the following steps:
1. click the login-symbol
2. type username and password
3. click login button
4. click the logout button

i'm using python to write the steps. i put the script on this link:
https://gist.github.com/mare1012/2495d23da32972aeb9e315745a0790d2

is it something wrong with my script?

**Comment by imurchie** [comment]
I was meaning if things are still loading, etc. iOS Safari automation is done largely by injecting JS into the page. So if things are not loaded there can be problems.

**Comment by mare1012** [comment]
if i see what's going on the iPhone, it will only open the url (https://web.de) and nothing happens. And i think this url is opening because "safariInitialUrl" not driver.get("url"). Because if this script works, after launching the url for the first time (safariInitialUrl), mobile safari will be refreshing (driver.get("url")). But in this case the mobile safari isn't refreshing.

If this is a not loading problem, is there something i can do to fix this?

**Comment by mare1012** [comment]
Hallo @imurchie,

can you tell me more about something that might make JavaScript execution flakey using appium?
because if i test another website (less contents than the previous website has more contents, ads etc), it works fine.

**Comment by faran** [comment]
@imurchie @mare1012 
Ok i found something it might be related.
Webview can find elements with iPhone 6 iOS 6 +
but it cant find elements with iPhone 7 iOS 7

**Comment by mare1012** [comment]
@faran i haven't tried with iPhone 7 because i don't have the device

**Comment by faran** [comment]
@mare1012
Sorry i mean to say iPhone 7 ios 10.3 simulator.

**Comment by mare1012** [comment]
@imurchie 
I'm just testing again and got a different log-file. the issue is still the same that operation timeout, but in the log-file I see these lines:

[IWDP] [ 'Page 27753/0 not found' ]
[IWDP] [ 'Already sent close_frame' ]

**Comment by OmarOrtega** [comment]
Is there any update?

**Comment by mare1012** [comment]
Hallo @imurchie  i was updating appium to version 1.6.5 (not beta) and IWDP to version 1.7.1. But the problem still appears. Do you have any Info about it?

**Comment by mare1012** [comment]
@imurchie i'm trying now to test https://google.de , but i still get the same error.  Is this error has to do with my script?or my appium configuration?

this is how i start the test
1. run appium in the first terminal : 
appium -p 4491 -bp 2271 -U a974f15a5f89f6a6b6a8338ae086e7aa9a380699
2. run the script in the second terminal:
python name_of_the_script.py


here is my python code:
https://gist.github.com/mare1012/cbb66ac36e840f93a64ace3487b3f922
here is the log file:
https://gist.github.com/mare1012/14395f42689d002ecd595a550d648470

**Comment by mare1012** [comment]
Hallo @imurchie ,

is the any update on this?

**Comment by mare1012** [comment]
@imurchie do you have any update on this issue?

**Comment by mayureshshirodkar** [comment]
@mare1012  even i have been having the same issue, where in the IWDP gets disconnected.
After a testcases are executed.
Probably reconnecting the IWDP manually again could be a solution. I haven't tried it though.

Error:
<script src="https://gist.github.com/mayureshshirodkar/62bbdec0f186afd5bf0eaa8f960359f3.js"></script>

**Comment by imurchie** [comment]
In the most recent versions of Appium you can set the `webkitResponseTimeout` to change how long it waits.
