### ISSUE TITLE
Error while executing atom: operation timed out

### ISSUE THREAD

**Issue by abhilashcae** [appium/appium#8490]
## The problem

I'm automating a hybrid app which is built using WK Webview on iOS. I switch to webview, perform some actions on the elements (find_element, click) and while closing the webview content I get an error saying `Error while executing atom: operation timed out`. I see that the webview content being closed and then Appium erroring out.

[debug] [MJSONWP] Calling AppiumDriver.click() with args: ["5000","892cdcae-fb2e-41dc-b6ee-7144a0f847b7"]
[debug] [XCUITest] Executing command 'click'
[debug] [RemoteDebugger] Executing 'click' atom in default context
[debug] [RemoteDebugger] Sending javascript command (function(){return function(){var k,aa="functio...
[debug] [RemoteDebugger] Sending WebKit data: {"method":"Runtime.evaluate","params":{"objectGroup":"console","includeCommandLineAPI":true,"doNotPauseOnExceptionsAndMuteConsole":true,"expression":"(function(){return function(){var k,aa=\"functi...
[debug] [RemoteDebugger] Webkit response timeout: 5000
[MJSONWP] Encountered internal error running command: Error: Error while executing atom: operation timed out
    at XCUITestDriver.callee$0$0$ (../../../lib/commands/web.js:79:11)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session/892cdcae-fb2e-41dc-b6ee-7144a0f847b7/element/5000/click 500 5024 ms - 218 
[HTTP] --> DELETE /wd/hub/session/892cdcae-fb2e-41dc-b6ee-7144a0f847b7 {}

This occurs only during the closure of a webview and not in the mid of it. I feel that Appium is trying to access webview even after the webview is closed and getting timed out.

## Environment

* Appium version : 1.6.4. I tried with the latest beta available as well.
* Desktop OS/version used to run Appium: Mac OS X El Capitan 10.11.6
* Node.js version (unless using Appium.app|exe): 6.10.0
* Mobile platform/version under test: iOS 10.0.2
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: CLI
* Scripting Language used: Python

## Link to Appium logs
Without showXcodeLog:
https://gist.github.com/abhilashcae/0a3a38cae6eef5c1a19d1e47ca0ed15b
With showXcodeLog set to True:
https://gist.github.com/abhilashcae/bad67be446f467306047ba30edee21ab

**Comment by imurchie** [comment]
Please use the `webkitResponseTimeout` capability to adjust the timeout.

**Comment by abhilashcae** [comment]
@imurchie - I tried using that, changing the timeout still fails the case.

**Comment by qatesting30** [comment]
I am also facing the same issue. Any update on this?

**Comment by imurchie** [comment]
Can you provide more information? Logs? This issue is a year old, so things have changed.

**Comment by aramana1** [comment]
@abhilashcae @qatesting30 - any work arounds or fix for this issue?
