### ISSUE TITLE
Unable to run App with Appium on real device Error Domain=NSCocoaErrorDomain Code=260 "The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/igoremelyanov/Library/Developer/Xcode/DerivedData/WebDriverAgent

### ISSUE THREAD

**Issue by igoremelyanov** [appium/appium#8491]
## The problem

Be able to build and deploy my App - WebDriverAgentRunner.app on iPhone5C
But when I am trying to run it Appium getting Errors:

Error Domain=NSCocoaErrorDomain Code=260 "The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/igoremelyanov/Library/Developer/Xcode/DerivedData/WebDriverAgent

Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}

** TEST EXECUTE FAILED *

xcodebuild exited with code '65' and signal 'null'

## Environment

* Appium version (or git revision) that exhibits the issue:   Appium v1.6.4
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:   Appium 1.0.2-betta
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:  10.3.1
* Real device or emulator/simulator: iPhone5C device
* Appium CLI or Appium.app|exe:  Appium.app  on Mac

## Link to Appium logs

The server is running
Start New SessionStop Server
[Appium] Welcome to Appium v1.6.4
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"automationName":"XCUITest","bundleId":"jostle.WebDriverAgentRunner","clearSystemFiles":false,"deviceName":"Igor's iPhone5C","fullReset":false,"platformName":"iOS","platformVersion":"10.3","showXcodeLog":false,"udid":"866ab408080b93c891c8b038755096207b44a2fc","xcodeConfigFile":"/Users/igoremelyanov/Downloads/XCodeConfig.xcconfig","xcodeOrgId":"66M3R2Z98Z","xcodeSigningId":"iphone Developer","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"automationName":"XCUITest","bundleId":"jostle.WebDriverAgentRunner","clearSystemFiles":false,"deviceName":"Igor's iPhone5C","fullReset":false,"platformName":"iOS","platformVersion":"10.3","showXcodeLog":false,"udid":"866ab408080b93c891c8b038755096207b44a2fc","xcodeConfigFile":"/Users/igoremelyanov/Downloads/XCodeConfig.xcconfig","xcodeOrgId":"66M3R2Z98Z","xcodeSigningId":"iphone Developer","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null,null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1495221923710 (12:25:23 GMT-0700 (PDT))
[Appium] Creating new XCUITestDriver (v2.27.2) session
[Appium] Capabilities:
[Appium]   automationName: 'XCUITest'
[Appium]   bundleId: 'jostle.WebDriverAgentRunner'
[Appium]   clearSystemFiles: false
[Appium]   deviceName: 'Igor\'s iPhone5C'
[Appium]   fullReset: false
[Appium]   platformName: 'iOS'
[Appium]   platformVersion: '10.3'
[Appium]   showXcodeLog: false
[Appium]   udid: '866ab408080b93c891c8b038755096207b44a2fc'
[Appium]   xcodeConfigFile: '/Users/igoremelyanov/Downloads/XCodeConfig.xcconfig'
[Appium]   xcodeOrgId: '66M3R2Z98Z'
[Appium]   xcodeSigningId: 'iphone Developer'
[Appium]   newCommandTimeout: 0
[Appium]   connectHardwareKeyboard: true
[XCUITest] XCUITestDriver version: 2.27.2
[BaseDriver] Session created with session id: 6a339211-6eee-47ff-84ba-65e043ff7395
[XCUITest] Xcode version set to '8.3.2' 
[XCUITest] iOS SDK Version set to '10.3'
[BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1495221924027 (12:25:24 GMT-0700 (PDT))
[XCUITest] Available devices: 866ab408080b93c891c8b038755096207b44a2fc
[XCUITest] Creating iDevice object with udid '866ab408080b93c891c8b038755096207b44a2fc'
[XCUITest] Determining device to run tests on: udid: '866ab408080b93c891c8b038755096207b44a2fc', real device: true
[BaseDriver] Event 'appConfigured' logged at 1495221924451 (12:25:24 GMT-0700 (PDT))
[BaseDriver] Event 'resetStarted' logged at 1495221924451 (12:25:24 GMT-0700 (PDT))
[XCUITest] Reset: running ios real device reset flow
[BaseDriver] Event 'resetComplete' logged at 1495221924452 (12:25:24 GMT-0700 (PDT))
[iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[BaseDriver] Event 'logCaptureStarted' logged at 1495221924670 (12:25:24 GMT-0700 (PDT))
[XCUITest] Setting up real device
[BaseDriver] Event 'wdaStartAttempted' logged at 1495221924672 (12:25:24 GMT-0700 (PDT))
[XCUITest] Using WDA path: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[XCUITest] Carthage found: '/usr/local/bin/carthage'
[XCUITest] Killing hanging processes
[XCUITest] Using Xcode configuration file: '/Users/igoremelyanov/Downloads/XCodeConfig.xcconfig'
[XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=866ab408080b93c891c8b038755096207b44a2fc -configuration Debug IPHONEOS_DEPLOYMENT_TARGET=10.3 -xcconfig /Users/igoremelyanov/Downloads/XCodeConfig.xcconfig' in directory '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Output from xcodebuild will not be logged
[XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[XCUITest] Log file for xcodebuild test: /Users/igoremelyanov/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/E14C69B0-1013-4831-813E-B357F88CA5F0/Session-WebDriverAgentRunner-2017-05-19_122534-4oFIUM.log
[Xcode] 2017-05-19 12:25:34.386 xcodebuild[4393:215090] Error Domain=NSCocoaErrorDomain Code=260 "The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/igoremelyanov/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7fb2b0995100 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
[Xcode] 2017-05-19 12:25:34.386 xcodebuild[4393:215090] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
[Xcode] 
[Xcode] ** TEST EXECUTE FAILED **
[Xcode] 
[Xcode] 
[XCUITest] xcodebuild exited with code '65' and signal 'null'
[BaseDriver] Event 'wdaStartFailed' logged at 1495221934423 (12:25:34 GMT-0700 (PDT))
[XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
[XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down iproxy process (pid 4392)
[XCUITest] iproxy exited with code 'null'
[XCUITest] Removing WDA application from device
[BaseDriver] Event 'wdaStartAttempted' logged at 1495221944920 (12:25:44 GMT-0700 (PDT))
[XCUITest] Using WDA path: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[XCUITest] Carthage found: '/usr/local/bin/carthage'
[XCUITest] Killing hanging processes
[XCUITest] Using Xcode configuration file: '/Users/igoremelyanov/Downloads/XCodeConfig.xcconfig'
[XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=866ab408080b93c891c8b038755096207b44a2fc -configuration Debug IPHONEOS_DEPLOYMENT_TARGET=10.3 -xcconfig /Users/igoremelyanov/Downloads/XCodeConfig.xcconfig' in directory '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Output from xcodebuild will not be logged
[XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[XCUITest] Log file for xcodebuild test: /Users/igoremelyanov/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/E5F5E95B-968A-4D09-94EB-ED59D82F7B27/Session-WebDriverAgentRunner-2017-05-19_122552-KCOEUu.log
[Xcode] 2017-05-19 12:25:52.187 xcodebuild[4421:215313] Error Domain=NSCocoaErrorDomain Code=260 "The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/igoremelyanov/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7f8f7ad8c470 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
[Xcode] 2017-05-19 12:25:52.187 xcodebuild[4421:215313] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
[Xcode] 
[Xcode] ** TEST EXECUTE FAILED **
[Xcode] 
[Xcode] 
[XCUITest] xcodebuild exited with code '65' and signal 'null'
[BaseDriver] Event 'wdaStartFailed' logged at 1495221952209 (12:25:52 GMT-0700 (PDT))
[XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
[XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down iproxy process (pid 4420)
[XCUITest] iproxy exited with code 'null'
[XCUITest] Removing WDA application from device

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by igoremelyanov** [comment]
that is what in my XCodeConfig.xcconfig
DEVELOPMENT_TEAM = 66M3R2Z98Z
CODE_SIGN_IDENTITY = iPhone Developer

**Comment by imurchie** [comment]
Can you try the following?
```
cd /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent

xcodebuild build-for-testing test-without-building -project /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=866ab408080b93c891c8b038755096207b44a2fc -configuration Debug IPHONEOS_DEPLOYMENT_TARGET=10.3 -xcconfig /Users/igoremelyanov/Downloads/XCodeConfig.xcconfig
```

**Comment by igoremelyanov** [comment]
Last login: Thu May 18 15:56:07 on ttys001
Igors-MacBook-Air:~ igoremelyanov$ xcodebuild build-for-testing test-without-building -project /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=866ab408080b93c891c8b038755096207b44a2fc -configuration Debug IPHONEOS_DEPLOYMENT_TARGET=10.3 -xcconfig /Users/igoremelyanov/Downloads/XCodeConfig.xcconfig
Build settings from command line:
    IPHONEOS_DEPLOYMENT_TARGET = 10.3

Build settings from configuration file '/Users/igoremelyanov/Downloads/XCodeConfig.xcconfig':
    CODE_SIGN_IDENTITY = iPhone Developer
    DEVELOPMENT_TEAM = 66M3R2Z98Z

=== BUILD TARGET WebDriverAgentLib OF PROJECT WebDriverAgent WITH CONFIGURATION Debug ===

Check dependencies
No signing certificate "iOS Development" found:  No "iOS Development" signing certificate matching team ID "66M3R2Z98Z" with a private key was found.

** TEST BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
2017-05-19 12:34:14.310 xcodebuild[4461:223091] [MT] IDETestOperationsObserverDebug: (9686C160-DD65-4E7B-97FE-0CCA96E752D0) Beginning test session WebDriverAgentRunner-9686C160-DD65-4E7B-97FE-0CCA96E752D0 at 2017-05-19 12:34:14.309 with Xcode 8E2002 on target <DVTiOSDevice: 0x7ffc74d94860> {
		deviceSerialNumber:         FFMNGBMDG2D8
		identifier:                 866ab408080b93c891c8b038755096207b44a2fc
		deviceClass:                iPhone
		deviceName:                 Igor's iPhone5C
		deviceIdentifier:           866ab408080b93c891c8b038755096207b44a2fc
		productVersion:             10.3.2
		buildVersion:               14F89
		deviceSoftwareVersion:      10.3.2 (14F89)
		deviceArchitecture:         armv7s
		deviceTotalCapacity:        5099380736
		deviceAvailableCapacity:    815792128
		deviceIsTransient:          NO
		ignored:                    NO
		deviceIsBusy:               NO
		deviceIsActivated:          YES
		deviceActivationState:      Activated
		isPasscodeLocked:           YES
		deviceType:                 <DVTDeviceType:0x7ffc74f76c50 Xcode.DeviceType.iPhone>
		supportedDeviceFamilies:    (
    1
)
		applications:              (null)
		provisioningProfiles:      (null)
		activityProgress:          -2
		activityTitle:             
		hasInternalSupport:        NO
		isSupportedOS:             YES
		developerDiskMountError:   (null)
(null)
	bootArgs:                  <unavailable>
		} (10.3.2 (14F89))
2017-05-19 12:34:14.311 xcodebuild[4461:223111]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/igoremelyanov/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/7F41F805-74CF-4659-A0FA-AFE31781C10A/Session-WebDriverAgentRunner-2017-05-19_123414-4E29Rc.log
2017-05-19 12:34:14.337 xcodebuild[4461:223091] Error Domain=NSCocoaErrorDomain Code=260 "The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/igoremelyanov/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7ffc759217c0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
2017-05-19 12:34:14.337 xcodebuild[4461:223091] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
** TEST EXECUTE FAILED **

Igors-MacBook-Air:~ igoremelyanov$

**Comment by imurchie** [comment]
You need to make sure you have a signing certificate/provisioning profile for `com.facebook.WebDriverAgentRunner`.

Please see the documentation for real devices: https://github.com/appium/appium/blob/master/docs/en/appium-setup/real-devices-ios.md

**Comment by igoremelyanov** [comment]
1. WebDriverAgentRunner.app from gitgub
http://prntscr.com/f9t9ah  my Provisioning screen shoot
and
http://prntscr.com/f9t9y9 - build Failed for WebDriverAgent

Not sure what exact should I change for Provisioning Profile. 
it says: None Required

2. I ve created my own WebDriverAgentRunner project in XCode.
Be able to build and Deploy on my iPhone
http://prntscr.com/f9tbxf
but can not run in Appium also.

**Comment by imurchie** [comment]
The first part: that is the lib target, not the runner. It does not need to be signed. The error is normal. That dependency will be downloaded by Appium. Or you can run `./Scripts/bootstrap.sh -d` from the `WebDriverAgent` directory.

The second part: you need to take that bundle identifier and send it to the session in the `updatedWDABundleId` desired capability.

**Comment by igoremelyanov** [comment]
I've added  "updatedWDABundleId"  to my Capabilities:  jostle.WebDriverAgentRunner
My Appium with Desired Capabilities -  http://prntscr.com/f9tjfm

should I add it to CCodeConfig.xcconfig  - http://prntscr.com/f9tlff

This is my Devises with my apps -  http://prntscr.com/f9tkc2
