### ISSUE TITLE
appium will be stuck at "getting process name for webview" or "geting device API level " or "starting logcat  capture"

### ISSUE THREAD

**Issue by lgw8186** [appium/appium#8495]
## The problem

 appium -a 127.0.0.1 -p 5743 -bp 5745 --session-override --chromedriver-port 10535 -U ca3c3f51

chromedriver:2.23.409699

## Environment

* Appium 1.46
* window7 used to run Appium:
* node -v : v6.10.1
* android 6.0.1  API level:23
* Real device 

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

![image](https://cloud.githubusercontent.com/assets/14970166/26276881/abb2b1d4-3db3-11e7-9566-30e84f010938.png)

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Appium 1.4 is old and not supported. Use 1.6.4

**Comment by mykola-mokhnach** [comment]
Log screenshots are not very useful for problem analysis. GIST is much more preferable.
