### ISSUE TITLE
I can't start the WDA session with iPhone 5, iOS 9.3

### ISSUE THREAD

**Issue by Akapylechka** [appium/appium#8497]
## The problem
I can not start the WDA session with iPhone 5, iOS 9.3, and app does not open.
(With iPhone 6 iOS 10.3 all was ok)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Last Appium version that did not exhibit the issue (if applicable): -
* Desktop OS/version used to run Appium: 10.12.4
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS 9.3
* Real device or emulator/simulator: sim iPhone 5
* Appium CLI or Appium.app|exe: app

## Link to Appium logs

https://gist.github.com/Akapylechka/8350f2cbec87c186b619b02e44ce4903

**Comment by mykola-mokhnach** [comment]
It is not recommended to use iPhone5 with XCTest at all. See https://github.com/appium/appium/issues/7441 for the reference.

Rebooting the device helps, but only for a short time.
