### ISSUE TITLE
Could Not Launch Appium Inspector using Appium 1.5.3 and simulator 9.3 version

### ISSUE THREAD

**Issue by Harish8260** [appium/appium#8500]
![screen shot 2017-05-22 at 11 54 00 am](https://cloud.githubusercontent.com/assets/28856178/26295190/570c6376-3ee6-11e7-9098-6a9beb5216b3.png)
## The problem
I am using appium 1.5.3 version and ios 9.3 simulator and MacOS Sierra 10.12.3 and xcode version is 8.3.1. when i tried to click inspector getting error "Could not Launch Appium Inspector".Please help me how to solve it.

## Environment

* Appium version 1.5.3
* Desktop OS/version used to run Appium: MacOS Sierra 10.12.3
* Node.js version (unless using Appium.app|exe):v7.8.0
* Mobile platform/version under test: 9.3
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: Appium.app

**Comment by mykola-mokhnach** [comment]
This inspector is not supported anymore. Please use https://github.com/appium/appium-desktop/releases

**Comment by Harish8260** [comment]
Thanks.Will try with appium-desktop-1.0.2-beta.2-mac.zip .Do i need to uninstall the appium 1.5.3?

**Comment by Harish8260** [comment]
Installed appium-desktop-1.0.2 and started server.desired capabilities is as follows:
{
  "platformName": "iOS",
  "platformVersion": "10.3",
  "deviceName": "iPhone 6",
  "app": "/Users/dharmendra/Library/Developer/Xcode/DerivedData/viola-evdbfjepthqalafheboztlcoesny/Build/Products/Debug-iphonesimulator/viola.app",
  "noReset": true
}
and start the session.Error occurred as shown in the screenshot.
![screen shot 2017-05-22 at 12 52 20 pm](https://cloud.githubusercontent.com/assets/28856178/26296805/f5ddcfe2-3eed-11e7-9248-884c7f21b9fc.png)

**Comment by mykola-mokhnach** [comment]
Do not hesitate to use search feature - there were several users who already experienced exactly the same problem
