### ISSUE TITLE
Unable to enter text using send_keys in Android 7, UI automator2

### ISSUE THREAD

**Issue by saikirankv** [appium/appium#8501]
## The problem

In Andriod-7 with uiautomator2 I'm unable to enter data into textboxes. It's reproducible using Appium desktop app and Appium-**python**. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OSX 10.11.6
* Node.js version (unless using Appium.app|exe): 6.2.1
* Mobile platform/version under test:
* Real device or emulator/simulator: Nexus 6, Android Version- 7.0
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/saikirankv/d7a0a1d5fad87fbb1dea97c30d53f745

## Code To Reproduce Issue [ Good To Have ]

driver.find_element_by_accessibility_id("Username").send_keys("testing")
or
try to enter text using sendKeys option in appium desktop with android7 and ui-automator2

**Comment by mykola-mokhnach** [comment]
is it some special text field or a regular one? Does the method work for other text fields?

**Comment by saikirankv** [comment]
it's a regular text field, I'm able to enter text with the same command in Android 6.

**Comment by mykola-mokhnach** [comment]
how about other text fields? is this particular field somehow different from them?

**Comment by saikirankv** [comment]
Sorry, I debugged the issue I'm trying to enter the text into AndroidView element, Now I try to enter the text using EditText tag it's working fine now.
