### ISSUE TITLE
Error occurred when started the session using Appium 1.0.2-beta.2.

### ISSUE THREAD

**Issue by Harish8260** [appium/appium#8502]
## The problem

Error occured while running when started the session using Appium 1.0.2-beta.2.

## Environment

* Appium version : Appium 1.0.2-beta.2
* Desktop OS/version used to run Appium: MacOS Sierra 10.12.3
* Node.js version (unless using Appium.app|exe):v7.8.0
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: simulator 10.3
* Appium CLI or Appium.app|exe: Appium.app

#Details

My desired capabalities is as follows:
{
  "platformName": "iOS",
  "platformVersion": "10.3",
  "deviceName": "iPhone 6",
  "app": "/Users/dharmendra/Library/Developer/Xcode/DerivedData/viola-evdbfjepthqalafheboztlcoesny/Build/Products/Debug-iphonesimulator/viola.app",
  "noReset": true
}
After starting the session Error occurred as shown in screenshot
![screen shot 2017-05-22 at 12 52 20 pm](https://cloud.githubusercontent.com/assets/28856178/26297158/581a73bc-3eef-11e7-9167-13211a097e30.png)

**Comment by mykola-mokhnach** [comment]
Closed as duplicate
