### ISSUE TITLE
Appium hangs in between for android 7.0

### ISSUE THREAD

**Issue by lohitsb** [appium/appium#8503]
I am also facing Same issue, i.e. after starting the script it runs for some time and then it will stop on particular step i.e while finding element "MobileElement helloText = (MobileElement) androidDriver.findElementByXPath("//*[@index='1'][@text='BILLING'][@resource-id='com.mytwc.common.resource:id/title_text']");" . I am using appium 1.6.4 beta 2 and Nexus 6 with 7.0.

If we minimize and maximize then it runs i.e it continues.

Same code works fine for 6.0 devices, but when try to runon Nexus 6 with 7.0, it hangs in this particular step.

I have tried by  setting "capabilities.setCapability("automationName", "uiautomator2");"  also but no chance.

Can some one help on the same?

## Environment

* Appium version 1.6.4

**Comment by mykola-mokhnach** [comment]
It's impossible to say anything without logs
Also, it would be useful to see adb logcat output

**Comment by lohitsb** [comment]
Attached logs
[test.txt](https://github.com/appium/appium/files/1019430/test.txt)
[new 16.txt](https://github.com/appium/appium/files/1019434/new.16.txt)

**Comment by mykola-mokhnach** [comment]
the xpath expression you use looks quite suspicious. Can you also attach the output of getPageSource?

**Comment by lohitsb** [comment]
sorry....i didn't get...what exactly you need?....do you want me to add element details using uiautomatorviewer? or some thing else?........Same works fine for the devices less then android7
![dump_3339694339885269482](https://cloud.githubusercontent.com/assets/26922867/26321082/0db79ad0-3f43-11e7-9563-d351c2ded50f.png)
[home.zip](https://github.com/appium/appium/files/1019683/home.zip)

**Comment by mykola-mokhnach** [comment]
There is a method to show page source as xml. I don't know exactly which client you use, but in java the corresponding method is called driver.getPageSource

**Comment by lohitsb** [comment]
i am using android device,  how can i get that xml? .....i have attached the uiautoamtor dump home.zip in my prrvious comment.....hope it is same

**Comment by mykola-mokhnach** [comment]
Can you show the part of client code then where you try to find the element?

Also, you may try to simplify your location strategy. For example, you might try to find element by id **title_text** and then filter found elements by their actual attributes.

**Comment by lohitsb** [comment]
Now it is displaying some other error:

Once it ran successfully all the test cases, but 2nd time when run the cases, it is giving below error. Can you please help on the same.






[HTTP] --> GET /wd/hub/session/35bf7ddf-4c57-4dbe-9c26-c599df95609a/element/e4fddaf4-47c9-4ad1-b726-7c381a3e0215/displayed {}
[debug] [MJSONWP] Calling AppiumDriver.elementDisplayed() with args: ["e4fddaf4-47c9-4ad1-b726-7c381a3e0215","35bf7ddf-4c57-4dbe-9c26-c599df95609a"]
[debug] [JSONWP Proxy] Proxying [GET /element/e4fddaf4-47c9-4ad1-b726-7c381a3e0215/attribute/displayed] to [GET http://localhost:8201/wd/hub/session/674ed111-b210-48b0-91c0-798ae8661b7e/element/e4fddaf4-47c9-4ad1-b726-7c381a3e0215/attribute/displayed] with body: {}
[MJSONWP] Encountered internal error running command:  {"jsonwp":{"sessionId":"674ed111-b210-48b0-91c0-798ae8661b7e","status":10,"value":"android.support.test.uiautomator.StaleObjectException\n\tat android.support.test.uiautomator.UiObject2.getAccessibilityNodeInfo(UiObject2.java:629)\n\tat android.support.test.uiautomator.UiObject2.hashCode(UiObject2.java:105)\n\tat java.lang.Object.toString(Object.java:260)\n\tat java.util.Formatter$FormatSpecifier.printString(Formatter.java:2922)\n\tat java.util.Formatter$FormatSpecifier.print(Formatter.java:2802)\n\tat java.util.Formatter.format(Formatter.java:2491)\n\tat java.util.Formatter.format(Formatter.java:2426)\n\tat java.lang.String.format(String.java:2626)\n\tat io.appium.uiautomator2.utils.ReflectionUtils.invoke(ReflectionUtils.java:91)\n\tat io.appium.uiautomator2.model.UiObject2Element.getBoolAttribute(UiObject2Element.java:114)\n\tat io.appium.uiautomator2.handler.GetElementAttribute.safeHandle(GetElementAttribute.java:40)\n\tat io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:56)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:202)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:193)\n\tat io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:44)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)\n\tat io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)\n\tat io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)\n\tat io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)\n\tat io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)\n\tat io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)\n\tat io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)\n\tat io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:611)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:552)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:466)\n\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)\n\tat io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)\n\tat java.lang.Thread.run(Thread.java:762)\n"}} ProxyRequestError: Could not proxy command to remote server. Original error: 500 - "{\"sessionId\":\"674ed111-b210-48b0-91c0-798ae8661b7e\",\"status\":10,\"value\":\"android.support.test.uiautomator.StaleObjectException\\n\\tat android.support.test.uiautomator.UiObject2.getAccessibilityNodeInfo(UiObject2.java:629)\\n\\tat android.support.test.uiautomator.UiObject2.hashCode(UiObject2.java:105)\\n\\tat java.lang.Object.toString(Object.java:260)\\n\\tat java.util.Formatter$FormatSpecifier.printString(Formatter.java:2922)\\n\\tat java.util.Formatter$FormatSpecifier.print(Formatter.java:2802)\\n\\tat java.util.Formatter.format(Formatter.java:2491)\\n\\tat java.util.Formatter.format(Formatter.java:2426)\\n\\tat java.lang.String.format(String.java:2626)\\n\\tat io.appium.uiautomator2.utils.ReflectionUtils.invoke(ReflectionUtils.java:91)\\n\\tat io.appium.uiautomator2.model.UiObject2Element.getBoolAttribute(UiObject2Element.java:114)\\n\\tat io.appium.uiautomator2.handler.GetElementAttribute.safeHandle(GetElementAttribute.java:40)\\n\\tat io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:56)\\n\\tat io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:202)\\n\\tat io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:193)\\n\\tat io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:44)\\n\\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\\n\\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\\n\\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)\\n\\tat io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)\\n\\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\\n\\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\\n\\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)\\n\\tat io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)\\n\\tat io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)\\n\\tat io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)\\n\\tat io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)\\n\\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\\n\\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\\n\\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)\\n\\tat io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)\\n\\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\\n\\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\\n\\tat io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)\\n\\tat io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)\\n\\tat io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:611)\\n\\tat io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:552)\\n\\tat io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:466)\\n\\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)\\n\\tat io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)\\n\\tat io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)\\n\\tat java.lang.Thread.run(Thread.java:762)\\n\"}"
    at JWProxy.proxy$ (../../../lib/jsonwp-proxy/proxy.js:144:13)
    at tryCatch (C:\Users\lbelaladavar\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\lbelaladavar\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\lbelaladavar\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\lbelaladavar\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[HTTP] <-- GET /wd/hub/session/35bf7ddf-4c57-4dbe-9c26-c599df95609a/element/e4fddaf4-47c9-4ad1-b726-7c381a3e0215/displayed 500 82 ms - 3927 
FAILED CONFIGURATION: @BeforeTest beforeMethod
org.openqa.selenium.StaleElementReferenceException: android.support.test.uiautomator.StaleObjectException
	at android.support.test.uiautomator.UiObject2.getAccessibilityNodeInfo(UiObject2.java:629)
	at android.support.test.uiautomator.UiObject2.hashCode(UiObject2.java:105)
	at java.lang.Object.toString(Object.java:260)
	at java.util.Formatter$FormatSpecifier.printString(Formatter.java:2922)
	at java.util.Formatter$FormatSpecifier.print(Formatter.java:2802)
	at java.util.Formatter.format(Formatter.java:2491)
	at java.util.Formatter.format(Formatter.java:2426)
	at java.lang.String.format(String.java:2626)
	at io.appium.uiautomator2.utils.ReflectionUtils.invoke(ReflectionUtils.java:91)
	at io.appium.uiautomator2.model.UiObject2Element.getBoolAttribute(UiObject2E

**Comment by mykola-mokhnach** [comment]
Check https://github.com/appium/appium/issues/7876

**Comment by imurchie** [comment]
Android 7 support is now available.
