### ISSUE TITLE
Proposal for @mykola-mokhnach to join Appium TC

### ISSUE THREAD

**Issue by jlipps** [appium/appium#8505]
Given @mykola-mokhnach's significant and frequent contributions across a range of Appium projects, I propose that they be added to Appium's Technical Committee (as outlined in our [governance doc](https://github.com/appium/appium/blob/master/GOVERNANCE.md)).

For this to move forward, I'd love to get a +1 from the current TC: @bootstraponline, @dandoveralba, and @penguinho. This proposal counts as my own +1 :-)

And of course we'd need a +1 from @mykola-mokhnach as well!

Anyone is free to make comments until the matter is decided.

**Comment by bootstraponline** [comment]
+1

**Comment by dandoveralba** [comment]
+1

**Comment by imurchie** [comment]
+1 for someone not on the TC.

**Comment by SrinivasanTarget** [comment]
+1

**Comment by pavanbachu0604** [comment]
+1

**Comment by saikrishna321** [comment]
+1

**Comment by penguinho** [comment]
+1

**Comment by KazuCocoa** [comment]
+1

**Comment by rkavalap** [comment]
+1

**Comment by lehungcuong** [comment]
+1

**Comment by dpgraham** [comment]
Added him to the Doc. @jlipps is there anything else that needs to be done or can we close this issue?
