### ISSUE TITLE
Feature: Android: ResetApp: Add flag to add permissions

### ISSUE THREAD

**Issue by amedvedjev** [appium/appium#8506]
## The problem

sometimes when we do resetApp() call with android app it will be useful to grant all permissions to avoid later dialogs (when no needed).

Now when app starting after reset it might ask for permission and Appium fails even to detect that app started (cause it trying to find declared activity)

Example of error in logs:
```
2017-05-22 16:36:22:810 - [ADB] Error: ee.xxx.* or ee.xxxx.xxxx.ee.xxxx.* never started
```

Best way: flag that control grant permission or not during reset.

**Comment by dpgraham** [comment]
Closing as duplicate: https://github.com/appium/appium/issues/5561
