### ISSUE TITLE
iOS 10 - Appium1.6.1-Beta - Real device - 'Connection to WDA timed out' after WDA and app are launched successfully

### ISSUE THREAD

**Issue by rajeshwaran88** [appium/appium#8507]
## The problem

I have configured Appium 1.6.1 Beta, WebDriverAgent, XCode 8.2.1 for automation testing. When I start the script the WDA and App launches successfully. But when the first line of the script which is find_element is executed, the script stops running with the error connection to WDA timed out. The exact same setup works in one of the Mac and fails in another Mac. I have admin access in the Mac where the script works fine. But in the Mac were it fails, limited admin access. Also when checked the WDA logs, saw there were some access denied errors while executing.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.1 Beta
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: OS X El Capitain
* Node.js version (unless using Appium.app|exe): 7.10.0
* Mobile platform/version under test: ios 10.1
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

In the log I can also see that the desired capabilities - realDeviceLogger is not recognised. But the same path works in the other Mac.

## Link to Appium logs

Appium : https://gist.github.com/rajeshwaran88/1ec6c134f622eb21cea82989b1c0726a
WDA : https://gist.github.com/rajeshwaran88/8734b0d0bb8e7b0ef141b96068582069

## Code To Reproduce Issue [ Good To Have ]

if self.driver.wait_for_element_exist(*HomePageLocators.FLIP_TO_HONEYCOMB):
                    self.driver.find_element(*HomePageLocators.FLIP_TO_HONEYCOMB).click()

The wait_for_element_exist fails as there is no element found. 

Exception thrown while execution when WDA connections times out.
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/selenium/webdriver/support/expected_conditions.py", line 328, in _find_element return driver.find_element(*by) AttributeError: 'NoneType' object has no attribute 'find_element'
Thanks in Advance!!!

**Comment by mykola-mokhnach** [comment]
Update Appium to version 1.6.4-stable or 1.6.5-beta and try again

**Comment by rajeshwaran88** [comment]
@mykola-mokhnach - Thanks for the suggestion!!!
Tried with 1.6.5-beta and got the below error:
Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65

I cleared and redid the entire steps for configuring WDA and got the same error again. Please find log below:
https://gist.github.com/rajeshwaran88/35e2277ec716e22f32318ee96559333d

**Comment by mykola-mokhnach** [comment]
Error 65 usually happens if WDA sources are not signed. Do you follow https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md ?

**Comment by mykola-mokhnach** [comment]
Also make sure you have no leftovers after the previous installation: delete WDA app from the device and clear Xcode cache

**Comment by mykola-mokhnach** [comment]
Closed as non Appium-related issue

**Comment by rajeshwaran88** [comment]
@mykola-mokhnach Thanks for the help!!!
