### ISSUE TITLE
Getting error: [REMOTE] Could not connect to WebKitRemoteDebugger server

### ISSUE THREAD

**Issue by vinothpandian18** [appium/appium#8510]
## The problem

Not able to tap Date of birth field through 'find element by id' in Appium-ruby(Native iOS App) for automation.

## Environment

* Appium version (or git revision) that exhibits the issue: Appium 1.4.13 Draco
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac os Sierra 10.12
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS 9.3.2
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium.app

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Appium logs
Getting below error in appium if i am trying to inspect the element:
error: [REMOTE] Could not connect to WebKitRemoteDebugger server

info: <-- GET /wd/hub/session/d2914a27-21eb-441c-9e1f-e389b79e5d62/screenshot 200 2367.571 ms - 106114 {"status":0,"value":"iVBORw0KGgoAAAANSUhEUgAAAu4AAAU2CAYAAADK1zMGAAAAAXNSR0IArs4c6QAAQABJREFUeAHsnQW8VEX7xx9ADEBEQAUkpUVFBTuwEbsARVEUG33F7r/Yvtjd3b52FzYmFqKINNIYiIIoCP/5zWXWs3t3b53d5e693+fz2d1TU985e84zM888U6PzlvstNQQCEIAABCAAAQhAAAIQqNQEalbq3JE5CEAAAhCAAAQgAAEIQMATQHHnRoAABCAAAQhAAAIQgEABEEBxL4BKIosQgAAEIAABCEAAAhBAcecegAAEIAABCEAAAhCAQAEQQHEvgEoiixCAAAQgAAEIQAACEEBx5x6AAAQgAAEIQAACEIBAARBAcS+ASiKLEIAABCAAAQhAAAIQQHHnHoAABCAAAQhAAAIQgEABEEBxL4BKIosQgAAEIAABCEAAAhBAcecegAAEIAABCEAAAhCAQAEQQHEvgEoiixCAAAQgAAEIQAACEEBx5x6AAAQgAAEIQAACEIBAARBAcS+ASiKLEIAABCAAAQhAAAIQQHHnHoAABCAAAQhAAAIQgEABEEBxL4BKIosQgAAEIAABCEAAAhBAcecegAAEIAABCEAAAhCAQAEQQHEvgEoiixCAAAQgAAEIQAACEEBx5x6AAAQgAAEIQAACEIBAARBAcS+ASiKLEIAABCAAAQhAAAIQQHHnHoAABCAAAQhAAAIQgEABEEBxL4BKIosQgAAEIAABCEAAAhBAcecegAAEIAABCEAAAhCAQAEQQHEvgEoiixCAAAQgAAEIQAACEEBx5x6AAAQgAAEIQAACEIBAARBAcS+ASiKLEIAABCAAAQhAAAIQQHHnHoAABCAAAQhAAAIQgEABEEBxL4BKIosQgAAEIAABCEAAAhBAcecegAAEIAABCEAAAhCAQAEQQHEvgEoiixCAAAQgAAEIQAACEEBx5x6AAAQgAAEIQAACEIBAARBAcS+ASiKLEIAABCAAAQhA...","sessionId":"d2914a27-21eb-441c-9e1f-e389b79e5d62"}
info: --> GET /wd/hub/session/d2914a27-21eb-441c-9e1f-e389b79e5d62/contexts {}
info: [debug] [REMOTE] Getting WebKitRemoteDebugger pageArray
info: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command. (Original error: connect ECONNREFUSED)","code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","origValue":"connect ECONNREFUSED"},"sessionId":"d2914a27-21eb-441c-9e1f-e389b79e5d62"}
info: <-- GET /wd/hub/session/d2914a27-21eb-441c-9e1f-e389b79e5d62/contexts 500 4.361 ms - 293 

## Code To Reproduce Issue

I am starting with $driver.start_driver #Starts appium driver before the tests begin

 Element label :
 label: Security_DOBTextFieldId 

Ruby Code : 
Then(/^I tap on identifier "([^"]*)"$/) do |arg| wait_true { exists { find_element(id: arg).click }} end

Please someone help me out how to handle this issue?

**Comment by mykola-mokhnach** [comment]
Appium 1.4 is not supported anymore. Please update to 1.6.4
