### ISSUE TITLE
How to convert from UIAutomation to XCUITest

### ISSUE THREAD

**Issue by leanhdung3491** [appium/appium#8511]
## The problem

When I run the automation test on iOS 9.3 with Xcode 7, it works but it doesn't work after I upgraded to Xcode 8.

## Environment

Appium version 1.6.4
iOS 10.3
Xcode 8

## Details
My question is how to transfer this "UIATarget.localTarget().frontMostApp().mainWindow().sliders()[0].value()" to similar script on XCUITest.

## My log file is 

org.openqa.selenium.WebDriverException: Method is not implemented (WARNING: The server did not provide any stacktrace information)

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/migrating-to-xcuitest.md

Regarding how to transfer:

```
driver.findElement(By.className("XCUIElementTypeSlider")).getAttribute("value")
```

Please use Appium forum to ask questions

**Comment by leanhdung3491** [comment]
Hi mykola-mokhnach. Thank you so much for your helping, it works well.
I have another issue, can you transfer this one for me:
`UIATarget.localTarget().frontMostApp().mainWindow().sliders()[0].dragInsideWithOptions({startOffset:{x:0.5,` y:0.936559}, endOffset:{x:0.5, y:0.1507527999999999}, duration:2.0})`
Thank you so much !
