### ISSUE TITLE
Not working Appium fullReset capability on iOS Device 

### ISSUE THREAD

**Issue by Elangopalakrishnan** [appium/appium#8514]
**Appium fullReset capability Not working on iOS Device** 

I need to Launch the Existing app in iOS device.

I'm automating the iOS app by using appium 1.6.4 with c# script.
For that i have installed my ios app at first time in ios device.
After that every test run it is uninstalling and installing the app in my ios device. so my app cache is deleted automatically.
It is not preferred, I need to install once and need to launch the app if that app already exists in my ios deivce.

## Environment
* Appium version (or git revision) that exhibits the issue: 1.6.4
* Desktop OS/version used to run Appium: OS X EI Capitan version 10.11.6
* Mobile platform/version under test: iPhone 6s plus version 10.2.1
* Real device or emulator/simulator:Real Device

## Details
I'm automating the iOS app by using appium 1.6.4 with c# script.
For that i have installed my ios app at first time in ios device.
After that every test run it is uninstalling and installing the app in my ios device.so my app cache is deleted automatically.

It is not preferred, I need to install once and need to launch the app if that app already exists in my ios deivce.

**Code used:**
public static void launchDeviceApp()
{
DesiredCapabilities capabilities = new DesiredCapabilities();
                    capabilities.SetCapability("platformName", "iOS");
                    capabilities.SetCapability("deviceName", "iPhone");
                    capabilities.SetCapability("platformVersion", "10.2.1");
                    capabilities.SetCapability("udid", "<deivce UDID>");

capabilities.SetCapability("newCommandTimeout", 120000);
capabilities.SetCapability("app", "/Users/user/Desktop/******/++++/myiosdevice.ipa"); 
capabilities.SetCapability("bundleId", "com.myiosappbundleid");
**capabilities.SetCapability("fullReset", "false");**  //I tried this but not working.

AppDriver = new IOSDriver<AppiumWebElement>(new Uri("http://**ipaddress**.*.*:4723/wd/hub"), capabilities, TimeSpan.FromSeconds(360));
ResultLogger.logMessage("App launched");
}
whenever i execute the "launchDeviceApp" function, it is checking whether the App is available or not in device, Even if it is available it will uninstall and install again,. But my requirement is, it should install if the app is not already installed in my device.

I have tried the fullReset capability but it is not working, Is there any other capability to check the app present or not and launch the existing app in ios device.

Appium Logs:
Users-Mac-mini:~ user$ appium -U 2293f9b820d3d9e3f6652929fbc9adf78324
[Appium] Welcome to Appium v1.6.4
[Appium] Non-default server args:
[Appium]   udid: 2293f9b820d3d9e3f6652929fbc9af78324
[Appium] Deprecated server args:
[Appium]   -U,--udid => --default-capabilities '{"udid":"2293f9b820d3d9e3f6652929fbc9af78324"}'
[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
[Appium]   udid: '2293f9b820d3d9e3f6652929fbc9af78324'
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"iOS","deviceName":"iPhone","platformVersion":"10.1","udid":"2293f9b820d3d9e3f6652929fbc9af78324","newCommandTimeout":120000,"app":"/Users/user/Desktop/MobileAutomation/myiosApp/myios.ipa","bundleId":"com.enterprise","fullReset":"false"}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformName":"iOS","deviceName":"iPhone","platformVersion":"10.1","udid":"2293f9b820d3d9e3f6652929fbc9af78324","newCommandTimeout":120000,"app":"/Users/user/Desktop/MobileAutomation/myiosApp/myios.ipa","bundleId":"com.enterprise","fullReset":"false"},null,null,null,null]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1495547775658 (19:26:15 GMT+0530 (IST))
[Appium] Requested iOS support with version >= 10, using XCUITest driver instead of UIAutomation-based driver, since the latter is unsupported on iOS 10 and up.
[Appium] Creating new XCUITestDriver (v2.27.2) session
[Appium] Capabilities:
[Appium]   platformName: 'iOS'
[Appium]   deviceName: 'iPhone'
[Appium]   platformVersion: '10.1'
[Appium]   udid: '2293f9b820d3d9e3f6652929fbc9adf78324'
[Appium]   newCommandTimeout: 120000
[Appium]   app: '/Users/user/Desktop/MobileAutomation/myiosApp/myios.ipa'
[Appium]   bundleId: 'com.enterprise'
[Appium]   fullReset: 'false'
[debug] [XCUITest] XCUITestDriver version: 2.27.2
[BaseDriver] Capability 'fullReset' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] Session created with session id: 85ecaa1f-1187-4f66-8971-1fbf281ffc66
[debug] [XCUITest] Xcode version set to '8.2.1' (tools v7.3.1.0.1.1461711523)
[debug] [XCUITest] iOS SDK Version set to '10.2'
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1495547777884 (19:26:17 GMT+0530 (IST))
[debug] [XCUITest] Available devices: 2293f9b820d3d9e3f6652929fbc9af78324
[debug] [XCUITest] Creating iDevice object with udid '2293f9b820c93ad3d9e3f6652929fbc9af78324'
[XCUITest] Determining device to run tests on: udid: '2293f9b820d3d9e3f6652929fbc9af78324', real device: true
[BaseDriver] Using local app '/Users/user/Desktop/MobileAutomation/myiosApp/myios.ipa'
[debug] [BaseDriver] Copying local zip to tmp dir
[debug] [BaseDriver] Unzipping /var/folders/hj/9t36nm690ll30kzfsywfqllw0000gn/T/2017423-27106-5n81n8.jxe8my4x6r/appium-app.zip
[debug] [BaseDriver] Testing zip archive: /var/folders/hj/9t36nm690ll30kzfsywfqllw0000gn/T/2017423-27106-5n81n8.jxe8my4x6r/appium-app.zip
[BaseDriver] Unzipped local app to '/var/folders/hj/9t36nm690ll30kzfsywfqllw0000gn/T/2017423-27106-5n81n8.jxe8my4x6r/Payload/myios.app'
[debug] [BaseDriver] Event 'appConfigured' logged at 1495547782506 (19:26:22 GMT+0530 (IST))
[debug] [XCUITest] Checking whether app '/var/folders/hj/9t36nm690ll30kzfsywfqllw0000gn/T/2017423-27106-5n81n8.jxe8my4x6r/Payload/myios.app' is actually present on file system
[debug] [XCUITest] App is present
[debug] [BaseDriver] Event 'resetStarted' logged at 1495547782507 (19:26:22 GMT+0530 (IST))
[debug] [XCUITest] Reset: running ios real device reset flow
[debug] [BaseDriver] Event 'resetComplete' logged at 1495547782508 (19:26:22 GMT+0530 (IST))
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1495547782749 (19:26:22 GMT+0530 (IST))
[XCUITest] Setting up real device
[debug] [XCUITest] Reset requested. Removing app with id 'com.enterprise' from the device
[debug] [XCUITest] Installing '/var/folders/hj/9t36nm690ll30kzfsywfqllw0000gn/T/2017423-27106-5n81n8.jxe8my4x6r/Payload/myios.app' on device with UUID '2293f9b820d3d9e3f6652929fbc9adf78324'...
[debug] [XCUITest] The app has been installed successfully.

Thanks in Advance!
Elango

**Comment by Brian-Watson** [comment]
Please try the caps together...

capabilities.SetCapability("noReset", true);
capabilities.SetCapability("fullReset", false);

**Comment by Elangopalakrishnan** [comment]
It is working now with 
capabilities.SetCapability("noReset", true);
capabilities.SetCapability("fullReset", false);
Thanks Brian Watson 👍  :)

Regards!
Elango
