### ISSUE TITLE
[debug] [XCUITest] Failed to create WDA session. Retrying, issue on real iOS device.

### ISSUE THREAD

**Issue by WasiqB** [appium/appium#8515]
## The problem

Getting error **[debug] [XCUITest] Failed to create WDA session. Retrying...** 75% of the time when running for iOS iPad Mini device, while sometimes it works.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: Mac OSX 10.12.4
* Node.js version (unless using Appium.app|exe): 6.10.2
* Mobile platform/version under test: 10.3.1
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: 1.6.4

## Details

This is a random behavior where it gives this error most of the times but sometimes it works. I tried everything I can, like from restarting the device to deploying WDA to device manually, but still having issues in running the test on real iPad Mini device. Please provide a fix for this as it is causing a bottleneck in our Mobile Automation implementation.

## Link to Appium logs

Here is the [logs](https://gist.github.com/WasiqB/1fe897d9f35c2703d29c5285cefb2fae) which shows the problem.

## Code To Reproduce Issue [ Good To Have ]

Following capabilities I have used, where it is causing issue:

{
   "app":"/Users/wasiq.bhamla/Documents/git/nelnet-mobile-automation/src/test/resources/app/ipad/NelnetCashierTablet.ipa",
   "noReset":false,
   "clearSystemFiles":true,
   "appName":"Campus Key",
   "xcodeOrgId":"9HZFT948M2",
   "bundleId":"com.talosdigital.NelnetCashierTablet",
   "deviceName":"iPad Mini 4",
   "fullReset":true,
   "xcodeSigningId":"iPhone Developer",
   "usePrebuiltWDA":false,
   "agentPath":"/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj",
   "bootstrapPath":"/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent",
   "newCommandTimeout":6000,
   "platformVersion":"10.3.1",
   "useNewWDA":false,
   "automationName":"XCUITest",
   "platformName":"iOS",
   "udid":"9c776d36f7e4f75d98a50fa11c49f2d59ddfe632",
   "wdaConnectionTimeout":6000
}

**Comment by mykola-mokhnach** [comment]
I don't think one can do much about this problem from Appium side. I would try to play with usePrebuiltWDA/useNewWDA values to avoid WDA reinstall on the device.

**Comment by deepeshpk** [comment]
We have the same issue.
Webdriver Agent/Runner all are building fine.
While launching via Appium Desktop we are facing thissue.

**Comment by mykola-mokhnach** [comment]
Check https://github.com/facebook/WebDriverAgent/issues/507 for the reference
