### ISSUE TITLE
Appium 1.6.4 cannot find webview of hybrid application on real device

### ISSUE THREAD

**Issue by ochubey** [appium/appium#8517]
## The problem

After switching to real device from Simulators code that was working with webviews and html in them stopped working. 
driver.getContextHandles() returns only NATIVE context, although application at that point has webview screen opened.
Tried to run `ios_webkit_debug_proxy -c [phone's udid]:27753` -d in teminal and setting capability startIWDP=true.
With `ios_webkit_debug_proxy -c [phone's udid]:27753` command executed and app with webview I'm getting [] when opening http://127.0.0.1:27753/json and not empty array when Safari with webpage is opened. 
## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Last Appium version that did not exhibit the issue (if applicable): same, but on Simulator
* Desktop OS/version used to run Appium: macOS Sierra, 10.12.4
* Node.js version (unless using Appium.app|exe): v7.2.0
* Mobile platform/version under test: ios/10.3.2
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: tried both Appium CLI and AppiumDesktop as a server

## Link to Appium logs
https://gist.github.com/ochubey/12b630d1e45665aa3cec72fcb9d42b11
`2017-05-23 18:21:28:643 - info: [HTTP] --> GET /wd/hub/session/840d09ab-c698-4443-a8a1-2227d7112234/contexts {}
2017-05-23 18:21:28:644 - info: [debug] [MJSONWP] Calling AppiumDriver.getContexts() with args: ["840d09ab-c698-4443-a8a1-2227d7112234"]
2017-05-23 18:21:28:645 - info: [debug] [XCUITest] Executing command 'getContexts'
2017-05-23 18:21:28:645 - info: [debug] [iOS] Getting list of available contexts
2017-05-23 18:21:28:647 - info: [debug] [iOS] Retrieving contexts and views
2017-05-23 18:21:28:648 - info: [debug] [iOS] Selecting by url: false 
2017-05-23 18:21:28:648 - info: [debug] [RemoteDebugger] Getting WebKitRemoteDebugger pageArray: localhost, 27753
2017-05-23 18:21:28:648 - info: [debug] [RemoteDebugger] Sending request to: http://localhost:27753/json
2017-05-23 18:21:28:672 - info: [debug] [RemoteDebugger] Page element JSON: []
2017-05-23 18:21:28:672 - info: [debug] [iOS] No web frames found.
2017-05-23 18:21:28:674 - info: [debug] [MJSONWP] Responding to client with driver.getContexts() result: ["NATIVE_APP"]
2017-05-23 18:21:28:675 - info: [HTTP] <-- GET /wd/hub/session/840d09ab-c698-4443-a8a1-2227d7112234/contexts 200 32 ms - 86 
`

## Code To Reproduce Issue [ Good To Have ]
`public class SimpleTest {
    private AppiumDriver driver;

    @Before
    public void setUp() throws Exception {

        DesiredCapabilities capabilities = new DesiredCapabilities();
        int SCRIPT_WAIT_DELAY = 5000;
        String iosDeclineScript = "$.delay(" + SCRIPT_WAIT_DELAY + "); XCUIApplication.alert(); $.dismissAlert(); true;";
        capabilities.setCapability(AllCapabilityType.WAIT_FOR_APP_SCRIPT, iosDeclineScript);
        capabilities.setCapability(AllCapabilityType.AUTOMATION_NAME, "XCUITest");
        capabilities.setCapability(AllCapabilityType.FULL_RESET, false);
        capabilities.setCapability(AllCapabilityType.NO_RESET, true);
        capabilities.setCapability(AllCapabilityType.UDID, "udid");
        capabilities.setCapability(AllCapabilityType.NEW_COMMAND_TIMEOUT, 120 + 10);
        capabilities.setCapability(AllCapabilityType.XCODE_ORG_ID, "XCODE_ORG_ID");
        capabilities.setCapability(AllCapabilityType.XCODE_SIGNING_ID, "iPhone Developer");
        capabilities.setCapability(AllCapabilityType.PLATFORM_NAME, "ios");
        capabilities.setCapability(AllCapabilityType.PLATFORM_VERSION, "10.3.2");
        capabilities.setCapability(AllCapabilityType.DEVICE_NAME, "DespoPhone");
        capabilities.setCapability(AllCapabilityType.APPIUM_VERSION, "1.6.4");
        capabilities.setCapability(AllCapabilityType.SHOW_XCODE_LOG, true);
        capabilities.setCapability(AllCapabilityType.APP, "/Users/username/Desktop/WebView2.ipa");
        capabilities.setCapability(AllCapabilityType.START_IWDP, true);
        capabilities.setCapability(AllCapabilityType.AUTO_WEBVIEW, false);

        driver = new IOSDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
    }

    @Test
    public void test() {
        driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
        driver.manage().timeouts().pageLoadTimeout(60, TimeUnit.SECONDS);
        driver.manage().timeouts().setScriptTimeout(30, TimeUnit.SECONDS);
        driver.findElement(By.id("Open UIWebView")).click();

        try {
            Thread.sleep(5000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

        System.out.println(driver.getContextHandles().toString());
    }

    /* We disable the driver after the test has been executed. */
    @After
    public void tearDown() throws Exception {
        driver.quit();
    }
}
`

**Comment by dpgraham** [comment]
Can you try it without running `ios_webkit_debug_proxy -c [phone's udid]:27753`. The `startIWDP` feature makes it unnecessary to run `ios_webkit_debug_proxy` externally.

Let me know if that changes anything.

**Comment by ochubey** [comment]
@dpgraham yes, I was trying them separately and together.
Unfortunately, both solutions return` Page element JSON: []` for hybrid application's webview.

**Comment by ochubey** [comment]
Looks like this issue is not directly related to Appium implementation.
I've opened issue for [ios_webkit_debug_proxy](https://github.com/google/ios-webkit-debug-proxy/issues/207) and closing this one.

**Comment by skansar** [comment]
Hello @masoodmd0786/ @imurchie / @jlipps , I am facing the similar issue with Appium v1.7.2 and Java_client 4.1.2, IOS 10.3(iphone 7s), mac OS Sierra, XCODE 9.2, ios_webkit_debug_proxy 1.8
Built with libimobiledevice v1.2.1, libplist v2.0.0 and safari 11.2.

WebViews are not recognized / shown with appium desktop as well through java client.

appium server
appium --webkit-debug-proxy-port 9222 (tried with OR 27753)
[Appium] Welcome to Appium v1.7.2
[Appium] Non-default server args:
[Appium] webkitDebugProxyPort: 9222 (OR 27753)
[Appium] Appium REST http interface listener started on 0.0.0.0:4723

wda
ios_webkit_debug_proxy
Listing devices on :9221 (OR 27753)
Connected :9222 to iPhone (470ab1f19c630548f76ed0b2f8a4a31614b2c847)

capabilities:
[Appium] Creating new XCUITestDriver (v2.64.0) session
[Appium] Capabilities:
[Appium] app: com.amazon.AmazonUK.Enterprise
[Appium] newCommandTimeout: 380
[Appium] platformVersion: 10.3
[Appium] xcodeOrgId: 94KV3E626L
[Appium] automationName: XCUITest
[Appium] autoWebview: false
[Appium] platformName: iOS
[Appium] udid: 470ab1f19c630548f76ed0b2f8a4a31614b2c847
[Appium] deviceName: IOSDevice
[Appium] xcodeSigningId: iPhone Developer

appium Log:
[debug] [MJSONWP] Calling AppiumDriver.getContexts() with args: ["e5be6ced-f4ac-4e21-8618-d97e1d9991c2"]
[debug] [XCUITest] Executing command 'getContexts'
[debug] [iOS] Getting list of available contexts
[debug] [iOS] Retrieving contexts and views
[debug] [iOS] Selecting by url: false
[debug] [RemoteDebugger] Getting WebKitRemoteDebugger pageArray: localhost, 27753
[debug] [RemoteDebugger] Sending request to: http://localhost:27753/json
[debug] [RemoteDebugger] Page element JSON: []
[debug] [iOS] No web frames found.
[debug] [MJSONWP] Responding to client with driver.getContexts() result: ["NATIVE_APP"]

Any help appreciated. Thank You.
