### ISSUE TITLE
Not able to Launch application: Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65

### ISSUE THREAD

**Issue by Aalmeen** [appium/appium#8519]
## The problem

iPa file getting installed but not able to launch using appium 1.6.4, I have attached logs. Please help as our project getting delayed. 

Note: WebdriverAgent signed/build successfully 

## Environment

* Appium version (or git revision) that exhibits the issue: **Appium 1.6.4 GUI**
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: **Mac OS 10.12.4**
* Node.js version (unless using Appium.app|exe): **Node 4.2.0**
* Mobile platform/version under test: **iPad 10.3.1**
* Real device or emulator/simulator: **Real device**
* **Appium CLI or Appium.app|exe: Tried Both**

## Link to Appium logs

https://gist.github.com/Aalmeen/26f506dcc18d10e1fc7f96ca1057691e/revisions

## Code To Reproduce Issue [ Good To Have ]

We are trying to launch app for now

**Comment by mykola-mokhnach** [comment]
Set the **showXcodeLog** capability to true and attach the collected log. BTW, is the signature you use for WDA developer or enterprise one? It won't work with enterprise.

**Comment by Aalmeen** [comment]
set the showXcodeLog to true and here is log: https://gist.github.com/Aalmeen/1ef9d223e8b75ada1abbf2e848741340

Note: With this signature we were able to launch application on iPad 9.3 using appium 1.5.3 but now requirement is changed to launch same application on iPad 10.3.2 so we switched to appium 1.6.4 (PS : all decencies are installed as per new version of appium)

**Comment by mykola-mokhnach** [comment]
> Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.3'

It does not look like WDA is signed. Try to open the project in Xcode and then deploy WebDriverAgent Runner application into your device manually from Xcode. If you manage to do this then Appium will be able to do it as well.

**Comment by Asimk21** [comment]
@Aalmeen 
Workaround:
1. Open node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj in xcode
2. Provide signing id 
3. Build project 
4. Rerun appium tests again.

Note: Need to run `/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Scripts/bootstrap.sh` from root i.e `/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent`

I think appium should have picked default developer cert on its own.

**Comment by Aalmeen** [comment]
![screen shot 2017-05-24 at 3 37 10 pm](https://cloud.githubusercontent.com/assets/10829287/26398536/68135c3a-4097-11e7-9d2a-e380da9f16f1.png)

WebDriverAgent build successfully, you can refer attached screenshot

**Comment by mykola-mokhnach** [comment]
Run Product > Test to deploy it on the device

**Comment by Aalmeen** [comment]
@mykola-mokhnach Got the below output 

dyld: Library not loaded: @rpath/XCTest.framework/XCTest
  Referenced from: /var/containers/Bundle/Application/035F4377-A7E6-445E-A289-DA6CE27C487F/WebDriverAgentRunner-Runner.app/XCTRunner
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/035F4377-A7E6-445E-A289-DA6CE27C487F/WebDriverAgentRunner-Runner.app/Frameworks/XCTest.framework/XCTest: code signing blocked mmap() of '/private/var/containers/Bundle/Application/035F4377-A7E6-445E-A289-DA6CE27C487F/WebDriverAgentRunner-Runner.app/Frameworks/XCTest.framework/XCTest'
	/private/var/containers/Bundle/Application/035F4377-A7E6-445E-A289-DA6CE27C487F/WebDriverAgentRunner-Runner.app/Frameworks/XCTest.framework/XCTest: code signing blocked mmap() of '/private/var/containers/Bundle/Application/035F4377-A7E6-445E-A289-DA6CE27C487F/WebDriverAgentRunner-Runner.app/Frameworks/XCTest.framework/XCTest'
Message from debugger: Terminated due to signal 6

**Comment by mykola-mokhnach** [comment]
Fix it and you're good to go.
BTW, have you seen the tutorial https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md ?

I'm closing the issue, since it's not related to Appium bugs. Similar questions have already been discussed many times here.

**Comment by Aalmeen** [comment]
Yes we have seen that page and already mentioned DEVELOPMENT_TEAM = <Team ID> and CODE_SIGN_IDENTITY = iPhone Developer but still facing same issues.

Thanks for your help!
