### ISSUE TITLE
Error while installing npm install -g ios-deploy on MAC 

### ISSUE THREAD

**Issue by Elangopalakrishnan** [appium/appium#8521]
## The problem

Installing the Appium 1.6.4 version in Mac Sierra 10.12.4 version. But I'm facing the below issue.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Desktop OS/version used to run Appium: Mac Sierra 10.12.4 version
* Node.js version (unless using Appium.app|exe): 
* Mobile platform/version under test: 10.2.1
* Real device or emulator/simulator: Real Device
* xcode version 8.3.2

## Details

Appium Installation:

I have installed the following s/w without issues, But I'm facing the issue when i install **npm install -g ios-deploy** 

**Install brew** 
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

**Install node for npm**  
	 brew install node

**Install appium**
	npm install -g  appium@1.6.4

**Install ideviceinstaller**
	brew install ideviceinstaller

**Install carthage**
	brew install carthage

**Install deviceconsole**
	npm install -g deviceconsole
Upto this i have installed, But below s/w i cannot install,
**Install ios-deploy**
	npm install -g ios-deploy

** Install xcpretty**
	gem install xcpretty 

**Install libimobiledevice**
	brew install libimobiledevice –HEAD 

When i try to install,

npm install -g ios-deploy 

**Error Logs:**

iMac:~ mkuser$ npm install -g ios-deploy

> ios-deploy@1.9.1 preinstall /usr/local/lib/node_modules/.staging/ios-deploy-298c9491
> ./src/scripts/check_reqs.js && xcodebuild

stderr: xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/Cellar/node/7.10.0/bin/node" "/usr/local/bin/npm" "install" "-g" "ios-deploy"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! ios-deploy@1.9.1 preinstall: `./src/scripts/check_reqs.js && xcodebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ios-deploy@1.9.1 preinstall script './src/scripts/check_reqs.js && xcodebuild'.
**npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ios-deploy package,
npm ERR! not with npm itself.**
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./src/scripts/check_reqs.js && xcodebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ios-deploy
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ios-deploy
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mkuser/.npm/_logs/2017-05-24T12_20_18_364Z-debug.log

And i have verified the node and npm is in latest version.
Please review and help me!

Thanks in advance
Elango

**Comment by mykola-mokhnach** [comment]
> Make sure you have the latest version of node.js and npm installed.
> If you do, this is most likely a problem with the ios-deploy package

Closed as Appium-unrelated issue.

**Comment by pavanbachu0604** [comment]
Do you have Xcode installed and working on your MAC?

On Wed, May 24, 2017 at 9:04 AM, Epk <notifications@github.com> wrote:

> The problem
>
> Installing the Appium 1.6.4 version in Mac Sierra 10.12.4 version. But I'm
> facing the below issue.
> Environment
>
>    - Appium version (or git revision) that exhibits the issue: 1.6.4
>    - Desktop OS/version used to run Appium: Mac Sierra 10.12.4 version
>    - Node.js version (unless using Appium.app|exe):
>    - Mobile platform/version under test: 10.2.1
>    - Real device or emulator/simulator: Real Device
>    - xcode version 8.3.2
>
> Details
>
> Appium Installation:
>
> I have installed the following s/w without issues, But I'm facing the
> issue when i install *npm install -g ios-deploy*
>
> *Install brew*
> /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.
> com/Homebrew/install/master/install
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__raw.githubusercontent.com_Homebrew_install_master_install&d=DwMFaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=GrVyjk9esLjbV-UuEWevVPxUeLcsCbkcwb9nvBHhjgE&m=hSxQQ6IFES5p_bJq55unaqtxt9h8a00ZnXThCZa4kCQ&s=NeXBBfVOVG_xvHRMtJfmY9ouNUCG80UdTNji7JYS1FQ&e=>
> )"
>
> *Install node for npm*
> brew install node
>
> *Install appium*
> npm install -g appium@1.6.4
>
> *Install ideviceinstaller*
> brew install ideviceinstaller
>
> *Install carthage*
> brew install carthage
>
> *Install deviceconsole*
> npm install -g deviceconsole
> Upto this i have installed, But below s/w i cannot install,
> *Install ios-deploy*
> npm install -g ios-deploy
>
> ** Install xcpretty**
> gem install xcpretty
>
> *Install libimobiledevice*
> brew install libimobiledevice –HEAD
>
> When i try to install,
>
> npm install -g ios-deploy
>
> *Error Logs:*
>
> iMac:~ mkuser$ npm install -g ios-deploy
>
> ios-deploy@1.9.1 preinstall /usr/local/lib/node_modules/.
> staging/ios-deploy-298c9491
> ./src/scripts/check_reqs.js && xcodebuild
>
> stderr: xcode-select: error: tool 'xcodebuild' requires Xcode, but active
> developer directory '/Library/Developer/CommandLineTools' is a command
> line tools instance
>
> npm ERR! Darwin 16.5.0
> npm ERR! argv "/usr/local/Cellar/node/7.10.0/bin/node"
> "/usr/local/bin/npm" "install" "-g" "ios-deploy"
> npm ERR! node v7.10.0
> npm ERR! npm v4.2.0
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
>
> npm ERR! ios-deploy@1.9.1 preinstall: ./src/scripts/check_reqs.js &&
> xcodebuild
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the ios-deploy@1.9.1 preinstall script
> './src/scripts/check_reqs.js && xcodebuild'.
>
>
> *npm ERR! Make sure you have the latest version of node.js and npm
> installed. npm ERR! If you do, this is most likely a problem with the
> ios-deploy package, npm ERR! not with npm itself.*
> npm ERR! Tell the author that this fails on your system:
> npm ERR! ./src/scripts/check_reqs.js && xcodebuild
> npm ERR! You can get information on how to open an issue for this project
> with:
> npm ERR! npm bugs ios-deploy
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR! npm owner ls ios-deploy
> npm ERR! There is likely additional logging output above.
>
> npm ERR! Please include the following file with any support request:
> npm ERR! /Users/mkuser/.npm/_logs/2017-05-24T12_20_18_364Z-debug.log
>
> And i have verified the node and npm is in latest version.
> Please review and help me!
>
> Thanks in advance
> Elango
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_appium_appium_issues_8521&d=DwMFaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=GrVyjk9esLjbV-UuEWevVPxUeLcsCbkcwb9nvBHhjgE&m=hSxQQ6IFES5p_bJq55unaqtxt9h8a00ZnXThCZa4kCQ&s=ynZbhW5J-gTzmzbbqBFsXuEbgu688XYEnFzuvJ7S15U&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AUPSxMEe7xJgimX2rvBGBDW9c7hoE1flks5r9CrFgaJpZM4NlEzq&d=DwMFaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=GrVyjk9esLjbV-UuEWevVPxUeLcsCbkcwb9nvBHhjgE&m=hSxQQ6IFES5p_bJq55unaqtxt9h8a00ZnXThCZa4kCQ&s=MaorWjc6UTlGjppF5CutWzM5xK4YoN4d1ZLarN_ga2Y&e=>
> .
>



-- 
Thanks
Pavan Bachu
