### ISSUE TITLE
error when running the test on iPhone 5s simulator: attempt to insert nil object from objects[1]

### ISSUE THREAD

**Issue by gaboF** [appium/appium#8522]
The problem

During test automation on iOS simulator, the test failed with the error (see below). It looks as it crashed at the startup of simulator.

## Environment
Appium version: 1.6.4
Mac Mini: 10.12.5
Node version: 4.2.1
iOS simulator: iPhone 5s, iOS 10.3

*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[1]

(
	0   CoreFoundation                      0x0000000106474b0b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000105ed9141 objc_exception_throw + 48
	2   CoreFoundation                      0x00000001063895cd -[__NSPlaceholderArray initWithObjects:count:] + 269
	3   CoreFoundation                      0x0000000106390314 +[NSArray arrayWithObjects:count:] + 52
	4   XCTest                              0x00000001058d54f7 -[XCElementSnapshot(Hitpoint) _transformPoint:windowContextID:windowDisplayID:] + 133
	5   XCTest                              0x00000001058d58e9 -[XCElementSnapshot(Hitpoint) hitPoint] + 386
	6   WebDriverAgentLib                   0x0000000117c0fa2a -[XCElementSnapshot(FBIsVisible) fb_isVisible] + 810
	7   WebDriverAgentLib                   0x0000000117c1b0db -[XCElementSnapshot(WebDriverAttributes) isWDVisible] + 43
	8   WebDriverAgentLib                   0x0000000117c2c2c3 +[FBElementCommands handleGetDisplayed:] + 259
	9   WebDriverAgentLib                   0x0000000117c12263 -[FBRoute_TargetAction mountRequest:intoResponse:] + 179
	10  WebDriverAgentLib                   0x0000000117c09164 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 548
	11  RoutingHTTPServer                   0x0000000117cabc18 -[RoutingHTTPServer handleRoute:withRequest:response:] + 136
	12  RoutingHTTPServer                   0x0000000117cac4fa __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 47
	13  libdispatch.dylib                   0x00000001095b3792 _dispatch_client_callout + 8
	14  libdispatch.dylib                   0x000000010959c4e0 _dispatch_barrier_sync_f_slow_invoke + 292
	15  libdispatch.dylib                   0x00000001095b3792 _dispatch_client_callout + 8
	16  libdispatch.dylib                   0x000000010959b247 _dispatch_main_queue_callback_4CF + 1041
	17  CoreFoundation                      0x0000000106439909 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	18  CoreFoundation                      0x00000001063ffae4 __CFRunLoopRun + 2164
	19  CoreFoundation                      0x00000001063ff016 CFRunLoopRunSpecific + 406
	20  Foundation                          0x00000001059c2480 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 274
	21  Foundation                          0x00000001059c235b -[NSRunLoop(NSRunLoop) run] + 76
	22  WebDriverAgentLib                   0x0000000117c08143 -[FBWebServer startServing] + 211
	23  WebDriverAgentRunner                0x000000011778e254 -[UITestingUITests testRunner] + 100
	24  CoreFoundation                      0x00000001063fcc6c __invoking___ + 140
	25  CoreFoundation                      0x00000001063fcb40 -[NSInvocation invoke] + 320
	26  XCTest                              0x000000010588d8e2 __24-[XCTestCase invokeTest]_block_invoke_2 + 491
	27  XCTest                              0x00000001058cbf62 -[XCTestContext performInScope:] + 190
	28  XCTest                              0x000000010588d6e4 -[XCTestCase invokeTest] + 254
	29  XCTest                              0x000000010588dfb2 -[XCTestCase performTest:] + 565
	30  XCTest                              0x000000010588b078 __27-[XCTestSuite performTest:]_block_invoke + 300
	31  XCTest                              0x000000010588ac68 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 29
	32  XCTest                              0x000000010588ae4e -[XCTestSuite performTest:] + 214
	33  XCTest                              0x000000010588b078 __27-[XCTestSuite performTest:]_block_invoke + 300
	34  XCTest                              0x000000010588ac68 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 29
	35  XCTest                              0x000000010588ae4e -[XCTestSuite performTest:] + 214
	36  XCTest                              0x000000010588b078 __27-[XCTestSuite performTest:]_block_invoke + 300
	37  XCTest                              0x000000010588ac68 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 29
	38  XCTest                              0x000000010588ae4e -[XCTestSuite performTest:] + 214
	39  XCTest                              0x00000001058d7a86 __44-[XCTTestRunSession runTestsAndReturnError:]_block_invoke + 40
	40  XCTest                              0x0000000105899f27 -[XCTestObservationCenter _observeTestExecutionForBlock:] + 574
	41  XCTest                              0x00000001058d7925 -[XCTTestRunSession runTestsAndReturnError:] + 281
	42  XCTest                              0x0000000105875a50 -[XCTestDriver runTestsAndReturnError:] + 254
	43  XCTest                              0x00000001058cf86e _XCTestMain + 559
	44  CoreFoundation                      0x000000010641ab5c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
	45  CoreFoundation                      0x00000001063ffe54 __CFRunLoopDoBlocks + 356
	46  CoreFoundation                      0x00000001063ff5ee __CFRunLoopRun + 894
	47  CoreFoundation                      0x00000001063ff016 CFRunLoopRunSpecific + 406
	48  GraphicsServices                    0x00000001088c7a24 GSEventRunModal + 62
	49  UIKit                               0x00000001068980d4 UIApplicationMain + 159
	50  XCTRunner                           0x00000001057f588b XCTRunner + 6283
	51  libdyld.dylib                       0x00000001095fc65d start + 1
	52  ???                                 0x0000000000000005 0x0 + 5
)
Command duration or timeout: 761 milliseconds
Build info: version: '2.48.2', revision: '41bccdd', time: '2015-10-09 19:55:52'
System info: host: 'lewis.local', ip: '10.16.35.23', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.5', java.version: '1.8.0_60'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities [{app=/AutoTest/Workplace.app, networkConnectionEnabled=false, databaseEnabled=false, deviceName=iPhone 5s, fullReset=true, platform=MAC, platformVersion=10.3, webStorageEnabled=false, locationContextEnabled=false, automationName=xcuitest, browserName=, takesScreenshot=true, javascriptEnabled=true, platformName=iOS, udid=8FF4DCA6-B5D4-40AB-BAE7-D3E7684DF8ED}]
Session ID: e0cfa969-667d-4758-aebc-91a93b8131b7
Stacktrace

org.openqa.selenium.WebDriverException: *** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[1]

(
	0   CoreFoundation                      0x0000000106474b0b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000105ed9141 objc_exception_throw + 48
	2   CoreFoundation                      0x00000001063895cd -[__NSPlaceholderArray initWithObjects:count:] + 269
	3   CoreFoundation                      0x0000000106390314 +[NSArray arrayWithObjects:count:] + 52
	4   XCTest                              0x00000001058d54f7 -[XCElementSnapshot(Hitpoint) _transformPoint:windowContextID:windowDisplayID:] + 133
	5   XCTest                              0x00000001058d58e9 -[XCElementSnapshot(Hitpoint) hitPoint] + 386
	6   WebDriverAgentLib                   0x0000000117c0fa2a -[XCElementSnapshot(FBIsVisible) fb_isVisible] + 810
	7   WebDriverAgentLib                   0x0000000117c1b0db -[XCElementSnapshot(WebDriverAttributes) isWDVisible] + 43
	8   WebDriverAgentLib                   0x0000000117c2c2c3 +[FBElementCommands handleGetDisplayed:] + 259
	9   WebDriverAgentLib                   0x0000000117c12263 -[FBRoute_TargetAction mountRequest:intoResponse:] + 179
	10  WebDriverAgentLib                   0x0000000117c09164 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 548
	11  RoutingHTTPServer                   0x0000000117cabc18 -[RoutingHTTPServer handleRoute:withRequest:response:] + 136
	12  RoutingHTTPServer                   0x0000000117cac4fa __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 47
	13  libdispatch.dylib                   0x00000001095b3792 _dispatch_client_callout + 8
	14  libdispatch.dylib                   0x000000010959c4e0 _dispatch_barrier_sync_f_slow_invoke + 292
	15  libdispatch.dylib                   0x00000001095b3792 _dispatch_client_callout + 8
	16  libdispatch.dylib                   0x000000010959b247 _dispatch_main_queue_callback_4CF + 1041
	17  CoreFoundation                      0x0000000106439909 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	18  CoreFoundation                      0x00000001063ffae4 __CFRunLoopRun + 2164
	19  CoreFoundation                      0x00000001063ff016 CFRunLoopRunSpecific + 406
	20  Foundation                          0x00000001059c2480 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 274
	21  Foundation                          0x00000001059c235b -[NSRunLoop(NSRunLoop) run] + 76
	22  WebDriverAgentLib                   0x0000000117c08143 -[FBWebServer startServing] + 211
	23  WebDriverAgentRunner                0x000000011778e254 -[UITestingUITests testRunner] + 100
	24  CoreFoundation                      0x00000001063fcc6c __invoking___ + 140
	25  CoreFoundation                      0x00000001063fcb40 -[NSInvocation invoke] + 320
	26  XCTest                              0x000000010588d8e2 __24-[XCTestCase invokeTest]_block_invoke_2 + 491
	27  XCTest                              0x00000001058cbf62 -[XCTestContext performInScope:] + 190
	28  XCTest                              0x000000010588d6e4 -[XCTestCase invokeTest] + 254
	29  XCTest                              0x000000010588dfb2 -[XCTestCase performTest:] + 565
	30  XCTest                              0x000000010588b078 __27-[XCTestSuite performTest:]_block_invoke + 300
	31  XCTest                              0x000000010588ac68 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 29
	32  XCTest                              0x000000010588ae4e -[XCTestSuite performTest:] + 214
	33  XCTest                              0x000000010588b078 __27-[XCTestSuite performTest:]_block_invoke + 300
	34  XCTest                              0x000000010588ac68 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 29
	35  XCTest                              0x000000010588ae4e -[XCTestSuite performTest:] + 214
	36  XCTest                              0x000000010588b078 __27-[XCTestSuite performTest:]_block_invoke + 300
	37  XCTest                              0x000000010588ac68 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 29
	38  XCTest                              0x000000010588ae4e -[XCTestSuite performTest:] + 214
	39  XCTest                              0x00000001058d7a86 __44-[XCTTestRunSession runTestsAndReturnError:]_block_invoke + 40
	40  XCTest                              0x0000000105899f27 -[XCTestObservationCenter _observeTestExecutionForBlock:] + 574
	41  XCTest                              0x00000001058d7925 -[XCTTestRunSession runTestsAndReturnError:] + 281
	42  XCTest                              0x0000000105875a50 -[XCTestDriver runTestsAndReturnError:] + 254
	43  XCTest                              0x00000001058cf86e _XCTestMain + 559
	44  CoreFoundation                      0x000000010641ab5c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
	45  CoreFoundation                      0x00000001063ffe54 __CFRunLoopDoBlocks + 356
	46  CoreFoundation                      0x00000001063ff5ee __CFRunLoopRun + 894
	47  CoreFoundation                      0x00000001063ff016 CFRunLoopRunSpecific + 406
	48  GraphicsServices                    0x00000001088c7a24 GSEventRunModal + 62
	49  UIKit                               0x00000001068980d4 UIApplicationMain + 159
	50  XCTRunner                           0x00000001057f588b XCTRunner + 6283
	51  libdyld.dylib                       0x00000001095fc65d start + 1
	52  ???                                 0x0000000000000005 0x0 + 5
)
Command duration or timeout: 761 milliseconds
Build info: version: '2.48.2', revision: '41bccdd', time: '2015-10-09 19:55:52'
System info: host: 'lewis.local', ip: '10.16.35.23', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.5', java.version: '1.8.0_60'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities [{app=/AutoTest/Workplace.app, networkConnectionEnabled=false, databaseEnabled=false, deviceName=iPhone 5s, fullReset=true, platform=MAC, platformVersion=10.3, webStorageEnabled=false, locationContextEnabled=false, automationName=xcuitest, browserName=, takesScreenshot=true, javascriptEnabled=true, platformName=iOS, udid=8FF4DCA6-B5D4-40AB-BAE7-D3E7684DF8ED}]
Session ID: e0cfa969-667d-4758-aebc-91a93b8131b7
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:647)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:326)
	at io.appium.java_client.DefaultGenericMobileElement.execute(DefaultGenericMobileElement.java:44)
	at io.appium.java_client.MobileElement.execute(MobileElement.java:1)
	at io.appium.java_client.ios.IOSElement.execute(IOSElement.java:1)
	at org.openqa.selenium.remote.RemoteWebElement.isDisplayed(RemoteWebElement.java:367)
	at org.openqa.selenium.support.ui.ExpectedConditions.elementIfVisible(ExpectedConditions.java:302)
	at org.openqa.selenium.support.ui.ExpectedConditions.access$1(ExpectedConditions.java:301)
	at org.openqa.selenium.support.ui.ExpectedConditions$7.apply(ExpectedConditions.java:205)
	at org.openqa.selenium.support.ui.ExpectedConditions$7.apply(ExpectedConditions.java:1)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:238)
	at jtcom.SANDBOX.IOS.lib.screenClasses.SettingsScreen.tapOnSecuritySection(Unknown Source)
	at jtcom.SANDBOX.IOS.lib.screenClasses.SettingsScreen.openSecuritySettingsWithPassword(Unknown Source)
	at jtcom.SANDBOX.IOS.testMethods.TestsMobilePolicies.test3DisableSyncOnDevice(Unknown Source)

**Comment by mykola-mokhnach** [comment]
Known XCTest/WDA issue: https://github.com/facebook/WebDriverAgent/issues/575
Try to update Appium to 1.6.5-beta, which includes newer WDA, where this issue is fixed.
