### ISSUE TITLE
Failed to create WDA session on iOS simulator 10.3

### ISSUE THREAD

**Issue by GURVARINDER** [appium/appium#8523]
Environment:
Appium-desktop version 1.0.1
macOS Sierra version 10.12.4

Problem:
Appium gets stuck on creating the WDA session and keeps on retrying. Hence, unable to launch the app. 

Logs: 
[Appium] Welcome to Appium v1.6.4
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/SINGH/Desktop/MintChip.app","deviceName":"iPhone Simulator","noReset":true,"platformName":"iOS","platformVersion":"10.3","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/SINGH/Desktop/MintChip.app","deviceName":"iPhone Simulator","noReset":true,"platformName":"iOS","platformVersion":"10.3","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null,null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1495648558080 (13:55:58 GMT-0400 (EDT))
[Appium] Requested iOS support with version >= 10, using XCUITest driver instead of UIAutomation-based driver, since the latter is unsupported on iOS 10 and up.
[Appium] Creating new XCUITestDriver (v2.27.2) session
[Appium] Capabilities:
[Appium]   app: '/Users/SINGH/Desktop/MintChip.app'
[Appium]   deviceName: 'iPhone Simulator'
[Appium]   noReset: true
[Appium]   platformName: 'iOS'
[Appium]   platformVersion: '10.3'
[Appium]   newCommandTimeout: 0
[Appium]   connectHardwareKeyboard: true
[XCUITest] XCUITestDriver version: 2.27.2
[BaseDriver] Session created with session id: 31c18b9c-1ad7-4bf1-b7d5-3532eab910d0
[XCUITest] Xcode version set to '8.3.2' 
[XCUITest] iOS SDK Version set to '10.3'
[BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1495648558366 (13:55:58 GMT-0400 (EDT))
[XCUITest] Changing deviceName from 'iPhone Simulator' to 'iPhone 6'
[iOSSim] Constructing iOS simulator for Xcode version 8.3.2 with udid 'B69F6207-D9B9-4D41-AFBC-F26C16895D98'
[XCUITest] Determining device to run tests on: udid: 'B69F6207-D9B9-4D41-AFBC-F26C16895D98', real device: false
[BaseDriver] Using local app '/Users/SINGH/Desktop/MintChip.app'
[BaseDriver] Event 'appConfigured' logged at 1495648558836 (13:55:58 GMT-0400 (EDT))
[XCUITest] Checking whether app '/Users/SINGH/Desktop/MintChip.app' is actually present on file system
[XCUITest] App is present
[iOS] Getting bundle ID from app '/Users/SINGH/Desktop/MintChip.app': 'com.nanopay.mintchip'
[XCUITest] Setting 'connectHardwareKeyboard' Simulator option to 'on'
[BaseDriver] Event 'resetStarted' logged at 1495648558855 (13:55:58 GMT-0400 (EDT))
[XCUITest] Reset: noReset is on. Leaving simulator as is
[BaseDriver] Event 'resetComplete' logged at 1495648558855 (13:55:58 GMT-0400 (EDT))
[iOSLog] Starting iOS 10.3 simulator log capture
[iOSLog] System log path: /Users/SINGH/Library/Logs/CoreSimulator/B69F6207-D9B9-4D41-AFBC-F26C16895D98/system.log
[BaseDriver] Event 'logCaptureStarted' logged at 1495648559024 (13:55:59 GMT-0400 (EDT))
[XCUITest] Setting up simulator
[iOS] No reason to set locale
[iOS] No iOS / app preferences to set
[XCUITest] Simulator with udid 'B69F6207-D9B9-4D41-AFBC-F26C16895D98' not booted. Booting up now
[iOSSim] Killing all iOS Simulators
[iOSSim] Simulator is not running. Continuing...
[iOSSim] Starting simulator with command: open -Fn /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app --args -CurrentDeviceUDID B69F6207-D9B9-4D41-AFBC-F26C16895D98
[iOSSim] Simulator booted in 29518ms
[BaseDriver] Event 'simStarted' logged at 1495648588940 (13:56:28 GMT-0400 (EDT))
[XCUITest] App 'com.nanopay.mintchip' is already installed. No need to reinstall.
[BaseDriver] Event 'appInstalled' logged at 1495648588962 (13:56:28 GMT-0400 (EDT))
[BaseDriver] Event 'wdaStartAttempted' logged at 1495648588966 (13:56:28 GMT-0400 (EDT))
[XCUITest] Using WDA path: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[XCUITest] Carthage found: '/usr/local/bin/carthage'
[XCUITest] Killing hanging processes
[XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=B69F6207-D9B9-4D41-AFBC-F26C16895D98 -configuration Debug IPHONEOS_DEPLOYMENT_TARGET=10.3' in directory '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Output from xcodebuild will not be logged
[XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[XCUITest] Log file for xcodebuild test: /Users/SINGH/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/3BB846D9-CC95-4F58-B3C7-088A77A15A7A/Session-WebDriverAgentRunner-2017-05-24_135633-7OgUOk.log
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"state\" : \"success\",\n    \"os\" : {\n      \"name\" : \"iOS\",\n      \"version\" : \"10.3\"\n    },\n    \"ios\" : {\n      \"simulatorVersion\" : \"10.3\",\n      \"ip\" : \"192.168.20.82\"\n    },\n    \"build\" : {\n      \"time\" : \"May 24 2017 13:20:33\"\n    }\n  },\n  \"sessionId\" : \"112383D8-0CEE-470C-9BF6-CFE7090A1CFE\",\n  \"status\" : 0\n}"
[XCUITest] WebDriverAgent running on ip '192.168.20.82'
[XCUITest] WebDriverAgent successfully started after 12987ms
[BaseDriver] Event 'wdaSessionAttempted' logged at 1495648602245 (13:56:42 GMT-0400 (EDT))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.nanopay.mintchip","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[JSONWP Proxy] Got response with status 200: {"value":"Failed to launch com.nanopay.mintchip application","sessionId":"112383D8-0CEE-470C-9BF6-CFE7090A1CFE","status":13}
[XCUITest] Failed to create WDA session. Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1495648851574 (14:00:51 GMT-0400 (EDT))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.nanopay.mintchip","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[JSONWP Proxy] Got response with status 200: {"value":"Failed to launch com.nanopay.mintchip application","sessionId":"112383D8-0CEE-470C-9BF6-CFE7090A1CFE","status":13}
[XCUITest] Failed to create WDA session. Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1495649094143 (14:04:54 GMT-0400 (EDT))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.nanopay.mintchip","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[HTTP] <-- POST /wd/hub/session - - ms - - 
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/SINGH/Desktop/MintChip.app","deviceName":"iPhone Simulator","noReset":true,"platformName":"iOS","platformVersion":"10.3","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/SINGH/Desktop/MintChip.app","deviceName":"iPhone Simulator","noReset":true,"platformName":"iOS","platformVersion":"10.3","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null,null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1495649158157 (14:05:58 GMT-0400 (EDT))
[JSONWP Proxy] Got response with status 200: {"value":"Failed to launch com.nanopay.mintchip application","sessionId":"112383D8-0CEE-470C-9BF6-CFE7090A1CFE","status":13}
[XCUITest] Failed to create WDA session. Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1495649336849 (14:08:56 GMT-0400 (EDT))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.nanopay.mintchip","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}

Please help.

**Comment by mykola-mokhnach** [comment]
1. Do not set newCommandTimeout to zero
2. The application with bundle id com.nanopay.mintchip cannot be executed on simulator according to the log. It might be broken, - what happens if you start it manually?

**Comment by GURVARINDER** [comment]
sorry, but can you elaborate how to start the WDA manually?

**Comment by GURVARINDER** [comment]
if i start the app manually on the simulator it closed immediately, does that mean something is wrong with the actual app?

**Comment by mykola-mokhnach** [comment]
Yes this means the app might have a critical bug, which prevents it from launch.
Closed as non Appium-related
