### ISSUE TITLE
background_app(1) fails in landscape orientation on iOS real devices

### ISSUE THREAD

**Issue by abhilashcae** [appium/appium#8524]
## The problem

I'm using Python client. driver.background_app(1) is failing on iOS real device (version 10.0.2) when I do it in landscape orientation. App never comes to foreground once it is backgrounded.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5 beta
* Desktop OS/version used to run Appium: Mac OS X El Capitan 10.11.6
* Node.js version (unless using Appium.app|exe): 6.10.0
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Real iOS device (OS version 10.0.2)
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs

https://gist.github.com/abhilashcae/724f46428f5d602be5b113e571be86ce

**Comment by mykola-mokhnach** [comment]
Known [WDA bug](https://github.com/facebook/WebDriverAgent/issues/553)
I've recently pushed a [PR](https://github.com/facebook/WebDriverAgent/pull/569) to fix it, but it's not merged yet

**Comment by abhilashcae** [comment]
@mykola-mokhnach - The branch you had the fix is deleted. Is it fixed by someone in WDA?
