### ISSUE TITLE
Large memory leak in instruments

### ISSUE THREAD

**Issue by ToyX** [appium/appium#8526]
Mac OS 10.9 and 10.10 with patches or not

Test works ~80 minutes and instruments use 50Gb of memory.
Based on comments in appium discussions I replace all xpath locators by ui automation locator.
Turn off screenshots. Trying different versions of Appium and Mac OS / XCode
But memory leak still exist

**Comment by mykola-mokhnach** [comment]
Can you provide more detailed info about your environment or just fill out the default reporting template properly?

**Comment by ToyX** [comment]
My test is ergodic using appium ,so use a lot of “driver.getPageSources()”,I doubt it cause the problem
After test works 120 minutes instruments use almost 50Gb of memory, and write byte almost 200GB

here is the instruments process info
[instruments.txt](https://github.com/appium/appium/files/1028474/instruments.txt)

**Comment by pavanbachu0604** [comment]
@ToyX: How did you find the memory leak while running the Appium Tests ?

On Thu, May 25, 2017 at 5:16 AM, ToyX <notifications@github.com> wrote:

> My test is ergodic using appium ,so use a lot of
> “driver.getPageSources()”,I doubt it cause the problem
> After test works 120 minutes instruments use almost 50Gb of memory, and
> write byte almost 200GB
>
> here is the instruments process info
> instruments.txt
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_appium_appium_files_1028474_instruments.txt&d=DwMFaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=GrVyjk9esLjbV-UuEWevVPxUeLcsCbkcwb9nvBHhjgE&m=iGaSGQjGZgPi9GSymOQZc2COJqU4LVslZ2uxMJeMxVA&s=aYf71GQEbYuBs4V5OguqxvSpC2YOm_yKpxMREoJXsK4&e=>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_appium_appium_issues_8526-23issuecomment-2D303963095&d=DwMFaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=GrVyjk9esLjbV-UuEWevVPxUeLcsCbkcwb9nvBHhjgE&m=iGaSGQjGZgPi9GSymOQZc2COJqU4LVslZ2uxMJeMxVA&s=dL8EIzEQtufjoKitYFQBlxSHJaBBYCWDC-of6Fss0gY&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AUPSxEfICo614HCeVRhvAt7IxOE-5FKkD-2Dks5r9UbRgaJpZM4Nl7MF&d=DwMFaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=GrVyjk9esLjbV-UuEWevVPxUeLcsCbkcwb9nvBHhjgE&m=iGaSGQjGZgPi9GSymOQZc2COJqU4LVslZ2uxMJeMxVA&s=2lIDxP1nnQ9p2RB81TeCa92IsbEuZtyHW8QzlV9Hybs&e=>
> .
>



-- 
Thanks
Pavan Bachu

**Comment by ToyX** [comment]
@pavanbachu0604 By using the Mac OS / Active Monitor

**Comment by dpgraham** [comment]
Closing because we no longer support instruments.
