### ISSUE TITLE
Browser is launched instead of app

### ISSUE THREAD

**Issue by swathi-b** [appium/appium#8529]
## The problem
 I wanted to launch ios app in a real device.But Browser is opened and "appium.io" page is launched everytime.I am not sure what is going on.Can you guys please help me.

## Environment

Appium version:- 1.6.5-beta
Xcode:-Version 8.2.1
Device:- iphone 6 plus

**Details**
I am starting appium from command prompt with the following command
appium  --udid xxxxxx

Log 
[appium_log1.txt](https://github.com/appium/appium/files/1027910/appium_log1.txt)

And also tried with

appium --app "xx.ipa" --browser-name "" -a 127.0.0.1 --device-name "iPhone 6s" --show-ios-log --automation-name "XCUITest" --udid xxxxxx

Log:-[appium_log.txt](https://github.com/appium/appium/files/1027995/appium_log.txt)

Code

[Code.txt](https://github.com/appium/appium/files/1028000/Code.txt)

**Comment by mykola-mokhnach** [comment]
All capabilities should be set in the code. Do not try to set them as command line arguments - this way has been deprecated a while ago. In this particular case it complains about the **browserName** capability presence, which shouldn't be set, if **app** capability is present.
[Here](https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md) you will find detailed tutorial about real device setup for appium.

Closed as configuration related issue, which has nothing to do to Appium bugs. Please use Appium forum for further questions.

**Comment by swathi-b** [comment]
Thanks @mykola-mokhnach  I sorted out the issue.
