### ISSUE TITLE
Unable to recognize controls on SAMSUNG TAB having version Android v6. 

### ISSUE THREAD

**Issue by deepban74** [appium/appium#8533]
## The problem

Unable to recognize controls on SAMSUNG TAB having version Android v6.  The same works with android v4.4

## Environment

*Appium V6.
* Appium V4.4
* Desktop OS/version used to run Appium: 1.4.13.1 and 1.6.4
* Real device or emulator/simulator: Real Device

## Details
When we use UI Automator on Android 6.0 Devices they are not available at granular level while the same works on Android 4.4 devices

**Comment by mykola-mokhnach** [comment]
Can you provide mode detailed information about the problem? Is Appium version the recent one (1.6.4)? Can you attach the output of getPageSource command and explicitly point out what's missing there on Android 6.0 devices?

**Comment by deepban74** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/18466156/26449941/a6a86ae0-4172-11e7-911d-2260be9ce744.png)
Attached screen shot is a menu that pops up when we click a android.widget.Button. The menu items are recognized when we use a SAMSUNG TAB having v 4.4. but when we switch to 6 it fails.

**Comment by mykola-mokhnach** [comment]
Still too little info to help. Try, maybe, UIAutomator2 for Android 6

**Comment by deepban74** [comment]
From where do we install UIAutomator2? Also, how does it relate to what Appium version we use? I also tried identifying the object using Appium version 1.6.4 but it fails.

**Comment by deepban74** [comment]
[AndroidBootstrap] Sending command to android: {"cmd":"action","action":"find","params":{"strategy":"accessibility id","selector":"Al Khan","context":"","multiple":false}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"accessibility id","selector":"Al Khan","context":"","multiple":false}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: find
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding 'Al Khan' using 'ACCESSIBILITY_ID' with the contextId: '' multiple: false
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[DESCRIPTION=Al Khan, INSTANCE=0]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Failed to locate element. Clearing Accessibility cache and retrying.

**Comment by deepban74** [comment]
I could get this done using adb shell input text '' command

**Comment by deepban74** [comment]
I could get this done using adb shell input text '' command
