### ISSUE TITLE
uiautomator2, testapp crash while sendkeys method input beyond textfield limit

### ISSUE THREAD

**Issue by TomHappy** [appium/appium#8538]
## The problem

I use uiautomator2 engine. The textfield limit 140 characters,when sendkeys with 150 characters，my testapp crashed

## Environment

* Appium version (or git revision) that exhibits the issue:1.6.4
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):6.10.3
* Mobile platform/version under test:5.1.1
* Real device or emulator/simulator:Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Details
when send 150 charactors, app crashed. So it input nothing and couldn't find element anymore

## Code To Reproduce Issue [ Good To Have ]
	//input 150 characters,10 "0" is superfluous
	public void inputBeyondLimit(){
		clearBox(inputBox);
		inputBox.sendKeys("111111111122222222223333333333444444444455555555556666666666777777777788888888889999999999111111111122222222223333333333444444444455555555550000000000");
	}
	//check limit charactor function
	public Boolean isLimitCharactorCorrect(){
		inputBeyondLimit();
		//"0"should not display
		Boolean a = !inputBox.getText().contentEquals("0");
		//text lenth should be 140
		Boolean b = getInputBoxLength() == 140;
		//remainingLength should be 0
		Boolean c = remainingLength.getText().contentEquals("0");
		
		return a&&b&&c;
	}

**Comment by TomHappy** [comment]
I'm sorry i can't give the log. By the way, anybody who can teach me how to write log into a local file when start appium programmatically.I tried but failed:
	public AppiumDriverLocalService setService() throws NumberFormatException, IOException{
		
		service = AppiumDriverLocalService.buildService(new AppiumServiceBuilder()
				.withIPAddress(readexcel.getValue("AppiumServerIp"))
				.withArgument(GeneralServerFlag.LOG_LEVEL, "error")
				.usingPort(Integer.parseInt(readexcel.getValue("AppiumServerPort")))
				.usingDriverExecutable(new File(readexcel.getValue("nodeJSExecutable_Path")))
				.withAppiumJS(new File(readexcel.getValue("mainJS_Path")))
				//.withLogFile(new File("E:\\log\\appium.log")) this doesn't work
				//.withLogFile(new File(System.getProperty("user.dir") + "\\log\\appium.log")) also this doesn't work
				.withCapabilities(setServerCapabilities()));
		return service;
	}

**Comment by mykola-mokhnach** [comment]
Can you try with 1.6.5-beta?

**Comment by TomHappy** [comment]
i tried with 1.6.5, but still crashed

**Comment by jlipps** [comment]
Unfortunately the crash is happening in Android code and there's nothing we can do to workaround this, because there's no way to know what the max length of a text field is. From what I understand the crash does not happen on Android 7 and up, so the workaround for you is to use newer versions of Android :-/
