### ISSUE TITLE
Can't use Selenium and Appium driver methods in a same cucumber test

### ISSUE THREAD

**Issue by EugeneMarrow** [appium/appium#8539]
Hi, I'm writing tests for native iOS app using Appium selenium and cucumber with Selenium::WebDriver as main driver.
Story is, I would like to use some Appium_lib methods in my tests along with Selenium ones.
For example:
I've tried to write a test for login via Facebook, which should switch to webview in order to process some commands via IWDP to Safari.
And thats where I feel a lack of commands.
problem is that I can't manage env.rb file to use methods from both libs.
Hope someone here has any suggestions on this.

Here is my env.rb file with witch I run cucumber tests using selenium methods:
```
require 'rspec'
require 'rspec/expectations'
require 'appium_lib'
require 'cucumber/ast'
require 'selenium-webdriver'
require 'capybara/cucumber'
#require 'capybara/rails'

class AppiumWorld
end


def caps
       {"deviceName"=> "iPhone 6s",
        "platformName"=> "iOS",
        #"browserName"=>"Safari",
        #"startIWDP"=>"true",
        "platformVersion"=> "10.3.1",
        "udid"=> "7cb9e60a22f9a3982523298ecbf806ba1b96c469",
        "app"=> "/Users/macpad/Projects/louder/Louder.me.ipa",
        "bundleId"=> "com.musicplatform.louderme",
        'noReset' => "true"
      }
end

def url 
   "http://localhost:4723/wd/hub" 
 end
 
def selenium
  @driver ||=Selenium::WebDriver.for(:remote, :desired_capabilities=>caps, :url=>url)
end
#Appium::Driver.new(caps)
#Appium.promote_appium_methods AppiumWorld

World do
  AppiumWorld.new
end

#Before { $driver.start_driver }
 After {@driver.quit}

```
Thanks in advance

**Comment by mykola-mokhnach** [comment]
I suppose this should be reported to https://github.com/appium/ruby_lib/issues instead

**Comment by KazuCocoa** [comment]
This issue can be closed since https://github.com/appium/ruby_lib/issues/595 has created in ruby_lib repository.
