### ISSUE TITLE
appium bootstrap socket crush when start parallel test

### ISSUE THREAD

**Issue by desided** [appium/appium#8545]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Last Appium version that did not exhibit the issue (if applicable): -
* Desktop OS/version used to run Appium: try desktop for windows and from cmd npm install, and also try git clone repository
* Node.js version (unless using Appium.app|exe): 7.10.0 and 4.2.0
* Mobile platform/version under test: android 4.4.4, 5.0.1
* Real device or emulator/simulator:-memu emulator
* Appium CLI or Appium.app|exe:

## Details
start appium server - appium -p 4724 -bp 4555 -U emulator-5562
when try to start second emulator i got this. i think i try all variants, but still get this error. appium doctor view that all right, installing appium-android-bootstap, change version of android, change adb port - nothing helps. and Your advice - its my last hope)
## Link to Appium logs
`Error: Android bootstrap socket crashed: Error: read ECONNRESET
    at Socket.<anonymous> (../../lib/bootstrap.js:87:21)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at emitErrorNT (net.js:1279:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]
        AndroidDriver driver;
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability("udid", "emulator-5562");
        capabilities.setCapability("platformVersion", "4.4.4");
        capabilities.setCapability("platformName", "Android");
        capabilities.setCapability("appPackage", "org.proxydroid");
        capabilities.setCapability("noReset", true);
        capabilities.setCapability("adbport", "5570");
        capabilities.setCapability("unicodeKeyboard", true);
        capabilities.setCapability("resetKeyboard", true);
        capabilities.setCapability("appActivity", ".ProxyDroid");
        capabilities.setCapability("appPackage", "org.proxydroid");
        driver = new AndroidDriver(new URL("http://127.0.0.1:4724/wd/hub"), capabilities) {};
        System.out.print("thread start");

**Comment by dpgraham** [comment]
Can you provide the Appium logs

**Comment by NOTtheMessiah** [comment]
@jlipps Appium doesn't even have any logged events after `[Appium] Appium REST http interface listener started on 0.0.0.0:4724`
This happens even in Appium Desktop when I *Start New Session* with a saved capability set. When I click *Start Session* I get **Error ECONNRESET**

If you want the full logs from that:

    [Appium] Welcome to Appium v1.6.5
    [Appium] Non-default server args:
    [Appium]   port: 4724
    [Appium] Appium REST http interface listener started on 0.0.0.0:4724

**Comment by jlipps** [comment]
@NOTtheMessiah then where did you see the "android bootstrap crashed" error?

**Comment by jlipps** [comment]
@NOTtheMessiah i'm confused. what is the error you are experiencing. did you see that the android bootstrap crashed? or are you seeing a message from appium desktop?

but yes, port 4724 shouldn't be used for appium as internally the android bootstrap also uses port 4724.
