### ISSUE TITLE
TypeError: _deviceLogIosPerformanceLog.IOSPerformanceLog is not a constructor

### ISSUE THREAD

**Issue by pavanbachu0604** [appium/appium#8546]
## The problem
When switching from Native View to Web View, getting this error

## Environment

* Appium version : 1.6.5
* Last Appium version that did not exhibit the issue (if applicable):1.6.4
* Desktop OS/version used to run Appium: MacOS
* Mobile platform/version under test: iOS 10.3.2
* Real device or emulator/simulator: Real Device

## Link to Appium logs

Gist to Appium [Logs](https://gist.github.com/pavanbachu0604/3d846bd11e684268bd9f284bd6a79ebe)

## Code To Reproduce Issue [ Good To Have ]

	        cap = DesiredCapabilities.ipad();
		cap.setCapability("deviceName", "iPad");
		cap.setCapability("automationName", "XCUITest");
		cap.setCapability("newCommandTimeout", "10000");
		cap.setCapability("useNewWDA", true);
		cap.setCapability("iosInstallPause", "7000");
               cap.setCapability("app", "YYYYYYY");
	       cap.setCapability("enablePerformanceLogging", "true");

And another question is how do we capture the Performance Logging ?

**Comment by imurchie** [comment]
Thanks for reporting. Looking into it.

**Comment by imurchie** [comment]
This is fixed now. You will need to get the latest without shrinkwrap (until we publish a beta).
```
npm uninstall -g appium
npm install -g appium --no-shrinkwrap
```

**Comment by pavanbachu0604** [comment]
Sure I will try now

On Fri, May 26, 2017 at 4:46 PM, Isaac A. Murchie <notifications@github.com>
wrote:

> This is fixed now. You will need to get the latest without shrinkwrap
> (until we publish a beta).
>
> npm uninstall -g appium
> npm install -g appium --no-shrinkwrap
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_appium_appium_issues_8546-23issuecomment-2D304384368&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=GrVyjk9esLjbV-UuEWevVPxUeLcsCbkcwb9nvBHhjgE&m=DIdOv639VKxWy4dJYMYa-LTaOU2V0PgirKPnILJrjNg&s=mk5hFdD2OfPqsNwzE931VWfFfsWSl42LYjQcWtK3OLA&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AUPSxLrkyILATZ9d8Psrt0M2ZXpzQHXfks5r9zoLgaJpZM4NnsWl&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=GrVyjk9esLjbV-UuEWevVPxUeLcsCbkcwb9nvBHhjgE&m=DIdOv639VKxWy4dJYMYa-LTaOU2V0PgirKPnILJrjNg&s=jaorhXmXpispXkBi05ZWvAdSTQLgO_zMbapwBprBu3w&e=>
> .
>



-- 
Thanks
Pavan Bachu

**Comment by pavanbachu0604** [comment]
How to retrieve the Performance logs ?

On Fri, May 26, 2017 at 5:24 PM, Bachu, Pavan KUMAR <
pavan.bachu@verizonwireless.com> wrote:

> Sure I will try now
>
> On Fri, May 26, 2017 at 4:46 PM, Isaac A. Murchie <
> notifications@github.com> wrote:
>
>> This is fixed now. You will need to get the latest without shrinkwrap
>> (until we publish a beta).
>>
>> npm uninstall -g appium
>> npm install -g appium --no-shrinkwrap
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_appium_appium_issues_8546-23issuecomment-2D304384368&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=GrVyjk9esLjbV-UuEWevVPxUeLcsCbkcwb9nvBHhjgE&m=DIdOv639VKxWy4dJYMYa-LTaOU2V0PgirKPnILJrjNg&s=mk5hFdD2OfPqsNwzE931VWfFfsWSl42LYjQcWtK3OLA&e=>,
>> or mute the thread
>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AUPSxLrkyILATZ9d8Psrt0M2ZXpzQHXfks5r9zoLgaJpZM4NnsWl&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=GrVyjk9esLjbV-UuEWevVPxUeLcsCbkcwb9nvBHhjgE&m=DIdOv639VKxWy4dJYMYa-LTaOU2V0PgirKPnILJrjNg&s=jaorhXmXpispXkBi05ZWvAdSTQLgO_zMbapwBprBu3w&e=>
>> .
>>
>
>
>
> --
> Thanks
> Pavan Bachu
>



-- 
Thanks
Pavan Bachu
