### ISSUE TITLE
noReset capability not resetting app state on real iOS device

### ISSUE THREAD

**Issue by ewscripps-jb** [appium/appium#8548]
## The problem

Testing appium capabilities using Appium Desktop app noReset=false is not resetting the app state of the app when testing real iOS devices.  The noReset=false is resetting the app state when testing real Android devices.  I also see the same behavior when testing using the appium CLI and Robot Framework.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: OS X 10.12.5
* Node.js version (unless using Appium.app|exe): 7.10.0
* Mobile platform/version under test: iOS 10.3.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium.app and CLI

## Details

In order to test app functionality that occurs after app install/reinstall, resetting the app state will allow for testing that functionality.

## Link to Appium logs

https://gist.github.com/ewscripps-jb/fd2e8f452c80205b8bf17856afe8bb6d

## Code To Reproduce Issue [ Good To Have ]

This is a sample of the saved capability used when starting session in Appium Desktop:

{
  "automationName": "XCUITest",
  "platformName": "iOS",
  "platformVersion": "10.3.1",
  "deviceName": "fbed2571a3abe6bfe6db4da723aae23019524e69",
  "udid": "fbed2571a3abe6bfe6db4da723aae23019524e69",
  "bundleId": "com.journalinteractive.dfeb9598fbfb97cc6bbcc0aff2c785d6",
  "fullReset": false,
  "xcodeOrgId": "TW9MN4DML4",
  "xcodeSigningId": "iPhone Developer",
  "updatedWDABundleId": "TW9MN4DML4.WebDriverAgentRunner",
  "noReset": false
}

**Comment by mykola-mokhnach** [comment]
There is no way to just delete application settings without reinstalling the app itself on iOS - Apple simply does not provide such features with XCTest.

**Comment by ewscripps-jb** [comment]
Okay, thanks for the quick response.  I did not see any mention of that in the appium documentation.  I will find a different way to run those type of tests.  Cheers!
