### ISSUE TITLE
Unable to find ByPath XCUIElementTypeOther Control for hybrid Cordova iOS app.    

### ISSUE THREAD

**Issue by igoremelyanov** [appium/appium#8549]
## The problem
I am running my IntelliJ Java scenario against iPhone5 Emulator.
And I am able to find byPath and Click on the button "Allow" for the native Modal screen.
But unable to find and click on actual Username Control by XPaths in hydrid - "//XCUIElementTypeOther[@name="xxxxxxxxxx"]/XCUIElementTypeOther[3]/XCUIElementTypeTextField"

## Environment

Appium version (or git revision) that exhibits the issue: Appium v1.6.4
Last Appium version that did not exhibit the issue (if applicable):
Desktop OS/version used to run Appium: Appium 1.0.2-betta
Node.js version (unless using Appium.app|exe):
Mobile platform/version under test: 10.3.1
Real device or emulator/simulator: iPhone5 Emulator
Appium CLI or Appium.app|exe: Appium.app built successfully in Xcode 8.3.2 Mac.

## Link to Appium logs
gist:f6682d333ab8f04e31315cc13c63ef97

https://gist.github.com/igoremelyanov/f6682d333ab8f04e31315cc13c63ef97#file-gistfile1-txt

**Comment by mykola-mokhnach** [comment]
Try to calculate element coordinates and then perform click by coordinates using TouchActions interface

**Comment by igoremelyanov** [comment]
how to calculate elements coordinates?

**Comment by amedvedjev** [comment]
Igor you need:
```
int x = ((MobileElement) el).getCenter().getX();
int y=  ((MobileElement) el).getCenter().getY();
```

**Comment by igoremelyanov** [comment]
the problem that can not even find byPhath my Control.
I can not get x,y because xPath provided by Appium Desktop inspector does not work. 

I thinking maybe I should play around Native and Hybrid Contexts.  
[NATIVE_APP, WEBVIEW_7929.1]

**Comment by igoremelyanov** [comment]
ok. I found the solution. It is all related to how Appium handles the XPath.
