### ISSUE TITLE
UIAutomator2 start fail with unlock

### ISSUE THREAD

**Issue by wenshi11019** [appium/appium#8551]
## The problem

I start the appium server use UIAutomator2, the real device is Android 7.0(HUAWEI). But it always remained at the unlock process until the appium server failed. I use the "skipUnlock" capability, it can successful initialization the appium driver, but still fail to start test. It just light up the screen，can't launch the test app.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: 10.12.5
* Node.js version (unless using Appium.app|exe): 7.10
* Mobile platform/version under test: Android 7.0 HUAWEI phone
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs

https://gist.github.com/wenshi11019/abc67e5b94c34c78deed696a1f803d8b

**Comment by wenshi11019** [comment]
if I use `UIAutomator` capability,  test Android 4.4 device with the same code, it can success to test.

**Comment by mykola-mokhnach** [comment]
Try "unlockType" capability: https://github.com/appium/appium-android-driver/blob/9a9ee19a71ba106d5afdfd3d98731881b7571b44/docs/UNLOCK.md

**Comment by wenshi11019** [comment]
@mykola-mokhnach what is the `unlockType`  capability value？ I use `pin` and `pattern`, but failed to start appium driver. Of course, I use the `unlockKey` capability too . Because I don't use the `pin` and `pattern`  to unlock the device.

**Comment by wenshi11019** [comment]
@mykola-mokhnach I found a solution that it uses the `skipUnlock` capability, and then use the adb command to unlock device.

**Comment by mykola-mokhnach** [comment]
Which exactly adb command you use to unlock it?

**Comment by wenshi11019** [comment]
adb -s + deviceID + shell input keyevent KEYCODE_MENU
