### ISSUE TITLE
error when install appium 1.6.5

### ISSUE THREAD

**Issue by TomHappy** [appium/appium#8552]
## The problem

I got an error when install appium 1.6.5 by cmd "npm install -g appium"

## Environment

* Appium version (or git revision) that exhibits the issue: v1.6.5
* Last Appium version that did not exhibit the issue (if applicable): v1.6.4
* Desktop OS/version used to run Appium: windows10
* Node.js version (unless using Appium.app|exe): 6.10.3
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe: cli

## Details

It seems i should install Python Env?

## Link to Appium logs

install log here:
error at 55 line
https://gist.github.com/TomHappy/7f263c624e5c8299fca66305b8621986

**Comment by mykola-mokhnach** [comment]
I suppose you need to have Python installed on your system

**Comment by imurchie** [comment]
This should still be functional, since it is an optional dependency. But this is ugly.
