### ISSUE TITLE
When I test an own company app ,sometimes click some element so slow and other element normal,and the same time screen flash.

### ISSUE THREAD

**Issue by TesterQiao** [appium/appium#8553]
APPIUM 1.6.4
<dependency>
		<groupId>io.appium</groupId>
		<artifactId>java-client</artifactId>
		<version>5.0.0-BETA8</version>
</dependency>
[log.txt](https://github.com/appium/appium/files/1033399/log.txt)

**Comment by mykola-mokhnach** [comment]
Please fill out the necessary information in the reporting form. It is not clear what the environment is. Also, it would be good to have more detailed description of the problem

**Comment by TesterQiao** [comment]
@mykola-mokhnach  
Also need other ？there are a lot of the same log in appium log and debug log
* Appium version :1.6.4
* Mac OS 10.11.6
* Node.js version 4.5.0
* IOS  10.2 
* Real device
* Appium CLI

**Comment by mykola-mokhnach** [comment]
Try to avoid using xpath locators. Your problem might be https://github.com/facebook/WebDriverAgent/issues/372
