### ISSUE TITLE
[appium 1.6.4]can't run test on real device

### ISSUE THREAD

**Issue by wensj** [appium/appium#8554]
## The problem

I can't run test on real device(iPhone6),test on iOS Simulator is OK.I don't know how to fix this problem,please help me.Thanks.

## Environment

* Appium version (or git revision) that exhibits the issue:
1.6.4
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
macOS Sirra 10.12.5
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
iOS 10.2.1
* Real device or emulator/simulator:
iPhone6
* Appium CLI or Appium.app|exe:
Appium.app

## Details

1. I found a XCUITest error : 
[XCUITest] Error: Could not install app: 'Command 'ios-deploy --id 2f2afa168f2c0bbafde249f7ca24c5b035c5b967 --uninstall --bundle /var/folders/0g/p2ndjzhs2w54tdwn8tkd8d480000gn/T/2017427-28163-6gauop.u7koxswcdi/TestApp.app' exited with code 253' at IOSDeploy.install$ 

2. So I try to run the command :'ios-deploy --id 2f2afa168f2c0bbafde249f7ca24c5b035c5b967 --uninstall --bundle /var/folders/0g/p2ndjzhs2w54tdwn8tkd8d480000gn/T/2017427-28163-6gauop.u7koxswcdi/TestApp.app' ,then I got this error:
2017-05-27 16:20:18.013 ios-deploy[33892:1588184] [ !! ] Error 0xe800801c: No code signature found. AMDeviceSecureInstallApplication(0, device, url, options, install_callback, 0)

3. It seem to be a code signature problem,but I don't know how to fix it.

**Comment by nvhoang56123** [comment]
You need to build ipa to install to real device

**Comment by mykola-mokhnach** [comment]
Please follow this tutorial: https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md

Closed as non-issue.
