### ISSUE TITLE
selectPickerWheelValue method work on 1.6.5

### ISSUE THREAD

**Issue by nvhoang56123** [appium/appium#8556]
## The problem

Getting "Unhandled endpoint" respond when calling selectPickerWheelValue on appium 1.6.5

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Desktop OS/version used to run Appium: MAC Sierra
* Node.js version (unless using Appium.app|exe): 4.6.1
* Mobile platform/version under test: iPhone 6s - 10.3.2
* Real device or emulator/simulator: Real
* Appium CLI or Appium.app|exe: CLI

## Details

> [HTTP] --> POST /wd/hub/session/61d2e236-ebbc-4f97-942e-069bd307deb9/execute {"script":"mobile: selectPickerWheelValue","args":[{"offset":0.15,"order":"next","element":"1AD01251-AD27-48F7-8F69-F11D77C117F5"}]}
> [debug] [MJSONWP] Calling AppiumDriver.execute() with args: ["mobile: selectPickerWheelValue",[{"offset":0.15,"order":"next","element":"1AD01251-AD27-48F7-8F69-F11D77C117F5"}],"61d2e236-ebbc-4f97-942e-069bd307deb9"]
> [debug] [XCUITest] Executing command 'execute'
> [debug] [JSONWP Proxy] Proxying [POST /wda/pickerwheel/1AD01251-AD27-48F7-8F69-F11D77C117F5/select] to [POST http://localhost:8100/session/3F47898B-C6D1-43F2-B88E-BF4CDBAC1012/wda/pickerwheel/1AD01251-AD27-48F7-8F69-F11D77C117F5/select] with body: {"order":"next","offset":0.15}
> [debug] [JSONWP Proxy] Got response with status 200: {"value":"Unhandled endpoint: /session/3F47898B-C6D1-43F2-B88E-BF4CDBAC1012/wda/pickerwheel/1AD01251-AD27-48F7-8F69-F11D77C117F5/select -- http://localhost:8100/ with parameters {\n wildcards = (\n "session/3F47898B-C6D1-43F2-B88E-BF4CDBAC1012/wda/pickerwheel/1AD01251-AD27-48F7-8F69-F11D77C117F5/select"\n );\n}","sessionId":"3F47898B-C6D1-43F2-B88E-BF4CDBAC1012","status":1}

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

```
List<IOSElement> wheels = driver.findElements(MobileBy.className("XCUIElementTypePickerWheel"));
JavascriptExecutor js = (JavascriptExecutor) driver;
Map<String, Object> params = new HashMap<>();
params.put("order", "next");
params.put("offset", 0.15);
params.put("element", ((RemoteWebElement) wheels.get(0)).getId());
js.executeScript("mobile: selectPickerWheelValue", params);
```

**Comment by mykola-mokhnach** [comment]
You either have WDA application from previous Appium installation on your device and it should be uninstalled manually or the beta it quite old. We've recently released 1.6.5-stable, so try that one.

Closed as non-issue.

**Comment by suganeby** [comment]
@nvhoang56123
Is selectPickerWheelValue method  working in appium 1.6.5?
I am still using appium 1.6.4. I need to upgrade to 1.6.5 only if i can set value to the picker directly.

**Comment by nvhoang56123** [comment]
@suganeby method works on 1.6.5 confirmed. However, it scrolls step by step; not select value directly

**Comment by suganeby** [comment]
@nvhoang56123, Thanks for your response.

huh... for step by step i have a workaround already. step by step is not good for pickers with long set of values. I have a picker with more than 300 numbers.

**Comment by bill2605** [comment]
@suganeby mind sharing or providing more information about your "workaround"?
Cheers

**Comment by suganeby** [comment]
@bill2605, this is the work around i am using for UIPickerView. For date and time picker, value can be set directly using SetValue. 

List wheels = driver.findElements(MobileBy.className("XCUIElementTypePickerWheel"))

Point p1=wheels.get(0).getLocation()
Dimension d1 = wheels.get(0).getSize()

//-100 scrolls up (taps the value below the currently selected value)
driver.tap(1, p1.getX(), p1.getY() + d1.getHeight() -100, 500)

//+100 scrolls down (taps the value above the currently selected value)
driver.tap(1, p1.getX(), p1.getY() +100, 500)

**Comment by bill2605** [comment]
@suganeby Thanks for the pointer!
