### ISSUE TITLE
Issues while sending Tab key on IOS Tablet

### ISSUE THREAD

**Issue by ravi1124339** [appium/appium#8558]
## The problem

We are facing issue while sending the Tab key to move to next control on IOS tablets. There is no Tab key on IOS keyboard of IPad but we want to perform Tab key press.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Desktop OS/version used to run Appium: Windows Server 2012 R2 64 bit.
* Node.js version (unless using Appium.app|exe): 6.2.1
* Mobile platform/version under test: Ipad (v10.3.1)
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe:Appium.app

## Details
The Tab functionality is not working and could not find a way to perform Tab key press as no TAB key is present on IOS Tablet keyboard.. I want to move form one control to another using TAB key only as a necessary requirement.

I want
## Code To Reproduce Issue [ Good To Have ]

The code that i am using is 
Actions action = new Actions(Driver);
action.SendKeys(Keys.Tab).Perform();

The above code didn't worked so I tried with 
((IOSDriver<IWebElement>)Driver).Keyboard.PressKey(Keys.Tab);

and also tried with 
((IOSDriver<IWebElement>)Driver).Keyboard.SendKeys(Keys.Tab);

Please give some way to achieve this.

**Comment by mykola-mokhnach** [comment]
> There is no Tab key on IOS keyboard of IPad but we want to perform Tab key press.

Appium just uses what Apple provides to us. There is no magic there. This means if there is no tab key on the on-screen keyboard then you will not be able to emulate press on it as well.
