### ISSUE TITLE
Requesting for gesture speed/velocity customisation while performing circular, oval etc gestures.

### ISSUE THREAD

**Issue by Rohithnm** [appium/appium#8559]
## The problem

I would like to have gesture speed/Velocity customisation in Nano Seconds with TouchAction.

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

In one of my project we need to perform different kinds of gestures like circular, oval, elliptical, octagon etc with the speed of nano seconds. But as per the current implementation we can have gesture with minimum of 100milliseconds With current touch actions class able to perform gesture but those gestures are not accepted by the app since the speed is very less. This is the one of the major functionality of our app. And I hope this will help in automating lots of gesture based application.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
this is the full list of available gestures provided by XCTest:
https://developer.apple.com/reference/xctest/xcuielement

Time intervals these are usually set by values of type float, which contain number of seconds (values less than 1.0 are also valid). I'm not sure what is the minimum time resolution unit supported there, but you can try to invoke most of these functions via mobile: interface (which itself is, actually, a thin wrapper over these method calls) like it is described here: https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios-xctest-mobile-gestures.md

If the stuff still does not work then be kind to reroute your feature request directly to Apple ;)
