### ISSUE TITLE
Can we stop particular port's appium server from mac terminal command ?

### ISSUE THREAD

**Issue by Elangopalakrishnan** [appium/appium#8560]
## The problem

Hi,  

I'am running the two Appium server in two different port numbers for parallel execution, so that i can execute tests in parallel.
I need to stop particular port's appium server from mac terminal after completion of one port's test case.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Desktop OS/version used to run Appium: mac sierra 10.12.5 
* Mobile platform/version under test: 10.2.1 
* Real device or emulator/simulator: Real device

## Details

I'm running the two appium server in two different ports 
eg, appium server 1 is **4723** and appium server 1 is **4727** 

mac terminal command to start appium server:
Server1:
**appium -p 4723 --webkit-debug-proxy-port 27753 -U <UDID> --tmp /tmp/ios/**

Server2:
**appium -p 4727 --webkit-debug-proxy-port 27753 -U <UDID> --tmp /tmp/ios/**

As of now i'm using **"KillAll -c node"**  so it is killing both terminal window because it's name process is **"node"**.

Here i need to stop **4723** port's server alone,
Is there any terminal command available ? if so please help me.

Thanks in advance!
Elango

**Comment by amedvedjev** [comment]
you have two options:
1) start appium as process! not as terminal command. and quit process whenever you need.
2) kill appium by port number. get list of app that uses some port and kill them all.

**Comment by mykola-mokhnach** [comment]
Sorry, but the question has nothing to do with Appium issues at all. Please use Appium forum instead. Closed as unrelated.
