### ISSUE TITLE
send_keys not working with uiautomator2

### ISSUE THREAD

**Issue by nairouz12** [appium/appium#8561]
## The problem

I am not unable to enter a text into this element:
_android.widget.RelativeLayout (0)
  id: com.bnppf.mbb.debug:id/password_

It works on Appium 1.6.5 with uiautomator
but not on Appium 1.6.5 with uiautomator2 (the same issue is reproducible on Appium1.6.4)

## Environment

* Appium version (or git revision) that exhibits the issue:1.6.5 or 1.6.4
* Last Appium version that did not exhibit the issue (if applicable): works with uiautomator but not with uiautomator2
* Desktop OS/version used to run Appium:MacOS Sierra 10.12.4
* Node.js version (unless using Appium.app|exe):7.2.1
* Mobile platform/version under test:Android 6
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: CLI

**These are the logs when it doesn't work (uiautomator2)**
`[HTTP] --> POST /wd/hub/session/f00dd932-58fe-4470-9558-14eba3e05937/element/1026e5b7-5184-406f-8cb8-3f1c70ae3fd0/value {"value":["88888"]}
[debug] [MJSONWP] Calling AppiumDriver.setValue() with args: [["88888"],"1026e5b7-5184-406f-8cb8-3f1c70ae3fd0","f00dd932-58fe-4470-9558-14eba3e05937"]
[debug] [JSONWP Proxy] Proxying [POST /element/1026e5b7-5184-406f-8cb8-3f1c70ae3fd0/value] to [POST http://localhost:8200/wd/hub/session/edac2e48-b965-4294-a6a1-b59c85a3d2e5/element/1026e5b7-5184-406f-8cb8-3f1c70ae3fd0/value] with body: {"elementId":"1026e5b7-5184-406f-8cb8-3f1c70ae3fd0","text":"88888","replace":false}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"edac2e48-b965-4294-a6a1-b59c85a3d2e5","status":0,"value":""}
[debug] [MJSONWP] Responding to client with driver.setValue() result: ""
[HTTP] <-- POST /wd/hub/session/f00dd932-58fe-4470-9558-14eba3e05937/element/1026e5b7-5184-406f-8cb8-3f1c70ae3fd0/value 200 16 ms - 74`

**And these are the logs when it works (uiautomator)**
`[HTTP] --> POST /wd/hub/session/d95fb16a-9a36-4593-acd0-3d1bc084d58d/element/1/value {"value":["88888"]}
[debug] [MJSONWP] Calling AppiumDriver.setValue() with args: [["88888"],"1","d95fb16a-9a36-4593-acd0-3d1bc084d58d"]
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"element:setText","params":{"elementId":"1","text":"88888","replace":false}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:setText","params":{"elementId":"1","text":"88888","replace":false}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: setText
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using element passed in: 1
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Attempting to clear using UiObject.clearText().
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Sending plain text to element: 88888
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [MJSONWP] Responding to client with driver.setValue() result: true
[HTTP] <-- POST /wd/hub/session/d95fb16a-9a36-4593-acd0-3d1bc084d58d/element/1/value 200 4745 ms - 76
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":true}`

**Comment by mykola-mokhnach** [comment]
Maybe you're trying to enter the text into a wrong control...I suppose it should be TextEdit instead of RelativeLayout

**Comment by nairouz12** [comment]
but it worked with uiautomator.
The problem appeared only when I moved to uiautomator2

**Comment by mykola-mokhnach** [comment]
I assume it happens because UIA1 uses very simple "adb input" call for text typing purposes (which inputs text where the input focus currently is) and UIA2 uses the one provided by the native UIObject2 interface instead.

**Comment by nairouz12** [comment]
So how can I make it working in my case?

**Comment by mykola-mokhnach** [comment]
fix element locator

**Comment by priyankshah217** [comment]
also before sending text u can click on that UIElement.

**Comment by nairouz12** [comment]
it works with EditText elements
