### ISSUE TITLE
 Error occured while starting App. Original error: Permission to start activity denied. Even if the manifest was updated to be "True"

### ISSUE THREAD

**Issue by AlexK07** [appium/appium#8563]
## The problem

For some applications I can't run test cases. I get " Error occured while starting App. Original error: Permission to start activity denied." . I asked an Android dev to set up the manifest settings and I have the same issue. I've attached the appium log. 

## Environment

* Appium version (or git revision) that exhibits the issue: Version 1.0.2-beta.2 (1.0.2-beta.2)
* Desktop OS/version used to run Appium: MacOS Siera 10.12.3 
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Android , OS: 6.0
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs 
Here is the link to the appium log
https://gist.github.com/AlexK07/dcf0181eef6d5236a0566a9921bc850f

#Code 
public DesiredCapabilities huaweiP8() throws MalformedURLException{

		 DesiredCapabilities capabilities = DesiredCapabilities.android();

	        //set android name desired capabilities -- adb device
	        capabilities.setCapability("deviceName", "W3D7N16612000327");
	        //set device name , in our case we have Android
	        capabilities.setCapability(CapabilityType.BROWSER_NAME, "Android");
	        //set android version
	        capabilities.setCapability(CapabilityType.VERSION, "6.0");
	        //set platform name
	        capabilities.setCapability("platformName", "Android");
	        //set application appPackage
	        capabilities.setCapability("appPackage", "org.rtribe.rtribe");
	        //set you application main activity
	        capabilities.setCapability("appActivity", "org.rtribe.rtribe.ui.main.MainActivity");
	        return capabilities ;
	 }

**Comment by AlexK07** [comment]
I've tested with other applications like 9gag,Pinterest and with that application the appium server works. My question is , what needs the android developers to change to their apk builds ?

**Comment by mykola-mokhnach** [comment]
Appium cannot do much if this command returns an error:

```
adb shell am start -W -n org.rtribe.rtribe/org.rtribe.rtribe.ui.main.MainActivity -S
```

Probably, you need to set **appWaitActivity** capability as well

**Comment by AlexK07** [comment]
java.lang.SecurityException: Permission Denial: starting Intent { flg=0x10000000 cmp=org.rtribe.rtribe/.ui.main.MainActivity } from null (pid=32244, uid=2000) not exported from uid 10169
	at android.os.Parcel.readException(Parcel.java:1602)
	at android.os.Parcel.readException(Parcel.java:1555)
	at android.app.ActivityManagerProxy.startActivityAndWait(ActivityManagerNative.java:2766)
	at com.android.commands.am.Am.runStart(Am.java:883)
	at com.android.commands.am.Am.onRun(Am.java:361)
	at com.android.internal.os.BaseCommand.run(BaseCommand.java:47)
	at com.android.commands.am.Am.main(Am.java:102)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:251)

 So the problem is with the apk build ? The problem may be the manifest settings ?

**Comment by AlexK07** [comment]
I resolved the issue, the main problem was with main activity. And the activities was fragmented. Thanks for the support .

Here was the problem 
capabilities.setCapability("appPackage", "org.rtribe.rtribe");
	        //set you application main activity
	        capabilities.setCapability("appActivity", "org.rtribe.rtribe.ui.LauncherActivity");

**Comment by manasa151916** [comment]
@AlexK07  how did you change the activity name to org.rtribe.rtribe.ui.LauncherActivity

**Comment by AlexK07** [comment]
@manasa151916, I changed the app activity name from the Capabilities class. Each app has an own launcher activity in my case it was org.rtribe.rtribe.ui.LauncherActivity. In your case, you can use APK info app from the play store to check your app launcher activity.

**Comment by manasa151916** [comment]
Thanks @AlexK07 . It worked for me
