### ISSUE TITLE
1.6.5- Android - Simulator - Hybrid App - Error: unknown error: Chrome version must be >= 55.0.2883.0

### ISSUE THREAD

**Issue by siggerzz** [appium/appium#8566]
## The problem

When running a Android hybrid app tests on an Android 7.1.1 simulator, an error is returned saying the Chromedriver version must be >= 55.0.2883.0.

If i downgrade the Chromedriver to v2.24, I'm able to get around the issue and run my tests without problems.

I've tested on a real device (Samsung Galaxy S8 on Android 7.0) and tests seem to run fine.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3/1.6.4/1.6.5
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: MacOS 10.12.3
* Node.js version (unless using Appium.app|exe): 6.10.3
* Mobile platform/version under test: Android 7.1.1
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: CLI

## Details

When running a Android hybrid app tests on an Android 7.1.1 simulator, an error is returned saying the Chromedriver version must be >= 55.0.2883.0

## Link to Appium logs

[Appium Logs](https://gist.github.com/siggerzz/f27aa1708e118bb825d14cb7ef9fe7b9)

## Code To Reproduce Issue [ Good To Have ]
N/A

**Comment by mykola-mokhnach** [comment]
Appium uses chromedriver. And chromedriver itself is only compatible to the particular versions of Android system webview. Read https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/chromedriver.md for more details. 
Closed as not an issue.

**Comment by mykola-mokhnach** [comment]
@imurchie Can we somehow link that error message and the document above?
