### ISSUE TITLE
1.6.5-beta - iOS version 10.12.5 When i run the test i see that WDA & APP is installed & app fails to launch

### ISSUE THREAD

**Issue by skhanam** [appium/appium#8567]
1.6.5-beta - iOS version 10.12.5 When i run the test i see that WDA & APP is installed & app fails to launch

Capabilities 👍 
DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, Platform.SIERRA);
        capabilities.setCapability(MobileCapabilityType.DEVICE_NAME,"iPhone 6")
       capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME,"XCUITest");
        capabilities.setCapability(MobileCapabilityType.APP,app);
        driver = new IOSDriver<MobileElement>(new URL(URL_STRING), capabilities);
        driver.manage().timeouts().implicitlyWait(35, TimeUnit.SECONDS);
Logs 👍 

[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/shabanakhanum/workspacepersonal/AwsAndroid/src/test/apps/Quidco.ipa","automationName":"XCUITest","platformName":"iOS","deviceName":"iPhone 6"},"requiredCapabilities":{},"capabilities":{"desiredCapabilities":{"app":"/Users/shabanakhanum/workspacepersonal/AwsAndroid/src/test/apps/Quidco.ipa","automationName":"XCUITest","platformName":"iOS","deviceName":"iPhone 6"},"requiredCapabilities":{}},"alwaysMatch":{"app":"/Users/shabanakhanum/workspacepersonal/AwsAndroid/src/test/apps/Quidco.ipa","automationName":"XCUITest","platformName":"iOS","deviceName":"iPhone 6"},"firstMatch":[]}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/shabanakhanum/workspacepersonal/AwsAndroid/src/test/apps/Quidco.ipa","automationName":"XCUITest","platformName":"iOS","deviceName":"iPhone 6"},{},{"desiredCapabilities":{"app":"/Users/shabanakhanum/workspacepersonal/AwsAndroid/src/test/apps/Quidco.ipa","automationName":"XCUITest","platformName":"iOS","deviceName":"iPhone 6"},"requiredCapabilities":{}}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1496148049882 (13:40:49 GMT+0100 (BST))
[Appium] Creating new XCUITestDriver (v2.30.0) session
[Appium] Capabilities:
[Appium]   app: '/Users/shabanakhanum/workspacepersonal/AwsAndroid/src/test/apps/Quidco.ipa'
[Appium]   automationName: 'XCUITest'
[Appium]   platformName: 'iOS'
[Appium]   deviceName: 'iPhone 6'
[debug] [XCUITest] XCUITestDriver version: 2.30.0
[BaseDriver] Session created with session id: d2bf58d7-7e23-45ea-bfa8-08ecac8cdf03
[debug] [XCUITest] Xcode version set to '8.3.1' 
[debug] [XCUITest] iOS SDK Version set to '10.3'
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1496148050094 (13:40:50 GMT+0100 (BST))
[XCUITest] Simulator udid not provided, using desired caps to create a new simulator
[XCUITest] No platformVersion specified. Using latest version Xcode supports: '10.3' This may cause problems if a simulator does not exist for this platform version.
[iOSSim] Constructing iOS simulator for Xcode version 8.3.1 with udid 'B444EC1A-AEC2-4FE5-A4A9-14B77DC78E49'
[XCUITest] Created simulator with udid 'B444EC1A-AEC2-4FE5-A4A9-14B77DC78E49'.
[XCUITest] Determining device to run tests on: udid: 'B444EC1A-AEC2-4FE5-A4A9-14B77DC78E49', real device: false
[BaseDriver] Using local app '/Users/shabanakhanum/workspacepersonal/AwsAndroid/src/test/apps/Quidco.ipa'
[debug] [BaseDriver] Copying local zip to tmp dir
[debug] [BaseDriver] Unzipping /var/folders/41/bcy_l36543g5py5r0n27lwb80000gp/T/2017430-5828-16dehzd.g5d0zr529/appium-app.zip
[debug] [BaseDriver] Testing zip archive: /var/folders/41/bcy_l36543g5py5r0n27lwb80000gp/T/2017430-5828-16dehzd.g5d0zr529/appium-app.zip
[BaseDriver] Unzipped local app to '/var/folders/41/bcy_l36543g5py5r0n27lwb80000gp/T/2017430-5828-16dehzd.g5d0zr529/Payload/Quidco.app'
[debug] [BaseDriver] Event 'appConfigured' logged at 1496148055555 (13:40:55 GMT+0100 (BST))
[debug] [XCUITest] Checking whether app '/var/folders/41/bcy_l36543g5py5r0n27lwb80000gp/T/2017430-5828-16dehzd.g5d0zr529/Payload/Quidco.app' is actually present on file system
[debug] [XCUITest] App is present
[debug] [iOS] Getting bundle ID from app '/var/folders/41/bcy_l36543g5py5r0n27lwb80000gp/T/2017430-5828-16dehzd.g5d0zr529/Payload/Quidco.app': 'com.quidco.quidco'
[debug] [BaseDriver] Event 'resetStarted' logged at 1496148055572 (13:40:55 GMT+0100 (BST))
[XCUITest] Not scrubbing third party app in anticipation of uninstall
[debug] [BaseDriver] Event 'resetComplete' logged at 1496148055688 (13:40:55 GMT+0100 (BST))
[debug] [iOSLog] Starting iOS 10.3 simulator log capture
[debug] [iOSLog] System log path: /Users/shabanakhanum/Library/Logs/CoreSimulator/B444EC1A-AEC2-4FE5-A4A9-14B77DC78E49/system.log
[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1496148055795 (13:40:55 GMT+0100 (BST))
[XCUITest] Setting up simulator
[debug] [iOS] No reason to set locale
[debug] [iOS] No iOS / app preferences to set
[XCUITest] Simulator with udid 'B444EC1A-AEC2-4FE5-A4A9-14B77DC78E49' not booted. Booting up now
[debug] [iOSSim] Killing all iOS Simulators
[debug] [iOSSim] Using fkill to kill processes: 3465
[iOSSim] Starting simulator with command: open -Fn /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app --args -CurrentDeviceUDID B444EC1A-AEC2-4FE5-A4A9-14B77DC78E49 -ConnectHardwareKeyboard 0
[iOSSim] Simulator booted in 14095ms
[debug] [BaseDriver] Event 'simStarted' logged at 1496148081314 (13:41:21 GMT+0100 (BST))
[debug] [XCUITest] Installing /var/folders/41/bcy_l36543g5py5r0n27lwb80000gp/T/2017430-5828-16dehzd.g5d0zr529/Payload/Quidco.app on Simulator with UUID 'B444EC1A-AEC2-4FE5-A4A9-14B77DC78E49'...
[debug] [XCUITest] The app has been installed successfully.
[debug] [BaseDriver] Event 'appInstalled' logged at 1496148087164 (13:41:27 GMT+0100 (BST))
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1496148087166 (13:41:27 GMT+0100 (BST))
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'
[debug] [XCUITest] Killing hanging processes
[debug] [XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=B444EC1A-AEC2-4FE5-A4A9-14B77DC78E49 -configuration Debug IPHONEOS_DEPLOYMENT_TARGET=10.3' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[debug] [XCUITest] Output from xcodebuild will not be logged
[debug] [XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [XCUITest] Log file for xcodebuild test: /Users/shabanakhanum/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/DAE25BB7-6C75-4EE9-8F49-7EE54B972CEF/Session-WebDriverAgentRunner-2017-05-30_134129-c8F3AE.log
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"state\" : \"success\",\n    \"os\" : {\n      \"name\" : \"iOS\",\n      \"version\" : \"10.3\"\n    },\n    \"ios\" : {\n      \"simulatorVersion\" : \"10.3\",\n      \"ip\" : \"192.168.1.131\"\n    },\n    \"build\" : {\n      \"time\" : \"May 27 2017 13:09:31\"\n    }\n  },\n  \"sessionId\" : \"D532025C-8433-4F66-B4D1-608ECB8F4434\",\n  \"status\" : 0\n}"
[debug] [XCUITest] WebDriverAgent running on ip '192.168.1.131'
[debug] [XCUITest] WebDriverAgent successfully started after 8466ms
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1496148095767 (13:41:35 GMT+0100 (BST))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.quidco.quidco","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}

**Comment by skhanam** [comment]
More logs 👍 

May 30 13:45:39 Lon-Quid-ML-82 assertiond[5888]: Submitted job with label: UIKitApplication:com.quidco.quidco[0x4fe1][5888]
May 30 13:45:39 Lon-Quid-ML-82 com.apple.CoreSimulator.SimDevice.B444EC1A-AEC2-4FE5-A4A9-14B77DC78E49.launchd_sim[5866] (UIKitApplication:com.quidco.quidco[0x4fe1][5888][6077]): Program specified by service does not contain one of the requested architectures: 
May 30 13:45:39 Lon-Quid-ML-82 assertiond[5888]: Unable to get pid for 'UIKitApplication:com.quidco.quidco[0x4fe1][5888]': No such process (3)
May 30 13:45:39 Lon-Quid-ML-82 assertiond[5888]: Failed to start job with error Error Domain=NSPOSIXErrorDomain Code=3 "No such process" UserInfo={NSLocalizedFailureReason=No such process, BKLaunchdOperation=launch_get_running_pid_4SB, BKLaunchdJobLabel=UIKitApplication:com.quidco.quidco[0x4fe1][5888], NSLocalizedDescription=Unable to get pid for label UIKitApplication:com.quidco.quidco[0x4fe1][5888]}
May 30 13:45:39 Lon-Quid-ML-82 assertiond[5888]: Deleted job with label: UIKitApplication:com.quidco.quidco[0x4fe1][5888]
May 30 13:45:39 Lon-Quid-ML-82 SpringBoard[5883]: [com.quidco.quidco] Bootstrap failed with error: <NSError: 0x60000064bf70; domain: BKSProcessErrorDomain; code: 1 (bootstrap-failed); reason: "Failed to start job">
May 30 13:45:39 Lon-Quid-ML-82 SpringBoard[5883]: [Common] Bootstrapping failed for <FBApplicationProcess: 0x7faa7451bae0; com.quidco.quidco; pid: -1> with error: Error Domain=BKSProcessErrorDomain Code=1 "Unable to bootstrap process with bundleID com.quidco.quidco" UserInfo={BKSProcessExitReason=1, NSLocalizedFailureReason=Failed to start job, NSUnderlyingError=0x60000064c510 {Error Domain=NSPOSIXErrorDomain Code=3 "No such process" UserInfo={BKLaunchdOperation=launch_get_running_pid_4SB, NSLocalizedDescription=Unable to get pid for label UIKitApplication:com.quidco.quidco[0x4fe1][5888], BKLaunchdJobLabel=UIKitApplication:com.quidco.quidco[0x4fe1][5888], NSLocalizedFailureReason=No such process}}, BSErrorCodeDescription=bootstrap-failed, BKSProcessJobLabel=UIKitApplication:com.quidco.quidco[0x4fe1][5888], NSLocalizedDescription=Unable to bootstrap process with bundleID com.quidco.quidco}
May 30 13:46:38 Lon-Quid-ML-82 XCTRunner[6046]: Enqueue Failure: App state is still not running, state = Not Running /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 35 1
May 30 13:47:08 Lon-Quid-ML-82 routined[5872]: CoreLocation: Error occurred while trying to retrieve motion state update: CMErrorDomain Code:104
May 30 13:47:38 Lon-Quid-ML-82 XCTRunner[6046]: Enqueue Failure: App does not have a process ID /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 35 1
May 30 13:48:39 Lon-Quid-ML-82 XCTRunner[6046]: Enqueue Failure: App accessibility isn't loaded /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 35 1

**Comment by skhanam** [comment]
debug] [XCUITest] Failed to create WDA session. Retrying...
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1496148581140 (13:49:41 GMT+0100 (BST))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.quidco.quidco","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[HTTP] <-- POST /wd/hub/session - - ms - - 
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/shabanakhanum/workspacepersonal/AwsAndroid/src/test/apps/Quidco.ipa","automationName":"XCUITest","platformName":"iOS","deviceName":"iPhone 6"},"requiredCapabilities":{},"capabilities":{"desiredCapabilities":{"app":"/Users/shabanakhanum/workspacepersonal/AwsAndroid/src/test/apps/Quidco.ipa","automationName":"XCUITest","platformName":"iOS","deviceName":"iPhone 6"},"requiredCapabilities":{}},"alwaysMatch":{"app":"/Users/shabanakhanum/workspacepersonal/AwsAndroid/src/test/apps/Quidco.ipa","automationName":"XCUITest","platformName":"iOS","deviceName":"iPhone 6"},"firstMatch":[]}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/shabanakhanum/workspacepersonal/AwsAndroid/src/test/apps/Quidco.ipa","automationName":"XCUITest","platformName":"iOS","deviceName":"iPhone 6"},{},{"desiredCapabilities":{"app":"/Users/shabanakhanum/workspacepersonal/AwsAndroid/src/test/apps/Quidco.ipa","automationName":"XCUITest","platformName":"iOS","deviceName":"iPhone 6"},"requiredCapabilities":{}}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1496148651908 (13:50:51 GMT+0100 (BST))

**Comment by mykola-mokhnach** [comment]
Seems like your application under test cannot be started on Simulator. Have you  tried this manually?

**Comment by skhanam** [comment]
yes it works well 

here are more logs 

org.openqa.selenium.WebDriverException: org.apache.http.NoHttpResponseException: 0.0.0.0:4723 failed to respond
Build info: version: '3.3.1', revision: '5234b325d5', time: '2017-03-10 09:10:29 +0000'
System info: host: 'Lon-Quid-ML-82.lan', ip: 'fe80:0:0:0:815:ee2c:804b:5ab0%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.5', java.version: '1.8.0_91'
Driver info: driver.version: IOSDriver

	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:84)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:604)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:40)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:244)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:36)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:114)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:132)
	at io.appium.java_client.ios.IOSDriver.<init>(IOSDriver.java:82)

**Comment by mykola-mokhnach** [comment]
> Program specified by service does not contain one of the requested architectures

That's for sure a sign, that the build cannot be executed on Simulator.
Make sure you use correct build.
Closed as not Appium-related.
