### ISSUE TITLE
Test fails on iOS simulator with hybrid app when using I.fillField() method

### ISSUE THREAD

**Issue by wjastrzemski** [appium/appium#8568]
## The problem

I have to implement test for iOS simulator and hybrid application. I have already intergation of Appium with iOS.
I want to implement simple test which will open the app and go to login view and login user.
I am trying to input text into textbox of hybrid application on iOS simulator.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4 (checked also on 1.6.3 and 1.6.5)
* Desktop OS/version used to run Appium: macOS Sierra 10.12.4
* Node.js version (unless using Appium.app|exe):7.10.0
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: iOS simulator 10.2
* WebDriverIO: 4.6.2
* CodeceptJS version: 0.5.1

## Details

When I am using method I.fillField the test is failing with information:
`Parameters were incorrect. We wanted {"required":["value"]} and you sent ["value","text"]`

Test login.js:

```
Scenario('Login test', (I, homePage, promoPopupFragment) => {
    promoPopupFragment.close();
    homePage.goToLogin();
    I.fillField('input[name="username"]','username');
    I.fillField('input[name="password"]','password');
    I.click('.submit');
    homePage.goToMyAccount();
    }
)
```

Configuration file:
```
exports.config = {
    tests: './tests/native/native_login_test.js',
    timeout: 30000,
    output: './output',
    helpers: {
        WebDriverIO: {
            "desiredCapabilities": {
                "app": "/Users/test.app",
                "platformName": "iOS",
                "platformVersion": "10.2",
                "deviceName": "Iphone 6 10.2",
                "autoWebview": true,
                "automationName": "XCUITest",
                "fullReset": true,
                "newCommandTimeout": 60,
            },
            "port": 4723,
            "browser": " ",
            "url": "http://localhost",
            "waitForTimeout": 30000
        },
        MyHelper: {
            require: './helpers/custom_methods/MyHelper.js',
        }
    },
    include: {
        I: './helpers/steps_file.js',
        loginPage: './helpers/mobile/pages/Login.js',
        ...
    },
    bootstrap: false,
    mocha: {
        reporterOptions: {
            reportDir: './output',
            enableCharts: true,
            reportTitle: 'Reporter'
        }
    },
    name: 'Test',
};
```

**Comment by mykola-mokhnach** [comment]
Known issue. There is a PR in master branch, but it's not tagged yet. You may downgrade webdriver.io to workaround the issue.

**Comment by mykola-mokhnach** [comment]
The change has been added to Appium 1.6.5-beta
Please update and try it

**Comment by wjastrzemski** [comment]
After update to 1.6.5-beta it worked. Thanks for help
