### ISSUE TITLE
Issue with tapping buttons on system dialogues in landscape mode 

### ISSUE THREAD

**Issue by Strybushnyi** [appium/appium#8569]
## The problem

Hi there!
I've got an issue with tapping buttons on system dialogue.
The thing is the button is tapped, but nothing happens on the device's screen
I have asked developers on this matter, but they replied they cannot handle this dialogue anyhow.
So, basically, Appium Taps on button "OK" to allow access to Camera and Microphone, test passes, app is closed, but system dialogue remains on the screen.
At this moment app is in landscape mode, thus, please confirm it relates to known issue with landscape mode.

Thank you in advance. 

## Environment

* Appium Desktop version 1.0.2-beta.2
* macOS Sierra 10.12.5
* iOS 10.3.1 & 10.2
* Real device 
* Appium Desktop

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/Strybushnyi/e8f33a1cf5838a417e837ae7c1244257

**Comment by mykola-mokhnach** [comment]
There is known XCTest bug. You may change to portrait and handle the alert then change back to landscape as a workaround.

**Comment by Strybushnyi** [comment]
Even if this screen in app is locked for Landscape mode only?

**Comment by mykola-mokhnach** [comment]
Then you have a problem. Try to calculate alert button coordinates and tap it by absolute coordinates.

**Comment by Strybushnyi** [comment]
I did it, I have 2 buttons:
"Don't Allow"
"OK"
I tried to set coordinates, but even with x:1 y:1 it taps "Don't Allow" 
So, It tapes this particular button with any set coordinates
