### ISSUE TITLE
App not Launching in Appium 1.6.4 for Android Emulator

### ISSUE THREAD

**Issue by mojojojo94** [appium/appium#8570]
## The problem

Not able to run a test script using appium desktop 1.6.4, mobile app does not open in Android emulator so test does not run. I can run appium inspector just fine, app opens up on that. Provided same capabilities for test case as appium inspector session. No errors in appium server logs so it is hard to identify the specific problem. Appium logs provided below.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Last Appium version that did not exhibit the issue (if applicable): n/a
* Desktop OS/version used to run Appium: 1.6.4
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Android 
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: Appium.app

## Details

Here are the capabilities I'm providing:
"platformName": "Android",
 "platformVersion": "4.4",
 "deviceName": "Android Emulator",
 "app": "/Users/myUserName/Documents/mobileApplications/mobileApp.zip",
 "avd": "api19"
 "appPackage": "com.companyName.mobile.android"
 "appActivity": "com.companyName.mobile.android.ui.RootActivity"

I don't know if its because I'm missing some android specific capability or if it because its appium is not able to unzip the file correctly and open it.

But it looks like I have the right capabilities set in order to launch my test case on an android emulator.

## Link to Appium logs

I'll post the appium logs here, since they're short.

[Appium] Welcome to Appium v1.6.4
[Appium] Non-default server args:
[Appium]   address: 127.0.0.1
[Appium] Appium REST http interface listener started on 127.0.0.1:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/myUserName/bitbucket_repo/automation-tests/Selenium_Gcom/Gcom_Automation/src/test/resources/Appium_App/Android/mobileApp.zip","appPackage":"com.companyName.mobile.android","appActivity":"com.companyName.mobile.android.ui.RootActivity","browerName":"","public":"share","platformVersion":"4.4","name":"ANDROID_LOGIN_LOGOUT","timeZone":"Central","platformName":"Android","deviceName":"Android Emulator","avd":"api19"}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/myUserName/bitbucket_repo/automation-tests/Selenium_Gcom/Gcom_Automation/src/test/resources/Appium_App/Android/mobileApp.zip","appPackage":"com.companyName.mobile.android","appActivity":"com.companyName.mobile.android.ui.RootActivity","browerName":"","public":"share","platformVersion":"4.4","name":"ANDROID_LOGIN_LOGOUT","timeZone":"Central","platformName":"Android","deviceName":"Android Emulator","avd":"api19"},null,null,null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1496160688825 (11:11:28 GMT-0500 (CDT))
[Appium] Creating new AndroidDriver (v1.17.1) session
[Appium] Capabilities:
[Appium]   app: '/Users/myUserName/bitbucket_repo/automation-tests/Selenium_Gcom/Gcom_Automation/src/test/resources/Appium_App/Android/mobileApp.zip'
[Appium]   appPackage: 'com.companyName.mobile.android'
[Appium]   appActivity: 'com.companyName.mobile.android.ui.RootActivity'
[Appium]   browerName: ''
[Appium]   public: 'share'
[Appium]   platformVersion: '4.4'
[Appium]   name: 'ANDROID_LOGIN_LOGOUT'
[Appium]   timeZone: 'Central'
[Appium]   platformName: 'Android'
[Appium]   deviceName: 'Android Emulator'
[Appium]   avd: 'api19'
[AndroidDriver] AndroidDriver version: 1.17.1
[BaseDriver] The following capabilities were provided, but are not recognized by appium: browerName, public, name, timeZone.
[BaseDriver] Session created with session id: d24616f1-fc0d-4aa4-9e21-b2f9ed014bf9
[AndroidDriver] Getting Java version
[AndroidDriver] Java version is: 1.8.0_121
[ADB] Checking whether adb is present
[ADB] Using adb from /Users/myUserName/Library/Android/sdk/platform-tools/adb
[ADB] Trying to find api19 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] 1 emulator(s) connected
[ADB] Sending telnet command to device: avd name
[ADB] Getting running emulator port
[ADB] Socket connection to device created
[ADB] Socket connection to device ready
[ADB] Telnet command got response: api19
[ADB] Found emulator api19 in port 5554
[ADB] Setting device id to emulator-5554
[AndroidDriver] Not launching AVD because it is already running.
[AndroidDriver] Using device: emulator-5554
[ADB] Checking whether adb is present
[ADB] Using adb from /Users/myUserName/Library/Android/sdk/platform-tools/adb
[ADB] Setting device id to emulator-5554
[BaseDriver] Using local app '/Users/myUserName/bitbucket_repo/automation-tests/Selenium_Gcom/Gcom_Automation/src/test/resources/Appium_App/Android/mobileApp.zip'
[BaseDriver] Copying local zip to tmp dir
[BaseDriver] Unzipping /var/folders/z0/r9v09hj940j9v5wz0tw2nj3jw317c1/T/2017430-93924-q7znwc.tc8kqehfr/appium-app.zip
[BaseDriver] Testing zip archive: /var/folders/z0/r9v09hj940j9v5wz0tw2nj3jw317c1/T/2017430-93924-q7znwc.tc8kqehfr/appium-app.zip
[BaseDriver] Got a relaxed match for app in zip, be careful for app match errors
[BaseDriver] Unzipped local app to '/var/folders/z0/r9v09hj940j9v5wz0tw2nj3jw317c1/T/2017430-93924-q7znwc.tc8kqehfr/mobileApp_latest.apk'
[AndroidDriver] Checking whether app is actually present
[AndroidDriver] Starting Android session
[ADB] Running '/Users/myUserName/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","wait-for-device"]
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running '/Users/myUserName/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","echo","ping"]
[ADB] Running '/Users/myUserName/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","echo","ping"]
[ADB] Restarting adb

appium doesn't move past this point, it gets stuck here.

## P.S.
iOS automation works great with appium 1.6.4, its the Android platform that has been giving us issue. Any help with identifying the problem would be of great help. Thank you for your time.

**Comment by mykola-mokhnach** [comment]
What if you exclude **deviceName** capability?

**Comment by mojojojo94** [comment]
Appium returns that deviceName capability can't be left blank -- here are the logs as well.

`[Appium] Welcome to Appium v1.6.4
[Appium] Non-default server args:
[Appium]   address: 127.0.0.1
[Appium] Appium REST http interface listener started on 127.0.0.1:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/myUserName/bitbucket_repo/automation-tests/Selenium_Gcom/Gcom_Automation/src/test/resources/Appium_App/Android/mobileApp.zip","appPackage":"com.companyName.mobile.android","appActivity":"com.companyName.mobile.android.ui.RootActivity","public":"share","platformVersion":"4.4","name":"ANDROID_LOGIN_LOGOUT","timeZone":"Central","platformName":"Android","avd":"api19"}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/myUserName/bitbucket_repo/automation-tests/Selenium_Gcom/Gcom_Automation/src/test/resources/Appium_App/Android/mobileApp.zip","appPackage":"com.companyName.mobile.android","appActivity":"com.companyName.mobile.android.ui.RootActivity","public":"share","platformVersion":"4.4","name":"ANDROID_LOGIN_LOGOUT","timeZone":"Central","platformName":"Android","avd":"api19"},null,null,null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1496218677612 (03:17:57 GMT-0500 (CDT))
[Appium] Creating new AndroidDriver (v1.17.1) session
[Appium] Capabilities:
[Appium]   app: '/Users/myUserName/bitbucket_repo/automation-tests/Selenium_Gcom/Gcom_Automation/src/test/resources/Appium_App/Android/mobileApp.zip'
[Appium]   appPackage: 'com.companyName.mobile.android'
[Appium]   appActivity: 'com.companyName.mobile.android.ui.RootActivity'
[Appium]   public: 'share'
[Appium]   platformVersion: '4.4'
[Appium]   name: 'ANDROID_LOGIN_LOGOUT'
[Appium]   timeZone: 'Central'
[Appium]   platformName: 'Android'
[Appium]   avd: 'api19'
[AndroidDriver] AndroidDriver version: 1.17.1
[BaseDriver] SessionNotCreatedError: A new session could not be created. Details: The desiredCapabilities object was not valid for the following reason(s): deviceName can't be blank.`

**Comment by mykola-mokhnach** [comment]
set it to **null** then

**Comment by mojojojo94** [comment]
Well, I get a null pointer exception.

**Comment by mojojojo94** [comment]
@mykola-mokhnach any other suggestions or more information I can give you, that could be of help resolving this issue?

**Comment by mykola-mokhnach** [comment]
For me it looks more like internal Emulator/adb issue. Try on other machine, recreate the emulator completely, try another emulator version...

**Comment by mojojojo94** [comment]
Ok, I'll try those, thank you for your suggestions!

**Comment by mojojojo94** [comment]
Its looking like a framework issue, closed ticket. Thank you @mykola-mokhnach
