### ISSUE TITLE
Appium 1.6.5 - click() not working for some iOS elements

### ISSUE THREAD

**Issue by Brian-Watson** [appium/appium#8571]
## The problem

I have a page in my app that has a XCUIElementTypeTable element on it with a collection of cells.  When first launched, the cell I wish to click on is not visible, as it's off screen at the time.  So I scroll the table down to make the cell visible. I then find a XCUIElementTypeTextField in the cell, and then try to click() on it.  Appium returns successfully, but the element isn't really clicked.  This worked in Appium 1.6.4.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Last Appium version that did not exhibit the issue (if applicable): 1.6.4
* Desktop OS/version used to run Appium: OS X
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS 10.3
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: CLI

## Details

After scrolling an element into view, the click() doesn't seem to actually work.  One thing I noticed is that in Appium 1.6.5, I now see a 'visible' attribute being returned in the page source for iOS elements.  This attribute comes back as 'false' for the element I'm trying to click, even after it's scrolled into view.

## Link to Appium logs

https://gist.github.com/Brian-Watson/bf6aee5b4652ba8fe4ce560e799e44c1

## Code To Reproduce Issue [ Good To Have ]

mobile:scroll down on my XCUIElementTypeTable element

Then click on a XCUIElementTypeTextField that should now be visible.

**Comment by mykola-mokhnach** [comment]
Try to set **simpleIsVisibleCheck** capability to false

**Comment by imurchie** [comment]
If scrolling works this shouldn't be a visibility issue.

**Comment by Brian-Watson** [comment]
With the following set...

desiredCapabilities.setCapability("simpleIsVisibleCheck", false);

Shows in the appium log as...

2017-05-30 13:13:00:274 - [Appium]   simpleIsVisibleCheck: false

It unfortunately behaved the same way.  What is interesting is that if I select some other cell which brings up another modal, and the go back, the control then shows as displayed and I can click it just fine.

**Comment by mykola-mokhnach** [comment]
I'd recommend to create an issue directly in https://github.com/facebook/WebDriverAgent/issues
The click logic has recently been slightly changed there.
