### ISSUE TITLE
iOS send_keys sometimes does not work

### ISSUE THREAD

**Issue by eduardoreynoso** [appium/appium#8573]
## The problem
I have several tests written in Python running in a simulator that input a search term in a text field, they all use the same method:
`self.driver.find_element_by_name('Address or landmark').click()
self.driver.find_element_by_name('Address or landmark').send_keys(search_term)`

Sometimes it does not work and the appium server logs shows a `200` response for that request.
[Appium server log](https://gist.github.com/eduardoreynoso/45b6820e928626b69a20ff598c14add1)

I have tried all `sendKeysStrategy` and still fails.
I also have tried clearing the text field, tapping on it before input of the search term.
The element is present, visible and I can retrieve it with my selector.
I have tried several simulator iOS versions and devices
Keyboard is also visible:

![image](https://cloud.githubusercontent.com/assets/531256/26603643/3064ac98-454d-11e7-9b91-b285b6e7e060.png)

Thank you!

## Environment

* Appium v1.6.4
* macOS Sierra 10.12.4
* Node.js v7.10.0
* Mobile platform/version under test: iOS 10.3
* Real device or emulator/simulator: Simulator iPhone 5s

**Comment by eduardoreynoso** [comment]
I updated to Appium v1.6.5 and still having this issue

**Comment by dpgraham** [comment]
Can you try calling get page source before you calling 'find_element_by_name' to confirm that the element with name `Address or landmark ` is in the XML.

**Comment by eduardoreynoso** [comment]
@dpgraham thanks for the reply, I printed the page source and I am seeing the element:
`<XCUIElementTypeTextField type="XCUIElementTypeTextField" value="Address or landmark" name="Address or landmark" label="Address or landmark" enabled="true" x="5" y="26" width="292" height="47"/>`

**Comment by dpgraham** [comment]
I'd have to see logs where it's failing.

It looks like in your server logs you provided, the sendKeys is successful.

**Comment by eduardoreynoso** [comment]
@dpgraham That's the issue, the server returns a 200 for that action, I can add a screen video of that action taken, including the server log and the simulator screen if it helps, but it will just show that the server responded 200 and no input was sent to the textfield.
It is a very weird issue, if I run the test case 3 times one of them might fail.
Any other ideas?
Thank you for taking the time to try and help me, I appreciate it!

**Comment by nairouz12** [comment]
Any update on this issue please? I'm facing the same issue, sometimes the send_keys does not work for iOS
appium: 1.6.4
MAC OS Sierra: 10.12.4
Node.js: 7.2.1
iOS 10.2

**Comment by nairouz12** [comment]
This is blocking my test.
can someone help on this please?

**Comment by neXussT** [comment]
I have also encountered this issue with a live iPhone 6 v10.3.2, Appium v1.6.4 on a Mac. I have used my script with Android without issue, but on iOS, Appium gives the error "WebDriverException...parameters are incorrect. we wanted {required:[value]} and you sent....". I have also tried setting the capability sendKeysStrategy=setValue, but to no avail. This is now blocking my progress in this area.

**Comment by mykola-mokhnach** [comment]
@neXussT Your issue is different. Update Appium to 1.6.6-beta or downgrade selenium lib to solve it

**Comment by neXussT** [comment]
Thanks @mykola-mokhnach . Anyways found element.set_value() fixed it for me on my version.

**Comment by eduardoreynoso** [comment]
Any updates on this? Can we get any developer or contributor to take a look please?
Thanks!

**Comment by dpgraham** [comment]
@eduardoreynoso I don't think we'll be able to reproduce this on our side. Are you able to send us an example .app with an Appium script that reproduces this issue?

**Comment by eduardoreynoso** [comment]
@dpgraham Let me talk to my team, that might be quite hard. But maybe we can just grab that text field and put in an sample app and I can write a simple script for that. Thanks for the quick reply, let me see what I can do.

**Comment by nairouz12** [comment]
any update please?

**Comment by nairouz12** [comment]
@dpgraham  can we use another function instead of "send_keys"?
"send_keys" is really failing my test

**Comment by dpgraham** [comment]
@nairouz12 There's no update on this. If I can get an example that re-produces this issue then I can work on a fix. And no there's no alternative to 'send_keys' unfortunately.

**Comment by eduardoreynoso** [comment]
Im still working with my devs to see if we can get a simplified app but we are very busy with new releases. @nairouz12 can you share any specifics on what type of textfield you are seeing this issue? For my app, it happens with a textfield that has autocomplete for google maps addresses, dont know if it might be related but thats the only difference that I can point out from other textfields in my app and I have only seen this issue with that textfield input.

**Comment by nairouz12** [comment]
@eduardoreynoso in my case it is a PIN entry field that needs to be filled in to log into the application, it is a "XCUIElementTypeTextField".
And thid is what I'm doing:
```
textfield = $driver.find_element_by_id(field_id) # field_id is the technical id of that XCUIElementTypeTextField
textfield.send_keys(text) #text: is the what I'm sending as a PIN code
```

**Comment by eduardoreynoso** [comment]
@nairouz12 does it always fail? For me its an intermittent issue. Are you running on emulator? what device/os version? Im trying to find any pattern

**Comment by eduardoreynoso** [comment]
@dpgraham hey Dan, I created a repo with a simple script and I included our latest public version of our app, the script is really simple it tries to set the text on the textfield and breaks into debugger if it cant, tries 100 times, hopefully that would be enough to reproduce, Ive ran it on my machine and around the 67th time I can reproduce, let me know if you need more info. thanks!
https://github.com/eduardoreynoso/iOSAppiumIssue8573/

**Comment by dpgraham** [comment]
Thanks @eduardoreynoso, I'll look at it right now.

**Comment by dpgraham** [comment]
Thanks @eduardoreynoso I can reproduce it now. Hopefully I can figure out the problem. It's tough to tell because it doesn't throw any errors, it just fails silently.

**Comment by dpgraham** [comment]
Looking at the logs now. Normally the call to get the value shows this in the log:

```
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"215 West Washington st\",\n  \"sessionId\" : \"51FB5199-D833-4A9E-BF40-EA365CE55815\",\n  \"status\" : 0\n}"
```

But when it fails it shows this:

```
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"Address or landmark\",\n  \"sessionId\" : \"DEE09547-AB6D-4E67-B216-E2E40496C8BC\",\n  \"status\" : 0\n}"
```

**Comment by eduardoreynoso** [comment]
Right, which means that it still has the place holder text. If you see the previous send_keys call in the server it actually says 200. Why would the server tell you that it succeeded to send the keys if the text never changed?

**Comment by dpgraham** [comment]
It's either a bug and it's not successfully sending the keys, or the app is clearing the keys in between the sendKeys and the getText

**Comment by eduardoreynoso** [comment]
I double checked with my devs the criteria to clear text on that field and unless you press the (x) button to clear, we never clear the text. I believe its a bug in appium, what else can we do to narrow it down?

**Comment by dpgraham** [comment]
It may also be a bug in XCUI (the underlying Apple framework). If that's the case then we probably won't be able to fix it.

**Comment by saikrishna321** [comment]
hey I see u finding the locator by name which has been deprecated long back, can you pls locate the same element as accessibility n check it should work

**Comment by nairouz12** [comment]
@eduardoreynoso  were you able to get it fixed?

**Comment by eduardoreynoso** [comment]
@nairouz12 no luck, I strongly believe that its an issue on XCUI Test framework and not related to appium. My workaround is to throw an exception when I cannot update the text and re try the test case that got that exception, sometimes takes several retries but its the only way that we can get a 100% tests passing and not hide other bugs.

**Comment by lanzelot1989** [comment]
We face this problem when using the following combination of tools:
Appium 1.8.1-beta1
Node 9.11.0
XCode 9.3.1

**Comment by mykola-mokhnach** [comment]
This is XCTest issue. There is nothing that can be done on Appium side
