### ISSUE TITLE
Appium 1.6.5 (iOS) Failed to fetch hit point for Button and setup closes

### ISSUE THREAD

**Issue by vjmaiky** [appium/appium#8575]
## The problem

Basically setup stops when i-m doing certain actions

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5, 1.6.4
* Last Appium version that did not exhibit the issue (if applicable): 1.6.3
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe): 7.4.0
* Mobile platform/version under test: iOS 10.3.2
* Real device or emulator/simulator: iPhone 6+
* Appium CLI or Appium.app|exe:

## Details
Application is closed and Xcuitest is throwing "Failed to fetch hit point for Button". It is not always reproducible...

## Link to Appium logs
https://gist.github.com/vjmaiky/52f21c4c152a4d3aaf02860279bc3367

## Code To Reproduce Issue [ Good To Have ]

I-m trying to forward an e-mail:

EmailReadView.click_ActionSheet();
public static void click_ActionSheet() {
		click(By.id(MORE_OPTIONS_BUTTON_NAME), true);
	}

When i try to select forward setup closes. It is not an app bug (tested many times on manual; also i started to face this issue from 1.6.4 but on 1.6.5 is frequent). On 1.6.3 i could not reproduce it.

EmailReadView.click_Weiterleiten();
	public static void click_Weiterleiten() {
		if (Properties.IOS_VERSION.contains("10")) {
			click(ANSWER_ONE_WEITERLEITEN_NAME, ELEMENT_TYPE_XCUIElementTypeButton, true);
		} else {
			click(ANSWER_ONE_WEITERLEITEN_NAME, ELEMENT_TYPE_UIABUTTON, true);
		}
	}

**Comment by mykola-mokhnach** [comment]
It's known WDA/XCTest issue. See https://github.com/facebook/WebDriverAgent/issues/372 for the reference. Try to replace xpath locator with something else to workaround it.

**Comment by vjmaiky** [comment]
but i`m using ID and an attribute (type); so no xpaths used.

**Comment by mykola-mokhnach** [comment]
both calls (visibility and click) use **hitPoint** XCTest call, which sometimes randomly fails and causes unexpected freezes. You may report the problem directly to WDA issue tracker, but it has nothing to do with Appium in any case.

**Comment by vjmaiky** [comment]
ok i understood; thanks
