### ISSUE TITLE
Unable to launch WebDriverAgentRunner in iPhone real device with appium 1.6.5

### ISSUE THREAD

**Issue by PavithraNavaneeth** [appium/appium#8576]
Unable to launch WebDriverAgentRunner in iPhone real device with appium 1.6.5

## Environment
Appium - 1.6.5/5.0.0-BETA8 JAVA client
MAC - 10.11.6
Xcode - 8.2
IOS - 10.1 - Iphone Real Device (which is been provisioned)

## Details
capability has been set with automationName - xcuitest. Device has been provisioned. WebDriverAgent xcode project has been signed with our developer certificate and with wildcard provisioing profile. 

When we try to launch the webdirver agent runner through xcode (with product-Test), app get launched in iphone however it just hangs and  Xcode throws below error:
dyld: Library not loaded: @rpath/XCTest.framework/XCTest
  Referenced from: /var/containers/Bundle/Application/98103A32-3798-4511-8077-C8D9BF8F7F7B/WebDriverAgentRunner-Runner.app/XCTRunner
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/98103A32-3798-4511-8077-C8D9BF8F7F7B/WebDriverAgentRunner-Runner.app/Frameworks/XCTest.framework/XCTest: code signing blocked mmap() of '/private/var/containers/Bundle/Application/98103A32-3798-4511-8077-C8D9BF8F7F7B/WebDriverAgentRunner-Runner.app/Frameworks/XCTest.framework/XCTest'
(lldb) 

## Appium logs while running the tests:
Xcode error for appium 1.6.5 (MAC 10.11/Xcode 8.2/iOS 10.1)
 
[debug] [XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=8e82ea984d9807b78b7e2b2f03c891bce1d5b039 -configuration Debug IPHONEOS_DEPLOYMENT_TARGET=10.1' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[debug] [XCUITest] Output from xcodebuild will not be logged
[debug] [XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[debug] [XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [XCUITest] Log file for xcodebuild test: /Users/jameschen/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/7885D9B7-B153-4F41-8521-056045661F42/Session-WebDriverAgentRunner-2017-05-31_154348-W7qBWm.log
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[Xcode] 2017-05-31 15:43:53.323 xcodebuild[58928:615843]  DTDeviceKit: Could not start house arrest service for app identifier com.apple.test.WebDriverAgentRunner-Runner [Error Domain=com.apple.dtdevicekit Code=-402653093 "Too many instances of this service are already running." UserInfo={NSLocalizedFailureReason=Too many instances of this service are already running., com.apple.dtdevicekit.stacktrace=(
[Xcode] 0   DTDeviceKitBase                     0x000000010af7837b DTDKCreateNSError + 113
[Xcode] 1   DTDeviceKitBase                     0x000000010af78ab9 DTDK_AMDErrorToNSError + 791
[Xcode] 2   DTDeviceKitBase                     0x000000010af8a2a5 __70-[DTDKRemoteDeviceConnection startHouseArrestServiceForAppIdentifier:]_block_invoke + 100
[Xcode] 3   DTDeviceKitBase                     0x000000010af89181 __48-[DTDKRemoteDeviceConnection futureWithSession:]_block_invoke_4 + 22
[Xcode] 4   DTDeviceKitBase                     0x000000010af7b2c7 __DTDKExecuteInSession_block_invoke + 38
[Xcode] 5   DTDeviceKitBase                     0x000000010af7a8f0 __DTDKExecuteWithConnection_block_invoke_2 + 477
[Xcode] 6   DTDeviceKitBase                     0x000000010af7a6ec __DTDKExecuteWithConnection_block_invoke + 107
[Xcode] 7   libdispatch.dylib                   0x00007fff8dfe840b _dispatch_client_callout + 8
[Xcode] 8   libdispatch.dylib                   0x00007fff8dfe99f2 _dispatch_barrier_sync_f_invoke + 74
[Xcode] 9   DVTFoundation                       0x00000001020f996b DVTDispatchBarrierSync + 206
[Xcode] 10  DVTFoundation                       0x00000001020d6317 -[DVTDispatchLock performLockedBlock:] + 116
[Xcode] 11  DTDeviceKitBase                     0x000000010af7a5f6 DTDKExecuteWithConnection + 223
[Xcode] 12  DTDeviceKitBase                     0x000000010af7b251 DTDKExecuteInSession + 121
[Xcode] 13  DTDeviceKitBase                     0x000000010af890b8 __48-[DTDKRemoteDeviceConnection futureWithSession:]_block_invoke_3 + 117
[Xcode] 14  DVTFoundation                       0x00000001020f8cc7 __DVTDispatchAsync_block_invoke + 827
[Xcode] 15  libdispatch.dylib                   0x00007fff8dff393d _dispatch_call_block_and_release + 12
[Xcode] 16  libdispatch.dylib                   0x00007fff8dfe840b _dispatch_client_callout + 8
[Xcode] 17  libdispatch.dylib                   0x00007fff8dffabd7 _dispatch_async_redirect_invoke + 1733
[Xcode] 18  libdispatch.dylib                   0x00007fff8dfe840b _dispatch_client_callout + 8
[Xcode] 19  libdispatch.dylib                   0x00007fff8dfec29b _dispatch_root_queue_drain + 1890
[Xcode] 20  libdispatch.dylib                   0x00007fff8dfebb00 _dispatch_worker_thread3 + 91
[Xcode] 21  libsystem_pthread.dylib             0x00007fff897104de _pthread_wqthread + 1129
[Xcode] 22  libsystem_pthread.dylib             0x00007fff8970e341 start_wqthread + 13
[Xcode] ), NSLocalizedRecoverySuggestion=Too many instances of this service are already running., NSLocalizedDescription=Too many instances of this service are already running.}]
[Xcode] 
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[Xcode] 2017-05-31 15:43:53.727 xcodebuild[58928:615812] Error Domain=IDETestOperationsObserverErrorDomain Code=5 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
[Xcode] 
[Xcode] ** TEST EXECUTE FAILED **
[Xcode] 
[Xcode] 
[Xcode] dyld: Library not loaded: @rpath/XCTest.framework/XCTest
[Xcode]   Referenced from: /var/containers/Bundle/Application/7CD73367-7635-46C2-B162-D8E7C3B2D674/WebDriverAgentRunner-Runner.app/XCTRunner
[Xcode]   Reason: no suitable image found.  Did find:
[Xcode]                /private/var/containers/Bundle/Application/7CD73367-7635-46C2-B162-D8E7C3B2D674/WebDriverAgentRunner-Runner.app/Frameworks/XCTest.framework/XCTest: code signing blocked mmap() of '/private/var/containers/Bundle/Application/7CD73367-7635-46C2-B162-D8E7C3B2D674/WebDriverAgentRunner-Runner.app/Frameworks/XCTest.framework/XCTest'
[Xcode] 
[XCUITest] xcodebuild exited with code '65' and signal 'null'
[debug] [BaseDriver] Event 'wdaStartFailed' logged at 1496209433743 (15:43:53 GMT+1000 (AEST))
[debug] [XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65

**Comment by Strybushnyi** [comment]
Try to sign WebDriverAgent with your developer's certificate and add following capabilities:
"bootstrapPath": "/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent",
"agentPath": "/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj"

**Comment by mykola-mokhnach** [comment]
This is signing issue. Please follow https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md to set up automation gor real device.
Closed as duplicate
