### ISSUE TITLE
allowTouchIdEnroll:true doesn't have any effect

### ISSUE THREAD

**Issue by zerdos** [appium/appium#8578]
## The problem

I set the allowTouchIdEnroll: true, but the emulator and the app starts without Touch Id enabled

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5-beta
* Last Appium version that did not exhibit the issue (if applicable): never worked (new feature)
* Desktop OS/version used to run Appium: MacOS Sierra 10.12.5
* Node.js version (unless using Appium.app|exe): 7.10
* Mobile platform/version under test: iOS 10.3
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: both (in the appium app I changed the used appium dependency to 1.6.5-beta as well

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
https://gist.github.com/zerdos/5cac399b27e2e204c575ad1f8f05883d

**Comment by mykola-mokhnach** [comment]
As far as I remember one has to add Terminal to the list of apps, that can access accessibility in system prefs. Right @dpgraham ?

**Comment by dpgraham** [comment]
That's correct @mykola-mokhnach. @zerdos Can you go to System Preferences > Security & Privacy > Accesibility and then add 'Terminal' to the list on the right pane and let me know if that fixes it.

We'll make an issue of this to add that instruction to the documentation and we should also add a notification in the Server Logs when a client uses touchIDEnroll to say something to the effect of

`Using touchIdEnrollment. Ensure that under System Preferences > Security & Privacy > Accessibility, Terminal is one of the listed apps`

**Comment by zerdos** [comment]
No, haven't solved my problem. :(

**Comment by dpgraham** [comment]
* When you run your test, can you open the file menu in the Simulator to see if 'Toggle Enrolled State' is set?

![toggle-enrolled-state](https://cloud.githubusercontent.com/assets/852574/26656347/8238b3cc-4613-11e7-943f-8c73d4bf1247.png)

* Are you calling `performTouchId`? `allowTouchId` only enrolls the Simulator to use touch-id, the performTouchId method applies a touch (it takes a boolean that when true applies a successful touch and when false applies an unsuccessful touch)

**Comment by zerdos** [comment]
No, the option isn't set in the menu.

<img width="929" alt="screen shot 2017-06-14 at 14 53 27" src="https://user-images.githubusercontent.com/1433047/27135755-4dba44d6-5111-11e7-9a60-f5bb9721215b.png">

**Comment by dpgraham** [comment]
Okay, thanks @zerdos I'll have a look at this.

**Comment by dpgraham** [comment]
Hi @zerdos, I'm unable to reproduce this on my end. I've run some touchId tests and it seems to be working and I have the same environment as you (same OS version, node version, etc...)

Can you double check that Terminal is added to accessibility? `System Preferences > Security & Privacy > Accessibility` 

It should look like this:

![screen shot 2017-06-14 at 10 23 59 am](https://user-images.githubusercontent.com/852574/27145798-d78801b0-50eb-11e7-9621-4dfda604d673.png)

Also, have you tried running your app inside of Appium Desktop (https://www.github.com/appium/appium-desktop/releases/latest)? You can run ad-hoc Sessions from inside of that.

**Comment by zerdos** [comment]
I tried with the appium app as well.
Also just tried with a colleague's mac - and it didn't work there either.
The simulator and the test script opens, but the without enrolled touch id

**Comment by dpgraham** [comment]
Do your colleagues have the accessibility preference set?

**Comment by Iryna-Pavlenko** [comment]
+1. Having same issue with set 'allowTouchIdEnroll': true - Simulator and test scripts started, but without enrolled touch id, Simulator>Hardware>Touch ID>Toggle Enrolled State is not set. 

Tried with appium v1.6.4/node v.7.7.1, then updated to appium v.1.6.5/node 8.1.1 - it did not work.

Appium version: v1.6.4, v1.6.5
Node version: v.7.7.1, v.8.1.1
Desktop OS/version used to run Appium: MacOS Sierra 10.12.3
Mobile platform/version under test: iOS 10.1, iOS 10.3
Real device or emulator/simulator: iPhone6 Simulator

'Terminal' accessibility set under System Preferences > Security & Privacy > Accessibility.

Note, running automation tests on java-client v.5.0.0-BETA8.

**Comment by zerdos** [comment]
@dpgraham yes, the terminal was added in the accessibility as well.

**Comment by dpgraham** [comment]
@zerdos I've tried the same capabilities as the ones you provided and I can now reproduce the issue. I'll look into this now and post updates on this issue. Thanks for your help on this!

**Comment by dpgraham** [comment]
@zerdos I have a pull request for this. The issue is that in order to use touchId you have to call the client method which toggles enrollment (which isn't yet part of Java).

The PR makes it so that touchId enrollment is enabled by default when the iOS Simulator is started.

As soon as this PR comes in and the package is published you and @Iryna-Pavlenko can reinstall the latest Appium beta version and the change will take affect.

I also added documentation that explains touchID and how to use it in more detail:

https://github.com/appium/appium-xcuitest-driver/blob/a15a20163e6b3f206f4f2f0f95b53b5c560a674c/docs/touch-id.md

**Comment by dpgraham** [comment]
The change has been published. If you install the latest beta v1.6.6-beta.2 (make sure to uninstall and then reinstall it) the changes will take affect and it should work.

If you still have problems, let me know and I'll re-open the ticket
