### ISSUE TITLE
Check for alerts during XCUITest-based webview/safari tests

### ISSUE THREAD

**Issue by imurchie** [appium/appium#8582]
## The problem

In `appium-ios-driver`, while executing in a webview context, we check to make sure that an alert is not blocking things.

Look at that logic and try to recreate in `appium-xcuitest-driver`.

**Comment by imurchie** [comment]
Two places: 
1. `this.closeAlertBeforeTest()` is called while finding contexts. It returns `true` if it closed alert, `false` if there was no alert to close.
2. `this.checkForAlert()` is called while waiting for an atom. It returns `true` if there is one.

**Comment by imurchie** [comment]
The first does not work easily, since the initial opening of the url is happening in WDA during session creation.

**Comment by imurchie** [comment]
With the current logic, even in `appium-ios-driver`, we cannot handle a popup that occurs while setting the url.

**Comment by ireneyu1** [comment]
Anyone know when we can expect a fix for this issue? Or are there any current work arounds?

**Comment by Hbouaz** [comment]
Has this been fixed?

**Comment by markdon** [comment]
I'm assuming this relates to interacting with these alerts? Appium stops responding when this appears.
[Imgur](https://i.imgur.com/rxtrt1o.png)

I was hoping that the people in [this SO question](https://stackoverflow.com/questions/44824289/ios-native-alert) figured it out but since there's no response from Appium, it's not going to work. I'm using webdriverio.

**Comment by donamani** [comment]
Did it got fixed? Please help

**Comment by mykola-mokhnach** [comment]
Please try appium@beta. The issue should be addressed there

**Comment by imurchie** [comment]
With `appium-xcuitest-driver@3.17.0` this should be fixed.

**Comment by ishanm120** [comment]
@imurchie 
I tired with latest version of appium 1.17 and also with latest beta version v1.17.0-beta.1

but didn't get success.

**Comment by ishanm120** [comment]
> Please try appium@beta. The issue should be addressed there

tried with latest beta version v1.17.0-beta.1 , but no success.

**Comment by imurchie** [comment]
@ishanm120 Feel free to provide the logs (as a link to a [gist](https://gist.github.com)). Otherwise there is little to nothing that can be said.

**Comment by ishanm120** [comment]
> @ishanm120 Feel free to provide the logs (as a link to a [gist](https://gist.github.com)). Otherwise there is little to nothing that can be said.

https://gist.github.com/ishanm120/b19ca0c67e0cd46fe3dfd059e0ec90db

**Comment by ishanm120** [comment]
@imurchie 
Can you please check and update?

**Comment by imurchie** [comment]
Can you post a screenshot of the alert?

**Comment by ishanm120** [comment]
> Can you post a screenshot of the alert?
> 
> Also, for reproducing, what is triggering the alert?

I have provided all details here :
https://github.com/appium/appium/issues/14091
