### ISSUE TITLE
come up with a concrete plan for new docs / site

### ISSUE THREAD

**Issue by jlipps** [appium/appium#8586]
Acceptance criteria:

- [x] decision about overall format (e.g. look like bluebird docs)
- [x] get candidate template
- [x] get candidate markdown -> template renderer
- [ ] come up with desired topic list / nav structure
- [x] figure out how we want to convey API information
- [x] figure out how we want to show differently languaged code snippets
- [x] figure out how we are going to host docs (part of appium.io gh-pages?)

**Comment by imurchie** [comment]
I've been using https://www.netlify.com/open-source/ for things. Easy as github-pages. Initially I did it because you can use https on custom domains. But the rest is nice too, and free for open source projects.

**Comment by jlipps** [comment]
exploring ESDocs as a candidate in #8947

**Comment by dpgraham** [comment]
Here's a staging site https://dpgraham.github.io/appium-docs/

**Comment by dpgraham** [comment]
So do we agree that API info will be done on a separate ESDocs site and that will be a separate project from publishing a new Appium site?

**Comment by dpgraham** [comment]
For the template I think we can use the default one but add our own styling to it.
