### ISSUE TITLE
Appium opens the app but no controls appear

### ISSUE THREAD

**Issue by sheldonyon** [appium/appium#8587]
## The problem

When appium runs it finds the package and then the activity but fails to find the button in the app. No controls are loaded by the app and once appium has been run the app is no longer fuctional and must the redeployed to work again.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Last Appium version that did not exhibit the issue (if applicable): n/a
* Desktop OS/version used to run Appium: windows 10
* Node.js version (unless using Appium.app|exe): latest
* Mobile platform/version under test: Android emulator
* Real device or emulator/simulator: emulator 
* Appium CLI or Appium.app|exe: Appium app

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
[Appium] Welcome to Appium v1.6.4
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"Android","platformVersion":"7.0","deviceName":"emulator","appPackage":"Tools.Tap.Android.TestApplication.Tools.Tap.Android.TestApplication","appActivity":"md5f3421630fdd297a543c9f06ea04c3aa8.MainActivity"}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformName":"Android","platformVersion":"7.0","deviceName":"emulator","appPackage":"Tools.Tap.Android.TestApplication.Tools.Tap.Android.TestApplication","appActivity":"md5f3421630fdd297a543c9f06ea04c3aa8.MainActivity"},null,null,null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1496256900510 (11:55:00 GMT-0700 (Pacific Daylight Time))
[Appium] Creating new AndroidDriver (v1.17.1) session
[Appium] Capabilities:
[Appium]   platformName: 'Android'
[Appium]   platformVersion: '7.0'
[Appium]   deviceName: 'emulator'
[Appium]   appPackage: 'Tools.Tap.Android.TestApplication.Tools.Tap.Android.TestApplication'
[Appium]   appActivity: 'md5f3421630fdd297a543c9f06ea04c3aa8.MainActivity'
[AndroidDriver] AndroidDriver version: 1.17.1
[BaseDriver] Session created with session id: 11ec0135-ccfb-4d3c-955b-74238e537087
[AndroidDriver] Getting Java version
[AndroidDriver] Java version is: 1.8.0_131
[ADB] Checking whether adb is present
[ADB] Using adb.exe from D:\Android\android-sdk\platform-tools\adb.exe
[AndroidDriver] Retrieving device list
[ADB] Trying to find a connected android device
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[AndroidDriver] Looking for a device with Android '7.0'
[ADB] Setting device id to emulator-5554
[ADB] Getting device platform version
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'D:\Android\android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","getprop","ro.build.version.release"]
[AndroidDriver] Using device: emulator-5554
[ADB] Checking whether adb is present
[ADB] Using adb.exe from D:\Android\android-sdk\platform-tools\adb.exe
[ADB] Setting device id to emulator-5554
[AndroidDriver] App file was not listed, instead we're going to run Tools.Tap.Android.TestApplication.Tools.Tap.Android.TestApplication directly on the device
[AndroidDriver] Checking whether package is present on the device
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'D:\Android\android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","pm","list","packages","Tools.Tap.Android.TestApplication.Tools.Tap.Android.TestApplication"]
[AndroidDriver] Starting Android session
[ADB] Running 'D:\Android\android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","wait-for-device"]
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'D:\Android\android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","echo","ping"]
[Logcat] Starting logcat capture
[AndroidDriver] Pushing settings apk to device...
[ADB] Getting install status for io.appium.settings
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'D:\Android\android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","pm","list","packages","io.appium.settings"]
[ADB] App is installed
[ADB] Getting package info for io.appium.settings
[ADB] Getting connected devices...
[ADB] Checking whether aapt is present
[ADB] Using aapt.exe from D:\Android\android-sdk\build-tools\25.0.2\aapt.exe
[ADB] 1 device(s) connected
[ADB] Running 'D:\Android\android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","dumpsys","package","io.appium.settings"]
[ADB] Cannot read version codes of C:\Users\sheldony\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\io.appium.settings\app\build\outputs\apk\settings_apk-debug.apk and/or io.appium.settings. Assuming correct app version is already installed
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'D:\Android\android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","getprop","ro.build.version.sdk"]
[ADB] Device API level: 24
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'D:\Android\android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","dumpsys","package","io.appium.settings"]
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'D:\Android\android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","pm","dump","io.appium.settings"]
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'D:\Android\android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","pm","grant","io.appium.settings","android.permission.WRITE_SETTINGS",";","pm","grant","io.appium.settings","android.permission.ACCESS_MOCK_LOCATION",";"]
[ADB] Running 'D:\Android\android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","pm","grant","io.appium.settings","android.permission.WRITE_SETTINGS",";","pm","grant","io.appium.settings","android.permission.ACCESS_MOCK_LOCATION",";"]
[AndroidDriver] Pushing unlock helper app to device...
[ADB] Running 'D:\Android\android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","install","C:\\Users\\sheldony\\AppData\\Local\\Programs\\appium-desktop\\resources\\app\\node_modules\\appium\\node_modules\\appium-unlock\\bin\\unlock_apk-debug.apk"]
[ADB] Running 'D:\Android\android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","install","C:\\Users\\sheldony\\AppData\\Local\\Programs\\appium-desktop\\resources\\app\\node_modules\\appium\\node_modules\\appium-unlock\\bin\\unlock_apk-debug.apk"]
[ADB] Application 'C:\Users\sheldony\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-unlock\bin\unlock_apk-debug.apk' already installed. Continuing.
[ADB] Device API level: 24
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'D:\Android\android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","appops","set","io.appium.settings","android:mock_location","allow"]
[ADB] Getting device platform version
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'D:\Android\android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","getprop","ro.build.version.release"]
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'D:\Android\android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","wm","size"]
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'D:\Android\android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","getprop","ro.product.model"]
[ADB] Current device property 'ro.product.model': Android SDK built for x86_64
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'D:\Android\android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","getprop","ro.product.manufacturer"]
[ADB] Current device property 'ro.product.manufacturer': unknown
[AndroidDriver] No app sent in, not parsing package/activity
[AndroidDriver] No app capability. Assuming it is already on the device
[AndroidDriver] Running fast reset (stop and clear)
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'D:\Android\android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","am","force-stop","Tools.Tap.Android.TestApplication.Tools.Tap.Android.TestApplication"]
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'D:\Android\android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","pm","clear","Tools.Tap.Android.TestApplication.Tools.Tap.Android.TestApplication"]
[AndroidBootstrap] Watching for bootstrap disconnect
[ADB] Forwarding system: 4724 to device: 4724
[ADB] Running 'D:\Android\android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","forward","tcp:4724","tcp:4724"]
[UiAutomator] Starting UiAutomator
[UiAutomator] Moving to state 'starting'
[UiAutomator] Parsing uiautomator jar
[UiAutomator] Found jar name: 'AppiumBootstrap.jar'
[ADB] Running 'D:\Android\android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","push","C:\\Users\\sheldony\\AppData\\Local\\Programs\\appium-desktop\\resources\\app\\node_modules\\appium\\node_modules\\appium-android-bootstrap\\bootstrap\\bin\\AppiumBootstrap.jar","/data/local/tmp/"]
[ADB] Attempting to kill all uiautomator processes
[ADB] Getting all processes with uiautomator
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'D:\Android\android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","ps"]
[ADB] Attempting to kill process 16406
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'D:\Android\android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","kill",16406]
[UiAutomator] Starting UIAutomator
[ADB] Creating ADB subprocess with args: ["-P",5037,"-s","emulator-5554","shell","uiautomator","runtest","AppiumBootstrap.jar","-c","io.appium.android.bootstrap.Bootstrap","-e","pkg","Tools.Tap.Android.TestApplication.Tools.Tap.Android.TestApplication","-e","disableAndroidWatchers",false,"-e","acceptSslCerts",false]
[UiAutomator] UiAutomator exited unexpectedly with code 4294967183, signal null
[UiAutomator] Moving to state 'stopped'
[AndroidDriver] Shutting down Android driver
[Appium] Closing session, cause was 'UiAUtomator shut down unexpectedly'
[Appium] Removing session eb106436-3777-40d0-97f2-6df87a24ea32 from our master session list
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'D:\Android\android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","am","force-stop","Tools.Tap.Android.TestApplication.Tools.Tap.Android.TestApplication"]
[UiAutomator] Moving to state 'online'
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Loading json...
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Registered crash watchers.
[AndroidBootstrap] Android bootstrap socket is now connected
[ADB] Getting connected devices...
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Client connected
[ADB] 1 device(s) connected
[ADB] Running 'D:\Android\android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","dumpsys","window"]
[AndroidDriver] Screen already unlocked, doing nothing
[ADB] Device API level: 24
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'D:\Android\android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","am","start","-W","-n","Tools.Tap.Android.TestApplication.Tools.Tap.Android.TestApplication/md5f3421630fdd297a543c9f06ea04c3aa8.MainActivity","-S"]
[ADB] Pressing the HOME button
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'D:\Android\android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","input","keyevent",3]
[AndroidBootstrap] Cannot shut down Android bootstrap; it has already shut down
[Logcat] Stopping logcat capture
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'D:\Android\android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","am","force-stop","io.appium.unlock"]
[AndroidDriver] Not cleaning generated files. Add `clearSystemFiles` capability if wanted.
[Appium] New AndroidDriver session created successfully, session 11ec0135-ccfb-4d3c-955b-74238e537087 added to master session list
[BaseDriver] Event 'newSessionStarted' logged at 1496256926203 (11:55:26 GMT-0700 (Pacific Daylight Time))
[MJSONWP] Responding to client with driver.createSession() result: {"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"platformName":"Android","platformVersion":"7.0","deviceName":"emulator","appPackage":"Tools.Tap.Android.TestApplication.Tools.Tap.Android.TestApplication","appActivity":"md5f3421630fdd297a543c9f06ea04c3aa8.MainActivity"},"platformName":"Android","platformVersion":"7.0","deviceName":"emulator-5554","appPackage":"Tools.Tap.Android.TestApplication.Tools.Tap.Android.TestApplication","appActivity":"md5f3421630fdd297a543c9f06ea04c3aa8.MainActivity","deviceUDID":"emulator-5554","deviceScreenSize":"1080x1920","deviceModel":"Android SDK built for x86_64","deviceManufacturer":"unknown"}
[HTTP] <-- POST /wd/hub/session 200 25697 ms - 862 
[HTTP] --> POST /wd/hub/session/11ec0135-ccfb-4d3c-955b-74238e537087/timeouts {"type":"implicit","ms":8000}
[MJSONWP] Calling AppiumDriver.timeouts() with args: ["implicit",8000,"11ec0135-ccfb-4d3c-955b-74238e537087"]
[BaseDriver] Set implicit wait to 8000ms
[MJSONWP] Responding to client with driver.timeouts() result: null
[HTTP] <-- POST /wd/hub/session/11ec0135-ccfb-4d3c-955b-74238e537087/timeouts 200 2 ms - 76 
[HTTP] --> POST /wd/hub/session/11ec0135-ccfb-4d3c-955b-74238e537087/element {"using":"id","value":"StopAutomationButton"}
[MJSONWP] Calling AppiumDriver.findElement() with args: ["id","StopAutomationButton","11ec0135-ccfb-4d3c-955b-74238e537087"]
[BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[BaseDriver] Waiting up to 8000 ms for condition
[AndroidBootstrap] Sending command to android: {"cmd":"action","action":"find","params":{"strategy":"id","selector":"StopAutomationButton","context":"","multiple":false}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"id","selector":"StopAutomationButton","context":"","multiple":false}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: find
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding 'StopAutomationButton' using 'ID' with the contextId: '' multiple: false
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[INSTANCE=0, RESOURCE_ID=Tools.Tap.Android.TestApplication.Tools.Tap.Android.TestApplication:id/StopAutomationButton]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[INSTANCE=0, RESOURCE_ID=StopAutomationButton]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[DESCRIPTION=StopAutomationButton, INSTANCE=0]
[AndroidBootstrap] Emitting alert message...
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Emitting system alert message
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Failed to locate element. Clearing Accessibility cache and retrying.
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding 'StopAutomationButton' using 'ID' with the contextId: '' multiple: false
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[INSTANCE=0, RESOURCE_ID=Tools.Tap.Android.TestApplication.Tools.Tap.Android.TestApplication:id/StopAutomationButton]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[INSTANCE=0, RESOURCE_ID=android:id/StopAutomationButton]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[INSTANCE=0, RESOURCE_ID=StopAutomationButton]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[DESCRIPTION=StopAutomationButton, INSTANCE=0]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":7,"value":"No element found"}
[AndroidBootstrap] Received command result from bootstrap
[HTTP] <-- POST /wd/hub/session/11ec0135-ccfb-4d3c-955b-74238e537087/element 500 50153 ms - 164 

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by sheldonyon** [comment]
DesiredCapabilities cap = new DesiredCapabilities();
            cap.SetCapability("platformName", "android");
            cap.SetCapability("platformVersion", "7.0");
            cap.SetCapability("deviceName", "emulator");
            cap.SetCapability("appPackage", "Tools.Tap.Android.TestApplication.Tools.Tap.Android.TestApplication");
            cap.SetCapability("appActivity", "md5f3421630fdd297a543c9f06ea04c3aa8.MainActivity");

**Comment by dpgraham** [comment]
The locator strategy + selector that you're using isn't finding the element. I recommend calling `getPageSource` prior to calling find element so you can inspect the XML and come up with a locator strategy.

I also recommend using https://github.com/appium/appium-desktop/releases/latest. It's an Appium UI that you can use to inspect your app's source.

**Comment by sheldonyon** [comment]
I found the problem Appium by default resets the app under test for some reason this renders the app unusable the fix is to add cap.SetCapability("noReset", "true"); to your Capabilities .
