### ISSUE TITLE
Get device status FALSE

### ISSUE THREAD

**Issue by lehungcuong** [appium/appium#8590]
## The problem

Im running parallel on 2 devices. but after some cases (about 15-20 cases), it cannot get device status (1 device), the other still running.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Last Appium version that did not exhibit the issue (if applicable): 1.5.0
* Desktop OS/version used to run Appium: Mac 10.12.5
* Node.js version (unless using Appium.app|exe): 7.0
* Mobile platform/version under test: 5.1.1
* Real device or emulator/simulator: Samsung Galaxy Note 3 Neo, HTC One
* Appium CLI or Appium.app|exe: CLI

## Details

Im running parallel on 2 devices. but after some cases (about 15-20 cases), it cannot get device status (1 device), the other still running.

## Link to Appium logs

* Setup Test Class [android.SettingTest] on thread [13]
- Get available device
getAvailableDevice: Get device status FALSE
getAvailableDevice: Get device status FALSE
- START APPIUM SESSION
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)

**Comment by imurchie** [comment]
Can you provide the logs for the failure? And a little more information? Is the device unresponsive? Or can you just not get the status?

**Comment by lehungcuong** [comment]
My devices have some problems. Its battery is not good. I closed this issue
