### ISSUE TITLE
App doesn't load in android 7.1.1 with appium 1.6.5

### ISSUE THREAD

**Issue by Shahunks** [appium/appium#8591]
App doesn't load, there is always a loading icon in appium desktop when i tried to inspect my app with Android 7.1.1 and appium 1.6.5
looks like there is no errors in log as well 
## Environment

* Appium version (or git revision) that exhibits th
![imageedit_1_5392068803](https://cloud.githubusercontent.com/assets/25055088/26666939/3f9d0d6c-46c0-11e7-8825-5ac45642ef63.gif)
e issue: 1.6.5
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MAC
* Node.js version (unless using Appium.app|exe): 1.6.4
* Mobile platform/version under test: Android 7.1.1
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe:

## Link to Appium logs
https://gist.github.com/Shahunks/0bbc93690e2289ce02b5c349b36a000c

**Comment by Shahunks** [comment]
Even after several refresh, its not loading in Appium desktop, but loaded in Android Emulator

**Comment by priyankshah217** [comment]
What are the capability are u using while initialising driver?

**Comment by Shahunks** [comment]
"platformName": "Android",
"platformVersion": "7.1.1",
"app": "/Users/app/location",
"appactivity": ".name",
"deviceName": "Andriod",
"appiumVersion": "1.6.5",
"apppackage": "com.app.workQC",
"showXcodeLog": true

**Comment by priyankshah217** [comment]
Can u please set automationName as UiAutomator2 and try again.

**Comment by Shahunks** [comment]
if i add that Capability- i get this error [UiAutomator] UiAutomator exited unexpectedly with code 0, signal null

**Comment by mykola-mokhnach** [comment]
Is there any reason to set newCommandTimeout to zero?

**Comment by Shahunks** [comment]
@mykola-mokhnach - i haven't set in the capability. but now sure how its showing in log.

**Comment by Shahunks** [comment]
@mykola-mokhnach - any help on this ?

**Comment by mykola-mokhnach** [comment]
Try to get the exception from adb logcat output. If bootstrap crashes then we need to know why.

**Comment by Shahunks** [comment]
this works fine when i set to Android 6.0

**Comment by Shahunks** [comment]
@mykola-mokhnach here is the logcat - https://gist.github.com/Shahunks/8224c3ef9be9f745121188b0c8dd65bf

**Comment by priyankshah217** [comment]
can u please try with UIAutomator2 as a capability name. and also please provide server logs. I think u are attempting wrong. Android 7.X does not work with old way of instrumentation.

**Comment by Shahunks** [comment]
@priyankshah217 - thank you, it worked after setting the automationName="UiAutomator2"
