### ISSUE TITLE
While swiping calls to element.getLocation().getY() returns same value.

### ISSUE THREAD

**Issue by deepban74** [appium/appium#8596]
## The problem

I am writing a function to scroll to a particular element.  The functions loops and keeps getting the top of the target element and compares it with some value to determine if it has reached a point.
The code runs fine on my device SAMSUNG GALAXY TAB A but the same code returns same value for the call element.getLocation().getY() on another device GALAXY TAB with SPEN
## Environment

* Appium version : Android 6
* 
* Real device or emulator/simulator: Real Device
*

**Comment by mykola-mokhnach** [comment]
It is hardly possible to suggest anything without having detailed problem description, logs/ screenshots, code examples. All people having extrasensory abilities are on vacation now.

**Comment by deepban74** [comment]
while()
{
 targetElementTop = element.getLocation().getY();
targetElementLeft = element.getLocation().getX();
driver.swipe(activeElementLeft, activeElementTop, activeElementLeft+moveBy, activeElementTop, 100);
}
this is a sample code which is written in a loop. the value written by the getlocation function does not change on certain devices,

**Comment by amedvedjev** [comment]
you did not mention what "element" means. if it like
```
@AndroidFindBy(id = "text)
private AndroidElement element;
```
or
```
AndroidElement element;
while() {
element = driver.findElement(....);
....
}
```
-> all will work

if it like:
```
AndroidElement element = driver.findElement(....);
while() {
....
}
```

**-> NOT CORRECT**
