### ISSUE TITLE
Unable to launch the real device(iPhone & iPad) session in Mac machine

### ISSUE THREAD

**Issue by GowriSethu** [appium/appium#8597]
I have been trying to setup the environment in Mac to execute the automation scripts in real device using Appium 1.6.4 version.

Our project is build with Selenium-java.try to executing the scripts using selenium grid.

I have done the environment setup in the Mac machine by following the steps in this link : http://toolsqa.com/mobile-automation/appium/appium-test-on-real-ios-device/

ios_webkit_debug_proxy -c <Connected device UDID>:27753 –d 
When I'm trying to execute the above command in terminal I'm getting the following error :

Could not connect to lockdownd. Exiting.: Permission denied
ss.remove_server_fd(4)
Unable to attach 5d59aeb93f96b07f94a4ac7c1e860c891d9493d9 inspector
Can anyone please help on this? or Is there any better way to done the iOS real device setup in mach machine?

**Comment by imurchie** [comment]
Our documentation is here: https://github.com/appium/appium/blob/master/docs/en/appium-setup/real-devices-ios.md

Is this a Safari or hybrid app? ios-webkit-debug-proxy is only needed for webview support.

**Comment by mykola-mokhnach** [comment]
Try

```bash
sudo chmod 777 /var/db/lockdown
```

Usually permissions to this file are reset if iTunes is executed.

**Comment by GowriSethu** [comment]
@mykola-mokhnach : if I'm executing the command it throws below error : 

     Could not connect to lockdownd. Exiting.: Broken pipe
     ss.remove_server_fd(4)
    Unable to attach 5d59aeb93f96b07f94a4ac7c1e860c891d9493d9 inspector

**Comment by mykola-mokhnach** [comment]
> Error : An unknown server-side error occurred while processing the command. Original error: Sdk '10.3.1' was not in list of simctl sdks (WARNING: The server did not provide any stacktrace information)

This error happens if one provides capabilities for Simulator instead of real device. Make sure your capabilities are correct and you follow the tutorial above.

**Comment by GowriSethu** [comment]
@mykola-mokhnach : Im using the below desired capabilities 
{
           "version":"10.3.1",
	   "maxInstances": 1,
           "platformName":"iOS",
	   "deviceName":"iPhone 7",	   	  	  	 	             	         "UDID":"5D59AEB93F96B07F94A4AC7C1E860C891",
	"bundleId":"****",
	"app":"***.ipa"
           
        }

**Comment by imurchie** [comment]
`UDID` is ignored. Use lower case `udid`.

**Comment by kavithaks** [comment]
@imurchie ,

I am trying to launch native app from real device using 1.6.5 appium.
App is getting installed successfully but not launches and log says "[debug] [XCUITest] Waiting up to 60000ms for WebDriverAgent to start " .. Could you please help me does appium uses web driver agent to launch native mobile app ? or do we have any other configuration for native app alone.

I have set all capabilities correctly .

Getting error at the end as "[MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 70
    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:386:15)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)

**Comment by Amar-Incture** [comment]
@imurchie 

I tried all possible ways to launch the app on iPhone 7 with version 10.3.3 but I am not able to launch as I am getting the same error as discussed by others above. Please find below the capabilities which I have declared:

public void setUp() throws MalformedURLException{
		DesiredCapabilities capabilities = new DesiredCapabilities();
		File app = new File(System.getProperty("user.dir") + File.separator +"app").listFiles()[0];
		capabilities.setCapability("browserName", "Safari");
		capabilities.setCapability("deviceName", "iPhone");
		capabilities.setCapability("udid", "abc123asd");
		capabilities.setCapability("version", "10.3.3");
		capabilities.setCapability("bundleid", "com.xxx.electronics");
		driver = (AppiumDriver) new IOSDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
	}

What else do I need to add or remove? I am using Appium Desktop version 1.6.5.

**Comment by imurchie** [comment]
@Amar-Incture Are you automating Safari? Or the app? Both are specified in your capabilities.

For real device testing there is build configuration necessary. Please see https://github.com/appium/appium/blob/master/docs/en/drivers/ios-xcuitest-real-devices.md
