### ISSUE TITLE
[MJSONWP] Encountered internal error running command: Error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8200

### ISSUE THREAD

**Issue by Zenerax** [appium/appium#8598]
## The problem

While running multiple test scripts to multiple devices in parallel, I see the following Appium error occurs from the first test script running on each devices and at some random scripts at times after that and it makes the test unreliable.  What can be the problem?

[MJSONWP] Encountered internal error running command: Error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8200

## Environment

* Appium version (or git revision) that exhibits the issue: Appium 1.6.5 with UiAutomator2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:   Linux  3.10.0
* Node.js version (unless using Appium.app|exe):  3.10.3
* Mobile platform/version under test: Android 6.x, 7.x
* Real device or emulator/simulator:  Real device
* Appium CLI or Appium.app|exe:

## Details

While running uiautomator2 test scripts to multiple devices, the initial test script running on each device shows the following Appium error and test failed.   Subsequent tests were executed OK after the initial failure or there were sporadic repro at random test scripts used with the same issue.

[MJSONWP] Encountered internal error running command: Error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8200

Appium log shows an error stating that platformName capability must be included, however the capability was already included as seen on the attached Appium log.

## Link to Appium logs
[appiumError-0.txt](https://github.com/appium/appium/files/1048126/appiumError-0.txt)

[appiumError-0-similar-but-slightly-different-log.txt](https://github.com/appium/appium/files/1048129/appiumError-0-similar-but-slightly-different-log.txt)

[appium-0.txt](https://github.com/appium/appium/files/1048168/appium-0.txt)

## Capabilities used to create the uiautomator2 session
[MJSONWP] Calling AppiumDriver.createSession() with args: [null,null,[{"desiredCapabilities":{"appPackage":"com.pandora.android","appActivity":".Main","noReset":true,"newCommandTimeout":600,"automationName":"uiautomator2","platformName":"Android","deviceName":"Android Device"}},{"requiredCapabilities":{}}]]

**Comment by Zenerax** [comment]
I tried assigning different unused ports for each test run using "systemPort" capability as a part of desired capability and it does not show the race condition.

https://github.com/appium/appium/pull/8535

**Comment by mirro0707** [comment]
I encountered the same problem，I don't known what happened. It is ok after I restart the win platform's appium server with nodeconfig.

**Comment by menglihuakaij** [comment]
我并行执行也遇到了这个问题，，，请问有人解决的吗。
