### ISSUE TITLE
Tap point is not within the bounds of the screen

### ISSUE THREAD

**Issue by hatwalneeraj** [appium/appium#8600]
Hi,

I am just trying to provide input to a search box but while calling sendKeys methods it throws error message - 
selenium.common.exceptions.WebDriverException: Message: tap point is not within the bounds of the screen
I am able to click on that search box but not able to search anything.
If anyone faced similar kind of issue, please help me out.
I am using - 
Xcode - 7.2
IOS version - 9.2
Simulator - iPad Air2

**Comment by dpgraham** [comment]
I recommend that you use a locator to find the element (see https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/finding-elements.md) and then calling sendKeys on the element directly.

**Comment by hatwalneeraj** [comment]
Do you think i was performing sendkeys operation without locating the element ?
However my problem was resolved by using setvalue method.

**Comment by dpgraham** [comment]
Ok.
