### ISSUE TITLE
How to resolve this error "Must supply a context name"

### ISSUE THREAD

**Issue by Logakarti** [appium/appium#8602]
Unable to switch from native_app to web view in the hybrid app, it gives "Must supply a context name" exception. How to solve this issue?

This is my code
Set<String> contextNames = driver.getContextHandles();
        for (String contextName : contextNames) {
            System.out.println( contextName );
            if (contextName.contains( "WEBVIEW_org.ck12.reader" )) {
                driver.context( contextName );
                System.out.println( contextName );
                try {
                    Thread.sleep( 1500 );
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
        }

**Comment by mykola-mokhnach** [comment]
Please fill out the reporting form and provide the necessary information asked there

**Comment by Logakarti** [comment]
I cant' understand your point. What is reporting form?

**Comment by imurchie** [comment]
The information asked for when you created the issue. Appium server logs (as a link to a [gist](https://gist.github.com)) being the most important to make any sort of assessment.

**Comment by Logakarti** [comment]
"Must supply context" name exception throws while running the test in AWS device farm, but the same code it works fine in Android emulators. "Webview" context does not find in AWS.

Please help me to solve this issue.

https://gist.github.com/Logakarti/87747f43654f7b8a04dd53a07fcb5739

**Comment by Logakarti** [comment]
@mykola-mokhnach
