### ISSUE TITLE
[Launch App] Failed to create WDA session - unable to launch app on simulator

### ISSUE THREAD

**Issue by karbon62** [appium/appium#8606]
## The problem
Unable to launch app on simulator 

## Environment
* Appium version 1.0.2-beta.2
* Mac 10.12.5 
* iPhone 5s | 10.0
* Simulator  
* Appium CLI 

## Details
After entering the capabilities that are required to launch my app, I receive error message from the WDA session. I am using a simulator on xcode to run this and not sure what is missed out in the configuration or dependencies.

**Comment by imurchie** [comment]
Are you able to launch the application manually on the simulator?

**Comment by karbon62** [comment]
Tried that doesn't seem to work either, closes instantly after opening.

**Comment by imurchie** [comment]
Generally that means that the application is not built for a simulator, and so cannot run on one.

**Comment by karbon62** [comment]
I'll try a different method in that case, thanks for helping.

**Comment by imurchie** [comment]
You just need to change the build target when building the app in Xcode.
