### ISSUE TITLE
Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1

### ISSUE THREAD

**Issue by amusharraf** [appium/appium#8607]
Hi Everyone,

So I just set up the entire environment on my Mac Mini, I am going to automate tests on iphones. I have one simulator from xcode on my machine and another virtual machine that has another xcode i phone simulator. Both have appium set up but when i run a test, i get a really weird error which is:

**WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1**

I have been looking everywhere and could not find why. I also have a Mac Book pro that i set up the exact same way and everything works perfectly. I did the setup on the Mac Mini multiple times, and the Mac mini is slower so i had to increase the timeout for appium when running on the Mac Mini. 

* Appium version (or git revision) that exhibits the issue: Appium Version 1.6.3
* Desktop OS/version used to run Appium: Mac OS. Mac Mini
* Mobile platform/version under test: iOS 10.2
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: 

Appium Logs: https://gist.github.com/amusharraf/529a8ceb456618849eea8209cbd56a22

**Comment by imurchie** [comment]
More recent versions of Appium have better error messaging around this. In the meantime, can you run the following in a terminal window on the machine running Appium:
```
cd /Users/jenkins/.nvm/versions/node/v5.12.0/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
./Scripts/bootstrap.sh -d
```

**Comment by amusharraf** [comment]
Fetching dependencies
*** Cloning peertalk
*** Checking out peertalk at "v1.0"
*** Cloning peertalk
*** Downloading RoutingHTTPServer.framework binary at "v1.0.1"
A shell task (/usr/bin/env git clone --bare --quiet https://github.com/marekcirkos/peertalk.git /Users/jenkins/Library/Caches/org.carthage.CarthageKit/dependencies/peertalk) failed with exit code 128:
fatal: could not read Username for 'https://github.com': terminal prompts disabled

**Comment by imurchie** [comment]
Ah, yes. My apologies, I forgot about this one.

One of the dependencies that Appium 1.6.3 used was deleted by its owner, making the initial run on the server impossible.

The only remedy is to upgrade to 1.6.4 or 1.6.5.

**Comment by amusharraf** [comment]
Thank you very much!
