### ISSUE TITLE
App Crashes and Failed to Create a WDA Session 

### ISSUE THREAD

**Issue by emmardy** [appium/appium#8608]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by emmardy** [comment]
Im trying to Launch a .ipa file for testing through appium , i have setup WebDriver Agent Successfully and i gave my app location in the Desired Capabilities as Well, But my Log says Failed to Create WDA session, I'm able to see the app icon on my simulator , but the app is getting crashed. 

Here is the Log that im able to see on appium command inspector 

[Appium] Creating new XCUITestDriver (v2.27.2) session
[Appium] Capabilities:
[Appium]   UDID: '16BA1664-DBB7-4D5E-B807-0F44E22B117F'
[Appium]   app: '/Users/ratnamadda/Documents/iOS TestCases/CbyGE2.ipa'
[Appium]   automationName: 'XCUITest'
[Appium]   clearSystemFiles: true
[Appium]   deviceName: 'iPhone 7 Plus'
[Appium]   platform: 'Mac'
[Appium]   platformName: 'iOS'
[Appium]   platformVersion: '10.3'
[Appium]   self.driver: 'http://localhost:4723/wd/hub'
[Appium]   xcodeOrgId: 'ali.mirza@ge.com'
[Appium]   xcodeSigningId: 'iPhone Developer'
[Appium]   newCommandTimeout: 0
[Appium]   connectHardwareKeyboard: true
[XCUITest] XCUITestDriver version: 2.27.2
[BaseDriver] The following capabilities were provided, but are not recognized by appium: UDID, platform, self.driver.
[BaseDriver] Session created with session id: 66b019e7-ec80-455c-9f1c-0c6be9f45bfd
[XCUITest] Xcode version set to '8.3.1' (tools v8.3.2.0.1.1492020469)
[XCUITest] iOS SDK Version set to '10.3'
[BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1496675450493 (11:10:50 GMT-0400 (EDT))
[iOSSim] Constructing iOS simulator for Xcode version 8.3.1 with udid '16BA1664-DBB7-4D5E-B807-0F44E22B117F'
[XCUITest] Determining device to run tests on: udid: '16BA1664-DBB7-4D5E-B807-0F44E22B117F', real device: false
[BaseDriver] Using local app '/Users/ratnamadda/Documents/iOS TestCases/CbyGE2.ipa'
[BaseDriver] Copying local zip to tmp dir
[BaseDriver] Unzipping /var/folders/7r/n7rqqwhd24v1npptysxvh2xh0000gn/T/201755-2309-1ahmd8y.rl00aoflxr/appium-app.zip
[BaseDriver] Testing zip archive: /var/folders/7r/n7rqqwhd24v1npptysxvh2xh0000gn/T/201755-2309-1ahmd8y.rl00aoflxr/appium-app.zip
[BaseDriver] Unzipped local app to '/var/folders/7r/n7rqqwhd24v1npptysxvh2xh0000gn/T/201755-2309-1ahmd8y.rl00aoflxr/Payload/CbyGE.app'
[BaseDriver] Event 'appConfigured' logged at 1496675453193 (11:10:53 GMT-0400 (EDT))
[XCUITest] Checking whether app '/var/folders/7r/n7rqqwhd24v1npptysxvh2xh0000gn/T/201755-2309-1ahmd8y.rl00aoflxr/Payload/CbyGE.app' is actually present on file system
[XCUITest] App is present
[iOS] Getting bundle ID from app '/var/folders/7r/n7rqqwhd24v1npptysxvh2xh0000gn/T/201755-2309-1ahmd8y.rl00aoflxr/Payload/CbyGE.app': 'cn.xlink.CbyGE'
[XCUITest] Setting 'connectHardwareKeyboard' Simulator option to 'on'
[BaseDriver] Event 'resetStarted' logged at 1496675453203 (11:10:53 GMT-0400 (EDT))
[XCUITest] Not scrubbing third party app in anticipation of uninstall
[BaseDriver] Event 'resetComplete' logged at 1496675453356 (11:10:53 GMT-0400 (EDT))
[iOSLog] Starting iOS 10.3 simulator log capture
[iOSLog] System log path: /Users/ratnamadda/Library/Logs/CoreSimulator/16BA1664-DBB7-4D5E-B807-0F44E22B117F/system.log
[BaseDriver] Event 'logCaptureStarted' logged at 1496675453615 (11:10:53 GMT-0400 (EDT))
[XCUITest] Setting up simulator
[iOS] No reason to set locale
[iOS] No iOS / app preferences to set
[XCUITest] Simulator with udid '16BA1664-DBB7-4D5E-B807-0F44E22B117F' not booted. Booting up now
[iOSSim] Killing all iOS Simulators
[iOSSim] Simulator is not running. Continuing...
[iOSSim] Starting simulator with command: open -Fn /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app --args -CurrentDeviceUDID 16BA1664-DBB7-4D5E-B807-0F44E22B117F
[iOSSim] Simulator booted in 26242ms
[BaseDriver] Event 'simStarted' logged at 1496675480231 (11:11:20 GMT-0400 (EDT))
[XCUITest] Reset requested. Removing app with id 'cn.xlink.CbyGE' from the device
[XCUITest] Installing /var/folders/7r/n7rqqwhd24v1npptysxvh2xh0000gn/T/201755-2309-1ahmd8y.rl00aoflxr/Payload/CbyGE.app on Simulator with UUID '16BA1664-DBB7-4D5E-B807-0F44E22B117F'...
[XCUITest] The app has been installed successfully.
[BaseDriver] Event 'appInstalled' logged at 1496675491134 (11:11:31 GMT-0400 (EDT))
[BaseDriver] Event 'wdaStartAttempted' logged at 1496675491139 (11:11:31 GMT-0400 (EDT))
[XCUITest] Using WDA path: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[XCUITest] Carthage found: '/usr/local/bin/carthage'
[XCUITest] Killing hanging processes
[XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=16BA1664-DBB7-4D5E-B807-0F44E22B117F -configuration Debug IPHONEOS_DEPLOYMENT_TARGET=10.3' in directory '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Output from xcodebuild will not be logged
[XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[XCUITest] Log file for xcodebuild test: /Users/ratnamadda/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/FF9739C1-28BE-490F-8DB2-0DAB06740CBE/Session-WebDriverAgentRunner-2017-06-05_111138-dFhYJl.log
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"state\" : \"success\",\n    \"os\" : {\n      \"name\" : \"iOS\",\n      \"version\" : \"10.3\"\n    },\n    \"ios\" : {\n      \"simulatorVersion\" : \"10.3\",\n      \"ip\" : \"3.30.192.203\"\n    },\n    \"build\" : {\n      \"time\" : \"May 31 2017 13:46:15\"\n    }\n  },\n  \"sessionId\" : \"894BDC48-ECC9-4E60-BDB4-F7B9CC179210\",\n  \"status\" : 0\n}"
[XCUITest] WebDriverAgent running on ip '3.30.192.203'
[XCUITest] WebDriverAgent successfully started after 15563ms
[BaseDriver] Event 'wdaSessionAttempted' logged at 1496675506857 (11:11:46 GMT-0400 (EDT))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"cn.xlink.CbyGE","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}

I takes longtime and after displaying this [XCUITest] Failed to create WDA session. Retrying...

**Comment by imurchie** [comment]
Can you manually launch the app on the simulator?

**Comment by emmardy** [comment]
No I'm not able to launch , i can see the Web Driver agent opening and getting closed 
![screen shot 2017-06-05 at 11 21 22 am](https://cloud.githubusercontent.com/assets/22243403/26790296/2b5b266c-49e1-11e7-89ab-ce045cf94c33.png)

**Comment by emmardy** [comment]
Here is my Desired Capability set I'm trying to launch from appium 
{
  "platformName": "iOS",
  "platformVersion": "10.3",
  "deviceName": "iPhone 7 Plus",
  "automationName": "XCUITest",
  "clearSystemFiles": true,
  "self.driver": "http://localhost:4723/wd/hub",
  "app": "/Users/ratnam/Documents/TestCases/app.ipa",
  "platform": "Mac",
  "UDID": "16BA1664-DBB7-4D5E-B807-0F44E22B117F",
  "xcodeOrgId": "michael777@gmail.com",
  "xcodeSigningId": "iPhone Developer"
}

**Comment by imurchie** [comment]
Most likely the application would sending is not built to be run on a simulator. In that case there is nothing Appium is able to do.

Re-build the app for the simulator and try again (most likely there will be no ipa artifact, just an app).

On a not-entirely-related note, the `UDID` capability is lower case (`udid`).

**Comment by emmardy** [comment]
After an un-successful attempt with the iPhone Simulator I'm trying to launch the app on physical device , then I'm getting this error 
![screen shot 2017-06-05 at 10 59 25 am](https://cloud.githubusercontent.com/assets/22243403/26790995/bb4114e2-49e3-11e7-89e8-267eed076454.png)

**Comment by imurchie** [comment]
Have you read https://github.com/appium/appium/blob/master/docs/en/appium-setup/real-devices-ios.md

**Comment by emmardy** [comment]
i Have setup my app by following the instructions from the above link, everytime i stuck at running the script ,, getting this error 
"-bash: ./Scripts/bootstrap.sh: No such file or directory"

**Comment by imurchie** [comment]
Are you running this manually? Where are you running it?

**Comment by emmardy** [comment]
Im running on Appium 1.6.3 beta desktop version, i got .ipa file from my client and i have unzipped the iPad file and i got the .app file , and I'm using the .app file to run on simulator , it crashes , then i used .ipa again it crashes , i have setup the WebDriver agent successfully and it is fine , i have setup appium and it is fine , now I'm trying to launch from appium giving desired caps but it throws me above error

**Comment by imurchie** [comment]
Ok. Appium 1.6.3 depended on an external tool, and the owner of that tool deleted it. So it cannot download the dependencies and fails in this way.

The only remedy is to upgrade to 1.6.4 or 1.6.5, unfortunately.

**Comment by emmardy** [comment]
i have upgraded to 1.6.5 , still the same issue, should i make any changes to that .ipa file in Xcode ???

**Comment by imurchie** [comment]
Which issue is this now? The `./Scripts/bootstrap.sh` error?

**Comment by emmardy** [comment]
no they main error Failed to create WDA session , i have followed the steps and I'm able to add my simulator in the list of devices and tried to launch, but failed to create WDA session,, it takes so long time and if i abort/terminate the connection it says failed.

**Comment by imurchie** [comment]
Ok. My apologies. Can you post a link to a [gist](https://gist.github.com) of the Appium server logs for the latest configuration?

**Comment by emmardy** [comment]
one thing i wanna make clear , here I'm testing with Simulator and a Device both, first im trying to launch the app from appium and the app is getting crashed , now i have connected a device and i have given its name and udid and I'm able to open the app.... but the log is completely different now , here is the gist link https://gist.github.com/emmardy/8b7a89ad249fe1bd627a54096e92bd4b

**Comment by imurchie** [comment]
This is now a code signing issue. The steps laid out in the documentation I linked above should be useful.

To get to a better understanding of the error, you can turn on Xcode logging by setting the `showXcodeLog` desired capability to `true`.

Also: this is the most recent logs? You say you've moved to 1.6.5 but the logs are for 1.6.4.

**Comment by emmardy** [comment]
yes this is the most recent log, i have a developer account signed in and i have provisioning certificate too , the latest error says "[XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65" and build failed now when i add the physical device on Xcode 
![screen shot 2017-06-05 at 1 43 14 pm](https://cloud.githubusercontent.com/assets/22243403/26795810/f8b87ba6-49f4-11e7-950c-949d835159aa.png)

**Comment by emmardy** [comment]
![screen shot 2017-06-05 at 1 53 28 pm](https://cloud.githubusercontent.com/assets/22243403/26796158/66e714f6-49f6-11e7-9c18-015dea45c247.png)

**Comment by imurchie** [comment]
Did you set xcode logging on and see how it works through the command line?

**Comment by emmardy** [comment]
Honestly i don't know how to do that !!! i gotta take a look

**Comment by imurchie** [comment]
https://github.com/appium/appium/issues/8608#issuecomment-306252014

**Comment by emmardy** [comment]
Here is the GIST : https://gist.github.com/emmardy/12067660ad72eea71b91853b78ccb6d1

**Comment by imurchie** [comment]
So you'll need to look at your signing certificates.
```
No signing certificate "iOS Development" found:  No "iOS Development" signing certificate matching team ID "ali.mirza@ge.com" with a private key was found.
```

**Comment by emmardy** [comment]
This is weird, I'm using my company's developer account and don't know why appium says, No Signing Certificate found.

**Comment by imurchie** [comment]
Is the certificate installed on your machine? Appium does not contact Apple, just looks locally.

**Comment by sl1991** [comment]
@ratnamaddha How do you solve this issue? Did you install the certificate on your machine?
