### ISSUE TITLE
WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: java.lang.NullPointerException

### ISSUE THREAD

**Issue by xiaoqi7s** [appium/appium#8609]
## The problem

when i use uiautomator2 in android 5.1.1 it don‘t have this problem. but when i use android 4.4.2 it has the problem. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Desktop OS/version used to run Appium: win7
* Node.js version (unless using Appium.app|exe): v7.4.0
* Mobile platform/version under test: android 4.4.2 and 5.1.1
* uiautomator2

## Link to Appium logs
[debug] [JSONWP Proxy] Proxying [POST /element/fad1032c-2dc3-4a3f-85bd-30680c336
ec8/value] to [POST http://localhost:8200/wd/hub/session/f67c5896-33bf-4d4a-8b84
-523719c171eb/element/fad1032c-2dc3-4a3f-85bd-30680c336ec8/value] with body: {"e
lementId":"fad1032c-2dc3-4a3f-85bd-30680c336ec8","text":"18081090702","replace":
false}
[debug] [JSONWP Proxy] Got response with status 200: {"value":"","status":0,"ses
sionId":"f67c5896-33bf-4d4a-8b84-523719c171eb"}
[debug] [MJSONWP] Responding to client with driver.setValue() result: ""
[HTTP] <-- POST /wd/hub/session/3f7e50e4-29b5-450b-b113-eb11e5d89069/element/fad
1032c-2dc3-4a3f-85bd-30680c336ec8/value 200 338 ms - 74
[HTTP] --> POST /wd/hub/session/3f7e50e4-29b5-450b-b113-eb11e5d89069/elements {"
using":"id","sessionId":"3f7e50e4-29b5-450b-b113-eb11e5d89069","value":"com.wlqq
:id/codeLogin"}
[debug] [MJSONWP] Calling AppiumDriver.findElements() with args: ["id","com.wlqq
:id/codeLogin","3f7e50e4-29b5-450b-b113-eb11e5d89069"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class
 name, accessibility id, -android uiautomator
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class
 name, accessibility id, -android uiautomator
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8200/
wd/hub/session/f67c5896-33bf-4d4a-8b84-523719c171eb/elements] with body: {"strat
egy":"id","selector":"com.wlqq:id/codeLogin","context":"","multiple":true}
[debug] [JSONWP Proxy] Got response with status 200: {"value":[{"ELEMENT":"1472e
e59-85cd-4eb8-ac7f-8a7afd7e8b2a"}],"status":0,"sessionId":"f67c5896-33bf-4d4a-8b
84-523719c171eb"}
[debug] [MJSONWP] Responding to client with driver.findElements() result: [{"ELE
MENT":"1472ee59-85cd-4eb8-ac7f-8a7afd7e8b2a"}]
[HTTP] <-- POST /wd/hub/session/3f7e50e4-29b5-450b-b113-eb11e5d89069/elements 20
0 410 ms - 124
[HTTP] --> POST /wd/hub/session/3f7e50e4-29b5-450b-b113-eb11e5d89069/element/147
2ee59-85cd-4eb8-ac7f-8a7afd7e8b2a/click {"sessionId":"3f7e50e4-29b5-450b-b113-eb
11e5d89069","id":"1472ee59-85cd-4eb8-ac7f-8a7afd7e8b2a"}
[debug] [MJSONWP] Calling AppiumDriver.click() with args: ["1472ee59-85cd-4eb8-a
c7f-8a7afd7e8b2a","3f7e50e4-29b5-450b-b113-eb11e5d89069"]
[debug] [JSONWP Proxy] Proxying [POST /element/1472ee59-85cd-4eb8-ac7f-8a7afd7e8
b2a/click] to [POST http://localhost:8200/wd/hub/session/f67c5896-33bf-4d4a-8b84
-523719c171eb/element/1472ee59-85cd-4eb8-ac7f-8a7afd7e8b2a/click] with body: {"e
lement":"1472ee59-85cd-4eb8-ac7f-8a7afd7e8b2a"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":true,"status":0,"s
essionId":"f67c5896-33bf-4d4a-8b84-523719c171eb"}
[debug] [MJSONWP] Responding to client with driver.click() result: true
[HTTP] <-- POST /wd/hub/session/3f7e50e4-29b5-450b-b113-eb11e5d89069/element/147
2ee59-85cd-4eb8-ac7f-8a7afd7e8b2a/click 200 34 ms - 76
[HTTP] --> POST /wd/hub/session/3f7e50e4-29b5-450b-b113-eb11e5d89069/elements {"
using":"id","sessionId":"3f7e50e4-29b5-450b-b113-eb11e5d89069","value":"com.wlqq
:id/passWord"}
[debug] [MJSONWP] Calling AppiumDriver.findElements() with args: ["id","com.wlqq
:id/passWord","3f7e50e4-29b5-450b-b113-eb11e5d89069"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class
 name, accessibility id, -android uiautomator
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class
 name, accessibility id, -android uiautomator
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8200/
wd/hub/session/f67c5896-33bf-4d4a-8b84-523719c171eb/elements] with body: {"strat
egy":"id","selector":"com.wlqq:id/passWord","context":"","multiple":true}
[debug] [JSONWP Proxy] Got response with status 200: {"value":[{"ELEMENT":"4f3f6
ddb-7513-4666-93dc-81996946f560"}],"status":0,"sessionId":"f67c5896-33bf-4d4a-8b
84-523719c171eb"}
[debug] [MJSONWP] Responding to client with driver.findElements() result: [{"ELE
MENT":"4f3f6ddb-7513-4666-93dc-81996946f560"}]
[HTTP] <-- POST /wd/hub/session/3f7e50e4-29b5-450b-b113-eb11e5d89069/elements 20
0 553 ms - 124
[HTTP] --> POST /wd/hub/session/3f7e50e4-29b5-450b-b113-eb11e5d89069/element/4f3
f6ddb-7513-4666-93dc-81996946f560/value {"sessionId":"3f7e50e4-29b5-450b-b113-eb
11e5d89069","id":"4f3f6ddb-7513-4666-93dc-81996946f560","value":["1","2","3","3"
,"2","1"]}
[debug] [MJSONWP] Calling AppiumDriver.setValue() with args: [["1","2","3","3","
2","1"],"4f3f6ddb-7513-4666-93dc-81996946f560","3f7e50e4-29b5-450b-b113-eb11e5d8
9069"]
[debug] [JSONWP Proxy] Proxying [POST /element/4f3f6ddb-7513-4666-93dc-81996946f
560/value] to [POST http://localhost:8200/wd/hub/session/f67c5896-33bf-4d4a-8b84
-523719c171eb/element/4f3f6ddb-7513-4666-93dc-81996946f560/value] with body: {"e
lementId":"4f3f6ddb-7513-4666-93dc-81996946f560","text":"123321","replace":false
}
[MJSONWP] Encountered internal error running command:  {"jsonwp":{"value":"java.
lang.NullPointerException\n\tat android.support.test.uiautomator.UiObject2.setTe
xt(UiObject2.java:601)\n\tat io.appium.uiautomator2.model.UiObject2Element.setTe
xt(UiObject2Element.java:129)\n\tat io.appium.uiautomator2.handler.SendKeysToEle
ment.safeHandle(SendKeysToElement.java:83)\n\tat io.appium.uiautomator2.handler.
request.SafeRequestHandler.handle(SafeRequestHandler.java:56)\n\tat io.appium.ui
automator2.server.AppiumServlet.handleRequest(AppiumServlet.java:202)\n\tat io.a
ppium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:193
)\n\tat io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java
:44)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandle
rContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.nett
y.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerCo
ntext.java:345)\n\tat io.netty.handler.codec.MessageToMessageDecoder.channelRead
(MessageToMessageDecoder.java:102)\n\tat io.netty.channel.AbstractChannelHandler
Context.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty
.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerC
ontext.java:352)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChanne
lRead(AbstractChannelHandlerContext.java:345)\n\tat io.netty.channel.CombinedCha
nnelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChanne
lDuplexHandler.java:435)\n\tat io.netty.handler.codec.ByteToMessageDecoder.fireC
hannelRead(ByteToMessageDecoder.java:293)\n\tat io.netty.handler.codec.ByteToMes
sageDecoder.channelRead(ByteToMessageDecoder.java:267)\n\tat io.netty.channel.Co
mbinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)\n\
tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractCha
nnelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContex
t.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.chann
el.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.j
ava:345)\n\tat io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(D
efaultChannelPipeline.java:1294)\n\tat io.netty.channel.AbstractChannelHandlerCo
ntext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.c
hannel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerCon
text.java:352)\n\tat io.netty.channel.DefaultChannelPipeline.fireChannelRead(Def
aultChannelPipeline.java:911)\n\tat io.netty.channel.nio.AbstractNioByteChannel$
NioByteUnsafe.read(AbstractNioByteChannel.java:131)\n\tat io.netty.channel.nio.N
ioEventLoop.processSelectedKey(NioEventLoop.java:611)\n\tat io.netty.channel.nio
.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:514)\n\tat io.netty.cha
nnel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:468)\n\tat io.netty.
channel.nio.NioEventLoop.run(NioEventLoop.java:438)\n\tat io.netty.util.concurre
nt.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)\n\tat io.
netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultT
hreadFactory.java:144)\n\tat java.lang.Thread.run(Thread.java:841)\n","status":1
3,"sessionId":"f67c5896-33bf-4d4a-8b84-523719c171eb"}} ProxyRequestError: Could
not proxy command to remote server. Original error: 500 - {"value":"java.lang.Nu
llPointerException\n\tat android.support.test.uiautomator.UiObject2.setText(UiOb
ject2.java:601)\n\tat io.appium.uiautomator2.model.UiObject2Element.setText(UiOb
ject2Element.java:129)\n\tat io.appium.uiautomator2.handler.SendKeysToElement.sa
feHandle(SendKeysToElement.java:83)\n\tat io.appium.uiautomator2.handler.request
.SafeRequestHandler.handle(SafeRequestHandler.java:56)\n\tat io.appium.uiautomat
or2.server.AppiumServlet.handleRequest(AppiumServlet.java:202)\n\tat io.appium.u
iautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:193)\n\tat
 io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:44)\n\
tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractCha
nnelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContex
t.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.chann
el.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.j
ava:345)\n\tat io.netty.handler.codec.MessageToMessageDecoder.channelRead(Messag
eToMessageDecoder.java:102)\n\tat io.netty.channel.AbstractChannelHandlerContext
.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channe
l.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.
java:352)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(A
bstractChannelHandlerContext.java:345)\n\tat io.netty.channel.CombinedChannelDup
lexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplex
Handler.java:435)\n\tat io.netty.handler.codec.ByteToMessageDecoder.fireChannelR
ead(ByteToMessageDecoder.java:293)\n\tat io.netty.handler.codec.ByteToMessageDec
oder.channelRead(ByteToMessageDecoder.java:267)\n\tat io.netty.channel.CombinedC
hannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)\n\tat io.
netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHan
dlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invok
eChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.channel.Abst
ractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345
)\n\tat io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultC
hannelPipeline.java:1294)\n\tat io.netty.channel.AbstractChannelHandlerContext.i
nvokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.
AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.ja
va:352)\n\tat io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultCha
nnelPipeline.java:911)\n\tat io.netty.channel.nio.AbstractNioByteChannel$NioByte
Unsafe.read(AbstractNioByteChannel.java:131)\n\tat io.netty.channel.nio.NioEvent
Loop.processSelectedKey(NioEventLoop.java:611)\n\tat io.netty.channel.nio.NioEve
ntLoop.processSelectedKeysPlain(NioEventLoop.java:514)\n\tat io.netty.channel.ni
o.NioEventLoop.processSelectedKeys(NioEventLoop.java:468)\n\tat io.netty.channel
.nio.NioEventLoop.run(NioEventLoop.java:438)\n\tat io.netty.util.concurrent.Sing
leThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)\n\tat io.netty.u
til.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFa
ctory.java:144)\n\tat java.lang.Thread.run(Thread.java:841)\n","status":13,"sess
ionId":"f67c5896-33bf-4d4a-8b84-523719c171eb"}
    at JWProxy.proxy$ (../../../lib/jsonwp-proxy/proxy.js:144:13)
    at tryCatch (C:\Users\hcb\AppData\Roaming\npm\node_modules\appium\node_modul
es\.5.8.24@babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\hcb\AppData\Roam
ing\npm\node_modules\appium\node_modules\.5.8.24@babel-runtime\regenerator\runti
me.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\
Users\hcb\AppData\Roaming\npm\node_modules\appium\node_modules\.5.8.24@babel-run
time\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\hcb\AppData\Roaming\npm\node_
modules\appium\node_modules\.5.8.24@babel-runtime\regenerator\runtime.js:136:37)

[HTTP] <-- POST /wd/hub/session/3f7e50e4-29b5-450b-b113-eb11e5d89069/element/4f3
f6ddb-7513-4666-93dc-81996946f560/value 500 573 ms - 3444
[HTTP] --> GET /wd/hub/session/3f7e50e4-29b5-450b-b113-eb11e5d89069/screenshot {
}
[debug] [MJSONWP] Calling AppiumDriver.getScreenshot() with args: ["3f7e50e4-29b

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

my code is just input text to element。

**Comment by mykola-mokhnach** [comment]
UIAutomator2 is incompatible to Android versions below 5 (Lollipop). Please use some other backend for these.
