### ISSUE TITLE
Unable to Scroll in Appium 1.6.4 IOS

### ISSUE THREAD

**Issue by Sudam-Mandhane** [appium/appium#8612]
I am trying to scroll giving me error as "Locator Strategy '-ios uiautomation' is not supported for this session"
I am passing text to scroll.

driver.ScrollTo("xyz");

**Comment by Sudam-Mandhane** [comment]
Thanks mokhnach, 
Also could you tell what else got deprecated?
like TouchActions, tap, zoom?

**Comment by mykola-mokhnach** [comment]
Only TouchActions should be used. Everything else must be removed.
