### ISSUE TITLE
WebDriverAgent XCode build fails with following error "IDETestOperationsObserverErrorDomain Code=13"

### ISSUE THREAD

**Issue by qual** [appium/appium#8614]
## The problem

I am unable to launch the iOS application using Appium due to XCode build failure. Getting following error:

2017-06-06 15:34:50.847 xcodebuild[28226:500330] Error **Domain=IDETestOperationsObserverErrorDomain Code=13 "Failed to background test runner**. If you believe this error represents a bug, please attach the log file at /Users/qual/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/CA8D9DDC-B560-4B76-80B5-3A29B1F3BF99/Session-WebDriverAgentRunner-2017-06-06_153412-EHO9s6.log" UserInfo={NSLocalizedDescription=Failed to background test runner.

**As mentioned in Appium logs, XCode log file is attached  at https://gist.github.com/qual/3aacdb5f5fcd74e512bc05359da41bf4**

## Environment
* Appium version (or git revision) that exhibits the issue: Appium Dekstop 1.0.0 (Appium Server 1.6.4)
* Last Appium version that did not exhibit the issue (if applicable): Appium Dekstop 1.0.0 (Appium Server 1.6.4)
* Desktop OS/version used to run Appium: 
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS 10.2
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium Desktop

## Details
As mentioned in the logs, here is the log file created by A

1. After installation of Appium desktop 1.0.0 (Appium Server 1.6.4) stable version,  WebDriverAgent project doesn't get built. It throws compile time errors.
2. Hence I replaced WebDriverAgent project with the latest master branch from its official github repository.

## Link to Appium logs
https://gist.github.com/qual/c0d2612de373740b007d53794da932d3

## Code To Reproduce Issue [ Good To Have ]
	       DesiredCapabilities capabilities = new DesiredCapabilities();
		try {
			capabilities.setCapability("platformName", "iOS");
			capabilities.setCapability("deviceName", "iPhone");
			capabilities.setCapability("udid","160a2335sdasdasassfadaa");
			capabilities.setCapability("automationName", "XCUITest");
			capabilities.setCapability("showXcodeLog", true);
			capabilities.setCapability("newCommandTimeOut", 1000);
			capabilities.setCapability("bundleId", "com.qual.UIKitCatalog");
			driver = new IOSDriver<MobileElement>(new URL("http://192.168.25.151:4723/wd/hub"), capabilities);
			driver.findElementByAccessibilityId("UIKitCatalog").click();
		} catch (Exception e) {
			e.printStackTrace();
		}
   }
}

**Comment by mykola-mokhnach** [comment]
Might be the same problem as in https://github.com/facebook/WebDriverAgent/issues/507

**Comment by qual** [comment]
Apologies for accidentally closing the issue. Reopened it.
@mykola-mokhnach I suspect this to be different than facebook/WebDriverAgent#507 since here getting specific error code IDETestOperationsObserverErrorDomain Code=13

**Comment by qual** [comment]
@mykola-mokhnach
Should i open the issue in webdriveragent github project ?

**Comment by mykola-mokhnach** [comment]
Try to restart the device and see if it fixes the problem

**Comment by mykola-mokhnach** [comment]
Creating a new issue won't help if it has been reported already. Better to find an acceptable solution/workaround.

**Comment by qual** [comment]
Issue disappeared after restart. Sorry for trouble. Closing this issue.

**Comment by mykola-mokhnach** [comment]
It may appear again after some time. Have you read the the issue report I mentioned above in WDA tracker?

**Comment by qual** [comment]
Yes. I went through facebook/WebDriverAgent#507 but didn't understand the conclusion. Also, the reporter was getting IDETestOperationsObserverErrorDomain code=5 error whereas I am getting code 13
Also, I encountered this error code 13 first time since I am working with Appium-iOS.

**Comment by mykola-mokhnach** [comment]
The final error might be different, but the reason is the same. One should keep WDA running without restart on the device for as long as possible to avoid manual device reboot.

**Comment by qual** [comment]
How to keep WDA running ? Is there any desired capability ?

**Comment by VenkateshPS** [comment]
@mykola-mokhnach 
I to keep seeing this defect intermittently it goes away though after device restart, but is for Automation which runs in CI?
