### ISSUE TITLE
Enable XPath visibility on Appium Desktop Inspector

### ISSUE THREAD

**Issue by lshyamsv** [appium/appium#8618]
## The problem

Even if there is a blank resource ID or description the visibility of XPath on the Desktop app/Inspector is hidden. It would be good to show XPath identifier or the complete path for all the elements.

P.S - Jonathan Lipps this is with regards to our discussion at Saucecon 2017, Appium 201 workshop.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: 1.0.1
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Android 6.0.1
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium.app

## Code To Reproduce Issue [ Good To Have ]

The App I am automating only has default resource ID's. Appium Desktop/Inspector when inspecting an element hides the XPath under the assumption that there is element locator. It would be nice to enable XPath for all the elements.

**Comment by dpgraham** [comment]
It should be showing the xpath regardless of it having a resource-id or description.

Do you have a screenshot that shows an example of this?

And can you also provide the source XML?

**Comment by lshyamsv** [comment]
Hi Dan,

Here is the screenshot. I tried for couple of elements and for both XPath is not displayed. I even showed the live example to John during SauceCon.
<img width="416" alt="screen shot 2017-06-09 at 11 50 03 am" src="https://user-images.githubusercontent.com/29240411/26990143-7deacb22-4d0a-11e7-9c27-356b5dd2a05a.png">
<img width="402" alt="screen shot 2017-06-09 at 11 49 32 am" src="https://user-images.githubusercontent.com/29240411/26990152-82ce7332-4d0a-11e7-8ba2-d0fa884b4708.png">

**Comment by dpgraham** [comment]
Aha. I understand now. The 'Find By' table shows the optimal locator strategy + selector. ID is superior to XPath because it's less brittle and more performant. I forgot that it did that.

I suppose we can add a second row to that table to include XPath.

Can I ask the specific reason why you want to see the xpath?

**Comment by lshyamsv** [comment]
Hi Dan,

Couple of reasons. 

1. We are in the process of implementing Resource ID's or content descriptions. We have resource ID's but since we are a media company /App, We have anti hack softwares which hides all the resource ID's.
2. Our automation mostly is in a very mature stage having all XPath's. So its good to see the XPath on Appium.

Thanks,
Shyam.

**Comment by dpgraham** [comment]
The next version of Appium Desktop will have this.
