### ISSUE TITLE
webview can not locate elements

### ISSUE THREAD

**Issue by Sanyusun** [appium/appium#8620]
## The problem
Hi guys ,because my app replace default browser kernel to another，now i can not locate the element in webview .what should i do?

## Environment

* Appium version:1.6.3
* Desktop OS/version used to run Appium: Mac os 10.12.4
* Node.js version (unless using Appium.app|exe):7.2.1
* Mobile platform/version under test: 4.4.4
* Real device or emulator/simulator:Real device
* Appium CLI or Appium.app|exe: Appium.app(1.5.3)

## Details

if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
     WebView.setWebContentsDebuggingEnabled(true);
}
is set 
page.source logs:
<html><head></head><body>
   <script type="text/javascript">
      if (!window['DeviceInsight'])
      {
         // Gingerbread emulator workaround: Use window.prompt to call back to Java
         (function() {
            window['DeviceInsight'] = {};
            function addCallback(name)
            {
               DeviceInsight[name] = function()
               {
                  var request = {
                     'method': name,
                     'arguments': Array.prototype.slice.call(arguments)
                  };
                  window.prompt(JSON.stringify(request));
               };
            }
            addCallback('start');
            addCallback('resolve');
            addCallback('reject');
         })();
      }
      window.DeviceInsight.start();
   </script>
   <script type="text/javascript">
   //<![CDATA[
   
   //]]>
   </script>
   <input type="text" name="js" id="js">
   <script type="text/javascript">
      try
      {
         if(!window.hasOwnProperty('fortyone'))
         {
            throw new Error("JSC entry point not found");
         }
         window.fortyone.collect('js');
         window.DeviceInsight.resolve(document.getElementById('js').value);
      }
      catch(e) { window.DeviceInsight.reject(e.message); }
   </script>

</body></html>
## Link

 [Appium](https://gist.github.com/Sanyusun/cc2210f000841113cd7097a038b1ec29) logs

**Comment by dpgraham** [comment]
I don't understand what you mean by 'replace default browser kernel to another'.

Can you elaborate on that?

**Comment by Sanyusun** [comment]
Thank you reply, I mean，our Android app do not use the system default browser to display webview , use X5 browser to display it.

**Comment by dpgraham** [comment]
If it's a browser other than the native Android or Chrome browser I don't think Appium will be able to support it

@imurchie Can you confirm this?

**Comment by imurchie** [comment]
Yes. If it is not supported by ChromeDriver then Appium cannot automate it.

**Comment by Sanyusun** [comment]
@dpgraham @imurchie thank you for your reply.The problem that can not find webview elements has been solved, but another issue occured  error log: `session not created exception: please close ' ' and try again `when switch context

**Comment by dpgraham** [comment]
@Sanyusun You'll need to make a new issue for that and provide detailed Appium logs.

**Comment by WangMegan713** [comment]
怎么解决的？

**Comment by WangMegan713** [comment]
我也遇到webview内核换成x5定位不到元素的问题了

**Comment by cschabetsberger-micro-focus** [comment]
I think this was supported in ChromeDriver but does not work anymore since ChromeDriver 2.22. I narrowed this down and logged a defect in the ChromeDriver issue tracker at https://bugs.chromium.org/p/chromedriver/issues/detail?id=1876

(Feel free to star this issue to get faster response)
