### ISSUE TITLE
QUESTION: How to locate element by index in find_element_by_ios_predicate

### ISSUE THREAD

**Issue by lavi-xu** [appium/appium#8622]
I run into an issue to locate element which most of attributes are same.

For example, we have 2 buttons, all attributes are same except its index are different.

In xpath, we can use like //XCUIElementTypeButton[1] and //XCUIElementTypeButton[2].

How can we do this from find_element_by_ios_predicate?

BR.

**Comment by mykola-mokhnach** [comment]
predicate locators don't know anything about the hierarchy. However you may try [class chain](https://github.com/facebook/WebDriverAgent/wiki/Queries) locator type if you still want to use location by predicate.
Also, you could use nested searches.

**Comment by lavi-xu** [comment]
class chain locator seems okay to me. However, there is no "class chain" support in python binding client:
 https://github.com/appium/python-client

Am I right?

**Comment by mykola-mokhnach** [comment]
I cannot say for sure, since I only use java client. However, there should be a way to manually specify locator type, that is expected on the server. This one is "-ios class chain".

**Comment by lavi-xu** [comment]
FYI.

[https://github.com/appium/python-client/issues/171](url)

Thanks,

**Comment by lavi-xu** [comment]
@mykola-mokhnach

I tried use class chain, it very fast, the call just takes less 1 sec (compared to xpath which normal takes 10s):
driver.find_element_by_ios_classchain('*/*/*/*/*/XCUIElementTypeStaticText[2]')

It 's great !!

I am not sure why there is limitation that path has to be directly.

Could I have a request, that having relative path for class chain? like xpath:
ie: driver.find_element_by_ios_classchain('//XCUIElementTypeStaticText[2]').

Then there would be no xpath need any more.

BR.

**Comment by mykola-mokhnach** [comment]
class chain is so fast because "in-deep" search is not part of the feature. Algorithm complexity will be O(n^2) instead of O(n) after it is implemented.

For simple cases like find the second XCUIElementTypeStaticText in the tree you could find multiple elements using className locator and then extract the second match.

**Comment by lavi-xu** [comment]
If the position of elements are kind of order by logic and easy to find out,  using className would be making sense.

For normal mobile application, there would not be too many elements that would be cost on "Algorithm complexity". 

I would ask where does "Algorithm" happen?

BR,

**Comment by mykola-mokhnach** [comment]
https://github.com/facebook/WebDriverAgent/blob/master/WebDriverAgentLib/Categories/XCUIElement%2BFBClassChain.m

**Comment by mykola-mokhnach** [comment]
You could create a PR there and I will be happy to review it. Right now I'm busy to change it myself, but I may get back to it in the near future.

**Comment by lavi-xu** [comment]
@mykola-mokhnach 
Meanwhile, could you please give us a simple on "use nested searches."
Is something like a/b -> find_element("a").find_element("b") ?

BR.

**Comment by mykola-mokhnach** [comment]
exactly

**Comment by lavi-xu** [comment]
FYI.

https://github.com/facebook/WebDriverAgent/issues/610

BR.

**Comment by Pr60** [comment]
@lavi-xu  How do you convert this xpath = `(//XCUIElementTypeButton[@name="actionButton"])[1]` to classchain ?
