### ISSUE TITLE
[XCUITest] NO scrolling to center of element

### ISSUE THREAD

**Issue by derunewige** [appium/appium#8623]
## The problem

With version 1.6.4 when I perform a scroll using TouchActions it scrolls till the center of the element is visible. Then I could do a click, which is as standard at the center of the element.
After update to 1.6.5 it scrolls only till the top of the element is visible. So if I perform a click to the element it does not work, since the center of the element is not visible(clickable). 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4-beta + 1.6.4-beta2. + 1.6.5
* Last Appium version that did not exhibit the issue (if applicable): 1.6.4
* Desktop OS/version used to run Appium: Mac OS 10.12.5
* Node.js version (unless using Appium.app|exe):  6.9.1
* Mobile platform/version under test: iOS 10.3
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs

[gist NOT working v1.6.5](https://gist.github.com/derunewige/cc78fa08a60e5a20b1dcca0d3f3e3f8f) 

[gist working v1.6.4](https://gist.github.com/derunewige/dcbe0df4ce1b8f90a410c22ee63d135a) 

## Code To Reproduce Issue [ Good To Have ]

```
public static void waitForVisibilityAndClick(By locator, long timeout) {
		AppiumDriver<IOSElement> driver = null;
		try {
			driver = AppiumDriverBuilder.getIOSDriver();
		} catch (MalformedURLException e) {
			e.printStackTrace();
		}
		WebDriverWait wait = new WebDriverWait(driver, timeout);

		IOSElement elem = (IOSElement) wait.until(ExpectedConditions.presenceOfElementLocated(locator));

		if (!elem.isDisplayed()) {
			try {
				driver.performTouchAction(new IOSTouchAction(driver).press(0, 0).moveTo(elem).release());
				// log.debug("after scrolling");
			} catch (WebDriverException e) {
				if (!e.getMessage().contains("Failed to find scrollable visible parent with 2 visible children")) {
					e.printStackTrace();
					throw new WebDriverException(e);
				} else {
					log.warn("Failed to find scrollable visible parent with 2 visible children");
				}
			}
		}
	 wait.until(ExpectedConditions.visibilityOf(elem)).click();
	}
```

**Comment by mykola-mokhnach** [comment]
Try to set **simpleIsVisibleCheck** capability to false

**Comment by mykola-mokhnach** [comment]
Report the issue directly to https://github.com/facebook/WebDriverAgent/issues if this does not help

**Comment by derunewige** [comment]
Change **simpleIsVisibleCheck** to false does not help. And also, with set to false other errors will occur. 

Do they know Appium at the WDA github - should I mention something special? I guess they have no idea which changes were made between appium 1.6.4 and 1.6.5!?

**Comment by mykola-mokhnach** [comment]
Appium log shows REST communication between the client and the server - this is what is important. 

Yes, they know about Appium and we are also committing fixes and features into WDA project.

However, I'd also try ["mobile: scroll" method](https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios-xctest-mobile-gestures.md) with different parameters first.

**Comment by derunewige** [comment]
It seems to work for one test case with 

```
JavascriptExecutor js = driver;
Map<String, Object> params = new HashMap<>();
params.put("name", elem.getAttribute("name"));
params.put("toVisible", "true");
js.executeScript("mobile: scroll", params);
```
I still have to try all the others.

Which is the preferred/suggested way to do swiping/scrolling?
This script executors or TouchActions? Is it a bug that TouchActions are not working?
Does it relate to WDA now?

**Comment by mykola-mokhnach** [comment]
TouchActions invokes the same "mobile:" actions under the hood, since XCTest itself does not provide any external interfaces to implement TouchActions. So I think it's OK to use "mobile:" call for now until we have some better approach implemented by Apple
