### ISSUE TITLE
WDA disconnects on switching to offline mode

### ISSUE THREAD

**Issue by mayureshshirodkar** [appium/appium#8624]
## The problem

WDA gets disconnected on switching to offline mode, and doesn't reconnect.As a result further testcases fail and further commands.

## Environment

* Appium version (or git revision) that exhibits the issue: v1.6.5
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MacOS 10.12.4
* Mobile platform/version under test: iOS 10.2.1 
* Real device or emulator/simulator:iPhone 6
* Appium CLI or Appium.app|exe: CLI

## Details

**[debug] [XCUITest] Connection to WDA timed out
[debug] [iProxy] recv failed: Operation not permitted**
[HTTP] --> POST /wd/hub/session/0286024c-b89b-4e50-bedb-ce914c6c5217/element {"using":"xpath","value":"//*[contains(@class,'offline-mode-message')]"}
[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["xpath","//*[contains(@class,'offline-mode-message')]","0286024c-b89b-4e50-bedb-ce914c6c5217"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[MJSONWP] Encountered internal error running command: Error: Error while executing atom: Remote debugger is not connected
    at XCUITestDriver.callee$0$0$ (../../../lib/commands/web.js:79:11)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at runMicrotasksCallback (internal/process/next_tick.js:58:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[HTTP] <-- POST /wd/hub/session/0286024c-b89b-4e50-bedb-ce914c6c5217/element 500 7 ms - 231 

## Link to Appium logs

https://gist.github.com/mayureshshirodkar/02ab59087fc9c560faf6a83d6daeb621

## Code To Reproduce Issue [ Good To Have ]
Steps:
Swipe up to reveal the control center
Click on the Airplane Mode
Close the Control center

				Base.swipeUp();
				Base.clickElementNative("//*[@name='Airplane Mode']");
				tapNativeElementViaCoordinates(100, 10);

**Comment by mykola-mokhnach** [comment]
This is the expected behaviour for now, since iproxy cannot work with idevice if it switched to airplane mode. Probably, there is some way to workaround this, however I don't have any idea yet about how it would be possible.

**Comment by mayureshshirodkar** [comment]
Do you if this is recent change, which has come with version 1.6.5?
As i used the same script for 1.6.3,1.6.4.

**Comment by mykola-mokhnach** [comment]
So you want to say exactly the same code was working without problems before and unexpectedly stopped working after update to Appium 1.6.5?

**Comment by mayureshshirodkar** [comment]
Yup... I have been using the offline mode script for sometime now without issues, and it suddenly stops working since 1.6.5.

**Comment by mykola-mokhnach** [comment]
This field is empty:
> Last Appium version that did not exhibit the issue

**Comment by mayureshshirodkar** [comment]
@mykola-mokhnach  i tried few runs on Mobile and Wifi, and it seems to be working fine with 1.6.5.
Seems to be a Phone issue or a network issue.
Closing this issue as the issue is not related to Appium.
