### ISSUE TITLE
Bootstrap Error IOS

### ISSUE THREAD

**Issue by amusharraf** [appium/appium#8626]
Whenever I try to run a test on my machine, the test does not start and instead i get the following error:

**WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: Command 'Scripts/bootstrap.sh -d' exited with code 133**

I know the test is functional because when I run the test on another Mac, it runs properly.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS El Captain
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS 10.2
* Real device or emulator/simulator: Xcode Simulator
* Appium CLI or Appium.app|exe:

Appium Logs:
https://gist.github.com/anonymous/4d55075cccff54a135e698f676725b36

**Comment by mykola-mokhnach** [comment]
Do you have carthage installed on the machine?
What is the command line output if you run 

```bash
cd /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
bash -x Scripts/bootstrap.sh -d
```

**Comment by amusharraf** [comment]
bash: Scripts/bootstrap.sh: No such file or directory

**Comment by amusharraf** [comment]
how do i install carthage?

**Comment by amusharraf** [comment]
I'm running the command brew install carthage

**Comment by amusharraf** [comment]
i keep getting no such file or directory

**Comment by mykola-mokhnach** [comment]
changed the path in my comment above to the one that you need

**Comment by amusharraf** [comment]
**This is what i get:**


+ set -e
+ export PATH=/Users/automationadmin/.nvm/versions/node/v5.12.0/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/opt/android-sdk/build-tools:/usr/local/opt/android-sdk/platform-tools:/usr/local/opt/android-sdk/tools:/usr/local/bin
+ PATH=/Users/automationadmin/.nvm/versions/node/v5.12.0/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/opt/android-sdk/build-tools:/usr/local/opt/android-sdk/platform-tools:/usr/local/opt/android-sdk/tools:/usr/local/bin
+ BOLD='\033[1m'
+ [[ ! -f Scripts/bootstrap.sh ]]
+ getopts ' i d D h ' option
+ case "$option" in
+ FETCH_DEPS=1
+ getopts ' i d D h ' option
+ [[ -n x ]]
+ fetch_and_build_dependencies
+ echo -e '\033[1mFetching dependencies'
Fetching dependencies
+ assert_has_carthage
+ command -v carthage
+ cmp -s Cartfile.resolved Carthage/Cartfile.resolved
+ carthage bootstrap
dyld: Symbol not found: __TMV6Result8AnyError
  Referenced from: /usr/local/Cellar/carthage/0.23.0/bin/../Frameworks/CarthageKit.framework/Versions/Current/Frameworks//ReactiveSwift.framework/ReactiveSwift
  Expected in: /Library/Frameworks/CarthageKit.framework/Versions/Current/Frameworks/Result.framework/Versions/A/Result
 in /usr/local/Cellar/carthage/0.23.0/bin/../Frameworks/CarthageKit.framework/Versions/Current/Frameworks//ReactiveSwift.framework/ReactiveSwift
Scripts/bootstrap.sh: line 45: 57475 Trace/BPT trap: 5       carthage bootstrap $USE_SSH

**Comment by amusharraf** [comment]
the path is pointing to the VMs that i have to run android tests i think

**Comment by mykola-mokhnach** [comment]
It's a problem with your carthage installation. This is what google shows to me:
https://github.com/Carthage/Carthage/issues/1044

**Comment by amusharraf** [comment]
Thank you very much!! I finally fixed everything.
