### ISSUE TITLE
[Error Code] Unknown device or simulator UDID: '************2eaa7a7f0946d5be85e28d83da'

### ISSUE THREAD

**Issue by karbon62** [appium/appium#8627]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

Appium version 1.0.2-beta.2
Mac 10.12.5
iPhone 5s | 10.3
Real device
Appium CLI

## Details

Running my script locally while also running Appium via Terminal. I continue to see the errors of "Un known UDID". I have the device connected also. 

## Link to Appium logs

https://gist.github.com/karbon62/590d9f4a7585392b1523dd4c6206ef8a

**Comment by mykola-mokhnach** [comment]
what is the output of 

```
system_profiler SPUSBDataType 
```

command on the computer whether the phone is connected?

**Comment by karbon62** [comment]
The I've linked it here: https://gist.github.com/karbon62/749e4e0c8781c47ff7acd80815180c83

**Comment by karbon62** [comment]
I'd just like to make it clear that I am using a real device to test. I've added that in the Appium settings and also in my script.

**Comment by mykola-mokhnach** [comment]
I don't see the ID of any iOS device in the command output - it is either not connected or is not functioning properly.

**Comment by karbon62** [comment]
Any suggestions on how to fix this? Would it be something from Xcode that I have misconfigured? I can run appium and the app loads on the phone.

**Comment by lavi-xu** [comment]
@karbon62 

It could be that appium could not find the file where it's for idevice_id.
Please add the correct PATH before run appium for a try.

**Comment by karbon62** [comment]
@lavi-xu I've included the PATH and the device ID if thats what you mean. The App installs on the device as well as on the simulator, it just refuses to run my script.

**Comment by imurchie** [comment]
Appium uses `idevice_id` (part of `libimobiledevice`) to determine the availability of the device. Can you run `idevice_id -l`? It seems that it is not finding anything.

If nothing is found, could you reinstall `libimobiledevice` (`brew uninstall --ignore-dependencies libimobiledevice && brew install libimobiledevice --HEAD`) and try again to get the list?

**Comment by karbon62** [comment]
@imurchie I reinstalled the library and have also run idevice_id -l and its also acknowledged it. Running it again for a second time.

**Comment by karbon62** [comment]
@imurchie other issues seemed to have spawned. Now receiving Error Code 65: https://gist.github.com/karbon62/f5e156b1d142c8a4d01e2a4edb0b5edf

**Comment by imurchie** [comment]
That is most likely a code signing issue now. I'm closing this one since it seems to be resolved, and muddying the issue with other issues is a bad thing.

**Comment by Schumin** [comment]
I had similar issue. My working environment stopped working all of a sudden. I tried everything mentioned above with no luck. Out of sheer frustration, I re-entered the same UDID again in the capabilities and everything was back to working. Not sure what caused or what fixed the issue.

**Comment by BShivShankar** [comment]
I have solved the problem by setting PATH in run configuration in eclipse

In terminal type 'echo $PATH' and copy the path
Go to eclipse and select which class file you have to run and select run configuration
Click on environment - select new
Name as 'PATH' and value as 'paste the path you have in terminal'
Now do apply and run will works
Below is the code to run appium server from script in eclipse for real iOS device, I ran and worked on iphone X

public static AppiumDriver setUp() throws Exception {
AppiumServiceBuilder builder = new AppiumServiceBuilder()
.withAppiumJS(new File("/usr/local/lib/node_modules/appium/build/lib/main.js"))
.usingDriverExecutable(new File("/usr/local/bin/node"))
.withArgument(GeneralServerFlag.LOG_LEVEL, "info")
.withIPAddress("127.0.0.1")
.usingPort(4723);

			service = AppiumDriverLocalService.buildService(builder);
			service.start();
			   
			DesiredCapabilities capabilities = new DesiredCapabilities();
			capabilities.setCapability("appium-version", "1.8");
			capabilities.setCapability("platformName", "iOS");
			capabilities.setCapability("app", "/Users/user/Downloads/test.ipa");
		capabilities.setCapability(CapabilityType.PLATFORM, "Mac");
			capabilities.setCapability("device", "iPhone");
			capabilities.setCapability("deviceName", "iPhone X");
		capabilities.setCapability("udid","de914cb8de4d88987aad5151709fc3f5b39462c6");
			capabilities.setCapability("platformVersion", "11.26");
			capabilities.setCapability("bundleId", "com....");
driver = new IOSDriver<>(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
return driver;
}
