### ISSUE TITLE
UiAutomator2 Could not proxy command to remote server. Original error: Error: socket hang up

### ISSUE THREAD

**Issue by mio4kon** [appium/appium#8631]
## The problem

Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: Error: socket hang up

## Environment

Appium : 1.6.5

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Appium logs
[log](https://gist.github.com/mio4kon/b253e4bcadb3e633fd9912d3e519cb56)

**Comment by mykola-mokhnach** [comment]
It looks like a problem with your device. UIA2 server simply stops responding to requests there.

**Comment by mio4kon** [comment]
@mykola-mokhnach  
my device:`xiaomi 4c`
android version: `7.0`

**Comment by dpgraham** [comment]
Is this still happening for you?

**Comment by mio4kon** [comment]
has solved, because of the phone kill the ui2 server

**Comment by BeggarMainFact** [comment]
Hi, how you fix it? How to disable phone to kill the ui2 server?

**Comment by KrishnaprabhaSNaik** [comment]
@mio4kon I am also facing the same issue. How did u fix it ? Please help me !!

**Comment by vikramvi** [comment]
This issue happening for me as well, @mio4kon please clarify how did you solve this ?

appium server version : 1.7.2-beta2

**Comment by PrasadMadge** [comment]
Even I am facing the same issue.

Temporary solution is to unistall uiautomator2.server , uiautomator2.server.test apk from the device and test it again.

But this issue seems to happen again like once in 10 times , any permanent solution ?

**Comment by CYsuncheng** [comment]
@mio4kon I am also facing this issue , please tell me how to solve this problem ???

**Comment by mio4kon** [comment]
@CYsuncheng check if the appium server on the phone is killed

**Comment by mio4kon** [comment]
@PrasadMadge @vikramvi  @KrishnaprabhaSNaik  @BeggarMainFact check if the appium server on the phone is killed, open Background freeze

**Comment by mio4kon** [comment]
@PrasadMadge @vikramvi  @KrishnaprabhaSNaik  @BeggarMainFact check if the appium server on the phone is killed, open Background freeze

**Comment by auto-mator** [comment]
Still occurring for me...
