### ISSUE TITLE
Cannot click android webview element

### ISSUE THREAD

**Issue by AlexDingSZ** [appium/appium#8632]
## The problem
It's a android hybrid app, when switch to web view , click webelement , there is no response and appium error info.  what's wrong with my code ? or how can I  click the web element correctly?
## Environment

Appium server  1.6.5
appium-chromedriver  2.9.4
 WebView in com.tencent.mm (53.0.2785.49)

## Link to Appium logs

[HTTP] --> POST /wd/hub/session/da2c645d-16d0-4222-a032-5c62d99d8937/element {"u
sing":"css selector","value":"li.fl.pointer.active > p"}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [JSONWP Proxy] Proxying [POST /wd/hub/session/da2c645d-16d0-4222-a032-5c
62d99d8937/element] to [POST http://127.0.0.1:8000/wd/hub/session/b89ea376ce0325
88352b875d979470d1/element] with body: {"using":"css selector","value":"li.fl.po
inter.active > p"}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"b89ea376ce032
588352b875d979470d1","status":0,"value":{"ELEMENT":"0.4743664131891554-2"}}
[JSONWP Proxy] Replacing sessionId b89ea376ce032588352b875d979470d1 with da2c645
d-16d0-4222-a032-5c62d99d8937
[HTTP] <-- POST /wd/hub/session/da2c645d-16d0-4222-a032-5c62d99d8937/element 200
 100 ms - 106
[HTTP] --> POST /wd/hub/session/da2c645d-16d0-4222-a032-5c62d99d8937/element/0.4
743664131891554-2/click {"id":"0.4743664131891554-2"}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [JSONWP Proxy] Proxying [POST /wd/hub/session/da2c645d-16d0-4222-a032-5c
62d99d8937/element/0.4743664131891554-2/click] to [POST http://127.0.0.1:8000/wd
/hub/session/b89ea376ce032588352b875d979470d1/element/0.4743664131891554-2/click
] with body: {"id":"0.4743664131891554-2"}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"b89ea376ce032
588352b875d979470d1","status":0,"value":null}
[JSONWP Proxy] Replacing sessionId b89ea376ce032588352b875d979470d1 with da2c645
d-16d0-4222-a032-5c62d99d8937
[HTTP] <-- POST /wd/hub/session/da2c645d-16d0-4222-a032-5c62d99d8937/element/0.4
743664131891554-2/click 200 249 ms - 76
[HTTP] --> POST /wd/hub/session/da2c645d-16d0-4222-a032-5c62d99d8937/element {"u
sing":"css selector","value":"textarea"}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [JSONWP Proxy] Proxying [POST /wd/hub/session/da2c645d-16d0-4222-a032-5c
62d99d8937/element] to [POST http://127.0.0.1:8000/wd/hub/session/b89ea376ce0325
88352b875d979470d1/element] with body: {"using":"css selector","value":"textarea
"}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"b89ea376ce032
588352b875d979470d1","status":0,"value":{"ELEMENT":"0.4743664131891554-3"}}
[JSONWP Proxy] Replacing sessionId b89ea376ce032588352b875d979470d1 with da2c645
d-16d0-4222-a032-5c62d99d8937
[HTTP] <-- POST /wd/hub/session/da2c645d-16d0-4222-a032-5c62d99d8937/element 200
 23708 ms - 106
[HTTP] --> POST /wd/hub/session/da2c645d-16d0-4222-a032-5c62d99d8937/element/0.4
743664131891554-3/value {"id":"0.4743664131891554-3","value":["hhhh"]}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [JSONWP Proxy] Proxying [POST /wd/hub/session/da2c645d-16d0-4222-a032-5c
62d99d8937/element/0.4743664131891554-3/value] to [POST http://127.0.0.1:8000/wd
/hub/session/b89ea376ce032588352b875d979470d1/element/0.4743664131891554-3/value
] with body: {"id":"0.4743664131891554-3","value":["hhhh"]}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"b89ea376ce032
588352b875d979470d1","status":0,"value":null}
[JSONWP Proxy] Replacing sessionId b89ea376ce032588352b875d979470d1 with da2c645
d-16d0-4222-a032-5c62d99d8937
[HTTP] <-- POST /wd/hub/session/da2c645d-16d0-4222-a032-5c62d99d8937/element/0.4
743664131891554-3/value 200 571 ms - 76

## Code To Reproduce Issue [ Good To Have ]
@Test
public void test(){
	//start apk
	this.apkStart("G6N7MBIZJ7YHLZO7", "com.tencent.mm", "com.tencent.mm.ui.LauncherUI", "127.0.0.1:4723");
	// switch to wechat h5 web page
	 river.context("WEBVIEW_com.tencent.mm:tools");
	 String page = driver.getPageSource();             
	WebElement ele = driver.findElement(By.cssSelector("#body > div:nth-child(2) > ul > li:nth-child(3) > h3"));
	// this can get h5 web page element attribute correctly
	String text = ele.getText();
	System.out.println(text);
	// this locator is right but can not click this web element and get no response ,there is no error log too.
	driver.findElementByCssSelector("li.fl.pointer.active > p").click();
	// can sendKeys 
	driver.findElementByCssSelector("textarea").sendKeys("bbbbbb");

}

public void apkStart(String udid, String packageName, String activityName, String appiumServer) {

	DesiredCapabilities capabilities = new DesiredCapabilities();

	capabilities.setCapability("deviceName", udid);
	capabilities.setCapability("udid", udid);		
	capabilities.setCapability("noReset", "true");
	capabilities.setCapability("fullReset", "false");
	capabilities.setCapability("platformVersion", "6.0");
	capabilities.setCapability("platformName", "Android");
	capabilities.setCapability("newCommandTimeout", 24000);
	capabilities.setCapability("device", "selendroid");		
	capabilities.setCapability("unicodeKeyboard", "True");
	capabilities.setCapability("resetKeyboard", "True");		
	capabilities.setCapability("appPackage", packageName);
	capabilities.setCapability("appActivity", activityName);	
	
	ChromeOptions options = new ChromeOptions();
		  options.setExperimentalOption("androidProcess", "com.tencent.mm:tools");
		  capabilities.setCapability(ChromeOptions.CAPABILITY, options);
	
	try {
		System.out.println("http://" + ConfigUtil.getBoxApkAppiumServer() + "/wd/hub");
		driver = new AndroidDriver<WebElement>(new URL("http://" + appiumServer + "/wd/hub"), capabilities);
		wait = new WebDriverWait(driver, 10);
	} catch (MalformedURLException e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
	}
}

**Comment by mykola-mokhnach** [comment]
Add clicks listener on the webpage under test and check at which position/element on the page the click actually happens. It might be the locator matches more than one element or there are some invisible overlays on the page.

**Comment by AlexDingSZ** [comment]
@mykola-mokhnach  thanks , but how to add clicks listener? Is there any sample ?

**Comment by mykola-mokhnach** [comment]
better to discuss it with your developers. this action has nothing to do with Appium.
