### ISSUE TITLE
WebDriverAgent fails to build with xCode 9 - beta

### ISSUE THREAD

**Issue by NicolaRettich1** [appium/appium#8633]
## The problem

I was trying to execute our crossplatform appium tests using xCode 9 beta and see if it still works. Unfortunately, the WebDriverAgent does not build with the new xCode version. xCode tells me that "'new' is unavailable: Use XCUIElementQuery to create XCUIElement instances." for XCUIElement+FBClassChain.m 
Is there a possibility to make it run without waiting for appium to be updated?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Desktop OS/version used to run Appium: OSX Sierra
* Node.js version (unless using Appium.app|exe): 7.8.0
* Mobile platform/version under test: iOS 10.3
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI

![screen shot 2017-06-08 at 13 58 56](https://user-images.githubusercontent.com/18442286/26927649-0b946eb4-4c53-11e7-9b6f-a485322925bd.png)

**Comment by mykola-mokhnach** [comment]
Please report the issue directly to https://github.com/facebook/WebDriverAgent/issues

> Is there a possibility to make it run without waiting for appium to be updated?
Yes, you can fix WDA compilation for on Xcode9-beta yourself
