### ISSUE TITLE
Why new appium Version 1.0.2-beta.2 (1.0.2-beta.2) can not record testcases?

### ISSUE THREAD

**Issue by msmirzazadeh** [appium/appium#8634]
## The problem

I'm new appium ( appium desktop for mac os ) user.
in the older version of appium, the inspector had a recorder function.
why is recorder function not in the new inspector?
which tool can you suggest me, to record and translate UI operation in Java such as the older recorder function?

## Environment

* Appium version (or git revision) that exhibits the issue:
Version 1.0.2-beta.2 (1.0.2-beta.2)
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
OSX 10.12.5

**Comment by dpgraham** [comment]
Appium Desktop is a complete rewrite and some of the features from the old inspector haven't been included (yet). I don't know of any other tool that does recording.

**Comment by msmirzazadeh** [comment]
Find why to use appium inspector recorder of appium Desktop Version 1.5.3 (Ara):
run appium inspector of desktop Version 1.5.3 (Ara) with suitable DesiredCapabilities when appium Version 1.0.2-beta.2 server was started
