### ISSUE TITLE
Problem Scroll java (Automation iOS)

### ISSUE THREAD

**Issue by HugoPA18** [appium/appium#8635]
JavascriptExecutor js = (JavascriptExecutor) driver; HashMap<String, String> scrollObject = new HashMap<String, String>(); scrollObject.put("direction", "down"); scrollObject.put("element", ((RemoteWebElement) element).getId()); js.executeScript("mobile: scroll", scrollObject);

I want to give it a break or give it a speed to the duration.

Help!

**Comment by saikrishna321** [comment]
@HugoPA18  pls raise question in discuss.appium.io @SrinivasanTarget pls close

**Comment by mykola-mokhnach** [comment]
Only **dragFromToForDuration** action supports duration argument.
