### ISSUE TITLE
BadStatusLine: ' '

### ISSUE THREAD

**Issue by amusharraf** [appium/appium#8636]
I am running tests on two simulators, one simulator on my current machine and my second simulator on another machine. I am using ssh to connect the two and when i run a test, all the appium stuff are successful but the simulator on the second machine does not start up instead i get the error:

BadStatusLine: ' '

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Desktop OS/version used to run Appium: Mac OS Sierra and El Captain
* Mobile platform/version under test: iOS 10.2
* Real device or emulator/simulator: Simulator

**Comment by imurchie** [comment]
This is generally Python's way of letting you know that the connection was lost.

Without the Appium server logs there is little that can be said, else.

**Comment by amusharraf** [comment]
First Device:
https://gist.github.com/amusharraf/48fe0ca93132aa53a9ea53bd6230c12a

Second Device:
[Appium] Welcome to Appium v1.6.4 (REV 0a95e77000515c1156be593642dd4e452f2f098e)
[Appium] Appium REST http interface listener started on 0.0.0.0:4723

**Comment by amusharraf** [comment]
anyone?

**Comment by amusharraf** [comment]
Fixed the issue. just go to the second device turn on appium. then verify appium is up by typing in the url with the ip and port in the main machine, and remote machine
