### ISSUE TITLE
Appium returns wrong top left point of a WebElement in Android Cordova Application

### ISSUE THREAD

**Issue by binhuang6** [appium/appium#8639]
## The problem

The WebElement top left point value returned from Appium  is different from the top left point value displayed on the Android sdk UI Automator tool.

## Environment

•Appium version : 1.6.5
•Desktop OS/version used to run Appium: Windows 7
•Node.js version (unless using Appium.app|exe): v6.3.0
•Mobile platform/version under test: Android 6.0.1
•Real device or emulator/simulator: Samsung Galaxy Tab S2
•Appium CLI or Appium.app|exe: appium 1.6.5 via command mode

## Details
 Call Appium findElement to find a WebElement successfully, call Appium WebElement getLocation to get the WebElement's top left point, and found the top left point value are different from the top left point value displayed on the Android sdk UI Automator tool.

The Android sdk UI Automator tool is from Android sdk located under Android\sdk\tools, the name is : uiautomatorviewer.bat.

## Link to Appium logs

https://gist.github.com/binhuang6/90fa7af392fa42de272745ed1dcc1af2

## Code To Reproduce Issue [ Good To Have ]

        driver.context("WEBVIEW_com.corp.app");
		WebElement root=driver.findElement(By.xpath("//*[@id='rootid']"));
        java.util.List<WebElement> children = root.findElements(By.xpath(".//*"));
        for(WebElement child:children)
        {       	
        		if(child.isDisplayed())
        		{
     				Dimension adim = child.getSize();
    				Point apt = child.getLocation();
    				System.out.println("dimensions: " + adim.toString());
    				System.out.println("location:   " + apt.toString());
         		}
        }

**Comment by dpgraham** [comment]
I'm not too sure how the two calculate the coordinates and if they calculate them differently.

Is this causing issues for you? It could be that they just report different units of measure.
