### ISSUE TITLE
keepAlive Failure Exception in middle of iOS test run

### ISSUE THREAD

**Issue by Elangopalakrishnan** [appium/appium#8643]
## keepAlive Failure Exception

I'am getting the keepAlive failure exception in middle of test run, 

iOS automation using appium with C# scripting, running from MTM.

Eg, I'm executing one test case, in that i missed the one xpath, then it should return No Such an Element Exception but i'm getting the Webdriver Exception with error message 
**"A exception with a null response was thrown sending an HTTP request to the remote WebDriver server for URL http://17.18.45.21:4723/wd/hub/session/3c75a67b-5965-4935-9c96-535e86d10cab/element. The status of the exception was KeepAliveFailure, and the message was: The underlying connection was closed: A connection that was expected to be kept alive was closed by the server."** 

I also have checked whether appium server is in active state or not in remote machine. It is running fine. 

I don't know where is the problem, in appium or visual studio ?

Can any one suggest me what is the reason of getting this kind of exception.
How we can solve this?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4 & 1.6.5 & 1.6.6 beta
* Desktop OS/version used to run Appium:EI Capitan 10.11.6 
* Mobile platform/version under test: iOS 10.2.1
* Real device or emulator/simulator: Real and Simulators

## Code To Reproduce Issue [ Good To Have ]

I'm connecting the mac machine from my windows machine by using below code:

var capabilities = new DesiredCapabilities();
                    capabilities.SetCapability(CapabilityType.BrowserName, "Safari");
                    capabilities.SetCapability("automationName", "XCUITest");
                    capabilities.SetCapability(MobileCapabilityType.PlatformName, "iOS"); 
                    capabilities.SetCapability(MobileCapabilityType.PlatformVersion, "10.2.1");
                    capabilities.SetCapability("realDeviceLogger", 
                    "/usr/local/lib/node_modules/deviceconsole/deviceconsole");
                    capabilities.SetCapability("wdaLocalPort", "8200");
                    capabilities.SetCapability("newCommandTimeout", "120000");
                    capabilities.SetCapability("clearSystemFiles", "true"); 
AppDriver = new IOSDriver<AppiumWebElement>(new Uri("http://17.18.45.21:4723/wd/hub"), capabilities, TimeSpan.FromSeconds(1800));

Thanks in advance!
Elango

**Comment by dpgraham** [comment]
Can you provide the Appium logs?

**Comment by Elangopalakrishnan** [comment]
It is because of webdriver 3.4.0,

**Comment by rutin31** [comment]
Hi
I have the same problem in case  running test from visual studio on IOS real device
Is anyone know how to solve this?
