### ISSUE TITLE
[UiAutomator2] Session is deleted when asking for the Android Version

### ISSUE THREAD

**Issue by luisromanbcn** [appium/appium#8645]
## The problem

I just started to use UiAutomator2 in my tests and I have a bean in my project to ask for the Android Version of the device but if I use UiAutomator2 it doesn't work and the session closes, if I mock the android version the app starts correctly but looks there is a problem when ask to the server for the android version when using the uiautomator2.

## Environment

* Appium version (or git revision) that exhibits the issue: BETA 1.6.6
* Desktop OS/version used to run Appium: macOS Sierra
* Mobile platform/version under test: Nexus 5 API 23
* Real device or emulator/simulator: Emulator

## Link to Appium logs

https://gist.github.com/luisromanwp/1d65881221d269ba5486345f2834788d

## Code To Reproduce Issue [ Good To Have ]

@Bean
  public Double androidVersion() {
    String version = driver.getCapabilities().getCapability(PLATFORM_VERSION).toString();
    return Double.valueOf(version.substring(0, 2));
  }

**Comment by luisromanwp** [comment]
No, it's just because I use emulator and real device and it works putting in the udid the emulator or device one

**Comment by dpgraham** [comment]
I don't see any issues in the logs. Where is the problem?

**Comment by luisromanwp** [comment]
@dpgraham the problem is when I use this code to get the android version of the device "driver.getCapabilities().getCapability(PLATFORM_VERSION).toString();"
In that moment the session is finished

**Comment by dpgraham** [comment]
* Have you confirmed that it only happens when you get the Android version? (ie: if you comment out that block of code does it work)
* What client code are you calling before that block of code?

**Comment by luisromanwp** [comment]
@dpgraham 
- Yes, if I comment that block the test works, that block is returning a null so that's why the test finishes
- It happened to me using Appium 1.6.5 and Appium 1.6.6-BETA3 with java-client 4.1.2 and 5.0.0-BETA9

**Comment by dpgraham** [comment]
What do you see when you setup a breakpoint in it? What does `driver.getCapabilities()` return? I think you may just need to update your code because `getCapability(PLATFORM_VERSION)` returns null now.
