### ISSUE TITLE
The "android" command is deprecated

### ISSUE THREAD

**Issue by alexandermomot** [appium/appium#8652]
## The problem

When you want to set an AVD to start when the server starts, you can set the "Launch AVD" parameter in the "Launch Device" menu subset (Android settings). The setting invokes  "./android" binary file from the SDK, then parsing the output and lets you choose from the list. As I can see right now, when I'm using android studio with most recent SDK, that binary says that:

```
*************************************************************************
The "android" command is deprecated.
For manual SDK, AVD, and project management, please use Android Studio.
For command-line tools, use tools/bin/sdkmanager and tools/bin/avdmanager
*************************************************************************
Running /Users/alex/Library/Android/sdk/tools/bin/avdmanager list avd

Available Android Virtual Devices:
  Name: nexus
  Device: Nexus 4 (Google)
  Path: /Users/alex/.android/avd/nexus.avd
  Target: Google APIs (Google Inc.)
  Based on: Android 5.1 (Lollipop) Tag/ABI: google_apis/x86
  Skin: nexus_4
  Sdcard: 1G
```

## Environment

* Version 1.5.3 (Ara)

## Details

Neither logs nor code to dublicate is necessary here

I would suggest to move forward and use brand new shell tools like sdkmanager and avdmanager

**Comment by mykola-mokhnach** [comment]
Appium version 1.5.3 is old not supported anymore. Please use 1.6.5
