### ISSUE TITLE
Not able to install iOS apps on real device: Error: Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65

### ISSUE THREAD

**Issue by vighneshpai-yml** [appium/appium#8654]
## The problem
Please help. I'm trying to install an iOS app on real device and I'm being thrown off with this error: Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65

## Environment variables set in appium
{
  "platformName": "iOS",
  "platformVersion": "10.3.1",
  "deviceName": "Mydevice",
  "udid": "#######<real device UDID>######",
  "bundleId": "<Real app bundle id, removing it due to security reasons>",
  "launchTimeout": 17500,
  "autoAcceptAlerts": true,
  "nativeInstrumentsLib": true
}

## Details
It's strange that I was able to run it without any modification last week, and today when I tried, I'm having this problem.

## Link to Appium logs
https://gist.github.com/vighneshpai-yml/ef1a807a9ffdb96266bb17063bfc406d

Please let me know in case you need any more info.

Appium v1.6.2
xcode: 8.3.1

**Comment by vighneshpai-yml** [comment]
Screw APPLE!!!! If you are getting this error then just restart your device. That's the solution I found and it worked here.

**Comment by mykola-mokhnach** [comment]
You can try https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/wda-custom-server.md to make your real device tests more stable in long-running perspective.
