### ISSUE TITLE
Test Appium with GBoard (iOS and Android)

### ISSUE THREAD

**Issue by aquintiliano** [appium/appium#8657]
## The problem

We're using Gboard on some iphones here and when we tried to sendText or setValue (java) an NoSuchElementException was thrown.

## Environment

* Appium 1.6.4 and 1.6.5
* OSX 10.12.5 (16F73)
* Node.js v6.9.1
* iOS
* Real device
* appium.app

## Code To Reproduce Issue [ Good To Have ]

((IOSElement) element).setValue("Some value");
// or
element.sendKeys("Some value");

**Comment by dpgraham** [comment]
Does it _never_ work or does it just sometimes not work?

**Comment by aquintiliano** [comment]
it never works

**Comment by dpgraham** [comment]
And you've confirmed that the same Appium code works without GBoard and stops working as soon as you start using GBoard?

**Comment by dpgraham** [comment]
Also, can you try getting the contents of the source prior to calling `((IOSElement) element).setValue("Some value");`?  

I think the issue may be that GBoard is blocking the UI somehow.

**Comment by dpgraham** [comment]
What does the source show? I just want to know if GBoard is preventing the app from reporting the source.

If you run a session using Appium Desktop (https://www.github.com/appium/appium-desktop/releases/latest) you can inspect the contents of the source through a user interface.

**Comment by aquintiliano** [comment]
if you are talking about the Appium Inspector, everything is there, I can see the textfield I am trying to set the text to, but still can't setText or setValue to it

**Comment by dpgraham** [comment]
Ok thanks @aquintiliano. We can put this on our backlog.

None of us on the team are too familiar with GBoard so we'd have to look into that more.

What's the impact of GBoard being incompatible with your Appium tests? Does it break test suites or is it just a nuisance because you can't test on devices with GBoard installed?

**Comment by poorvikamahesh** [comment]
@dpgraham 
I am trying to run a script on Android 7.1.2 using UIAutomator2 (uses a GBoard) on a Pixel device

Basically, I need to check the max number of characters accepted by a textbox (WebView Element)

I have tried using

element.sendKeys(value);
&
element.click();
driver.getKeyboard().sendKeys(value);

Both **sets** more than 100 characters in the textfield (though, manually the field accepts only 100 characters) and my script fails

I am unable to type in the text field using the keyboard. 

Not sure if this is related to the same issue, but it would be helpful if you can suggest a solution.

Thanks

P.S. element.sendKeys(value); was working as expected on Android 6.x device using UIAutomator

**Comment by dpgraham** [comment]
@poorvikamahesh I think our team is going to need to do some research on GBoard and how it interacts with Appium.

**Comment by amedvedjev** [comment]
@aquintiliano  @poorvikamahesh 
not sure but maybe temporarily help to split text into chars and enter one by one directly.
e.g. to enter "0"
```
((AndroidDriver) driver).pressKeyCode(AndroidKeyCode.KEYCODE_0);
```

**Comment by mykola-mokhnach** [comment]
The `sendKeys` API uses native calls for both iOS and Android, so there is nothing more that could be done there from Appium side. On Android it is also possible to use `mobile: type` helper, which enters the text using a custom IME.
