### ISSUE TITLE
I'm unable to unlock the iPhone locked screen using appium 

### ISSUE THREAD

**Issue by prashantkumar1041** [appium/appium#8658]
## The problem

1. My app uses the user's passcode/finger print to do authentication. 
2. Once the user comes to the page, app gives option of fingerprint if fingerprint is enrolled with iPhone. Otherwise, 'Continue with passcode' option is seen.
3. On tapping 'Continue with passcode', iPhone's lock screen appears and user have to enter the same password as to unlock the iPhone.
4. Now, here I'm not able to unlock the iPhone screen. And, unable to proceed further.
5. Neither, do I find any option to use fingerprint anyhow.

Please help me with this, atleast by using the passcode. If this feature is not yet implemented, is it possible to implement this feature.

## Environment

* Appium version: 1.6.4
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: 10.12.5
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: both
* Appium CLI or Appium.app|exe:

**Comment by dpgraham** [comment]
We added touchId (fingerprint) recently, but that still needs to be added to the Java client.

What happens when you try entering the passcode?

**Comment by mykola-mokhnach** [comment]
Apple XCTest does not contain any methods to work with UI when the screen is locked

**Comment by dpgraham** [comment]
@prashantkumar1041 The latest java client actually has support for touchId 

https://github.com/appium/java-client/releases

You can try that. The passcode issue can't be resolved as @mykola-mokhnach said, due to limitations.
