### ISSUE TITLE
Xcode 8.2.1, Appium 1.6.4, Mac OS Sierra 10.12.5

### ISSUE THREAD

**Issue by bdenli** [appium/appium#8659]
## Steps to Reproduce
- Run the test script using Eclipse Neon 3
- Simulator is launched
- Webdriver is installed
- app is installed
- opens the app but then immediately closes it

## Environment

* Appium version ( git revision) that exhibits the issue: 1.6.4
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS Sierra 10.12.5
* Node.js version (unless using Appium.app|exe): 8.1.0
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: simiulator
* Appium CLI or Appium.app|exe: 

## Link to Appium logs

MacBook-Pro:~$ appium &
[1] 24033
MacBook-Pro:~$ [Appium] Welcome to Appium v1.6.4
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"capabilities":{"alwaysMatch":{"deviceName":"iPhone 7","platformName":"iOS","app":"/Users/<userName>/<appName>.app","noReset":"true","platformVersion":"10.2","showXcodeLog":"true","automationName":"XCUITest"},"firstMatch":[]},"desiredCapabilities":{"deviceName":"iPhone 7","showXcodeLog":"true","automationName":"XCUITest","noReset":"true","platformVersion":"10.2","platformName":"iOS","app":"/Users/<userName>/<appName>.app"}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"deviceName":"iPhone 7","showXcodeLog":"true","automationName":"XCUITest","noReset":"true","platformVersion":"10.2","platformName":"iOS","app":"/Users/<userName>/<appName>.app"},null,{"alwaysMatch":{"deviceName":"iPhone 7","platformName":"iOS","app":"/Users/<userName>/<appName>.app","noReset":"true","platformVersion":"10.2","showXcodeLog":"true","automationName":"XCUITest"},"firstMatch":[]},null,null]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1497294870995 (15:14:30 GMT-0400 (EDT))
[Appium] Creating new XCUITestDriver (v2.27.2) session
[Appium] Capabilities:
[Appium]   deviceName: 'iPhone 7'
[Appium]   showXcodeLog: 'true'
[Appium]   automationName: 'XCUITest'
[Appium]   noReset: 'true'
[Appium]   platformVersion: '10.2'
[Appium]   platformName: 'iOS'
[Appium]   app: '/Users/<userName>/<appName>.app'
[debug] [XCUITest] XCUITestDriver version: 2.27.2
[BaseDriver] Capability 'noReset' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] Capability 'showXcodeLog' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] Session created with session id: 173a6f81-3266-4e4a-830c-ce132427d444
[debug] [XCUITest] Xcode version set to '8.2.1' (tools v8.3.2.0.1.1492020469)
[debug] [XCUITest] iOS SDK Version set to '10.2'
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1497294871193 (15:14:31 GMT-0400 (EDT))
[iOSSim] Constructing iOS simulator for Xcode version 8.2.1 with udid '65EC7788-3036-4C3C-B013-9C4325D8151D'
[XCUITest] Determining device to run tests on: udid: '65EC7788-3036-4C3C-B013-9C4325D8151D', real device: false
[BaseDriver] Using local app '/Users/<userName>/<appName>.app'
[debug] [BaseDriver] Event 'appConfigured' logged at 1497294871364 (15:14:31 GMT-0400 (EDT))
[debug] [XCUITest] Checking whether app '/Users/<user>/Documents/<appName>.app' is actually present on file system
[debug] [XCUITest] App is present
[debug] [iOS] Getting bundle ID from app '/Users/<userName>/Documents/<appName>.app': '<bundleId>'
[debug] [BaseDriver] Event 'resetStarted' logged at 1497294871367 (15:14:31 GMT-0400 (EDT))
[debug] [XCUITest] Reset: noReset is on. Leaving simulator as is
[debug] [BaseDriver] Event 'resetComplete' logged at 1497294871367 (15:14:31 GMT-0400 (EDT))
[debug] [iOSLog] Starting iOS 10.2 simulator log capture
[debug] [iOSLog] System log path: /Users/<userName>/Library/Logs/CoreSimulator/65EC7788-3036-4C3C-B013-9C4325D8151D/system.log
[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1497294871469 (15:14:31 GMT-0400 (EDT))
[XCUITest] Setting up simulator
[debug] [iOS] No reason to set locale
[debug] [iOS] No iOS / app preferences to set
[XCUITest] Simulator with udid '65EC7788-3036-4C3C-B013-9C4325D8151D' not booted. Booting up now
[debug] [iOSSim] Killing all iOS Simulators
[debug] [iOSSim] Using fkill to kill processes: 23986
[iOSSim] Starting simulator with command: open -Fn /Applications/Xcode_8_2_1.app/Contents/Developer/Applications/Simulator.app --args -CurrentDeviceUDID 65EC7788-3036-4C3C-B013-9C4325D8151D -ConnectHardwareKeyboard 0
[debug] [XCUITest] App '<bundleId>' is already installed. No need to reinstall.
[iOSSim] Simulator booted in 8451ms
[debug] [BaseDriver] Event 'simStarted' logged at 1497294880260 (15:14:40 GMT-0400 (EDT))
[debug] [BaseDriver] Event 'appInstalled' logged at 1497294880262 (15:14:40 GMT-0400 (EDT))
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1497294880264 (15:14:40 GMT-0400 (EDT))
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'
[debug] [XCUITest] Killing hanging processes
[debug] [XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=65EC7788-3036-4C3C-B013-9C4325D8151D -configuration Debug IPHONEOS_DEPLOYMENT_TARGET=10.2' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[debug] [XCUITest] Output from xcodebuild will be logged
[Xcode] Build settings from command line:
[Xcode] 
[debug] [XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[Xcode]     IPHONEOS_DEPLOYMENT_TARGET = 10.2
[Xcode] 
[Xcode] 
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[Xcode] === BUILD TARGET WebDriverAgentLib OF PROJECT WebDriverAgent WITH CONFIGURATION Debug ===
[Xcode] 
[Xcode] 
[Xcode] Check dependencies
[Xcode] 
[Xcode] 
[Xcode] 
[Xcode] === BUILD TARGET WebDriverAgentRunner OF PROJECT WebDriverAgent WITH CONFIGURATION Debug ===
[Xcode] 
[Xcode] 
[Xcode] Check dependencies
[Xcode] 
[Xcode] 
[Xcode] 
[Xcode] ** TEST BUILD SUCCEEDED **
[Xcode] 
[Xcode] 
[debug] [XCUITest] Log file for xcodebuild test: /Users/<userName>/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/0FDF896F-2F9A-467C-BE89-86D7297C2399/Session-WebDriverAgentRunner-2017-06-12_151442-3rgbOX.log
[Xcode] 2017-06-12 15:14:42.661 xcodebuild[24214:1564756] [MT] IDETestOperationsObserverDebug: (3BB77128-4FC5-48A6-B48F-0C18AED339C5) Beginning test session WebDriverAgentRunner-3BB77128-4FC5-48A6-B48F-0C18AED339C5 at 2017-06-12 15:14:42.661 with Xcode 8C1002 on target <DVTiPhoneSimulator: 0x7fd4c9109cd0> {
[Xcode] 		SimDevice: SimDevice : iPhone 7 (65EC7788-3036-4C3C-B013-9C4325D8151D) : state={ Booted } deviceType={ SimDeviceType : com.apple.CoreSimulator.SimDeviceType.iPhone-7 } runtime={ SimRuntime : 10.2 (14C89) - com.apple.CoreSimulator.SimRuntime.iOS-10-2 }
[Xcode] } (10.2 (14C89))
[Xcode] 2017-06-12 15:14:42.661 xcodebuild[24214:1564764]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
[Xcode] /Users/<userName>/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/0FDF896F-2F9A-467C-BE89-86D7297C2399/Session-WebDriverAgentRunner-2017-06-12_151442-3rgbOX.log
[Xcode] 
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"state\" : \"success\",\n    \"os\" : {\n      \"name\" : \"iOS\",\n      \"version\" : \"10.2\"\n    },\n    \"ios\" : {\n      \"simulatorVersion\" : \"10.2\",\n      \"ip\" : \"192.168.1.215\"\n    },\n    \"build\" : {\n      \"time\" : \"Jun 12 2017 13:57:47\"\n    }\n  },\n  \"sessionId\" : \"0E998FA9-10AE-47B9-A5CE-75F60DDD15C0\",\n  \"status\" : 0\n}"
[debug] [XCUITest] WebDriverAgent running on ip '192.168.1.215'
[debug] [XCUITest] WebDriverAgent successfully started after 9554ms
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1497294889946 (15:14:49 GMT-0400 (EDT))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"<bundleId","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}

## Code To Reproduce Issue

import unittest
import os
from appium import webdriver

class Test(unittest.TestCase):

    def setUp(self):
        
        # set up appium
        app = os.path.abspath('/Users/<username>/Documents/<appName>.app')
        self.driver = webdriver.Remote(
            command_executor='http://127.0.0.1:4723/wd/hub',
            desired_capabilities={
                'automationName': 'XCUITest',
                'app': app,
                'platformName': 'iOS',
                'platformVersion': '10.2',
                'deviceName': 'iPhone 7',
                'noReset': 'true',
                'showXcodeLog': 'true'
            })

        pass

    def tearDown(self):
        pass

    def testName(self):
        pass

if __name__ == "__main__":
    # import sys;sys.argv = ['', 'Test.testName']
    unittest.main()

**Comment by mykola-mokhnach** [comment]
What happens if you open the app manually? Do you see any errors/exceptions in the device log?

**Comment by bdenli** [comment]
Same thing happens when I open app manually on the iOS simulator. Here is the device log:

Jun 12 16:55:51 MacBook-Pro com.apple.CoreSimulator.SimDevice.65EC7788-3036-4C3C-B013-9C4325D8151D.launchd_sim[24058] (UIKitApplication:com.abc.ios.dev[0x7d45][24586]): Program specified by service does not contain one of the requested architectures: 
Jun 12 16:55:51 MacBook-Pro SpringBoard[24075]: [Common] Unable to get pid for 'UIKitApplication:com.abc.ios.dev[0x7d45]': No such process (err 3)
Jun 12 16:55:51 MacBook-Pro SpringBoard[24075]: [Common] Bootstrapping failed for <FBApplicationProcess: 0x7faf67441900; <bundleId>; pid: -1>
Jun 12 16:55:52 MacBook-Pro com.apple.CoreSimulator.SimDevice.65EC7788-3036-4C3C-B013-9C4325D8151D.launchd_sim[24058] (UIKitApplication:com.abc.ios.dev[0x87c5][24587]): Program specified by service does not contain one of the requested architectures: 
Jun 12 16:55:52 MacBook-Pro SpringBoard[24075]: [Common] Unable to get pid for 'UIKitApplication:com.abc.ios.dev[0x87c5]': No such process (err 3)
Jun 12 16:55:52 MacBook-Pro SpringBoard[24075]: [Common] Bootstrapping failed for <FBApplicationProcess: 0x7faf677ab9d0; <bundleId>; pid: -1>

**Comment by mykola-mokhnach** [comment]
> Program specified by service does not contain one of the requested architectures

This is the root of the problem. Your build is broken and it is necessary to prepare a correct one, which is compatible to the current iOS Simulator.

Closed as not an issue.
