### ISSUE TITLE
Unable to identify object using Path

### ISSUE THREAD

**Issue by rsmodake** [appium/appium#8660]
## The problem

Appium desktop failed to identify object for below xpath,
//com.XXXX.UAT[@text='Add Card' and @width>0]

getting error as unable to identify object.

## Environment

* Appium version (or git revision) that exhibits the issue: Appium Desktop Version 1.1.0 beta 2
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: Windows / Mac
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: 5.0.2
* Real device or emulator/simulator: Android Real device
* Appium CLI or Appium.app|exe: Appium app

## Details
Recently we have migrated from SeeTest to Appium, but facing issues while identifying simple objects using Path. getting above error.

**Comment by mykola-mokhnach** [comment]
This part of xpath expression does not look good to me:

```
@width>0
```

What exactly are you trying to check?

One can use

```
boolean(string(@width))
```

to verify node attribute _width_ exists and the length of it is greater than zero.
