### ISSUE TITLE
Xcodebuild exited with code '65' and signal 'null'

### ISSUE THREAD

**Issue by Timoxa84** [appium/appium#8661]
## The problem

After a number of tests, Appium fails to start testing with code 65. My testing setup includes restarting of the Appium every time the test scenario is started. Also, I have tried a number of devices - iPhone 5s and two different iPhone 6 Plus. The issue reproduces for all of them. By the way, for iPhone 5s it is much easier is to reproduce the issue.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Desktop OS/version used to run Appium: macOS Sierra
* Node.js version (unless using Appium.app|exe): 6.6.0
* Mobile platform/version under test: iOS 10.3
* Real device or emulator/simulator: Real
* Appium CLI or Appium.app|exe: cli

## Link to Appium logs
[Appium logs GIST](https://gist.github.com/Timoxa84/8a87d87025d853f1484200f19244f53f)

**Comment by mykola-mokhnach** [comment]
Try https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/wda-custom-server.md as a workaround

Closed as known [XCTest issue](https://github.com/facebook/WebDriverAgent/issues/507).

**Comment by haseebzagir** [comment]
My solution was to navigate to the WebDriveragent.xcodeproj which is in the path your_username/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent and update the project to the recommended settings.
