### ISSUE TITLE
Cannot hide keyboard using driver.hideKeyboard() for Android in UIAutomator2 run

### ISSUE THREAD

**Issue by poorvikamahesh** [appium/appium#8662]
Hello

driver.hideKeyboard() does not hide the keyboard when executed for Android 7.1.2 when using UIAutomator2

Is there an alternate approach?

Executing Keys.DONE or RETURN, submits the form instead of just hiding the keyboard.
Please help

**Comment by HPramesh** [comment]
Hi 
I am using device Nexus5x with 7.1.2 Android version and its working fine for me. Sorry, couldn't reproduce the issue.

**Comment by imurchie** [comment]
Can you elaborate on what happens? Do it just return successfully without hiding the keyboard? Or is there a failure of some sort?

Can you post the logs (as a link to a [gist](https://gist.github.com))?

**Comment by poorvikamahesh** [comment]
@HPramesh and @imurchie 
Its working fine now. No idea why that happened yesterday.

Thanks

**Comment by imurchie** [comment]
Glad it's working!
