### ISSUE TITLE
Error: Could not install app: Command ios-deploy --id b65cd5e524cf556451e23f0820ab28e9947d4bc6 --uninstall --bundle /var/folders/rw/h6mqjtk512z996r3wjwmj6mh0000gp/T/2017512-47277-14794f4.mhklrw9udi/Payload/Practice.app exited with code 253

### ISSUE THREAD

**Issue by mikhailpractice** [appium/appium#8663]
## The problem

I am getting this error only on iOS 10.3+ devices (works perfect on iOS 10.0). This error occurs 5 out of 10 times: Error: Could not install app: ‘Command ‘ios-deploy --id b65cd5e524cf556451e23f0820ab28e9947d4bc6 --uninstall --bundle /var/folders/rw/h6mqjtk512z996r3wjwmj6mh0000gp/T/2017512-47277-14794f4.mhklrw9udi/Payload/Practice.app’ exited with code 253

## Environment

* Appium version: tried 1.6.3 and 1.6.5 Beta
* Desktop OS/version used to run Appium: MacOS Sierra
* Node.js version (unless using Appium.app|exe): 6.9.1
* Mobile platform/version under test: iOS 10.3.1
* Real device or emulator/simulator: Real Device

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Logs: https://gist.github.com/mikhailpractice/61fd118270ea7def51b964ad8c7b231a

**Comment by imurchie** [comment]
Can you manually run `ios-deploy --id b65cd5e524cf556451e23f0820ab28e9947d4bc6 --uninstall --bundle /var/folders/rw/h6mqjtk512z996r3wjwmj6mh0000gp/T/2017512-47277-14794f4.mhklrw9udi/Payload/Practice.app` from the command line, to see what the error is?

**Comment by mikhailpractice** [comment]
@imurchie Can't access app path '/var/folders/rw/h6mqjtk512z996r3wjwmj6mh0000gp/T/2017512-47277-14794f4.mhklrw9udi/Payload/Practice.app' : No such file or directory 
This is directory on the phone, I can not access it from command line

**Comment by mikhailpractice** [comment]
@imurchie But I can install if give right path (from desktop)

**Comment by mikhailpractice** [comment]
@imurchie It's only happening on iOS 10.3 (works perfect on iOS 10.0)

**Comment by imurchie** [comment]
It's not a directory on the phone. It's a temporary file Appium when extracting the app from the ipa file.

There could be something wrong with the unzipping. I can't tell with the little bit of logs you supplied.

**Comment by mikhailpractice** [comment]
@imurchie  I have updated logs, it has full log: https://gist.github.com/mikhailpractice/61fd118270ea7def51b964ad8c7b231a

Also I run ios-deploy manually and it does not have any errors:
https://gist.github.com/mikhailpractice/b4e4a64a5e25247e2c7dfe8dfe988ec1

**Comment by imurchie** [comment]
Since you say it is flakey (not failing all the time) can you try a few times to see if it fails?

**Comment by mikhailpractice** [comment]
@imurchie I have tried to run ios-deploy more than 30 times, and it always works

**Comment by mikhailpractice** [comment]
@imurchie Anything else I could try?

**Comment by mikhailpractice** [comment]
@mykola-mokhnach Same results (tried with .app)

**Comment by LukasLewandowski** [comment]
I have the same problem, after switching from iOS 10.3 emulator into iOS 10.3 real device, I have to rebuild app through Xcode and after that, it is working fine.

**Comment by siggerzz** [comment]
I'm also seeing the same issue.

**Comment by sharecommute** [comment]
me too. experiencing the same issue. sometimes it works perfectly and sometimes it fails at the installation step.

**Comment by jlipps** [comment]
Sounds like maybe we could add a retry? Or figure out why the results seem somehow less stable when run within Appium.

**Comment by imurchie** [comment]
We could. I think it is much more stable since @mykola-mokhnach removed the uninstall part.

**Comment by imurchie** [comment]
There is now a retry on this, too. Available in `appium-xcuitest-driver` v2.41.1 and above.

**Comment by afrozanjum12** [comment]
Hi , am new to Appium  . am seeing below error when am trying to inpect

**Comment by jlipps** [comment]
closing since a retry was added. @afrozanjum12 if ios-deploy is not working correctly on its own, then it will also not work correctly with appium. Please ensure you're using the latest appium beta as some improvements have been made.

**Comment by A0SK-PGE** [comment]
@afrozanjum12 - Hi, even I faced the same issue while using Appium desktop 1.2.6, Xcode 9 and IOS 11 real device. Could you figure out your issue? Please suggest if any solutions.

Thanks in advance.

Atul.

**Comment by nikhilishwar** [comment]
@afrozanjum12  -Hello, even I am having same issue I am getting same error. Please suggest with the better Solution.

[ 52%] CreatingStagingDirectory
[ 57%] ExtractingPackage
[ 60%] InspectingPackage
[ 60%] TakingInstallLock
[ 65%] PreflightingApplication
[ 65%] InstallingEmbeddedProfile
[ 65%] InstallingEmbeddedProfile
[ 70%] VerifyingApplication
2017-11-22 14:16:47.383 ios-deploy[19466:138948] [ !! ] Error 0xe8000067: There was an internal API error. AMDeviceSecureInstallApplication(0, device, url, options, install_callback, 0)
