### ISSUE TITLE
App does not activate after background_app(1) in landscape orientation on iOS real devices

### ISSUE THREAD

**Issue by abhilashcae** [appium/appium#8665]
## The problem

I'm using Python client. driver.background_app(1) is backgrounding the app on iOS real device (version 10.0.2) when I do it in landscape orientation. However, app never comes to foreground once it is backgrounded.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Desktop OS/version used to run Appium: OS X El Capitan 
* Desktop OS/version used to run Appium: Mac OS X El Capitan 10.11.6
* Node.js version (unless using Appium.app|exe): 6.10.0
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Real iOS device (OS version 10.0.2)
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs
https://gist.github.com/abhilashcae/30ae2a00f7e7dc60612d1896c25e10ab

## Related Issues
#8524 
https://github.com/facebook/WebDriverAgent/issues/553

The error now is different from the earlier one:
`Error Domain=com.facebook.WebDriverAgent Code=1 \"Timeout waiting for application to activate\" UserInfo={NSLocalizedDescription=Timeout waiting for application to activate}`

Cc: @mykola-mokhnach

**Comment by mykola-mokhnach** [comment]
Try 1.6.6-beta. Version 1.6.5 does not include my fix.

**Comment by mykola-mokhnach** [comment]
In case the problem still happens, but only in landscape, then there is not much one can do - it is a known XCTest bug.

**Comment by mykola-mokhnach** [comment]
@abhilashcae Please check if [this WDA patch](https://github.com/facebook/WebDriverAgent/pull/623) works for you

**Comment by abhilashcae** [comment]
@mykola-mokhnach - thank you! When will this be available in 1.6.6-beta?
