### ISSUE TITLE
Updated to Appium 1.6.5. Getting this error: Unable to launch WebDriverAgent because of xcodebuild failure: Command 'Scripts/bootstrap.sh -d' exited with code 1

### ISSUE THREAD

**Issue by xshuRoadie** [appium/appium#8666]
## The problem

All the tests ran ok until after Appium was upgraded to 1.6.5. Getting this error all the time:

WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: Command 'Scripts/bootstrap.sh -d' exited with code 1

desired capabilities:
       'deviceName': 'QA 6-Plus',
        'platformName': 'iOS',
        'platformVersion': '10.3.2",
        'udid': '{uid}', 
        'autoAcceptAlerts': 'true',
        'newCommandTimeout': 240,
        'automationName': 'XCUITest',
        'realDeviceLogger':'/Users/someone/.node/lib/node_modules/deviceconsole/deviceconsole',
        'xcodeConfigFile': '/Users/someone/someone/src/myconfig.xcconfig',
        'showXcodeLog':'true',
        'fullReset': 'true'

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Last Appium version that did not exhibit the issue (if applicable): 1.6.4
* Desktop OS/version used to run Appium: macOS Sierra; Version 10.12.5 (16F73)
* Node.js version (unless using Appium.app|exe): v6.7.0
* Mobile platform/version under test: iOS 10.3.2
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:  Appium CLI 

## Link to Appium logs
https://gist.github.com/xshuRoadie/66a2763a8d35147e663142fa0575fa42

**Comment by xshuRoadie** [comment]
Got the fix from https://github.com/appium/appium/issues/7752. Things are looking good. Closing the ticket.

**Comment by edrum** [comment]
I used appium 1.7.2 & i did Only two things(reinstallation & linking) to solve

1. brew uninstall carthage
2. brew install carthage
3. brew link --overwrite carthage
4. restart & try
