### ISSUE TITLE
Test is failed before first screen is loaded

### ISSUE THREAD

**Issue by livastar** [appium/appium#8667]
## The problem

While running tests on MacOS with appium: **v.1.6.5** or **v1.6.6-beta**; with node: **v8.1.0** on **Simulator**.
I've pressed Run test case in my IDE and Test Case is failed before the first screen loads.

Maybe some time parameters are missing?

**AppName and userName were changed intentionally**

## Link to Appium logs
Here are the appium logs: https://gist.github.com/livastar/fe6586f5c0ad569620643d870df60c02

## Serenity properties file
Here is the serenity.property capabilities: https://gist.github.com/livastar/7b9f70d759e19fbaf0f2a7d26013aa8a

## IDE error
Here are the IDE logs: https://gist.github.com/livastar/f69da03b55e84aa07629c86be6bef29b

## Code To Reproduce Issue 
    public void clickOnElement(WebElement el) {
        if (waitForElement(el)) {
            el.click();
        } else {
            System.out.println("Element doesn't appear after 15 seconds");
            return;
        }
    }

    public boolean waitForElement(WebElement el) {
        try {
            withTimeoutOf(15, SECONDS).waitFor(el).waitUntilVisible().isCurrentlyVisible();
        } catch (Exception e) {
            return false;
        }
        return true;
    }

**Comment by livastar** [comment]
Thanks for your help :)

**Comment by mykola-mokhnach** [comment]
the log itself looks good. Appium simply cannot detect the element you are trying to find on the current page. Probably, the element id is wrong

**Comment by livastar** [comment]
@mykola-mokhnach 
Appium tries to find the element before the app starts. 
If I put Sleeper in 10 seconds before first step, the test will pass

**Comment by mykola-mokhnach** [comment]
The problem might be in the app itself when it reports to XCTest the UI is ready, but loading is still in progress. Appium just receives application readiness status from [WDA](https://github.com/facebook/WebDriverAgent/issues). Please report your issue there, because we cannot do much from Appium side.
