### ISSUE TITLE
Android 7 and UIAutomator2 - Can't find element after upgrading android version 

### ISSUE THREAD

**Issue by alenus2** [appium/appium#8669]
## The problem
Android 7 and UIAutomator2 - Can't find element after upgrade 
After upgrading phone( Samsung Galaxy S6)  from 6.1 to Android  and while using 
 capabilities.setCapability("automationName", "uiautomator2")  - can't run cases which work fine for Android 6   and  UIAutomator

The script fails for simple command as test = appDriver.findElement(By.xpath(OR.getProperty(objectName)));
## Environment
* Appium 1.6.4
* Windows 

*  Android 7
* Real device  - Samsung Galaxy S6

## Link to Appium logs

[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["xpath","//*[contains(@content-desc,'test')]","d079b37d-e576-4160-a3c9-75441e3d9ceb"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [BaseDriver] Waiting up to 10000 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8201/wd/hub/session/8b1b68f1-12f2-4acc-a985-e770a1f1e4b9/element] with body: {"strategy":"xpath","selector":"//*[contains(@content-desc,'test')]","context":"","multiple":false}

## Code To Reproduce Issue [ Good To Have ]

The script fails for simple command as test = appDriver.findElement(By.xpath(OR.getProperty(objectName)));

**Comment by mykola-mokhnach** [comment]
Can you also attach the output of getPageSource method?

**Comment by alenus2** [comment]
This is page Source from **Android 6**

<?xml version="1.0" encoding="UTF-8"?>
<hierarchy rotation="0">
   <android.widget.FrameLayout index="0" text="" class="android.widget.FrameLayout" package="com.xyz.mobile.nativeApplication" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,1920]" resource-id="" instance="0">
      <android.widget.LinearLayout index="0" text="" class="android.widget.LinearLayout" package="com.xyz.mobile.nativeApplication" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,1920]" resource-id="" instance="0">
         <android.widget.FrameLayout index="0" text="" class="android.widget.FrameLayout" package="com.xyz.mobile.nativeApplication" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,72][1080,1920]" resource-id="android:id/content" instance="1">
            <android.widget.FrameLayout index="0" text="" class="android.widget.FrameLayout" package="com.xyz.mobile.nativeApplication" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,72][1080,1920]" resource-id="" instance="2">
               <android.widget.FrameLayout index="0" text="" class="android.widget.FrameLayout" package="com.xyz.mobile.nativeApplication" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,72][1080,1920]" resource-id="" instance="3">
                  <android.widget.FrameLayout index="0" text="" class="android.widget.FrameLayout" package="com.xyz.mobile.nativeApplication" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,72][1080,1920]" resource-id="" instance="4">
                     <android.widget.FrameLayout index="0" text="" class="android.widget.FrameLayout" package="com.xyz.mobile.nativeApplication" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,72][1080,1920]" resource-id="" instance="5">
                        <android.webkit.WebView index="0" text="" class="android.webkit.WebView" package="com.xyz.mobile.nativeApplication" content-desc="New Profile" checkable="false" checked="false" clickable="false" enabled="true" focusable="true" focused="true" scrollable="true" long-clickable="false" password="false" selected="false" bounds="[0,72][1080,1920]" resource-id="" instance="0">
                           <android.widget.Button index="0" text="" class="android.widget.Button" package="com.xyz.mobile.nativeApplication" content-desc="? " checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[15,87][96,189]" resource-id="" instance="0" />
                           <android.view.View index="1" text="" class="android.view.View" package="com.xyz.mobile.nativeApplication" content-desc="New Profile" checkable="false" checked="false" clickable="true" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[183,72][897,201]" resource-id="" instance="0" />
                           <android.view.View index="2" text="" class="android.view.View" package="com.xyz.mobile.nativeApplication" content-desc="Add " checkable="false" checked="false" clickable="true" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[939,72][1080,204]" resource-id="" instance="1" />
                           <android.view.View index="3" text="" class="android.view.View" package="com.xyz.mobile.nativeApplication" content-desc="? " checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[912,72][1080,204]" resource-id="" instance="2" />
                           <android.view.View index="4" text="" class="android.view.View" package="com.xyz.mobile.nativeApplication" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[1083,222][2025,462]" resource-id="" instance="3">
                              <android.view.View index="0" text="" class="android.view.View" package="com.xyz.mobile.nativeApplication" content-desc="Profile Name" checkable="false" checked="false" clickable="true" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[1098,258][1389,324]" resource-id="" instance="4" />
                              <android.widget.EditText NAF="true" index="1" text="" class="android.widget.EditText" package="com.xyz.mobile.nativeApplication" content-desc="" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[1098,345][2010,447]" resource-id="" instance="0" />
                           </android.view.View>
                           <android.view.View index="5" text="" class="android.view.View" package="com.xyz.mobile.nativeApplication" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[1083,468][2025,708]" resource-id="" instance="5">
                              <android.view.View index="0" text="" class="android.view.View" package="com.xyz.mobile.nativeApplication" content-desc="Server URL" checkable="false" checked="false" clickable="true" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[1098,504][1389,570]" resource-id="" instance="6" />
                              <android.widget.EditText index="1" text="" class="android.widget.EditText" package="com.xyz.mobile.nativeApplication" content-desc="http://server:port/test" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[1098,591][2010,693]" resource-id="" instance="1" />
                           </android.view.View>
                           <android.view.View index="6" text="" class="android.view.View" package="com.xyz.mobile.nativeApplication" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[1083,714][2025,954]" resource-id="" instance="7">
                              <android.view.View index="0" text="" class="android.view.View" package="com.xyz.mobile.nativeApplication" content-desc="User Name" checkable="false" checked="false" clickable="true" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[1098,750][1389,816]" resource-id="" instance="8" />
                              <android.widget.EditText NAF="true" index="1" text="" class="android.widget.EditText" package="com.xyz.mobile.nativeApplication" content-desc="" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[1098,837][2010,939]" resource-id="" instance="2" />
                           </android.view.View>
                           <android.view.View index="7" text="" class="android.view.View" package="com.xyz.mobile.nativeApplication" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[1083,960][2025,1200]" resource-id="" instance="9">
                              <android.view.View index="0" text="" class="android.view.View" package="com.xyz.mobile.nativeApplication" content-desc="Password" checkable="false" checked="false" clickable="true" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[1098,996][1389,1062]" resource-id="" instance="10" />
                              <android.widget.EditText NAF="true" index="1" text="" class="android.widget.EditText" package="com.xyz.mobile.nativeApplication" content-desc="" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" scrollable="false" long-clickable="false" password="true" selected="false" bounds="[1098,1083][2010,1185]" resource-id="" instance="3" />
                           </android.view.View>
                        </android.webkit.WebView>
                     </android.widget.FrameLayout>
                     <android.widget.FrameLayout index="1" text="" class="android.widget.FrameLayout" package="com.xyz.mobile.nativeApplication" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,72][1080,1920]" resource-id="" instance="6">
                        <android.view.View index="0" text="" class="android.view.View" package="com.xyz.mobile.nativeApplication" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,72][1080,1920]" resource-id="" instance="11" />
                     </android.widget.FrameLayout>
                  </android.widget.FrameLayout>
               </android.widget.FrameLayout>
            </android.widget.FrameLayout>
         </android.widget.FrameLayout>
      </android.widget.LinearLayout>
      <android.view.View index="1" text="" class="android.view.View" package="com.xyz.mobile.nativeApplication" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,72]" resource-id="android:id/statusBarBackground" instance="12" />
   </android.widget.FrameLayout>
</hierarchy>

**Comment by alenus2** [comment]
This is Page Source for the same screen while using  Android 7 and UIAutomator2

**The issue that all attributes for the fields in this form are gone, and we are trying to access the field by using Xpath as '"//android.view.View[@content-desc='Profile Name'' in this View**

**Comment by alenus2** [comment]
Hello, Do  any updates on this issue? Any workaround  which you could suggest ? Any upcoming patch?

Thanks!

**Comment by dpgraham** [comment]
Appium doesn't have control over what is reported by the `getPageSource()` method.

If the source changed then you'll need to update your selector to something compatible with the new source.

This is why we generally recommend adding `resource-id` to your elements instead of using XPath. It's less brittle and performs better.

I'm going to close this though, I don't believe there's anything we can fix on our end.
