### ISSUE TITLE
[Espresso Driver]failed to launch activity

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium#8670]
## The problem

Try espresso driver in https://github.com/appium/ruby_lib/issues/598

Then, `A new session could not be created. Details: Could not launch activity (Selenium::WebDriver::Error::SessionNotCreatedError)` was happened.

uiautomator1 and 2 work fine.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.6-beta
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS 10.12
* Node.js version (unless using Appium.app|exe): 7.10.0
* Mobile platform/version under test: Android 6.0
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: cli

## Details

1. Run appium server
2. Run `rake android` in https://github.com/KazuCocoa/ruby_lib/tree/support_espresso/android_tests
3. Then tests failed to launch a target activity and **had diff** for the target apk

## Link to Appium logs

ruby_lib side, appium server side and apk diff
https://gist.github.com/KazuCocoa/297b1272e4fb0373b06cfffb9712a015

```
$ npm list appium-espresso-driver
appium@1.6.6-beta /Users/kazuaki/GitHub/appium
└── appium-espresso-driver@1.0.0-beta.2
```

## Code To Reproduce Issue [ Good To Have ]

- Success to launch the activity
- Doesn't have diff for the test target apk

**Comment by KazuCocoa** [comment]
Hi, @dpgraham

I encountered the above error when I try to conduct espresso driver against ruby_lib's test suite.
 Could you check this?

**Comment by dpgraham** [comment]
Yeah I can have a look, thanks @KazuCocoa.

Thanks for providing sample tests!

**Comment by JaniJegoroff** [comment]
I had quick try with my Android app and Ruby bindings (8.2.1). Didn't see any issues with launching activities but with `timeouts/implicit_wait` endpoint instead:
```
[HTTP] --> POST /wd/hub/session/d55990cb-fa35-4c8b-bce2-3f2c3ca1bf82/timeouts/implicit_wait {"ms":0}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [JSONWP Proxy] Proxying [POST /wd/hub/session/d55990cb-fa35-4c8b-bce2-3f2c3ca1bf82/timeouts/implicit_wait] to [POST http://localhost:8080/session/a49eac3c-a1d4-4f92-8937-a67f32ebfafa/timeouts/implicit_wait] with body: {"ms":0}
[MJSONWP] Encountered internal error running command: Error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: 501 - {"message":"The operation requested is not yet implemented by Espresso driver","stackTrace":null}
    at doJwpProxy$ (../../../lib/mjsonwp/mjsonwp.js:385:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session/d55990cb-fa35-4c8b-bce2-3f2c3ca1bf82/timeouts/implicit_wait 500 58 ms - 368
```

Full Appium log: https://gist.github.com/JaniJegoroff/96bc517c5d24f30d1a9a9a03844a1733

**Comment by dpgraham** [comment]
@JaniJegoroff That's expected. A lot of the spec hasn't been implemented yet.

**Comment by JaniJegoroff** [comment]
@dpgraham Absolutely, I understand. This was more like a knowledge sharing since I know @KazuCocoa is working with Ruby bindings and Espresso. :)

**Comment by KazuCocoa** [comment]
The main thing was fixed
