### ISSUE TITLE
App is closing unexpectedly

### ISSUE THREAD

**Issue by arrk-shch** [appium/appium#8672]
## The problem

Executing script which is failing due to not finding element. When analysing,
 it unexpectedly closing. Its happening on particular screen. I tried opening & inspecting same page with Appium desktop. When on that particular page then inspector shows blank screen and on refreshing it closes the app.
<img width="1074" alt="screen shot 2017-06-15 at 3 59 44 pm" src="https://user-images.githubusercontent.com/4715168/27177375-c8aedb66-51e3-11e7-982d-fff3ea45e32f.png">
App is working fine when launching it manually on simulator.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Last Appium version that did not exhibit the issue (if applicable):1.6.4
* Desktop OS/version used to run Appium:10.3
* Node.js version (unless using Appium.app|exe):latest
* Mobile platform/version under test:iPhone 6s
* Real device or emulator/simulator:Simulator
* Appium CLI or Appium.app|exe:

## Details

Appium log while on Appium desktop-
[HTTP] <-- GET /wd/hub/session/ce64c9d3-5a80-45c5-925a-49f080555388/screenshot 200 106 ms - 66778 
[HTTP] --> GET /wd/hub/session/ce64c9d3-5a80-45c5-925a-49f080555388/source {}
[MJSONWP] Calling AppiumDriver.getPageSource() with args: ["ce64c9d3-5a80-45c5-925a-49f080555388"]
[XCUITest] Executing command 'getPageSource'
[JSONWP Proxy] Proxying [GET /source] to [GET http://localhost:8100/session/3C462F92-9C55-4330-8866-125DCA864AE4/source] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"Application is not running, possibly crashed\",\n  \"sessionId\" : \"3C462F92-9C55-4330-8866-125DCA864AE4\",\n  \"status\" : 10\n}"
[HTTP] <-- GET /wd/hub/session/ce64c9d3-5a80-45c5-925a-49f080555388/source 500 7418 ms - 131 

## Link to Appium logs

https://gist.github.com/arrk-shch/2ee7dcc82ae4445f603186e59b829a12

## Code To Reproduce Issue [ Good To Have ]

My scripts were running successfully with older version of Appium (below 1.6.4).

**Comment by mykola-mokhnach** [comment]
Please get the simulator log and attach it to the issue.

**Comment by arrk-shch** [comment]
Here is simulator log:
`Jun 16 08:36:04 ARRKs-MacBook-Pro backboardd[65413]: [Common] Couldn't find the digitizer HID service, this is probably bad
Jun 16 08:36:04 --- last message repeated 2 times ---
Jun 16 08:36:04 ARRKs-MacBook-Pro Evolution[65805]: Could not load the "checkmark" image referenced from a nib in the bundle with identifier "com.barbour-abi.com.sitelines"
Jun 16 08:36:08 ARRKs-MacBook-Pro Evolution[65805]: [Application] -[UIApplication endIgnoringInteractionEvents] called without matching -beginIgnoringInteractionEvents. Ignoring.
Jun 16 08:36:08 ARRKs-MacBook-Pro Evolution[65805]: [Warning] Warning once only: Detected a case where constraints ambiguously suggest a height of zero for a tableview cell's content view. We're considering the collapse unintentional and using standard height instead.
Jun 16 08:36:39 ARRKs-MacBook-Pro Evolution[65805]: *** Assertion failure in -[UITableView _classicHeightForRowAtIndexPath:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit_Sim/UIKit-3600.7.47/UITableView.m:12353
Jun 16 08:36:39 --- last message repeated 1 time ---
Jun 16 08:36:39 ARRKs-MacBook-Pro Evolution[65805]: invalid mode 'kCFRunLoopCommonModes' provided to CFRunLoopRunSpecific - break on _CFRunLoopError_RunCalledWithInvalidMode to debug. This message will only appear once per execution.
Jun 16 08:36:44 ARRKs-MacBook-Pro Evolution[65805]: *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid row height provided by table delegate. Value must be greater than zero or UITableViewAutomaticDimension.'
	*** First throw call stack:`

When page loads then it goes blank for 3 second & then we display loading image till it fetch the records. How to tackle this scenario with Appium?

**Comment by mykola-mokhnach** [comment]
The log says the application under test crashes and the problem should be fixed somewhere in the source code first. There is nothing one can do from Appium side.

**Comment by arrk-shch** [comment]
Thanks for a quick reply. But this is crashing only when app is executing through Appium/ Appium desktop. If I run it manually then it works fine.

**Comment by mykola-mokhnach** [comment]
Sorry, but I cannot advice more on this. You can either continue doing tests manually or check the crash with application developers and fix it.

**Comment by leongibhub** [comment]
@arrk-shch  did you resolve the issue you meet ?

**Comment by arrk-shch** [comment]
Sorry for not updating. Yes, the issues resolved for me long back. It was an issue with app building.

**Comment by leongibhub** [comment]
@arrk-shch 
Because of I meet the issue as you, so could you please tell me why it is an APP building issue?
what does the developer need to update so that the issue could be fixed ?
Thanks
