### ISSUE TITLE
The necessary pause between methods closeApp and launchApp for the correct Instruments logs removing.

### ISSUE THREAD

**Issue by Hanna-Kokhanava** [appium/appium#8673]
## The problem

During the relaunch app process, which contains consistent calling of methods _DriverManager.getDriver().closeApp()_ and _DriverManager.getDriver().launchApp()_  the **org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Abnormal Instruments termination!** is thrown, because the current session is terminated.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Selenium Java version: 2.53.0
* Appium Java client: 5.0.0-BETA8
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS Sierra 10.12.5
* Node.js version (unless using Appium.app|exe): v8.0.0
* Mobile platform/version under test:  iOS 9.3.2, iPhone 6 Plus
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:

## Link to Appium logs

https://gist.github.com/Hanna-Kokhanava/1e59d68049cb200c8b581c32660e2470

## Decision

Just add the Sleeper between the closeApp() and launchApp() methods. Sleeper for 5 seconds is working for me.

**Comment by dpgraham** [comment]
If you have a workaround then I think I'll close this issue. I don't think there's anything to fix on the Appium side.
