### ISSUE TITLE
iOS 11 Support

### ISSUE THREAD

**Issue by imurchie** [appium/appium#8675]
Appium will _eventually_ support iOS 11. This issue will serve to track progress on support. 

Individual issues in iOS 11 support can be linked to this one.

**Comment by mykola-mokhnach** [comment]
Linking https://github.com/facebook/WebDriverAgent/issues/618

**Comment by mykola-mokhnach** [comment]
@imurchie @jlipps I think this task can be closed now. Appium beta supports iOS 11 at very decent level

**Comment by imurchie** [comment]
No. With each new beta of Xcode 9 things change.

For instance, currently, touch id stuff fails because we cannot run applescript against the simulator.
