### ISSUE TITLE
sudo authorize-ios

### ISSUE THREAD

**Issue by amusharraf** [appium/appium#8679]
## The problem

Whenever I run this command, i get "Encountered an issue changing user priveledges for iOS...."
Please help me ASAP, I do not know how to change permissions so that i can do this. I tried sudo chown -R $USER, and chmod 777 on the directory, i got operation not permitted. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4

**Comment by mykola-mokhnach** [comment]
Please provide all the necessary details requested by the default issue reporting template (especially server logs) and reopen your issue. It is not possible to say anything having the currently provided information.
