### ISSUE TITLE
driver.context("WEBVIEW_1") doesn't work in Appium 1.6.5

### ISSUE THREAD

**Issue by Ashishqa** [appium/appium#8682]
## The problem
io.appium.java_client.NoSuchContextException: No such context found. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 22 milliseconds

## Environment
Appium 1.6.5
Win 10 64-bit
Chrome browser 58.0
Selenium 3.4.0
Java Client 5.0.0 Beta 8

## Details
It throw error message when go app view to web view.

Kindly let me know if any one have solution.

**Comment by mykola-mokhnach** [comment]
Please attach full Appium log

**Comment by Ashishqa** [comment]
Thank you. After looking in log come to know that two contexts are available.
1. NATIVE_APP
2. CHROMIUM
So I need to use CHROMIUM instead of WEBVIEW_1.
Now it works with driver.context("CHROMIUM").
