### ISSUE TITLE
Running Xcode Simulators

### ISSUE THREAD

**Issue by amusharraf** [appium/appium#8685]
## The problem

Hello, I am running tests on Xcode simulators using appium but i am encountering multiple issues that can be seen in the logs that i have attached below. Please help me resolve these issues ASAP, some issues include:

Error: simctl error running fbsimctl:....
Failed to harvest strings for pathless uuid....
Failed to enable path: code=113...
Error in registering callback port 
Could not create service from plist at path...
and a lot more

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.6-beta
* Desktop OS/version used to run Appium: Sierra
* Node.js version (unless using Appium.app|exe): 
* Mobile platform/version under test: iOS 10.2
* Real device or emulator/simulator: Simulator

## Link to Appium logs

https://gist.github.com/amusharraf/a3318ad58599f6eac01aef7320984c39

**Comment by mykola-mokhnach** [comment]
What is _hackpium_? Appium does not support fbsimctl

**Comment by amusharraf** [comment]
its a rendition of appium

**Comment by imurchie** [comment]
You'll have to contact the people who did that to get help. If they'd worked with us and gotten the changes into Appium we could be of use. Alas.
