### ISSUE TITLE
Click(tap) action is not performed with latest appium@1.6.5

### ISSUE THREAD

**Issue by SergiyBeno** [appium/appium#8686]
## The problem
Hi guys.
I'm new to Appium (actually not but it already past like 2 years since the last time I've been using it for the last time) but look like I have faced with one strange obstacle.
At the splash screen of my AUT I have tiny button that can be easily found using `id 'I have an account'` expression. Everything works perfectly while running scripts under appium@1.6.4. Last Friday I decided to test latest appium@1.6.5 version. And what I see is that appium no longer able to tap mentioned above button. There were no any app changes that could cause this behavior. The only possible thing (I think so) that I upgraded Xcode version (8.3.2 -> 8.3.3) but alongside with this change I also updated WebDriverAgent by running `npm uninstall/install/update wd` (tried all possible ways cause I thought that problem was somewhere there). Also I have checked carefully appium console output and compared it to previous output (1.6.5 and 1.6.4) - also nothing suspicious. 
After that I decided to test desktop versions and guess what - the same situation: I'm selecting necessary ui item ('I have an account' button) on the screenshot, tap the "Tap" button and nothing happens (I see that I'm getting 200 response code but on the screen actually nothing happens).

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5 (desktop appium-desktop-1.1.0-beta.2)
* Last Appium version that did not exhibit the issue (if applicable): 1.6.4 (desktop appium-desktop-1.0.2-beta.2)
* Desktop OS/version used to run Appium: Sierra 10.12.5
* Node.js version (unless using Appium.app|exe): 8.1.2
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: both

## Link to Appium logs
https://gist.github.com/SergiyBeno/cc639f23713ef689df7d4fce1cd2bcb2

**Comment by mykola-mokhnach** [comment]
Can you please attach the full log?
Is it landscape or portrait orientation? Native or web context?
Have you tried to calculate coordinates and tap the button by its absolute screen coordinates?

**Comment by SergiyBeno** [comment]
Yes, already updated the attachment (considering click method and tap using coordinates).
It is native application that supports only portrait orientation.
Yes, and following are the results:
`tap(x:255, y:637, element: id('I have an account'))` -> it works (button has been successfully pressed)
`id('I have an account').click` -> still not working (nothing happens on the screen)

**Comment by mykola-mokhnach** [comment]
It might be the coordinates calculated by WDA for the native click call don't satisfy the actual button constrains. Try Appium 1.6.6-beta, which includes recent WDA, and if this still does not work then report an issue directly to https://github.com/facebook/WebDriverAgent/issues

**Comment by SergiyBeno** [comment]
Thank you for your time and attention @mykola-mokhnach 
Confirming - appium@1.6.6-beta.2 works smoothly.

**Comment by saimeera22** [comment]
Hi,
I have tried click, tap, touch event for a ionic Cordova application.. it is working at some buttons but in few places it was not working.
Tried with xpath, ID, x and y co-ordinate etc.
Test is passed, as if it clicked the concern element, but it is not redirecting to the next state if click was successful.
I am using Webview_com.xxx as context.
Capabilities set are App package, App activity, uniautomator2 etc..
Please help me with this struck here for past 2 days.
Went through many of ur comments, hope you will help me with this
