### ISSUE TITLE
Unable to install iOS app on the real device using Appium Desktop

### ISSUE THREAD

**Issue by rsmodake** [appium/appium#8687]
## The problem

Getting error  while installing an app on iPhone.

iPhone - 10.2.1

Desired Capabilities are as below,

{
  "platformName": "iOS",
  "platformVersion": "10.2.1",
  "noReset": true,
  "deviceName": "Ann iPhone",
  "app": "/Users/cathy/Downloads/UAT.ipa",
  "udid": "55f7859aXxXXXXXXXXXXXXXd55",
  "bundleId": "com.XXXXXXXX.otgouat",
  "showXcodeLog": true,
  "automationName": "XCUITest"
}

## Environment

* Appium version (or git revision) that exhibits the issue: Appium Desktop
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: V.1.6.5
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Exe

## Details

Getting below error when trying to install iOS app,

Error
An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65

Basically app gets installed on the device, but I try to open an app, popup gets displayed as,

"Untrusted Enterprise Developer

"iPhone Distribution: XXXXXXX Inc" has not been trusted on this phone. Until this developer has been trusted, their enterprise apps will not be available for use.
"

## Link to Appium logs

[Appium] Welcome to Appium v1.6.5
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> GET /wd/hub/sessions {}
[MJSONWP] Calling AppiumDriver.getSessions() with args: []
[MJSONWP] Responding to client with driver.getSessions() result: []
[HTTP] <-- GET /wd/hub/sessions 200 11 ms - 40 
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/cathy/Downloads/UAT.ipa","automationName":"XCUITest","bundleId":"com.XXXXXX.otgouat","deviceName":"Ann iPhone","noReset":true,"platformName":"iOS","platformVersion":"10.2.1","showXcodeLog":true,"udid":"55f7859abae9529dd20662d0142ad233f6ee0d55","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/cathy/Downloads/UAT.ipa","automationName":"XCUITest","bundleId":"com.XXXXXXX.otgouat","deviceName":"Ann iPhone","noReset":true,"platformName":"iOS","platformVersion":"10.2.1","showXcodeLog":true,"udid":"55f7859abae9529dd20662d0142ad233f6ee0d55","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1497792450977 (09:27:30 GMT-0400 (EDT))
[Appium] Creating new XCUITestDriver (v2.30.0) session
[Appium] Capabilities:
[Appium]   app: '/Users/cathy/Downloads/UAT.ipa'
[Appium]   automationName: 'XCUITest'
[Appium]   bundleId: 'com.dunkinbrands.otgouat'
[Appium]   deviceName: 'Ann iPhone'
[Appium]   noReset: true
[Appium]   platformName: 'iOS'
[Appium]   platformVersion: '10.2.1'
[Appium]   showXcodeLog: true
[Appium]   udid: '55f7859abae9529dd20662d0142ad233f6ee0d55'
[Appium]   newCommandTimeout: 0
[Appium]   connectHardwareKeyboard: true
[XCUITest] XCUITestDriver version: 2.30.0
[BaseDriver] Session created with session id: cca1c7cf-88d4-4f09-8054-b944c072e928
[XCUITest] Xcode version set to '8.3.3' 
[XCUITest] iOS SDK Version set to '10.3'
[BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1497792451181 (09:27:31 GMT-0400 (EDT))
[XCUITest] Available devices: 55f7859abae9529dd20662d0142ad233f6ee0d55
[XCUITest] Creating iDevice object with udid '55f7859abae9529dd20662d0142ad233f6ee0d55'
[XCUITest] Determining device to run tests on: udid: '55f7859abae9529dd20662d0142ad233f6ee0d55', real device: true
[BaseDriver] Using local app '/Users/cathy/Downloads/UAT.ipa'
[BaseDriver] Copying local zip to tmp dir
[BaseDriver] Unzipping /var/folders/bh/ywcwfc0x6b927kjsh8hm4j2m0000gr/T/2017518-2562-97h351.hwssx7p66r/appium-app.zip
[BaseDriver] Testing zip archive: /var/folders/bh/ywcwfc0x6b927kjsh8hm4j2m0000gr/T/2017518-2562-97h351.hwssx7p66r/appium-app.zip
[BaseDriver] Unzipped local app to '/var/folders/bh/ywcwfc0x6b927kjsh8hm4j2m0000gr/T/2017518-2562-97h351.hwssx7p66r/Payload/dd-national-ios.app'
[BaseDriver] Event 'appConfigured' logged at 1497792462769 (09:27:42 GMT-0400 (EDT))
[XCUITest] Checking whether app '/var/folders/bh/ywcwfc0x6b927kjsh8hm4j2m0000gr/T/2017518-2562-97h351.hwssx7p66r/Payload/dd-national-ios.app' is actually present on file system
[XCUITest] App is present
[BaseDriver] Event 'resetStarted' logged at 1497792462772 (09:27:42 GMT-0400 (EDT))
[XCUITest] Reset: fullReset not set. Leaving as is
[BaseDriver] Event 'resetComplete' logged at 1497792462774 (09:27:42 GMT-0400 (EDT))
[iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[BaseDriver] Event 'logCaptureStarted' logged at 1497792462999 (09:27:42 GMT-0400 (EDT))
[XCUITest] Setting up real device
[XCUITest] Installing '/var/folders/bh/ywcwfc0x6b927kjsh8hm4j2m0000gr/T/2017518-2562-97h351.hwssx7p66r/Payload/dd-national-ios.app' on device with UUID '55f7859abae9529dd20662d0142ad233f6ee0d55'...
[XCUITest] The app has been installed successfully.
[BaseDriver] Event 'appInstalled' logged at 1497792470643 (09:27:50 GMT-0400 (EDT))
[BaseDriver] Event 'wdaStartAttempted' logged at 1497792470648 (09:27:50 GMT-0400 (EDT))
[XCUITest] Using WDA path: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[XCUITest] Carthage found: '/usr/local/bin/carthage'
[XCUITest] Killing hanging processes
[XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=55f7859abae9529dd20662d0142ad233f6ee0d55 -configuration Debug IPHONEOS_DEPLOYMENT_TARGET=10.2' in directory '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Output from xcodebuild will be logged
[XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[Xcode] Build settings from command line:
[Xcode]     IPHONEOS_DEPLOYMENT_TARGET = 10.2
[Xcode] 
[Xcode] 
[XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[Xcode] === BUILD TARGET WebDriverAgentLib OF PROJECT WebDriverAgent WITH CONFIGURATION Debug ===
[Xcode] 
[Xcode] Check dependencies
[Xcode] 
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[Xcode] 
[Xcode] 
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[Xcode] === BUILD TARGET WebDriverAgentRunner OF PROJECT WebDriverAgent WITH CONFIGURATION Debug ===
[Xcode] 
[Xcode] Check dependencies
[Xcode] Signing for "WebDriverAgentRunner" requires a development team. Select a development team in the project editor.
[Xcode] Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.3'
[Xcode] Signing for "WebDriverAgentRunner" requires a development team. Select a development team in the project editor.
[Xcode] 
[Xcode] Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.3'
[Xcode] Signing for "WebDriverAgentRunner" requires a development team. Select a development team in the project editor.
[Xcode] Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.3'
[Xcode] Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.3'
[Xcode] 
[Xcode] 
[Xcode] ** TEST BUILD FAILED **
[Xcode] 
[Xcode] 
[Xcode] The following build commands failed:
[Xcode] 	Check dependencies
[Xcode] (1 failure)
[Xcode] 
[XCUITest] Log file for xcodebuild test: /Users/cathy/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/C957B2AA-E971-4A22-BD6A-2A879BEDB210/Session-WebDriverAgentRunner-2017-06-18_092759-Dzf0zA.log
[Xcode] 2017-06-18 09:27:59.956 xcodebuild[2688:69753]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
[Xcode] /Users/cathy/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/C957B2AA-E971-4A22-BD6A-2A879BEDB210/Session-WebDriverAgentRunner-2017-06-18_092759-Dzf0zA.log
[Xcode] 2017-06-18 09:27:59.957 xcodebuild[2688:69722] [MT] IDETestOperationsObserverDebug: (3CFCCC34-2F70-47DE-9FC0-F063F5D265C1) Beginning test session WebDriverAgentRunner-3CFCCC34-2F70-47DE-9FC0-F063F5D265C1 at 2017-06-18 09:27:59.956 with Xcode 8E3004b on target  {
[Xcode] 		deviceSerialNumber:         FK1QD17UGRXQ
[Xcode] 		identifier:                 55f7859abae9529dd20662d0142ad233f6ee0d55
[Xcode] 		deviceClass:                iPhone
[Xcode] 		deviceName:                 Ann’s iPhone
[Xcode] 		deviceIdentifier:           55f7859abae9529dd20662d0142ad233f6ee0d55
[Xcode] 		productVersion:             10.2.1
[Xcode] 		buildVersion:               14D27
[Xcode] 		deviceSoftwareVersion:      10.2.1 (14D27)
[Xcode] 		deviceArchitecture:         arm64
[Xcode] 		deviceTotalCapacity:        11943038976
[Xcode] 		deviceAvailableCapacity:    9282740224
[Xcode] 		deviceIsTransient:          NO
[Xcode] 		ignored:                    NO
[Xcode] 		deviceIsBusy:               NO
[Xcode] 		deviceIsActivated:          YES
[Xcode] 		deviceActivationState:      Activated
[Xcode] 		isPasscodeLocked:           NO
[Xcode] 		deviceType:                 
[Xcode] 		supportedDeviceFamilies:    (
[Xcode]     1
[Xcode] )
[Xcode] 		applications:              (null)
[Xcode] 		provisioningProfiles:      (null)
[Xcode] 		activityProgress:          -2
[Xcode] 		activityTitle:             
[Xcode] 		hasInternalSupport:        NO
[Xcode] 		isSupportedOS:             YES
[Xcode] 		developerDiskMountError:   (null)
[Xcode] (null)
[Xcode] 	bootArgs:                  
[Xcode] 		} (10.2.1 (14D27))
[Xcode] 
[Xcode] 2017-06-18 09:27:59.986 xcodebuild[2688:69722] Error Domain=NSCocoaErrorDomain Code=260 "The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/cathy/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7fb6f1d73ff0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
[Xcode] 2017-06-18 09:27:59.986 xcodebuild[2688:69722] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
[Xcode] ** TEST EXECUTE FAILED **
[Xcode] 
[Xcode] 
[XCUITest] xcodebuild exited with code '65' and signal 'null'
[Xcode] Contents of xcodebuild log file '/Users/cathy/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/C957B2AA-E971-4A22-BD6A-2A879BEDB210/Session-WebDriverAgentRunner-2017-06-18_092759-Dzf0zA.log':
[Xcode] 09:27:59.958 xcodebuild[2688:69722] Beginning test session WebDriverAgentRunner-3CFCCC34-2F70-47DE-9FC0-F063F5D265C1 at 2017-06-18 09:27:59.956 with Xcode 8E3004b on target  {
[Xcode] 		deviceSerialNumber:         FK1QD17UGRXQ
[Xcode] 		identifier:                 55f7859abae9529dd20662d0142ad233f6ee0d55
[Xcode] 		deviceClass:                iPhone
[Xcode] 		deviceName:                 Ann’s iPhone
[Xcode] 		deviceIdentifier:           55f7859abae9529dd20662d0142ad233f6ee0d55
[Xcode] 		productVersion:             10.2.1
[Xcode] 		buildVersion:               14D27
[Xcode] 		deviceSoftwareVersion:      10.2.1 (14D27)
[Xcode] 		deviceArchitecture:         arm64
[Xcode] 		deviceTotalCapacity:        11943038976
[Xcode] 		deviceAvailableCapacity:    9282740224
[Xcode] 		deviceIsTransient:          NO
[Xcode] 		ignored:                    NO
[Xcode] 		deviceIsBusy:               NO
[Xcode] 		deviceIsActivated:          YES
[Xcode] 		deviceActivationState:      Activated
[Xcode] 		isPasscodeLocked:           NO
[Xcode] 		deviceType:                 
[Xcode] 		supportedDeviceFamilies:    (
[Xcode]     1
[Xcode] )
[Xcode] 		applications:              (null)
[Xcode] 		provisioningProfiles:      (null)
[Xcode] 		activityProgress:          -2
[Xcode] 		activityTitle:             
[Xcode] 		hasInternalSupport:        NO
[Xcode] 		isSupportedOS:             YES
[Xcode] 		developerDiskMountError:   (null)
[Xcode] (null)
[Xcode] 	bootArgs:                  
[Xcode] 		} (10.2.1 (14D27))
[Xcode] 09:27:59.958 xcodebuild[2688:69722] 	/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild
[Xcode] build-for-testing
[Xcode] test-without-building
[Xcode] -project
[Xcode] /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj
[Xcode] -scheme
[Xcode] WebDriverAgentRunner
[Xcode] -destination
[Xcode] id=55f7859abae9529dd20662d0142ad233f6ee0d55
[Xcode] -configuration
[Xcode] Debug
[Xcode] IPHONEOS_DEPLOYMENT_TARGET=10.2
[Xcode] 09:27:59.958 xcodebuild[2688:69722] Launching with Xcode.IDEFoundation.Launcher.PosixSpawn
[Xcode] 09:27:59.973 xcodebuild[2688:69727] Connecting to mobile device: 55f7859abae9529dd20662d0142ad233f6ee0d55
[Xcode] 09:27:59.978 xcodebuild[2688:69722] Launch session started.
[Xcode] 09:27:59.978 xcodebuild[2688:69727] Starting session with mobile device
[Xcode] 09:27:59.984 xcodebuild[2688:69722] Test operation failure: Launch session expired before checking in.
[Xcode] 09:27:59.985 xcodebuild[2688:69722] _finishWithError:Error Domain=IDETestOperationsObserverErrorDomain Code=5 "Launch session expired before checking in." UserInfo={NSLocalizedDescription=Launch session expired before checking in.} didCancel: 1
[Xcode] 
[BaseDriver] Event 'wdaStartFailed' logged at 1497792480072 (09:28:00 GMT-0400 (EDT))
[XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
[XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down iproxy process (pid 2687)
[XCUITest] iproxy exited with code 'null'
[XCUITest] Removing WDA application from device
[BaseDriver] Event 'wdaStartAttempted' logged at 1497792490349 (09:28:10 GMT-0400 (EDT))
[XCUITest] Using WDA path: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[XCUITest] Carthage found: '/usr/local/bin/carthage'
[XCUITest] Killing hanging processes
[XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=55f7859abae9529dd20662d0142ad233f6ee0d55 -configuration Debug IPHONEOS_DEPLOYMENT_TARGET=10.2' in directory '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Output from xcodebuild will be logged
[XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[Xcode] Build settings from command line:
[Xcode]     IPHONEOS_DEPLOYMENT_TARGET = 10.2
[Xcode] 
[Xcode] 
[XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[Xcode] === BUILD TARGET WebDriverAgentLib OF PROJECT WebDriverAgent WITH CONFIGURATION Debug ===
[Xcode] 
[Xcode] Check dependencies
[Xcode] 
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[Xcode] 
[Xcode] 
[Xcode] === BUILD TARGET WebDriverAgentRunner OF PROJECT WebDriverAgent WITH CONFIGURATION Debug ===
[Xcode] 
[Xcode] Check dependencies
[Xcode] Signing for "WebDriverAgentRunner" requires a development team. Select a development team in the project editor.
[Xcode] Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.3'
[Xcode] 
[Xcode] Signing for "WebDriverAgentRunner" requires a development team. Select a development team in the project editor.
[Xcode] Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.3'
[Xcode] Signing for "WebDriverAgentRunner" requires a development team. Select a development team in the project editor.
[Xcode] Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.3'
[Xcode] Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.3'
[Xcode] 
[Xcode] 
[Xcode] ** TEST BUILD FAILED **
[Xcode] 
[Xcode] 
[Xcode] The following build commands failed:
[Xcode] 	Check dependencies
[Xcode] (1 failure)
[Xcode] 
[XCUITest] Log file for xcodebuild test: /Users/cathy/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/67299E77-4EDF-4975-A651-3D01030AFE22/Session-WebDriverAgentRunner-2017-06-18_092818-5STX1g.log
[Xcode] 2017-06-18 09:28:18.372 xcodebuild[2716:69913]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
[Xcode] /Users/cathy/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/67299E77-4EDF-4975-A651-3D01030AFE22/Session-WebDriverAgentRunner-2017-06-18_092818-5STX1g.log
[Xcode] 2017-06-18 09:28:18.373 xcodebuild[2716:69908] [MT] IDETestOperationsObserverDebug: (F64A025E-442F-472A-8EC3-FDE06FFA5E0E) Beginning test session WebDriverAgentRunner-F64A025E-442F-472A-8EC3-FDE06FFA5E0E at 2017-06-18 09:28:18.372 with Xcode 8E3004b on target  {
[Xcode] 		deviceSerialNumber:         FK1QD17UGRXQ
[Xcode] 		identifier:                 55f7859abae9529dd20662d0142ad233f6ee0d55
[Xcode] 		deviceClass:                iPhone
[Xcode] 		deviceName:                 Ann’s iPhone
[Xcode] 		deviceIdentifier:           55f7859abae9529dd20662d0142ad233f6ee0d55
[Xcode] 		productVersion:             10.2.1
[Xcode] 		buildVersion:               14D27
[Xcode] 		deviceSoftwareVersion:      10.2.1 (14D27)
[Xcode] 		deviceArchitecture:         arm64
[Xcode] 		deviceTotalCapacity:        11943038976
[Xcode] 		deviceAvailableCapacity:    9285652480
[Xcode] 		deviceIsTransient:          NO
[Xcode] 		ignored:                    NO
[Xcode] 		deviceIsBusy:               NO
[Xcode] 		deviceIsActivated:          YES
[Xcode] 		deviceActivationState:      Activated
[Xcode] 		isPasscodeLocked:           NO
[Xcode] 		deviceType:                 
[Xcode] 		supportedDeviceFamilies:    (
[Xcode]     1
[Xcode] )
[Xcode] 		applications:              (null)
[Xcode] 		provisioningProfiles:      (null)
[Xcode] 		activityProgress:          -2
[Xcode] 		activityTitle:             
[Xcode] 		hasInternalSupport:        NO
[Xcode] 		isSupportedOS:             YES
[Xcode] 		developerDiskMountError:   (null)
[Xcode] (null)
[Xcode] 	bootArgs:                  
[Xcode] 		} (10.2.1 (14D27))
[Xcode] 
[Xcode] 2017-06-18 09:28:18.410 xcodebuild[2716:69908] Error Domain=NSCocoaErrorDomain Code=260 "The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/cathy/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7fcc6ccd7ba0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
[Xcode] 2017-06-18 09:28:18.411 xcodebuild[2716:69908] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
[Xcode] ** TEST EXECUTE FAILED **
[Xcode] 
[Xcode] 
[XCUITest] xcodebuild exited with code '65' and signal 'null'
[Xcode] Contents of xcodebuild log file '/Users/cathy/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/67299E77-4EDF-4975-A651-3D01030AFE22/Session-WebDriverAgentRunner-2017-06-18_092818-5STX1g.log':
[Xcode] 09:28:18.373 xcodebuild[2716:69908] Beginning test session WebDriverAgentRunner-F64A025E-442F-472A-8EC3-FDE06FFA5E0E at 2017-06-18 09:28:18.372 with Xcode 8E3004b on target  {
[Xcode] 		deviceSerialNumber:         FK1QD17UGRXQ
[Xcode] 		identifier:                 55f7859abae9529dd20662d0142ad233f6ee0d55
[Xcode] 		deviceClass:                iPhone
[Xcode] 		deviceName:                 Ann’s iPhone
[Xcode] 		deviceIdentifier:           55f7859abae9529dd20662d0142ad233f6ee0d55
[Xcode] 		productVersion:             10.2.1
[Xcode] 		buildVersion:               14D27
[Xcode] 		deviceSoftwareVersion:      10.2.1 (14D27)
[Xcode] 		deviceArchitecture:         arm64
[Xcode] 		deviceTotalCapacity:        11943038976
[Xcode] 		deviceAvailableCapacity:    9285652480
[Xcode] 		deviceIsTransient:          NO
[Xcode] 		ignored:                    NO
[Xcode] 		deviceIsBusy:               NO
[Xcode] 		deviceIsActivated:          YES
[Xcode] 		deviceActivationState:      Activated
[Xcode] 		isPasscodeLocked:           NO
[Xcode] 		deviceType:                 
[Xcode] 		supportedDeviceFamilies:    (
[Xcode]     1
[Xcode] )
[Xcode] 		applications:              (null)
[Xcode] 		provisioningProfiles:      (null)
[Xcode] 		activityProgress:          -2
[Xcode] 		activityTitle:             
[Xcode] 		hasInternalSupport:        NO
[Xcode] 		isSupportedOS:             YES
[Xcode] 		developerDiskMountError:   (null)
[Xcode] (null)
[Xcode] 	bootArgs:                  
[Xcode] 		} (10.2.1 (14D27))
[Xcode] 09:28:18.374 xcodebuild[2716:69908] 	/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild
[Xcode] build-for-testing
[Xcode] test-without-building
[Xcode] -project
[Xcode] /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj
[Xcode] -scheme
[Xcode] WebDriverAgentRunner
[Xcode] -destination
[Xcode] id=55f7859abae9529dd20662d0142ad233f6ee0d55
[Xcode] -configuration
[Xcode] Debug
[Xcode] IPHONEOS_DEPLOYMENT_TARGET=10.2
[Xcode] 09:28:18.374 xcodebuild[2716:69908] Launching with Xcode.IDEFoundation.Launcher.PosixSpawn
[Xcode] 09:28:18.389 xcodebuild[2716:69963] Connecting to mobile device: 55f7859abae9529dd20662d0142ad233f6ee0d55
[Xcode] 09:28:18.393 xcodebuild[2716:69963] Starting session with mobile device
[Xcode] 09:28:18.396 xcodebuild[2716:69908] Launch session started.
[Xcode] 09:28:18.408 xcodebuild[2716:69908] Test operation failure: Launch session expired before checking in.
[Xcode] 09:28:18.409 xcodebuild[2716:69908] _finishWithError:Error Domain=IDETestOperationsObserverErrorDomain Code=5 "Launch session expired before checking in." UserInfo={NSLocalizedDescription=Launch session expired before checking in.} didCancel: 1
[Xcode] 
[BaseDriver] Event 'wdaStartFailed' logged at 1497792498496 (09:28:18 GMT-0400 (EDT))
[XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
[XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down iproxy process (pid 2715)
[XCUITest] iproxy exited with code 'null'
[XCUITest] Removing WDA application from device
[XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
    at XCUITestDriver.quitAndUninstall$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:386:15)
    at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
 Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
    at XCUITestDriver.quitAndUninstall$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:386:15)
    at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
    at XCUITestDriver.quitAndUninstall$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:386:15)
    at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session 500 57749 ms - 230

**Comment by mykola-mokhnach** [comment]
> [Xcode] Signing for "WebDriverAgentRunner" requires a development team. Select a development team in the project editor.
> [Xcode] Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.3'

You need to setup WDA code signing properly. Here is the [tutorial](https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md)

Closed as duplicate.
