### ISSUE TITLE
Left towards swipe option does not work any more on Appium 1.6 version

### ISSUE THREAD

**Issue by mucs0412** [appium/appium#8690]
## The problem
On iOS simulator, I wanna make a gesture swiping an item left towards to show the option list like "Delete" option.
It works well on Appium 1.5.3, here is my python script:
def swipe_to_delete(user):
    i=0
    cells = wd.find_elements_by_class_name("XCUIElementTypeCell")
    while i < len(cells):
        names = cells[i].find_element_by_id("title")
        if names.text == user:
            location = cells[i].location
            width = cells[i].size['width']
            point_y = location['y']
            from_x = int(width * 0.5)
            to_x = int(width * 0.35)
            action = TouchAction(wd)
            action.press(x=from_x,y=point_y).move_to(x=-to_x,y=0).release().perform()
            wd.find_element_by_id("Delete").click()
	    break
	i+=1
but after upgrading my appium to 1.6 version, it does not work any more.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Last Appium version that did not exhibit the issue (if applicable): 1.5.3
* Desktop OS/version used to run Appium: macOS 10.12.5
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iPhone 7/iOS 10.3
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: 1.1.0-beta.2

**Comment by mykola-mokhnach** [comment]
Appium 1.6.4+ supports natively supports _mobile:_ gestures, including swipe. Please read https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios-xctest-mobile-gestures.md for more details.
