### ISSUE TITLE
How to paste sometext from clipboard

### ISSUE THREAD

**Issue by lehungcuong** [appium/appium#8693]
## The problem
On android,
I coppied some texts into clipboard but I dont know how to paste them on a field. Please help me

## Environment

* Appium version (or git revision) that exhibits the issue:N/A
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

**Comment by lehungcuong** [comment]
https://github.com/appium/appium/issues/1923
In this issue, seveniruby said he use long press and send control+v to paste. but how to control+v?

**Comment by lehungcuong** [comment]
@seveniruby please help me

**Comment by mykola-mokhnach** [comment]
Long press a text field then just tap a Paste balloon. Please use Appium forum to ask questions.

**Comment by seveniruby** [comment]
@lehungcuong if you are a chinese, you can search testerhome.com for the answer. one link is https://testerhome.com/topics/320

```
driver.sendKeyEvent(xxx,AndroidKeyMetastate.META_CTRL_ON)
```
