### ISSUE TITLE
Unable to get attribute of an element for iOS app

### ISSUE THREAD

**Issue by zhixau** [appium/appium#8695]
## The problem

I was trying to get attribute 'enabled' of an element, but it failed.
I got the error below:
======================
  File "/Users/xxx/.pyenv/versions/3.6.0/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py", line 144, in get_attribute
    if name != 'value' and attributeValue.lower() in ('true', 'false'):
AttributeError: 'bool' object has no attribute 'lower'
=======================

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Desktop OS/version used to run Appium: MacOS Version 10.12.5
* Node.js version (unless using Appium.app|exe): 8.1.0
* Mobile platform/version under test: iOS 10.3.1
* Real device or emulator/simulator: Emulator iPad Air
* Appium CLI or Appium.app|exe: v1.1.0-beta.2

## Details
For the same code, it works on Android device. And I checked the issue list, found that the issue fixed on Android last month.

## Code To Reproduce Issue [ Good To Have ]
Code like this:
driver.find_element(MobileBy.ACCESSIBILITY_ID, 'login button').get_attribute('enabled')

Will it fix on iOS device?

Thanks!

**Comment by mykola-mokhnach** [comment]
This happens because WDA API is not fully compatible to https://www.w3.org/TR/webdriver/ and may return non-string result in response to getAttrbute call (it returns boolean one in this particular case).

**Comment by mykola-mokhnach** [comment]
The fix has been merged to Appium 1.6.6-beta
