### ISSUE TITLE
How do I open Web Browsers on windows through AppiumDriver instead of WebDriver

### ISSUE THREAD

**Issue by samnit** [appium/appium#8696]
How can I use appium driver to run web browsers on windows as when I try to initialise my Appium Driver with RemoteWebDriver or FirefoxDriver they give an error.
When I Use : 
**AppiumDriver driver=(AppiumDriver) new RemoteWebDriver(sUrl,caps);**

**It opens the browser but after that throws the error cannot convert from RemoteWebDriver to Appium Driver** 
and When I use this : 
**AppiumDriver driver=new FirefoxDriver();**

**It gives the compilation error that cannot convert from FirefoxDriver to AppiumDriver.**

**How can I Use AppiumDriver for web browsers ??**

**Comment by mykola-mokhnach** [comment]
> AppiumDriver driver=(AppiumDriver) new RemoteWebDriver(sUrl,caps);

It is impossible to do it since AppiumDriver itself is inherited from RemoteWebDriver. 

Closed issue as server unrelated. Please use Appium forum to ask question or https://github.com/appium/java-client/issues to report java_client related issues.
