### ISSUE TITLE
Appium freezes after screenshot command is executed; Screenshot is not taken and is stuck 

### ISSUE THREAD

**Issue by ajaj91** [appium/appium#8697]
## The problem
When Screenshot method is called, command is executed, but appium stays frozen after it is called and does not process the screenshot either. After testing this multiple times, it often works only once within a Test Case where the screenshot method is called multiple times.  I'm using the Ruby Client.

## Environment

Appium version (or git revision) that exhibits the issue: 1.6.5
Desktop OS/version used to run Appium: Windows 7
Mobile platform/version under test: Android 7.0.1
Real device or emulator/simulator: Google Nexus 6P 
Appium CLI or Appium.app|exe: CLI

## Details
Trying to complete an SMS Test while taking a screenshot. SMS sends successfully and screenshot method is called but freezes while it is being taken and doesn't go anywhere after unless script is terminated.

## Link to Appium logs

https://gist.github.com/ajaj91/

## Code To Reproduce Issue [ Good To Have ]

def goto_compose_sms_message
            
	click_element home_xpaths[:compose_image_btn], 10
	input_string home_xpaths[:to_textfield], "-----------"
	press_enter_button
	click_element home_xpaths[:next_arrow_btn], 10
	input_string home_xpaths[:enter_message], "Test Message"
	click_element home_xpaths[:send], 10
         sleep 2
         take_screenshot "C:/Screenshots", "SMS_Test.png"
	#press_back_button
	if check_exist?(home_xpaths[:mms_confirm])
		puts "SMS Sent Successfully"
	end	
end

Screenshot Method: 
def take_screenshot(save_dir, file_name)
       FileUtils.mkdir_p save_dir
       sleep 3
       driver.screenshot "#{save_dir}/#{file_name}"
       sleep 3
end

**Comment by mykola-mokhnach** [comment]
Does freeze upon each test execution or this happens randomly?

**Comment by JamesChungZLL** [comment]
It appears that when the screen shot png file's size is 0 byte, the appium server will free at 'adb pull <path of image>'.

**Comment by mykola-mokhnach** [comment]
> [MJSONWP] Responding to client with driver.getScreenshot() result: "iVBORw0KGgoAAAANSUhEUgAABaAAAAoACAYAAABH9IXPAACAAElEQVR4AezBCZzUhWH3/+/vmHtmT2APWG6W5b40gBBZ1BivGO+gkjhqxa59osbmaNoYYxOftE1TjzaebcYYY/JEE7Ve1USFEqUqconrcqgcwnLtfczO+fu/fP4v+mzHXVhght2Fz/ttvH6FHAEAAAAAAAAAkGWmAAAAAAAAAADIAVMAAAAAAAAAAOSAKQAAAAAAAAAAcsAUAAAAAAAAAAA5YAoAAAAAAAAAgBwwBQAAAAAAAABADpgCAAAAAAAAACAHTAEAAAAAAAAAkAOmAAAAAAAAAADIAVMAAAAAAAAAAOSAKQAAAAAAAAAAcsAUAAAAAAAAAAA5YAoAAAAAAAAAgBwwBQAAAAAAAABADpgCAAAAAAAAACAHbAEAAAAAAAAY0Hwl42QHCnW04k27FW/dJyeVFHA82QIAAAAAAACgqpqI6h64VgORHSiQu7BMRysVbZXRdkCOgOPLFgAAAAAAANCD4OiZGn/N3epu3Z2L1V1w9EyNv+Zu9cWeFb/QnuWPavw19yg4eoYOZesvvqH2bet0vFTVRFRaHVbdA9cKQPbYAgAAAAAAAHpg+wtUMLlah2L7C1QwuVp90Vy7Qp8Kjp6pgsmLdCi2v0DHS1VNRKXVYQHIPlvAYZi2W8WzL9DIi/9aobFzdDQ6d2/Stid/oANv/17pZFwAAAAAAAADQVVNRKXVYQHIDVsnEFdoiEo+f7XaPlqjlrqV6k+WL6T8CfPVuOEVDWaGaalw+tkaccFtCo6aoaPlKx2vigtuUzoZU+OaF5ROxgUAAAAAAAa/9u3rtO7OxTpo5h2vq7utv/iG2ret06e69m9TT9bduViZ2revU65V1URUWh3WQOArGSc7UKje2MFCHQt3YbnsQIGcdFo9iTftVqxpt4BsszXIWZ6AfGWVGnLKhRpx/jdk+/MVa9qtD+67Ss21K3Q8mS6P3AWlCo6epaLpZ8v0+NW44RUNVpbH...
> [HTTP] <-- GET /wd/hub/session/06e8d5ec-e609-4470-8dfd-ea460cf1a433/screenshot 200 7246 ms - 309354 
> [BaseDriver] Shutting down because we waited 60 seconds for a command

Appium driver is shut down automatically after 60s-timeout expires. This timeout can be configured with **newCommandTimeout** and the log says the driver is killed automatically because it receives no commands from the client script during this period. I don't observe any freezes.

**Comment by JamesChungZLL** [comment]
I have set the timeout to 300 seconds, but the Appium still hangs on pull image file which's size is 0;

**Comment by mykola-mokhnach** [comment]
Does the freeze happen if you try to pull the same file manually using _adb pull_?

**Comment by JamesChungZLL** [comment]
No, when I type 'adb pull ...' manually,   the command works well, and pull the 0 size png file.

**Comment by mykola-mokhnach** [comment]
Can it be, that an incorrect Appium og file is attached?

**Comment by StoneTree1** [comment]
I'm seeing this issue too. Happens at the same point in a test every time I run it. Screenshots prior to this point are working. Issue also occurs in 1.6.6beta2. Issue does not occur in 1.6.4

Desktop OS/version used to run Appium: Mac 10.11.6
Mobile platform/version under test: Android 6.0.1 and 5.0.2
Real device or emulator/simulator: Real Nexus 5 and LG g3
Appium CLI or Appium.app|exe: CLI


> [HTTP] --> GET /wd/hub/session/c6211690-5531-47f3-8563-a8c70bc8462b/screenshot {}
> [debug] [MJSONWP] Calling AppiumDriver.getScreenshot() with args: ["c6211690-5531-47f3-8563-a8c70bc8462b"]
> [debug] [ADB] Device API level: 23
> [AndroidDriver] Cannot get screenshot data with 'adb exec-out' because of 'Command output is not a valid PNG file ( !== 89504e47)'. Defaulting to 'adb shell' call
> [debug] [ADB] Getting connected devices...
> [debug] [ADB] 1 device(s) connected
> [debug] [ADB] Running '/usr/local/opt/android-sdk/platform-tools/adb' with args: ["-P",5037,"-s","09852c1d032694da","shell","/system/bin/rm","/data/local/tmp/screenshot.png;","/system/bin/screencap","-p","/data/local/tmp/screenshot.png"]
> [debug] [ADB] Running '/usr/local/opt/android-sdk/platform-tools/adb' with args: ["-P",5037,"-s","09852c1d032694da","pull","/data/local/tmp/screenshot.png","/var/folders/3y/3bsjq8wx3qq1vggdsbbmh94h0000gq/T/appium117527-86511-1raengt.paseixusor.png"]

**Comment by StoneTree1** [comment]
Note in my case Appium is not fully unresponsive. There are empty responses coming through. But they take several minutes to come through. And after the initial empty response to the screenshot request all other requests have similar empty responses and delay in returning. 

> [HTTP] --> GET /wd/hub/session/c6211690-5531-47f3-8563-a8c70bc8462b/screenshot {}
[debug] [MJSONWP] Calling AppiumDriver.getScreenshot() with args: ["c6211690-5531-47f3-8563-a8c70bc8462b"]
[debug] [ADB] Device API level: 23
[AndroidDriver] Cannot get screenshot data with 'adb exec-out' because of 'Command output is not a valid PNG file ( !== 89504e47)'. Defaulting to 'adb shell' call
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/usr/local/opt/android-sdk/platform-tools/adb' with args: ["-P",5037,"-s","09852c1d032694da","shell","/system/bin/rm","/data/local/tmp/screenshot.png;","/system/bin/screencap","-p","/data/local/tmp/screenshot.png"]
[debug] [ADB] Running '/usr/local/opt/android-sdk/platform-tools/adb' with args: ["-P",5037,"-s","09852c1d032694da","pull","/data/local/tmp/screenshot.png","/var/folders/3y/3bsjq8wx3qq1vggdsbbmh94h0000gq/T/appium117527-86511-1raengt.paseixusor.png"]
[HTTP] <-- GET /wd/hub/session/c6211690-5531-47f3-8563-a8c70bc8462b/screenshot - - ms - - 
[HTTP] --> POST /wd/hub/session/c6211690-5531-47f3-8563-a8c70bc8462b/element/47/click {}
[debug] [MJSONWP] Calling AppiumDriver.click() with args: ["47","c6211690-5531-47f3-8563-a8c70bc8462b"]
[HTTP] <-- POST /wd/hub/session/c6211690-5531-47f3-8563-a8c70bc8462b/element/47/click - - ms - - 
[HTTP] --> GET /wd/hub/session/c6211690-5531-47f3-8563-a8c70bc8462b/screenshot {}
[debug] [MJSONWP] Calling AppiumDriver.getScreenshot() with args: ["c6211690-5531-47f3-8563-a8c70bc8462b"]
[HTTP] <-- GET /wd/hub/session/c6211690-5531-47f3-8563-a8c70bc8462b/screenshot - - ms - - 
[HTTP] --> GET /wd/hub/session/c6211690-5531-47f3-8563-a8c70bc8462b/source {}
[debug] [MJSONWP] Calling AppiumDriver.getPageSource() with args: ["c6211690-5531-47f3-8563-a8c70bc8462b"]

**Comment by mykola-mokhnach** [comment]
I did some adjustments to the screenshoting method so the change will be available in Appium 1.6.6-beta soon. Just keep an eye on the PR above.

**Comment by mayureshshirodkar** [comment]
@mykola-mokhnach i am facing a similar issue. In my case, Appium hangs every time screenshot method is called. Also i take the screenshot in a Webview context.
Right now i am on Appium 1.6.6-Beta 3.


Here are my logs:
https://gist.github.com/mayureshshirodkar/301ce534d9ff27c6f1789044f3165507

**Comment by mykola-mokhnach** [comment]
@mayureshshirodkar I assume screenshot inside a webview is not handled by Appium, but rather by chromedriver itself, so your issue is most likely unrelated to that.

**Comment by jlipps** [comment]
correct, screenshots in web contexts are handled by Chromedriver, unless you use `nativeWebScreenshot`

**Comment by kimbo-slice** [comment]
I'm curious why this issue has been closed - I am seeing the same issue even after upgrading to 1.7.1 today. 

I'm fairly certain this is a regression, as this functionality was working in previous Appium versions, but now is not (I can't confirm this for sure).

My use case is: I'm automating an app that pulls up the Visa Checkout after that payment method is selected. I don't know if this is a new activity or what's happening behind the scenes, but the checkout doesn't seem to be a part of the native app. I'm using the inspector to try to grab the elements on the screen. 

I'm on an Android 6 device.
I've attempted this using Appium 1.6.5 using the Desktop version (where it just freezes), and Appium 1.7.1, where I get the following logs: https://gist.github.com/kimbo-slice/768a00339efc8b2c9c4650d7fca7dba2

**Comment by jlipps** [comment]
@kimbo-slice thanks for the update. Could you connect your same device and manually navigate it to the screen in question, then run these adb commands to try it outside of appium:

```
adb -P 5037 -s 0499f211251e9b62 shell /system/bin/rm /data/local/tmp/screenshot.png
adb -P 5037 -s 0499f211251e9b62 shell /system/bin/screencap -p /data/local/tmp/screenshot.png
adb -P 5037 -s 0499f211251e9b62 shell ls -la /data/local/tmp/screenshot.png
```

What do you get there?

**Comment by kimbo-slice** [comment]
Sure thing! Here's what I get:

cpe-172-100-3-186:~ kklask$ adb -P 5037 -s 0499f211251e9b62 shell /system/bin/rm /data/local/tmp/screenshot.png
cpe-172-100-3-186:~ kklask$ adb -P 5037 -s 0499f211251e9b62 shell /system/bin/screencap -p /data/local/tmp/screenshot.png
cpe-172-100-3-186:~ kklask$ adb -P 5037 -s 0499f211251e9b62 shell ls -la /data/local/tmp/screenshot.png
-rw-rw-r-- shell    shell           0 2017-09-27 17:08 screenshot.png

**Comment by mykola-mokhnach** [comment]
The behaviour on Appium 1.7+ is correct - it throws an exception about the screenshot size is zero, which is true. I don't think anything else can be done here.

**Comment by mykola-mokhnach** [comment]
@dpgraham

**Comment by kimbo-slice** [comment]
@mykola-mokhnach But why is the screenshot size zero? Is this something we're just not going to be able to automate? I'm seeing this on another project as well, when it *looks* like another sdk or activity is launched and the screenshot returns with size zero. Works on iOS but not Android.

**Comment by mykola-mokhnach** [comment]
It might be that screenshoting is disabled by the application under test. So then there is no way to workaround it.

**Comment by kimbo-slice** [comment]
@mykola-mokhnach This has worked with previous versions of Appium and also with an Android 6 emulator, so I don't think it's the application under test.

**Comment by dpgraham** [comment]
@kimbo-slice When you did the adb commands that @jlipps suggested, what was output to `/data/local/tmp/screenshot.png`?

**Comment by mykola-mokhnach** [comment]
> This has worked with previous versions of Appium and also with an Android 6 emulator, so I don't think it's the application under test.

Try to update Android SDK and tools to the most recent version then. Appium anyway uses ADB tool, so if it cannot take the screenshot then Appium server cannot do that as well.

**Comment by dpgraham** [comment]
Android has a security setting called [FLAG_SECURE](https://developer.android.com/reference/android/view/WindowManager.LayoutParams.html#FLAG_SECURE) that prevents screenshots from being taken. I doubt that there's any workaround for this because it's a security feature doing what it's supposed to do.

What we should do is add logging to notify the user that this MAY be the issue.
