### ISSUE TITLE
realDeviceLogger capability should be brought back

### ISSUE THREAD

**Issue by rajfidel** [appium/appium#8698]
## The problem

realDeviceLogger capability was deprecated in Appium 1.6.4
When starting appium, idevicesyslog instance is created. 
I have tried providing the deprecated 'realDeviceLogger' capability to point to deviceconsole but it ends up starting a idevicesyslog instance instead.

Why I need this:
idevicesyslog intermittently stops output of device logs. 
The application states / events in background and foreground states are exposed to us for testing via NSLog statements that we access in real time using idevicesyslog / deviceconsole (using --show-ios-log).
Would like to replace the capability to be able to set the default logger to 'deviceconsole' instead of 'idevicesyslog'

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: macOS 10.12.5
* Node.js version (unless using Appium.app|exe): 7.1
* Mobile platform/version under test: 10.2
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI

## Link to Appium logs

https://gist.github.com/rajfidel/ed31df123b8d542bf409a1b4289776ad

## Code To Reproduce Issue
Start the appium server:
appium --log-timestamp --local-timezone --address 10.94.64.33 --webkit-debug-proxy-port 27752 --port 4724 --tmp /tmp/4724 | fgrep --line-buffered -e [Appium] -e [XCUITest] -e [MJSONWP] -e [JSONWP -e [HTTP] -e [iOS] -e [BaseDriver]

Run the below code (used dotnet driver)

            DesiredCapabilities caps1 = new DesiredCapabilities();

            caps1.SetCapability(MobileCapabilityType.PlatformName, "iOS");
            caps1.SetCapability(MobileCapabilityType.DeviceName, "iPhone");
            caps1.SetCapability(MobileCapabilityType.Udid, "<<hidden>>");
            caps1.SetCapability(MobileCapabilityType.AutomationName, "xcuitest");
            caps1.SetCapability(CapabilityType.TakesScreenshot, "true");
            caps1.SetCapability(MobileCapabilityType.NewCommandTimeout, "36000");
            caps1.SetCapability(IOSMobileCapabilityType.LaunchTimeout, "120000");
            caps1.SetCapability("wdaLocalPort", "27752");
            caps1.SetCapability(IOSMobileCapabilityType.BundleId, "com.apple.Preferences");
            caps1.SetCapability(IOSMobileCapabilityType.ShowIOSLog, "true");
            caps1.SetCapability("realDeviceLogger", "/usr/local/lib/node_modules/deviceconsole/deviceconsole");

            AppiumDriver<AppiumWebElement> appDriver1 = new IOSDriver<AppiumWebElement>(new Uri("http://" + AppConfig.APPIUM_SERVER_IP + @":" + AppConfig.APPIUM_SERVER_PORT + "/wd/hub"), caps1);

**Comment by imurchie** [comment]
Try removing `idevicesyslog` from your PATH.

**Comment by rajfidel** [comment]
New gist of Appium logs with idevicesyslog removed from PATH
https://gist.github.com/rajfidel/367af4ae52148c7f5dc3a8eb4b4c7925

The line of interest is:
2017-06-19 10:57:15:681 - [XCUITest] Could not capture logs from device. Continuing without capturing logs.

**Comment by rajfidel** [comment]
<img width="1235" alt="screen shot 2017-06-19 at 11 07 30 am" src="https://user-images.githubusercontent.com/577594/27299044-d14ffa80-54df-11e7-834a-46ba92e372a4.png">

Also, deviceconsole at the correct location as shown from the commandline output screenshot

**Comment by imurchie** [comment]
I've proposed some changes.

In the meantime, the "correct" place for automatically using `ideviceconsole` is to have it installed in the `build` directory of Appium. It used to be bundled there. I'm not sure when it was removed.

**Comment by imurchie** [comment]
Update ios driver and xcuitest driver to allow the user to specify a `realDeviceLogger` capability, which is either:
* nothing (use the system `idevicesyslog`)
* `idevicesyslog` (use the system `idevicesyslog`)
* path to `idevicesyslog`
* `deviceconsole` (use `deviceconsole` in Appium's `build` directory)
* path to `deviceconsole`.

**Comment by samsonbarukula** [comment]
I have enabled the show_XCODE_LOG and Show_IOS_LOG but still not getting the crash logs ? pls help

**Comment by samsonbarukula** [comment]
through java

**Comment by uterator** [comment]
Hi, is there a ticket for this? 
> I have enabled the show_XCODE_LOG and Show_IOS_LOG but still not getting the crash logs ? pls help
> through java
I am experiencing the same issue, the crash log is available on simulators but not on devices. The show-ios-log is ON.
Thanks

**Comment by imurchie** [comment]
Crash logs have never been inlined into the Appium logs. The device logs will work.
