### ISSUE TITLE
Failed to create WDA session. Retrying... error appears

### ISSUE THREAD

**Issue by DevaVG** [appium/appium#8700]
## The problem

While trying to launch iPhone simulator through appium with capabilities, it fails to create wda session and test application do not get launched. 

## Environment
Appium v1.6.5; 
XCUITestDriver version: 2.30.0; 
Xcode version set to '8.3.2';
iOS SDK Version set to '10.3'

## Details

I am using below capabilities for launching iPhone simulator from appium. Simulator launches successfully and application installation and web driver installation is also successful but application is not getting opened and on seeing appium log it says failed to create wda session. 
```json
{
  "platformName": "ios",
  "platformVersion": "10.3",
  "deviceName": "iPhone SE",
  "automationName": "XCUITest",
  "app": "/Users/deva/Downloads/M-FilesIoSLatest.app"
}
```
## Link to Appium logs
https://gist.github.com/DevaVG/ed0c47789f5771a200e5137f9a1930fe

**Comment by imurchie** [comment]
Can your app be launched manually? This seems like an issue with the build.

**Comment by GhenTerr** [comment]
I have a similar issue where if I put 'autoLaunch' capability as false, the app won't get installed and stuck at Failed to create WDA session. If I set it to be true, everything worked fine.

On a real iPhone 7.

**Comment by DevaVG** [comment]
@imurchie... yes i can launch application without any problems..

**Comment by imurchie** [comment]
Strange. `ipa` files are rarely built for simulators.

**Comment by DevaVG** [comment]
i m sorry, i have posted wrong capability "app": "/Users/deva/Downloads/M-FilesIoSLatest.ipa" . Actually using .app file.

**Comment by imurchie** [comment]
Do you have logs for such a run?
