### ISSUE TITLE
Broken link in appium/docs/en/advanced-concepts/grid.md

### ISSUE THREAD

**Issue by z00sts** [appium/appium#8701]
Broken link to http://selenium.googlecode.com/git/docs/api/java/org/openqa/selenium/Platform.html in appium/docs/en/advanced-concepts/grid.md

```
The requested URL /git/docs/api/java/org/openqa/selenium/Platform.html was not found on this server.
```

**Comment by dpgraham** [comment]
Thanks for reporting this @z00sts. I just put in a PR to fix it now.
