### ISSUE TITLE
Appium 1.6.5 unable to load page source on certain device

### ISSUE THREAD

**Issue by GEvanscsumb** [appium/appium#8703]
## The problem

Using two different android devices I was getting different results when navigating to another activity on the android app I'm testing. Using the desktop appium 1.6.5, the page source loaded for one device, but not the other. However, it is able to load in 1.5.3.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Last Appium version that did not exhibit the issue (if applicable): 1.5.3
* Desktop OS/version used to run Appium: Sierra 10.12.5
* Mobile platform/version under test: 6.0.1
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium.app

## Desired Capabilities

Device with problem
devicename=HTC 10
platform=Android
platformversion=6.0.1

Device that works
devicename=Nexus 6p
platform=Android
platformversion=7.1.2

## Link to Appium logs

Note: Some of the from setting up with the app have been excluded due to confidentiality reasons. Where the log ends is where appium gets stuck on getting the page source. The command is sent to the device fine, but getting the new page source leads to an endless loading screen.

https://gist.github.com/GEvanscsumb/f967229deb4091ae9d31e36f9ae7471a

## Code To Reproduce Issue [ Good To Have ]

I don't have access to the source code.

**Comment by mykola-mokhnach** [comment]
Try switching to UIAutomator2 backend
