### ISSUE TITLE
Tabs are not getting closed after driver.quit on IOS

### ISSUE THREAD

**Issue by ravi1124339** [appium/appium#8705]
## The problem

I am running the tests on iPad as well as iPhone but after the tests are complete and driver.quit is called the Safari is getting closed.
If any subsequent test starts after this then what I can see is the previous tab is still there and the safari is getting launched with tests running in a new tab.

## Environment

* Appium version (or git revision) that exhibits the issue: Appium 1.6.5
* Desktop OS/version used to run Appium: macOS Sierra 10.12.4
* Node.js version (unless using Appium.app|exe): v6.2.1
* Mobile platform/version under test: IOS 10.3.1
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium app on MAC

## Details
I used the capabilities below to run the code but everytime the tabs are retained.
Also tried adding 
Capabilities.Add(new KeyValuePair<string, object>("ensureClearSession", "true"));
to the capabilities but it didn't worked.
The tests are working fine except the tab issue.

## Code To Reproduce Issue [ Good To Have ]

The Capabilities that I am using is as follows:
Capabilities.Add(new KeyValuePair<string, object>("xcodeOrgId", "ORG_ID_OF_DEVELOPER_ACC"));
Capabilities.Add(new KeyValuePair<string, object>("xcodeSigningId", "iPhone Developer"));
Capabilities.Add(new KeyValuePair<string, object>("wdaLaunchTimeout", 200000));
Capabilities.Add(new KeyValuePair<string, object>("fullReset", _false));
Capabilities.Add(new KeyValuePair<string, object>("platformName", "iOS"));
Capabilities.Add(new KeyValuePair<string, object>("automationName", "XCUITest"));
Capabilities.Add(new KeyValuePair<string, object>("platformVersion", 10.3.1));
Capabilities.Add(new KeyValuePair<string, object>("udid", "DeviceName"));
Capabilities.Add(new KeyValuePair<string, object>("deviceName", "DeviceName"));
Capabilities.Add(new KeyValuePair<string, object>("newCommandTimeout", 300));
Capabilities.Add(new KeyValuePair<string, object>("clearSystemFiles", true));
Capabilities.Add(new KeyValuePair<string, object>("preventWDAAttachments", true));
Capabilities.Add(new KeyValuePair<string, object>("launchTimeout", 180000));
Capabilities.Add(new KeyValuePair<string, object>("app", ""));
Capabilities.Add(new KeyValuePair<string, object>("browserName", "Safari"));
Capabilities.Add(new KeyValuePair<string, object>("safariInitialUrl", PageUri));

**Comment by mykola-mokhnach** [comment]
You may try to close tabs by overriding the quit method: https://stackoverflow.com/questions/29502255/is-there-a-way-to-close-a-tab-in-webdriver-or-protractor

**Comment by dpgraham** [comment]
Closing this. I think @mykola-mokhnach's link should answer your questions.
