### ISSUE TITLE
Unable to swipe an element with XCUI

### ISSUE THREAD

**Issue by gkvappium** [appium/appium#8707]
## The problem

Unable to swipe an element with XCUI

## Environment

* Appium version (or git revision) that exhibits the issue:1.6.6-beta
* Last Appium version that did not exhibit the issue (if applicable):1.6.0 beta
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:IOS 10.2
* Real device or emulator/simulator:Real device
* Appium CLI or Appium.app|exe:

## Details

I am trying to swipe an element (Swiping actually results in change of track in the music player app that I am working with). But the swipe is treated as a click/tap which results in a different behavior than what I am looking for.

I am using Appium python web driver and use something like this
self.driver.execute_script("mobile:swipe",
                                       {"direction":'right',"element":element})

I've also tried scroll which results in the same behavior. Logs might not be useful in this case since there is no error as such.

debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"y\" : 520,\n    \"x\" : 0,\n    \"width\" : 48,\n    \"height\" : 48\n  },\n  \"sessionId\" : \"6E59358E-7EE2-4F3F-BCD0-BBD1EDD0ECDD\",\n  \"status\" : 0\n}"
[debug] [MJSONWP] Responding to client with driver.getLocation() result: {"x":0,"y":520}
[HTTP] <-- GET /wd/hub/session/e4e8edbc-29c9-47ec-a3e0-7a5743ccc063/element/100F4EBB-30B1-492B-9C44-42FD4226C265/location 200 723 ms - 87 
[HTTP] --> GET /wd/hub/session/e4e8edbc-29c9-47ec-a3e0-7a5743ccc063/element/100F4EBB-30B1-492B-9C44-42FD4226C265/location {}
[debug] [MJSONWP] Calling AppiumDriver.getLocation() with args: ["100F4EBB-30B1-492B-9C44-42FD4226C265","e4e8edbc-29c9-47ec-a3e0-7a5743ccc063"]
[debug] [XCUITest] Executing command 'getLocation'
[debug] [JSONWP Proxy] Proxying [GET /element/100F4EBB-30B1-492B-9C44-42FD4226C265/rect] to [GET http://localhost:8100/session/6E59358E-7EE2-4F3F-BCD0-BBD1EDD0ECDD/element/100F4EBB-30B1-492B-9C44-42FD4226C265/rect] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"y\" : 520,\n    \"x\" : 0,\n    \"width\" : 48,\n    \"height\" : 48\n  },\n  \"sessionId\" : \"6E59358E-7EE2-4F3F-BCD0-BBD1EDD0ECDD\",\n  \"status\" : 0\n}"
[debug] [MJSONWP] Responding to client with driver.getLocation() result: {"x":0,"y":520}
[HTTP] <-- GET /wd/hub/session/e4e8edbc-29c9-47ec-a3e0-7a5743ccc063/element/100F4EBB-30B1-492B-9C44-42FD4226C265/location 200 682 ms - 87 
[HTTP] --> POST /wd/hub/session/e4e8edbc-29c9-47ec-a3e0-7a5743ccc063/execute {"sessionId":"e4e8edbc-29c9-47ec-a3e0-7a5743ccc063","args":[{"direction":"right","element":{"element-6066-11e4-a52e-4f735466cecf":"100F4EBB-30B1-492B-9C44-42FD4226C265","ELEMENT":"100F4EBB-30B1-492B-9C44-42FD4226C265"}}],"script":"mobile:swipe"}
[debug] [MJSONWP] Calling AppiumDriver.execute() with args: ["mobile:swipe",[{"direction":"right","element":{"element-6066-11e4-a52e-4f735466cecf":"100F4EBB-30B1-492B-9C44-42FD4226C265","ELEMENT":"100F4EBB-30B1-492B-9C44-42FD4226C265"}}],"e4e8edbc-29c9-47ec-a3e0-7a5743ccc063"]
[debug] [XCUITest] Executing command 'execute'
[debug] [JSONWP Proxy] Proxying [POST /wda/element/100F4EBB-30B1-492B-9C44-42FD4226C265/swipe] to [POST http://localhost:8100/session/6E59358E-7EE2-4F3F-BCD0-BBD1EDD0ECDD/wda/element/100F4EBB-30B1-492B-9C44-42FD4226C265/swipe] with body: {"direction":"right"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"6E59358E-7EE2-4F3F-BCD0-BBD1EDD0ECDD","status":0}
[debug] [MJSONWP] Responding to client with driver.execute() result: {}
[HTTP] <-- POST /wd/hub/session/e4e8edbc-29c9-47ec-a3e0-7a5743ccc063/execute 200 2200 ms - 74 
[HTTP] --> POST /wd/hub/session/e4e8edbc-29c9-47ec-a3e0-7a5743ccc063/timeouts/implicit_wait {"sessionId":"e4e8edbc-29c9-47ec-a3e0-7a5743ccc063","ms":0}
[debug] [MJSONWP] Calling AppiumDriver.implicitWait() with args: [0,"e4e8edbc-29c9-47ec-a3e0-7a5743ccc063"]
[debug] [XCUITest] Executing command 'implicitWait'
[debug] [BaseDriver] Set implicit wait to 0ms
ue [ Good To Have ]

@mykola-mokhnach @imurchie can you please have a look into this?

**Comment by mykola-mokhnach** [comment]
what the _element_ variable contains? You can also try _scroll_ endpoint either with relative and absolute coordinates.

**Comment by gkvappium** [comment]
element is self.song_sticky_player.wait_until_visible().web_element (I have integrated toolium into the framework so as to facilitate page object modelling)

song_sticky_player = Button(MobileBy.ACCESSIBILITY_ID, "txt_artist_name")

Is there any other way apart from using co-ordinates?

I also tried the below code but doesn't work
element = self.song_sticky_player.wait_until_visible().web_element
 location = slider.location
 endx = int(slider.size.get('width'))
 y = int(slider.location.get('y'))
 action = TouchAction(self.driver)
 action.press(element, 2000).move_to(None, endx, y).release().perform()

**Comment by mykola-mokhnach** [comment]
The mobile:swipe expects element's id to be passed as argument rather than object instance itself. However, I cannot say how to extract in Python client.

**Comment by gkvappium** [comment]
Can you redirect this to somebody who can help me out ?

Thanks

**Comment by mykola-mokhnach** [comment]
Probably @imurchie

**Comment by amedvedjev** [comment]
but best redirection is https://discuss.appium.io/

**Comment by gkvappium** [comment]
@imurchie ,

Could you please have a look into this? I also tried action.press(elem1).wait(2000).move_to(elem2).release().perform() which Appium executes as dragfromtoforduration. But I don't see any click happening.

//localhost:8100/session/C0896A74-4856-40AA-BE06-085DDEDFE81C/wda/dragfromtoforduration] with body: {"fromX":24,"fromY":544,"toX":292,"toY":544,"duration":2}
