### ISSUE TITLE
appium 1.6.5 failing on ios-deploy --uninstall

### ISSUE THREAD

**Issue by claudiosvcc** [appium/appium#8709]
## The problem
By using appium 1.6.5, appium is failing on the ios-deploy --uninstall step. Doesn't matter if app is installed or not, fails the same way.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Desktop OS/version used to run Appium: Sierra 10.12.5
* Node.js version (unless using Appium.app|exe): 8.0.0
* Real device or emulator/simulator: real device on iOS 10
* Appium CLI or Appium.app|exe: CLI

## Details
This is a Cordova app v6.5.0 built on Xcode8. The app installs fine manually. I can also install it using ideviceinstaller.

I've tried running ios-deploy manually. It fails saying "Unable to get bundle id from user command or package /var/folders/etc <the full path where the app files were extracted>". I can see the Info.plist has the correct bundle Id on it. 

I'm starting appium with the bundleId capability set. If I don't pass the bundle_id on capabilities, it will fail with a similar error message, but on appium side. If I execute ios-deploy passing the bundle_id as parameter, it works fine.

It seems to me that by passing the bundle_id as a capability makes appium works fine because it ignores the step of trying to get the bundleId from the app itself. But instead of also sending the bundle ID to ios-deploy, it's sending the app path, which will fail.

I have no idea why the bundle id is not being detected.

Just a curious detail: I was running on ios-deploy 1.3.2 before. The app was installing and running on device (it was failing in a later step, but it was installing and I could grab a screenshot, for example). However, the same error message was being shown. Difference is that it wasn't stopping the test. After I upgraded ios-deploy to 1.9.0 I started seeing this failure on test. 

## Link to Appium logs

https://gist.github.com/anonymous/c4454d4d649db023786646d5c9e28cc0

**Comment by mykola-mokhnach** [comment]
If the app cannot be installed manually then I assume it's rather ios-deploy issue or some problem with configuration of your application under test. Try to report the problem directly into  https://github.com/phonegap/ios-deploy/issues

Closed as non-Appium issue.

**Comment by claudiosvcc** [comment]
After struggling a bit, I've figured out what the problem is: The url I'm using is valid and can be downloaded by anyone with the link. However it has query values  containing a SAS key (something like https://host/MyApp.ipa?sv=abcd&sr=deff, etc. This is making appium download the ipa and copy it directly to temp folder as it was an app file, without unzipping it. If I have the same  app without the appended SAS, it will download AND unzip the file, making the test work fine.

Is there any way to avoid this behavior?
