### ISSUE TITLE
Receiving Error Code 65

### ISSUE THREAD

**Issue by karbon62** [appium/appium#8712]
## The problem
Tried installing most of the required dependencies however I am still receiving an Error 65.

## Environment
Appium version 1.0.2-beta.2
Mac 10.12.5
iPhone 5s | 10.3
Real device
Appium CLI
## Link to Appium logs

https://gist.github.com/karbon62/f5e156b1d142c8a4d01e2a4edb0b5edf

**Comment by imurchie** [comment]
You can run the `xcodebuild` command manually to see what the problem is:
```
cd /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent

xcodebuild build-for-testing test-without-building -project /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=e65c629569f4a82eaa7a7f0946d5be85e28d83da -configuration Debug IPHONEOS_DEPLOYMENT_TARGET=10.3
```

I have also had this particular error happen and resolved it by switching USB ports that the device was connected to. No idea why that helped.

**Comment by karbon62** [comment]
I haven't got xcode setup to do this. Its a app that Im using to test my script basically and to be able to run tests using Appium server.

**Comment by imurchie** [comment]
Appium is running that xcodebuild command in order to launch the tests, so if it is not possible to run manually, it will not be able to be run automatically.
