### ISSUE TITLE
Appium 1.6.4; on Android 6.0.1 - execution gives Launcher Activity error when run from RDC

### ISSUE THREAD

**Issue by poojatrivedi7** [appium/appium#8713]
Currently we are using Appium 1.6.4 to automate Android scripts in 6.0.1. We have Win 7 professional Machine. Scripts are written in Python Code Base.

With the below given desired capability; we are able to run tests smoothly on local machine:
'app' = 'C:\\Test\\Apps\\APK File name'
'deviceName' = 'SAMSUNG-S6-EDGE'
'newCommandTimeout' = 600
'noReset' = True
'platformName' = 'Android'
'platformVersion'= '6.0.1'

However, when someone takes a Remote Desktop Connection (RDC) for this same machine and uses Vysor to control device; then at that time; for appium scripts execution we get a Launcher activity error given below and this occurrence is intermittent. Sometimes scripts do run correctly; but sometimes Appium throws this error as soon as we instantiate with this apk :

Message: An unknown server-side error occurred while processing the command. Original error: Error occured while starting App. Original error: com.test.panic/md5db13112359cbaf44a20e73cc78238655.LauncherActivity or com.testpanic.md5db13112359cbaf44a20e73cc78238655.LauncherActivity never started

We have avoided giving app package and activity as we have many apk's involved and would add more entries on config file. If any one can let us know any work around in current scripts without using app package and launcher activity; it would be of much help as we have a geographically distributed team and RDC Execution is of utmost importance to run scripts.

**Comment by mykola-mokhnach** [comment]
Can you please attach two full appium logs - for the case when test startup succeeds and for the case when the same test fails?

**Comment by poojatrivedi7** [comment]
Thanks @mykola-mokhnach 
Please find both logs attached herewith 
[appium-pass-logs.txt](https://github.com/appium/appium/files/1097607/appium-pass-logs.txt)
[appium-fail-logs.txt](https://github.com/appium/appium/files/1097608/appium-fail-logs.txt)

**Comment by mykola-mokhnach** [comment]
Both logs don't show anything unusual. I think it's the application under test, which might randomly crash on startup. Try to scan the logcat output for the failed case. Probably, you'll find some stacktraces there.

**Comment by jlipps** [comment]
The activity which finallylaunches is `md5e28a4be388d559c905d7623f90ab332c.HomeActivity`. You should add an `appWaitActivity` with this value to tell Appium this is the activity which it should ultimately wait for. Many Android apps have different activities which launch the app vs which are the ones that run when the app is launched.
