### ISSUE TITLE
Error: Could not connect to a valid app after 25 tries in iOS App

### ISSUE THREAD

**Issue by Logakarti** [appium/appium#8715]
Error: Could not connect to a valid app after 25 tries occur while running cases in iOS simulators. How to resolve this error?

* Appium version : 1.6.4
* Desktop OS/version used to run Appium: MAC 
* iOS Simulator

**Comment by Logakarti** [comment]
@jlipps

**Comment by mykola-mokhnach** [comment]
Please ask questions in Appium forum. We only solve issues here.

**Comment by Logakarti** [comment]
@mykola-mokhnach : Please give appium forum link

**Comment by mykola-mokhnach** [comment]
yw https://discuss.appium.io/
