### ISSUE TITLE
How to enter the names of all the elements in the array? And how click to XCUIElementTypeStaticText?

### ISSUE THREAD

**Issue by Akapylechka** [appium/appium#8716]
1. How do you enter the names of all the elements that are on the screen in an array?
So that depending on what on the screen we did different actions
If you immediately try to find an item, and there is not, then an error

2. I have this structure:
    `<XCUIElementTypeButton>` 
           ` <XCUIElementTypeStaticText name="Empty category">` 

I need to click on this "button" field, how can this be done? By means of what to address?
(I try this: MobileElement button = (MobileElement) (new WebDriverWait(driver, 20)).until(ExpectedConditions.presenceOfElementLocated(By.xpath(buttonXpath))); but don't works)

**Comment by mykola-mokhnach** [comment]
Sorry, but I can hardly understand what this is about. Would you mind to provide a detailed description of the problem? Screenshots, logs, more code examples will be useful.

**Comment by Akapylechka** [comment]
У меня после нажатия на кнопку может показаться один из трех разных экранов. Я хочу проверить появившийся экран на содержание "Согласна", "Да, Согласна" или "Да" (На экране будет только один из этих вариантов). Дальнейшие действия зависят от появившегося экрана.

**Comment by Akapylechka** [comment]
I after clicking the button may seem one of three different screens. I want to check the screen that appears for the content "I agree", "Yes, I agree" or "Yes" (Only one of these options will be displayed on the screen). Further actions depend on the screen that appears.

**Comment by mykola-mokhnach** [comment]
If you just want to create a locator, which matches any of these buttons, and if these all buttons have their captions set as **label** attribute then the resulting locator might look like:

iOS Predicate (faster one)

```
label == 'I agree' OR label == 'Yes, I agree' OR label == 'Yes'
```

xpath (slower one):

```
//*[@label='I agree' or @label='Yes, I agree' or @label='Yes']
```
