### ISSUE TITLE
org.openqa.selenium.NoSuchElementException: An element could not be located on the page using the given search parameters. (WARNING: The server did not provide any stacktrace information)

### ISSUE THREAD

**Issue by yefankongge** [appium/appium#8718]
## The problem

org.openqa.selenium.NoSuchElementException: An element could not be located on the page using the given search parameters. (WARNING: The server did not provide any stacktrace information)
## Environment

* Appium version :1.6.4
* java-client:5.0.0-BETA8
* mac os:10.12
* simulator:iphone6s 10.3

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/987EDCD5-A010-49B2-A93C-4BE365EC2E7D/element] with body: {"using":"xpath","value":"//XCUIElementTypeTextField[1]"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":"*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[1]\n\n(\n\t0   CoreFoundation                      0x000000010d4c9b0b __exceptionPreprocess + 171\n\t1   libobjc.A.dylib                     0x000000010cf2e141 objc_exception_throw + 48\n\t2   CoreFoundation                      0x000000010d3de5cd -[__NSPlaceholderArray initWithObjects:count:] + 269\n\t3   CoreFoundation                      0x000000010d3e5314 +[NSArray arrayWithObjects:count:] + 52\n\t4   XCTest                              0x000000010c92a4f7 -[XCElementSnapshot(Hitpoint) _transformPoint:windowContextID:windowDisplayID:] + 133\n\t5   XCTest                              0x000000010c92a8e9 -[XCElementSnapshot(Hitpoint) hitPoint] + 386\n\t6   WebDriverAgentLib                   0x000000011e46df4a -[XCElementSnapshot(FBIsVisible) fb_isVisible] + 810\n\t7   WebDriverAgentLib                   0x000000011e478f3b -[XCElementSnapshot(WebDriverAttributes) isWDVisible] + 43\n\t8   WebDriverAgentL...

## Code To Reproduce Issue [ Good To Have ]

        driver.findElementByXPath("//XCUIElementTypeStaticText[@name='我的']").click();
        driver.manage().timeouts().implicitlyWait(2, TimeUnit.SECONDS);
        driver.findElementByXPath("//XCUIElementTypeTextField[1]").sendKeys("xxxxxx");
       driver.findElementByXPath("//XCUIElementTypeSecureTextField[1]").sendKeys("xxxxxx");
        driver.findElementByXPath("//XCUIElementTypeButton[@name='登 录']").click();

**Comment by mykola-mokhnach** [comment]
This is known WDA issue. Update your Appium to 1.6.6-beta and try again

**Comment by yefankongge** [comment]
thanks，I will try

**Comment by YangDan** [comment]
I met the same problem,  had you  sloved ?

**Comment by jgouda** [comment]
I also have same issue, any body got solution for this issue. Please share it, if you found it.

**Comment by Jyothiik** [comment]
hi am also facing the same issue anyone kindly help me

**Comment by mudassar12** [comment]
i am was facing the same problem when i restart my android device this was working fine for me thanks

**Comment by netravm** [comment]
Use id instead of xapth. Just now I have done experiment, which is working for id, not for xpath..
