### ISSUE TITLE
PDF file upload cannot be uploaded on website using Appium on Android emulator

### ISSUE THREAD

**Issue by harshit2** [appium/appium#8719]
## The problem

PDF file upload cannot be uploaded on website using Appium on Android emulator.

I am using Saucelabs and raise the ticket with Saucelabs for the same, and the answer was Appium is not having file upload feature and to request Appium community to build the feature. Thanks.

PDF cannot be uploaded.
Can you help me on how I can upload PDF file on Android emulator on the website I’m testing.
The below code help me to upload file from my local to website under test on saucelabs in desktop mode, but not in Android emulator.
driver.setFileDetector(new LocalFileDetector());
Please help.

## Environment

* Appium version 1.6.4
SauceLabs
Android emulator

**Comment by jlipps** [comment]
@harshit2 the way to accomplish this is to use `pushFile` to get a file into the device's library, then automate the UI of the app when it's requesting a file upload. i.e., do it the way a user would do it.
