### ISSUE TITLE
Not able to change the date value of a date time picker which is in "ddd dd MMM HH mm" format

### ISSUE THREAD

**Issue by gopi-seeni** [appium/appium#8720]
My iOS app has the picker control for setting date & time in a table cell. When I try to change the date time using send key method, then the time is getting changed correctly. But no luck with the date. 

My picker is in below format

PickeWheel[1]  - ddd dd MMM (Tue 22 Mar 10)  - Not working
PickerWheer[2] - HH - Working
PickerWheel[3] - mm - Working

Appium Versions I checked
1.6.3 to latest 1.6.5

Note 1: Previously it was working fine with Instruments. But after this XCTest migration (I mean with the new appium versions) I am facing this issue

Note 2: @mykola-mokhnach - You've mentioned in one post that using "titleForRow" delegate may solve this issue. We are already using the same but no luck.

func pickerView(_ pickerView: UIPickerView, titleForRow row: Int, forComponent component: Int) -> String? {
        if let picData = pickerData {
            return picData[row]
        } else {
            return ""
        }
    }

Can you please suggest any other option if available?

**Comment by mykola-mokhnach** [comment]
You could try [mobile: selectPickerWheelValue](https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios-xctest-mobile-gestures.md) endpoint to workaround the problem (available in Appium 1.6.5). I don't know any other ways to solve it.

Closed as duplicate.
