### ISSUE TITLE
Creating iOS driver  object  is taking few min.

### ISSUE THREAD

**Issue by Siddh010** [appium/appium#8721]
## The problem

While creating IOSDriver instance  it take around 2-3   min.
   driver = new IOSDriver<>(new URL(sURL), iosNative());

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Last Appium version that did not exhibit the issue (if applicable):  Was able to reproduce in previous version also
* Desktop OS/version used to run Appium:OS X EI Caption
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS 10.0.2
* Real device or emulator/simulator: Real Phone
* Appium CLI or Appium.app|exe: Appium.app

## Details

While "Sending createSession command to WDA", it take few min.
  If I restart my device and Mac system , first time it will work fine but in next execution again I face same issue.

Code line while executing  :- 

   driver = new IOSDriver<>(new URL(sURL), iosNative());

Appium Server Log :- 

2017-06-23 11:04:28:532 - info: [debug] [XCUITest] Sending createSession command to WDA
2017-06-23 11:04:28:537 - info: [debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.empower-retirement.ios.Participant-Mobile","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}

  In Xcode log  below message is displayed :- 

:28.344 xcodebuild[22828:6188331] (LOG ARBITER) Rotating message buffer with 1 messages.
16:34:31.343 xcodebuild[22828:6188566] (LOG ARBITER) Rotating message buffer with 156 messages.
16:34:34.954 xcodebuild[22828:6189015] (LOG ARBITER) Rotating message buffer with 1 messages.
16:35:31.349 xcodebuild[22828:6189415] (LOG ARBITER) Rotating message buffer with 2 messages.
16:36:31.348 xcodebuild[22828:6189415] (LOG ARBITER) Rotating message buffer with 294 messages.
16:36:34.348 xcodebuild[22828:6189825] (LOG ARBITER) Rotating message buffer with 194 messages.
16:36:46.348 xcodebuild[22828:6189975] (LOG ARBITER) Rotating message buffer with 372 messages.
16:36:49.984 xcodebuild[22828:6189975] (LOG ARBITER) Rotating message buffer with 80 messages.

## Link to Appium logs
Session-WebDriverAgentRunner_Log
https://gist.github.com/Siddh010/f5a38f61479df2de72f3761274bc44d8

Appiam IOS Log 
https://gist.github.com/Siddh010/fabf7e4ebf95b673a69626bbb93b5cc3

Forum  :- 
 https://stackoverflow.com/questions/40983184/xcode-8-ui-testing-taking-very-long

## Code To Reproduce Issue [ Good To Have ]

   driver = new IOSDriver<>(new URL(sURL), iosNative());

**Comment by mykola-mokhnach** [comment]
Try to keep WDA running on the device like it is described in https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/wda-custom-server.md instead of redeploying it for each session restart.

**Comment by Siddh010** [comment]
Thank you MyKola, I shall look into this. 

Thanks
Siddartha

**Comment by mykola-mokhnach** [comment]
I've also added a patch to the recent Appium 1.6.6-beta, which tries to keep WDA running if _useNewWDA_ capability is set to false (the default setting). You could try it out.

**Comment by Siddh010** [comment]
Hi Mykola,
I tried  with appium 1.6.6 beta, WDA session is working as accepted but still it is taking time to get response  (around 2- 3 min) once app is lunch first time.

I have also notice that if I manually  try to go another page once app is lunch then I will not have  driver creation time issue.

Log details :-  

[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.empower-retirement.ios.Participant-Mobile","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}

****** Getting below  response it  is taking 2 -3 min from WDA****

[debug] [JSONWP Proxy] Got response with status 200: {"value":{"sessionId":"FA441C63-FCD6-41E9-9DFB-139431703F4D","capabilities":{"device":"iphone","browserName":"Empower","sdkVersion":"10.0.2","CFBundleIdentifier":"com.empower-retirement.ios.Participant-Mobile"}},"sessionId":"FA441C63-FCD6-41E9-9DFB-139431703F4D","status":0}

**Comment by mykola-mokhnach** [comment]
Please attach the full log

**Comment by mykola-mokhnach** [comment]
Also, don't expect too see the change immediately. You will need to reboot your device and restart the driver at least one time to see the difference in initialisation speed.

**Comment by Siddh010** [comment]
Solved After  setting capability waitForQuiescence = false

https://github.com/appium/appium/issues/8858
