### ISSUE TITLE
Unable to detect some elements on Android Nougat with Appium 1.6.5

### ISSUE THREAD

**Issue by xshuRoadie** [appium/appium#8722]
## The problem

I am seeing issues where Appium 1.6.5 cannot detect some UI elements on Android 7 and then hangs there forever. I have to manually kill a test to end it. However the same tests are running fine with a lower Android OS such as Lollipop: No issues are spotted with finding the same UI elements. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Last Appium version that did not exhibit the issue (if applicable):  
* Desktop OS/version used to run Appium: macOS Sierra
* Node.js version (unless using Appium.app|exe): 6.7.0
* Mobile platform/version under test:  Android 7.1.2
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI and Appium. app

## Link to Appium logs
https://gist.github.com/xshuRoadie/5c15a6a0bb63236403a8a16602fbbd89

**Comment by mykola-mokhnach** [comment]
Try uiatomator2 as automation backend

**Comment by xshuRoadie** [comment]
I just tried and a test failed before it reached the previous stopping point. Per the log it seems like uiautomator2 is not taking some commands such as finding the coordinates of a component. I am on the Python client which has not released for a while. Not sure if that is the reason. 
https://gist.github.com/xshuRoadie/03a28f6371d366c82b4bc8ae4a4eea09

**Comment by lehungcuong** [comment]
@xshuRoadie I face the same issue. Did you fix this issue?

**Comment by xshuRoadie** [comment]
@lehungcuong No. Unfortunately I have to run all the tests on lower Android versions such as Lollipop by specifying "automationName: appium" in desired capabilities. @mykola-mokhnach Any recommendations or update on the issue? Thanks.

**Comment by Steve-Liu** [comment]
.

**Comment by Steve-Liu** [comment]
.

**Comment by xshuRoadie** [comment]
@Steve-Liu Did you try to say something? :)

**Comment by Steve-Liu** [comment]
nah..marking it for update...lol

**Comment by jlipps** [comment]
@xshuRoadie why are you trying to find an element by content-desc inside xpath? The much better way is to find by accessibility id directly. It will be much more reliable. And yes, we are putting work moving forward into the uiautomator2 driver since uiautomator1 has not been updated in years.

**Comment by xshuRoadie** [comment]
@jlipps In some cases we have to use that attribute or others with a unique value to find an element. Yeah I wish all the code was done to well support test automation. I am glad that the work into uiautomator2 started and looking forward to having the problem resolved soon.

**Comment by sagarsheth27** [comment]
please help
