### ISSUE TITLE
In full screen mode, Appium doesn't return the full screen height on Androids that have a navigation bar

### ISSUE THREAD

**Issue by neXussT** [appium/appium#8724]
## The problem

In full screen mode, on a live Android that has a navigation bar, Appium reports the screen boundaries where the height does not include the height of the navigation bar. So, I can't tap or swipe in that location.

## Environment

I am testing a program on Android with Appium v1.6.5 with an LG K7 and Samsung Galaxy S6 Edge+, on Ubuntu Trusty Linux (Kernel 3.13.11) with Python v2.7.6.

## Details

I am performing swipe gestures in my test program at different areas across the width of the screen. On the Galaxy, I have no issues whatsoever. However, with the LG, which has a navigation bar, I get errors from Appium.

In my test application, the navigation bar is fully hidden - so full screen mode. When I read the screen size (appium_driver.get_window_size()), I get 480,782. This is not the full screen size. The height is minus the navigation bar. When I try to swipe the bottom of the screen, which is outside those bounds, Appium throws an error, and my try/except block fails. driver.swipe(1, 800, 479, 800). I know this is within the full screen size, but because it's outside what Appium thinks are the boundaries, it fails.

## Link to Appium logs

From Appium:
.....[debug] Display bounds: [0,0][480,782]
.....Sending command to android....action:swipe,params:startx:1, starty:800, endx:479, endy:800, steps:22
.....Returning result: status:13....x=1.0, y=800.0 is outside of element rect: [0,0][480,782]

I don't think the entire logs are needed, because Appium is functioning as designed. Let me know and I'll post the gist.

## Code To Reproduce Issue [ Good To Have ]
Just need any device that has a navigation bar, then use any program that has a full screen mode. I'm sorry, I can't post my company's program here for confidentiality reasons. 

Use the standard "appium_driver.get_window_size()" to read the screen in regular mode, and then again after you tell the program to go to full screen mode. I would expect the screen dimensions to be reported differently after moving into that mode, or just report the actual screen size including the navigation bar. But, currently this is not happening.

**Comment by neXussT** [comment]
This is still an issue for me. Can someone please take a look at the feasibility of fixing it, so I can have an estimate of when it can be completed?

**Comment by jlipps** [comment]
This is the UiAutomator method being called: https://developer.android.com/reference/android/support/test/uiautomator/UiDevice.html#getDisplayHeight() (along with `getDisplayWidth`). These are the values that Android sends back to us. As Appium, we don't know whether a device has a navigation bar or not. If the Android methods are returning incorrect values, there's not too much we can do about it. At this point I think the workaround is for testers of specific devices to build offsets into their tests when running on those specific devices, knowing that the UiAutomator implementation for those devices is incorrect. Or you could file a bug with LG so they know they need to fix something.

**Comment by neXussT** [comment]
@jlipps - Fair enough. We can't change the values read from Android, but an offset won't work at this point, because Appium returns an error when I tap out of the bounds it has set - even though they are wrong. Is there a way to ignore this warning? Could we build in a capability to allow the tap even if it fails?

**Comment by jlipps** [comment]
@neXussT i'm not sure. the out of bounds error is also returned from UiAutomator (not appium). it sounds like the issue is in certain Android implementers' version of UiAutomator. in this case it sounds like a bug on LG's side.

**Comment by neXussT** [comment]
Just to complete this thread, I have tested this on Nexus 6 and a Motorola Moto E, both of which have a virtual navigation bar. These two also exhibit this issue, so it's not limited to LG.

I found this, which when executed while the program is in full screen mode, returns the entire size of the usable screen:
driver.find_element_by_xpath("//*[not(*)]").size

However, because the appium swipe command returns an exception when out of bounds, I can't use it to perform the gesture.

My workaround, is to execute both xpath().size, and driver.get_window_size(). If there is a discrepancy , then I will use the later to swipe the screen with appium as far as possible, and then call "adb shell input touchscreen swipe" to complete the rest. 

Thanks for your help @jlipps.

**Comment by jlipps** [comment]
Thanks for the workaround report, @neXussT!

**Comment by develmi** [comment]
It seems like UiAutomator has a method for getting the exact device resolution without any decorations, can't you just use it instead of `getDisplay*`?

I'm talking about this one:
https://developer.android.com/reference/android/support/test/uiautomator/UiDevice#getDisplaySizeDp()
