### ISSUE TITLE
Android bootstrap logging level does not change when appium logging level is changed

### ISSUE THREAD

**Issue by jamesvanhorn** [appium/appium#8725]
## The problem
I start my server with the command `appium --session-override --log-level info` and it fires up as expected. 

When running my Android test, however, I still get flooded with lines such as `[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: find`

I checked the appium-bootsrap, appium-support, and npmlog repos, but didn't find a way to set the logging level manually. 

Even if I can set it by hand, it would be nice for the server log level to be pushed down to the android bootstrap automatically to keep things in line. 

## Environment
* Appium version (or git revision) that exhibits the issue: 1.6.5
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Mac Sierra
* Node.js version (unless using Appium.app|exe): 8.1.2
* Mobile platform/version under test: Android 5.0.1, 6, and 7.1.2
* Real device or emulator/simulator: Real devices
* Appium CLI or Appium.app|exe: CLI

**Comment by jamesvanhorn** [comment]
Also, if anyone knows a workaround to set the bootsrap logging level directly that would be great.

**Comment by jlipps** [comment]
Made a PR which should hopefully fix this: https://github.com/appium/appium-android-bootstrap/pull/47
