### ISSUE TITLE
Cannot push any apk to device

### ISSUE THREAD

**Issue by eduardoreynoso** [appium/appium#8726]
## The problem
This is the exception that I am getting:
`Encountered internal error running command: Error: Error executing adbExec. Original error: 'Command '/root/platform-tools/adb -P 5037 -s emulator-5554 install /usr/lib/node_modules/appium/node_modules/appium-unlock/bin/unlock_apk-debug.apk' timed out after 60000ms'; Stderr: ''; Code: 'null'`

I am using the docker image appium-emulator:
https://hub.docker.com/r/appium/appium-emulator/

Running that command inside the container actually works and next time I run tests it just skips this step but then I get more exceptions related to pushing apks into the device.
I do not believe this issue is with the docker image as I have another ubuntu 14 instance with the same problem.

## Environment
* Appium v1.6.5-beta
* Ubuntu 16.06 (Docker image appium/emulator)
* Android 7.0 on a Nexus 5 (default from the docker image)

## Logs:
https://gist.github.com/eduardoreynoso/471d5ad2377261ab04c854572663138e

Any help is appreciated, thank you!

**Comment by lehungcuong** [comment]
@eduardoreynoso I faced the same issue. Have any update?

**Comment by imurchie** [comment]
If you run the command manually does it succeed, but take longer than 60 seconds?

**Comment by eduardoreynoso** [comment]
@imurchie Takes less than 60 secs and succeeds, I have tried increasing the timeout in the appium-android-driver configuration and no luck.

**Comment by jlipps** [comment]
@eduardoreynoso if you run all of this outside the docker image, does it succeed? I'm just wondering if appium-emulator may be doing something odd, and I've never used it myself.

**Comment by SrinivasanTarget** [comment]
@eduardoreynoso  Docker image you have specified above is deprecated by us. We suggest to use [this](https://github.com/butomo1989/docker-android) for emulators and [this](https://github.com/appium/appium-docker-android) for real devices.
