### ISSUE TITLE
Element location works wrong for browser testing

### ISSUE THREAD

**Issue by kottenator** [appium/appium#8727]
## The problem

I'm testing my website on iPhone Simulator. I'm new to Appium so feel free to correct me, if I'm wrong ;)

Let's say I have a long vertical page with a small element in the middle. First I scroll browser view to the very bottom. Then I run:

```sh
curl localhost:4723/wd/hub/session/a6fcfd99-665a-471f-bea9-5e2aa9836882/element/5000/location
```

- it scrolls the element into view - *it's an unexpected behavior*, I don't want to interact with the page, I just want to know the element location;
- and then it returns `{"x": 0, "y": 0, ...}` - *it's wrong* because the element is in the middle of the page and _as I understand_ it's location should be relative to `(0, 0)` of the whole page, not the viewport.

BTW, are you going to replace `/element/{id}/location` with `/element/{id}/rect` in the future?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Last Appium version that did not exhibit the issue (if applicable): I don't know
* Desktop OS/version used to run Appium: macOS 10.12
* Node.js version (unless using Appium.app|exe): 8.1.2
* Mobile platform/version under test: iOS 10.3
* Real device or emulator/simulator: iPhone 7 Simulator (Xcode 8.3.3)
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs

[Gist](https://gist.github.com/anonymous/b4812177e5561226cbb6776cdf2d59fe).

## Code To Reproduce Issue

```sh
# Init session
curl localhost:4723/wd/hub/session -d '{"desiredCapabilities": {"platformName": "iOS", "platformVersion": "10.3", "browserName": "Safari", "automationName": "XCUITest", "deviceName": "iPhone 7"}}' -H "Content-Type: application/json" -X POST

# Load URL
curl localhost:4723/wd/hub/session/<your-session-id>/url -d '{"url": "https://www.w3.org/TR/webdriver"}' -H "Content-Type: application/json" -X POST

# Scroll to bottom
curl localhost:4723/wd/hub/session/<your-session-id>/execute -d '{"args":[],"script":"window.scrollTo(0,document.body.scrollHeight)"}' -H "Content-Type: application/json" -X POST

# Get an element in the middle
curl localhost:4723/wd/hub/session/<your-session-id>/element -d '{"using":"id","value":"get-element-rect"}' -H "Content-Type: application/json" -X POST

# Get the element location
curl localhost:4723/wd/hub/session/<your-session-id>/element/<element-id>/location
```

As you can see in the browser, the viewport was scrolled to the element and it's position: `{"y": 0, ...}`

**Comment by jlipps** [comment]
@kottenator the code that is executed on the Appium side when you request element location in a webview is (from appium-ios-driver/lib/commands/element.js):

```js
    let atomsElement = await this.useAtomsElement(el);
    return await this.executeAtom('get_top_left_coordinates', [atomsElement]);
```

Basically we're just running the `get_top_left_coordinates` atom. Sounds like that may not be working correctly. We can try and do an atoms update and rebuild soon to see if it could be fixed. You could also dump the current version of that atom into the appropriate file and see if it fixes things.

**Comment by kottenator** [comment]
@jlipps - I've never worked with atoms. But I assume it uses some kind of WebDriver protocol implementation. So eventually it may be a problem of the WebDriver implementation. But that's just my thoughts.

**Comment by jlipps** [comment]
OK. I ran your repro case and think I see the problem. It's just returning the location in view. we'd need to add the scrollTop/scrollLeft. I made a PR (https://github.com/appium/appium-xcuitest-driver/pull/486) that does this, which you can try out. You can also use executeScript (the same way this PR does) to get those values right now. I'm a bit concerned about landing the PR immediately since it would be a breaking change for current users.

**Comment by kottenator** [comment]
Thanks a lot! It's not urgent for me - it's up to you when to release it.
