### ISSUE TITLE
Appium - 1.6.5 - NoElementFoundException when switching from Native Context to Webview Context

### ISSUE THREAD

**Issue by siggerzz** [appium/appium#8728]
## The problem

I'm testing a Hybrid Android application, my app is primarily in a webview, however I need to switch into native view for one of my pages.

I'm able to successfully Switch from Webview > Native and click my Native elements, however when I switch back to webview again, I get a NoElementFoundException.

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): v6.11.0
* Mobile platform/version under test: Android - 7.0
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

Basic Flow flow of Test:

Dashboard Page (Webview)
Click Web Element
Upgrade Page (Native)
Switch to Native Context
Click Native Elements
Upgrade Complete Page (Webview)
Switch to Webview Context
Click Web Element (NoElementFoundException.

Even when setting breakpoints to wait for the Upgrade Complete page to load before setting webview context, I still get NoElementFound when clicking the web element on the Upgrade Complete page.

One thing I did notice is once on the Upgrade Complete page, Driver.Url is still equal to the Upgrade page URL. Not sure if this could be related.

## Link to Appium logs

https://pastebin.com/4Cbm4pWL

## Code To Reproduce Issue [ Good To Have ]
```

            var upgradeBtn = _dashboardPage.UpgradeNowBtn;
            var stripeBtn = _upgradeAndroidNativePage.AndroidStripeBtn;
            var enterCardTitleTxt = _upgradeAndroidNativePage.EnterYourCardTitleTxt;
            var cardNumberTxt = _upgradeAndroidNativePage.CardNumberTxt;
            var cardExpiryTxt = _upgradeAndroidNativePage.ExpiryDateTxt;
            var cardCvvTxt = _upgradeAndroidNativePage.CvvNumberTxt;
            var stripeModalDoneBtn = _upgradeAndroidNativePage.EnterCardNumberDoneBtn;
            var upgradeCompleteTitleTxt = _upgradeCompletePage.TitleTxt;
            var upgradeCompleteMessageTxt = _upgradeCompletePage.MessageTxt;
            var pickDomainBtn = _upgradeCompletePage.PickADomainBtn;

            wait.Until(ExpectedConditions.UrlContains("dashboard"));
            upgradeBtn.Click();
            wait.Until(ExpectedConditions.UrlContains("upgrade"));
            SetNativeAppContext(_driver);
            stripeBtn.Click();
            wait.Until(ExpectedConditions.ElementToBeClickable(cardNumberTxt));
            cardNumberTxt.SendKeys("4242424242424242");
            wait.Until(ExpectedConditions.ElementToBeClickable(cardExpiryTxt));
            cardExpiryTxt.SendKeys("0919");
            wait.Until(ExpectedConditions.ElementToBeClickable(cardCvvTxt));
            cardCvvTxt.SendKeys("123");
            wait.Until(ExpectedConditions.ElementToBeClickable(stripeModalDoneBtn));
            stripeModalDoneBtn.Click();
            WaitForPageLoad();
            SetWebviewContext(_driver);
            pickDomainBtn.Click();
```

**Comment by mykola-mokhnach** [comment]
Did you check the actual page source before to locate the element? Probably, there is no match for the given locator there.

**Comment by siggerzz** [comment]
@mykola-mokhnach It seems to be getting the page source of my previous page, even when debugging and setting a breakpoint.

**Comment by mykola-mokhnach** [comment]
what happens if _refresh_ is called? Does the page source stay the same?

**Comment by Naresh-Edla** [comment]
Hi,
 I faced the same problem while opening chrome browser. chrome browser is opened but automation is not working since  driver.contexts is returning on  list of available session 'NATIVE_APP' session.

**Comment by jlipps** [comment]
once you go back into a webview, you need to find your elements again. you can't use an old element since it's a completely different webdriver session under the hood.
