### ISSUE TITLE
Appium 1.6.5 - How to stop appium from clearing the Android local data?

### ISSUE THREAD

**Issue by Jennifer-traderev** [appium/appium#8729]
## The problem

I am getting this issue after upgrading my appium from 1.4.16 to 1.6.4 (and 1.6.5). It clears the Android local data. 
I was trying to use setCapability below but unable to stop Appium from clearing local data:                	
		cap.setCapability("no-reset", "true");
                cap.setCapability("dontStopAppOnReset", true);	

## Environment

* Appium Version: 1.6.4 and 1.6.5
* Last Appium version that did not exhibit the issue (if applicable): 1.4.16
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): v6.10.3
* Mobile platform/version under test: Android -  5.0.2 / 6.0.1 / 7.1.2 
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Code To Reproduce Issue [ Good To Have ]
private void setupCapabilities(String deviceid, String version, String appApk) throws MalformedURLException {
		cap = new DesiredCapabilities();
		cap.setCapability(CapabilityType.BROWSER_NAME, "Android");
		cap.setCapability("deviceName", deviceid);
		cap.setCapability("platformName", "Android");
		cap.setCapability(CapabilityType.VERSION, version);
		cap.setCapability("appPackage", appApk);
		cap.setCapability("appActivity", "com.mycompany.android.ui.activities.SplashActivity");
		cap.setCapability("--session-override", true);
		cap.setCapability("unicodeKeyboard", true);
		cap.setCapability("resetKeyboard", true);
		cap.setCapability("dontStopAppOnReset", true);
		cap.setCapability("newCommandTimeout", 300);		
		cap.setCapability("no-reset", "true");
		cap.setCapability("full-reset", "false");
		cap.setCapability("automationName", "uiautomator2");

**Comment by mykola-mokhnach** [comment]
correct capability name is **noReset**

**Comment by Jennifer-traderev** [comment]
Thanks a lot @mykola-mokhnach . It works good by using:
cap.setCapability("noReset", "true");
