### ISSUE TITLE
Appium 1.6.5 Real IOS: Getting stuck on "Could not launch WebdriverAgentRunner" process launch failed:timed out waiting for app to launch

### ISSUE THREAD

**Issue by anu009** [appium/appium#8731]
@imurchie 
When i try running a test through appium 1.6.5 i get below error:
**[debug] [XCUITest] Unable to start WebDriverAgent session: Could not proxy command to remote server. Original error: Error: socket hang up**
I opened webdriveragent in xcode, provisioning profiles are set correct but when i selected webdriveragentrunner and tried to test (cmd+u) then i see the  below error:
**"Could not launch WebdriverAgentRunner" process launch failed:timed out waiting for app to launch**
Xcode: 8.3.3
Appium: 1.6.5
appium-xcuitest-driver: 2.30.0
IOS Real Device- IPhone 6S
It would be a great if you could help me with issue.
Please find the below link for logs
https://gist.github.com/anu009/9baecbb000df4bff7a08bcc02bf842cc

**Comment by mykola-mokhnach** [comment]
> [XCUITest] Error: Could not remove app: 'Command 'ios-deploy --uninstall_only --id xxxxxxxxxx --bundle_id com.apple.test.WebDriverAgentRunner-Runner' exited with code 253'

There is a problem with _ios-deploy_ failing to uninstall web driver app from the device. Try to execute the above command manually with verbose output enabled and/or consult their project issue tracker: https://github.com/phonegap/ios-deploy/issues

**Comment by imurchie** [comment]
I think that is after the fact...

@anu009 Can you try to either turn on xcode logging (set the `showXcodeLog` desired capability to `true`) or manually run the command:
```
cd /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent

xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=xxxxxxxxxx -configuration Debug -xcconfig /var/folders/xw/tgz602g902z_qhb0ln_fd_fw0000gn/T/2017525-2119-ouy7dm.6d1p7/appium-temp.xcconfig
```

**Comment by imurchie** [comment]
Also, just noticed the post-facto xcode build log file. App start timed out:
```
18:16:36.021 Xcode[476:6088] _finishWithError:Error Domain=IDEDebugSessionErrorDomain Code=3 "Could not launch “WebDriverAgentRunner”" UserInfo={NSLocalizedDescription=Could not launch “WebDriverAgentRunner”, NSLocalizedFailureReason=process launch failed: timed out waiting for app to launch} didCancel: 1
```

Can you manually uninstall any WebDriverAgentRunner app on the device? Also remove any build artifacts, just to make sure (`rm -rf ~/Library/Developer/Xcode/DerivedData/WebDriverAgent-*`)

**Comment by anu009** [comment]
@mykola-mokhnach 
I tried executing the following command
"ios-deploy --uninstall_only --id xxxxxxxxxx --bundle_id com.apple.test.WebDriverAgentRunner-Runner" command
WebdriveragentRunner app uninstalled successfully.

**Comment by anu009** [comment]
@imurchie 
I tried executing the following command manually:
xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=xxxxxxxxxx -configuration Debug -xcconfig /var/folders/xw/tgz602g902z_qhb0ln_fd_fw0000gn/T/2017525-2119-ouy7dm.6d1p7/appium-temp.xcconfig.
Please find the attached log
[webdriveragentrunner_logs.docx](https://github.com/appium/appium/files/1103189/webdriveragentrunner_logs.docx)

**Comment by anu009** [comment]
@imurchie 
Uninstalled webdriveragentrunner app from the device and executed the following command:
rm -rf ~/Library/Developer/Xcode/DerivedData/WebDriverAgent-*
But could not launch webdriveragentrunner app on device.

**Comment by imurchie** [comment]
@anu009 I cannot open a Word file. Please attach a link to a [gist](https://gist.github.com).

**Comment by anu009** [comment]
@imurchie 
Please find the below link  for logs
https://gist.github.com/anu009/35e3b40eccb17484001e9323db55dddf

**Comment by imurchie** [comment]
Your signing identity is not working. See https://github.com/appium/appium/blob/master/docs/en/appium-setup/real-devices-ios.md

**Comment by anu009** [comment]
@imurchie 
I followed the link you provided and when I run below command manually build was successful.
**xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=xxxxxxxxxx -configuration Debug -xcconfig /var/folders/xw/tgz602g902z_qhb0ln_fd_fw0000gn/T/2017525-2119-ouy7dm.6d1p7/appium-temp.xcconfig.**
When i try running a test through appium 1.6.5, **webdriveragent** is not installed in device but  still i get below error:
[debug] [XCUITest] Unable to start WebDriverAgent session: Could not proxy command to remote server. Original error: Error: socket hang up 

Please find the below link for logs:
https://gist.github.com/anu009/fbddd6074594fab40d88e24daa0dbfd7

**Comment by jlipps** [comment]
@imurchie notice this in the logs:

```
[debug] [XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=xxxxxxxxxx-configuration Debug -xcconfig /var/folders/xw/tgz602g902z_qhb0ln_fd_fw0000gn/T/2017527-2196-1rt17a1.bnco/appium-temp.xcconfig' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[debug] [XCUITest] Output from xcodebuild will be logged
[debug] [XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[Xcode] Build settings from configuration file '/var/folders/xw/tgz602g902z_qhb0ln_fd_fw0000gn/T/2017527-2196-1rt17a1.bnco/appium-temp.xcconfig':
[Xcode] 
[debug] [XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[Xcode]     CODE_SIGN_IDENTITY = iPhone Developer
[Xcode]     DEVELOPMENT_TEAM = xxxx
[Xcode] 
[Xcode] 
```

it looks like there may be an async bug or race condition; the build configuration file contents are printed out after several other logs. could this be related?

**Comment by imurchie** [comment]
I don't think so. This is just the interleaving of the command output. The way we "Wait up to XXXms for WebDriverAgent to start" is to poll `/status` on the device. At the same time, `xcodebuild` is running, and the normal output on a real device test is something like:
```
$ xcodebuild build-for-testing test-without-building -project /Users/isaac/code/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=a77841db006fb1762fee0bb6a2477b2b3e1cfa7f IPHONEOS_DEPLOYMENT_TARGET=10.3 -xcconfig /Users/isaac/teamconfig.xcconfig
Build settings from command line:
    IPHONEOS_DEPLOYMENT_TARGET = 10.3

Build settings from configuration file '/Users/isaac/teamconfig.xcconfig':
    CODE_SIGN_IDENTITY = iPhone Developer
    DEVELOPMENT_TEAM = CQGM24D4PH

=== BUILD TARGET WebDriverAgentLib OF PROJECT WebDriverAgent WITH CONFIGURATION Debug ===

Check dependencies

Write auxiliary files
.....
```

We could wait a while before starting the polling, but how long to wait? Different systems can be drastically different, and even more so if it is already built and just needs to be run.

**Comment by jlipps** [comment]
OK, I'm out of ideas then. @imurchie let me know if you see anything else untoward in the logs otherwise we should probably close this.
