### ISSUE TITLE
[uiautomator1.0] kill the uiautomator process failed when run driver.quit()

### ISSUE THREAD

**Issue by Carlgege** [appium/appium#8732]
## The problem
When test case completed, appium will kill uiautomator process, but the phone has no permission to run the kill command.
So could you help to check the process is exist or not ? If it still in on running, send one message to the server and the server will do system.exit(1).

## Environment
* Appium 1.6.3

**Comment by mykola-mokhnach** [comment]
1. Please try the most recent Appium 1.6.6-beta
2. Attach full Appium log if it still does not work in 1.6.6
