### ISSUE TITLE
[XCUITest] Cannot launch an Enterprise build

### ISSUE THREAD

**Issue by luisromanwp** [appium/appium#8733]
## The problem

Hi! I have a problem trying to launch tests with an enterprise build, we have an enterprise build for dev purposes and an adhoc build for release version, I can launch the tests with the release build putting the Signing Code for it, but when I try to launch the Enterprise build with its Signing Code it launches the WebDriverAgentRunner but it doesn't launch the app, there's something different I have to do when a build is signed with an Enterprise In-house firm?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.6 BETA
* Desktop OS/version used to run Appium: macOS Sierra
* Mobile platform/version under test: iPhone 6s 10.1
* Real device or emulator/simulator: Real device

## Link to Appium logs

Code where Appium stops
https://gist.github.com/luisromanwp/3849fab78ca32bfb9017045a1e02d97e

**Comment by mykola-mokhnach** [comment]
Enterprise build won't work. Only debug configuration is supported.

**Comment by luisromanwp** [comment]
Thanks for the info! :)
