### ISSUE TITLE
Appium is unable to execute Javascript on IOS Simulator if pages changes.

### ISSUE THREAD

**Issue by NarayanaBojja** [appium/appium#8735]
## The problem
Appium is unable to execute Javascript on IOS Simulator if pages changes.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Desktop OS/version used to run Appium: MacBook Pro 10 
* Node.js version (unless using Appium.app|exe): 7.4.0
* Mobile platform/version under test: IOS 10.1
* Real device or emulator/simulator: simulator ( Iphone 6 ) 10.1
* Appium CLI or Appium.app|exe: Appium CLI 

## Details

I am trying to record user actions by injecting javascript code into a mobile web page in simulator.
I am able to record user actions in a first page . If page changes , js files are injecting but user actions are not recording. Below are the steps that I follow  .

1. Open the url using " driver.get(url); "
2. Once url is launched , inject three js files that will record user actions. 
3. These js files will inject successfully,  record user actions.
4. Click any hyperlink in the page , page changes . Js files will inject in the new page (I confirmed by reading appium logs).  But those js files are not being  executing.
I tried to put alert statements in js files to confirm whether they are working or not. Js files are not executing if page changes. If there is mistake in the Js file or Java code , it shouldn't work for first page also. But it is working for first page. If page changes, Js files are injecting into new page. But they are not  executing. So I thought problem with appium. 

## Link to Appium logs

https://gist.github.com/NarayanaBojja/7c9e6fa77885baf33307acdb854e5f81

## Code To Reproduce Issue [ Good To Have ]

             DesiredCapabilities capabilities = new DesiredCapabilities();
			capabilities.setCapability(CapabilityType.BROWSER_NAME, browserName); 
			capabilities.setCapability("deviceName", deviceName);
			capabilities.setCapability("platformVersion", platformVersion);
			capabilities.setCapability("platformName", "IOS");
			capabilities.setCapability("enableAsyncExecuteFromHttps", true);
			capabilities.setCapability("udid", udid);
			capabilities.setCapability("newCommandTimeout", 999999);
               public boolean checkPageReady() {
		boolean pageReady = false;
		if (((JavascriptExecutor) driver).executeScript(
				"return document.readyState").equals("complete")) {
			pageReady = true;
		} else {
			checkPageReady();
		}

		return pageReady;
	}
	@SuppressWarnings("deprecation")
	public String[] recordElements() {

		LOG.info("Injecting JS files start");

		String[] elementsDataArray = new String[5];
	
		js = (JavascriptExecutor) driver;

		try {
			jqueryFileContents = Files.toString(new File(JQUERY_LOAD_SCRIPT),
					Charsets.UTF_8);
			

			domContents = Files.toString(new File(DOM_SCRIPT), Charsets.UTF_8);

			collectScriptContents = Files.toString(new File(COLLECT_SCRIPT),
					Charsets.UTF_8);
		
			if (isPageReady()) {
				js.executeScript(jqueryFileContents);
				
				js.executeScript(domContents);
				
				LOG.info("Injecting JS files end");
				elementsDataArray = getSingleElementData();
			} else {
				recordElements();
			}

		} catch (Exception e) {
			LOG.error("Failed in loading js files: ", e);

		}

		return elementsDataArray;
	}

	/**
	 * This method returns a single element action data
	 * 
	 * @return String[]
	 */
	public String[] getSingleElementData() {
		LOG.info("recording user action start");
		String[] elementsDataArray = new String[5];
		int number = 1;
		while (number < 2) {

			try {
				number++;

				driver.manage().timeouts().setScriptTimeout(1, TimeUnit.HOURS);

				Object qv2data = js.executeAsyncScript(collectScriptContents);
		
				if (qv2data != null) {
			
					String[] elementDataArray = qv2data.toString().split("#qv2#");

                     Thread.sleep(20000);
                     checkPageReady();
					js.executeScript(jqueryFileContents);
					
					js.executeScript(domContents);
				  
					elementsDataArray = processElementArray(elementDataArray);
				}

				LOG.info("recording user action end");
			} catch (Exception ex) {
				LOG.error("Failed in getting element action data: ", ex);

			}

		}
		return elementsDataArray;
	}

I am  unable to attach Javascript files. Below are links to the files. 
https://gist.github.com/NarayanaBojja/84f40ae3a5624958117cd50f3d5404e6

https://gist.github.com/NarayanaBojja/a7d1a06f2c6014f595d719d2feda467e

If you some one can figure out , Please help me.

**Comment by jlipps** [comment]
The difference between the first round of injection and the second round of injection is that in the first round, the async_execute completes successfully and talks back to the Appium server. in the second case, it does not. To know exactly what could be going wrong we'd need to see your whole client script, not just the parts you linked here. Looking at the contents of the async script, my guess is that this condition:

```js
if(qv2RecordedData!=="" && qv2RecordedData!==undefined && qv2RecordedData!==null){
```

is not satisfied on the second page. Did you try adding alerts to this recursive function so you can see what it's doing?

**Comment by NarayanaBojja** [comment]
There are no other scripts . I have only two scripts which I have linked here. By the way , we have stopped working on this project. Issue doesn't get resolved. If you want , you can close this issue.

**Comment by jlipps** [comment]
OK, thank you @NarayanaBojja
