### ISSUE TITLE
the height of scolling up is to small(appium)

### ISSUE THREAD

**Issue by yefankongge** [appium/appium#8736]
## The problem

the height I want to scroll up for many，but whaterver I set the startY and endY，it scrolls up i little

## Environment

* Appium version：1.6.5
* java-client:5.0.0-BETA8
* mac os:10.12
* simulator:iphone6s 10.3

## Details

the height I want to scroll up for many，but whaterver  I set the startY和endY，it scrolls up i little

## Link to Appium logs

[HTTP] --> POST /wd/hub/session/68325fd4-df90-4e12-8f05-104086dbcb58/touch/perform {"actions":[{"action":"press","options":{"x":100,"y":600}},{"action":"wait","options":{"ms":1000}},{"action":"moveTo","options":{"x":0,"y":600}},{"action":"release","options":{}}]}
[debug] [MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"x":100,"y":600}},{"action":"wait","options":{"ms":1000}},{"action":"moveTo","options":{"x":0,"y":600}},{"action":"release","options":{}}],"68325fd4-df90-4e12-8f05-104086dbcb58"]
[debug] [XCUITest] Executing command 'performTouch'
[debug] [XCUITest] Received the following touch action: press(options={"x":100,"y":600})-wait(options={"ms":1000})-moveTo(options={"x":0,"y":600})-release(options={})
[debug] [XCUITest] Found matching gesture: drag
[debug] [JSONWP Proxy] Proxying [POST /wda/dragfromtoforduration] to [POST http://localhost:8100/session/61B42D83-453F-44A7-97D2-89D0D049D149/wda/dragfromtoforduration] with body: {"fromX":100,"fromY":600,"toX":100,"toY":1200,"duration":1}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"61B42D83-453F-44A7-97D2-89D0D049D149","status":0}

## Code To Reproduce Issue [ Good To Have ]

@Test
    public void testBuyBuy() throws  InterruptedException {
        Thread.sleep(3000);
        driver.findElementByName("买买买").click();
        Thread.sleep(3000);
        for(int i = 0; i < 10; i++){
            int startX = 100;
            int startY = 600;
            int endX = 0;
            int endY = 600;
            IOSTouchAction iosTouchAction = new IOSTouchAction(driver);
            iosTouchAction.press(startX,startY).waitAction(1000).moveTo(endX,endY).release().perform();
        }

**Comment by mykola-mokhnach** [comment]
all the further coordinates in the chain are relative to the start coordinates, but not absolute. For your case endX = 100 + 0 and endY = 600 + 600:
> [debug] [JSONWP Proxy] Proxying [POST /wda/dragfromtoforduration] to [POST http://localhost:8100/session/61B42D83-453F-44A7-97D2-89D0D049D149/wda/dragfromtoforduration] with body: {"fromX":100,"fromY":600,"toX":100,"toY":1200,"duration":1}

**Comment by mykola-mokhnach** [comment]
Closed as not an issue

**Comment by yefankongge** [comment]
int startX = driver.manage().window().getSize().width;
 int startY = driver.manage().window().getSize().height;
 return scroll(startX/2, startY/2, 0, startY, driver);
code for this is ok,scoll up for half screen.
