### ISSUE TITLE
How to click Search key on the keyboard of an ios device to automate a webapp using selenium?

### ISSUE THREAD

**Issue by aakashRepo** [appium/appium#8737]
Application Type: Web App

Device: IOS(iPAD)

Browser: Safari

I am trying to search a incident in the search box but the only option I can do it is by clicking the 'Search' key on the keyboard after entering incident id. I am able to enter the incident id using sendkeys() but not getting how to click the 'Search' key on the keyboard.

I have tried the below things for this:

1.  SEARCHBOX.sendKeys(Keys.chord(Keys.ENTER));

2.  SEARCHBOX.sendKeys(Keys.chord(Keys.RETURN));

3.  SEARCHBOX.sendKeys("\n");

4.  SEARCHBOX.sendKeys(Keys.ENTER);

5.  Robot r = new Robot();
    r.keyPress(KeyEvent.VK_ENTER);
but non of them worked.

**Comment by mykola-mokhnach** [comment]
The key itself is just a UI element, which can be located and clocked.
However it might not work as expected in landscape mode due to known XCTest bugs.

Closed as non-issue

**Comment by aakashRepo** [comment]
@mykola-mokhnach what's the way to locate the soft key while we are working on a webapp?

**Comment by mykola-mokhnach** [comment]
Switch to native context?
