### ISSUE TITLE
TouchAction seems to translate the coordinates incorrectly (Coordinate [x, y] is outside of element rect)

### ISSUE THREAD

**Issue by vanangelov** [appium/appium#8738]
## The problem

I am trying to simulate a pull-to-refresh gesture (basically a vertical swipe from the middle of the screen at the top 1/4  to the bottom 1/4 of the screen).

Here is my code:

        Dimension screenSize = driver.manage().window().getSize();
        int width = (int) (screenSize.width / 2);
        (new TouchAction(driver)).press(width, (int)(screenSize.height*0.25))
                .waitAction(Duration.ofMillis(2000))
                .moveTo(width, (int)(screenSize.height*0.75))
                .waitAction(Duration.ofMillis(300))
                .release().perform();

When I execute the code above I am getting the following output from the server. It seems it is trying to move to a coordinate outside the screen, although based on the java code it does not look like that.

```
[HTTP] --> POST /wd/hub/session/07fa6b88-21d2-4a94-ad44-c974be06f795/touch/perform {"actions":[{"action":"press","options":{"x":540,"y":448}},{"action":"wait","options":{"ms":2000}},{"action":"moveTo","options":{"x":540,"y":1345}},{"action":"wait","options":{"ms":300}},{"action":"release","options":{}}]}
[MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"x":540,"y":448}},{"action":"wait","options":{"ms":2000}},{"action":"moveTo","options":{"x":540,"y":1345}},{"action":"wait","options":{"ms":300}},{"action":"release","options":{}}],"07fa6b88-21d2-4a94-ad44-c974be06f795"]
[AndroidBootstrap] Sending command to android: {"cmd":"action","action":"element:touchDown","params":{"x":540,"y":448}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:touchDown","params":{"x":540,"y":448}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: touchDown
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Display bounds: [0,0][1080,1794]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Performing TouchDown using element? false x: 540, y: 448
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":true}
[AndroidBootstrap] Received command result from bootstrap
[AndroidBootstrap] Sending command to android: {"cmd":"action","action":"element:touchMove","params":{"x":1080,"y":1793}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:touchMove","params":{"x":1080,"y":1793}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: touchMove
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Display bounds: [0,0][1080,1794]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":29,"value":"Coordinate [x=1080.0, y=1793.0] is outside of element rect: [0,0][1080,1794]"}
```

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS
* Node.js version (unless using Appium.app|exe): Appium Desktop
* Mobile platform/version under test: Android 
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: Appium Desktop

## Link to Appium logs

https://gist.github.com/vanangelov/f8fef88f169f0d9936bdc180862650cc

**Comment by mykola-mokhnach** [comment]
It works as designed. You have just remember, that all the further coordinates in actions chain are relative to the very first coordinate point, rather than absolute.

**Comment by vanangelov** [comment]
I see - Maybe the method name in Java will make more sense if it was just move(), not moveTo()
Somehow I think To implies that it needs the target coordinates that you want to go to.
