### ISSUE TITLE
pass  incorrect args while response for touchDown/touchMove/touchUp

### ISSUE THREAD

**Issue by gogoyqj** [appium/appium#8739]
## The problem

receive:
```
[HTTP] --> POST /wd/hub/session/7d2d2ac6-573e-423b-87a6-79b3c0189c3c/touch/move {"x":0,"y":249}
```

=> call:appium-base-driver/build/lib/mjsonwp/njsonwp.js:
```
function buildHandler
...
args = makeArgs(req.params, jsonObj, spec.payloadParams || []);
```
formats args: 
```
[0,249,"7d2d2ac6-573e-423b-87a6-79b3c0189c3c"]
```

=> call: appium-android-driver/build/lib/commands/element.js:
```
commands.touchMove = function callee$0$0(elementId, x, y)
```
expected: `elementId, x, y`, actually received: `x, y, sessionId`

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS Sierra 10.12.5
* Mobile platform/version under test: android 5.1
* Real device or emulator/simulator: android emulator Nexus 5X API 22-2
* Appium CLI or Appium.app|exe:1.1.0-beta.2 (1.1.0-beta.2)

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

```
[HTTP] --> POST /wd/hub/session/7d2d2ac6-573e-423b-87a6-79b3c0189c3c/touch/move {"x":0,"y":249}
[MJSONWP] Calling AppiumDriver.touchMove() with args: [0,249,"7d2d2ac6-573e-423b-87a6-79b3c0189c3c"]
[AndroidBootstrap] Sending command to android: {"cmd":"action","action":"element:touchMove","params":{"elementId":0,"x":249,"y":"7d2d2ac6-573e-423b-87a6-79b3c0189c3c"}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:touchMove","params":{"elementId":0,"x":249,"y":"7d2d2ac6-573e-423b-87a6-79b3c0189c3c"}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: touchMove
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":13,"value":"Invalid double: \"7d2d2ac6-573e-423b-87a6-79b3c0189c3c\""}
```

**Comment by mykola-mokhnach** [comment]
Can you please show the client code, which generates such request? It looks like the requests expects elementId to be present in the body, but it is missing.

**Comment by gogoyqj** [comment]
i'm using webdriverio with its browser.touchDown(null, x, y)/touchMove/touchUp(null, x, y) api, it generated these requests below:

```
[HTTP] --> POST /wd/hub/session/3d7a8a19-5ece-418d-8475-2c3ef5b1ebb2/touch/down {"x":0,"y":88}
[HTTP] --> POST /wd/hub/session/3d7a8a19-5ece-418d-8475-2c3ef5b1ebb2/touch/move {"x":0,"y":88}
[HTTP] --> POST /wd/hub/session/3d7a8a19-5ece-418d-8475-2c3ef5b1ebb2/touch/up {"x":0,"y":88}
```

**Comment by mykola-mokhnach** [comment]
what if you replace the first argument with, say _'dummy'_ instead of _null_?

**Comment by gogoyqj** [comment]
sorry, i made a mistake... its api is: browser.touchDown(x, y)/touchMove(x, y)/touchUp(x, y).

**Comment by mykola-mokhnach** [comment]
this endpoint is marked as deprecated there. Can you try http://webdriver.io/api/mobile/touchPerform.html instead? And also try to  provide a value to element argument if it still does not work.

**Comment by gogoyqj** [comment]
i'll try it and thank u

**Comment by gogoyqj** [comment]
well, it didn't work:
```
[16:18:37]  COMMAND     GET      "/wd/hub/session/41a2614e-4409-4325-8254-f84fd236cf81/contexts"
[16:18:37]  DATA                {}
[16:18:37]  RESULT              ["NATIVE_APP","CHROMIUM"]
[16:18:37]  COMMAND     POST     "/wd/hub/session/41a2614e-4409-4325-8254-f84fd236cf81/touch/perform"
[16:18:37]  DATA                {"actions":[{"action":"press","options":{"x":20,"y":600}}]}
err { Error: An unknown server-side error occurred while processing the command.
    at touchPerform([object Object]) - a.js:99:14
  message: 'Method has not yet been implemented',
  type: 'RuntimeError',
  seleniumStack:
   { status: 13,
     type: 'UnknownError',
     message: 'An unknown server-side error occurred while processing the command.',
     orgStatusMessage: 'Method has not yet been implemented' } }
```
since i'm using appium to drive android chrome, actually seems that appium drives chrome with chromedriver which hasn't implemented `/touch/perform` protocal but implemented `/touch/move {"x":0,"y":249}` which didn't work with appium

```
    // Using appium
    port: 4723,
    desiredCapabilities: { // android chrome
        browserName: 'chrome',
        platformName: "Android",
        deviceName: "emulator-5554",
        platformVersion: "5.1"
    },
```
but `/touch/move {"x":0,"y":249}` works with selenium standalone:
```js
    // Using selenium standalone:
    port: 4444,
    desiredCapabilities: { // android mobile
        browserName: 'chrome',
        platformName: "Android",
        platformVersion: "5.1",
        deviceName: "emulator-5554",
        chromeOptions: {
            androidPackage: 'com.android.chrome'
        }
    },
```

**Comment by mykola-mokhnach** [comment]
You could switch to native context, perform the gesture and then switch back. Would it be possible?

**Comment by gogoyqj** [comment]
it finally works and seems the most compatible way for touch action

**Comment by mykola-mokhnach** [comment]
Good, we will most likely remove the deprecated endpoints from the driver completely.
