### ISSUE TITLE
Date picker blocks consequent actions

### ISSUE THREAD

**Issue by lanzelot1989** [appium/appium#8740]
## The problem
![date-picker](https://user-images.githubusercontent.com/773651/27582977-2b6fbd26-5b33-11e7-88b1-48694f6e7991.png)

After closing a date picker, Appium blocks further actions and answers with "Cannot find element" exceptions. 
When changing the view with Driver.Tap on the position of a back button everything works again.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5 (also tried with 1.6.6-beta2)
* Desktop OS/version used to run Appium: Win 10
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs

* see [GIST](https://gist.github.com/lanzelot1989/44e5268868e338ae773d2c011b6d0ed8)

## Code To Reproduce Issue
using appium-dotnet-driver
```
            Picker.Tap();
            var dateToPick = DateTime.Now.AddYears(-18);
            Driver.FindElementByAccessibilityId(dateToPick.ToString("dd MMMM yyyy")).Click();
            Driver.FindElementById("android:id/button1").Click(); //// OK button
            //// consequent actions cannot be performed
```

**Comment by mykola-mokhnach** [comment]
Try to print the page source after the picker is closed to see what is really visible on the page for the driver.

**Comment by lanzelot1989** [comment]
Hi, Driver.PageSource is one of the commands that is blocked and times out after the configured 40 seconds with a WebDriverException.

**Comment by lanzelot1989** [comment]
My current workaround is to change views by tapping the position of a back button Driver.Tap(1, x, y, 100) which solves the blocking.

**Comment by mykola-mokhnach** [comment]
Check the device logcat output - probably there are some interesting records there. 

You may also try put a breakpoint after click and get the snapshot of UI manually using adb

```
adb shell
uiautomator dump /sdcard/ui.xml
exit
adb pull /sdcard/ui.xml
```

**Comment by lanzelot1989** [comment]
Logcat blurts out lots of these messages
```
06-27 10:37:57.679 16282 16294 E QueryController: Got null root node from accessibility - Retrying...
06-27 10:37:57.930 16282 16294 E QueryController: Got null root node from accessibility - Retrying...
06-27 10:37:58.181 16282 16294 E QueryController: Got null root node from accessibility - Retrying...
06-27 10:37:58.433 16282 16294 E QueryController: Cannot proceed when root node is null. Aborted search
06-27 10:37:58.433 16282 16282 W art     : Long monitor contention with owner WatchTimer (16294) at android.view.accessibility.AccessibilityNodeInfo com.android.uiautomator.core.QueryController.findAccessibilityNodeInfo(com.android.uiautomator.core.UiSelector, boolean)(QueryController.java:149) waiters=0 in android.view.accessibility.AccessibilityNodeInfo com.android.uiautomator.core.QueryController.findAccessibilityNodeInfo(com.android.uiautomator.core.UiSelector, boolean) for 754ms
```

uiautomator did not seem to work during a running Appium test.

**Comment by mykola-mokhnach** [comment]
I assume this is [one](https://groups.google.com/forum/#!topic/appium-discuss/BdYYQMlsnXo) of these UIA issues, that are never going to be fixed (because only Google can fix them). You could try UIAutomator2 as the automation backend.
Also, we are currently working on espresso driver implementation for Appium

**Comment by lanzelot1989** [comment]
It seems that this would need some code rewriting to get to the point where the date picker occurs, I may get back to you at a later time, thanks for the help!

**Comment by peterwest83** [comment]
@lanzelot1989, Thanks for the workaround solved my problem.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
