### ISSUE TITLE
[XCUITest] Error: Could not initialize ios-deploy make sure it is installed (npm install -g ios-deploy) and works on your system.

### ISSUE THREAD

**Issue by rgupta7888** [appium/appium#8741]
## The problem

When I run appium server programmatically with the below code I am getting error "[XCUITest] Error: Could not initialize ios-deploy make sure it is installed (npm install -g ios-deploy) and works on your system" . Please find below code :
AppiumDriverLocalService service;
service = AppiumDriverLocalService.buildService(new AppiumServiceBuilder().withIPAddress("127.0.0.1").usingPort(port).usingDriverExecutable(new File("/usr/local/bin/node")).withAppiumJS(new File("/usr/local/lib/node_modules/appium/build/lib/main.js")).withLogFile(new File("/Users/cex/Downloads/iOS/iOSAutomationHybridFramework/src/com/cexwebuy/logs/Application.log")));
		if(device.trim().contains(deviceData[0])){//437593bb0b56b28071b0b8287b2c6844f680178c
	capabilities.setCapability(CapabilityType.VERSION, CONFIG.getProperty("version"));
	capabilities.setCapability(CapabilityType.PLATFORM, CONFIG.getProperty("platform"));
	capabilities.setCapability("deviceName", CONFIG.getProperty("Device"));
	capabilities.setCapability("udid", CONFIG.getProperty("UDID"));// 6 plus
	capabilities.setCapability("bundleId", CONFIG.getProperty("bundleID"));//""com.cex.ecomiosapp""//com.cex.cexdevinternal//com.cex.ecomapp
	//capabilities.setCapability("bundleId", "com.cex.ecomiosapp");
	capabilities.setCapability("automationName", CONFIG.getProperty("automationName"));
	capabilities.setCapability("ipa", CONFIG.getProperty("appName"));
	capabilities.setCapability("NoReset", CONFIG.getProperty("noResetVal"));
//capabilities.setCapability("realDeviceLogger",CONFIG.getProperty("deviceLog"));
	capabilities.setCapability("session-override", CONFIG.getProperty("sessionOvrdVal"));
	//capabilities.setCapability("useNewWDA", true);
	capabilities.setCapability("wdaLocalPort", CONFIG.getProperty("devicePort"));
	capabilities.setCapability("clearSystemFiles", true);
	capabilities.setCapability("newCommandTimeout",CONFIG.getProperty("commandTimeOut"));
	driver = new IOSDriver<MobileElement>(service, capabilities);}

Passing the actual values from config.properties file. When I run the script on the real device through running appium server manually then the script runs but at the time of running appium through above script getting the error that is mentioned in the title of the issue.

I installed ios-deploy and set the path as well in eclipse and with sudo nano /etc/path. Please help

**Comment by mykola-mokhnach** [comment]
Where is ios-deploy binary located. Is this path present in PATH environment variable passed to Appium daemon? 
One may use `ps eww <PID>` terminal command in Mac OS to see the actual environment of a precess with the particular id.

**Comment by rgupta7888** [comment]
@mykola-mokhnach 
i set the path ios-deploy as /usr/local/bin/ios-deploy under eclipse under run configuration and same set under PATH.

I am not getting what you asked to check ps eww <PID> with that . Please help me.

**Comment by mykola-mokhnach** [comment]
It might be that AppiumDriverLocalService does not pick up the variable you set in Eclipse. Try to set it explicitly in the service builder (use _withEnvironment_ builder method).

**Comment by rgupta7888** [comment]
I am closing the issue as the suggestion worked ![bitmoji](https://render.bitstrips.com/v2/cpanel/10212025-294527585_1-s1-v1.png?transparent=1&palette=1&width=246)
