### ISSUE TITLE
Could not find Automation.tracetemplate in any of the followinglocations

### ISSUE THREAD

**Issue by sanatzzz** [appium/appium#8742]
Could not find Automation.tracetemplate in any of the followinglocations /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate,/Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.bundle/Contents/Resources/Automation.tracetemplate 

* Appium version (or git revision) that exhibits the issue: Appium 1.4.13
* Last Appium version that did not exhibit the issue (if applicable): 1.4.13
* Desktop OS/version used to run Appium: MacOS Seirra
* Mobile platform/version under test: iOS 9.3.5
* Real device or emulator/simulator: Real Device

I am using Xcode 7.3 and Appium 1.4.13 but still getting the error. I know that if Xcode and Appium versions mismatch we get this error but I am using the correct versions plus Automation.Tracetemplate cannot be found on both  AutomationInstrument.bundle and AutomationInstrument.xrplugin paths

Here are the full logs :
https://gist.github.com/sanatzzz/c1aea9f9094e8bba54a0e57aa37aa9b5

**Comment by imurchie** [comment]
That usually happens with Xcode 8.

The locations Appium is looking in are:
/Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate
/Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.bundle/Contents/Resources/Automation.tracetemplate

Is anything like that available?

**Comment by sanatzzz** [comment]
I have Xcode 7.3 installed.
I can't find the two paths that Appium is looking in. There is no Applications folder in the Contents folder nor there is any Automation.tracetemplate anywhere in the Xcode app

**Comment by sanatzzz** [comment]
I uninstalled 7.3 and installed 7.1.1 and now it's working. 7.1.1 has Automation.tracetemplate that appium is searching so I got my test running. Both 7.3 and 8 either don't have Automation.tracetemplate or maybe I did not correctly install them ( i guess it's the former). In conclusion, it's all about  Automation.Tracetemplate and if appium is able to find it
