### ISSUE TITLE
Appium 1.6.5 - Logcat terminated with code 0, signal null

### ISSUE THREAD

**Issue by nairouz12** [appium/appium#8743]
## The problem

After running a set of scenarios, the test stuck and the error below is thrown:
`[Logcat] Logcat terminated with code 0, signal null`

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Last Appium version that did not exhibit the issue (if applicable): 1.6.4
* Desktop OS/version used to run Appium: MacOS Sierra 10.12.4
* Node.js version (unless using Appium.app|exe): v7.2.1
* Mobile platform/version under test: Android 6.0
* Real device or emulator/simulator: genymotion emulator
* Appium CLI or Appium.app|exe: Appium CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

```
debug] [ADB] Current device property 'sys.boot_completed': 0
[debug] [ADB] Waiting for reboot. This takes time
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/usr/local/opt/android-sdk/platform-tools/adb' with args: ["-P",5037,"-s","192.168.56.101:5555","shell","getprop","sys.boot_completed"]
[debug] [ADB] Current device property 'sys.boot_completed': 0
[debug] [ADB] Waiting for reboot. This takes time
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/usr/local/opt/android-sdk/platform-tools/adb' with args: ["-P",5037,"-s","192.168.56.101:5555","shell","getprop","sys.boot_completed"]
[debug] [ADB] Current device property 'sys.boot_completed': 0
[debug] [ADB] Waiting for reboot. This takes time
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/usr/local/opt/android-sdk/platform-tools/adb' with args: ["-P",5037,"-s","192.168.56.101:5555","shell","getprop","sys.boot_completed"]
[debug] [ADB] Current device property 'sys.boot_completed': 1
[debug] [Logcat] Starting logcat capture
[Logcat] Logcat terminated with code 0, signal null
[HTTP] <-- POST /wd/hub/session - - ms - -
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"browserName":"","version":"","platform":"ANDROID","javascriptEnabled":true,"cssSelectorsEnabled":true,"takesScreenshot":true,"nativeEvents":false,"rotatable":false,"platformName":"Android","deviceName":"Samsung Galaxy S6 - 6.0.0 - API 23 - 1440x2560","app":"/Users/admin/Desktop/ui-testing/app-dummy-debug.apk","noReset":false,"platformVersion":"6.0","language":"nl","clearSystemFiles":true,"newCommandTimeout":250,"automationName":"uiautomator2","fullReset":false}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"browserName":"","version":"","platform":"ANDROID","javascriptEnabled":true,"cssSelectorsEnabled":true,"takesScreenshot":true,"nativeEvents":false,"rotatable":false,"platformName":"Android","deviceName":"Samsung Galaxy S6 - 6.0.0 - API 23 - 1440x2560","app":"/Users/admin/Desktop/ui-testing/app-dummy-debug.apk","noReset":false,"platformVersion":"6.0","language":"nl","clearSystemFiles":true,"newCommandTimeout":250,"automationName":"uiautomator2","fullReset":false},null,null]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1498571681667 (15:54:41 GMT+0200 (CEST))
```

**Comment by tfcardoso** [comment]
Probably the same as https://github.com/appium/appium/issues/7217, but the solution in there (switching to UIAutomator2) is not very good due to the long list of bugs UIAutomator2 still has.

This issue happens to me also from time to time

**Comment by nairouz12** [comment]
They recommanded the switch to UIAutomator2 that is why I did it. But indeed, there are many instability issues that I'm facing

**Comment by nairouz12** [comment]
I'm still facing the same issue even after reverting back to UIAutomator
`[debug] [ADB] Running '/usr/local/opt/android-sdk/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","getprop","sys.boot_completed"]
[debug] [ADB] Current device property 'sys.boot_completed': 0
[debug] [ADB] Waiting for reboot. This takes time
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/usr/local/opt/android-sdk/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","getprop","sys.boot_completed"]
[debug] [ADB] Current device property 'sys.boot_completed': 0
[debug] [ADB] Waiting for reboot. This takes time
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/usr/local/opt/android-sdk/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","getprop","sys.boot_completed"]
[debug] [ADB] Current device property 'sys.boot_completed': 1
[debug] [Logcat] Starting logcat capture
[Logcat] Logcat terminated with code 0, signal null`

**Comment by amias-channer** [comment]
You might get better results if you switch the automationName to 'Appium' instead of UIAutomator2 , the latter is not actively supported by google anymore.

Have experienced these issues before and they required a restart of the Appium server, I reduced the instances of this by configuring my tests to launch and stop the app for each scenario then adding an at_exit handler that explicitly quits the driver before restarting. It seems that scripts dieing or timing out can leave the Appium server stuck until it gets a driver_quit or is restarted completely.

**Comment by jlipps** [comment]
FWIW, `automationName: Appium` does precisely nothing. It uses UiAutomator1, which is even less used and less supported than UiAutomator2.

For the rest of you experiencing this, are you able to successfully run `adb logcat` on your own outside of Appium? But if the server is simply hanging that sounds like a bug we can fix somehow.

**Comment by benz-philip** [comment]
Experiencing the same issue. After a set of testcases the session hangs with error - 
[Logcat] Logcat terminated with code 0, signal null

**Comment by jlipps** [comment]
@benz-philip any pattern to when it hangs? Can you reproduce it reliably? Is it always after multiple testcases? etc.

**Comment by benz-philip** [comment]
@jlipps By running more number of cases say, 200TC, the run interrupts with error message [Logcat terminated with code 0]. there may be failed cases in the run. Last time it happened after 28 TCs

![image](https://user-images.githubusercontent.com/18724283/28808938-f776876a-7690-11e7-810f-bc337d784b66.png)

**Comment by jlipps** [comment]
@imurchie can you think of anything weird in our logcat handling that would lead to a hang after logcat terminates?

**Comment by imurchie** [comment]
I figured out the problem on Appium's side. Not why `adb logcat` is failing, but why it hangs. Getting a PR in place.

**Comment by imurchie** [comment]
Updating to the latest beta ought to get `appium-adb@2.26.0`, which should fix this.
