### ISSUE TITLE
How to find not visible elements

### ISSUE THREAD

**Issue by janice0402** [appium/appium#8745]
The problem

I have working tests running on simulator for appium 1.6.5. but not visible elements which is offscreen.
On simulator cannot find , so scroll to visible command not working. 
ele=driver.find_element(“//XCUIElementTypeApplication[1]//XCUIElementTypeCollectionView[1]//XCUIElementTypeStaticText[@name="AT-lgwqs.doc" ][1] “)
driver.execute_script('mobile: scroll', {"element": ele, "toVisible": True})

Environment
Appium version (or git revision) that exhibits the issue: 1.6.5 release
Desktop OS/version used to run Appium: macOS 10.12
Node.js version (unless using Appium.app|exe): 6.9.1
Mobile platform/version under test: iOS 10.2
Real device or emulator/simulator: real device iPhone6

**Comment by mykola-mokhnach** [comment]
> driver.execute_script('mobile: scroll', {"element": ele, "toVisible": True})

element id is expected here instead of the instance

Please use Appium forum to ask questions.

Closed as not an issue.
