### ISSUE TITLE
sometimes command ‘swipe’  not working 

### ISSUE THREAD

**Issue by vivian2011** [appium/appium#8746]
## The problem
command swipe not working

## Environment

* Appium version :   1.5.3
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium:    mac OS V10.11.6
* Node.js version (unless using Appium.app|exe):    7.3.0
* Mobile platform/version under test:    IOS 9.3.2
* Real device or emulator/simulator:   real device，iphone 6s plus
* Appium CLI or Appium.app|exe:    Appium.app

## Details

when the screen displays picture animations efects，swipe not working

## Link to Appium logs

[HTTP] --> POST /wd/hub/session/7ce07cfb-0daa-47d6-841c-e3535d1e29ab/touch/perform {"sessionId":"7ce07cfb-0daa-47d6-841c-e3535d1e29ab","actions":[{"action":"press","options":{"y":200,"x":100}},{"action":"wait","options":{"ms":2800}},{"action":"moveTo","options":{"y":-200,"x":100}},{"action":"release","options":{}}]}
[MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"press","option...
[debug] [iOS] Executing iOS command 'performTouch'
[debug] [UIAuto] Sending command to instruments: target.touch([{"touch":[{"x":100,"y":200}],"time":0.2},{"touch":[{"x":100,"y":200}],"time":3},{"touch":[{"x":200,"y":0}],"time":3.2}])

[debug] [Instruments] [INST] 2017-06-28 07:14:42 +0000 Debug: Got new command 18 from instruments: target.touch([{"touch":[{"x":100,"y":200}],"time":0.2},{"touch":[{"x":100,"y":200}],"time":3},{"touch":[{"x":200,"y":0}],"time":3.2}])
[debug] [Instruments] [INST] 2017-06-28 07:14:42 +0000 Debug: evaluating target.touch([{"touch":[{"x":100,"y":200}],"time":0.2},{"touch":[{"x":100,"y":200}],"time":3},{"touch":[{"x":200,"y":0}],"time":3.2}])
[debug] [Instruments] [INST] 2017-06-28 07:14:42 +0000 Debug: target.touch(__NSCFArray)
[debug] [UIAuto] Socket data received (25 bytes)
[debug] [UIAuto] Got result from instruments: {"status":0,"value":""}
[MJSONWP] Responding to client with driver.performTouch() result: null
[HTTP] <-- POST /wd/hub/session/7ce07cfb-0daa-47d6-841c-e3535d1e29ab/touch/perform 200 4055 ms - 76

**Comment by KuKiSiNi77** [comment]
Sometimes the reason course by the iOS version.you can try the latest iOS version.

**Comment by vivian2011** [comment]
@KuKiSiNi77   thank you for your reply.  
for ios10.0.1 , appium1.6.5 , i got the same problem:

[HTTP] --> POST /wd/hub/session/8be39dc0-5dbc-41e3-810c-dc6747656d71/touch/perform {"sessionId":"8be39dc0-5dbc-41e3-810c-dc6747656d71","actions":[{"action":"press","options":{"y":200,"x":100}},{"action":"wait","options":{"ms":2800}},{"action":"moveTo","options":{"y":-200,"x":100}},{"action":"release","options":{}}]}
[debug] [MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"y":200,"x":100}},{"action":"wait","options":{"ms":2800}},{"action":"moveTo","options":{"y":-200,"x":100}},{"action":"release","options":{}}],"8be39dc0-5dbc-41e3-810c-dc6747656d71"]
[debug] [XCUITest] Executing command 'performTouch'
[debug] [XCUITest] Received the following touch action: press(options={"y":200,"x":100})-wait(options={"ms":2800})-moveTo(options={"y":-200,"x":100})-release(options={})
[debug] [XCUITest] Found matching gesture: drag
[debug] [JSONWP Proxy] Proxying [POST /wda/dragfromtoforduration] to [POST http://localhost:8100/session/580335E9-B213-4452-AFBC-97F383E473CC/wda/dragfromtoforduration] with body: {"fromX":100,"fromY":200,"toX":200,"toY":0,"duration":2.8}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"580335E9-B213-4452-AFBC-97F383E473CC","status":0}
[debug] [MJSONWP] Responding to client with driver.performTouch() result: null
[HTTP] <-- POST /wd/hub/session/8be39dc0-5dbc-41e3-810c-dc6747656d71/touch/perform 200 8707 ms - 76

**Comment by SrinivasanTarget** [comment]
@vivian2011 Please use latest version of appium for `mobile:swipe` methods to work. See [here](https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios-xctest-mobile-gestures.md#mobile-swipe) for docs.

**Comment by SrinivasanTarget** [comment]
@vivian2011 FYI - TouchActions may not always work. There are known issues over there already which is being tracked in separate thread. Feel free to reopen incase if you hit the same over `mobile:` methods.
