### ISSUE TITLE
Android Emulator failed to scroll up and down using javascript - driver.execute_script("mobile: scroll",{"direction": "down"}) 

### ISSUE THREAD

**Issue by cindysongzi** [appium/appium#8748]
## The problem

driver.execute_script("mobile: scroll",{"direction": "down"}) 

Ran the above statement in my script, and it reported "selenium.common.exceptions.WebDriverException: Message: Method has not yet been implemented" exception. 

## Environment

* Appium version (or git revision) that exhibits the issue: appium 1.6.5-beta
* Last Appium version that did not exhibit the issue (if applicable): I remember the method is supported Appium1.6.3 running on iOS Simulators.... 
* Desktop OS/version used to run Appium: macOS Sierra V10.12.4
* Node.js version (unless using Appium.app|exe): v6.0.0
* Mobile platform/version under test: Android Emulator v4.4
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: Appium CLI

Waiting for your response. Thanks.

**Comment by imurchie** [comment]
Yes, the `mobile: xxx` methods are only available on iOS.

**Comment by mykola-mokhnach** [comment]
closed as designed

**Comment by mykola-mokhnach** [comment]
Use TouchActions interface for Android

**Comment by cindysongzi** [comment]
TouchAction works. But I have to give coordinates....

**Comment by cindysongzi** [comment]
Thank you!
