### ISSUE TITLE
Encountered internal error running command: Error: Process didn't end after 10000ms

### ISSUE THREAD

**Issue by Logakarti** [appium/appium#8750]
I'm facing the below error while automating my app cases in AWS device farm for the hybrid app.

Appium version: 1.6.3
Android version: 6.0
Appium Log:
https://gist.github.com/Logakarti/b53a79a837f39ff0e67785a0ddd4ec2e

@mykola-mokhnach

**Comment by mykola-mokhnach** [comment]
This is the real cause of the problem:

> 2017-06-28 09:57:25:064 - [Chromedriver] [STDOUT] [15.252][INFO]: RESPONSE InitSession unknown error: Chrome version must be >= 53.0.2785.0

Please read https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/chromedriver.md

Closed as duplicate
