### ISSUE TITLE
iPhone simulator is launching while requesting the iPad in appium 1.6.5

### ISSUE THREAD

**Issue by kommuswamy** [appium/appium#8753]
Hi @imurchie ,

when I tried to launch iPad simulator it is launching iPhone inside of iPad and app is loading in iPhone simulator.

Can you please check once !!

Thanks.

**Comment by imurchie** [comment]
Please provide the _full_ Appium server logs as a link to a [gist](https://gist.github.com). Without it, I cannot have any position whatsoever.

**Comment by kommuswamy** [comment]
[appium.zip](https://github.com/appium/appium/files/1109697/appium.zip)

**Comment by imurchie** [comment]
I cannot open a random zip file. Sorry.

Please provide the _full_ Appium server logs as a link to a [gist](https://gist.github.com).

**Comment by kommuswamy** [comment]
<script src="https://gist.github.com/kommuswamy/37f1f548866fd395e901203bfa699111.js"></script>

**Comment by kommuswamy** [comment]
@imurchie ,updated in gist.

**Comment by kommuswamy** [comment]
https://gist.github.com/kommuswamy/37f1f548866fd395e901203bfa699111

**Comment by babusurendra** [comment]
Hi @imurchie , I am also facing the same issue, can you please check this once

**Comment by timyhou** [comment]
@kommuswamy how are you setting the deviceName capability? That is how you can specify iPad, iPhone, etc.

From you log`[BaseDriver] SessionNotCreatedError: A new session could not be created. Details: The desiredCapabilities object was not valid for the following reason(s):  deviceName can't be blank,` According to the log you passed the following: 
```
"screenshotWaitTimeout":60,
"newCommandTimeout":200,
"platformVersion":"9.3",
"automationName":"XCUITest",
"browserName":"FactSet",
"waitForAppScript":"target.elements().length > 0;",
"platformName":"ios",
"platform":"MAC"
```

**Comment by babusurendra** [comment]
@timyhou I just  went through @kommuswamy  logs and found that only one time it is showing that **deviceName can't be blank,** error and this issues i have also seen when missed giving device name.

But remaining all the times it is shwoing appropriate simulator , I dont think this is causing the issue here.

can you check full logs once ?

**Comment by timyhou** [comment]
Sorry, OP's log has at least 20 attempts at launching the driver. A lot of them with errors. 

If you would be so kind to have a log of just a single attempt where you saw the bad behavior it would make analyzing it much easier. 

Anyway, assuming the last run was where OP saw the bad behavior. 

`2017-06-28 15:22:58:592 - warn: [XCUITest] Carthage not found. Install using 'brew install carthage'`
It looks like you are missing carthage. Might as well check any other dependencies too https://github.com/appium/appium-xcuitest-driver#external-dependencies


```
2017-06-28 17:57:46:431 - info: [Appium] Capabilities:
2017-06-28 17:57:46:432 - info: [Appium]   platform: 'MAC'
2017-06-28 17:57:46:432 - info: [Appium]   platformName: 'ios'
2017-06-28 17:57:46:433 - info: [Appium]   platformVersion: '9.3'
2017-06-28 17:57:46:433 - info: [Appium]   deviceName: 'iPad Retina'
2017-06-28 17:57:46:433 - info: [Appium]   browserName: 'FactSet'
2017-06-28 17:57:46:433 - info: [Appium]   app: '/BuildArchives/2017_V1/iphone_snapshot_2.40.0.0_build/2.40.11.2/release/bin/Release_Sim/FactSet.app'
2017-06-28 17:57:46:433 - info: [Appium]   automationName: 'XCUITest'
2017-06-28 17:57:46:433 - info: [Appium]   screenshotWaitTimeout: 60
2017-06-28 17:57:46:433 - info: [Appium]   newCommandTimeout: 200
2017-06-28 17:57:46:433 - info: [Appium]   waitForAppScript: 'target.elements().length > 0;'
```
The capabilities seem okay. `platform` is superfluous though and can be removed. Appium will toss it out anyway. `browserName` should be blank if you are automating an app.

`2017-06-28 17:57:48:468 - info: [iOSSim] Starting simulator with command: open -Fn /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app --args -CurrentDeviceUDID A821C859-18E8-4A08-99CA-4D779BD8D938 -ConnectHardwareKeyboard 0`

This shows which simulator was being launched (CurrentDeviceUDID). You can check which simulators that is by running this command `instruments -s devices | grep A821C859-18E8-4A08-99CA-4D779BD8D938` I doubt that this is the problem though, which leads me to some questions...

Does this behavior only occur when you are trying to test your App? 
What if you try just launching safari on the iPad or iPhone?

**Comment by kommuswamy** [comment]
Hi @timyhou ,

I have checked the device name **instruments -s devices | grep A821C859-18E8-4A08-99CA-4D779BD8D938** by running this command it shows iPad Retina, but it launches the iPhone simulator inside the iPad Retina Device.

**Comment by kommuswamy** [comment]
I have Added latest appium logs in gist, https://gist.github.com/kommuswamy/20341f60eefe2f5caab7e2c7b8b07546

**Comment by kommuswamy** [comment]
<script src="https://gist.github.com/kommuswamy/20341f60eefe2f5caab7e2c7b8b07546.js"></script>

**Comment by imurchie** [comment]
Since you are not specifying a `udid` for a particular simulator, Appium does the following:
1. Take the `deviceName` and `platformVersion`, and find a matching simulator by running `xcrun simctl list`.
2. If one is found, use it.
3. If one is not found, create one.

**Comment by imurchie** [comment]
If you open the simulator manually what does it looks like?

**Comment by kommuswamy** [comment]
@imurchie Thanks a lot for the help. I was able to narrow down the problem to 

- App launches normally when the '.app' file is on the mac machine. ex:  Desktop
- App is loading in iPhone(the simulator window is still an iPad but it internally has an iPhone) when the '.app' file is in a network location which is mounted to the mac machine as a local directory
![2017-07-13_23-17-28](https://user-images.githubusercontent.com/18289360/28180051-86749246-6821-11e7-879a-355f3d00806b.png)

**Comment by SrinivasanTarget** [comment]
@kommuswamy Are you running iPhone app in iPad? Its an iPad Sim opened up clearly with diff dimensions. Its not iPhone Sim that opened. Incase if you still wanted to confirm that it is iPad, please run `xcrun simctl list devices` and see what sim is actually booted.

**Comment by babusurendra** [comment]
@SrinivasanTarget if you observe in the above screen capture the wrapper is iPad Sim but inside iPhone Sim is loading.
once we move into the further test steps there it shows the iPhone view in clear.

**Comment by kommuswamy** [comment]
@SrinivasanTarget , Visually it shows iPad but internally it launches the iPhone simulator, below is the pure iPad simulator.
![image](https://user-images.githubusercontent.com/18289360/28210048-2f0db22a-68b3-11e7-92b6-549a02cc18bc.png)

**Comment by kommuswamy** [comment]
@SrinivasanTarget , Can we have any update on this?

**Comment by kommuswamy** [comment]
Hi @imurchie,

Please, can some one take a look into it?

Thanks..

**Comment by imurchie** [comment]
I have no idea why this would be happening. Nor do I have any idea how to figure out. Unfortunately.

**Comment by SrinivasanTarget** [comment]
@kommuswamy No idea either, please check in discuss forum.
