### ISSUE TITLE
Appium 1.6.5: Got error when use set "unicodeKeyboard" to 'true'

### ISSUE THREAD

**Issue by Jennifer-traderev** [appium/appium#8755]
## The problem

Unable to create a new session with with setCapabilities("unicodeKeyboard",true)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Last Appium version that did not exhibit the issue (if applicable): 1.4.16
* Desktop OS/version used to run Appium: windows 10
* Node.js version (unless using Appium.app|exe): 6.10.3
* Mobile platform/version under test: Android 7.1.2
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: CLl

## Details

It works well without: cap.setCapability("unicodeKeyboard", true);

## Link to Appium logs

[debug] [ADB] 2 device(s) connected
[debug] [ADB] Running 'C:\QA\sdk\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","xxxxx15C21000186","shell","echo","ping"]
[debug] [Logcat] Starting logcat capture
[debug] [AndroidDriver] Enabling Unicode keyboard support
[debug] [AndroidDriver] Pushing unicode ime to device...
[debug] [ADB] Running 'C:\QA\sdk\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","xxxxx15C21000186","install","C:\\Users\\Vivian Smith\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-android-ime\\bin\\UnicodeIME-debug.apk"]
[debug] [ADB] Running 'C:\QA\sdk\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","xxxxx15C21000186","install","C:\\Users\\Vivian Smith\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-android-ime\\bin\\UnicodeIME-debug.apk"]
[debug] [UiAutomator2] Deleting UiAutomator2 session
[debug] [UiAutomator2] Deleting UiAutomator2 server session
[UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error was: Error: Trying to proxy a session command without session id

## Code To Reproduce Issue [ Good To Have ]

cap = new DesiredCapabilities();
		cap.setCapability(CapabilityType.BROWSER_NAME, "Android");
		cap.setCapability("deviceName", deviceid);
		cap.setCapability("platformName", "Android");
		cap.setCapability(CapabilityType.VERSION, "7.1.2");
		cap.setCapability("appPackage", appApk);
		cap.setCapability("appActivity", "com.mycompany.android.ui.activities.SplashActivity");
		cap.setCapability("--session-override", true);
//		cap.setCapability("unicodeKeyboard", true);
//		cap.setCapability("resetKeyboard", true);
		cap.setCapability("dontStopAppOnReset", true);
		cap.setCapability("newCommandTimeout", 300);		
		cap.setCapability("noReset", "true");
		cap.setCapability("automationName", "uiautomator2");

**Comment by jlipps** [comment]
Please upload the full set of appium logs to gist.github.com and link them here. We need to see the full log in order to help.

**Comment by mekxtari** [comment]
Hi, i don't know if the issue in unicoKeyboard is also causing problems in my test. I started refactoring my android tests to work with uiautomator2 driver. I noticed that resetKeyboard is not working anymore. Appium Android Input Manager for Unicode says as default keyboard and this is really annoying. It is working if i used the old default driver. 

Only tried this with latest appium version 1.6.5

**Comment by imurchie** [comment]
@mekxtari Can you provide the full Appium server logs (as a link to a [gist](https://gist.github.com))? We cannot do anything without them.

**Comment by mekxtari** [comment]
hi @imurchie ,

what you mean by full appium server logs? What kind of log level should be used? Our CI currently uses this: appium -p ${PORTNUMBER} --log-level warn

br Tommi

**Comment by mekxtari** [comment]
Hi @imurchie

Here is a full appium log: 

https://gist.github.com/mekxtari/598f26eecc1b3d0472745289f37fd748

**Comment by imurchie** [comment]
Problem: we are not saving the IME before we change it, in the UIAutomator2 driver.

Fixing.

**Comment by mekxtari** [comment]
Great!

**Comment by imurchie** [comment]
The latest version (with `appium-uiautomator2-driver@0.5.4`) ought to fix this problem.

**Comment by mekxtari** [comment]
Hi @imurchie,

it seems that issue still exist in Appium 1.7.1. Appium unicode keyboard stays as default and resetKeyboard does not work. Here is a log file:
https://gist.github.com/mekxtari/723933a7317c7c8363d6ee7a21a2ca39

**Comment by imurchie** [comment]
@mekxtari You are starting out with Appium's Unicode keyboard as default, so the system just "returns" it to that. This is not a bug.

See https://gist.github.com/mekxtari/723933a7317c7c8363d6ee7a21a2ca39#file-appium_server-log-L99
