### ISSUE TITLE
User can't install WDA on Xcode 8.3.3

### ISSUE THREAD

**Issue by Bamivani** [appium/appium#8757]
## The problem

User can't install WDA on Xcode 8.3.3
(XCTRunner does not have an architecture that device name can execute.)

I can install WDA on old Xcode version successfully

## Environment

* Appium version 1.6.6 beta
* Mobile platform/version under test: 10.3
* Real device or emulator/simulator: Real device

**Comment by mykola-mokhnach** [comment]
Please attach full Appium log and xcodebuild log

**Comment by Bamivani** [comment]
Could you show me where Appium and xcodebuild log are ?

**Comment by Bamivani** [comment]
Hi mykola-mokhnach

I install WDA via https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md

But when I build WDA on XCODE 8.3.3, error display "XCTRunner does not have an architecture that device name can execute"

I build WDA on old version XCODE successfully.

Pls help me find out root cause issue above

**Comment by Bamivani** [comment]
Pls get log to see more detail

**Comment by mykola-mokhnach** [comment]
> [Xcode] 2017-06-30 09:33:10.347 xcodebuild[1093:70491] Error Domain=com.apple.dtdevicekit Code=-402653093 "Too many instances of this service are already running." UserInfo={NSLocalizedFailureReason=Too many instances of this service are already running., com.apple.dtdevicekit.stacktrace=(

This is known XCTest issue, which happens after WDA has been restarted several times on a real device. Rebooting the device helps for some time. Read https://github.com/facebook/WebDriverAgent/issues/507 for more details.

Closed as duplicate.
