### ISSUE TITLE
Issue automating Android native browser

### ISSUE THREAD

**Issue by droidscout** [appium/appium#8759]
## The problem
Hi,
I'm trying to automate differend browser (Android native browser, Chrome) on Android. Therefore I'm using the Android emulator (Android 6.0 Marshmellow). Since I'm having problems with xpath (not subject to this issue) in Chrome, I wanted to try if the problem also exists with the native browser. 
Automating Chrome webbrowser on Android works with Appium, automating Android native webbrowser doesn't, see details.

I have attached my appium log. I'm using chromedriver and as for the logs it looks like its an issue with this. But since I'm not sure if it really is the chromedriver part (as it works for chrome), I wanted to post my issue here. 

## Environment
Appium 1.6.4 CLI
Windows 7 64bit
Android emulator with Android 6.0 (API 23) Marshmellow
chromedriver 2.30.477700
Selenium 3.4.0

## Details
When I start the automation test for the Chrome browser it works except for the xpath problem that I have, but that's another story. When I start the automation test for the Android native browser (blue world icon) it opens the browser, the start page starts loading and the browser gets closed. The process of opening and closing is performed a few times and then the automation stops with failure. 

## Link to Appium logs
https://gist.github.com/droidscout/5b8491e3b9550dbd12b01271140613a3

## Code To Reproduce Issue
**Connection setup with Java:**

        URL appiumServerUrl = new URL( "http://127.0.0.1:4723/wd/hub" );
        DesiredCapabilities caps = new DesiredCapabilities();

        caps.setCapability( "clearSystemFiles", true );
        caps.setCapability( "noReset", true );
        // we set the new command timeout to a higher value than 60 sec. to prevent the
        // session being closed after one minute.
        caps.setCapability( MobileCapabilityType.NEW_COMMAND_TIMEOUT, 720 );
        // only set the device name when we automate a real device
        if ( deviceName != null &&
                (realDevice || operatingSystem.toLowerCase().equals( IOS_DEVICE )) ) {
            caps.setCapability( MobileCapabilityType.DEVICE_NAME, deviceName );
        }
        // if we want to automate with an android emulator, we need to set device name and
        // "avd" capability to start the emulator automatically if not already started
        else if ( deviceName != null & !realDevice
                && operatingSystem.toLowerCase().equals( ANDROID_DEVICE ) ) {
            caps.setCapability( MobileCapabilityType.DEVICE_NAME, deviceName );
            caps.setCapability( AndroidMobileCapabilityType.AVD, deviceName );
        }

        String linuxPath = "/usr/local/bin/chromedriver";
        String windowsPath = "C:\\Users\\lo\\chromedriver\\chromedriver.exe";
        String chromeDriverPath = "";

       if ( SystemUtils.IS_OS_MAC_OSX || SystemUtils.IS_OS_LINUX ) {
            chromeDriverPath = linuxPath;
        } else if ( SystemUtils.IS_OS_WINDOWS ) {
            chromeDriverPath = windowsPath;
        }

        // capabilities setup for Android device
        caps.setCapability( MobileCapabilityType.PLATFORM_NAME, "Android" );
        caps.setCapability( AndroidMobileCapabilityType.CHROMEDRIVER_EXECUTABLE, chromeDriverPath );
        caps.setCapability( AndroidMobileCapabilityType.RECREATE_CHROME_DRIVER_SESSIONS, true );
        // browser type safari was used with android device which is not supported
        if ( browserType.toLowerCase().equals( BROWSER_TYPE_SAFARI ) ) {
               throw new IllegalArgumentException( "Browser " + BROWSER_TYPE_SAFARI + " not supported with android device!\n" +
                            "Use " + BROWSER_TYPE_ANDROID + ", " + BROWSER_TYPE_CHROME + "or " + BROWSER_TYPE_FIREFOX + " instead." );
        }
        caps.setCapability( MobileCapabilityType.BROWSER_NAME, browserType );
        driver = new AppiumDriver( appiumServerUrl, caps );
       
Thanks in advance for any support!

**Comment by mykola-mokhnach** [comment]
the log says it might be useful for you to take a look at this document https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/chromedriver.md

**Comment by droidscout** [comment]
Thanks for the comment. The information on that page is related to Chrome browser only. I'm trying to automate the native android webbrowser.

**Comment by mykola-mokhnach** [comment]
Yes, but we still try to use the same driver for this purpose. And the problem there, that the actual versions of chromedriver and built-in browser (which internally uses Chromium core) don't match

**Comment by droidscout** [comment]
Ok, gotcha. I will try to find out which chromedriver I have to use and come back with any updates. 
Thank you!

**Comment by droidscout** [comment]
So it works with chromedriver version 2.19.346078.
