### ISSUE TITLE
Question: Does appium support to launch the emulator as part of each test

### ISSUE THREAD

**Issue by vsadineni1** [appium/appium#8762]
Hello 
I have a question regarding appium for android emulators.

Does appium support launching the emulator when the test starts & shuts-down after the test.
I see that the appium --avd command option is deprecated.
**_appium -p 7777 --avd Nexus_5X_API_2_**
Is there a way we can achieve this instead of updating each test to pass the desired capability:
Example:
**_cap.setCapability("avd", "Nexus_5X_API_23")_**

Environment:
Appium: 1.6.4
OS: Mac Sierra 10.12.5 or Ubntu: 14.04
Android: OS: 6.0 (Marshamallow) API Level = 23

**Comment by vsadineni1** [comment]
@jlipps

**Comment by imurchie** [comment]
The `--avd` server flag is deprecated (but still works) in favor of using a "default capability", which are passed in through the `--default-capabilities` server flag.

See https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/default-capabilities-arg.md
