### ISSUE TITLE
RESPONSE ExecuteScript chrome not reachable

### ISSUE THREAD

**Issue by Logakarti** [appium/appium#8763]
I'm facing "RESPONSE ExecuteScript chrome not reachable" exception while automating the app cases in AWS for Android hybrid app. Especially I get this exception for my download cases(download the book from my app).

## Environment
* Appium version: 1.6.3
* Device:  Motorola Moto G (AT&T)
* Android version: 4.4.4

## Link to Appium logs
https://gist.github.com/Logakarti/a785ed8ab3f3cb41ec41b177d776d76e

## Code To Reproduce Issue [ Good To Have ]
Here are my used capabilities,

final String URL_STRING = "http://127.0.0.1:4723/wd/hub";
        URL url = new URL ( URL_STRING );
        DesiredCapabilities capabilities = new DesiredCapabilities ( );
        driver = new AndroidDriver<MobileElement> ( url, capabilities );
        capabilities.setCapability(CapabilityType.BROWSER_NAME, "");
        capabilities.setCapability("newCommandTimeout", "50000");
        capabilities.setCapability("recreateChromeDriverSessions", true );
        //Use a higher value if your mobile elements take time to show up
        driver.manage().timeouts().implicitlyWait(80, TimeUnit.SECONDS );

**Comment by Logakarti** [comment]
@mykola-mokhnach

**Comment by mykola-mokhnach** [comment]
I don't think it's anyhow related to Appium. There might e problem in the app under test/chromedriver itself.

**Comment by Logakarti** [comment]
Thanks @mykola-mokhnach
