### ISSUE TITLE
AndroidDriver cannot use Duration with waitAction()

### ISSUE THREAD

**Issue by LeePray** [appium/appium#8765]
## The problem
As you can see, i can not use Duration with waitAction ()
## Environment

* Appium version 1.6.5
* Desktop OS/version used to run Appium: Mac OS ver 10.12.5
* Mobile platform/version under test: Android 6.0.1
* Real device or emulator/simulator: Real device

## Details

    public static void swipeHorizontal(AndroidDriver driver, double startPercentage, double finalPercentage, double anchorPercentage, int duration)
    {
        Dimension size = (driver.manage().window().getSize());
        int anchor = (int) (size.height * anchorPercentage);
        int startPoint = (int) (size.width * startPercentage);
        int endPoint = (int) (size.width * finalPercentage);
        new TouchAction(driver).press(startPoint, anchor)
                .waitAction()
                .moveTo(endPoint, anchor)
                .release()
                .perform();
    }

When i put the duration in .waitAction() , popup says " waitAction(int) is deprecated " 
How can i do that.

**Comment by JaniJegoroff** [comment]
I'm not familiar with Java bindings but you are trying to use `int` instead of `Duration`.
How about trying `waitAction(Duration.ofSeconds(1))`

```
https://appium.github.io/java-client/io/appium/java_client/TouchAction.html

waitAction(java.time.Duration duration)
Waits for specified amount of time to pass before continue to next touch action.

waitAction(int ms)
Deprecated.
```

**Comment by mykola-mokhnach** [comment]
Closed as non server-ralted. There is a separate repository for java client issues: https://github.com/appium/java-client

**Comment by LeePray** [comment]
@JaniJegoroff  Sorry i already did. But it doesn't work.

**Comment by mykola-mokhnach** [comment]
Your problem might be that you try to provide absolute values as the endpoint coordinates, but they should be relative to the starting point

**Comment by LeePray** [comment]
@mykola-mokhnach  Very thanks for helping. But can you give me some example code?

**Comment by LeePray** [comment]
@mykola-mokhnach  It is my test code Gist 
https://gist.github.com/LeePray/4bc2b50b7b1979a7fff79feaa92fb5cc

**Comment by JaniJegoroff** [comment]
Like I already said you can't pass `int` to the `waitAction` because method expects `Duration`.

**Comment by LeePray** [comment]
@JaniJegoroff  But it is same as changing to Duration
