### ISSUE TITLE
Please help! Unable to start Appium service.

### ISSUE THREAD

**Issue by cyw119** [appium/appium#8767]
## The problem

Hi, I am new to appium, when I launch appium and click on Start New Session, I am not able to launch the app.

## Environment

* Appium version: 1.6.4
* Desktop OS/version used to run Appium: MAC Sierra 10.12.4
* Node.js version (unless using Appium.app|exe): 7.10.0
* Mobile platform/version under test: IOS 10.3
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

Setting in Appium
{
  "platformName": "iOS",
  "platformVersion": "10.3",
  "deviceName": "iPhone Simulator",
  "app": "[USER_PATH]/Library/Developer/Xcode/DerivedData/AribaSupplier-ajzhohmfqtlmppaawsefcemwybth/Build/Products/Debug-iphonesimulator/AribaSupplier.app",
  "noReset": "true"
}

## Details

Log:
[XCUITest] Failed to create WDA session. Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1498848041338 (11:40:41 GMT-0700 (PDT))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[XCUITest] Failed to create WDA session. Retrying...
[XCUITest] Unable to start WebDriverAgent session: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8100
[XCUITest] Quitting and uninstalling WebDriverAgent, then retrying

**Comment by imurchie** [comment]
Can you post the _full_ server logs as a link to a [gist](https://gist.github.com)?

**Comment by cyw119** [comment]
Sorry, done.

**Comment by imurchie** [comment]
The xcodebuild process is being shutdown for some reason:
```
[XCUITest] xcodebuild exited with code 'null' and signal 'SIGABRT'
```

Not sure why that would happen. To get more information, can you turn on xcode logging by adding the boolean desired capability `showXcodeLog` set to `true`, and reposting the logs from an attempted run?

**Comment by cyw119** [comment]
Updated, thanks for your help.

**Comment by mykola-mokhnach** [comment]
> [Xcode] 2017-06-30 13:50:51.812 xcodebuild[53121:3348440] [MT] DVTAssertions: ASSERTION FAILURE in /Library/Caches/com.apple.xbs/Sources/DVTFrameworks/DVTFrameworks-12154/DVTFoundation/MacroExpansion/DVTMacroDefinitionConditionSet.mm:154
> [Xcode] Details:  stringRep should be a non-empty string, but it's an empty string

It looks like some internal Xcode misconfiguration. Try to clean Xcode caches/update to a newer Xcode version/run the automation on some other machine.

**Comment by cyw119** [comment]
Thanks for your help, but I still have some issue.  My colleague observed that I don't have "web driver agent" installed on my simulator.  That's why it kept displayed the following:

Failed to create WDS session.  Retrying...

Any idea how to install "web driver agent" ?

Thanks a lot

**Comment by mykola-mokhnach** [comment]
Like I said try on the other machine. The current one is somehow corrupted.

**Comment by bigdrum** [comment]
I got exactly the same error. However if I copied the command line of xcodebuild that was printed in the log to iterm and run it, it ran without any problem. Could there be some kind of environment setup problem by the appium?

**Comment by dpgraham** [comment]
@bigdrum @cyw119 I know this is an old issue but I can just ask if this issue happened for the two of you in Appium Desktop (the GUI) or in terminal?

I'm facing this same issue and am looking to make a fix for it for the next version. I suspect that this only is happening in Appium Desktop.
