### ISSUE TITLE
getText does not work with xpath

### ISSUE THREAD

**Issue by anand853** [appium/appium#8768]
getText does not work with xpath

I tried all the types of xpath to find the get of element  but i never succeeded. can you please let me know how to get the text of this element with the name 'automatic' 

## Environment

* Appium version 1.1.0 beta 2
<img width="1205" alt="screen shot 2017-06-30 at 10 51 41 pm" src="https://user-images.githubusercontent.com/3404193/27758638-8e33c7ac-5de7-11e7-823c-9dd91425fb14.png">

**Comment by linhnh123** [comment]
try: (Ruby)
`
element = driver.find_element(:xpath, '//android.widget.CheckedTextView[@text="Automatic"]')
text = element.text
`

**Comment by mykola-mokhnach** [comment]
Please use Appium forum to ask questions.

Closed as non server-related.

**Comment by anand853** [comment]
can you please share the link of it?

**Comment by mykola-mokhnach** [comment]
https://discuss.appium.io
