### ISSUE TITLE
when I start appium test this is another uiautomator run at the phone,then even if i kil the uiautomator  program I can not start any more ,the log is below

### ISSUE THREAD

**Issue by melissalu** [appium/appium#8774]
[debug] [ADB] Running '/Users/melissalu/Documents/AndroidSDK/sdk/platform-tools/adb' with args: ["-P",5037,"-s","ZX1G22M5ST","forward","tcp:4724","tcp:4724"]
[debug] [UiAutomator] Starting UiAutomator
[debug] [UiAutomator] Moving to state 'starting'
[debug] [UiAutomator] Parsing uiautomator jar
[debug] [UiAutomator] Found jar name: 'AppiumBootstrap.jar'
[debug] [ADB] Running '/Users/melissalu/Documents/AndroidSDK/sdk/platform-tools/adb' with args: ["-P",5037,"-s","ZX1G22M5ST","push","/Users/melissalu/Documents/old/workspace/systest/appium-1.6.3/node_modules/appium-android-bootstrap/bootstrap/bin/AppiumBootstrap.jar","/data/local/tmp/"]
[debug] [ADB] Attempting to kill all uiautomator processes
[debug] [ADB] Getting all processes with uiautomator
[debug] [ADB] Getting connected devices...
[debug] [ADB] 2 device(s) connected
[debug] [ADB] Running '/Users/melissalu/Documents/AndroidSDK/sdk/platform-tools/adb' with args: ["-P",5037,"-s","ZX1G22M5ST","shell","ps"]
[ADB] No uiautomator process found to kill, continuing...
[debug] [UiAutomator] Starting UIAutomator
[debug] [ADB] Creating ADB subprocess with args: ["-P",5037,"-s","ZX1G22M5ST","shell","uiautomator","runtest","AppiumBootstrap.jar","-c","io.appium.android.bootstrap.Bootstrap","-e","pkg","com.tencent.wework","-e","disableAndroidWatchers",false,"-e","acceptSslCerts",false]
[UiAutomator] UiAutomator exited unexpectedly with code 0, signal null
[debug] [UiAutomator] Moving to state 'stopped'
[HTTP] --> GET /wd/hub/sessions {}
[debug] [MJSONWP] Calling AppiumDriver.getSessions() with args: []
[HTTP] <-- GET /wd/hub/sessions - - ms - - 
[HTTP] --> POST /wd/hub/session {"requiredCapabilities":{},"desiredCapabilities":{"deviceName":"sanxing note 4","unicodeKeyboard":true,"udid":"ZX1G22M5ST","noReset":true,"resetKeyboard":true,"platformVersion":"6.0","appPackage":"com.tencent.wework","platformName":"Android","appActivity":"com.tencent.wework.launch.WwMainActivity"}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"deviceName":"sanxing note 4","unicodeKeyboard":true,"udid":"ZX1G22M5ST","noReset":true,"resetKeyboard":true,"platformVersion":"6.0","appPackage":"com.tencent.wework","platformName":"Android","appActivity":"com.tencent.wework.launch.WwMainActivity"},{},null,null,null]
[HTTP] --> GET /wd/hub/sessions {}
[debug] [MJSONWP] Calling AppiumDriver.getSessions() with args: []
[HTTP] <-- GET /wd/hub/sessions - - ms - - 
[HTTP] --> POST /wd/hub/session {"requiredCapabilities":{},"desiredCapabilities":{"deviceName":"sanxing note 4","unicodeKeyboard":true,"udid":"ZX1G22M5ST","noReset":true,"resetKeyboard":true,"platformVersion":"6.0","appPackage":"com.tencent.wework","platformName":"Android","appActivity":"com.tencent.wework.launch.WwMainActivity"}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"deviceName":"sanxing note 4","unicodeKeyboard":true,"udid":"ZX1G22M5ST","noReset":true,"resetKeyboard":true,"platformVersion":"6.0","appPackage":"com.tencent.wework","platformName":"Android","appActivity":"com.tencent.wework.launch.WwMainActivity"},{},null,null,null]
[HTTP] --> GET /wd/hub/sessions {}
[debug] [MJSONWP] Calling AppiumDriver.getSessions() with args: []
[HTTP] <-- GET /wd/hub/sessions - - ms - - 
[HTTP] --> GET /wd/hub/sessions {}
[debug] [MJSONWP] Calling AppiumDriver.getSessions() with args: []
[HTTP] <-- GET /wd/hub/sessions - - ms - - 
[HTTP] --> GET /wd/hub/sessions {}
[debug] [MJSONWP] Calling AppiumDriver.getSessions() with args: []
[HTTP] <-- POST /wd/hub/session - - ms - -

**Comment by melissalu** [comment]
![image](https://user-images.githubusercontent.com/13230344/27814140-24dd0d22-60ad-11e7-90a8-252182a53f5f.png)
and I can not shut down

**Comment by mykola-mokhnach** [comment]
Do you use the latest Appium version (1.6.5)?
