### ISSUE TITLE
Unable to find element using iOSClassChain locator strategy.

### ISSUE THREAD

**Issue by adamlfs** [appium/appium#8776]
## The problem

Unable to find any element using iOSClassChain locator strategy.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Last Appium version that did not exhibit the issue (if applicable): - 
* Desktop OS/version used to run Appium: macOS Sierra 10.2.3
* Node.js version (unless using Appium.app|exe): 7.5.0
* Mobile platform/version under test: iOS 10.2.1
* Real device or emulator/simulator: iphone 5s(real device)
* Appium CLI or Appium.app|exe: CLI

## Details

I am trying to avoid using XPath locators in my code. I would like to replace as much xpaths as possible because I notice that they work unstable. I would like to use iOSClassChain locators which are suggested as substitution for xpath locators however Im not able to perform ClassChain query for element even in simple case like using the following:
`MobileBy.iOSClassChain("XCUIElementTypeStaticText[1]")`

In the appium log it looks like the locator is valid. Im sure that on the screen there is at least on element of type XCUIElementTypeStaticText.

I use  5.0.0-BETA9 java-client to execute tests. 

## Link to Appium logs

https://gist.github.com/adamlfs/2818cbf0435ef7057364c4326febd981

**Comment by adamlfs** [comment]
@mykola-mokhnach should it work as described above or there is something wrong with my code?

**Comment by mykola-mokhnach** [comment]
Is XCUIElementTypeStaticText the direct child of the element on which search is executed?

**Comment by adamlfs** [comment]
Thanks for response.
Im looking for XCUIElementTypeStaticText in context of whole application.
I would like to replace xpath: (//XCUIElementTypeStaticText)[1]

**Comment by mykola-mokhnach** [comment]
This won't work for now - class chain only supports direct children lookup. There is a [PR](https://github.com/facebook/WebDriverAgent/pull/612) for indirect search, but it's still waiting for review.

**Comment by adamlfs** [comment]
Thanks

**Comment by mykola-mokhnach** [comment]
you could use class name lookup for such simple case:

```
driver.findElement(By.className("XCUIElementTypeStaticText"))
```

**Comment by adamlfs** [comment]
Yes, but I would like to replace some xpaths with classChain locator to improve reliability of my tests. Its not possible now as you explain me. In the  final locator I would like to limit query results using some attributes like name,label etc.

**Comment by mykola-mokhnach** [comment]
Then add a like to the PR and wait until it's merged ;)

**Comment by adamlfs** [comment]
I would like to handle alert notification. Till now I use xpath to locate Alert with description like this: 
//XCUIElementTypeAlert[contains(@name,'would like to make data available to nearby Bluetooth devices')]//XCUIElementTypeButton[@name='OK' or @name='Allow']
I want to be aware during test execution that I accept Bluetooth access permission and nothing else. The xpath doesnt work stable in appium 1.6.5 and thats why I tried to replace it with classChain locator.

**Comment by mykola-mokhnach** [comment]
there are separate endpoints for alerts, for example: `getDriver().switchTo().alert().getText()`

Why not to use these?

**Comment by aljones15** [comment]
does this work yet?
