### ISSUE TITLE
Adb session terminates when more than 3 devices connected.

### ISSUE THREAD

**Issue by rajit30** [appium/appium#8777]
## The problem

When I am trying to run test cases in more than 3 devices parallely(in my case i connected 4 devices), then 2 of the appium server reports the  error:

Error:
Unhandled rejection Error: Error executing adbExec. Original error: 'Command '/opt/android-sdk-linux/platform-tools/adb -P 5037 -s 4203aa20c8715200 shell am force-stop com.*****.android' exited with code 1'; Stderr: 'error: device '4203aa20c8715200' not found'; Code: '1'
    at ADB.execFunc$ (../../../lib/tools/system-calls.js:228:13)
    at tryCatch (/usr/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:109:7)

This happened multiple times while running the test cases parallely.If I run sequentially everything is working fine.

## Environment

Appium Version- 1.6.5
Scripting Language Used- Python

## Appium Launched in 4 different instances using pre-launch mode

appium -a 127.0.0.1 -p 4725 -bp 5000 --pre-launch --device-name Android --udid 4203aa20c8715200 --app-pkg com.******.android --app-activity com.******.android.xyzvfg.app.view.activity.******Activity --platform-name Android --app /home/rajit.s/Desktop/Automation_APK/xyzvfg-4.2.2-production-release.apk --session-override

appium -a 127.0.0.2 -p 4725 -bp 5002 --pre-launch --device-name Android --udid 250dcc7a --app-pkg com.******.android --app-activity com.******.android.xyzvfg.app.view.activity.******Activity --platform-name Android --app /home/rajit.s/Desktop/Automation_APK/xyzvfg-4.2.2-production-release.apk --session-override

appium -a 127.0.0.3 -p 4726 -bp 5001 --pre-launch --device-name Android --udid T0094111BV --app-pkg com.******.android --app-activity com.******.android.xyzvfg.app.view.activity.******Activity --platform-name Android --app /home/rajit.s/Desktop/Automation_APK/xyzvfg-4.2.2-production-release.apk --session-override

appium -a 127.0.0.4 -p 4727 -bp 5003 --pre-launch --device-name Android --udid 0123456789ABCDEF --app-pkg com.******.android --app-activity com.******.android.xyzvfg.app.view.activity.******Activity --platform-name Android --app /home/rajit.s/Desktop/Automation_APK/xyzvfg-4.2.2-production-release.apk --session-override

Desired capabilities are set in script as:
 desired_caps = {}
        cls.driver = webdriver.Remote('http://127.0.0.2:4725/wd/hub', desired_caps)

Note: For each Script same port and ips are used which is mentioned in appium pre-launch command.

Attached is the lof file of the appium server when failed-

[appium_log.txt](https://github.com/appium/appium/files/1121723/appium_log.txt)

My Insight:
I believe the issue is with appium adb which is getting crashed. (not sure, just my suspect)

Thanks,
Rajit

**Comment by mykola-mokhnach** [comment]
Sorry, but we neither support nor test parallel tests on on multiple devices officially in Appium.

**Comment by rajit30** [comment]
But the issue is due to some adb and appium . Can you please have a look. 
For the time being even if we forget about parallel execution, still appium should not fail the script right.

I believe the issue has the same root cause as:
https://github.com/appium/appium/issues/5949

Really appreciate if someone can have a look on the issue

**Comment by mykola-mokhnach** [comment]
For me it does not look like Appium issue at all - there is adb command failure because of unexpected device disconnection. It's very hard to guess what causes the disconnect.

**Comment by rajit30** [comment]
Looks like the issue was due to adb . Hence closing the issue.
