### ISSUE TITLE
Executing "mobile: scroll" gives Unexpected error: Command not implemented

### ISSUE THREAD

**Issue by Exoow** [appium/appium#8778]
## The problem

Following the exact lines of code from the documentation, I'm getting an exception.
See code below.

## Environment

* Appium version (or git revision) that exhibits the issue: **NuGet v3.0.0.2**
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: **Windows 10**
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: **Windows 10**
* Real device or emulator/simulator: **Real device (windows desktop)**
* Appium CLI or Appium.app|exe: **Initialized via C# in Visual Studio, see code below**

## Code To Reproduce Issue [ Good To Have ]

```
// App.Session is a property getting a driver that was created like so:
// new WindowsDriver<WindowsElement>(new Uri(WindowsApplicationDriverUrl), appCapabilities);
Dictionary<string, string> scrollObject = new Dictionary<string, string>();
scrollObject.Add("direction", "down");
((IJavaScriptExecutor)App.Session).ExecuteScript("mobile: scroll", scrollObject);
```
Exception:

```
**OpenQA.Selenium.WebDriverException: Unexpected error. Command not implemented: POST: /session/DA6A0AA9-F399-4DB6-93B2-EBAF2909E858/execute**
Result StackTrace:	
bij OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   bij OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   bij OpenQA.Selenium.Appium.AppiumDriver`1.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   bij OpenQA.Selenium.Remote.RemoteWebDriver.ExecuteScriptCommand(String script, String commandName, Object[] args)
   bij OpenQA.Selenium.Remote.RemoteWebDriver.ExecuteScript(String script, Object[] args)
```

**Comment by mykola-mokhnach** [comment]
This only works for iOS xcuitest driver. For other drivers one must use TouchAction interface

closed as not an issue.
