### ISSUE TITLE
Geo Location dosen't work with genymotion ondemand emulator

### ISSUE THREAD

**Issue by egorvas** [appium/appium#8779]
## The problem

I faced with problem that geolocation not working for genymotion ondemand emulator. More info about this type of emulator can be found here: https://www.genymotion.com/on-demand/
Issue caused because genymotion connected to adb via tcp so adb recognize it as emulator.
In case of emulator appium set geolocation by another way, can be found in file https://github.com/appium/appium-adb/blob/67522746e618fdd41d4491958cbba226332ab2fa/lib/tools/adb-commands.js
method setGeoLocation

But genymotion can't set geolocation by command `emu geo fix 0 0` it needs common way with starting service in appium-settings app.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.6-beta2
* Desktop OS/version used to run Appium: any
* Node.js version (unless using Appium.app|exe): any
* Mobile platform/version under test: android
* Real device or emulator/simulator: genymotion ondemand

## Details

My idea is add something like new capability or setting to ignore check for emulator because in some cases real devices or another types of emulators connected by tcp can be recognized as standard android emulator.

**Comment by mykola-mokhnach** [comment]
This is how Appium detects emulator:

```
  isEmulator () {
    return !!(this.opts.avd || /emulator/.test(this.opts.udid));
  }
```

So you should not set _avd_ capability and there should be no _emulator_ substring in the udid to make it believe we are running on a real device.

**Comment by egorvas** [comment]
@mykola-mokhnach so, this is reason why I wring to you. Ofc I didn't use avd optional.
What about emulator substring, its automatic adb option when any device connected to your pc via tcp adb set it as emulator. In my case I use genymotion instead of native android emulator, but your code acceptable only for native android emulator.

**Comment by mykola-mokhnach** [comment]
@vrunoa FYI

**Comment by vrunoa** [comment]
@mykola-mokhnach i'll try to get a genymotion emulator to check what's going on.

**Comment by imurchie** [comment]
@vrunoa I don't think this is GenyMotion in general, but it on AWS.

**Comment by egorvas** [comment]
@vrunoa @imurchie guys, I contacted support of genymotion and they advised another way to connect AWS instance. This issue can be closed.
BTW for any how will search solution of this problem:

Genymotion ondemand has undocumented possibility to connect emulator: You just need to open 5555 port in your security group on AWS and connect to emulator with command `adb connect IP_OF_YOUR_INSTANCE:5555`
