### ISSUE TITLE
WiFi is not getting ON and OFF in appium 1.6.5 version

### ISSUE THREAD

**Issue by srahul91** [appium/appium#8781]
Hi Guys,
I am also facing the same issue, **WiFi is not getting ON by using driver.setConnection(Connection.WIFI)** function.

**Environment:**
java client 5.0.0-BETA5
**Appium server version: 1.6.5Beta**
Mobile platform/version under test: Android 5.1.1
Real device: Galaxy Note Edge
Appium is running on: Windows7

**Please get the appium logs below:**
https://pastebin.com/RMkZC6Ay

**Comment by mykola-mokhnach** [comment]
Does it disable Wi-Fi if you execute

```
adb shell am broadcast -a io.appium.settings.wifi --es setstatus disable
```

from the command line?

Can you also check what is the version of Appium Settings application installed on the device?

**Comment by srahul91** [comment]
@mykola-mokhnach 
Please get the required information as below:
1. **WiFi didn't disabled after executing below command from command line.**
`adb shell am broadcast -a io.appium.settings.wifi --es setstatus disable`

It is showing like below after executing the above command in command line.
```
C:\Users\srahul>adb shell am broadcast -a io.appium.settings.wifi --es setstatus disable
Broadcasting: Intent { act=io.appium.settings.wifi (has extras) }
Broadcast completed: result=0
C:\Users\srahul>
```
2. **Appium Settings application version is : version 2.1**

Please let me know you need any more information.

**Comment by mykola-mokhnach** [comment]
Are there any errors/exceptions in logcat output after the command above is executed?

**Comment by srahul91** [comment]
Hi @mykola-mokhnach ,
I am unable to analyze the exact errors/exceptions which you are looking for. 
Therefore, I have taken up the logcat output during executing the above mentioned command.

Timestamp: I have executed the command between `07-06 16:43:00 to 07-06 16:43:40`.

Please get the logcat output in below link:
https://pastebin.com/Fg0uvwrk

**Please let me know for any further details.**

**Comment by mykola-mokhnach** [comment]
Unfortunately I don't see any errors, which may help to figure out the reason, in the attached logs. You could get the [source](https://github.com/appium/io.appium.settings) and debug the app on your device under test to find out why wifi state switching does not want to work properly there.
