### ISSUE TITLE
Appium cannot kill all the uiautomator processes, and stop at getting connected devices.

### ISSUE THREAD

**Issue by Dan2712** [appium/appium#8784]
## The problem
I'm trying to run some scripts on appium. Accidentally appium cannot kill all the uiautomator processes when shutting down after one script. The log showed it stopped at "[debug] [UiAutomator] Moving to state 'stopped'", and the next step must get connected devices.

## Environment

* Appium version (or git revision) that exhibits the issue: Appium v1.6.3
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: OS 10.11.6
* Node.js version (unless using Appium.app|exe): v7.5.0
* Mobile platform/version under test: Android 5.1
* Real device or emulator/simulator: Real
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs

https://gist.github.com/Dan2712/702e74a7fa8fb9dec534572878249801.js

**Comment by mykola-mokhnach** [comment]
Link to GIST is broken. Also, it might be the issue has nothing to do with Appium. It's just adb, which stops to interact with the device without any visible reason - I've seen several similar issue reports before.

**Comment by Dan2712** [comment]
Thx for answering! I'm also using the adb to do something intermittently. Maybe it cause conflict？

**Comment by mykola-mokhnach** [comment]
Might be. To know for sure you may stop your test after this issue happens and then try to execute the mentioned adb command manually.
