### ISSUE TITLE
How to use appium-adb

### ISSUE THREAD

**Issue by prudhvialahari** [appium/appium#8787]
## The problem

I have read the documentation provided on https://github.com/appium/appium-adb. I wanted to use Appium-adb in my Java tests, installed it using "npm install appium-adb". I'm not sure how to import and use appium-adb in my Java tests. Help me with the further steps.

## Environment

Appium 1.6.4
Windows 10
Android 7.0

**Comment by mykola-mokhnach** [comment]
appium-adb is just a helper module and it is not possible to use it directly. You need to select one of available drivers: UIAutomation1 or UIAutomation2 or Espresso (beta).

Closed as non issue. Please use Appium forum to ask questions.

**Comment by prudhvialahari** [comment]
Hi Mykola,
I asked about appium-adb here because there was no response to the Appium forum question. Please provide an example for the same.
https://discuss.appium.io/t/how-to-use-appium-adb-java-client/10531

**Comment by imurchie** [comment]
You cannot do it. `appium-adb` is a JavaScript library.

**Comment by prudhvialahari** [comment]
Hi Imurchie,
Thanks for clarifying that about appium-adb. Does Java-client have any such adb support?

**Comment by imurchie** [comment]
The Appium Java client does not have general adb support. Much is exposed through the WebDriver API in Appium. 

What are you trying to do with adb?

**Comment by prudhvialahari** [comment]
I was trying to check whether the keyboard is present on screen or not. Saw that it is supported in appium-adb and I got very much interested in it.

**Comment by imurchie** [comment]
The Java client implements a method `isKeyboardShown` (https://github.com/appium/java-client/blob/master/src/main/java/io/appium/java_client/android/HasDeviceDetails.java#L32) that, eventually, ends in the `appium-adb` method begin called. Only whether it is visible is returned, not whether it is closable.

**Comment by prudhvialahari** [comment]
Thanks, Imurchie I'll try that.
