### ISSUE TITLE
Original error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65

### ISSUE THREAD

**Issue by Arun-AG** [appium/appium#8788]
## The problem

Trying to run sample program in mobile safari browser. program existed with Xcode build failure 65. webdriverrunner.app is trying to installed in mobile but exited with failure.

## Environment

* Appium version (or git revision) that exhibits the issue:1.65
* Last Appium version that did not exhibit the issue (if applicable):NIL
* Desktop OS/version used to run Appium: OS Sierra 10.12.3
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: 10.2.1
* Real device or emulator/simulator:(iPhone 7)
* Appium CLI or Appium.app|exe: Appium.app

## Details

Using python Scripting  to connect mobile safari browser through appium. program gets exited with exit code 65. Installed all relevant package as mentioned by imurchie and provided signing details too(Arunkumar ag (personal team) and code in the file.

## Link to Appium logs

I have enable Xcode log in appiumerver and pasted in the gist.
gist.github link: Arun-AG/exitcode65 and null_ Arun.ag_python

## Code To Reproduce Issue [ Good To Have ] python scripting

```python
import time
from selenium import webdriver
from selenium.webdriver.common.by import By

desired_cap = {'browserName': 'Safari', 'deviceName':'iPhone 7', 'platformName': 'iOS','platformVersion':'10.2',
                "automationName": "XCUITest",'showXcodeLog': True,
               'udid':'d9ddaa496c5f95f9ee02e5c7af65c10ba4b3ebf6','bundleId':'com.apple.mobilesafari'}

class TestApplypage:
    def __init__(self, url, driver):
        self.url = url
        self.driver = driver
        self.driver.get(self.url)

    def home_page(self):
        print "In home page"
        self.getstarted =  self.driver.find_element(By.ID, 'go1')
        self.getstarted.click()

    def close_browser(self):
        self.driver.close()
        print "closed browser"


if __name__ == "__main__":
    url = "https://www.google.co.uk/"
    cmd_exec = 'http://127.0.0.1:4723/wd/hub'
    des_cap = desired_cap
    print des_cap
    driver = webdriver.Remote(command_executor=cmd_exec, desired_capabilities=des_cap)
    test = TestApplypage(url, driver)
    time.sleep(10)
    test.home_page()
```

**Comment by mykola-mokhnach** [comment]
Usually error 65 reflects WDA signing problem and there multiple solved issues reported before about it. Didn't you found a solution in these prior to reporting this one?

**Comment by vikramvi** [comment]
@Arun-AG https://github.com/appium/appium/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20error%2065 , am sure you can find your answer here.

**Comment by swachhab** [comment]
@Arun This is code signing issue, it happens when setup for appium have some problem in configuring webdriver-agent in appium library, you can even configure webdriver-agent with free apple developer account as well, follow these steps in video: https://www.youtube.com/watch?v=dyijACVRQOc It worked for me, hope it will help everybody here!
