### ISSUE TITLE
Cannot launch Chrome Browser in Android Real device using Appium v1.4.16.

### ISSUE THREAD

**Issue by Elangopalakrishnan** [appium/appium#8789]
## The problem
Appium v1.4.16 version has started and adb.exe also in running state, but when i try launch a chrome browser in Android device it is giving exception like - 
"A new session could not be created. (Original error: An operation did not complete before its timeout expired. (Original error: timeout: Adb command timed out after 30 seconds
  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platform=Windows NT 6.1 SP1 x86_64))) (InsecureCertificate)"

## Environment
* Script: C#
* Appium version (or git revision) that exhibits the issue: v1.4.16
* Desktop OS/version used to run Appium: Windows 7 (64bit)
* Node.js version (unless using Appium.app|exe): 3.10.10
* Mobile platform/version under test: Samsung 5/4.4.1
* Real device or emulator/simulator: Real Device

## Details

Exception throws when i try to launch a chrome browser in android real device.  
I used chrome 2.21 and latest 2.30 also, please review the code and help me to fix it.

                                    
## Link to Appium logs

C:\>"C:\Program Files (x86)\Appium\node.exe" "C:\Program Files (x86)\Appium\node
_modules\appium\bin\Appium.js" --address 172.17.224.199 --chromedriver-port 9516
 --bootstrap-port 4725 --device-ready-timeout 120 --selendroid-port 8082 --no-re
set --local-timezone --udid f433970a
info: Welcome to Appium v1.4.16 (REV ae6877eff263066b26328d457bd285c0cc62430d)
info: Appium REST http interface listener started on 172.17.224.199:4723
info: [debug] Non-default server args: {"udid":"f433970a","address":"172.17.224.
199","bootstrapPort":4725,"noReset":true,"localTimezone":true,"androidDeviceRead
yTimeout":"120","selendroidPort":8082,"chromeDriverPort":9516}
info: Console LogLevel: debug
info: --> GET /wd/hub/status {}
info: [debug] Responding to client with success: {"status":0,"value":{"build":{"
version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}}}
info: <-- GET /wd/hub/status 200 9.331 ms - 105 {"status":0,"value":{"build":{"v
ersion":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}}}
info: --> POST /wd/hub/session {"desiredCapabilities":{"acceptInsecureCerts":tru
e,"platformName":"Android","deviceName":"SAMSUNG","device":"Android","platformVe
rsion":"5.0.1","browserName":"Chrome","newcommandtimeout":"120000"},"capabilitie
s":{"firstMatch":[{"acceptInsecureCerts":true,"platformName":"Android","deviceNa
me":"SAMSUNG","device":"Android","platformVersion":"5.0.1","browserName":"Chrome
","newcommandtimeout":"120000"}]}}
info: Client User-Agent string: undefined
info: [debug] The following desired capabilities were provided, but not recogniz
ed by appium. They will be passed on to any other services running on this serve
r. : acceptInsecureCerts, device, newcommandtimeout
info: Set mode: Proxying straight through to Chromedriver
info: [debug] Looks like we want chrome on android
info: [debug] Creating new appium session f49e1e92-8553-4cda-986b-f913f94779be
info: [debug] Checking whether adb is present
info: [debug] Using adb from C:\Automation\android-sdk-windows\platform-tools\ad
b.exe
info: [debug] Using fast reset? false
info: [debug] Preparing device for session
info: [debug] Not checking whether app is present since we are assuming it's alr
eady on the device
info: Retrieving device
info: [debug] Trying to find a connected android device
info: [debug] Getting connected devices...
info: [debug] executing cmd: C:\Automation\android-sdk-windows\platform-tools\ad
b.exe devices
info: [debug] 2 device(s) connected
info: Found device f433970a
info: [debug] Setting device id to f433970a
info: [debug] Waiting for device to be ready and to respond to shell commands (t
imeout = 120)
info: [debug] executing cmd: C:\Automation\android-sdk-windows\platform-tools\ad
b.exe -s f433970a wait-for-device
info: [debug] executing cmd: C:\Automation\android-sdk-windows\platform-tools\ad
b.exe -s f433970a shell "echo 'ready'"
info: [debug] Starting logcat capture
info: [debug] Pushing unlock helper app to device...
info: [debug] executing cmd: C:\Automation\android-sdk-windows\platform-tools\ad
b.exe -s f433970a install "C:\Program Files (x86)\Appium\node_modules\appium\bui
ld\unlock_apk\unlock_apk-debug.apk"
info: [debug] executing cmd: C:\Automation\android-sdk-windows\platform-tools\ad
b.exe -s f433970a shell "dumpsys window"
info: [debug] Screen already unlocked, continuing.
info: [debug] Forwarding system:4725 to device:4724
info: [debug] executing cmd: C:\Automation\android-sdk-windows\platform-tools\ad
b.exe -s f433970a forward tcp:4725 tcp:4724
info: [debug] Pushing appium bootstrap to device...
info: [debug] executing cmd: C:\Automation\android-sdk-windows\platform-tools\ad
b.exe -s f433970a push "C:\\Program Files (x86)\\Appium\\node_modules\\appium\\b
uild\\android_bootstrap\\AppiumBootstrap.jar" /data/local/tmp/
info: Starting App
info: [debug] Attempting to kill all 'uiautomator' processes
info: [debug] Getting all processes with 'uiautomator'
info: [debug] executing cmd: C:\Automation\android-sdk-windows\platform-tools\ad
b.exe -s f433970a shell "ps 'uiautomator'"
info: [debug] No matching processes found
info: [debug] Running bootstrap
info: [debug] spawning: C:\Automation\android-sdk-windows\platform-tools\adb.exe
 -s f433970a shell uiautomator runtest AppiumBootstrap.jar -c io.appium.android.
bootstrap.Bootstrap -e pkg com.android.chrome -e disableAndroidWatchers false
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
info: [debug] [UIAUTOMATOR STDOUT] io.appium.android.bootstrap.Bootstrap:
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRun
ner
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.andro
id.bootstrap.Bootstrap
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 1
info: [debug] [BOOTSTRAP] [debug] Socket opened on port 4724
info: [debug] [BOOTSTRAP] [debug] Appium Socket Server Ready
info: [debug] [BOOTSTRAP] [debug] Loading json...
info: [debug] [BOOTSTRAP] [debug] Registered crash watchers.
info: [debug] Pushing command to appium work queue: ["getDataDir",{}]
info: [debug] [BOOTSTRAP] [debug] Client connected
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action"
:"getDataDir","params":{}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: getDataDir
info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":"\/data\
/local\/tmp"}
info: [debug] dataDir set to: /data/local/tmp
info: Chromedriver: Changed state to 'starting'
info: Chromedriver: Set chromedriver binary as: C:\Program Files (x86)\Appium\no
de_modules\appium\node_modules\appium-chromedriver\chromedriver\win\chromedriver
.exe
info: Chromedriver: Killing any old chromedrivers, running: FOR /F "usebackq tok
ens=5" %a in (`netstat -nao ^| findstr /R /C:"9516 "`) do (FOR /F "usebackq" %b
in (`TASKLIST /FI "PID eq %a" ^| findstr /I chromedriver.exe`) do (IF NOT %b==""
 TASKKILL /F /PID %a))
info: Chromedriver: No old chromedrivers seemed to exist
info: Chromedriver: Spawning chromedriver with: C:\Program Files (x86)\Appium\no
de_modules\appium\node_modules\appium-chromedriver\chromedriver\win\chromedriver
.exe --url-base=wd/hub --port=9516
info: Chromedriver: [STDOUT] Starting ChromeDriver 2.21.371459 (36d3d07f660ff2bc
1bf28a75d1cdabed0983e7c4) on port 9516
Only local connections are allowed.
info: JSONWP Proxy: Proxying [GET /status] to [GET http://127.0.0.1:9516/wd/hub/
status] with no body
info: JSONWP Proxy: Got response with status 200: "{\"sessionId\":\"\",\"status\
":0,\"value\":{\"build\":{\"version\":\"alpha\"},\"os\":{\"arch\":\"x86_64\",\"n
ame\":\"Windows NT\",\"version\":\"6.1 SP1\"}}}"
info: JSONWP Proxy: Proxying [POST /session] to [POST http://127.0.0.1:9516/wd/h
ub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage"
:"com.android.chrome","androidDeviceSerial":"f433970a"}}}
info: JSONWP Proxy: Got response with status 200: {"sessionId":"7307b4d43820554e
e46ca4baeac450ca","status":21,"value":{"message":"timeout: Adb command timed out
 after 30 seconds\n  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf
28a75d1...
info: JSONWP Proxy: Proxying [POST /session] to [POST http://127.0.0.1:9516/wd/h
ub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage"
:"com.android.chrome","androidDeviceSerial":"f433970a"}}}
info: JSONWP Proxy: Got response with status 200: {"sessionId":"7f75e5d1107e28de
28eb6b67b6a48dfc","status":21,"value":{"message":"timeout: Adb command timed out
 after 30 seconds\n  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf
28a75d1...
info: JSONWP Proxy: Proxying [POST /session] to [POST http://127.0.0.1:9516/wd/h
ub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage"
:"com.android.chrome","androidDeviceSerial":"f433970a"}}}
info: JSONWP Proxy: Got response with status 200: {"sessionId":"e082bc66614d0f63
01e210af14deb6c1","status":21,"value":{"message":"timeout: Adb command timed out
 after 30 seconds\n  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf
28a75d1...
info: JSONWP Proxy: Proxying [POST /session] to [POST http://127.0.0.1:9516/wd/h
ub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage"
:"com.android.chrome","androidDeviceSerial":"f433970a"}}}
info: JSONWP Proxy: Got response with status 200: {"sessionId":"c66c6c889e47ca15
1fe88cd35c49d957","status":21,"value":{"message":"timeout: Adb command timed out
 after 30 seconds\n  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf
28a75d1...
error: Chromedriver: Chromedriver exited unexpectedly with code null, signal SIG
TERM
info: Chromedriver: Changed state to 'stopped'
info: Chromedriver stopped unexpectedly on us, shutting down then calling back u
p with the on-die callback
error: Chromedriver: Error: An operation did not complete before its timeout exp
ired. (Original error: timeout: Adb command timed out after 30 seconds
  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7
c4),platform=Windows NT 6.1 SP1 x86_64))
    at JWProxy.command$ (lib/proxy.js:133:15)
    at tryCatch (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\
appium-chromedriver\node_modules\appium-jsonwp-proxy\node_modules\babel-runtime\
regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Program Files (x86)\Ap
pium\node_modules\appium\node_modules\appium-chromedriver\node_modules\appium-js
onwp-proxy\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\P
rogram Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\n
ode_modules\appium-jsonwp-proxy\node_modules\babel-runtime\regenerator\runtime.j
s:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Program Files (x86)\Appium\node_mod
ules\appium\node_modules\appium-chromedriver\node_modules\appium-jsonwp-proxy\no
de_modules\babel-runtime\regenerator\runtime.js:136:37)
    at bound (domain.js:284:14)
    at GeneratorFunctionPrototype.runBound (domain.js:297:12)
    at run (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appiu
m-chromedriver\node_modules\appium-jsonwp-proxy\node_modules\babel-runtime\node_
modules\core-js\library\modules\es6.promise.js:89:39)
    at C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chr
omedriver\node_modules\appium-jsonwp-proxy\node_modules\babel-runtime\node_modul
es\core-js\library\modules\es6.promise.js:100:28
    at flush (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\app
ium-chromedriver\node_modules\appium-jsonwp-proxy\node_modules\babel-runtime\nod
e_modules\core-js\library\modules\$.microtask.js:17:13)
    at process._tickDomainCallback (node.js:381:11)
 { [Error: An operation did not complete before its timeout expired. (Original e
rror: timeout: Adb command timed out after 30 seconds
  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7
c4),platform=Windows NT 6.1 SP1 x86_64))]
  status: 21,
  value: { message: 'timeout: Adb command timed out after 30 seconds\n  (Driver
info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platfo
rm=Windows NT 6.1 SP1 x86_64)' },
  httpCode: 200 }
info: [debug] Cleaning up appium session
error: Failed to start an Appium session, err was: Error: An operation did not c
omplete before its timeout expired. (Original error: timeout: Adb command timed
out after 30 seconds
  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7
c4),platform=Windows NT 6.1 SP1 x86_64))
info: [debug] Error: An operation did not complete before its timeout expired. (
Original error: timeout: Adb command timed out after 30 seconds
  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7
c4),platform=Windows NT 6.1 SP1 x86_64))
    at JWProxy.command$ (lib/proxy.js:133:15)
    at tryCatch (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\
appium-chromedriver\node_modules\appium-jsonwp-proxy\node_modules\babel-runtime\
regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Program Files (x86)\Ap
pium\node_modules\appium\node_modules\appium-chromedriver\node_modules\appium-js
onwp-proxy\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\P
rogram Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\n
ode_modules\appium-jsonwp-proxy\node_modules\babel-runtime\regenerator\runtime.j
s:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Program Files (x86)\Appium\node_mod
ules\appium\node_modules\appium-chromedriver\node_modules\appium-jsonwp-proxy\no
de_modules\babel-runtime\regenerator\runtime.js:136:37)
    at bound (domain.js:284:14)
    at GeneratorFunctionPrototype.runBound (domain.js:297:12)
    at run (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appiu
m-chromedriver\node_modules\appium-jsonwp-proxy\node_modules\babel-runtime\node_
modules\core-js\library\modules\es6.promise.js:89:39)
    at C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chr
omedriver\node_modules\appium-jsonwp-proxy\node_modules\babel-runtime\node_modul
es\core-js\library\modules\es6.promise.js:100:28
    at flush (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\app
ium-chromedriver\node_modules\appium-jsonwp-proxy\node_modules\babel-runtime\nod
e_modules\core-js\library\modules\$.microtask.js:17:13)
    at process._tickDomainCallback (node.js:381:11)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"
A new session could not be created. (Original error: An operation did not comple
te before its timeout expired. (Original error: timeout: Adb command timed out a
fter 30 seconds\n  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28
a75d1cdabed0983e7c4),platform=Windows NT 6.1 SP1 x86_64)))","status":21,"value":
{"message":"timeout: Adb command timed out after 30 seconds\n  (Driver info: chr
omedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platform=Window
s NT 6.1 SP1 x86_64)"},"httpCode":200,"origValue":"An operation did not complete
 before its timeout expired. (Original error: timeout: Adb command timed out aft
er 30 seconds\n  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a7
5d1cdabed0983e7c4),platform=Windows NT 6.1 SP1 x86_64))"},"sessionId":null}
info: <-- POST /wd/hub/session 500 220963.319 ms - 828
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"shutdown"}
info: [debug] [BOOTSTRAP] [debug] Got command of type SHUTDOWN
info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":"OK, shu
tting down"}
info: [debug] [BOOTSTRAP] [debug] Closed client connection
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=.
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRun
ner
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.andro
id.bootstrap.Bootstrap
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 0
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
info: [debug] [UIAUTOMATOR STDOUT] Test results for WatcherResultPrinter=.
info: [debug] [UIAUTOMATOR STDOUT] Time: 217.775
info: [debug] [UIAUTOMATOR STDOUT] OK (1 test)
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: -1
info: [debug] Sent shutdown command, waiting for UiAutomator to stop...
info: [debug] UiAutomator shut down normally
info: [debug] executing cmd: C:\Automation\android-sdk-windows\platform-tools\ad
b.exe -s f433970a shell "am force-stop com.android.chrome"
info: [debug] Stopping logcat capture
info: [debug] Logcat terminated with code null, signal SIGTERM
info: [debug] Cleaning up appium session

## Code To Reproduce Issue [ Good To Have ]
**Launch code:**

                    executeShellCMDInHiddenMode("adb.exe", "start-server");

                    DesiredCapabilities capabilities = new DesiredCapabilities();
                    capabilities.AcceptInsecureCerts = true;
                    capabilities.SetCapability("platformName", "Android");
                    capabilities.SetCapability("deviceName", "SAMSUNG");
                    capabilities.SetCapability("device", "Android");
                    capabilities.SetCapability("platformVersion", "5.0.1");
                    capabilities.SetCapability("browserName", "Chrome");
                    capabilities.SetCapability("newcommandtimeout", "120000");
                    capabilities.SetCapability("appWaitActivity", ".install.TermsOfUseActivity");                    

                    AppDriver = new AndroidDriver<AppiumWebElement>(new Uri("http://" + AppiumIPAddress + ":" + AppiumPort + "/wd/hub"), capabilities, TimeSpan.FromSeconds(300));

Thanks in Advance!
Elango

**Comment by mykola-mokhnach** [comment]
Appium 1.4.16 is old and is not supported. Please try with 1.6.5

**Comment by Elangopalakrishnan** [comment]
@mykola-mokhnach  I have tried to install and use 1.6.5 , but it is giving issue, 
please refer below pic:
![image](https://user-images.githubusercontent.com/26897289/27909369-f1e19900-6215-11e7-8032-82b60182fe2f.png)

And guide me !

Thanks!
Elango

**Comment by mykola-mokhnach** [comment]
Please move the thread to [Appium forum](https://discuss.appium.io). Here we only try to solve server issues.

**Comment by Elangopalakrishnan** [comment]
ok, Thank you :)
