### ISSUE TITLE
How to Update appium version 1.4.16 to 1.6.5 version using node.js cmd

### ISSUE THREAD

**Issue by ShibiKP** [appium/appium#8791]
## The problem
Unable to download the appium 1.6.5 version  "self signed certificate in certificate chain".

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Desktop OS/version used to run Appium: Windows 7 (64 bit)
* Node.js version (unless using Appium.app|exe): 6.11
* Mobile platform/version under test:4.4.1
* Real device or emulator/simulator: Real Devices

## Details

open Node.js command prompt and Entered the npm install -g appium@1.6.5 version in node.js command prompt. It is downloaded the chromedriver.Zip file and it is showing the Error Message as "self signed certificate in certificate chain".

## Link to Appium logs

![image](https://user-images.githubusercontent.com/12896310/27911352-63b33ede-6276-11e7-99fb-5d20fc82fcdf.png)

Thanks,
Shibi Kp

**Comment by mykola-mokhnach** [comment]
This is usually an issue if you are behind a corporate proxy. But it anyway has nothing to do with Appium server- it's a problem with npm and local network configuration.

Closed as non Appium issue.
