### ISSUE TITLE
[BaseDriver] The following capabilities were provided, but are not recognized by  appium: aapPackage, device, aapActivity.

### ISSUE THREAD

**Issue by kapilrana16** [appium/appium#8792]
## The problem
I am new to Appium so i install Drag-sort Demo app from Playstore directly, after that i fetched appActivity and aapPackage. As the app is directly installed in mobile i do not require to set path of APK in code. so when i run the code i got below error.

```
[debug] [AndroidDriver] AndroidDriver version: 1.20.0
[BaseDriver] The following capabilities were provided, but are not recognized by
 appium: aapPackage, device, aapActivity.
[AndroidDriver] Error: The desired capabilities must include either an app, appP
ackage or browserName
```

## Environment

* Appium version : 1.6.5 this i am using from command line.
* Last Appium version that did not exhibit the issue (if applicable): v1.1.0-beta.4 (this is UI version) {This is with UI}
* Desktop OS/version used to run Appium: Window 7 proffesional / 64 bit
* Node.js version (unless using Appium.app|exe):  Node.js 6.11.0 (x64) and npm
* Mobile platform/version under test: 4.2.1
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI

## Link to Appium logs

https://gist.github.com/kapilrana16/f813bf4d94a48feeaecd34d6fbb2c505

## Code To Reproduce Issue [ Good To Have ]

`package com.qa.DragAndDrop;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.TimeUnit;
import org.junit.Test;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;

public class DragandDrop 
{
	WebDriver driver;
	String device = "Android"; 
	String devicename = "0123456789ABCDEF";
	String platformversion = "4.2.1";
	String platformname = "Android";
	
	@Test
	public void getDesireCapabilities() throws MalformedURLException, InterruptedException
	{
		
		//File file = new File("src");
		//File app = new File(file,"BookMyShow-4.2.3.apk");
		
		DesiredCapabilities cap = new DesiredCapabilities();
		cap.setCapability("device", device);
		cap.setCapability("deviceName", devicename);
		cap.setCapability("platformName", platformname);
		cap.setCapability("platformVersion", platformversion);
		cap.setCapability("browserName", "");
		cap.setCapability("aapPackage", "com.mobeta.android.demodslv");
		cap.setCapability("aapActivity", "com.mobeta.android.demodslv.Launcher");
		//cap.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, "100");
		//cap.setCapability(MobileCapabilityType.APP, app.getAbsolutePath()); // get the path from app object and appium will then run it.
		System.out.println("Test1");
		driver = new RemoteWebDriver(new URL("http://0.0.0.0:4723/wd/hub"),cap);
		driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		System.out.println("Test2");
		driver.quit();
		
	}

}

`

**Comment by mykola-mokhnach** [comment]
Change a**a**pPackage , a**a**pActivity to a**p**pPackage , a**p**pActivity

Closed as not an issue. Please use Appium forum for questions

**Comment by kapilrana16** [comment]
Hi @mykola-mokhnach 

I am realy very sorry for waisting your time. i was a sily mistake. 
Thanks

**Comment by Yog352** [comment]
Hi @mykola-mokhnach
am facing the same issue here whenever i am launching an app with appium m getting below error in eclipse error---
Exception in thread "main" org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Error occured while starting App. Original error: 'com.quikr.old.SplashActivity' never started (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 81.17 seconds




and i have written below code



 public static void main (String args[]) throws MalformedURLException, InterruptedException {
      
        //setup appium
        File appDir = new File("D:\\Tools_Selenium\\MobieAutomate\\ApkFolder");
        File app = new File(appDir, "com.quikr.apk"); //my case “demo1.apk”
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability(CapabilityType.BROWSER_NAME, "");
        capabilities.setCapability("platformName", "Android");
        capabilities.setCapability("deviceName", "Samsung");
        capabilities.setCapability("platformVersion","4.4.4");
       
        capabilities.setCapability("app", app.getAbsolutePath());
        capabilities.setCapability("appPackage","com.quikr");  
        capabilities.setCapability("launchActivity ", "old.SplashActivity");  //my case RootActivity
      //  capabilities.setCapability("app-wait-activity", "");
       // capabilities.setCapability("noRest", true);


       // capabilities.setCapability("NO_RESET", "True");
        Thread.sleep(50000);
     
        driver = new AndroidDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
        driver.manage().timeouts().implicitlyWait(80, TimeUnit.SECONDS);
     
    }  

canu plse help me here?
