### ISSUE TITLE
Appium fails installing the app if the URL has appended security information

### ISSUE THREAD

**Issue by claudiosvcc** [appium/appium#8793]
## The problem

If ipa is passed as a URL and it contains information such as a SAS key appended, appium treats it as an app and does not unzips the file.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: OSX
* Node.js version (unless using Appium.app|exe): 8.0.1
* Mobile platform/version under test: ios
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: appium cli

## Details

If on capabilities the app is a https url containing a sas key, it's not unzipped (e.g., https://myhost/myapp.ipa?sv=abc&sr=def). Since, it's treated as an .app, it won't find the plist and ios-deploy will fail, failing the test. The URL is well formed, file is valid, if I give a local path or a public URL it works fine. With the SAS key appended it works fine on Appium 1.4.13 (didn't tested any version in between). 

Tested by setting different content types on the blob storage (such as application/x-itunes-ipa, x-zip-compressed or octet-stream with no different behavior).

## Link to Appium logs

https://gist.github.com/anonymous/c4454d4d649db023786646d5c9e28cc0

## Code To Reproduce Issue

On capabilities, set {app: "https://<HOST>/App.ipa?<whatever>"}

**Comment by imurchie** [comment]
Thanks for reporting this. A fix is in the works.

**Comment by imurchie** [comment]
A fix is in `appium-base-driver@2.10.2`. You can update by re-installing the Appium beta (`npm uninstall -g appium && npm cache clean && npm install -g appium@beta`).
