### ISSUE TITLE
Turn On/Off Location Services for Android

### ISSUE THREAD

**Issue by mojojojo94** [appium/appium#8794]
## The problem

Can we get an enhancement to enable location services (on/off) for Android; just like iOS has capabilities:
locationServicesEnabled: boolean
locationServicesAuthorized: boolean

**Comment by mykola-mokhnach** [comment]
I think it might be only possible to do it on Emulator. Right @vrunoa ?

**Comment by mojojojo94** [comment]
Even just emulator its a great addition.

**Comment by vrunoa** [comment]
@mykola-mokhnach yes 
```bash
adb shell settings put secure location_providers_allowed -gps
adb shell settings put secure location_providers_allowed +gps
```
should turn on/off gps.

Same for network provider,
`adb shell settings put secure location_providers_allowed +network`, but this will require an action to agree on a dialog.

**Comment by mojojojo94** [comment]
I wanted a capability, so its easier to test on saucelab android emulators because they don't come preconfigured with settings like location services off.

**Comment by vrunoa** [comment]
@mojojojo94 @mykola-mokhnach i'm seeing there's an endpoint `'/wd/hub/session/:sessionId/appium/device/toggle_location_services'`
and a _toggleLocationServices_ method
https://github.com/appium/appium-android-driver/blob/ec317fa22a0e2abb396051b78e73124f45dc90ea/lib/commands/network.js#L98
maybe we need to update this method

**Comment by jlipps** [comment]
@vrunoa should we keep this open to track getting those toggles associated with the capabilities mentioned?

**Comment by vrunoa** [comment]
@jlipps the `-gps` option is no longer available for the emulator launch args. We can provide this capability by running the adb command right before launching the app. I'll create a PR for this.

**Comment by vrunoa** [comment]
@mojojojo94 https://github.com/appium/appium-android-driver/pull/254

**Comment by mojojojo94** [comment]
Sweet! Thanks Guys!! 😄

**Comment by mojojojo94** [comment]
Did you guys update the readme file https://github.com/appium/appium-android-driver with how to turn on/off gps location services for Android?

**Comment by vrunoa** [comment]
Not yet, i'll add it later today.

**Comment by vrunoa** [comment]
@mojojojo94 capabilities were added in appium docs. https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/caps.md
