### ISSUE TITLE
"Error: unexpected server response (404)" shows after switch context(webview) in iOS real device

### ISSUE THREAD

**Issue by Logakarti** [appium/appium#8795]
## The problem

"Error: unexpected server response (404)" shows after switch context(webview) while automating the cases in AWS device farm.

## Environment

* Appium version  : 1.6.3
* Desktop OS/version used to run Appium: MAC
* Mobile platform/version under test: 9.3
* Real device : iPhone 5s 

## Link to Appium logs
https://gist.github.com/Logakarti/501c528fee2a8457d69ffa77f25d1c18

## Code To Reproduce Issue [ Good To Have ]

public DesiredCapabilities iOScapabilities() throws MalformedURLException {
        //AWS
        final String URL_STRING = "http://127.0.0.1:4723/wd/hub";
        URL url = new URL ( URL_STRING );
        //Use a empty DesiredCapabilities object
        DesiredCapabilities capabilities = new DesiredCapabilities ( );
        driver = new IOSDriver<MobileElement> ( url, capabilities );
        capabilities.setCapability("newCommandTimeout", "50000");
        driver.manage().timeouts().implicitlyWait(80, TimeUnit.SECONDS );
        try {
            Thread.sleep( 15000 );
        } catch (InterruptedException e) {
            e.printStackTrace ( );
        }
        Set<String> contextNames = driver.getContextHandles();
        for (String contextName : contextNames) {
            System.out.println( contextName );
            if (contextName.contains( "WEBVIEW" )) {
                driver.context( contextName );
                System.out.println( contextName );
                try {
                    Thread.sleep( 15000 );
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
        }
        return capabilities;
    }

Please help anyone to solve this issue.

**Comment by mykola-mokhnach** [comment]
You must update Appium to 1.6.5 and set **startIWDP** capability to true if you want to test webviews on real devices.
Also, it is not recommended to use XCTest on iPhone models older than 6.

Closed as not an issue

**Comment by Logakarti** [comment]
Thanks, @mykola-mokhnach.

Is there need to add "webkitResponseTimeout" capability for my case? Please suggest.

@mykola-mokhnach

**Comment by mykola-mokhnach** [comment]
It's optional

**Comment by Logakarti** [comment]
Still, I get the same exception "Error: unexpected server response (404)".

Used Appium version: 1.6.5
Add and set  the capability "startIWDP" to "true"

**Comment by mykola-mokhnach** [comment]
Please attach the updated appium log

**Comment by mykola-mokhnach** [comment]
Also try with the recent Appium version, which is 1.6.5

**Comment by Logakarti** [comment]
Tried with latest appium v1.6.5, still, the issue occurs. 

Please find the below appium log,

https://gist.github.com/Logakarti/a33a0e4dfbd30a648153d0e2c2b06a0a

**Comment by mykola-mokhnach** [comment]
The startIWDP capability is not set to true in the log above

**Comment by mykola-mokhnach** [comment]
It is also not recommended to pass Appium args via command line - they should be converted into capabilities.

**Comment by Logakarti** [comment]
I used and set "startIWDP" capability in appium setup, but it doesn't show in the appium log. I don't know the reason for it.  I'm not used in any appium args in command line, actually I automate the app cases in AWS device farm

**Comment by Logakarti** [comment]
@mykola-mokhnach: Any solution for this issue?

**Comment by mykola-mokhnach** [comment]
I'd rather contact AWS support. No idea why not all capabilities are passed.

**Comment by Logakarti** [comment]
Thanks @mykola-mokhnach 

Let me know once you resolve this issue.

**Comment by jlipps** [comment]
It sounds like this is not an Appium issue but an AWS issue. I would recommend contacting their support to ask how it is possible to use new versions of Appium which support the `startIWDP` capability; probably this is something AWS needs to turn on and potentially will cause some work on their side.
