### ISSUE TITLE
Automating Mobile Gestures For iOS With WebDriverAgent/XCTest Backend not implemented for dotNetDriver 

### ISSUE THREAD

**Issue by rajfidel** [appium/appium#8797]
## The problem

Using Appium 1.6.5
Automating Mobile Gestures For iOS With WebDriverAgent/XCTest Backend is not working / not implemented using dotNetDriver. (Used reference code as suggested in  https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios-xctest-mobile-gestures.md )
driver.Swipe() and driver.Tap()  (which used to work in Appium 1.6.3) give Unhandled exceptions as well.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Last Appium version that did not exhibit the issue (if applicable): 1.6.3
* Desktop OS/version used to run Appium: macOS Sierra 10.12.5
* Node.js version (unless using Appium.app|exe): 8.1.3
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

Used the below test code

```
using OpenQA.Selenium.Appium.iOS;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium;
using OpenQA.Selenium.Appium.Interfaces;
using OpenQA.Selenium.Appium.MultiTouch;

namespace AppiumDemo
{
    class MainClass
    {
        public static void Main(string[] args)
        {
			DesiredCapabilities capabilities = new DesiredCapabilities();
            capabilities.SetCapability(MobileCapabilityType.PlatformName, "iOS");
			capabilities.SetCapability(MobileCapabilityType.DeviceName, "iPhone");
			capabilities.SetCapability(IOSMobileCapabilityType.BundleId, "com.apple.Preferences");
			capabilities.SetCapability(MobileCapabilityType.Udid, <<hidden>>);
			capabilities.SetCapability(MobileCapabilityType.AutomationName, "xcuitest");
            capabilities.SetCapability("xcodeOrgId", <<hidden>>);
			capabilities.SetCapability("xcodeSigningId", "iPhone Developer");

			AppiumDriver<AppiumWebElement> appDriver = new IOSDriver<AppiumWebElement>(new Uri("http://127.0.0.1:4723/wd/hub"), capabilities, TimeSpan.FromMinutes(5));

            //Scenario 1
            ITouchAction act1 = new TouchAction(appDriver);
            act1.Press(20,500).MoveTo(20,10).Release();
            act1.Perform();

            //Scenario 2
			ITouchAction act2 = new TouchAction(appDriver);
			act2.Press(20, 500).Wait(500).MoveTo(20, 10).Release();
			act2.Perform();

			//Scenario 3
			Dictionary<string, string> swipe = new Dictionary<string, string>();
			swipe.Add("direction", "down");
			((IJavaScriptExecutor)appDriver).ExecuteScript("mobile: swipe", swipe);

            //Scenario 4
            Dictionary<string, string> scrollUsingDrag = new Dictionary<string, string>();
            scrollUsingDrag.Add("duration", "1.0");
			scrollUsingDrag.Add("fromX", "1.0");
			scrollUsingDrag.Add("fromY", "1.0");
			scrollUsingDrag.Add("toX", "1.0");
			scrollUsingDrag.Add("toY", "1.0");
            ((IJavaScriptExecutor)appDriver).ExecuteScript("mobile: dragFromToForDuration", scrollUsingDrag);

            //Scenario 5
			var wifiElement1 = appDriver.FindElement(By.Name("Wi-Fi"));
			Dictionary<string, string> tap = new Dictionary<string, string>();
			tap.Add("element", wifiElement1.Id);
			tap.Add("x", "0");
			tap.Add("y", "0");
			((IJavaScriptExecutor)appDriver).ExecuteScript("mobile: tap", tap);

            //Scenario 6
            var wifiElement2 = appDriver.FindElement(By.Name("Wi-Fi"));
            Dictionary<string, string> tHold = new Dictionary<string, string>();
            tHold.Add("element", wifiElement2.Id);
			tHold.Add("duration", "2.0");
            ((IJavaScriptExecutor)appDriver).ExecuteScript("mobile: touchAndHold", tHold);

            //Scenario 7
            Dictionary<string, string> scroll = new Dictionary<string, string>();
			scroll.Add("direction", "down");
            ((IJavaScriptExecutor)appDriver).ExecuteScript("mobile: scroll", scroll);


        }
    }
}

```
The appium logs for Scenario 1 is given below
https://gist.github.com/rajfidel/22f6f398cbb69fcee4e0cf0b1755ddee

The appium logs for Scenario 2 is given below
https://gist.github.com/rajfidel/1c38b6b2e1ba373fd9c3b82c1f8f4616

The appium logs for Scenario 3 is given below
https://gist.github.com/rajfidel/685f5f7b8c2e888d5aac046dee4b6b03

The appium logs for Scenario 4 is given below
https://gist.github.com/rajfidel/e862da3a56f57329f37e05e17d5ff46e

The appium logs for Scenario 5 is given below
https://gist.github.com/rajfidel/c2da25e73eefcbc818b5f25809df6fba

The appium logs for Scenario 6 is given below
https://gist.github.com/rajfidel/b6407ce4f07909e1fca0ad4fd15bc57f

The appium logs for Scenario 7 is given below
https://gist.github.com/rajfidel/17dfc39f879088796a9ab2eddd28a582

**Comment by mykola-mokhnach** [comment]
Try to uninstall WebDriverAgentRunner manually from the device and restart the test

**Comment by rajfidel** [comment]
Thanks @mykola-mokhnach I had tried this earlier along with some of the other steps suggested in another thread [here](https://github.com/appium/appium/issues/7815#issuecomment-282245440) and for some reason wasnt working. 

Tried this morning again after removing WebDriverAgentRunner manually from the iPhone again and had no luck. 

Removed WebDriverAgentRunner, cleaned the Webdriver project and it then started working !

**Comment by vikramvi** [comment]
@triager please close per last comment
