### ISSUE TITLE
ADB screencap not work after install new Android SDK

### ISSUE THREAD

**Issue by camillake** [appium/appium#8800]
## The problem
execute command "adb exec-out '/system/bin/screencap -p' > test.png" works, but Cannot get screenshot by AppiumDriver.getScreenshot()
## Environment
* Android SDK: 26.0.2
* Appium version (or git revision) that exhibits the issue: 1.6.5
* Last Appium version that did not exhibit the issue (if applicable):1.6.0
* Desktop OS/version used to run Appium: Ubutu 16
* Node.js version (unless using Appium.app|exe): v6.10.0
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Both
* Appium CLI or Appium.app|exe: python 0.24

## Details
error message as below:

Cannot get screenshot data with 'adb exec-out' because of 'Command '/home/user/Software/android-sdk-linux-new/platform-tools/adb exec-out '/system/bin/screencap -p'' exited with code 255'. 

E       selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot get screenshot data because of 'Unable to get file size for '/data/local/tmp/screenshot.png': Unable to parse size from list output: '-rw-rw-r-- shell    shell      134355 2017-07-07 17:41 screenshot.png''

## Link to Appium logs
[log](https://gist.github.com/camillake/e3e2e6377d9874e0919d7cb9184cef5f)

**Comment by mykola-mokhnach** [comment]
@imurchie FYI

**Comment by mykola-mokhnach** [comment]
Can you please try Appium 1.6.6-beta?

**Comment by camillake** [comment]
Is this solved on Appium 1.6.6-beta

**Comment by mykola-mokhnach** [comment]
We did some fixes there - you never know until you try

**Comment by camillake** [comment]
Still not work after upgrade to 1.6.6.-beta

**Comment by mykola-mokhnach** [comment]
Please attach the full log for beta

**Comment by mykola-mokhnach** [comment]
Also it would be interesting to know why adb returns code 255 for screencap.
Do you get the same error code after executing `/home/cloudmosa-qci/Software/android-sdk-linux-new/platform-tools/adb exec-out '/system/bin/screencap -p' > /dev/null; echo $?`

**Comment by imurchie** [comment]
The file size parsing has been updated. Appium beta ought to work now.

**Comment by mykola-mokhnach** [comment]
@camillake Please update to the recent Appium beta (appium-adb version should be 2.23.8 or greater) and let us know if there are still any problems.

**Comment by camillake** [comment]
@mykola-mokhnach It works after I update appium to the latest version, 1.6.6-beta.2. (appium-adb version is 2.23.8)

**Comment by pisarenco92** [comment]
@mykola-mokhnach I still see the problem with appium version 1.6.6-beta.2 and appium-adb version - 2.23.8. I run on GalaxyNote5 (6.0.1) real device.

**Comment by mykola-mokhnach** [comment]
@pisarenco92 It is some issue with adb. Try to figure out why it returns code 255 for that command and what is needed to make it return zero.
