### ISSUE TITLE
Android executeScript("some script") doesn't work

### ISSUE THREAD

**Issue by crazyk2** [appium/appium#8801]
## The problem

Command  `driver.executeScript("some script")` doesn't work.

## Environment

* java client 5.0.0-BETA9
* Appium server version: v1.6.6-beta.2
* UIAutomator2 Driver version:0.3.4 or AndroidDriver (v1.24.0)
* Node.js version: 7.5.0
* Mobile platform/version under test: Android 4.4.2
* Real device or emulator/simulator: HTC Desire 820G dual sim

## Details
In case when UIAutomator2 is used you haven't included 
`['POST', new RegExp('^/session/[^/]+/execute')],`
to [NO_PROXY](https://github.com/appium/appium-uiautomator2-driver/blob/master/lib/driver.js#L30)

and haven't realized `execute` command for example in commands/general.js

In case when  AndroidDriver is used I haven't found realization of command `execute` too (neither BaseDriver nor AndroidDriver). But [error](https://github.com/appium/appium-base-driver/blob/master/lib/basedriver/driver.js#L183) hasn't been thrown too. 

## Link to Appium logs

[UIAutomator2 logs](https://gist.github.com/crazyk2/24dede900535754d79405c5ab209b41b) 

[AndroidDriver (v1.24.0) logs](https://gist.github.com/crazyk2/ce72f660a901ad1165df168eeebe3102)

**Comment by imurchie** [comment]
Even if it is not proxied, it is just going to return "not implemented". The `executeScript` works in a webview.

**Comment by crazyk2** [comment]
I attached logs if it doesn't enough to understand where is the problem (and is there the problem at all?) please tell me.  "not implemented" error is not  In full logs too.

**Comment by jlipps** [comment]
As @imurchie said, `driver.executeScript` will not work for native apps. There's no JavaScript context for scripts to run in on native apps. The method should work, however, if you are in a webview context.
