### ISSUE TITLE
adb devices cannot find the Android Nougat emulator when noReset capability is set to false

### ISSUE THREAD

**Issue by nairouz12** [appium/appium#8804]
## The problem

In my script I've "noReset" set to "false" for some scenarios and this makes adb devices cannot find my emulator anymore.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Desktop OS/version used to run Appium: MAcOS Sierra 10.12.4
* Node.js version (unless using Appium.app|exe): 7.2.1
* Mobile platform/version under test: Android Nougat (7.1.0)
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: CLI

## Details

Before running the script, adb devices could detect my emulator.
Just after running the script, I lost the connection with the emulator and the script failed
This is my capability:
`[caps]
platformName = "Android"
deviceName = "Google Nexus 6 - 7.1.0 - API 25 - 1440x2560"
noReset= false
platformVersion = "7.1"
language = "en"
clearSystemFiles = true
newCommandTimeout = 250`

The issue is not reproduced when noReset=false

## Link to Appium logs
Here below are the logs:
https://gist.github.com/nairouz12/fca5d2f96d77ebf5edc9b88c50e58dbc

**Comment by mykola-mokhnach** [comment]
Please update Appium to 1.6.5
Also, it is recommended to use **avd** capability to provide emulator name.

**Comment by nairouz12** [comment]
@mykola-mokhnach do you mean "avd" instead of "deviceName"?
Is the issue solved in 1.6.5?

**Comment by mykola-mokhnach** [comment]
I would try both

**Comment by nairouz12** [comment]
I updated appium 1.6.5
run the test and I'm getting an error with the avd capability:
`Avd 'Google Nexus 6 - 7.1.0 - API 25 - 1440x2560' is not available. please select your avd name from one of these: '(Nexus_5X_API_25)'`

**Comment by mykola-mokhnach** [comment]
hm, I find the error message quite self-descriptive...

**Comment by nairouz12** [comment]
@mykola-mokhnach indeed loool
I'll to re-execute the tests with the changes that you recommended and let you know if it resolves my issue

**Comment by nairouz12** [comment]
issue not reproduced with appium 1.6.5
