### ISSUE TITLE
How to start the appium 1.6.5 in windows using .bat file with UDID 

### ISSUE THREAD

**Issue by ShibiKP** [appium/appium#8805]
## The problem

When i am starting the appium 1.6.5 using "cd \ 
"C:/Program Files/Appium/node.exe" "C:/Program Files/Appium/node_modules/appium/bin/Appium.js" --address 127.0.0.1 --chromedriver-port 9516 --bootstrap-port 4725 --selendroid-port 8082 --no-reset --local-timezone --udid sr45a5" but it is launched the appium 1.4.16 version only

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Last Appium version that did not exhibit the issue (if applicable): 1.4.16
* Desktop OS/version used to run Appium: Windows 7
* Node.js version (unless using Appium.app|exe): 7.2.0
* Mobile platform/version under test:Android/6.1
* Real device or emulator/simulator: Real devices

## Details

When i am starting the appium 1.6.5 using "cd \ 
"C:/Program Files/Appium/node.exe" "C:/Program Files/Appium/node_modules/appium/bin/Appium.js" --address 127.0.0.1 --chromedriver-port 9516 --bootstrap-port 4725 --selendroid-port 8082 --no-reset --local-timezone --udid sr45a5" but it is launched the appium 1.4.16 version only

 But when i have passing the cmd as "Appium" then it have started the Appium 1.6.5 version

And two node.exe file have been creating in windows processor 

## Link to Appium logs

Launched through .bat file

C:\Automation\LocalExecution>cd \

C:\>"C:/Program Files/Appium/node.exe" "C:/Program Files/Appium/node_modules/app
ium/bin/Appium.js" --address 127.0.0.1 --chromedriver-port 9516 --bootstrap-port
 4725 --selendroid-port 8082 --no-reset --local-timezone
info: Welcome to Appium v1.4.16 (REV ae6877eff263066b26328d457bd285c0cc62430d)
info: Appium REST http interface listener started on 127.0.0.1:4723
info: [debug] Non-default server args: {"address":"127.0.0.1","bootstrapPort":47
25,"noReset":true,"localTimezone":true,"selendroidPort":8082,"chromeDriverPort":
9516}
info: Console LogLevel: debug

launched by CMD 

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\username>appium
[Appium] Welcome to Appium v1.6.5
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[Appium] Received SIGINT - shutting down

**Comment by mykola-mokhnach** [comment]
The most of the commend line arguments have been moved to capabilities after Appium 1.4
Please read the documentation on the particular driver

**Comment by ShibiKP** [comment]
Shall i uninstall the appium 1.4.16 version

**Comment by mykola-mokhnach** [comment]
You can keep it if you want, but it is old and is not supported anymore

**Comment by ShibiKP** [comment]
Thanks MyKola

**Comment by imurchie** [comment]
I don't think you're using the right path to Appium. Is `C:/Program Files/Appium/node_modules/appium/bin/Appium.js` what comes up when you run `where appium`?

**Comment by ShibiKP** [comment]
Hi imurchie,

when executing the appium cmd in CMD prompt it will be execute the below command.
 
 C:\Users\Username>appium
[Appium] Welcome to Appium v1.6.5
[Appium] Appium REST http interface listener started on 0.0.0.0:4723

Thanks !

**Comment by imurchie** [comment]
I understand. I'm trying to ascertain where that `appium` command exists. Which is generally, on windows, gleaned from `where appium`.

**Comment by ShibiKP** [comment]
Just go open Cmd>> type as "appium"
then enter you appium server will start.

**Comment by imurchie** [comment]
Yes. I understand.

But that `appium` command exists somewhere. If you want your batch file to launch Appium with `"C:/Program Files/Appium/node.exe" "<some path>" --address 127.0.0.1 --chromedriver-port 9516 --bootstrap-port
4725 --selendroid-port 8082 --no-reset --local-timezone` you need to figure out where that path is.

**Comment by ShibiKP** [comment]
path as  "C:/Program Files/Appium/node_modules/app
ium/bin/Appium.js"

**Comment by imurchie** [comment]
Clearly it's not, since that starts 1.4.16.

**Comment by ShibiKP** [comment]
Thanks Imurchie 

is there is any other way to start the appium 1.6.5 using .bat file.

**Comment by imurchie** [comment]
That's what I'm trying to ascertain. The output of `where appium` should give you the path to use.

**Comment by ShibiKP** [comment]
This path where i have Started appium.
Some path as:- 
"C:\Program Files\Appium\node_modules\appium\bin\appium.js"

**Comment by ShibiKP** [comment]
Very much thanks for Supporting **_imurchine_** 

Now it have been solved,

C:\Users\username>appium --udid T2334RS23--port 4725 --address 127.0.0.1 --chr
omedriver-port 9516 --bootstrap-port 4725 --selendroid-port 8082  --no-reset --l
ocal-timezone
[Appium] Welcome to Appium v1.6.5
[Appium] Non-default server args:
[Appium]   address: 127.0.0.1
[Appium]   port: 4725
[Appium]   bootstrapPort: 4725
[Appium]   localTimezone: true
[Appium]   selendroidPort: 8082
[Appium]   chromeDriverPort: 9516
[Appium]   udid: HKE675SK
[Appium]   noReset: true
[Appium] Deprecated server args:
[Appium]   -U,--udid => --default-capabilities '{"udid":"HKE675SK"}'
[Appium]   --no-reset => --default-capabilities '{"noReset":true}'
[Appium] Default capabilities, which will be added to each request unless overri
dden by desired capabilities:
[Appium]   udid: 'HKE675SK'
[Appium]   noReset: true
[Appium] Appium REST http interface listener started on 127.0.0.1:4725

Thanks !
