### ISSUE TITLE
1.6.6-beta.2 doesn't find the locators intermittently

### ISSUE THREAD

**Issue by AnuvrathElastica** [appium/appium#8806]
## Environment

* Appium version (or git revision) that exhibits the issue:1.6.6-beta.2
* Last Appium version that did not exhibit the issue (if applicable):1.6.4
* Desktop OS/version used to run Appium: MacOS Sierra 10.12.5
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS 10.3.2
* Real device or emulator/simulator:Real Device
* Appium CLI or Appium.app|exe: Appium CLI

In the attached XML, my tests fails sometimes complaining that it can't find **Email or phone** element, sometime "NEXT" button.. Tests are failing at least 6 out of 10 times because of either of these missing elements. 

The xpath am using is:  //XCUIElementTypeTextField[@name='Email or phone']

[xml.txt](https://github.com/appium/appium/files/1132501/xml.txt)

**Comment by mykola-mokhnach** [comment]
1. Try to replace xpath locator with accessibility id or predicate
2. Try to perform location after switching into webview context
3. It it necessary to have full Appium log attached to the issue report
