### ISSUE TITLE
"socket hang up" error prevents me from running mobile safari on iOS Simulator

### ISSUE THREAD

**Issue by tomykaira** [appium/appium#8807]
## The problem

expected: Simulator opens SafariLauncher then launches safari
actual: Simulator opens SafariLauncher, but safari does not come up, instead, "socket hang up" error is reported.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.6-beta.2
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: macOS Sierra
* Node.js version (unless using Appium.app|exe): v7.4.0
* Mobile platform/version under test: iOS 10.3.1
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: appium CLI

## Link to Appium logs

https://gist.github.com/tomykaira/eb04138e9dc1e4f389d354fe5d0cc913

## Code To Reproduce Issue

```
# python
from selenium import webdriver
import subprocess
import time

appium_url = 'http://127.0.0.1:4723/wd/hub'
capabilities = {
    'automationName': 'XCUITest',
    'browserName': 'Safari',
    'deviceName': 'iPhone Simulator',
    'platformName': 'iOS',
    'platformVersion': '10.3',
    'showXcodeLog': True,
    'fullReset': True,
}

with file('appium.log', 'a') as appium_log:
    appium_process = subprocess.Popen(['/usr/local/bin/appium'], stdout=appium_log, stderr=appium_log)
    time.sleep(5) # wait for appium to start up
    try:
        driver = webdriver.Remote(appium_url, capabilities)
        driver.get('https://google.com')
    finally:
        appium_process.terminate()
        appium_log.flush()
```

**Comment by mykola-mokhnach** [comment]
Try to build and execute /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj project on Simulator manually.
Also, you need to set the device name to some precise value, for example "iPhone 6".

**Comment by tomykaira** [comment]
Sorry, but I have no idea which scheme to run on Simulator.
I ran IntegrationApp, only one that is runnable, but it seems like different from what I am looking for.
<img width="278" alt="screen shot 2017-07-11 at 1 08 56" src="https://user-images.githubusercontent.com/789929/28027842-8a602c7e-65d5-11e7-835b-25b6bb4612ec.png">

**Comment by mykola-mokhnach** [comment]
You should be able to run WebDriverAgentRunner scheme
