### ISSUE TITLE
Hundreds of `tail` process instances for long running test suite

### ISSUE THREAD

**Issue by cosminstirbu** [appium/appium#8808]
## The problem

While running our test suite on iOS, that takes approx. 12-13hrs to run, our CI machine runs into an issue due to too many processes that were created. I've noticed that there are hundreds of `tail` process instances, and this occurs only on iOS, on Android we don't run into this issue.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS 10.12.4
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS 10.3
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe:

## Details

We have a suite of 630 Cucumber scenarios that run in Jenkins, and they take usually approx 12hr to run. We run them on both iOS and Android.

Recently while running the tests on iOS we started to receive this error: `fork: Resource temporarily unavailable` in our CI server terminal.

Looking at the open processes, we noticed there were hundreds of `tail` processes instances. The log flag is set to `error` to Appium so I'm not sure what could cause this. 

The interesting piece is that on Android this issue doesn't reproduce.

I have checked the parent process of all those `tail` instances and it's Appium.

I think the cause of it is that I call `driver.launchApp()` before each test to make the tests independent.

Thank you,
Cosmin

## Link to Appium logs

Log level is set to `error`

**Comment by mykola-mokhnach** [comment]
tail process captures Simulator log. Normally we start capturing logs on driver init/app startup and finish it upon quitting the driver/stopping the app. Which means if you only invoke start/launch, but never call quit then these processes stay in memory

**Comment by cosminstirbu** [comment]
Even with calling `driver.closeApp()` and having the console log

```
[HTTP] --> POST /wd/hub/session/8237a068-a4a7-495e-9cca-385028c3ce53/appium/app/close {}
[debug] [MJSONWP] Calling AppiumDriver.closeApp() with args: ["8237a068-a4a7-495e-9cca-385028c3ce53"]
[debug] [XCUITest] Executing command 'closeApp'
[debug] [JSONWP Proxy] Proxying [DELETE /session/8237a068-a4a7-495e-9cca-385028c3ce53] to [DELETE http://localhost:8100/session/F135876B-DD27-4285-8FC3-2E9C29B128BD] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n\n  },\n  \"sessionId\" : \"BBB4FDA1-F5F8-4187-A039-CDFC7FFB8186\",\n  \"status\" : 0\n}"
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down xcodebuild process (pid 3479)
[XCUITest] xcodebuild exited with code 'null' and signal 'SIGTERM'
[iOS] Successfully closed the '/Users/myuser/Library/Developer/Xcode/DerivedData/MyApp-fvegmdzhpuccgbffkheveaeojjbf/Build/Products/Debug-iphonesimulator/MyApp.app' app.
[debug] [MJSONWP] Responding to client with driver.closeApp() result: null
```

There still are severals instances of `tail` running.

However if I call `driver.quit` and then I recreate the `driver` the issue is fixed. However, quitting the driver and recreating it is significantly more expensive than calling `driver.launchApp`.

I think it would make sense to kill the `tail` process also when calling `closeApp`, since we span a new instance when calling `driver.launchApp` - so we reach some kind of symmetry.

Or not call it at all when `driver.launchApp` is called.

**Comment by mykola-mokhnach** [comment]
> However, quitting the driver and recreating it, or closing the app and relaunching it is significantly more expensive than simply calling driver.launchApp, without calling quit or closeApp.

It should not be if you set `noReset`capability  to _true_. 

> Even with calling driver.closeApp() and having the console log

We'll check it, thanks for the report.

**Comment by cosminstirbu** [comment]
I was actually wrong. Calling `driver.launchApp` or quitting and recreating the the driver takes about the same amount of time - migrating to an approach where I quit the driver and recreate it between each test run works for me.

Thank you for your help!
