### ISSUE TITLE
uiautomator2 element.tag_name not work

### ISSUE THREAD

**Issue by wangtao169447** [appium/appium#8810]
## The problem

When i run testcase on android7 version, sometimes,when i run driver.page_source,will hand up.
so , i changed to use uiautomator2. However, when i use element.tag_name ,it throw exception like this :
`[MJSONWP] Encountered internal error running command: Error: Did not get a valid response object. Object was: {"status":0,"sessionId":"d433ebe9-e91c-4f36-ace7-90cb5d3006ad"}
    at JWProxy.command$ (../../../lib/jsonwp-proxy/proxy.js:165:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
Traceback (most recent call last):
  File "/Users/june/Documents/product/autotest/demo_test/test.py", line 3109, in click_tap_element
    class_name = element.tag_name
  File "/Library/Python/2.7/site-packages/selenium-2.52.0-py2.7.egg/selenium/webdriver/remote/webelement.py", line 66, in tag_name
    return self._execute(Command.GET_ELEMENT_TAG_NAME)['value']
  File "/Library/Python/2.7/site-packages/selenium-2.52.0-py2.7.egg/selenium/webdriver/remote/webelement.py", line 469, in _execute
    return self._parent.execute(command, params)
  File "/Library/Python/2.7/site-packages/selenium-2.52.0-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 201, in execute
    self.error_handler.check_response(response)
  File "build/bdist.macosx-10.11-intel/egg/appium/webdriver/errorhandler.py", line 29, in check_response
    raise wde
WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Did not get a valid response object. Object was: {"status":0,"sessionId":"d433ebe9-e91c-4f36-ace7-90cb5d3006ad"}`

## Environment

* Appium version (or git revision) that exhibits the issue:1.6.5
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:mac os
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:android
* Real device or emulator/simulator:real device
* Appium CLI or Appium.app|exe:cli

thanks for help
@mykola-mokhnach @imurchie

**Comment by mykola-mokhnach** [comment]
Known issue. This is fixed in 1.6.6-beta

**Comment by wangtao169447** [comment]
ok , i update to 1.6.6-beta and have a try.
thanks

**Comment by wangtao169447** [comment]
@mykola-mokhnach 
i update appium to 1.6.6-beta,(npm uninstall -g appium && npm install -g appium@1.6.6-beta --no-shrinkwrap)
and then ,i do then follow things:
adb uninstall io.appium.uiautomator2.server
adb uninstall io.appium.uiautomator2.server.test

however i still meet this kind of exception:
`[MJSONWP] Encountered internal error running command: Error: Did not get a valid response object. Object was: {"status":0,"sessionId":"d433ebe9-e91c-4f36-ace7-90cb5d3006ad"} at JWProxy.command$ (../../../lib/jsonwp-proxy/proxy.js:165:13) at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40) at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22) at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21) at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37) Traceback (most recent call last): File "/Users/june/Documents/product/autotest/demo_test/test.py", line 3109, in click_tap_element class_name = element.tag_name File "/Library/Python/2.7/site-packages/selenium-2.52.0-py2.7.egg/selenium/webdriver/remote/webelement.py", line 66, in tag_name return self._execute(Command.GET_ELEMENT_TAG_NAME)['value'] File "/Library/Python/2.7/site-packages/selenium-2.52.0-py2.7.egg/selenium/webdriver/remote/webelement.py", line 469, in _execute return self._parent.execute(command, params) File "/Library/Python/2.7/site-packages/selenium-2.52.0-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 201, in execute self.error_handler.check_response(response) File "build/bdist.macosx-10.11-intel/egg/appium/webdriver/errorhandler.py", line 29, in check_response raise wde WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Did not get a valid response object. Object was: {"status":0,"sessionId":"d433ebe9-e91c-4f36-ace7-90cb5d3006ad"}`

**Comment by mykola-mokhnach** [comment]
Please double check if the version of appium-uiautomator2-driver is equal or greater to 0.3.4
Also, full Appium log is needed.

**Comment by wangtao169447** [comment]
@mykola-mokhnach 
i have checked my appium-uiautomator2-driver is equal 0.34

  2   "_from": "appium-uiautomator2-driver@0.x",
  3   "_id": "appium-uiautomator2-driver@0.3.4",
  4   "_inBundle": false,

below is full appium log:
https://gist.github.com/wangtao169447/3e42e07ef09263a06dc2415801a19dc1

thanks

**Comment by mykola-mokhnach** [comment]
It looks like there is some wrong assumption inside UIA2 server. I need to check it

**Comment by wangtao169447** [comment]
ok,thanks.
if you fix this bug ,and release a new version ,please let me know.

**Comment by sravanmedarapu** [comment]
published in appium-uiautomator2-driver v0.4.3.

**Comment by wangtao169447** [comment]
@mykola-mokhnach @sravanmedarapu 

i have update my appium-uiautomator2-driver is to 0.43
however i still face exception.

https://gist.github.com/wangtao169447/6503e1e296d9d8c857a11ef6bb3a9693

**Comment by mykola-mokhnach** [comment]
@wangtao169447 Can you also attach adb logcat output?

**Comment by wangtao169447** [comment]
@mykola-mokhnach https://gist.github.com/wangtao169447/573888de5a9b99042a7302d28dbb62d6
thanks

**Comment by mykola-mokhnach** [comment]
Good, I think I know what the problem might be. Created one more PR: https://github.com/appium/appium-uiautomator2-server/pull/66

**Comment by jlipps** [comment]
bug was fixed in that PR, looks like.
