### ISSUE TITLE
Appium v1.1.0-.4beta always install app, although I don't add app path to server capabilities

### ISSUE THREAD

**Issue by Bamivani** [appium/appium#8812]
## The problem

Appium v1.1.0-.4beta always install app

## Environment

* Appium version : 1.1.0-.4 beta
* Last Appium version that did not exhibit the issue (if applicable):
* Mobile platform/version under test: 6.
* Real device or emulator/simulator: real android device
* Appium.app|exe:

**Comment by mykola-mokhnach** [comment]
Please report to https://github.com/appium/appium-desktop/issues
Also, the full Appium log and screenshots are necessary.
