### ISSUE TITLE
Randomly getting - - ms - - from appium server

### ISSUE THREAD

**Issue by anshumanchatterji** [appium/appium#8814]
## The problem

`2017-07-01 10:11:49:851 - info: [HTTP] <-- POST /wd/hub/session/f0959bfd-0901-4613-81e1-584ad58d163f/element/15/value - - ms - -`

I am getting this in the logs randomly, and whenever i get this, the Selenium Hub says `org.openqa.selenium.WebDriverException: Session [f0959bfd-0901-4613-81e1-584ad58d163f] was terminated due to FORWARDING_TO_NODE_FAILED`

I think the HTTP Response Code header is missing in the reply from Appium, due to which Selenium Hub is confused. Whenever this happens, i see a gap of 5000 ms(between the` --> POST` and `<-- POST`). I believe that this is due to the implicit wait timeout(5000 ms in my case), in which the http header is missing.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Last Appium version that did not exhibit the issue (if applicable): 1.6.3
* Mobile platform/version under test: Android/iOS
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs
https://pastebin.com/B4syZHF2

**Comment by jlipps** [comment]
@anshumanchatterji this kind of HTTP log happens when the client disconnects and does not wait for the response. Any reason you can think of why the client would be doing this? Seems like something in between the hub and Appium is getting confused.

**Comment by anshumanchatterji** [comment]
@jlipps Nops, i am not able to deduce this strange behaviour to something particular. Also, this log happens in the Appium Server, and is not related to Selenium HUB. I have also seen this in some of the Android Devices.

It might be possible that whenever the device is not able to respond within 5000 ms, some other thread is responding with this error.

**Comment by jlipps** [comment]
The log happens in the Appium server, but what the log is saying is that the client disconnected. The client disconnecting is not an Appium error. I'm happy to keep this issue open for a while if you think you'll be able to uncover some other evidence that something is going awry in Appium. But from what we can see here, the issue is that the client is (for some unknown reason) no longer waiting on Appium. A timeout is the most likely culprit, either in the client or in the grid.

**Comment by anshumanchatterji** [comment]
Thanks @jlipps  for the insight. I will try to look more into the issue and the timeout configurations in the client and the hub.
