### ISSUE TITLE
Language capability works with Genymotion emulator but not with AVD from Android studio

### ISSUE THREAD

**Issue by nairouz12** [appium/appium#8815]
## The problem

I was using Genymotion emulator and then because of some stability issues I decided to start using AVD from Android Studio. But then I get the issue of the language setting that cannot be set properly using language capability.
This is what I've in my capability file:
`language = "en"`
But, when the AVD is started, the language of AVD takes the default language instead of setting the one from the capability file.
Please note that I didn't face this issue with Genymotion emulator.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: MAcOS Sierra 10.12.4
* Node.js version (unless using Appium.app|exe):7.2.1
* Mobile platform/version under test:Android Nougat (7.1.0)
* Real device or emulator/simulator:emulator
* Appium CLI or Appium.app|exe:CLI

## Link to Appium logs
https://gist.github.com/nairouz12/69273d053633a59ddc6dc7d951d81f5c

**Comment by jlipps** [comment]
Looks like this is setting both language and locale to "en", which is weird. Maybe related to https://github.com/appium/appium/issues/6026? In any case what if you also include the "locale" capability as "en_US"?

**Comment by jlipps** [comment]
closing, no response
