### ISSUE TITLE
Alert is obstructing view

### ISSUE THREAD

**Issue by VenkateshPS** [appium/appium#8816]
## The problem

get below error even when there is no visible alert on App UI
[debug] [JSONWP Proxy] Got response with status 200: {"value":"Alert is obstructing view","sessionId":"71A4B21C-CCBA-4DAB-B4F3-7ECA1C65EC1F","status":26}

## Environment

* 1.6.5 Beta
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: mac book OS sera
* Node.js version (unless using Appium.app|exe):v7.5.0
* Mobile platform/version under test:
* Real device or emulator/simulator:Simulator ios 10
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
This exception happens if you try to interact with an element, which is covered by an alert. The solution is to handle the alert first.

**Comment by VenkateshPS** [comment]
How do I close the Alert if it is not visible?

**Comment by mykola-mokhnach** [comment]
> How do I close the Alert if it is not visible?

I don't know it, looking at the attached Appium log and page source, which is missing in the issue report above.
