### ISSUE TITLE
WDA Retrying to launch app but fails because App not showing in simulator intermittently

### ISSUE THREAD

**Issue by mmurali88** [appium/appium#8818]
## The problem

Automation scripts work fine on for some time during execution but after a couple of tests the appium checks if the app is installed in the simulator, the logs say it's installed and but looks like the app is not installed in the simulator. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Desktop OS/version used to run Appium: OS EL Capitan 10.11.6
* Node.js version (unless using Appium.app|exe): 6.10.2
* Mobile platform/version under test: iOS SDK set to 10.3 XCode set to 8.3.3
* Real device or emulator/simulator: Simulator 10.2
* Appium CLI or Appium.app|exe: CLI launched through appium-java

## Details

Our scripts uninstall the app before every script execution and launch the app using launchApp. We also use noReset - true, fullReset - False. We have a need to reinstall the app before every script. The script works with the provided app file for 10 + scenarios but post that the automation starts breaking because the app is not available in the simulator but the logs say otherwise.

`Capabilities [{app=/Users/devops/jenkins_home/workspace/AQA_Regression_test/GROUP/checkout/PLATFORM/ios/SITE/ZZZ/label/android_smoke/qaautomation/ZZZ.app, networkConnectionEnabled=false, noReset=true, scaleFactor=0.5, recordVideo=true, databaseEnabled=false, deviceName=iPhone 7, fullReset=false, iosInstallPause=8000, platform=MAC, showXcodeLog=true, sendKeyStrategy=grouped, newCommandTimeout=900, platformVersion=10.2, webStorageEnabled=false, locationContextEnabled=false, browserName=, takesScreenshot=true, javascriptEnabled=true, recordScreenshots=true, platformName=iOS, udid=D4ECE422-0044-4BB6-A201-ECE5F7A1579E}]`

## Link to Appium logs

Includes XcodeLog

https://gist.github.com/mmurali88/340f50ea4dcf3d760f2281a265a4e46b

Simulator Log

https://gist.github.com/mmurali88/ffd23651bd4dc329f74dd901c28dcf8c

@mykola-mokhnach Added simulator log for your verification.

**Comment by mykola-mokhnach** [comment]
The log shows that your application under test cannot be executed. Checking Simulator log might provide more information.
Also, it is not recommended to use _launchApp_ to start the session. Simply create a new driver instance and then quit it after the test finishes. Performance-wise it will be the same.

**Comment by crazyk2** [comment]
@mykola-mokhnach 
I've got the same issue. I use such capabilities
```
capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.IOS_XCUI_TEST);
       capabilities.setCapability(MobileCapabilityType.APP, "/Users/user/IdeaProjects/MobileService//Messenger.app";
       capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, MobilePlatform.IOS);    
       capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, device.getVersion());
       capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, ((IOSDevice) device).getName());
       capabilities.setCapability(MobileCapabilityType.UDID, device.getUdid());  
       
       capabilities.setCapability(MobileCapabilityType.NO_RESET, true);
       capabilities.setCapability(MobileCapabilityType.FULL_RESET, false);
       capabilities.setCapability(IOSMobileCapabilityType.USE_NEW_WDA, false);
       
       return capabilities;
```
When I start Simulator via `fbsimctl 444B894A-22EF-4277-91FF-384C0EEE3A93  boot` and run test case at the first time everything is going OK. But when I start the same test case at the second time I catch bunch of errors
[appium_logs_ok_fist_time](https://gist.github.com/crazyk2/958c74c78ef3270b6927b303027e8713)
[appium_logs_fail_second_time](https://gist.github.com/crazyk2/3f580282c7ad2f77aaaa723c46a65684)

[ios_logs_ok_fist_time](https://gist.github.com/crazyk2/9d2efc83ba9a5e8cdc651583de3c9991)
[ios_logs_bad_second_time](https://gist.github.com/crazyk2/b26c3aca0f9b55aef98ae5f3ccec9364)
From `ios_logs_bad_second_time`
`Jul 11 12:56:38 MacBook-Pro-user XCTRunner[45360]: Enqueue Failure: Failed to terminate ru.ncloudtech.messenger:45363 after 60.0s; state is still `Running Active` (3), should be `Not Running` (1) /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 35 1`

**Comment by mykola-mokhnach** [comment]
@crazyk2 I don't see any problems with Appium here. Try to report the issue to https://github.com/facebook/WebDriverAgent/issues

**Comment by crazyk2** [comment]
@mykola-mokhnach Link for related issue https://github.com/facebook/WebDriverAgent/issues/643

**Comment by crazyk2** [comment]
@mykola-mokhnach 

> You can use /wda/healthcheck to check whether it is working properly.

**Comment by saranyaarun24** [comment]
@mykola-mokhnach Attached the requested logs. Do you have some time to look into it ?

**Comment by jlipps** [comment]
Looks like the answer from WDA was "don't kill xcodebuild"
