### ISSUE TITLE
org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 16:57:40' System info: host:  os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_71'

### ISSUE THREAD

**Issue by vladbelo** [appium/appium#8820]
## The problem
I try to run Appium with Android Emulator I get UnreachableBrowser error
## Environment

* Appium version 1.4.16
Eclipse
Selenium 2.5
*Windows 10

**# **## Link to Appium logs****

> info: Installing App
> info: [debug] executing cmd: C:\Users\vovan\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell "mkdir -p /data/local/tmp/"
> info: [debug] Removing any old apks
> info: [debug] executing cmd: C:\Users\vovan\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell "ls /data/local/tmp/*.apk"
> info: [debug] Found an apk we want to keep at /data/local/tmp/c1cfcc3552f5a0b647e5da00b06abaff.apk
> info: [debug] Couldn't find any apks to remove
> info: [debug] Uninstalling com.disney.mdx.wdw.google
> info: [debug] executing cmd: C:\Users\vovan\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell "am force-stop com.disney.mdx.wdw.google"
> info: [debug] executing cmd: C:\Users\vovan\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 uninstall com.disney.mdx.wdw.google
> info: [debug] App was not uninstalled, maybe it wasn't on device?
> info: [debug] executing cmd: C:\Users\vovan\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell "pm install -r /data/local/tmp/c1cfcc3552f5a0b647e5da00b06abaff.apk"
> warn: Installing remote apk failed, going to uninstall and try again
> info: [debug] Removing any old apks
> info: [debug] executing cmd: C:\Users\vovan\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell "ls /data/local/tmp/*.apk"
> info: [debug] executing cmd: C:\Users\vovan\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell rm "/data/local/tmp/c1cfcc3552f5a0b647e5da00b06abaff.apk"
> info: [debug] executing cmd: C:\Users\vovan\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 push "C:\\Users\\vovan\\workspace\\Appiumintro\\AppiumVova\\Appium_Final\\src\\com.disney.mdx.wdw.google.apk" /data/local/tmp/c1cfcc3552f5a0b647e5da00b06abaff.apk
> info: [debug] Attempting to install again for the last time
> info: [debug] executing cmd: C:\Users\vovan\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell "pm install -r /data/local/tmp/c1cfcc3552f5a0b647e5da00b06abaff.apk"
> info: [debug] Stopping logcat capture
> info: [debug] Logcat terminated with code null, signal SIGTERM
> info: [debug] Sent shutdown command, waiting for UiAutomator to stop...
> warn: UiAutomator did not shut down fast enough, calling it gone
> info: [debug] Cleaning up android objects
> info: [debug] Cleaning up appium session
> 

**CODE**

import static org.junit.Assert.*;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import org.junit.Test;

import org.openqa.selenium.remote.DesiredCapabilities;

import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.remote.MobileCapabilityType;
import io.appium.java_client.remote.MobilePlatform;

public class desiredcap {
	
	
	@Test
public void test() throws MalformedURLException {
		File appDir = new File("src");
		File app = new File(appDir, "com.disney.mdx.wdw.google.apk");
		
		DesiredCapabilities cap = new DesiredCapabilities();
		cap.setCapability(MobileCapabilityType.PLATFORM_NAME, MobilePlatform.ANDROID);
		cap.setCapability(MobileCapabilityType.DEVICE_NAME, "Android Emulator");
		cap.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, "25");
		cap.setCapability(MobileCapabilityType.APP, app.getAbsolutePath());
		//cap.setCapability(MobileCapabilityType.APP_PACKAGE, "com.disney.mdx.wdw.google");
		//cap.setCapability(MobileCapabilityType.APP_ACTIVITY, "com.alphabetlabs.deviceinfo.activities.MainActivity");
		
		
		AndroidDriver driver = new AndroidDriver(new URL("http://192.168.1.35:4723/wd/hub"), cap);
}
		
		
		}

**Comment by mykola-mokhnach** [comment]
Appium 1.4 is old and is not supported now. Please try with 1.6.5

**Comment by vladbelo** [comment]
Thanks alot!

**Comment by vladbelo** [comment]
Thanks a lot.
