### ISSUE TITLE
Unable to resolve findElementByAndroidUIAutomator with java client :5.0.0-BETA9 version

### ISSUE THREAD

**Issue by skmvali** [appium/appium#8821]
## The problem

Unable to resolve the method findElementByAndroidUIAutomator with andriod driver object. Instead working fine with "MobileBy.AndroidUIAutomator("")".  is "findElementByAndroidUIAutomator " deprecated with latest version?
## Environment

* Appium Java Client version : 5.0.0-BETA9

## Code To Reproduce Issue 

Working Code 
=========

DesiredCapabilities cap=new DesiredCapabilities();
 cap.setCapability(AndroidMobileCapabilityType.APP_ACTIVITY, "");        
 AppiumDriver<AndroidElement> driver=new AndroidDriver<AndroidElement>(new URL(""), cap);

driver.findElement(MobileBy.AndroidUIAutomator("")).click();

Unresolved code
============

driver.findElementByAndroidUIAutomator(").click()

**Comment by mykola-mokhnach** [comment]
Please report to https://github.com/appium/java-client/issues

Closed as non server-related issue.
