### ISSUE TITLE
Error while starting a new session:

### ISSUE THREAD

**Issue by baxatob** [appium/appium#8822]
## The problem

Error while starting a new session:

**An unknown server-side error occurred while processing the command. Original error: Command 'java -version' exited with code 20**

## Environment

* Appium version: **1.6.5**
* Desktop OS/version used to run Appium: **macOS Sierra 10.12.5**
* Mobile platform/version under test: **Android 5.0**
* Real device or emulator/simulator: **Simulator**
* Appium CLI or Appium.app|exe: **Appium.app**

## Link to Appium logs

https://gist.github.com/baxatob/4a4c9e158827f4b86b2b5059eefd712d

**Comment by mykola-mokhnach** [comment]
Do you have java installed and available in PATH? What is the output of the command above if you execute it from the command line?

**Comment by baxatob** [comment]
Problem solved by recording java version in .bash_profile:

`export JAVA_HOME="$(/usr/libexec/java_home -v 1.8)"`

Thank you!
