### ISSUE TITLE
How to do parallel execution of appium script using docker?

### ISSUE THREAD

**Issue by rajit30** [appium/appium#8823]
## The problem

i am trying to do parallel execution for android in a docker. Can someone suggest how it could be done, since the docker files runs everything sequentially.

**Comment by dpgraham** [comment]
You should ask this question at: https://discuss.appium.io/

One of the users there may have an answer.

**Comment by SrinivasanTarget** [comment]
Here you [go](https://github.com/butomo1989/docker-android/blob/master/docker-compose.yml)
