### ISSUE TITLE
Starting APN page on Android 7.1.2 shows "Access Point Name settings are not available for this user"

### ISSUE THREAD

**Issue by Zenerax** [appium/appium#8824]
## The problem

Opening APN page using Appium test script on Google Pixel/Pixel XL devices with Android 7.1.2 shows "_**Access Point Name settings are not available for this user.**_" when the settings page is opened using adb shell command such as 

- "adb -s <device_serial> am start -a android.settings.APN_SETTING --user 0"
- "adb -s <device_serial> am start -a android.settings.APN_SETTING --user current"

Opening the same  APN page on the same Android 7.1.2 devices manually shows all the APNs list without the same message stated above.

The same Appium test script using the same adb call listed the APNs and allowed user interactions using test automation fine on devices with Android 7.0 and below.   It seems that the introduction of User accounts/profiles caused the different behavior on Android 7.1.2 (and probably 7.1.1 as well).  

How can I have the Appium test open such APN Settings page as the same user on the device without seeing the "_**Access Point Name settings are not available for this user.**_" message?

## Environment

* Appium version (or git revision) that exhibits the issue:  1.6.5
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:  Android 7.1.2
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:  Android 7.1.2
* Real device or emulator/simulator:  Real device.  Pixel, Pixel XL
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

There was no error generated from Appium, but APN page on the Pixel/Pixel XL devices shows the "_**Access Point Name settings are not available for this user.**_" message instead of actual APN lists.

**Comment by jlipps** [comment]
You have two options for opening up an activity (such as the APN page):
1. automate the UI by tapping buttons the way a user would. use this strategy to navigate to the APN page
2. use the `startActivity` method

It sounds like (2) is not working for you. I don't think there's any way we can improve it as we're just using the basic adb commands. If the APN page behaves differently when started by ADB that's not something Appium can fix. So maybe try (1)?

**Comment by Zenerax** [comment]
Thank you!  I just went witj option 1 and it worked ok as a workaround.
