### ISSUE TITLE
[Feature Request] Ability to run a script to parse iOS device logs for each test that is run.

### ISSUE THREAD

**Issue by MattFoley** [appium/appium#8825]
## The problem

I would like the ability to run a bash script (or other language) after each test, which then parses iOS device logs for that test. From what I can tell, this isn't something that's possible. 

## Details

For example, I would like to output an NSLog for each API request made during a given test run (via my App). Then, after each individual test, run a bash script that would then iterate over that log, and parse those specific NSLogs into a file in order to track how many API calls are made per test.

This would let us track over all API usage per UI flow, as well as other performance information. I'm new to Appium, so let me know if I'm completed wrong, and this already exists. Thanks!

**Comment by imurchie** [comment]
You can get the device logs and run whatever script and analysis you'd like. If Appium were to implement this it would almost certainly not meet everyone's criteria.

It would be easy to pull the device logs during your test tear-down, and parse them.

**Comment by jlipps** [comment]
Yes, you can use Appium to retrieve the device logs and perform any kind of analysis on them.
