### ISSUE TITLE
Could not proxy command to remote server, connect ECONNREFUSED after setting text for element

### ISSUE THREAD

**Issue by darina-techery** [appium/appium#8831]
## The problem

Appium test on Android emulator under macOS fails when trying to lookup the field on screen. It occurs right after we find and set text to another element (which causes no crash). 
This issue is constantly reproduced only on 1 workstation in our company.
Please find the link to Appium logs below.

## Environment

* Appium version (or git revision) that exhibits the issue:
```
npm -g list | grep appium
├─┬ appium@1.6.5
│ ├─┬ appium-android-driver@1.24.0
│ │ ├─┬ appium-adb@2.23.8
│ │ ├─┬ appium-android-bootstrap@2.9.1
│ │ │ ├─┬ appium-uiautomator@1.1.1
│ │ ├── appium-android-ime@2.0.0
│ │ ├─┬ appium-chromedriver@2.12.0
│ │ ├── appium-unlock@0.1.1
│ │ ├── io.appium.settings@2.2.1
│ ├─┬ appium-base-driver@2.10.2
│ ├─┬ appium-fake-driver@0.1.11
│ ├─┬ appium-ios-driver@1.25.0
│ │ ├─┬ appium-ios-simulator@1.24.1
│ │ ├─┬ appium-remote-debugger@3.5.0
│ │ ├─┬ appium-xcode@3.3.0
│ ├─┬ appium-mac-driver@1.0.2
│ ├─┬ appium-selendroid-driver@1.6.2
│ ├─┬ appium-support@2.8.2
│ ├─┬ appium-uiautomator2-driver@0.3.4
│ │ ├── appium-uiautomator2-server@0.1.6
│ ├─┬ appium-windows-driver@0.5.0
│ ├─┬ appium-xcuitest-driver@2.37.1
│ ├── appium-youiengine-driver@1.0.13
├─┬ appium-doctor@1.4.2
│ ├─┬ appium-support@2.8.2
│ │ ├─┬ appium-xcode@3.3.0
```

* Last Appium version that did not exhibit the issue (if applicable): 1.6.5 on another workstation
* Desktop OS/version used to run Appium: macOS 10.12
* Node.js version (unless using Appium.app|exe): 3.10.10
* Mobile platform/version under test: Android 6.0, API 23
* Real device or emulator/simulator: AVD emulator for nexus5 
* Appium CLI or Appium.app|exe: java-client

## Details

If we comment out the problematic statement in our code, the test fails with the same error on any next interaction with UI (say, click 'Login' button instead of setting a password), which means it fails after first setText for some reason, no matter what kind of element we are looking up.
I will be glad to provide more details if needed.

## Link to Appium logs

https://gist.github.com/darina-techery/b6c94ea46b5f4f4ce4b64047c84e0f40

## Code To Reproduce Issue [ Good To Have ]

NDA :(

**Comment by mykola-mokhnach** [comment]
This might be an issue in UIAutomation itself. Try UIAutomation2 as the backend.

**Comment by imurchie** [comment]
Looks like `adb` is crashing:
```

17:17:56.902 [main] INFO  (CMDUtils.java:95): Execute >> adb -s emulator-5554 shell dumpsys input_method | grep mInputShown | sed 's/.*mInputShown=\(.*\)/\1/'
--
  | 2017-07-12 17:17:57:013 - [Logcat] Logcat terminated with code 0, signal null
```

**Comment by darina-techery** [comment]
It actually is UiAutomator2, we use it for Android tests.

**Comment by rshmn** [comment]
Hi
Looks like update of ADB to actual version resolves  this issue.
