### ISSUE TITLE
Cannot access HTML elements on iOS device [Timeout]

### ISSUE THREAD

**Issue by SpedsT** [appium/appium#8833]
Note: I'm just starting to work with end-to-end testing so please forgive my noobness. 

## The problem

I am trying to execute end-to-end test using Protractor with Jasmine and Appium on a iOS device on a simple dummy application created with Ionic v1. All what I am trying to make the test do is just click a button located with: `element(by.css('a[icon-on=ion-ios-chatboxes]'))`. 

What I am getting is a timeout but I wasn't able to track down the problem to the root.

> Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.

The interesting part is that on an Android device works without any problem. 

## Environment

* Appium version: v1.6.5
* Last Appium version that did not exhibit the issue: -
* Desktop OS/version used to run Appium: macOS Sierra 10.12.3
* Node.js version (unless using Appium.app|exe): v7.8.0
* Mobile platform/version under test: iOS 10.3.1
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI

## Link to Appium, Protractor and webDriver logs

https://gist.github.com/SpedsT/e16e4ee6093fde873c18467e96392296

**Comment by imurchie** [comment]
Hmm. Seems like we are pulling the wrong URL for async callback. I'm digging a little deeper.

**Comment by j2ali** [comment]
@imurchie 
I am experiencing the same problem.
Which I upgraded appium-ios-driver to v1.26.0 which includes the fix by increasing the version number in appium's package.json.

I still experience the same problem

**Comment by imurchie** [comment]
The `appium-ios-driver` is mixed into the `appium-xcuitest-driver`, so much of its functionality is used for iOS 10+.

Without the logs (posted as a link to a [gist](https://gist.github.com) of the _full_ server logs) it is difficult to tell anything at all.

I would upgrade everything at once, since parts communicate and mixing and matching leads to very difficult-to-debug errors. To upgrade, you can do `npm uninstall -g appium && npm cache clean && npm install -g appium@beta`.

**Comment by j2ali** [comment]
@imurchie I uninstall and install beta 3 using the instructions you provided.

I still receive the timeout error:

```
**************************************************
*                    Failures                    *
**************************************************

1) About You Page Should contain the "Continue" button
  - Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
  - Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
  - Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
```

[Here is the appium log](https://gist.github.com/j2ali/210dc00b91ccb79e032007efeebde278)

**Comment by imurchie** [comment]
What is the script being sent to `execute_script`? Can you try with a minimal one (like sending in `arguments[arguments.length - 1](123);`)?

**Comment by j2ali** [comment]
@imurchie I am unsure how to see what script is being sent to execute_script.
However I have created a barebones angular-cli project. 
Which still give the timeout error
https://github.com/j2ali/protractor-ios-demo

Protractor is already configured to work with appium to run an ios simulator.

Steps:
Clone repo
`npm install`
Start local instance of appium (1.6.6 Beta3 should start on (0.0.0.0:4723) )
Start running test `npm run e2e`

[Here are the logs from above tests](https://gist.github.com/j2ali/8875810c28ea6813081a0ed799c74756)
