### ISSUE TITLE
Not able to inspect elements using Appium Inspector

### ISSUE THREAD

**Issue by lareddy** [appium/appium#8838]
## The problem

I am using Appium inspector to inspect elements of a real iOS device. When I click on Appium inspector it is not launching app and giving error as "Couldn't find Automation Trace Template".
Using Xcode - 8.3.3

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS Sierra - 10.12.5
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:ios 10.3
* Real device or emulator/simulator: iPad Air
* Appium CLI or Appium.app|exe:
XCODE version - 8.3.3
## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

[debug] [iOS] Starting UIAutoClient, and launching Instruments.
[debug] [UIAuto] Instruments socket server started at /var/folders/d0/r2c7bx2d2rn__js6gj11x_k5m309hx/T/instruments_sock

[Xcode] Could not find Automation.tracetemplate in any of the followinglocations /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate,/Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.bundle/Contents/Resources/Automation.tracetemplate

**Comment by mykola-mokhnach** [comment]
You are using outdated inspector, which is not supported anymore. [This inspector](https://github.com/appium/appium-desktop/releases) is the the correct one.
