### ISSUE TITLE
WebDriverAgentRunner won't start on :8100 port but :0

### ISSUE THREAD

**Issue by risinek** [appium/appium#8843]
I am stuck at running webdriveragentrunner. It starts ok, but it says 
`2017-07-13 12:32:30.601 XCTRunner[263:8839] ServerURLHere->http://192.168.1.168:0<-ServerURLHere`

I'm building this with command below
`xcodebuild build-for-testing test-without-building -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=<iphone-id> -configuration Debug -xcconfig Configurations/ProjectSettings.xcconfig`

full log: 
`xcodebuild build-for-testing test-without-building -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=xxxxxxxxxxxxxxx -configuration Debug -xcconfig Configurations/ProjectSettings.xcconfig
Build settings from configuration file 'Configurations/ProjectSettings.xcconfig':
    CLANG_ANALYZER_NONNULL = YES
    CLANG_WARN_ASSIGN_ENUM = YES
    CLANG_WARN_BOOL_CONVERSION = YES
    CLANG_WARN_CONSTANT_CONVERSION = YES
    CLANG_WARN_ENUM_CONVERSION = YES
    CLANG_WARN_INT_CONVERSION = YES
    CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF = YES
    CLANG_WARN_OBJC_REPEATED_USE_OF_WEAK = YES
    CLANG_WARN_SUSPICIOUS_IMPLICIT_CONVERSION = YES
    GCC_PREPROCESSOR_DEFINITIONS = $(inherited)
    GCC_TREAT_WARNINGS_AS_ERRORS = YES
    GCC_WARN_64_TO_32_BIT_CONVERSION = YES
    GCC_WARN_ABOUT_MISSING_FIELD_INITIALIZERS = YES
    GCC_WARN_ABOUT_POINTER_SIGNEDNESS = YES
    GCC_WARN_ALLOW_INCOMPLETE_PROTOCOL = YES
    GCC_WARN_MISSING_PARENTHESES = YES
    GCC_WARN_PEDANTIC = YES
    GCC_WARN_SHADOW = YES
    GCC_WARN_SIGN_COMPARE = YES
    GCC_WARN_UNUSED_PARAMETER = YES
    GCC_WARN_UNUSED_VALUE = YES
    GCC_WARN_UNUSED_VARIABLE = YES
    RUN_CLANG_STATIC_ANALYZER = YES
    WARNING_CFLAGS = $(inherited) -Weverything -Wno-objc-missing-property-synthesis -Wno-unused-macros -Wno-disabled-macro-expansion -Wno-gnu-statement-expression -Wno-language-extension-token -Wno-overriding-method-mismatch -Wno-missing-variable-declarations -Rno-module-build -Wno-auto-import -Wno-objc-interface-ivars -Wno-documentation-unknown-command -Wno-reserved-id-macro -Wno-unused-parameter -Wno-gnu-conditional-omitted-operand -Wno-explicit-ownership-type -Wno-date-time -Wno-cast-align -Wno-cstring-format-directive -Wno-double-promotion -Wno-partial-availability

=== ANALYZE TARGET WebDriverAgentLib OF PROJECT WebDriverAgent WITH CONFIGURATION Debug ===

Check dependencies

=== ANALYZE TARGET IntegrationApp OF PROJECT WebDriverAgent WITH CONFIGURATION Debug ===

Check dependencies
Signing for "IntegrationApp" requires a development team. Select a development team in the project editor.
Code signing is required for product type 'Application' in SDK 'iOS 10.3'

** TEST BUILD FAILED **

The following build commands failed:
	Check dependencies
(1 failure)
2017-07-13 12:39:20.269 xcodebuild[10278:869128]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/richardstehlik/Library/Developer/Xcode/DerivedData/WebDriverAgent-alnssjowicwrrleazhtvqchaompi/Logs/Test/E014F5D6-AE75-4B7B-B210-85B4CA8FDF9F/Session-WebDriverAgentRunner-2017-07-13_123920-poCFIw.log
2017-07-13 12:39:20.269 xcodebuild[10278:868931] [MT] IDETestOperationsObserverDebug: (D8610A44-D7BC-44C5-8A9F-F62C23545DF1) Beginning test session WebDriverAgentRunner-D8610A44-D7BC-44C5-8A9F-F62C23545DF1 at 2017-07-13 12:39:20.269 with Xcode 8E3004b on target <DVTiOSDevice: 0x7ffd11b22ce0> {
		deviceSerialNumber:         F18RX4HZH2XX
		identifier:                 cd007672f6ccda61357dfda6e9be40113877b229
		deviceClass:                iPhone
		deviceName:                 Zuzana's iphone
		deviceIdentifier:           cd007672f6ccda61357dfda6e9be40113877b229
		productVersion:             9.3.5
		buildVersion:               13G36
		deviceSoftwareVersion:      9.3.5 (13G36)
		deviceArchitecture:         arm64
		deviceTotalCapacity:        12732485632
		deviceAvailableCapacity:    9024544768
		deviceIsTransient:          NO
		ignored:                    NO
		deviceIsBusy:               NO
		deviceIsActivated:          YES
		deviceActivationState:      Activated
		isPasscodeLocked:           NO
		deviceType:                 <DVTDeviceType:0x7ffd1161a890 Xcode.DeviceType.iPhone>
		supportedDeviceFamilies:    (
    1
)
		applications:              (null)
		provisioningProfiles:      (null)
		activityProgress:          -2
		activityTitle:
		hasInternalSupport:        NO
		isSupportedOS:             YES
		developerDiskMountError:   (null)
(null)
	bootArgs:                  <unavailable>
		} (9.3.5 (13G36))
MDMCreateDeltaDirectory:1920 calling MDMDirectoryDiff with:
state->old_bundle: /var/folders/0f/s1hx6d994nb2y89bfmym8lsw0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/c50c1f0685ac66e2fe9500024f10047e/cd007672f6ccda61357dfda6e9be40113877b229/WebDriverAgentRunner-Runner.app
state->new_bundle: /Users/richardstehlik/Library/Developer/Xcode/DerivedData/WebDriverAgent-alnssjowicwrrleazhtvqchaompi/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app
state->dst_bundle: /var/folders/0f/s1hx6d994nb2y89bfmym8lsw0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.l5Zesx/WebDriverAgentRunner-Runner.app_sparse.ipa/Payload//WebDriverAgentRunner-Runner.app, binaryDiff flag: FALSE
	dst_ipa: /var/folders/0f/s1hx6d994nb2y89bfmym8lsw0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.l5Zesx/WebDriverAgentRunner-Runner.app_sparse.ipa
__MDMDirectoryDiff_block_invoke.37:1473 calling writeDictToFile with: /var/folders/0f/s1hx6d994nb2y89bfmym8lsw0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.l5Zesx/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist
writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/0f/s1hx6d994nb2y89bfmym8lsw0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.l5Zesx/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist
2017-07-13 12:39:24.688 XCTRunner[271:9980] Running tests...
2017-07-13 12:39:25.550 XCTRunner[271:9980] Continuing to run tests in the background with task ID 1
Test Suite 'All tests' started at 2017-07-13 12:39:26.181
Test Suite 'WebDriverAgentRunner.xctest' started at 2017-07-13 12:39:26.182
Test Suite 'UITestingUITests' started at 2017-07-13 12:39:26.183
Test Case '-[UITestingUITests testRunner]' started.
    t =     0.00s     Start Test at 2017-07-13 12:39:26.184
    t =     0.00s     Set Up
2017-07-13 12:39:26.190 XCTRunner[271:9980] Built at Jul 13 2017 10:30:46
2017-07-13 12:39:26.209 XCTRunner[271:9980] ServerURLHere->http://192.168.1.168:0<-ServerURLHere
`

**Comment by imurchie** [comment]
You are running it manually? Try adding `USE_PORT=8100` to the command line

**Comment by risinek** [comment]
Yes, I was trying to run it manually as I had a problem with signing the webdriveragent to use it on real device with appium inspector.. But now I solved it and it works with appium inspector ok..

The problem was, I was editing wrong WebDriverAgent xcproject.. I didn't realized, that the one, appium is using is inside the appium folder in `lib/appium/node_modules/appium-xcuitest-driver/` ... I had WebDriverAgent installed separately in `lib/node_modules/appium-xcuitest-driver`

So now I'm able to run Appium desktop inspector with appium 1.6.6 beta server..

**Comment by imurchie** [comment]
Cool.
