### ISSUE TITLE
uiautomator2 driver v0.4.0 fails to create session

### ISSUE THREAD

**Issue by NagyRobertt** [appium/appium#8844]
## The problem

Using the latest version of uiautomator2 driver v0.4.0 i fail to start a session. (Gist below)
With v0.3.4 my tests are running fine.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Desktop OS/version used to run Appium: Mac Sierra 10.12.5
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Android 7
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: cli

## Link to Appium logs

https://gist.github.com/NagyRobertt/31ccde4308c951bd9171686ac5deee98

**Comment by mykola-mokhnach** [comment]
What do you see in the terminal after executing 

```
/Users/asa1_smpsdkbuild/Library/Android/sdk/build-tools/25.0.2/aapt dump badging /Users/asa1_smpsdkbuild/.jenkins/aut1-budm33959715a-adr/workspace/AppiumServerDeployer/node_modules/appium-uiautomator2-driver/uiautomator2/appium-uiautomator2-server-v0.1.6.apk
```

command?

**Comment by imurchie** [comment]
I think the published version is messed up. The server doesn't seem to be included or installed. I'm looking into it.

**Comment by NagyRobertt** [comment]
Interesting. The uiautmator2 folder is missing inside the driver when i download 0.4.0

/Users/asa1_smpsdkbuild/Library/Android/sdk/build-tools/25.0.2/aapt dump badging /Users/asa1_smpsdkbuild/.jenkins/aut1-budm33959715a-adr/workspace/AppiumServerDeployer/node_modules/appium-uiautomator2-driver/uiautomator2/appium-uiautomator2-server-v0.1.6.apk
W/asset   (25505): Asset path /Users/asa1_smpsdkbuild/.jenkins/aut1-budm33959715a-adr/workspace/AppiumServerDeployer/node_modules/appium-uiautomator2-driver/uiautomator2/appium-uiautomator2-server-v0.1.6.apk is neither a directory nor file (type=1).
ERROR: dump failed because assets could not be loaded

It is there in 0.3.4

**Comment by imurchie** [comment]
YEs. That's what I'm looking into.

**Comment by imurchie** [comment]
@NagyRobertt Can you try installing again? 0.4.2 ought to work now.

**Comment by NagyRobertt** [comment]
Checked it. Now it is fine.
Thanks.
