### ISSUE TITLE
Appium has freezing while text input

### ISSUE THREAD

**Issue by hepilt** [appium/appium#8846]
## The problem

Sometimes, may be in 1 case of 10, while text has inputing into field, appium can freeze and no action will happen after.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4 - 1.6.6-beta2
* Node.js version (unless using Appium.app|exe): 7.9.0
* Mobile platform/version under test: ios 10.2.1
* Real device or emulator/simulator: real device, iPhone 6+

## Details

Only while text input, i tried to use different capabilities 

## Link to Appium logs

[HTTP] --> POST /wd/hub/session/45751419-64a2-4f0d-ae50-afea2142f9f8/appium/element/4394FB49-BE6D-49B2-8688-F44A0DAF9CD1/value {"id":"4394FB49-BE6D-49B2-8688-F44A0DAF9CD1","value":"123456qW"}
[debug] [MJSONWP] Calling AppiumDriver.setValueImmediate() with args: ["123456qW","4394FB49-BE6D-49B2-8688-F44A0DAF9CD1","45751419-64a2-4f0d-ae50-afea2142f9f8"]
[debug] [XCUITest] Executing command 'setValueImmediate'
[XCUITest] There is currently no way to bypass typing using XCUITest. Setting value through keyboard
[debug] [JSONWP Proxy] Proxying [POST /element/4394FB49-BE6D-49B2-8688-F44A0DAF9CD1/value] to [POST http://localhost:8100/session/9951863E-F68C-4603-A30E-9A0FD4A7ADA2/element/4394FB49-BE6D-49B2-8688-F44A0DAF9CD1/value] with body: {"value":["1","2","3","4","5","6","q","W"]}

---here everything freezing---

[HTTP] <-- POST /wd/hub/session/45751419-64a2-4f0d-ae50-afea2142f9f8/appium/element/4394FB49-BE6D-49B2-8688-F44A0DAF9CD1/value - - ms - -

**Comment by mykola-mokhnach** [comment]
This is [known](https://github.com/facebook/WebDriverAgent/issues/476) XCTest issue 
You may try to play with **maxTypingFrequency** capability value to workaround it
