### ISSUE TITLE
How to open a keyboard in iOS device by using Appium

### ISSUE THREAD

**Issue by Elangopalakrishnan** [appium/appium#8848]
## The problem

Need to open a Keyboard in iOS devices.
I need to enter the value in search text box, I tried webElement.sendKeys("abcd"); but it is not working.
So i tried to enter a value by keyboard.

I opened keyboard manually and executed this code to enter a value.

AppDriver.Keyboard.SendKeys(sValue);
But how to open a keyboard ???

I tried below codes,

1. webElement.click(); and

2. AppWebElement = AppDriver.FindElement(By.XPath("//*@id='mkmersNavbar']/div[2]/form/div/input"));
                Actions builder = new Actions(AppDriver);
                AppWebElement.Click();
                builder.Click(AppWebElement);
                builder.DoubleClick(AppWebElement);

3.               AppWebElement = AppDriver.FindElement(By.XPath("//*@id='mkmersNavbar']/div[2]/form/div/input"));
               Dictionary<string, string> tfTap = new Dictionary<string, string>();
               tfTap.Add("element", string.Format("{0:X}", AppWebElement));
               ((IJavaScriptExecutor).AppDriver).ExecuteScript("mobile: twoFingerTap", tfTap);
               AppWebElement.Click();
4.
IWebElement element = AppDriver.FindElement(By.XPath("//*[@id='mkmersNavbar']/div[2]/form/div/input"));
               Point point = element.Location;
               int a = point.X;
               int b = point.Y;
               Dictionary<String, Double> coords = new Dictionary<string, double>();
               coords.Add("x", a);
               coords.Add("y", b);
               AppDriver.ExecuteScript("mobile: tap", coords);

5.  new TouchActions(AppDriver).SingleTap(webElement).Perform();

Above all is not working, it is not tapping on text box and not opening keyboard.

In c#, There is no method to open keyboard.

Is there any way to open a keyboard???

## Environment

* Appium version (or git revision) that exhibits the issue:1.6.6 beta2
* Mobile platform/version under test:iOS 10.2.1
* Real device or emulator/simulator: Real device
* Script: c#

Thanks!
Elango

**Comment by mykola-mokhnach** [comment]
There is no separate method to open keyboard - it only open when an element with input focus is activated. Regarding how you activate it - try to do perform the click in native context.

**Comment by chandra306** [comment]
Hi elan,

Did you find a solutions for this? If yes, can you please share how you resolved this issue.

**Comment by go-green** [comment]
I am having the same issue? Any solution?

**Comment by henrydzung** [comment]
For me, I was having the same issue when testing on Safari/iPad real device. Then I added `'appium:nativeWebTap': true` capability and the keyboard is opened again when typing.

**Comment by rajann44** [comment]
@henrydzung Thanks its working, using the capability mentioned by you above.

**Comment by HarryZHX** [comment]
@henrydzung, hi when you used 'appium:nativeWebTap': true, did you test it in browserstack? or Appium's own real device? Thank you

**Comment by henrydzung** [comment]
@HarryZHX I tested with Appium on real device locally.
