### ISSUE TITLE
Not able to run Appium on Android Nougat 

### ISSUE THREAD

**Issue by bbaitikova** [appium/appium#8851]
## The problem
I am running my test using real devices. Android 6 and 5 work fine. But Android 7.x does not work. I am using latest version of Appium, which should support Android Nougat. 

## Environment

Appium version (or git revision) that exhibits the issue: 1.6.5 and desktop : Version 1.1.0-beta.4 (1.1.0-beta.4)
Last Appium version that did not exhibit the issue (if applicable): 1.5.3
Desktop OS/version used to run Appium: 1.5.3
Node.js version (unless using Appium.app|exe): v8.1.0
Mobile platform/version under test: Android 7.1
Real device or emulator/simulator: nexus 6, samsung s7 - real devices
Appium CLI or Appium.app|exe: v1.6.5
Mac: 10.12.5
Android: Samsung s7 and Pixel 6, OS 7.1.2
Programming language: Python

## Details

Appium does not running test on Android OS 7.1.2. I have tried to use different devices (Samsung, Pixel, Tango), nu luck. 

Error from PyCharm: WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Unable to find an active device or emulator with OS 7.1.2
. The following are available: HT7540207064 (7.1.2)

My setup page is correct, since test works on Marshmallow and Lollipop android version. 

## Link to Appium logs

https://gist.github.com/bbaitikova/26ee4bdfe930e9b85213ba7fc8fa2fae

**Comment by imurchie** [comment]
Can you post a gist of the _full_ logs? So I can see the configuration?

**Comment by bbaitikova** [comment]
Updated gist with full logs

**Comment by imurchie** [comment]
For now, can you take the newline out of the `platformVersion`, and try again?

**Comment by bbaitikova** [comment]
OMG, it is working!!!!! Thank you so much.

**Comment by imurchie** [comment]
Cool! I'm opening a PR to trim the platformVersion, but it is better to not send newlines at all!
