### ISSUE TITLE
"RoutingHTTPServer: code signing blocked mmap()" error crashing WebDriverAgent on startup

### ISSUE THREAD

**Issue by codedgeass** [appium/appium#8854]
## The problem

WebDriverAgent immediately crashes after starting due to an issue using RoutingHTTPServer.

## Environment

* Appium version (or git revision) that exhibits the issue: **1.6.5**
* Desktop OS/version used to run Appium: **Mac 10.12.5**
* Node.js version (unless using Appium.app|exe): **8.1.4**
* Mobile platform/version under test: **iOS** **10.3.1**
* Real device or emulator/simulator: **Real**
* Appium CLI or Appium.app|exe: **CLI**

## Details

I have gone through the steps of using Xcode to sign and build WebDriverAgent. Yet, the app is still crashing due to a 

> code signing blocked mmap() 

error. Am I missing a code sign? I'm able to build all the targets of WebDriverAgent on Xcode.

## Link to Appium logs

https://gist.github.com/codedgeass/0183f06df685f829a8dfd0fed80b03b1

**Comment by codedgeass** [comment]
Passing xcodeOrgId and xcodeSigningId into my capabilities prevented the signing error from occuring. Should this be closed? I'm fairly confident I performed the manually provisioning correctly.

**Comment by mykola-mokhnach** [comment]
Yes this a problem with code signing. WDA was not able to be installed on the device since it is not properly signed. Closed as duplicate.
