### ISSUE TITLE
iOS 11 Device : 200 Response with Exception while trying to find elements. ( Working on different machine with same appium version and Xcode beta 9 )

### ISSUE THREAD

**Issue by SatishKumarKV** [appium/appium#8857]
## The problem

iOS 11 Device : 200 Response with Exception while trying to find elements.
**Tried with latest code from GIT**

`[HTTP] --> POST /wd/hub/session/329807f3-d0bf-4868-a453-08bd85131eff/elements {"using":"xpath","value":"//*[contains(@name,'MaaS')]"}
[debug] [MJSONWP] Calling AppiumDriver.findElements() with args: ["xpath","//*[contains(@name,'MaaS')]","329807f3-d0bf-4868-a453-08bd85131eff"]
[debug] [XCUITest] Executing command 'findElements'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 10000 ms for condition
[debug] [XCUITest] Setting custom timeout to 600000 ms for "findElements" command
[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8338/session/01C11059-D64C-4C0A-BCC1-CE1EB7C66A5D/elements] with body: {"using":"xpath","value":"//*[contains(@name,'MaaS')]"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":[{"ELEMENT":"DD56E102-8522-44CC-8F1F-11380BB7C57E","type":"XCUIElementTypeButton","label":null}],"sessionId":"01C11059-D64C-4C0A-BCC1-CE1EB7C66A5D","status":0}
[debug] [MJSONWP] Responding to client with driver.findElements() result: [{"ELEMENT":"DD56E102-8522-44CC-8F1F-11380BB7C57E","type":"XCUIElementTypeButton","label":null}]
[HTTP] <-- POST /wd/hub/session/329807f3-d0bf-4868-a453-08bd85131eff/elements 200 1488 ms - 168 

Total elements found on screen : 1
[HTTP] --> GET /wd/hub/session/329807f3-d0bf-4868-a453-08bd85131eff/element/DD56E102-8522-44CC-8F1F-11380BB7C57E/displayed {}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [XCUITest] Executing command 'proxyReqRes'
[debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/329807f3-d0bf-4868-a453-08bd85131eff/element/DD56E102-8522-44CC-8F1F-11380BB7C57E/displayed] to [GET http://localhost:8338/session/01C11059-D64C-4C0A-BCC1-CE1EB7C66A5D/element/DD56E102-8522-44CC-8F1F-11380BB7C57E/displayed] with body: {}
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : false,\n  \"sessionId\" : \"01C11059-D64C-4C0A-BCC1-CE1EB7C66A5D\",\n  \"status\" : 0\n}"
[JSONWP Proxy] Replacing sessionId 01C11059-D64C-4C0A-BCC1-CE1EB7C66A5D with 329807f3-d0bf-4868-a453-08bd85131eff
[HTTP] <-- GET /wd/hub/session/329807f3-d0bf-4868-a453-08bd85131eff/element/DD56E102-8522-44CC-8F1F-11380BB7C57E/displayed 200 238 ms - 77 
[HTTP] --> GET /wd/hub/session/329807f3-d0bf-4868-a453-08bd85131eff/element/DD56E102-8522-44CC-8F1F-11380BB7C57E/text {}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [XCUITest] Executing command 'proxyReqRes'
[debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/329807f3-d0bf-4868-a453-08bd85131eff/element/DD56E102-8522-44CC-8F1F-11380BB7C57E/text] to [GET http://localhost:8338/session/01C11059-D64C-4C0A-BCC1-CE1EB7C66A5D/element/DD56E102-8522-44CC-8F1F-11380BB7C57E/text] with body: {}
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : null,\n  \"sessionId\" : \"01C11059-D64C-4C0A-BCC1-CE1EB7C66A5D\",\n  \"status\" : 0\n}"
[JSONWP Proxy] Replacing sessionId 01C11059-D64C-4C0A-BCC1-CE1EB7C66A5D with 329807f3-d0bf-4868-a453-08bd85131eff
[HTTP] <-- GET /wd/hub/session/329807f3-d0bf-4868-a453-08bd85131eff/element/DD56E102-8522-44CC-8F1F-11380BB7C57E/text 200 264 ms - 76 
Returning found element : null
[HTTP] --> GET /wd/hub/session/329807f3-d0bf-4868-a453-08bd85131eff/element/DD56E102-8522-44CC-8F1F-11380BB7C57E/displayed {}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [XCUITest] Executing command 'proxyReqRes'
[debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/329807f3-d0bf-4868-a453-08bd85131eff/element/DD56E102-8522-44CC-8F1F-11380BB7C57E/displayed] to [GET http://localhost:8338/session/01C11059-D64C-4C0A-BCC1-CE1EB7C66A5D/element/DD56E102-8522-44CC-8F1F-11380BB7C57E/displayed] with body: {}
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : false,\n  \"sessionId\" : \"01C11059-D64C-4C0A-BCC1-CE1EB7C66A5D\",\n  \"status\" : 0\n}"
[JSONWP Proxy] Replacing sessionId 01C11059-D64C-4C0A-BCC1-CE1EB7C66A5D with 329807f3-d0bf-4868-a453-08bd85131eff
[HTTP] <-- GET /wd/hub/session/329807f3-d0bf-4868-a453-08bd85131eff/element/DD56E102-8522-44CC-8F1F-11380BB7C57E/displayed 200 231 ms - 77 
[HTTP] --> GET /wd/hub/session/329807f3-d0bf-4868-a453-08bd85131eff/element/DD56E102-8522-44CC-8F1F-11380BB7C57E/location {}
[debug] [MJSONWP] Calling AppiumDriver.getLocation() with args: ["DD56E102-8522-44CC-8F1F-11380BB7C57E","329807f3-d0bf-4868-a453-08bd85131eff"]
[debug] [XCUITest] Executing command 'getLocation'
[debug] [XCUITest] Setting custom timeout to 600000 ms for "getElementRect" command
[debug] [JSONWP Proxy] Proxying [GET /element/DD56E102-8522-44CC-8F1F-11380BB7C57E/rect] to [GET http://localhost:8338/session/01C11059-D64C-4C0A-BCC1-CE1EB7C66A5D/element/DD56E102-8522-44CC-8F1F-11380BB7C57E/rect] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"Invalid number value (infinite) in JSON write\\n\\n(\\n\\t0   CoreFoundation                      0x00000001859b7e70 <redacted> + 148\\n\\t1   libobjc.A.dylib                     0x0000000184ec8528 objc_exception_throw + 56\\n\\t2   CoreFoundation                      0x00000001859b7da0 <redacted> + 0\\n\\t3   Foundation                          0x00000001864263fc <redacted> + 408\\n\\t4   Foundation                          0x0000000186424f44 <redacted> + 520\\n\\t5   Foundation                          0x00000001864272bc <redacted> + 192\\n\\t6   CoreFoundation                      0x00000001858ddb9c <redacted> + 168\\n\\t7   Foundation                          0x0000000186426884 <redacted> + 388\\n\\t8   Foundation                          0x00000001864272bc <redacted> + 192\\n\\t9   CoreFoundation                      0x00000001858ddb9c <redacted> + 168\\n\\t10  Foundation                          0x0000000186426884 <redacted> + 388\\n\\t11  Foundation                          0x000...
[HTTP] <-- GET /wd/hub/session/329807f3-d0bf-4868-a453-08bd85131eff/element/DD56E102-8522-44CC-8F1F-11380BB7C57E/location 500 246 ms - 6075 `

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Last Appium version that did not exhibit the issue (if applicable): 1.6.5
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by imurchie** [comment]
Xcode 9/iOS 11 support is still being worked on.
