### ISSUE TITLE
shouldWaitForQuiescence capability

### ISSUE THREAD

**Issue by GEvanscsumb** [appium/appium#8858]
## The problem

I'm testing an ios app through appium that was sent to me by the developers through an ipa file. Through my research, it seems that this is the capability that will wait for the app to idle before performing touch gestures. The pages I want to use the drag gesture on seem to have animations, thus the time it takes to perform the gesture itself clocks in at about 5 minutes. I've noticed this after the WDA session is created successfully:

> {"desiredCapabilities":{"bundleId":"com.testapp.webdriverrun","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}

Is there a way to set the value to false? I was reading the docs in WDA which said that it's set to NO by default, but I'm not sure where its value is changing. I've also tried explicitly setting the capability to false but it's not recognized.

> The following capabilities were provided, but are not recognized by appium: shouldWaitForQuiescence.

I posted this on the WDA github as well [https://github.com/facebook/WebDriverAgent/issues/644](url) but I was directed here. 

## Environment

* Desktop OS/version used to run Appium: Sierra 10.12.5
* Node.js version (unless using Appium.app|exe): Appium 1.6.5
* Mobile platform/version under test: ios 10.0.1
* Real device or emulator/simulator: Real Device

**Comment by imurchie** [comment]
Yes. There is a capability `waitForQuiescence` which gets passed along.
