### ISSUE TITLE
Tap function does not work on Tango Lenovo device. 

### ISSUE THREAD

**Issue by bbaitikova** [appium/appium#8859]
## The problem

I want to perform Tap function (tap on button by coordinates), but Tap does not work properly. I have checked the button coordinates 10 times. Same test with same app works on Nexus and Samsung devices. Only on Tango it does not work.  

Appium version (or git revision) that exhibits the issue: 1.6.5 and desktop : Version 1.1.0-beta.4 (1.1.0-beta.4)
Last Appium version that did not exhibit the issue (if applicable): 1.5.3
Desktop OS/version used to run Appium: 1.5.3
Node.js version (unless using Appium.app|exe): v8.1.0
Mobile platform/version under test: Android 7.1
Real device or emulator/simulator:Real device - Tango lenovo 
Appium CLI or Appium.app|exe: v1.6.5
Mac: 10.12.5
Android: Tango Lenovo  OS 6.0.1
Programming language: Python

## Details
I am running test in Pycharm and console is displaying Test pass, but UI on actual device has never pass. Button was never clicked. 

## Link to Appium logs

Logs: <script src="https://gist.github.com/bbaitikova/42f759617762bbf0732322a4ec7173a7.js"></script>

position = []
position.append((720, 2215))

        self.driver.tap(position)
        print "click start button"

Console is printing the "click start button".

**Comment by mykola-mokhnach** [comment]
driver.tap is deprecated. Try TouchAction interface

**Comment by bbaitikova** [comment]
I updated script, but it does not perform the press or tap. Logs and test result are pass. But real device UI does not display expected result. 

el = self.driver.find_element(*self.page)
action = TouchAction(self.driver)
action.tap(el, 720, 2195, 1).perform()

**Comment by bbaitikova** [comment]
el = self.driver.find_element(*self.page)
action = TouchAction(self.driver)
action.tap(el, 720, 2195, 1).release().perform()

i added release() and same issue. does not work

**Comment by bbaitikova** [comment]
and it stopped working on other my devices.

**Comment by dpgraham** [comment]
@bbaitikova Have you tried using a locator to find the button and then perform a click on it instead?

Also, if you have a chance, can you try testing opening your tests in Appium Desktop? Appium Desktop provides details about the elements on the right panel. I'd like to see what the attributes of the button are.

**Comment by bbaitikova** [comment]
I'd love to use elements locators, but I am testing App, developed in unity
and Appium inspector dies not display any locators: Id, class, text etc. it
highlights only the page full view. That's why I am using coordinates. It's
only one solution for me.

**Comment by dpgraham** [comment]
How are you able to determine the coordinates of the button?

**Comment by bbaitikova** [comment]
I have used UIAutomate viewer and also calculate button position using
screen size (height and width) and button dimension from Unity asset.

**Comment by bbaitikova** [comment]
Do you have any idea why same test does not work on Tango device? XY
coordinate positions of button are exactly same as Samsung has.

**Comment by dpgraham** [comment]
Not sure why, but I do know that using absolute coordinates isn't always reliable. I don't know why it doesn't work on the Lenovo device.

Are you sure you can't use locators though? Could you try outputting the page source (in Python I think it's `self.driver.source`) before you do the click and have a look at the XML to see if you can locate the button via XPath.
