### ISSUE TITLE
No command-timeout option

### ISSUE THREAD

**Issue by cool-firer** [appium/appium#8866]
## The problem

Appium 1.6.4 
`const deprecatedArgs = [
  [['--command-timeout'], {
    defaultValue: 60,
    dest: 'defaultCommandTimeout',
    type: 'int',
    required: false,
    help: '[DEPRECATED] No effect. This used to be the default command ' +
          'timeout for the server to use for all sessions (in seconds and ' +
          'should be less than 2147483). Use newCommandTimeout cap instead'
  }],`
but there is no newCommandTimeout  option

**Comment by amedvedjev** [comment]
it is in capability :-)
```
capabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, "120");
```
