### ISSUE TITLE
Click option is not working in Appium program

### ISSUE THREAD

**Issue by zilongo** [appium/appium#8867]
## The problem

I config AndroidDriver and get elemt by id, perform click method，but android device no effect。

## Environment

* Appium version ：Version: 1.1.0-beta.4
* Desktop OS/version used to run Appium: window 10 
* Node.js version (unless using Appium.app|exe): 8.1
* Mobile platform/version under test: Android 7.1.1
* Real device or emulator/simulator:Real device
* Appium CLI or Appium.app|exe:Appium.exe

## Details

Click option is not working in Appium program

## Link to Appium logs

https://gist.github.com/zilongo/6228f378a8cfc249465402290dd5c7a9

## Code To Reproduce Issue [ Good To Have ]

``` java 
	public static void main(String[] args) throws InterruptedException {
		DesiredCapabilities caps = new DesiredCapabilities();
		caps.setCapability(CapabilityType.BROWSER_NAME, ""); 
		caps.setCapability("deviceName", "dcf581ed");
		//caps.setCapability("udid", "dcf581ed"); //Give Device ID of your mobile phone
		caps.setCapability("platformName", "Android");
		caps.setCapability("platformVersion", "7.1.1");
		caps.setCapability("appPackage", "com.miui.calculator");
		caps.setCapability("appActivity", "com.miui.calculator.cal.NormalCalculatorActivity");
		caps.setCapability("noReset", "true");
		caps.setCapability("simpleIsVisibleCheck", false);
		caps.setCapability("sessionOverride", true);
		//name=com.miui.calculator/com.miui.calculator.cal.NormalCalculatorActivity
		//Instantiate Appium Driver		
		try {
			AndroidDriver<AndroidElement> driver = new AndroidDriver<AndroidElement>(new URL("http://127.0.0.1:4723/wd/hub"), caps);
			 driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS); 

			 MobileElement e = (MobileElement)driver.findElementById("com.miui.calculator:id/btn_1");
			 e.click();
		} catch (MalformedURLException e) {
			System.out.println(e.getMessage());
		}
	}
```

**Comment by mykola-mokhnach** [comment]
There are no errors in the log. Either try to click by absolute control coordinates or try UIAutomation2 as the backend.

**Comment by zilongo** [comment]
@mykola-mokhnach Tank you and add "caps.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.ANDROID_UIAUTOMATOR2);" ,fix my problem
