### ISSUE TITLE
Encountered internal error running command: Error: Error occured while starting App. Original error: com.company.organization.controller.activities.Activity or com.company.organization.controller.COM.COMPANY.ORGANIZATION.CONTROLLER.activities.Activitry never started

### ISSUE THREAD

**Issue by danigol** [appium/appium#8868]
## The problem
Emphasis added in title and package name generalized. 

When trying to run automation using Appium Version 1.1.0-beta.4, and since Appium 1.6, we've noticed the above error. 

What happens:

1. The app starts up
2. The Appium log then reports this error
3. The app is closed, despite running just fine on the device

There is no app wait activity set. When we do set it to, for example, one of the missing activities, we find that it just keeps repeating the package root name for each activity added, eventually becoming long strings. (Logs below.)

Example from the title shows this:
Encountered internal error running command: Error: Error occured while starting App. Original error: com.company.organization.controller.activities.Activity or com.company.organization.controller.COM.COMPANY.ORGANIZATION.CONTROLLER.activities.Activitry never started

Adding either of the activities would lead to an error that looks like this:
Encountered internal error running command: Error: Error occured while starting App. Original error: com.company.organization.controller.COM.COMPANY.ORGANIZATION.CONTROLLER.activities.Activity or com.company.organization.controller.COM.COMPANY.ORGANIZATION.CONTROLLER.COM.COMPANY.ORGANIZATION.CONTROLLER.COM.COMPANY.ORGANIZATION.CONTROLLER.activities.Activitry never started

The capitalized parts repeating.

This is forcing a working app to close. Our automation retries a few times to set up a driver, and catches driver related failures for a full retry, which we've found to cause the automation to sometimes start. We can actually get through an entire test suite without a failure thanks to these retries, but the tests take well over 4 times as long to complete.

## Environment

* Appium version: Appium Desktop 1.1.0 beta 4, Appium 1.6.5
* Last Appium version that did not exhibit the issue (if applicable): 1.5.3, but this does not run tests on Android 7, Nougat.
* Desktop OS/version used to run Appium: macOS Sierra, 10.12.4
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Android 7.0
* Real device or emulator/simulator: Real device, tested on both Samsung Galaxy S8 and Moto G4
* Appium CLI or Appium.app|exe: 

## Link to Appium logs

[(Slightly edited) Appium logs](https://gist.github.com/danigol/581e0ae44acf8e24e3b700527c373fc2)

**Comment by imurchie** [comment]
Thanks for the report. This is reproducible. I'll see about a fix.

**Comment by imurchie** [comment]
Can you try installing the latest beta (`npm uninstall -g appium && npm cache clean && npm install -g appium@beta`)? It should have `appium-adb@2.24.1`. I've made changes that I hope will fix this issue.

**Comment by danigol** [comment]
Hey, sorry, @imurchie, I'm still seeing this with [the beta.](https://gist.github.com/danigol/577798b3cffb9f6b52961ca110c3bc5b)

**Comment by imurchie** [comment]
From the logs, I don't see the repetition anymore. I do see that the activity that is started is not the one you are looking for.

**Comment by danigol** [comment]
That's the thing, I'm not looking for an activity. 
```
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/<USERNAME>/development/built apps/organization-google-mobile-ampprod-release.apk","appPackage":"com.company.organization.controller","newCommandTimeout":1200,"platformVersion":"7.0","udid":"<DEVICEUDID>","platformName":"Android","deviceName":"<DEVICEUDID>"}}
```

Desired capabilities mention the app package, but nothing about an activity.

**Comment by imurchie** [comment]
Appium pulls the activity from the application's manifest. If it is not right, you can either specify one, or use the `appWaitActivity` and `appWaitPackage` capabilities.

**Comment by danigol** [comment]
That seems to have done the trick. Pulled a few potential activities from the app's manifest file and we're in business. Thanks!
Not seeing the repeated package name, so the fix associated with this issue seems to work as well.

**Comment by farooqyousuf** [comment]
Thanks @danigol and @imurchie, this thread helped me solve my issue!

**Comment by estefafdez** [comment]
Hi all, I'm still facing the same problem with Appium 1.7.2-beta2 and I can't make it work even with the appWaitActivity or the appWaitPackage. Any other solution? thanks.

**Comment by avanishf** [comment]
Hi all, im also facing the same problem with Appium 1.7.2-beta2 and can't make it work even with the appWaitActivity or the appWaitPackage in Bitrise(CI tool). Pls help me out! The same test runs locally on my machine but not on CI, its really bugging me off! i have already explained my problem with #9898 but here is the [gist](https://gist.github.com/avanishf/14e43b742b48d14e7a8109015df54910) file for the logs after making changes suggested in this thread

**Comment by imurchie** [comment]
@avanishf The log you have linked just has the Appium install. There is no server log to see what is happening. So there is nothing that we can do.

**Comment by avanishf** [comment]
@imurchie  thx for the tip, in script, appium command was set as `appium &>/dev/null &` which hides the console log, so i removed the `&>/dev/null` part and it printed the log in CI which then helped me to debug and helped me solved my issue. But now i m facing another issue that it doesn't pickup a locator in CI (on local machine, tests runs absolutely fine) but for some strange reason, its not picking up the password field locator, i have raised this issue here ... #9911

**Comment by poojach1310** [comment]
@imurchie  Hi,
 I recently started facing this issue.I upgraded my appium version to 1.6.5 but while running automation when i try to launch app i am getting following error.

[ADB] Error: com.abc.xyz.ui.SplashActivity or com.abc.xyz.dev.com.abc.xyz.ui.SplashActivity never started at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13) at ADB.callee$0$0$ (../../../lib/tools/apk-utils.js:153:7) at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40) at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22) at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21) at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37) at

**Comment by imurchie** [comment]
@poojach1310 What activity _is_ started?

**Comment by poojach1310** [comment]
@imurchie Hi, 

The splash activity only launched. On the physical device everything is happening fine. Its launching and doing what is written in my test cases but still i am getting this error in appium logs. I am running 2 jenkins jobs in first job one job i get too

This is actually frustrating now i have done lots of things to solve these errors but not able to.

 [Logcat] Logcat terminated with code 0, signal null
[UiAutomator] UiAutomator exited unexpectedly with code 0, signal null
exit-status: 0
[ADB] Error: Error while getting connected devices. Original error: Command '/Users/localadmin/Library/Android/sdk/platform-tools/adb devices' exited with code 1
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at ADB.callee$0$0$ (../../../lib/tools/system-calls.js:123:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>

**Comment by poojach1310** [comment]
@imurchie Hi, I am not able to figure out now if the error is with appium , adb or uiautomator
