### ISSUE TITLE
Don't want to install Unlock/Appium Setting anymore

### ISSUE THREAD

**Issue by wangtao169447** [appium/appium#8870]
## The problem

I want to install Unlock, Appium Setting, IME by manual , and then ,if i run testcase using appium ,i don't to install this kind of apk anymore.

what can i do?

thanks for help.

**Comment by vikramvi** [comment]
@wangtao169447 please post query in https://discuss.appium.io/

**Comment by mykola-mokhnach** [comment]
Closed as not an issue

**Comment by wangtao169447** [comment]
@vikramvi @mykola-mokhnach OK，thanks。
