### ISSUE TITLE
feature request: API for iOS element accessible endpoint supported by WDA

### ISSUE THREAD

**Issue by UlhasDeshmukh** [appium/appium#8871]
## The problem
Currently there is no API available for checking if  element is accessible or not.
WDA does support endpoint for same but it is not implemented.

https://github.com/appium/WebDriverAgent/blob/master/WebDriverAgentLib/Commands/FBElementCommands.m#L120

https://github.com/appium/appium-xcuitest-driver/blob/1774ca7952dfbdc4dd9063f1a04e0ce1848ebd39/docs/endpoints-wda.md

## Environment

* Appium version (or git revision) that exhibits the issue:1.6.4
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium:Mac OS X El Caitan 
* Node.js version (unless using Appium.app|exe): NA
* Mobile platform/version under test: iOS 10.2
* Real device or emulator/simulator:Real device iPhone 7
* Appium CLI or Appium.app|exe: Appium.app

**Comment by mykola-mokhnach** [comment]
It is supported via getAttribute call:

```java
boolean isAccessible = element.getAttribute("isWDAccessible");
// or
boolean isAccessible = element.getAttribute("wdAccessible");
```

also, it can be used in predicate lookup queries.
