### ISSUE TITLE
Could not find Automation.tracetemplate in any of the followinglocations /a

### ISSUE THREAD

**Issue by navin499** [appium/appium#8874]
## The problem

I am trying to automate iphone(real device) with appium using robotframework appiumlibrary,

I have the app installed in my real device also i do have the .ipa file available, I can see the installed app in Xcode from where i got uuid, bundle id and other details.

I started appium and then started robotframework script, and got an error "Could not find Automation.tracetemplate in any of the followinglocations "

## Environment
Mac version:- 10.12.5
Appium- 1.5.3 (xcode path set with 8.3.2)
Xcode- 8.3.2
iOS-real device:- iPhone 5s (version:- 10.3.2)
App installed on real device 
RobotFramework

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/navin499/535d8421d04f648f9fb534624f854abb

Let me know if you need more details.

Thanks in advance.

**Comment by imurchie** [comment]
Xcode 8+ does include the Instruments automation trace template. It is, unfortunately, impossible to use Appium 1.5.3 (which depends on the trace template) to automate with Xcode 8+ and iOS 10+.

The only solution is to upgrade Appium.

**Comment by navin499** [comment]
@imurchie thanks for your quick response, I have both appium 1.5.3 and appium Version 1.1.0-beta.4 (1.1.0-beta.4), getting error with both appium versions.
Could you suggest me the appropriate appium version which should work with my configuration

**Comment by imurchie** [comment]
1.6.5 would be best. I think that comes bundled in the desktop version 1.1.0-beta.4.

If the problem persists there, you need to provide the server logs for it.

**Comment by navin499** [comment]
@imurchie , 

With appium 1.6.5, I am getting below error:

WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65

Please find below server logs:

=========================================================

Appium] Welcome to Appium v1.6.5
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"requiredCapabilities":{},"desiredCapabilities":{"deviceName":"iPhone5s","udid":"b4eecdf6c41ff99c852f9b2cdaf3051d695fe40d","automationName":"appium","platformVersion":"10.3","platformName":"iOS","bundleId":"com.airbnb.appenterprise"}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"deviceName":"iPhone5s","udid":"b4eecdf6c41ff99c852f9b2cdaf3051d695fe40d","automationName":"appium","platformVersion":"10.3","platformName":"iOS","bundleId":"com.airbnb.appenterprise"},{},null]
[BaseDriver] Event 'newSessionRequested' logged at 1500396522958 (09:48:42 GMT-0700 (PDT))
[Appium] Requested iOS support with version >= 10, using XCUITest driver instead of UIAutomation-based driver, since the latter is unsupported on iOS 10 and up.
[Appium] Creating new XCUITestDriver (v2.30.0) session
[Appium] Capabilities:
[Appium]   deviceName: 'iPhone5s'
[Appium]   udid: 'b4eecdf6c41ff99c852f9b2cdaf3051d695fe40d'
[Appium]   automationName: 'appium'
[Appium]   platformVersion: '10.3'
[Appium]   platformName: 'iOS'
[Appium]   bundleId: 'com.airbnb.appenterprise'
[XCUITest] XCUITestDriver version: 2.30.0
[BaseDriver] Session created with session id: c2f63332-af8a-4d31-8a71-46ca3416bfac
[XCUITest] Xcode version set to '8.3.2' (tools v8.3.2.0.1.1492020469)
[XCUITest] iOS SDK Version set to '10.3'
[BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1500396523087 (09:48:43 GMT-0700 (PDT))
[XCUITest] Available devices: b4eecdf6c41ff99c852f9b2cdaf3051d695fe40d
[XCUITest] Creating iDevice object with udid 'b4eecdf6c41ff99c852f9b2cdaf3051d695fe40d'
[XCUITest] Determining device to run tests on: udid: 'b4eecdf6c41ff99c852f9b2cdaf3051d695fe40d', real device: true
[BaseDriver] Event 'appConfigured' logged at 1500396523348 (09:48:43 GMT-0700 (PDT))
[BaseDriver] Event 'resetStarted' logged at 1500396523614 (09:48:43 GMT-0700 (PDT))
[XCUITest] Reset: running ios real device reset flow
[BaseDriver] Event 'resetComplete' logged at 1500396523616 (09:48:43 GMT-0700 (PDT))
[iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[BaseDriver] Event 'logCaptureStarted' logged at 1500396523714 (09:48:43 GMT-0700 (PDT))
[XCUITest] Setting up real device
[BaseDriver] Event 'wdaStartAttempted' logged at 1500396523720 (09:48:43 GMT-0700 (PDT))
[XCUITest] Using WDA path: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[XCUITest] Carthage found: '/usr/local/bin/carthage'
[XCUITest] Killing hanging processes
[XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=b4eecdf6c41ff99c852f9b2cdaf3051d695fe40d -configuration Debug IPHONEOS_DEPLOYMENT_TARGET=10.3' in directory '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Output from xcodebuild will not be logged
[XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[XCUITest] Log file for xcodebuild test: /Users/zak_chaban/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/9B053F12-7165-41A6-8ECF-FE871CEEBDC8/Session-WebDriverAgentRunner-2017-07-18_094851-g6HwhP.log
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[Xcode] 2017-07-18 09:48:51.312 xcodebuild[5271:1729162] Error Domain=NSCocoaErrorDomain Code=260 "The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/zak_chaban/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7fe09e567d20 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
[Xcode] 
[Xcode] 2017-07-18 09:48:51.312 xcodebuild[5271:1729162] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
[Xcode] 
[Xcode] ** TEST EXECUTE FAILED **
[Xcode] 
[Xcode] 
[XCUITest] xcodebuild exited with code '65' and signal 'null'
[BaseDriver] Event 'wdaStartFailed' logged at 1500396531348 (09:48:51 GMT-0700 (PDT))
[XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
[XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down iproxy process (pid 5269)
[XCUITest] iproxy exited with code 'null'
[XCUITest] Removing WDA application from device
[BaseDriver] Event 'wdaStartAttempted' logged at 1500396541577 (09:49:01 GMT-0700 (PDT))
[XCUITest] Using WDA path: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[XCUITest] Carthage found: '/usr/local/bin/carthage'
[XCUITest] Killing hanging processes
[XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=b4eecdf6c41ff99c852f9b2cdaf3051d695fe40d -configuration Debug IPHONEOS_DEPLOYMENT_TARGET=10.3' in directory '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Output from xcodebuild will not be logged
[XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[XCUITest] Log file for xcodebuild test: /Users/zak_chaban/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/331F8BDF-6029-4940-BFB8-19F3F2FC0A37/Session-WebDriverAgentRunner-2017-07-18_094909-KYcL3W.log
[Xcode] 2017-07-18 09:49:09.953 xcodebuild[5299:1729447] Error Domain=NSCocoaErrorDomain Code=260 "The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/zak_chaban/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7fcb9a1f20a0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
[Xcode] 
[Xcode] 2017-07-18 09:49:09.953 xcodebuild[5299:1729447] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
[Xcode] 
[Xcode] ** TEST EXECUTE FAILED **
[Xcode] 
[Xcode] 
[XCUITest] xcodebuild exited with code '65' and signal 'null'
[BaseDriver] Event 'wdaStartFailed' logged at 1500396549977 (09:49:09 GMT-0700 (PDT))
[XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
[XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down iproxy process (pid 5298)
[XCUITest] iproxy exited with code 'null'
[XCUITest] Removing WDA application from device
[XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
    at XCUITestDriver.quitAndUninstall$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:386:15)
    at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
    at XCUITestDriver.quitAndUninstall$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:386:15)
    at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
    at XCUITestDriver.quitAndUninstall$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:386:15)
    at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[HTTP] <-- POST /wd/hub/session 500 37341 ms - 230 
Appium server stopped successfully

**Comment by imurchie** [comment]
That is an entirely different issue. Please read https://github.com/appium/appium/blob/master/docs/en/appium-setup/real-devices-ios.md and, if there is still an issue, look through the existing issues as this has been covered a number of times.

**Comment by navin499** [comment]
@imurchie 

I did try the process mentioned  but still getting same error :-(


Please help me to resolve this issue, as on the same MAC device I am able to run automation on real android device but not able to run on iPhone 
============  server logs ============

Developer","platformVersion":"10.3","platformName":"iOS","bundleId":"com.airbnb.appenterprise"},{},null]
[BaseDriver] Event 'newSessionRequested' logged at 1500490194386 (11:49:54 GMT-0700 (PDT))
[Appium] Requested iOS support with version >= 10, using XCUITest driver instead of UIAutomation-based driver, since the latter is unsupported on iOS 10 and up.
[Appium] Creating new XCUITestDriver (v2.30.0) session
[Appium] Capabilities:
[Appium]   deviceName: 'iPhone5s'
[Appium]   xcodeOrgId: '5LL7P8E8RA'
[Appium]   udid: 'b4eecdf6c41ff99c852f9b2cdaf3051d695fe40d'
[Appium]   automationName: 'Appium'
[Appium]   xcodeSigningId: 'iPhone Developer'
[Appium]   platformVersion: '10.3'
[Appium]   platformName: 'iOS'
[Appium]   bundleId: 'com.airbnb.appenterprise'
[XCUITest] XCUITestDriver version: 2.30.0
[BaseDriver] Session created with session id: 715549e9-6db2-4261-923d-501d25ab506b
[XCUITest] Xcode version set to '8.3.2' (tools v8.3.2.0.1.1492020469)
[XCUITest] iOS SDK Version set to '10.3'
[BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1500490194514 (11:49:54 GMT-0700 (PDT))
[XCUITest] Available devices: b4eecdf6c41ff99c852f9b2cdaf3051d695fe40d
[XCUITest] Creating iDevice object with udid 'b4eecdf6c41ff99c852f9b2cdaf3051d695fe40d'
[XCUITest] Determining device to run tests on: udid: 'b4eecdf6c41ff99c852f9b2cdaf3051d695fe40d', real device: true
[BaseDriver] Event 'appConfigured' logged at 1500490194918 (11:49:54 GMT-0700 (PDT))
[BaseDriver] Event 'resetStarted' logged at 1500490195235 (11:49:55 GMT-0700 (PDT))
[XCUITest] Reset: running ios real device reset flow
[BaseDriver] Event 'resetComplete' logged at 1500490195238 (11:49:55 GMT-0700 (PDT))
[iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[BaseDriver] Event 'logCaptureStarted' logged at 1500490195395 (11:49:55 GMT-0700 (PDT))
[XCUITest] Setting up real device
[BaseDriver] Event 'wdaStartAttempted' logged at 1500490195404 (11:49:55 GMT-0700 (PDT))
[XCUITest] Using WDA path: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[XCUITest] Carthage found: '/usr/local/bin/carthage'
[XCUITest] Killing hanging processes
[ADB] Pressing the HOME button
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running '/Users/zak_chaban/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","4200156af271b3f9","shell","input","keyevent",3]
[XCUITest] Generating xcode config file for orgId '5LL7P8E8RA' and signingId 'iPhone Developer'
[XCUITest] Writing xcode config file to /var/folders/br/c0g4m_6111x8c9r1vy8c4f600000gn/T/2017619-8352-1ruotpn.jx2mkdfgvi/appium-temp.xcconfig
[XCUITest] Using Xcode configuration file: '/var/folders/br/c0g4m_6111x8c9r1vy8c4f600000gn/T/2017619-8352-1ruotpn.jx2mkdfgvi/appium-temp.xcconfig'
[XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=b4eecdf6c41ff99c852f9b2cdaf3051d695fe40d -configuration Debug IPHONEOS_DEPLOYMENT_TARGET=10.3 -xcconfig /var/folders/br/c0g4m_6111x8c9r1vy8c4f600000gn/T/2017619-8352-1ruotpn.jx2mkdfgvi/appium-temp.xcconfig' in directory '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Output from xcodebuild will not be logged
[XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[AndroidBootstrap] Sending command to android: {"cmd":"shutdown"}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"shutdown"}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type SHUTDOWN
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":"OK, shutting down"}
[AndroidBootstrap] Received command result from bootstrap
[UiAutomator] Shutting down UiAutomator
[UiAutomator] Moving to state 'stopping'
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Closed client connection
[AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: numtests=1
[AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: stream=.
[AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
[AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
[AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
[AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: current=1
[AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS_CODE: 0
[UiAutomator] UiAutomator shut down normally
[UiAutomator] Moving to state 'stopped'
[ADB] Attempting to kill all uiautomator processes
[ADB] Getting all processes with uiautomator
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running '/Users/zak_chaban/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","4200156af271b3f9","shell","ps"]
[ADB] No uiautomator process found to kill, continuing...
[UiAutomator] Moving to state 'stopped'
[Logcat] Stopping logcat capture
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running '/Users/zak_chaban/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","4200156af271b3f9","shell","am","force-stop","io.appium.unlock"]
[AndroidDriver] Not cleaning generated files. Add `clearSystemFiles` capability if wanted.
[XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[XCUITest] Log file for xcodebuild test: /Users/zak_chaban/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/1C6C65A0-4E70-44CE-81F7-54F31D16587D/Session-WebDriverAgentRunner-2017-07-19_115006-3uCavs.log
[Xcode] 2017-07-19 11:50:06.430 xcodebuild[17128:612452] Error Domain=NSCocoaErrorDomain Code=260 "The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/zak_chaban/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7fea08d36370 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
[Xcode] 
[Xcode] 2017-07-19 11:50:06.430 xcodebuild[17128:612452] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
[Xcode] 
[Xcode] ** TEST EXECUTE FAILED **
[Xcode] 
[Xcode] 
[XCUITest] xcodebuild exited with code '65' and signal 'null'
[BaseDriver] Event 'wdaStartFailed' logged at 1500490206492 (11:50:06 GMT-0700 (PDT))
[XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
[XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down iproxy process (pid 17123)
[XCUITest] iproxy exited with code 'null'
[XCUITest] Removing WDA application from device
[BaseDriver] Event 'wdaStartAttempted' logged at 1500490216738 (11:50:16 GMT-0700 (PDT))
[XCUITest] Using WDA path: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[XCUITest] Carthage found: '/usr/local/bin/carthage'
[XCUITest] Killing hanging processes
[XCUITest] Generating xcode config file for orgId '5LL7P8E8RA' and signingId 'iPhone Developer'
[XCUITest] Writing xcode config file to /var/folders/br/c0g4m_6111x8c9r1vy8c4f600000gn/T/2017619-8352-15ve872.bpq6umzpvi/appium-temp.xcconfig
[XCUITest] Using Xcode configuration file: '/var/folders/br/c0g4m_6111x8c9r1vy8c4f600000gn/T/2017619-8352-15ve872.bpq6umzpvi/appium-temp.xcconfig'
[XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=b4eecdf6c41ff99c852f9b2cdaf3051d695fe40d -configuration Debug IPHONEOS_DEPLOYMENT_TARGET=10.3 -xcconfig /var/folders/br/c0g4m_6111x8c9r1vy8c4f600000gn/T/2017619-8352-15ve872.bpq6umzpvi/appium-temp.xcconfig' in directory '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Output from xcodebuild will not be logged
[XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
Appium server stopped successfully

**Comment by imurchie** [comment]
These logs are deeply weird. Why is there Android stuff going on?

**Comment by imurchie** [comment]
Can you try running the following in your terminal:
```
cd /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent

xcodebuild build-for-testing test-without-building -project /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=b4eecdf6c41ff99c852f9b2cdaf3051d695fe40d -configuration Debug IPHONEOS_DEPLOYMENT_TARGET=10.3 -xcconfig /var/folders/br/c0g4m_6111x8c9r1vy8c4f600000gn/T/2017619-8352-1ruotpn.jx2mkdfgvi/appium-temp.xcconfig
```

**Comment by navin499** [comment]
@imurchie 
I tried above steps in terminal and got below log :=

--------------------------------------------------------------------

n$ cd /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
ml006453zchaban:WebDriverAgent zak_chaban$ ls
CONTRIBUTING.md			PrivateHeaders
Cartfile			README.md
Cartfile.resolved		Resources
Carthage			Scripts
Configurations			WebDriverAgent.xcodeproj
Inspector			WebDriverAgentLib
LICENSE				WebDriverAgentRunner
PATENTS				WebDriverAgentTests
ml006453zchaban:WebDriverAgent zak_chaban$ xcodebuild build-for-testing test-without-building -project /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=b4eecdf6c41ff99c852f9b2cdaf3051d695fe40d -configuration Debug IPHONEOS_DEPLOYMENT_TARGET=10.3 -xcconfig /var/folders/br/c0g4m_6111x8c9r1vy8c4f600000gn/T/2017619-8352-1ruotpn.jx2mkdfgvi/appium-temp.xcconfig
Build settings from command line:
    IPHONEOS_DEPLOYMENT_TARGET = 10.3

Build settings from configuration file '/var/folders/br/c0g4m_6111x8c9r1vy8c4f600000gn/T/2017619-8352-1ruotpn.jx2mkdfgvi/appium-temp.xcconfig':
    CODE_SIGN_IDENTITY = iPhone Developer
    DEVELOPMENT_TEAM = 5LL7P8E8RA

=== BUILD TARGET WebDriverAgentLib OF PROJECT WebDriverAgent WITH CONFIGURATION Debug ===

Check dependencies
No signing certificate "iOS Development" found:  No "iOS Development" signing certificate matching team ID "5LL7P8E8RA" with a private key was found.

** TEST BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
2017-07-19 22:39:11.753 xcodebuild[29241:1055912]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/zak_chaban/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/CD84BD14-475A-4D1A-A3EC-A151C9248611/Session-WebDriverAgentRunner-2017-07-19_223911-yF9Wa5.log
2017-07-19 22:39:11.757 xcodebuild[29241:1055910] [MT] IDETestOperationsObserverDebug: (BC938A13-9C41-425D-9D49-B467B83038C7) Beginning test session WebDriverAgentRunner-BC938A13-9C41-425D-9D49-B467B83038C7 at 2017-07-19 22:39:11.755 with Xcode 8E2002 on target <DVTiOSDevice: 0x7f977ab14000> {
		deviceSerialNumber:         F2MN52EZFFDQ
		identifier:                 b4eecdf6c41ff99c852f9b2cdaf3051d695fe40d
		deviceClass:                iPhone
		deviceName:                 Gil's iPhone
		deviceIdentifier:           b4eecdf6c41ff99c852f9b2cdaf3051d695fe40d
		productVersion:             10.3.2
		buildVersion:               14F89
		deviceSoftwareVersion:      10.3.2 (14F89)
		deviceArchitecture:         arm64
		deviceTotalCapacity:        12337876992
		deviceAvailableCapacity:    9160093696
		deviceIsTransient:          NO
		ignored:                    NO
		deviceIsBusy:               NO
		deviceIsActivated:          YES
		deviceActivationState:      Activated
		isPasscodeLocked:           NO
		deviceType:                 <DVTDeviceType:0x7f977a4e2740 Xcode.DeviceType.iPhone>
		supportedDeviceFamilies:    (
    1
)
		applications:              (null)
		provisioningProfiles:      (null)
		activityProgress:          -2
		activityTitle:             
		hasInternalSupport:        NO
		isSupportedOS:             YES
		developerDiskMountError:   (null)
(null)
	bootArgs:                  <unavailable>
		} (10.3.2 (14F89))
2017-07-19 22:39:11.803 xcodebuild[29241:1055910] Error Domain=NSCocoaErrorDomain Code=260 "The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/zak_chaban/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7f977ad1cf80 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
2017-07-19 22:39:11.803 xcodebuild[29241:1055910] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
** TEST EXECUTE FAILED **

**Comment by imurchie** [comment]
You need to be sure you have your signing certificates in order:
```
No signing certificate "iOS Development" found:  No "iOS Development" signing certificate matching team ID "5LL7P8E8RA" with a private key was found.
```

**Comment by navin499** [comment]
@imurchie ,

Thanks for your assistance , I will check on this with the developers and keep you posted here.
