### ISSUE TITLE
 Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65

### ISSUE THREAD

**Issue by navin499** [appium/appium#8876]
## The problem
I am trying to automate iphone(real device) with appium using robotframework appiumlibrary,

I have the app installed in my real device also i do have the .ipa file available, I can see the installed app in Xcode from where i got uuid, bundle id and other details.

I started appium and then started robotframework script, and got an error
 Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65

## Environment

Mac version:- 10.12.5
Appium- Version 1.1.0-beta.4 (1.1.0-beta.4)  ( started server V1.6.5)
Xcode- 8.3.2
iOS-real device:- iPhone 5s (version:- 10.3.2)
App installed on real device
RobotFramework

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/navin499/7d57ce8c7b1cb3a613017426aa9d6122

## Code To Reproduce Issue [ Good To Have ]

iOS_Test
    [Tags]  iOS
    ${REMOTE_URL}  set variable  http://localhost:4723/wd/hub
    ${PLATFORM_NAME}  set variable  iOS
    ${PLATFORM_VERSION}  set variable  10.3     #9.3        #10.3.1
    ${DEVICE_NAME}  set variable  iPhone5s       #iPhone5s
    ${APP_LOCATION}  set variable  /Users/XYZ/Desktop/AIRBNB/ResourcesData/Airbnb 17.15.ipa 
    ${BundleId}  set variable  com.airbnb.appenterprise
    ${UDID}  set variable  b4eecdf6c41ff99c852f9b2cdaf3051d695fe40d     
    open application  ${REMOTE_URL}  platformName=${PLATFORM_NAME}  platformVersion=${PLATFORM_VERSION}  deviceName=${DEVICE_NAME}  automationName=Appium  udid=${UDID}  bundleId=${BundleId}

Any help would be appreciated .

Thanks

**Comment by Leo-80** [comment]
Surprisingly, to fix this, I just replugged my iPhone to another port （https://stackoverflow.com/questions/43171020/unit-testing-ios-dtxproxychannel-error-1）

**Comment by mykola-mokhnach** [comment]
WDA source should to be signed with correct development signature. Read https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md for more details.

Closed as duplicate.
