### ISSUE TITLE
ADB Log reading support 

### ISSUE THREAD

**Issue by amias-channer** [appium/appium#8878]
Thanks Appium developers , 

## The problem

I am testing an app that is a controller for complex IOT devices , we need to access the logs on the device via our ruby scripts. I really don't want to use ADB directly because it prevents us using remote Appium servers and a lot of cloud testing solutions. Attempts thus far have yielded incomplete or old logs.

Our App uses several complex protocols that are not bound to UI elements (an important principle in app design) so we cannot see their progress via the UI unless we treat them as a black box. We need to get log messages from the devices to verify progress and to assist with diagnosing failures.
Whilst it isn't generally good practice in testing to use the logs this is a valid use case, it will enable others to do less helpful things but with caution and clearly defined log messages and classes it can be safe to make test assertions on log messages. I'm happy to help write guidelines on using this safely.

## Environment

* Appium version: All (up to 1.6.6-beta.2 as of writing)
* Last Appium version that did not exhibit the issue (if applicable): None
* Desktop OS/version used to run Appium: macOS Sierra 10.12.5
* Node.js version (unless using Appium.app|exe): 7.7.4.  (and desktop)
* Mobile platform/version under test: Android from api 21 up
* Real device or emulator/simulator: Both
* Appium CLI or Appium.app|exe: Both

## Suggested Solution

It should be possible to make the adb on the Appium server able relay to the log data and make it available on a given port kind of like syslog.  Current attempts via driver.manage.logs have only delivered a snapshot of the logs which makes waiting for a specific message consume a lot of resources and doesn't seem to update. A more flexible solution would be to have some kind of generator yield individual log messages, this would reduce the amount of duplicated data and reduce the need to poll for it. It should then be easy for automation code to then process them via its own logging. There is also a remote debugging option for adb which could be used.

I am happy to help on this , I'm new to Appium internals and node.js so might need a bit of hand.
I can certainly help test it.

**Comment by mykola-mokhnach** [comment]
Linking https://github.com/appium/appium-android-driver/pull/343

This change will allow to make logcat records available in realtime by broadcasting them to a websocket. However, this strategy is not supported by Selenium grid, so the feature will only work if the client has direct access to the machine where Appium server  is running.

**Comment by mykola-mokhnach** [comment]
Closed as implemented.
