### ISSUE TITLE
Strange issue seen with Android Nougat. Screen is not visible to appium during long running tests though Stay awake is enabled in developer options

### ISSUE THREAD

**Issue by gkvappium** [appium/appium#8879]
## The problem

Strange issue seen with Android Nougat. Screen is not visible to appium during long running tests though Stay awake is enabled in developer options

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.0 Release version
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Android 7.0 Samsung Galaxy S8 edge
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

1. I have a working framework for both Android 5 and 6
2. Recently I started to upgrade the test suite to support Android 7 execution as well
3. I didn't face this problem on Android 5 and 6. Execution is just fine.
4. Here is the problem on Android 7 - Execution starts without any problem. I get to a screen where I have to click the Cancel button after performing lot of steps. I see that the element click is failing since appium is not able to see the element
5. During debugging I found that appium is not able to see the screen itself though it is very much awake and not locked or something. Appium will keep looking for the element and will eventually fail after the timeout has been reached (Which I have set it at 10 seconds). If I tap the screen manually, appium is able to find the exact element and is able to click without any problem. This is more of a 'Stay awake' problem. Not sure if there is anything that I could do to resolve the problem. 

## Link to Appium logs
There is no concrete info the logs since it just looks for the element and fails telling that the element is not visible.

@mykola-mokhnach @imurchie  : Could you please have a look into this issue?

I can provide any specific details that you need

**Comment by gkvappium** [comment]
I found out something interesting. The problem happens after a toast message is cleared. Appium is not able to see the screen after a toast message is cleared. If I tap the screen again manually, appium wakes up and starts to see the screen and thus the element. This issue is seen only on Android 7

Note: I've tested this with uiautomator2 as well. I still see the issue

**Comment by mykola-mokhnach** [comment]
I think this is an UI Automator issue and we hardly can do anything on Appium side.

**Comment by gkvappium** [comment]
Ok. Thanks @mykola-mokhnach . As a workaround, I am doing a self.driver.back() to go to the initial screen of the app and coming back to the problematic screen. This seems to mitigate the problem since this is a screen refresh issue. This happens specifically after a delete operation is followed by a toast message notofication

**Comment by mykola-mokhnach** [comment]
It might be the same problem as described in https://github.com/appium/appium/issues/8747

**Comment by jlipps** [comment]
Yes, sounds like an Android/Uiautomator issue. Good to know there's a workaround @gkvappium!
