### ISSUE TITLE
Need help with WDAServer

### ISSUE THREAD

**Issue by shapovalovei** [appium/appium#8880]
@mykola-mokhnach Hi, I found your code for WDAServer. 
And I have some problem. I don't understand how it works with Appium. 
I create WDAServer in my framework and it doesn't works   :(

![screen shot 2017-07-19 at 17 05 00](https://user-images.githubusercontent.com/8914951/28371905-ee9418ea-6ca6-11e7-84fa-bdecb802bb3f.png)

My WDAServer: https://gist.github.com/shapovalovei/cc9979c0a9d6b0b90fa8859042a05a26
Class for creating driver: https://gist.github.com/shapovalovei/1a1869c006e51e907d6fee1a32b2d1f7

If you have time, please add me on skype: shapovalov298 
Or send me email: shapovalovei@gmail.com

**Comment by mykola-mokhnach** [comment]
Sorry, but I don't have enough time for code investigation. However, you can still ask for help on Appium forum. Probably, there are people, who already implemented similar approach.

Closed as server-unrelated.
