### ISSUE TITLE
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. desired capabilities = Capabilities [{appPackage=io.appium.unlock, appActivity=io.appium.unlock.Unlock, app=F://ApiDemos-debug.apk, browserName=android, platformName=Android, version=6.0.1, deviceName=bc55c8c7d73, platform=ANDROID}], required capabilities = Capabilities [{}]

### ISSUE THREAD

**Issue by madhusudhanbv** [appium/appium#8883]
## The problem

I'm trying to install an app on Android device but getting the exception as mentioned in the title.

## Environment

* Appium version 1.6.5
* Desktop OS/version used to run Appium: windows8
* Node.js version (unless using Appium.app|exe):8.1.0
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real device

## Details

DesiredCapabilities cap=DesiredCapabilities.android();
		cap.setCapability("appPackage", "io.appium.unlock");
		cap.setCapability("appActivity", "io.appium.unlock.Unlock");
		cap.setCapability(MobileCapabilityType.PLATFORM, Platform.ANDROID);
		cap.setCapability(MobileCapabilityType.PLATFORM_NAME, "Android");
		cap.setCapability(MobileCapabilityType.DEVICE_NAME, "bc55c8c7d73");
cap.setCapability(MobileCapabilityType.VERSION, "6.0.1");
ap.setCapability(MobileCapabilityType.APP,"F://ApiDemos-debug.apk");
URL url=new URL("http://127.0.0.1:4723/wb/hub");
		driver=new AndroidDriver<WebElement>(url,cap);

Appium log:
[HTTP] <-- POST /wb/hub/session 404 5 ms - 57
[HTTP] --> POST /wb/hub/session {"desiredCapabilities":{"appPackage":"io.appium.
unlock","appActivity":"io.appium.unlock.Unlock","app":"F://ApiDemos-debug.apk","
browserName":"android","platformName":"Android","version":"6.0.1","deviceName":"
bc55c8c7d73","platform":"ANDROID"},"requiredCapabilities":{}}
[debug] [HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- POST /wb/hub/session 404 5 ms - 57
[HTTP] --> POST /wb/hub/session {"capabilities":[{"desiredCapabilities":{"appPac
kage":"io.appium.unlock","appActivity":"io.appium.unlock.Unlock","app":"F://ApiD
emos-debug.apk","browserName":"android","platformName":"Android","version":"6.0.
1","deviceName":"bc55c8c7d73","platform":"ANDROID"}},{"requiredCapabilities":{}}
]}
[debug] [HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- POST /wb/hub/session 404 6 ms - 57
[HTTP] --> POST /wb/hub/session {"capabilities":[{"desiredCapabilities":{"appPac
kage":"io.appium.unlock","appActivity":"io.appium.unlock.Unlock","app":"F://ApiD
emos-debug.apk","browserName":"android","platformName":"Android","version":"6.0.
1","deviceName":"bc55c8c7d73","platform":"ANDROID"}},{"requiredCapabilities":{}}
],"desiredCapabilities":{"appPackage":"io.appium.unlock","appActivity":"io.appiu
m.unlock.Unlock","app":"F://ApiDemos-debug.apk","browserName":"android","platfor
mName":"Android","version":"6.0.1","deviceName":"bc55c8c7d73","platform":"ANDROI
D"},"requiredCapabilities":{}}
[debug] [HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- POST /wb/hub/session 404 4 ms - 57
[HTTP] --> POST /wb/hub/session {"desiredCapabilities":{"appPackage":"io.appium.
unlock","appActivity":"io.appium.unlock.Unlock","app":"F://ApiDemos-debug.apk","
browserName":"android","platformName":"Android","version":"6.0.1","deviceName":"
bc55c8c7d73","platform":"ANDROID"},"requiredCapabilities":{}}
[debug] [HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- POST /wb/hub/session 404 4 ms - 57
[HTTP] --> POST /wb/hub/session {"capabilities":[{"desiredCapabilities":{"appPac
kage":"io.appium.unlock","appActivity":"io.appium.unlock.Unlock","app":"F://ApiD
emos-debug.apk","browserName":"android","platformName":"Android","version":"6.0.
1","deviceName":"bc55c8c7d73","platform":"ANDROID"}},{"requiredCapabilities":{}}
]}
[debug] [HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- POST /wb/hub/session 404 4 ms - 57

Thanks for the help.

Regards,
Madhu

**Comment by mykola-mokhnach** [comment]
> [HTTP] <-- POST /wb/hub/session 404 5 ms - 57

404 means that there is no such page and most likely this happens because of the typo in the URL:
/**wb**/hub -> /**wd**/hub

Closed as server-unrelated.
