### ISSUE TITLE
Problem getting session data for driver type AndroidDriver; does it implement 'get driverData'?

### ISSUE THREAD

**Issue by siggerzz** [appium/appium#8885]
## The problem

This issue occurs on Android (from what I've experienced, only devices on 7.0+). I've been seeing this error mostly when running Android tests in parallel with iOS on Jenkins/dev environment, but also occasionally if I run a test in my dev envionment, terminate it and then try to run a test again.

## Environment

* Appium version (or git revision) that exhibits the issue: Tested in 1.6.4 / 1.6.5
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: MacOS - 10.2.3
* Node.js version (unless using Appium.app|exe): 6.10.3
* Mobile platform/version under test: Android 7.0
* Real device or emulator/simulator: Real Device (Samsung Galaxy S8, also seen on Nexus 6P)
* Appium CLI or Appium.app|exe: CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
[Appium Log](
https://gist.github.com/siggerzz/37bd34c8a1aefecf75d6419f3568f6a8)

## Code To Reproduce Issue [ Good To Have ]

N/A

**Comment by imurchie** [comment]
This happens when you try to start a session in the middle of another session.

**Comment by siggerzz** [comment]
I get that,  but I've been seeing this issue on my Jenkins test run, meaning it's occasionally trying to start a new session before the other one has finished (Despite quitting the driver in my teardown method).

I tried to get around the issue by using the --session-override server capability, which resolves the issue, but then I get the following error:

A session is either terminated or not started
TearDown : System.InvalidOperationException : A session is either terminated or not started

**Comment by imurchie** [comment]
The Appium server only responds to requests from the client, so it would seem something is going wrong in the flow within your tests.

**Comment by siggerzz** [comment]
I don't believe It's an issue with my code. All my tests have the same Teardown method, and It'll happen to any of my tests at random. I just don't know how to reliably run tests in series.

I either get Problem getting session data for driver type AndroidDriver; does it implement 'get driverData'? at random.

and If I specify --session-override, I get : TearDown : System.InvalidOperationException : A session is either terminated or not started,  at random.


This is my teardown method for all my tests:

```
public void Teardown()
        {
            if(TestContext.CurrentContext.Result.Outcome != ResultState.Success)
            {
                ScreenshotHelper helper = new ScreenshotHelper();
                var testName = TestContext.CurrentContext.Test.Name;
                helper.TakeAndSaveScreenshot(_driver, testName, _platformName, _platformVersion);
            }

            if (_environment == "Saucelabs")
            {
                // Gets the status of the current test
                bool passed = TestContext.CurrentContext.Result.Outcome.Status == TestStatus.Passed;
                try
                {
                    // Logs the result to Sauce Labs
                    ((IJavaScriptExecutor)_driver).ExecuteScript("sauce:job-result=" + (passed ? "passed" : "failed"));
                }
                finally
                {
                    // Terminates the remote webdriver session
                    _driver.Quit();
                }
            }
            else
            {
                _driver.Quit();
            }
        }    
```

**Comment by siggerzz** [comment]
@imurchie I managed to reproduce the ': A session is either terminated or not started' error whilst doing a parallel run on iOS/Android, with the error occurring on iOS on one of my tests. (Tested passed after re-running).

The error occured on the 'LoginToEditor'

Hopefully you'll be able to spot something of use in the log.

https://gist.github.com/siggerzz/f1e741a6154d791e70812e09212c4160

**Comment by imurchie** [comment]
Any chance you can give me some hint as to where this error is in the 9000 lines of logs? Search doesn't see "LoginToEditor" anywhere

**Comment by siggerzz** [comment]
@imurchie Sorry, If you view the full file, the LoginToEditor test starts on line 10558.

**Comment by imurchie** [comment]
What I see is the `LoginToEditor` test working away and then the `ResetPassword` test starting in the middle of it.
```
[HTTP] --> POST /wd/hub/session/5e456b69-2062-4590-958c-c45439cdfd19/execute {"script":"return document.readyState","args":[]}
[debug] [MJSONWP] Calling AppiumDriver.execute() with args: ["return document.readyState",[],"5e456b69-2062-4590-958c-c45439cdfd19"]
[debug] [XCUITest] Executing command 'execute'
[debug] [RemoteDebugger] Executing 'execute_script' atom in default context
[debug] [RemoteDebugger] Sending javascript command (function(){return function(){for(var aa="funct...
[debug] [RemoteDebugger] Sending WebKit data: {"method":"Runtime.evaluate","params":{"objectGroup":"console","includeCommandLineAPI":true,"doNotPauseOnExceptionsAndMuteConsole":true,"expression":"(function(){return function(){for(var aa=\"func...
[debug] [RemoteDebugger] Webkit response timeout: 5000
[HTTP] --> GET /wd/hub/status {}
[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.5","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 8 ms - 83 
[debug] [RemoteDebugger] Receiving WebKit data: {"result":{"result":{"type":"object","value":{"status":0,"value":"interactive"}},"wasThrown":false},"id":36}
[debug] [RemoteDebugger] Found handler for message '36'
[debug] [RemoteDebugger] Received result for atom 'execute_script' execution: "interactive"
[debug] [MJSONWP] Responding to client with driver.execute() result: "interactive"
[HTTP] <-- POST /wd/hub/session/5e456b69-2062-4590-958c-c45439cdfd19/execute 200 185 ms - 85 
[HTTP] --> POST /wd/hub/session/5e456b69-2062-4590-958c-c45439cdfd19/execute {"script":"return document.readyState","args":[]}
[debug] [MJSONWP] Calling AppiumDriver.execute() with args: ["return document.readyState",[],"5e456b69-2062-4590-958c-c45439cdfd19"]
[debug] [XCUITest] Executing command 'execute'
[debug] [RemoteDebugger] Executing 'execute_script' atom in default context
[debug] [RemoteDebugger] Sending javascript command (function(){return function(){for(var aa="funct...
[debug] [RemoteDebugger] Sending WebKit data: {"method":"Runtime.evaluate","params":{"objectGroup":"console","includeCommandLineAPI":true,"doNotPauseOnExceptionsAndMuteConsole":true,"expression":"(function(){return function(){for(var aa=\"func...
[debug] [RemoteDebugger] Webkit response timeout: 5000
[HTTP] --> GET /wd/hub/status {}
[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.5","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 6 ms - 83 
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"name":"ResetPassword","deviceName":"Qa's iPad Mini","platformName":"iOS","platformVersion":"10.3.2","environment":"Local","autoWebview":true,"startIWDP":true,"app":"/Users/ChrisLivings/Desktop/Appium/iOS/Staging/Basekit-07-07-staging.ipa"}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"name":"ResetPassword","deviceName":"Qa's iPad Mini","platformName":"iOS","platformVersion":"10.3.2","environment":"Local","autoWebview":true,"startIWDP":true,"app":"/Users/ChrisLivings/Desktop/Appium/iOS/Staging/Basekit-07-07-staging.ipa"},null,null]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1500562953796 (16:02:33 GMT+0100 (BST))
[Appium] Requested iOS support with version >= 10, using XCUITest driver instead of UIAutomation-based driver, since the latter is unsupported on iOS 10 and up.
[Appium] Creating new XCUITestDriver (v2.30.0) session
[Appium] Capabilities:
[Appium]   name: 'ResetPassword'
[Appium]   deviceName: 'Qa\'s iPad Mini'
[Appium]   platformName: 'iOS'
[Appium]   platformVersion: '10.3.2'
[Appium]   environment: 'Local'
[Appium]   autoWebview: true
[Appium]   startIWDP: true
[Appium]   app: '/Users/ChrisLivings/Desktop/Appium/iOS/Staging/Basekit-07-07-staging.ipa'
[Appium]   udid: '93a868ca6faacea11c6a4f8772fb39e59e9db70a'
[Appium] Session override is on. Deleting other sessions.
[Appium]     Deleting session '5e456b69-2062-4590-958c-c45439cdfd19'
[debug] [JSONWP Proxy] Proxying [DELETE /session/5e456b69-2062-4590-958c-c45439cdfd19] to [DELETE http://localhost:8100/session/2107D157-0E02-42EB-843D-E93A18F7D47A] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n\n  },\n  \"sessionId\" : \"B8310EAA-A439-472C-8E0B-B8B2BB3B5D02\",\n  \"status\" : 0\n}"
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down xcodebuild process (pid 61891)
[XCUITest] xcodebuild exited with code 'null' and signal 'SIGTERM'
[XCUITest] Shutting down iproxy process (pid 61881)
[debug] [XCUITest] iproxy exited with code 'null'
[debug] [XCUITest] Found WDA derived data folder: '/Users/ChrisLivings/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy'
[XCUITest] Setting '755' permissions to '/Users/ChrisLivings/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/Attachments' folder
[debug] [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[debug] [XCUITest] In a web session. Removing remote debugger
[debug] [RemoteDebugger] Disconnecting from WebKit remote debugger
[debug] [iOSLog] Stopping iOS log capture
[Appium] Removing session 5e456b69-2062-4590-958c-c45439cdfd19 from our master session list
[debug] [XCUITest] XCUITestDriver version: 2.30.0
[BaseDriver] The following capabilities were provided, but are not recognized by appium: name, environment.
[BaseDriver] Session created with session id: 545b99a9-9a4a-4d09-ad65-5d146ccaa881
[debug] [RemoteDebugger] WebKit remote debugger socket disconnected
```

**Comment by jlipps** [comment]
@siggerzz this is usually a sign that your code is not thread-safe. Probably the session ids for the drivers are getting set to some non-thread-safe variable.

**Comment by sarozNep** [comment]
@imurchie i am still getting same issue in version v1.2.0-beta.1 .... what might be the problem

**Comment by pradeepta02** [comment]
I am also facing the same issue while running the tests in sequence. First test passes, then remaining tests are skipped throwing error that "Problem getting session data for driver type AndroidDriver; does it implement 'get driverData'?". I am running tests on android chrome with appium version v1.2.0-beta.1 . I am creating the driver in beforeMethod and quitting the driver in afterMethod in TestNG.

**Comment by pradeepta02** [comment]
Appium version is 1.6.5

**Comment by imurchie** [comment]
@pradeepta02 Please provide the _full_ appium server logs as a link to a [gist](https://gist.github.com). Without them there is nothing that can be done.

**Comment by pradeepta02** [comment]
https://gist.github.com/pradeepta02/6f64f0c50d679f30d98edf3220040f48

**Comment by imurchie** [comment]
@pradeepta02 Something is going wrong in your client code. It feels like you have threading issues.

In the logs it goes awry here: https://gist.github.com/pradeepta02/6f64f0c50d679f30d98edf3220040f48#file-appium-log-L896-L908

**Comment by pradeepta02** [comment]
What could be the issue? I am running tests in sequence. Is quitting driver at end of test causing the issue? I have few tests. All tests extend BaseTest. In BaseTest @BeforeMethod, I am creating Appium driver and @AfterMethod I am calling driver.quit(). First test runs sucessfully. All remaining tests are skipped throwing the same error.

**Comment by imurchie** [comment]
I don't know what the problem is. This is something in your tests.

If you want to force Appium to kill sessions when a new one comes in, start it with the `--session-override` flag.

**Comment by pradeepta02** [comment]
I am already using --session-override flag.

**Comment by imurchie** [comment]
There is no indication that you are. You didn't give the _full_ server logs so I have no idea how you've invoked it or anything.

**Comment by pradeepta02** [comment]
I will write some sample code and will share with you, if that will help.

**Comment by pradeepta02** [comment]
Ok, my issue was that I had added type argument to Android Driver while creating it. 

`driver = new AndroidDriver<WebElement>(remoteHubUrl, caps);`

I changed the above line to ` driver = new AndroidDriver(remoteHubUrl, caps); ` and I am able to run the tests sequentially in Android Chrome browser.

**Comment by pradeepta02** [comment]
@imurchie, thanks for the quick response. Really appreciate it.
