### ISSUE TITLE
Android: StartActivity() does not allow configure appWaitActivity

### ISSUE THREAD

**Issue by amedvedjev** [appium/appium#8886]
## The problem

When i want so start some activity on phone there is no way set "appWaitAcivity". as result this cause fail in code.

Why not remove "Depricated" from other startActivity() ?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.6-beta2, java-client: 5.0.0-BETA9

## Details

**Failed code:**
```
        Activity activity = new Activity("com.android.chrome","com.google.android.apps.chrome.Main");
        ((AndroidDriver) driver).startActivity(activity);
       // chrome browser starting BUT appium failed to find started activity
```

**Working code:**
```
((AndroidDriver) driver).startActivity(
                "com.android.chrome",
                "com.google.android.apps.chrome.Main",
                "com.android.chrome",
                "org.chromium.chrome.browser.ChromeTabbedActivity",
                "android.intent.action.MAIN",
                "android.intent.category.LAUNCHER",
                "",
                null,
                false);
```

**Comment by imurchie** [comment]
Why not remove "Depricated" from other startActivity() ?
I'm not sure what this means.

**Comment by amedvedjev** [comment]
@imurchie i mean this -> https://screencast.com/t/FKjqyooVkT
thanks!

**Comment by mykola-mokhnach** [comment]
I assume the best place for this report would be https://github.com/appium/java-client/issues then
