### ISSUE TITLE
: An unknown server-side error occurred while processing the command. Original error: Could not install app:

### ISSUE THREAD

**Issue by siggerzz** [appium/appium#8887]
## The problem

I've been seeing this error on iOS, mainly when running tests in series/parallel. Occasionally I get this error message, although it's very intermittent (hence why my log is so long, I ran 9 tests in series before seeing the issue.) 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5 / 1.6.4
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: MacOS - 10.12.3
* Node.js version (unless using Appium.app|exe): 6.10.3
* Mobile platform/version under test: iOS - 10.3.2
* Real device or emulator/simulator: Real Device - iPhone 6S
* Appium CLI or Appium.app|exe: CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

[Appium Log](https://gist.github.com/siggerzz/8aeec9d06690ce9980994cbe896769ca)

**Comment by imurchie** [comment]
The link to the logs doesn't exist.

**Comment by SrinivasanTarget** [comment]
@siggerzz Please fill out the description properly for us to look into

**Comment by siggerzz** [comment]
Whoops, my bad. Try now 👍

**Comment by imurchie** [comment]
This issue has been fixed in the most recent version. See https://github.com/appium/appium-xcuitest-driver/pull/462

**Comment by siggerzz** [comment]
I take it this is included in 1.6.6 beta?

**Comment by imurchie** [comment]
Yes.
