### ISSUE TITLE
WDA socket hang-up after successful install and launch

### ISSUE THREAD

**Issue by squeemish** [appium/appium#8888]
## The problem

WDA installs on my real device, launches and closes properly, but then the actual app to be tested never launches.  Error given is 'socket hang up'.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5 
* Last Appium version that did not exhibit the issue (if applicable): 1.6.1 I think
* Desktop OS/version used to run Appium: macOS 10.12.5
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: Desktop 1.1.0 Beta 4

## Details

AUT installs properly.
WDA installs properly.
WDA launches and minimizes properly.
AUT never launches.

## Link to Appium logs

https://gist.github.com/anonymous/61d78265559dc1ba4e5cafb1eb8558d0

https://gist.github.com/squeemish/16e8a1b948c69d53ad31256955f38df8

https://gist.github.com/squeemish/cf8d8e6a7920ff1f9e87ea1c4d48a3a6 -- after clean up

https://gist.github.com/squeemish/391d63cbe213114249443f5842d00f4d -- iOS and xcode logs

https://gist.github.com/squeemish/e818bec93f742bf97e97016005ac0210 -- latest WDA

**Comment by imurchie** [comment]
Can you add the `showXcodeLog` capability (set to `true`) and then re-post the logs with the xcode logging on?

**Comment by squeemish** [comment]
additional logs attached to top

**Comment by imurchie** [comment]
Well, that didn't provide any more information. Can you clean up the agent and then try again? 
1. Manually delete `WebDriverAgent` from your device.
2. `rm -rf /Users/cseplo.scott/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs`

Then post the logs (with `showXcodeLog` on).

**Comment by squeemish** [comment]
attached logs to top (--after clean up)

**Comment by imurchie** [comment]
:( Things seem good in there, until nothing can connect to WDA.

The final thing to try is to look at the device logs and see if anything is going wrong in there.

**Comment by squeemish** [comment]
ok.  thanks for looking at this.  been banging my head for a couple of days, at least it wasn't something simple and obvious

**Comment by mykola-mokhnach** [comment]
@squeemish Are you sure your app is signed with Developer signature? Are you able to install and start it manually on the device?

**Comment by squeemish** [comment]
@mykola-mokhnach Yes.  I can confirm the app is signed with dev signature and that it can be installed and launched manually.

for reference, I have had this issue on the iPad Retina that is in the logs, a new iPad, and an iPhone 6+.  So the issue is not isolated to this particular device.

**Comment by mykola-mokhnach** [comment]
Maybe the app crashes after startup - can you also attach the device log to know for sure?

**Comment by mykola-mokhnach** [comment]
Also try to reboot the device - just in case.

**Comment by squeemish** [comment]
@mykola-mokhnach rebooted device and reran.  uploaded logs capturing iOS device and xcode.

please let me know if any other log combinations would be helpful

**Comment by mykola-mokhnach** [comment]
> [iOSLog] [IOS_SYSLOG_ROW] Jul 20 13:10:08 Rockville-iPad XCTRunner(WebDriverAgentLib)[210] : ServerURLHere->http://localhost:0<-ServerURLHere

Maybe the problem lies here. The port is set to zero because of the reason unknown to me.

**Comment by imurchie** [comment]
That could be a version mismatch. We specify that.

I would upgrade.

**Comment by squeemish** [comment]
upgrade the XCUITestDriver?  I'm just using the downloaded desktop Appium version downloaded July 12, 2017
I've completely removed the command-line Appium version.

I'll grab the latest XCUITestDriver and swap it out with what came with the desktop version

**Comment by squeemish** [comment]
I replaced WDA with the latest from https://github.com/appium/WebDriverAgent/tree/9f635358d128f5a9842946250ed0fce540a7c68a

same issue.  attached logs for reference

**Comment by imurchie** [comment]
That is the wrong technique. That code may not match up with the Appium code.

How did you swap out the `appium-xcuitest-driver` module?

**Comment by squeemish** [comment]
I downloaded WDA from the link above and just replaced the folder.  re-signed the app and ran Appium.

is there a better way to do this since I'm using the Desktop version (I just need to use the inspector) that is already bundled together?

**Comment by imurchie** [comment]
My feeling is that the issue is with a mismatch of WDA and the code that starts it and sends command to it. We now have to launch with a port, and I think the calling code you have does not do so but WDA expects it. So no port is there.

If, from the terminal, you run
```
cd /Applications/Appium.app/Contents/Resources/app/node_modules/appium
rm -rf node_modules/appium-xcuitest-driver
npm install appium-xcuitest-driver
```
then it should update correctly.

**Comment by squeemish** [comment]
that fixed it!  thank you very much for your attention today.  absolutely appreciated.

**Comment by imurchie** [comment]
All glories go to @mykola-mokhnach for catching that in the logs. But glad it worked out!

**Comment by mmolotov** [comment]
super hi.
we have same issue.
appium desktop for mac (Version 1.4.1)
appium command-line version 1.7.2

if i start appium server from terminal, all is good.
but from appium desktop it doesn't work.
i tried to reinstall appium-xcuitest-driver in /Applications/Appium.app//Contents/Resources/app/node_modules/appium but it did not help

so, only way -- to start server from command line, dat's not bad, just to let you know the problem.
