### ISSUE TITLE
when appium run about 10  test cases, appium exit

### ISSUE THREAD

**Issue by william5065** [appium/appium#8890]
## The problem

when appium run about 10  test cases, appium exit.
and windows 10 prompted ：Appium has not stopped work

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4

* Desktop OS/version used to run Appium: windows 10
* Node.js version (unless using Appium.app|exe): v6.10.0
* Mobile platform/version under test: android 4.4.2
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: appium -desktop 1.6.4

## Details

!

**Comment by william5065** [comment]
![img](https://user-images.githubusercontent.com/15863415/28449375-2645bcbe-6e12-11e7-989f-60b258780f02.png)

**Comment by william5065** [comment]
Looking forward to your reply！

**Comment by william5065** [comment]
use robot framework +appium +python to auto test

**Comment by mykola-mokhnach** [comment]
Please attach full Appium log

**Comment by william5065** [comment]
[llog.txt](https://github.com/appium/appium/files/1164805/llog.txt)

**Comment by mykola-mokhnach** [comment]
I don't see any explicit issues in the log. Can you please translate the text on the error message you see on the screenshot?

**Comment by william5065** [comment]
**translate windows error：**

Appium has stopped working

A problem has occurred that causes the program to stop working properly. If there is a solution available, Windows will close the program to notify you.

**Comment by mykola-mokhnach** [comment]
For me it looks more like an internal issue of Appium Desktop application, which should be reported to https://github.com/appium/appium-desktop
In general, it is not recommended to use desktop app to run automated tests. Install the CLI server with npm and use it for such purpose. Desktop app is mostly useful for tests development and debugging.
