### ISSUE TITLE
Appium is going to hang state during long run

### ISSUE THREAD

**Issue by jebapraveenmano** [appium/appium#8891]
## The problem

While running tests on real Android device using Appium, display is going to hang state. But still it is working properly in the back ground

## Environment

Appium 1.6.4
iPad 10 - Real device
MacMini 10
Xcode 8.3.2

**Comment by mykola-mokhnach** [comment]
Please attach full Appium log.

I cannot understand what is tested. You say "tests on real Android device", but below I see "iPad 10 - Real device"
