### ISSUE TITLE
"Max scroll count reached" error on scrolling

### ISSUE THREAD

**Issue by sebinjqburst** [appium/appium#8892]
## The problem

I am able to perform scrolling 90% of the time. But for a specific section of the app, the scroll is failing with the error 'Failed to perform scroll with visible cell due to max scroll count reached'. I am using moveTo in touch action to perform scrolling.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.6-beta.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac 10.12.1
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:

## Appium logs

[debug] [XCUITest] Found matching gesture: scroll
[debug] [JSONWP Proxy] Proxying [POST /wda/element/40E5D714-C40E-4480-B69B-83C16D718A61/scroll] to [POST http://localhost:8100/session/183138DA-08A6-4290-821F-33F441FEF957/wda/element/40E5D714-C40E-4480-B69B-83C16D718A61/scroll] with body: {"toVisible":true}
[debug] [JSONWP Proxy] Got response with status 200: {"value":"Error Domain=com.facebook.WebDriverAgent Code=1 \"Failed to perform scroll with visible cell due to max scroll count reached\" UserInfo={NSLocalizedDescription=Failed to perform scroll with visible cell due to max scroll count reached}","sessionId":"183138DA-08A6-4290-821F-33F441FEF957","status":13}

**Comment by mykola-mokhnach** [comment]
There is a hardcoded limitation in WDA, so it throws an error if number of scrolls until your element is visible exceeds some particular value. I'd try to ignore the error on the client code and retry. 

If you think this is a bug then please report it to https://github.com/facebook/WebDriverAgent/issues

Closed as third-party issue.

**Comment by sebinjqburst** [comment]
@mykola-mokhnach But the scroll is working for elements before and after this specific section. Also, a single scroll enough gets the elements in the section. Then why it is returning the 'max count reached' error. If it is the total number of scrolls I have used, how it is working for the elements after this section?
