### ISSUE TITLE
Unknown build action 'build-for-testing', appium 1.6.6-beta.3

### ISSUE THREAD

**Issue by raspu** [appium/appium#8893]
## The problem

Trying to run a simulator instance the WebDriverAgent is failing to build. The reported error is `Unknown build action 'build-for-testing'`

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.6-beta.3
* Desktop OS/version used to run Appium: macOS Sierra, 10.12.5
* Node.js version (unless using Appium.app|exe): 5.2.0
* Mobile platform/version under test: iOS 10.3.1 (Xcode 8.3.3)
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: CLI

## Details

If I run the xcodebuild line manually: 
```
xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=606A2282-B107-4755-8227-BAD9EC08E5BC IPHONEOS_DEPLOYMENT_TARGET=10.3
```
The build succeeds. 

## Link to Appium logs

[GIST](https://gist.github.com/raspu/4f5bd9783253b6fa9788fa390233d83b)

**Comment by mykola-mokhnach** [comment]
It is a problem with your local Xcode installation. Are you sure that xcode-select points to the correct version (8.3.3) of development tools?

**Comment by raspu** [comment]
Yes, it is pointing to the correct installation. I just restarted and seems to be working fine, I am not really sure what was de issue.
