### ISSUE TITLE
[Appium 1.6.5] appiumVersion capability not recognized by appium 

### ISSUE THREAD

**Issue by Abinmathews** [appium/appium#8896]
## The problem

Tried to run a test with appium, i have provided the appiumVersion as capability,But getting the following error message " The following capabilities were provided, but are not recognized by appium: appiumVersion."

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Ubuntu 14.04LTS
* Node.js version (unless using Appium.app|exe):7.0.0
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Android Emulator(5.1 sdk)
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs

[Appium] Creating new AndroidDriver (v1.20.0) session
[Appium] Capabilities:
[Appium]   deviceName: 'Android Emulator'
[Appium]   language: 'en'
[Appium]   locale: 'GB'
[Appium]   app: '/home/ushusadmin/dev/Release/python_android_testt/387369777/HPCards.apk'
[Appium]   automationName: null
[Appium]   platformVersion: '5.0'
[Appium]   platformName: 'Android'
[Appium]   appiumVersion: '1.6.5'
[debug] [AndroidDriver] AndroidDriver version: 1.20.0
[BaseDriver] The following capabilities were provided, but are not recognized by appium: appiumVersion.

## Code To Reproduce Issue [ Good To Have ]

capabilities.setCapability("appiumVersion", "1.6.5");

**Comment by imurchie** [comment]
This is just a warning, saying that Appium has no idea about the `appiumVersion` capability. The Appium server is whatever version it is.

`appiumVersion` is a Sauce Labs capability so they can spin up the right server version for you.
