### ISSUE TITLE
chrome browser automation not working seamlessly on uiautomator2 driver

### ISSUE THREAD

**Issue by jlipps** [appium/appium#8897]
## The problem

It looks like we don't automatically navigate into a webview and start chromedriver when using `browserName: chrome` in the uiautomator2 driver

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://app.testobject.com/#/share/4959aac4-ffbf-4122-9298-2b893ce94000/appium

**Comment by dpgraham** [comment]
Published to v0.5.5 (https://www.npmjs.com/package/appium-uiautomator2-driver)

**Comment by oldstone** [comment]
Hi, is this included in Appium 1.7?

**Comment by dpgraham** [comment]
It is, yes.
