### ISSUE TITLE
Implement '-ios class chain' on all clients

### ISSUE THREAD

**Issue by dpgraham** [appium/appium#8898]
Currently, not all appium clients support `-ios class chain` selectors. In light of the performance troubles we're having with XPath on XCUITest, I think it's important that we add these to our client libraries.

Acceptance Criteria
* [x] WebDriverIO (http://webdriver.io/guide/usage/selectors.html#Class-Name)
* [ ] WD
* [ ] PHP
* [x] .NET
* [x] Update `appium-desktop` recorder to use class chain

(Ruby, Java, Python are done already)

**Comment by mykola-mokhnach** [comment]
@dpgraham I've recently extended this lookup strategy to be able to find not only children, but rather descendants of an element. The updated examples and tutorials can be found at https://github.com/facebook/WebDriverAgent/wiki/Queries

**Comment by dpgraham** [comment]
Awesome. Yeah, we should update the docs for Appium too.

**Comment by tmytlovych** [comment]
@mykola-mokhnach 
Hi. 
Is there any way to perform searching of preceding-, following-sibling, parent elements with -ios class chain?

**Comment by mykola-mokhnach** [comment]
@tmytlovych Unfortunately there is no way to do it within a single request. class chain locators under the hood "mimic" location strategies, natively provided by XCTest.

**Comment by tmytlovych** [comment]
@mykola-mokhnach Thanks for quick response.
Maybe, there is a way to perform such kind of a search (when we need to use tree hierarchy) with ns predicate String? 

I was looking for it but, haven't found some kind of attribute like 'parent' or 'child' which I can use in predicate query  
For example, How to rewrite following locator without xpath:
"//XCUIElementTypeCell[preceding-sibling::XCUIElementTypeOther[@name='August']]"

**Comment by mykola-mokhnach** [comment]
For locators like the one above it's impossible to do it in one step. It's how XCTest is working and only Apple can change that.

**Comment by tmytlovych** [comment]
thanks.
Where can I find more info how to do it in more than 1 step?
And how it will look?

**Comment by lavi-xu** [comment]
@mykola-mokhnach 
https://github.com/facebook/WebDriverAgent/issues/610

Not work with find elements.

**Comment by KazuCocoa** [comment]
link: https://github.com/appium/appium-dotnet-driver/blob/96d945c754559e4cb65acaba90ae4e15f2fd2d9b/src/Appium.Net/Appium/Enums/MobileSelector.cs#L28

**Comment by christian-bromann** [comment]
This has been implemented in WebdriverIO for a while, so checking it from the list, see https://webdriver.io/docs/selectors.html#ios-xcuitest-predicate-strings-and-class-chains

**Comment by KazuCocoa** [comment]
AD already has.

https://github.com/appium/appium-desktop/search?q=-ios+class+chain&unscoped_q=-ios+class+chain

**Comment by mykola-mokhnach** [comment]
Closed as fixed
