### ISSUE TITLE
Failed at the appium-uiautomator2-driver@0.4.4 install script.

### ISSUE THREAD

**Issue by vjmaiky** [appium/appium#8902]
## The problem
I`m  trying to run npm install -g appium@1.6.6-beta.3 and it is failing

## Environment
node - 8.2.1
npm - 5.3.0

> appium-uiautomator2-driver@0.4.4 install C:\Users\lumihai\AppData\Roaming\npm\
node_modules\appium\node_modules\appium-uiautomator2-driver
> gulp prepublish && node ./bin/install.js

'gulp' is not recognized as an internal or external command,
operable program or batch file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\app
ium\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! appium-uiautomator2-driver@0.4.4 install: `gulp prepublish && node ./bi
n/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the appium-uiautomator2-driver@0.4.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lumihai\AppData\Roaming\npm-cache\_logs\2017-07-24T10_33_3
9_079Z-debug.log

few days ago it worked with no problems.

**Comment by vjmaiky** [comment]
https://gist.github.com/vjmaiky/e83bb966596c54ce4905357e0221e995

**Comment by mykola-mokhnach** [comment]
try `npm i -g gulp`

**Comment by vjmaiky** [comment]
i ran it then again npm install for appium:

Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

U:\>npm install -g appium@1.6.6-beta.3
npm WARN deprecated babel-core@5.8.24: Babel 5 is no longer being maintained. Up
grade to Babel 6.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher
 to avoid a RegExp DoS issue
npm WARN deprecated line-numbers@0.2.0: Copy its ~20 LOC directly into your code
 instead.
C:\Users\lumihai\AppData\Roaming\npm\appium -> C:\Users\lumihai\AppData\Roaming\
npm\node_modules\appium\build\lib\main.js

> appium-chromedriver@2.12.0 install C:\Users\lumihai\AppData\Roaming\npm\node_m
odules\appium\node_modules\appium-chromedriver
> node install-npm.js

info Chromedriver Install Installing Chromedriver version '2.30' for platform 'w
in' and architecture '32'
info Chromedriver Install Opening temp file to write chromedriver_win32 to...
info Chromedriver Install Downloading https://chromedriver.storage.googleapis.co
m/2.30/chromedriver_win32.zip...
info Chromedriver Install Writing binary content to C:\Users\lumihai\AppData\Loc
al\Temp\2017624-4728-11zntcw.nth1\chromedriver_win32.zip...
info Chromedriver Install Extracting C:\Users\lumihai\AppData\Local\Temp\2017624
-4728-11zntcw.nth1\chromedriver_win32.zip to C:\Users\lumihai\AppData\Local\Temp
\2017624-4728-11zntcw.nth1\chromedriver_win32
info Chromedriver Install Creating C:\Users\lumihai\AppData\Roaming\npm\node_mod
ules\appium\node_modules\appium-chromedriver\chromedriver\win...
info Chromedriver Install Copying unzipped binary, reading from C:\Users\lumihai
\AppData\Local\Temp\2017624-4728-11zntcw.nth1\chromedriver_win32\chromedriver.ex
e...
info Chromedriver Install Writing to C:\Users\lumihai\AppData\Roaming\npm\node_m
odules\appium\node_modules\appium-chromedriver\chromedriver\win\chromedriver.exe
...
info Chromedriver Install C:\Users\lumihai\AppData\Roaming\npm\node_modules\appi
um\node_modules\appium-chromedriver\chromedriver\win\chromedriver.exe successful
ly put in place

> appium-selendroid-driver@1.6.2 install C:\Users\lumihai\AppData\Roaming\npm\no
de_modules\appium\node_modules\appium-selendroid-driver
> node ./bin/install.js

dbug AndroidDriver Getting Java version
info AndroidDriver Java version is: 1.8.0_131
info Selendroid Ensuring C:\Users\lumihai\AppData\Roaming\npm\node_modules\appiu
m\node_modules\appium-selendroid-driver\selendroid\download exists
info Selendroid Downloading Selendroid standalone server version 0.17.0 from htt
p://repo1.maven.org/maven2/io/selendroid/selendroid-standalone/0.17.0/selendroid
-standalone-0.17.0-with-dependencies.jar --> C:\Users\lumihai\AppData\Roaming\np
m\node_modules\appium\node_modules\appium-selendroid-driver\selendroid\download\
selendroid-server-7cf7163ac47f1c46eff95b62f78b58c1dabdec534acc6632da3784739f6e9d
82.jar
info Selendroid Writing binary content to C:\Users\lumihai\AppData\Roaming\npm\n
ode_modules\appium\node_modules\appium-selendroid-driver\selendroid\download\sel
endroid-server.jar.tmp
info Selendroid Selendroid standalone server downloaded
info Selendroid Determining AndroidManifest location
info Selendroid Determining server apk location
info Selendroid Extracting manifest and apk to C:\Users\lumihai\AppData\Roaming\
npm\node_modules\appium\node_modules\appium-selendroid-driver\selendroid\downloa
d
info Selendroid Copying manifest and apk to C:\Users\lumihai\AppData\Roaming\npm
\node_modules\appium\node_modules\appium-selendroid-driver\selendroid
info Selendroid Cleaning up temp files
info Selendroid Fixing AndroidManifest icon bug

> appium-uiautomator2-driver@0.4.4 install C:\Users\lumihai\AppData\Roaming\npm\
node_modules\appium\node_modules\appium-uiautomator2-driver
> gulp prepublish && node ./bin/install.js

'gulp' is not recognized as an internal or external command,
operable program or batch file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\app
ium\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! appium-uiautomator2-driver@0.4.4 install: `gulp prepublish && node ./bi
n/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the appium-uiautomator2-driver@0.4.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lumihai\AppData\Roaming\npm-cache\_logs\2017-07-24T11_25_3
3_087Z-debug.log

U:\>npm i -g gulp
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher
 to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher
 to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail o
n node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible
. Use 'npm ls graceful-fs' to find it in the tree.
C:\Users\lumihai\AppData\Roaming\npm\gulp -> C:\Users\lumihai\AppData\Roaming\np
m\node_modules\gulp\bin\gulp.js
+ gulp@3.9.1
added 185 packages in 12.18s

U:\>npm install -g appium@1.6.6-beta.3
npm WARN deprecated babel-core@5.8.24: Babel 5 is no longer being maintained. Up
grade to Babel 6.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher
 to avoid a RegExp DoS issue
npm WARN deprecated line-numbers@0.2.0: Copy its ~20 LOC directly into your code
 instead.
C:\Users\lumihai\AppData\Roaming\npm\appium -> C:\Users\lumihai\AppData\Roaming\
npm\node_modules\appium\build\lib\main.js

> appium-chromedriver@2.12.0 install C:\Users\lumihai\AppData\Roaming\npm\node_m
odules\appium\node_modules\appium-chromedriver
> node install-npm.js

info Chromedriver Install Installing Chromedriver version '2.30' for platform 'w
in' and architecture '32'
info Chromedriver Install Opening temp file to write chromedriver_win32 to...
info Chromedriver Install Downloading https://chromedriver.storage.googleapis.co
m/2.30/chromedriver_win32.zip...
info Chromedriver Install Writing binary content to C:\Users\lumihai\AppData\Loc
al\Temp\2017624-8696-w2wkp7.z3izq\chromedriver_win32.zip...
info Chromedriver Install Extracting C:\Users\lumihai\AppData\Local\Temp\2017624
-8696-w2wkp7.z3izq\chromedriver_win32.zip to C:\Users\lumihai\AppData\Local\Temp
\2017624-8696-w2wkp7.z3izq\chromedriver_win32
info Chromedriver Install Creating C:\Users\lumihai\AppData\Roaming\npm\node_mod
ules\appium\node_modules\appium-chromedriver\chromedriver\win...
info Chromedriver Install Copying unzipped binary, reading from C:\Users\lumihai
\AppData\Local\Temp\2017624-8696-w2wkp7.z3izq\chromedriver_win32\chromedriver.ex
e...
info Chromedriver Install Writing to C:\Users\lumihai\AppData\Roaming\npm\node_m
odules\appium\node_modules\appium-chromedriver\chromedriver\win\chromedriver.exe
...
info Chromedriver Install C:\Users\lumihai\AppData\Roaming\npm\node_modules\appi
um\node_modules\appium-chromedriver\chromedriver\win\chromedriver.exe successful
ly put in place

> appium-selendroid-driver@1.6.2 install C:\Users\lumihai\AppData\Roaming\npm\no
de_modules\appium\node_modules\appium-selendroid-driver
> node ./bin/install.js

dbug AndroidDriver Getting Java version
info AndroidDriver Java version is: 1.8.0_131
info Selendroid Ensuring C:\Users\lumihai\AppData\Roaming\npm\node_modules\appiu
m\node_modules\appium-selendroid-driver\selendroid\download exists
info Selendroid Downloading Selendroid standalone server version 0.17.0 from htt
p://repo1.maven.org/maven2/io/selendroid/selendroid-standalone/0.17.0/selendroid
-standalone-0.17.0-with-dependencies.jar --> C:\Users\lumihai\AppData\Roaming\np
m\node_modules\appium\node_modules\appium-selendroid-driver\selendroid\download\
selendroid-server-7cf7163ac47f1c46eff95b62f78b58c1dabdec534acc6632da3784739f6e9d
82.jar
info Selendroid Writing binary content to C:\Users\lumihai\AppData\Roaming\npm\n
ode_modules\appium\node_modules\appium-selendroid-driver\selendroid\download\sel
endroid-server.jar.tmp
info Selendroid Selendroid standalone server downloaded
info Selendroid Determining AndroidManifest location
info Selendroid Determining server apk location
info Selendroid Extracting manifest and apk to C:\Users\lumihai\AppData\Roaming\
npm\node_modules\appium\node_modules\appium-selendroid-driver\selendroid\downloa
d
info Selendroid Copying manifest and apk to C:\Users\lumihai\AppData\Roaming\npm
\node_modules\appium\node_modules\appium-selendroid-driver\selendroid
info Selendroid Cleaning up temp files
info Selendroid Fixing AndroidManifest icon bug

> appium-uiautomator2-driver@0.4.4 install C:\Users\lumihai\AppData\Roaming\npm\
node_modules\appium\node_modules\appium-uiautomator2-driver
> gulp prepublish && node ./bin/install.js

module.js:487
    throw err;
    ^

Error: Cannot find module 'appium-gulp-plugins'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\lumihai\AppData\Roaming\npm\node_modules\app
ium\node_modules\appium-uiautomator2-driver\gulpfile.js:4:19)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\app
ium\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! appium-uiautomator2-driver@0.4.4 install: `gulp prepublish && node ./bi
n/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the appium-uiautomator2-driver@0.4.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lumihai\AppData\Roaming\npm-cache\_logs\2017-07-24T11_35_2
6_049Z-debug.log

U:\>npm i -g gulp
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher
 to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher
 to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail o
n node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible
. Use 'npm ls graceful-fs' to find it in the tree.
C:\Users\lumihai\AppData\Roaming\npm\gulp -> C:\Users\lumihai\AppData\Roaming\np
m\node_modules\gulp\bin\gulp.js
+ gulp@3.9.1
updated 1 package in 6.772s

U:\>

**Comment by mykola-mokhnach** [comment]
> Error: Cannot find module 'appium-gulp-plugins'

`npm i -g appium-gulp-plugins`

**Comment by vjmaiky** [comment]
worked. thank you

**Comment by satazor** [comment]
I just stumble upon the same issue reported by @vjmaiky .

Relying on `gulp` &  `appium-gulp-plugins` being installed globally is flaky. If the project has some step that must be run on install, it must work without relying on OS specific binaries or global packages. Can this be re-open so that a proper solution is implemented?

Thanks.
