### ISSUE TITLE
Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65

### ISSUE THREAD

**Issue by iamhaseebiqbal** [appium/appium#8903]
## The problem

Hi dear, I'm starting to automate mobile testing and started with the appium-demo application. I'm getting this exit with code 65 error, Although demo application is running perfectly on simulator.

## Environment

* Appium Desktop version : 1.1.0-beta.4
* MAC OSX : 10.12.5 (16F73)
* iOS 10.2.1 + 10.3.3
* Phone 5S + 6S

## Details

I've also tried WebDriverAgent manually and getting,

> 2017-07-24 13:21:17.056 xcodebuild[53915:9961361] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
> 
> Testing failed:
> 	Test target WebDriverAgentRunner encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted)
> ** TEST FAILED **

Already tried uninstalling both WDA and Application + restarting device. It didn't help at all.

iPhone5s Logs
https://a.uguu.se/r0XwQY1kHD33_iphone5s_Logs.txt

I'm stuck at this from 2 days. Please guide. Thanks

**Comment by mykola-mokhnach** [comment]
Make sure the application under test is signed properly (follow https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md)

Closed as duplicate.

**Comment by iamhaseebiqbal** [comment]
I'm able to solve this issue by downgrading Appium-Desktop(to 1.0.1). Thanks btw.
