### ISSUE TITLE
How to Restart the android devices using cmd 

### ISSUE THREAD

**Issue by ShibiKP** [appium/appium#8904]
How to restart the android devices by using the cmd Not to be Reboot the devices.

## Environment

* Desktop OS/version used to run Appium:Windows/ 1.6.4
* Node.js version (unless using Appium.app|exe): 7.2.0
* Mobile platform/version under test:Android/6.1
* Real device or emulator/simulator: Real Devices

## Details

Need to Restart my android devices using the ADB shell command. Lot of document they are said to reboot the android devices.

**Comment by mykola-mokhnach** [comment]
Please use Appium forum to ask questions.

Closed as server-unrelated.
