### ISSUE TITLE
Appium capability nativeWebScreenshot is ignored when using uiautomator2 

### ISSUE THREAD

**Issue by sigsegv8** [appium/appium#8906]
## The problem

When I start appium with the capabilities:

"automationName" : "uiautomator2"
"nativeWebScreenshot" : true

Whenever I am in webview context, it tries to take the screenshot using chromedriver still instead of native adb. It seems like the capability nativeWebScreenshot is not seen by uiautomator2. If I use uiautomator and nativeWebScreenshot is set to true, the screenshot is taken with native adb. Seems to only happen when I use uiautomator2

## Environment

* Appium 1.6.5
* macOS 10.12.5
* node 4.4.0
* Huawei Nexus 6p Android 7.0
* Run appium at command line with the following args:

appium -p 4772 -bp 4773 --strict-caps --chromedriver-port 9521 --default-capabilities '{"nativeWebScreenshot": true, "automationName":"uiautomator2", "platformName": "Android", "platformVersion":"7.0", "udid": "ABCDE1234", "recreateChromeDriverSessions": true, "appPackage" : "com.mypackage", "appActivity" : "com.mypackage.MainActivity"}' --tmp /tmp/24

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
`[debug] [ADB] Running '/Users/mobileqa01/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","ABCDE1234","shell","ps"]
[debug] [AndroidDriver] Parsed pid: 24561 pkg: com.mypackage!
[debug] [AndroidDriver] from: u0_a712,24561,548,1984536,168668,SyS_epoll_,0000000000,S,com.mypackage
[debug] [AndroidDriver] returning process name: com.mypackage
[debug] [AndroidDriver] Found webviews: ["WEBVIEW_com.mypackage"]
[debug] [AndroidDriver] Available contexts: ["NATIVE_APP","WEBVIEW_com.mypackage"]
[debug] [AndroidDriver] Connecting to chrome-backed webview context 'WEBVIEW_com.mypackage'
[debug] [Chromedriver] Changed state to 'starting'
[Chromedriver] Set chromedriver binary as: /usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/chromedriver/mac/chromedriver
[Chromedriver] Killing any old chromedrivers, running: pkill -15 -f "/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/chromedriver/mac/chromedriver.*--port=9521"
[Chromedriver] No old chromedrivers seemed to exist
[Chromedriver] Spawning chromedriver with: /usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/chromedriver/mac/chromedriver --url-base=wd/hub --port=9521 --adb-port=5037
[Chromedriver] [STDOUT] Starting ChromeDriver 2.28.455517 (2c6d2707d8ea850c862f04ac066724273981e88f) on port 9521
Only local connections are allowed.
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9521/wd/hub/status] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"\",\"status\":0,\"value\":{\"build\":{\"version\":\"alpha\"},\"os\":{\"arch\":\"x86_64\",\"name\":\"Mac OS X\",\"version\":\"10.12.5\"}}}"
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:9521/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.mypackage","androidUseRunningApp":true,"androidDeviceSerial":"ABCDE1234"}}}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"02754150a65670a1b7b7f04076e6e30b","status":0,"value":{"acceptSslCerts":true,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"browserName":"chrome","chrome":{"chromedriverVersion":"2.28.455517 (2c6d2707d8ea850c862f04ac066724273981e88f)"},"cssSelectorsEnabled":true,"databaseEnabled":false,"handlesAlerts":true,"hasTouchScreen":true,"javascriptEnabled":true,"locationContextEnabled":true,"mobileEmulationEnabled":false,"nativeEvents":true,"pageLoadStrategy":"normal","platform":"ANDROID","rotatable":false,"takesHeapSnapshot":true,"takesScreenshot":true,"unexpectedAlertBehaviour":"","version":"59.0.3071.125","webStorageEnabled":true}}
[debug] [Chromedriver] Changed state to 'online'
[debug] [MJSONWP] Responding to client with driver.setContext() result: null
[HTTP] <-- POST /wd/hub/session/381066cb-9c8c-49b9-9ff1-fe110811693f/context 200 1082 ms - 76 
[HTTP] --> POST /wd/hub/session/381066cb-9c8c-49b9-9ff1-fe110811693f/element {"using":"css selector","value":"body"}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [JSONWP Proxy] Proxying [POST /wd/hub/session/381066cb-9c8c-49b9-9ff1-fe110811693f/element] to [POST http://127.0.0.1:9521/wd/hub/session/02754150a65670a1b7b7f04076e6e30b/element] with body: {"using":"css selector","value":"body"}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"02754150a65670a1b7b7f04076e6e30b","status":0,"value":{"ELEMENT":"0.11536852070685577-1"}}
[JSONWP Proxy] Replacing sessionId 02754150a65670a1b7b7f04076e6e30b with 381066cb-9c8c-49b9-9ff1-fe110811693f
[HTTP] <-- POST /wd/hub/session/381066cb-9c8c-49b9-9ff1-fe110811693f/element 200 168 ms - 107 
[HTTP] --> GET /wd/hub/session/381066cb-9c8c-49b9-9ff1-fe110811693f/element/0.11536852070685577-1/text {}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/381066cb-9c8c-49b9-9ff1-fe110811693f/element/0.11536852070685577-1/text] to [GET http://127.0.0.1:9521/wd/hub/session/02754150a65670a1b7b7f04076e6e30b/element/0.11536852070685577-1/text] with body: {}
[debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"02754150a65670a1b7b7f04076e6e30b\",\"status\":0,\"value\":\"test\\n\\n\\n\\n\\n  \"}"
[JSONWP Proxy] Replacing sessionId 02754150a65670a1b7b7f04076e6e30b with 381066cb-9c8c-49b9-9ff1-fe110811693f
[HTTP] <-- GET /wd/hub/session/381066cb-9c8c-49b9-9ff1-fe110811693f/element/0.11536852070685577-1/text 200 264 ms - 650 
[HTTP] --> GET /wd/hub/session/381066cb-9c8c-49b9-9ff1-fe110811693f/screenshot {}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/381066cb-9c8c-49b9-9ff1-fe110811693f/screenshot] to [GET http://127.0.0.1:9521/wd/hub/session/02754150a65670a1b7b7f04076e6e30b/screenshot] with body: {}`

**Comment by mykola-mokhnach** [comment]
Linking https://github.com/appium/appium/issues/8897

**Comment by jlipps** [comment]
Yeah, probably just need to port the code from AndroidDriver to UiAutomator2Driver to open this up.

**Comment by imurchie** [comment]
Forgot that I had done this already. Opening a PR.

**Comment by imurchie** [comment]
`appium-uiautomator2-driver@0.5.1` includes this capability.
