### ISSUE TITLE
FAILED CONFIGURATION: @BeforeClass setup org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Device 5210eea7b4e3a3ab was not in the list of connected devices (WARNING: The server did not provide any stacktrace information) but the device is in the list

### ISSUE THREAD

**Issue by sidvicious786** [appium/appium#8908]
The problem : i am getting the error which i never used to get on my appium suite. Error : **FAILED CONFIGURATION: @BeforeClass setup org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Device 5210eea7b4e3a3ab was not in the list of connected devices (WARNING: The server did not provide any stacktrace information) but the device is in the list**

When i try to run any android test, i am getting the above error. Which i never used to get it. We have app just like shareit and we need two phones both communicating on different port and we test it using appium 

## Environment
git version : git version 2.11.0 (Apple Git-81)
Appium version : 1.6.3
* Desktop OS/version used to run Appium: 1.6.3
* Node.js version (unless using Appium.app|exe): v7.2.1
* Mobile platform/version under test: 6.0.1
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI 

## Details
When i try to run the test on any android version i have started getting the error before they were working fine and were able to initialize the app but now i am getting FAILED CONFIGURATION: @BeforeClass setup. i tried debugging the issue but i did not find any error in the app.

## Link to Appium logs
https://gist.github.com/sidvicious786/ddd02787bc6df614e064cf8d44b1d956

## Code To Reproduce Issue [ Good To Have ] : We use GitLab to keep our or else i would have share the repo to reproduce the issue.

package com.rjil.snw.android.permission.test;

import java.io.IOException;

import org.apache.log4j.Logger;
import org.testng.Assert;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import com.rjil.snw.mobileAutomation.PropertyFileReader;
import com.rjil.snw.mobileAutomation.pageobjects.android.HomePage;
import com.rjil.snw.mobileAutomation.pageobjects.android.ModifySystemSetting;
import com.rjil.snw.mobileAutomation.permission.AllowPermission;
import com.rjil.snw.mobileAutomation.test.BaseTest;
/**
 * 
 * @author sidharthlala
 *
 */
public class AllowPermissionTest extends BaseTest {

	static Logger log = Logger.getLogger(AllowPermissionTest.class.getName());

	static PropertyFileReader properties = new PropertyFileReader();
	HomePage senderHomePage = null;
	AllowPermission senderAlllowPermission = null;
	ModifySystemSetting modifysystemsettings = null;
	/**
	 * This method will be run before the first test methods in the this class
	 * are invoked. This method will initialize sender Application
	 * 
	 * @throws Exceptions
	 **/

	@BeforeClass(alwaysRun=true)
	public void setup() throws IOException, InterruptedException {
		initialiseSenderDriver();
		senderAlllowPermission = new AllowPermission(senderDriver);
		senderHomePage = new HomePage(senderDriver);
		senderHomePage.skipTutorialpage();
		senderAlllowPermission.AllowManagePhoneCalls();
		senderAlllowPermission.DenyJioSwitchMediaPhotos();		
	}
	
	/**
	 * com.android.packageinstaller:id/permission_deny_button
	 */

	@Test(groups = {"Regression"}, priority = 1)
	public void verifyExternalStorageMessage_SPR12_5_116a() {
		String actual = "Access to external storage is required to read or write files on your phone that you share using JioSwitch. Please allow access to external storage by clicking on Retry.";
		String expected = senderAlllowPermission.OFFs();
		Assert.assertEquals(expected, actual);
	
	}

	@Test(groups = {"Regression"},priority = 2)
	public void clickReTry_SPR12_5_13b() {
		senderAlllowPermission.ClickRetryButton();
		senderAlllowPermission.DenyJioSwitchMediaPhotos();
	}

	@Test(groups = {"Regression"}, priority = 3)
	public void clickOkButton_SPR12_5_13e() {
		senderAlllowPermission.clickOkButton();
	}
	
	/**
	 * This method will be run after execution of all the test methods of this
	 * class. This method is used to close and release the appium driver.
	 */
	@AfterClass
	public void endTest() {
		releaseDriver();
	}

}

**Comment by mykola-mokhnach** [comment]
The error happens because the device with given id cannot be found in the list of connected devices. you can see the list of connected devices by executing `adb devices -l` command in terminal.

**Comment by mykola-mokhnach** [comment]
It would be good to have Appium log attached to the issue.

**Comment by mykola-mokhnach** [comment]
Closed due to missing activity
