### ISSUE TITLE
Crash after tap the "appium setting" app on device

### ISSUE THREAD

**Issue by liu3821** [appium/appium#8913]
Hi guys, long time no see, I have a new issue AGAIN.

## The problem
try to run script on real device. Crash after tap the "appium setting" app on device.

## Environment

* Appium version (or git revision) that exhibits the issue:
1.4.16
* Desktop OS/version used to run Appium:
window7 sp1
* Mobile platform/version under test:
android 5.1.1
* Real device or emulator/simulator:
real android phone:vivo x7
* Appium CLI or Appium.app|exe:
Appium.exe

## Detail
 "Error: /data/local/tmp/AppiumBootstrap.jar does not exist"(log)
actually I find the file name was "AppiumBootstrap.j" on real device.

## Link to Appium logs
sorry,  I can't access gist.github.com.
ignore Chinese Characters,the same script(same directory for install appium) woking fine on other machine.
log in attach file:
[log.txt](https://github.com/appium/appium/files/1171990/log.txt)

## Code To Reproduce Issue 
code with python3.5, just try to open app no special operation

**Comment by mykola-mokhnach** [comment]
Version 1.4.16 is not supported anymore. Please use 1.6.5 and remove Appium Aettings application from the device manually before installing the new Appium version.
