### ISSUE TITLE
Android Heads Up (and other system) Notifications - enhancements

### ISSUE THREAD

**Issue by yahman72** [appium/appium#8914]
## The problem
Handling heads up notifications (https://developer.android.com/guide/topics/ui/notifiers/notifications.html#Heads-up) is somewhat cumbersome with appium because one needs to open the notifications bar before accessing the heads up notification. 
However the heads up notifications are there so that the users don't have to open the notification bar before responding to them. 

For example the incoming call notification:
![image](https://user-images.githubusercontent.com/8724383/28568454-25296e6c-7136-11e7-8ac2-683e770868d7.png)
One could simply click on that "ANSWER" button to answer the call.
There are a couple of issues about the heads up notifications (#6324 and #5671) but they handle a bit different aspects of this topic. 

Now this is possible only like this:
<pre>
driver.open_notifications()
e = driver.find_element_by_xpath("//android.widget.Button[contains(@text, 'ANSWER')]")
e.click()
</pre>

The above code first opens the notification bar and then clicks on the "ANSWER" button, but IMHO this could be improved - because when automating/testing heads up notifications we actually just want to click on that "ANSWER" button without opening the notifications bar.
On the code level it could look like one of these options:
1) appiums checks if it finds a match with the locator in the app under test, if not it checks whether there are matches in heads up notifications (and possibly other systemui elements) that are visible on the screen.
This kind of "automatic check if there are heads up notifications visible" approach could also be used to fix #5671 i.e. avoid clicking heads up notifications by accident.
<pre>
e = driver.find_element_by_xpath("//android.widget.Button[contains(@text, 'ANSWER')]")
e.click()
</pre>

2) we instruct the driver to find a match in the in heads up notifications (and possibly other systemui elements) that are visible on the screen but we do not open the notifications bar before finding the element.
<pre>
driver.focus_notifications()
e = driver.find_element_by_xpath("//android.widget.Button[contains(@text, 'ANSWER')]")
e.click()
</pre>

This would be great if it's possible, but I'm not sure whether android itself supports this - the problem seems to be that one can set the uiautomator focus to the notifications bar only by opening them first. I.e. UIAutomator does not find that ANSWER button unless the notification bar is opened.

**Comment by mykola-mokhnach** [comment]
You're welcome to create a PR if you have ideas about how to implement this feature wither with UIA2 or espresso backends.

**Comment by jlipps** [comment]
> This would be great if it's possible, but I'm not sure whether android itself supports this

Yes, this is the question. Have you taken a uiautomatorviewer snapshot while the heads-up notification is present? Is there any way to mark it out specially in the XML?

**Comment by yahman72** [comment]
>  Have you taken a uiautomatorviewer snapshot while the heads-up notification is present? Is there any way to mark it out specially in the XML?

yes, it sees the XML but only when the "focus" is on the notification bar which in the current implementation happens after calling open_notifications(). 

I was thinking that there might be a way to change the "focus" in some other way than opening the notifications bar. Unfortunately I haven't been working with the automation components on the Android platform so I was hoping that some Android experts have some ideas how to do this, maybe with some fancy android locators that also find system UI's on the screen.

**Comment by jlipps** [comment]
@yahman72 calling `open_notifications` in Appium eventually triggers the [openNotification uiAutomator API](https://developer.android.com/reference/android/support/test/uiautomator/UiDevice.html#openNotification()). If the elements aren't visible without that, I'm not sure we have any way around using this API. I don't think elements which don't show up in a uiautomatorviewer snapshot can be found by any other fancy method, but there's a lot I don't know! Maybe @vrunoa would have an idea?

**Comment by vrunoa** [comment]
@jlipps @yahman72 for emulators we have a PR coming that will resolve the answer call issue, since we're adding support for handling phone calls. I'll check if there's something we can implement for real devices, notifications responds to intents so we can try finding out which intent should be triggered and calling it with adb. Same solution could work for any other app.

**Comment by jlipps** [comment]
thanks @vrunoa keep us updated!

**Comment by yahman72** [comment]
sounds good indeed @vrunoa! Is that PR already having a number

Could you elaborate a bit more about the plans i.e. how do you plan detect that heads-up dialog (as uiautomator doesn't seem to detect it).

**Comment by mykola-mokhnach** [comment]
I close this issue for now. UIA(2) provides quite limited support of notifications API and with Espresso one can use a backdoor endpoint for such purpose.
