### ISSUE TITLE
registering appium node with selenium server stopped working

### ISSUE THREAD

**Issue by vikramvi** [appium/appium#8916]
## The problem

- not able to launch app on android simulator which is registered as node to selenium hub
- appium 1.6.6-beta.3
- selenium-server-standalone-3.4.0.jar
- start selenium java -jar selenium-server-standalone-3.4.0.jar -role hub
- register appium node appium --nodeconfig device_1.json -p 4723 -bp 4724 -U emulator-5554
device_1.json
{"capabilities":[{"browserName":"Android","platformName":"ANDROID","maxInstances":1,"applicationName":"dummy_Android_1"}],"configuration":{"proxy":"org.openqa.grid.selenium.proxy.DefaultRemoteProxy","cleanUpCycle":2000,"port":4700,"host":"127.0.0.1","maxSession":1,"hubHost":"192.168.178.21","registerCycle":5000,"hubPort":4444,"timeout":30000,"register":true}} 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.6-beta.3
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium:  Mac 10.12.5
* Node.js version (unless using Appium.app|exe): v7.9.0
* Mobile platform/version under test: Android simulator
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

appium server for node log
https://gist.github.com/vikramvi/00c877d228edd1d0e8d74f7e984cc2de

Selenium Server log
https://gist.github.com/vikramvi/e564bf089f1c46487ff0d9d112e77e7d

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by vikramvi** [comment]
https://github.com/SeleniumHQ/selenium/issues/4142

selenium team has confirmed it's appium related issue

**Comment by mykola-mokhnach** [comment]
What is the terminal output for the command `/Users/vikram-anna/Library/Android/sdk/build-tools/25.0.0/aapt dump badging /Users/vikram-anna/Documents/Noa/Workspace/Mobile-Automation/Android-Automation/serenityAppiumFlipkart-JustinFrameworkMigrationToJava/ApiDemos-debug.apk` ?

**Comment by mykola-mokhnach** [comment]
Also, why **avd** capability is not used to start emulator?

**Comment by vikramvi** [comment]
@mykola-mokhnach please find below clarification

1. ApiDemos-debug.apk was not able to be installed on Android emulator; so I used another working one com.wunderkinder.wunderlistandroid.apk

1.1  With this apk does gets installed but still see the errors in selenium server logs
https://gist.github.com/vikramvi/731b286983640a784b9ddbb8f3c96fed

1.2 appium log
https://gist.github.com/vikramvi/731b286983640a784b9ddbb8f3c96fed

2. As I've kept Android emulator  in open state, didn't use **avd** caps

**Comment by mykola-mokhnach** [comment]
It looks like the grid didn't like our response for session creation request. @imurchie @jlipps  Any thoughts?

**Comment by vikramvi** [comment]
ping @imurchie @jlipps please review

**Comment by imurchie** [comment]
The grid is getting the following capabilities:
```json
{
  "capabilities": [
    {
      "desiredCapabilities": {
        "app": "/Users/vikram-anna/Documents/ApiDemos-debug.apk",
        "appPackage": "io.appium.android.apis",
        "noReset": true,
        "appWaitActivity": "io.appium.android.apis.ApiDemos",
        "platformName": "Android",
        "deviceName": "Android",
        "applicationName": "dummy_Android_1"
      }
    },
    {
      "requiredCapabilities": {}
    }
  ],
  "desiredCapabilities": {
    "app": "/Users/vikram-anna/Documents/ApiDemos-debug.apk",
    "appPackage": "io.appium.android.apis",
    "noReset": true,
    "appWaitActivity": "io.appium.android.apis.ApiDemos",
    "platformName": "Android",
    "deviceName": "Android",
    "applicationName": "dummy_Android_1"
  },
  "requiredCapabilities":{}
}
```

I have no idea why it is not liking this. The throwing code is https://github.com/SeleniumHQ/selenium/blob/master/java/server/src/org/openqa/grid/web/servlet/handler/WebDriverRequest.java#L66-L80

**Comment by yaphatak** [comment]
Well, look like this [PR](https://github.com/SeleniumHQ/selenium/commit/dc0d523c797434baeda6da62a793e83cfb143f9a) broke backward compatibility. This is 7 days old PR. @vikramvi , if you want to unblock yourself you can use little older grid binaries. I believe it should work.
Its broken because of this https://github.com/SeleniumHQ/selenium/blob/49c043c90331d083a2b9f268e370e2e1a5f47628/java/server/src/org/openqa/selenium/remote/server/NewSessionPayload.java#L171-L253, but its difficult to guess as code is little complicated, need to debug.

**Comment by imurchie** [comment]
@dpgraham You were working on capability compatibility with the W3C spec and whatnot, right? I think this falls into that.

**Comment by dpgraham** [comment]
@imurchie It could be due to `capabilities` and `desiredCapabilities` both being defined and it not handling that.

I can look into that today. It shouldn't reject the capabilities. I'll use the caps provided in this issue as a test case.

**Comment by jlipps** [comment]
@imurchie @dpgraham both being defined should be ok. Unfortunately what's inside of `capabilities` is not correct. It should be the two properties `alwaysMatch` and `firstMatch`, along with their appropriate contents. I'd say it should probably look like:

```json
{
  "capabilities": {
    "alwaysMatch": {
      "app": "/Users/vikram-anna/Documents/ApiDemos-debug.apk",
      "appPackage": "io.appium.android.apis",
      "noReset": true,
      "appWaitActivity": "io.appium.android.apis.ApiDemos",
      "platformName": "Android",
      "deviceName": "Android",
      "applicationName": "dummy_Android_1"
    }, "firstMatch": []
  },
  "desiredCapabilities": {
    "app": "/Users/vikram-anna/Documents/ApiDemos-debug.apk",
    "appPackage": "io.appium.android.apis",
    "noReset": true,
    "appWaitActivity": "io.appium.android.apis.ApiDemos",
    "platformName": "Android",
    "deviceName": "Android",
    "applicationName": "dummy_Android_1"
  },
  "requiredCapabilities":{}
}
```

Is this something we're creating, or what?

**Comment by TikhomirovSergey** [comment]
I suspect that there is the server side issue. It seems it doesn't work due to this fix: 
https://github.com/appium/java-client/pull/597
it is related to this issue: https://github.com/appium/java-client/issues/594

**Comment by jlipps** [comment]
excellent, thank you @TikhomirovSergey!

**Comment by TikhomirovSergey** [comment]
@jlipps 
So what the solution? Should I correct the client? Does the appium server support the `alwaysMatch` and `firstMatch`? Please take a look at the https://github.com/appium/java-client/issues/594

**Comment by jlipps** [comment]
@TikhomirovSergey yes, the server has been updated to support the new-style `capabilities` object. So it should be safe to update the client, though it means the client will only work with newer servers of course.

**Comment by TikhomirovSergey** [comment]
ok. We are planning to release 5.0.0 which has no deprecated code (it is really breaking release).

**Comment by jlipps** [comment]
makes sense, hooray for deleting code!

**Comment by mykola-mokhnach** [comment]
shall we also update other clients in such case. How about Ruby client and Python? @KazuCocoa @dpgraham

**Comment by KazuCocoa** [comment]
Ruby client hasn't supported the new capability yet, new style capability has been supported `selenium-webdriver 3.4.1+`, because we also need to update some methods to catch up with latest Ruby client version.

I've created issues for it, https://github.com/appium/ruby_lib/issues/501 , https://github.com/appium/ruby_lib/issues/558, and I'll start working to support it.

**Comment by vikramvi** [comment]
@TikhomirovSergey can you please let me know tentative date for 5.0.0 release ?

**Comment by dpgraham** [comment]
@mykola-mokhnach Yeah, we'll need to update the JS clients, PHP and Python

**Comment by KazuCocoa** [comment]
When I run with `selenium-webdriver3.4.3` and `selenium grid 3.4.0`, I encountered the following issue between selenium-webdriver's code and selenium grid's code.
So, in ruby client side, we should use under `selenium grid 3.3.x` until fix the following issue.

https://github.com/SeleniumHQ/selenium/issues/3808#issue-220806937

**Comment by jlipps** [comment]
@TikhomirovSergey any update on fixing the java client for this issue?

**Comment by jlipps** [comment]
@TikhomirovSergey with java-client 5.0.1 released, should this be considered resolved?

**Comment by SrinivasanTarget** [comment]
@jlipps Yes this is fixed in latest java-client.

**Comment by SrinivasanTarget** [comment]
@jlipps Nope, it isn't.

**Comment by TikhomirovSergey** [comment]
Guys, please close it. It was resolved here https://github.com/appium/java-client/pull/682
