### ISSUE TITLE
Appium no longer identifies ListView on Android.

### ISSUE THREAD

**Issue by greenejason** [appium/appium#8917]
## The problem

Using Visual Studio C# and Appium I open an emulator with Visual Studio to carry out automated tests on Android devices. The first test opens the login page, identifies all the elements and logs into the system with Username and Password. The main menu then appears which is a List View. Two weeks ago Appium was able to find the ListView and place items within the ListView into a list. It is now no longer able to find the ListView by its Id 'mainMenuListView and the test fails. I have tried using different methods such as ClassName and XPath but to no avail.

## Environment

* Appium version 1.6.5.
* Unsure if Appium version has updated.
* Using Windows 7:
* Using Visual Studio C#:
* Testing with Android:
* Using Android Studio Emulator.

## Code To Reproduce Issue

 AppiumWebElement element = dvr.FindElement(By.Id("mainMenuListView"));
                IList<AppiumWebElement> listViewElements = new List AppiumWebElement();
                listViewElements = element.FindElements(By.Id("list_item_text"));

**Comment by mykola-mokhnach** [comment]
Probably, it's time to switch to UIAutomation2

**Comment by mykola-mokhnach** [comment]
Also, what do you see in page source instead of the previous element?

**Comment by greenejason** [comment]
Can you tell me what difference UIAutomator2 will make.
Please see the path to the ListView below.
![image](https://user-images.githubusercontent.com/25926074/28617172-3ea2796c-71f7-11e7-93e9-806416145acb.png)

**Comment by mykola-mokhnach** [comment]
> Can you tell me what difference UIAutomator2 will make.

UIA2 is based on UIObject2 unlike UIA1, which is based on UIObject and is outdated. Also it is not supported by Google anymore is not expected to behave properly in recent Android versions.

**Comment by greenejason** [comment]
UIAutomator issue resolved this issue.
I had to reinstall Android Studio with UIAutomator2 driver and list the driver in my capabilities.
Thanks.
