### ISSUE TITLE
UiAutomator locating with getChildByText runs into endless loop

### ISSUE THREAD

**Issue by oscheller1** [appium/appium#8921]
## The problem

Searching with uiautomator strategy using `getChildByText` makes appium run into an endless loop.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Last Appium version that did not exhibit the issue (if applicable): -
* Desktop OS/version used to run Appium: Mac OS Sierra
* Node.js version (unless using Appium.app|exe): npm 4.2.0
* Mobile platform/version under test: Android 7.0
* Real device or emulator/simulator: real device Pixel C
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs

Appium server log:
https://gist.github.com/oscheller1/0ae20af66a3642521cde7ffa1ee25bdf

The last part of the log shows the endless loop, e.g. 
```
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Element[] is null: (9701)
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements tmp selector:UiSelector[INSTANCE=9701, CONTAINER=UiSelector[SCROLLABLE=true], PATTERN=UiSelector[INSTANCE=2, PATTERN=UiSelector[CLASS=android.widget.RelativeLayout]]]
```

## Code To Reproduce Issue [ Good To Have ]

Execute a search by uiautomator that searches inside a UiCollection for a UiObject that has a particular child which has set a particular text. E.g. 
```
new UiScrollable(new UiSelector().scrollable(true)).getChildByText(new UiSelector().className("android.widget.RelativeLayout"), "Backofen")
```

P.s.

On that note, 

see  documentation for `getChildByText`: https://developer.android.com/reference/android/support/test/uiautomator/UiCollection.html#getChildByText(android.support.test.uiautomator.UiSelector, java.lang.String)

Then see appium documentation: https://appium.readthedocs.io/en/stable/en/writing-running-appium/uiautomator_uiselector/ that says:
```
Find the first scrollable element, then find a TextView with the text "Tabs". The "Tabs" element will be scrolled into view.

# ruby
element = find_element(:uiautomator, 'new UiScrollable(new UiSelector().scrollable(true).instance(0)).getChildByText(new UiSelector().className("android.widget.TextView"), "Tabs")')
```
which does not match the explained functionality of `getChildByText` on the android docs. Should it work like the android docs say, or does it work as described in the appium docs?

From my understanding, the query from above (under 'Code To Reproduce Issue') should find a relative layout that has some child (or even descendant) element with a text property of `Backofen`. The relative layout should be inside a scrollable container. Appium should return the relative layout as a webdriver element, and NOT the text element.

There are multiple relative layouts in that container, and the query shall find the one that includes that particular text as a child (or descendant) element.

**Comment by jlipps** [comment]
@oscheller1 I'm not sure I agree. Doesn't `getChildByText` return a `UiObject`? Seems to me that's what I would expect to be returned as a result of this call...?

**Comment by oscheller1** [comment]
For some reason I can not get `getChildByText` to work at all.

An easy command like the following outputs an error: 
```
new UiScrollable(new UiSelector().scrollable(true)).getChildByText(new UiSelector().className("android.widget.TextView"), "Register")
```

Error Appium Log:

```
[debug] [AndroidBootstrap] [UIAUTO STDOUT] java.lang.reflect.InvocationTargetException
[debug] [AndroidBootstrap] [UIAUTO STDOUT] 	at java.lang.reflect.Method.invoke(Native Method)
[debug] [AndroidBootstrap] [UIAUTO STDOUT] 	at io.appium.android.bootstrap.utils.UiScrollableParser.applyArgsToMethod(UiScrollableParser.java:285)
[debug] [AndroidBootstrap] [UIAUTO STDOUT] 	at io.appium.android.bootstrap.utils.UiScrollableParser.consumeFunctionCall(UiScrollableParser.java:188)
[debug] [AndroidBootstrap] [UIAUTO STDOUT] 	at io.appium.android.bootstrap.utils.UiScrollableParser.parse(UiScrollableParser.java:68)
[debug] [AndroidBootstrap] [UIAUTO STDOUT] 	at io.appium.android.bootstrap.utils.UiAutomatorParser.consumeStatement(UiAutomatorParser.java:98)
[debug] [AndroidBootstrap] [UIAUTO STDOUT] 	at io.appium.android.bootstrap.utils.UiAutomatorParser.parse(UiAutomatorParser.java:45)
[debug] [AndroidBootstrap] [UIAUTO STDOUT] 	at io.appium.android.bootstrap.handler.Find.getSelectors(Find.java:368)
[debug] [AndroidBootstrap] [UIAUTO STDOUT] 	at io.appium.android.bootstrap.handler.Find.execute(Find.java:148)
[debug] [AndroidBootstrap] [UIAUTO STDOUT] 	at io.appium.android.bootstrap.handler.Find.execute(Find.java:109)
[debug] [AndroidBootstrap] [UIAUTO STDOUT] 	at io.appium.android.bootstrap.AndroidCommandExecutor.execute(AndroidCommandExecutor.java:81)
[debug] [AndroidBootstrap] [UIAUTO STDOUT] 	at io.appium.android.bootstrap.SocketServer.runCommand(SocketServer.java:203)
[debug] [AndroidBootstrap] [UIAUTO STDOUT] 	at io.appium.android.bootstrap.SocketServer.handleClientData(SocketServer.java:105)
[debug] [AndroidBootstrap] [UIAUTO STDOUT] 	at io.appium.android.bootstrap.SocketServer.listenForever(SocketServer.java:159)
[debug] [AndroidBootstrap] [UIAUTO STDOUT] 	at io.appium.android.bootstrap.Bootstrap.testRunServer(Bootstrap.java:37)
[debug] [AndroidBootstrap] [UIAUTO STDOUT] 	at java.lang.reflect.Method.invoke(Native Method)
[debug] [AndroidBootstrap] [UIAUTO STDOUT] 	at junit.framework.TestCase.runTest(TestCase.java:168)
[debug] [AndroidBootstrap] [UIAUTO STDOUT] 	at junit.framework.TestCase.runBare(TestCase.java:134)
[debug] [AndroidBootstrap] [UIAUTO STDOUT] 	at junit.framework.TestResult$1.protect(TestResult.java:115)
[debug] [AndroidBootstrap] [UIAUTO STDOUT] 	at junit.framework.TestResult.runProtected(TestResult.java:133)
[debug] [AndroidBootstrap] [UIAUTO STDOUT] 	at junit.framework.TestResult.run(TestResult.java:118)
[debug] [AndroidBootstrap] [UIAUTO STDOUT] 	at junit.framework.TestCase.run(TestCase.java:124)
[debug] [AndroidBootstrap] [UIAUTO STDOUT] 	at com.android.uiautomator.testrunner.UiAutomatorTestRunner.start(UiAutomatorTestRunner.java:160)
[debug] [AndroidBootstrap] [UIAUTO STDOUT] 	at com.android.uiautomator.testrunner.UiAutomatorTestRunner.run(UiAutomatorTestRunner.java:96)
[debug] [AndroidBootstrap] [UIAUTO STDOUT] 	at com.android.commands.uiautomator.RunTestCommand.run(RunTestCommand.java:91)
[debug] [AndroidBootstrap] [UIAUTO STDOUT] 	at com.android.commands.uiautomator.Launcher.main(Launcher.java:83)
[debug] [AndroidBootstrap] [UIAUTO STDOUT] 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
[debug] [AndroidBootstrap] [UIAUTO STDOUT] 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:251)
[debug] [AndroidBootstrap] [UIAUTO STDOUT] Caused by: com.android.uiautomator.core.UiObjectNotFoundException: UiSelector[INSTANCE=0, SCROLLABLE=true]
[debug] [AndroidBootstrap] [UIAUTO STDOUT] 	at com.android.uiautomator.core.UiScrollable.scrollBackward(UiScrollable.java:495)
[debug] [AndroidBootstrap] [UIAUTO STDOUT] 	at com.android.uiautomator.core.UiScrollable.scrollToBeginning(UiScrollable.java:543)
[debug] [AndroidBootstrap] [UIAUTO STDOUT] 	at com.android.uiautomator.core.UiScrollable.scrollToBeginning(UiScrollable.java:562)
[debug] [AndroidBootstrap] [UIAUTO STDOUT] 	at com.android.uiautomator.core.UiScrollable.scrollIntoView(UiScrollable.java:264)
[debug] [AndroidBootstrap] [UIAUTO STDOUT] 	at com.android.uiautomator.core.UiScrollable.getChildByText(UiScrollable.java:212)
[debug] [AndroidBootstrap] [UIAUTO STDOUT] 	at com.android.uiautomator.core.UiScrollable.getChildByText(UiScrollable.java:189)
[debug] [AndroidBootstrap] [UIAUTO STDOUT] 	... 27 more
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":9,"value":"Could not parse UiSelector argument: problem using reflection to call this method"}
```

I don't run into any problems using `scrollIntoView` like this 
```
new UiScrollable(new UiSelector().scrollable(true)).scrollIntoView(new UiSelector().className("android.widget.TextView").text("Register"))
```

Could there be a basic problem with `getChildByText` ?

**Comment by oscheller1** [comment]
To elaborate a bit further why I need this:
Here's a UI layout in our Android app. I need to identify the "+" button based on the unique identifier inside the relative layout. All of the "+" butons in the list have the same resource ID. See this image: http://imgur.com/biye7N5

To do this with uiautomator, I think there's no way around using `getChildByText`, I had no luck so far though. I might have to shift to using xpath for this, which I want to avoid.

**Comment by jlipps** [comment]
It may be a problem with `getChildByText` then. In principle xpath shouldn't be that much worse than doing it this way, just has a bit more overhead. Does it make it obviously worse for your test?

**Comment by oscheller1** [comment]
In our case we've built a small python framework using different layers of abstraction to create automation queries that are then executed by Appium. Our Android handler is currently based solely on UI Automation, so switching to a xpath solution here will create a high level of customization for that particular part.

**Comment by jlipps** [comment]
@oscheller1 the only thing I can recommend right now is to reconstruct the query in UiAutomator Java and see if you get a weird response that could explain Appium's behavior

**Comment by jlipps** [comment]
closing for now since I can't think of anything to try and fix in appium
