### ISSUE TITLE
[Android]:Displaying [HTTP] <-- POST /wd/hub/session 500 12 ms - 193  fail launch application

### ISSUE THREAD

**Issue by chennareddy08** [appium/appium#8923]
## The problem
[Android]:Displaying [HTTP] <-- POST /wd/hub/session 500 12 ms - 193  fail launch application

Loglink:https://gist.github.com/chennareddy08/1404e4fa80e09daca82a495061648f42

               
## Environment
 'app': app,
                'platformName': 'Android',
                'platformVersion': '6.0.1',
                'deviceName': '4210ecd7c21ba3d7'

## Link to Appium logs
https://gist.github.com/chennareddy08/1404e4fa80e09daca82a495061648f42

**Comment by mykola-mokhnach** [comment]
It looks like you are trying to initiate a new session while another one is still in progress. Try to execute appium server with _--session-override_ argument

**Comment by chennareddy08** [comment]
tried no luck

**Comment by mykola-mokhnach** [comment]
> file:///Applications/Appium.app/Contents/Resources/app/app/renderer/styles/github-gist.css Failed to load resource: net::ERR_FILE_NOT_FOUND

This error is not related to Appium and could be a bug of Appium Desktop application itself. Here's its bug tracker: https://github.com/appium/appium-desktop/issues

**Comment by chennareddy08** [comment]
Even this is happening when running appium from terminal (the log shown from terminal only)

**Comment by jlipps** [comment]
@chennareddy08 why are you sending a new session request while another session is in progress?

**Comment by chennareddy08** [comment]
I am not sending new  new session request

**Comment by imurchie** [comment]
Something in your code is, though. See https://gist.github.com/chennareddy08/1404e4fa80e09daca82a495061648f42#file-gistfile1-txt-L172-L181

**Comment by chennareddy08** [comment]
worked so closing issue

**Comment by chennareddy08** [comment]
Thank you for help

**Comment by shravan999** [comment]
I am facing same issue. What was the fix? @chennareddy08

**Comment by risinek** [comment]
What does `appium-doctor` say? (`npm install -g appium-doctor`)

**Comment by dswarnanil** [comment]
KrishnakumarAS - I faced the same issue and the reason was I was using host as 0.0.0.0 while starting the Appium server, I replaced it with 127.0.0.1 and it worked.
You may try and check once

**Comment by QolsysAuto** [comment]
My issue was the UDID (device name) was inputted incorrectly in the appium config.
