### ISSUE TITLE
Can not get CPU info&Memory info when running appium

### ISSUE THREAD

**Issue by Dan2712** [appium/appium#8924]
## The problem

When running a test case, can I get the the system info, like cpu&heap info, using shell command(“adb shell dumpsys meminfo xxxx”)?

I was trying to do this, but always get the error below.

daemon not running. starting it now on port 5038 *
daemon started successfully *
error: device not found

Is it because appium occupyed the port, so cannot do other adb operation?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows 7
* Node.js version (unless using Appium.app|exe): 3.10.8
* Mobile platform/version under test: Android 5.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:

**Comment by mykola-mokhnach** [comment]
Running another adb command should not be a problem. Try to explicitly set the port number and device id as adb arguments.

**Comment by imurchie** [comment]
Appium supports getting performance data. See https://github.com/appium/java-client/blob/a41dca1fd5737261b06801e1c265c03ff5960a95/src/test/java/io/appium/java_client/android/AndroidDriverTest.java#L148-L182

**Comment by jlipps** [comment]
the adb daemon often crashes. sometimes running `adb kill-server && adb devices` fixes it. But yes if you want performance data, you can just use Appium too!
