### ISSUE TITLE
uiautomator2 driver extracts wrong strings.xml when locale is configured

### ISSUE THREAD

**Issue by drhoet** [appium/appium#8930]
## The problem

When Appium is started with a language + locale, the getStrings command loads the wrong strings resource file.

## Environment

* Appium version (or git revision) that exhibits the issue: Appium 1.6.3 + uiautomator2-driver 0.2.3
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Windows 7
* Node.js version (unless using Appium.app|exe): v6.9.1
* Mobile platform/version under test: Android (all versions)
* Real device or emulator/simulator: Both
* Appium CLI or Appium.app|exe: Appium java client

## Details

When launching the app, the appium-uiautomator2-driver extracts a strings.xml file from the apk and uploads it to the device. This is done with the language that is configured in the Appium capabilities. When a locale is also configured, this is not taken into account (see [driver.js#314](https://github.com/appium/appium-uiautomator2-driver/blob/e919d73b8c135cd290689c56d550eb78280b734a/lib/driver.js#L314)).

The appium-android-driver however does take the locale into account when starting the app, switching the simulator to the correct language + region. (See [here](https://github.com/appium/appium-android-driver/blob/d9af06b70d5e6247aee69eccc1d6b6c610c794b6/lib/android-helpers.js#L66)). This results in a mismatch between device locale and extracted strings.xml.

## Link to Appium logs
[Appium log](https://gist.github.com/drhoet/9ff9883739e0234af920c46e74a01ff0#file-appium-log)

## Code To Reproduce Issue
```
import static org.junit.Assert.assertEquals;

import java.net.MalformedURLException;
import java.net.URL;

import io.appium.java_client.remote.MobileCapabilityType;
import io.appium.java_client.remote.MobilePlatform;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.remote.DesiredCapabilities;

import com.bosch.sh.systemtest.appium_driver.AndroidDriver;

public class GetStringsTest
{

   private AndroidDriver driver;

   @Before
   public void setup() throws MalformedURLException
   {
      final DesiredCapabilities capabilities = new DesiredCapabilities();
      capabilities.setCapability( MobileCapabilityType.AUTOMATION_NAME, "uiautomator2" );
      capabilities.setCapability( MobileCapabilityType.PLATFORM_NAME, MobilePlatform.ANDROID );
      capabilities.setCapability( MobileCapabilityType.DEVICE_NAME, "Nexus_9_API_23" );
      capabilities.setCapability( MobileCapabilityType.APP, "C:\\temp\\VodQA.apk" );

      capabilities.setCapability( MobileCapabilityType.LANGUAGE, "fr" );
      capabilities.setCapability( MobileCapabilityType.LOCALE, "CA" );

      driver = new AndroidDriver<>( new URL( "http://127.0.0.1:4723/wd/hub" ), capabilities );
   }

   @Test
   public void testGetStrings()
   {
      assertEquals( "Terminé", driver.getAppStringMap().get( "abc_action_mode_done" ) );
   }
}
```

**Comment by jlipps** [comment]
@drhoet are you saying that android-driver is doing the right thing but uiautomator2-driver is not?

**Comment by drhoet** [comment]
@jlipps I think the android-driver has the same issue.
The [ensureDeviceLocale](https://github.com/appium/appium-android-driver/blob/d9af06b70d5e6247aee69eccc1d6b6c610c794b6/lib/android-helpers.js#L66) method (a method from android-driver that I believe is used by the uiautomator2-driver) seems to do the right thing. When extracting the strings.xml however, I think both android-driver (see [here](https://github.com/appium/appium-android-driver/blob/d9af06b70d5e6247aee69eccc1d6b6c610c794b6/lib/driver.js#L326)) and uiautomator2-driver (see [here](https://github.com/appium/appium-uiautomator2-driver/blob/e919d73b8c135cd290689c56d550eb78280b734a/lib/driver.js#L314)) have the same issue.

**Comment by jlipps** [comment]
OK thanks, good to know. We'll fix it in both places then.

**Comment by zavvio** [comment]
I hope issue[1] in #9181 could also be fixed when this gets resolved; keeping a close eye here.

**Comment by imurchie** [comment]
Can you try the latest code (install with `npm uninstall -g appium && npm install -g appium --no-shrinkwrap`)?

**Comment by zavvio** [comment]
Tried that, got appium@1.7.0 & appium-uiautomator2-driver@0.6.4
Result is app_strings("en-rUS") could only return strings from _values-en-rUS_ but not default values from both _values-en_ and _values_.

i.e.
Expected behavior: app_strings would return ALL string values, including default values, language values and region/country values;
Actual behavior: app_strings only return region values.
