### ISSUE TITLE
Can't get pageSoure of some Pages

### ISSUE THREAD

**Issue by shulinlimiandiulexie** [appium/appium#8934]
## The problem

Have you ever had a problem like that ,I can't locate some elements  have resource-id by 'driver.findElementById()'. and can't  get pageSoure of some page. The program will enter the waiting room but will not report the errorBut elsewhere it is normal,
Some pages are normal and some pages will fail,Will it be a version issue,Maybe it's a configuration problem that I haven't noticed

caps.setCapability("automationName", "Appium");
		 caps.setCapability("deviceName", "33137a32");
		 caps.setCapability("platformName", "Android"); 
		 caps.setCapability("platformVersion", "7.0"); 
		 caps.setCapability("udid", "33137a32")
		 caps.setCapability("noReset", true);

**Comment by mykola-mokhnach** [comment]
This is most likely the issue of UIAutomation backend. Try to use UIAutomation2 instead.
