### ISSUE TITLE
Unexpected error. The URL '/wd/hub/session//element' did not map to a valid resource

### ISSUE THREAD

**Issue by CharanpreetHora** [appium/appium#8935]
## Unexpected error. The URL '/wd/hub/session//element' did not map to a valid resource

I am using latest appium 1.6.5 desktop version. with selenium c#.

Also using Visual Studio 2013. I am able to execute tests successfully while executing individually. Also if test are written in one single method then also all test are working fine.

But while executing the same from test explorer window not individually all in one go, only 1st test script executes successfully for rest others I am getting following error:-
OpenQA.Selenium.WebDriverException: Unexpected error. The URL '/wd/hub/session//element' did not map to a valid resource
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Appium.AppiumDriver`1.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(String mechanism, String value)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElementById(String id)
   at OpenQA.Selenium.By.<>c__DisplayClass2.<Id>b__0(ISearchContext context)
   at OpenQA.Selenium.By.FindElement(ISearchContext context)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(By by)
   at OpenQA.Selenium.Support.PageObjects.DefaultElementLocator.LocateElement(IEnumerable`1 bys)
   at OpenQA.Selenium.Support.PageObjects.WebElementProxy.get_Element()
   at OpenQA.Selenium.Support.PageObjects.WebElementProxy.Invoke(IMessage msg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at OpenQA.Selenium.IWebElement.Click() 

## Environment

* Appium version 1.6.5
* Desktop OS/version used to run Appium: windows 7
*Android device Samsung s5
* Real device 
* Appium.exe

Using following capabilities code from config file:-
<capability name="app" value="C:\\Project files\\c.5.apk" />
<capability name="appPackage" value="com.carnival.android" />
<capability name="platformName" value="Android" />
<capability name="automationName" value="Appium" />
<capability name="platformVersion" value="5.0"/>
<capability name="deviceName" value="36b29617" />
<capability name="appActivity" value="com.test.android.activities.SplashScreenActivity" />
<remoteServerAddress>http://127.0.0.1:4723/wd/hub</remoteServerAddress>

**Comment by mykola-mokhnach** [comment]
the error is thrown because session id is missing in the URL. We don't support parallel testing officially and don't verify it.

**Comment by CharanpreetHora** [comment]
But this is not parallel testing. This is sequential testing only. I am able to see my first script executed successfully. Second script invoked and then closed abruptly. After this 3rd script invoked and terminated abruptly and so on.. Is this parallel testing? I am able to see session id is missing. Not sure how to proceed with this. That means VIsual Studio do not supports Appium if user is trying to run sequential tests.  As I explained in the detail that while writing all the scripts in one method is working flawlessly. Kindly help me in this.

**Comment by mykola-mokhnach** [comment]
It is not possible to say anything for sure without having a log

**Comment by CharanpreetHora** [comment]
Logs are already posted in the description. Do you need any other log.

**Comment by mykola-mokhnach** [comment]
The description only contains error traceback. And we need Appium server log

**Comment by CharanpreetHora** [comment]
Please find attached appium logs. It seems session is getting deleted and removed after first script get executed. Not sure how I need to make session active in visual studio until all the scripts are executed.

[AndroidBootstrap] Sending command to android: {"cmd":"action","action":"element:click","params":{"elementId":"2"}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:click","params":{"elementId":"2"}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: click
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":true}
[AndroidBootstrap] Received command result from bootstrap
[MJSONWP] Responding to client with driver.click() result: true
[HTTP] <-- POST /wd/hub/session/da3e68b8-eef2-4012-a4d7-55507d4fb9d7/element/2/click 200 860 ms - 76 
[HTTP] --> POST /wd/hub/session/da3e68b8-eef2-4012-a4d7-55507d4fb9d7/timeouts {"type":"implicit","ms":0}
[MJSONWP] Calling AppiumDriver.timeouts() with args: ["implicit",0,"da3e68b8-eef2-4012-a4d7-55507d4fb9d7"]
[BaseDriver] Set implicit wait to 0ms
[MJSONWP] Responding to client with driver.timeouts() result: null
[HTTP] <-- POST /wd/hub/session/da3e68b8-eef2-4012-a4d7-55507d4fb9d7/timeouts 200 1 ms - 76 
[HTTP] --> POST /wd/hub/session/da3e68b8-eef2-4012-a4d7-55507d4fb9d7/element {"using":"xpath","value":"//android.widget.ImageView[contains(@resource-id,'com.carnival.android:id/loading_spinner')]"}
[MJSONWP] Calling AppiumDriver.findElement() with args: ["xpath","//android.widget.ImageView[contains(@resource-id,'com.carnival.android:id/loading_spinner')]","da3e68b8-eef2-4012-a4d7-55507d4fb9d7"]
[BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[BaseDriver] Waiting up to 0 ms for condition
[AndroidBootstrap] Sending command to android: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"//android.widget.ImageView[contains(@resource-id,'com.carnival.android:id/loading_spinner')]","context":"","multiple":false}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"//android.widget.ImageView[contains(@resource-id,'com.carnival.android:id/loading_spinner')]","context":"","multiple":false}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: find
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding '//android.widget.ImageView[contains(@resource-id,'com.carnival.android:id/loading_spinner')]' using 'XPATH' with the contextId: '' multiple: false
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":7,"value":"Could not find an element using supplied strategy. "}
[AndroidBootstrap] Received command result from bootstrap
[HTTP] <-- POST /wd/hub/session/da3e68b8-eef2-4012-a4d7-55507d4fb9d7/element 500 151 ms - 164 
[HTTP] --> POST /wd/hub/session/da3e68b8-eef2-4012-a4d7-55507d4fb9d7/timeouts {"type":"implicit","ms":45000}
[MJSONWP] Calling AppiumDriver.timeouts() with args: ["implicit",45000,"da3e68b8-eef2-4012-a4d7-55507d4fb9d7"]
[BaseDriver] Set implicit wait to 45000ms
[MJSONWP] Responding to client with driver.timeouts() result: null
[HTTP] <-- POST /wd/hub/session/da3e68b8-eef2-4012-a4d7-55507d4fb9d7/timeouts 200 4 ms - 76 
[HTTP] --> POST /wd/hub/session//element {"using":"id","value":"com.carnival.android:id/folio_number"}
[HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- POST /wd/hub/session//element 404 0 ms - 66 
[HTTP] --> GET /wd/hub/session/da3e68b8-eef2-4012-a4d7-55507d4fb9d7/url {}
[MJSONWP] Calling AppiumDriver.getUrl() with args: ["da3e68b8-eef2-4012-a4d7-55507d4fb9d7"]
[HTTP] <-- GET /wd/hub/session/da3e68b8-eef2-4012-a4d7-55507d4fb9d7/url 501 1 ms - 122 
[HTTP] --> DELETE /wd/hub/session/da3e68b8-eef2-4012-a4d7-55507d4fb9d7 {}
[MJSONWP] Calling AppiumDriver.deleteSession() with args: ["da3e68b8-eef2-4012-a4d7-55507d4fb9d7"]
[BaseDriver] Event 'quitSessionRequested' logged at 1501277616480 (17:33:36 GMT-0400 (Eastern Daylight Time))
[AndroidDriver] Shutting down Android driver
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'C:\Users\charanpreeth\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","36b29617","shell","am","force-stop","com.carnival.android"]
[ADB] Pressing the HOME button
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'C:\Users\charanpreeth\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","36b29617","shell","input","keyevent",3]
[AndroidBootstrap] Sending command to android: {"cmd":"shutdown"}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"shutdown"}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type SHUTDOWN
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":"OK, shutting down"}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Closed client connection
[AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: numtests=1

[AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: stream=.

[AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner

[AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: test=testRunServer

[AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap

[AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: current=1

[AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS_CODE: 0

[AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: stream=

[AndroidBootstrap] [UIAUTO STDOUT] Test results for WatcherResultPrinter=.

[AndroidBootstrap] [UIAUTO STDOUT] Time: 9.346

[AndroidBootstrap] [UIAUTO STDOUT] OK (1 test)

[AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS_CODE: -1

[AndroidBootstrap] Received command result from bootstrap
[UiAutomator] Shutting down UiAutomator
[UiAutomator] Moving to state 'stopping'
[UiAutomator] UiAutomator shut down normally
[UiAutomator] Moving to state 'stopped'
[ADB] Attempting to kill all uiautomator processes
[ADB] Getting all processes with uiautomator
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'C:\Users\charanpreeth\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","36b29617","shell","ps"]
[ADB] No uiautomator process found to kill, continuing...
[UiAutomator] Moving to state 'stopped'
[Logcat] Stopping logcat capture
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'C:\Users\charanpreeth\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","36b29617","shell","am","force-stop","io.appium.unlock"]
[AndroidDriver] Not cleaning generated files. Add `clearSystemFiles` capability if wanted.
[Appium] Removing session da3e68b8-eef2-4012-a4d7-55507d4fb9d7 from our master session list
[BaseDriver] Event 'quitSessionFinished' logged at 1501277618588 (17:33:38 GMT-0400 (Eastern Daylight Time))
[MJSONWP] Received response: null
[MJSONWP] But deleting session, so not returning
[MJSONWP] Responding to client with driver.deleteSession() result: null
[HTTP] <-- DELETE /wd/hub/session/da3e68b8-eef2-4012-a4d7-55507d4fb9d7 200 2109 ms - 76 
[HTTP] --> DELETE /wd/hub/session/ {}
[HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- DELETE /wd/hub/session/ 404 0 ms - 58

**Comment by mykola-mokhnach** [comment]
Can you also show the part of client code where element with the id com.carnival.android:id/folio_number is queried?

**Comment by CharanpreetHora** [comment]
[FindsBy(How = How.Id, Using = "com.carnival.android:id/folio_number")]
        private IWebElement ll_folionumber = null;
string folioNum = DataTable.GetData("TESTApp", "FolioNumber");
ll_folionumber.Click();
                    ll_folionumber.Clear();
                    ll_folionumber.SendKeys(folioNum);

**Comment by mykola-mokhnach** [comment]
@TikhomirovSergey might it be there is a bug in C#'s client PageObject implementation?

**Comment by jlipps** [comment]
looks like you're setting an `IWebElement` to null and then calling methods on it. How does that work? Or does the annotation fill the value? At any rate this is not an Appium issue; the client is simply not sending a session ID during the find. Going to close this here, you probably want to open the issue at the C# client repo.

**Comment by CharanpreetHora** [comment]
This forum is awesome. I am able to resolve the issue. I have done minor changes in my script. Included App driver instance in all the reusable the classes where  App driver objects are used.
AppDriver = (AppiumDriver<IWebElement>)Driver.Get();
