### ISSUE TITLE
A new session could not be created

### ISSUE THREAD

**Issue by samik1233** [appium/appium#8939]
## Environment
* Appium v1.6.5
* Windows 10
*Mi Redmi Note 3 .Android 6.0.1 MMB29M
* Real Device

## Link to Appium logs
https://gist.github.com/samik1233/aca2990260aad223f6ec9dc33dfceb4d.j

**Comment by lolotoms** [comment]
Hi, 
I think error is clear. You need to have deviceName Capabilities when you run your appium server. Could you share your appium server run code and your test code? I can't acces your appium logs, could you send it again?
