### ISSUE TITLE
Cant clone/install appium beta

### ISSUE THREAD

**Issue by j0hnsa** [appium/appium#8943]
## The problem

When trying to clone install appium EINTEGRITY error is thrown and cant start node:

PS C:\Users\xxxxxxxxxx\appium-cln\appium> npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: core-js@2.4.1 (node_modules\babel-helpers\node_modules\core-js):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, utime 'C:\Users\xxxxxxx\appium-cln\appium\node_modules\.staging\core-js-4da4bed7\fn\array\push.js'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: core-js@2.4.1 (node_modules\babel-register\node_modules\core-js):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, utime 'C:\Users\xxxxxxxxxxxx\appium-cln\appium\node_modules\.staging\core-js-10dda52e\fn\string\virtual\sub.js'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: core-js@2.4.1 (node_modules\isparta\node_modules\core-js):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, utime 'C:\Users\xxxxxx\appium-cln\appium\node_modules\.staging\core-js-094ea94a\fn\string\virtual\trim-start.
js'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: core-js@2.4.1 (node_modules\babel-generator\node_modules\core-js):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, utime 'C:\Users\xxxxxxxxxx\appium-cln\appium\node_modules\.staging\core-js-ce42e1dd\library\fn\set-interval.js'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: core-js@2.4.1 (node_modules\babel-messages\node_modules\core-js):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, utime 'C:\Users\xxxxxxx\appium-cln\appium\node_modules\.staging\core-js-ac4c441c\fn\object\get-own-property-de
scriptors.js'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: core-js@1.2.7 (node_modules\core-js):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, utime 'C:\Users\xxxxxxxxx\appium-cln\appium\node_modules\.staging\core-js-11a56730\library\fn\array\filter.js'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: core-js@2.4.1 (node_modules\babel-template\node_modules\core-js):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, utime 'C:\Users\xxxxxxx\appium-cln\appium\node_modules\.staging\core-js-73b4dffb\library\fn\get-iterator.js'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: core-js@2.4.1 (node_modules\babel-types\node_modules\core-js):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: EEXIST: file already exists, mkdir 'C:\Users\xxxxxxxxxx\appium-cln\appium\node_modules\.staging\core-js-9c80adaf'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: File exists: C:\Users\xxxxxxxx\appium-cln\appium\node_modules\.staging\core-js-9c80adaf
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: core-js@2.4.1 (node_modules\babel-traverse\node_modules\core-js):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, utime 'C:\Users\xxxxxxx\appium-cln\appium\node_modules\.staging\core-js-88084199\fn\map.js'

npm ERR! code EINTEGRITY
npm ERR! sha1-TvgOjJGpXBlcgXPJToRE9NJsa4c= integrity checksum failed when using sha1: wanted sha1-TvgOjJGpXBlcgXPJToRE9NJsa4c= but got sha1-bSqiOaFzP/KPXBmsuSD5Gqoz/Pw=. (629892 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxxxxxxx\AppData\Roaming\npm-cache\_logs\2017-07-31T11_23_24_234Z-debug.log
PS C:\Users\xxxxxxxxxxx\appium-cln\appium> node .
module.js:471
    throw err;
    ^

Error: Cannot find module 'C:\Users\xxxxxxxxx\appium-cln\appium'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
PS C:\Users\xxxxxxx\appium-cln\appium>

## Environment

* Appium version (or git revision) that exhibits the issue: clone of 1.6.6-beta.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:Windows 10
* Node.js version (unless using Appium.app|exe): v6.11.0
* Mobile platform/version under test: Android 7/6
* Real device or emulator/simulator: Real
* Appium CLI or Appium.app|exe:

what should I do?

Thanks and Regards

**Comment by imurchie** [comment]
Can you paste `C:\Users\it140258\AppData\Roaming\npm-cache_logs\2017-07-31T11_23_24_234Z-debug.log` into a [gist](https://gist.github.com) and link it here?

**Comment by j0hnsa** [comment]
Hi @imurchie,

Thanks for the quick reply, here is the gist:
<script src="https://gist.github.com/j0hnsa/e13f879071d41722bcc1a207274e0e17.js"></script>

Regards

**Comment by imurchie** [comment]
Can you try the things suggested here: https://github.com/npm/npm/issues/16861

**Comment by j0hnsa** [comment]
Hi @imurchie 

That did the trick thanks,

Regards
