### ISSUE TITLE
Expose installApp command in UiAutomator2 driver

### ISSUE THREAD

**Issue by Prasant-Sutaria** [appium/appium#8946]
The test are not getting driver on Emulators when the app is not already installed on Emulator. The install_app method is throwing error with response code 500.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.6-beta.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MAC 10.11.6
* Node.js version (unless using Appium.app|exe): 7.4.0
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: Appium CLI

## Details
While running test on Android 7 with automationName=uiautomator2, the test runs fine if the app is already installed on Emulator but if the app is not already installed the install_app method is throwing error response code 500.

## Link to Appium logs
https://gist.github.com/Prasant-Sutaria/7b77b435835b16f01f87b46a1308e34f

## Code To Reproduce Issue [ Good To Have ]
Instantiate driver on Android.

**Comment by mykola-mokhnach** [comment]
UIA2 just does not implement this endpoint. 

@jlipps should the endpoint be supported by UIA2?

**Comment by jlipps** [comment]
@mykola-mokhnach, yes, I will consider this an enhancement request.

@Prasant-Sutaria why are you using `installApp`? Appium will also install the app when you pass it in via the `app` capability, regardless of whether it's already installed.

**Comment by Prasant-Sutaria** [comment]
@jlipps app desired capability is failing due to same install_app method. After driver is initialized we are checking whether app is available on the device. If the result is false we are calling installApp.

**Comment by jlipps** [comment]
@Prasant-Sutaria are you saying that an empty test which just starts a session and runs no commands, on a device which doesn't have the app installed, is failing? If so can you provide logs for that?

**Comment by mykola-mokhnach** [comment]
>After driver is initialized we are checking whether app is available on the device. If the result is false we are calling installApp.

This is, actually, what **noReset** capability is doing if set to _true_

**Comment by mykola-mokhnach** [comment]
Fixed in the recent beta
