### ISSUE TITLE
Investigate ESDoc as a docs candidate for Appium

### ISSUE THREAD

**Issue by jlipps** [appium/appium#8947]
As a minimum, can we:

- [ ] generate prose markdown files as well as API docs (looks like yes so far)
- [ ] show snippets of code in multiple languages with syntax highlighting and the ability to change language

Evaluate whether these things can be found in an ecosystem or how hard it would be to build them as extensions.

**Comment by mykola-mokhnach** [comment]
Linking https://doc.esdoc.org/github.com/esdoc/esdoc/manual/tags.html

**Comment by KazuCocoa** [comment]
just a comment.

A few days ago, ESDoc 1.0 was released.(finished alpha version)
 🎉  https://github.com/esdoc/esdoc/releases

**Comment by jlipps** [comment]
The decision moving forward is to use ESDoc for library API documentation and something like MkDocs for user documentation, and to keep these separate since they are separate use cases.

**Comment by h13i32maru** [comment]
> something like MkDocs for user documentation

FYI ESDoc supports user documentation feature as `manual`.

- https://esdoc.org/manual/feature.html#integration-manual
- https://esdoc.org/manual/config.html#integrate-manual-config

**Comment by dpgraham** [comment]
@h13i32maru Do you have any experience with publishing ESDocs manual? From what I could see, publishing markdown isn't simple.

**Comment by h13i32maru** [comment]
@dpgraham I made https://esdoc.org with ESDoc manual(markdown). The site repository is https://github.com/esdoc/esdoc-site
And the following sites made by ESDoc manual.
- http://reactivex.io/rxjs/
- http://developer.sketchapp.com/reference/api/
