### ISSUE TITLE
Add support for changing settings of targeted app on iOS

### ISSUE THREAD

**Issue by TFry** [appium/appium#895]
I would like the functionality to change a few settings of the app I am testing through the settings menu on iOS.  

If at all possible, I feel this feature would be very useful for development of any apps on iOS that have settings that modify large parts of the behavior of the app.

Arguments for or against?

**Comment by mykola-mokhnach** [comment]
This feature fill, most likely, be possible since iOS 11 and with apps management stuff available on WDA side: https://github.com/facebook/WebDriverAgent/pull/687

**Comment by jlipps** [comment]
That's great, thanks @mykola-mokhnach

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium-xcuitest-driver/pull/576
