### ISSUE TITLE
UiAutomator2: Press Key code method fails

### ISSUE THREAD

**Issue by mayureshshirodkar** [appium/appium#8951]
## The problem

On trying to execute method press key code, error is thrown with uiautomator2 on appium 1.6.6 beta3
This method worked fine with uiautomator on appium 1.6.6 beta3

On trying to execute this method:
getWebDriver().pressKeyCode(AndroidKeyCode.BACK);

Appium throws an error

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.6 beta 3
* Desktop OS/version used to run Appium: MacOS Sierra 10.12.6
* Mobile platform/version under test: Moto G4 Android 7.0 Nougat
* Real device or emulator/simulator: Real device

## Link to Appium logs
https://gist.github.com/mayureshshirodkar/71aa1adc9cdd1761e45f3b1a32a5e0fa

**Comment by jlipps** [comment]
fix has been merged in the uiautomator2 driver.

**Comment by mayureshshirodkar** [comment]
@mykola-mokhnach Is fix available to Test on latest appium version?

**Comment by mykola-mokhnach** [comment]
yes, try the recent beta (UIA2 driver version should be 0.5.0 or higher)

**Comment by mayureshshirodkar** [comment]
Checked it. Works perfectly. Thanks @mykola-mokhnach

**Comment by webmagit** [comment]
For those of us who cannot upgrade to get the fix, is there a workaround to send key events?
