### ISSUE TITLE
Test fails as WDA HANGS and takes ages to launch app

### ISSUE THREAD

**Issue by SamyQAZ** [appium/appium#8953]
## The problem

1. Started with login test, with reset application keyword[robot framework]
Test starts and launch app, covers successful login and logout then proceed with another set of test. Run next script in sequence, appium logs appears however it takes ages to launch app.
LOG always stuck [here](https://gist.github.com/SamyQAZ/edb35b9edf59e13a1fa9de91cd3bde02)

2. The same issue happens when any test fails, screen goes black and WDA doesnt close somehow. Eventually leads to failure of next test suite until manually go to device home page/ kill WDA.

## Environment

* Appium version: v1.6.5
* Desktop OS/version used to run Appium: MacOS Sierra(10.12.5)
* Node.js version (unless using Appium.app|exe): v7.10.0
* Mobile platform/version under test: iphone 5(10.3.2)
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI
* appium-xcuitest-driver: 2.40.0

## Link to Appium logs

Here is the [GIST](https://gist.github.com/SamyQAZ/099fc935c996ff52ffd542b702172c96)

**Comment by jlipps** [comment]
@SamyQAZ why are you using the `removeApp` command?

**Comment by SamyQAZ** [comment]
I am using it to start fresh test each time.

**Comment by SamyQAZ** [comment]
Seems issue happens quite frequently on every few tests.

Here is the [GIST](https://gist.github.com/SamyQAZ/72efc9e43a0e680b37f2805a88947cd9) from today.
Did anyone encountered the same issue. Any idea how to fix it.

**Comment by jlipps** [comment]
@SamyQAZ it's a much better practice to have 1 session per test case. Then just set the reset strategy to whatever is important (`fullReset` would definitely uninstall the app)
