### ISSUE TITLE
variable name used for element lookup instead of Page Factory annotation for IOSElement (native app)

### ISSUE THREAD

**Issue by squeemish** [appium/appium#8954]
## The problem

The variable name assigned to an IOSElement in Page Factory annotation is used to lookup the element instead of the actual annotation locator provided.

If the variable name is the same as the 'name' of the element, the element is found.  But if you name the element variable anything different than the actual assigned name of the element in code, the element is not found.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.1.1
* Last Appium version that did not exhibit the issue (if applicable): unsure
* Desktop OS/version used to run Appium: macOS 10.12.6
* Node.js version (unless using Appium.app|exe): n/a
* Mobile platform/version under test: iOS 10.3
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: Appium.app

## Details

ActivationLinkPage:  https://gist.github.com/squeemish/251504367c13caa16ef04336c75cfb4c
Driver/Appium creation:  https://gist.github.com/squeemish/7c77faaa839b5d7ffcb82f9d1515d05b
POM with system properties:  https://gist.github.com/squeemish/fd8f80dfd1e5730d471f9179a4183cf0

## Link to Appium logs

https://gist.github.com/squeemish/eac632e9b22836a436f500c460306914

**Comment by mykola-mokhnach** [comment]
Please report directly to https://github.com/appium/java-client/issues

Closed as non server-related issue.

**Comment by squeemish** [comment]
done. thank you for pointing me to the proper place
