### ISSUE TITLE
Investigate MkDocs

### ISSUE THREAD

**Issue by dpgraham** [appium/appium#8959]
Look at MkDocs as a possibility for our new documentation site.

**Comment by dpgraham** [comment]
Capabilities of MkDocs
* Generates static HTML that can be deployed to GitHub pages
* Themes (http://mkdocs.github.io/mkdocs-bootswatch/) or you can do your own theme
* Has an extension for displaying tabbed coding examples

**Comment by dpgraham** [comment]
This is what the default template and the tabbed coding examples looks like:

![screen shot 2017-08-02 at 1 44 28 pm](https://user-images.githubusercontent.com/852574/28894175-dd28f3cc-7788-11e7-9931-12c9e75d6be8.png)

**Comment by jlipps** [comment]
This is phenomenal! Is there a way to give the sections custom names? (For example not "Writing running appium")

**Comment by dpgraham** [comment]
You can whitelist all of the documents that go into it and choose the names.

Right now it's just using the directory names to name the section. Ideally we should be able to alias the directory name to something else.
