### ISSUE TITLE
Find control's properties 

### ISSUE THREAD

**Issue by CheNMorD** [appium/appium#8960]
## The problem

I'm using appium in visual studio for testing a simple WPF application,
I'm using WindowsDriver

`WindowsDriver<WindowsElement> driver = new WindowsDriver<WindowsElement>(new Uri("http://127.0.0.1:4723"), desiredCapabilities);
`
I know how to enter text and how to get text from TextBox:

`driver.FindElementByAccessibilityId("MyTextBox").SendKeys("123");
`

I wanted to know if there any way to get and set control's properties, For example: get IsChecked from CheckBox, get Background from TextBlock etc.

Thanks.

## Environment

Appium version: 1.6.5 / 1.6.6 beta
Desktop OS/version: Windows 10

## Details

I wanted to know if there any way to get and set control's properties,.

Thanks.

**Comment by mykola-mokhnach** [comment]
Have you checked the **value** property for such elements in page source?

**Comment by CheNMorD** [comment]
@mykola-mokhnach 
I'm testing a desktop app, using XAML for the ui, for example:
`<TextBlock AutomationProperties.AutomationId="MyTextBlock" Background="Red"/>`
lets say i want to get my TextBox Background value, how do i do that?

**Comment by jlipps** [comment]
@yodurr is there a way to get the background value of a TextBlock via WAD? something like `element.getAttribute('Background')`?

**Comment by yodurr** [comment]
we're expanding the attributes you can query in v1.0 which is coming out in the next few days.  I expect you'll be able to get this but will confirm...

**Comment by timotiusmargo** [comment]
In v1.0 we will be able to query any attribute that shows in `inspect.exe`. See https://github.com/Microsoft/WinAppDriver#inspecting-ui-elements

Unfortunately, **Background** is not an automation attribute that is typically exposed by XAML UI element. So this particular scenario is not supported unless you are using a custom XAML element that exposes it as an automation attribute.

**CheckBox** state on the other hand, can be queried easily. The XAML **CheckBox** element has **Toggle.ToggleState** value that you can query using `element.getAttribute("Toggle.ToggleState")`. But in most cases, I would simply check `element.selected` that should reflect the current **CheckBox** state. See https://github.com/Microsoft/WinAppDriver/blob/v0.9-beta/Tests/UWPControls/CheckBox.cs#L106 as a reference.

**Comment by CheNMorD** [comment]
Thanks for the answers, 
But what about more complicated things?, 
for example: select from ComboBox, get items count from GridView etc.

@timotiusmargo i know that i can get attribute but there are many properties that you can't get
by attribute, is there any way to get the properties of the controls?

Thanks.

**Comment by jlipps** [comment]
@CheNMorD it sounds like that won't be possible if it's not available through `inspect.exe`; maybe it'd be best to add a feature request at the WinAppDriver repo if this is something you need! Closing for now.
