### ISSUE TITLE
Finding Elements md file has 3 broken links

### ISSUE THREAD

**Issue by raulovidiu** [appium/appium#8961]
The "writing-running-appium/finding-elements.md" documentation file has 3 broken links. 

All these 3 links are found under the "Overview" section, named "Step 1", and when clicked, they point to a "Not Found" resource.

The URL to the .md file is https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/finding-elements.md

**Comment by imurchie** [comment]
Thanks for letting us know!

**Comment by imurchie** [comment]
@dpgraham These are to do with the old inspector. Could you update with appropriate images (and text changes) for `appium-desktop`?
