### ISSUE TITLE
java.lang.IllegalArgumentException: If you use a '@$Proxy14' annotation, you must not also use a '@$Proxy15' annotation

### ISSUE THREAD

**Issue by pavanbachu0604** [appium/appium#8963]
## The problem
Observing the above error message in Page Factory Model. I have referred [Link](https://github.com/appium/java-client/blob/master/src/test/java/io/appium/java_client/pagefactory_tests/IOSPageFactoryTest.java)
 for writing the xpath

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Last Appium version that did not exhibit the issue (if applicable):1.6.5
* Desktop OS/version used to run Appium:MACOS
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS 10.2.1
* Real device or emulator/simulator:Real Device
* Appium CLI or Appium.app|exe:
*Java Client :4.1.2 

## Link to Appium logs

https://gist.github.com/pavanbachu0604/dd8c036bc5ac5bd005a5f7eddf76fca0

## Code To Reproduce Issue [ Good To Have ]

https://gist.github.com/pavanbachu0604/41a0786cc60dc35c730cb14b86aa4dd2

**Comment by mykola-mokhnach** [comment]
Please report directly to https://github.com/appium/java-client

Closed as non server-related
