### ISSUE TITLE
scroll using move to element not working if the element is just below the screen

### ISSUE THREAD

**Issue by sebinjqburst** [appium/appium#8964]
## The problem

If the element is just below the screen that is currently visible on the iPad, scroll to element will return the max scroll count reached error without scrolling at least once.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.6-beta.4
* Last Appium version that did not exhibit the issue (if applicable): 1.6.6-beta.3
* Desktop OS/version used to run Appium: mac
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS 10.3
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:

## Appium logs

ERROR-Settings org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Error Domain=com.facebook.WebDriverAgent Code=1 "Failed to perform scroll with visible cell due to max scroll count reached" UserInfo={NSLocalizedDescription=Failed to perform scroll with visible cell due to max scroll count reached} (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 97.69 seconds

## Code To Reproduce Issue [ Good To Have ]

TouchAction ta1 = new TouchAction(driver);
ta1.press(100,100).moveTo(element).release();
ta1.perform();

**Comment by mykola-mokhnach** [comment]
Please report the issue directly to https://github.com/facebook/WebDriverAgent/issues
We cannot do anything to change this behaviour from Appium
