### ISSUE TITLE
Return the error 2 visible children even though only one element exists with the identifier

### ISSUE THREAD

**Issue by sebinjqburst** [appium/appium#8967]
## The problem

While performing scroll, I get "Failed to find scrollable visible parent with 2 visible children\" error. But only one element with the identifier is present there. I have accessed the screen 1 at first (I perform some scrolling here) and then went to some other screen, say screen 2. Later, when I came back to screen 1 and try to scroll to some element on the screen, it returns this error. I tried scrolling to the same element in the first attempt, that is without switching between the screens and it was successful.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.6-beta.4
* Last Appium version that did not exhibit the issue (if applicable): 1.6.6-beta.3
* Desktop OS/version used to run Appium: mac
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS 10.3
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:

## Appium logs

[debug] [XCUITest] Found matching gesture: scroll
[debug] [JSONWP Proxy] Proxying [POST /wda/element/4A4E80AE-54B8-4CD4-912C-98D3AB445858/scroll] to [POST http://localhost:8100/session/8EA8B88F-CD11-4F01-A0AB-C8FE4EBA7E3E/wda/element/4A4E80AE-54B8-4CD4-912C-98D3AB445858/scroll] with body: {"toVisible":true}
[debug] [JSONWP Proxy] Got response with status 200: {"value":"Error Domain=com.facebook.WebDriverAgent Code=1 \"Failed to find scrollable visible parent with 2 visible children\" UserInfo={NSLocalizedDescription=Failed to find scrollable visible parent with 2 visible children}","sessionId":"8EA8B88F-CD11-4F01-A0AB-C8FE4EBA7E3E","status":13}

**Comment by mykola-mokhnach** [comment]
Please report directly to https://github.com/facebook/WebDriverAgent/issues
We cannot change anything there on Appium side
