### ISSUE TITLE
how can i turn off allow_mock_location?

### ISSUE THREAD

**Issue by vivian2011** [appium/appium#8969]
## The problem

the allow_mock_location status is allow after installed apk successfully
how can i turn it off ？

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Mobile platform/version under test: android 5.1
* Real device or emulator/simulator: Real device

**Comment by jlipps** [comment]
@vivian2011 why don't you want this turned on? it's necessary for setting coordinates via appium

**Comment by vivian2011** [comment]
my app don‘t allow user to turn on it,
it's an LBS app.

**Comment by vivian2011** [comment]
@jlipps    My app don't allow user to turn on it.  it‘s an LBS app

**Comment by jlipps** [comment]
OK, I marked this as an enhancement request. We should have a capability that you can use to turn this off. It should be relatively easy to implement.

**Comment by vivian2011** [comment]
@jlipps  thank you ～～～～～～

**Comment by swizes** [comment]
Does anybody have a solution?

**Comment by mykola-mokhnach** [comment]
appium@beta got `mockLocationApp` capability. This capability only works for real devices and can be set to application identifier, which should be used as mock location provider. Setting it to an empty string or `null` will skip location mocking.

**Comment by swizes** [comment]
Thanks for the explanation.

I did the following steps and it worked as expected

installed beta version via -> npm i appium@1.17.1-beta.0
added `mockLocationApp: null` to the caps.

the select mock location app section in the developer options of the device was -> "No mock location app set"

**Comment by mallicodejava** [comment]
> Thanks for the explanation.
> 
> I did the following steps and it worked as expected
> 
> installed beta version via -> npm i appium@1.17.1-beta.0
> added `mockLocationApp: null` to the caps.
> 
> the select mock location app section in the developer options of the device was -> "No mock location app set"

It's not working for me I have written like this 

caps.setCapability("mockLocationApp"," ");

Am using 1.19.1 version.
In the developer option also no app is set. Can anyone help me one this?
