### ISSUE TITLE
Unable to launch Google Native Application inside my device

### ISSUE THREAD

**Issue by nidhitri** [appium/appium#8972]
## The problem

I was unable to launch google native app in my device using **package-name** as "**com.google.android.googlequicksearchbox**" and with several activity-name as given blow 
# com.google.android.intent.category.LAUNCHER
# com.google.android.apps.gsa.searchnow.SearchNowActivity
# com.google.android.apps.gsa.assistant.handoff.BrowserReturnActivity

It was throwing me the error as "**Activity is not launchable . Please use another activity name**"

## Environment

* Appium version (or git revision) that exhibits the issue: Appium 1.6.4 and Appium 1.4.16
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:Windows 8
* Node.js version (unless using Appium.app|exe):Using Appium.app
* Mobile platform/version under test:Android 6.0.1
* Real device or emulator/simulator:Real Device
* Appium CLI or Appium.app|exe:Appium.app

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]
import java.io.IOException;
import java.net.URL;

import org.openqa.selenium.By;
import org.openqa.selenium.remote.DesiredCapabilities;

import io.appium.java_client.android.AndroidDriver;

public class Instant {
	public static AndroidDriver driver;
	public static void main (String args[]) throws IOException, InterruptedException{
		
		
		DesiredCapabilities desiredCapabilities = new DesiredCapabilities();
		//desiredCapabilities.setCapability("app", "E:\\Appium\\com.google.android.googlequicksearchbox-2.apk");
	desiredCapabilities.setCapability("appPackage","com.google.android.googlequicksearchbox");
		desiredCapabilities.setCapability("appActivity" ,"com.google.android.apps.gsa.assistant.handoff.BrowserReturnActivity");
		desiredCapabilities.setCapability("platformName", "Android");
		desiredCapabilities.setCapability("deviceName", "070a25bc00cac213");
		desiredCapabilities.setCapability("platformVersion", "6.0.1");
		//desiredCapabilities.setCapability("browserName", "Chrome");
		
		
	 driver = new AndroidDriver(new URL("http://0.0.0.0:4723/wd/hub"), desiredCapabilities);

	driver.findElement(By.id("com.google.android.googlequicksearchbox:id/search_edit_frame")).click();
	 driver.findElement(By.name("Google")).click();
	 //driver.findElement(By.id("com.google.android.googlequicksearchbox:id/search_edit_frame")).sendKeys("Instant App");
}
}

**Comment by mykola-mokhnach** [comment]
You need to find out which activity is the main one. Also, it might be necessary to set **appWaitActivity**.

**Comment by nidhitri** [comment]
Thanks Mykola for the reply, Is there a way to find the main activity name ,coz I 've tried all the possible ways to do that.

**Comment by jlipps** [comment]
Here's what I found by googling "android apk find main activity": https://stackoverflow.com/questions/5964735/android-how-to-find-the-name-of-the-main-activity-of-an-application
