### ISSUE TITLE
Tableview cell finding issue in Appium.

### ISSUE THREAD

**Issue by MRameshiOS** [appium/appium#8976]
Hi,
 
   I have the tableview,  It enabled accessibility identifier, and  It contains 700+ cells. But appium is not finding the all cell. It finding only 500 cells. Main problem It is not finding visible cells. tableview contains default cell and default label.

**Comment by mykola-mokhnach** [comment]
Please report directly to https://github.com/facebook/WebDriverAgent/issues

We cannot do anything on Appium side to change this behaviour.
