### ISSUE TITLE
Appium uiautoamtor2 server apk 0.18 seems not to be accessible 

### ISSUE THREAD

**Issue by vjmaiky** [appium/appium#8977]
## The problem
I`m trying to setup a parallel run on Android and i started to receive an error:
AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-driver\uiautomator2\appium-uiautomator2-server-v0.1.8.apk'. Does the package exist and is accessible?

## Environment
Windows 8, appium 1.6.6 beta3, node 8.2.1

## Details
Basically i have a custom start of appium server. Server seems to start but it stops after because seems to be a problem with finding the uiautomator 2 server apk.

## Link to Appium logs
https://gist.github.com/vjmaiky/7280902c99d6ecd32cf1724cf5e1daae

**Comment by mykola-mokhnach** [comment]
there is some problem with npm not putting that apk file into the right place while beta is installed. Can you simply download the apk file from https://github.com/appium/appium-uiautomator2-server/releases and put it at the path mentioned in the error message?

**Comment by vjmaiky** [comment]
08-04-2017 11:22:18 - [core.managers.DriverManagerAndroid / getCaps][INFO ] - Creating driver caps for device: 192.168.92.101:5555
[ADB] Error "Command 'D\:\\AndroidStudioSDK\\build-tools\\25.0.2\\aapt.exe d badging C\:\\Users\\lumihai\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-uiautomator2-driver\\uiautomator2\\appium-uiautomator2-server-v0.1.8.apk' exited with code 1" while getting badging info
[UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error was: Error: Trying to proxy a session command without session id
[UiAutomator2] Unable to remove port forward 'Error executing adbExec. Original error: 'Command 'D\:\\AndroidStudioSDK\\platform-tools\\adb.exe -P 5037 -s 192.168.92.101\:5555 forward --remove tcp\:8200' exited with code 1'; Stderr: 'error: listener 'tcp:8200' not found'; Code: '1''
[MJSONWP] Encountered internal error running command: Error: Cannot read manifest information from 'C:\Users\lumihai\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-driver\uiautomator2\appium-uiautomator2-server-v0.1.8.apk'. Does the package exist and is accessible?
    at UiAutomator2Server.installServerApk$ (../../lib/uiautomator2.js:39:13)
    at tryCatch (C:\Users\lumihai\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\lumihai\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\lumihai\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\lumihai\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[ADB] Error "Command 'D\:\\AndroidStudioSDK\\build-tools\\25.0.2\\aapt.exe d badging C\:\\Users\\lumihai\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-uiautomator2-driver\\uiautomator2\\appium-uiautomator2-server-v0.1.8.apk' exited with code 1" while getting badging info

**Comment by mykola-mokhnach** [comment]
What do you see if this command is executed manually?

```
D:\AndroidStudioSDK\build-tools\25.0.2\aapt.exe d badging C:\Users\lumihai\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-driver\uiautomator2\appium-uiautomator2-server-v0.1.8.apk
```

**Comment by vjmaiky** [comment]
D:\AndroidStudioSDK\build-tools\25.0.2>aapt.exe d badging C:\Users\lumihai\AppDa
ta\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-driver\uiaut
omator2\appium-uiautomator2-server-v0.1.8.apk
W/        ( 6196): Unable to open 'C:\Users\lumihai\AppData\Roaming\npm\node_mod
ules\appium\node_modules\appium-uiautomator2-driver\uiautomator2\appium-uiautoma
tor2-server-v0.1.8.apk': Permission denied
W/zipro   ( 6196): Error opening archive C:\Users\lumihai\AppData\Roaming\npm\no
de_modules\appium\node_modules\appium-uiautomator2-driver\uiautomator2\appium-ui
automator2-server-v0.1.8.apk: I/O Error
ERROR: dump failed because no AndroidManifest.xml found

D:\AndroidStudioSDK\build-tools\25.0.2>

**Comment by mykola-mokhnach** [comment]
> W/ ( 6196): Unable to open 'C:\Users\lumihai\AppData\Roaming\npm\node_mod
ules\appium\node_modules\appium-uiautomator2-driver\uiautomator2\appium-uiautoma
tor2-server-v0.1.8.apk': Permission denied

I suppose it's clear what to do next

**Comment by vjmaiky** [comment]
it is possible that permission changed after updating appium?

**Comment by mykola-mokhnach** [comment]
no idea how npm handles that under Windows

**Comment by vjmaiky** [comment]
It seems that every time when you update appium, permissions are deleted; only admin is visible; you need to grant permissions. Would be nice if i could have your skype or some direct contact :).

**Comment by mykola-mokhnach** [comment]
You can find us in Appium channel on Slack. However we only discuss Appium development progress there. 

@imurchie @dpgraham FYI

**Comment by vjmaiky** [comment]
if i remember well on slack groups i need to be invited; or now it is changed?

**Comment by imurchie** [comment]
What is the output of 
```
ls -la C:\Users\lumihai\AppData\Roaming\npm\node_mod
ules\appium\node_modules\appium-uiautomator2-driver\uiautomator2
```

**Comment by vjmaiky** [comment]
@imurchie i think you ment dir (because it is windows)

08/06/2017  04:42 PM    <DIR>          .
08/06/2017  04:42 PM    <DIR>          ..
08/06/2017  04:42 PM         1,809,663 appium-uiautomator2-server-debug-androidTest.apk
08/06/2017  04:42 PM         1,553,892 appium-uiautomator2-server-v0.1.8.apk
               2 File(s)      3,363,555 bytes
               2 Dir(s)  30,511,845,376 bytes free

**Comment by vjmaiky** [comment]
but it can be closed now its working
