### ISSUE TITLE
[Error: Could not detect Mac OS X Version from sw_vers output: '10.12.6 ']

### ISSUE THREAD

**Issue by davidmorrison1981** [appium/appium#8978]
Ive just installed Appium and was going thru the steps to set it up, however I cant seem to find anything about how I fix this error message when I run the Doctor tool:

[Error: Could not detect Mac OS X Version from sw_vers output: '10.12.6']

## Environment

* Appium version (or git revision) that exhibits the issue: Version 1.5.3 (Ara)
* Desktop OS/version used to run Appium:  mac OS Sierra 10.12.6
* Node.js version (unless using Appium.app|exe): Appium App
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: iPhone 6 (Real)
* Appium CLI or Appium.app|exe: Appium App

Can you help?

**Comment by imurchie** [comment]
The only help is to upgrade. Appium 1.5.3 came out before MacOS Sierra, and doesn't understand it.
