### ISSUE TITLE
Touch Actions does not function properly in Selenium 3.2.0.

### ISSUE THREAD

**Issue by dmlch123** [appium/appium#8981]
## The problem

I am using selenium to add dependency of Maven.
From 3.2.0 onwards, TouchActions do not function normally.
NullPointException occurs in perform().
In the version 3.1.0, it operates normally.

## Environment

* Appium version (or git revision) that exhibits the issue: selenium-java 3.2.0
* Last Appium version that did not exhibit the issue (if applicable):  selenium-java 3.1.0
* Desktop OS/version used to run Appium: Win7 / appium v1.6.5
* Node.js version (unless using Appium.app|exe):  v6.10.2
* Mobile platform/version under test: LG G5_v6.0.1
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

I used scroll.

java.lang.NullPointerException
	at org.openqa.selenium.interactions.Actions$BuiltAction.perform(Actions.java:627)
	at org.openqa.selenium.interactions.Actions.perform(Actions.java:589)

**Comment by mykola-mokhnach** [comment]
Java client 3 is outdated. Please use 5.0.0-BETA9

Closed as non server-related
