### ISSUE TITLE
Unable to start session with ios settings without reset

### ISSUE THREAD

**Issue by risinek** [appium/appium#8982]
I have an app, in which I start activation, and the activation needs to install profile into device. So I start a session with our app, then I control the app, and start activation. When the profile installation begins, it is opened in Settings app.. AFAIK apple does not allow to control more than one app in one session. So I tried to workaround this, and end one session with our app, then start new session with Settings.. But whenever I start new session with Settings, it will cancel the profile installation - the profile installation prompt disappear..
I have set `noReset = true` also I tried to start server with `--no-reset` but without any success..
Is it possible to somehow workaround this, or is this unautomatable? 

I'm automating on real iOS10 device

**Comment by mykola-mokhnach** [comment]
There is a possibility to put the app into background and then interact with the dashboard and application icons there. However, I'm not sure if you can control another app if you open it from there.

**Comment by risinek** [comment]
This doesn't allow me to control the Settings then.. I need to start the session with `"app" "settings"` to be able to click on "Install" buttons.. But when I start new session, the installation process is canceled

**Comment by mykola-mokhnach** [comment]
Apple has introduced multi application support in XCTest since iOS 11: http://shashikantjagtap.net/hands-xcuitest-features-xcode-9/ 
You can try this feature by directly using XCTest, but there is no support in Appium for it (yet).

**Comment by risinek** [comment]
Is it planned to add support for this ASAP or not?

**Comment by mykola-mokhnach** [comment]
I don't think so.
