### ISSUE TITLE
Tests stop executing after some steps on Android versions higher than 6.0

### ISSUE THREAD

**Issue by denispolkhovskiy** [appium/appium#8986]
## The problem

Can not run tests on Android versions higher than 6.0, whereas it works fine on Android 6.0. Also, when I do same steps in Appium GUI, after logging in Appium GUI freezes and can not load page

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Desktop OS/version used to run Appium: Windows
* Mobile platform/version under test: Android version 7.0
* Real device or emulator/simulator: emulator for tablet Nexus 9
* Environment Robot Framework + Python + Appium

## Details

It opens login page and it could fill all required data for logging in, but when activity changes everything starts to be stuck 

## Link to Appium logs

https://gist.github.com/denispolkhovskiy/31b6c47812a03b8e972666d62c79205d

**Comment by mykola-mokhnach** [comment]
You, probably, need to switch to UIAutomator2 backend. UIA1 is not supported by Google anymore.

**Comment by denispolkhovskiy** [comment]
Thank you @mykola-mokhnach  it solved my problem.
