### ISSUE TITLE
Unable to find element by name in latest[Version: 1.1.1] appium.

### ISSUE THREAD

**Issue by ajit-jadhav** [appium/appium#8987]
## The problem

Unable to find element by name property on android devices.

## Environment

* Appium version - 1.6.3
* Desktop OS/version used to run Appium: 1.1.1
* Mobile platform/version under test: Android 4.4
* Real device or emulator/simulator: Real Device Asus
* Appium CLI or Appium.app|exe: Appium.exe

## Details
Unable to find element by name.
find below replacement for reference.
wait.until(ExpectedConditions.visibilityOfElementLocated(By.name("MyElement")))//________Not working
wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//*[@text='MyElement']")))//_____Working

**Comment by mykola-mokhnach** [comment]
Use AccessibilityId or Id locators instead. This is by design
