### ISSUE TITLE
Why can't I tap an element that is 'disabled'?

### ISSUE THREAD

**Issue by gkvappium** [appium/appium#8988]
## The problem

Can't tap an element which has enabled set to 'False'

## Environment

* Appium version (or git revision) that exhibits the issue:1.6.6 beta
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

I work on a player app. There are lot of buttons that will be disabled. Example play/pause/shuffle/repeat. When I see the properties, enabled is false. So in python when I do a element.is_enabled(), it returns false which is fine. But why is it that I am not allowed to click this. When I try to do a click, it says that the element is not visible. Here the case is that the element is visible but is not enabled.

@mykola-mokhnach : Any inputs?

**Comment by mykola-mokhnach** [comment]
Try to tap by coordinates. The current behaviour is expected

**Comment by gkvappium** [comment]
Isn't this is a bug?

There would be lot of elements that would be greyed out in the software indicating that is not in enabled state. User has to tap that element to enable it. Example shuffle button in a music player. 

Tap using x and y is not a feasible approach since we test it from iphone4s to a tab with various screen sizes.

**Comment by mykola-mokhnach** [comment]
One should not hardcode there coordinates - they have to be calculated dynamically. Selenium for browser works similarly - you are not able to interact with disabled elements there.

**Comment by gkvappium** [comment]
I have not hardcoded any x and y values in any of the test cases. Ex in Android if I want to move the track slider I take width of the element and then drag it till the end based on x and y values (send_keys to a slider works fine only for IOS). But in this case, I don't see the element at all. So how do I tap that specific element?

**Comment by gkvappium** [comment]
@imurchie @mykola-mokhnach ,

Can you please let me know how to tackle this scenario?

Thanks.

**Comment by gkvappium** [comment]
@mykola-mokhnach ,

Is this an issue on the software side?

From automation side, I would like to see if an element is disabled or enabled (Get true or false). If it is disabled, I need to enable it and then do certain validations based on the software behavior. 

Are you saying that this is something that cannot be validated using Appium?

**Comment by jlipps** [comment]
@gkvappium how would a user of your application cause the control to become enabled?

**Comment by gkvappium** [comment]
@jlipps ,

Ours is a music player application. There are buttons like Shuffle,Play,Pause,Repeat. User has to just tap these elements to enable it. Here are my observations.

1. Some of these elements have enabled-true and visible-true. But some of them have enabled-false and visible-true. I've notified this to the dev team about the inconsistency.
2. With Automation, I have to achieve this. Check the state of the buttons after defaulting the application settings. In this case all the buttons are in the disabled state. When I do a element.is_enabled(), this returns false and I use assertFalse for the validation which is fine. Now, I have to tap these elements to enable it. How do I tap it since appium cannot see the elements that are not enabled? But the visibility of these elements is 'true'?

Thanks

**Comment by gkvappium** [comment]
@jlipps ,

Any inputs from your end to tackle this situation in Automation?

Thanks.

**Comment by jlipps** [comment]
I think it's a bad design pattern to disable an element which can be enabled by tapping on it. The whole point of a disabled element is that you can't interact with it. So why would a user think they could tap on it? A better way would be to use different icons to show state rather than setting the element itself to disabled. But if you can't convince your dev team to change this, then you will need to tap by pre-determined coordinates, unfortunately!

**Comment by gkvappium** [comment]
@jlipps 

Well yeah, that makes sense. Even if that property is set to 'Enabled', Appium can't really find out if the element is disabled or enabled since the element is greyed out but still enabled unless I do an image comparison which I think is too much for such a simple scenario.

But for your point , why would a user think they can tap it - If you see the music player app for example. Shuffle/Repeat is greyed out (Looks like disabled). So user will know that he or she has to tap on the element to enable this feature. But appium really can't find out if the element is enabled or disabled if the property is set to enabled but it is greyed out unless I decide to verify the functionality itself.

**Comment by jlipps** [comment]
Yes. I'm not saying it's a bad user interface pattern, I'm saying it's a bad technical solution for the UI problem. Having two states for an element to show whether an app function is enabled is a good idea. But it should be two kinds of "enabled" states under the hood, just with different visual indication to the users.

**Comment by gkvappium** [comment]
Ok. Thanks @jlipps . I'll suggest this to the dev team. Simple thing would be is to have 2 labels something like Repeat_Off and Repeat_On for the same button with both enabled so that I can enable/disable based on the existing state/label

**Comment by jlipps** [comment]
@gkvappium yes that's the idea
