### ISSUE TITLE
How can i Hide the Keyboard?

### ISSUE THREAD

**Issue by KuKiSiNi77** [appium/appium#8989]
## The problem

 1. `driver.hideKeyboard();`
 2. `driver.getKeyboard().pressKey(Keys.ENTER);`
 3. `driver.navigate().back();`

There are no any action.
have other way that can make it work?

## Environment

* Appium version (or git revision) that exhibits the issue: v1.6.6-beta.3
* Desktop OS/version used to run Appium: macOS 10.12.8
* Node.js version (unless using Appium.app|exe): v6.6.0
* Mobile platform/version under test: 10.3.3
* Real device or emulator/simulator: Real device

## Link to Appium logs

`[debug] [JSONWP Proxy] Proxying [POST /wda/keyboard/dismiss] to [POST http://localhost:8100/session/68E58D3B-BEFE-4236-8C3C-6F71ECC853FD/wda/keyboard/dismiss] with no body`

**Comment by mykola-mokhnach** [comment]
This is the way how XCTest works and we cannot change that. You have to rely on the actions, that are available in the application under test to hide the keyboard.
