### ISSUE TITLE
appium is not able to click on the button of  app-generated pop-up

### ISSUE THREAD

**Issue by abisekkachroo** [appium/appium#8990]
## The problem
Scenario is I have to enter the phone number and click on next button, the moment I click on Next button a system generated pop-up with ok and cancel buttons are displayed 
Not able to click OK button  on the pop-up 
I have tried using the tap button by getting the co-ordinates of the button and I have checked in the code that the element is displayed or enabled or not ,
My code runs correctly 2 out of 4 times 
Means I didn't get how this is even possible
I have also tried switching contexts and also used the alert interface but still no use

## Environment

* Appium version 1.6.4
* Mobile platform/version under test:-  android 5.1 and 6.1 
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe:

## Details
com.edmobilelabs.sling.dev:id/btnPositive this is the id which is sometimes clicked   and sometimes not .
 My code runs on to the next screen  where I have to enter the OTP  but on the mobile its freezed on the OK button which is the current screen 

## Link to Appium logs

[AndroidBootstrap] Received command result from bootstrap
[MJSONWP] Responding to client with driver.click() result: true
[HTTP] <-- POST /wd/hub/session/573b7baf-4e78-49a5-9243-fcbfb82a8470/element/8/click 200 350 ms - 76 
[HTTP] --> POST /wd/hub/session/573b7baf-4e78-49a5-9243-fcbfb82a8470/element {"using":"id","value":"com.edmobilelabs.sling.dev:id/btnPositive"}
[MJSONWP] Calling AppiumDriver.findElement() with args: ["id","com.edmobilelabs.sling.dev:id/btnPositive","573b7baf-4e78-49a5-9243-fcbfb82a8470"]
[BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[BaseDriver] Waiting up to 5000 ms for condition
[AndroidBootstrap] Sending command to android: {"cmd":"action","action":"find","params":{"strategy":"id","selector":"com.edmobilelabs.sling.dev:id/btnPositive","context":"","multiple":false}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"id","selector":"com.edmobilelabs.sling.dev:id/btnPositive","context":"","multiple":false}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: find
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding 'com.edmobilelabs.sling.dev:id/btnPositive' using 'ID' with the contextId: '' multiple: false
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[INSTANCE=0, RESOURCE_ID=com.edmobilelabs.sling.dev:id/btnPositive]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":{"ELEMENT":"9"}}
[AndroidBootstrap] Received command result from bootstrap
[MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"9"}
[HTTP] <-- POST /wd/hub/session/573b7baf-4e78-49a5-9243-fcbfb82a8470/element 200 515 ms - 87 
[HTTP] --> GET /wd/hub/session/573b7baf-4e78-49a5-9243-fcbfb82a8470/element/9/displayed {}
[MJSONWP] Calling AppiumDriver.elementDisplayed() with args: ["9","573b7baf-4e78-49a5-9243-fcbfb82a8470"]
[AndroidBootstrap] Sending command to android: {"cmd":"action","action":"element:getAttribute","params":{"attribute":"displayed","elementId":"9"}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:getAttribute","params":{"attribute":"displayed","elementId":"9"}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: getAttribute
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":"true"}
[AndroidBootstrap] Received command result from bootstrap
[MJSONWP] Responding to client with driver.elementDisplayed() result: true
[HTTP] <-- GET /wd/hub/session/573b7baf-4e78-49a5-9243-fcbfb82a8470/element/9/displayed 200 10 ms - 76 
[HTTP] --> POST /wd/hub/session/573b7baf-4e78-49a5-9243-fcbfb82a8470/element {"using":"id","value":"com.edmobilelabs.sling.dev:id/btnPositive"}
[MJSONWP] Calling AppiumDriver.findElement() with args: ["id","com.edmobilelabs.sling.dev:id/btnPositive","573b7baf-4e78-49a5-9243-fcbfb82a8470"]
[BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[BaseDriver] Waiting up to 5000 ms for condition
[AndroidBootstrap] Sending command to android: {"cmd":"action","action":"find","params":{"strategy":"id","selector":"com.edmobilelabs.sling.dev:id/btnPositive","context":"","multiple":false}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"id","selector":"com.edmobilelabs.sling.dev:id/btnPositive","context":"","multiple":false}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: find
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding 'com.edmobilelabs.sling.dev:id/btnPositive' using 'ID' with the contextId: '' multiple: false
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[INSTANCE=0, RESOURCE_ID=com.edmobilelabs.sling.dev:id/btnPositive]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":{"ELEMENT":"10"}}
[AndroidBootstrap] Received command result from bootstrap
[MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"10"}
[HTTP] <-- POST /wd/hub/session/573b7baf-4e78-49a5-9243-fcbfb82a8470/element 200 9 ms - 88 
[HTTP] --> POST /wd/hub/session/573b7baf-4e78-49a5-9243-fcbfb82a8470/element/10/click {"id":"10"}
[MJSONWP] Calling AppiumDriver.click() with args: ["10","573b7baf-4e78-49a5-9243-fcbfb82a8470"]
[AndroidBootstrap] Sending command to android: {"cmd":"action","action":"element:click","params":{"elementId":"10"}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:click","params":{"elementId":"10"}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: click
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":true}
[AndroidBootstrap] Received command result from bootstrap
[MJSONWP] Responding to client with driver.click() result: true
[HTTP] <-- POST /wd/hub/session/573b7baf-4e78-49a5-9243-fcbfb82a8470/element/10/click 200 3196 ms - 76 
[HTTP] --> POST /wd/hub/session/573b7baf-4e78-49a5-9243-fcbfb82a8470/timeouts {"type":"implicit","ms":8000}
[MJSONWP] Calling AppiumDriver.timeouts() with args: ["implicit",8000,"573b7baf-4e78-49a5-9243-fcbfb82a8470"]
[BaseDriver] Set implicit wait to 8000ms
[MJSONWP] Responding to client with driver.timeouts() result: null
[HTTP] <-- POST /wd/hub/session/573b7baf-4e78-49a5-9243-fcbfb82a8470/timeouts 200 2 ms - 76 
[HTTP] --> POST /wd/hub/session/573b7baf-4e78-49a5-9243-fcbfb82a8470/element {"using":"id","value":"com.edmobilelabs.sling.dev:id/etVerificationCode"}
[MJSONWP] Calling AppiumDriver.findElement() with args: ["id","com.edmobilelabs.sling.dev:id/etVerificationCode","573b7baf-4e78-49a5-9243-fcbfb82a8470"]
[BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[BaseDriver] Waiting up to 8000 ms for condition
[AndroidBootstrap] Sending command to android: {"cmd":"action","action":"find","params":{"strategy":"id","selector":"com.edmobilelabs.sling.dev:id/etVerificationCode","context":"","multiple":false}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"id","selector":"com.edmobilelabs.sling.dev:id/etVerificationCode","context":"","multiple":false}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: find
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding 'com.edmobilelabs.sling.dev:id/etVerificationCode' using 'ID' with the contextId: '' multiple: false
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[INSTANCE=0, RESOURCE_ID=com.edmobilelabs.sling.dev:id/etVerificationCode]
## Code To Reproduce Issue [ Good To Have ]

public boolean navigateToLoginPage() throws SQLException{
		String strngx = new String();
		newObj = new LogInPage();
		wait = new WebDriverWait(driver,20);
		wait.until(ExpectedConditions.visibilityOf(GetStarted));
		GetStarted.click();
		driver.manage().timeouts().implicitlyWait(5000, TimeUnit.MILLISECONDS);
		if(Country.isDisplayed()){
			Country.click();
			wait.until(ExpectedConditions.visibilityOf(Cancel));
			Cancel.click();
		} 
		MobileNumber.sendKeys("9730643945");
		Next.click();
		wait.until(ExpectedConditions.visibilityOf(OKButton));
		//String currentContext = driver.getContext();
		//driver.context("Native_App");
		OKButton.click();
		//driver.context(currentContext);
		strngx = newObj.gettingOTPasString();
		System.out.println(strngx);
		driver.manage().timeouts().implicitlyWait(8000, TimeUnit.MILLISECONDS);
		EnterOTP.sendKeys(strngx);
		Next.click();
		Utility.CaptureScreenShot(driver,"1stScreenShot");
		return true;	
	}

**Comment by mykola-mokhnach** [comment]
Try to print the page source if the test fails. Probably, there is some kind of race condition.

**Comment by abisekkachroo** [comment]
@mykola-mokhnach  
I don't  think there is the race-around condition , I have removed the code which would be the used which would be used when the user navigates to the next screen and still sometimes I am able to click successfully and sometimes not 
the logs on the appium server are also same 
Logs when there is successful click on OK button

[BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[BaseDriver] Waiting up to 5000 ms for condition
[AndroidBootstrap] Sending command to android: {"cmd":"action","action":"find","params":{"strategy":"id","selector":"com.edmobilelabs.sling.dev:id/btnPositive","context":"","multiple":false}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"id","selector":"com.edmobilelabs.sling.dev:id/btnPositive","context":"","multiple":false}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: find
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding 'com.edmobilelabs.sling.dev:id/btnPositive' using 'ID' with the contextId: '' multiple: false
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[INSTANCE=0, RESOURCE_ID=com.edmobilelabs.sling.dev:id/btnPositive]
[AndroidBootstrap] Received command result from bootstrap
[MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"6"}
[HTTP] <-- POST /wd/hub/session/3bf30cbb-d607-4e0b-929d-eeb12c9f342d/element 200 15 ms - 87 
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":{"ELEMENT":"6"}}
[HTTP] --> POST /wd/hub/session/3bf30cbb-d607-4e0b-929d-eeb12c9f342d/element/6/click {"id":"6"}


Logs when there is unsucessful operation for clicking on OK button 


[BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[BaseDriver] Waiting up to 5000 ms for condition
[AndroidBootstrap] Sending command to android: {"cmd":"action","action":"find","params":{"strategy":"id","selector":"com.edmobilelabs.sling.dev:id/btnPositive","context":"","multiple":false}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"id","selector":"com.edmobilelabs.sling.dev:id/btnPositive","context":"","multiple":false}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: find
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding 'com.edmobilelabs.sling.dev:id/btnPositive' using 'ID' with the contextId: '' multiple: false
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[INSTANCE=0, RESOURCE_ID=com.edmobilelabs.sling.dev:id/btnPositive]
[AndroidBootstrap] Received command result from bootstrap
[MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"5"}
[HTTP] <-- POST /wd/hub/session/2a637b2d-319f-4509-b46b-58c8bcd57551/element 200 649 ms - 87 
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":{"ELEMENT":"5"}}
[HTTP] --> GET /wd/hub/session/2a637b2d-319f-4509-b46b-58c8bcd57551/element/5/displayed {}
[MJSONWP] Calling AppiumDriver.elementDisplayed() with args: ["5","2a637b2d-319f-4509-b46b-58c8bcd57551"]
[AndroidBootstrap] Sending command to android: {"cmd":"action","action":"element:getAttribute","params":{"attribute":"displayed","elementId":"5"}}

there is difference in the element Id  for unsucessful is 5  and for successful it  is  6

and following are my logs 

page source when the button clicked is successful

<?xml version="1.0" encoding="UTF-8"?><hierarchy rotation="0"><android.widget.FrameLayout index="0"
 text="" class="android.widget.FrameLayout" package="com.edmobilelabs.sling.dev" content-desc="" 
 checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" 
 scrollable="false" long-clickable="false" password="false" selected="false" bounds="[149,562][570,766]" 
 resource-id="" instance="0"><android.widget.LinearLayout index="0" text="" class="android.widget.LinearLayout" 
 package="com.edmobilelabs.sling.dev" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" 
 focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" 
 bounds="[149,562][570,766]" resource-id="" instance="0"><android.widget.FrameLayout index="0" text="" class="android.widget.FrameLayout" 
 package="com.edmobilelabs.sling.dev" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" 
 long-clickable="false" password="false" selected="false" bounds="[149,562][570,766]" resource-id="android:id/content" instance="1"><android.widget.LinearLayout index="0" text=""
  class="android.widget.LinearLayout" package="com.edmobilelabs.sling.dev" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" 
  focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[149,562][570,766]" resource-id="" instance="1"><android.widget.LinearLayout index="0" 
  text="" class="android.widget.LinearLayout" package="com.edmobilelabs.sling.dev" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false"
   focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[203,612][516,708]" resource-id="" instance="2"><android.widget.ProgressBar index="0" 
   text="" class="android.widget.ProgressBar" package="com.edmobilelabs.sling.dev" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false"
    focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[203,612][299,708]" resource-id="com.edmobilelabs.sling.dev:id/pbLoader" instance="0"/>
    <android.widget.TextView index="1" text="Sending OTP..." class="android.widget.TextView" package="com.edmobilelabs.sling.dev" content-desc="" checkable="false" checked="false" 
    clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[323,639][516,680]" 
    resource-id="com.edmobilelabs.sling.dev:id/tvMessage" instance="0"/>
    </android.widget.LinearLayout></android.widget.LinearLayout></android.widget.FrameLayout></android.widget.LinearLayout></android.widget.FrameLayout></hierarchy>

page source when the button clicked is not successful

<?xml version="1.0" encoding="UTF-8"?><hierarchy rotation="0"><android.widget.FrameLayout index="0" 
text="" class="android.widget.FrameLayout" package="com.edmobilelabs.sling.dev" 
content-desc="" checkable="false" checked="false" clickable="false" enabled="true" 
focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[40,311][680,607]" 
resource-id="" instance="0"><android.widget.LinearLayout index="0" text="" class="android.widget.LinearLayout" package="com.edmobilelabs.sling.dev" 
content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" 
long-clickable="false" password="false" selected="false" bounds="[40,311][680,607]" resource-id="" instance="0"><android.widget.FrameLayout index="0" text="" class="android.widget.FrameLayout"
 package="com.edmobilelabs.sling.dev" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" 
 long-clickable="false" password="false" selected="false" bounds="[40,311][680,607]" resource-id="android:id/content" instance="1"><android.widget.RelativeLayout index="0" text="" 
 class="android.widget.RelativeLayout" package="com.edmobilelabs.sling.dev" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" 
 focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[40,311][680,607]" resource-id="" instance="0"><android.widget.RelativeLayout index="0" 
 text="" class="android.widget.RelativeLayout" package="com.edmobilelabs.sling.dev" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" 
 focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[94,361][626,437]" resource-id="com.edmobilelabs.sling.dev:id/topSection" instance="1">
 <android.widget.TextView index="0" text="You will receive an SMS on +91 9*********5. Proceed?" class="android.widget.TextView" package="com.edmobilelabs.sling.dev" content-desc="" checkable="false" 
 checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[94,361][626,437]"
  resource-id="com.edmobilelabs.sling.dev:id/tvMessage" instance="0"/>
  </android.widget.RelativeLayout><android.widget.LinearLayout index="1" text="" class="android.widget.LinearLayout" 
  package="com.edmobilelabs.sling.dev" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" 
  password="false" selected="false" bounds="[352,485][674,597]" resource-id="com.edmobilelabs.sling.dev:id/llButtonBar" instance="1"><android.widget.Button index="0" text="CANCEL" 
  class="android.widget.Button" package="com.edmobilelabs.sling.dev" content-desc="" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[368,501][530,581]" 
  resource-id="com.edmobilelabs.sling.dev:id/btnNegative" instance="0"/><android.widget.Button index="1" text="OK" class="android.widget.Button" 
  package="com.edmobilelabs.sling.dev" content-desc="" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[530,501][658,581]" 
  resource-id="com.edmobilelabs.sling.dev:id/btnPositive" instance="1"/></android.widget.LinearLayout></android.widget.RelativeLayout></android.widget.FrameLayout></android.widget.LinearLayout>
  </android.widget.FrameLayout></hierarchy>

there is some change in the co-ordinates but the Id is same so I didn't think this matter 
I don't know but it can be the bug in appium

![capture](https://user-images.githubusercontent.com/22616085/29110935-03c92e2a-7d06-11e7-9205-e6b84ac7bfae.PNG)

**Comment by tfcardoso** [comment]
My 2cents,

I have a similar problem on one specific real device (a Samsung) on very similar dialogs, where sometimes the coordinates given are not the actual location of the button, so the actual tap occurs, but outside the OK button.

Run from your IDE and place a break point. Analise the location of the element to see if it really is where it is supposed.

**Comment by abisekkachroo** [comment]
@tfcardoso 
Its x and y co-ordinates  changes almost  everytime , cant understand but  why it should matter
Its id attribute is same , doesn't change

Moreover I have saw this unique issue like my test fails if it didn't meet with the if-condition
for e.g I have a code like 
                if(Country.isDisplayed()){
			Country.click();
			wait.until(ExpectedConditions.visibilityOf(Cancel));
			Cancel.click();
		}  
Normal code below this : 
this element country is present sometimes depending upon the api response 
but cant understand when  (if) condition is not met 
rest of the test-case is not executed 
Without executing the below code it shows  no such webelement exception

**Comment by abisekkachroo** [comment]
@tfcardoso , @mykola-mokhnach 
I have gone through the logs and in case of success bounds are  bounds="[323,639][516,680]" 
and in failure bounds are  bounds="[530,501][658,581]" 
What should I do in such a  case 
Could you please suggest

**Comment by jlipps** [comment]
I'm sorry @abisekkachroo but it doesn't seem that this is an appium error. If UiAutomator is returning incorrect bounds or differing bounds, that would be an Android issue. The element id is irrelevant; it just shows how many requests to that endpoint your script has been made. As a final suggestion, perhaps the `isDisplayed` check is not the one which is most suitable for your test case.
