### ISSUE TITLE
Appium Real Device error 

### ISSUE THREAD

**Issue by AdnanRafiqKhan** [appium/appium#8991]
## The problem

An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65

## Environment

All latest versions up till now

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Usually this error happens if WDA source is not signed properly. Read https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md fpr more details on device setup. 

Closed as duplicate.
