### ISSUE TITLE
How to get exact value in SQL Server

### ISSUE THREAD

**Issue by nageshkumarapp** [appium/appium#8992]
I am dividing 100000=Amount into 9=Shift into Days=30
But when I need the actual amount so how do I get it?

[In SQL](https://mindmajix.com/ssis-training):

Declare @R1 as money, @R2 as money, @R3 as money

Set @R1 = 100000 / 9 / 30
Set @R2 = @R1 * 9 * 30

select @R2 As 'ActualAmount'
I need exactly 100,000, but the result is 99900.00 - why?

**Comment by imurchie** [comment]
I think you need to look up IEEE floating point math. See, for instance, http://floating-point-gui.de/

But also, this is nothing to do with Appium. Closing.
