### ISSUE TITLE
Appium setup with python on Real Android Device

### ISSUE THREAD

**Issue by manusimply3333** [appium/appium#8993]
Can someone please help me to provide full setup of appium on Mac OSX with Python on android real device. It would be very helpful if can provide a simple code which just launch the play store.

Thanks in advance 

I have tried setup but every time i am getting error as Bad parameters. I have tried many links but most of are with JAVA and of python are not working on my system.

**Comment by mykola-mokhnach** [comment]
Check [sample code](https://github.com/appium/sample-code) repository or ask people on Appium forum.
