### ISSUE TITLE
No exception when pushing file to not existing or invalid path

### ISSUE THREAD

**Issue by pushFile** [appium/appium#8995]
## The problem

If I want to push a file to a not existing or not writeable path no exception occurs. Is that a bug?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4 (with Appium Desktop)
* Last Appium version that did not exhibit the issue (if applicable): -
* Desktop OS/version used to run Appium: Windows 7
* Node.js version (unless using Appium.app|exe): -
* Mobile platform/version under test: Android 7
* Real device or emulator/simulator: real
* Appium CLI or Appium.app|exe: -

## Details

I'm using the Appium Python Client (0.24) and want to send a file to the device. If the path exists and is writable everything works fine. But if I send it to "/foo/bar" there is no response that the file transfer fails.

In contrast pull_file works in that case, there is an exception when getting a not existing file.

Also when using adb directly an exception occurs (adb: error: failed to copy 'file.log' to '/foo/bar').

## Link to Appium logs
```

[HTTP] --> POST /wd/hub/session/7c770de8-0914-4880-8025-37401bf35323/appium/device/push_file {"path":"/foo/bar","sessionId":"7c770de8-0914-4880-8025-37401bf35323","data":"...
[MJSONWP] Calling AppiumDriver.pushFile() with args: ["/foo/bar",...
[ADB] Running 'C:\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","ZY223S8FKT","push","C:\\Users\\...\\AppData\\Local\\Temp\\appium11778-9628-i7f2td.bhnv29be29.tmp","/foo/bar"]
[MJSONWP] Responding to client with driver.pushFile() result: null
[HTTP] <-- POST /wd/hub/session/7c770de8-0914-4880-8025-37401bf35323/appium/device/push_file 200 80 ms - 76 
[HTTP] --> POST /wd/hub/session/7c770de8-0914-4880-8025-37401bf35323/appium/device/pull_file {"path":"/foo/bar","sessionId":"7c770de8-0914-4880-8025-37401bf35323"}
[MJSONWP] Calling AppiumDriver.pullFile() with args: ["/foo/bar","7c770de8-0914-4880-8025-37401bf35323"]
[ADB] Running 'C:\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","ZY223S8FKT","pull","/storage/emulated/0/2017-08-08__14-44-03_TT.png","C:\\Users\\...\\AppData\\Local\\Temp\\appium11778-9628-yufnzd.6wxxhia4i.tmp"]
[MJSONWP] Encountered internal error running command: Error: ENOENT: no such file or directory, open 'C:\Users\...\AppData\Local\Temp\appium11778-9628-yufnzd.6wxxhia4i.tmp' at Error (native)
[HTTP] <-- POST /wd/hub/session/7c770de8-0914-4880-8025-37401bf35323/appium/device/pull_file 500 67 ms - 293
```

**Comment by mykola-mokhnach** [comment]
What is the output of 

```
C:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s ZY223S8FKT push C:\\windows\\explorer.exe /foo/bar
```

command? The driver code says that adb creates target folder hierarchy automatically.

**Comment by imurchie** [comment]
Also, what is the output of `C:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s ZY223S8FKT ls /foo/bar`?

**Comment by pushFile** [comment]
```C:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s ZY223S8FKT push C:\\windows\\explorer.exe /foo/bar```
gives
```adb: error: failed to copy 'C:\\windows\\explorer.exe' to '/foo/bar': remote secure_mkdirs failed: Read-only file system C:\\windows\\explorer.exe: 0 files pushed. 14.4 MB/s (196608 bytes in 0.013s)```

```C:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s ZY223S8FKT shell ls /foo/bar```
gives
```ls: /foo/bar: No such file or directory```

For the sake of completeness I've tested the same ADB and Appium commands with an Android 7.1 emulator and got the same results.

**Comment by mykola-mokhnach** [comment]
Can you also check the exit code value there? For me it looks like adb prints an error, but the exit code is still zero...

just execute
```
echo Exit Code is %errorlevel%
```

after the adb push command above.

**Comment by pushFile** [comment]
`Exit Code is 1`

Can you reproduce the problem or is it just me?

**Comment by mykola-mokhnach** [comment]
Now I see the problem.

@imurchie We silence adb errors if stdout is not empty:

```js
  let execFunc = async () => {
    let linkerWarningRe = /^WARNING: linker.+$/m;
    try {
      if (!(cmd instanceof Array)) {
        cmd = [cmd];
      }
      let args = this.executable.defaultArgs.concat(cmd);
      log.debug(`Running '${this.executable.path}' with args: ` +
                `${JSON.stringify(args)}`);
      let {stdout} = await exec(this.executable.path, args, opts);
      // sometimes ADB prints out weird stdout warnings that we don't want
      // to include in any of the response data, so let's strip it out
      stdout = stdout.replace(linkerWarningRe, '').trim();
      return stdout;
    } catch (e) {
      let protocolFaultError = new RegExp("protocol fault \\(no status\\)", "i").test(e);
      let deviceNotFoundError = new RegExp("error: device ('.+' )?not found", "i").test(e);
      if (protocolFaultError || deviceNotFoundError) {
        log.info(`Error sending command, reconnecting device and retrying: ${cmd}`);
        await sleep(1000);
        await this.getDevicesWithRetry();
      }

      if (e.stdout) {
        let stdout = e.stdout;
        stdout = stdout.replace(linkerWarningRe, '').trim();
        return stdout;
      }

      throw new Error(`Error executing adbExec. Original error: '${e.message}'; ` +
                        `Stderr: '${(e.stderr || '').trim()}'; Code: '${e.code}'`);
    }
  };
```

And in our case the error code is 1 and the actual stdout value: 

```
[100%] /foo/bar
adb: error: failed to copy '/Users/elf/Desktop/Thumbs.db' to '/foo/bar': secure_mkdirs failed: Read-only file system
```

I would like to know on which stage should we handle the error - either here or inside adb-commands module by analyzing the actual command output or return the actual output to the corresponding driver and handle it there?

**Comment by imurchie** [comment]
I think it should be done here. Adding stdout to the message. Only returning stdout alone if code is 0.

**Comment by pushFile** [comment]
Thanks for your investigation!

I'll guess it will be fixed in the next version?
