### ISSUE TITLE
XCUITest enabled property for ImageView returns always true

### ISSUE THREAD

**Issue by morpheus554** [appium/appium#8996]
## The problem

During checking UiImageView properties enabled property is returned always as true.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5 and earlier probably also
* Last Appium version that did not exhibit the issue (if applicable): n/a
* Desktop OS/version used to run Appium: MacOS Sierra 10.12.3
* Node.js version (unless using Appium.app|exe): v7.7.3
* Mobile platform/version under test: iOS 10.0.2, objective-c
* Real device or emulator/simulator: both - checked 
* Appium CLI or Appium.app|exe: cli

## Details

In my test application I got UIImageView which has set property userInteractionEnabled to false. When I'm trying to get this value using isEnabled or isWDEnabled I'm getting always value false. Is there a way of getting value from userInteractionEnabled using appium? I thought that isEnabled was best choice since UIImageView doesn't have setEnabled method.

## Link to Appium logs

No need to attach logs.

**Comment by mykola-mokhnach** [comment]
Appium gets the value of enabled property directly from WebDriverAgent (and WDA itself gets it from _isEnabled_ property of the corresponding XCUIElement instance) and there is nothing we can change there. Please report you issue directly to https://github.com/facebook/WebDriverAgent/issues if you think it is a bug.

**Comment by morpheus554** [comment]
@mykola-mokhnach  thank you for quick reply. 

You confirmed me investigation which I've made already. I've noticed that XCUITest framework returns same value. But do you know maybe if we can extract userInteractionEnabled property somehow?

**Comment by mykola-mokhnach** [comment]
You could a PR to WebDriverAgent
