### ISSUE TITLE
iOS application is opened and closed in simulator. 

### ISSUE THREAD

**Issue by tamuntech** [appium/appium#8997]
## The problem

I am starting the new session from appium desktop 1.6.5. It opened the app and closed immediately. I tried to find the solution but unable to get it. I posted my logs in gist. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Sierra latest
* Node.js version (unless using Appium.app|exe): 8.1
* Mobile platform/version under test: 10.3
* Real device or emulator/simulator: xcode simulattor iPhone 7
* Appium CLI or Appium.app|exe:

Log is available here https://gist.github.com/tamuntech/4ef6640a6565d39fcef8f1bae7e67f0f

**Comment by imurchie** [comment]
The problem is most likely that you are using an app built for a real device, which will not run on a simulator.
```
[iOSLog] [IOS_SYSLOG_ROW] Aug  8 11:54:26 Bryans-MacBook-Pro com.apple.CoreSimulator.SimDevice.652724A1-17FF-4809-B006-93C268C28643.launchd_sim[24511] (UIKitApplication:com.app.Shadow[0x9552][24533][25031]): Program specified by service does not contain one of the requested architectures:
```

**Comment by tamuntech** [comment]
Thanks Murchie

Let me check and confirm here

**Comment by tamuntech** [comment]
Muchie and Mykola

Apologizes for the delay in update.... Hence I am an automation tester, I had the dependency on getting build. Still we are facing the same issue with simulator as well as in the real device. We are working on that.

**Comment by tamuntech** [comment]
It is working fine with simulator app.
