### ISSUE TITLE
Appium automation ridiculously slow - taking minutes to click element if not failing

### ISSUE THREAD

**Issue by asharma88** [appium/appium#8998]
Android Appium automation horrendously slow 

I keep seeing these errors 3˜4 times before an element is clicked, sometimes taking up to 5 minutes.

Aug 08, 2017 10:31:00 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://127.0.0.1:4723: The target server failed to respond
Aug 08, 2017 10:31:00 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://127.0.0.1:4723

## Environment

* Appium: 1.6.5
* Desktop OS/version used to run Appium: MAC os and Linux Ubuntu
* Node.js version (unless using Appium.app|exe): 8.1.0
* Mobile platform/version under test: Android 4.4.2 / 6.0 / 5.1.1
* Real device or emulator/simulator: Galaxy S5/Nexus 5/Emulators
* Appium CLI or Appium.app|exe: I tried app/cli the lot

## Details

click any element, check presence of any element ... basically do anything to find or operate on an element and either it won't find the element or it could take as long as minutes to click on an element

## Link to Appium logs

https://gist.github.com/asharma88/db380056f9c7674bcb3c5158c2bf3e20

## Code To Reproduce Issue
It looks like a general issue, no specific code is doing this

Please you can contact me on a1arjun@gmail.com for further details if required.

*Note-> Selendroid is working flawlessly super fast.

**Comment by mykola-mokhnach** [comment]
Do you have some background animations running while element location is performed?

**Comment by asharma88** [comment]
we don't have any animations in the app, its a location based app with google maps embedded.

**Comment by mykola-mokhnach** [comment]
I'd switch UIAtomator2. Note, that this backend is only supported by Android 5.0+

**Comment by asharma88** [comment]
we tried that without luck, we'll just stick to Selendroid and use coordinates for alerts

Thanks Arjun

**Comment by vjmaiky** [comment]
strange; i switched as a spike to uiautomator2 (using Uiselector) and it is working smooth...
