### ISSUE TITLE
iOS 11: Unable to take screenshot in Native context

### ISSUE THREAD

**Issue by mayureshshirodkar** [appium/appium#8999]
## The problem

Screenshot API returns a 500 error on trying to take a screenshot, when on Native context of the app.

Worked fine 
iOS- 10.3.3, Xcode 8.3.2
Issue with:
iOS- 11 public beta 4, Xcode 9.0 beta

## Environment

* Appium version (or git revision) that exhibits the issue: v1.6.6-beta.3
* Last Appium version that did not exhibit the issue (if applicable): v1.6.6-beta.3
* Desktop OS/version used to run Appium:
* Mobile platform/version under test: iOS 11 public beta
* Real device or emulator/simulator: iPhone 5s
* Appium CLI or Appium.app|exe: Appium cli

## Link to Appium logs
https://gist.github.com/mayureshshirodkar/631c50edcd74c3cbced8b456d2ef88b4

## Code To Reproduce Issue [ Good To Have ]
driver.switchToNativeContext();
ATUReports.add(step_description, input, expected, actual, LogAs.FAILED, new CaptureScreen(CaptureScreen.ScreenshotOf.BROWSER_PAGE));
driver.switchToWebviewContext();

new CaptureScreen(CaptureScreen.ScreenshotOf.BROWSER_PAGE)-  
The above method internally uses (TakesScreenshot)driver).getScreenshotAs(OutputType.FILE);

**Comment by mykola-mokhnach** [comment]
Try the most recent beta release, which includes some useful WDA updates

**Comment by mayureshshirodkar** [comment]
@mykola-mokhnach  I am able to replicate the issue with Appium v1.6.6-beta.4.
Heres the log:
https://gist.github.com/mayureshshirodkar/32214833ca4ac30f461c6695524002ed

**Comment by mykola-mokhnach** [comment]
I believe it is XCTest issue. We anyway cannot do anything on Appium side to fix it.

**Comment by mayureshshirodkar** [comment]
@mykola-mokhnach This could be a problem, while using the appium inspector on the Appium desktop app  with iOS 11 as the screenshots are taken natively.

**Comment by mykola-mokhnach** [comment]
It might be, but there is no other way to get a screenshot. Welcome to the world of proprietary software.

**Comment by mykola-mokhnach** [comment]
@mayureshshirodkar We've recently added a [fallback](https://github.com/appium/appium-xcuitest-driver/pull/510) for getting real device screenshot. Make sure you have idevicescreenshot tool available  on the machine where the test is running, update appium to the most recent beta version and try again.

**Comment by mayureshshirodkar** [comment]
I tried the beta and it works. Thanks @mykola-mokhnach for considering this and providing a workaround.

**Comment by dilsreccse** [comment]
I'm facing the issue while taking screenshot in iOS 11.0 , could you help me how to install  idevicescreenshot tool on mac ?
Log : [debug] [MJSONWP] Calling AppiumDriver.getScreenshot() with args: ["c28cfb6e-f32d-4870-af14-b257969a5c82"]
[debug] [XCUITest] Executing command 'getScreenshot'
[debug] [XCUITest] Taking screenshot with 'idevicescreenshot'
[XCUITest] Error getting screenshot: this.getOrientation is not a function
[debug] [XCUITest] Retrying screenshot through WDA
[debug] [JSONWP Proxy] Proxying [GET /screenshot] to [GET http://localhost:8100/session/6E770FEC-FE26-47BF-A72D-37F3C28E9823/screenshot] with no body
[debug] [iProxy] Error connecting to device!


Kindly help to resolve this issue @mykola-mokhnach

**Comment by imurchie** [comment]
@dilsreccse Please upgrade your Appium server. This issue has been fixed.

**Comment by dilsreccse** [comment]
Hi @imurchie thank you! It worked :+1:
