### ISSUE TITLE
Android: Unable to create session on emulator with API>=23

### ISSUE THREAD

**Issue by vmaxim** [appium/appium#9000]
## The problem
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command.
Original error: Error executing adbExec.
Original error: 'Command 'C\:\\Users\\xxx\\android-sdk\\platform-tools\\adb.exe -P 5037 -s emulator-5554 shell appops set io.appium.settings android\:mock_location allow' exited with code 4294967295';
Stderr: '**Error: No UID for io.appium.settings in user 0'; Code: '4294967295**' (WARNING: The server did not provide any stacktrace information)

## Environment

* Appium version (or git revision) that exhibits the issue: **v1.6.6-beta.4**
* Last Appium version that did not exhibit the issue (if applicable): **v1.6.3**
* Desktop OS/version used to run Appium: **Win+Mac**
* Node.js version (unless using Appium.app|exe): **v6.11.0**
* Mobile platform/version under test: **Android API>=23**
* Real device or emulator/simulator: **Emulator**
* Appium CLI or Appium.app|exe: **CLI**

## Link to Appium logs

https://gist.github.com/vmaxim/79c608c0fc15ad9928fe7bd293f89648

**Comment by mykola-mokhnach** [comment]
The fix has been merged and is available in the recent Appium beta

**Comment by AnastasiiaKravets** [comment]
I have the same problem even with the latest merged fixes.

Appium version (or git revision) that exhibits the issue: v1.6.6-beta.4
Desktop OS/version used to run Appium: Win
Mobile platform/version under test: Android API>=24
Real device or emulator/simulator: Emulator
Appium CLI or Appium.app|exe: CLI
