### ISSUE TITLE
Appium can't find the TableCell

### ISSUE THREAD

**Issue by KarenXuan** [appium/appium#9001]
I am using Appium for iOS automation test, in one page there is a tableView, in the tableView there is some cell, I can see the cell in page, and I can get the cell in Appium.app in inspect elements as XCUIElementTypeCell, but in the code, I can't find the cells, no matter I use by.xpath or by.classname or other function, and I use getPageSource to printf all the page elements, there is only XCUIElementTypeTable but no XCUIElementTypeCell, why there is no XCUIElementTypeCell in the page source?
PS. I just meet the issues in one page, the other pages are ok.

**Comment by mykola-mokhnach** [comment]
Appium receives the page source from WebDriverAgent. So if there is an issue then it should be reported to https://github.com/facebook/WebDriverAgent/issues

Closed as third party issue
