### ISSUE TITLE
xcodebuild exited with code '65' and signal 'null'

### ISSUE THREAD

**Issue by davidmorrison1981** [appium/appium#9003]
## The problem
I cant get appium to run because  WebDriverAgent wont install.  I have followed this:

 https://github.com/imurchie/appium-xcuitest-driver/blob/isaac-rs/docs/real-device-config.md#basic-manual-configuration.  Basic Config didnt work so I am following the Full Manual Config.

I got as far as locating where appium is installed but no such file or directory exists for /lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent

Can you help please.

## Environment

* Appium version (or git revision) that exhibits the issue: v1.6.5
* Last Appium version that did not exhibit the issue (if applicable): n/a
* Desktop OS/version used to run Appium: Mac OS 10.12.6
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS 10.1.1
* Real device or emulator/simulator: Device
* Appium CLI or Appium.app|exe: Appium.app

## Link to Appium logs

https://gist.github.com/davidmorrison1981/bbf99f8aee8b0bd9236320c1163f8161

**Comment by imurchie** [comment]
Is is not that `/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent` doesn't exist, but that `WebDriverAgentRunner-Runner.app` doesn't exist. This is a product of xcodebuild, and most usually a signing problem.

Can you run the following and post a link to the logs in a [gist](https://gist.github.com):
```
cd /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent

xcodebuild build-for-testing test-without-building -project /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=6e8cb3def2c41f327dc34a8484926fd95e1f79a2 -configuration Debug IPHONEOS_DEPLOYMENT_TARGET=10.1 -xcconfig /var/folders/np/k7r_38056j709m2jq6gxljyc0000gn/T/201779-9400-s27skm.bz834sra4i/appium-temp.xcconfig
```

**Comment by davidmorrison1981** [comment]
I realised after I ran this, my real device was unplugged, which is why it flagged the id could not be found but I assume the rest of the log is useful

<script src="https://gist.github.com/davidmorrison1981/2cfe557f392c856f691ce73fb8e21885.js"></script>

**Comment by mykola-mokhnach** [comment]
> No certificate matching 'iPhone Developer: David Morrison (3MP484KWU2)' for team '3MP484KWU2': Select a different signing certificate for CODE_SIGN_IDENTITY, a team that matches your selected certificate, or switch to automatic provisioning.

This is for sure signing problem

**Comment by mykola-mokhnach** [comment]
Closed as duplicate
