### ISSUE TITLE
Appium Desktop App 1.6.5 Record and Playback Issue

### ISSUE THREAD

**Issue by claudespivy** [appium/appium#9004]
**Details**

Currently, using Appium desktop 1.6.5 on OS X 10.12.6 with iPhone6s (iOS 10.3.1) simulator. I am able to use inspector and record my interactions in ruby withy my company iOS mobile application. Unfortunately, when I playback my recording the scripts stops when trying to access table element el2 (see code below) and displays error message XCTRunner[1830:67966] Enqueue Failure: Failure fetching attributes for element  Device element: Error Domain=XCTDaemonErrorDomain Code=13 "Error copying attributes (see log link below). Any help would be greatly appreciated. 

**Environment**

Appium: 1.6.5
Desktop OS/version used to run Appium: MAC OS X 10.12.6 
Node.js version (unless using Appium.app|exe): 8.2.1
Mobile platform/version under test:  iOS 10.3.1
Real device or emulator/simulator:  iPhone6s (iOS 10.3.1) simulator
Appium CLI or Appium.app|exe: Appium.exe Desktop

**Code To Reproduce Issue** 

require 'rubygems'
require 'appium_lib'

caps = {}
caps["platformName"] = "iOS"
caps["platformVersion"] = "10.3.1 (14E8301)"
caps["deviceName"] = "iPhone 6s"
caps["app"] = "/Users/example/Desktop/Example QA.app"
caps["browserName"] = "undefined" # Add undefined manually
caps["newCommandTimeout"] = 300
caps["udid"] = "15212345-3250-40E2-8B01-D08289E12345"
opts = {
    sauce_username: nil,
    server_url: "http://localhost:4723/wd/hub"
}
driver = Appium::Driver.new({caps: caps, appium_lib: opts}).start_driver

el1 = driver.find_element(:xpath, "//XCUIElementTypeButton[@name=\"Allow\"]")
el1.click
el2 = driver.find_element(:xpath, "//XCUIElementTypeStaticText[@name=\"Register\"]") 
el2.click
el3 = driver.find_element(:xpath, "//XCUIElementTypeTextField[@name=\"Email\"]")
el3.click
el3.send_keys "example@example"
el4 = driver.find_element(:xpath, "//XCUIElementTypeSecureTextField[@name=\"Password\"]")
el4.click
el4.send_keys "12345"
el5 = driver.find_element(:xpath, "//XCUIElementTypeTextField[@name=\"Zip Code\"]")
el5.click
el5.send_keys "12345"
el6 = driver.find_element(:xpath, "//XCUIElementTypeApplication[@name=\"Example QA\"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeTable")
el6.click

driver.quit

**Link to Appium logs:**

https://gist.github.com/claudespivy/4c7e41a6ec82ccf3cb2c910641b1e198

**Comment by dpgraham** [comment]
The recorder isn't guaranteed to generate perfect Appium scripts. It's just meant to generate a script that gives you a starting point for writing Appium scripts.

Looking at your script you should probably take browserName out, and also try running the script without doing any interactions:

```ruby
caps = {}
caps["platformName"] = "iOS"
caps["platformVersion"] = "10.3.1 (14E8301)"
caps["deviceName"] = "iPhone 6s"
caps["app"] = "/Users/example/Desktop/Example QA.app"
caps["newCommandTimeout"] = 300
caps["udid"] = "15212345-3250-40E2-8B01-D08289E12345"
opts = {
sauce_username: nil,
server_url: "http://localhost:4723/wd/hub"
}
driver = Appium::Driver.new({caps: caps, appium_lib: opts}).start_driver
```

If that fails, then you probably may have an issue with your Appium configuration.

**Comment by mykola-mokhnach** [comment]
> XCTRunner[1830:67966] Enqueue Failure: Failure fetching attributes for element Device element: Error Domain=XCTDaemonErrorDomain Code=13 "Error copying attributes

This is known XCTest issue. Try NOT to use XPath locators to workaround it. Check https://github.com/facebook/WebDriverAgent/issues/372 for more details.
