### ISSUE TITLE
How to kill app and start it again without cleaning app data on Android

### ISSUE THREAD

**Issue by egorvas** [appium/appium#9006]
## The problem

Hi, I am trying to find a way how to kill application on Android with appium without erasing application data.
I tried to use:
- driver.resetApp()
- driver.stopApp()
- driver.launchApp()
- driver.startActivity(activity.setStopApp(true))

But in all this cases application data erasing after performing this commands and capability noReset = true cann't change it.

So, my question is, how can I do it?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.6 beta
* Desktop OS/version used to run Appium: OSX
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Both

**Comment by mykola-mokhnach** [comment]
Set _noReset_ to true then quite the driver and start it again with the same capabilities.

**Comment by amedvedjev** [comment]
@egorvas if you want to do it in ONE test i use:
```
        driver.closeApp();
        try {driver.runAppInBackground(Duration.ofSeconds(1));} catch (Exception e){}
```

**Comment by sebinjqburst** [comment]
Hi @mykola-mokhnach,

Is there a way to launch an app from the background with the same screen I was using prior? I'm using runAppInBackground to push my App into background and then turn off wifi by getting into Settings using activateApp("com.apple.Preferences"). Now I want launch my application back with the same screen I was using. Any help is appreciated.

**Comment by campus10049158** [comment]
Activity activity = new Activity("package name","activity name");
			activity.setStopApp(false); 
			((StartsActivity) driver).startActivity(activity);
