### ISSUE TITLE
New to Automation - Need guidance in installing Appium for iOS App Automation 

### ISSUE THREAD

**Issue by marysubaidha** [appium/appium#9008]
## The problem

1. I am new to Software Automation Testing. 
2. I need to use Appium to automate API, Functional, and UI test cases of my iOS App. 
3. I need guidance (preferably video links) in configuring Appium with my iOS App 

## Environment

1. Appium Version : 1.2.0-beta.1 (1.2.0-beta.1)
2. Desktop OS : mac OS Sierra Version 10.12.6
3. Mobile Platform : iOS 
4. Device Version : 10.3.3 
5. Real Device and Simulators 

## Details
1. I installed JDK 
2. Appium is installed 
3. Eclipse is installed 
4. Source code is downloaded and running successfully in Simulators and Real time devices 
5. When I started using Appium, I reached to the below-mentioned screenshot. I do not know how to start from here 

<img width="1570" alt="screen shot 2017-08-10 at 5 06 12 pm" src="https://user-images.githubusercontent.com/28738211/29197272-10d49192-7def-11e7-8fe2-5317cbfcbe10.png">

**Comment by mykola-mokhnach** [comment]
Sorry, but we don't provide guidances here. Please post your questions to [Appium forum](https://discuss.appium.io/).
