### ISSUE TITLE
Check scroll position relatively to the application

### ISSUE THREAD

**Issue by uarlouski** [appium/appium#9009]
## The question
   Hello,
   During working I faced with issue when I need to know if the scroll at the top of application or at the bottom, so do we have any possibility to check it? Solution with swipe, when we check page source after and before swipe for checking start or end of application isn't applicable for me.

**Comment by amedvedjev** [comment]
@uarlouski with iOS if you know your first/last element you can detect with Android no way. As workaround you may try to swipe and see if visible elements are changing.
