### ISSUE TITLE
Got response with status 200: {"value":"Failed to open url","sessionId":"id","status":13

### ISSUE THREAD

**Issue by Zaakupendrak** [appium/appium#9011]
## The problem

Hello! 

I'm working on mobile Safari automation testing using PC OS X 10.12.6, Appium v1.6.5, simulated iOS 10.3. The problem is I got connection beetwen PC and simulator but can't get any URL. I have new iOSDriver started with URL http://127.0.0.1:4723/wd/hub, it seems safari is working. Got response with: "Let's browse!". But when I want iOSDriver to get any URL for ex. google.com my java program throws error: "Failed to open http://google.com" (no matter if it's http or https) and appium gives back 200 response code which says: Got response with status 200: {"value":"Failed to open https://google.com","sessionId":"CE4A34DB-0799-4C83-B421-53D0858A53F3","status":13}. I tried different configurations but stuck on this. I got no problem testing:
- via linux:  desktop chrome and android chrome sessions
- via OS X:  desktop Safari sessions.

I provide debug log from appium and piece of my java code what I run. I start Appium from terminal with:
appium --log-level debug -a 127.0.0.1 -p 4723 
and then perform test my Java code from Netbeans IDE.

I'm not sure if I need to set context to NATIVE_APP or stay with WEBVIEW_xxxx.x. But with WebView iIgot error when executing java test that driver.get is not implemented yet.

Lookin forward your help. 

## Environment

* Appium version (or git revision) that exhibits the issue: v1.6.5
* Last Appium version that did not exhibit the issue (if applicable): --------
* Desktop OS/version used to run Appium: OS X 10.12.6 Sierra
* Node.js version (unless using Appium.app|exe): v6.11.1
* Mobile platform/version under test: iOS 10.3 
* Real device or emulator/simulator: Simulator 
* Appium CLI or Appium.app|exe: Appium CLI

## Details

The driver cant get any URL by itself from java test code but when I try to get it by myself typing google.com inside safari URL bar it easily get google search site.

## Link to Appium logs

Here is Appium log from terminal with log-level = debug https://gist.github.com/Zaakupendrak/22b1bae0ee7bed1a8dbce725a0d1f4c6

## Code To Reproduce Issue [ Good To Have ]

Here is core code of my test program:
https://gist.github.com/Zaakupendrak/d225528afbda43aa36a975d0b266bc4e

**Comment by imurchie** [comment]
Do _not_ set the context to anything. It is already in the MobileSafari webview.

The url setting you are currently doing is trying to open a deep link in the native MobileSafari app.

**Comment by Zaakupendrak** [comment]
I have tried it before like I said in 1st comm. 

When I don't set any context i got this from apium:
https://gist.github.com/Zaakupendrak/cde844ffa2345cf3324b17b070de273a

And iOSDriver still stuck on 127.0.0.1/welcome: Let's browse! and nothing more happens.

**Comment by imurchie** [comment]
What is the error being returned from setting the url (the server indicates it returns a 501, but not what is returned).

**Comment by Zaakupendrak** [comment]
I don't know if I understand you correctly.

IDE gives me error while executing line "wd.get("https://google.com");"
and says that "Method is not implemented yet" throwing WebDriverException.

here is surefire-report
https://gist.github.com/Zaakupendrak/7094222385ec5a4b00df8e4ff996c039

**Comment by imurchie** [comment]
This is very strange. The method is definitely implemented. I will try to reproduce.

**Comment by Zaakupendrak** [comment]
I dont know if it's important or not (and I don't want to waste your time) but im using hackintosh not Apple device.  May it be linked with the problem?

And just for info: we got vacation time now in Poland so it may happen I'll give next reply in the middle of next week.

**Comment by imurchie** [comment]
I have no idea if Hackintosh would make a difference.

**Comment by Zaakupendrak** [comment]
Ok, if you will not be able to reproduce I ll try get access to Apple desktop device.

**Comment by Zaakupendrak** [comment]
@imurchie  have u found anything?

**Comment by shapovalovei** [comment]
@Zaakupendrak  try use RemoteWebDriver

**Comment by jlipps** [comment]
@Zaakupendrak the only issue here appears to be that you are entering the native context when you do not need to.

**Comment by Tverdomi** [comment]
With remote driver and	capabilities.setCapability(MobileCapabilityType.AUTO_WEBVIEW, true);

landed on Page: appium.io

error:

[debug] [JSONWP Proxy] Got response with status 200: {"value":"Failed to open https://google.ch","sessionId":"23D79271-1EB3-4D9C-A47D-42BA80AEEC86","status":13}

info AppiumDoctor Appium Doctor v.1.4.3
info AppiumDoctor ### Diagnostic starting ###
info AppiumDoctor  ✔ The Node.js binary was found at: /usr/local/bin/node
info AppiumDoctor  ✔ Node version is 6.11.2
info AppiumDoctor  ✔ Xcode is installed at: /Applications/Xcode.app/Contents/Developer
info AppiumDoctor  ✔ Xcode Command Line Tools are installed.
info AppiumDoctor  ✔ DevToolsSecurity is enabled.
info AppiumDoctor  ✔ The Authorization DB is set up properly.
info AppiumDoctor  ✔ Carthage was found at: /usr/local/bin/carthage
info AppiumDoctor  ✔ HOME is set to: /Users/########
info AppiumDoctor ### Diagnostic completed, no fix needed. ###
info AppiumDoctor 
info AppiumDoctor Everything looks good, bye!

macOS Sierra Version 10.12.6

nodeconfig.json
{
"capabilities": [
{
"browserName" : "safari",
"maxInstances" : 1,
"platform" : "mac",
"platformName" : "iOS",
"platformVersion" : "10.3.3",
"deviceName" : "Miklos"
}
],
"configuration": {
"cleanUpCycle" : 2000,
"timeout" : 300000,
"browserTimeout" : 60000,
"proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
"hub" : "http://127.0.0.1:4444/grid/register",
"maxSession" : 1,
"host" : "127.0.0.1",
"port" : 4723,
"hubPort" : 4444,
"hubHost" : "127.0.0.1",
"url" : "http://127.0.0.1:4723/wd/hub",
"register" : true,
"registerCycle" : 5000,
"role" : "node"
}
}

**Comment by Tverdomi** [comment]
Error Message on appium node:

Mikloss-Mac-mini:appium miklostverdota$ appium --nodeconfig nodeconfig.json
[Appium] Welcome to Appium v1.7.0-beta
[Appium] Non-default server args:
[Appium]   nodeconfig: nodeconfig.json




[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.7.0-beta","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 125 ms - 88 
[debug] [iOS] Navigating to most recently opened webview
[debug] [iOS] Retrieving contexts and views
[debug] [iOS] Selecting by url: true (expected url: 'http://appium.io')
[debug] [RemoteDebugger] Getting WebKitRemoteDebugger pageArray: localhost, 27753
[debug] [RemoteDebugger] Sending request to: http://localhost:27753/json
[debug] [RemoteDebugger] Page element JSON: [{"devtoolsFrontendUrl":"/devtools/devtools.html?ws=localhost:27753/devtools/page/1","faviconUrl":"","thumbnailUrl":"/thumb/http://appium.io/","title":"Appium: Mobile App Automation Made Awesome.","url":"http://appium.io/","webSocketDebuggerUrl":"ws://localhost:27753/devtools/page/1","appId":"PID:223"}]
[debug] [iOS] Retrieving contexts and views
[debug] [iOS] Selecting by url: true (expected url: 'http://appium.io')
[debug] [RemoteDebugger] Getting WebKitRemoteDebugger pageArray: localhost, 27753
[debug] [RemoteDebugger] Sending request to: http://localhost:27753/json
[debug] [RemoteDebugger] Page element JSON: [{"devtoolsFrontendUrl":"/devtools/devtools.html?ws=localhost:27753/devtools/page/1","faviconUrl":"","thumbnailUrl":"/thumb/http://appium.io/","title":"Appium: Mobile App Automation Made Awesome.","url":"http://appium.io/","webSocketDebuggerUrl":"ws://localhost:27753/devtools/page/1","appId":"PID:223"}]
[debug] [iOS] Picking webview 'NATIVE_APP'
[debug] [iOS] Attempting to set context to 'NATIVE_APP'
[debug] [RemoteDebugger] Unregistering from page readiness notifications
[debug] [BaseDriver] Event 'initialWebviewNavigated' logged at 1504696770299 (13:19:30 GMT+0200 (CEST))
[Appium] New XCUITestDriver session created successfully, session 3aed7712-e7a8-489d-b7a5-6cced37de5c4 added to master session list
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1504696770301 (13:19:30 GMT+0200 (CEST))
[debug] [MJSONWP] Responding to client with driver.createSession() result: {"webStorageEnabled":false,"locationContextEnabled":false,"browserName":"safari","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takesScreenshot":true,"networkConnectionEnabled":false,"appiumVersion":"1.7.0","platformVersion":"10.3.3","automationName":"XCuiTest","autoWebview":true,"platformName":"ios","udid":"c81bd81ebb9c7b41d282a6a244d11e51af827ff0","version":"","deviceName":"Miklos","launchTimeout":5000000}
[HTTP] <-- POST /wd/hub/session 200 47901 ms - 503 
[HTTP] --> POST /wd/hub/session/3aed7712-e7a8-489d-b7a5-6cced37de5c4/timeouts {"type":"implicit","ms":60000}
[debug] [MJSONWP] Calling AppiumDriver.timeouts() with args: ["implicit",60000,"3aed7712-e7a8-489d-b7a5-6cced37de5c4"]
[debug] [XCUITest] Executing command 'timeouts'
[debug] [BaseDriver] Set implicit wait to 60000ms
[debug] [MJSONWP] Responding to client with driver.timeouts() result: null
[HTTP] <-- POST /wd/hub/session/3aed7712-e7a8-489d-b7a5-6cced37de5c4/timeouts 200 6 ms - 76 
[HTTP] --> GET /wd/hub/status {}
[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.7.0-beta","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 13 ms - 88 
[HTTP] --> GET /wd/hub/status {}
[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.7.0-beta","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 118 ms - 88 
[HTTP] --> POST /wd/hub/session/3aed7712-e7a8-489d-b7a5-6cced37de5c4/url {"url":"https://google.ch"}
[debug] [MJSONWP] Calling AppiumDriver.setUrl() with args: ["https://google.ch","3aed7712-e7a8-489d-b7a5-6cced37de5c4"]
[debug] [XCUITest] Executing command 'setUrl'
[debug] [JSONWP Proxy] Proxying [POST /url] to [POST http://localhost:8100/session/23D79271-1EB3-4D9C-A47D-42BA80AEEC86/url] with body: {"url":"https://google.ch"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":"Failed to open https://google.ch","sessionId":"23D79271-1EB3-4D9C-A47D-42BA80AEEC86","status":13}
[HTTP] <-- POST /wd/hub/session/3aed7712-e7a8-489d-b7a5-6cced37de5c4/url 500 126 ms - 203 
[HTTP] --> GET /wd/hub/status {}
[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.7.0-beta","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 8 ms - 88 

https://guides.github.com/activities/hello-world/

https://github.com/appium/appium/issues/9011

**Comment by Zaakupendrak** [comment]
@shapovalovei 
Even with RemoteWebDriver I get message: failed - method not implemented yet

@jlipps 
I believe u didnt checked the whole thread where imurchie said me not to set the context at all. It's auto set to webview and i fixed it but still got error.

**Comment by Tverdomi** [comment]
Its easy to get out: first goes to webwiew and go to page http://appium.io, then change mode to native (Picking webview 'NATIVE_APP'). The next get(URL) goes wrong.

debug] [iOS] Navigating to most recently opened webview
[debug] [iOS] Retrieving contexts and views
[debug] [iOS] Selecting by url: true (expected url: 'http://appium.io')
[debug] [RemoteDebugger] Getting WebKitRemoteDebugger pageArray: localhost, 27753
[debug] [RemoteDebugger] Sending request to: http://localhost:27753/json
[debug] [RemoteDebugger] Page element JSON: [{"devtoolsFrontendUrl":"/devtools/devtools.html?ws=localhost:27753/devtools/page/1","faviconUrl":"","thumbnailUrl":"/thumb/http://appium.io/","title":"Appium: Mobile App Automation Made Awesome.","url":"http://appium.io/","webSocketDebuggerUrl":"ws://localhost:27753/devtools/page/1","appId":"PID:223"}]
[debug] [iOS] Retrieving contexts and views
[debug] [iOS] Selecting by url: true (expected url: 'http://appium.io')
[debug] [RemoteDebugger] Getting WebKitRemoteDebugger pageArray: localhost, 27753
[debug] [RemoteDebugger] Sending request to: http://localhost:27753/json
[debug] [RemoteDebugger] Page element JSON: [{"devtoolsFrontendUrl":"/devtools/devtools.html?ws=localhost:27753/devtools/page/1","faviconUrl":"","thumbnailUrl":"/thumb/http://appium.io/","title":"Appium: Mobile App Automation Made Awesome.","url":"http://appium.io/","webSocketDebuggerUrl":"ws://localhost:27753/devtools/page/1","appId":"PID:223"}]
[debug] [iOS] Picking webview 'NATIVE_APP'

**Comment by jlipps** [comment]
@Zaakupendrak that is interesting. Can you try running Appium 1.7.0-beta to see if it persists? The line of code where it would be failing has been changed in master for some time.

**Comment by Tverdomi** [comment]
I am running on 1.7.0-Beta

[Appium] Welcome to Appium v1.7.0-beta
[Appium] Non-default server args:
[Appium]   nodeconfig: nodeconfig.json
[debug] [Appium] Starting auto register thread for grid. Will try to register every 5000 ms.
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[debug] [Appium] Appium successfully registered with the grid on 127.0.0.1:4444
[HTTP] --> GET /wd/hub/status {}
[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.7.0-beta","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 16 ms - 88 
[

**Comment by Tverdomi** [comment]
public class ConnectToSafari {
	static WebDriver wd = null;
	static String url = "https://google.ch";

	public static void main(String[] args) throws MalformedURLException, InterruptedException {
		DesiredCapabilities capabilities = new DesiredCapabilities().safari();
//		DesiredCapabilities capabilities = new DesiredCapabilities();
		capabilities.setCapability(MobileCapabilityType.APPIUM_VERSION, "1.7.0");
		capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "ios");
		capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "10.3.3");
		capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "Miklos");
		capabilities.setCapability(MobileCapabilityType.UDID,"c81bd81ebb9c7b41d282a6a244d11e51af827ff0");
		capabilities.setCapability(IOSMobileCapabilityType.LAUNCH_TIMEOUT,5000000);
		capabilities.setCapability(MobileCapabilityType.AUTO_WEBVIEW, true);
		capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME,AutomationName.IOS_XCUI_TEST);
//		capabilities.setCapability(MobileCapabilityType.BROWSER_NAME, "Safari");

		wd = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), capabilities);
		wd.manage().timeouts().implicitlyWait(60, TimeUnit.SECONDS);

		try {
			Thread.sleep(10000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}

        wd.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);   
        
//		wd.manage().deleteAllCookies();
		wd.get(url);
		
		try {
			Thread.sleep(20000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		// stopCollectCPU()
//		wd.close();
	}

**Comment by jlipps** [comment]
@Tverdomi nothing in what you've posted looks equivalent to what this issue is about. Please open a new issue with your full logs and a description of what's going on.

**Comment by Zaakupendrak** [comment]
@jlipps  

Almost I've lost all my hopes but we've got turn!

Removing latest 1.6.5 Appium and installing 1.7.0-beta (via npm install) solved the problem. I don't know if it was related to the Hackintosh or not. But now we got the answer: you can perform appium test on hackintosh pc too!! 
Test works for both IOSDriver and RemoteWebDriver.

**Comment by jlipps** [comment]
great news that upgrading to latest solved the problem, @Zaakupendrak! and thanks for confirming that a hackintosh will work as well :-)
