### ISSUE TITLE
Original error: 'Command '/Library/android-sdk-macosx/platform-tools/adb -P 5037 -s HT4AYJT00507 install /usr/local/lib/node_modules/appium/node_modules/appium-unlock/bin/unlock_apk-debug.apk' exited with code 1'; Stderr: 'Failed to install /usr/local/lib/node_modules/appium/node_modules/appium-unlock/bin/unlock_apk-debug.apk

### ISSUE THREAD

**Issue by Logakarti** [appium/appium#9012]
## The problem
The below exception throws while running the app cases in Android tablet devices.

Original error: 'Command '/Library/android-sdk-macosx/platform-tools/adb -P 5037 -s HT4AYJT00507 install /usr/local/lib/node_modules/appium/node_modules/appium-unlock/bin/unlock_apk-debug.apk' exited with code 1'; Stderr: 'Failed to install /usr/local/lib/node_modules/appium/node_modules/appium-unlock/bin/unlock_apk-debug.apk

## Environment

* Appium version : 1.6.6-beta.2
* Desktop OS/version used to run Appium: MAC Sierra 10.12.5 
* Mobile platform/version under test: 7.1.1
* Real device : Nexus 9

## Link to Appium logs
https://gist.github.com/Logakarti/08fc2654a336d3ffc66aa229917b36aa

## Code To Reproduce Issue [ Good To Have ]

public DesiredCapabilities androidcapabilities(String appPath, String appActivity, String appPackage, String autolaunch){
        File app=new File(appPath);
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability("noReset", true);
        capabilities.setCapability("fullReset", false);
        capabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, 300);//how long (in seconds) Appium will wait for a new command from the client before assuming the client quit and ending the session
        capabilities.setCapability(MobileCapabilityType.APP, app.getAbsolutePath());
        capabilities.setCapability(CapabilityType.BROWSER_NAME, "");
        capabilities.setCapability("autoWebview", "true");
        capabilities.setCapability("autoLaunch", Boolean.parseBoolean(autolaunch));
        capabilities.setCapability(MobileCapabilityType.APP_ACTIVITY,appActivity);
        capabilities.setCapability(MobileCapabilityType.APP_PACKAGE, appPackage);
        capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, MobilePlatform.ANDROID);
        capabilities.setCapability (MobileCapabilityType.DEVICE_NAME, "HT4AYJT00507");   
        capabilities.setCapability("chromedriverExecutable", "/Users/Gokul/Desktop/Chromedriver/27/chromedriver"); 
        return capabilities;
    }

Please anyone help to solve my problem.

**Comment by Logakarti** [comment]
@mykola-mokhnach

**Comment by mykola-mokhnach** [comment]
Remove the Appium Unlock application from the device manually

**Comment by Logakarti** [comment]
Thanks, @mykola-mokhnach. It works fine and app launched successfully, but the below exception throws in appium log after launching the app

Encountered internal error running the command: Error: Could not proxy. Proxy error: Chromedriver quit unexpectedly during session

Please find the appium log:
https://gist.github.com/Logakarti/243f7475fa4a1755cd731ba135bf537e

**Comment by mykola-mokhnach** [comment]
This has to be some other problem. Create another issue for it.

**Comment by Logakarti** [comment]
Thanks, @mykola-mokhnach. I have created the new issue for it.
