### ISSUE TITLE
integrity checksum failed when using sha1 while installing appium using npm.

### ISSUE THREAD

**Issue by pankajazy** [appium/appium#9018]
## The problem

not able to install via : npm install -g appium

## Environment

* Desktop OS/version WINDOWS 10 HOME 
* Node.js version (unless using Appium.app|exe):
C:\Users\Pankaj>npm version
{ npm: '5.3.0',
  ares: '1.10.1-DEV',
  cldr: '31.0.1',
  http_parser: '2.7.0',
  icu: '59.1',
  modules: '57',
  node: '8.2.1',
  openssl: '1.0.2l',
  tz: '2017b',
  unicode: '9.0',
  uv: '1.13.1',
  v8: '5.8.283.41',
  zlib: '1.2.11' }

## Details
link to log:
https://www.dropbox.com/s/wjnzs6jcj7e0tpq/2017-08-13T20_43_24_495Z-debug.log?dl=0

**Comment by mykola-mokhnach** [comment]
This issue is usually caused by an antivirus software or corporate firewall restrictions.

**Comment by pankajazy** [comment]
Even after disabling the firewall as i am installing it in my home. It is the same.
Another thing is that appium gui is working fine.

**Comment by jlipps** [comment]
The integrity checksum is not an appium issue, and could be caused by a variety of factors including general internet connectivity issues.
