### ISSUE TITLE
Tests running time very high due to some blockage

### ISSUE THREAD

**Issue by andreiaionitoaiesv** [appium/appium#9020]
## The problem

Every time I run a test at the same step / point, Appium seems to be stucked for like 3 minutes. 
Before this i'm looking for an element over and over, until it gets displayed and when that label is found the 200 response seems to kill the WDA and it gets stuck for a period(~ 3 minutes) then the test continue to run.

## Environment

Appium: 1.6.5
macOS Sierra: 10.12.6
Node.js: 8.1.4
Mobile platform/version under test: iPhone 6 Real Device, iOS version 10.3
xCode: 8.3.3

## Link to Appium logs

https://gist.github.com/andreiaionitoaiesv/047c2c2b25b022b7671bcd115561faa6

**Comment by mykola-mokhnach** [comment]
Check the device log - there might be something interesting there

**Comment by andreiaionitoaiesv** [comment]
Here are the logs. FYI now the this happens less and the waiting time is like 30 seconds. Here are the phone logs.

https://gist.github.com/andreiaionitoaiesv/399cb81019cac07d1afde075e96ff62b

**Comment by jlipps** [comment]
@mykola-mokhnach this would probably be a WDA issue if anything, right?

**Comment by mykola-mokhnach** [comment]
Yes, I don't think there is something we can improve on Appium side

**Comment by jlipps** [comment]
@andreiaionitoaiesv i would open an issue at the webdriveragent repo to see if anyone there has any ideas
