### ISSUE TITLE
Original error: Activity used to start app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity

### ISSUE THREAD

**Issue by bbaitikova** [appium/appium#9024]
## The problem

I am not  able to run my test cases using Appium. I have run them all the time, but today exactly same test cases stop working. I have not modified them. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Last Appium version that did not exhibit the issue (if applicable): 1.6.5
* Desktop OS/version used to run Appium: Mac sierra 
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Samsung S7, Marshmallow
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: Version 1.1.0-beta.4 (1.1.0-beta.4)

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

<script src="https://gist.github.com/bbaitikova/65c4adc494369eea92c087aba7a08438.js"></script>

## Code To Reproduce Issue [ Good To Have ]

class SetUpPage(unittest.TestCase):
    device_name = 'device_name'
    os_version = 'os_version'
    API_Level = 'API_Level'
    proc_video = None
    model_name = 'model_name'
    mobile_app_mt = "xxx.apk"
    app_package_mt = "xxx"

 def setUp(self):
        desired_caps = {
            'noSign': True,
            'platformName': 'Android',
            'platformVersion\n': self.os_version,
            'deviceName': self.device_name,
            'automationName': 'Appium',
            'appPackage': self.app_package_mt,
            'app': self.mobile_app_mt,
            'newCommandTimeout': 180,
            #"autoGrantPermissions": True,
            #'no-reset': False,
            'full-reset': True
        }

        self.driver = webdriver.Remote('http://127.0.0.1:4723/wd/hub', desired_caps)
        self.driver.implicitly_wait(100)

 def tearDown(self):
        pid = self.proc_video.pid
        os.kill(pid, signal.SIGINT)
        time.sleep(3)

from PageObjectModuleMT import Locators
from SetUpPage import SetUpPage
class Monster(SetUpPage):
    def setUp(self):
        super(Monster, self).setUp()
        self.value = Locators(self.driver)
        time.sleep(15)

    def test01_install_app(self):
        self.value.lock_tracking()

if __name__ == "__main__":
    unittest.main(verbosity=2)

**Comment by mykola-mokhnach** [comment]
Usually this problems happens if the application under test cannot start (for example because of a crash) or an incorrect activity is set as main/wait activity.

Please fix the link to Appium logs

**Comment by bbaitikova** [comment]
Link to gist: https://gist.github.com/bbaitikova/65c4adc494369eea92c087aba7a08438

**Comment by bbaitikova** [comment]
resolved by itself, did not changed anything. 
closing. raising other issue, tho.
