### ISSUE TITLE
sh ./Scripts/bootstrap.sh -d throws 'https://github.com/marekcirkos/peertalk.git/' not found

### ISSUE THREAD

**Issue by xlzdew** [appium/appium#9028]
sh ./Scripts/bootstrap.sh -d 
throws 'https://github.com/marekcirkos/peertalk.git/' not found
I tried accessing to https://github.com/marekcirkos/peertalk.git/ manually, it returns 404, this git project do not exist currently. See the full log as below
->sh ./Scripts/bootstrap.sh -d
Fetching dependencies
*** Checking out peertalk at "v1.0"
*** Cloning peertalk
*** Downloading RoutingHTTPServer.framework binary at "v1.0.1"
A shell task (/usr/bin/env git clone --bare --quiet https://github.com/marekcirkos/peertalk.git /Users/xxxx/Library/Caches/org.carthage.CarthageKit/dependencies/peertalk) failed with exit code 128:
remote: Repository not found.
fatal: repository 'https://github.com/marekcirkos/peertalk.git/' not found

**Comment by mykola-mokhnach** [comment]
You must update Appium to the most recent version (1.6.5) to fix this problem.

Closed as duplicate
