### ISSUE TITLE
setValue cut off texts on text field in iOS Simulator

### ISSUE THREAD

**Issue by Brad19** [appium/appium#9029]
## The problem

When I enter the text value with setValue method or sendKeys, I see that the texts values are cutting off. For eg., 

MobileElement email = (MobileElement) driver.findElement(MobileBy.xpath(locatorsForPersonalRego.get("email").toString()));
email.click();
email.setValue("Helloworld@test.com");

//1st time run - output
Hllwrld@tst.com

//2nd time run - output
Hlloworl@tet.com

Similarly the texts are cutting off accordingly for other text input fields. I think it should be impacting the secure field as well.

I'm not sure what is happening and how to proceed. Got struck for 1 day. I believe it should impact me for Android as well (Yet to try). Can anyone please advise.

## Environment
* Appium version - 1.6.5 and now upgraded to 1.6.6-beta.4
* Java-client - 5.0.0-BETA9
* Selenium-java - 3.3.1
* Application - React-Native
* Node.js version (unless using Appium.app|exe): v8.1.2 (Not sure if this matters)
* Mobile platform/version under test: Mobile 
* Real device or emulator/simulator: IOS Simulator 10.3
* Appium CLI or Appium.app|exe: -

## Reference
I saw the following issue and have upgraded my appium version from 1.6.5 to 1.6.6-beta.4 https://github.com/appium/appium/issues/8638

Thanks,
BradT

**Comment by mykola-mokhnach** [comment]
Try to change the default value of _maxTypingFrequency_ capability

**Comment by mykola-mokhnach** [comment]
Also this might be a side effect of text autocorrection

**Comment by Brad19** [comment]
Can you pls throw me some light on adding maxTypingFrequency capability for IOS.  Also if it is an autocorrection, then it should work similarly when i manually type it. This looks like an issue with appium on IOS simulator. And just to let you know that for android it works good.

**Comment by Brad19** [comment]
I'm struck with this issue for the past 2 days. If someone pls advise, that'll be really helpful.

**Comment by mykola-mokhnach** [comment]
I've never faced any similar problems. As a workaround you can try to use copy/paste if you have physical access to simulator.

There is `xcrun simctl pbcopy` command, which puts the stuff from stdin into Simulator's clipboard so then one can simulate long tap on a field and click Paste badge.

**Comment by Brad19** [comment]
My simulator is 10.3 - IPhone 7 and does it have anything to do with simulator settings? Please advise.

**Comment by Brad19** [comment]
Please find my observation below
1. I found this one to be odd, when I launch the test via appium and after it completed my test, i opened the app again and try to manually type in the text field which to my surprise didn't allow me to type at all. Also found that the simulator keyboard settings was not selected with "Connect Hardware keyboard". I tried to over ride manually in the simulator, but it wasn't allowing me to do. Also please note this is the debug version of the app which it requires package manager to be run in order to run the app.

2. Secondly, when i created a build with react-native run-ios, it installs the debug version of the app in the simulator. But this time I found that i'm able to type the text in text field.

I believe this is something to do with the simulator settings. Please advise as i'm in real need of this to get completed soon.

**Comment by Brad19** [comment]
Found the fix, What i did was the following which works for Appium 1.6.5 & 1.6.6-beta.4 version as well.

capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone 6");
                        capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "iOS" );
                        capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "10.2");
                        capabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, 10000);
                        capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME,"XCUITest");
                        capabilities.setCapability(MobileCapabilityType.APP, app.getAbsolutePath());
                        capabilities.setCapability("maxTypeFrequency", 5);

But the above capabilities didn't work for IOS 10.3 version which is strange and apparently not sure. For now, my problem is resolved and I think It might be the problem with Appium compatibility with IOS versions. Awaiting fix if that is the issue with Appium. If I'm wrong, Please advise.

**Comment by mykola-mokhnach** [comment]
There is nothing one can do about such issues in Appium. It's rather an issue between XCTest and React interoperability.

**Comment by sshivaswamy-lifesize** [comment]
Hello All,

I am also running into this issue as originally described by @Brad19.

Tried the following combinations of Appium and iOS simulator:
1. Appium: 1.6.4, Simulator: 10.0, 10.1, 10.2, 10.3
2. Appium: 1.6.5, Simulator: 10.0, 10.1, 10.2, 10.3
3. Appium: 1.7.1, Simulator: 10.0, 10.1, 10.2, 10.3

Other Details on the environment:
WebdriverIO version: 4.7.1
Application - Built using react-native

Below is my desired capabilities:
`desiredCapabilities: {
      automationName: "XCUITest",
      platformName: "iOS",
      appiumVersion: "1.7.1", //"1.6.5", "1.6.4"
      app: "PATH_TO_APP",
      avdReadyTimeout: "1000",
      deviceName: "iPhone 6",
      deviceOrientation: "portrait",
      platformVersion: "10.2", //"10.0", "10.1", "10.3"
      newCommandTimeout: 7200,
      maxTypeFrequency: 5
    }`

I am not seeing this issue on real Android devices.

Any help will be appreciated.

Thanks,
Sunil

**Comment by d814343** [comment]
@sshivaswamy-lifesize Yes, am also facing the same issue. None of the iOS 10.x.x versions works out with any of the Appium server version. However, 1.7.1 is working perfectly fine with iOS 11. But the problem I am facing is, my application's minimum target is 10.x and AWS device farm doesn't support iOS11 on Appium yet. So, I am kind of blocked with my automation testing. Not sure whether anyone sees this comment, but am just venting out my findings for future references.
