### ISSUE TITLE
WebDriverException: Message: A session is either terminated or not started

### ISSUE THREAD

**Issue by bbaitikova** [appium/appium#9032]
## The problem
I am not able to run my test. Getting next error: 

> Unhandled rejection Error: Error while getting connected devices. Original error: Command '/Users/user/Library/Android/sdk/platform-tools/adb devices' exited with code 1

I was able to run same test on last week. Let me know if you need more information. 
## Environment

Appium version (or git revision) that exhibits the issue: 1.6.5
Last Appium version that did not exhibit the issue (if applicable): 1.6.5
Desktop OS/version used to run Appium: Mac sierra
Node.js version (unless using Appium.app|exe):
Mobile platform/version under test: Samsung S7, Marshmallow
Real device or emulator/simulator: real device
Appium CLI or Appium.app|exe: Version 1.1.0-beta.4 (1.1.0-beta.4)
## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/bbaitikova/0dfa7221ee9dfba52b9afc903a92822e

**Comment by bbaitikova** [comment]
i just updated my appium version to Version 1.2.0-beta.1 (1.2.0-beta.1) and still not working. [](url)

**Comment by mykola-mokhnach** [comment]
This is usually an adb issue. It just stops to detect connected devices without any reason especially if these devices are under high load. Try to update Android SDK and tools to the most recent available version.

**Comment by bbaitikova** [comment]
You are right. Updated the sdk. Works fine. 
Thanks.
