### ISSUE TITLE
Getting v.split is not a function when i run a test case on remote pc.  

### ISSUE THREAD

**Issue by sharecommute** [appium/appium#9036]
## The problem

When i try to execute a iOS test case from remote pc, i get a v.split is not a function error, but i can execute the same test case on mac without any issues.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS, 10.3.2
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe:

## Details

1. Start the appium on mac machine and connect iPhone to the mac.
2. Set the appium url to the ip of the mac machine.
3. On Windows machine, try to execute a test case using python
4. Check the error on the mac machine.
5. After you see the error (from step4) , execute same test on the mac.
6. Same test case on mac will be successful.
 
## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

https://gist.github.com/sharecommute/aa8c3e4fca8424ea5c4ce4fe859b0ca1

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by imurchie** [comment]
Interesting. Strange that it only happens from a PC. Investigating.

**Comment by sharecommute** [comment]
Thank you @imurchie for the quick reply. I will wait for your update.

**Comment by mykola-mokhnach** [comment]
I think this problem has been fixed in 1.6.5 or 1.6.6-beta

**Comment by mykola-mokhnach** [comment]
@imurchie https://github.com/appium/appium-xcuitest-driver/pull/478/files

**Comment by imurchie** [comment]
Yes, I am adding unit tests and it seems to be fixed.

**Comment by sharecommute** [comment]
but @mykola-mokhnach , its not happening if we run on the same machine and it happens only from remote pc. It's a strange issue and only happens for ios. I tried on android and it works fine.

**Comment by imurchie** [comment]
Android and iOS have _completely_ different code for running the commands. So it is not surprising that it happens in one and not the other.

The windows part is odd. Do you have logs from a successful test run from Mac? Where this command works?

**Comment by sharecommute** [comment]
oh ok got it @imurchie .yes, i will share the logs.

**Comment by sharecommute** [comment]
updated same gist with successful log.

https://gist.github.com/sharecommute/aa8c3e4fca8424ea5c4ce4fe859b0ca1#file-successlog-log

**Comment by imurchie** [comment]
The error is still there. https://gist.github.com/sharecommute/aa8c3e4fca8424ea5c4ce4fe859b0ca1#file-appium-log-L202-L246

**Comment by mykola-mokhnach** [comment]
the PR has been merged and is present in Appium beta. xcuitest driver version should be 2.44.0 or higher
