### ISSUE TITLE
still can not get the "enabled" attribute in IOS devices

### ISSUE THREAD

**Issue by yingkanBranko** [appium/appium#9037]
## The problem

 still can not get the "enabled" attribute in IOS devices using python appium client. the error is :'bool' object has no attribute 'lower'

## Environment

* Appium version:1.6.6-beta.4
* Last Appium version that did not exhibit the issue (if applicable): None
* Desktop OS/version used to run Appium: OS10.12.3
* Node.js version (unless using Appium.app|exe):v6.11.2
* Mobile platform/version under test:IOS
* Real device or emulator/simulator:ios simulator iphone 7
* Appium CLI or Appium.app|exe: Appium-Python-Client (0.24)

## Details

            resp = self._execute(Command.GET_ELEMENT_ATTRIBUTE, {'name': name})
            attributeValue = resp.get('value') #attributeValue returns as a bool,but bool has not attribute \'enabled',
                                          
            if attributeValue is not None:
                if name != 'value' and attributeValue.lower() in ('true', 'false'):
                    attributeValue = attributeValue.lower()   

## Link to Appium logs

the error is in appium-client, so the appium server's log is normal as follow:
[HTTP] --> GET /wd/hub/session/18d9d9ba-d7ca-43f7-9662-29b40fadfb29/element/0187BCCD-8123-4564-8E62-D69C9FC05437/attribute/enabled {}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [XCUITest] Executing command 'proxyReqRes'
[debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/18d9d9ba-d7ca-43f7-9662-29b40fadfb29/element/0187BCCD-8123-4564-8E62-D69C9FC05437/attribute/enabled] to [GET http://localhost:8100/session/5E413B54-9C0E-4D60-B92B-49861EC88C3A/element/0187BCCD-8123-4564-8E62-D69C9FC05437/attribute/enabled] with body: {}
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : true,\n  \"sessionId\" : \"5E413B54-9C0E-4D60-B92B-49861EC88C3A\",\n  \"status\" : 0\n}"
[JSONWP Proxy] Replacing sessionId 5E413B54-9C0E-4D60-B92B-49861EC88C3A with 18d9d9ba-d7ca-43f7-9662-29b40fadfb29
[HTTP] <-- GET /wd/hub/session/18d9d9ba-d7ca-43f7-9662-29b40fadfb29/element/0187BCCD-8123-4564-8E62-D69C9FC05437/attribute/enabled 200 199 ms - 76 

## Code To Reproduce Issue [ Good To Have ]
#just get the attribute  "enabled" of element such as:
accessid = XXX
element = self.driver.find_element_by_accessibility_id(accessid)
element.get_attribute("enabled")

**Comment by mykola-mokhnach** [comment]
This is the server code:

```js
commands.getAttribute = async function (attribute, el) {
  el = util.unwrapElement(el);
  if (!this.isWebContext()) {
    const value = await this.proxyCommand(`/element/${el}/attribute/${attribute}`, 'GET');
    // The returned value must be of type string according to https://www.w3.org/TR/webdriver/#get-element-attribute
    return (_.isNull(value) || _.isString(value)) ? value : JSON.stringify(value);
  }
  let atomsElement = this.getAtomsElement(el);
  if (_.isNull(atomsElement)) {
    throw new errors.UnknownError(`Error converting element ID for using in WD atoms: '${el}`);
  } else {
    return await this.executeAtom('get_attribute_value', [atomsElement, attribute]);
  }
};
```

This function properly converts boolean values into strings. Make sure server version version is really 1.6.6-beta (check xcuidriver version number printed at the top of the log)

**Comment by yingkanBranko** [comment]
@mykola-mokhnach ,thank you for your reply
the appium verion is printed as follows:
/setup/node-v6.11.2-darwin-x64/bin/appium --session-override
[Appium] Welcome to Appium v1.6.6-beta.4
[Appium] Non-default server args:
[Appium]   sessionOverride: true
[Appium] Appium REST http interface listener started on 0.0.0.0:4723

and the xcuidriver version is printed as follows:
[Appium] Requested iOS support with version >= 10, using XCUITest driver instead of UIAutomation-based driver, since the latter is unsupported on iOS 10 and up.
[Appium] Creating new XCUITestDriver (v2.43.2) session

**Comment by amedvedjev** [comment]
@yingkanBranko  with latest appium look like i met similar issue with iOS. "true" -> "1". i just added logic:
```
tmp = cellSwitchControl.get(0).findElement(MobileBy.className("XCUIElementTypeSwitch")).getAttribute("value");
            if (tmp.equals("true") || tmp.equals("1")) {
                return true;
            } else {
                return false;
            }
```

**Comment by JaniJegoroff** [comment]
I don't see any issues using `Ruby client`. Appium server always returns correct value. Tested with `XCUIElementTypeButton`.
```
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : true,\n  \"sessionId\" : \"7B6C7EB4-EDB2-4077-B38F-6D03D88A7735\",\n  \"status\" : 0\n}"
```

@yingkanBranko I guess you should open issue to python-client.

**Comment by mykola-mokhnach** [comment]
@JaniJegoroff This is the issue. W3C standard requires the value to be a string rather than boolean. So the returned result should look like

```
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"true\",\n  \"sessionId\" : \"7B6C7EB4-EDB2-4077-B38F-6D03D88A7735\",\n  \"status\" : 0\n}"
```

And the code above must return such result

**Comment by yingkanBranko** [comment]
@amedvedjev , thank you for your reply. it means you has resolved the problem, right? but your code looks like change string "True" to bool True

**Comment by yingkanBranko** [comment]
@mykola-mokhnach , can you fix the issue? best wishes

**Comment by amedvedjev** [comment]
@yingkanBranko yes you correct. but before i had string "true" in response in some 1.6.6-beta1 or 2 but now i have string "1". so i just added that both = return boolean true to check if some switch enabled or not.

**Comment by mykola-mokhnach** [comment]
This, probably, has been changed by WDA. I'll add a check for "1" value and will transform it to 'true'

**Comment by yingkanBranko** [comment]
@mykola-mokhnach , i see, thank you

**Comment by mykola-mokhnach** [comment]
The improvement has been merged to Appium beta and is present in xcuitest driver since version 2.44.0

**Comment by alangithubtrader** [comment]
Hi guys,

Sorry but I am still seeing this issue with appium 1.7.0 with appium C# driver v3.0.0.2
