### ISSUE TITLE
Javascript execution is failing on hybrid app iOS 11 beta appium 1.6.5 and 1.6.6 beta 4

### ISSUE THREAD

**Issue by fabianaapateanu** [appium/appium#9038]
## The problem

I have a hybrid mobile app which I test with Appium. I make use of executeScript method from JavaScriptExecutor, because this is how a trigger some javascript events in the application.
Currently this is failing, while testing with the new versions of tools for iOS 11.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5 and 1.6.6-beta 4 
* Last Appium version that did not exhibit the issue (if applicable): 1.6.3, on 
* Desktop OS/version used to run Appium: Mac OS High Sierra 10.13 Beta
* Node.js version (unless using Appium.app|exe): 8.3.0
* Mobile platform/version under test: iOS 11 beta 6
* Real device or emulator/simulator: iPhone 6
* Appium CLI or Appium.app|exe:
* Webdriver agent version: latest from Master branch
* Java client: 4.1.2
* ios-webkit-debug-proxy: latest from Master
* Xcode: 9.0 beta 5

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/fabianaapateanu/c315d0621d1c0e214a16f5582fb153a9
 Full log:
https://gist.github.com/fabianaapateanu/9df1e05fcc809e4db18d0225405c876d

## Code To Reproduce Issue [ Good To Have ]

**Comment by mykola-mokhnach** [comment]
Please attach full appium log

**Comment by fabianaapateanu** [comment]
https://gist.github.com/fabianaapateanu/9df1e05fcc809e4db18d0225405c876d

**Comment by fabianaapateanu** [comment]
Hello @mykola-mokhnach and all, I am happy to provide any other info in this issue, as our framework is currently 95% based on javascript execution, therefore this issue makes it unusable on iOS 11 :) So anything I can help with, please do tell.

Many thanks!

**Comment by imurchie** [comment]
I don't see any attempt to execute JavaScript here. The logs show setting the context to a webview, and then nothing else.

Also: do you have Xcode command line tools installed? The logs show
```
debug: [XCUITest] Xcode version set to '9.0' 
```
instead of:
```
debug: [XCUITest] Xcode version set to '9.0' (tools v9.0.0.0.1.1496343141)
```

**Comment by fabianaapateanu** [comment]
Hello, yes I have installed command line tools.
So after further investigation, the error is actually thrown after performing the switch to WebView context with the code:

 ' DriverHelper.getDriver().context(webviewContext);'  where DriverHelper.getDriver() is an AppiumDriver object.

I believe the WebView did not get the chance to load properly, but the driver performed the switch and the error "TypeError: Cannot read property 'wasThrown' of undefined" appears only in the console, basically the driver session dies there.

**Comment by fabianaapateanu** [comment]
This issue can be closed, as this is not a bug.
