### ISSUE TITLE
Appium didn't clean adb forward resource when closing chromedriver.

### ISSUE THREAD

**Issue by babyrjw** [appium/appium#9039]
Appium start a webview session by establishing a connection between ADB with chromedriver. It kill all of chromedriver processes existed.  After establishing a connection ADB will listen on a random tcp port and chromedriver will connect this port. This port  was been listening after chromedriver process has been killed. The quantity of ports listened by adb will increased one by one until exhausted if switch context to webview frequently.

So I add some code into  appium-chromedriver/lib/chromedriver.js  file,  change function killAll like this:

<pre><cdoe>
async killAll () {
    let cmd;
    if (system.isWindows()) {
      // js hint cannot handle backticks, even escaped, within template literals
      cmd = "FOR /F \"usebackq tokens=5\" %a in (`netstat -nao ^| " +
            "findstr /R /C:\"" + this.proxyPort + " \"`) do (" +
            "FOR /F \"usebackq\" %b in (`TASKLIST /FI \"PID eq %a\" ^| " +
            "findstr /I chromedriver.exe`) do (IF NOT %b==\"\" TASKKILL " +
            "/F /PID %a))";
    } else {
      cmd = `pkill -15 -f "${this.chromedriver}.*--port=${this.proxyPort}"`;
    }
    log.info(`Killing any old chromedrivers, running: ${cmd}`);
    try {
      await (B.promisify(cp.exec))(cmd);
      log.info("Successfully cleaned up old chromedrivers");
    } catch (err) {
      log.info("No old chromedrivers seemed to exist");
    }	
	try {
	  cmd = "FOR /F \"usebackq tokens=2\" %a in (`adb forward --list ^| findstr /R /C:\"webview\"`) do ( adb forward --remove %a )";
	  await (B.promisify(cp.exec))(cmd);
	  log.info("Successfully cleaned up old forward");
	} catch (err) {
	  log.info("No old forward seemed to exist");
	}
  }
</code></pre>

**Comment by mykola-mokhnach** [comment]
Please create a PR with your fix. We are happy to review it.
