### ISSUE TITLE
Touch Action- perform() not working as expected - Appium 1.6.5

### ISSUE THREAD

**Issue by nels0ne** [appium/appium#9040]
## The problem

I am trying to tap on one of the options from a radio button in my hybrid app but getting below error 
"org.openqa.selenium.WebDriverException: Method has not yet been implemented (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 38 milliseconds"

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Last Appium version that did not exhibit the issue (if applicable): None
* Desktop OS/version used to run Appium: Windows 10 / 1.6.5 
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Android / Nougat 7
* Real device or emulator/simulator: Real- Samsung Galaxy S7 Edge
* Appium CLI or Appium.app|exe: CLI

## Details

Code that I am using

		DesiredCapabilities capabilities = new DesiredCapabilities();
		capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "Samsung Galaxy");
		capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "7.0");
		capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "Android");
		capabilities.setCapability(MobileCapabilityType.PLATFORM,"Android");
		capabilities.setCapability(MobileCapabilityType.AUTO_WEBVIEW, "true");
		
		capabilities.setCapability("appPackage", "com.xx.xxx");
		capabilities.setCapability("appActivity", "com.xx.xx.xxx");
		capabilities.setCapability("noReset",true);
		capabilities.setCapability("fullReset",false);
		
		AppiumDriver driver = new AppiumDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);

		WebElement el =  (WebElement) driver.findElements(By.tagName("option")).get(1);
		System.out.println(el.getText());
		TouchAction TA= new TouchAction(driver);
		TA.perform();

## Link to Appium logs

https://gist.github.com/nels0ne/7e3f7e2322f1a007e03ba142a7e65d8a

## Code To Reproduce Issue [ Good To Have ]

Added in Details section

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by imurchie** [comment]
These methods do not work in a webview context. Either move into the native context, or use a different tapping strategy. Click usually works.

**Comment by nels0ne** [comment]
Thanks for the quick response, imurchie.
Would you be able to suggest me what other tapping strategies to use?
Do I need to move to Native context and use the same code as I have put in the details?
For me Click just selects the radio button but when we try manually an item from the radio button is selected and radio button form disappears as expected

**Comment by imurchie** [comment]
If clicking doesn't do what you want, I suppose the touch action is the only way. I have no idea from your particular case/app.

**Comment by jlipps** [comment]
Most often, this problem is caused by your form elements listening to certain kinds of js events, which are sometimes different than the ones triggered by say Chromedriver. You could try `.tap()` instead of `.click()` for example, or as a last resort, just run `executeScript()` and fire the js event your form is listening for. Otherwise, go into the native context and try a tap by coordinates. Those are your options. But the problem you are experiencing is either a Chromedriver bug or some kind of poor choice of event listener in your application.

**Comment by HP1508** [comment]
Even I'm facing the same issue.
java-client: 4.1.2
Npm appium: 1.6.5
