### ISSUE TITLE
How can we test on iOS simulator and android device simultaneously in mac ? It would be great if anyone help with some steps or setup. 

### ISSUE THREAD

**Issue by sarozNep** [appium/appium#9043]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by SrinivasanTarget** [comment]
@sarozNep Check this [out](https://github.com/saikrishna321/AppiumTestDistribution)

**Comment by SrinivasanTarget** [comment]
@sarozNep Going forward please raise your questions in appium discuss [forum](discuss.appium.io).

**Comment by ochubey** [comment]
Basically, you would need to run 2 (or more if more devices should be used in parallel execution) instances of Appium server that would be using different port values.
In case you need to run only 1 Simulator and 1 Emulator - then:

- if Appium server initialized from the code - you'll need to use AppiumServiceBuilder with usingAnyFreePort like following `AppiumDriverLocalService service = AppiumDriverLocalService.
buildService(new AppiumServiceBuilder().
usingDriverExecutable(new File (driverExecutable)).
withAppiumJS(new File(appiumJs)).
withIPAddress(ipAddress).
usingAnyFreePort());` 
- if Appium server run as CLI - you need to run 2 instances of it with different port values like this `appium -a localhost -p 4832` and `appium -a localhost -p 4832`

In case you need to run more than one instance of the test against the same platform you need to keep in mind 2 more ports that must be unique on each of the Appium servers. Based on the platform you need to define unique ports:

- for iOS: `-p 4832 --webkit-debug-proxy-port 8302 --webdriveragent-port 8202`;
-  for Android: `-p 4730 -bp 4720 --chromedriver-port 8400`.

Also, please check out https://github.com/testvagrant/optimusTemplate for parallel execution. It looks promising.

**Comment by saikrishna321** [comment]
@ochubey you should also take a look at https://github.com/saikrishna321/AppiumTestDistribution

which helps you run parallel android and iOS device/simulator in the same mac host machine.
