### ISSUE TITLE
Long pause between sending mobile:scroll command and scrolling starting

### ISSUE THREAD

**Issue by jamesvanhorn** [appium/appium#9044]
## The problem

Issuing a scroll: mobile toVisible command to scroll an element into view before interacting takes multiple minutes until the scrolling actually starts.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.6-beta.4
* Last Appium version that did not exhibit the issue (if applicable): N/A Present from 1.6.4
* Desktop OS/version used to run Appium: Mac Sierra
* Node.js version (unless using Appium.app|exe): 8.2.1
* Mobile platform/version under test: ios 10.3.3
* Real device or emulator/simulator: real
* Appium CLI or Appium.app|exe: CLI

## Details

I see in the logs that the command is sent to scroll the element into view. The server hangs for about 1 minute or so, then seems to act like the same command was sent again. Then about 30 seconds or so after this, it starts scrolling finally. Once it starts, its fine and we get there eventually. But it takes a long time.

## Link to Appium logs

https://gist.github.com/jamesvanhorn/071b2f769c573b33148e70da8cdc5d90

## Code To Reproduce Issue [ Good To Have ]
Where `element` is an element at the bottom of the current page and not visible. In our case, it's pretty far down there. Maybe it's just a limitation due to our large page size, taking a while for appium/xcuitest to find the element and try to scroll to it.
```
final JavascriptExecutor js = (JavascriptExecutor) this.driver();
final HashMap<String, String> scrollObject = new HashMap<String, String>();
scrollObject.put("element", ((RemoteWebElement) element).getId());
scrollObject.put("toVisible", "true");
js.executeScript("mobile: scroll", scrollObject);
```

**Comment by mykola-mokhnach** [comment]
This might be related to https://github.com/facebook/WebDriverAgent/issues/675

Anyway there is no way to fix anything there on Appium side

**Comment by jamesvanhorn** [comment]
Thanks!
