### ISSUE TITLE
How to click on the center of the screen on Android device

### ISSUE THREAD

**Issue by CharanpreetHora** [appium/appium#9046]
## The problem

Not able to click center of the screen  on Android device. Tried AppDriver.Tap(200, 200, 200, 200);

There is not identification property of the Image object. There are too many classes with android.widget.Image. I am successfully able to navigate or scroll on to the Image with reading other elements. Every image has content-desc. But this is dynamic with no COMMON text. 

I want to click center of phone screen. How can I achieve this.

## Environment

* Appium version Desktop version 1.6.5:
* C#, Selenium, VS 2013

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Not able to click center of the screen  on Android device. Tried AppDriver.Tap(200, 200, 200, 200);

There is not identification property of the Image object. There are too many classes with android.widget.Image. I am successfully able to navigate or scroll on to the Image with reading other elements. Every image has content-desc. But this is dynamic with no COMMON text. 

I want to click center of phone screen. How can I achieve this.

**Comment by mykola-mokhnach** [comment]
one can get screen dimensions by calling driver.manage.window.getSize API.

Please use Appium forum to ask questions.

**Comment by vrunoa** [comment]
I have never use the c# driver , but i'm seeing the Tap method can be use different.
https://github.com/appium/appium-dotnet-driver/blob/master/appium-dotnet-driver/Appium/MultiAction/TouchAction.cs#L238
Have you tried `AppDriver.Tap(200, 200, 1)` ? I'm basing this on the method description

**Comment by mykola-mokhnach** [comment]
get size method returns the actual size of the screen to calculate the center coordinates. The click itself can be done via TouchActions interface.

**Comment by vrunoa** [comment]
looking at the method params `Tap(Int32 fingers, Int32 x, Int32 y, Int32 duration)` shouldnt be something like `.Tap(1, 200, 200, 1)` since the first params seems to be fingers ?  duration is 1 if it's seconds or 500 if it's miliseconds. And mykola is right, you should try to get the center coordinates with the window size.

**Comment by CharanpreetHora** [comment]
While trying AppDriver.Manage().Window.Size = new Size();
getting following error:-
Method is not implemented at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse) at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters) at OpenQA.Selenium.Appium.AppiumDriver`1.Execute(String driverCommandToExecute, Dictionary`2 parameters) at OpenQA.Selenium.Remote.RemoteWindow.set_Size(Size value)

@vrunoa - Now AppDriver.Tap(1,200, 200, 2); is getting executed but no action is performed on screen.
So I am suing the method as below:-
AppDriver.Tap(1,200, 200, 2);

In case I am executing with Size like below getting exception.
AppDriver.Manage().Window.Size = new Size();
AppDriver.Tap(1,200, 200, 2);

Kindly suggest as this is show stopper for me. :-(

**Comment by CharanpreetHora** [comment]
can someone help me clicking on android device center point of the screen??

**Comment by CharanpreetHora** [comment]
ok let me check. Otherwise I will post the same in other forum. Thanks for your time vrunoa. :-)

**Comment by CharanpreetHora** [comment]
finally i am able to click it. using following code:-
            Size size = AppDriver.Manage().Window.Size;
            int startx = (int)(size.Width * 0.5);
            //int startx = (int)(size.Width * 1);
            int starty = size.Height / 2;
            //int endy = size.Height / 7;
            AppDriver.Tap(1, startx, starty, 5);
