### ISSUE TITLE
"Nested" FindElementsBy returns WebElements instead of WindowsElements

### ISSUE THREAD

**Issue by caulfield2** [appium/appium#9057]
## The problem

When using a nested search on a Windows application using WinAppDriver, a WebElement is returned instead of a WindowsElement.

## Environment

* Appium version (or git revision) that exhibits the issue: Appium.WebDriver NuGet 3.0.0.3
* Desktop OS/version used to run Appium: Windows 7

Using WinAppDriver.exe with C# in VS 2015 to run tests on a Windows application in a Windows 10 VM.

## Details

My only experience with Appium is through using [WinAppDriver](https://github.com/Microsoft/WinAppDriver) to automate Windows applications, so I apologize in advance for any incorrect assumptions I make. I was recommended to post this here after originally posting to the WinAppDriver page [here](https://github.com/Microsoft/WinAppDriver/issues/237). 

I am trying to narrow down a search to a certain section of my app and then find all elements within that section by a certain name. In VS 2015, my initial thought was to do the following:

`driver = new WindowsDriver<WindowsElement>(new Uri(WindowsApplicationDriverUri),`
`desktopCapabilities);`
`WindowsElement element = driver.FindElementByName("name1");`
`IList<WindowsElement> list = (IList<WindowsElement>)element.FindElementsByName("name2");`

I do not get any complaints in VS about this before I run my test. At runtime, I get the error below on the cast:

![image](https://user-images.githubusercontent.com/25783833/29522947-ceed5df8-8650-11e7-9423-ed301b26cc41.png)

Upon further inspection, it seems that `element.FindElementsByName("name2")` is returning type:

System.Collections.ObjectModel.ReadOnlyCollection<OpenQA.Selenium.Appium.AppiumWebElement>

which is why I am getting the cast exception. My workaround to this is to just replace

`IList<WindowsElement> list = (IList<WindowsElement>)element.FindElementsByName("name2");`

with 

`var list = element.FindElementsByName("name2");`
`list[0].Click();`

and I am able to click the desired element without issue. However, it doesn't make much sense that a WebElement should ever be returned, especially when my driver is instantiated as a `WindowsDriver<WindowsElement>`.

I am not sure if the error is because I am converting from a ReadOnlyCollection to an IList, or from WebElement to WindowsElement because

`WindowsElement element1 = driver.FindElementByName("name1");`
`WindowsElement element2 = (WindowsElement)element1.FindElementByName("name2").Click();`

executes without error as well, although the cast is needed which means that the "nesting" here is returning a WebElement as well. Can someone confirm whether this is a valid concern? The way I see it, am explicit cast to a WindowsElement shouldn't be necessary when nesting a search like I do above.

**Comment by mykola-mokhnach** [comment]
Please report to https://github.com/appium/appium-dotnet-driver

Closed as non server-related.

**Comment by caulfield2** [comment]
For reference, issue posted [here](https://github.com/appium/appium-dotnet-driver/issues/188)
