### ISSUE TITLE
Android settings_apk-debug.apk: Unable to create session on emulator with API 24 and higher

### ISSUE THREAD

**Issue by AnastasiiaKravets** [appium/appium#9059]
## The problem

Encountered internal error running command: Error: Error executing adbExec. Original error: 'Command 'c\:\\Users\\an.kravets\\AppData\\Local\\Android\\sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.20.101\:5555 shell appops set io.appium.settings android\:mock_location allow' exited with code 3221226356'; Stderr: ''; Code: '3221226356'

## Environment
Appium version (or git revision) that exhibits the issue: v1.6.6-beta.4 (tried with all latest versions from 1.6.5)
Desktop OS/version used to run Appium: Win
Mobile platform/version under test: Android API>=24
Real device or emulator/simulator: Emulator
Appium CLI or Appium.app|exe: CLI

* Appium version (or git revision) that exhibits the issue: v1.6.6-beta.4 (I've tried with all latest versions from 1.6.5)
* Desktop OS/version used to run Appium: Win 10
* Node.js version (unless using Appium.app|exe):  v8.2.1
* Mobile platform/version under test: Android API >= 24
* Real device or emulator/simulator: Emulator (Genymotion)
* Appium CLI or Appium.app|exe: CLI

## Details

Tried with UiAutomator2 and UiAutomator
Settings_apk-debug.apk v2.1

The same test runs on Android API 22, 23 without any problem

## Link to Appium logs

Encountered internal error running command: Error: Error executing adbExec. Original error: ‘Command ‘c:\Users\an.kravets\AppData\Local\Android\sdk\platform-tools\adb.exe -P 5037 -s 192.168.20.101:5555 shell appops set io.appium.settings android:mock_location allow’ exited with code 3221226356’; Stderr: ‘’; Code: '3221226356’
at ADB.execFunc$ (…/…/…/lib/tools/system-calls.js:234:13)
at tryCatch (C:\Users\an.kravets\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\an.kravets\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\an.kravets\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
at GeneratorFunctionPrototype.invoke (C:\Users\an.kravets\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
at 
at process._tickCallback (internal/process/next_tick.js:188:7)

## Code To Reproduce Issue [ Good To Have ]

desired_caps['platformName'] = 'Android'
desired_caps['platformVersion'] = '7.0'
desired_caps['deviceName'] = '192.168.20.101:5555'
desired_caps['app'] = 'C:\\Users\\an.kravets\Downloads\\ua.novaposhtaa.apk'
desired_caps['appActivity'] = '.activities.MainActivity'
desired_caps['noReset'] = True
desired_caps['appWaitActivity'] = '.activities.MainActivity'
desired_caps['automationName'] = 'UiAutomator2'
driver = webdriver.Remote('http://localhost:4723/wd/hub', self.desired_caps)

**Comment by mykola-mokhnach** [comment]
1. Use **avd** capability in order to set emulator name
2. Try Appium 1.6.6-beta. This issue has been fixed there.

Closed as duplicate

**Comment by AnastasiiaKravets** [comment]
I've tried on v1.6.6-beta.4 and it doesn't help.
And Genymotion emulators do not displayed in list of avd

**Comment by mykola-mokhnach** [comment]
It's probably, an issue with Genymotion itself. @imurchie shall we wrap shell appops call into try/catch and print a warning instead of throwing an error?

**Comment by imurchie** [comment]
This should be fixed in the latest beta, with `appium-android-driver@1.25.1`.

**Comment by AnastasiiaKravets** [comment]
Thank you so much!!!
