### ISSUE TITLE
java.lang.NullPointerException using TouchAction in Android for Scrolling

### ISSUE THREAD

**Issue by bgpros** [appium/appium#9061]
## The problem
I'm trying to scroll down, in an Android Studo Simulator, so I can find some elements, but I haven't found a way to do it, Appium log isn't showing usefull information.

## Environment

* Appium version (or git revision) that exhibits the issue: v1.6.5
* Desktop OS/version used to run Appium: macOS Sierra version 10.12.5
* Mobile platform/version under test: 6.0
* Real device or emulator/simulator: Simulator (Nexus 6)

Also using TestNG

## Details
The code i'm using is:

	//Scroll Using Touch Action Classes
	    	APP_LOGS.debug("Starting to find the X and Y for Scroll");
	    	TouchAction tAction=new TouchAction(mobDriver);
	    	int startx = driver.findElement(MobileBy.xpath(OR.getProperty("startIndustry"))).getLocation().getX();
	    	APP_LOGS.debug("Start X found");
	    	int starty = driver.findElement(MobileBy.xpath(OR.getProperty("startIndustry"))).getLocation().getY();
	    	APP_LOGS.debug("Start Y found");
	    	int endx = driver.findElement(MobileBy.xpath(OR.getProperty("endIndustry"))).getLocation().getX();
	    	APP_LOGS.debug("End Y found");
	    	int endy = driver.findElement(MobileBy.xpath(OR.getProperty("endIndustry"))).getLocation().getY();
	    	APP_LOGS.debug("End X found");
	    	System.out.println(startx + " ::::::: " + starty + " ::::::: " + endx +  " ::::::: " +	endy); 
	    	Thread.sleep(1000);
	    	
	    	//First tap on the screen and swipe it right using moveTo function
	    	tAction.press(startx,starty).waitAction(1000).moveTo(endx,endy).release().perform(); 
	    	
	    	Thread.sleep(1000);

Also Tried adding the coordinates numbers directly and I have the same error.

## Link to Appium logs
[debug] [MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"40"}
[info] [HTTP] <-- POST /wd/hub/session/dea3bc0e-f77a-4000-9392-cad8fb81051d/element 200 115 ms - 88 
[info] [HTTP] --> GET /wd/hub/session/dea3bc0e-f77a-4000-9392-cad8fb81051d/element/40/location {}
[debug] [MJSONWP] Calling AppiumDriver.getLocation() with args: ["40","dea3bc0e-f77a-4000-9392-cad8fb81051d"]
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"element:getLocation","params":{"elementId":"40"}}
[info] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:getLocation","params":{"elementId":"40"}}
[info] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[info] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: getLocation
[info] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":{"x":0,"y":808}}
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [MJSONWP] Responding to client with driver.getLocation() result: {"x":0,"y":808}
[info] [HTTP] <-- GET /wd/hub/session/dea3bc0e-f77a-4000-9392-cad8fb81051d/element/40/location 200 23 ms - 87 
[info] [HTTP] --> POST /wd/hub/session/dea3bc0e-f77a-4000-9392-cad8fb81051d/element {"using":"xpath","value":"/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.RelativeLayout/android.widget.FrameLayout[1]/android.widget.LinearLayout/android.support.v7.widget.RecyclerView/android.widget.LinearLayout[1]/android.widget.FrameLayout/android.widget.RelativeLayout"}
[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["xpath","/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.RelativeLayout/android.widget.FrameLayout[1]/android.widget.LinearLayout/android.support.v7.widget.RecyclerView/android.widget.LinearLayout[1]/android.widget.FrameLayout/android.widget.RelativeLayout","dea3bc0e-f77a-4000-9392-cad8fb81051d"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [BaseDriver] Waiting up to 10000 ms for condition
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.RelativeLayout/android.widget.FrameLayout[1]/android.widget.LinearLayout/android.support.v7.widget.RecyclerView/android.widget.LinearLayout[1]/android.widget.FrameLayout/android.widget.RelativeLayout","context":"","multiple":false}}
[info] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.RelativeLayout/android.widget.FrameLayout[1]/android.widget.LinearLayout/android.support.v7.widget.RecyclerView/android.widget.LinearLayout[1]/android.widget.FrameLayout/android.widget.RelativeLayout","context":"","multiple":false}}
[info] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[info] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: find
[info] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding '/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.RelativeLayout/android.widget.FrameLayout[1]/android.widget.LinearLayout/android.support.v7.widget.RecyclerView/android.widget.LinearLayout[1]/android.widget.FrameLayout/android.widget.RelativeLayout' using 'XPATH' with the contextId: '' multiple: false
[info] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[CLASS=android.widget.RelativeLayout, INSTANCE=1]
[info] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":{"ELEMENT":"41"}}
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"41"}
[info] [HTTP] <-- POST /wd/hub/session/dea3bc0e-f77a-4000-9392-cad8fb81051d/element 200 118 ms - 88 
[info] [HTTP] --> GET /wd/hub/session/dea3bc0e-f77a-4000-9392-cad8fb81051d/element/41/location {}
[debug] [MJSONWP] Calling AppiumDriver.getLocation() with args: ["41","dea3bc0e-f77a-4000-9392-cad8fb81051d"]
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"element:getLocation","params":{"elementId":"41"}}
[info] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:getLocation","params":{"elementId":"41"}}
[info] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[info] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: getLocation
[info] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":{"x":0,"y":160}}
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [MJSONWP] Responding to client with driver.getLocation() result: {"x":0,"y":160}
[info] [HTTP] <-- GET /wd/hub/session/dea3bc0e-f77a-4000-9392-cad8fb81051d/element/41/location 200 21 ms - 87 
[info] [HTTP] --> POST /wd/hub/session/dea3bc0e-f77a-4000-9392-cad8fb81051d/element {"using":"xpath","value":"/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.RelativeLayout/android.widget.FrameLayout[1]/android.widget.LinearLayout/android.support.v7.widget.RecyclerView/android.widget.LinearLayout[1]/android.widget.FrameLayout/android.widget.RelativeLayout"}
[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["xpath","/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.RelativeLayout/android.widget.FrameLayout[1]/android.widget.LinearLayout/android.support.v7.widget.RecyclerView/android.widget.LinearLayout[1]/android.widget.FrameLayout/android.widget.RelativeLayout","dea3bc0e-f77a-4000-9392-cad8fb81051d"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [BaseDriver] Waiting up to 10000 ms for condition
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.RelativeLayout/android.widget.FrameLayout[1]/android.widget.LinearLayout/android.support.v7.widget.RecyclerView/android.widget.LinearLayout[1]/android.widget.FrameLayout/android.widget.RelativeLayout","context":"","multiple":false}}
[info] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.RelativeLayout/android.widget.FrameLayout[1]/android.widget.LinearLayout/android.support.v7.widget.RecyclerView/android.widget.LinearLayout[1]/android.widget.FrameLayout/android.widget.RelativeLayout","context":"","multiple":false}}
[info] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[info] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: find
[info] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding '/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.RelativeLayout/android.widget.FrameLayout[1]/android.widget.LinearLayout/android.support.v7.widget.RecyclerView/android.widget.LinearLayout[1]/android.widget.FrameLayout/android.widget.RelativeLayout' using 'XPATH' with the contextId: '' multiple: false[info] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[CLASS=android.widget.RelativeLayout, INSTANCE=1]
[info] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":{"ELEMENT":"42"}}
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"42"}
[info] [HTTP] <-- POST /wd/hub/session/dea3bc0e-f77a-4000-9392-cad8fb81051d/element 200 84 ms - 88 
[info] [HTTP] --> GET /wd/hub/session/dea3bc0e-f77a-4000-9392-cad8fb81051d/element/42/location {}
[debug] [MJSONWP] Calling AppiumDriver.getLocation() with args: ["42","dea3bc0e-f77a-4000-9392-cad8fb81051d"]
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"element:getLocation","params":{"elementId":"42"}}
[info] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:getLocation","params":{"elementId":"42"}}
[info] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[info] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: getLocation
[info] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":{"x":0,"y":160}}
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [MJSONWP] Responding to client with driver.getLocation() result: {"x":0,"y":160}
[info] [HTTP] <-- GET /wd/hub/session/dea3bc0e-f77a-4000-9392-cad8fb81051d/element/42/location 200 14 ms - 87 [info] [HTTP] --> POST /wd/hub/session/dea3bc0e-f77a-4000-9392-cad8fb81051d/elements {"using":"xpath","value":"/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.RelativeLayout/android.widget.FrameLayout[1]/android.widget.LinearLayout/android.support.v7.widget.RecyclerView/android.widget.LinearLayout[5]/android.widget.FrameLayout/android.widget.RelativeLayout"}
[debug] [MJSONWP] Calling AppiumDriver.findElements() with args: ["xpath","/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.RelativeLayout/android.widget.FrameLayout[1]/android.widget.LinearLayout/android.support.v7.widget.RecyclerView/android.widget.LinearLayout[5]/android.widget.FrameLayout/android.widget.RelativeLayout","dea3bc0e-f77a-4000-9392-cad8fb81051d"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [BaseDriver] Waiting up to 10000 ms for condition
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.RelativeLayout/android.widget.FrameLayout[1]/android.widget.LinearLayout/android.support.v7.widget.RecyclerView/android.widget.LinearLayout[5]/android.widget.FrameLayout/android.widget.RelativeLayout","context":"","multiple":true}}
[info] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.RelativeLayout/android.widget.FrameLayout[1]/android.widget.LinearLayout/android.support.v7.widget.RecyclerView/android.widget.LinearLayout[5]/android.widget.FrameLayout/android.widget.RelativeLayout","context":"","multiple":true}}
[info] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[info] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: find
[info] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding '/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.RelativeLayout/android.widget.FrameLayout[1]/android.widget.LinearLayout/android.support.v7.widget.RecyclerView/android.widget.LinearLayout[5]/android.widget.FrameLayout/android.widget.RelativeLayout' using 'XPATH' with the contextId: '' multiple: true
[info] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[CLASS=android.widget.RelativeLayout, INSTANCE=5]
[info] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements selector:UiSelector[CLASS=android.widget.RelativeLayout, INSTANCE=5]
[info] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Selector ends with instance.
[info] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":[{"ELEMENT":"43"}]}
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [MJSONWP] Responding to client with driver.findElements() result: [{"ELEMENT":"43"}]
[info] [HTTP] <-- POST /wd/hub/session/dea3bc0e-f77a-4000-9392-cad8fb81051d/elements 200 59 ms - 90 [info] [HTTP] --> DELETE /wd/hub/session/dea3bc0e-f77a-4000-9392-cad8fb81051d {}
[debug] [MJSONWP] Calling AppiumDriver.deleteSession() with args: ["dea3bc0e-f77a-4000-9392-cad8fb81051d"]
[debug] [BaseDriver] Event 'quitSessionRequested' logged at 1503374202897 (22:56:42 GMT-0500 (CDT))
[debug] [AndroidDriver] Shutting down Android driver
[debug] [AndroidDriver] Resetting IME to io.appium.android.ime/.UnicodeIME
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/Brenda/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","ime","set","io.appium.android.ime/.UnicodeIME"][debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/Brenda/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","am","force-stop","com.k2partnering.k2konnectapp.k2konnect"][debug] [ADB] Pressing the HOME button
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/Brenda/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","input","keyevent",3][debug] [AndroidBootstrap] Sending command to android: {"cmd":"shutdown"}
[info] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"shutdown"}
[info] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type SHUTDOWN
[info] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":"OK, shutting down"}
[info] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Closed client connection
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: numtests=1
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: stream=.
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: current=1
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS_CODE: 0
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: stream=
[debug] [AndroidBootstrap] [UIAUTO STDOUT] Test results for WatcherResultPrinter=.
[debug] [AndroidBootstrap] [UIAUTO STDOUT] Time: 80.065
[debug] [AndroidBootstrap] [UIAUTO STDOUT] OK (1 test)
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS_CODE: -1
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [UiAutomator] Shutting down UiAutomator
[debug] [UiAutomator] Moving to state 'stopping'
[debug] [UiAutomator] UiAutomator shut down normally
[debug] [UiAutomator] Moving to state 'stopped'
[debug] [ADB] Attempting to kill all uiautomator processes
[debug] [ADB] Getting all processes with uiautomator
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/Brenda/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","ps"]
[info] [ADB] No uiautomator process found to kill, continuing...
[debug] [UiAutomator] Moving to state 'stopped'
[debug] [Logcat] Stopping logcat capture
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/Brenda/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","am","force-stop","io.appium.unlock"][debug] [AndroidDriver] Not cleaning generated files. Add `clearSystemFiles` capability if wanted.
[info] [Appium] Removing session dea3bc0e-f77a-4000-9392-cad8fb81051d from our master session list
[debug] [BaseDriver] Event 'quitSessionFinished' logged at 1503374204896 (22:56:44 GMT-0500 (CDT))
[debug] [MJSONWP] Received response: null
[debug] [MJSONWP] But deleting session, so not returning
[debug] [MJSONWP] Responding to client with driver.deleteSession() result: null
[info] [HTTP] <-- DELETE /wd/hub/session/dea3bc0e-f77a-4000-9392-cad8fb81051d 200 2001 ms - 76

**Comment by mykola-mokhnach** [comment]
Can you please attach the correct log, which contains the error message? There is nothing wrong with the current one.

BTW, try with UIAutomator2 backend. It should work better on newer Android versions.

**Comment by bgpros** [comment]
ok, that is the weird thing, Appium log isn't showing any error. The Log when I run the script is this one: 

FAILED: TestPrimaryRoleAnd("Login_1", "**************test@***********", "*********", "selectProjectAndroidTSB", "Y", "*****", "")
java.lang.NullPointerException
	at io.appium.java_client.TouchAction.perform(TouchAction.java:323)
	at appium.SuiteTruthItemAndroid.TestAddMoreIndustryAndroid.TestPrimaryRoleAnd(TestAddMoreIndustryAndroid.java:143)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)

**Comment by mykola-mokhnach** [comment]
Most likely it fails due to a bug in the client code.

**Comment by bgpros** [comment]
Any thoughts of what could be the code problem?  I can't find a reason why this is happening when I debugged the code, when it goes to the TouchAction line it takes me to the TestNG Invoker exception code and it closes my session.

**Comment by jlipps** [comment]
It appears to be a NPE generated by the java-client library. I'd raise an issue on that repo so the maintainers will see it.

**Comment by Gocoollnath** [comment]
Any updates on this issue. It's reproducible in Java client 6.0.0 and appium 1.8.1

**Comment by Gocoollnath** [comment]
Code Used:
               PointOption pt=new PointOption();
	       TouchAction ta=new TouchAction(driver);
		ta.tap(pt.withCoordinates(763,100)).perform();
		ta.tap(PointOption.point(763,100)).perform();
		ta.press(pt.withCoordinates(763,100)).perform();

Stack trace:

java.lang.NullPointerException
	at io.appium.java_client.TouchAction.perform(TouchAction.java:187)
	at test_demo.step1(test_demo.java:269)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

**Comment by narendra-chandratre** [comment]
@Gocoollnath Completely agree. 

This is suddenly reproducible now. Any one found solution to fix it?
