### ISSUE TITLE
Not able to launch and run iOS 10 application testcases in Simulator

### ISSUE THREAD

**Issue by Kavya-Kumari** [appium/appium#9062]
## The problem   

Not able to launch and run iOS 10 application testcases in Simulator

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Last Appium version that did not exhibit the issue (if applicable): 1.5.3 (for iOS 9)
* Desktop OS/version used to run Appium: 1.1.0-beta.4  and   1.2.0-beta.1
* Node.js version (unless using Appium.app|exe): v6.11.1
* Mobile platform/version under test: iPad/ iOS 10
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe:

## Details

Problem Description : 
We are using robot framework , Pycharm and Appium desktop to run testcases.

Problem1 :  We are not able to launch or run iOS 10 application in Simulator.

Problem2 : While running in device, it is taking very long time to locate buttons , open popover and to locate table cells in popover .
Takes more 10-15 mins to locate one element. 

Problem3: Appium desktop is taking too long time to refresh screen, on click of element . So finding xPath has become very difficult
 [than](url
[LogsFromAppiumDesktop.txt](https://github.com/appium/appium/files/1241055/LogsFromAppiumDesktop.txt)
)
Appium 1.4.3 for iOS 9 was very quick was taking less than a minute to locate elements

## Link to Appium logs

Please find the attached document : LogsFromAppiumDesktop

**Comment by mykola-mokhnach** [comment]
It is not recommended to use xpath with XCTest automation backend. It is slow and it will be slow, since XCTest does not natively support xpath. You should replace xpath locators with accessibility id, predicate and class chain ones.
