### ISSUE TITLE
Appium fails while waiting for Selendroid

### ISSUE THREAD

**Issue by Mriegel** [appium/appium#9063]
## The problem

Running Appium from the command line seems to be failing waiting for Selendroid.

## Environment

* Appium version: 1.6.5
* Desktop OS: MacOS 10.12.5
* Node.js version: 6.10.3 
* Mobile platform: Android 7.1.2
* Real device or emulator/simulator: Real device (Google Pixel)
* Appium CLI

## Details

From what I can tell, Appium starts, the app is successfully installed, and on the screen I see what looks like a momentary app open and immediate shut down.  

My script at this point is just trying to start the appium driver with the following capabilities: 
```
Capabilities:
[Appium]   browserName: ''
[Appium]   platformName: 'android'
[Appium]   deviceName: 'android'
[Appium]   app: '/Users/mriegelhaupt/Documents/Workspace/Android-Client-Library/android-automation-app/automation-app/build/outputs/apk/automation-app-release.apk'
[Appium]   automationName: 'selendroid'
[Appium]   fullReset: true
[Appium]   noReset: false
```

Thus far I have tried restarting the device and my machine, and uninstalling selendroid from the device.

## Link to Appium logs

[appium logs](https://gist.github.com/Mriegel/6cec7a700b1eeb06a20cf88950e43813)
[adb logs](https://gist.github.com/Mriegel/ff5e5431b24138021645f647875de35c)

**Comment by mykola-mokhnach** [comment]
It looks like Selendroid just crashes on the device because of an unknown reason. I don't think this is going to be solved, since the package is not supported since yeah 2016. I'd rather use UIAutomator2 backend for newer Android versions.
