### ISSUE TITLE
Appiun iOS UI Automation best practices

### ISSUE THREAD

**Issue by jsalama99** [appium/appium#9067]
## The problem

I am trying to find a best practice document I can hand to my iOS developers on what they need to set in their UI coding for me to be able to best be able to access the UI elements. So far I have them set name and label values to match the corresponding texts. 

I've also been told to have them set the Accessibility ID with a unique identifier as finding elements using this ID is much more reliable. What is a good naming convention for this?

I found this here:
https://medium.com/the-ministry-of-testing/adding-accessibility-identifiers-to-an-ios-app-c8e09d9c20f3

Thoughts?

**Comment by dpgraham** [comment]
This would be better suited for the discussion forum: discuss.appium.io
