### ISSUE TITLE
Appium Bogged down with Android 7.X Devices

### ISSUE THREAD

**Issue by WoodPlank** [appium/appium#9069]
## The problem

Appium seems to stall out for at least 2 of my Android Nougat devices. Appium will just stop on a method. The method changes depending on the device but it seems like Appium is getting bogged down and unable to continue. Interestingly, every device that's a previous version to Android N works without any issues.

## Environment

* Appium version: Appium Desktop 1.1.1
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): 
* Mobile platform/version under test: Android N 7.X
* Real device or emulator/simulator: real device

## Details

When a particular method is run on an Android Nougat device it seems like Appium just stalls indefinitely. However, once I close chrome (on my windows machine) Appium starts up again and tries to find the element it stalled on but this time it really is null because the webview changed on the Android app because I closed chrome on the Windows machine. 

This is the log of Appium when it's trying to find the element after I close Chrome on the Windows machine:
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Element[] is null: (0)
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements tmp selector:UiSelector[INSTANCE=0, RESOURCE_ID=android:id/buttonAcceptTerms]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[RESOURCE_ID=buttonAcceptTerms]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements selector:UiSelector[RESOURCE_ID=buttonAcceptTerms]

## Link to Appium logs

Gist: [link](https://gist.github.com/WoodPlank/d0c7e558f9d5658ac1cbcc882f82cc90)

**Comment by mykola-mokhnach** [comment]
We don't expect UIAutomator to work properly on newer Android versions, since it's outdated and Google itself does not support it anymore. Please try UIAutomator2 as the backend.
