### ISSUE TITLE
Appium v1.6.5 always install app, although I don't add app path to server capabilities

### ISSUE THREAD

**Issue by Bamivani** [appium/appium#9070]
## The problem

Appium v1.6.5 always install app, although I don't add app path to server capabilities

## Environment

* Appium version 1.6.5
![29347956-51dd9488-827a-11e7-9c0b-2f3d199e1bbe](https://user-images.githubusercontent.com/26729836/29598411-e17391c4-87f2-11e7-91b5-bd8ac7b0b40d.png)
![29347961-5816c6ee-827a-11e7-8c9d-0f3751b5eb93](https://user-images.githubusercontent.com/26729836/29598410-e1737f4a-87f2-11e7-8940-8f79e65ea85d.png)

Pls get screenshot to see more detail

**Comment by mykola-mokhnach** [comment]
Please attach full server log.

**Comment by Bamivani** [comment]
Hi mykola-mokhnach

Pls get attached file to see full server log

Thanks
[log.txt](https://github.com/appium/appium/files/1244489/log.txt)

**Comment by mykola-mokhnach** [comment]
There are no issues visible in the attached log. Are you sure this is the correct one?

**Comment by Bamivani** [comment]
Yes of course,
This issue always displays on my app.
So I have to run automation on appium old version.
I can't run on latest version.
Pls help me find out root cause issue above

**Comment by tfcardoso** [comment]
Hi,

have you tried setting noReset to true.

Because by default it will reset. From your logs:
2017-08-23 07:09:05:675 - info: [debug] [AndroidDriver] No app capability. Assuming it is already on the device
2017-08-23 07:09:05:676 - info: [debug] [AndroidDriver] Running fast reset (stop and clear)

**Comment by Bamivani** [comment]
Hi tfcardoso,

Thank for your helping.

It's work for me.

Thanks,
