### ISSUE TITLE
Appium Inspector throws error

### ISSUE THREAD

**Issue by Sai1sush** [appium/appium#9071]
## The problem

I have a test app, and configured Appium to launch it. When I click the “Launch” button, Appium starts the iOS simulator and launches my app. So far so good.
However, when I click the “i” button to launch the inspector, a “Could Not Launch Appium Inspector” dialog pops up, with this message:
“Could not start a new session
Be sure the Appium server is running with an application opened by using the “App Path” parameter in Appium.app (along with package and activity for Android) or by connecting with selenium client and supplying this in the desired capabilities object.”

## Environment

* Appium version (or git revision) that exhibits the issue: 1.5.3 (Ara)
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MacOS Sierra v10.12.6
* Node.js version (unless using Appium.app|exe): v8.3.0
* Mobile platform/version under test: iOS 6/ 10.2
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: Appium.app

## Details

Appium doctor is perfect but unable to open appium inspector

## Link to Appium logs

[MJSONWP] Encountered internal error running command: Error: Command failed: ideviceinstaller -u FC72C72B-CC0A-4E31-A494-2C1861ECEBFF -U nz.co.nzblood.nzbs

at ChildProcess.exithandler (child_process.js:202:12)
at emitTwo (events.js:100:13)
at ChildProcess.emit (events.js:185:7)
at maybeClose (internal/child_process.js:850:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)

**Comment by mykola-mokhnach** [comment]
The old Appium inspector is not supported anymore Please use https://github.com/appium/appium-desktop/releases instead
