### ISSUE TITLE
While switching on Airplane mode, Wi-Fi won't get disabled in Android 7.0 (SM-T719Y)

### ISSUE THREAD

**Issue by tadesushilgithub** [appium/appium#9074]
## The problem

Wi-Fi network should disabled after enabling the Airplane mode but it won't get disabled. Is any API to disable the Wi-Fi network?. When I enable the Airplane mode manually Wi-Fi disables. Looks like there is issue with API. 

API used (C#):
AndroidCommandExecutionHelper.SetConection(driver,ConnectionType.AirplaneMode);

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Last Appium version that did not exhibit the issue (if applicable): 1.3
* Desktop OS/version used to run Appium: Windows 7
* Node.js version (unless using Appium.app|exe): 6.9.2
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: CLI

## Details
Wi-Fi network should get disconnected but it's not working when I execute the API to switch on the Airplane mode. 

## Link to Appium logs

Not available.

## Code To Reproduce Issue [ Good To Have ]
![29628682-39f1963c-8804-11e7-83ae-92a224efe856](https://user-images.githubusercontent.com/17309586/29650762-f15470e0-886a-11e7-8f23-7ac363c336b2.png)

API used (C#) .net client:
AndroidCommandExecutionHelper.SetConection(driver,ConnectionType.AirplaneMode);

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Airplane mode cannot be changed on Android 7.0+. This is system limitation. One can only turn WiFi on/off.
