### ISSUE TITLE
Original error: ENOENT: no such file or directory, scandir

### ISSUE THREAD

**Issue by avanishf** [appium/appium#9076]
## Problem:
I am trying to setup Appium framework from scratch in my organization. But currently i am facing issues in starting a new session in Appium (Desired Capabilities). When i try to start a new session, it gives me the following error message : 
An unknown server-side error occurred while processing the command.
Original error: ENOENT: no such file or directory, scandir '/“/Users/avanishf/Library/Android/sdk”/build-tools'

## Environment
* Appium version: Version 1.2.0-beta.1
* Desktop OS/version used to run Appium: Desktop MAC OSSierra 10.12.4
* Mobile platform/version under test: Android 4.3
* Real device or emulator/simulator: Genymotion Emulator
* Appium CLI or Appium.app|exe: Appium.app

## Details
Here are my Env. variables set up on MAC OSSierra 10.12.4 :  
export JAVA_HOME=$(/usr/libexec/java_home)
export PATH=$JAVA_HOME/bin:$PATH
	
export ANDROID_HOME=/Users/avanishf/Android/sdk
export PATH=$ANDROID_HOME/platform-tools:$PATH
export PATH=$ANDROID_HOME/tools:$PATH

As you see above, ANDROID_HOME is set to : /Users/avanishf/Android/sdk 
and the error message path is showing : '/“/Users/avanishf/Library/Android/sdk”/build-tools'

So the issue is not just the double quotes("") but also the extra 'Library' folder. Earlier "Android/sdk" was set in "/Users/avanishf/Library" folder but later on moved it to "Users/avanishf" folder and despite saving those changes in env. variables when i try to start a new session by setting up DesiredCapabilites in Appium, i still get the same error.

DesiredCapabilites :
{
  "platformName": "Android",
  "platformVersion": "4.3",
  "deviceName": "192.168.56.101:5555",
  "appPackage": "com.android.calculator2",
  "appActivity": "com.android.calculator2.Calculator"
}

**Comment by imurchie** [comment]
How is Appium being invoked?

**Comment by avanishf** [comment]
via Java code : 
driver = new AndroidDriver<MobileElement>(new URL("http://127.0.0.1:4723/wd/hub"), null);

where Appium local host : 127.0.0.1 , port : 4723

**Comment by avanishf** [comment]
From the Appium desktop -> Start server -> Start session (Automatic server)
where localhost : 127.0.0.1, port : 4723

**Comment by mykola-mokhnach** [comment]
what do you see in Terminal if you print Appium's process environment?

```
ps -wwE -p <Appium_PID>
```

**Comment by avanishf** [comment]
Syntax error near unexpected token 'newline'

**Comment by imurchie** [comment]
What version of Appium desktop is being used. Somehow the export from your shell is replicated wrong.

**Comment by avanishf** [comment]
Version : 1.2.0-beta. 1

**Comment by imurchie** [comment]
@dpgraham Any ideas about environment variable replication in `appium-desktop`?

**Comment by dpgraham** [comment]
We use a library called `shell-env` (https://www.npmjs.com/package/shell-env)

My understanding is that it gets a snapshot of all the environment variables before the GUI starts but doesn't update them.

**Comment by avanishf** [comment]
Thanks guys, appreciate the help. @dpgraham solution worked for me.

**Comment by dpgraham** [comment]
@avanishf Out of curiosity, what was the fix? You just restarted it?

**Comment by avanishf** [comment]
@dpgraham I installed the library shell-env (followed the steps from the link you provided) and done!

**Comment by dpgraham** [comment]
Hmmm that's surprising. You shouldn't have to install shell-env manually. I'll take a look at this.

**Comment by Jitarinc** [comment]
@avanishf How did you fix the issue of missing package.json file?

**Comment by avanishf** [comment]
Hi @Jitarinc , i found the package.json file from the file system(there will be multiple package.json files, i picked the very first one) and dragged it into the directory where it was needed.

**Comment by Jitarinc** [comment]
@avanishf Thanks, it work now

**Comment by bsdbcp** [comment]
Hi @avanishf even I have been facing similar issue like yours, though I did what ever that is been mentioned as a solution the problem still persists. 


The error message as follows: An unknown server-side error occurred while processing the command. Original error: ENOENT: no such file or directory, scandir '/Users/vijeth/Library/Android/sdk/build-tools' (WARNING: The server did not provide any stacktrace information)

export ANDROID_HOME=/Users/vijeth/Library/Android/sdk
export PATH=$ANDROID_HOME/platform-tools:$PATH
export PATH=$ANDROID_HOME/tools:$PATH

As you see above, ANDROID_HOME has been set to : /Users/vijeth/Library/Android/sdk
but the error message path is shown as  : '/Users/vijeth/Library/Android/sdk/build-tools'

I have verified the ANDROID_HOME by running echo $ANDROID_HOME on the terminal
and I have run after changing the path as well but still I'm getting error with the same path
'/Users/vijeth/Library/Android/sdk/build-tools'

**Comment by AnandSrikumar** [comment]
I have tried everything but still the same problem!
I have set path correctly, still in logs, wrong path is showed!

**Comment by GitDemo007** [comment]
[MJSONWP] Encountered internal error running command: Error: ENOENT: no such file or directory, scandir 'C:\Users\Srikanth\AppData\Local\Android\Sdk\platform-tools;C:\Users\Srikanth\AppData\Local\Android\Sdk\platform-tools\build-tools;\build-tools'

This is the same error which come everytime. I lost 4 days installing and reinstalling, eclipse, android studio, appium but nothing worked. any other way to work with appium.

**Comment by RoyBS1** [comment]
Does it still happens? I still gets the same error , should it be fixes in the new version?

**Comment by imurchie** [comment]
@misbell This seems like a problem on your system. Npm seems to have left things in a weird state.  Could you try getting rid of `/usr/local/lib/node_modules/.staging` and then uninstalling and installing? 

As an aside, I would _highly_ recommend MacOS users take advantage of the [node version manager (nvm)](https://github.com/creationix/nvm).
