### ISSUE TITLE
Appium 1.6.6-beta.4 Webview  IOS_Webkit_Proxy 1.8 Not working for IOS 10.3.3

### ISSUE THREAD

**Issue by Nesaganesh** [appium/appium#9077]
## The problem

Appium 1.6.6-beta.4 supports IOS 11 both Native and Hybrid Apps (with ios-webkit-proxy 1.8 new version) which is good 

But when we try the older version with the above configuration example **IOS 10.3.3**  

in the appium logs it tries to remove the webdriver agent and install it again and throws an exception 
'**iproxy excited with code 208**'

## Environment

* Appium version 1.6.6-beta.4
* Mobile platform/version under test: ios 10.3.3
* Real device : IPhone 7
* Xcode: 9 beta

**Comment by mykola-mokhnach** [comment]
I assume the reason is that Apple did some breaking changes in the remote debugging protocol, so it works differently on iOS11 and is not backward compatible.
Anyway its hard to say anything without a log.

**Comment by Nesaganesh** [comment]
Here I am attaching the logs

Nesas-MacBook-Pro:node_modules nesag$ cd /usr/local/lib/node_modules && node appium -a 10.203.49.114 -p 4491 --bootstrap-port 4491 -U 5414af35fd99390fb5da8ac41c78c9407847c56d --nodeconfig /Users/admin/Automation/Nodes/Node_Safari.json --webkit-debug-proxy-port 27753 --webdriveragent-port 8100 --safari --tmp /tmp/ios/
[Appium] Welcome to Appium v1.6.6-beta.4
[Appium] Non-default server args:
[Appium]   address: 10.203.49.114
[Appium]   port: 4491
[Appium]   bootstrapPort: 4491
[Appium]   safari: true
[Appium]   nodeconfig: /Users/admin/Automation/Nodes/Node_Safari.json
[Appium]   tmpDir: /tmp/ios/
[Appium]   udid: 5414af35fd99390fb5da8ac41c78c9407847c56d
[Appium] Deprecated server args:
[Appium]   -U,--udid => --default-capabilities '{"udid":"5414af35fd99390fb5da8ac41c78c9407847c56d"}'
[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
[Appium]   udid: '5414af35fd99390fb5da8ac41c78c9407847c56d'
[debug] [Appium] Starting auto register thread for grid. Will try to register every 5000 ms.
[Appium] Appium REST http interface listener started on 10.203.49.114:4491
[debug] [Appium] Appium successfully registered with the grid on 10.203.49.114:3366
[HTTP] --> GET /wd/hub/status {}
[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.6-beta.4","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 19 ms - 90 
[HTTP] --> GET /wd/hub/status {}
[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.6-beta.4","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 12 ms - 90 
[HTTP] --> GET /wd/hub/status {}
[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.6-beta.4","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 13 ms - 90 
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"buldleId":"none","realDeviceLogger":"/usr/local/lib/node_modules/deviceconsole/deviceconsole","safariAllowPopups":false,"automationName":"XCUITest","browserName":"Safari","platformName":"iOS","startIWDP":"true","deviceName":"Matthew's iPhone"}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"buldleId":"none","realDeviceLogger":"/usr/local/lib/node_modules/deviceconsole/deviceconsole","safariAllowPopups":false,"automationName":"XCUITest","browserName":"Safari","platformName":"iOS","startIWDP":"true","deviceName":"Matthew's iPhone"},null,null]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1503572163059 (11:56:03 GMT+0100 (BST))
[Appium] Creating new XCUITestDriver (v2.43.1) session
[Appium] Capabilities:
[Appium]   buldleId: 'none'
[Appium]   realDeviceLogger: '/usr/local/lib/node_modules/deviceconsole/deviceconsole'
[Appium]   safariAllowPopups: false
[Appium]   automationName: 'XCUITest'
[Appium]   browserName: 'Safari'
[Appium]   platformName: 'iOS'
[Appium]   startIWDP: 'true'
[Appium]   deviceName: 'Matthew\'s iPhone'
[Appium]   udid: '5414af35fd99390fb5da8ac41c78c9407847c56d'
[debug] [XCUITest] XCUITestDriver version: 2.43.1
[BaseDriver] Capability 'startIWDP' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] The following capabilities were provided, but are not recognized by appium: buldleId.
[BaseDriver] Session created with session id: 774892f5-1b95-4f89-827d-2145ea7d68e6
[debug] [XCUITest] Xcode version set to '9.0' 
[debug] [XCUITest] iOS SDK Version set to '11.0'
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1503572163221 (11:56:03 GMT+0100 (BST))
[HTTP] --> GET /wd/hub/status {}
[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.6-beta.4","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 12 ms - 90 
[debug] [XCUITest] Available devices: 5414af35fd99390fb5da8ac41c78c9407847c56d
[debug] [XCUITest] Creating iDevice object with udid '5414af35fd99390fb5da8ac41c78c9407847c56d'
[XCUITest] Determining device to run tests on: udid: '5414af35fd99390fb5da8ac41c78c9407847c56d', real device: true
[XCUITest] Safari test requested
[debug] [BaseDriver] Event 'appConfigured' logged at 1503572163349 (11:56:03 GMT+0100 (BST))
[debug] [BaseDriver] Event 'resetStarted' logged at 1503572163350 (11:56:03 GMT+0100 (BST))
[debug] [XCUITest] Reset: running ios real device reset flow
[debug] [BaseDriver] Event 'resetComplete' logged at 1503572163351 (11:56:03 GMT+0100 (BST))
[debug] [iOSLog] Attempting iOS device log capture via deviceconsole
[debug] [iOSLog] Using 'deviceconsole' from '/usr/local/lib/node_modules/deviceconsole'
[debug] [iOSLog] Starting iOS device log capture with: '/usr/local/lib/node_modules/deviceconsole/deviceconsole'
[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1503572164883 (11:56:04 GMT+0100 (BST))
[XCUITest] Setting up real device
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[debug] [XCUITest] Capability 'useNewWDA' set to false, so trying to reuse currently running WDA instance at 'http://localhost:8100/'
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [XCUITest] WDA is not listening at 'http://localhost:8100/'. Rebuilding...
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1503572164905 (11:56:04 GMT+0100 (BST))
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'
[debug] [XCUITest] Killing hanging processes
[debug] [XCUITest] 'pgrep -nif xcodebuild.*5414af35fd99390fb5da8ac41c78c9407847c56d' didn't detect any matching processes. Return code: 1
[debug] [XCUITest] 'pgrep -nif iproxy.*5414af35fd99390fb5da8ac41c78c9407847c56d' didn't detect any matching processes. Return code: 1
[debug] [XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[debug] [XCUITest] iproxy exited with code '208'
[debug] [BaseDriver] Event 'wdaStartFailed' logged at 1503572165136 (11:56:05 GMT+0100 (BST))
[debug] [XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: "iproxy exited with code '208'". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
[debug] [XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[debug] [XCUITest] Removing WDA application from device
[HTTP] --> GET /wd/hub/status {}
[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.6-beta.4","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 12 ms - 90 
[XCUITest] Error starting iproxy: 'Cannot read property 'unref' of null'
[HTTP] --> GET /wd/hub/status {}
[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.6-beta.4","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 13 ms - 90 
[XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: "iproxy exited with code '208'". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:379:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 Error: Unable to launch WebDriverAgent because of xcodebuild failure: "iproxy exited with code '208'". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:379:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[debug] [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: "iproxy exited with code '208'". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:379:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[HTTP] <-- POST /wd/hub/session 500 12543 ms - 469

**Comment by mykola-mokhnach** [comment]
Have you checked similar issues, for example https://github.com/appium/appium/issues/7879 ?

**Comment by imurchie** [comment]
Error code 208 happens when there is an iproxy instance running. Try killing it.

**Comment by Nesaganesh** [comment]
@imurchie Yes you are right, there were an hanging session on the port number, once I killed this working fine.

Now Appium Beta works for both IOS11 and lower versions also.

Thank you so much for the quick support, really appreciated.
