### ISSUE TITLE
WebDriverException: Simulator is not booted after 120 seconds

### ISSUE THREAD

**Issue by jwang-net** [appium/appium#9078]
## The problem

Running into `WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Simulator is not booted after 120 seconds`

## Environment

* Appium version: 1.6.5
* Last Appium version that didn't have this issue: 1.5.3
* OS: OSX version 10.11.6
* Node.js version: 7.8.0
* Mobile Platform: iPhone 6s Simulator
* Appium CLI
* xcode version: 8.0

## Details

So we have an app that we build for debug, and I pass the 'app' desired capability the .app file. The other desired capabilities that we send to Appium are as follows:

```
"deviceName": "iPhone 6s"
"app": <path-to-.app>
"noReset": "true"
"platformName": "iOS"
"appiumVersion": "1.6.5"
"automationName": "XCUITest"
"nativeEvents": "true"
"nativeWebTap": "true"
```

Appium log: https://gist.github.com/jwang-net/8d55db0fd37233ee5f7f91b523526f4a

Everything looks good up until it tries to install... says there's an issue with installing, but when I look on the simulator it's there. Wondering if anyone's had similar issues recently or if I'm just totally missing something...

**Comment by mykola-mokhnach** [comment]
Try to update Xcode to 8.3

**Comment by jwang-net** [comment]
Looks like that was the issue. You can close this whenever
