### ISSUE TITLE
Real iOS devices receives request to run test, but times out

### ISSUE THREAD

**Issue by Nintendot** [appium/appium#9079]
## The problem

Selenium receives request, sends to Appium node, Appium seems to have received it yet does not proceed to execute, causing tests to fail/time out.

## Environment

* Appium version (or git revision) that exhibits the issue: **1.6.6 beta**
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: **OSX 10.12.6**
* Node.js version (unless using Appium.app|exe): **8.4.0**
* Mobile platform/version under test: **multiple, ranges from iOS 9.3.3 to 10.3.3**
* Real device or emulator/simulator: **Real device**
* Appium CLI or Appium.app|exe:**CLI**

## Details

- The Selenium grid is hosted a Mac Mini box
- There are 3 other Mac Mini boxes running Appium nodes, with up to 4 devices/Appium nodes connect to each, all nodes point to the same grid
- All Mac Mini boxes are on the same router
- **None of the android device have similar problems**
- The problem happens across different iOS devices, not device specific

I have seen errors such as
`[iProxy] recv failed: Operation not permitted`
and
`"Grid registration error: Cannot find proxy with ID =http://<ip>:<port> in the registry."`
When running earlier version of Appium (1.6.5), but not since updating to 1.6.6 beta

### Appium/Debugproxy/JSONConfig files:
Here're 2 sets of files that powers 2 of the Appium nodes/iOS devices, an iPhone7 and an iPad Pro

#### iPad Pro
[Appium](https://gist.github.com/Nintendot/7c67504ec050e0c6c1ad06f490992c98)
[JSONConfig](https://gist.github.com/Nintendot/87950e20a71ae30d122507b7948277d8)
[Debugproxy](https://gist.github.com/Nintendot/99346908f2618f5b63835ef7efb0bccb)

#### iPhone7
[Appium](https://gist.github.com/Nintendot/f1757564df02f90d5e8a5719b732a9a1)
[JSONConfig](https://gist.github.com/Nintendot/a792ec03d715d43927883b5c3a1e374f)
[Debugproxy](https://gist.github.com/Nintendot/ee3e3598543ddc42491c0649e50eac4b)

## Link to Appium logs

I logged the iPad Pro appium/debugproxy as follows:
[Appium logs](https://gist.github.com/Nintendot/9c5618406775100f77a66f60e92617ff)
[Debugproxy logs](https://gist.github.com/Nintendot/509b2ce46322719d731f30ec1489675e)

And [Selenium logs](https://gist.github.com/Nintendot/3aa5bb8703c615814b0936ab0c73e021)

**Comment by imurchie** [comment]
Is there any indication of why MobileSafari is not launching on the device?

**Comment by Nintendot** [comment]
> Is there any indication of why MobileSafari is not launching on the device?

@imurchie I haven't found any clues from the logs.

Thought it's something related to the WDA, so I've tried to turn on the `useNewWDA` capability in the json config file, but according to Appium logs it's not picked up: `2017-08-24 14:59:53:099 - [debug] [XCUITest] Capability 'useNewWDA' set to false, so trying to reuse currently running WDA instance at 'http://localhost:8111/'`

Sometimes by restarting the device, the tests start working again, but there's no golden rule to follow to reproduce it :/

**Comment by imurchie** [comment]
Can you either turn on device logging (setting the `showIOSLog` cap to `true`) or look in the device logs at the time of the test run?

**Comment by mykola-mokhnach** [comment]
It might be this issue: https://github.com/facebook/WebDriverAgent/issues/507

The possible workaround would be to keep WDA running for as long as possible without reinstalling it.

**Comment by Nintendot** [comment]
@mykola-mokhnach 
Previously I have ran the scenario without reinstalling the WDA every time, the problem has still occurred.
By default useNewWDA is false, and in the appium log I attached it appears to not have picked up the value set in the json config anyway.
Also, I thought the WDA issue (before useNewWDA was introduced) is regarding memory (which was indeed the case for me), after running a significant amount of tests, the system basically blew up in memory consumption.

**Comment by mykola-mokhnach** [comment]
You can also check device log - there might be more information there.

**Comment by Nintendot** [comment]
@mykola-mokhnach may I ask how to access that device log? 
I added the `showIOSLog` capability @imurchie mentioned and didn't find anything.

**Comment by mykola-mokhnach** [comment]
Real device logs can be collected with Xcode: https://support.kaspersky.com/us/12419
We need logs for the time period when the session tries to start and fails to do so.

**Comment by Nintendot** [comment]
Thanks @mykola-mokhnach 
I've tried running it again with device logs, here's the result:

Tried running tests against the same device (iPadAir2, OS: 9.3.3) twice
The first test started around 16:06 and `passed`
The second started around 16:13 and `failed`

Logs:
- [Appium](https://gist.github.com/Nintendot/83d993ee696cd93819696d428f273804) 
- [Selenium](https://gist.github.com/Nintendot/8e9a680a41237b4ef0c52bd6c2413cda) 
- [Devicelog](https://gist.github.com/Nintendot/7db5a997f12045d1fb9fdc541a3ab6e5)

(sorry about the Appium log format as it's captured by winston, but should be clear)

Could you provide some pointers based on these logs? 

Much appreciated.

**Comment by mykola-mokhnach** [comment]
These log lines look a bit suspicious to me:
Aug 29 16:17:37 TOR-iPad-Air2 XCTRunner[806] <Warning>: Enqueue Failure: '<XCUIApplicationImpl: 0x135e3b0d0 com.apple.mobilesafari>' App state is still not running active, state = Not Running /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1

> Aug 29 16:17:40 TOR-iPad-Air2 SpringBoard[58] <Warning>: -[SBMainWorkspace _handleOpenApplicationRequest:options:origin:withResult:]: Can't launch com.apple.mobilesafari when device is locked, passcode locked or blocked.
> Aug 29 16:17:40 TOR-iPad-Air2 SpringBoard[58] <Warning>: [FBSystemService] Error launching com.apple.mobilesafari: Locked (7)
> Aug 29 16:17:40 TOR-iPad-Air2 SpringBoard[58] <Warning>: [FBSystemService] Error launching com.apple.mobilesafari: Locked (7)

I would try to disable autolock in device preferences to workaround it.

**Comment by Nintendot** [comment]
@mykola-mokhnach Thanks for the suggestion, this seems to worked around the issue, but probably not an ideal long term solution.

**Comment by mykola-mokhnach** [comment]
All complains to Apple. XCTest us literally useless if device screen is locked %)
