### ISSUE TITLE
Add session id to log lines for multiple session readability

### ISSUE THREAD

**Issue by jlipps** [appium/appium#9080]
Currently it's very hard to know which log line pertains to which session if there are multiple simultaneous sessions. We should see if there's an easy way to prepend the sessionid for logs generated in the context of a session.

**Comment by mykola-mokhnach** [comment]
Probably, for convenience we need only to add first 8 chars from session id (this is a normal GUID, git does the same). It is unique enough.

**Comment by saikrishna321** [comment]
@mykola-mokhnach @jlipps any ideas on how we can implement this ?

**Comment by mykola-mokhnach** [comment]
This has been added to the base driver. I don't think we can do much more there having the current architecture
