### ISSUE TITLE
getPageSource only returns visible element for iOS simulator

### ISSUE THREAD

**Issue by jamesvanhorn** [appium/appium#9081]
## The problem

Detecting presence of elements on page but not visible (for use with mobile: scroll toVisible: true) does not work with iOS simulator 10.3 and XCode 8.3.3. More specifically, calling driver.getPageSource() only returns elements currently visible. 

If running on a real device, the full page is returned as expected, allowing use of scroll tovisible. The work around for the simulator is calling scroll: down and checking visibility after each scroll, but it would be nice if the same code worked on sim and real device. Unless i'm missing a capability to do a full page scan or only visible page scan somewhere.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.6-beta.4
* Last Appium version that did not exhibit the issue (if applicable): Not sure
* Desktop OS/version used to run Appium: Mac Sierra
* Node.js version (unless using Appium.app|exe): 8.4.0
* Mobile platform/version under test: iOS 10.3 for both device and simulator
* Real device or emulator/simulator: Both
* Appium CLI or Appium.app|exe: CLI

## Code To Reproduce Issue [ Good To Have ]

driver.getPageSource() called for the same page of the same app, once on a simulator and once on a real device.

**Comment by mykola-mokhnach** [comment]
Try to set _simpleIsVisibleCheck_ capability to _false_. 

It's all on WDA/XCTest side and cannot be changed by Appium.
