### ISSUE TITLE
App launched but error in execution

### ISSUE THREAD

**Issue by auto-mate17** [appium/appium#9082]
## The problem

I am trying to execute in the simple selendroid app using Appium. I am able to successfully launch the app but the code shows error after that even though I have taken correct xpath.

## Environment

* Appium version : 1.14
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:Windows 7
* Mobile platform/version under test: Android 5.0
* Real device or emulator/simulator:Real Device
* Selenium 3.5 BETA

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
1. Use the recent Appium version (1.6.5)
2. Use the recent Java client version (5.0.0)
3. Attach the server log to the issue description if it still does not work
