### ISSUE TITLE
Appium[1.6.5][IOS10.3] "Failure fetching attributes for element" when find element in IOS simulator

### ISSUE THREAD

**Issue by coolbirda** [appium/appium#9083]
## The problem
Appium[1.6.5][IOS10.3] "Failure fetching attributes for element" when find element in IOS simulator

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Last Appium version that did not exhibit the issue (if applicable): 1.6.4
* Desktop OS/version used to run Appium: macOS Sierra 10.12.6
* Node.js version (unless using Appium.app|exe): 8.4.0
* Mobile platform/version under test: IOS 10.3 
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe:  Appium CLI 

## Details
This issue occurred  in Appium 1.6.5 but it is fine working  in 1.6.4

## Link to Appium logs

Aug 25 10:20:02 localhost systemsoundserver-simd[1190]: [aqme] 254: AQDefaultDevice (173): skipping input stream 0 0 0x0
Aug 25 10:20:02 localhost XCTRunner[1180]: Enqueue Failure: Failure fetching attributes for element <XCAccessibilityElement: 0x608000058d80> Device element: Error Domain=XCTDaemonErrorDomain Code=13 "Error copying attributes -25202" UserInfo={NSLocalizedDescription=Error copying attributes -25202} /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 35 1
Aug 25 10:20:02 localhost XCTRunner[1180]: Failed to fetch hit point for Other 0x6080003630c0: {{0.0, 0.0}, {375.0, 667.0}} - *** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[1]
Aug 25 10:20:02 localhost XCTRunner[1180]: Enqueue Failure: Failure fetching attributes for element <XCAccessibilityElement: 0x60800024dc50> Device element: Error Domain=XCTDaemonErrorDomain Code=13 "Error copying attributes -25202" UserInfo={NSLocalizedDescription=Error copying attributes -25202} /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 35 1
Aug 25 10:20:02 localhost XCTRunner[1180]: Failed to fetch hit point for Other 0x608000363180: {{0.0, 0.0}, {375.0, 667.0}} - *** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[1]
Aug 25 10:20:02 localhost XCTRunner[1180]: Enqueue Failure: Failure fetching attributes for element <XCAccessibilityElement: 0x608000242700> Device element: Error Domain=XCTDaemonErrorDomain Code=13 "Error copying attributes -25202" UserInfo={NSLocalizedDescription=Error copying attributes -25202} /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 35 1
Aug 25 10:20:02 localhost XCTRunner[1180]: Failed to fetch hit point for Other 0x608000363480: {{15.0, 69.0}, {345.0, 305.0}} - *** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[1]

**Comment by mykola-mokhnach** [comment]
Try Appium 1.6.6-beta, which contains recent WDA snapshot.

Closing the issue as non Appium-related.

**Comment by coolbirda** [comment]
Hi @mykola-mokhnach 

Thank you for reply !

I installed appium 1.6.6-beta.4 & carthage but below "Carthage not found. Install using `brew install carthage`" still occurred , What should I do next ?

[XCUITest] Error: Carthage not found. Install using `brew install carthage`
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at checkForDependencies$ (../../../lib/wda/utils.js:58:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
 Error: Carthage not found. Install using `brew install carthage`
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at checkForDependencies$ (../../../lib/wda/utils.js:58:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>

##My environment check：
localhost:~ denny$ appium -v
1.6.6-beta.4
localhost:~ denny$ cd /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
localhost:WebDriverAgent denny$ ./Scripts/bootstrap.sh -d
Fetching dependencies
*** Downloading RoutingHTTPServer.framework binary at "v1.0.1"
*** xcodebuild output can be found in /var/folders/mc/tpvd7j0n2wn3311qypw68kj80000gn/T/carthage-xcodebuild.3K9T5J.log
localhost:WebDriverAgent denny$ brew list --versions
carthage 0.24.0
icu4c 59.1
node 8.4.0
localhost:WebDriverAgent denny$ which carthage
/usr/local/bin/carthage

**Comment by mykola-mokhnach** [comment]
Probably carthage executable is not visible to appium process. Check the content of PATH environment variable passed to the process.

**Comment by coolbirda** [comment]
Hi @mykola-mokhnach 
Thank you for quick responds 
Which should I add to path carthage or RoutingHTTPServer.framework ？

This is my path config :
localhost:WebDriverAgent denny$ cat ~/.bash_profile 

export JAVA_HOME=$(/usr/libexec/java_home)
export M2_HOME=/Users/denny/Documents/tools/apache-maven-3.3.9
export ANDROID_HOME=/Users/denny/Library/Android/sdk
export PATH=/usr/local/bin:$PATH:$JAVA_HOME:$JAVA_HOME/bin:$ANDROID_HOME:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/25.0.2:$M2_HOME/bin

**Comment by mykola-mokhnach** [comment]
The PATH in profile and in the actual process environment might be different, Use 

```
ps -wwE -p <Appim_PID>
```

to see the environment of the process.

**Comment by coolbirda** [comment]
Hi  @mykola-mokhnach 

I started appium Service via eclipse  ，and eclipse PID is : 7984

localhost:WebDriverAgent denny$ ps -wwE -p 7984
  PID TTY           TIME CMD
 7984 ??         3:15.41 /Applications/Eclipse.app/Contents/MacOS/eclipse TMPDIR=/var/folders/mc/tpvd7j0n2wn3311qypw68kj80000gn/T/ __CF_USER_TEXT_ENCODING=0x1F5:0x19:0x34 SHELL=/bin/bash HOME=/Users/denny Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.O43kCu5Qet/Render SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.rN1FU1AVgE/Listeners PATH=/usr/bin:/bin:/usr/sbin:/sbin LOGNAME=denny XPC_SERVICE_NAME=org.eclipse.platform.ide.15076 USER=denny XPC_FLAGS=0x1

Should I add something to eclipse Run configurations ？

**Comment by mykola-mokhnach** [comment]
> PATH=/usr/bin:/bin:/usr/sbin:/sbin

You need to alter /usr/local/bin folder, where carthage binary is located, there.

**Comment by coolbirda** [comment]
Hi @mykola-mokhnach 

Thank you for your guide , after that my IDE found carthage and Appium 1.6.6-beta.4 working 

But I still have same issue as original ， 
What the different of WDA between Appium 1.6.4（which working） and Appium 1.6.5 （or 1.6.6 which not working）？
What should I do next ？  
Detail log ：

Aug 25 23:59:23 dongyideMacBook-Pro XCTRunner[2885]: Enqueue Failure: Failure fetching attributes for element <XCAccessibilityElement: 0x618000257b20> Device element: Error Domain=XCTDaemonErrorDomain Code=13 "Error copying attributes -25202" UserInfo={NSLocalizedDescription=Error copying attributes -25202} /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
Aug 25 23:59:23 dongyideMacBook-Pro XCTRunner[2885]: Failed to fetch hit point for Other 0x61800036da40: {{0.0, 0.0}, {375.0, 667.0}} - *** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[1]
Aug 25 23:59:23 dongyideMacBook-Pro XCTRunner[2885]: Enqueue Failure: Failure fetching attributes for element <XCAccessibilityElement: 0x61800025a940> Device element: Error Domain=XCTDaemonErrorDomain Code=13 "Error copying attributes -25202" UserInfo={NSLocalizedDescription=Error copying attributes -25202} /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
Aug 25 23:59:23 dongyideMacBook-Pro XCTRunner[2885]: Failed to fetch hit point for Other 0x61800036dd40: {{0.0, 0.0}, {375.0, 667.0}} - *** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[1]
Aug 25 23:59:23 dongyideMacBook-Pro XCTRunner[2885]: Enqueue Failure: Failure fetching attributes for element <XCAccessibilityElement: 0x61800025a370> Device element: Error Domain=XCTDaemonErrorDomain Code=13 "Error copying attributes -25202" UserInfo={NSLocalizedDescription=Error copying attributes -25202} /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
Aug 25 23:59:23 dongyideMacBook-Pro XCTRunner[2885]: Failed to fetch hit point for Other 0x61800036e280: {{15.0, 69.0}, {345.0, 305.0}} - *** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[1]

**Comment by mykola-mokhnach** [comment]
This issue is unrelated to Appium and should be reported directly to https://github.com/facebook/WebDriverAgent/issues

**Comment by coolbirda** [comment]
Hi @mykola-mokhnach 

Ok , I reported this issue to WDA ， Can you help to involve anyone who can make farther investment in WDA ? 

https://github.com/facebook/WebDriverAgent/issues/696

Thank you !

**Comment by keshavwy** [comment]
@mykola-mokhnach @coolbirda 

PATH=/usr/bin:/bin:/usr/sbin:/sbin
You need to alter /usr/local/bin folder, where carthage binary is located, there.

Can you guys help with exact steps where I need to go and alter the folder?

**Comment by ShrithaDivya** [comment]
@mykola-mokhnach Need help with this step 
PATH=/usr/bin:/bin:/usr/sbin:/sbin
You need to alter /usr/local/bin folder, where carthage binary is located, there.
My project on eclipse doesn't run though the carthage is installed and the PATH is set on mac

**Comment by keshavwy** [comment]
@ShrithaDivya,
**You need to alter /usr/local/bin folder, where Carthage binary is located, there.**
Please follow these steps to make your project work on eclipse:

1. Open terminal and type echo $PATH. 
2. You will see the path of the variables set it in your system.
3. Now copy the path of the variables shown in the terminal.

Open eclipse, go to your project. If you are trying to run a test suite using testng, you need to some changes in the environment of eclipse during runtime. 

1. In the eclipse, go to "Run" menu > Run configuration.  Select the testng file which you are trying to run.

2. Once you select the testng file, go to Environment tab, create a new variable and put the path of the variables copied from the terminal and save it. 

P.S : select the option "Append environment to native environment" in the Environment tab. I hope it helps to you.
