### ISSUE TITLE
Problem getting session data for driver type AndroidDriver; does it implement 'get driverData'? 

### ISSUE THREAD

**Issue by sarozNep** [appium/appium#9084]
i am frequently getting this error .. i am trying to test an android app on mac....appium version is v1.2.0-beta.1

**Comment by imurchie** [comment]
Can you provide the information asked for in the issue template? Particularly the logs, as a link to a [gist](https://gist.github.com).

**Comment by sarozNep** [comment]
yes but one thing. when i start session from the appium the uiautomator works fine and i can trace the element .. 
but when i start to test the test case from intelliz it gives this error and in appium log file there are no changes ......

**Comment by mykola-mokhnach** [comment]
Such error might appear if one tries to start a new session while the previous one is still in progress. Try to add --session-override argument to appium server to workaround that

**Comment by sarozNep** [comment]
its the only one session i started.... and there are no other session in progress

**Comment by sarozNep** [comment]
same code runs fine in lower version of appium in windows ...but not in mac ?? problem with version maybe ?

**Comment by jlipps** [comment]
@sarozNep we won't be able to help you unless you link to a set of full appium server logs as a gist.

**Comment by sarozNep** [comment]
@jlipps I solved it .. its was session override issue. Thank you for your concern :)
