### ISSUE TITLE
"com.google.common.collect.Multimaps.transformValues" error shows while running the app suite in AWS

### ISSUE THREAD

**Issue by Logakarti** [appium/appium#9088]
## The problem
"com.google.common.collect.Multimaps.transformValues(Lcom/google/common/collect/ListMultimap;Lcom/google/common/base/Function;)Lcom/google/common/collect/ListMultimap" error shows while automating the app suite in AWS for Android. 

I have no idea to predict the exact issue and where it.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Mobile platform/version under test: Android
* Real device or emulator/simulator:  Samsung Galaxy Tab S2 8.0" (WiFi)

## Link to Appium logs

https://gist.github.com/Logakarti/6bb23a42091bebf4670f42b6fc290a22

Please help me to solve this issue.

**Comment by Logakarti** [comment]
@mykola-mokhnach

**Comment by mykola-mokhnach** [comment]
This is java client issue and should be reported to https://github.com/appium/java-client/issues

Closed as server-unrelated.
