### ISSUE TITLE
Update WinAppDriver version

### ISSUE THREAD

**Issue by dsaner** [appium/appium#9089]
There are newer versions of WinAppDriver available that address some issues that I've been encountering.  Is there a way for me to manually change what version of WinAppDriver Appium is utilizing?  When will Appium be including newer versions of this library and what determines when these updates occur?

**Comment by dpgraham** [comment]
We'll update to a new version next release. We're a few versions behind right now. Thanks for the reminder!

**Comment by jlipps** [comment]
the appium-windows-driver has been updated to 0.5.0, which contains WinAppDriver 1.0-RC
