### ISSUE TITLE
Scroll action is getting performed twice, even though command is send once.

### ISSUE THREAD

**Issue by pr4bh4sh** [appium/appium#9090]
## The problem

I'm trying to perform scroll on the screen while automation an iOS app on the simulator.
Scrolling works and the scroll action is performed, but the issue is, it is getting performed twice.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5 and v1.6.6-beta.4 (REV 589a9112bd0516befea756cc8e976fb1c4b031e9)
* Desktop OS/version used to run Appium: Mac OSX 10.12.6 (16G29)
* Node.js version (unless using Appium.app|exe): v6.9.2
* Mobile platform/version under test: iPhone 7 Sim(10.3) 
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: CLI

## Details
I'm using Java client 5Beta9. However, I don't find (in my analysis) this related to language binding as the command execution log is displayed only once in the terminal, logs below.

## Appium logs

```
[HTTP] --> POST /wd/hub/session/7a33dc0c-4914-4e5b-aee2-f6e0a874e8a0/execute {"script":"mobile: scroll","args":[{"direction":"down"}]}
[debug] [MJSONWP] Calling AppiumDriver.execute() with args: ["mobile: scroll",[{"direction":"down"}],"7a33dc0c-4914-4e5b-aee2-f6e0a874e8a0"]
[debug] [XCUITest] Executing command 'execute'
[debug] [BaseDriver] Waiting up to 15000 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/A237EC08-DB06-4F40-B479-4781B15C91BD/element] with body: {"using":"class name","value":"XCUIElementTypeApplication"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"ELEMENT":"F626BC4A-3260-4C6A-9C8B-CFD8C403CF4A","type":"XCUIElementTypeApplication","label":"Test App Dev"},"sessionId":"A237EC08-DB06-4F40-B479-4781B15C91BD","status":0}
[debug] [JSONWP Proxy] Proxying [POST /wda/element/F626BC4A-3260-4C6A-9C8B-CFD8C403CF4A/scroll] to [POST http://localhost:8100/session/A237EC08-DB06-4F40-B479-4781B15C91BD/wda/element/F626BC4A-3260-4C6A-9C8B-CFD8C403CF4A/scroll] with body: {"direction":"down"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"A237EC08-DB06-4F40-B479-4781B15C91BD","status":0}
[debug] [MJSONWP] Responding to client with driver.execute() result: {}
[HTTP] <-- POST /wd/hub/session/7a33dc0c-4914-4e5b-aee2-f6e0a874e8a0/execute 200 6983 ms - 74
```

## Code To Reproduce Issue:

```Java
JavascriptExecutor js = appiumDriver;
HashMap<String, String> param = new HashMap<>();
param.put("direction", "down");
js.executeScript("mobile: scroll", param);
```

**Comment by pr4bh4sh** [comment]
Figured out from [here](https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios-xctest-mobile-gestures.md) that It's a correct behavior(unless I'm wrong again).
Closing this issue.

**Comment by pr4bh4sh** [comment]
Is this an intended behavior of the Appium server?

**Comment by mykola-mokhnach** [comment]
If there is a problem there then it should be on [WebDriverAgent](https://github.com/facebook/WebDriverAgent/issues) side. There is nothing that can be changed on Appium side.

**Comment by rajfidel** [comment]
@pr4bh4sh mobile: scroll with direction up / down / left / right argument is intended to scroll 'exactly'  to the next / previous page (irrespective of the number of scroll attempts it takes to get to this state, though I have generally seen this happen in 2 attempts as well). If you would like to do a single swipe, mobile: swipe with the direction argument is the one to use. The range of swipe motion is pretty broad though and not as accurate (at least from what I have seen).
