### ISSUE TITLE
Facebook Auth. Android fails on Linux, on macOS - OK. 

### ISSUE THREAD

**Issue by isnifer** [appium/appium#9091]
## The problem

Hi, get ready for a cool story. Between **11th** and **12th** of August I've updated `node` version from 4.2.6 (default for Ubuntu 16.4 now) to 8.3.0. The same day I've experienced problems with tests for Android on Linux. 
Not sure that a newer version of node broke my tests and it's only a coincidence.
But, my tests are successful on Android on macOS and fails on Android on Ubuntu.
Does anyone know what's wrong?
Why doesn't appium find an element via accessibilityId?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4 (Linux)
* Last Appium version that did not exhibit the issue (if applicable): 1.6.4 (macOS)
* Desktop OS/version used to run Appium: macOS/Ubuntu 16.4
* Node.js version (unless using Appium.app|exe): 8.3.0
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs
https://gist.github.com/paynd/0aaeeb7f82ac48d749e8656ea9e2fa5c

Successful macOS tests:
![face](https://user-images.githubusercontent.com/1788245/29749731-9f4442ac-8b3b-11e7-8be6-ec7857a9a223.gif)

Failed Linux tests: https://youtu.be/CRJdPvI36xA?t=1m03s

## P.S. I saw issues about accessibilityId on WebViews that does not work, but it's working on macOS.

**Comment by mykola-mokhnach** [comment]
Please attach full Appium log

**Comment by isnifer** [comment]
@mykola-mokhnach https://gist.github.com/paynd/0aaeeb7f82ac48d749e8656ea9e2fa5c here a part of log before error. Should I paste full log?

**Comment by mykola-mokhnach** [comment]
Yes full log is better.

**Comment by isnifer** [comment]
@mykola-mokhnach Full log is here [appium_log.txt](https://github.com/appium/appium/files/1261212/appium_log.txt)

**Comment by mykola-mokhnach** [comment]
do you see the button in the xml if you call driver.getPageSource before locating it?

**Comment by isnifer** [comment]
@mykola-mokhnach let me check

**Comment by isnifer** [comment]
@mykola-mokhnach https://gist.githubusercontent.com/anonymous/2749ebe903fc5605b886228b2816f777/raw/4175fee531da7210916e223a7cb9a08253a1bd60/gist1.xml yes it here, but as I can see **content-desc** equals **"Log In "** not **"Log In"**

**Comment by mykola-mokhnach** [comment]
I'd say this might be some internal platform-related thing in the application code not related to Appium. Just change the locator to match the id by "starts-with" condition instead of doing exact match.

**Comment by isnifer** [comment]
@mykola-mokhnach yes, you are correct. My fault. But it was one of the two problems

**Comment by isnifer** [comment]
@mykola-mokhnach and the main problem on the CI server.
When appium started Facebook authorization test, emulator goes through three states:
1. Open login page
![](http://i.imgur.com/TMLmZKo.png)
2. Click on Facebook button and loading Facebook WebView
![](http://i.imgur.com/FBPCBvl.png)
3. Strange crash application
![](http://i.imgur.com/wXGiIJY.png)

I want to show you the full **[Appium Log](https://gist.github.com/anonymous/c6e75c45048ab93d29a8bedcf176a938)**
And the **[`adb logcat` log](https://gist.github.com/anonymous/6b3ff86e244fbcc759a1785e9e951dae)**

**Comment by mykola-mokhnach** [comment]
What makes you think this application crash has anything to do with Appium?

**Comment by isnifer** [comment]
@mykola-mokhnach I don't know, that's why I've created an issue

**Comment by isnifer** [comment]
@jlipps @imurchie can you look into this too?

**Comment by jlipps** [comment]
@isnifer your appium log link 404s for me. i don't know what your app is called or anything about it so i can't use the adb log very fruitfully. did you look at all the exceptions in it to see which one might be related to the crash? if an app crashes there's almost always a section in the logcat log that says why.

**Comment by isnifer** [comment]
@jlipps problem solved. There is a bug on Android emulator 26.1.4 with --no-window.

**Comment by jlipps** [comment]
love bugs that aren't my fault! thanks @isnifer.
