### ISSUE TITLE
when click the element，memory  rise suddenly

### ISSUE THREAD

**Issue by yefankongge** [appium/appium#9092]
## The problem
click the shop new tab by hand，memory raise a few，but when executing the next code，memory raise suddenly，raise 100MB
driver.findElementByXPath("//XCUIElementTypeOther[2]/XCUIElementTypeButton[3]").click()；

## Environment

Appium version：1.6.5
java-client:5.0.0-BETA8
mac os:10.12
Real device:iphone6s plus 10.3

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

//enter into shopindex
driver.findElementByXPath("//XCUIElementTypeStaticText[@name='xxxxxx']").click();
Thread.sleep(1000L);
//enter into shop new tab
driver.findElementByXPath("//XCUIElementTypeOther[2]/XCUIElementTypeButton[3]").click();

**Comment by mykola-mokhnach** [comment]
Do you mean memory usage on the computer where Appium server is running or on iOS device?

**Comment by yefankongge** [comment]
@mykola-mokhnach I mean that app's memory raise a lot when running the ui testcase with appium

**Comment by mykola-mokhnach** [comment]
This is controlled by XCTest and Appium itself has no control of application memory usage. If you think this is a bug then please report an issue to Apple.

**Comment by yefankongge** [comment]
@mykola-mokhnach I use ui testcase with appium to collect app's memory, but it raise memory suddenly, so the way to collecting app's memory is impossible
