### ISSUE TITLE
appium hangs after performing longpress touch action on ios10.3.2

### ISSUE THREAD

**Issue by sharecommute** [appium/appium#9093]
## The problem

Appium/iproxy is hanging after doing longpress on locator.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):5.0.3
* Mobile platform/version under test: 10.3.2
* Real device or emulator/simulator:yes
* Appium CLI or Appium.app|exe:

## Details
1. Long press on the locator
2. check the behavior

Note: I am seeing this iproxy hangup error after exiting from appium instance else it will stay in that state for more time.
If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

https://gist.github.com/sharecommute/d97cfd566fa53e821f774802a1b3ae63

## Code To Reproduce Issue [ Good To Have ]
Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Long tap is happening on WebDriverAgent side, so we cannot do anything there to fix it. You can try Appium 1.6.6-beta, which includes the most recent WDA snapshot and/or report an issue into https://github.com/facebook/WebDriverAgent/issues if it still does not work.

**Comment by sharecommute** [comment]
ok sure @mykola-mokhnach . I will try that and create a new issue on wda if it still happens.

**Comment by sharecommute** [comment]
@mykola-mokhnach , no-issues after installing 1.6.5
