### ISSUE TITLE
[iOS][XCUITest] Is it possible perform two finger tap and hold it for period of time?

### ISSUE THREAD

**Issue by nottyo** [appium/appium#9094]
## The problem

I cannot perform gesture two finger tap at any x,y on my iOS app and hold it for period of time. I've tried mobile gesture like this

```
HashMap<String, Object> tfLongTap = new HashMap<String, Object>();
tfLongTap.put("x", 200.0);
tfLongTap.put("y", 300.0);
tfLongTap.put("duration", 2.0);
driver.executeScript("mobile: twoFingerTap", tfLongTap);
```
I can see two finger tap applied to my app but it doesn't hold it for period of time (in this case is 2.0 seconds) Noted that there is no error after mobile gesture is performed.

As far as I know, Appium with XCUITest only support mobile gesture for swipe, scroll, pinch, doubleTap, touchAndHold, twoFingerTap, tap, dragFromToForDuration, selectPickerWheelValue and alert referred to [this document.](https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios-xctest-mobile-gestures.md) So I want both "**touchAndHold**" and "**twoFingerTap**" gestures in one action. Is it possible?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS
* Node.js version (unless using Appium.app|exe): 8.2.1
* Mobile platform/version under test: iOS 10.3
* Real device or emulator/simulator: iPhone 7 simulator
* Appium CLI or Appium.app|exe: Using AppiumDriverLocalService class.

## Details
Detail description is provided at the Problem section.

## Link to Appium logs
[https://gist.github.com/nottyo/f65e27103536e58f5f0214e928d7ca0c](https://gist.github.com/nottyo/f65e27103536e58f5f0214e928d7ca0c)

## Code To Reproduce Issue [ Good To Have ]

Sample code is provided at the Problem section.

**Comment by mykola-mokhnach** [comment]
Unfortunately it's impossible with XCTest. See https://developer.apple.com/documentation/xctest/xcuicoordinate and https://developer.apple.com/documentation/xctest/xcuielement for the reference.
