### ISSUE TITLE
Appium 5.0.0 - No swipe method detected

### ISSUE THREAD

**Issue by tlytvyn** [appium/appium#9095]
There is no swipe method for AppiumDriver in 5.0.0 version ?

**Comment by mykola-mokhnach** [comment]
It's by design. One has to use TouchActions interface instead. 
Closed as server unrelated.

**Comment by tlytvyn** [comment]
@mykola-mokhnach 
Can you provide swipe example using TouchActions? I didn't find any related up to date docs

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/sample-code/search?utf8=✓&q=touch
