### ISSUE TITLE
Mobile testing with appium/Android - can't access webelements in the mobile app

### ISSUE THREAD

**Issue by Sanjeewahsp** [appium/appium#9096]
Android mobile app testing with appiumv1.6.5 and java-client-3.2.0. I can't access webelements in the mobile app home page. Home page is loaded, but there is an other window loaded saying "session is expired". No way to move that new window.

driver.switchTo().activeElement()/driver.switchTo().alert() gives "org.openqa.selenium.WebDriverException: Method has not yet been implemented..."
I was trying to check page source, when calling driver.getPageSource(), it was hanging. I have to close mobile app through the device to move to the next step in the code.
capabilities = DesiredCapabilities.android(); 
capabilities.setCapability(MobileCapabilityType.PLATFORM, Platform.ANDROID); capabilities.setCapability("platformName", Platform.ANDROID);
 capabilities.setCapability("deviceName", "emu");	
capabilities.setCapability("app", app.getAbsolutePath()); 
capabilities.setCapability("appPackage", "com.faber.worker"); 
capabilities.setCapability("appActivity", "com.faber.worker.MainActivity"); 
driver = new RemoteWebDriver(new URL("127.0.0.1:4723/wd/hub"), capabilities);	
Thread.sleep(20000); driver.switchTo().activeElement().click(); 

why I can't access webelements there.

further....
when I tried to view home page through appiumv1.6.5 (start New session -->startSession) using following code { "platformName": "Android", "deviceName": "emulator-5554", "app": "D:\\sdk-tools-windows-3859397\\Faber.apk", "appPackage": "com.faber.worker", "appActivity": "com.faber.worker.MainActivity"} it is not loaded complete home page. Since it is getting more than 10 seconds to load my mobile test app. Appium is expecting it before 10 seconds.When I try to "Refresh source and screenshot" after completely loaded the home page, then it is hanging.

Any help?

**Comment by mykola-mokhnach** [comment]
In general, it is necessary to select a proper context prior doing anything inside a webview.
Also:
1.  java-client-3.2.0 is  very old. Please use 5.0.0
2. Attach full server log

**Comment by Sanjeewahsp** [comment]
updated java-client to java-client-5.0.0-BETA7.
Please see the attached server log.
[appium-server-logs.txt](https://github.com/appium/appium/files/1256970/appium-server-logs.txt)

**Comment by Sanjeewahsp** [comment]
I have done following tests too. see logs and screenshot as well
step 1
start session with
{
  "platformName": "Android",
  "deviceName": "emulator-5554",
  "app": "D:\\sdk-tools-windows-3859397\\Faber.apk",
  "appPackage": "com.faber.worker",
  "appActivity": "com.faber.worker.MainActivity"
}
It got the screen shot on the appium window but still app is loading on device.

step 2
Click "Refresh Source and Screenshot" on the appium window
Then hanging here..... Trying to load the app on the appium window....

step 3
Closed the app on the device. Then I can see the device on appium window.

[appium-server-logs-test2.txt](https://github.com/appium/appium/files/1257216/appium-server-logs-test2.txt)
![step1](https://user-images.githubusercontent.com/31409058/29779240-d8b9aa44-8c09-11e7-81f9-85c8055b080b.png)
![step2](https://user-images.githubusercontent.com/31409058/29779255-e636a974-8c09-11e7-9b95-360ab87d8133.png)
![step3](https://user-images.githubusercontent.com/31409058/29779276-f6ec9418-8c09-11e7-8e45-7dd2cec0a2b6.png)

Please see this and help me to sort this out :)

**Comment by mykola-mokhnach** [comment]
I don't see you change the context in the attached log.

**Comment by Sanjeewahsp** [comment]
Sorry mykola-mokhnach, I am new to appium/moble testing..
I have java 1.8.0.141
D:\sdk-tools-windows-3859397\tools\bin>javac -version
javac 1.8.0_141
I added java-client-5.0.0-BETA7 to my eclipse.
Is there any other location I have to change java version?
Then I run above tests.
What you mean that I haven't changed ?

**Comment by jlipps** [comment]
@Sanjeewahsp please read the Appium documentation on webviews and specifically the Contexts API. There are plenty of code samples out there of how to switch to webviews for web automation in the middle of an Appium test.
