### ISSUE TITLE
SplashScreenActivity never started (appium 1.6.4) occurs sporadically

### ISSUE THREAD

**Issue by danielMayberg** [appium/appium#9097]
Problem:
I'm running appium 1.6.4 with Ruby on android real device(samsung galaxy s5, os6)
every time I run a test suite a few of the tests fail splash screen activity never started. I read up on all the issues, tried their solutions and they didn't seem to apply: https://github.com/appium/appium/issues/3514
https://discuss.appium.io/t/appium-android-dispatchactivity-never-started-and-app-is-crashing-on-launch/9188
https://github.com/appium/appium/issues/7267
https://github.com/appium/appium/issues/4298

Sample from code:
in my caps I put : {appWaitActivity:  ".main.activities.SplashScreenActivity"}
I also am using fullReset
is it possible that the appWaitActivity is not working? or did I not put the cap in correctly?

I get the following stack trace:
[Error: air.com.myheritage.mobile/air.com.myheritage.mobile.main.activities.SplashScreenActivity never started]
17:34:15 [ADB] Error: Error occured while starting App. Original error: air.com.myheritage.mobile/air.com.myheritage.mobile.main.activities.SplashScreenActivity never started
17:34:15     at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
17:34:15     at ADB.callee$0$0$ (../../../lib/tools/apk-utils.js:77:9)
17:34:15     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
17:34:15     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
17:34:15     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
17:34:15     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
17:34:15     at run (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:108:47)
17:34:15     at /usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:119:28
17:34:15     at flush (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.microtask.js:19:5)
17:34:15     at _combinedTickCallback (node.js:376:9)
17:34:15     at process._tickCallback (node.js:407:11)
17:34:15  [Error: Error occured while starting App. Original error: air.com.myheritage.mobile/air.com.myheritage.mobile.main.activities.SplashScreenActivity never started]

**Comment by mykola-mokhnach** [comment]
There might be sevreal issues  Either the app crashes on startup or some other activity is started and it is necessary to set a wildcard rather than precise activity name. 
Anyway full server log would be useful.

**Comment by danielMayberg** [comment]
The app isn't crashing on startup and this is the activity name that's in the android manifest of the app.

**Comment by danielMayberg** [comment]
I see this error in the appium log, any idea why sometimes it gets the right activitiy and sometimes it tries to use the autentication activity?
 
Running '/Users/builder/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","87289671","shell","dumpsys","window","windows"]
2017-08-28 08:49:30:429 - info: [debug] [ADB] Found package: 'air.com.myheritage.mobile' and fully qualified activity name : 'air.com.myheritage.mobile.authentication.activities.AuthenticationActivity'
2017-08-28 08:49:30:429 - info: [debug] [ADB] Incorrect package and activity. Retrying.
2017-08-28 08:49:31:185 - info: [debug] [ADB] Getting focused package and activity
2017-08-28 08:49:31:185 - info: [debug] [ADB] Getting connected devices...
2017-08-28 08:49:31:196 - info: [debug] [ADB] 1 device(s) connected
2017-08-28 08:49:31:196 - info: [debug] [ADB] Running '/Users/builder/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","87289671","shell","dumpsys","window","windows"]
2017-08-28 08:49:31:270 - info: [debug] [ADB] Found package: 'air.com.myheritage.mobile' and fully qualified activity name : 'air.com.myheritage.mobile.authentication.activities.AuthenticationActivity'
2017-08-28 08:49:31:270 - info: [debug] [ADB] Incorrect package and activity. Retrying.
2017-08-28 08:49:32:042 - error: [ADB] Error: air.com.myheritage.mobile/air.com.myheritage.mobile.main.activities.SplashScreenActivity or air.com.myheritage.mobile.air.com.myheritage.mobile.main.activities.SplashScreenActivity never started

**Comment by danielMayberg** [comment]
Hi, managed to fix the issue, added air.com.myheritage.mobile.authentication.activities.AuthenticationActivity to the waitAppActivity key. :) thanks for the help.

**Comment by estefafdez** [comment]
Hi, even I add the activity to the appWaitActivity capability, I can't make it work. I'm still have the same issue, any other help¿
