### ISSUE TITLE
iOS clicking/tapping an anchor which triggers an alert causes Appium to stop responding

### ISSUE THREAD

**Issue by timyhou** [appium/appium#9099]
## The problem

In iOS when trying to click a button which triggers an alert, Appium stops responding. 

## Environment

* 1.6.6 beta 4
* Mac OSX Sierra XCode 8 
* Node 7.8
* 10.2 iOS Iphone 6 Simulator 
* Appium CLI 

## Details

In the webview there is a styled anchor which triggers an Alert to confirm the user actions. We noticed the automation was hanging at the spot where the anchor is clicked on. At first we thought it was the alert not being handled properly, but we noticed during debugging that the Click event never finishes executing and is what was getting stuck. 

What is strange is that if we manually intervene by dismissing the alert, appium regains control and can execute commands normally. Other places in the app which have alerts occur are handled normally. 

## Link to Appium logs

https://gist.github.com/timyhou/35709c088fa4089c5b5cf0f5962f9b41

## Code To Reproduce Issue [ Good To Have ]
Nothing really special going on with the script. 
```
# Already validated alert is present and visible
element = driver.find_element_by_id("button")
element.click() # This is the line where Appium stops responding.
alert = driver.switch_to.alert
alert.accept()
```

**Comment by imurchie** [comment]
Thanks for letting us know. This is related to something I'm working on. Hopefully I can get a fix for it.

**Comment by timyhou** [comment]
Thanks! Looking forward to a fix.

**Comment by imurchie** [comment]
@timyhou Can you provide the HTML for the anchor? Just to make sure we reproduce.

**Comment by timyhou** [comment]
```
<div id="recjobSubscribe" class="recjob recjobWidget" style="display: block;">
    <div class="recjobHeader">Get recommended jobs sent to your inbox</div>
    <a class="btn btn-block btn-primary">Send email alerts</a>
</div>
```

Not much is happening in the html of the anchor itself.

**Comment by imurchie** [comment]
How is the alert being triggered?

**Comment by timyhou** [comment]
There is javascript which attaches a listener to the anchor link button. The listener then triggers the alert to happen via a request. I am not sure if you'll be able to recreate a watered down version of that.

**Comment by timyhou** [comment]
Sorry for the delay, I needed a fast lesson closure. The handler listens to [goog.events.EventType.CLICK](https://google.github.io/closure-library/api/goog.events.EventType.html)

**Comment by Trucnt** [comment]
Hi, I've given same problem. Can you please let me know if any update. Thank you so muck.

**Comment by mykola-mokhnach** [comment]
@timyhou is the problem still relevant?

**Comment by timyhou** [comment]
This can be closed. I am not sure if it is still relevant honestly since we've moved on.
