### ISSUE TITLE
Appium Installation fails for chromedriver

### ISSUE THREAD

**Issue by MarkusStadtmann** [appium/appium#9100]
## The problem

In process of installing appium first time, on a corporate network using proxy for http/https. Install process goes thru up-until chromedriver installation, then fails with error "RequestError: Error: getaddrinfo ENOTFOUND chromedriver.storage.googleapis.com chromedriver.storage.googleapis.com:443"

I did configure the proxy in .npmrc and the settings have removed a lot of previous errors but do not seem to help for the chromedriver.

Did google quite some time to fix the reported ENOTFOUND issue without success. Any suggestions?

## Environment

* Appium version (or git revision): most recent
* Last Appium version that did not exhibit the issue (if applicable): none
* Desktop OS/version used to run Appium: Win7 SP1
* Node.js version (unless using Appium.app|exe): 3.10.10
* Mobile platform/version under test: None yet
* Real device or emulator/simulator: None yet
* Appium CLI or Appium.app|exe: None yet

## Details

.npmrc
strict-ssl=false
proxy=http://[USERNAME]:[PASSWORD]@[PROXY]:8080/
https-proxy=http://[USERNAME]:[PASSWORD]@[PROXY]:8080
registry=http://registry.npmjs.org/

## Link to Appium logs

> appium-chromedriver@2.11.2 install C:\Users\mas4kor.US\AppData\Roaming\npm\node_modules\appium\node_modules\appium-chromedriver
> node install-npm.js

info Chromedriver Install Installing Chromedriver version '2.28' for platform 'win' and architecture '32'
info Chromedriver Install Opening temp file to write chromedriver_win32 to...
info Chromedriver Install Downloading https://chromedriver.storage.googleapis.com/2.28/chromedriver_win32.zip...
RequestError: **Error: getaddrinfo ENOTFOUND chromedriver.storage.googleapis.com chromedriver.storage.googleapis.com:443**
    at new RequestError (C:\Users\mas4kor.US\AppData\Roaming\npm\node_modules\appium\node_modules\request-promise\lib\errors.js:11:15)
    at Request.RP$callback [as _callback] (C:\Users\mas4kor.US\AppData\Roaming\npm\node_modules\appium\node_modules\request-promise\lib\rp.js:60:32)
    at self.callback (C:\Users\mas4kor.US\AppData\Roaming\npm\node_modules\appium\node_modules\request\request.js:188:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (C:\Users\mas4kor.US\AppData\Roaming\npm\node_modules\appium\node_modules\request\request.js:884:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

## Code To Reproduce Issue [ Good To Have ]

npm install -g appium

**Comment by mykola-mokhnach** [comment]
You're probably behind enterprise proxy, which prevents the binary above to be downloaded. Try to add this proxy to npm configuration.

**Comment by MarkusStadtmann** [comment]
@mykola-mokhnach , yes, this is indeed correct, I am behind a firewall. I have no problems installing appium on a direct connection, but the proxy is causing the pain. I did configure the proxies in .npmrc as 
proxy=http://[USERNAME]:[PASSWORD]@[PROXY]:8080/
https-proxy=http://[USERNAME]:[PASSWORD]@[PROXY]:8080
and this solved many other error messages the install process otherwise cuased. However, it does not resolve the problem of the chromedriver. 
Is there any additional place I need to configure the proxy to make this work?

**Comment by jlipps** [comment]
@MarkusStadtmann per https://github.com/appium/appium-chromedriver/blob/master/lib/install.js#L11, you can set the `--chromedriver_cdnurl` flag during npm install to another server which is accessible within your firewall. it needs to have the same file structure as the official chromedriver cdn (https://chromedriver.storage.googleapis.com).

e.g.:

```
npm install appium --chromedriver_cdnurl=http://localhost:1234
```

**Comment by MarkusStadtmann** [comment]
@jlipps Thanks for the suggestion. This actually worked for me so happy I can proceed. :-)
Would be interesting to know if there is a way also to really solve this rather than to use a workaround like this...

**Comment by jlipps** [comment]
@MarkusStadtmann the only way to get around your corporate firewall's limitations would be to build proxy support into the chromedriver package downloader, but that's not a high-priority enhancement for us. I'd merge the PR though if someone did the work!

**Comment by samsonbarukula** [comment]
I have Tried with "npm install -g appium --chromedriver_cdnurl=http://localhost:8080" but still the same error : 
Johns-Mac-mini-4:~ john$ npm install -g appium --chromedriver_cdnurl=http://localhost:8080
/usr/local/bin/appium -> /usr/local/lib/node_modules/appium/build/lib/main.js

> appium-chromedriver@3.0.1 install /usr/local/lib/node_modules/appium/node_modules/appium-chromedriver
> node install-npm.js

info Chromedriver Install Installing Chromedriver version '2.30' for platform 'mac' and architecture '64'
info Chromedriver Install Opening temp file to write chromedriver_mac64 to...
info Chromedriver Install Downloading http://localhost:8080/2.30/chromedriver_mac64.zip...
RequestError: Error: connect ECONNREFUSED 127.0.0.1:8080
    at new RequestError (/usr/local/lib/node_modules/appium/node_modules/request-promise/lib/errors.js:11:15)
    at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/appium/node_modules/request-promise/lib/rp.js:60:32)
    at self.callback (/usr/local/lib/node_modules/appium/node_modules/request/request.js:186:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/usr/local/lib/node_modules/appium/node_modules/request/request.js:878:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! appium-chromedriver@3.0.1 install: `node install-npm.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the appium-chromedriver@3.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/john/.npm/_logs/2017-11-24T15_34_11_801Z-debug.log

**Comment by samsonbarukula** [comment]
Can any one help this is the log : 15781 silly install appium-chromedriver@3.0.1
15782 info lifecycle appium-chromedriver@3.0.1~install: appium-chromedriver@3.0.1
15783 verbose lifecycle appium-chromedriver@3.0.1~install: unsafe-perm in lifecycle true
15784 verbose lifecycle appium-chromedriver@3.0.1~install: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/node_modules/.bin:/usr/local/lib/node_modules/appium/node_modules/.bin:/usr/local/lib/node_modules/.bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/john/.rvm/bin
15785 verbose lifecycle appium-chromedriver@3.0.1~install: CWD: /usr/local/lib/node_modules/appium/node_modules/appium-chromedriver
15786 silly lifecycle appium-chromedriver@3.0.1~install: Args: [ '-c', 'node install-npm.js' ]
15787 silly lifecycle appium-chromedriver@3.0.1~install: Returned: code: 1  signal: null
15788 info lifecycle appium-chromedriver@3.0.1~install: Failed to exec install script
15789 verbose unlock done using /Users/john/.npm/_locks/staging-3a08f0df5026584d.lock for /usr/local/lib/node_modules/.staging
15790 verbose stack Error: appium-chromedriver@3.0.1 install: `node install-npm.js`
15790 verbose stack Exit status 1
15790 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
15790 verbose stack     at emitTwo (events.js:126:13)
15790 verbose stack     at EventEmitter.emit (events.js:214:7)
15790 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
15790 verbose stack     at emitTwo (events.js:126:13)
15790 verbose stack     at ChildProcess.emit (events.js:214:7)
15790 verbose stack     at maybeClose (internal/child_process.js:925:16)
15790 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
15791 verbose pkgid appium-chromedriver@3.0.1
15792 verbose cwd /Users/john
15793 verbose Darwin 16.7.0
15794 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "appium" "--chromedriver_cdnurl=http://localhost:1234"
15795 verbose node v8.9.1
15796 verbose npm  v5.5.1
15797 error code ELIFECYCLE
15798 error errno 1
15799 error appium-chromedriver@3.0.1 install: `node install-npm.js`
15799 error Exit status 1
15800 error Failed at the appium-chromedriver@3.0.1 install script.
15800 error This is probably not a problem with npm. There is likely additional logging output above.
15801 verbose exit [ 1, true ]

**Comment by samsonbarukula** [comment]
any help is highly appreciated

**Comment by samsonbarukula** [comment]
it is working by setting npm proxy server.... thank you all

**Comment by samsonbarukula** [comment]
Owner was correct ... great ..... Jonathan thank you
