### ISSUE TITLE
Proposal to add new members to Appium's TC

### ISSUE THREAD

**Issue by jlipps** [appium/appium#9101]
I would like to propose new members for Appium's [Technical Committee](https://github.com/appium/appium/blob/master/GOVERNANCE.md), to recognize the extraordinary commitment these individuals have made to Appium and their importance in the project's maintenance and evolution. (For these maintainers to join the TC, it will be necessary for a pro vote from each current TC member)

1. Recommendation of @imurchie : for some time Isaac has been the lead developer and code reviewer for Appium's core libraries and drivers, and currently has the deepest understanding of the Appium codebase and architecture.

    * [X] @bootstraponline 
    * [X] @dandoveralba 
    * [X] @jlipps
    * [x] @mykola-mokhnach 
    * [X] @penguinho 

2. Recommendation of @TikhomirovSergey : Sergey is the lead maintainer of the Java client, historically the most extensively-developed client library for Appium. It is important that the Appium TC have not just core developers but also library maintainers.

    * [X] @bootstraponline 
    * [X] @dandoveralba 
    * [X] @jlipps
    * [x] @mykola-mokhnach 
    * [X] @penguinho 

3. Recommendation of @KazuCocoa : Kazu is the maintainer of the Ruby client. They started out as a contributor not too long ago but have made many, many improvements, and have brought the Ruby client back from the brink of abandonment.

    * [X] @bootstraponline 
    * [X] @dandoveralba 
    * [X] @jlipps
    * [x] @mykola-mokhnach 
    * [X] @penguinho

**Comment by jlipps** [comment]
(suppose I could have done this as a PR, will follow up with one and link once approvals are confirmed)

**Comment by bootstraponline** [comment]
Approved.

**Comment by jlipps** [comment]
@mykola-mokhnach do you approve? turns out github doesn't save it when you check a box in the issue, you actually have to edit the markdown

**Comment by mykola-mokhnach** [comment]
Yes I approve

**Comment by penguinho** [comment]
👍

**Comment by dandoveralba** [comment]
👍

**Comment by bootstraponline** [comment]
> suppose I could have done this as a PR

I think going forward, PR approvals make more sense than checkboxes in markdown. 😄

**Comment by jlipps** [comment]
@bootstraponline fully agree, i have learned my lesson :-)

**Comment by KazuCocoa** [comment]
thanks so much!
