### ISSUE TITLE
Unable to launch app by bundle I'd on iOS simulator

### ISSUE THREAD

**Issue by jamesvanhorn** [appium/appium#9102]
## The problem

Setting app capability to com.apple.Preferences does not work for iOS simulator, throwing an error stating unable to find an app by bundleId "com.apple.Preferences". Same error if I set capability.app to "settings" as suggested elsewhere. The really strange thing here is that this works on a real device for me, but not the simulator. All documentation I could find mentions this launching by bundle I'd as a simple only option. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.6-beta4
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac Sierra
* Node.js version (unless using Appium.app|exe): 8.4.0
* Mobile platform/version under test: iOS 10.3.3 real device iOS 10.3.1 sim
* Real device or emulator/simulator: aim for error
* Appium CLI or Appium.app|exe: cli

I wonder if this could be related to how the iOS simulator stores system apps vs apps installed. The folders were structured differently when I looked in the simulator on disk. Also of note, if I specify capability.app=<bundleID> of the app we normally automate, that works on a real device AND simulator.

**Comment by mykola-mokhnach** [comment]
can you please attach server log with the error?

**Comment by jamesvanhorn** [comment]
Will do

**Comment by mykola-mokhnach** [comment]
Try not to set the **app** capability, but rather set the **bundleId** one to "com.apple.Preferences"

**Comment by jamesvanhorn** [comment]
Same result with setting bundleId. Does it matter at all that the simulator stores apps at /Users/jamesvanhorn/Library/Developer/CoreSimulator/Devices/34CA3317-796B-46EF-A2D0-9266BE625572/data/Containers/Bundle/<HASH>/whatever.app?

There are only 2 hashed folder here, one for the app under test, the other for WDA. Not sure if thats the directory that driver.js checks for? Trying to understand how isAppInstalled works for the simulator.

As a semi-workaround, i can use `xcrun simctl launch 34CA3317-796B-46EF-A2D0-9266BE625572 com.apple.Preferences` and that does work

**Comment by mykola-mokhnach** [comment]
that's strange. I'll investigate that

**Comment by mykola-mokhnach** [comment]
Please update to the recent beta version. The fix should be there.

**Comment by jamesvanhorn** [comment]
@mykola-mokhnach update to newest appium beta (1.7.0)? Or update node-simctl to its latest beta? Also, will i need --no-shrinkwrap arg? Thanks
