### ISSUE TITLE
Mobile testing with appium/Android - Session expired and timeout issues in appium

### ISSUE THREAD

**Issue by Sanjeewahsp** [appium/appium#9105]
Appiumv1.6.5 and app testing on android device.
Steps I have followed,
Start new session on appium. start session with setting as
{
  "platformName": "Android",
  "deviceName": "emulator-5554",
  "app": "D:\\sdk-tools-windows-3859397\\Faber.apk",
  "appPackage": "com.faber.worker",
  "appActivity": "com.faber.worker.MainActivity"
}
Then I can see my device on appium window and still my app is loading on the device. but before completely loading the app ,the Appium is getting the screenshot and stop. So I can't see the home page there.
After that I tried to clicking "Refresh Source and Screenshot". Then it was hanging...

Is there any way to setting timeouts and session times in appium ?
Is this not related to timeouts and session times ? or issue with my app.
normally my app is taking 12 seconds to load on device.

![step2](https://user-images.githubusercontent.com/31409058/29810926-a23b6940-8c99-11e7-8266-c4018f8fc247.png)

**Comment by mykola-mokhnach** [comment]
Please use Appoim forum to ask questions.
