### ISSUE TITLE
Javascript does not work on Safari real devices.

### ISSUE THREAD

**Issue by mahesh-thuma** [appium/appium#9107]
I have a scenario where i need to enter email and click on submit button but when webdriver enters email and clicks on submit button an error is thrown "Email is Required" although webdriver entered the email which i can see. I have this issue on Firefox and Safari both on Desktop and mobile devices. With a bit of research i able to fix for Firefox with below javascript code.

```
JavascriptExecutor js = ((JavascriptExecutor)driver);
js.executeScript("var e=document.getElementById('email'); e.dispatchEvent(new Event('change')); e.dispatchEvent(new Event('blur')); return true;" );
```
But the same code does not work on mobile safari on real device. Could someone help in fixing this issue ?		

## Environment

* Appium version - 1.6.5
* Mac os : 10.12.6 
* Node.js version - 3.10.10
* Mobile platform/version under test: - 10.3 
* Iphone 6 Real device
* Using Appium desktop client

Logs: <script src="https://gist.github.com/mahesh-thuma/f02f6fdc81d48d4c0a16e2dd71412e0c.js"></script>

**Comment by dpgraham** [comment]
Instead of executing a Javascript code snippet, have you tried using actual Selenium commands (e.g.: `findElement(by.id("email"))`).

**Comment by mahesh-thuma** [comment]
@dpgraham I did try by id. Please find below incase you don't get my point by my question.

**Step 1)** driver.findElement(by.id("email")).sendkeys("test@xyz.com"); --> **webdriver able to enter email in the field.**

**Step 2)** driver.findElement(by.id("submit")).click(); --> **webdriver able to click on the submit button.**

**Issue:** After Step 2 i am getting error thrown in the application as "Email is Required". So upon the webdriver click on submit button my application is ignoring the email entered by webdriver in Step 1.

As mentioned in the query i faced this issue on firefox and safari both on desktop and mobile. But with the javascript which i inserted between Step 1 and Step 2 i was able to fix this issue in firefox browser. But i still have this issue only on Real iOS device.

**Note:** The issue here is not finding the element but more of element losing the focus on some change events or something which i don't have enough knowledge on.

**Comment by mahesh-thuma** [comment]
Figured out the issue. There is a small change in the email attribute from desktop ("email") to mobile ("Email"). Modified the javascript accordingly and i am able to proceed ahead. Though this is still an workaround but does the job. Closing this issue and Thanks to anyone investing time on this.
