### ISSUE TITLE
No screenshot displayed in the Appium Inspector

### ISSUE THREAD

**Issue by farooqyousuf** [appium/appium#9108]
## The problem
There is no screenshot displayed in the Appium Inspector.
Instead of the screenshot display it says: "Could not obtain screenshot: [object Object]

Appium logs give this error:
[AndroidDriver] Error: Cannot get screenshot data because of 'The size of the taken screenshot equals to zero.'

## Environment
* Appium version (or git revision) that exhibits the issue: 1.6.6-beta.4
* Last Appium version that did not exhibit the issue (if applicable): n/a
* Desktop OS/version used to run Appium: macOS Sierra Version 10.12.6
* Node.js version (unless using Appium.app|exe): 5.3.0
* Mobile platform/version under test: Android 7.0 
* Real device or emulator/simulator: Real device and emulator
* Appium CLI or Appium.app|exe: Appium CLI

## Details
There is no screenshot displayed in the Appium Inspector.
Instead of the screenshot display it says: "Could not obtain screenshot: [object Object]

Appium logs give this error:
[AndroidDriver] Error: Cannot get screenshot data because of 'The size of the taken screenshot equals to zero.'

## Link to Appium logs
Appium logs:
https://gist.github.com/farooqyousuf/db85c3d56184c1508c4abd8f5138797e

**Comment by mykola-mokhnach** [comment]
It seems like Android app you want to take a screenshot from prevents this, so the size of resulting screenshot file is zero.

**Comment by farooqyousuf** [comment]
@mykola-mokhnach Thanks, just tried to take a screenshot of the app manually and you are right it won't allow it due to security policy.
