### ISSUE TITLE
ios driver - no response when click on radio button by xpath

### ISSUE THREAD

**Issue by niu0220** [appium/appium#9109]
## The problem
I have trouble to click on radio button by using xpath.
the issue is only happen in 1.6.5 version (1.6.4 is working correctly)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5 
* Last Appium version that did not exhibit the issue (if applicable): 1.6.4
* Desktop OS/version used to run Appium: 10.12.6
* Node.js version (unless using Appium.app|exe):v8.1.1
* Mobile platform/version under test: 10.3
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: Appium Desktop

## Details
The radio button is inside of UIWebView in iOS App.  the radio button is not selected when I used inspector to find xpath, and tap element.

## Link to Appium logs

[Appium-log.txt](https://github.com/appium/appium/files/1261520/Appium-log.txt)

![img_9344](https://user-images.githubusercontent.com/31452800/29840481-0d832f18-8cb7-11e7-87e3-23f1e693ccb6.JPG)

**Comment by mykola-mokhnach** [comment]
Try to change the context to webview.

**Comment by niu0220** [comment]
Hi mykola-mokhnach, I am not able to change source codes. is any other way to do it?

**Comment by jlipps** [comment]
webviews cannot be automated in appium desktop. if you want to inspect a webview element, use Safari to connect to your app in the simulator. Read the docs on the context api, this is something you use in your test code, not something in the app code.
