### ISSUE TITLE
Element Property shows Enabled always even if the element is disabled

### ISSUE THREAD

**Issue by reach2jeyan** [appium/appium#9116]
I find in the appium inspector and even `isenabled?` code, that the element that has `userinteraction = false` shows `enabled = true` in Appium.

This happens when I view element in iOS on both device and simulator.

I need to pass a check, that returns me `enabled = false` if the element is disabled.

I need to know if its an issue with Appium or which property in iOS element, should be modified so that Appium recognises that element status to be True/False based on the element being enabled/disabled respectively.

**Comment by mykola-mokhnach** [comment]
The value of this property is taken from WebDriverAgent, which gets its from _isEnabled_ property of the corresponding XCUIElement object. It is not possible to change anything there on Appium side.

**Comment by mykola-mokhnach** [comment]
https://github.com/facebook/WebDriverAgent/blob/master/WebDriverAgentLib/Categories/XCUIElement%2BFBWebDriverAttributes.m

**Comment by reach2jeyan** [comment]
@mykola-mokhnach Why does Appium show a disabled element to be enabled? Is there anything to be implemented in the iOS Application code? or what property of the element in the application code, does Appium access to get this when I inspect.

**Comment by mykola-mokhnach** [comment]
Check the source code above. WDA property name is **wdEnabled**. 

> Is there anything to be implemented in the iOS Application code

Check the XCTest framework documentation and I believe you'll find something.
