### ISSUE TITLE
iOS: Log capture broken! Ruby Client!

### ISSUE THREAD

**Issue by reach2jeyan** [appium/appium#9117]
I am trying to fetch the logs with appium for iOS application. But I am thrown an undefined error for the code, which was working previously with appium.

I have tried this code in 1.6.4, 1.6.5 and 1.6.5beta but in vain.

To fetch the logs code
```
$driver.get_log(“crashlog”)
$driver.get_log(“syslog”)
```

My Desired capabilities has
`showIOSLog: "true",`

The error I get:
`undefined method `get_log’ for #Appium::Driver:0x007f8876165610`

I am using Xcode version more than 8.

Has the code changed? or is this still an open issue?

**Comment by mykola-mokhnach** [comment]
Please report ruby client issues to the correct project: https://github.com/appium/ruby_lib

**Comment by reach2jeyan** [comment]
@mykola-mokhnach  Has the issue been fixed in the Appium 1.6.5beta? this issue could be related to the appium cleints too?>

**Comment by imurchie** [comment]
The `showIOSLog` capability controls whether the logs get inlined into the Appium server logs.

The issue you are seeing is purely a client issue.
