### ISSUE TITLE
iOS 11 - Error connecting to device! 

### ISSUE THREAD

**Issue by dilsreccse** [appium/appium#9118]
## The problem

Unable to kick start Native App automation in iOS 11 beta with Appium beta (1.2.0-beta.3) version. "[iProxy] Error connecting to device!" error message is displayed in the appium log after the application launch.

## Environment

* Appium version (or git revision) that exhibits the issue: Appium beta (1.2.0-beta.3) 
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Desktop OS
* Node.js version (unless using Appium.app|exe): 
* Mobile platform/version under test: iPad Pro iOS 11
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Link to Appium logs

Find the console log in the below GIST link
 [GIST](https://gist.github.com/dilsreccse/fedc3c7f482e14ef460b7ba9e31a0d6f)

**Comment by saikrishna321** [comment]
you need to have latest 1.6.6.beta

**Comment by mykola-mokhnach** [comment]
WDA is unable to take a screenshot from the device. There is a workaround in the recent beta release, although it is only available if you install it via npm.
