### ISSUE TITLE
can not input file path in the input box

### ISSUE THREAD

**Issue by vickywyy** [appium/appium#9120]
## The problem
i am using robotframework+appiumlibrary+winAppDriver to test my windows PC application.
but I can not input the file path in the input box via the **Input Text** keyword in appiumlibrary.  
if the file path is valid, it will throw out an error in robotframework:
**"WebDriverException: Message: The URL '/wd/hub/session/69a45511-8491-4f91-b3f3-ee8140ccd10d/file' did not map to a valid resource"**
the path is treated as a file, not a path string.

in the appium server log, you can see
[HTTP] --> POST /wd/hub/session/69a45511-8491-4f91-b3f3-ee8140ccd10d/file {"sessionId":"69a45511-8491-4f91-b3f3-ee8140ccd10d","id":"42.3342964"**,"file":**"UEsDBBQAAAAIAABrkEUpnp0Fq10rADZYLwAKAAAAZmxvd2VyLmJtcIzbdXQjW54n+HyQYBAzM4Ml\nyyC0LTMzyCQ.....

details, please have a check the attached log <test_appium_console_validPath.txt>

but if the file path does not exists, the path can be input in the input box
in the appium server log, you can see it is Post as value, not file

[HTTP] --> POST /wd/hub/session/474fd1e3-ff7b-4680-a8bd-0ca7a4856bc4/element/42.8915682/value {"sessionId":"474fd1e3-ff7b-4680-a8bd-0ca7a4856bc4","id":"42.8915682","value":["C",":","\\","f","l","o","w","e","r","1",".","b","m","p"]}

details, please have a check the attached log <test_appium_console_invalidPath.txt>

[test_appium_console_invalidPath.txt](https://github.com/appium/appium/files/1263043/test_appium_console_invalidPath.txt)
[test_appium_console_validPath.txt](https://github.com/appium/appium/files/1263044/test_appium_console_validPath.txt)

please have a check what is wrong. thx!
## Environment

* Appium version (or git revision) that exhibits the issue: v1.6.5
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Win10
* Node.js version (unless using Appium.app|exe): appium.exe
* Mobile platform/version under test:N/A
* Real device or emulator/simulator:N/A
* Appium CLI or Appium.app|exe: Appium.exe

**Comment by mykola-mokhnach** [comment]
This looks like Robot Framework issue, because it automatically tries to check for file existence and call the appropriate API. This works in case of browser automation, but is not the case for Appium. Please check whether it is possible to change this behaviour on RF side.

**Comment by jlipps** [comment]
There is no way to upload files in mobile browsers. That is a technique for using selenium with desktop browsers. Think how a user of your app would upload something instead, and automate it that way.
