### ISSUE TITLE
Tests stuck on 2 hours 

### ISSUE THREAD

**Issue by shapovalovei** [appium/appium#9121]
## The problem

After I run test suit all work fine. But after sometimes  I have error ``` 2017-08-29 20:31:40:712 - [MJSONWP] Encountered internal error running command: Error: Could not proxy. Proxy error: UiAUtomator shut down unexpectedly ```. 
And tests stuck on  ``` [Appium] Closing session, the cause was 'New Command Timeout of 60 seconds expired. Try customizing the timeout using the 'newCommandTimeout' desired capability' ```

```
[INFO]  13:47:05: [DriverFactory] **************************** CREATING REMOTE WEB DRIVER ***************************
[INFO]  13:47:05: [DriverFactory] PLATFORM NAME: Android
[INFO]  13:47:05: [DriverFactory] PLATFORM VERSION: 6.0.1
[INFO]  13:47:05: [DriverFactory] DEVICE NAME: Samsung edge 6 (Jenkins SF)
[INFO]  13:47:05: [DriverFactory] DEVICE BROWSER: Chrome
[INFO]  13:47:05: [DriverFactory] DEVICE UDID: 06157df688763d11
[INFO]  13:47:05: [DriverFactory] DEVICE USB PORT: null
[INFO]  13:47:05: [DriverFactory] ***********************************************************************************
[INFO]  13:47:05: [DriverFactory] 

2017-08-29 20:47:11:882 - [ADB] Cannot read version codes of /usr/local/lib/node_modules/appium/node_modules/io.appium.settings/app/build/outputs/apk/settings_apk-debug.apk and/or io.appium.settings. Assuming correct app version is already installed
2017-08-29 20:47:21:957 - [AndroidDriver] No app sent in, not parsing package/activity
2017-08-29 20:48:43:190 - [BaseDriver] Shutting down because we waited 60 seconds for a command
2017-08-29 20:48:43:198 - [Appium] Closing session, cause was 'New Command Timeout of 60 seconds expired. Try customizing the timeout using the 'newCommandTimeout' desired capability'
[INFO]  16:47:06: [DriverFactory] Looks like we have problem with creating driver. Try restart all servers.
[INFO]  16:47:06: [DriverFactory] DELETE APPIUM
[INFO]  16:47:06: [DriverFactory] 
``` 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Last Appium version that did not exhibit the issue (if applicable): 1.6.5
* Desktop OS/version used to run Appium: OS X
* Node.js version (unless using Appium.app|exe): v7.9.0
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real 
* Appium CLI or Appium.app|exe: cli

**Comment by mykola-mokhnach** [comment]
> UiAUtomator shut down unexpectedly

This is UIA issue and it cannot be fixed on Appium side. Try to use UIAutomator2.

**Comment by shapovalovei** [comment]
@mykola-mokhnach How can I switch on UIAutomator2?

**Comment by ochubey** [comment]
@shapovalovei 
In java you set capability like this one:
`capabilities.setCapability("automationName", "UiAutomator2");`

**Comment by shapovalovei** [comment]
@ochubey @mykola-mokhnach many Thanks.
