### ISSUE TITLE
Device fall asleep while testing in Android, Chrome resulting /screenshot timed out after 180 seconds.

### ISSUE THREAD

**Issue by mittt** [appium/appium#9125]
## The problem

Devices' displays started to fall asleep while testing in Android, Chrome, resulting in "/screenshot timed out after 180 seconds."

The tests where working, a week before. My theory is that the Android Chrome got updated or I may have updated the SDK Platform tools(adb). 

I was using appium@1.6.3(from Git, can't check the revision anymore), updated to the latest - the test fails on both. 

## Environment

* Appium version (or git revision) that exhibits the issue:  appium@1.6.3, appium@1.6.5 (npm install appium -g)
* Last Appium version that did not exhibit the issue (if applicable): appium@1.6.3
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): v5.9.1
* Mobile platform/version under test: Android 6.0, Android 6.0.1, Android 5.0.1
* Real device or emulator/simulator: real
* Appium CLI or Appium.app|exe: cli
.NET Client Lib - Appium.WebDriver v. 3.0.0.2 (latest)

## Details
Those are exerts from the Appium log:
[Appium log exerts ](https://gist.github.com/mittt/4618eac654d19850351576cfe4f085ec)

## Link to Appium logs

[.NET Client Exception](https://gist.github.com/mittt/45b8da39535a902c1d990f71ac56f648)
[Full Appium Log](https://gist.github.com/mittt/ff8ace868ac3744e2a85c109dd42497f)

**Comment by mykola-mokhnach** [comment]
Probably, it would be easier to just disable sleep/lock timer for the device under test.

**Comment by mittt** [comment]
On those devices, the maximum is 30min, we have a test that runs for more then that, it's a kind of a benchmark test, we are testing for performance degradation and memory leaks this way.

**Comment by jlipps** [comment]
Sorry @mittt it sounds like you're right that this is a chrome or android issue. I'd recommend looking for device settings that prevent the display from falling asleep.
