### ISSUE TITLE
Flexible way of obtaining capabilities for a device

### ISSUE THREAD

**Issue by jbhandari** [appium/appium#9127]
Hey there,

This is related to **[Issue #574](https://github.com/appium/ruby_lib/issues/574)** where the original poster was inquiring about how to find more capabilities from a single known attribute.

In majority of the use cases, when testing out a device you would know basic attributes such as the device id, the operating system, the operating system version. 

**However here is an alternative context:**

What if your devices sat physically connected to a server in a remote location, and you did not have physical access to it? You knew a basic single attribute like device name or device id, but you did not know if someone at the remote server location updated the device operating system from 10.1.1 to 10.1.2? 

_Put another way:_

What if the capabilities creation for devices was more simple and the code was able to decipher additional attributes. For example, in creating the capabilities for the device we only pass in the UDID and then Appium takes that UDID, scans the server's system for connected devices and from those devices finds the match based on the UDID and then sets operating system, operating system version, etc.

Does Appium have this capability or does it require that these capabilities be known before hand? Or is there a way other developers were able to achieve that scenario I stated above?

Thanks in advance

**Comment by jlipps** [comment]
Pretty sure that all you really need to know at the moment is the UDID? Or has that not been your experience.

**Comment by jbhandari** [comment]
The scenario where you have the UDID is straight forward I agree. However I am inquiring about large scale test operations that need major flexibility.

For example:

A test team sits remotely from an Appium server that has several devices connected to it. The team is concerned with how their app interacts with a specific iOS version. The server may have several iPhones connected that differ in attributes (ex: iPhone 6s running iOS 10.1.1, iPhone 6s running iOS 10.1.2, iPhone 6 running 9.0.1, iPhone 5s running iOS 10.1.1, etc.). For efficiency purposes all a team member sends in for arguments: 

```
  def server_scan(platform: 'ios', version: '10.1')
    * do something *
  end
```

The appium server is then flexible enough to scan the server for connected devices and find one that meets the criteria to run a test on. If we want to target a specific phone model we write:


```
  def server_scan(model: '6s', platform: 'ios', version: '10.1')
    * do something *
  end
```
Then appium uses the criteria to scan and find a device that matches or throws an error back to the developer that the server_scan function does not have a device that meets the criteria. 

So what I am trying to zero in on is if there is this ability in appium, or is there a way that you are aware of that developers have been able to achieve this?

Thanks for getting back to me, I really appreciate it!

**Comment by jbhandari** [comment]
Just to add, the flexibility I am inquiring/advocating about in my scenarios reduces the need to have an exact UDID, and allows for testers to concentrate on simple attributes like phone, os, and os versions.

**Comment by jbhandari** [comment]
@jlipps Any idea on this feature if it exists? I wanted to know if Appium has this under the hood that I may not know about or missed in the docs. 

If this feature does not exist, please look into these libraries for [iOS](https://github.com/bbc/device_api-ios) and [Android](https://github.com/bbc/device_api-android). They allow us to scan all devices connected to a computer, and we can find a device or set of devices that match more general capabilities like os, os version, model, etc. instead of sending in something as explicit as UDID. This solves that increased flexibility/server scan feature I am talking about.

Please let me know if you find this of value, and if you would like I could perhaps make a pull request, or create a plugin, with your guidance on this. The libraries both hold the MIT license. Please let me know your thoughts.

**Comment by jlipps** [comment]
@jbhandari pretty sure this feature exists for android already. if you specify a platformVersion, appium will find a connected device of the appropriate version. this feature does not exist for iOS. i'll mark this issue as an enhancement request.
