### ISSUE TITLE
W3C Compliance: platformName and Appium requests

### ISSUE THREAD

**Issue by matthewdoerksen** [appium/appium#9128]
## The problem

As of Selenium 3.5.2, platform and platformName are now considered equivalent as per the W3C spec. In the future, platformName will be the only variable used. In conjunction with Selenium Grid, platformName is injected which means that for iOS tests (though Android is likely to also be affected) MAC is listed as the platform (and now platformName).

## Environment

Issue exists on all platforms and versions not yet W3C compliant.

## Details

What needs to be done is:
1) switch to using platformName everywhere in place of platform to get up to W3C spec compliance.
2) come up with an appropriate workaround, such as using platformName = Mac and a new variable to house the current platformName (e.g. automationName = "iOS")

## Additional Info

PR for a temporary fix in Selenium to add an iOS platform: https://github.com/SeleniumHQ/selenium/issues/4557

**Comment by mykola-mokhnach** [comment]
@jlipps FYI

**Comment by jlipps** [comment]
Thanks @matthewdoerksen. I want to make sure I understand. Are you saying that, during use of Selenium Grid, your Appium client will send `platformName: iOS` to the Grid, and then the Grid will send `platformName: MAC` to the Appium server?

Your workaround is reasonable. We could even keep `automationName` the same as it currently is (`XCUITest` for example), and simply check `automationName` before we check `platformName`. What do you think @imurchie?

**Comment by imurchie** [comment]
That should work. We already do that, so it should work now.

**Comment by matthewdoerksen** [comment]
@jlipps To clarify, for now we will continue to send platformName: iOS and platform: Mac in the JSON blob (on the Selenium side this was fixed in 3.5.3) to remain backwards compatible. At some point in the future, Appium should transition to using automationName and platformName since this better aligns with the W3C standard.

**Comment by imurchie** [comment]
You could try now with `platformName` = `Mac` and `automationName` = 'xcuitest`. Appium should work with that.

**Comment by SrinivasanTarget** [comment]
@TikhomirovSergey FYI

**Comment by jlipps** [comment]
it sounds like nothing more needs to be done given an appropriate automationName in the capabilities, so I'm going to close this.
