### ISSUE TITLE
[MJSONWP] Encountered internal error running command with Appium 1.6.5 and Android 7

### ISSUE THREAD

**Issue by Ashley-Belka** [appium/appium#9129]
## The problem
Recently we had to update our Android tablets and test environment to Android 7. In Android 6 everything works perfectly fine but Android 7 with the latest Appium (1.6.5) and the "automationName" capability set to "uiautomator2" is not working. Even without setting the automationName capability tests do not run correctly, and will at times not correctly find elements where they previously were able to successfully and consistently in Android 6.

Appium-doctor says everything looks good, adb works via command line since the %ANDROID_HOME% and path are configured. The app launches, clicks the first button correctly, but displays the error in the gist below multiple times.

[GebConfig gist](https://gist.github.com/Ashley-Belka/96c04402a0306c52071ab7d46b36a2ec)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Last Appium version that did not exhibit the issue (if applicable): 1.6.3 (Ran 1.6.3 with Android 6)
* Desktop OS/version used to run Appium: Windows 7
* Node.js version (unless using Appium.app|exe): 6.3.0
* Mobile platform/version under test: Android 7 (Samsung tablet)
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs

[The Appium logs](https://gist.github.com/Ashley-Belka/ee66b2178c994ccb9e32d6650be3a8c7)

[The error shown on the client (test) side.](https://gist.github.com/Ashley-Belka/b01572d03a750bd1d86e1328b8916fda)

**Comment by mykola-mokhnach** [comment]
I see you are using "-android uiautomator" location strategy. The UIAutomation object is not supported by Google, so I wouldn't be surprised if it does not work as expected in newer Android versions. Does it work  if you replace these locator types with xpath/acessbility id?

**Comment by mykola-mokhnach** [comment]
Also, my assumption can be confirmed by the comment inside UIA2 server code method for nested children search:

```
        if (selector instanceof UiSelector) {
     /**
             * We can't find the child element with UiSelector on UiObject2,
             * as an alternative creating UiObject with UiObject2's AccessibilityNodeInfo
             * and finding the child element on UiObject.
             */
...
```

**Comment by Ashley-Belka** [comment]
I use a library (Geb-Mobile) for finding elements through Appium. Turns out it was an issue with that. Thanks for your feedback.
