### ISSUE TITLE
Exception in thread "ThreadedStreamConsumer" java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by KuKiSiNi77** [appium/appium#9130]
## The problem

i don't know how to describe the problem.there has not any other message.when the log display, the program stopped running.

## Environment

* Appium version (or git revision) that exhibits the issue: Appium v1.6.6-beta.4
* Desktop OS/version used to run Appium: macOS 10.12.5 (16F73)
* Node.js version (unless using Appium.app|exe): node v6.6.0
* Real device or emulator/simulator: Real device 

[Appium] Capabilities:
[Appium]   noReset: true
[Appium]   platformVersion: '10.3.0'
[Appium]   automationName: 'XCuiTest'
[Appium]   useNewWDA: true
[Appium]   browserName: ''
[Appium]   udid: '9da82887884423f91840e4a4601862d2821de94a'
[Appium]   platformName: 'iOS'
[Appium]   deviceName: 'autotest'
[Appium]   launchTimeout: 500000

XCUITestDriver version: 2.43.1
Xcode version set to '8.3.3' (tools v8.3.2.0.1.1492020469)
iOS SDK Version set to '10.3'

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

```java 

Exception in thread "ThreadedStreamConsumer" java.lang.OutOfMemoryError: Java heap space
2017-08-31 05:41:52.723 java[748:27006] JavaNativeFoundation error occurred obtaining Java exception description
Exception in thread "Thread-2" java.lang.OutOfMemoryError: Java heap space

```

**Comment by rajfidel** [comment]
Can you provide the code that threw the error?

**Comment by KuKiSiNi77** [comment]
maybe i have found the problem. i get a endless loop

```java
while (!commonToolsDefinition.iSElementDisplay(salesPage.bookTicketUseCellList.get(count))) {
                            commonToolsDefinition.swipeAction(salesPage.tvBookTicketUse, "upward");
                        }

                        if (runTime > 3) {
                            System.out.println("退出循环");
                            break;
                        }

```

**Comment by rajfidel** [comment]
Endless loop is the usual suspect for OutOfMemoryError.

**Comment by mykola-mokhnach** [comment]
closed as server-unrelated issue
