### ISSUE TITLE
Android: UIAUTOMATOR2: CHAIN strategy does not work

### ISSUE THREAD

**Issue by amedvedjev** [appium/appium#9133]
## The problem

Chain strategy does not work when finding elements. Problem does not exists when caps set to:
```
capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.APPIUM);
```

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.0-beta, java-client: 5.0.1
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real phone with Android 6.0

## Code To Reproduce Issue [ Good To Have ]

```
    @HowToUseLocators(androidAutomation = LocatorGroupStrategy.CHAIN)
    @AndroidFindBy(id = "sliding_dashboard")
    @AndroidFindBy(id = "handle_icon")
    private AndroidElement switchAccountIcon;
```

## Link to Appium logs

https://gist.github.com/amedvedjev/2da1468ca7aad98f9b827cd171e80118

**Comment by mykola-mokhnach** [comment]
I assume the issue has to be reported to java client rather than here, shouldn't it?

**Comment by amedvedjev** [comment]
@mykola-mokhnach i suggested that logic in java-client is same. and it is visible in logs that it is. so if you sure that it is problem not in UIAUTOMATOR2 driver i will copy bug into java-client. pls confirm.

**Comment by mykola-mokhnach** [comment]
UIA2 driver itself (and all the other driver types) has nothing to do with chained locators - it's pure high-level java client's page object's extension implementation. It could be UIA2 driver if issue if the particular locator wouldn't have worked as expected/created stacktraces in nodejs code. However, I see no issues there.

**Comment by amedvedjev** [comment]
done :-) - https://github.com/appium/java-client/issues/716
