### ISSUE TITLE
iOS Simulators created by appium should be cleaned up

### ISSUE THREAD

**Issue by fuzzybinary** [appium/appium#9134]
## The problem

If you do not specify a simulator udid, but do specify a platform and device name, appium creates it's own isolated simulator of the correct type named "appiumTest-<sessionId>". 👍 

However, after these tests are completed, this simulator really should be deleted from the list of simulators, as the session is now closed and that simulator is unlikely to be reused.  Otherwise it just creates clutter in the test environment.

## Environment

* Appium version: v1.7.0-beta, appium-XCUITest-driver 2.47.0, node-simctl 3.10.0
* macOS Sierra
* iOS Simulator, all versions
* Appium CLI

**Comment by fuzzybinary** [comment]
I can start looking into a fix for this and submit a PR if desired.

**Comment by fuzzybinary** [comment]
Additional info: It looks like cleanup does happen in the case that noReset is not set. However, if noReset is set, the next session created will not be able to find the simulator from the previous run, kill it, and not clean up after itself.

This is a bigger issue with how simulators are created and reused between sessions in the case "noReset" is set, which I'm also looking into.

**Comment by mykola-mokhnach** [comment]
I assume this is more client issue, because the idea of noReset option itself is to keep the device. So there is no reason not to use a device, that already exists in the system, taking into account that device creation and deletion takes additional time.

**Comment by mykola-mokhnach** [comment]
also, it is possible to set the _udid_ capability to _auto_ in the recent beta to avoid new simulator device from being created for the given platform version and device name if it does not exist.

**Comment by fuzzybinary** [comment]
Setting to auto doesn't fisx the problem if the simulator isn't already running.  It turns out a second precursor to the issue is not having platformVersion set.

 Desired functionality is

- Don't set platformVersion (have it detected automatically)
- Don't set a udid (auto would also be fine)
- Set noReset
- Set deviceName (to, say, iPhone 6)
- Don't have a simulator currently running
- Launch a test 
-- boot the iPhone 6 simulator, 
-- run the test, leave the simulator running, 
-- start the next test, have it reuse the running simulator

This works with the attached PR.
