### ISSUE TITLE
iOS 11 Allow access location popup

### ISSUE THREAD

**Issue by a-pikachu** [appium/appium#9142]
## The problem

In iOS 11 beta 8, the location popup has the default changed to "Don't Allow", in our test app we do need location service. Our current code will dismiss the popup by click on the default "Don't Allow" which will break our test.

The code we use:
AppiumDriver m_driver;
m_driver.switchTo().alert().accept();

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.6-beta.4
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS 10.12.6
* Node.js version (unless using Appium.app|exe): 6.11.2
* Mobile platform/version under test: iOS 11 beta 8
* Real device or emulator/simulator: ipad mini 4
* Appium CLI or Appium.app|exe: CLI

**Comment by mykola-mokhnach** [comment]
is it not possible to change _accept_ to _dismiss_?

**Comment by a-pikachu** [comment]
Tried, permission not granted.

**Comment by rajfidel** [comment]
Pretty sure that using Xpath will work. (At least works on iOS 10.x) for any alert button.

`driver.findElement(By.Xpath(@"//XCUIElementTypeAlert//XCUIElementTypeButton[@name='Allow']")).click()`

**Comment by mykola-mokhnach** [comment]
You can also use the "mobile: alert" endpoint to click the particular alert button. Please check https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios-xctest-mobile-gestures.md.

BTW, try to avoid xpath usage, since it's slow with XCTest.

**Comment by rajfidel** [comment]
Can confirm that 'mobile: alert' endpoint works to click iOS 11 alert buttons.

**Comment by mykola-mokhnach** [comment]
Closing the issue. @a-pikachu Please comment it out if it still doesn't work for you.

**Comment by vikramvi** [comment]
@mykola-mokhnach can you please share sample java code to "mobile: alert"  tap on iOS 11.0

**Comment by vikramvi** [comment]
@mykola-mokhnach  re-posting below query for benefits of others who may land here from google search )

I could get it working as below, but first checkpoint which confirms if alert dialog is present takes quite long because of xpath on iOS 11.0 I guess ( from your other post answers )
How can I make it faster ? 

```
if(getDriver().findElements(By.xpath("//XCUIElementTypeAlert[contains(@name,'access your location while you are using the app')]")).size()  ) {
                JavascriptExecutor js = (JavascriptExecutor) getDriver();
                HashMap<String, String> tapObject = new HashMap<String, String>();
                tapObject.put("action", "accept");
                tapObject.put("label", "Allow");
                js.executeScript("mobile:alert", tapObject);
              }
```

**Comment by mykola-mokhnach** [comment]
the faster solution would be to just enclose `executeScript` try try/catch block. and ignore an exception if there is no alert.

**Comment by rajfidel** [comment]
@vikramvi To replace xpath search that is slow,
`MobileBy.XPath("//XCUIElementTypeAlert'")`
 you could use ios ns predicates 
`MobileBy.IosNSPredicate("wdType == 'XCUIElementTypeAlert'")`
or use ios class chain.

**Comment by Gnanaraj-S** [comment]
I had the same issue with iOS 10 & 11.

In iOS 10 - I can get it done using driver.switchTo().alert().accept();
In iOS 11 - The same works. Along with that just inspecting the element using @iOSFindBy annotation for "Allow" and clicking on it also works.

**Comment by grpratap69** [comment]
Hi..I am facing plenty of issues while locating elements using xpath for Table view list..is there any way to store all the data of the list in table view with unique accessibility id?

**Comment by GnanarajS** [comment]
Yes it is possible.

 @AndroidFindBys(id = "YOUR_ID")
    private List<MobileElement> variable_name;

**Comment by grpratap69** [comment]
We don't have a unique id for list entries...suppose if i have 3 entries in list then id for each of them is its name only so can't fetch entire list data with 1 id ..

**Comment by risinek** [comment]
just updating broken link that Mykola posted before with `mobile: alert`.. https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios/ios-xctest-mobile-gestures.md

**Comment by grpratap69** [comment]
Hi....wait statements are not working in my scripts....tried using
different version of selenium java jars...any suggestions?

here is my pom


<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="
http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
http://maven.apache.org/xsd/maven-4.0.0.xsd">
<modelVersion>4.0.0</modelVersion>
<groupId>com.TravelBook</groupId>
<artifactId>TravelBook</artifactId>
<version>0.0.1-SNAPSHOT</version>

<dependencies>

<dependency>
<groupId>com.google.guava</groupId>
<artifactId>guava</artifactId>
<version>21.0</version>
</dependency>


<dependency>
<groupId>org.testng</groupId>
<artifactId>testng</artifactId>
<version>6.14.3</version>
</dependency>

<dependency>
<groupId>org.seleniumhq.selenium</groupId>
<artifactId>selenium-support</artifactId>
<version>2.53.0</version>
</dependency>

<dependency>
<groupId>org.seleniumhq.selenium</groupId>
<artifactId>selenium-server</artifactId>
<version>2.53.0</version>
</dependency>

<dependency>
<groupId>org.seleniumhq.selenium</groupId>
<artifactId>selenium-java</artifactId>
<version>2.53.0</version>
</dependency>





<dependency>
<groupId>io.appium</groupId>
<artifactId>java-client</artifactId>
<version>3.3.0</version>
</dependency>


<dependency>
<groupId>org.apache.poi</groupId>
<artifactId>poi</artifactId>
<version>3.11</version>
</dependency>


<dependency>
<groupId>org.apache.poi</groupId>
<artifactId>poi-ooxml</artifactId>
<version>3.11</version>
</dependency>

<dependency>
<groupId>commons-io</groupId>
<artifactId>commons-io</artifactId>
<version>2.6</version>
</dependency>

<dependency>
<groupId>com.relevantcodes</groupId>
<artifactId>extentreports</artifactId>
<version>2.41.2</version>
</dependency>
<dependency>
<groupId>com.googlecode.json-simple</groupId>
<artifactId>json-simple</artifactId>
<version>1.1</version>
</dependency>
<dependency>
<groupId>org.hamcrest</groupId>
<artifactId>hamcrest-all</artifactId>
<version>1.3</version>
<scope>test</scope>
</dependency>
</dependencies>

<build>
<plugins>
<plugin>
<groupId>org.apache.maven.plugins</groupId>
<artifactId>maven-compiler-plugin</artifactId>
<version>3.7.0</version>
<configuration>
<source>1.8</source>
<target>1.8</target>
<encoding>UTF-8</encoding>
</configuration>
</plugin>
<plugin>
<groupId>org.apache.maven.plugins</groupId>
<artifactId>maven-surefire-plugin</artifactId>
<version>2.19</version>
<configuration>
<suiteXmlFiles>
<suiteXmlFile>testng.xml</suiteXmlFile>
</suiteXmlFiles>
</configuration>
</plugin>
</plugins>
</build>

</project>

**Comment by grpratap69** [comment]
Hi all.....In ios i am unable to get screen attributes through appium for map view and list view integrated with it ...able to get all the other screenshots......any reason why?

**Comment by risinek** [comment]
@grpratap69 How are your questions related to this thread?

**Comment by kenny-evitt** [comment]
@vikramvi @mykola-mokhnach Would either of you, or anyone else, mind deleting the unrelated comments on this issue (or moving them to another issue) please?

**Comment by alexbuicescu** [comment]
I'm on appium@1.15.0-rc.5 and `autoAcceptAlerts` is still clicking the `Don't Allow` button in the alert for the location permission. And I don't think it's supposed to work this way. Also, I believed that `locationServicesAuthorized` (together with `bundleId`) would make the alert not to appear in the first place. In the meantime I've come up with the following workaround (I'm calling this method at the start of my tests) (this is for webdriverio):
```javascript
// try once a second to accept the alert, if time exceeds the `timeout`, throw an error if `exitSilently` is true
// if `exitSilently` is false then return whether the alert was closed successfully
export async function acceptLocationPermission(driver, timeout = 20e3, exitSilently = true) {
    for (let i = 0; i < timeout / 1e3; i++) {
        try{
            const text = await driver.getAlertText();
            // change this to whatever your alert text says [1]
            if (text.startsWith('Allow “') && text.endsWith('” to access your location?\nApp requires background tracking')) {
                // find more about 'mobile: alert' here
                // https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios/ios-xctest-mobile-gestures.md
                await driver.executeScript('mobile: alert', [{'action': 'accept', 'buttonLabel': 'Always Allow'}]);

                // alert closed successfully
                return true;
            }
        }catch (e) {
            // getAlertText() is throwing an Error if there is no alert visible
        }
        await sleep(1e3);
    }

    if (exitSilently) {
        // if we closed the alert, then we would already have exited the function, so if we got
        // here then we could not close it
        return false;
    }
    throw new Error('LOCATION_PERMISSION_NOT_FOUND');
}
```
[1] You should change the condition for the alert with what message appears in your alert. In my case the alert had the text:
```
Allow “My-App-Name” to access your location?
App requires background tracking
```

**Comment by mykola-mokhnach** [comment]
@alexbuicescu Unfortunately we cannot rely on button names while accepting alerts, since these might be localized or have custom texts. The current logic assumes that Accept button is always  the first one and the Reject button is always the last one. Although, for the particular location permission alert they are, probably, deliberately exchanged in order to avoid unintentional permissions sharing.
Also the accessibility layer does not provide any hints about which button is doing what. As a universal solution I was thinking about a setting, which allows to set custom text for accept/reject button hints. Please let us know if you have any better ideas

**Comment by alexbuicescu** [comment]
@mykola-mokhnach I haven't seen an alert such as the location alert until now (with 3 buttons), and the rest of the alerts are handled perfectly fine by the current appium solution. So I was thinking that the location alert could be handled separately, in order to not overcomplicate the code.

I think that one problem would be to identify the alert in the first place, because we can't rely on text alone, as it would be a nightmare to identify it for every language (maybe there is some hint that apple applies to their alerts?). I think this would also be a problem with the "button hints" you suggested.

**Comment by mykola-mokhnach** [comment]
> maybe there is some hint that apple applies to their alerts?

I would be happy if they had. Maybe you know something that we don't know? :)

> I think this would also be a problem with the "button hints" you suggested.

Yes, it's ugly, but I don't see a possibility to make it better yet

**Comment by mykola-mokhnach** [comment]
I would say https://github.com/appium/WebDriverAgent/pull/240/ is the best we could do for now
