### ISSUE TITLE
Not able to click Button at the bottom of the screen

### ISSUE THREAD

**Issue by CharanpreetHora** [appium/appium#9144]
## The problem
Not able to click Button at the bottom of the screen. This is working fine in s5 Android 5.0. It seems like some action is getting performed. But nothing is happening. Am not sure but I think while clicking button bottom controls comes into picture automatically.

## Environment

Appium 1.6.5
Andorid 7.0
Mobile - Samsung s8

## Details
I tried various methods mentioned below:-
String sp_Booknowbutton = "//android.view.View[contains(@content-desc,'BOOK NOW')]";
1)
AppDriver.FindElementByXPath(sp_Booknowbutton).Click();

2)
seleniumUtils.swipeDown();
TouchAction Action = new TouchAction(AppDriver);
Action.Tap(AppDriver.FindElementByXPath(sp_Booknowbutton)).Perform();

Need your quick input.

Thanks.

**Comment by CharanpreetHora** [comment]
Can someone help me on this?

**Comment by mykola-mokhnach** [comment]
If this button is not visible then it is necessary to scroll down to make it visible first and only then perform the click

**Comment by CharanpreetHora** [comment]
It is visible and if you see above I am already calling scroll function. Still not working. :-(

**Comment by mykola-mokhnach** [comment]
Try to calculate button coordinates and perform tap by coordinates

**Comment by CharanpreetHora** [comment]
This can be closed now as I have locked phone controls at bottom and now I am able to click button. :-)
