### ISSUE TITLE
After click on Permissions allow button for photos scripts is unable to perform further execution

### ISSUE THREAD

**Issue by CharanpreetHora** [appium/appium#9145]
## The problem
After click on Permissions allow button for photos scripts is unable to perform further execution

## Environment

Appium 1.6.5
Android 7.0
Samsung s8

## Details

AppDriver.FindElementByXPath(cf_NoAvtarImage).Click();
                    if (isElementPresent(By.XPath(cf_allowButton), 2))
                    {
                        AppDriver.FindElementByXPath(cf_allowButton).Click();
                        Thread.Sleep(1000);
                        AppDriver.FindElementByXPath(cf_allowButton).Click();
                        Thread.Sleep(3000);
                        int count = 0;
                        do
                        {
                            seleniumUtils.swipeDown();
                            count++;
                        }
                        while (!seleniumUtils.isElementPresent(By.XPath(cf_NoAvtarImage), 2) && count < 3);

                        **_AppDriver.FindElementByXPath(cf_NoAvtarImage).Click();_**
                        
                    }

In above code snippet after click on system generated pop ups, again clicking on same element, is not working. Basically Appium doesnot identify the App objects.

Kindly help me with the issue.

Thanks

**Comment by CharanpreetHora** [comment]
Can someone help me on this?

**Comment by mykola-mokhnach** [comment]
This can be a known issue if you use UIAutomator1. Switch to UIAutomator2 then

**Comment by CharanpreetHora** [comment]
I am not getting you. WHat is the role of uiautomator here. I am able to identify objects and perform action. Now I have used following code. still this is not working for 2nd time.
 AppDriver.FindElementByXPath(cf_NoAvtarImage).Click();
                    while (AppDriver.FindElement(MobileBy.XPath(cf_allowButton)).Displayed)
                    {
                        AppDriver.FindElement(MobileBy.XPath(cf_allowButton)).Click();
                    }
                    AppDriver.FindElementByXPath(cf_NoAvtarImage).Click();

Not sure why Avtar image is not clicked 2nd time. Please suggest something as this is a blocker for me. 

Thanks.

**Comment by mykola-mokhnach** [comment]
UIA1 is quite old framework and it is not supported by Google for quite a long time. So there will be more and more problems with it in newer Android versions. Also, if you look through previous issue reports, there is a known UIA issue about unexpected freeze after alert popup is accepted. It might be the same problem.

**Comment by CharanpreetHora** [comment]
I am providing following capability:-
<capability name="automationName" value="uiautomator2"/>
Thanks very much mykola. It resolved my issue.

**Comment by CharanpreetHora** [comment]
capability name "automationName"
value = "uiautomator2"
