### ISSUE TITLE
iOS 10 - real device - socket hang up/Error connecting to device

### ISSUE THREAD

**Issue by LukasLewandowski** [appium/appium#9150]
## The problem

I have two tests that are crashing during the test run, only on real device iPad with iOS 10.3.3.
It is happening on different actions in each test case but always on the same step in a single test case. During the test execution, for some reason tested mobile app is going to background and Appium log is showing some problem with connection to the device.

## Environment

* Appium 1.6.5
* OSX 10.12.5
* Node.js version: 6.10.1
* Mobile platform/version under test: iOS 10.3.3 iPad
* Real device iPad
* Appium CLI or Appium.app|exe: CLI
* Language: Python

## Details
I am using switch context to access webview in mobile app. I already tried different caps, restarting the device, reinstalling WDA and the app. Also when I skip problematic step in test case, test will fail with the same error on the next step. 

The same tests are running without any issue on other devices and simulators, for example on iOS 10.3.3 iPhone 6, iOS 10.3 iPhone 7 simulator, Android 7.0 - Samsung Galaxy S7

My cabs:

        "IOS_10_iPad": {
            # iPad with iOS 10.3.3
            "platformName": "iOS",
            "platformVersion": "10.3.3",
            "deviceName": "iPad 2048x1536",
            "app": os.path.join(PROJECT_ROOT, "OCA-iOS-10.3.app"),  # path to .app file
            "bundleId": "",
            "xcodeOrgId": "",  # 10 characters string generated by Apple
            "xcodeSigningId": "iPhone Developer",
            # "usePrebuiltWDA": True,  # Skips the build phase of running the WDA app
            "useNewWDA": False,  # If True, forces uninstall of any existing WebDriverAgent app on device
            "preventWDAAttachments": True,  # capability to help with XCUITest speed and disk usage
            "automationName": "XCUITest",
            "clearSystemFiles": True,
            "startIWDP": True,  # start ios-webkit-debug-proxy
            # "maxTypingFrequency": 5,
            # "webkitResponseTimeout": 500,  # seconds, milliseconds ?
            "showXcodeLog": True,
            "noReset": False,
            "fullReset": False,
            "enableAsyncExecuteFromHttps": True,
            # "realDeviceLogger": "/usr/local/lib/node_modules/deviceconsole/deviceconsole",
            "realDeviceLogger": "idevicesyslog, /usr/local/lib/node_modules/deviceconsole/deviceconsole",
            "shouldUseSingletonTestManager": False,  # Use default proxy for test management within WebDriverAgent. Setting this to false sometimes helps with socket hangup problems.
            # "autoAcceptAlerts": True,  # not working for XCUIT
            "udid": ""
        },

## Link to Appium logs
https://gist.github.com/LukasLewandowski/5f1c45254e9229dbe2cfba404d58e34c

Appium logs with Xcode log, from different TC:
https://gist.github.com/LukasLewandowski/03a4296f1ae040d233fc8110b421e3ae

Appium log file with iOS device logs:
[appium_log3.txt](https://github.com/appium/appium/files/1270021/appium_log3.txt)

**Comment by mykola-mokhnach** [comment]
I assume you need to set **startIWDP** capability to _true_ if you want to access a webview on real devices.

**Comment by LukasLewandowski** [comment]
Yep, as You can see in my caps, I already have that set to True :), also I would like to add that the same tests are running without any issue on other devices and simulators, for example on iOS 10.3.3 iPhone 6, iOS 10.3 iPhone 7 simulator, Android 7.0 - Samsung Galaxy S7.

**Comment by LukasLewandowski** [comment]
Could You tell me what are You looking for in device log? :)

**Comment by mykola-mokhnach** [comment]
From the log I see that WDA crashed and it was the reason why iproxy was not able to reconnect to the device. The real reason of the crash is unknown to me. It might be this one:

> 2017-09-01 10:41:30:161 - info: [iOSLog] [IOS_SYSLOG_ROW] Sep  1 12:41:30 iPad-2048x1536 OCA(UIAccessibility)[649] <Error>: This child can't be serialized correctly: <AXUIElement 0x1740b97a0> {pid=649}

but might be something else as well. Unfortunately there is nothing we can do on Appium side to workaround that. It's most likely some internal XCTest issue, which is not easy to debug at all.

**Comment by mykola-mokhnach** [comment]
You can also try there recent Appium beta release - it might be the stuff works better with it.

**Comment by LukasLewandowski** [comment]
Thx for looking into this :)
