### ISSUE TITLE
Try to click 5 time at the same coordinate

### ISSUE THREAD

**Issue by AlwineS** [appium/appium#9151]
I Try to click or tap 5 times on the same coordinate. But it seemes to be to slow.
My First example:
webdriver.execute_script("mobile: tap", {"tapCount": 5.0, "duration":0.0, "x":coordinate_x, "y":coordinate_y})
This takes nearly 2 seconds for the run. If i would set tapCount to 20 or 40 ... it also takes nearly 2 seconds to run.

My Second example was to run the execute_script mit tapCount of 2.0 but 3 times but behind another
This takes for every call 2 seconds --> total nearly 6 Seconds.

Is there any possibility to click a coordinate at the screen very quick? 

For Android Real Device it works with this code: Content is not realy a element like a button, but it is the element witch contains all of the other elements (like Main-Window)
        for _ in range(0, 6):
            action.tap(self.content, coordinate_x, coordinate_y).perform() 

## Environment
* Device: Reald Device iPhone 5 with iOS 10
* Device is connected to AppleMini and run Appium Desktop for mac 1.2.0 beta3: 
* Appium server version -> 1.6.5
* Appium version (python)-> Appium-Python-Client = (0.24)

**Comment by mykola-mokhnach** [comment]
tapCount argument is not supported for this endpoint like you expect it to work. Simply call it in a loop instead:

```python
for _ in xrange(5):
    webdriver.execute_script("mobile: tap", {"x":coordinate_x, "y":coordinate_y})
```

**Comment by mykola-mokhnach** [comment]
regarding slowness - the click is done on XCTest side, so there is nothing we can do in Appium to make ti faster
