### ISSUE TITLE
Reason: 'simctl error running 'create': Invalid runtime: 10.3

### ISSUE THREAD

**Issue by bbaitikova** [appium/appium#9153]
## The problem

Not able to launch test with IOS platform 

* Appium version (or git revision) that exhibits the issue: Version 1.2.0-beta.1 (1.2.0-beta.1)
* Last Appium version that did not exhibit the issue (if applicable): n/a
* Desktop OS/version used to run Appium: Version 1.2.0-beta.1 (1.2.0-beta.1)
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: IOS 11 and ios 10.3
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe:
*xcode: v8 and v9 beta

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/bbaitikova/eb34306fb0810ae44c5b16768ac147aa

## Code To Reproduce Issue [ Good To Have ]
`
class SetUpiOS(unittest.TestCase):

    mobile_app_md = "/Users/bbaitikova/Downloads/test.ipa"
   

    def setUp(self):
        desired_caps = {
            'platformName': 'iOS',
            'platformVersion\n': "11",
            'deviceName': 'iPhone 7',
            'automationName': 'XCUITest',
            'app': self.mobile_app_md,
            'newCommandTimeout': 180,
            "autoGrantPermissions": True,
            # 'no-reset': False,
            'full-reset': True
        }

        self.driver = webdriver.Remote('http://127.0.0.1:4723/wd/hub', desired_caps)
        self.driver.implicitly_wait(100)

    def test_home(self):
        windows_size = self.driver.get_window_size()
        print windows_size

    def tearDown(self):
        self.driver.quit()

if __name__ == "__main__":
    unittest.main(verbosity=2)`

**Comment by rajfidel** [comment]
You need Xcode 9 beta to be able to use Appium with iOS 11. Xcode 8.3.3 only supports up to 10.3.x. If you already have the Xcode 9 beta installed on your mac, go to your Xcode preferences, and select the Command Line Tools to "Xcode 9.0' under the Locations tab. Also, you have Appium 1.6.5. I would recommend that you install the latest Appium 1.6.6 beta.4.

**Comment by bbaitikova** [comment]
Thanks for reply. 

Looks like Appium does not support Xcode 9 yet.  i have error "Original error: Xcode version 9.0 is not yet supported". 

When will Appium start supporting xcode 9?

**Comment by saikrishna321** [comment]
Appium does support iOS11 with Xcode 9 beta with latest Appium beta. Try below 
npm uninstall -g appium && npm install -g appium@beta 

You should the latest 1.7.0.beta

**Comment by Akulavenkatesh** [comment]
@bbaitikova Work around for this - we can inspect elements on Xcode 9 + iOS 11 using Appium Version 1.5.3 (Ara), check the below video

[Solved] Appium Error - Xcode version 9.0 is not yet supported
https://www.youtube.com/watch?v=mGpfjbPsO20
