### ISSUE TITLE
Mobile testing with appium/Android - buttion click not working since page is not correctly loading with appium

### ISSUE THREAD

**Issue by Sanjeewahsp** [appium/appium#9154]
## The problem
step1.
When I open "my profile page" through appium new session, the "edit profile" button is not loaded. so you can't move to edit page from tap it. when you tap it, it is trying to move edit page. But not moving. please see step1 image and logs

<img width="960" alt="step1" src="https://user-images.githubusercontent.com/31409058/29989578-d6d0b802-8f6b-11e7-86cd-0e9842d12cd5.png">
[step1.txt](https://github.com/appium/appium/files/1271636/step1.txt)

step2.
Then I move to "edit page" with finger click on the device. again come back to "my profile page" and "Refresh source and screen shot" on the appium window. Now I can see the "edit buttion" there(with different colour). Now I can tap it. it is moving to edit page. see the image and logs.
<img width="960" alt="step2" src="https://user-images.githubusercontent.com/31409058/29989676-641bcfa8-8f6c-11e7-83ca-60a4a614f077.png">
[step2.txt](https://github.com/appium/appium/files/1271641/step2.txt)
<img width="960" alt="step2b" src="https://user-images.githubusercontent.com/31409058/29989691-7fa4b69a-8f6c-11e7-9f49-8c35b4d90d56.png">

Same thing is happening from my selenium test, Sometime this "Edit Profile" buttion is working. Sometime not.
In the other pages also button click and .sendKeys() methods are not working consistency. Some time working sometime not. I checked my application manually on the device. There is no any issues in the app pages. I believe that appium is not properly reading these pages.

## Environment

* Appium version (or git revision) that exhibits the issue: appiumv1.6.5 desktop
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: windows 10
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: 
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:

## code
File appDir = new File("D:\\sdk-tools-windows-3859397");
            File app = new File(appDir, "Faber.apk");
            DesiredCapabilities capabilities = new DesiredCapabilities();
            capabilities.setCapability(MobileCapabilityType.BROWSER_NAME, "Android");
            capabilities.setCapability(MobileCapabilityType.PLATFORM, Platform.ANDROID);
            capabilities.setCapability("platformName", Platform.ANDROID);
            capabilities.setCapability("deviceName", "CC524Y401167");
            capabilities.setCapability("app", app.getAbsolutePath());
            capabilities.setCapability("appPackage", "com.faber.worker");
            capabilities.setCapability("appActivity", "com.faber.worker.MainActivity");
            capabilities.setCapability("autoAcceptAlerts", true);
            capabilities.setCapability("unicodeKeyboard", true);
            capabilities.setCapability("resetKeyboard", true);
            driver  =  new AppiumDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);

**Comment by mykola-mokhnach** [comment]
Try UIAutomation2 as the backend

**Comment by Sanjeewahsp** [comment]
{
  "platformName": "Android",
  "deviceName": "CC524Y401167",
  "app": "D:\\sdk-tools-windows-3859397\\Faber.apk",
  "appPackage": "com.faber.worker",
  "appActivity": "com.faber.worker.MainActivity",
  "automationName": "uiautomator2"
}
I have set as above in the appium new session and tried to load my app through appium session inspector.
This time even the login page is not properly loaded. when I click on the screen Ican't see or select any text field. only one yellow layer is there. I can't select text fields or login button. see image 1

Then  I have refreshed couple of times. Then only I can see username,password text fields as different colour(blue ). When I clicked "sendKeys" with giving username it gave null pointer exception.
Please see the images and log
<img width="960" alt="image1" src="https://user-images.githubusercontent.com/31409058/30039889-1b6511e2-91cf-11e7-981d-e86720c3cab3.png">
<img width="960" alt="image2" src="https://user-images.githubusercontent.com/31409058/30039892-206c8800-91cf-11e7-8937-87ff8a52be25.png">
<img width="960" alt="image3" src="https://user-images.githubusercontent.com/31409058/30039897-24b6dec4-91cf-11e7-8772-c482cc07f880.png">
[appium-server-logs.txt](https://github.com/appium/appium/files/1275632/appium-server-logs.txt)

**Comment by mykola-mokhnach** [comment]
Appium inspector does not work properly if one tries to interact with webviews, because it is in the native context by default.
You need to wrote some testing code first and switch the context to webview. Only after that it will be possible to properly work with elements hierarchy.

**Comment by mykola-mokhnach** [comment]
@dpgraham please correct me if I'm wrong

**Comment by dpgraham** [comment]
That's correct @mykola-mokhnach.
