### ISSUE TITLE
refresh command broken in python client

### ISSUE THREAD

**Issue by jashsu** [appium/appium#9155]
## The problem

I cannot call driver.refresh() to refresh the page hierarchy.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5 from appium-desktop-1.2.0-beta.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Ubuntu 16.04.2 LTS
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Android 7.1.1
* Real device or emulator/simulator: Nexus 5X
* Appium CLI or Appium.app|exe: Appium Desktop

## Details

.>>> type(driver)
<class 'appium.webdriver.webdriver.WebDriver'>
.>>> 'refresh' in dir(driver)
True
.>>> driver.refresh()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 692, in refresh
    self.execute(Command.REFRESH)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 297, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/appium/webdriver/errorhandler.py", line 29, in check_response
    raise wde
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: 404 - undefined

.>>>

## Link to Appium logs

https://gist.github.com/jashsu/88c53688c0d12285cdae5313b5859e38

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
The refresh command does not work in native context. This is by design, since it has no sense in mobile context.
What are you trying to do with it?

**Comment by jashsu** [comment]
Was looking for a way to refresh the page hierarchy in appium from python (analogous to pressing the reload button in the Appium Desktop Inspector. I worked around it by sending the same command directly:

requests.get('http://localhost:4723/wd/hub/session/{}/source'.format(driver.session_id))

I believe in other bindings there is a .getPageSource() function but I don't see that in python.

**Comment by mykola-mokhnach** [comment]
I believe it's called get_page_source.

**Comment by jashsu** [comment]
Nope.

```
>>> 'get_page_source' in dir(driver)
False
>>> driver.get_page_source()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'WebDriver' object has no attribute 'get_page_source'
```

**Comment by mykola-mokhnach** [comment]
Try the _page_source_ property:
http://selenium-python.readthedocs.io/api.html?highlight=source#selenium.webdriver.remote.webdriver.WebDriver.page_source
