### ISSUE TITLE
Not able to start web driver agent session in ios simulator

### ISSUE THREAD

**Issue by Aditya1209** [appium/appium#9156]
## The problem

i am want to execute my scripts in iPhone simulator. when i start execution WDA agent session is not creating.Keep on retrying to create WDA session. i have installed all required dependencies as per mentioned in appium-xcuitest-driver docs. When i start execution iPhone simulator is launching and web driver agent is creating in simulator after that in appium server its showing failed to create WDA session. 

query 1: is it mandatory to sign in  with valid apple developer account in xcode project webdriveragent ? if yes woth out this can't we proceed further for execution.

## Environment

* Appium version (or git revision) that exhibits the issue: appium v1.6.0-beta2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: appium v1.6.0-beta2
* Node.js version (unless using Appium.app|exe):v6.11.2
* Mobile platform/version under test:
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: appium CLI and appium.app same issue in both
*mac os version : macOS SIerra V 10.12.6

## Link to Appium logs
[Appium] Welcome to Appium v1.6.0-beta2
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"automationName":"XCUITest","browserName":"Safari","platformName":"iOS","udid":"7BF56004-173B-4F65-B854-4DB4B5BB4BBC","deviceName":"iPhone 6s"},"requiredCapabilities":{},"capabilities":{"desiredCapabilities":{"automationName":"XCUITest","browserName":"Safari","platformName":"iOS","udid":"7BF56004-173B-4F65-B854-4DB4B5BB4BBC","deviceName":"iPhone 6s"},"requiredCapabilities":{}},"alwaysMatch":{"automationName":"XCUITest","browserName":"Safari","platformName":"iOS","udid":"7BF56004-173B-4F65-B854-4DB4B5BB4BBC","deviceName":"iPhone 6s"},"firstMatch":[]}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"automationName":"XCUITest","browserName":"Safari","platformName":"iOS","udid":"7BF56004-173B-4F65-B854-4DB4B5BB4BBC","deviceName":"iPhone 6s"},{},{"desiredCapabilities":{"automationName":"XCUITest","browserName":"Safari","platformName":"iOS","udid":"7BF56004-173B-4F65-B854-4DB4B5BB4BBC","deviceName":"iPhone 6s"},"requiredCapabilities":{}}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1504335267583 (12:24:27 GMT+0530 (IST))
[Appium] Creating new XCUITestDriver session
[Appium] Capabilities:
[Appium]   automationName: 'XCUITest'
[Appium]   browserName: 'Safari'
[Appium]   platformName: 'iOS'
[Appium]   udid: '7BF56004-173B-4F65-B854-4DB4B5BB4BBC'
[Appium]   deviceName: 'iPhone 6s'
[BaseDriver] Session created with session id: 65a7825b-e004-4a5c-b14d-00c293ae466a
[debug] [XCUITest] Xcode version set to '8.3.2' (tools v8.3.2.0.1.1492020469)
[debug] [XCUITest] iOS SDK Version set to '10.3'
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1504335267665 (12:24:27 GMT+0530 (IST))
[iOSSim] Constructing iOS simulator for Xcode version 8.3.2 with udid '7BF56004-173B-4F65-B854-4DB4B5BB4BBC'
[XCUITest] Determining device to run tests on: udid: '7BF56004-173B-4F65-B854-4DB4B5BB4BBC', real device: false
[XCUITest] No platformVersion specified. Using device version: '10.3'
[XCUITest] Safari test requested
[debug] [BaseDriver] Event 'appConfigured' logged at 1504335267824 (12:24:27 GMT+0530 (IST))
[debug] [BaseDriver] Event 'resetStarted' logged at 1504335267824 (12:24:27 GMT+0530 (IST))
[simctl] Error: simctl error running 'terminate': An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=53):
Error returned in reply: Connection interrupted
Software caused connection abort
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at simCommand$ (../../lib/simctl.js:29:11)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:109:7)
 Error: simctl error running 'terminate': An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=53):
Error returned in reply: Connection interrupted
Software caused connection abort
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at simCommand$ (../../lib/simctl.js:29:11)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:109:7)
[debug] [iOSSim] Cleaning mobile safari data files
[debug] [iOSSim] Checking whether simulator has been run before
[debug] [iOSSim] Simulator has been run before
[debug] [iOSSim] Checking whether simulator has been run before
[debug] [iOSSim] Simulator has been run before
[debug] [iOSSim] Building bundle path map
[debug] [BaseDriver] Event 'resetComplete' logged at 1504335268015 (12:24:28 GMT+0530 (IST))
[debug] [iOSLog] Starting iOS 10.3 simulator log capture
[debug] [iOSLog] System log path: /Users/MACUSER/Library/Logs/CoreSimulator/7BF56004-173B-4F65-B854-4DB4B5BB4BBC/system.log
[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1504335268029 (12:24:28 GMT+0530 (IST))
[XCUITest] Setting up simulator
[debug] [iOS] No reason to set locale
[debug] [iOS] No iOS / app preferences to set
[debug] [iOSSim] The count of running Simulator UI client instances is 0
[debug] [iOSSim] Killing all iOS Simulators
[debug] [iOSSim] Simulator is not running. Continuing...
[iOSSim] Starting Simulator UI with command: open -Fn /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app --args -CurrentDeviceUDID 7BF56004-173B-4F65-B854-4DB4B5BB4BBC -ConnectHardwareKeyboard 0
[debug] [iOSSim] The count of running Simulator UI client instances is 1
[iOSSim] Simulator with UDID 7BF56004-173B-4F65-B854-4DB4B5BB4BBC booted in 13 seconds
[debug] [BaseDriver] Event 'simStarted' logged at 1504335281298 (12:24:41 GMT+0530 (IST))
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[debug] [XCUITest] Capability 'useNewWDA' set to false, so trying to reuse currently running WDA instance at 'http://localhost:8100/'
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [XCUITest] WDA is not listening at 'http://localhost:8100/'. Rebuilding...
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1504335284373 (12:24:44 GMT+0530 (IST))
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'
[debug] [XCUITest] Killing running processes 'xcodebuild.*7BF56004-173B-4F65-B854-4DB4B5BB4BBC, iproxy 8100 , 7BF56004-173B-4F65-B854-4DB4B5BB4BBC.*XCTRunner' for the device 7BF56004-173B-4F65-B854-4DB4B5BB4BBC...
[debug] [XCUITest] 'pgrep -nif xcodebuild.*7BF56004-173B-4F65-B854-4DB4B5BB4BBC' didn't detect any matching processes. Return code: 1
[debug] [XCUITest] 'pgrep -nif iproxy 8100 ' didn't detect any matching processes. Return code: 1
[debug] [XCUITest] 'pgrep -nif 7BF56004-173B-4F65-B854-4DB4B5BB4BBC.*XCTRunner' didn't detect any matching processes. Return code: 1
[debug] [XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=7BF56004-173B-4F65-B854-4DB4B5BB4BBC IPHONEOS_DEPLOYMENT_TARGET=10.3' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[debug] [XCUITest] Output from xcodebuild will not be logged. To see xcode logging, use 'showXcodeLog' desired capability
[debug] [XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [XCUITest] Log file for xcodebuild test: /Users/MACUSER/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/76E0C584-26C0-46F2-8D60-254F6F0D9723/Session-WebDriverAgentRunner-2017-09-02_122445-CVLu1z.log
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [XCUITest] Unable to connect to running WebDriverAgent: Could not proxy command to remote server. Original error: Error: ETIMEDOUT
[XCUITest] Getting status of WebDriverAgent on device timed out. Continuing
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1504335465910 (12:27:45 GMT+0530 (IST))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [XCUITest] Failed to create WDA session. Retrying...
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1504335542108 (12:29:02 GMT+0530 (IST))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [XCUITest] Failed to create WDA session. Retrying...
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1504335618185 (12:30:18 GMT+0530 (IST))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [XCUITest] Failed to create WDA session. Retrying...
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1504335694267 (12:31:34 GMT+0530 (IST))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [XCUITest] Failed to create WDA session. Retrying...
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1504335770639 (12:32:50 GMT+0530 (IST))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [XCUITest] Failed to create WDA session. Retrying...
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1504335846787 (12:34:06 GMT+0530 (IST))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[HTTP] <-- POST /wd/hub/session - - ms - - 
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"automationName":"XCUITest","browserName":"Safari","platformName":"iOS","udid":"7BF56004-173B-4F65-B854-4DB4B5BB4BBC","deviceName":"iPhone 6s"},"requiredCapabilities":{},"capabilities":{"desiredCapabilities":{"automationName":"XCUITest","browserName":"Safari","platformName":"iOS","udid":"7BF56004-173B-4F65-B854-4DB4B5BB4BBC","deviceName":"iPhone 6s"},"requiredCapabilities":{}},"alwaysMatch":{"automationName":"XCUITest","browserName":"Safari","platformName":"iOS","udid":"7BF56004-173B-4F65-B854-4DB4B5BB4BBC","deviceName":"iPhone 6s"},"firstMatch":[]}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"automationName":"XCUITest","browserName":"Safari","platformName":"iOS","udid":"7BF56004-173B-4F65-B854-4DB4B5BB4BBC","deviceName":"iPhone 6s"},{},{"desiredCapabilities":{"automationName":"XCUITest","browserName":"Safari","platformName":"iOS","udid":"7BF56004-173B-4F65-B854-4DB4B5BB4BBC","deviceName":"iPhone 6s"},"requiredCapabilities":{}}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1504335869587 (12:34:29 GMT+0530 (IST))

**Comment by mykola-mokhnach** [comment]
Please update appium to 1.7.0-beta and try again.

**Comment by Aditya1209** [comment]
tried with 1.7.0-beta. but still same issue.

**Comment by mykola-mokhnach** [comment]
Please attach the updated log.

To me it looks like some internal Simulator issue. see https://stackoverflow.com/questions/43527115/xcode-error-connecting-to-simulator-software-caused-connection-abort for example

**Comment by Aditya1209** [comment]
Hi,
Thanks for the update I will do as mentioned in that blog.
I just want to give you more info about error.I am trying to launch safari browser to execute my web application. when I start execution simulator is launching with the name of appiumTest and webdriver agent is installed, after that in appium console it's sowing failed connecting wda agent.its jeep on repeating trying to connect to wda agent.

**Comment by Aditya1209** [comment]
Hi,

 I followed your suggestions as per https://stackoverflow.com/questions/43527115/xcode-error-connecting-to-simulator-software-caused-connection-abort this. but no luck its giving me same issue.

Thanks,
Aditya

**Comment by Aditya1209** [comment]
Hi,

its giving me belo issue:

Encountered internal error running command: Error: Unable to start WebDriverAgent session because of xcodebuild failure: "Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 10.27.208.100:8100".
    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:380:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by mykola-mokhnach** [comment]
Please attach the full log.

Are you able to start the simulator with given UDID manually?

**Comment by Aditya1209** [comment]
Yes i am able to create simulator manually.

**Comment by ranikp** [comment]
Aditya1209,mykola-mokhnach
could you both look at the issue I have created 
https://github.com/appium/appium/issues/9164
I think you would solve the issue at last for me please

**Comment by IrinaDvorin** [comment]
Hello, I need help!
I get the same issue using:
xCode 9, Appium v1.7.1

my configuration:
  "platformName": "iOS",
  "deviceName": "iPhone 6",
  "app": "Calendar",
  "automationName": "XCUITest",
  "udid": "800a331d8b1e4bf837e9d22882c50a90d646196d",
  "showXcodeLog": "true",
  "platformVersion": "11.0.3",
  "xcodeOrgId": "XXXX",
  "xcodeSigningId": "iPhone Developer",
  "showIOSLog": "false",
  "autoWebview": "true",
  "realDeviceLogger": "/usr/local/lib/node_modules/deviceconsole"

Appium log: [appium-server-logs.txt](https://github.com/appium/appium/files/1397903/appium-server-logs.txt)

**Comment by IrinaDvorin** [comment]
Sure, I advice the log! Nothing in your tutorium doesn't help me. You can explain what is my problem?

**Comment by imurchie** [comment]
I do not know from the logs. Does the WebDriverAgent-Runner run on the device, if you start it manually?

**Comment by IrinaDvorin** [comment]
@imurchie 
1. Running by: xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=800a331d8b1e4bf837e9d22882c50a90d646196d' test

I can not run it through USB port 8100 (I don't know how it will be configured). It runs only through the wi-fi network, but I noticed that he is trying to listen to the port 0, horror that is not accurate! I changed code of WebDriverAgentLib in the place where the port is located to 8100 ( server.port = 8100; /*(UInt16)port;*/). Now it listens correctly and gets the date:
Cellexs-Mac-mini:~ cellexnetworks$ curl -X GET $JSON_HEADER $DEVICE_URL/status
curl: (3) Port number ended with 'a'
{
  "value" : {
    "state" : "success",
    "os" : {
      "name" : "iOS",
      "version" : "11.0.3"
    },
    "ios" : {
      "simulatorVersion" : "11.0.3",
      "ip" : "192.168.200.227"
    },
    "build" : {
      "time" : "Oct 22 2017 13:00:19"
    }
  },
  "sessionId" : "D33B7A8A-2E05-40F3-AD1F-620136FF015A",
  "status" : 0
}

2. I still can't to run it due to Appium app, can you help me???

**Comment by IrinaDvorin** [comment]
Finally I fixed my problem. 
The a few stages to understanding the problem:
1 Need to check WDA correctly installed and responding on the your physical device:
    searching in log  entry part : ServerURLHere  (this appears when the  showIOSLog is on):
RLHere->http://192.168.200.227:8100<-ServerURLHere
2.  Check what is the address, may be it is Wi-Fi connection address? It must be USB connection ip.
   Disable Wi-Fi connection. Run test again
3.  Now browsing to getting URL (http://<IP>:8100/status). Do you receive some thing like device configuration in json format? If yes WDA is correctly installed and responded to you.
4.  Now browsing to http://localhost:8100/status).  No Server Found? Do you need to add localhost configuration to etc/host file. Follow my instruction:
sudo nano /private/etc/hosts add a new line  127.0.0.1 localhost, if it already doesn’t exist. Remark on all other lines containing 127.0.0.1. CTRL + O to save CTRL + X to exit.

I hope my instruction will help someone

**Comment by Aditya1209** [comment]
Hi,

Thank you so much for the solution. Same is working fine for my problem as
well.

Thanks,
Aditya
