### ISSUE TITLE
Unable to launch WebDriverAgent because of xcodebuild failure: spawn EACCES

### ISSUE THREAD

**Issue by alexbuicescu** [appium/appium#9158]
## The problem

**Unable to launch WebDriverAgent because of xcodebuild failure: spawn EACCES** is thrown when I'm running tests on the appium server installed using npm. However, when I start the appium server from Applications/Appium.app my tests work just fine.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5 (both app and cli)
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS 10.12.6
* Node.js version (unless using Appium.app|exe): 5.4.0
* Mobile platform/version under test:  ios 10.3.1
* Real device or emulator/simulator: simulator iPhone 7 Plus
* Appium CLI or Appium.app|exe: both
* Xcode version: 8.3.3 (8E3004b)

## Details
My installation steps:
```bash
brew install carthage
npm install -g appium
npm install -g authorize-ios
sudo authorize-ios
```
requirements.txt:
```
Appium-Python-Client==0.24
pytest==3.2.1
selenium==3.3.1
```
Also, I have automatic code signing in Xcode and Code Signing Identity: iOS Developer 

## Link to Appium logs
when starting from cli: https://gist.github.com/alexbuicescu/0a090fe5d351fb7fbf5d1eff001bd623
when starting from app: https://gist.github.com/alexbuicescu/daf241ee57d7af6e3a26294f9826c1bd

## Code To Reproduce Issue
Start appium server:
```
appium --webdriveragent-port 8100 -bp 4724 --selendroid-port 8080 --port 4723
```
Some relevant python code
```python
from appium import webdriver
import os

app = os.path.abspath('ios/build/Build/Products/Debug-iphonesimulator/yourAppNameHere.app')
self.driver = webdriver.Remote(
    command_executor='http://127.0.0.1:4723/wd/hub',
    desired_capabilities={
        'app': app,
        'platformName': 'iOS',
        'platformVersion': '10.3',
        'deviceName': 'iPhone 7 Plus',
        'autoAcceptAlerts': True,
        'autoGrantPermissions': True,
    }
)
```

**Comment by mykola-mokhnach** [comment]
Did you use sudo to install Appium using npm?

**Comment by alexbuicescu** [comment]
No, I didn't. I just tried right now to do it and I get **EACCES: permission denied** (for ```sudo npm install -g appium```):
```
npm WARN deprecated babel-core@5.8.24: Babel 5 is no longer being maintained. Upgrade to Babel 6.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated line-numbers@0.2.0: Copy its ~20 LOC directly into your code instead.
/usr/local/bin/appium -> /usr/local/lib/node_modules/appium/build/lib/main.js

> appium-chromedriver@2.11.2 install /usr/local/lib/node_modules/appium/node_modules/appium-chromedriver
> node install-npm.js

(node:635) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/201783-635-1w8va9.zxzlv'
(node:635) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
info Chromedriver Install Installing Chromedriver version '2.28' for platform 'mac' and architecture '64'
info Chromedriver Install Opening temp file to write chromedriver_mac64 to...
Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/201783-635-1rqwmo5.v67x'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! appium-chromedriver@2.11.2 install: `node install-npm.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the appium-chromedriver@2.11.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by mykola-mokhnach** [comment]
The thing is that sudo should never be user with it. Try

```
sudo chown -R $USER /usr/local
```

and then install Appium as usually.

**Comment by alexbuicescu** [comment]
It still didn't work (here are some logs https://gist.github.com/alexbuicescu/8d23e334cefffd621da70e0a5b15d476)
What is odd is that now appium closed the specified simulator (iPhone 7 Plus) and opened a different one (iPhone SE - which I never opened or used). Everything still works as expected when I use the Appium.app

**Comment by mykola-mokhnach** [comment]
You need to set platformVersion explicitly. Also make sure you can start the given simulator manually.

**Comment by alexbuicescu** [comment]
Looks like the problem with the wrong simulator was because I started appium using sudo. And looks like the problem is solved. I tested the following:
1. This:

    ```
    sudo chown -R $USER /usr/local
    sudo npm install -g appium
    appium --webdriveragent-port 8100 -bp 4724 --selendroid-port 8080 --port 4723
    ```

1. And this:
    ```
    sudo chown -R $USER /usr/local
    npm install -g appium  # notice the missing of sudo here
    appium --webdriveragent-port 8100 -bp 4724 --selendroid-port 8080 --port 4723
    ```

And both of these worked. So my guess is that ```sudo chown -R $USER /usr/local``` was enough to solve the problem. I'll close this issue and thank you.

**Comment by jamesvanhorn** [comment]
This happened to me on 2 different machines after upgrading appium versions. The fix I found was to uninstall and reinstall node (and appium then). My node installation is managed by Homebrew if that matters. Posting here in case someone else is affected.
