### ISSUE TITLE
iPad Real Device Issue - Cant click on a specific button, user gets invalid selector error

### ISSUE THREAD

**Issue by mirza-ae** [appium/appium#9159]
## The problem

Mouse clicks for a particular button doesnt work for Safari browsers (iPad real device). Appium can detect the element fine, but when it clicks on it, a weird error is thrown. Clicking on the button manually works. This issue cant be replicated on other browsers.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5, 1.6.6-beta.4
* Desktop OS/version used to run Appium: Mac OSX Sierra
* Node.js version (unless using Appium.app|exe): 8.2.1
* Mobile platform/version under test: iOS Safari
* Real device or emulator/simulator: iPad Real device

## Details

1. Access the site, https://www.aetv.com/profile/sign-in?mode=register&referrerUrl=http://www.aetv.com using an iOS Safari browser.
2. Using a locator, click on the 'SIGN UP WITH FACEBOOK' button. 
3. Observe that a weird error is thrown.
Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: -[NSNull doubleValue]: unrecognized selector sent to instance 0x39f9e978

## Link to Appium logs
https://gist.github.com/mirza-ae/3f6990af8320c6393079767e45f92a2f

## Code To Reproduce Issue [ Good To Have ]
`
By xpath = By.xpath("//*[text()='Sign up with Facebook']");
boolean isDisplayed = driver.findElement(xpath).isDisplayed();
boolean isEnabled = driver.findElement(xpath).isEnabled();
int count = driver.findElements(xpath).size();
driver.findElement(xpath).click();
`

**Comment by mykola-mokhnach** [comment]
@imurchie FYI

**Comment by imurchie** [comment]
I think I've figured out the issue. Working on a fix.

**Comment by imurchie** [comment]
My fix did not pan out. There is now some additional logging to try to get more information. Could you try updating to the latest code (`npm uninstall -g appium && npm install -g appium --no-shrinkwrap`) and post the logs? Sorry for the delay and the trouble.

**Comment by mirza-ae** [comment]
Hello Issac,


I will provide an update on Monday.

________________________________

**Comment by mirza-ae** [comment]
@imurchie 

Hello Issac,

The new logs are below:

https://gist.github.com/mirza-ae/e9baca4654ef77238fb0a73816f65813

**Comment by imurchie** [comment]
Sorry for the delay. This is even worse now! It seems like there is no Webview being found.

Can you try exiting to the `NATIVE_APP` context and getting the source, and posting that?

**Comment by mirza-ae** [comment]
@imurchie 

I have no idea how to do that. Can you please provide step by step instructions on how to do so?

**Comment by imurchie** [comment]
I don't know what language you are using to write the tests. Java?
```java
driver.context("NATIVE_APP");
String pageSource = driver.getPageSource();
```

**Comment by mirza-ae** [comment]
I am using Java, yes.

So, you are saying that I should put that block of code before I click on the button?

**Comment by mirza-ae** [comment]
@imurchie 

Hello Issac,

I created the new log as you have requested. It can be found below:

https://gist.github.com/mirza-ae/2e07b755a37796cb516d55d8b8a4d10f

**Comment by mirza-ae** [comment]
@imurchie 

Hello Issac,

Any update?

**Comment by imurchie** [comment]
This should be fixed in the latest code.
