### ISSUE TITLE
Unable to scroll screen on iOS automate test (mobile screen). Please let me know if anybody has used it.

### ISSUE THREAD

**Issue by NimishaBhut** [appium/appium#9161]
## The problem

I want to fetch an element from the bottom of the page but right now in mobile screen it will click only on those elements which are visible to them on screen and **_I am unable to scroll the screen_**.

## Environment

* "appium-version": "1.6.3",
* Desktop OS : iOS
* Node.js version (unless using Appium.app|exe): 6.11.0
* Mobile platform/version under test: 10.3.2
* Real device or emulator/simulator: iPhone 5s

**Comment by mykola-mokhnach** [comment]
Have you tried to use TouchActions interface or the set of [mobile](https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios-xctest-mobile-gestures.md) commands? Do you get any errors in the log if yes?

**Comment by NimishaBhut** [comment]
@mykola-mokhnach : Yes, i tried mobile:scroll which is available in [mobile](https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios-xctest-mobile-gestures.md) but it's not working at all.

**Comment by ochubey** [comment]
Hi @NimishaBhut,
Following (Java code) works on for me on Simulator and Real iOS device version 10.+ on Appium version 1.6+. Let me know if this helps or you need more info:

> private static final double SCROLL_START_HEIGHT_RATIO = 0.70;
> private static final double SCROLL_END_HEIGHT_RATIO = 0.30;
> private static final int SWIPE_DURATION = 1000;
> private static final int SCROLL_RETRIES = 50;
> 
> private void verticalScroll() {
>         Dimension size = getDriverInstance().getDriver().manage().window().getSize();
>         int yStart = (int) (size.height * SCROLL_START_HEIGHT_RATIO);
>         int yEnd = (int) (size.height * SCROLL_END_HEIGHT_RATIO);
>         int x = 0;
>         int upScrollDecreasePixels = 50;
>         try {
>                 getDriverInstance().getDriver().swipe(x, yStart, x, yEnd, SWIPE_DURATION);
>         } catch (WebDriverException webDriverException) {
>             logInfo("scrolling is not possible anymore:\n" + webDriverException.getMessage());
>         }
>     }

**Comment by JaniJegoroff** [comment]
I'm using Ruby + simulator for simple scrolling and swiping:
```
def scroll(direction)
  execute_script('mobile: scroll', direction: direction.to_s)
end

def swipe(direction)
  execute_script('mobile: swipe', direction: direction.to_s)
end
```

**Comment by mykola-mokhnach** [comment]
@NimishaBhut Make sure you use the most recent Appium version: 1.6.5 or 1.7.0-beta

**Comment by mykola-mokhnach** [comment]
@JaniJegoroff there are Ruby bindings for _mobile_ methods. You can use them for better readability.

**Comment by NimishaBhut** [comment]
I want to click on an element let say "element1" which is available at bottom or mid of the page/screen.
So, I have written as:

.waitForElementByName("element1", <timeout>)
.elemenyByName("element1")
.click()

Then, to implement scroll I tried following:

1)
return browser.elementByName("element1")
.then(function (el) {
  browser.execute("mobile: scroll", [{direction: "down", element: el.value}]);
});

above code is not working for scrolling.

I also tried:  

2)
browser.scrollTo("element1")

3)
browser.elementByName("element1")
.scrollToVisible()

--Anything from above is not working for scrolling. 
Correct me if I am wrong.

@mykola-mokhnach : I am using appium version 1.6.3 and 1.6.5 both.

**Comment by mykola-mokhnach** [comment]
Since you don't provide any logs I can only assume that you can be inside a webview. Then all these method won't work at all unless you switch to native context. 
If you are already working inside native context then make sure you perform scroll/swipe operation on a correct element. In the most common case this should be a parent view/table, which contains the element you need to scroll to. One more thing to pay attention to: if you provide an **element** parameter then its value is expected to be a unique hexadecimal id of the corresponding element, not the element object itself. For different Appium clients it has a different property name.

**Comment by NimishaBhut** [comment]
I want to perform scroll on UI Table view and yes I am using unique ID for an element itself which I want to use/click.

Can you provide any example to scroll in UI Table view.

**Comment by mykola-mokhnach** [comment]
Sorry, but we don't provide examples here. We solve bugs (or at least try to solve). Please check our [sample code repository](https://github.com/appium/sample-code) and/or create a new thread on [appium forum](https://discuss.appium.io).

**Comment by VTINFOJames** [comment]
I'm using Xcode 9.2, Java TestNG and iOS 11.2.5 to test a native iOS app. If I use tap on an element that is not displayed / off screen the application will scroll to it and tap on it.

```
String dba = "My Account";  
MobileElement el = driver.findElementByName(dba);  
el.tap(1, 1000); // I tried click() which doesn't work b/c it's not a user action in iOS.  
assertTrue(el.isDisplayed());  
```
https://forums.developer.apple.com/message/47116#47116
