### ISSUE TITLE
Android: API18: Driver failed to start

### ISSUE THREAD

**Issue by amedvedjev** [appium/appium#9162]
## The problem

when i use test with Android Emulator API18 appium cannot start correctly. in logs we see unlock error although unlock happens correctly in emulator.

As workaround i am killing driver start after 120sec in start driver again. it is starting with unlocked screen and continues normally further.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.0-beta
* Last Appium version that did not exhibit the issue (if applicable): 1.6.6 ? (do not remember)
* Desktop OS/version used to run Appium: mac OS 10.12.6
* Mobile platform/version under test: Android
* Real device or emulator/simulator: emulator API18

## Link to Appium logs

https://gist.github.com/amedvedjev/f7a642592920e6f0e2fda7adacf34a4c

**Comment by mykola-mokhnach** [comment]
@vrunoa FYI

**Comment by vrunoa** [comment]
@amedvedjev are you using emulator 2.0 ?  The unlock app doesnt work anymore on this emus. Even if you see it unlock, the browser or apps may not launch. 
Have you tried using the unlock capabilities ? This will unlock the device via  ui-automation. 
https://github.com/appium/appium-android-driver/blob/master/docs/UNLOCK.md

**Comment by amedvedjev** [comment]
@vrunoa emulator not locked. it is in pure state as is. i am using API18 (this is Android **4.3**) emulator with Nexus 5x device from Android Studio. simple swipe needed to unlock screen.

**Comment by vrunoa** [comment]
@amedvedjev i'm seeing simple swipe to unlock is not implemented using ui-automation, i'll try to have some PR near the weekend

**Comment by vrunoa** [comment]
@mykola-mokhnach assing the issue to myself if you want

**Comment by mykola-mokhnach** [comment]
@vrunoa Unfortunately and don't see you in the list of people I can assign the issue to.

**Comment by vrunoa** [comment]
no worries @mykola-mokhnach. working on this branch, still need to add support for API 18, 19. https://github.com/vrunoa/appium-android-driver/tree/add-swipe-to-unlock
