### ISSUE TITLE
"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}

### ISSUE THREAD

**Issue by ranikp** [appium/appium#9164]
## App crashing on simulator as soon as it opens

I am trying to run the app on Simulator,the app opens but crashes.

## Test Environment

* Desktop OS/version used to run Appium:Version 1.2.0-beta.3 (1.2.0-beta.3)
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:ios simulator
iPhone 6s plus 10.2

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

ranikp/gist:0bf45eb1bdee244eecf95fd7ec93f29a

## Code To Reproduce Issue [ Good To Have ]

1.Pulled latest code from sourcetree
2.opened xcode
3.made a archive file
4.got the app file from there.
5.opened Appium desktop app
6.added the desired capabilities 
7.{
  "app": "/Users/Desktop/PreProd.app",
  "platformName": "iOS",
  "deviceName": "iPhone 6s Plus",
  "platformVersion": "10.2",
  "automationName": "XCUITest"
}
8.The app opens and crashes

**Comment by mykola-mokhnach** [comment]
Please update the link to the Appium log
Are you able to install and start the app manually without Appium?

**Comment by ranikp** [comment]
Hi mykola-mokhnach 

I have already uploaded the log here
ranikp/gist:0bf45eb1bdee244eecf95fd7ec93f29a
Is that not the right place?Shall I update anywhere
Thanks

**Comment by ranikp** [comment]
Hi mykola-mokhnach

I am copying the code here

[Appium] Welcome to Appium v1.6.5
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> GET /wd/hub/sessions {}
[MJSONWP] Calling AppiumDriver.getSessions() with args: []
[MJSONWP] Responding to client with driver.getSessions() result: []
[HTTP] <-- GET /wd/hub/sessions 200 9 ms - 40 
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/Desktop/PreProd.app","automationName":"XCUITest","deviceName":"iPhone 6s Plus","platformName":"iOS","platformVersion":"10.2","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/Desktop/PreProd.app","automationName":"XCUITest","deviceName":"iPhone 6s Plus","platformName":"iOS","platformVersion":"10.2","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1504527445792 (13:17:25 GMT+0100 (BST))
[Appium] Creating new XCUITestDriver (v2.30.0) session
[Appium] Capabilities:
[Appium]   app: '/Users/Desktop/PreProd.app'
[Appium]   automationName: 'XCUITest'
[Appium]   deviceName: 'iPhone 6s Plus'
[Appium]   platformName: 'iOS'
[Appium]   platformVersion: '10.2'
[Appium]   newCommandTimeout: 0
[Appium]   connectHardwareKeyboard: true
[XCUITest] XCUITestDriver version: 2.30.0
[BaseDriver] Session created with session id: 4c7c5094-4aa1-43da-b61b-7ae2965e9e14
[XCUITest] Xcode version set to '8.3.3' (tools v8.3.2.0.1.1492020469)
[XCUITest] iOS SDK Version set to '10.3'
[BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1504527447309 (13:17:27 GMT+0100 (BST))
[iOSSim] Constructing iOS simulator for Xcode version 8.3.3 with udid 'B1900EC8-6C7F-4E42-B1B9-1FCE682E0832'
[XCUITest] Determining device to run tests on: udid: 'B1900EC8-6C7F-4E42-B1B9-1FCE682E0832', real device: false
[BaseDriver] Using local app '/Users/Desktop/PreProd.app'
[BaseDriver] Event 'appConfigured' logged at 1504527448848 (13:17:28 GMT+0100 (BST))
[XCUITest] Checking whether app '/Users/Desktop/PreProd.app' is actually present on file system
[XCUITest] App is present
[iOS] Getting bundle ID from app '/Users/Desktop/PreProd.app': 'com.appTest'
[XCUITest] Setting 'connectHardwareKeyboard' Simulator option to 'on'
[BaseDriver] Event 'resetStarted' logged at 1504527448854 (13:17:28 GMT+0100 (BST))
[XCUITest] Not scrubbing third party app in anticipation of uninstall
[BaseDriver] Event 'resetComplete' logged at 1504527448980 (13:17:28 GMT+0100 (BST))
[iOSLog] Starting iOS 10.2 simulator log capture
[iOSLog] System log path: /Users/Library/Logs/CoreSimulator/B1900EC8-6C7F-4E42-B1B9-1FCE682E0832/system.log
[BaseDriver] Event 'logCaptureStarted' logged at 1504527449127 (13:17:29 GMT+0100 (BST))
[XCUITest] Setting up simulator
[iOS] No reason to set locale
[iOS] No iOS / app preferences to set
[XCUITest] Simulator with udid 'B1900EC8-6C7F-4E42-B1B9-1FCE682E0832' not booted. Booting up now
[iOSSim] Killing all iOS Simulators
[iOSSim] Simulator is not running. Continuing...
[iOSSim] Starting simulator with command: open -Fn /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app --args -CurrentDeviceUDID B1900EC8-6C7F-4E42-B1B9-1FCE682E0832
[XCUITest] Reset requested. Removing app with id 'com.appTest' from the device
[iOSSim] Simulator booted in 22250ms
[BaseDriver] Event 'simStarted' logged at 1504527471675 (13:17:51 GMT+0100 (BST))
[XCUITest] Installing /Users/Desktop/PreProd.app on Simulator with UUID 'B1900EC8-6C7F-4E42-B1B9-1FCE682E0832'...
[XCUITest] The app has been installed successfully.
[BaseDriver] Event 'appInstalled' logged at 1504527486855 (13:18:06 GMT+0100 (BST))
[BaseDriver] Event 'wdaStartAttempted' logged at 1504527486857 (13:18:06 GMT+0100 (BST))
[XCUITest] Using WDA path: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[XCUITest] Carthage found: '/usr/local/bin/carthage'
[XCUITest] Killing hanging processes
[XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=B1900EC8-6C7F-4E42-B1B9-1FCE682E0832 -configuration Debug IPHONEOS_DEPLOYMENT_TARGET=10.2' in directory '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Output from xcodebuild will not be logged
[XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[XCUITest] Log file for xcodebuild test: /Users/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/61E6EEB5-89BF-4F8B-99F8-571FD23F33D2/Session-WebDriverAgentRunner-2017-09-04_131809-zdZjtI.log
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"state\" : \"success\",\n    \"os\" : {\n      \"name\" : \"iOS\",\n      \"version\" : \"10.2\"\n    },\n    \"ios\" : {\n      \"simulatorVersion\" : \"10.2\",\n      \"ip\" : \"10.150.13.82\"\n    },\n    \"build\" : {\n      \"time\" : \"Sep  1 2017 11:29:59\"\n    }\n  },\n  \"sessionId\" : \"CF067245-4043-4FF1-900B-DB905B587CFD\",\n  \"status\" : 0\n}"
[XCUITest] WebDriverAgent running on ip '10.150.13.82'
[XCUITest] WebDriverAgent successfully started after 10210ms
[BaseDriver] Event 'wdaSessionAttempted' logged at 1504527497158 (13:18:17 GMT+0100 (BST))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.appTest","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[JSONWP Proxy] Got response with status 200: {"value":"Failed to launch com.appTest application","sessionId":"CF067245-4043-4FF1-900B-DB905B587CFD","status":13}
[XCUITest] Failed to create WDA session. Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1504527739881 (13:22:19 GMT+0100 (BST))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.appTest","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[JSONWP Proxy] Got response with status 200: {"value":"Failed to launch com.appTest application","sessionId":"CF067245-4043-4FF1-900B-DB905B587CFD","status":13}
[XCUITest] Failed to create WDA session. Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1504527982554 (13:26:22 GMT+0100 (BST))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.appTest","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[HTTP] <-- POST /wd/hub/session - - ms - - 
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/Desktop/PreProd.app","automationName":"XCUITest","deviceName":"iPhone 6s Plus","platformName":"iOS","platformVersion":"10.2","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/Desktop/PreProd.app","automationName":"XCUITest","deviceName":"iPhone 6s Plus","platformName":"iOS","platformVersion":"10.2","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1504528048054 (13:27:28 GMT+0100 (BST))
[JSONWP Proxy] Got response with status 200: {"value":"Failed to launch com.appTest application","sessionId":"CF067245-4043-4FF1-900B-DB905B587CFD","status":13}
[XCUITest] Failed to create WDA session. Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1504528225931 (13:30:25 GMT+0100 (BST))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.appTest","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[JSONWP Proxy] Got response with status 200: {"value":"Failed to launch com.appTest application","sessionId":"CF067245-4043-4FF1-900B-DB905B587CFD","status":13}
[XCUITest] Failed to create WDA session. Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1504528478534 (13:34:38 GMT+0100 (BST))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.appTest","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[HTTP] <-- POST /wd/hub/session - - ms - - 
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/Desktop/PreProd.app","automationName":"XCUITest","deviceName":"iPhone 6s Plus","platformName":"iOS","platformVersion":"10.2","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/Desktop/PreProd.app","automationName":"XCUITest","deviceName":"iPhone 6s Plus","platformName":"iOS","platformVersion":"10.2","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1504528648049 (13:37:28 GMT+0100 (BST))
[JSONWP Proxy] Got response with status 200: {"value":"Failed to launch com.appTest application","sessionId":"CF067245-4043-4FF1-900B-DB905B587CFD","status":13}
[XCUITest] Failed to create WDA session. Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1504528729695 (13:38:49 GMT+0100 (BST))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.appTest","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[JSONWP Proxy] Got response with status 200: {"value":"Failed to launch com.appTest application","sessionId":"CF067245-4043-4FF1-900B-DB905B587CFD","status":13}
[XCUITest] Failed to create WDA session. Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1504528985379 (13:43:05 GMT+0100 (BST))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.appTest","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[JSONWP Proxy] Got response with status 200: {"value":"Failed to launch com.appTest application","sessionId":"CF067245-4043-4FF1-900B-DB905B587CFD","status":13}
[XCUITest] Failed to create WDA session. Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1504529236015 (13:47:16 GMT+0100 (BST))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.appTest","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[HTTP] <-- POST /wd/hub/session - - ms - - 
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/Desktop/PreProd.app","automationName":"XCUITest","deviceName":"iPhone 6s Plus","platformName":"iOS","platformVersion":"10.2","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/Desktop/PreProd.app","automationName":"XCUITest","deviceName":"iPhone 6s Plus","platformName":"iOS","platformVersion":"10.2","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1504529248874 (13:47:28 GMT+0100 (BST))
[JSONWP Proxy] Got response with status 200: {"value":"Failed to launch com.appTest application","sessionId":"CF067245-4043-4FF1-900B-DB905B587CFD","status":13}
[XCUITest] Failed to create WDA session. Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1504529489341 (13:51:29 GMT+0100 (BST))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.appTest","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[JSONWP Proxy] Got response with status 200: {"value":"Failed to launch com.appTest application","sessionId":"CF067245-4043-4FF1-900B-DB905B587CFD","status":13}
[XCUITest] Failed to create WDA session. Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1504529732008 (13:55:32 GMT+0100 (BST))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.appTest","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[HTTP] <-- POST /wd/hub/session - - ms - - 
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/Desktop/PreProd.app","automationName":"XCUITest","deviceName":"iPhone 6s Plus","platformName":"iOS","platformVersion":"10.2","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/Desktop/PreProd.app","automationName":"XCUITest","deviceName":"iPhone 6s Plus","platformName":"iOS","platformVersion":"10.2","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1504529850586 (13:57:30 GMT+0100 (BST))
[JSONWP Proxy] Got response with status 200: {"value":"Failed to launch com.appTest application","sessionId":"CF067245-4043-4FF1-900B-DB905B587CFD","status":13}
[XCUITest] Failed to create WDA session. Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1504529979894 (13:59:39 GMT+0100 (BST))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.appTest","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[JSONWP Proxy] Got response with status 200: {"value":"Failed to launch com.appTest application","sessionId":"CF067245-4043-4FF1-900B-DB905B587CFD","status":13}
[XCUITest] Failed to create WDA session. Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1504530222588 (14:03:42 GMT+0100 (BST))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.appTest","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[HTTP] <-- POST /wd/hub/session - - ms - - 
[JSONWP Proxy] Got response with status 200: {"value":"Failed to launch com.appTest application","sessionId":"CF067245-4043-4FF1-900B-DB905B587CFD","status":13}
[XCUITest] Failed to create WDA session. Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1504530465259 (14:07:45 GMT+0100 (BST))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.appTest","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[JSONWP Proxy] Got response with status 200: {"value":"Failed to launch com.appTest application","sessionId":"CF067245-4043-4FF1-900B-DB905B587CFD","status":13}
[XCUITest] Failed to create WDA session. Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1504530709153 (14:11:49 GMT+0100 (BST))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.appTest","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[JSONWP Proxy] Got response with status 200: {"value":"Failed to launch com.appTest application","sessionId":"CF067245-4043-4FF1-900B-DB905B587CFD","status":13}
[XCUITest] Failed to create WDA session. Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1504530951888 (14:15:51 GMT+0100 (BST))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.appTest","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[JSONWP Proxy] Got response with status 200: {"value":"Failed to launch com.appTest application","sessionId":"CF067245-4043-4FF1-900B-DB905B587CFD","status":13}
[XCUITest] Failed to create WDA session. Retrying...
[XCUITest] Unable to start WebDriverAgent session: An unknown server-side error occurred while processing the command. Original error: Failed to launch com.appTest application
[XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down xcodebuild process (pid 2249)
[XCUITest] xcodebuild exited with code 'null' and signal 'SIGTERM'
[XCUITest] Removing WDA application from device
[BaseDriver] Event 'wdaStartAttempted' logged at 1504531225448 (14:20:25 GMT+0100 (BST))
[XCUITest] Using WDA path: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[XCUITest] Carthage found: '/usr/local/bin/carthage'
[XCUITest] Killing hanging processes
[XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=B1900EC8-6C7F-4E42-B1B9-1FCE682E0832 -configuration Debug IPHONEOS_DEPLOYMENT_TARGET=10.2' in directory '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Output from xcodebuild will not be logged
[XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[XCUITest] Log file for xcodebuild test: /Users/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/554B8FC5-C80B-4D15-B7C1-13D56EE7301F/Session-WebDriverAgentRunner-2017-09-04_142028-pBh9i4.log
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"state\" : \"success\",\n    \"os\" : {\n      \"name\" : \"iOS\",\n      \"version\" : \"10.2\"\n    },\n    \"ios\" : {\n      \"simulatorVersion\" : \"10.2\",\n      \"ip\" : \"10.150.13.82\"\n    },\n    \"build\" : {\n      \"time\" : \"Sep  1 2017 11:29:59\"\n    }\n  },\n  \"sessionId\" : \"5A7B7DF1-60F2-47D6-8898-2FE92D93F1AC\",\n  \"status\" : 0\n}"
[XCUITest] WebDriverAgent running on ip '10.150.13.82'
[XCUITest] WebDriverAgent successfully started after 15734ms
[BaseDriver] Event 'wdaSessionAttempted' logged at 1504531241350 (14:20:41 GMT+0100 (BST))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.appTest","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[JSONWP Proxy] Got response with status 200: {"value":"Failed to launch com.appTest application","sessionId":"5A7B7DF1-60F2-47D6-8898-2FE92D93F1AC","status":13}
[XCUITest] Failed to create WDA session. Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1504531484032 (14:24:44 GMT+0100 (BST))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.appTest","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[JSONWP Proxy] Got response with status 200: {"value":"Failed to launch com.appTest application","sessionId":"5A7B7DF1-60F2-47D6-8898-2FE92D93F1AC","status":13}
[XCUITest] Failed to create WDA session. Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1504531731225 (14:28:51 GMT+0100 (BST))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.appTest","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[JSONWP Proxy] Got response with status 200: {"value":"Failed to launch com.appTest application","sessionId":"5A7B7DF1-60F2-47D6-8898-2FE92D93F1AC","status":13}
[XCUITest] Failed to create WDA session. Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1504531983148 (14:33:03 GMT+0100 (BST))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.appTest","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[JSONWP Proxy] Got response with status 200: {"value":"Failed to launch com.appTest application","sessionId":"5A7B7DF1-60F2-47D6-8898-2FE92D93F1AC","status":13}
[XCUITest] Failed to create WDA session. Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1504532225848 (14:37:05 GMT+0100 (BST))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.appTest","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[JSONWP Proxy] Got response with status 200: {"value":"Failed to launch com.appTest application","sessionId":"5A7B7DF1-60F2-47D6-8898-2FE92D93F1AC","status":13}
[XCUITest] Failed to create WDA session. Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1504532470106 (14:41:10 GMT+0100 (BST))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.appTest","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}

**Comment by ranikp** [comment]
I am able to install app by Xcode

**Comment by mykola-mokhnach** [comment]
From the given log it looks like you are trying to create multiple sessions even after the first session is started successfully.

**Comment by ranikp** [comment]
Ok,but where I am doing that.
I am clicking on start session on Appium ,thats it
Not sure how to resolve this

**Comment by jlipps** [comment]
@ranikp are you clicking the start session button more than once?

**Comment by haithngn** [comment]
I'm facing with this, please fix

**Comment by ranaara91** [comment]
I'm also experiencing this issue. Could you please take a look at it? It wasn't like that on Appium 1.6.5.
Now writing UI Tests is really painful if I have to restart iOS simulator & Appium every 20 min..
