### ISSUE TITLE
PageSource is extremely slow on combination of iOS 11 + Xcode 9 beta 6 + Appium 1.7.0 beta

### ISSUE THREAD

**Issue by rajfidel** [appium/appium#9166]
## The problem

PageSource retrieval is extremely slow on iOS 11 + Xcode 9 beta 6 (had issue on previous betas as well) + Appium 1.7.0 beta (Also had issues on previous 1.6.6 betas)

Got the page source of the Settings app (com.apple.Preferences) and looped it **20 times** to get the total time as shown below for the various combinations:
iOS 11 + 1.7.0 beta + xcode 9 beta 6 -> 8 min 5 sec, Appium Log [here](https://gist.github.com/rajfidel/a8437cbf6d943921c5c1ca46c4eaacbb)
iOS 10 + 1.7.0 beta + xcode 9 beta 6 -> 3 min 38 sec, Appium Log [here](https://gist.github.com/rajfidel/c8c95c4bd4496e28fa0833d44a2fd06d)
iOS 10 + 1.6.5 + xcode 8.3.3 -> 1 min 22 sec, Appium Log [here](https://gist.github.com/rajfidel/47993bf24a35b49c4ea6fb1252c966f9)

The Settings app on the iOS 11 phone is pretty stock and has very less table rows when compared to the Settings app on the iOS 10 phone which has 2.5x rows (due to greater installed apps). iOS 11 PageSource command still takes much more to complete.
iOS 10 performs twice as better than iOS 11 with Appium 1.7.0 beta with 2.5x more elements to process.

I understand that PageSource should not be used for local processing, and that Xpath can be terribly slow as well. However, in this case, we use it to log the PageSource (when the test runs into failures) for debugging later.

Also wondering if I should have reported this issue in the WebdriverAgent project [here](https://github.com/facebook/WebDriverAgent) instead

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.6 beta and above
* Last Appium version that did not exhibit the issue (if applicable): 1.6.5
* Desktop OS/version used to run Appium: mac OS Sierra 10.12.6
* Node.js version (unless using Appium.app|exe): 8.1.4
* Mobile platform/version under test: 11.0 beta 9
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: Appium CLI

**Comment by mykola-mokhnach** [comment]
Yes, it would be better to report the problem into WDA project.
BTW, can you also attach the logs from real device for the time period when source tree construction is in progress?

**Comment by rajfidel** [comment]
Sure. will submit to WDA project along with the device logs. Thanks.

**Comment by NagyRobertt** [comment]
Hi, did you open issue on WDA project? I would like to follow it if you did. It is a big problem for me as well.

**Comment by rajfidel** [comment]
@NagyRobertt Not yet. Didn't get time to rerun the scenarios to capture device logs. Hopefully will submit today.

**Comment by kommuswamy** [comment]
Hi, did you open issue on WDA project? I would like to follow it if you did. It is a big problem for me as well.

**Comment by rajfidel** [comment]
Submitted issue [here](https://github.com/facebook/WebDriverAgent/issues/711)

**Comment by dzaiats** [comment]
Hi guys! I found the solution. Use the capability useJSONSource=true. It makes getting of source 2x or 3x faster.
