### ISSUE TITLE
Encountered internal error running command: Error: Sdk '11' was not in list of simctl sdks

### ISSUE THREAD

**Issue by Logakarti** [appium/appium#9167]
## The problem

"Encountered internal error running command: Error: SDK '11' was not in list of simctl SDKs" exception throws while running the app cases in iPhone 7 - iOS 11 Simulators (Use Xcode 9 beta). Please help me to solve the issue.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Desktop OS/version used to run Appium: MAC
* Mobile platform/version under test: iOS 11
* Real device or emulator/simulator: iPhone 7

## Link to Appium logs
https://gist.github.com/Logakarti/706d7a2c17ca92f2a8df6fd02fdb9c58

## Code To Reproduce Issue [ Good To Have ]

Capabilities:

        File appdir = new File("/Users/apple/Downloads");
        File app = new File(appdir, "CK-12-3.7.0.77225w.ipa");
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, MobilePlatform.IOS);
        capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "11");
        capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone 7");
        capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, "XCUITest");
        capabilities.setCapability("safariAllowPopups", true);
        capabilities.setCapability("autoWebview", true);
        capabilities.setCapability("safariOpenLinksInBackground", true);
        capabilities.setCapability("webviewConnectRetries", 25);
        capabilities.setCapability("app", app.getAbsolutePath());
        driver = new IOSDriver(new URL("http://127.0.0.1:4729/wd/hub"), capabilities);
        driver.manage().timeouts().implicitlyWait(60, TimeUnit.SECONDS);
        try {
            Thread.sleep(15000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        return capabilities;
    }

iOS node Config:

{
	"capabilities": [{
		"browserName": "safari",
		"version": "11",
		"maxInstances": 1,
		"platform": "MAC"
	}],
	"configuration": {
		"cleanUpCycle": 2000,
		"timeout": 30000,
		"proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
		"url": "http://127.0.0.1:4729/wd/hub",
		"host": "127.0.0.1",
		"port": 4729,
		"maxSession": 1,
		"register": true,
		"registerCycle": 5000,
		"hubPort": 4444,
		"hubHost": "192.168.1.14"
	}
}

**Comment by mykola-mokhnach** [comment]
Try 11.0 instead. Version number is expected to look the same way it is printed by `xcrun simctl list`

**Comment by Logakarti** [comment]
Device List:

How to identify the version for the devices and also some device status shows "Shutdown".
== Device Types ==
iPhone 4s (com.apple.CoreSimulator.SimDeviceType.iPhone-4s)
iPhone 5 (com.apple.CoreSimulator.SimDeviceType.iPhone-5)
iPhone 5s (com.apple.CoreSimulator.SimDeviceType.iPhone-5s)
iPhone 6 (com.apple.CoreSimulator.SimDeviceType.iPhone-6)
iPhone 6 Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-6-Plus)
iPhone 6s (com.apple.CoreSimulator.SimDeviceType.iPhone-6s)
iPhone 6s Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-6s-Plus)
iPhone 7 (com.apple.CoreSimulator.SimDeviceType.iPhone-7)
iPhone 7 Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-7-Plus)
iPhone SE (com.apple.CoreSimulator.SimDeviceType.iPhone-SE)
iPad 2 (com.apple.CoreSimulator.SimDeviceType.iPad-2)
iPad Retina (com.apple.CoreSimulator.SimDeviceType.iPad-Retina)
iPad Air (com.apple.CoreSimulator.SimDeviceType.iPad-Air)
iPad Air 2 (com.apple.CoreSimulator.SimDeviceType.iPad-Air-2)
iPad (5th generation) (com.apple.CoreSimulator.SimDeviceType.iPad--5th-generation-)
iPad Pro (9.7-inch) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro--9-7-inch-)
iPad Pro (12.9-inch) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro)
iPad Pro (12.9-inch) (2nd generation) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro--12-9-inch---2nd-generation-)
iPad Pro (10.5-inch) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro--10-5-inch-)
Apple TV 1080p (com.apple.CoreSimulator.SimDeviceType.Apple-TV-1080p)
Apple Watch - 38mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-38mm)
Apple Watch - 42mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-42mm)
Apple Watch Series 2 - 38mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-2-38mm)
Apple Watch Series 2 - 42mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-2-42mm)
== Runtimes ==
iOS 10.3 (10.3.1 - 14E8301) (com.apple.CoreSimulator.SimRuntime.iOS-10-3)
tvOS 10.2 (10.2 - 14W260) (com.apple.CoreSimulator.SimRuntime.tvOS-10-2)
watchOS 3.2 (3.2 - 14V243) (com.apple.CoreSimulator.SimRuntime.watchOS-3-2)
== Devices ==
-- iOS 10.3 --
    iPhone 5 (AF4CDC85-40D6-4DF0-875C-22AAAE821C90) (Shutdown)
    iPhone 5s (215BD885-F8F0-4BFB-A8B7-98B883030E23) (Shutdown)
    iPhone 6 (B4C17221-2DA6-44F9-858B-357E070AB226) (Shutdown)
    iPhone 6 Plus (4F0344EA-063B-4B43-AC72-D69794124EC3) (Shutdown)
    iPhone 6s (986C6462-D45D-4A30-B727-0844EB95B42E) (Shutdown)
    iPhone 6s Plus (F8C000CF-7818-4979-93BA-3E52DC34FD8C) (Shutdown)
    iPhone 7 (FB78170C-D96E-48F7-852F-8C5D5C1969B4) (Shutdown)
    iPhone 7 Plus (C5DE4A24-540F-41DE-A777-63F5AC6F4127) (Shutdown)
    iPhone SE (0626823A-A487-4B0C-9475-81BB0D27967B) (Shutdown)
    iPad Air (E531200A-7350-414B-BD6E-6872E7EB4BB8) (Shutdown)
    iPad Air 2 (189EB01D-096B-46C5-8FF3-701DDEB7BB75) (Shutdown)
    iPad (5th generation) (C60C2559-80D4-4E98-AAE9-7F233BD3511C) (Shutdown)
    iPad Pro (9.7 inch) (A2264691-6149-46A1-B77A-1D28611A7B95) (Shutdown)
    iPad Pro (12.9 inch) (4F641567-AA14-4B46-8B30-65DBE99BA2E2) (Shutdown)
    iPad Pro (12.9-inch) (2nd generation) (79A19281-8E77-4304-B534-874A0D231B72) (Shutdown)
    iPad Pro (10.5-inch) (AE8F6B49-F8FF-48DC-B340-36451769DFA5) (Shutdown)
-- tvOS 10.2 --
    Apple TV 1080p (DC55E87C-C685-48A1-8143-AA539370DC0A) (Shutdown)
-- watchOS 3.2 --
    Apple Watch - 38mm (E01AFC14-4955-4136-BDFB-DAB20BD61FE9) (Shutdown)
    Apple Watch - 42mm (E23AD749-708A-4FE2-B048-709141E9D36D) (Shutdown)
    Apple Watch Series 2 - 38mm (128B1ECA-AF49-4BAF-A40A-927B1EFCE474) (Shutdown)
    Apple Watch Series 2 - 42mm (AE39302E-76B4-4912-BC4B-0E2BCD1F1EE5) (Shutdown)
-- Unavailable: com.apple.CoreSimulator.SimRuntime.iOS-11-0 --
    iPhone 5s (11DA05BF-E91A-4816-A7FB-E0D69AE7823A) (Shutdown) (unavailable, runtime profile not found)
    iPhone 6 (1F46592F-F13F-4044-9CDA-08A6C12468D3) (Shutdown) (unavailable, runtime profile not found)
    iPhone 6 Plus (08DD97F7-7C56-468D-BDA4-CAE55BE4DF05) (Shutdown) (unavailable, runtime profile not found)
    iPhone 6s (EC62D8DD-0C19-4C59-97E9-E22B20E5755E) (Shutdown) (unavailable, runtime profile not found)
    iPhone 6s Plus (14344699-397D-4DF6-B559-746C8722F9A1) (Shutdown) (unavailable, runtime profile not found)
    iPhone 7 (706B763F-FB84-4F92-A430-09AEE80CFBCC) (Shutdown) (unavailable, runtime profile not found)
    iPhone 7 Plus (7ACA8563-815C-46DE-B22D-B7BA50E7C591) (Shutdown) (unavailable, runtime profile not found)
    iPhone SE (AC3D0E69-46DC-4328-A79E-C66D52F8FF5D) (Shutdown) (unavailable, runtime profile not found)
    iPad Air (EA956A1E-BF1F-4912-975D-D8823C9DFB12) (Shutdown) (unavailable, runtime profile not found)
    iPad Air 2 (C9165E5C-1302-441D-994B-D209E2ECE3EC) (Shutdown) (unavailable, runtime profile not found)
    iPad (5th generation) (7B40C1F8-B3FA-4A01-82FE-24A3010854AB) (Shutdown) (unavailable, runtime profile not found)
    iPad Pro (9.7-inch) (6D4D3B5A-1177-443A-8E0E-D222687A8E4D) (Shutdown) (unavailable, runtime profile not found)
    iPad Pro (12.9-inch) (4C1E3B5E-F665-40A1-922B-24BCDA9E9D76) (Shutdown) (unavailable, runtime profile not found)
    iPad Pro (12.9-inch) (2nd generation) (0B1EF278-0537-417C-AF38-3A9407A49940) (Shutdown) (unavailable, runtime profile not found)
    iPad Pro (10.5-inch) (FFC25910-5B31-4D92-8DBC-5FE6C84EC89A) (Shutdown) (unavailable, runtime profile not found)
-- Unavailable: com.apple.CoreSimulator.SimRuntime.watchOS-4-0 --
    Apple Watch - 38mm (9969B820-D339-4884-9627-7C790FE3E67B) (Shutdown) (unavailable, runtime profile not found)
    Apple Watch - 42mm (720F0EC3-EACE-4CE4-8E44-8C8F5846AE95) (Shutdown) (unavailable, runtime profile not found)
    Apple Watch Series 2 - 38mm (314B8E1E-FBB8-4B95-A575-D982A460EF6A) (Shutdown) (unavailable, runtime profile not found)
    Apple Watch Series 2 - 42mm (645EF41C-CD35-40BD-9741-A11846003CA7) (Shutdown) (unavailable, runtime profile not found)
== Device Pairs ==
96F8EDFE-1B40-4DC0-B0DA-B0AC3615586C (active, disconnected)
    Watch: Apple Watch - 38mm (E01AFC14-4955-4136-BDFB-DAB20BD61FE9) (Shutdown)
    Phone: iPhone 6s (986C6462-D45D-4A30-B727-0844EB95B42E) (Shutdown)
0E9C2004-D979-4A08-9D96-7540867AD070 (active, disconnected)
    Watch: Apple Watch - 42mm (E23AD749-708A-4FE2-B048-709141E9D36D) (Shutdown)
    Phone: iPhone 6s Plus (F8C000CF-7818-4979-93BA-3E52DC34FD8C) (Shutdown)
EAD797B8-210A-41FF-A73C-F88792332339 (active, disconnected)
    Watch: Apple Watch Series 2 - 38mm (128B1ECA-AF49-4BAF-A40A-927B1EFCE474) (Shutdown)
    Phone: iPhone 7 (FB78170C-D96E-48F7-852F-8C5D5C1969B4) (Shutdown)
6828726F-0B8B-47F7-9500-CB0DE569B787 (active, disconnected)
    Watch: Apple Watch Series 2 - 42mm (AE39302E-76B4-4912-BC4B-0E2BCD1F1EE5) (Shutdown)
    Phone: iPhone 7 Plus (C5DE4A24-540F-41DE-A777-63F5AC6F4127) (Shutdown)
299736ED-41BD-457A-974C-C3C6C532FB15 (unavailable)
    Watch: Apple Watch Series 2 - 38mm (314B8E1E-FBB8-4B95-A575-D982A460EF6A) (Shutdown)
    Phone: iPhone 7 (706B763F-FB84-4F92-A430-09AEE80CFBCC) (Shutdown)
E05A9970-C17B-46C2-862F-21513FD52727 (unavailable)
    Watch: Apple Watch Series 2 - 42mm (645EF41C-CD35-40BD-9741-A11846003CA7) (Shutdown)
    Phone: iPhone 7 Plus (7ACA8563-815C-46DE-B22D-B7BA50E7C591) (Shutdown)
