### ISSUE TITLE
Android real device: Zoom with a MutliTouchAction does not work

### ISSUE THREAD

**Issue by mpau** [appium/appium#9168]
## The problem

I've implemented a method to zoom in with a MutliTouchAction for Android. It looks like it would work but nothing happens at all. 

## Environment

* Appium version (or git revision) that exhibits the issue:
Appium Desktop 1.2.0-beta.3 with 1.6.5 and also tested with 1.6.6-beta.2 CLI
* Desktop OS/version used to run Appium:
macOS Sierra 10.12.6
* Node.js version (unless using Appium.app|exe):
v7.8.0
* Mobile platform/version under test:
Android 7.0
* Real device or emulator/simulator:
Real device Samsung S8
* Appium CLI or Appium.app|exe:
Both

## Details

I also activated the developer option/show touch-show pointer and can see, that there is a touch and a move to like wished. But at the end, nothing happens.

## Link to Appium logs

https://gist.github.com/mpau/0bbd211aacf0e5e16a3783dd8ae53f81

## Code To Reproduce Issue [ Good To Have ]

 static void zoomIn(AppiumDriver driver) {
        int screenHeight = driver.manage().window().getSize().getHeight()
        int screenWidth = driver.manage().window().getSize().getWidth()

        MultiTouchAction multiTouchAction = new MultiTouchAction(driver)
        TouchAction touchAction0 = new TouchAction(driver)
        TouchAction touchAction1 = new TouchAction(driver)

        touchAction0
                .press(((int) screenWidth/2), ((int) screenHeight/2))
                .moveTo(20, -400)
                .release()

        touchAction1
                .press(((int) screenWidth/2), ((int) (screenHeight/2) + 150))
                .moveTo(-20, 400)
                .release()

        multiTouchAction
                .add(touchAction0)
                .add(touchAction1)
                .perform()

        Thread.sleep(2000)
    }

**Comment by mykola-mokhnach** [comment]
Have you tried to set UIAutomator2 as the automation backend?

**Comment by mykola-mokhnach** [comment]
Also the link to Appium logs is corrupted

**Comment by mpau** [comment]
I've installed now via npm the appium-uiautomator2-driver and set the capability to MobileCapabilityType.AUTOMATION_NAME, "uiautomator2" but it does not change anything. The Appium logs link should work now.

**Comment by mykola-mokhnach** [comment]
It might be you are performing the gesture on a wrong UI element, which, actually, does not listen to it.

**Comment by mpau** [comment]
But if you check out my example code, you see that I use the MutliTouchAction class and I can not see, where I could add an element to this, to perform on it. I don't use the Driver.zoom method, where you can do such an action on an element, cause zoom does not work at all. I also have similar problems with iOS.

**Comment by mykola-mokhnach** [comment]
Closed as inactive. Additionally, UIA2 and Espresso drivers got support of W3C actions, including multitouch ones. Check https://appiumpro.com/editions/29
