### ISSUE TITLE
Certificate mismatch confusion

### ISSUE THREAD

**Issue by davidmorrison1981** [appium/appium#9169]
Related to xcodebuild exited with code '65' and signal 'null' #9003. 

I still can't get appium to run on a physical device.  

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5 App version
* Last Appium version that did not exhibit the issue (if applicable): n/a
* Desktop OS/version used to run Appium: sierra 10.12.6
* Node.js version (unless using Appium.app|exe): n/a
* Mobile platform/version under test: iOS 10.1.1
* Real device or emulator/simulator: iPhone 7
* Appium CLI or Appium.app|exe: app

The scenario is as follows:
I am QA in a large dev team and I have access to download either a .dgm or .ipa file.  For manual testing I install the .ipa on the device.  I have installed it on the device and I know I can open it and it runs normally.

I have xcode 8.2.1 and I have a developer certificate associated to the organisation. 
I have the mobile provisioning certificates for the same organisation
The device is associated to the development account also.

My understanding was that appium uses Xcode to build the web driver agent and as long as I have developer certificates and provisioning credentials it should build properly.  What's missing/ what can i check?

**Comment by rajfidel** [comment]
Assuming that by 1.6.5 App version, you are using Appium Desktop available [here](https://github.com/appium/appium-desktop/releases/) 
If that is the case, have you opened the WebdriverAgent.xcodeproj available at /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent in Xcode
and selected 'Automatically manage signing' checkbox and the developer team name  for targets 'WebdriverAgentLib' and 'WebdriverAgentRunner'?

**Comment by davidmorrison1981** [comment]
It was the provisioning profile on my Xcode account that was the issue.  Its now resolved and inspector is now open targeting the device.  Next, learn how to run tests!  Thanks
