### ISSUE TITLE
Incorrect work with coordinates in landscape mode while executing press + moveTo commands

### ISSUE THREAD

**Issue by tmytlovych** [appium/appium#9176]
## The problem

While executing the following command in landscape, appium treats 'x' as 'y' and vise versa.
   

## Environment

* Appium version (or git revision) that exhibits the issue: Appium v1.7.0-beta, v1.6.6-beta.4
* Last Appium version that did not exhibit the issue (if applicable): Appium v1.6.3
* Desktop OS/version used to run Appium: Sierra Version 10.12.5
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iPad Air 2, iOS 11.0
* Real device or emulator/simulator: simulator 
* Appium CLI or Appium.app|exe:

## Details

Also by executing the commands added, element is moved from the bottom of the screen by the diagonal (not just by one of the axis)

## Link to Appium logs

Found matching gesture: drag

[debug] [JSONWP Proxy] Proxying [POST /wda/dragfromtoforduration] to [POST http://localhost:8100/session/1EB033B5-BDAD-4132-950A-D1B91D8C0437/wda/dragfromtoforduration] with body: {"fromX":716,"fromY":209,"toX":1543,"toY":418,"duration":1}

## Code To Reproduce Issue [ Good To Have ]

new TouchAction(appiumDriver).press(716, 209).waitAction(1000).moveTo(827, 209).release().perform();

**Comment by mykola-mokhnach** [comment]
Please report the issue directly to https://github.com/facebook/WebDriverAgent/issues

Looks like Apple has finally fixed the bug in XCTest %)

**Comment by tmytlovych** [comment]
Thanks
