### ISSUE TITLE
Appium closes app immediately after launching it

### ISSUE THREAD

**Issue by FaithFayF** [appium/appium#9177]
## The problem

Appium closes app immediately after launches it. When it builds with Xcode 8.3.3 it launches the app correctly in simulator. However, when Appium tries to launch the app in simulator it appears and disappears and looks like it's crashing. I have look through the log file many times I don't find any error. I have switched from using *.ipa to *.app.

## Environment
Appium: 1.6.5
Simulator Device: iPhone 6s
Simulator iOS Version: 10.0
Xcode: 8.3.3

## Link to Appium logs
[GIST](https://gist.github.com/FaithFayF/7c742f5c335b2055700669279439c71d)

**Comment by imurchie** [comment]
Can you turn on device logging (set the `showIOSLog` capability to `true`) and run the test, then post a new link to a [gist](https://gist.github.com) of the logs?

**Comment by FaithFayF** [comment]
Thanks for your prompt response :)

Here you go gist[](https://gist.github.com/FaithFayF/2dd03159be833eef9556680bd5727868)

**Comment by mykola-mokhnach** [comment]
> [debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"joycechin.com.Motivation-Ninjas","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
> [info] [iOSLog] [IOS_SYSLOG_ROW] Sep  6 21:44:36 Q-MBA com.apple.CoreSimulator.SimDevice.4BBCF2D2-0CEA-441F-8A77-97B0142B3226.launchd_sim[2552] (UIKitApplication:joycechin.com.Motivation-Ninjas[0x21c3][3171]): Service exited due to Abort trap: 6
> [info] [iOSLog] [IOS_SYSLOG_ROW] Sep  6 21:44:36 Q-MBA assertiond[2573]: notify_suspend_pid() failed with error 7
> [info] [iOSLog] [IOS_SYSLOG_ROW] Sep  6 21:44:38 Q-MBA nanotimekitcompaniond[3011]: *** -[NSKeyedUnarchiver initForReadingWithData:]: data is NULL
> [info] [iOSLog] [IOS_SYSLOG_ROW] Sep  6 21:44:49 Q-MBA mobileassetd[2619]: mobileassetd - _localURLForAsset: [com.apple.accessibility.AccessibilityUIServer] _localURLForAsset[com.apple.MobileAsset.VoiceServicesVocalizerVoice]: unable to get local URL for asset: Error Domain=MobileAssetError Code=1 "(null)" [com_apple_MobileAsset_VoiceServicesVocalizerVoice/67ea7dd3dda1183a978f1dca63b1fb1003787c2b.zip]

The application under test just crashes. the problem has nothing to do with Appium.

**Comment by FaithFayF** [comment]
Is that a way to fix this issue? The app does look fine when built with Xcode and loaded correctly.

**Comment by FaithFayF** [comment]
Developer had a look suspect the Apple developer account as we are still waiting to purchase one. Anyone encounter similar issue?

**Comment by ochubey** [comment]
@FaithFayF can you run same app (installed by Appium) on the same Simulator after the test fails?
Could it be that app was built for another architecture/SDK version?

**Comment by FaithFayF** [comment]
@ochubey I'm just trying to launch the app in simulator not even hook up with any test yet and it keep clashing. 

Any particular step/command to find out the architecture/sdk version?

**Comment by ochubey** [comment]
Open your favorite terminal, navigate to ios app source code folder:
run `xcodebuild clean build -workspace {yourWorkspace}.xcworkspace -scheme {yourSchema} -configuration Debug -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6s,OS=10.0' -derivedDataPath ~/Desktop/LatestBuild` asking developers what should be put into {yourWorkspace} and {yourSchema} + if any project specific actions need to be done. You would not need to have Apple developer account to do it.
As a result in the derived data folder, you would be able to find the resulting app, that should work with SDK 10.+ and iPhone 6s+ Simulators with your Appium tests.

**Comment by FaithFayF** [comment]
@ochubey Thanks! We got it working in the end! We have done so many things and we did try out the command above as well. There's probably few issues altogether. Thanks for your pointer it does help us get to the finishing line! And I'm able to launch simulator from the code too.
