### ISSUE TITLE
Not able to launch the app on real device

### ISSUE THREAD

**Issue by Rnij** [appium/appium#9178]
## The problem

Running the following command displays the username abcd of another user that uses the machine. 
How can I add or modify this so that I will not have issues using appium?

ls -la /usr/local/bin/appium

lrwxrwxrwx  1 abcd  admin  44 Jul 14 15:50 /usr/local/bin/appium -> ../lib/node_modules/appium/build/lib/main.js

## Environment
•Appium version (or git revision) that exhibits the issue:1.6.5
•Last Appium version that did not exhibit the issue (if applicable):
•Desktop OS/version used to run Appium:10.12.5
•Node.js version (unless using Appium.app|exe):
•Mobile platform/version under test:10.3.3
•Real device or emulator/simulator:iPad Pro
•Appium CLI or Appium.app|exe:

## Details
I am trying to launch the app on real device and having issues for which I have opened issue 9103.
I found some information in issue 6853 which mentioned on running below command, I found that I was not listed as a user. We have a mac and another user has been using this mac is listed as admin in the output of this command. Is there a way I can add myself or update ?
 
ls -la /usr/local/bin/appium
lrwxrwxrwx  1 abcd  admin  44 Jul 14 15:50 /usr/local/bin/appium -> ../lib/node_modules/appium/build/lib/main.js

**Comment by jlipps** [comment]
You should install appium locally for your user then. Rather than doing `npm install -g appium`, you should try:

```
mkdir appium
cd appium
npm install appium
```

This will install appium into that directory. Now you can run appium by going to that directory and running

```
$(npm bin)/appium
```

Inside that directory.

Or of course you could `chown` the director `/usr/local/lib/node_moduels/appium` to your user. This is not an appium issue in any case, this is a unix/mac usage issue.

**Comment by Rnij** [comment]
@jlipps Thanks. In order to uninstall and then install Appium locally as you mentioned and node can you please provide the steps in details as I would like to uninstall everything related to Appium and then start fresh.
