### ISSUE TITLE
TouchAction command queue not cleared in 1.6.5

### ISSUE THREAD

**Issue by alexandlazaris** [appium/appium#9179]
## The problem

Tried a basic example of a drag and drop using ApiDemos-debug.apk. I am trying to long press an element. It seems that the command queue for TouchAction is not being cleared, which means only the very first action is executed. 

## Environment

* Appium version: 1.6.5. Tried to repro in 1.6.3/4, couldn't start server
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): v6.3.0
* Mobile platform/version under test: Google Pixel, API 25
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: Appium CLI (well, start server in code in Eclipse)

## Details

I've since lost the stack trace for the TouchAction.longPress() method, however the logs for that method included previous TouchAction methods that had already been run, which made it look like each TouchAction method was being added to a chain, resulting in errors. 

## Link to Appium logs

```org.openqa.selenium.NoSuchElementException: An element could not be located on the page using the given search parameters. (WARNING: The server did not provide any stacktrace information)```

## Code To Reproduce Issue

```TouchAction actions = new TouchAction(driver);
actions.tap((AndroidElement)driver.findElementByAndroidUIAutomator("text(\"Views\")")).perform();

driver.findElementByAndroidUIAutomator("text(\"Drag and Drop\")").click();

AndroidElement element1 = driver.findElement(By.id("io.appium.android.apis:id/drag_dot_1"));

AndroidElement element2 = driver.findElement(By.id("io.appium.android.apis:id/drag_dot_2"));

actions.longPress(element1).waitAction(3000).perform().release();
```
If I were to add a new ```TouchAction``` variable (e.g. ```actions2```) and use that to call another TouchAction method, it will work. Unsure if this an issue with the Appium version or the perform() method not clearing the command queue (if it's even meant to do that).

**Comment by mykola-mokhnach** [comment]
The java client cleans up actions chain every time you call _perform_. For this particular case this means that the _release_ call will fail with NoSuchElementException, since it is executed on the clean chain, which is, actually, happening.

Try this chain instead:

```
actions.longPress(element1).waitAction(3000).release().perform();
```

**Comment by alexandlazaris** [comment]
Woops sorry @mykola-mokhnach , the above code was meant to be release followed by perform, I was experimenting 😓 😅 

Same result either way. Does not allow another action to be performed.

**Comment by mykola-mokhnach** [comment]
Is your java client is at the recent version 5.0.3?

**Comment by alexandlazaris** [comment]
Java version is 1.8.0_131

Not the same as java client I assume?

**Comment by alexandlazaris** [comment]
Ahh @mykola-mokhnach  it's 4.1.2. Currently performing an update to latest.
