### ISSUE TITLE
Unable to swipe from page to page on an iOS pagination

### ISSUE THREAD

**Issue by DeepthiBalla** [appium/appium#9182]
## The problem
Unable to swipe from page to page on an iOS pagination. i would like to perform swiping from page to page on an iOS pagination and perform something on each page but could not swipe to immediate next page itself
## Environment

* Appium Version 3.0.0.2
iOS 10
real device - iphone 6s
Language - c#

code-      
            Dictionary<string, string> swipeObject = new Dictionary<string, string>();
            swipeObject.Add("direction", "right");
          
            ((IJavaScriptExecutor)testiOSdriver).ExecuteScript("mobile: swipe", swipeObject);
         
        }

I am not getting an error plus it is not swiping to next page, just staying in the first page and result of the test is pass, can you please let me if i am missing anything in the code

**Comment by mykola-mokhnach** [comment]
Try to swipe on the particular element, which handles the event, rather than swiping the whole screen. There is also _mobile: scroll_ endpoint, which might be useful.

Closing this issue as non Appium-related.

**Comment by DeepthiBalla** [comment]
i need to swiping whole screen, because elements in each page change dynamically, so can't swipe to a particular element, as the elements in the page change dynamically
