### ISSUE TITLE
error

### ISSUE THREAD

**Issue by bensandra** [appium/appium#9183]
C:\Users\sandra\AppData\Roaming\npm\node_modules\appium\node_modules\heapdump>if
 not defined npm_config_node_gyp (node "C:\Program Files\Nodejs\node_modules\npm
\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else
(node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\Nodejs\node_modules\npm\nod
e_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at C:\Program Files\Nodejs\node_modules\npm\node_modules\node
-gyp\lib\configure.js:404:11
gyp ERR! stack     at C:\Program Files\Nodejs\node_modules\npm\node_modules\grac
eful-fs\polyfills.js:264:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\Nodejs\\node.exe" "C:\\Program Files\\Nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\sandra\AppData\Roaming\npm\node_modules\appium\node_module
s\heapdump
gyp ERR! node -v v6.11.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
C:\Users\sandra\AppData\Roaming\npm
`-- appium@1.6.5

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.x (node_modules\appiu
m\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"
})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: heapdump@0.3.9 (node_modules\app
ium\node_modules\heapdump):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: heapdump@0.3.9 install: `node-gy
p rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

**Comment by mykola-mokhnach** [comment]
I assume the error there is pretty clear:

> gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.

Python should be installed and the PYTHON environment variable should be set.

**Comment by hemano** [comment]
This is not merely going to go away by setting the path.

before running npm install -g appium you need to run below command:

npm --add-python-to-path='true' --debug install --global windows-build-tool

https://github.com/felixrieseberg/windows-build-tools/issues/56
