### ISSUE TITLE
Null pointer exception (element not found) when clicking on element via Jenkins run

### ISSUE THREAD

**Issue by vjmaiky** [appium/appium#9184]
## The problem
I get null pointer exception the i try to click on an element while i run tests with Jenkins. If i run the tests locally with Intellij it is working with no problems.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7
* Node.js version (unless using Appium.app|exe): v7.4.0
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: iPhone 6+ 10.3.2

## Link to Appium logs
https://gist.github.com/vjmaiky/c7a924ef0fddf0710564c043a7cdee2d
## Code To Reproduce Issue [ Good To Have ]
**# Setup:**
    private static AppiumDriverLocalService createService() throws IOException, ParseException {
        Map<String, String> env = new HashMap<>(System.getenv());
        env.put("PATH", "/usr/local/bin:" + env.get("PATH"));

        service = AppiumDriverLocalService
                .buildService(new AppiumServiceBuilder()
                        .usingDriverExecutable(new File(nodeJS))
                        .withAppiumJS(new File(appiumJS))
                        .withIPAddress(getIP())
                        .usingAnyFreePort()
                        .withEnvironment(env)
                        .withStartUpTimeOut(120, TimeUnit.SECONDS)
//                        .withArgument(Arg.LOG_LEVEL, "warn"));
                        .withArgument(Arg.LOG_LEVEL, "debug"));

        MyLogger.log.info("+++++++++++++++++++++++ STARTING APPIUM SERVER ++++++++++++++++++++++");
        MyLogger.log.info(String.format(
                "Appium server running for device with UDID: " + getDeviceId()));
        MyLogger.log.info("++++++++++++++++++ STARTED APPIUM SERVER ++++++++++++++++++: " + service.getUrl());
        return (AppiumDriverLocalService) service;
    }

    public static void createiOSDriver() throws IOException, ParseException {
        String device = getDeviceId();
        try {
            deviceID = device;
            if (useDevice(deviceID)) {
                queueUp();
                gracePeriod();
                MyLogger.log.info("Trying to create new Driver for device: " + device);
                createService().start();
                Android.driverIos = getNewDriver((AppiumDriverLocalService) service, getCaps());
                leaveQueue();
            }
        } catch (Exception e) {
            e.printStackTrace();
            //Ignore and try next device
        }
    }

**# Test**
    @Test
    public void unlockAppWithPin() {
        inflightiOS.pinCode.unlockWithPinCode(1, 1, 1, 1, 1, 1);
    }

    public PinCode unlockWithPinCode(int digit1, int digit2, int digit3, int digit4, int digit5, int digit6) {
        try {
            MyLogger.log.info("dismiss touch id alert");
            try {
                WebElement alert = Android.driverIos.findElement(touchIdAlert);
                if (alert.isDisplayed()) {
                    MyLogger.log.info(alert + " Was found and now we are dismissing it");
                    gestures.clickOn(cancelTouchIdAlert);
                }
            } catch (WebDriverException e) {
                //do nothing
            }
            MyLogger.log.info("Entering pin digits");
            click_digit(digit1);
            click_digit(digit2);
            click_digit(digit3);
            click_digit(digit4);
            click_digit(digit5);
            click_digit(digit6);
            return this;
        } catch (NoSuchElementException e) {
            throw new AssertionError("Cannot tap on pincode number to access contacts");
        }
    }

    public PinCode click_digit(int i) {
        try {
            String pinNumber = Integer.toString(i);
//            String pinNumber = "" + i;
            MyLogger.log.info("Tap on pincode number: " + pinNumber + " button from FTW");
            Android.driverIos.getPageSource();
            gestures.clickOn(By.id(pinNumber));
            return this;
        } catch (NoSuchElementException e) {
            throw new AssertionError("Cannot tap on pincode number: " + i + "to access contacts");
        }
    }

**Comment by vjmaiky** [comment]
Click method:
   //click on mobile element of type By
    public void clickOn(By element) {
        waithelper.waitForElementVIsibilityIOS(element);
        Android.driverIos.findElement(element).click();
    }

wait method:
    public void waitForElementVIsibilityIOS(By element) {
        FluentWait<IOSDriver> wait = new FluentWait<IOSDriver>(Android.driverIos).withTimeout(20, TimeUnit.SECONDS).ignoring(NoSuchElementException.class);
        wait.until(ExpectedConditions.visibilityOfElementLocated(element));
    }

**Comment by mykola-mokhnach** [comment]
Can you please format the description properly and enclose code examples into [triple backticks](https://help.github.com/articles/creating-and-highlighting-code-blocks/)?

**Comment by mykola-mokhnach** [comment]
I see the exception is happening in java code rather than the server code. Please report your problem to https://github.com/appium/java-client

**Comment by vjmaiky** [comment]
i`ll update to java 5.0.2 and if it`s still happening i`ll post an issue to them; thanks

**Comment by vjmaiky** [comment]
seems that with the new library from java it is working
