### ISSUE TITLE
Appium iPad iOS Simulator launch app but as iPhone app

### ISSUE THREAD

**Issue by avrahamShutterFly** [appium/appium#9186]
## The problem

The issue is that when I try to launch app on iPad simulator is launch but as iPhone app and not as "iPad app"

## Environment

* Appium version: 1.6.5-betta 
* Desktop OS/version used to run Appium: mac 
* Node.js version: v8.2.1
*  iOS iPadAir 2 
* simulator 9.3

**Comment by mykola-mokhnach** [comment]
Is your issue reproducible manually? Does it make any difference if you stop the app started by the automated test and then open it manually?

**Comment by avrahamShutterFly** [comment]
@mykola-mokhnach Thanks for your quick reply,  It's not working both manually and automated by test):

**Comment by mykola-mokhnach** [comment]
Then I don't think it has something to do with Appium. Check the issue with your developers.

**Comment by avrahamShutterFly** [comment]
@mykola-mokhnach Maybe there is a problem WDA build?

**Comment by avrahamShutterFly** [comment]
Please Help!!

**Comment by jlipps** [comment]
@avrahamShutterFly if your app won't even launch manually then there's nothing WDA or Appium can do to help. As @mykola-mokhnach said, you should consult your developers until you get a working build that you can launch on the simulator manually.

**Comment by avrahamShutterFly** [comment]
Thanks @jlipps  @mykola-mokhnach  , I ask the team leader of iOS team and he told me that the app file was not config Right i create a new build for app file. and now it's working.
