### ISSUE TITLE
Unable to open URL in Safari. Appium does not work in Selenium grid for Browser Testing.

### ISSUE THREAD

**Issue by Tverdomi** [appium/appium#9188]
## The problem

Unable to open URL in Safari.
Appium does not work in Selenium grid for Browser Testing.
 
## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.0-beta 
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS Sierra Version 10.12.6
* Node.js version (unless using Appium.app|exe): Node version is 6.11.2
* Mobile platform/version under test:10.3.3
* Real device or emulator/simulator:Real device
* Appium CLI or Appium.app|exe:Appium CLI

## Details

Do not navigate to the URL

[debug] [JSONWP Proxy] Proxying [POST /url] to [POST http://localhost:8100/session/E60044AC-94D5-49E7-8B5A-3893DE4B5479/url] with body: {"url":"https://google.ch"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":"Failed to open https://google.ch","sessionId":"E60044AC-94D5-49E7-8B5A-3893DE4B5479","status":13}
[HTTP] <-- POST /wd/hub/session/44dd7fc4-ea6a-46c3-8bb5-5d8f2cde6425/url 500 134 ms - 203 

Instead of that set URL to appointed.io

## Link to Appium logs

https://gist.github.com/Tverdomi/50119ed1599a59b812844f940c304bb4

## Code To Reproduce Issue [ Good To Have ]

1) Selenium hub 2) Proxy 3) appium node

1) java -jar selenium-server-standalone-3.5.3.jar -role hub
2) ios_webkit_debug_proxy -c c81bd81ebb9c7b41d282a6a244d11e51af827ff0:27753 -d 
3) appium --nodeconfig nodeconfig.json
[IssueCode.zip](https://github.com/appium/appium/files/1291743/IssueCode.zip)

**Comment by mykola-mokhnach** [comment]
What if you set **safariInitialUrl** capability to _https://google.ch_?

**Comment by Tverdomi** [comment]
String url = "https://google.ch";		
capabilities.setCapability("safariInitialUrl", url);

Navigation is OK. but the next get is still a crash.

**Comment by mykola-mokhnach** [comment]
Created a PR to fix the problem: https://github.com/appium/appium-xcuitest-driver/pull/522

**Comment by jamesvanhorn** [comment]
I updated to xcuitest-driver 2.47.1 and i still see this issue. Any ideas?

[HTTP] --> POST /wd/hub/session/e347c361-5daa-4c9c-8f41-9a14095867ea/url {"url":"appName://Settings?modal=1"}
[debug] [MJSONWP] Calling AppiumDriver.setUrl() with args: ["appName://Settings?modal=1","e347c361-5daa-4c9c-8f41-9a14095867ea"]
[debug] [XCUITest] Executing command 'setUrl'
[debug] [JSONWP Proxy] Proxying [POST /url] to [POST http://localhost:8100/session/DD2E4986-3B32-4359-B4D8-EA5C7FF33C9D/url] with body: {"url":"appName://Settings?modal=1"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":"Failed to open appName://Settings?modal=1","sessionId":"DD2E4986-3B32-4359-B4D8-EA5C7FF33C9D","status":13}
[HTTP] <-- POST /wd/hub/session/e347c361-5daa-4c9c-8f41-9a14095867ea/url 500 87 ms - 215

**Comment by mykola-mokhnach** [comment]
The fix is merged to master, but it's not tagged yet. Wait for the next driver version tag.

**Comment by jamesvanhorn** [comment]
My mistake @mykola-mokhnach i misread the branch tags. Thanks.

**Comment by imurchie** [comment]
This should be in `appium-xcuitest-driver@2.47.2`.
