### ISSUE TITLE
Empty string as result of getText() call

### ISSUE THREAD

**Issue by a-en** [appium/appium#9189]
## The problem

Empty string is returned as result of getText() call for View. I have to find nested TextView in order to get actual text. It is ReactNative application on Android.

Structure looks like that:

<android.view.View accessibilityLabel="my-label">
  <android.widget.TextView>Text123</android.widget.TextView>
</android.view.View>
  

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Desktop OS/version used to run Appium: Mac OS X 10.12.6
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Android 5.1, Android 7.1.1 
* Real device or emulator/simulator: emulator (Nexus 5X)
* Appium CLI or Appium.app|exe: Version 1.2.0-beta.3 (1.2.0-beta.3)

## Code

`driver.findElement(By.id('my-label')).getText()` -> empty string

**Comment by mykola-mokhnach** [comment]
Why do you think it is a bug? A view can contain multiple controls - what getText should return in such case?

**Comment by a-en** [comment]
@mykola-mokhnach, I expected it to work in the same way as for web -- if there are a few nested elements and each of them contains text, all of these texts should be returned

<div id="parent">
  <span>text1  <p>text2</p></span>
  <span>text3</span>
</div>

so as result of `driver.findElement(By.id('parent')).getText` I expect to see "text1 text2\ntext3". Again, it works in this way for web and it makes sense for me - texts of all visible elements within container should be returned. If someone needs particular text, then child element should be located additionally.

**Comment by jlipps** [comment]
Unfortunately @a-en Appium just returns the text of each view, not the view plus any subviews. This does differ from web but there would be insane performance decrease if we did this on mobile. If you want to do this, you should use an xpath query to get all descendants of the node you're interested in, and iterate through them getting the text of each.

**Comment by a-en** [comment]
Thanks @jlipps for explanation. Just some additional details in that context -- the thing is that on iOS nested elements of this view are not available. So that I had to call getText() for view itself & then parse results text. For Android the same call returned empty string.

I realize _how_ it could be fixed from my side, but unfortunately it breaks concept 'written once, works in same way for various platforms' and makes me write 'platform-based' code.

**Comment by jlipps** [comment]
@a-en I feel your pain. If there were fewer performance considerations at stake, I think you've made a good case for Appium to try to normalize these behaviors. I would look at a PR that hid this standardization behind a capability of some kind!
