### ISSUE TITLE
RoutingHTTPServer not found build using xcodebuild

### ISSUE THREAD

**Issue by navinjethani** [appium/appium#9192]
2017-09-11 08:27:36.766795-0700 XCTRunner[1423:373859] Running tests...
2017-09-11 08:27:36.804966-0700 XCTRunner[1423:373859] The bundle “WebDriverAgentRunner” couldn’t be loaded because it is damaged or missing necessary resources. Try reinstalling the bundle.
2017-09-11 08:27:36.805030-0700 XCTRunner[1423:373859] (dlopen_preflight(/var/containers/Bundle/Application/B2853321-46AF-4391-9558-CBAEF385DB91/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner): Library not loaded: @rpath/RoutingHTTPServer.framework/RoutingHTTPServer
  Referenced from: /private/var/containers/Bundle/Application/B2853321-46AF-4391-9558-CBAEF385DB91/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/WebDriverAgentLib
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/B2853321-46AF-4391-9558-CBAEF385DB91/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer: required code signature missing for '/private/var/containers/Bundle/Application/B2853321-46AF-4391-9558-CBAEF385DB91/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer'
)
2017-09-11 08:27:45.300 xcodebuild[8559:144039] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}

 ./node_modules/.bin/appium --version 
1.6.5

I am able to build WebDriverAgent and install WebDriverAgent using xcode.
iPhone shows a white screen

**Comment by mykola-mokhnach** [comment]
Try to reinstall Appium and make sure your current user has R/W permissions in the folder where Appium modules are installed.

**Comment by navinjethani** [comment]
tried uninstalling appium & changed rw permissions also (few times)

same error
====================================================
2017-09-11 11:09:37.710987-0700 XCTRunner[1558:412489] The bundle
“WebDriverAgentRunner” couldn’t be loaded because it is damaged or missing
necessary resources. Try reinstalling the bundle.
2017-09-11 11:09:37.711055-0700 XCTRunner[1558:412489]
(dlopen_preflight(/var/containers/Bundle/Application/36F51F2E-66DE-4225-8DB0-91EFDCB1D9B7/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner):
Library not loaded: @rpath/RoutingHTTPServer.framework/RoutingHTTPServer
  Referenced from:
/private/var/containers/Bundle/Application/36F51F2E-66DE-4225-8DB0-91EFDCB1D9B7/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/WebDriverAgentLib
  Reason: no suitable image found.  Did find:

/private/var/containers/Bundle/Application/36F51F2E-66DE-4225-8DB0-91EFDCB1D9B7/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer:
required code signature missing for
'/private/var/containers/Bundle/Application/36F51F2E-66DE-4225-8DB0-91EFDCB1D9B7/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer'
)
2017-09-11 11:09:46.479 xcodebuild[10357:171693] Error
Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit,
operation never finished bootstrapping - no restart will be attempted"
UserInfo={NSLocalizedDescription=Early unexpected exit, operation never
finished bootstrapping - no restart will be attempted}

Testing failed:
    Test target WebDriverAgentRunner encountered an error (Early unexpected
exit, operation never finished bootstrapping - no restart will be attempted)
==========================

**Comment by mykola-mokhnach** [comment]
> Reason: no suitable image found. Did find:
/private/var/containers/Bundle/Application/B2853321-46AF-4391-9558-CBAEF385DB91/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer: required code signature missing for 

This means the bundle is not signed properly and thus cannot be installed on the device. Make sure you set up WDA signing properly.

**Comment by navinjethani** [comment]
I am able to build using xcode

**Comment by mykola-mokhnach** [comment]
Did you follow [real device setup tutorial](https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md) ?

**Comment by navinjethani** [comment]
I got the WebDriverAgent running on iosDevice.
Followed the tutorial & redid everytime.

Thx for your help, really appreciate a lot
