### ISSUE TITLE
allowTouchIdEnroll not recognized by appium

### ISSUE THREAD

**Issue by chickenbeef** [appium/appium#9194]
## The problem

When setting the allowTouchIdEnroll desired capability to true, it has no effect. Appium does not recognize the key and Touch ID enrollment is disabled when the simulator starts up. Terminal has been granted accessibility permission to control this computer.

> [BaseDriver] The following capabilities were provided, but are not recognized by appium: allowTouchIdEnroll.

## Environment

* Appium v1.6.6 beta 4 and v1.7.0-beta
* MacOS Sierra 10.12.6
* Node v8.2.1
* iOS
* Simulator
* Appium CLI or Appium.app|exe: Appium node
* XCode 9

## Link to Appium logs

https://gist.github.com/chickenbeef/d1ff025324945c6b738d461f31a0074f

**Comment by mykola-mokhnach** [comment]
This capability has been deprecated in the recent beta. Also there is a possibility now to explicitly set touch enroll feature state. See https://github.com/appium/java-client/commit/6f3351dfa0b77ec7d3997ef5ac935f26e4b63e10 for more details
