### ISSUE TITLE
Unable to uninstall APK under Android 8 Oreo

### ISSUE THREAD

**Issue by appiumnovice** [appium/appium#9196]
## The problem

I have the error "Unable to uninstall APK ... 'Command '/Users/xxx/Library/android/sdk/platform-tools/adb -P 5037 -s 013a3a8de3d93345 uninstall com.xxx.fusion' exited with code 255'"
when I launch test on Android 8.0 (Oreo) on Emulator and on Device Nexus 5x.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Desktop OS/version used to run Appium: OSX 12.10.5
* Mobile platform/version under test: Emulator from Android Studio 3 beta 5 with Android 8.0
* Real device or emulator/simulator: Nexus 5x with Android 8.0
* Appium CLI or Appium.app|exe: CLI

## Details

On emulator, after the creation of the emulator, the app is installed once with success by Appium and the test is correctly run.
The reinstallation of the app for the next test doesn't work.
So I uninstalled the app manually and tried again : same error.

On device, I have the same error.

## Link to Appium logs

Appium server log
https://gist.github.com/appiumnovice/c192975a6737ae8d18ac6b8a2f3f8371

**Comment by mykola-mokhnach** [comment]
Do you get the same error if this command is executed manually? What error description do you see in the terminal?
Also, make sure your platform tools are at the recent version.

**Comment by appiumnovice** [comment]
Yes, I have an error too :

adb -P 5037 -s 013a3a8de3d93345 uninstall com.sncf.fusion

Exception occurred while executing:
java.lang.IllegalArgumentException: Unknown package: com.sncf.fusion
	at com.android.server.pm.Settings.isOrphaned(Settings.java:4400)
	at com.android.server.pm.PackageManagerService.isOrphaned(PackageManagerService.java:21418)
	at com.android.server.pm.PackageManagerService.deletePackageVersioned(PackageManagerService.java:18492)
	at com.android.server.pm.PackageInstallerService.uninstall(PackageInstallerService.java:913)
	at com.android.server.pm.PackageManagerShellCommand.runUninstall(PackageManagerShellCommand.java:912)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:134)
	at android.os.ShellCommand.exec(ShellCommand.java:96)
	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:21717)
	at android.os.Binder.shellCommand(Binder.java:573)
	at android.os.Binder.onTransact(Binder.java:473)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2644)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:3485)
	at android.os.Binder.execTransact(Binder.java:674)

**Comment by mykola-mokhnach** [comment]
Yep, it looks like since 7.1 Android's pm tool handles missing package uninstall differently. Related issue reports:
https://jira.lineageos.org/browse/BUGBASH-999?attachmentViewMode=list
https://github.com/openstf/stf/issues/448

@imurchie Looks like we need to handle this properly on our side as well

**Comment by appiumnovice** [comment]
For information, I didn't have this problem with Android 7.1.2 previously installed on Nexus 5x.

**Comment by mykola-mokhnach** [comment]
the fix is merged to 1.7.0-beta. Please update and let us know if it works

**Comment by appiumnovice** [comment]
Thanks for your new release :)

I have many differents results.

1. The first time I run a test, I obtained the error "Unable to uninstall APK"

2. After a new try, I obtained the error "Activity used to start app doesn't exist or cannot be launched!"

https://gist.github.com/appiumnovice/c192975a6737ae8d18ac6b8a2f3f8371#file-log-with-appium-1-7-0-beta

**Comment by imurchie** [comment]
Can you delete the unlock helper? It seems to not be launchable for some reason?

**Comment by mykola-mokhnach** [comment]
Or set the **skipUnlock** capability to _true_

**Comment by appiumnovice** [comment]
I tried the 2 solutions : remove Unlock before run the test and add the capability "skipUnlock".
Without success.

https://gist.github.com/appiumnovice/c192975a6737ae8d18ac6b8a2f3f8371#file-with-skipunlock

**Comment by mykola-mokhnach** [comment]
The recent log looks very messy to me. It looks like several operations are being concurrently executed at the same time and this causes problems.

**Comment by appiumnovice** [comment]
OK. I stoped all others tests which run in parallel.

I tried 2 processes:

1. The app is already installed (manually)
-> The test run, despite the error "Activity used to start app doesn't exist or cannot be launched!" and "Unable to uninstall APK"
https://gist.github.com/appiumnovice/c192975a6737ae8d18ac6b8a2f3f8371#file-app-still-installed

2. The app is not installed and all Appiums tools are uninstalled
-> The app is not installed
https://gist.github.com/appiumnovice/c192975a6737ae8d18ac6b8a2f3f8371#file-app-is-not-installed

**Comment by mykola-mokhnach** [comment]
OK, found the problem.

**Comment by imurchie** [comment]
This should be fixed if you get the latest beta (`npm uninstall -g appium && npm install -g appium@beta`).

**Comment by appiumnovice** [comment]
Yes, it works !
Thanks to you for your reactivity  :)
You can close this issue.

**Comment by imurchie** [comment]
All thanks go to @mykola-mokhnach !

**Comment by omidrezaaa** [comment]
@imurchie hi, could you help me how can i run your solution, i'm beginner and have same error:
npm uninstall -g appium && npm install -g appium@beta

**Comment by KazuCocoa** [comment]
The command was uninstalling old appium and installing new one.
It meant to use newer appium.

**Comment by remmcal** [comment]
I did: 
clean project
rebuild project 
and fix that problem
