### ISSUE TITLE
support SafariViewService-based webviews

### ISSUE THREAD

**Issue by alexsunder** [appium/appium#9197]
Sorry, I'm new with the Appium and probably this is a duplicate issue. But I'm really confusing. Please, help me with this issue.

## The problem

I have a hybrid iOS app. I'm trying to run a test on a real iOS device and on Simulator. First I run it on a real device and it works fine, but if I run it on the simulator it crashes on the getContextHandles() step. I would appreciate if you could guide me what I'm doing wrong or if you could fix this if this is a bug.

## Environment

* Appium version (or git revision) that exhibits the issue: Appium v. 1.6.5
* Last Appium version that did not exhibit the issue (if applicable): I started from 1.6.5
* Desktop OS/version used to run Appium: macOS Sierra 10.12.6
* Node.js version (unless using Appium.app|exe): 8.4.0
* Mobile platform/version under test: 10.3.1
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: Appium from Command Line

## Link to Appium logs

https://gist.github.com/alexsunder/fedb59624f208cc5d847758313908621

## Code To Reproduce Issue [ Good To Have ]

Capabilities:

       caps.setCapability("deviceName", "iPhone 6");
       caps.setCapability("platformName", Platform.IOS);
       caps.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, "100");
       caps.setCapability(MobileCapabilityType.PLATFORM_VERSION, "10.3.1");
       caps.setCapability(MobileCapabilityType.UDID, "636C6053-1E84-4988-80EF-CBEDAD19081B");
       caps.setCapability("automationName", "XCUITest");
       caps.setCapability("app", "/Users/fes/Desktop/Sim.app");
       caps.setCapability("browserName", "");
       caps.setCapability("useNewWDA", true);

Java code:

        IOSDriver<IOSElement> driver = iPhone7SimulatorCapabilities();
        driver.findElement(By.xpath("//XCUIElementTypeButton[@name=\"Log In\"]")).click();
        Thread.sleep(12000);
        // getting contexts and switch to webView
        List<String> handles = new ArrayList<>();
        handles.addAll(driver.getContextHandles()); // doesn't work on simulator
        driver.context(handles.get(1));

**Comment by mykola-mokhnach** [comment]
Do you get the same error in Appium 1.7.0-beta?

**Comment by alexsunder** [comment]
Didn't install yet 1.7.0 yet. I'll check it

**Comment by alexsunder** [comment]
Yes. Same issue with Appium 1.7.0-beta - it works on a real device but it crashes in a simulator.

**Comment by mykola-mokhnach** [comment]
@imurchie FYI

**Comment by jlipps** [comment]
@imurchie here are the log lines of interest:

```
[debug] [RemoteDebugger] Found separate bundleId 'com.apple.SafariViewService' acting as proxy for 'com.ecwid.adminapp', with app id 'PID:35312'
[debug] [RemoteDebugger] Trying out the possible app ids: PID:35312
[debug] [RemoteDebugger] Selecting app PID:35312 (try #20 of 20)
[debug] [RemoteDebugger] Sending '_rpc_forwardGetListing:' message to remote debugger
[debug] [RemoteDebugger] Receiving data from remote debugger: '{"__argument":{"WIRApplicationIdentifierKey":"PID:35312","WIRListingKey":{}},"__selector":"_rpc_applicationSentListing:"}'
[debug] [RemoteDebugger] Received response from socket send: '["PID:35312",{}]'
[debug] [RemoteDebugger] Page changed: {}
[debug] [RemoteDebugger] Empty page dictionary received
[debug] [RemoteDebugger] Error checking application: 'Error: Empty page dictionary received'. Retrying connection
[RemoteDebugger] Error: Could not connect to a valid app after 20 tries.
```

any ideas? not sure what it means to have an empty page dict

**Comment by imurchie** [comment]
This means that we don't actually have any way of automating SafariViewService-based webviews. This is only the second time anyone has ever brought them up. We could probably figure them out, but the demand is low.

**Comment by jlipps** [comment]
@alexsunder can you use the regular UI webviews in your app instead?

**Comment by alexsunder** [comment]
I'll ask developers. Thank you for the information and explanation

**Comment by alexsunder** [comment]
I got the answer from the developer. He said that we can't use the regular UI webviews and the reason is that the Safari's views are safer and more advanced.

**Comment by jlipps** [comment]
@alexsunder I see. Unfortunately Appium does not currently support SavariViewService webviews. I will keep this issue open as an enhancement request.

**Comment by alexsunder** [comment]
OK. Thank you

**Comment by cqqian** [comment]
Vote for this support too. I also meet the same problem, when my app open SafariViewService-based webviews, it can not locate the elements. Thanks!

**Comment by AuriStorm** [comment]
Faced a similar problem.
In my case this code works, but seems like unstable:
(appium 1.7.2 / python client / ios 11.2 / native app)
```python
#invoke webview page
sleep(n)
driver.switch_to.context(driver.contexts[1]) #jump to webview
#work with webview elements
#invoke action that close webview
driver.switch_to.context(driver.contexts[0]) #jump to native app
#work with native app elements
```

The problem is, if the webview closes too fast (or manually setted sleep for few sec) then I can't interract with native app. Attempt to switch context raise already mentioned error:
```
[debug] [RemoteDebugger] Selecting app PID:38438 (try #20 of 20)
[debug] [RemoteDebugger] Sending '_rpc_forwardGetListing:' message to remote debugger
[debug] [RemoteDebugger] Receiving data from remote debugger: '{"__argument":{"WIRApplicationIdentifierKey":"PID:38438","WIRListingKey":{}},"__selector":"_rpc_applicationSentListing:"}'
[debug] [RemoteDebugger] Received response from socket send: '["PID:38438",{}]'
[debug] [RemoteDebugger] Page changed: {}
[debug] [iOS] Remote debugger notified us of a new page listing: {"appIdKey":"38438","pageArray":[]}
[debug] [iOS] No key id found. Choosing first id from page array
[debug] [iOS] We do not appear to have window set yet, ignoring
[debug] [RemoteDebugger] Empty page dictionary received
[debug] [RemoteDebugger] Error checking application: 'Error: Empty page dictionary received'. Retrying connection
[debug] [RemoteDebugger] Error: Empty page dictionary received
```

**Comment by nenaddrop** [comment]
Just hit the wall with this one. Is there any plans to start supporting this type of webviews in the future?

**Comment by mykola-mokhnach** [comment]
They are supported
