### ISSUE TITLE
swipe is not working on iOS10 on appium 1.6.5

### ISSUE THREAD

**Issue by vutukuriswathi** [appium/appium#9199]
problem:
swipe is not working on iOS10
## Environment

Appium:1.6.5
Mac OS:10.11.6
appium java client: tried on both 4.0.0 and 5.0.0
iOS device:10.0

## Details

I tried the below code
JavascriptExecutor js = (JavascriptExecutor) driver;
 HashMap swipeObject = new HashMap();
  swipeObject.put("direction", "right");
js.executeScript("mobile: swipe", swipeObject);

and also this code as well
Dimension size = driver.manage().window().getSize();
        int startx = size.getWidth() / 2;
        int starty = (int) (size.getHeight() * 0.8);
        int endy = (int) (size.getHeight() * 0.2);

TouchAction action = new TouchAction(driver);
      action.press(startx,starty).waitAction(1000).moveTo(startx,endy).release().perform();

## Link to Appium logs

/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/bin/java -ea -Didea.test.cyclic.buffer.size=1048576 "-javaagent:/Applications/IntelliJ IDEA CE.app/Contents/lib/idea_rt.jar=50804:/Applications/IntelliJ IDEA CE.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath "/Applications/IntelliJ IDEA CE.app/Contents/lib/idea_rt.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/testng/lib/testng-plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/jaccess.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/jfxswt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/lib/packager.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/lib/tools.jar:/Users/gunuputis4r/Documents/Intellijiworkspace/KidsIviewPhonesAutomation/target/test-classes:/Users/gunuputis4r/.m2/repository/io/appium/java-client/5.0.0/java-client-5.0.0.jar:/Users/gunuputis4r/.m2/repository/org/seleniumhq/selenium/selenium-java/3.5.2/selenium-java-3.5.2.jar:/Users/gunuputis4r/.m2/repository/org/seleniumhq/selenium/selenium-chrome-driver/3.5.2/selenium-chrome-driver-3.5.2.jar:/Users/gunuputis4r/.m2/repository/org/seleniumhq/selenium/selenium-edge-driver/3.5.2/selenium-edge-driver-3.5.2.jar:/Users/gunuputis4r/.m2/repository/org/seleniumhq/selenium/selenium-firefox-driver/3.5.2/selenium-firefox-driver-3.5.2.jar:/Users/gunuputis4r/.m2/repository/org/seleniumhq/selenium/selenium-ie-driver/3.5.2/selenium-ie-driver-3.5.2.jar:/Users/gunuputis4r/.m2/repository/org/seleniumhq/selenium/selenium-opera-driver/3.5.2/selenium-opera-driver-3.5.2.jar:/Users/gunuputis4r/.m2/repository/org/seleniumhq/selenium/selenium-remote-driver/3.5.2/selenium-remote-driver-3.5.2.jar:/Users/gunuputis4r/.m2/repository/org/seleniumhq/selenium/selenium-safari-driver/3.5.2/selenium-safari-driver-3.5.2.jar:/Users/gunuputis4r/.m2/repository/cglib/cglib-nodep/3.2.4/cglib-nodep-3.2.4.jar:/Users/gunuputis4r/.m2/repository/org/apache/commons/commons-exec/1.3/commons-exec-1.3.jar:/Users/gunuputis4r/.m2/repository/commons-codec/commons-codec/1.10/commons-codec-1.10.jar:/Users/gunuputis4r/.m2/repository/commons-logging/commons-logging/1.2/commons-logging-1.2.jar:/Users/gunuputis4r/.m2/repository/org/w3c/css/sac/1.3/sac-1.3.jar:/Users/gunuputis4r/.m2/repository/net/sourceforge/cssparser/cssparser/0.9.23/cssparser-0.9.23.jar:/Users/gunuputis4r/.m2/repository/com/google/guava/guava/23.0/guava-23.0.jar:/Users/gunuputis4r/.m2/repository/com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9.jar:/Users/gunuputis4r/.m2/repository/com/google/errorprone/error_prone_annotations/2.0.18/error_prone_annotations-2.0.18.jar:/Users/gunuputis4r/.m2/repository/com/google/j2objc/j2objc-annotations/1.1/j2objc-annotations-1.1.jar:/Users/gunuputis4r/.m2/repository/org/codehaus/mojo/animal-sniffer-annotations/1.14/animal-sniffer-annotations-1.14.jar:/Users/gunuputis4r/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:/Users/gunuputis4r/.m2/repository/net/sourceforge/htmlunit/htmlunit/2.27/htmlunit-2.27.jar:/Users/gunuputis4r/.m2/repository/net/sourceforge/htmlunit/htmlunit-core-js/2.27/htmlunit-core-js-2.27.jar:/Users/gunuputis4r/.m2/repository/net/sourceforge/htmlunit/neko-htmlunit/2.27/neko-htmlunit-2.27.jar:/Users/gunuputis4r/.m2/repository/org/apache/httpcomponents/httpcore/4.4.6/httpcore-4.4.6.jar:/Users/gunuputis4r/.m2/repository/org/apache/httpcomponents/httpmime/4.5.3/httpmime-4.5.3.jar:/Users/gunuputis4r/.m2/repository/org/eclipse/jetty/jetty-client/9.4.5.v20170502/jetty-client-9.4.5.v20170502.jar:/Users/gunuputis4r/.m2/repository/org/eclipse/jetty/jetty-http/9.4.5.v20170502/jetty-http-9.4.5.v20170502.jar:/Users/gunuputis4r/.m2/repository/org/eclipse/jetty/jetty-io/9.4.5.v20170502/jetty-io-9.4.5.v20170502.jar:/Users/gunuputis4r/.m2/repository/org/eclipse/jetty/jetty-util/9.4.5.v20170502/jetty-util-9.4.5.v20170502.jar:/Users/gunuputis4r/.m2/repository/net/java/dev/jna/jna/4.1.0/jna-4.1.0.jar:/Users/gunuputis4r/.m2/repository/net/java/dev/jna/jna-platform/4.1.0/jna-platform-4.1.0.jar:/Users/gunuputis4r/.m2/repository/junit/junit/4.12/junit-4.12.jar:/Users/gunuputis4r/.m2/repository/com/codeborne/phantomjsdriver/1.4.0/phantomjsdriver-1.4.0.jar:/Users/gunuputis4r/.m2/repository/org/seleniumhq/selenium/htmlunit-driver/2.27/htmlunit-driver-2.27.jar:/Users/gunuputis4r/.m2/repository/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar:/Users/gunuputis4r/.m2/repository/org/eclipse/jetty/websocket/websocket-api/9.4.5.v20170502/websocket-api-9.4.5.v20170502.jar:/Users/gunuputis4r/.m2/repository/org/eclipse/jetty/websocket/websocket-client/9.4.5.v20170502/websocket-client-9.4.5.v20170502.jar:/Users/gunuputis4r/.m2/repository/org/eclipse/jetty/websocket/websocket-common/9.4.5.v20170502/websocket-common-9.4.5.v20170502.jar:/Users/gunuputis4r/.m2/repository/xalan/serializer/2.7.2/serializer-2.7.2.jar:/Users/gunuputis4r/.m2/repository/xalan/xalan/2.7.2/xalan-2.7.2.jar:/Users/gunuputis4r/.m2/repository/xerces/xercesImpl/2.11.0/xercesImpl-2.11.0.jar:/Users/gunuputis4r/.m2/repository/xml-apis/xml-apis/1.4.01/xml-apis-1.4.01.jar:/Users/gunuputis4r/.m2/repository/org/seleniumhq/selenium/selenium-support/3.5.2/selenium-support-3.5.2.jar:/Users/gunuputis4r/.m2/repository/org/seleniumhq/selenium/selenium-api/3.5.2/selenium-api-3.5.2.jar:/Users/gunuputis4r/.m2/repository/com/google/code/gson/gson/2.8.1/gson-2.8.1.jar:/Users/gunuputis4r/.m2/repository/org/apache/httpcomponents/httpclient/4.5.3/httpclient-4.5.3.jar:/Users/gunuputis4r/.m2/repository/cglib/cglib/3.2.5/cglib-3.2.5.jar:/Users/gunuputis4r/.m2/repository/org/ow2/asm/asm/5.2/asm-5.2.jar:/Users/gunuputis4r/.m2/repository/org/apache/ant/ant/1.9.6/ant-1.9.6.jar:/Users/gunuputis4r/.m2/repository/org/apache/ant/ant-launcher/1.9.6/ant-launcher-1.9.6.jar:/Users/gunuputis4r/.m2/repository/commons-validator/commons-validator/1.6/commons-validator-1.6.jar:/Users/gunuputis4r/.m2/repository/commons-beanutils/commons-beanutils/1.9.2/commons-beanutils-1.9.2.jar:/Users/gunuputis4r/.m2/repository/commons-digester/commons-digester/1.8.1/commons-digester-1.8.1.jar:/Users/gunuputis4r/.m2/repository/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar:/Users/gunuputis4r/.m2/repository/org/apache/commons/commons-lang3/3.6/commons-lang3-3.6.jar:/Users/gunuputis4r/.m2/repository/commons-io/commons-io/2.5/commons-io-2.5.jar:/Users/gunuputis4r/.m2/repository/org/springframework/spring-context/4.3.10.RELEASE/spring-context-4.3.10.RELEASE.jar:/Users/gunuputis4r/.m2/repository/org/springframework/spring-aop/4.3.10.RELEASE/spring-aop-4.3.10.RELEASE.jar:/Users/gunuputis4r/.m2/repository/org/springframework/spring-beans/4.3.10.RELEASE/spring-beans-4.3.10.RELEASE.jar:/Users/gunuputis4r/.m2/repository/org/springframework/spring-core/4.3.10.RELEASE/spring-core-4.3.10.RELEASE.jar:/Users/gunuputis4r/.m2/repository/org/springframework/spring-expression/4.3.10.RELEASE/spring-expression-4.3.10.RELEASE.jar:/Users/gunuputis4r/.m2/repository/org/aspectj/aspectjweaver/1.8.10/aspectjweaver-1.8.10.jar:/Users/gunuputis4r/.m2/repository/org/openpnp/opencv/3.2.0-1/opencv-3.2.0-1.jar:/Users/gunuputis4r/.m2/repository/org/testng/testng/6.9.10/testng-6.9.10.jar:/Users/gunuputis4r/.m2/repository/com/beust/jcommander/1.48/jcommander-1.48.jar:/Users/gunuputis4r/.m2/repository/org/beanshell/bsh/2.0b4/bsh-2.0b4.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/testng/lib/jcommander.jar" org.testng.RemoteTestNGStarter -usedefaultlisteners false -socket50803 @w@/private/var/folders/6f/cm41jlqd0vbfmj_f6nwv7tf4sskhh6/T/idea_working_dirs_testng.tmp -temp /private/var/folders/6f/cm41jlqd0vbfmj_f6nwv7tf4sskhh6/T/idea_testng.tmp
objc[53467]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
[TestNG] Running:
  /Users/gunuputis4r/Library/Caches/IdeaIC2017.1/temp-testng-customsuite.xml
Sep 13, 2017 2:30:03 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS

org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Unhandled endpoint: /session/184902FC-9518-4CA8-BF42-0F056F813AC2/wda/element/E4604F68-52C1-4F7E-8860-3A2ADEF3F751/swipe -- http://localhost:8100/ with parameters {
    wildcards =     (
        "session/184902FC-9518-4CA8-BF42-0F056F813AC2/wda/element/E4604F68-52C1-4F7E-8860-3A2ADEF3F751/swipe"
    );
} (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.5.2', revision: '10229a9', time: '2017-08-21T17:29:55.15Z'
System info: host: 'WS054576', ip: '10.25.176.134', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_60'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities [{app=/Users/gunuputis4r/Documents/Intellijiworkspace/KidsIviewPhonesAutomation/src/test/resources/com/kidsIview/mobileApps/kidsiviewiphone.ipa, networkConnectionEnabled=false, bundleId=au.net.abc.kids-iview, databaseEnabled=false, deviceName=Abc_iPhone6plus, platform=MAC, platformVersion=10.0, webStorageEnabled=false, locationContextEnabled=false, browserName=, takesScreenshot=true, javascriptEnabled=true, udid=4c7399acc39cb0e3b8609e6d069c5f619700b70d, platformName=iOS}]
Session ID: 0f89923a-ca38-44e6-9cc4-847ae943b234

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:215)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:167)
	at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:82)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:45)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:89)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:641)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:577)
	at com.kidsIview.util.Util.swipeUp(Util.java:138)
	at com.kidsIview.tests.HomePageTest.checkHomePageSwiping(HomePageTest.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:127)

===============================================
Default Suite
Total tests run: 1, Failures: 1, Skips: 0
===============================================

Process finished with exit code 0

**Comment by mykola-mokhnach** [comment]
> Unhandled endpoint: /session/184902FC-9518-4CA8-BF42-0F056F813AC2/wda/element/E4604F68-52C1-4F7E-8860-3A2ADEF3F751/swipe 

Most likely you have an old WebDriverAgent version cached somewhere. Make sure it is deleted from the device and Xcode cache is clear.

**Comment by vutukuriswathi** [comment]
@mykola-mokhnach can you please tell me how to update the webdriverAgent version

**Comment by mykola-mokhnach** [comment]
The sources are updated together with Appium. However, it's up to you to clear the build cache and the runner application on the device.

**Comment by vutukuriswathi** [comment]
After i clear the cache it is running fine.Thanks a lot.

**Comment by Dheepthi** [comment]
How to clear the webdriverAgent cache?
