### ISSUE TITLE
@AndroidFindBys annotation is not working on appium java client 5.0.0

### ISSUE THREAD

**Issue by vutukuriswathi** [appium/appium#9200]
problem:
@AndroidFindBys annotation is not working on appium java client 5.0.0
	@AndroidFindBys({
			@AndroidFindBy(id = "au.net.abc.kidsiview:id/action_bar"),
			@AndroidFindBy(className = "android.widget.TextView")
	)
	public MobileElement pageHeading;

Error:
Incompatiable types error

The same is working fine on appium java client 4.0.0.

## Environment

Appium:1.6.5
Mac OS:10.11.6
appium java client: tried on both 4.0.0 and 5.0.0

**Comment by mykola-mokhnach** [comment]
Please report to https://github.com/appium/java-client

Closed as server-unrelated.
