### ISSUE TITLE
For now , npm install -g appium failed

### ISSUE THREAD

**Issue by yangheng** [appium/appium#9201]
## The problem

Today npm install -g appium failed  ，but some other npm packages all success . I tried many times.
Who can tell me why ? 

## Environment

* Node.js : v7.7.0
*NPM :v4.1.2

**Comment by mykola-mokhnach** [comment]
Most likely no-one unless you provide more details on the error.

**Comment by yangheng** [comment]
@mykola-mokhnach 
$ npm install appium@1.6.5 -g
npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/Cellar/node/7.9.0/bin/node" "/usr/local/bin/npm" "install" "appium@1.6.5" "-g"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0

npm ERR! shasum check failed for /var/folders/w3/nvln7hkd3wz0q7s9wwy8dd1w0000gn/T/npm-85484-a3528ede/registry.npmjs.org/appium/-/appium-1.6.5.tgz
npm ERR! Expected: cab50da890e9d2df9a25178fb1a8d802bf5c81e3
npm ERR! Actual:   1fbbc5d941dc990ee193d9dc28291d2f51e11889
npm ERR! From:     https://registry.npmjs.org/appium/-/appium-1.6.5.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kukuchong/.npm/_logs/2017-09-14T07_08_08_895Z-debug.log

**Comment by mykola-mokhnach** [comment]
It must be a problem with npm itself. Try, probably, some solutions, that Google advices, for example https://github.com/npm/npm/issues/2701

**Comment by jlipps** [comment]
Yes, this is usually a problem with your network, firewall, or npm itself.

**Comment by yangheng** [comment]
Thank you ! This is npm itself problem， and now installed  success after npm update latest version!!
