### ISSUE TITLE
Old Documentation in XCUITest Driver (iOS Real Devices)

### ISSUE THREAD

**Issue by PatrickDuncan** [appium/appium#9207]
## The problem

The iOS real devices documentation in:
https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md
is old compared to the one in this repository: https://github.com/appium/appium/blob/master/docs/en/drivers/ios-xcuitest-real-devices.md

**Comment by dpgraham** [comment]
Thanks for opening this.

**Comment by jlipps** [comment]
Thanks @PatrickDuncan. We're trying to consolidate all our docs in the main appium repo for the new docs site we are building. Not sure if we want to maintain docs on the xcuitest-driver repo as well. CC @imurchie @mykola-mokhnach
