### ISSUE TITLE
Appium iOS Safari Parallel execution

### ISSUE THREAD

**Issue by DanielPradoPino** [appium/appium#9209]
Appium version 1.7.0 beta

## Introduction
With the new XCode 9 Beta now we are able to have multiple iOS simulators running at the same time, I was able to run parallel appium executions in all of them while they are using Pure Native apps. 

## The problem
The problem arise when I am trying to automate 2 apps that use WebView or simply automating 2 safari test cases, it seem Appium tries to listen always from the same WebContent PID so second execution will not work as it will be throwing a "page has changed" issue.

Message in logs is "Found app id key 'PID: xxxx ' for bundle '.com.apple.mobilesafari' 

To fix this Appium should check all WebContent PID's.
Is any easy way to fix this?

Thanks!!!

**Comment by mykola-mokhnach** [comment]
Can you please attach the full log for failed session?

**Comment by DanielPradoPino** [comment]
Hi sure, thanks for reply, Basically the log is repeating itself until I break.

[appium parallel safari log.docx](https://github.com/appium/appium/files/1302860/appium.parallel.safari.log.docx)

**Comment by mykola-mokhnach** [comment]
@imurchie FYI

**Comment by imurchie** [comment]
Yes. I don't think the remote debugger is going to be able to handle it. I also don't have time to investigate.

**Comment by mykola-mokhnach** [comment]
I've just checked opened ports while two Simulators with opened browsers are running and I see that only one port is being listened by webinspector process. Also, Safari remote debugger only sees the Simulator, which has been executed as the first one. All the other instances are not listening and not visible to the Safari remote debugger. 
Probable, this is something, that Apple should look into.

**Comment by jlipps** [comment]
Yes, this does seem like an Apple bug. We should document it wherever we have multiple sessions documented for XCUITest.

**Comment by lanzelot1989** [comment]
Hi, just checking in, is there any progress on that front?

We would welcome it to better utilize our Macs by being able run tests against multiple simulators on the same VM.

**Comment by lanzelot1989** [comment]
Has this been raised with Apple somehow?
Is somebody from Apple listening in here?

**Comment by roosto** [comment]
Hello, I’m running into this issue, too. Is there a radar filed with Apple that we can dupe?

**Comment by roosto** [comment]
I was wondering why this got closed? It’s still not working correctly for me. Is it being closed b/c it’s dependent on Apple fixing things on their end?

**Comment by mykola-mokhnach** [comment]
Yes the problem is on Apple side.

**Comment by anhuiliujun** [comment]
is there any progress?

**Comment by savtambe** [comment]
Hi Team,

Any updates on this issue?

**Comment by ShubhamPagarwar** [comment]
yes we can perform parallel execution on safari using two capabilities:
wdaLocalPort unique wdaPort, as WDA defaults to 8100
webkitDebugProxyPort unique webKitProxy, as IWDP defaults to 27753

**Comment by varun2810** [comment]
Have you tried with simulator ??? Is it working in simulator

**Comment by saikrishna321** [comment]
@varun2810 parallel safari testing does not work on simulator

**Comment by imurchie** [comment]
It should, starting with iOS 11.3.

**Comment by saikrishna321** [comment]
> starting with iOS 11.3

Awesome ...

**Comment by varun2810** [comment]
@imurchie still facing the same above issue in simulator (iOS 11.3). Unable to detect webview when i  run the script in 2 simulators parallel. [one simulator is 11.1 & another is 11.3

**Comment by imurchie** [comment]
Yes, this will not work with anything below 11.3. Sorry if that was not clear.

**Comment by varun2810** [comment]
@imurchie Thanks your Reply. :)
But the fact is . I'm running my scripts on multiple simulators simultaneously[11.1 & 11.3]. The scripts runs and detects the webview in iOS 11.1. But it does not detects in iOS 11.3. (Works fine in 11.1 & doesn't works in 11.3). Thats where i struck. It works in lower version and not working in higher version ??? 

Appium Version : 1.8.1
xcode version : 9.4. Is there anything i missed ?

**Comment by imurchie** [comment]
It would all be guesses without logs of some sort.

**Comment by saikrishna321** [comment]
@imurchie for simulator web parallel test do we need ios_webkit_debug_proxy running in different port ?

**Comment by imurchie** [comment]
For simulator you don't need ios-webkit-debug-proxy at all.

**Comment by kevinwee0712** [comment]
Just did a parallel safari execution in iOS12.1, still doesn't work in iPhone XR simulator. My wdaPort is unique, appium server is running on an unique port as well. Each time, WebDriverAgent is reinstalled by the next execution and safari is restarted. Previous safari test will definitely fail, only the latest run could make it through. 

      capabilities.put(MobileCapabilityType.PLATFORM_NAME, System.getProperty(MobileCapabilityType.PLATFORM));
      capabilities.put(MobileCapabilityType.PLATFORM_VERSION, System.getProperty(MobileCapabilityType.PLATFORM_VERSION));
      capabilities.put(MobileCapabilityType.DEVICE_NAME, System.getProperty(MobileCapabilityType.DEVICE_NAME));
      capabilities.put(MobileCapabilityType.BROWSER_NAME, "Safari");
      capabilities.put("wdaLocalPort", Integer.valueOf(System.getProperty("wdaLocalPort")));
      capabilities.put("udid", "8E97AA1D-AD97-49F7-BE7A-9B3B85111111");

**Comment by kevinwee0712** [comment]
> Just did a parallel safari execution in iOS12.1, still doesn't work in iPhone XR simulator. My wdaPort is unique, appium server is running on an unique port as well. Each time, WebDriverAgent is reinstalled by the next execution and safari is restarted. Previous safari test will definitely fail, only the latest run could make it through.
> 
> ```
>   capabilities.put(MobileCapabilityType.PLATFORM_NAME, System.getProperty(MobileCapabilityType.PLATFORM));
>   capabilities.put(MobileCapabilityType.PLATFORM_VERSION, System.getProperty(MobileCapabilityType.PLATFORM_VERSION));
>   capabilities.put(MobileCapabilityType.DEVICE_NAME, System.getProperty(MobileCapabilityType.DEVICE_NAME));
>   capabilities.put(MobileCapabilityType.BROWSER_NAME, "Safari");
>   capabilities.put("wdaLocalPort", Integer.valueOf(System.getProperty("wdaLocalPort")));
>   capabilities.put("udid", "8E97AA1D-AD97-49F7-BE7A-9B3B85111111");
> ```

Sorry guys, false alarm. We could parallel run safari tests on iOS12.1 without any problem. I made a terrible mistake, all parallel running tests were set to the same DEVICE_NAME which means only one simulator would be launched. But as soon as I distribute all tests to all available iphone simulators, they could run in parallel. The concurrent test number is only limited to how many simulators you got under particular iOS version.
