### ISSUE TITLE
Android App is minimizing on one device when another participant from another device joins meeting on 1st device and robot throws [ WARN ] Keyword 'Capture Page Screenshot' could not be run on failure: No application is open [ WARN ] Keyword 'Capture Page Screenshot' could not be run on failure: WebDriverException: Message:

### ISSUE THREAD

**Issue by Rsingh03** [appium/appium#9211]
## The problem
a video conf app is running on 1 device and participant joins from another device,As soon as participant joins app on 1st device goes to system tray and as execution proceeds Robot throws error [ WARN ] Keyword 'Capture Page Screenshot' could not be run on failure: No application is open
[ WARN ] Keyword 'Capture Page Screenshot' could not be run on failure: WebDriverException: Message:

NOTE : If I perform this task manually , app does not go to system tray
please find recording for the issue : http://recordit.co/4pXb6QqQ4P

## Environment

* Appium version (or git revision) that exhibits the issue: 1.4.16.1
* Last Appium version that did not exhibit the issue (if applicable):NA
* Desktop OS/version used to run Appium: Windows
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: android 6.0
* Real device or emulator/simulator:real device
* Appium CLI or Appium.app|exe: appium cli

## Details
app1,video conf app, is running on device1 .Sme app is running on device and I joined user from device 2 on device 1's meeting(started on app1)
When user joins in meeting from device 2 ,app on device1 goes to system tray , After this I am switching to app1 using switch application command , Robot throws [ WARN ] Keyword 'Capture Page Screenshot' could not be run on failure: No application is open
[ WARN ] Keyword 'Capture Page Screenshot' could not be run on failure: WebDriverException: Message:

error even when I open app from tray 

## Link to Appium logs

<script src="https://gist.github.com/Rsingh03/89fa3c96f7325d6c55f11043afdb401a.js"></script>
https://gist.github.com/Rsingh03/89fa3c96f7325d6c55f11043afdb401a

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by jlipps** [comment]
in device 1 logs, you can see:

> [36minfo[39m: [debug] Didn't get a new command in 60 secs, shutting down...

This means you ran into the new command timeout. You should set the newCommandTimeout capability to something higher so that the session doesn't die while you're waiting for device 2.

**Comment by Rsingh03** [comment]
Thank you so much.. this was the actual issue and solved it by setting newCommandTimeout capablity more than 60s ..Thanks a lot :)
