### ISSUE TITLE
[MJSONWP] Encountered internal error running command: .... io.appium.uiautomator2. common.exceptions.UiSelectorSyntaxException: Could not parse UiSelector argument : new UISelector method expects an argument

### ISSUE THREAD

**Issue by DonnaZh** [appium/appium#9213]
## The problem

We are doing test on real Android phone. Key facts: Appium 1.6.4, UiAutomator2, Android7, C#.

The test scenario is desktop version makes an app call to Android mobile phone version. Android version needs to accept the app call by clicking the [AcceptCall] button on the incoming call page. The incoming call page will show up and stay for about 30 seconds. after that, it will disappear, another page shows up.

We get stuck on accepting incoming call. It looks like Appium got hang when the incoming call page shows up. Before and after the incoming call page, Appium finds elements very quickly.

Usually, we are able to find an element by 
IWebElement element = driver.FindElementById(id);

but on this "incoming call" page, Appium just hang there until app changes to another page.
then we tried different locator, "-android uiautomator"  

IWebElement elem = driver.FindElement("-android uiautomator", "new UISelector().resourceId("myAppPackageName:id/call_phone")");

this time, Appium trying to look for element on the "incoming call page", but failed with error message saying ... "io.appium.uiautomator2.
common.exceptions.UiSelectorSyntaxException: Could not parse UiSelector argument
: new UISelector method expects an argument" 

we looked into Appium log (full log added below), but cannot find any clue why it gets hang. Please help!

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows Server 2008 R2
* Node.js version (unless using Appium.app|exe): 6.10.0
* Mobile platform/version under test: Android7
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

[AppiumLogs](https://gist.github.com/DonnaZh/e4e4e176ba1ccc447b4567f5d8e57d5f.js)

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
I saw similar reports before and it looks like a bug of Google UIA framework itself. Switch to UIAutomator2 or try a workaround with Back button clicking.

**Comment by DonnaZh** [comment]
@mykola-mokhnach Thank you very much for your reply! 

I think it doesn't matter which locator to use. 
From the log, i see  
[BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
i tried xpath, id, accessibility id, -android uiautomator, none of them works. 

After taking a close look into the log, I found that Appium froze 24 seconds after receiving the findElement command, and that was the right time the "incoming call page" shows on the screen. 

2017-09-26 22:19:38:986 - info: [HTTP] --> POST /wd/hub/session/6d4a58b3-56f4-48e6-83ce-71b8769250b3/element {"using":"id","value":"com.myApp:id/connect_callee_text_line_2"}
2017-09-26 22:19:38:986 - info: [debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["id","com.myApp:id/connect_callee_text_line_2","6d4a58b3-56f4-48e6-83ce-71b8769250b3"]
2017-09-26 22:19:38:986 - info: [debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
2017-09-26 22:19:38:986 - info: [debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
2017-09-26 22:19:38:986 - info: [debug] [BaseDriver] Waiting up to 5000 ms for condition
2017-09-26 22:19:38:986 - info: [debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8203/wd/hub/session/87b6e5e8-2b96-4640-87d4-bfd729d9ac23/element] with body: {"strategy":"id","selector":"com.myApp:id/connect_callee_text_line_2","context":"","multiple":false}
2017-09-26 22:20:02:218 - info: [HTTP] <-- POST /wd/hub/session/6d4a58b3-56f4-48e6-83ce-71b8769250b3/element 500 23225 ms - 164 
2017-09-26 22:20:02:218 - info: [HTTP] --> GET /wd/hub/session/6d4a58b3-56f4-48e6-83ce-71b8769250b3/screenshot {}
2017-09-26 22:20:02:218 - info: [debug] [MJSONWP] Calling AppiumDriver.getScreenshot() with args: ["6d4a58b3-56f4-48e6-83ce-71b8769250b3"]

Your suggested work around didn't work for me because go "Back" was treated as Hang Up / Decline the call. It breaks the test scenario. And one thing i noticed that it is only this incoming call page freezes Appium. If we let it rings and go away as Miss call, as soon as the next page shows up, Appium resume and able to find elements rapidly. 

We have another team tests same scenario on Android 5.5.1, Appium 1.5.3 and Python, They do not have this problem. Below is what they use to find element. They are using find_element_by_android_uiautomator(), it leads me to try -android uiautomator locator in my original post.
element_id = ui_element_map['id']
cmd = "new UiSelector().resourceId(\"{0}\")".format(element_id)
test_driver.find_element_by_android_uiautomator(cmd)

Anybody has any idea? Appreciate for any comments. Thanks!

**Comment by mykola-mokhnach** [comment]
@vmaxim This should be the case anymore with after your recent PR is merged, right?

**Comment by vmaxim** [comment]
@mykola-mokhnach I don't think that this issue is related to selectors parsing.

> i tried xpath, id, accessibility id, -android uiautomator, none of them works.
