### ISSUE TITLE
Use Appium with Eclipse or Android Studio ?

### ISSUE THREAD

**Issue by ChandreshParmar** [appium/appium#9214]
## The problem

I am totally new to Appium and starting a new project in it. There are several posts I have seen which describes the use of Appium with Android Studio as well as Eclipse. I am not sure what to start from. I need to automate Hybrid App as well as Native App. 

## Environment

* This needs to be done running Windows OS.

**Comment by mykola-mokhnach** [comment]
Please use Appium forum to ask questions.
