### ISSUE TITLE
NullPointerException on WebElement with latest Appium (1.6.5)

### ISSUE THREAD

**Issue by droidscout** [appium/appium#9215]
## The problem

I'm trying to interact with WebElements in Android native browser or Chrome. My code to select a value from a drop down list ist as follows:
```java
public void selectState( String state ) {
	try {
		assertEquals( 1, driver.findElements( By.id( "dk0-m1" ) ).size() ); <--- working
		WebElement stateSelection = driver.findElement( By.id( "dk0-m1" ) ); <--- working

		List<WebElement> selectedState = driver.findElements( By.tagName( "option" ) ); <--- working
		WebElement selectionState = null;
		for ( WebElement st : selectedState ) {
			if( st.isDisplayed() ) { <--- not working
				if ( st.getText().toLowerCase().equals( state.toLowerCase() ) ) { <--- call to 'getText() not working
					selectionState = st;
				}
			}
		}
		if ( selectionState != null ) {
			selectionState.click();
		}
		WebElement okButton = driver.findElement( By.className( "btn-action" ) );
		okButton.click();
	} catch ( AssertionError e ) {
		System.err.println( e.getMessage() );
	}
}
```
The method asserEquals is working find and is not throwing an AssertionError. Therefore I can expect, that the element "dk-m01" is available. The next call to findElement also works as well as the driver.findElements(). findElements() returns a List of type RemoteWebElements. Whenever I want to call a method on one of those "RemoteWebElements" objects, I get a NullPointerException. 
Any suggestions?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Last Appium version that did not exhibit the issue (if applicable): 1.6.3
* Desktop OS/version used to run Appium: Windows 7 and Mac OSX 10.12.6
* Node.js version (unless using Appium.app|exe): - 
* Mobile platform/version under test: Android 6.0 
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: 1.2.1

## Link to Appium logs

[Appium Log](https://gist.github.com/droidscout/8fe84626029bf927c3e182898905196e)

**Comment by imurchie** [comment]
I don't think the logs you supplied correspond to this code. There are calls to find elements by XPath, and nothing for `isDisplayed` or `getText`

**Comment by mykola-mokhnach** [comment]
To me it looks like the issue is more appropriate for https://github.com/appium/java-client project

**Comment by droidscout** [comment]
@mykola-mokhnach, @imurchie, thank you for the help. 
Where can someone find prerequisites for new appium versions with all the reuquired versions of the appiums dependencies? Could you place a link to the prerequisites on the download page for the appium so that this is easy to find?

**Comment by jlipps** [comment]
@droidscout that's a good idea for a doc for sure

**Comment by droidscout** [comment]
Dear @jlipps,
when can this be implemented? The sooner the better, this might help to reduce questions related to inappropriate versions! 
Thx.

**Comment by jlipps** [comment]
@droidscout i'm not sure. we're in the midst of a big docs sprint with other priorities at the moment

**Comment by droidscout** [comment]
@jlipps Well, I don't think this will be a note for the documentation but rather for the release notes since the documentation is not meant to change as frequent as release notes.

BR,
Ralph
