### ISSUE TITLE
Appium hangs if test leaves application.

### ISSUE THREAD

**Issue by shynkevich-alex** [appium/appium#9219]
Appium can hangs till 60seconds when my test left application.

## Environment

* Appium server 1.6.5
* Java client 5.0.3
* Mac OS 10.12.6 (16G29)
* iOS
* Real device
* PlatformVersion 10.3.3

## Details
Test just clicks on link and safari opens and I am waiting that element (by accessibilityId) can't be found or it is not visible.
I want to continue test but sometimes I can't find elements after it at all.

## Link to Appium logs

https://gist.github.com/shynkevich-alex/f9a3327801d3fd8c8429f4f3275257c8

**Comment by mykola-mokhnach** [comment]
> [Xcode] 2017-09-15 19:49:29.133900+0300 XCTRunner[576:39750] Enqueue Failure: Failure getting snapshot Error Domain=XCTDaemonErrorDomain Code=12 "Failed to get main window after 30 retries: kAXErrorServerNotFound (see <rdar://problem/15530121>)" UserInfo={NSLocalizedDescription=Failed to get main window after 30 retries: kAXErrorServerNotFound (see <rdar://problem/15530121>)} <unknown> 0 1

This error usually means that application under test is crashed. We anyway cannot do anything about it on Appium side. Please report the issue to https://github.com/facebook/WebDriverAgent/issues.
