### ISSUE TITLE
Not able to build app on real device - Error Failed to write value for key AutomationDisableFauxCollectionCells

### ISSUE THREAD

**Issue by lareddy** [appium/appium#9224]
## The problem

I am trying to build app on ios real device. After setting up WebDriver Agent, ran command 
xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination '<UDID' test
Now, I am getting below error and app is not built in iPad
Failed to write value for key AutomationDisableFauxCollectionCells in CFPrefsPlistSource<0x178119980> (Domain: com.apple.Accessibility, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null)): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access, switching to read-only
2017-09-15 22:42:28.691394-0500 XCTRunner[231:6432] Built at Sep 15 2017 22:06:37
2017-09-15 22:42:28.719845-0500 XCTRunner[231:6432] ServerURLHere->http://192.168.1.113:8100<-ServerURLHere

## Environment

* Appium version (or git revision) that exhibits the issue:1.6.5
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:Mac OS Sierra version 10.12.6
* Node.js version (unless using Appium.app|exe):8.5.0
* Mobile platform/version under test: iOS 10.3.3
* Real device or emulator/simulator: Real device - iPad Air
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

MDMCreateDeltaDirectory:1920 calling MDMDirectoryDiff with:
state->old_bundle: /var/folders/d0/r2c7bx2d2rn__js6gj11x_k5m309hx/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/92b5311dde1272189cee5c91383b0865/c0b391e67593a7fd8c5285106d346edfe029d35d/WebDriverAgentRunner-Runner.app
state->new_bundle: /Users/lareddy/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app
state->dst_bundle: /var/folders/d0/r2c7bx2d2rn__js6gj11x_k5m309hx/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.QTXdsH/WebDriverAgentRunner-Runner.app_sparse.ipa/Payload//WebDriverAgentRunner-Runner.app, binaryDiff flag: FALSE
	dst_ipa: /var/folders/d0/r2c7bx2d2rn__js6gj11x_k5m309hx/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.QTXdsH/WebDriverAgentRunner-Runner.app_sparse.ipa
__MDMDirectoryDiff_block_invoke.37:1473 calling writeDictToFile with: /var/folders/d0/r2c7bx2d2rn__js6gj11x_k5m309hx/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.QTXdsH/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist
writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/d0/r2c7bx2d2rn__js6gj11x_k5m309hx/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.QTXdsH/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist
2017-09-16 14:17:45.457203-0500 XCTRunner[329:31101] Running tests...
2017-09-16 14:17:46.494090-0500 XCTRunner[329:31101] Continuing to run tests in the background with task ID 1
Test Suite 'All tests' started at 2017-09-16 14:17:46.551
Test Suite 'WebDriverAgentRunner.xctest' started at 2017-09-16 14:17:46.554
Test Suite 'UITestingUITests' started at 2017-09-16 14:17:46.555
Test Case '-[UITestingUITests testRunner]' started.
    t =     0.00s     Start Test at 2017-09-16 14:17:46.558
    t =     0.00s     Set Up
2017-09-16 14:17:46.572080-0500 XCTRunner[329:31123] [User Defaults] Failed to write value for key AutomationDisableFauxCollectionCells in CFPrefsPlistSource<0x17811aa60> (Domain: com.apple.Accessibility, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null)): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access, switching to read-only
2017-09-16 14:17:46.574094-0500 XCTRunner[329:31101] Built at Sep 15 2017 22:06:37
2017-09-16 14:17:46.606292-0500 XCTRunner[329:31101] ServerURLHere->http://192.168.1.113:8100<-ServerURLHere

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
This does not look like an error, but rather like a warning. Could you attach the full server log?

**Comment by lareddy** [comment]
Thank you for your prompt response. After I get the error nothing is happening in terminal and app is not installed on iPad. Attached are the full server logs. Please help me with this.


[Server Log.pdf](https://github.com/appium/appium/files/1308640/Server.Log.pdf)

**Comment by mykola-mokhnach** [comment]
This is not an Appium log, but rather xcodebuild one.

**Comment by mykola-mokhnach** [comment]
Closed as inactive
