### ISSUE TITLE
Appium Error : [XCUITest] Unable to connect to running WebDriverAgent: 

### ISSUE THREAD

**Issue by vamsidharj12** [appium/appium#9225]
## The problem

I am facing below error  when trying to launch application
[XCUITest] Unable to connect to running WebDriverAgent: Could not proxy command to remote server. Original error: Error: ESOCKETTIMEDOUT

## Environment

* Appium version (or git revision) that exhibits the issue: 1.2.0
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: MAC os Sierra,  ver 10.12.6
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: IPAD Mini  OS v10.3.3
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium.exe

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Please attach full server log. ESOCKETTIMEDOUT usually means that WDA server is not running at all.

**Comment by mykola-mokhnach** [comment]
Closed as inactive
