### ISSUE TITLE
Android O: Unable to unlock screen on simulator.

### ISSUE THREAD

**Issue by vmaxim** [appium/appium#9228]
## The problem

[helpers.isShowingLockscreen()](https://github.com/appium/appium-adb/blob/master/lib/helpers.js#L117)

There is no ```mShowingLockscreen``` variable on simulator.

Locked device:
```
adb shell "dumpsys window | grep Lockscreen"
mShowingDream=false mDreamingLockscreen=true mDreamingSleepToken=null
mAllowLockscreenWhenOn=false mLockScreenTimeout=60000 mLockScreenTimerActive=false
```

Unlocked device:
```
adb shell "dumpsys window | grep Lockscreen"
mShowingDream=false mDreamingLockscreen=false mDreamingSleepToken=null
mAllowLockscreenWhenOn=false mLockScreenTimeout=60000 mLockScreenTimerActive=false
```

## Environment

* Appium version (or git revision) that exhibits the issue: **1.7.0-beta**
* Last Appium version that did not exhibit the issue (if applicable): **N/A**
* Desktop OS/version used to run Appium: **Win/Mac**
* Node.js version (unless using Appium.app|exe): **6.11**
* Mobile platform/version under test: **Android API 26**
* Real device or emulator/simulator: **Simulator Google APIs Intel x86 Atom System Image Rev. 5**
* Appium CLI or Appium.app|exe: **CLI**

**Comment by mykola-mokhnach** [comment]
@vmaxim You're welcome to create a PR
