### ISSUE TITLE
Appium inspector keep closing with error.

### ISSUE THREAD

**Issue by SamyQAZ** [appium/appium#9232]
## The problem

Start appium inspector session, keep closing after few minutes throwing below error.
`
[Logcat] Logcat terminated with code 0, signal null
[UiAutomator] UiAutomator exited unexpectedly with code 0,
`

## Environment

* Appium version (or git revision) that exhibits the issue: Version 1.2.1 (1.2.1)
* Desktop OS/version used to run Appium: 10.12.6(sierra)
* Node.js version (unless using Appium.app|exe): v7.10.0
* Mobile platform/version under test: Android(5.1.1)
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium.app|exe

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Gist to appium logs [GIST](https://gist.github.com/SamyQAZ/61912aeeee69db707e84aa49631c7cdf)

## Code To Reproduce Issue [ Good To Have ]

Appium capabilities
{
  "platformName": "Android",
  "platformVersion": "5.1.1",
  "deviceName": "Samsung Galaxy J1 (2016)",
  "app": "/mobile_automation/zwoop_automation/android_automation/android_builds/0.5.4-demo.apk",
  "appPackage": "com.xxx.android",
  "noReset": true,
  "appActivity": "com.xxx.android.ui.splash.SplashActivity",
  "deviceReadyTimeout": 3000,
  "newCommandTimeout\t": 60
}

I doubt that it happens due to session time out, however tried increasing session timeout. 
Still no luck.

**Comment by mykola-mokhnach** [comment]
This looks like an internal adb issue. It is said that updating Android SDK tools to the most recent version might solve the problem.

**Comment by SamyQAZ** [comment]
Tried to update adb, still no luck

**Comment by mykola-mokhnach** [comment]
Try switching to UIAutomator2 backend

**Comment by SamyQAZ** [comment]
Issues with npm. Doesnt work.
`
Apples-MBP:android-sdk Shamiya$ npm install appium-uiautomator2-driver

> appium-uiautomator2-driver@0.6.3 install /Users/apple/node_modules/appium-uiautomator2-driver
> node ./bin/install.js

dbug AndroidDriver Getting Java version
info AndroidDriver Java version is: 1.8.0_131
info UiAutomator2 downloading UiAutomator2 Server APK v0.1.8 : https://github.com/appium/appium-uiautomator2-server/releases/download/v0.1.8/appium-uiautomator2-server-v0.1.8.apk
info UiAutomator2 downloading UiAutomator2 Server test APK v0.1.8 : https://github.com/appium/appium-uiautomator2-server/releases/download/v0.1.8/appium-uiautomator2-server-debug-androidTest.apk
info UiAutomator2 UiAutomator2 Server APKs downloaded
npm WARN saveError ENOENT: no such file or directory, open '/Users/apple/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/apple/package.json'
npm WARN apple No description
npm WARN apple No repository field.
npm WARN apple No README data
npm WARN apple No license field.

+ appium-uiautomator2-driver@0.6.3
updated 1 package in 119.743s
`

Cant get why cant install.

**Comment by imurchie** [comment]
Those are warnings, just meaning that you are not inside an npm package when running npm install. I'm not sure what you're trying to do, but it worked.

**Comment by SamyQAZ** [comment]
Let me give a try again. Thanks for information

**Comment by SamyQAZ** [comment]
Still no luck with this. npm install throws error when triggered from package

**Comment by SamyQAZ** [comment]
Doesnt happen after getting new appium( 1.2.7) update so closing it
