### ISSUE TITLE
APPIUM COULD NOT GET XCODE VERSION plist does not exist

### ISSUE THREAD

**Issue by CharanpreetHora** [appium/appium#9236]
## The problem

APPIUM COULD NOT GET XCODE VERSION plist does not exist

## Environment

Appium 1.6.5 desktop version
xcode 7.1

## Details
xcode-select -p and shows correct path "Application/Xcode.app/Developers/Content

Using following capabilities:-
	  "app": "Users/xyz/Desktop/Automation/xyzapp/ipa/xyz_2.0.0.ipa"
	  "appPackage": "com.xyz.android",
	  "platformName": "Ios",
	  "automationName": "XCUITest",
	  "platformVersion": "10.3.2",
	  "appActivity": "com.xyz.android.activities.SplashScreenActivity",
	  "deviceName": "xyz iPhone",
	  "newCommandTimeout": "120",
	  "udid": "bd72b44012e988316c8f8174a02b78f36d72709e",
	  "bundleId": "com.xyz.funhub"
Not sure why I am not able to start inspector and getting error as APPIUM COULD NOT GET XCODE VERSION plist does not exist . It seems some path I need to set. But not sure how can i set the path with Appium Desktop.

Kindly suggest.

**Comment by imurchie** [comment]
Can you provide the full logs as a link to a [gist](https://gist.github.com)? 

Also, Xcode 7.1 will not be able to automate iOS 10.3.2.

**Comment by CharanpreetHora** [comment]
I think my current issue is fixed. Now I am getting error as 
xcode 8.1 maximum sdk version of 10.1, it does not support ios 1.3.2
ANy idea by appium 1.6.5 what are the ios versions and sdk version are supported.

**Comment by imurchie** [comment]
Xcode 8.3 and above will support iOS 10.3. That is an Apple thing.

**Comment by CharanpreetHora** [comment]
Yes I have done the same and working fine for me now. Closing this ticket.

**Comment by JavonDavis** [comment]
@CharanpreetHora How did you fix it? I'm experiencing the same issue now

**Comment by imurchie** [comment]
@JavonDavis There are, unfortunately, two different issues here. What exactly are you experiencing?

**Comment by JavonDavis** [comment]
<img width="651" alt="screen shot 2018-03-07 at 1 05 36 pm" src="https://user-images.githubusercontent.com/6520461/37109563-5a7e4136-2208-11e8-9645-80e6508358b7.png">

**Comment by JavonDavis** [comment]
Environment

appium 1.7.2
xcode 9.2

**Comment by imurchie** [comment]
Try running `sudo xcode-select -s /Applications/Xcode.app` and then re-running Appium.

**Comment by imurchie** [comment]
If you have Xcode in another place, the path will need to be adjusted.

**Comment by JavonDavis** [comment]
Wow I swear I did this already and it didn't work, but it's working now! Thanks much!

**Comment by imurchie** [comment]
Cool!
