### ISSUE TITLE
iOS - 1.7.0 - SendKeys command gets executed but value isn't set

### ISSUE THREAD

**Issue by siggerzz** [appium/appium#9243]
## The problem

I'm trying to use SendKeys to send text to a WYSIWYG text editor. My test works fine on Android, however when I run the test on iOS, Appium sets the value, however no text is set in the field. Appium then tries to carry on executing the rest of the test case.

I have been seeing this issue since Appium 1.6.6.beta-4, when appium-remote-debugger had Selenium Atoms updated to 3.6.0

This is different behaviour from what I was seeing in previous Appium versions:

Appium 1.6.5/4/3/ - I was getting the following error - https://github.com/appium/appium/issues/8927

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.6-beta-4
* Last Appium version that did not exhibit the issue (if applicable): 1.6.5 (This errored with https://github.com/appium/appium/issues/8927 instead)
* Desktop OS/version used to run Appium: MacOS Sierra
* Node.js version (unless using Appium.app|exe): 6.10.3
* Mobile platform/version under test: iOS - 10.3.3
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: CLI

## Details

As mentioned in https://github.com/appium/appium/issues/8927 , the element I'm trying to SendKeys to has a contenteditable=true attribute, a number of other people have also experienced similar issues when trying to SendKeys to elements like this:

https://github.com/appium/appium/issues/6506
https://github.com/appium/appium/issues/1001
https://discuss.appium.io/t/sendkeys-is-not-working-in-ipad-safari/3466/2

## Link to Appium logs

[Appium Server Log](https://gist.github.com/siggerzz/d5b4395491c12a973a6994773b104a15) - The element in question is 'js-full-page-texteditor-content'

**Comment by mykola-mokhnach** [comment]
I think it's not Appium's problem, but rather Selenium's one. Check https://stackoverflow.com/questions/30310872/error-while-sending-text-to-div-field-in-safari-using-protractor

**Comment by siggerzz** [comment]
Sorry @mykola-mokhnach Any idea how I might achieve this? My JS knowledge isn't great.

Like: `_driver.ExecuteJavaScript("return document.getElementByClassName('js-full-page-texteditor-content');");` ?
