### ISSUE TITLE
Android 7.0 - Appium 1.7.0 - Hybrid app tests no longer run

### ISSUE THREAD

**Issue by siggerzz** [appium/appium#9245]
## The problem

I've just noticed that since upgrading to 1.7.0, my Android tests no longer run, as Appium crashes after launching the app.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.0
* Last Appium version that did not exhibit the issue (if applicable): 1.6.5
* Desktop OS/version used to run Appium: MacOS
* Node.js version (unless using Appium.app|exe): 6.10.3
* Mobile platform/version under test: Android - 7.0
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe:

## Link to Appium logs

https://gist.github.com/siggerzz/f53670f10cfa833d73ed13cb8a4fe96c

**Comment by imurchie** [comment]
Yes. I appear to have broken process mapping for webviews.

**Comment by imurchie** [comment]
The new logic depends on the `ps` command returning lined-up columns and entries, which it does on all devices I had available.

Can you provide a [gist](https://gist.github.com) with the result of running `adb shell ps` on your device?

**Comment by siggerzz** [comment]
Sure!

[Nexus 9](https://gist.github.com/siggerzz/c37984bfe3a6333b0eebc8aa97103ca1)
[Samsung Galaxy S6](https://gist.github.com/siggerzz/70764a1b516d3ef64e052b740183b658)

**Comment by imurchie** [comment]
https://github.com/appium/appium-android-driver/pull/271

**Comment by imurchie** [comment]
With `appium-android-driver` 1.27.1 this issue should be fixed. You can update appium using `npm uninstall -g appium && npm install -g appium --no-shrinkwrap`.

**Comment by siggerzz** [comment]
@imurchie Thanks for the prompt fix! Seems to be working as expected now 👍
