### ISSUE TITLE
Appium iOS syslog 

### ISSUE THREAD

**Issue by invisbo** [appium/appium#9246]
## The problem

I am simply using  `driver.manage().logs().get("syslog").getAll()` and getting device logs. All i need is application logs but at the beggining method returns list with 10000 length and its not full of all logs. How can i get only application logs or is there a way to override this 10000 limit?

## Environment

* Appium version 5.0.0-BETA9 that exhibits the issue:

**Comment by dpgraham** [comment]
Appium 5.0.0-beta9 isn't a valid Appium version. That's probably the Java client. Can you provide the Appium server logs so I can see the Appium version? 

I think this issue may be related to https://github.com/appium/appium/issues/8223 and may already be fixed with a newer version.

**Comment by skyline-gleb** [comment]
## The problem

On `driver.get_log('syslog')` i get nothing

## Environment

* Appium version (or git revision) that exhibits the issue: appium@1.7.0
* Desktop OS/version used to run Appium: macSO Sierra 10.12.6
* Node.js version (unless using Appium.app|exe): v8.4.0
* Mobile platform/version under test: iOS 11.0
* Real device or emulator/simulator: real
* Appium CLI or Appium.app|exe:

## Link to Appium logs
[link](https://gist.github.com/skyline-gleb/e4821256578df2d64daf231beb36efe3)

**Comment by imurchie** [comment]
@skyline-gleb Do you see anything in the actual device logs? Xcode 9 broke iOS logging in general.

**Comment by skyline-gleb** [comment]
@imurchie see from xcode 'device and simulator' window, but get error on manually call `idevicesyslog`:
```
$ idevicesyslog -u <udid>
ERROR: Could not start service com.apple.syslog_relay.
Could not start logger for udid <udid>
```

**Comment by rajfidel** [comment]
@skyline-gleb 
Run the below command to reinstall libimobiledevice after installing Appium 1.7.0
brew reinstall --HEAD libimobiledevice

**Comment by skyline-gleb** [comment]
@rajfidel unfortunately it does not work for me

**Comment by imurchie** [comment]
If `idevicesyslog` doesn't work, you can try `deviceconsole`. Install with `npm install -g deviceconsole`. Try it out. Then you can pass in the path to the program (retrieve with `which deviceconsole`) to Appium in the `realDeviceLogger` capability.

**Comment by invisbo** [comment]
I checked appium js files and found some 10000 limitation. I customized that file according to my needs.

**Comment by skyline-gleb** [comment]
@imurchie thanks, it's worked (sorry for long answer)
