### ISSUE TITLE
Even though the elements are visible,appium is showing visible as false.

### ISSUE THREAD

**Issue by vutukuriswathi** [appium/appium#9249]
## The problem

Even though we are able to see the element on the native iOS app,appium is showing the visible attribute as false.
I observed this behaviour for few elements.

## Environment

ios Device:10.0
appium:1.6.5
appium java client :4.0.0
Macos:10.11.6

![snip20170920_1](https://user-images.githubusercontent.com/13588038/30622956-2a7a6bc0-9df8-11e7-8b3c-059a57c4b325.png)

**Comment by dpgraham** [comment]
We don't support this UI anymore.

Can you try with Appium Desktop? https://github.com/appium/appium-desktop/releases/latest

**Comment by vutukuriswathi** [comment]
I tried by installing appium desktop.Appium desktop is unable to open the ios app and it throws "xcodebuild exited with code 65 and signal null" error.
This is the capabilities i passed to the appium desktop.

{
  "udid": "4c7399acc39cb0e3b8609e6d069c5f619700b70d",
  "deviceName": "Abc_iPhone6plus",
  "automationName": "XCUITest",
  "platformName": "ios",
  "bundleId": "au.net.abc.kids-iview",
  "app": "/Users/gunuputis4r/Documents/Intellijiworkspace/KidsIviewPhonesAutomation/src/test/resources/com/kidsIview/mobileApps/kidsiviewiphone.ipa"
}

But i am able to open the app using previous app inspector and able to run the testcases on iOS10.
Any help on this is higly reagrded.


Attached is the appium logs:
[Appium] Welcome to Appium v1.6.5
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> GET /wd/hub/sessions {}
[MJSONWP] Calling AppiumDriver.getSessions() with args: []
[MJSONWP] Responding to client with driver.getSessions() result: []
[HTTP] <-- GET /wd/hub/sessions 200 9 ms - 40 
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/gunuputis4r/Documents/Intellijiworkspace/KidsIviewPhonesAutomation/src/test/resources/com/kidsIview/mobileApps/kidsiviewiphone.ipa","automationName":"XCUITest","bundleId":"au.net.abc.kids-iview","deviceName":"Abc_iPhone6plus","platformName":"ios","udid":"4c7399acc39cb0e3b8609e6d069c5f619700b70d","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/gunuputis4r/Documents/Intellijiworkspace/KidsIviewPhonesAutomation/src/test/resources/com/kidsIview/mobileApps/kidsiviewiphone.ipa","automationName":"XCUITest","bundleId":"au.net.abc.kids-iview","deviceName":"Abc_iPhone6plus","platformName":"ios","udid":"4c7399acc39cb0e3b8609e6d069c5f619700b70d","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1505880813201 (14:13:33 GMT+1000 (AEST))
[Appium] Creating new XCUITestDriver (v2.30.0) session
[Appium] Capabilities:
[Appium]   app: '/Users/gunuputis4r/Documents/Intellijiworkspace/KidsIviewPhonesAutomation/src/test/resources/com/kidsIview/mobileApps/kidsiviewiphone.ipa'
[Appium]   automationName: 'XCUITest'
[Appium]   bundleId: 'au.net.abc.kids-iview'
[Appium]   deviceName: 'Abc_iPhone6plus'
[Appium]   platformName: 'ios'
[Appium]   udid: '4c7399acc39cb0e3b8609e6d069c5f619700b70d'
[Appium]   newCommandTimeout: 0
[Appium]   connectHardwareKeyboard: true
[XCUITest] XCUITestDriver version: 2.30.0
[BaseDriver] Session created with session id: b5c77716-cf63-4253-aeca-c47953bcecab
[XCUITest] Xcode version set to '8.2.1' (tools v8.2.0.0.1.1480973914)
[XCUITest] iOS SDK Version set to '10.2'
[BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1505880813441 (14:13:33 GMT+1000 (AEST))
[XCUITest] Available devices: 4c7399acc39cb0e3b8609e6d069c5f619700b70d
[XCUITest] Creating iDevice object with udid '4c7399acc39cb0e3b8609e6d069c5f619700b70d'
[XCUITest] Determining device to run tests on: udid: '4c7399acc39cb0e3b8609e6d069c5f619700b70d', real device: true
[BaseDriver] Using local app '/Users/gunuputis4r/Documents/Intellijiworkspace/KidsIviewPhonesAutomation/src/test/resources/com/kidsIview/mobileApps/kidsiviewiphone.ipa'
[BaseDriver] Copying local zip to tmp dir
[BaseDriver] Unzipping /var/folders/6f/cm41jlqd0vbfmj_f6nwv7tf4sskhh6/T/2017820-45144-1g3lshw.42woc7hkt9/appium-app.zip
[BaseDriver] Testing zip archive: /var/folders/6f/cm41jlqd0vbfmj_f6nwv7tf4sskhh6/T/2017820-45144-1g3lshw.42woc7hkt9/appium-app.zip
[BaseDriver] Unzipped local app to '/var/folders/6f/cm41jlqd0vbfmj_f6nwv7tf4sskhh6/T/2017820-45144-1g3lshw.42woc7hkt9/Payload/kids-iview.app'
[BaseDriver] Event 'appConfigured' logged at 1505880814357 (14:13:34 GMT+1000 (AEST))
[XCUITest] Checking whether app '/var/folders/6f/cm41jlqd0vbfmj_f6nwv7tf4sskhh6/T/2017820-45144-1g3lshw.42woc7hkt9/Payload/kids-iview.app' is actually present on file system
[XCUITest] App is present
[BaseDriver] Event 'resetStarted' logged at 1505880814359 (14:13:34 GMT+1000 (AEST))
[XCUITest] Reset: running ios real device reset flow
[BaseDriver] Event 'resetComplete' logged at 1505880814359 (14:13:34 GMT+1000 (AEST))
[iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[BaseDriver] Event 'logCaptureStarted' logged at 1505880814474 (14:13:34 GMT+1000 (AEST))
[XCUITest] Setting up real device
[XCUITest] Reset requested. Removing app with id 'au.net.abc.kids-iview' from the device
[XCUITest] Installing '/var/folders/6f/cm41jlqd0vbfmj_f6nwv7tf4sskhh6/T/2017820-45144-1g3lshw.42woc7hkt9/Payload/kids-iview.app' on device with UUID '4c7399acc39cb0e3b8609e6d069c5f619700b70d'...
[XCUITest] The app has been installed successfully.
[BaseDriver] Event 'appInstalled' logged at 1505880818569 (14:13:38 GMT+1000 (AEST))
[BaseDriver] Event 'wdaStartAttempted' logged at 1505880818571 (14:13:38 GMT+1000 (AEST))
[XCUITest] Using WDA path: '/Users/gunuputis4r/Downloads/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/Users/gunuputis4r/Downloads/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[XCUITest] Carthage found: '/usr/local/bin/carthage'
[XCUITest] Killing hanging processes
[XCUITest] Cannot parse major and minor version numbers from platformVersion "undefined". Will build for the default platform instead
[XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /Users/gunuputis4r/Downloads/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=4c7399acc39cb0e3b8609e6d069c5f619700b70d -configuration Debug' in directory '/Users/gunuputis4r/Downloads/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Output from xcodebuild will not be logged
[XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"state\" : \"success\",\n    \"os\" : {\n      \"name\" : \"iOS\",\n      \"version\" : \"10.0\"\n    },\n    \"ios\" : {\n      \"simulatorVersion\" : \"10.0\",\n      \"ip\" : \"10.97.23.155\"\n    },\n    \"build\" : {\n      \"time\" : \"Sep 13 2017 15:50:02\"\n    }\n  },\n  \"sessionId\" : \"A79C74F5-BF4C-4643-B9E9-E2A02BAD2673\",\n  \"status\" : 0\n}"
[XCUITest] WebDriverAgent running on ip '10.97.23.155'
[XCUITest] WebDriverAgent successfully started after 2451ms
[BaseDriver] Event 'wdaSessionAttempted' logged at 1505880826125 (14:13:46 GMT+1000 (AEST))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"au.net.abc.kids-iview","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[XCUITest] Log file for xcodebuild test: /Users/gunuputis4r/Library/Developer/Xcode/DerivedData/WebDriverAgent-hemggfywgiutqoetikikhirskrvs/Logs/Test/D817F635-8C69-4693-88A7-7B098A67CD27/Session-WebDriverAgentRunner-2017-09-20_141351-1xbi76.log
[Xcode] 2017-09-20 14:13:51.192 xcodebuild[45771:2265352] Error Domain=NSCocoaErrorDomain Code=260 "The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/gunuputis4r/Library/Developer/Xcode/DerivedData/WebDriverAgent-hemggfywgiutqoetikikhirskrvs/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7f844e87c480 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
[Xcode] 
[Xcode] 2017-09-20 14:13:51.192 xcodebuild[45771:2265352] Error Domain=IDETestOperationsObserverErrorDomain Code=5 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
[Xcode] 
[Xcode] ** TEST EXECUTE FAILED **
[Xcode] 
[Xcode] 
[XCUITest] xcodebuild exited with code '65' and signal 'null'
[JSONWP Proxy] Got response with status 200: {"value":"Failed to launch au.net.abc.kids-iview application","sessionId":"A79C74F5-BF4C-4643-B9E9-E2A02BAD2673","status":13}
[XCUITest] Failed to create WDA session. Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1505880977873 (14:16:17 GMT+1000 (AEST))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"au.net.abc.kids-iview","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}

**Comment by vutukuriswathi** [comment]
I tried the same with the appium desktop.But even the appium desktop also has same problem.Please find the screenshot.
![snip20170920_2](https://user-images.githubusercontent.com/13588038/30627328-c6aaba3a-9e12-11e7-99f6-49954c810825.png)

**Comment by mykola-mokhnach** [comment]
Visibility value depends on what the application returns to iOS Accessibility and can be changed programmatically. Appium just shows what XCTest returns to it. Read https://developer.apple.com/documentation/uikit/accessibility/uiaccessibility?language=objc for more details

**Comment by vutukuriswathi** [comment]
@mykola-mokhnach Do you mean the developers set the visible to false for these elements.I have gone through the document which you shared but I did not understand much.

**Comment by Michael-Benton** [comment]
Any updates on this? I ran into the same issue. Accessibility is set to true, but Appium can't find element and Appium desktop is showing visible variables on element equal to false.

**Comment by Akulavenkatesh** [comment]
Facing the same issue with iOS app! **visible** is set to **false** for buttons

**Comment by Akulavenkatesh** [comment]
**visible** is shown as **true** in Appium Inspector when I build my app using xcode 9.2 (previously I was using xcode 9.3)

**Comment by sainivarun** [comment]
Facing same issue with appium desktop 1.10.0

**Comment by shenjianyun** [comment]
i‘m also encoutering the same issue with appium 1.12.1 and i asked the developer modified via https://developer.apple.com/documentation/uikit/accessibility/uiaccessibility?language=objc mentioned above, and not work
![image](https://user-images.githubusercontent.com/48910607/61687557-47cdb600-ad55-11e9-91b2-deb1299c9f60.png)

**Comment by Vadym1123456** [comment]
Also have this problem xcode Version 12.4, Appium v1.23.0-beta.0 
When i click on image element it return visible false!
![image](https://user-images.githubusercontent.com/92034764/140485871-95645a4f-1861-4272-b5fc-7f19ec5cb6f0.png)

**Comment by ArunVicky001** [comment]
I am also facing the same issue. when embedding a SwiftUI view within a UIKit view, Appium is unable to detect the elements due to visibility issues. In the screenshot below, you can see that the visibility for the specific element we’re trying to inspect is set to false, which prevents access to its properties.

To address this, I’ve tried the following workarounds:

Setting isAccessibilityElement = true

Using .accessibilityHidden(false).accessibilityEnabled(true)

Unfortunately, neither of these solutions resolved the issue.

It appears that many users are experiencing this same problem, but there is no clear workaround available yet.

<img width="1402" alt="Screenshot 2024-11-14 at 4 20 27 PM" src="https://github.com/user-attachments/assets/adc19264-f181-48ed-adc4-84378b9a35b3">

Native XCode accessibility inspector I am able to inspect the element not via appium.  
I am using iPhone 16 and iOS 18 for testing 

Please suggest the solution for this issue.

**Comment by ArunVicky001** [comment]
I had fixed this issue by setting below property to hosting view controller view 
            
```
view.isAccessibilityElement = true
view.accessibilityIdentifier = "viewidentifier" 
```
