### ISSUE TITLE
[Uiautomator2][Occasionally] Can not get status repsonse during starting uiautomator2 server.

### ISSUE THREAD

**Issue by Carlgege** [appium/appium#9250]
## Environment
Appium 1.6.3

## Link to Appium logs
https://gist.github.com/Carlgege/a91dffa2adf265085964d604b377a1ec

## My advice
Whether add an router(ex: exit) on uiautomator2 server to replace the command(force-stop) is better or not?

BRs

**Comment by mykola-mokhnach** [comment]
Please update Appium to 1.7.0
