### ISSUE TITLE
[xcode 9, appium 1.7, iOS 10] Could not obtain source element tree if test left application.

### ISSUE THREAD

**Issue by shynkevich-alex** [appium/appium#9254]
## The problem
The error appears when test left application.

> Could not obtain source: {"cause":{"sessionId":"41031a12-d8a0-487f-8ecb-17462ee12c14","status":13,"value":{"message":"An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up"}},"jsonwire-error":{"detail":"An unknown server-side error occurred while processing the command.","status":13,"summary":"UnknownError"},"message":"[source()] Error response status: 13, , UnknownError - An unknown server-side error occurred while processing the command. Selenium error: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up","status":13}

## Environment

* Appium version:  1.7
* Last Appium version that did not exhibit the issue (if applicable): 1.6.5
* Appium Java Client: 5.0.3
* Desktop OS/version used to run Appium: mac OS 10.12.6
* Xcode Version: 9.0 (9A235)
* Real device : iPad 10.3.3

## Details
When test leave application and tries obtain elements tree the issue happens.
It reproduces in iPad pro  with iOS 10.3.3. 
I have the same iPad with iOS 11.0 and it works fine with it.
I've tried get elements tree with appium desktop UI Inspector but the same issue happens. No matter if home screen is opened or safari.

## Link to Appium logs
iPad 10.3.3 Logs: https://gist.github.com/shynkevich-alex/aaf9542a38beb3dabdcb81469a9e4bc6
iPad 11.0 Logs: https://gist.github.com/shynkevich-alex/62e35db714fccc88f590f60baee07977

**Comment by mykola-mokhnach** [comment]
This is a problem of WebDriverAgent/XCTest itself. Please move your issue to  https://github.com/facebook/WebDriverAgent/issues

Also, please attach the logs from the device under test, since these might be useful.

**Comment by shynkevich-alex** [comment]
Ok, I've created issue: https://github.com/facebook/WebDriverAgent/issues/725

**Comment by mykola-mokhnach** [comment]
Thanks. Also, as I said, make sure you have the log from real device with a stacktrace/error codes. Otherwise it would be hardly possible to understand what the problem might be.

**Comment by shynkevich-alex** [comment]
Yes, I've also added logs from device. Thank you.
