### ISSUE TITLE
Trailing \r in webview context on windows 7 breaks autoWebview

### ISSUE THREAD

**Issue by Sykomaniac** [appium/appium#9255]
## The problem

When running automated tests with Appium via Webdriver.io the application web view context has a trailing "\r" that is not stripped out of the context name. This only occurs on Windows 7 and works fine on Windows 10 (tested). This prevents the autoWebview option from working (you can manually set the context in test initialisation).

## Environment

* Appium version: 1.7.0
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Windows 7
* Node.js version (unless using Appium.app|exe): 6.9.2
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs

https://gist.github.com/Sykomaniac/ca14f517d914ec090a3e03c43a730a2f

Search for the word webview to find the error quicker

## Code To Reproduce Issue [ Good To Have ]
https://github.com/Sykomaniac/wdio-test

**Comment by imurchie** [comment]
The logic for this parsing has been changed yesterday. Can you update Appium (`npm uninstall -g appium && npm install -g appium --no-shrinkwrap`) and check to see if it happens?

If it still does we will need to see how to strip that carriage return character on Windows 7, but I think it ought to work now.

**Comment by Sykomaniac** [comment]
@imurchie will test tomorrow and let you know.

**Comment by Sykomaniac** [comment]
Can confirm that the latest version resolves the issue

**Comment by imurchie** [comment]
Excellent! Thanks for letting us know!
