### ISSUE TITLE
Using uiautomator2, cannot getAttribute("contentDescription") if there is no value

### ISSUE THREAD

**Issue by tslape** [appium/appium#9257]
## The problem

I am checking to see that an element is does not have a certain contentDescription on it and if the element it finds does not have a contentDescription, it says that it did not get a valid response object.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows 10 
* Node.js version (unless using Appium.app|exe): 8.1.4
* Mobile platform/version under test: Android 7.1.1
* Real device or emulator/simulator: Real Device Nexus 9
* Appium CLI or Appium.app|exe: Appium.exe

## Details

When using uiautomator it just returns "", but when using uiautomator2 it does not get the valid response object and errors. 

Using the code below with uiautomator it will pass. 

Also if you use the code below, but instead use className as the attribute, it will pass as well.

## Link to Appium logs

https://gist.github.com/tslape/61fff6512c1911b3873146a71d92620e

## Code To Reproduce Issue [ Good To Have ]

Using the Android API Demos App and JavaScript
`
	it("should find an element", function () {
		return driver
			.elementByXPath('//android.widget.TextView[@text=\'API Demos\']')
			.getAttribute('contentDescription').should.not.become('Test');
	});
`

**Comment by mykola-mokhnach** [comment]
Can you please try Appium 1.7.0?

**Comment by tslape** [comment]
Tested with 1.7.0. Now when you get the contentDescription if there is no value, it will return null.
