### ISSUE TITLE
Can't get screenshot for iOS11 device

### ISSUE THREAD

**Issue by jeet4320** [appium/appium#9259]
## The problem
When running app on iOS11 Iphone 7 plus device, screenshot is not obtained

![screen shot 2017-09-20 at 4 45 55 pm](https://user-images.githubusercontent.com/11895196/30669275-58d5d696-9e23-11e7-8021-e2b455d4cf9b.png) 

![screen shot 2017-09-20 at 4 46 01 pm](https://user-images.githubusercontent.com/11895196/30669281-5cf3c2b0-9e23-11e7-8e7e-8947e7d4ffe9.png)

![screen shot 2017-09-21 at 9 30 41 am](https://user-images.githubusercontent.com/11895196/30701838-ef76d64e-9eb0-11e7-9c04-3058fe607b29.png)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.0
* Last Appium version that did not exhibit the issue (if applicable): 1.7.0
* Desktop OS/version used to run Appium:  macOS sierra 10.12.6 (16G29)
* Node.js version (unless using Appium.app|exe): v8.3.0
* Mobile platform/version under test: iOS 11
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe:

##Details:
It works on iOS10 devices, screenshot gets generated.

## Link to Appium logs

https://gist.github.com/jeet4320/930a352ceba23a69fb51dabe69b73ee3

[MJSONWP] Encountered internal error running command: Error: Unable to take screenshot. WDA returned '{}'
    at XCUITestDriver.getScreenshotFromWDA$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/screenshots.js:12:13)
    at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- GET /wd/hub/session/96452e6a-ed7a-46e3-bd32-5ab3a2522d95/screenshot 500 9256 ms - 215 
[XCUITest] Connection to WDA timed out
[iProxy] recv failed: Operation not permitted

**Comment by mykola-mokhnach** [comment]
Can you please attach full server log?

**Comment by mykola-mokhnach** [comment]
@dpgraham @imurchie Can we fix the error description in the inspector window aka `[object Object]`?

**Comment by imurchie** [comment]
Should be fixed already: https://github.com/appium/appium-desktop/commit/35bf2e81d000c157e723a1292e14b0026b2118ea

**Comment by mykola-mokhnach** [comment]
@jeet4320 you need to try the newest version of Appium Desktop then

**Comment by akashkhandelwal** [comment]
I am using latest version, Version 1.2.1 (1.2.1). Getting same issue.

**Comment by jeet4320** [comment]
@mykola-mokhnach added full server log: https://gist.github.com/jeet4320/930a352ceba23a69fb51dabe69b73ee3. I am using Appium version 1.7.0, not sure why is it showing "Welcome to Appium v1.6.5" on server log.

**Comment by mykola-mokhnach** [comment]
> not sure why is it showing "Welcome to Appium v1.6.5" on server log. 

It would be good to figure out why

**Comment by jeet4320** [comment]
I reinstalled appium desktop, restarted my laptop still I see " Welcome to Appium v1.6.5". Do you see " Welcome to Appium v1.7.0" on your appium desktop? @mykola-mokhnach . If yes can you please help me to resolve this issue as well.

**Comment by imurchie** [comment]
I don't think a version of `appium-desktop` with 1.7.0 has been released yet.

Commits: https://github.com/appium/appium-desktop/commits/master

**Comment by jeet4320** [comment]
Sorry for confusion. I am talking about appium version (not appium desktop version, I already have appium desktop v1.2.1). I see "Start Server v1.6.5" as per below screenshot. I should see v1.7.0 (if I do appium -v on terminal I see v1.7.0).
![screen shot 2017-09-21 at 10 02 42 am](https://user-images.githubusercontent.com/11895196/30702981-0a43ba8e-9eb4-11e7-9b29-5c990db64c5e.png)

**Comment by imurchie** [comment]
Yes. And I am saying that there is no desktop version yet that comes bundled with 1.7.0. The terminal version is altogether different.

**Comment by jeet4320** [comment]
ok. Then I have all latest versions of appium(v1.7.0) and appium-desktop(1.2.1). So can you please help me with the actual screenshot not getting generated issue? I have attached logs as well. This is the link https://gist.github.com/jeet4320/930a352ceba23a69fb51dabe69b73ee3.

**Comment by mykola-mokhnach** [comment]
It's simple - 1.6.5 does not contain screenshot workaround, which is present in 1.7.0, so you need to wait until the next version of Appium Desktop bundled with 1.7.0 is released.

**Comment by dpgraham** [comment]
You can use Appium 1.7.0 from the command line and run sessions on it in Appium desktop.
