### ISSUE TITLE
Getting httphostconnectionexception while running Android on Windows: Connection refused:

### ISSUE THREAD

**Issue by sanojqa** [appium/appium#9262]
Getting httphostconnectionexception while running Android on Windows.

Appium version: 1.4.16
Android version: 6.0
Windows 7

After some test case it automatically coming in the logs.

Anyone have the idea on this error?

Actual Error:

org.openqa.selenium.WebDriverException:
org.apache.http.conn.HttpHostConnectException: Connect to
127.0.0.1:49341 [/127.0.0.1] failed: Connection refused:

**Comment by mykola-mokhnach** [comment]
v. 1.4.16 is not supported anymore. Please update to 1.7.0
