### ISSUE TITLE
Unable to start WebDriverAgent session: Could not proxy command to remote server. Original error: Error: Invalid protocol

### ISSUE THREAD

**Issue by rsudam** [appium/appium#9264]
## The problem
I am trying to run appium for my iOS 10.2.1 app using appium 1.6.5. I have configured and installed all the external dependencies. When I am trying to run my sample script, the following error is appearing on my appium log. 
"Unable to start WebDriverAgent session: Could not proxy command to remote server. Original error: Error: Invalid protocol"

Please help and I am stuck at initial stage and wouldn't possible to automate anything. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS(10.12.3) 
* Node.js version (unless using Appium.app|exe):v6.11.0
* Mobile platform/version under test: 10.2.1
* Real device or emulator/simulator:Real Device
* Appium CLI or Appium.app|exe:

## Link to Appium logs
[appium-server-logs.txt](https://github.com/appium/appium/files/1320532/appium-server-logs.txt)

## Code To Reproduce Issue [ Good To Have ]

```

DesiredCapabilities capabilitiesForAppium = new DesiredCapabilities();
		capabilitiesForAppium.setCapability(MobileCapabilityType.PLATFORM_NAME, "iOS");
		capabilitiesForAppium.setCapability(MobileCapabilityType.PLATFORM_VERSION, "10.2.1");
		capabilitiesForAppium.setCapability(MobileCapabilityType.DEVICE_NAME, DeviceName);
		capabilitiesForAppium.setCapability(IOSMobileCapabilityType.LAUNCH_TIMEOUT, 10000);
		capabilitiesForAppium.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.IOS_XCUI_TEST);
		capabilitiesForAppium.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT,8000);
		capabilitiesForAppium.setCapability("showXcodeLog", true);
		capabilitiesForAppium.setCapability(MobileCapabilityType.UDID, udid);
		capabilitiesForAppium.setCapability(IOSMobileCapabilityType.BUNDLE_ID, bundleID);
IOSDriver driver = new IOSDriver(new URL("http://127.0.0.1:4723/wd/hub"),
				capabilitiesForAppium);
		driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		
		driver.closeApp();
```

**Comment by mykola-mokhnach** [comment]
Make sure the correct iproxy binary is installed and available in PATH. You can also try to start WDA application manually on the device, execute `iproxy 8100 8100` from command line and then check if you get any response on http://localhost:8100.

**Comment by rsudam** [comment]
Hi @mykola-mokhnach, apologies I was bit drifted from the project and couldn't able to reply you back.  I did follow your instructions and please find the below results. 

iproxy 8100 8100
```
waiting for connection
accepted connection, fd = 4
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 2 (serial: 808fa5c6139e362aaf2ed3080dffa026c4caa041), port 8100
run_ctos_loop: fd = 4
run_stoc_loop: fd = 4
```

http://localhost:8100/
```
{
  "value" : "Unhandled endpoint: \/ -- http:\/\/localhost:8100\/ with parameters {\n    wildcards =     (\n        \"\"\n    );\n}",
  "sessionId" : "F95F8C83-14C2-46E4-9BD7-4B650A071BCB",
  "status" : 1
}
```
Please suggest me, thanks.

**Comment by rsudam** [comment]
@mykola-mokhnach, do you get any chance to look into this.

**Comment by mykola-mokhnach** [comment]
Try to upgrade Appium to the most recent version 1.7.1

**Comment by rsudam** [comment]
After degrading to appium version 1.6.4, able to launch the application, not sure how this issue persists in 1.6.5
