### ISSUE TITLE
getting error Unable to launch WebDriverAgent because of xcodebuild failure: Carthage not found

### ISSUE THREAD

**Issue by kommuswamy** [appium/appium#9265]
getting error Unable to launch WebDriverAgent because of xcodebuild failure: Carthage not found. Install using "brew install carthage"

When I ran the above command, it shows Warning message **" Carthage 0.24 already installed "** and I have checked the Carthage version it shows 0.24.

## Environment

* Appium version :1.7.0
* Desktop OS/: 10.12.6
* Node.js version (unless using Appium.app|exe): 6.11
* Mobile platform/version under test: 10.3
* Real device or emulator/simulator: iPhone

Appium Logs: https://gist.github.com/kommuswamy/1ef2b797ff6c87742e548a6b22cbd1f4

**Comment by mykola-mokhnach** [comment]
Make sure it is available in PATH and this environment variable is visible to Appium process

**Comment by tobecrazy** [comment]
I met the same issue.
$ brew install carthage
Updating Homebrew...
Warning: carthage 0.25.0 is already installed

**Comment by pkulkarnii** [comment]
Try Running command $appium-doctor to run a diagnostic.

**Comment by kommuswamy** [comment]
Hi @pkulkarnii ,

I ran this  **$appium-doctor** command, then it shows everything is good message.

Thanks :)

**Comment by kommuswamy** [comment]
@mykola-mokhnach, How can I verify the Path in MacOS and environment variable is visible or not to Appium process?

Thanks

**Comment by kommuswamy** [comment]
Hi @mykola-mokhnach ,

even I am seeing the same issue in appium 1.7.0-beta.

**Comment by enguyen1967** [comment]
does anyone here has solution how to fix it?
I am running only simulator on Jenkins with
Xcode 8.3.3
Appium 1.7.1

I got the error Unable to launch WebDriverAgent
[debug] [XCUITest] The app has been installed successfully.
[debug] [BaseDriver] Event ‘appInstalled’ logged at 1506633726485 (14:22:06 GMT-0700 (PDT))
[XCUITest] Using WDA path: ‘/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent’
[XCUITest] Using WDA agent: ‘/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj’
[debug] [XCUITest] Capability ‘useNewWDA’ set to false, so trying to reuse currently running WDA instance at ‘http://localhost:8100/’
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [XCUITest] WDA is not listening at ‘http://localhost:8100/’. Rebuilding…
[debug] [BaseDriver] Event ‘wdaStartAttempted’ logged at 1506633726525 (14:22:06 GMT-0700 (PDT))
[XCUITest] Launching WebDriverAgent on the device
[XCUITest] Error: Carthage not found. Install using brew install carthage
at Object.wrappedLogger.errorAndThrow (…/…/lib/logging.js:63:13)
at checkForDependencies$ (…/…/…/lib/wda/utils.js:59:9)
at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
at 
Error: Carthage not found. Install using brew install carthage
at Object.wrappedLogger.errorAndThrow (…/…/lib/logging.js:63:13)
at checkForDependencies$ (…/…/…/lib/wda/utils.js:59:9)
at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
at

I ran Appium Doctor and seem everything are ok
auto-mac-01:~ autobot$ appium-doctor --ios
info AppiumDoctor Appium Doctor v.1.4.3
info AppiumDoctor ### Diagnostic starting ###
info AppiumDoctor  :heavy_check_mark: The Node.js binary was found at: /usr/local/bin/node
info AppiumDoctor  :heavy_check_mark: Node version is 8.5.0
info AppiumDoctor  :heavy_check_mark: Xcode is installed at: /Applications/Xcode.app/Contents/Developer
info AppiumDoctor  :heavy_check_mark: Xcode Command Line Tools are installed.
info AppiumDoctor  :heavy_check_mark: DevToolsSecurity is enabled.
info AppiumDoctor  :heavy_check_mark: The Authorization DB is set up properly.
info AppiumDoctor  :heavy_check_mark: Carthage was found at: /usr/local/bin/carthage
info AppiumDoctor  :heavy_check_mark: HOME is set to: /Users/autobot
info AppiumDoctor ### Diagnostic completed, no fix needed. ###
info AppiumDoctor
info AppiumDoctor Everything looks good, bye!
info AppiumDoctor

If I ran locally then everything work fine.
Please help me how to fix this? I saw couple post about this but nothing help. Much appreciated.

**Comment by garlapati99** [comment]
I am also facing the same issue. Carthage is installed properly with 0.25 version. I am still unable to start the appium on ios simulator. Thanks

**Comment by FA-tvonmoll** [comment]
Just curious: what happens when you make a new freestyle jenkins job with `appium-doctor` just as an execute shell build step? It might be that you need to set your `PATH` as a pre-build step if that fails.

**Comment by enguyen1967** [comment]
Hi FA-tvonmoll! 
I am sure your comment, you mean running appium-doctor every build to check for Carthage?

**Comment by FA-tvonmoll** [comment]
Not necessarily (although I suppose you could). The suggestion it more to double-check that the `PATH` as far as Jenkins is concerned is what you think it is (I see where you ran `$ appium-doctor` above, but it looks like that was from the context of a user on the machine, not from Jenkins).

You could also just `echo $PATH` in a freestyle job just to make sure  `/usr/local/bin` (where your Carthage installation lives) is indeed in there from the Jenkins perspective. If it isn't, you can add it in on a per-job basis with a pre-build shell step that includes `export PATH=/usr/local/bin:$PATH`

**Comment by Vinothbk** [comment]
I am facing the same issue, can anyone help me here with APPIUM V1.7.1
tried in both the way Desktop appium and CLI method both throws this error, i am not getting the above comment can anyone explain it?

**Comment by tareqalomour** [comment]
I fixed this by doing the following steps:

1- Right click on your project > Run as > Run Configuration
2- Select Environment
3- Update your project PATH to be like this: /bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin

**Comment by Bhuvanavd** [comment]
Have a scenario,  code in eclipse on windows,  start the appium server on mac from windows.
Installed appium through npm, manually if i start the server on mac and trigger the run using the eclispe code on windows is working fine. when i start the appium server though code, Im getting the below error. Also tried setting the PATH variable on mac and also in eclipse environment Run congiuration.–> No luck.
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: "Carthage not found. Install using brew install carthage". (WARNING: The server did not provide any stacktrace information)

Note: Carthage is installed. carthage version- 0.27
appium 1.7.1
node version - v6.4.0
npm version -v3.10.6

Appreciate help

**Comment by Vinothbk** [comment]
same issue i am facing, can anyone help on this please?

**Comment by Bhuvanavd** [comment]
Fixed the issue. Thanks!. Make sure the PATH variable is available for all the processes.

**Comment by Niravpatel102** [comment]
@Bhuvanavd 
Can you please explain how did you fixed this issue?
i am facing same issue , can you help?

**Comment by tareqalomour** [comment]
@Niravpatel102 Read my above comment, this will fix your issue.

**Comment by Niravpatel102** [comment]
@tareqalomour 

Thank you.

**Comment by shabsi4u** [comment]
I am able to see the /usr/local/bin in the Appium process path, and in the /etc/paths file. I can't use the solution in #9265 since I am trying to use the Appium Mac app with simulator. Could you please help unblock me on this? @mykola-mokhnach

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/java-client/blob/master/docs/environment.md

**Comment by shabsi4u** [comment]
Thanks for the update @mykola-mokhnach . Unfortunately this. does not solve the problem for me. Listing this out again:

1. My path variable has all the required binaries' bin folders listed when I do echo $PATH
2. I am using Appium.app on Mac, so I am not invoking this programmatically and I see no reason why it could not get the PATH value
3. When I do a ps -eww on the Appium PID, I see the path reflected correctly.
4. I can see the PATH to Carthage in my etc/paths file.

Not sure what would be wrong after this.

**Comment by imurchie** [comment]
@shabsi4u The issue you are on is quite old. Can you post your _full_ Appium server logs as a link to a [gist](https://gist.github.com) so the details of the problem can be seen? Not much can be done otherwise.

**Comment by mykola-mokhnach** [comment]
is carthage utility itself working and up to date?

**Comment by shabsi4u** [comment]
I finally got it working. I had uninstall all the installed appium dependencies and appium itself and perform an install again. Post a reboot after the reinstall of all the components, things work fine, even though all the settings remain the same as the previous one. It was probably a one-off error that I was running into. 
Thanks for the help @mykola-mokhnach @imurchie

**Comment by ssmalan94** [comment]
For me Carthage is Installed in /usr/local/bin. But appium refers only on '/usr/bin:/bin:/usr/sbin:/sbin' these places. Am not able to copy the Carthage to any of the above folders. 

The issue is only when launching the Appium Inspector for inspecting the element. Am able to run the test by starting the Appium from Command line

Can you guys help me to change the Path Variable Path where Appium referring too??

**Comment by LyubomirStoimchev** [comment]
@ssmalan94 I had the same problem when I updated from 1.6.2 to 1.6.3 and couldn't resolve it.
When I reverted back to 1.6.2 everything was fine.

**Comment by JGVB** [comment]
@tareqalomour What project are we right clicking on?  carthage is in `usr/local/bin`, and appium does not use that PATH.

**Comment by megaspaz** [comment]
@LyubomirStoimchev Same issue... looks like 1.6.3 changes the environment behavior as it doesn't use them... android also ignored...

`An unknown server-side error occurred while processing the command. Original error: Could not find adb Please set the ANDROID_HOME environment variable with the Android SDK root directory path. (Selenium::WebDriver::Error::UnknownError)`

Anyway, you can workaround for ios, if turning off SIP first, then
`sudo ln -s /usr/local/Cellar/carthage/0.30.1/bin/carthage /usr/bin/carthage`

maybe you can turn SIP back on... but I dunno, I already have SIP disabled... I also thought fixing android could be more hassle than worth it... so I rolled back to 1.6.2 and removed the link...

**Comment by dpgraham** [comment]
Hey folks. I'd recommend reverting Appium Desktop to 1.6.2

I'm pretty sure there's a bug that's overwriting the environment variables.

I'm working on a fix now.

**Comment by dpgraham** [comment]
I published a hot-fix for this: https://github.com/appium/appium-desktop/releases/download/v1.6.3/Appium-1.6.3.dmg... there was a race-conditioning causing the `PATH` variable to be overridden

It's a pre-release. I've tested it on my machine and it works fine, @megaspaz @JGVB @ssmalan94 @LyubomirStoimchev would one of you be able to try it and see if it works for you?

**Comment by ssmalan94** [comment]
Sure... I'll check and revert

**Comment by megaspaz** [comment]
@dpgraham for my limited use at the moment, it looked fine to me...

**Comment by dpgraham** [comment]
@ssmalan94 If it works you won't need to revert. I'll just publish that version and that will be the up-to-date verison.
