### ISSUE TITLE
[Xcode 9] Cannot detect any element in Safari

### ISSUE THREAD

**Issue by luisromanwp** [appium/appium#9266]
## The problem

I'm trying to use the Appium Inspector to detect elements in Safari but I cannot detect any element inside the webview, this happens after I updated to Xcode 9 and Appium 1.7.0

Here you have the appium session log:
https://gist.github.com/luisromanwp/408f5dd0dc8e2c6ef8156b58ee97d8ac

![inspector appium](https://user-images.githubusercontent.com/24296182/30695186-82712ba4-9ed7-11e7-9b75-229f2dc95d27.jpeg)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.0
* Last Appium version that did not exhibit the issue (if applicable):  1.7.0 with Xcode 8
* Desktop OS/version used to run Appium: Mac OS X
* Mobile platform/version under test:  iPhone 7, iPhone SE (10.3 and 11)
* Real device or emulator/simulator: emulator

**Comment by ochubey** [comment]
Do you see WebView in Desktop Safari (Develop > {PhoneName} > Safari ...)?

**Comment by mykola-mokhnach** [comment]
Appium Desktop is not designed to work with WebViews, but rather native elements. Please use remote debugging for such cases.

**Comment by luisromanwp** [comment]
@mykola-mokhnach thanks for your info, but then why I could detect elements in Safari with Xcode 8 and Appium Desktop?

**Comment by mykola-mokhnach** [comment]
Use the standard remote debugging feature as @ochubey mentioned above
