### ISSUE TITLE
issue in spying/identify ios objects using appium desktop ie 1.6.5

### ISSUE THREAD

**Issue by CharanpreetHora** [appium/appium#9270]
issue in spying/identify ios objects using appium desktop ie 1.6.5

Appium 1.6.5
ios 10

Most of the objects i am able to identify. But there are objects like "Done" button, "> " on a ribbon which comes after click on textfiled object where we need to enter numbers. 
Until We click on Done button ribbon will not go away. Is there any other way of identifying objects for Native ios app. ANy other tool?

Kindly help.

thanks.

**Comment by mykola-mokhnach** [comment]
Please use Appium forum to ask questions.
