### ISSUE TITLE
Getting httphostconnectionexception while running Android on Windows

### ISSUE THREAD

**Issue by sanojqa** [appium/appium#9271]
Getting httphostconnectionexception while running Android on Windows

Appium version: 1.6.5
Android version: 6.0
OS: Windows 7

After some test case it automatically coming in the logs.

Observation varies depends on system. One system it may happen after 10 test cases and other it happens after 15 test cases like that there is no specific order on that failure. Why this failure happening.

Anyone have the idea on this error?

Actual Error:

org.openqa.selenium.WebDriverException:
org.apache.http.conn.HttpHostConnectException: Connect to
127.0.0.1:49341 [/127.0.0.1] failed: Connection refused:

**Comment by mykola-mokhnach** [comment]
Please attach full server log. _org.apache.http.conn.HttpHostConnectException_ usually signals that the server is down/not responding and the client cannot connect to it.

**Comment by mykola-mokhnach** [comment]
Closed as inactive
