### ISSUE TITLE
Tests stops working randomly after migrating to 1.7

### ISSUE THREAD

**Issue by faran** [appium/appium#9273]
## The problem

Started running my tests after migrating to Appium 1.7. Very first run stopped randomly after around 50 test cases there was another 200 to go they all failed with same error(gist). I thought once off problem. Kicked the run back again. 
But it started failing again, failure was on different test but there was still 180 to go. So bit puzzled. 

Will try to give as much detail as possible and apologies in advance if this is logged before i have searched to my abilities and cant find similar issue.

## Environment
Appium 1.7
Mac Mini running Sierra, 10.12.6
Xcode 9,
iPhone 6s with iOS 11. 
Node is 8.2.1

Previously working fine with Appium 1.6.5 and iOS 10.3
## Link to Appium logs

https://gist.github.com/faran/c0342d99b182b67e2ebbf09558404c12

**Comment by mykola-mokhnach** [comment]
This issue happens because xcodebuild log file is growing very fast, so we cannot fit it into the memory when we try to read it.
We've addressed this problem recently and the fix will be available in the next beta version (most likely today). You could temporarily set the _preventWDAAttachments_ capability to _false_ as a workaround.

**Comment by faran** [comment]
Thanks a lot , going to try capability mentioned.

**Comment by faran** [comment]
@mykola-mokhnach Just FYI 
I introduced aforementioned capability and it did not work. Waiting for some kind of fix or new information to try out.

**Comment by mykola-mokhnach** [comment]
I'll let you know when the fix is available in beta, so you can try it.

**Comment by mykola-mokhnach** [comment]
Try also to clear up the Xcode derived data folder

**Comment by faran** [comment]
ok will clear xcode derived data folder but test case are showing similar pattern. it run up to some round about number of lets say 50 - 55 test cases then fail.

**Comment by mykola-mokhnach** [comment]
There is also _clearSystemFiles_ capability. Setting it to _true_ should automatically delete xcode logs on each driver session termination

**Comment by faran** [comment]
going to try clearSystemFiles. 
Will update accordingly in due course.
Many thanks for your swift responses.

**Comment by mykola-mokhnach** [comment]
The patch has been published to 1.7.0-beta. Make sure the version of appium-xcuitest-driver component is 2.50.0 or higher.

**Comment by mykola-mokhnach** [comment]
@faran Can you please confirm the patch works for you?

**Comment by faran** [comment]
Going to try patch now. But both flags did not provide solution.

**Comment by niu0220** [comment]
where can I find the patch? I can help to test too

**Comment by faran** [comment]
@mykola-mokhnach Hey, Patch is working for me, i do not see the reported problem. Thanks again for swift response.

@niu0220 do 
"npm install -g appium@1.7.0-beta"

**Comment by vbutzke** [comment]
Hey, I am facing this issue still.
I am with version 1.7.2, already tried mentioned capabilities, and cleaning XCode Derived Data folder, and nothing seems to be helping, do you have any other suggestions?

**Comment by faran** [comment]
@vbutzke I am still on 1.7.1 and have not experience same problem since. You can double check with 1.7.1 and if problem goes away means bug in 1.7.2 and then you can log separate ticket for the problem.

**Comment by vbutzke** [comment]
Thanks for your response @faran I will try it out.

**Comment by vbutzke** [comment]
@faran Changed to 1.7.1 and the problem still occurs. Seems like some of the tests are ignored by appium like they didn't exist. The console output is success for all tests run with no failures, but there are 23 tests and only random 19 or 18 are running each time.

**Comment by faran** [comment]
@vbutzke Ok so i don't know how you concluding that this is same issue.
Here are the logs i got. https://gist.github.com/faran/c0342d99b182b67e2ebbf09558404c12 
You need to check your logs first and dig in what you can find and then search appium forums. I logged the problem here once i knew that its a bug.

**Comment by vbutzke** [comment]
@faran I "concluded" it because the last test didn't close the app on the simulator, like if a test was stopped on the middle of its execution. Also, as you can see on the screenshot above, the tests are not even considered and no error is displayed, and logs are not telling me anything valuable as I've already checked several times, so it really made sense to be a memory/cash problem as well as yours. If I had something better than this I would be certainly somewhere else, but I am having a hard time on finding anything close to what is happening here, and I thought this issue could be close to what I am looking for. Anyway thanks for your time.

**Comment by faran** [comment]
@vbutzke try these 
capabilities.setCapability("preventWDAAttachments", false);
capabilities.setCapability("clearSystemFiles", true);
and also you need to dig logs if you want to resolve the issue otherwise its like finding the needle in haystack.
Try few things from here
https://github.com/appium/appium-xcuitest-driver#desired-capabilities
