### ISSUE TITLE
Great delay when searching for locators

### ISSUE THREAD

**Issue by manyakin** [appium/appium#9274]
## The problem

After the upgrade to version 1.6.5, there is a very large delay in searching for items. After returning back to version 1.6.0 the problem remained. After the upgrade to version 1.7.0, the delay is still high. The speed of the tests has increased by 7-10 times. What am I doing wrong? What could be the problem? Please, help.

In the gist, I attached the test logs, which was previously performed in 2 minutes, and now runs for 9 minutes.

## Environment

* Appium version  that exhibits the issue: 1.7.0
* Last Appium version that did not exhibit the issue : 1.6.0
* Desktop OS/version used to run Appium:  Mac OS(10.12.5)
* Node.js version : 8.5.0
* Mobile platform/version under test: 10.3.3
* Real device or emulator/simulator:Real Device
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/manyakin/65531e2e7b4aa3cc396523a38d588d9d

## Code To Reproduce Issue [ Good To Have ]

        DesiredCapabilities capa = new DesiredCapabilities();
           capa.setCapability(MobileCapabilityType.DEVICE_NAME, "Iphone_6");
           capa.setCapability(MobileCapabilityType.UDID, "###");
           capa.setCapability(MobileCapabilityType.PLATFORM_NAME, "iOS");
           capa.setCapability(MobileCapabilityType.PLATFORM_VERSION, "10.3.2");
           capa.setCapability(MobileCapabilityType.AUTOMATION_NAME, "XCUITest");
           capa.setCapability(MobileCapabilityType.FULL_RESET,"True");
           capa.setCapability("xcodeConfigFile", "Config.xcconfig");
           capa.setCapability("keychainPath", "BIA.keychain");
           capa.setCapability("keychainPassword", "###");
           capa.setCapability("app", "app.ipa");
           capa.setCapability("unicodeKeyboard", true);
           capa.setCapability("resetKeyboard", true);
           capa.setCapability("maxTypingFrequency", "30");

        driver = new IOSDriver(new URL("http://127.0.0.1:4444/wd/hub"), capa);
        driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);

**Comment by mykola-mokhnach** [comment]
There is nothing that can be done on Appium side to make the lookup faster. It's mainly how XCTest works, and, a little bit, on [WebDriverAgent](https://github.com/facebook/WebDriverAgent/issues) side.
