### ISSUE TITLE
[Mac] Xcode version 9.0 is not yet supported 

### ISSUE THREAD

**Issue by ashishranjanJN** [appium/appium#9275]
Unknowingly I have upgraded my Xcode today to 9.0 and now I am not able to run Appium.

When can we expected to get it up and running?

Xcode: 9.0
Appium: Appium Desktop [Version 1.1.1 (1.1.1)]

**Comment by imurchie** [comment]
You need Appium 1.7.0 at least.

**Comment by tobecrazy** [comment]
A new session could not be created. Details: Appium's IosDriver does not support xcode version 9.0. Apple has deprecated UIAutomation. Use the "XCUITest" automationName capability instead.

**Comment by ashishranjanJN** [comment]
@imurchie But the latest Appium Desktop version is 1.2.1, which I have updated.
But still I am not able to run.
