### ISSUE TITLE
X/Y coordinates are swapped in iOS landscape mode

### ISSUE THREAD

**Issue by rg-software** [appium/appium#9282]
## The problem

The recent XCode update seemingly broke screen coordinates.
Let's consider the landscape mode. 
Appium correctly returns screen tap size: height = 768, width = 1024.
However, the upper-left corner is (0, 768), and the direction to the right corresponds to the smaller value of the second coordinate. The (0, 0) point is somewhere near the right-hand side of the device (but not exactly in the corner, since it ends after 768 points, not after 1024).
To go down, I have to increase the first coordinate. Say, (500, 768) is somewhere in the middle-left of the screen.

The "landscape right" mode has different axis directions.

It is unfortunately that the problem cannot be fixed by swapping some coordinates on the client side since some parts of the screen are simply inaccessible (right screen side in the range 768-1024).

## Environment
* Appium 1.7.0 with XCode 9
* Appium 1.6.5 with XCode 8 is OK
* MacOS Sierra
* Real IOS 10
* Real device or emulator/simulator:

**Comment by mykola-mokhnach** [comment]
It's XCTest bug. We had a workaround for it in Xcode8, but now it has been changed again. You can try [this patch](https://github.com/facebook/WebDriverAgent/pull/714) to check it out under Xcode9.

**Comment by rg-software** [comment]
Sorry, what is the solution for this problem for Appium 1.7.1? Do I still need to apply the patch manually and how to do it?
