### ISSUE TITLE
Unable to detect expected Webview whereas Safari is able to populate

### ISSUE THREAD

**Issue by wadjevaishali** [appium/appium#9283]
## The problem
I am trying to test a Webview (Mopub Ad) loaded inside the App in a container(UIView). Whenever I run the test, I see the native and webview context. Then I switch to webview context and print pagesource to check the html content. It is always empty. When I checked Mac Safari->Develop->Simulator, I could see a couple of links to webviews.
I am able to test on Android.

## Environment

* Appium version (or git revision) that exhibits the issue:1.7.0
* Last Appium version that did not exhibit the issue (if applicable):1.7.0
* Desktop OS/version used to run Appium: Mac OS 10.12.6
* Node.js version (unless using Appium.app|exe):8.4.0
* Mobile platform/version under test:iOS 10.3
* Real device or emulator/simulator: iPhone 7 Simulator
* Appium CLI or Appium.app|exe: Appium CLI

## Code To Reproduce Issue [ Good To Have ]
Capabilities:
            DesiredCapabilities capabilities = new DesiredCapabilities();
            capabilities.setCapability("deviceName", "iPhone 7");
            capabilities.setCapability("platformName", "iOS");
            capabilities.setCapability("platformVersion", "10.3");
            capabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, "100");
Sample Code:
            Set<String> contextNames = iosDriver.getContextHandles();
            System.out.println(contextNames.size());

            for(String contextName : contextNames){
                System.out.println(contextName);
                if(contextName.contains("WEBVIEW")){
                    iosDriver.context(contextName);
                    break;
                }
            }
            System.out.println(iosDriver.getPageSource());
PageSource content: <html><head></head><body></body></html>

**Comment by mykola-mokhnach** [comment]
Please attach full server log. What type of webview is used? Is it [SafariViewService](https://github.com/appium/appium/issues/9197)?

**Comment by wadjevaishali** [comment]
This is a third party Ad server webview like MPAdView, DFPBannerView. Ad servers like Mopub(Twitter), DFP(Google). It's not SafariViewService.

There are no errors in the logs, hence did not share.

**Comment by mykola-mokhnach** [comment]
Sorry, we won't be able to help without logs.

**Comment by shynkevich-alex** [comment]
@wadjevaishali Ads can use java script so you can't see all elements of ad. I also have some tests for advertisement and I do not use webView content for them.

**Comment by wadjevaishali** [comment]
@mykola-mokhnach I am not sure if I can share logs with you. Let me confirm once.
@shynkevich-alex you may be right. But our use case is to test the webview because we want to make sure ad rendered properly. There is no such issue with Android test. I am hopeful that iOS will also show.
Anyways, how are you testing ads then?

**Comment by shynkevich-alex** [comment]
@wadjevaishali We test only what passible. For example logic of ads call etc...
If you  will found a solution to test advertisement in iOS let me know please.

**Comment by wadjevaishali** [comment]
@mykola-mokhnach To the surprise, this time I got more than one webview contexts including the one I was looking for and my test passed. But I still suspect some delay from Appium side.
Please take a look at the below server logs.
https://gist.github.com/wadjevaishali/a8ab58e49b60fc18f3399d01b87ee4a3
You can see webview contexts on line 305 in the gist.

**Comment by wadjevaishali** [comment]
@shynkevich-alex Sure, I can help you out with sample steps so that you can try on your ad.

**Comment by mykola-mokhnach** [comment]
So now it's random that the webview is not detected?

**Comment by wadjevaishali** [comment]
Yes, you can say that. The time I upgraded to Appium 1.7, I experience server get stuck sometimes, delay in response.
Do you think this could be the reasons for unavailability of Webview?

**Comment by wadjevaishali** [comment]
@shynkevich-alex I have documented sample steps here: https://gist.github.com/wadjevaishali/aa9cb6856da3633d362bbccf5a0efa6f

I hope that it will help you some way.

**Comment by shynkevich-alex** [comment]
@wadjevaishali Thank you a lot.

**Comment by shynkevich-alex** [comment]
@wadjevaishali  So, I tried your code and I do not see WebView contexts. Only NATIVE.
But in native I can see some elements of banners, natives and inters. (buttons, images, texts, etc..)
Unfortunately not all of them detected because of js.
The major problem for us it is testing of interstitials where user should drag and drop some items when we can't detect them to drag. Do you have similar scenario wich has success usin WebView context?

**Comment by ambatisuman** [comment]
I do have the similar issue with Appium 1.7.0
When we used Appium 1.6.5, it was fine in handling the webviews and with the 1.7.0 it is only handling the Native. Not really sure that, how we can handle this issue now.
Any suggestions would be great.

**Comment by wadjevaishali** [comment]
@shynkevich-alex For banner, I was able to find webview contexts most of the times. Are you waiting for the ad to be loaded before you are check the webview context? This is one of the ways to troubleshoot the webview.

We do not have similar test scenario as yours intersitial but we do have deep linking. Let me try getting interstitial webview context.

**Comment by wadjevaishali** [comment]
@ambatisuman Is it happening on Android, iOS or both? Also, check for delays in getting the webview contexts.

**Comment by shynkevich-alex** [comment]
@wadjevaishali  Could you provide your driver capabilities?

**Comment by wadjevaishali** [comment]
@shynkevich-alex it's pretty straightforward.
   DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability("deviceName", "Android Emulator");
        capabilities.setCapability("platformName", "Android");
        capabilities.setCapability("app", "xyz.apk");
        androidDriver = new AndroidDriver<WebElement>(new URL("http://0.0.0.0:4723/wd/hub"), capabilities);

No webview context found for real devices! So far I was testing with Emulators/Simulators. This is very lame in terms of feature.

**Comment by wadjevaishali** [comment]
@mykola-mokhnach Can you tell me why simulators/emulators can display webviews but not real devices? I am trying to understand what makes a difference or what blocking it from displaying on real devices because same functionality should be working on similar!
Any help would be good.

**Comment by mykola-mokhnach** [comment]
Because on real devices Appium requires IWDP (web debug proxy) in order to communicate with webviews. This component is developed by a third party and Apple puts some changes into the protocol from time to time, so all the dependent components need to be in sync then. This takes effort and time. 

And Simulator simply makes webviews available directly via web socket, so we can interact with them without any additional intermediate layers.
