### ISSUE TITLE
Possible Bug: "A session is either terminated or not started"

### ISSUE THREAD

**Issue by aliveli186** [appium/appium#9285]
## The problem

I have 2 or more threads that wait for some elements to be enabled/displayed by polling every 500 ms with driver.FindElements().
The threads which start to poll at the same time receive the "A session is either terminated or not started" exception but **there is no log in Appium logs related to those requests** and **there is no DELETE session log in Appium logs**.

I guess it's related with making parallel requests.
If more than one request arrives to the driver (AndroidDriver) it throws an exception internally without even forwarding the requests to the server. That's why those requests don't appear in Appium logs. Or there is something else going on?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5/1.2.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Android 4.4/6.0
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe:

## Details

Here is the log of my app:
From the first 3 log lines below the request for "first_name_input" starts before the other 2, which fail, and there is log for that first request in Appium logs as well but nothing about the other 2.

```
17:37:19.484 TryFindElement: By.Id: com.myapp.test:id/first_name_input
17:37:19.491 TryFindElement: By.Id: com.android.packageinstaller:id/permission_deny_button
17:37:19.491 TryFindElement: By.Id: com.myapp.test:id/button2
17:37:19.544 TryFindElement error: By.Id: com.android.packageinstaller:id/permission_deny_button: A session is either terminated or not started
17:37:19.552 TryFindElement error: By.Id: com.myapp.test:id/button2: A session is either terminated or not started
17:37:20.002 TryFindElement: By.Id: com.android.packageinstaller:id/permission_deny_button
17:37:20.002 TryFindElement: By.Id: com.myapp.test:id/button2
17:37:20.070 TryFindElement error: By.Id: com.android.packageinstaller:id/permission_deny_button: A session is either terminated or not started
17:37:20.084 TryFindElement error: By.Id: com.myapp.test:id/button2: A session is either terminated or not started
17:37:20.503 TryFindElement: By.Id: com.myapp.test:id/button2
17:37:20.503 TryFindElement: By.Id: com.android.packageinstaller:id/permission_deny_button
17:37:20.534 TryFindElement error: By.Id: com.myapp.test:id/button2: A session is either terminated or not started
17:37:20.556 TryFindElement error: By.Id: com.android.packageinstaller:id/permission_deny_button: A session is either terminated or not started
17:37:20.696 TryFindElement: By.Id: com.myapp.test:id/first_name_input: Succeeded: True
```

## Link to Appium logs

https://gist.github.com/aliveli186/1b777d30ed17f3037aeb99d417350358#file-txt

**Comment by saikrishna321** [comment]
@aliveli186 i just see one device connected and one session created ..

 > I guess it's related with making parallel requests
I don't see this in the logs...

**Comment by mykola-mokhnach** [comment]
One cannot make parallel requests to the UI server in scope of a single session. These requests are anyway put into a single queue on the server side.

**Comment by aliveli186** [comment]
@saikrishna321 That's the problem it doesn't show in the logs which suggests it's firing exception before being sent to the server.

**Comment by aliveli186** [comment]
@mykola-mokhnach What should be the timespan between 2 requests to be accepted in such case?
If the android driver uses the same web client to make requests to the server then somehow it's internal state gets destroyed and firing an exception before making the actual request?

**Comment by mykola-mokhnach** [comment]
There is no such thing like time span - you must execute the next request only after the previous one returned a response.

> If the server queues the requests and not showing any error in logs then the driver has the problem.

It is theoretically possible to implement some synchronisation primitives and throw an error if two or more requests are executed at the same time in scope of a single session, but this would have added unnecessary complexity in the driver code.
