### ISSUE TITLE
Duplicate files are found when running an Appium test

### ISSUE THREAD

**Issue by tnraddatz** [appium/appium#9286]
## The problem

Duplicate files are found when running an Appium test within android studio.  This problem seems to be extremely common among recent downloads within the most recent android studio.  Some responses to the issue have been to -- exclude problematic files in the gradle, which is in part illegal, and also just doesn't work. 

##LOGS 
:app:mergeDebugAssets UP-TO-DATE
:app:processDebugJavaRes UP-TO-DATE
:app:transformResourcesWithMergeJavaResForDebug FAILED
:app:buildInfoGeneratorDebug

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK META-INF/LICENSE
	File1: C:\Users\XXXX\.gradle\caches\modules-2\files-2.1\xerces\xercesImpl\2.11.0\9bb329db1cfc4e22462c9d6b43a8432f5850e92c\xercesImpl-2.11.0.jar
	File2: C:\Users\XXXX\.gradle\caches\modules-2\files-2.1\com.fasterxml.jackson.core\jackson-annotations\2.6.0\a0990e2e812ac6639b6ce955c91b13228500476e\jackson-annotations-2.6.0.jar
	File3: C:\Users\XXXX\.gradle\caches\modules-2\files-2.1\org.apache.httpcomponents\httpmime\4.5\7bdb321e86724b16af6134a0fd22fec649eda971\httpmime-4.5.jar

**Comment by mykola-mokhnach** [comment]
I cannot understand how this problem is related to the server. If it is some, that has to do with java client then the issue should be reported to https://github.com/appium/java-client

P. S.
Have you tried ?

```
packagingOptions {
   pickFirst  'META-INF/LICENSE'
}
```
