### ISSUE TITLE
Appium, Once a week there is a notification that say:  "Your disk is almost full", and my tests fail:>

### ISSUE THREAD

**Issue by avrahamShutterFly** [appium/appium#9287]
## The problem

Once a week My mac get massage of "Your disk is almost full", this computer is run only simulators (iPad/iPhone)

## Environment

* Appium version: 1.6.5-beta 
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: mac 10.12.6
* Node.js version (unless using Appium.app|exe): v8.3.0
* Mobile platform/version under test: simulator
* Real device or emulator/simulator: simulator

## Details
Those tests run by Jenkins

**Comment by mykola-mokhnach** [comment]
Try setting the _clearSystemFiles_ capability to _true_. Appium itself does not create any extra stuff on the hard disk, but XCTest can.

**Comment by avrahamShutterFly** [comment]
Okay, I try this and update you

**Comment by avrahamShutterFly** [comment]
@mykola-mokhnach  After that I add this capability it steel give me that notification, what can I do?

**Comment by avrahamShutterFly** [comment]
@mykola-mokhnach  this folder's size is 210G 
/Users/mblea-ios/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test
There is allot of "2A7F1812-AC8D-4C99-9465-031D8D02C443" folders with different number,
there is a capabilities to delete those folder after tests?

**Comment by mykola-mokhnach** [comment]
Just delete these files manually. Or use Appium 1.7.0 + Xcode9. There WDA does not create tons of logs and attachments anymore.

**Comment by avrahamShutterFly** [comment]
@mykola-mokhnach  Thanks allot for your quick reply, I read that Appium 1.7.0 + Xcode9 not working with id's? this is true?

**Comment by avrahamShutterFly** [comment]
I mean we cannot use id to find element and click, only xpath working?!

**Comment by mykola-mokhnach** [comment]
can you provide the issue number/logs?

**Comment by avrahamShutterFly** [comment]
I am not remember where and what the issue number it is:(

**Comment by avrahamShutterFly** [comment]
You are not familiar with that?

**Comment by avrahamShutterFly** [comment]
@mykola-mokhnach
