### ISSUE TITLE
Unable to perform click action on an element in android device when launched through appium

### ISSUE THREAD

**Issue by rajeshchy** [appium/appium#9292]
This is same as   https://github.com/appium/appium/issues/9007

Please find the log below. Sorry for providing log very late. 

[-.txt](https://github.com/appium/appium/files/1329624/-.txt)

After these logs when i click on button no logs are getting generated.

**Comment by pavanbachu0604** [comment]
Can u share the code in form of gist and screenshot of screen and element you are trying to click ?

**Comment by mykola-mokhnach** [comment]
Closed as inactive
