### ISSUE TITLE
Appium 1.7.0/1.7.0-beta running very slow execution on iPad Air with iOS 11.0

### ISSUE THREAD

**Issue by swachhab** [appium/appium#9293]
## The problem
Appium 1.7.0/1.7.0-beta running very slow execution on iPad Air with iOS 11.0, previously it was running fine with iOS 10.3.3 and Appium 1.6.5, tried both appium version 1.7.0 and 1.7.0-beta, none of both are working. As I observed in appium logs, it sometimes stuck on finding any elements. Like it hangs on executing this command and run after some time:
"[HTTP] --> POST /wd/hub/session/c00f8335-67b8-4276-baef-9eb1d89411ac/elements {"using":"xpath","sessionId":"c00f8335-67b8-4276-baef-9eb1d89411ac","value":"//XCUIElementTypeImage"}"

[SAME IS RUNNING FINE WITH iPHONE 7 IOS11]

## Environment

Appium: 1.7.0 and 1.7.0-beta
iOS Device: iPad Air 2
iOS Version: 11.0

## Appium Logs

[debug] [XCUITest] Executing command 'findElements'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:4754/session/C4F1A7A8-D660-4FC6-B2CA-6265728992E3/elements] with body: {"using":"accessibility id","value":"Select Channels"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":[{"ELEMENT":"ADC8DC7C-5213-4A9F-B95B-10189578F713"}],"sessionId":"C4F1A7A8-D660-4FC6-B2CA-6265728992E3","status":0}
[debug] [MJSONWP] Responding to client with driver.findElements() result: [{"ELEMENT":"ADC8DC7C-5213-4A9F-B95B-10189578F713"}]
[HTTP] <-- POST /wd/hub/session/c00f8335-67b8-4276-baef-9eb1d89411ac/elements 200 2595 ms - 124 
[HTTP] --> POST /wd/hub/session/c00f8335-67b8-4276-baef-9eb1d89411ac/elements {"using":"xpath","sessionId":"c00f8335-67b8-4276-baef-9eb1d89411ac","value":"//XCUIElementTypeImage"}
[debug] [MJSONWP] Calling AppiumDriver.findElements() with args: ["xpath","//XCUIElementTypeImage","c00f8335-67b8-4276-baef-9eb1d89411ac"]
[debug] [XCUITest] Executing command 'findElements'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:4754/session/C4F1A7A8-D660-4FC6-B2CA-6265728992E3/elements] with body: {"using":"xpath","value":"//XCUIElementTypeImage"}
[Xcode] 8s Find the "Pick your favorite channels." StaticText
[Xcode]     t =   170.09s     Snapshot accessibility hierarchy for app with pid 2209
[Xcode]     t =   170.13s     Find: Descendants matching type Any
[Xcode]     t =   170.13s     Find: Elements matching predicate '"Pick your favorite channels." IN identifiers'
[Xcode]     t =   170.13s     Find: Element at index 0
[Xcode]     t =   170.74s Find the Application "com...dynamic" 0x1c00ded80
[Xcode]     t =   170.75s     Snapshot accessibility hierarchy for app with pid 2209
[Xcode]     t =   171.27s Find the Application "com.dynamic" 0x1c00ded80
[Xcode]     t =   171.27s     Snapshot accessibility hierarchy for app with pid 2209
[Xcode]     t =   171.41s Find the Application "com...dynamic" 0x1c00ded80
[Xcode]     t =   171.41s     Snapshot accessibility hierarchy for app with pid 2209
[Xcode]     t =   171.55s Get all elements bound by index for: Elements matching predicate '"Select Channels" IN identifiers'
[Xcode]     t =   171.56s     Snapshot accessibility hierarchy for app with pid 2209
[Xcode]     t =   171.73s     Find: Descendants matching type Any
[Xcode]     t =   171.73s     Find: Elements matching predicate '"Select Channels" IN identifiers'
[Xcode]     t =   171.74s Snapshot accessibility hierarchy for app with pid 2209
[Xcode]     t =   171.89s Find: Descendants matching type Alert
[Xcode]     t =   171.89s Snapshot accessibility hierarchy for app with pid 2209
[Xcode]     t =   172.04s Find: Descendants matching type Sheet
[Xcode]     t =   172.04s Find the Application "com.apple.springboard" 0x1c00dfdb0
[Xcode]     t =   172.05s     Snapshot accessibility hierarchy for app with pid 55
[Xcode]     t =   172.29s Snapshot accessibility hierarchy for app with pid 55
[Xcode]     t =   172.56s Find: Descendants matching type Alert
[Xcode]     t =   172.56s Snapshot accessibility hierarchy for app with pid 55
[Xcode]     t =   172.84s Find: Descendants matching type Sheet
[Xcode]     t =   173.20s Find the Application "com...dynamic" 0x1c00ded80
[Xcode]     t =   173.21s     Snapshot accessibility hierarchy for app with pid 2209
[Xcode]     t =   173.48s Find the Application "com...dynamic" 0x1c00ded80
[Xcode]     t =   173.49s     Snapshot accessibility hierarchy for app with pid 2209
[Xcode]     t =   173.63s Find the Application "com...dynamic" 0x1c00ded80
[Xcode]     t =   173.63s     Snapshot accessibility hierarchy for app with pid 2209
[Xcode]     t =   326.74s Find the Application "com...dynamic" 0x1c00ded80
[Xcode]     t =   326.75s     Snapshot accessibility hierarchy for app with pid 2209
[Xcode]     t =   326.97s Get all elements bound by index for: Elements matching predicate 'wdUID IN {879, 880, 881, 883, 884, 885, 888, 889, 890, 892, 893, 894, 896, 897, 898, 900, 901, 902, 904, 905, 906, 908, 909, 910, 912, 913, 914, 916, 917, 918, 921, 922, 923, 926, 927, 928, 930, 931, 932, 934, 935, 936, 938, 939, 940, 942, 943, 944, 946, 947, 948, 950, 951, 952, 954, 955, 956, 958, 959, 960, 962, 963, 964, 967, 968, 969, 971, 972, 973, 975, 976, 977, 980, 981, 982, 984, 985, 986, 989, 990, 991, 993, 994, 995, 997, 998, 999, 1001, 1002, 1003, 1005, 1006, 1007, 1009, 1010, 1011, 1013, 1014, 1015, 1017, 1018, 1019, 1021, 1022, 1023, 1025, 1026, 1027} AND (1 == 1 OR identifier == 0 OR frame == 0 OR value == 0 OR title == 0 OR label == 0 OR elementType == 0 OR enabled == 0 OR placeholderValue == 0)'
[Xcode]     t =   326.98s     Snapshot accessibility hierarchy for app with pid 2209
[Xcode]     t =   327.16s     Find: Descendants matching type Image
[Xcode]     t =   327.16s     Find: Elements matching predicate 'wdUID IN {879, 880, 881, 883, 884, 885, 888, 889, 890, 892, 893, 894, 896, 897, 898, 900, 901, 902, 904, 905, 906, 908, 909, 910, 912, 913, 914, 916, 917, 918, 921, 922, 923, 926, 927, 928, 930, 931, 932, 934, 935, 936, 938, 939, 940, 942, 943, 944, 946, 947, 948, 950, 951, 952, 954, 955, 956, 958, 959, 960, 962, 963, 964, 967, 968, 969, 971, 972, 973, 975, 976, 977, 980, 981, 982, 984, 985, 986, 989, 990, 991, 993, 994, 995, 997, 998, 999, 1001, 1002, 1003, 1005, 1006, 1007, 1009, 1010, 1011, 1013, 1014, 1015, 1017, 1018, 1019, 1021, 1022, 1023, 1025, 1026, 1027} AND (1 == 1 OR identifier == 0 OR frame == 0 OR value == 0 OR title == 0 OR label == 0 OR elementType == 0 OR enabled == 0 OR placeholderValue == 0)'
[Xcode]     t =   327.17s Snapshot accessibility hierarchy for app with pid 2209
[Xcode]     t =   327.34s Find: Descendants matching type Image
[Xcode]     t =   327.34s Find: Elements matching predicate 'wdUID IN {879, 880, 881, 883, 884, 885, 888, 889, 890, 892, 893, 894, 896, 897, 898, 900, 901, 902, 904, 905, 906, 908, 909, 910, 912, 913, 914, 916, 917, 918, 921, 922, 923, 926, 927, 928, 930, 931, 932, 934, 935, 936, 938, 939, 940, 942, 943, 944, 946, 947, 948, 950, 951, 952, 954, 955, 956, 958, 959, 960, 962, 963, 964, 967, 968, 969, 971, 972, 973, 975, 976, 977, 980, 981, 982, 984, 985, 986, 989, 990, 991, 993, 994, 995, 997, 998, 999, 1001, 1002, 1003, 1005, 1006, 1007, 1009, 1010, 1011, 1013, 1014, 1015, 1017, 1018, 1019, 1021, 1022, 1023, 1025, 1026, 1027} AND (1 == 1 OR identifier == 0 OR frame == 0 OR value == 0 OR title == 0 OR label == 0 OR elementType == 0 OR enabled == 0 OR placeholderValue == 0)'
[Xcode]     t =   327.35s Find: Element at index 0
[Xcode]     t =   327.35s Find the Image
[Xcode]     t =   327.35s     Snapshot accessibility hierarchy for app with pid 2209
[Xcode]     t =   327.52s     Find: Descendants matching type Image
[Xcode]     t =   327.52s     Find: Elements matching predicate 'wdUID IN {879, 880, 881, 883, 884, 885, 888, 889, 890, 892, 893, 894, 896, 897, 898, 900, 901, 902, 904, 905, 906, 908, 909, 910, 912, 913, 914, 916, 917, 918, 921, 922, 923, 926, 927, 928, 930, 931, 932, 934, 935, 936, 938, 939, 940, 942, 943, 944, 946, 947, 948, 950, 951, 952, 954, 955, 956, 958, 959, 960, 962, 963, 964, 967, 968, 969, 971, 972, 973, 975, 976, 977, 980, 981, 982, 984, 985, 986, 989, 990, 991, 993, 994, 995, 997, 998, 999, 1001, 1002, 1003, 1005, 1006, 1007, 1009, 1010, 1011, 1013, 1014, 1015, 1017, 1018, 1019, 1021, 1022, 1023, 1025, 1026, 1027} AND (1 == 1 OR identifier == 0 OR frame == 0 OR value == 0 OR title == 0 OR label == 0 OR elementType == 0 OR enabled == 0 OR placeholderValue == 0)'
[Xcode]     t =   327.53s     Find: Element at index 0
[Xcode]     t =   327.53s Snapshot accessibility hierarchy for app with pid 2209
[Xcode]     t =   327.70s Find: Descendants matching type Image
[Xcode]     t =   327.71s Find: Elements matching predicate 'wdUID IN {879, 880, 881, 883, 884, 885, 888, 889, 890, 892, 893, 894, 896, 897, 898, 900, 901, 902, 904, 905, 906, 908, 909, 910, 912, 913, 914, 916, 917, 918, 921, 922, 923, 926, 927, 928, 930, 931, 932, 934, 935, 936, 938, 939, 940, 942, 943, 944, 946, 947, 948, 950, 951, 952, 954, 955, 956, 958, 959, 960, 962, 963, 964, 967, 968, 969, 971, 972, 973, 975, 976, 977, 980, 981, 982, 984, 985, 986, 989, 990, 991, 993, 994, 995, 997, 998, 999, 1001, 1002, 1003, 1005, 1006, 1007, 1009, 1010, 1011, 1013, 1014, 1015, 1017, 1018, 1019, 1021, 1022, 1023, 1025, 1026, 1027} AND (1 == 1 OR identifier == 0 OR frame == 0 OR value == 0 OR title == 0 OR label == 0 OR elementType == 0 OR enabled == 0 OR placeholderValue == 0)'
[Xcode]     t =   327.71s Find: Element at index 1
[Xcode]     t =   327.71s Find the Image
[Xcode]     t =   327.71s     Snapshot accessibility hierarchy for app with pid 2209
[Xcode]     t =   327.89s     Find: Descendants matching type Image
[Xcode]     t =   327.89s     Find: Elements matching predicate 'wdUID IN {879, 880, 881, 883, 884, 885, 888, 889, 890, 892, 893, 894, 896, 897, 898, 900, 901, 902, 904, 905, 906, 908, 909, 910, 912, 913, 914, 916, 917, 918, 921, 922, 923, 926, 927, 928, 930, 931, 932, 934, 935, 936, 938, 939, 940, 942, 943, 944, 946, 947, 948, 950, 951, 952, 954, 955, 956, 958, 959, 960, 962, 963, 964, 967, 968, 969, 971, 972, 973, 975, 976, 977, 980, 981, 982, 984, 985, 986, 989, 990, 991, 993, 994, 995, 997, 998, 999, 1001, 1002, 1003, 1005, 1006, 1007, 1009, 1010, 1011, 1013, 1014, 1015, 1017, 1018, 1019, 1021, 1022, 1023, 1025, 1026, 1027} AND (1 == 1 OR identifier == 0 OR frame == 0 OR value == 0 OR title == 0 OR label == 0 OR elementType == 0 OR enabled == 0 OR placeholderValue == 0)'
[Xcode]     t =   327.89s     Find: Element at index 1
[Xcode]     t =   327.90s Snapshot accessibility hierarchy for app with pid 2209
[Xcode]     t =   328.07s Find: Descendants matching type I
[Xcode] mage
[Xcode]     t =   328.07s Find: Elements matching predicate 'wdUID IN {879, 880, 881, 883, 884, 885, 888, 889, 890, 892, 893, 894, 896, 897, 898, 900, 901, 902, 904, 905, 906, 908, 909, 910, 912, 913, 914, 916, 917, 918, 921, 922, 923, 926, 927, 928, 930, 931, 932, 934, 935, 936, 938, 939, 940, 942, 943, 944, 946, 947, 948, 950, 951, 952, 954, 955, 956, 958, 959, 960, 962, 963, 964, 967, 968, 969, 971, 972, 973, 975, 976, 977, 980, 981, 982, 984, 985, 986, 989, 990, 991, 993, 994, 995, 997, 998, 999, 1001, 1002, 1003, 1005, 1006, 1007, 1009, 1010, 1011, 1013, 1014, 1015, 1017, 1018, 1019, 1021, 1022, 1023, 1025, 1026, 1027} AND (1 == 1 OR identifier == 0 OR frame == 0 OR value == 0 OR title == 0 OR label == 0 OR elementType == 0 OR enabled == 0 OR placeholderValue == 0)'
[Xcode]     t =   328.07s Find: Element at index 2
[Xcode]     t =   328.07s Find the Image
[Xcode]     t =   328.08s     Snapshot accessibility hierarchy for app with pid 2209
[Xcode]     t =   328.25s     Find: Descendants matching type Image
[Xcode]     t =   328.25s     Find: Elements matching predicate 'wdUID IN {879, 880, 881, 883, 884, 885, 888, 889, 890, 892, 893, 894, 896, 897, 898, 900, 901, 902, 904, 905, 906, 908, 909, 910, 912, 913, 914, 916, 917, 918, 921, 922, 923, 926, 927, 928, 930, 931, 932, 934, 935, 936, 938, 939, 940, 942, 943, 944, 946, 947, 948, 950, 951, 952, 954, 955, 956, 958, 959, 960, 962, 963, 964, 967, 968, 969, 971, 972, 973, 975, 976, 977, 980, 981, 982, 984, 985, 986, 989, 990, 991, 993, 994, 995, 997, 998, 999, 1001, 1002, 1003, 1005, 1006, 1007, 1009, 1010, 1011, 1013, 1014, 1015, 1017, 1018, 1019, 1021, 1022, 1023, 1025, 1026, 1027} AND (1 == 1 OR identifier == 0 OR frame == 0 OR value == 0 OR title == 0 OR label == 0 OR elementType == 0 OR enabled == 0 OR placeholderValue == 0)'

**Comment by mykola-mokhnach** [comment]
Just avoid using xpath locators where possible. Closed as known issue.

**Comment by swachhab** [comment]
yes, I know and already avoiding xpath wherever possible. But why it is reproducing in ios 11 and particularly iPadAir?
