### ISSUE TITLE
Not able to swipe horizontally in appium 1.7.0  and 1.6.5

### ISSUE THREAD

**Issue by suryakanta939** [appium/appium#9296]
## The problem

Trying to swipe horizontally from left to right and from right to left but it's not able to do so.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.0 and 1.6.5
* Last Appium version that did not exhibit the issue (if applicable):1.6.3
* Desktop OS/version used to run Appium: windows 7
* Node.js version (unless using Appium.app|exe):lattest
* Mobile platform/version under test: android marshmallow

## Details

1.Not able to scroll horizontally and also vertically if there is no scrollbar.
2.alternativily using the scroll into view option to scroll up and down, but this code is working for some application, not for all
3. To scroll up and down using the scroll into view function but it's not working for all the application.
4.some how able to scroll up and down but failed to do it in horizontally way, tried all the possible options suggested by the users but not able to do so
## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Bellow is the code with touch action to do horizontally
TouchAction act=new TouchAction(driver);
	Dimension size = driver.manage().window().getSize();
    int anchor = (int) (size.height * 0.5);
    int startPoint = (int) (size.width * 0.9);
    int endPoint = (int) (size.width * 0.01);
   // new TouchAction(driver).press(startPoint, anchor).waitAction(duration).moveTo(endPoint, anchor).release().perform();
	act.press(startPoint, anchor).moveTo(endPoint, anchor).release().perform();

2.This code to  scroll down

public static void scrollToElemntBytext(AndroidDriver<AndroidElement> driver,String text){
		String s1="new UiScrollable(new UiSelector()).scrollIntoView(text(\"";
		String s2="\"));";
		driver.findElementByAndroidUIAutomator(s1+text+s2);
	}

	public static void scrollToElemntByid(AndroidDriver<AndroidElement> driver,String id){
		String s1="new UiScrollable(new UiSelector()).scrollIntoView(resourceId(\"";
		String s2="\"));";
		driver.findElementByAndroidUIAutomator(s1+id+s2);
	}

3.bellow is another option

public static void scrollToDesiredElementInVertcalWay(AndroidDriver<AndroidElement> driver,String title){
		
	        System.out.println("  tapCellByTitle(): " + title);
	        List<AndroidElement> elementList = driver.findElements(MobileBy.AndroidUIAutomator(
	                "new UiScrollable(new UiSelector().resourceIdMatches(\".*id/list\")).setMaxSearchSwipes(5).scrollIntoView("
	                        + "new UiSelector().text(\"" + title + "\"))"));
	        
	}

**Comment by mykola-mokhnach** [comment]
Are there any errors in server logs?

**Comment by suryakanta939** [comment]
Sorry, it's my bad error was in my code.  I tried in a different way and it worked fine.

**Comment by vselvaraj2011** [comment]
could you post the code. Even im Getting error while swipe

**Comment by Trisha1212** [comment]
+1
