### ISSUE TITLE
Appium 1.7.0 XCUITest Stuck in getPageSource

### ISSUE THREAD

**Issue by Dheepthi** [appium/appium#9306]
## Problem
Hello Team,

I was trying to run the iOS automation in simulator which was working fine in Appium 1.6.3.

After updating to Appium 1.7.0 the test is getting stuck at getPageSource().

Env Versions:
Appium 1.7.0

i followed this post https://www.bountysource.com/issues/38464919-getpagesource-goes-in-loop-with-after-met-error

npm uninstall -g appium
npm install -g appium --no-shrinkwrap

iOS Simulator : 10.2
XCode: 8.2.1
Mac OSx: Sierra 10.12

### **What my test do?**

Enter registeration key -- Works fine
Hit OK button -- Works fine
try to login. -- stuck to get the pageSource

[debug] [MJSONWP] Calling AppiumDriver.getPageSource() with args: ["76d752bf-94aa-48e0-8381-9dd21470f58c"]
[debug] [XCUITest] Executing command 'getPageSource'
[debug] [JSONWP Proxy] Proxying [GET /source] to [GET http://localhost:8100/session/98F7E8ED-45EF-4324-9F6F-A6515109F849/source] with no body

Note: When i try to hit "http://localhost:8100/session/98F7E8ED-45EF-4324-9F6F-A6515109F849/source" i dont get any response. also no response for http://localhost:8100/status

Please help me with this, all our tests are stuck at login page.

## Details

I have filed issue with WDA : https://github.com/facebook/WebDriverAgent/issues/730
not sure if appium is also involved so creating an issue in Appium bucket as well.

## Link to Appium logs

Full Logs with showXCodelogs enabled : https://gist.github.com/Dheepthi/e3d84dd110e7f768f1f0b88fbc3ace32

**Comment by Dheepthi** [comment]
based on comments in
#372

i tried the comment posted by
mykola-mokhnach commented on Mar 27
7d2896e should fix the problem described in this issue.

the following changes to latest WDA works fine and my tests are passing fine.

/**

Copyright (c) 2015-present, Facebook, Inc.
All rights reserved.
This source code is licensed under the BSD-style license found in the
LICENSE file in the root directory of this source tree. An additional grant
of patent rights can be found in the PATENTS file in the same directory.
*/
#import "XCUIElement+FBIsVisible.h"

#import "FBApplication.h"
#import "FBConfiguration.h"
#import "FBMathUtils.h"
#import "FBXCodeCompatibility.h"
#import "XCElementSnapshot+FBHelpers.h"
#import "XCUIElement+FBUtilities.h"
#import "XCTestPrivateSymbols.h"
#import <XCTest/XCUIDevice.h>
#import "XCElementSnapshot+FBHitPoint.h"

@implementation XCUIElement (FBIsVisible)

//- (BOOL)fb_isVisible
//{
// return self.fb_lastSnapshot.fb_isVisible;
//}

- (BOOL)fb_isVisible
{
if (!self.lastSnapshot) {
[self resolve];
}
return self.lastSnapshot.fb_isVisible;
}

@EnD

@implementation XCElementSnapshot (FBIsVisible)

/*- (BOOL)fb_isVisible
{
if (CGRectIsEmpty(self.frame)) {
return NO;
}
CGRect visibleFrame = self.visibleFrame;
if (CGRectIsEmpty(visibleFrame)) {
return NO;
}
if ([FBConfiguration shouldUseTestManagerForVisibilityDetection]) {
return [(NSNumber *)[self fb_attributeValue:FB_XCAXAIsVisibleAttribute] boolValue];
}
CGRect appFrame = [self fb_rootElement].frame;
CGSize screenSize = FBAdjustDimensionsForApplication(appFrame.size, (UIInterfaceOrientation)[XCUIDevice sharedDevice].orientation);
CGRect screenFrame = CGRectMake(0, 0, screenSize.width, screenSize.height);
if (!CGRectIntersectsRect(visibleFrame, screenFrame)) {
return NO;
}
if (CGRectContainsPoint(appFrame, self.fb_hitPoint)) {
return YES;
}
for (XCElementSnapshot elementSnapshot in self._allDescendants.copy) {
if (CGRectContainsPoint(appFrame, elementSnapshot.fb_hitPoint)) {
return YES;
}
}
return NO;
}/

**- (BOOL)fb_isVisible
{
if (CGRectIsEmpty(self.frame) || CGRectIsEmpty(self.visibleFrame)) {
return NO;
}
if ([FBConfiguration shouldUseTestManagerForVisibilityDetection]) {
return [(NSNumber )[self fb_attributeValue:FB_XCAXAIsVisibleAttribute] boolValue];
}
XCElementSnapshot app = [self _rootElement];
CGSize screenSize = FBAdjustDimensionsForApplication(app.frame.size, (UIInterfaceOrientation)[XCUIDevice sharedDevice].orientation);
CGRect screenFrame = CGRectMake(0, 0, screenSize.width, screenSize.height);
BOOL rectIntersects = CGRectIntersectsRect(self.visibleFrame, screenFrame);
BOOL isActionable = CGRectContainsPoint(app.frame, self.hitPoint);
return rectIntersects && isActionable;
}**

Why are these changes not made available along with latest appium 1.7.0?

**Comment by swachhab** [comment]
I am also facing same issue in iOS 11 and appium 1.7.0, it get stuck while executing getPageSource.

**Comment by swachhab** [comment]
> the following changes to latest WDA works fine and my tests are passing fine.

@Dheepthi Please let me know you did these changes in latest WDA within latest appium? and Now stuck issue resolved with it completely?

**Comment by mykola-mokhnach** [comment]
Sorry, there is nothing about it we can do in Appium. 
The workaround above might work, but then visibility detection will not be precise.
Closing as duplicate.

**Comment by swachhab** [comment]
@mykola-mokhnach @Dheepthi Please help us out, I also tried after applying patch in "_XCUIElement+FBIsVisible.m_" as a workaround. But still facing same issue in iOS11 real device. 
_**getPageSource**_ is still taking a lot of time, it get stuck on this command:

```
### [debug] [XCUITest] Executing command 'getPageSource'
[debug] [JSONWP Proxy] Proxying [GET /source] to [GET http://localhost:4754/session/C4F1A7A8-D660-4FC6-B2CA-6265728992E3/source] with no body
```

Then after sometime about 2-3 mins, it throws strange logs:

**[Xcode]     t =   549.46s     Find: Element at index 1**   : It execute these commands until index 107 in this case. I haven't observed these kind of logs in iOS10.  Logs snippet of logs till last index are:

```
[Xcode]     t =   549.46s     Find: Element at index 106
[Xcode]     t =   549.47s Snapshot accessibility hierarchy for app with pid 2902
[Xcode]     t =   549.64s Find: Descendants matching type Image
[Xcode]     t =   549.64s Find: Elements matching predicate 'wdUID IN {669, 670, 671, 673, 674, 675, 677, 678, 679, 681, 682, 683, 685, 686, 687, 689, 690, 691, 693, 694, 695, 697, 698, 699, 701, 702, 703, 705, 706, 707, 709, 710, 711, 713, 714, 715, 717, 718, 719, 721, 722, 723, 725, 726, 727, 729, 730, 731, 733, 734, 735, 737, 738, 739, 741, 742, 743, 745, 746, 747, 749, 750, 751, 753, 754, 755, 757, 758, 759, 761, 762, 763, 765, 766, 767, 769, 770, 771, 773, 774, 775, 777, 778, 779, 781, 782, 783, 785, 786, 787, 789, 790, 791, 793, 794, 795, 797, 798, 799, 801, 802, 803, 805, 806, 807, 809, 810, 811} AND (1 == 1 OR identifier == 0 OR frame == 0 OR value == 0 OR title == 0 OR label == 0 OR elementType == 0 OR enabled == 0 OR placeholderValue == 0)'
[Xcode]     t =   549.64s Find: Element at index 107
[Xcode]     t =   549.65s Find the Image
[Xcode]     t =   549.65s     Snapshot accessibility hierarchy for app with pid 2902
[Xcode]     t =   549.82s     Find: Descendants matching type Image
[Xcode]     t =   549.82s     Find: Elements matching predicate 'wdUID IN {669, 670, 671, 673, 674, 675, 677, 678, 679, 681, 682, 683, 685, 686, 687, 689, 690, 691, 693, 694, 695, 697, 698, 699, 701, 702, 703, 705, 706, 707, 709, 710, 711, 713, 714, 715, 717, 718, 719, 721, 722, 723, 725, 726, 727, 729, 730, 731, 733, 734, 735, 737, 738, 739, 741, 742, 743, 745, 746, 747, 749, 750, 751, 753, 754, 755, 757, 758, 759, 761, 762, 763, 765, 766, 767, 769, 770, 771, 773, 774, 775, 777, 778, 779, 781, 782, 783, 785, 786, 787, 789, 790, 791, 793, 794, 795, 797, 798, 799, 801, 802, 803, 805, 806, 807, 809, 810, 811} AND (1 == 1 OR identifier == 0 OR frame == 0 OR value == 0 OR title == 0 OR label == 0 OR elementType == 0 OR enabled == 0 OR placeholderValue == 0)'
[Xcode]     t =   549.83s     Find: Element at index 107
[Xcode]     t =   549.83s Snapshot accessibility hierarchy for app w
[debug] [JSONWP Proxy] Got response with status 200: {"value":[{"ELEMENT":"F3E99710-1342-48CA-B0D4-96BEB282562D"},{"ELEMENT":"F5D185BC-167D-43D2-833A-6EEA1C80445A"},{"ELEMENT":"C641CD9E-1954-4D2A-904B-FDD02FBC0369"},{"ELEMENT":"44423421-8DDD-4CB2-85D7-6C7FE2C7BB8E"},{"ELEMENT":"379C0B89-96E5-426E-8445-D69FCFAD6659"},{"ELEMENT":"A35B0CDD-F3E5-4FDA-A564-B4A8CE001C90"},{"ELEMENT":"5DB4851B-988D-485B-A87A-7F320228E3DA"},{"ELEMENT":"E8438323-E4BD-4A7A-875B-E3818484FDD6"},{"ELEMENT":"1EB07968-EF07-476F-81BE-E879658772A2"},{"ELEMENT":"26D81D83-0321-467C-A9F3-462639704DBC"},{"ELEMENT":"37F58E8A-8F4A-426A-812D-740B97CE9B6C"},{"ELEMENT":"93B1EC07-75C2-44FD-AD9C-98887AF519ED"},{"ELEMENT":"9A1AB6E2-0527-4DD2-838E-59B1794EFDC1"},{"ELEMENT":"7BEFE2E2-0B4D-4F60-A2EF-F2A4D8155B54"},{"ELEMENT":"98554009-9F4E-4842-8D55-A5B896DC5103"},{"ELEMENT":"C5CB85EC-0665-4E0A-9963-BCE45FDB3550"},{"ELEMENT":"4785F6D1-E95A-4340-86C1-16D6836431CD"},{"ELEMENT":"EBE63B9D-BA1D-4BB4-9BC4-5760B993F19F"},{"ELEMENT":"89AE7332-C21D-4399-BD08-B80C0DAB82E8"},{"ELEMENT":"C378EB07-9A6C-4BAF-AB90-E3058E...
[debug] [MJSONWP] Responding to client with driver.findElements() result: [{"ELEMENT":"F3E99710-1342-48CA-B0D4-96BEB282562D"},{"ELEMENT":"F5D185BC-167D-43D2-833A-6EEA1C80445A"},{"ELEMENT":"C641CD9E-1954-4D2A-904B-FDD02FBC0369"},{"ELEMENT":"44423421-8DDD-4CB2-85D7-6C7FE2C7BB8E"},{"ELEMENT":"379C0B89-96E5-426E-8445-D69FCFAD6659"},{"ELEMENT":"A35B0CDD-F3E5-4FDA-A564-B4A8CE001C90"},{"ELEMENT":"5DB4851B-988D-485B-A87A-7F320228E3DA"},{"ELEMENT":"E8438323-E4BD-4A7A-875B-E3818484FDD6"},{"ELEMENT":"1EB07968-EF07-476F-81BE-E879658772A2"},{"ELEMENT":"26D81D83-0321-467C-A9F3-462639704DBC"},{"ELEMENT":"37F58E8A-8F4A-426A-812D-740B97CE9B6C"},{"ELEMENT":"93B1EC07-75C2-44FD-AD9C-98887AF519ED"},{"ELEMENT":"9A1AB6E2-0527-4DD2-838E-59B1794EFDC1"},{"ELEMENT":"7BEFE2E2-0B4D-4F60-A2EF-F2A4D8155B54"},{"ELEMENT":"98554009-9F4E-4842-8D55-A5B896DC5103"},{"ELEMENT":"C5CB85EC-0665-4E0A-9963-BCE45FDB3550"},{"ELEMENT":"4785F6D1-E95A-4340-86C1-16D6836431CD"},{"ELEMENT":"EBE63B9D-BA1D-4BB4-9BC4-5760B993F19F"},{"ELEMENT":"89AE7332-C21D-4399-BD08-B80C0DAB82E8"},{"ELEMENT":"C378EB07-9A6C-4BAF-AB90-E3058E022696"},...
[HTTP] <-- POST /wd/hub/session/c4fc19c4-d1ab-4c1e-9859-60bc4700d7d0/elements 200 195108 ms - 5581 
[HTTP] --> POST /wd/hub/session/c4fc19c4-d1ab-4c1e-9859-60bc4700d7d0/elements {"using":"xpath","sessionId":"c4fc19c4-d1ab-4c1e-9859-60bc4700d7d0","value":"//XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[2]/XCUIElementTypeCollectionView[1]/XCUIElementTypeCell[2]/XCUIElementTypeOther[1]/XCUIElementTypeStaticText[1]"}
[debug] [MJSONWP] Calling AppiumDriver.findElements() with args: ["xpath","//XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[2]/XCUIElementTypeCollectionView[1]/XCUIElementTypeCell[2]/XCUIElementTypeOther[1]/XCUIElementTypeStaticText[1]","c4fc19c4-d1ab-4c1e-9859-60bc4700d7d0"]
[debug] [XCUITest] Executing command 'findElements'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:4754/session/355FC27B-75E4-45F1-B430-02A9444607AF/elements] with body: {"using":"xpath","value":"//XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[2]/XCUIElementTypeCollectionView[1]/XCUIElementTypeCell[2]/XCUIElementTypeOther[1]/XCUIElementTypeStaticText[1]"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":[{"ELEMENT":"0F8DA2E3-884B-4F75-B216-B24CEF4C4C2B"}],"sessionId":"355FC27B-75E4-45F1-B430-02A9444607AF","status":0}
[debug] [MJSONWP] Responding to client with driver.findElements() result: [{"ELEMENT":"0F8DA2E3-884B-4F75-B216-B24CEF4C4C2B"}] 
```
