### ISSUE TITLE
Cannot hide the keyboard after use driver.hide_keyboard() in Python with Appium v1.6.5

### ISSUE THREAD

**Issue by aray0322** [appium/appium#9310]
## The problem

 I need to enter some text to a element type is "XCUIElementTypeTextView". after I enter the text, the keyboard always on my screen. i cannot do the next step. I have tried driver.hide_keyboard(). and send_keys("\n").    I am use python

## Environment

* Appium version (or git revision) that exhibits the issue: v1.6.5
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: IOS 10.3
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iphone 5s
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe:

## Details

My request: I need to hide the keyboard on my screen. So that i can go to next.

**Comment by mykola-mokhnach** [comment]
This is known XCTest issue. The keyboard can only be hidden if it has "Hide" key. Otherwise you must use the same approach that application user is supposed to follow in order to hide it.
