### ISSUE TITLE
click() functionality not working in iOS 

### ISSUE THREAD

**Issue by avanishf** [appium/appium#9311]
## The problem
I encountered a problem today where i was not able to click on the login button to perform a login action. Its strange that i was able to click on previous buttons prior to login but while validating the login credentials, it somehow just stays right there and doesn't land me on the home page. Surprisingly test pass on login but doesn't give the expected output(landing on homepage) which is strange. Is this a bug in the appium?
P.S: I also tried using submit() but it seems it is not implemented as yet.

## Environment

* Appium version : 1.2.1 
* Desktop OS/version used to run Appium: macOS Sierra v10.12.6
* Mobile platform/version under test: iPhone 7 simulator, OS v10.3
* Real device or emulator/simulator: Sim
* Appium CLI or Appium.app|exe: Appium.app
* Java client: 5.0.3

## Link to Appium logs
 Logs attached in GIST
https://gist.github.com/avanishf/bbf310e3ee8ac3a5ce1a6e93eaf45af3

## Code To Reproduce Issue [ Good To Have ]
LoginScreen.java :  
https://gist.github.com/avanishf/707b899993cd60bf740b42839e282f89

loginTest.java : 
https://gist.github.com/avanishf/e2fc6e8e6ec0546fbb427a81b1f45fe6
(comments added where the issue is found)

Test Output in Eclipse console : 
Valid login test passed
PASSED: validLogin

**Comment by mykola-mokhnach** [comment]
It might be you try to lick a wrong element. Make sure the locater matches the correct button. Also you can try to calculate element coordinates and then tap by coordinates.

**Comment by avanishf** [comment]
Hi Mykola,
I checked, its the correct locator im trying to access. I have attached snapshot for confirmation. Then cross-check the validateLogin locator in LoginScreen.java and its as expected. The same test works for Android with its corresponding locators but not with iOS locators (You can't see the Android locators in the gist code). 
![login screengrab](https://user-images.githubusercontent.com/26178613/30890949-56990092-a373-11e7-9f8c-2f5d4a8ce6ab.png)

**Comment by avanishf** [comment]
The button is found. While debugging, it does execute that line of code. So my understanding is, it also clicks along with it. The label "Log in" (with a small 'i') itself is set as id in locator. Alternatively you can also use label as accessibility instead of id.

**Comment by avanishf** [comment]
i see similar issue with #8571

**Comment by mykola-mokhnach** [comment]
If you think the issue is similar to then one then updating Appium to 1.7.0 should resolve it.

**Comment by avanishf** [comment]
Installing appium through npm (latest version) didn't work either. I replaced the locator with the xpath and it worked. I used Macaca inspector to fecth xpath. Hence closing the issue but the problem with "id" still remains, maybe its not able to recognize it as a button , not sure.
