### ISSUE TITLE
[1.7.1][UiAutomator2] Send Keys command crashes app when sending a string longer than android:maxLength value

### ISSUE THREAD

**Issue by welnanick** [appium/appium#9312]
## The problem
When using the Send Keys command in an instance that has UiAutomator2 as the automationName, if you send a string to an editText that is longer than the editText's android:maxLength parameter the app crashes.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.0
* Last Appium version that did not exhibit the issue (if applicable): N/A I started using UiAutomator2 with 1.7.0
* Desktop OS/version used to run Appium: macOS Sierra 10.12.6
* Node.js version (unless using Appium.app|exe): 8.5.0
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: CLI

## Details
I have a test for my app where I must test that an editText handles entering too much input correctly. In my case the android:maxLength parameter is set to 17. I send the edit text a string with 18 characters and the app crashes. This exhibits itself with both appium-desktop and the java-client.

## Link to Appium logs
[logs](https://gist.github.com/welnanick/48a7089fd2fbd899afc5ffe56163d448)

**Comment by welnanick** [comment]
Issue is also in 1.7.1

**Comment by imurchie** [comment]
This is a problem in Android below version 7.0. Unfortunately there is no way to check the length restriction, and no indication other than the error that it has failed. It needs to be handled on the client side.

**Comment by welnanick** [comment]
Client side as in the java-client, or in my tests? Currently I've switched to using setValue() in that specific case, as that does not cause the crash.

**Comment by welnanick** [comment]
@imurchie So does this mean I should close this issue, since its something that can't be fixed on your end?

**Comment by imurchie** [comment]
In your tests, unfortunately.

**Comment by welnanick** [comment]
Alright, already did that. Thanks for letting me know!
