### ISSUE TITLE
Appium 1.7.0 + iOS10.x not finding element on new app if manually navigated to new app

### ISSUE THREAD

**Issue by rajfidel** [appium/appium#9313]
## The problem

This below mentioned issue is only present in iOS 10.x + Appium 1.7.0:
1. If appium session was started for a bundleID (in this case com.fidlee.ICMHelper), and another app is manually opened (in this case com.apple.Preferences), findElement does not find any element present on com.apple.Preferences.
PageSource shows all the elements correctly though.
2. FindElement only works if the appium session was started for the bundleID on which the element is present. So if appium session was started for bundleID com.apple.Preferences, it would be able to find elements present in com.apple.Preferences application.

This issue was not present in Appium 1.6.5 on iOS 10.x
On Appium 1.7.0 this issue is only present on iOS 10.x. 
**Appium 1.7.0 with iOS 11.0 works fine**.

Appium Logs are available below:
1. On iOS 10 + Appium 1.7.0, create session for com.fidlee.ICMHelper, manually launch com.apple.Preferences and try to find an element. Logs available [here](https://gist.github.com/rajfidel/a64124d5399d26167d5db79782133dc7) (**Is unable to find element** All other scenarios described below work fine)
2. On iOS 10 + Appium 1.7.0, create session for com.apple.Preferences and try to find an element. Logs available [here](https://gist.github.com/rajfidel/145120d2c8e7c31c872ab6632723b510) (Is able to find element)
3. On iOS 11 + Appium 1.7.0, create session for com.fidlee.ICMHelper, manually launch com.apple.Preferences and try to find an elements. Logs available [here](https://gist.github.com/rajfidel/9b9c624a553fe20b32c9d6a5a4ade74c) (Is able to find element)
4. On iOS 11 + Appium 1.7.0, create session for com.apple.Preferences and try to find an element. Logs available [here](https://gist.github.com/rajfidel/ac7c2320f39bd91722f6b0970118e188) (Is able to find element)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.0
* Last Appium version that did not exhibit the issue (if applicable): 1.6.5
* Desktop OS/version used to run Appium: mac OS 10.12.6
* Node.js version (unless using Appium.app|exe): 8.5.0
* Mobile platform/version under test: 10.3.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

**Comment by mykola-mokhnach** [comment]
There is nothing we can do about it in Appium. Please report to https://github.com/facebook/WebDriverAgent/issues
