### ISSUE TITLE
WebDriverAgent service status can't be obtained

### ISSUE THREAD

**Issue by havenqi** [appium/appium#9315]
## The problem

I had the service running successfully according to wiki,
`xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=<myID>' test`
...
...
Test Suite 'All tests' started at 2017-09-27 11:04:50.894
Test Suite 'WebDriverAgentRunner.xctest' started at 2017-09-27 11:04:50.898
Test Suite 'UITestingUITests' started at 2017-09-27 11:04:50.899
Test Case '-[UITestingUITests testRunner]' started.
    t =     0.02s Start Test at 2017-09-27 11:04:50.915
    t =     0.02s Set Up
2017-09-27 11:04:50.951596+0800 WebDriverAgentRunner-Runner[300:15831] Built at Sep 26 2017 18:05:11
2017-09-27 11:04:51.549347+0800 WebDriverAgentRunner-Runner[300:15831] ServerURLHere->**http://169.254.126.217:0**<-ServerURLHere

The port is 0 instead of 8100 mentioned in wiki. It's strange.
Then I tried to check the server status as below, but failed. Any idea?
(by the way, wiki page needs minor update to the JSON string in to remove the space after ":" in the export DEVICE_URL command.) 

```
QArt:~ QArt$ echo $DEVICE_URL
http://169.254.126.217:0
QArt:~ QArt$ echo $JSON_HEADER
-H "Content-Type:application/json;charset=UTF-8, accept:application/json"
QArt:~ QArt$ curl -X GET $JSON_HEADER $DEVICE_URL/status
curl: (3) Port number ended with 'a'
curl: (7) Port number ended with 'a'
```

## Environment

* Appium version 1.7, Xcode 9:

**Comment by mykola-mokhnach** [comment]
You must pass _USE_PORT=<port_number>_ environment variable to xcodebuild command line. See https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/wda-custom-server.md for more details
