### ISSUE TITLE
Doesn't select checkbox on webview, whereas it executes fine without any error

### ISSUE THREAD

**Issue by denispolkhovskiy** [appium/appium#9318]
## The problem

Can not select the checkbox on webview, whereas it executes fine and does not show any errors, and actual condition of checkbox remains the same as it was (unchecked).

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Desktop OS/version used to run Appium: Windows
* Mobile platform/version under test: Android version 7.0
* Real device or emulator/simulator: emulator for tablet Nexus 9
* Environment Robot Framework + Python + Appium

## Details

It works fine with input text into elements for such paths: //textarea[@id="132"]. Whereas, when I try to select a checkbox for the paths like  //input[@id="200"], execution passes, but checkbox remains unselected.

For example, webview HTML for average checkbox looks like that  
```html
<input type="radio" name="218" onchange="checkBoxChanged(this.name)" value="1" id="40" data-type-ios="5">
```
Chrome driver version for webview is 2.23

## Link to Appium logs
https://gist.github.com/denispolkhovskiy/953ff3fd9fb854af3e6c737e99c2ff07

**Comment by mykola-mokhnach** [comment]
Try to perform tap by coordinates. If it still does not work you may simulate triggering the corresponding event on the checkbox using executeScript.

**Comment by denispolkhovskiy** [comment]
Tried to simulate by using JavaScript and jquery with following scripts: ```document.getElementById("200").checked = true```
 or 
```jquery $("#200").attr('checked', 'checked')```
, but no luck. Any other ideas? Thanks in advance.

**Comment by mykola-mokhnach** [comment]
```js
$.fn.changeVal = function (v) {
    return $(this).val(v).trigger("change");
}

$("#my-input").changeVal("Tyrannosaurus Rex");
```

**Comment by siggerzz** [comment]
@denispolkhovskiy I was able to select check boxes by doing:

`checkboxInput.SendKeys(Keys.Space);`

Worth giving it a try!

**Comment by denispolkhovskiy** [comment]
@siggerzz @mykola-mokhnach  Thank you guys, @siggerzz solution helped me.
