### ISSUE TITLE
Unable to connect to running WebDriverAgent: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 10.42.5.27:8100

### ISSUE THREAD

**Issue by anandbhayre2007** [appium/appium#9319]
## The problem

I have been trying to automate launch safari browser on real IOS device but didn't get success
## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5 GUI/1.7 from terminal
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:10.12.6 Mac Sierra
* Node.js version (unless using Appium.app|exe):v6.11.3
* Mobile platform/version under test: iOS 10.1.1, 10.3, 11.0 etc.
* Real device or emulator/simulator: Real Devices
* Appium CLI or Appium.app|exe: Tried on both

## Details

Steps to reproduce:
successfully Installed below dependencies:
brew install ideviceinstaller
brew install carthage
npm install -g ios-deploy
npm install deviceconsole
sudo gem install xcpretty
brew install libimobiledevice --HEAD
brew update
brew reinstall --HEAD libimobiledevice
brew reinstall -s ios-webkit-debug-proxy

ios_webkit_debug_proxy -c 51a43b64942ce094c4acc3b8f3002366f9d47686:27753 =>"Device successfully connected"

For WebDriver Agent:
Run the following 2 commands:
- mkdir -p Resources/WebDriverAgent.bundle
- sh ./Scripts/bootstrap.sh -d

Open the Xcode project (Under the WebDriverAgent folder) 
- Make sure that the device under testing is connected
- Sign the WebDriverLib & the WebDriverAgent.

Tried: Installing from XCode-Successfully installed
Tried: Installing from terminal -successfully installed
xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=51d8c712258a5b0ac63516aa5be9d10014b0c270' test

Jar File: Latest java client and latest selenium standalone
Java Code:
DesiredCapabilities capabilities = new DesiredCapabilities(); 	
		
		capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "iOS"); 	
			
		capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "10.1.1"); 	
		capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone SE"); 	
		
		capabilities.setCapability(MobileCapabilityType.UDID, "51a43b64942ce094c4acc3b8f3002366f9d47686"); 	
		capabilities.setCapability(IOSMobileCapabilityType.LAUNCH_TIMEOUT, 500000000); 	
		capabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, 360); 	
		capabilities.setCapability("nativeWebTap", true); 	
		capabilities.setCapability("webkitResponseTimeout",120000);
		
		
		capabilities.setCapability(MobileCapabilityType.BROWSER_NAME, "Safari");
		IOSDriver<WebElement> webdriver = new IOSDriver<>(new URL("http://127.0.0.1:4723/wd/hub"),capabilities);
		webdriver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);

## Link to Appium logs

https://gist.github.com/anandbhayre2007/f09d5ee4c86bd4961dba275256491c62

## Code To Reproduce Issue [ Good To Have ]

Jar File: Latest java client(5.0.3) and latest selenium standalone(3.5.3)
Java Code:
DesiredCapabilities capabilities = new DesiredCapabilities(); 	
		
		capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "iOS"); 	
			
		capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "10.1.1"); 	
		capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone SE"); 	
		
		capabilities.setCapability(MobileCapabilityType.UDID, "51a43b64942ce094c4acc3b8f3002366f9d47686"); 	
		capabilities.setCapability(IOSMobileCapabilityType.LAUNCH_TIMEOUT, 500000000); 	
		capabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, 360); 	
		capabilities.setCapability("nativeWebTap", true); 	
		capabilities.setCapability("webkitResponseTimeout",120000);
		
		
		capabilities.setCapability(MobileCapabilityType.BROWSER_NAME, "Safari");
		IOSDriver<WebElement> webdriver = new IOSDriver<>(new URL("http://127.0.0.1:4723/wd/hub"),capabilities);
		webdriver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);

**Comment by mykola-mokhnach** [comment]
Can you attach the log with _showXcodeLog_ capability set to true?

**Comment by anandbhayre2007** [comment]
log with showXcodeLog capability set to true:
https://gist.github.com/anandbhayre2007/5d480be7f1cbc5f7bd0e8a7bc5374a00

Note: 
1. I tried using xcode 8.2.1, 8.3.3, 9.0 but didn't get success
2. Tried with 5 different provisioning profiles
3. One more thing webdriveragent is used to install successfully, but during execution it opened for a fraction of second then minimised and start throwing error 
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body

**Comment by mykola-mokhnach** [comment]
> [Xcode] /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/PrivateHeaders/XCTest/XCUIApplication.h:37:1: error: type of property 'unsigned long long' in class extension does not match property type in primary class
> [Xcode] @property unsigned long long state; // @synthesize state=_state;
> [Xcode] ^
> [Xcode] In module 'XCTest' imported from /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Categories/XCUIApplication+FBHelpers.h:10:
> [Xcode] /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks/XCTest.framework/Headers/XCUIApplication.h:110:43: note: property declared here
> [Xcode] @property (readonly) XCUIApplicationState state;
> [Xcode]                                           ^
> [Xcode] 1 error generated.

WDA sources cannot be compiled according to the log.

**Comment by anandbhayre2007** [comment]
So what should I do now? Any solution?

**Comment by anandbhayre2007** [comment]
Please find below steps which followed in order to install webdriveragent:
1. Navigate to webdriveragent folder from terminal and execute below commands
- mkdir -p Resources/WebDriverAgent.bundle
- sh ./Scripts/bootstrap.sh -d

2. Open the Xcode project (Under the WebDriverAgent folder)
-Make sure that the device under testing is connected
-Sign the WebDriverLib & the WebDriverAgent
-Build the project and run webdriveragentrunner from product-->>Test. It will install the webdriveragent in to the mobile device
3. Close the Xcode 
4. Start appium
5. Start ios-webkit-proxy. Make sure device is connected
6. Now run above java code

Output:
1. It launch the webdriveragent for a fraction of second then start throwing above error in logs

**Comment by mykola-mokhnach** [comment]
You need to fix WebDriverAgent source manually if you run bootstrap from the command line. 

Otherwise Appium performs sources patching and bootstrap execution automatically as soon as a new version of xcuitest driver is installed. 

Here is the part of Appium code, which patches WDA source for Xcode9:

```js
const FBMACROS_FILE = 'WebDriverAgentLib/Utilities/FBMacros.h';
const XCUIAPPLICATION_FILE = 'PrivateHeaders/XCTest/XCUIApplication.h';

async function fixFBMacrosFile (bootstrapPath, initial = true) {
  const file = path.resolve(bootstrapPath, FBMACROS_FILE);

  let oldDef = '#define FBStringify(class, property) ({if(NO){[class.new property];} @#property;})';
  let newDef = '#define FBStringify(class, property) ({@#property;})';
  if (!initial) {
    [oldDef, newDef] = [newDef, oldDef];
  }
  await replaceInFile(file, oldDef, newDef);
}

async function fixXCUIApplicationFile (bootstrapPath, initial = true) {
  const file = path.resolve(bootstrapPath, XCUIAPPLICATION_FILE);

  let oldDef = '@property(nonatomic, readonly) NSUInteger state; // @synthesize state=_state;';
  let newDef = '@property XCUIApplicationState state;';
  if (!initial) {
    [oldDef, newDef] = [newDef, oldDef];
  }
  await replaceInFile(file, oldDef, newDef);
}

async function fixForXcode9 (bootstrapPath, initial = true) {
  await fixFBMacrosFile(bootstrapPath, initial);
  await fixXCUIApplicationFile(bootstrapPath, initial);
}
```

**Comment by mykola-mokhnach** [comment]
Also there is _startIWDP_ capability, which automatically starts webkit debugger

**Comment by anandbhayre2007** [comment]
I am executing-sh  ./Scripts/bootstrap.sh -d everytime, what else I have to?
As I mentioned, after executing this command I tried both the methods to install webdriveragent in devices and successfully installed on all the devices
1. From terminal
xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=51d8c712258a5b0ac63516aa5be9d10014b0c270' test

2. From Xcode- Product-->>Test

Please let me know what mistake I am doing, I followed same steps on my client's machine and it was working fine, so what could be the issue in my machine?
Xcode - I have 8.2, 8.3.3, 9.0
OS- Mac Sierra 12.6
Appium-1.7(command line), 1.6.5 GUI
All the dependencies are installed
brew install ideviceinstaller
brew install carthage
npm install -g ios-deploy
npm install deviceconsole
sudo gem install xcpretty
brew install libimobiledevice --HEAD
brew update
brew reinstall --HEAD libimobiledevice
brew reinstall -s ios-webkit-debug-proxy

Now what else I have to do?

**Comment by mykola-mokhnach** [comment]
Closed as inactive

**Comment by braincraft359** [comment]
what sense does it make to close "as inactive" when you guys haven't answered the last question of the author? he's asking, you're not answering -> closed as incactive... BS

**Comment by vikramvi** [comment]
@braincraft359  be careful & respectful about your language, otherwise your id will be reported to github and you will be banned permanently from github

**Comment by joamafer** [comment]
To be honest @braincraft359 is right. You didn't reply @anandbhayre2007 and closed it as inactive...

**Comment by anandbhayre2007** [comment]
Still I am facing this issue, can you please re open this it again.

**Comment by estefafdez** [comment]
I am also facing the issue and I did not know how to solve it. I tried the solution you provide on your answer but none of them works for me. Can you help me please? thanks.

**Comment by anandbhayre2007** [comment]
For me this issue has been fixed by adding localhost entry in to host file.

**Comment by Jaspreet23** [comment]
> For me this issue has been fixed by adding localhost entry in to host file.
> […](#)

Hey @anandbhayre2007 which host file did you edit? Can you help please

**Comment by anandbhayre2007** [comment]
Hi there,

Please use the steps mentioned in below links to open the host file on your
mac machine:
https://www.imore.com/how-edit-your-macs-hosts-file-and-why-you-would-want

and add below line your hostfile
127.0.0.1 localhost 255.255.255.255 broadcasthost ::1 localhost

Regard,
Anand Bhayre
+918149817873
