### ISSUE TITLE
Appium claims that Xcode 9 is not supported

### ISSUE THREAD

**Issue by dgong24** [appium/appium#9322]
## The problem

I recently updated my macbook to HighSierra, and with it came Xcode 9. Now when I try to launch the app through appium, it complains about not being supported. I've googled the best i can but I'm not getting anywhere. I'm thinking there's something wrong here since xcode9 beta was going on for months and i don't think Appium devs would ignore that... any thoughts appreciated.

## Environment
Appium 1.7.0
Appium Desktop 1.2.2 (which i think uses 1.6.5)
Appium Python Bindings 0.24?

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
Gist here

https://gist.github.com/dgong24/91c867c2dc872dc16944e52a6a7b8f23

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by swachhab** [comment]
Latest Appium version supports iOS 11 and Xcode 9. Check your appium version: you have 1.6.5 installed. You need to upgrade it to 1.7.0.
You logs:
> [Appium] Welcome to Appium v1.6.5
> [Appium] Appium REST http interface listener started on 0.0.0.0:4723

**Comment by dgong24** [comment]
I thought i did, when I enter

appium --version

i get 1.7.0

I think the desktop version automatically is routing to it's packaged version, 1.6.5. Any idea on how to force the desktop version to a different one?

**Comment by swachhab** [comment]
I have not used appium desktop much, but I dont think if there's any option in Appium desktop version.
This was present in previous Appium Inspector(1.5.0) 

You can check screenshot of previous version of Appium:

![screen shot 2017-09-28 at 10 49 29 am](https://user-images.githubusercontent.com/11949406/30950582-7385fd0e-a43b-11e7-9a2b-9578715cc177.png)

**Comment by mykola-mokhnach** [comment]
the recent Appium Desktop uses Appium 1.6.5, which does not support Xcode9. You need to install Appium from npm and connect the desktop client to that server (the actual version number can be seen at the very beginning of server logs)
