### ISSUE TITLE
[Appium 1.7.0][iOS 11.0.1] save_screenshot fails with error "socket hang up"

### ISSUE THREAD

**Issue by sathaiahc** [appium/appium#9323]
**Issue:** [Appium 1.7.0][iOS 11.0.1] web_driver.save_screenshot fails with error "socket hang up"
**Error:**
[MJSONWP] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: Error: socket hang up
    at JWProxy.proxy$ (../../../lib/jsonwp-proxy/proxy.js:152:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>

**Appium Log:**
[debug] [MJSONWP] Calling AppiumDriver.getScreenshot() with args: ["48e76841-c885-4b56-8122-35f5c8ee33ff"]
[debug] [XCUITest] Executing command 'getScreenshot'
[debug] [JSONWP Proxy] Proxying [GET /screenshot] to [GET http://localhost:8100/session/45D785B9-3235-4ED8-980F-06C361129AE5/screenshot] with no body
[debug] [XCUITest] Log file for xcodebuild test: /var/folders/r7/664fc1fj191bpnywg9sv8kg40000gp/T/com.apple.dt.XCTest/IDETestRunSession-498727BC-358E-4B42-B995-88609D3F3CC5/WebDriverAgentRunner-F816CF9A-B753-4EF1-BE26-D87DD3805D4F/Session-WebDriverAgentRunner-2017-09-27_172812-B8FQRw.log
[debug] [XCUITest] Connection to WDA timed out
[debug] [iProxy] recv failed: Operation not permitted
[XCUITest] Falling back to 'idevicescreenshot' API
[XCUITest] Cannot take a screenshot from the device 60a636b6610af5ee3a9293c0e14093102f317a5f using idevicescreenshot. Original error: Command 'idevicescreenshot -u 60a636b6610af5ee3a9293c0e14093102f317a5f /var/folders/r7/664fc1fj191bpnywg9sv8kg40000gp/T/2017827-5481-1sfowe.npvwy/screenshot-60a636b6610af5ee3a9293c0e14093102f317a5f.tiff' exited with code 255
[debug] [JSONWP Proxy] Proxying [GET /screenshot] to [GET http://localhost:8100/session/45D785B9-3235-4ED8-980F-06C361129AE5/screenshot] with no body
[debug] [iProxy] Error connecting to device!
[debug] [JSONWP Proxy] Proxying [GET /screenshot] to [GET http://localhost:8100/session/45D785B9-3235-4ED8-980F-06C361129AE5/screenshot] with no body
[debug] [iProxy] Error connecting to device!
[debug] [JSONWP Proxy] Proxying [GET /screenshot] to [GET http://localhost:8100/session/45D785B9-3235-4ED8-980F-06C361129AE5/screenshot] with no body
[debug] [iProxy] Error connecting to device!
[debug] [JSONWP Proxy] Proxying [GET /screenshot] to [GET http://localhost:8100/session/45D785B9-3235-4ED8-980F-06C361129AE5/screenshot] with no body
[debug] [iProxy] Error connecting to device!
[debug] [JSONWP Proxy] Proxying [GET /screenshot] to [GET http://localhost:8100/session/45D785B9-3235-4ED8-980F-06C361129AE5/screenshot] with no body
[debug] [iProxy] Error connecting to device!
[XCUITest] xcodebuild exited with code '65' and signal 'null'
[MJSONWP] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: Error: socket hang up
    at JWProxy.proxy$ (../../../lib/jsonwp-proxy/proxy.js:152:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
[HTTP] <-- GET /wd/hub/session/48e76841-c885-4b56-8122-35f5c8ee33ff/screenshot 500 13399 ms - 250 
[HTTP] --> DELETE /wd/hub/session/48e76841-c885-4b56-8122-35f5c8ee33ff {}

**Environment**

* Appium version (or git revision) that exhibits the issue: 1.7.0
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: NA
* Node.js version (unless using Appium.app|exe): v8.5.0
* Mobile platform/version under test: 11.0.1
* Real device or emulator/simulator: Real Device
Robot Framework - Appium-Python-Client version 0.24, selenium version 3.6.0

**Comment by mykola-mokhnach** [comment]
This looks like a problem with the device itself. It even stops responding to idevicescreenshot calls. I don't think there is something, which can be changed on Appium side, to workaround it.

**Comment by sathaiahc** [comment]
This got fixed after updating libimobiledevice. Here are the steps:
brew uninstall libimobiledevice
brew install --HEAD libimobiledevice
