### ISSUE TITLE
multiple iOS simulators support

### ISSUE THREAD

**Issue by bearxc** [appium/appium#9325]
Xocde 9 supports  multiple simulators now , does  appium support this also ?     

so far , when specify wdaLocalPort   on appium ,   WDA still launches  as default port 8100, we need have a way to  launch WDA  as same port number .    

Is it possible to do  now   ?

**Comment by saikrishna321** [comment]
> Xocde 9 supports multiple simulators now , does appium support this also ?

Yes, appium supports. You need to have the latest appium 1.7.0.

To run multiple simulators and have it thread safe you need to have wdaLocalPort,SimulatorUDID, deviceName, OSversion capabilities. 

Take a look at the video which runs multiple simulator 
https://www.youtube.com/watch?v=sf0YARF5ppQ&t=64s
