### ISSUE TITLE
how to run multiple appium  against   multiple iOS simulator   on same mac 

### ISSUE THREAD

**Issue by bearxc** [appium/appium#9326]
xcode 9 support multiple simulators now ,  
I try to  run multiple  appium/iOS simulator  on same mac,  and  each  appium instance connect to different  iOS simulator.

is it possible to do that  ?   

when I specify wdaLocalPort  in appium  ,  the WDA agent only run on default 8100,  it is impossible to launch multiple WDA agents ,   appium server also  looks  for   that unavailable  port which specifyed on wdaLocalPort .

**Comment by swachhab** [comment]
Yes, you can achieve that, Even we can able to execute tests on multiple devices with previous appium versions as well on same mac. 
With latest appium ie 1.7.0, you don't need to start different appium server(with different ports), you just need unique WDA port for each device.

**Comment by mykola-mokhnach** [comment]
Please ask questions in Appium forum. 
There are several examples of multiple simulators usage like https://github.com/saikrishna321/TestNGParallelThreads/

**Comment by reach2jeyan** [comment]
@swachhab Is there any working example or documentation for ruby appium tests to run distributed tests across simulators? in one mac machine? 

@bearxc Were you able to achieve it? 

@mykola-mokhnach Is there a official documentation available from appium on this?

**Comment by nikhilniwdunge** [comment]
1.How many simulators can run on same mac at same time.? What happens in terms of performance?

2.When i tried with 5 simulators with unique wda port but it throws an below error.
[iOSSim] 'xcrun simctl boot E28153A1-30DD-4264-ACFF-XXXXXXXXXXXX' command has returned non-zero code. The problem was: undefined.

**Comment by swachhab** [comment]
Hi @nikhilniwdunge 
I hope you have done Appium setup correctly, if not then check this tutorial https://youtu.be/dyijACVRQOc
I tried same test scripts on 5 real devices and 5 simulators at same time(parallel), and there was no difference in terms of speed or performance in execution. 
1 more thing, If you are running on multiple devices parallely, don't execute in on same appium instance. Run appium in different terminals with different ports. 
**Note:** Running same appium on multiple device impacts its performance.

**Comment by swachhab** [comment]
Never tested the limits, but most probably any number of simulators that shows in your xcode under devices section

**Comment by reach2jeyan** [comment]
@nikhilniwdunge Your mac is gonna be terribly slow though if your running 5 simulators in parallel. Something that I am facing in i5 mac mini

**Comment by saikrishna321** [comment]
> Running same appium on multiple device impacts its performance

@swachhab what is the performance issue ur facing ? How did u measure that ? 

I have been running on single server session on multiple real devices i don't see any issues

**Comment by swachhab** [comment]
Running multiple devices on same appium session impacting execution speed in my case, but after running single appium session for a device running flawlessly.

**Comment by reach2jeyan** [comment]
@swachhab  what configuration of mac are you using?

**Comment by swachhab** [comment]
Mac Mini with 2.6 GHz Intel Core i5

**Comment by reach2jeyan** [comment]
I am not facing problems running appium sessions on multi simulators in parallel, however, mac CI systems become insanely slow on having all the 5 simulators running.

Is there a way you have optimized the mac machine?
