### ISSUE TITLE
[appium-uiautomator2-server] UiScrollable().scrollIntoView() is flaky

### ISSUE THREAD

**Issue by vmaxim** [appium/appium#9328]
## The problem

Sometimes appium-uiautomator2-server can not scroll to element in scrollable context via `UiScrollable().scrollIntoView()`.
## Environment

* Appium version (or git revision) that exhibits the issue: **1.7.0**
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: **Win/Mac**
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: **Android 5.0.1, 8.0.0**
* Real device or emulator/simulator: **both**
* Appium CLI or Appium.app|exe:

## Code To Reproduce Issue [ Good To Have ]
1. Change "Radio Group" to "WebView" in [scrollTest()](https://github.com/appium/appium-uiautomator2-server/blob/master/app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/HandlersTest.java#L580)
2. Run e2e tests

## Details
1. appium-uiautomator2-server:
```
1) scrollTest(io.appium.uiautomator2.unittest.test.HandlersTest)
java.lang.AssertionError: By.accessibilityId: WebView not found
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at io.appium.uiautomator2.unittest.test.HandlersTest.scrollTest(HandlersTest.java:592)
```
[logcat](https://gist.github.com/vmaxim/a36a5dce43a86a50be2622a1a53d87cf)

```
D/InteractionController( 7231): scrollSwipe (360, 273, 360, 1169, 55) *UP*
W/InteractionController( 7231): runAndwaitForEvents timed out waiting for events
D/InteractionController( 7231): scrollSwipe (360, 1169, 360, 273, 55) *DOWN*
W/InteractionController( 7231): runAndwaitForEvents timed out waiting for events
D/InteractionController( 7231): scrollSwipe reached scroll end: false
D/InteractionController( 7231): scrollSwipe (360, 1169, 360, 273, 55) *DOWN*
W/InteractionController( 7231): runAndwaitForEvents timed out waiting for events
D/InteractionController( 7231): scrollSwipe (360, 273, 360, 1169, 55) *UP*
W/InteractionController( 7231): runAndwaitForEvents timed out waiting for events
D/InteractionController( 7231): scrollSwipe reached scroll end: false
D/InteractionController( 7231): scrollSwipe (360, 273, 360, 1169, 55) *UP*
W/InteractionController( 7231): runAndwaitForEvents timed out waiting for events
D/InteractionController( 7231): scrollSwipe reached scroll end: true
D/InteractionController( 7231): scrollSwipe (360, 1169, 360, 273, 55) *DOWN*
W/InteractionController( 7231): runAndwaitForEvents timed out waiting for events
D/InteractionController( 7231): scrollSwipe reached scroll end: false
D/InteractionController( 7231): scrollSwipe (360, 1169, 360, 273, 55) *DOWN*
W/InteractionController( 7231): runAndwaitForEvents timed out waiting for events
I/appium  ( 7231): Find element command
D/appium  ( 7231): payload: {"context":"","strategy":"accessibility id","selector":"WebView"}
I/appium  ( 7231): find element command using 'accessibility id' with selector 'WebView'.
I/appium  ( 7231): AppiumResponse: {"sessionId":":sessionId","status":7,"value":"An element could not be located on the page using the given search parameters."}
```
2. Pure UIAutomator2:
[code](https://github.com/vmaxim/appium-uiautomator2-server/blob/flaky_scroll/app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/ScrollTest.java)
[logcat](https://gist.github.com/vmaxim/bb1100602cc65f6599bc32a154606206)

```
D/InteractionController( 6242): scrollSwipe (360, 273, 360, 1169, 55) *UP*
W/InteractionController( 6242): runAndwaitForEvents timed out waiting for events
D/InteractionController( 6242): scrollSwipe (360, 1169, 360, 273, 55) *DOWN*
W/InteractionController( 6242): runAndwaitForEvents timed out waiting for events
D/InteractionController( 6242): scrollSwipe reached scroll end: false
D/InteractionController( 6242): scrollSwipe (360, 1169, 360, 273, 55) *DOWN*
W/InteractionController( 6242): runAndwaitForEvents timed out waiting for events
D/InteractionController( 6242): scrollSwipe reached scroll end: false
D/InteractionController( 6242): scrollSwipe (360, 1169, 360, 273, 55) *DOWN*
W/InteractionController( 6242): runAndwaitForEvents timed out waiting for events
D/InteractionController( 6242): scrollSwipe reached scroll end: true
D/InteractionController( 6242): clickAndSync(360, 1232)
```
It seems that sometimes `InteractionController` can not catch scroll event.

**Comment by mykola-mokhnach** [comment]
This looks looks liek UiAutomation bug. I don't think there is anything in Appium that can be done in orderto fix it.

**Comment by vmaxim** [comment]
@mykola-mokhnach Please take a look to the second clause under **Details** section. `scrollIntoView()` always works fine without `io.appium.uiautomator2.server`

**Comment by mykola-mokhnach** [comment]
It's because the actual implementation of scrollTo method is slightly different from yours https://github.com/appium/appium-uiautomator2-server/blob/8eb809776b2a48435ec8574e28a553279124dd90/app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/TestUtil.java#L478

**Comment by vmaxim** [comment]
I can't see any difference not in logcats neither in code
https://github.com/appium/appium-uiautomator2-server/blob/master/app/src/main/java/io/appium/uiautomator2/utils/Device.java#L38

**Comment by vmaxim** [comment]
The root of cause in `io.appium.uiautomator2.model.NotificationListener`

**Comment by vmaxim** [comment]
I think it's a bad idea to execute `UiAutomation.executeAndWaitForEvent()` [continuously in background](https://github.com/appium/appium-uiautomator2-server/blob/master/app/src/main/java/io/appium/uiautomator2/model/NotificationListener.java#L69) .

When [`executeAndWaitForEvent`](https://android.googlesource.com/platform/frameworks/base.git/+/master/core/java/android/app/UiAutomation.java#590) invoked it clears event queue and breaks `UIAutomator` sync (scrollSwipe, clickAndSync, sendKeyAndWaitForEvent, clickAndWaitForNewWindow).

Can we grab toast text in another way?

**Comment by vmaxim** [comment]
@mykola-mokhnach close please - the tests are [passed](https://travis-ci.org/appium/appium-uiautomator2-driver/builds/342203622)

**Comment by Gocoollnath** [comment]
Issue still there.
Sample code:

driver.findElementByAndroidUIAutomator("new UiScrollable(new UiSelector()).scrollIntoView(text(\"English\"));");

The object is a Spinner and it displays a drop down with values as a list view. The view is scrollable. It just do a single forward and a single backward scroll and throws NoSuchElement exception.

**Comment by vmaxim** [comment]
@Gocoollnath Did you turn off notification listener?

**Comment by Gocoollnath** [comment]
No. Please, could you say how to turn off them?

**Comment by vmaxim** [comment]
https://appium.io/docs/en/commands/session/settings/update-settings/
https://appium.io/docs/en/advanced-concepts/settings/index.html
