### ISSUE TITLE
[TouchAction - iOS 10, 11] TouchAction(tap, press) with co-ordinates does not work on iOS 10, 11

### ISSUE THREAD

**Issue by quannd307** [appium/appium#9329]
## The problem

`new TouchAction(driver).tap(x, y).release().perform();` works normally on real devices with iOS 8, 9.
But when i use that code on iOS 10, 11. It doesn't tap even response code is 200 in appium log.

## Environment

* Appium version (or git revision) that exhibits the issue: **1.7.1**
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: **MacOS Sierra 10.12.6, Xcode 9.0**
* Node.js version (unless using Appium.app|exe): 
* Mobile platform/version under test: **iPad Air 2(iOS 10.3.2), iPhone 7(iOS 11)**
* Real device or emulator/simulator: **Real device**
* Appium CLI or Appium.app|exe:

## Appium logs

```
[HTTP] --> POST /wd/hub/session/60d6ceba-41cd-4773-a4ca-c5e926e5a63a/touch/perform {"actions":[{"action":"tap","options":{"x":839,"y":675}},{"action":"release","options":{}}]}
[debug] [MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"tap","options":{"x":839,"y":675}},{"action":"release","options":{}}],"60d6ceba-41cd-4773-a4ca-c5e926e5a63a"]
[debug] [XCUITest] Executing command 'performTouch'
[debug] [XCUITest] Received the following touch action: tap(options={"x":839,"y":675})-release(options={})
[debug] [XCUITest] Found matching gesture: tap
[debug] [JSONWP Proxy] Proxying [POST /wda/tap/0] to [POST http://localhost:8100/session/DD954ED5-9335-4CD2-898D-1FD7DDBF0C3B/wda/tap/0] with body: {"x":839,"y":675}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"DD954ED5-9335-4CD2-898D-1FD7DDBF0C3B","status":0}
[debug] [MJSONWP] Responding to client with driver.performTouch() result: null
[HTTP] <-- POST /wd/hub/session/60d6ceba-41cd-4773-a4ca-c5e926e5a63a/touch/perform 200 1112 ms - 76 
[HTTP] --> GET /wd/hub/session/60d6ceba-41cd-4773-a4ca-c5e926e5a63a/screenshot {}
```

**Comment by mykola-mokhnach** [comment]
Is the orientation set to landscape?

**Comment by quannd307** [comment]
@mykola-mokhnach Yes, my app is opened in landscape mode.

**Comment by mykola-mokhnach** [comment]
Then it's known WDA issue. You can try to workaround it by providing an actual webelement instance to TouchActions interface to tap on or wait until https://github.com/facebook/WebDriverAgent/pull/714 is merged and published

**Comment by quannd307** [comment]
@mykola-mokhnach Thank you.

**Comment by quannd307** [comment]
Hi @mykola-mokhnach I tried the latest version of WDA(v2.56.0), but this issue still happens. Could you plz recheck this issue?
