### ISSUE TITLE
Click on Alerts(OK,Allow,Cancel) does not work on Appium v1.7.0-beta

### ISSUE THREAD

**Issue by VenkateshPS** [appium/appium#9331]
## The problem

Click on Alerts(OK,Allow,Cancel) does not work on Appium 1.7

## Environment

* 1.7.0-beta
* Last Appium version that did not exhibit the issue (if applicable): v1.6.6-beta.4
* Desktop OS/version used to run Appium: os siera 10.12.6
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS 10.3, iOS 11
* Real device or emulator/simulator: Real devices
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

driver.findElementById("OK").click();
works fine on 1.6.6 beta4

**Comment by mykola-mokhnach** [comment]
Use ["mobile: alert"](https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios-xctest-mobile-gestures.md) endpoint for such purpose.

**Comment by VenkateshPS** [comment]
looks like this is Xcode 9 rather than appium issue, it does not works even if i move to 1.6.6.

was working fine with Xcode 8.3.3 and appium 1.6.6, when i upgraded to Xcode 9 seeing this issue.

**Comment by VenkateshPS** [comment]
Can somebody provide me java equivalent code for  

# Python
driver.execute_script('mobile: alert', {'action': 'accept', 'buttonLabel': 'My Cool Alert Button'});

**Comment by vikramvi** [comment]
@VenkateshPS  did you get it working ? Even I'm looking for this solution

**Comment by vikramvi** [comment]
@mykola-mokhnach I could get it working as below, but first checkpoint which confirms if alert dialog is present takes quite long because of xpath on iOS 11.0 I guess ( from your other post answers )
How can I make it faster ? 

```
if(getDriver().findElements(By.xpath("//XCUIElementTypeAlert[contains(@name,'access your location while you are using the app')]")).size()  ) {
                JavascriptExecutor js = (JavascriptExecutor) getDriver();
                HashMap<String, String> tapObject = new HashMap<String, String>();
                tapObject.put("action", "accept");
                tapObject.put("label", "Allow");
                js.executeScript("mobile:alert", tapObject);
              }
```

@VenkateshPS above solution is working perfectly except first query needs to be resolved.

**Comment by Gnanaraj-S** [comment]
I had the same issue with iOS 10 & 11.

In iOS 10 - I can get it done using driver.switchTo().alert().accept();
In iOS 11 - The same works. Along with that just inspecting the element using @iOSFindBy annotation for "Allow" and clicking on it also works.
