### ISSUE TITLE
Appium fails to start tests on Samsung S6 Edge after upgrading to latest appium version 1.7.1

### ISSUE THREAD

**Issue by skumar1122** [appium/appium#9332]
## The problem

I am trying to run my existing tests on Android devices using appium, since I did upgraded to latest version 1.7. I am having issues in running same tests on Samsung S6 Edge device with 7.0 OS.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Node.js version (unless using Appium.app|exe): v8.4.0
* Mobile platform/version under test:7.0
* Real device or emulator/simulator:Samsung s6edge
* Appium CLI or Appium.app|exe:

## Details

Failing to start tests on Samsung S6 Edge after upgrading to latest appium version.

## Link to Appium logs
https://gist.github.com/skumar1122/6c99cfd41ab90a3ad14f22520ed1e22f

Could some one please let me know If this has been recorded ?

Thanks
Shiva

**Comment by mykola-mokhnach** [comment]
You must use Selenium client/grid version 3.5+

**Comment by imurchie** [comment]
Are you able to run `/Users/international/Library/Android/sdk/platform-tools/adb -P 5037 -s 04157df45bc7e123 forward --list` on your own? This appears to be failing.

**Comment by reuningATL** [comment]
@mykola-mokhnach How can I upgrade Selenium by itself if is contained in appium?

**Comment by mykola-mokhnach** [comment]
Appium itself does not contain anything, but it has a protocol to interact with selenium grid, which is an external service. And since version 3 selenium grid registration interfaces have been changed to make them compatible with W3C standard, so Appium had to update these as well, which makes it incompatible to Selenium grid v2.

**Comment by skumar1122** [comment]
Thank you guys , I will update selenium version now.

**Comment by skumar1122** [comment]
Hi @mykola-mokhnach ,

I am using latest version Grid 3.6.0 with Appium 1.7.1 running tests same device gives me below error,
https://gist.github.com/skumar1122/9bd3afb590a465f1d924093c143cf565

**Comment by skumar1122** [comment]
@imurchie 
Sorry I dint get that , could you please let me know more what do you mean?

> Are you able to run /Users/international/Library/Android/sdk/platform-tools/adb -P 5037 -s 04157df45bc7e123 forward --list on your own? This appears to be failing.

**Comment by mykola-mokhnach** [comment]
This is another problem now. Make sure your Android SDK tools are up to date on this machine and install the recent beta version of appium.

**Comment by skumar1122** [comment]
I have updated now with latest Android Studio 2.3.3 and Appium 1.7.2-beta and restarted machine, its working now.  As said before still it opens Appium settings(not an issue for me but trying to understand) and then it opens browser, is this newly implemented as part oflatest Appium version ?

**Comment by mykola-mokhnach** [comment]
I also find it a bit annoying that settings app is started each time the session starts. Will try to improve that soon.

**Comment by skumar1122** [comment]
Hi @mykola-mokhnach ,
Sorry , I am seeing same issue again after few successful tests. Now I am seeing browser loads up initially and stays on same page and it fails to navigate to url. Please could you suggest ?
Android Studio - 2.3.3
Appium - 1.7.2 beta
Device - Samsung s6 or s6edge same
OS - 7.0

Logs:
https://gist.github.com/skumar1122/ecca86fe31c2edcb5fd5a32d4eb91710

![06157df68947b219](https://user-images.githubusercontent.com/20112173/31612390-7b45c052-b277-11e7-93c4-2e4405ea6395.jpg)
