### ISSUE TITLE
xcodebuild exited with code 65

### ISSUE THREAD

**Issue by kanemontreuil** [appium/appium#9333]
## The problem

Launching the Appium session via our Java project results in a `xcodebuild exited with code 65 and signal null` error.

## Environment

* Appium version (or git revision) that exhibits the issue: `1.7.1`
* Desktop OS/version used to run Appium: `macOS 10.12.6 (16G29)`
* Node.js version (unless using Appium.app|exe): `v7.10.0`
* Mobile platform/version under test: `iOS 10.2 (14C92)`
* Real device or emulator/simulator: `Real device`
* Appium CLI or Appium.app|exe: `Appium CLI`
* Xcode version: `9.0 (9A235)`

## Details

xcodebuild 'test' command:
```
xcodebuild -project /usr/local/lib/node\_modules/appium/node\_modules/appium\-xcuitest\-driver/WebDriverAgent/WebDriverAgent\.xcodeproj -scheme WebDriverAgentRunner -destination 'id=96ceff3e69ddd6419dba5fec6239f818dc20df8c' test
```

xcodebuild 'debug' command:
```
xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=96ceff3e69ddd6419dba5fec6239f818dc20df8c -configuration Debug -xcconfig /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Configurations/ProjectSettings.xcconfig
```

Resulting error for both xcodebuild commands:
```
CodeSign /Users/ncrsilver/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app/Frameworks/XCTAutomationSupport.framework
```

Resulting error for launching Appium session via Java project:
```
CodeSign /Users/ncrsilver/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/WebDriverAgentLib.framework/Frameworks/RoutingHTTPServer.framework
```

## Link to Appium logs

* Appium error logs: [appium.log](https://gist.github.com/kanemontreuil/065536fd20601ed343643cd4be3b4bdf)
* xcodebuild 'test' logs: [xcodebuild_test.log](https://gist.github.com/kanemontreuil/a168af339828d719b1053d93d6147928)
* xcodebuild 'debug' logs: [xcodebuild_debug.log](https://gist.github.com/kanemontreuil/9d02669f3eb6477833829e168bc584fa)

**Comment by mykola-mokhnach** [comment]
Error 65 means there are problems with WDA sources signing. Make sure you follow https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md

**Comment by kanemontreuil** [comment]
We have followed the steps outlined in the doc linked above, but are still facing the 65 error. Is there any other information we can provide to determine the exact issue with the WDA signing process?

**Comment by bangyApp** [comment]
@mykola-mokhnach  : i have followed the steps mentioned in the linked document, but still facing the same issue. Can you provide any insight for this? I'm using Appium v 1.7.1 (desktop app 1.2.6) to launch webdriveragent.

**Comment by vikramvi** [comment]
@bangyApp @kanemontreuil please check https://github.com/appium/appium/issues/9035#issuecomment-323005773 and let me know if it helps
