### ISSUE TITLE
Aapt dump badging command exited with code 127

### ISSUE THREAD

**Issue by rachuta** [appium/appium#9334]
Appium is throwing exited with code 127 when aapt dump badging command is executed.

* Build tools: 23.0.1, 23.0.3, 24.0.1
* Appium version (or git revision) that exhibits the issue: 1.6.5
* Desktop OS/version used to run Appium: Ubuntu
* Mobile platform/version under test: Android 6
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI

Appium Logs
>     2017-09-28 00:22:01:480 - info: [debug] [Logcat] Stopping logcat capture
>     2017-09-28 00:22:01:482 - info: [debug] [ADB] Removing forwarded port socket connection: 8200
>     2017-09-28 00:22:01:483 - info: [debug] [ADB] Running '/home/local/ANT/jaysent/android-sdk-linux/platform-tools/adb' with args: ["-P",5037,"-s","32080bdf636a5181","forward","--remove","tcp:8200"]
>     2017-09-28 00:22:01:495 - error: [MJSONWP] Encountered internal error running command: Error: Command '/home/local/ANT/jaysent/android-sdk-linux/platform-tools/aapt dump badging /usr/local/avm/versions/1.6.5/node_modules/appium/node_modules/appium-uiautomator2-driver/uiautomator2/appium-uiautomator2-server-v0.1.5.apk' exited with code 127
>         at ChildProcess.<anonymous> (../../lib/teen_process.js:70:19)
>         at emitTwo (events.js:100:13)
>         at ChildProcess.emit (events.js:185:7)
>         at maybeClose (internal/child_process.js:850:16)
>         at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
>     2017-09-28 00:22:01:497 - info: [HTTP] <-- POST /wd/hub/session 500 23751 ms - 383
>     2017-09-28 00:22:01:515 - info: [HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"appPackage":"com.amazon.sellermobile.android","appActivity":"com.amazon.sellermobile.android.startup.StartupActivity","newCommandTimeout":500,"automationName":"uiautomator2","browserName":"","udid":"32080bdf636a5181","platformName":"Android","deviceName":"Android"}}

what is the preferred build tools version for Appium 1.6.5?

**Comment by mykola-mokhnach** [comment]
This can happen if the server apk itself is damaged or not accessible. Can you update to 1.7.1 and try again?

**Comment by rachuta** [comment]
This command works when

**Comment by mykola-mokhnach** [comment]
It might be that appium process does not have permissions to that file. Make sure appium server process owner has R/W permissions to the folder where the corresponding node module is installed.

**Comment by rachuta** [comment]
I provided R/W permission to the corresponding node module, but still the process is unable to run the command.

**Comment by mykola-mokhnach** [comment]
Try to uninstall appium and install the newest version, which is currently 1.7.1. Make sure you perform all the operations as the current user (not as a root).
