### ISSUE TITLE
Unable to launch the app on the Simulator 

### ISSUE THREAD

**Issue by Rnij** [appium/appium#9335]
## The problem

I am trying to launch the app on the simulator.

## Environment

Appium version: 1.6.5
•Desktop OS/version used to run Appium: Mac OS Sierra 10.12.5
 Node.js version (unless using Appium.app|exe):
 Mobile platform/version under test:10.3
 Real device or emulator/simulator:iPad Pro Simulator
 Appium CLI or Appium.app|exe: 1.2.1

## Details
Following are the desired capabilities that I am giving in the Appium Session.

Capabilities:
 app: '/Users/rgupte/Desktop/POD.app'
 automationName: 'XCUITest'
deviceName: 'iPad Pro (9.7 inch)'
 platformName: 'iOS'
 platformVersion: '10.3.1'
 udid: '4B3B8228-0EC9-4B46-A94F-539F4AC99ADA'
 xCodeOrgId: 'AUP79D422L'
 xCodeSigningId: 'iPhone Developer'

I can see the webdriveragent getting installed on the simulator and can also see the app getting installed successfully on the simulator but it fails to launch the app. It gives "Got response with status 200: {"value":"Failed to launch Davita.POD-ipad-app application","sessionId":"285CD6D3-B9D4-46CF-95C1-FEC0AFC84CA8","status":13} Failed to create WDA session. Retrying...[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1506621311205 (12:55:11 GMT-0500 (CDT))
[debug] [XCUITest] Sending createSession command to WDA"

## Link to Appium logs

[appium-server-logs.txt](https://github.com/appium/appium/files/1341940/appium-server-logs.txt)

**Comment by alvingalangcitaka** [comment]
"Carthage not found. Install using `brew install carthage`"

First thing first, make sure that you have carthage installed.

I encounter this problem so many times when setting up new machine.
If you are running the test on eclipse, make sure that you open the eclipse by running :
open /path/to/Eclipse.app/Contents/MacOS/eclipse
example : open /Application/Eclipse.app/Contents/MacOS/eclipse
Dont open directly from the /Application folder by clicking the Eclipse.app.

Because when it tries to install the WDAgents, it's going to utilize the carthage, you might have installed carthage but it's not executable from eclipse you are opening.

Hope it helps.

**Comment by Rnij** [comment]
I have already installed carthage and which Carthage displays 
/usr/local/bin/carthage
I am trying to launch my app from the Appium desktop app. I have tried through exclipse and it displays the same thing Failed to launch the app with status 13.  Please advise on what might be the issue and how can I resolve it.

**Comment by mykola-mokhnach** [comment]
> Failed to launch Davita.POD-ipad-app application

This is what the log says. Are you able to execute install and execute the app manually on Simulator?

**Comment by Rnij** [comment]
@mykola-mokhnach can you please share the steps on how to install and execute the app manually on Simulator?

**Comment by mykola-mokhnach** [comment]
You may use `xcrun simctl install` command line utility for such purpose.

**Comment by Rnij** [comment]
@mykola-mokhnach I tried installing on the simulator manually using xcrun command line utility  and it did not give me any error or success message. On trying to launch it manually through terminal with the command line utility, it does not do anything, the cursor just moves to the next line on terminal. 
I tried to click on the app to launch but it just flashes, opens and closes immediately.

**Comment by mykola-mokhnach** [comment]
> I tried to click on the app to launch but it just flashes, opens and closes immediately.

This means that the application crashes on startup. I would check the build with developers.
