### ISSUE TITLE
With 1.7.1 not able to tap on the assistive touch window using coordinates

### ISSUE THREAD

**Issue by manoj0384** [appium/appium#9336]
## The problem

To navigate to he widgets and other apps from the test I was using assistive touch to go to the home screen and then navigate to the desired app or widgets. This was working fine till I upgraded appium to 1.7.1 from 1.6.5.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable): 1.6.5
* Desktop OS/version used to run Appium: McOSSierra
* Node.js version (unless using Appium.app|exe): v7.7.3
* Mobile platform/version under test: iOS 10.3
* Real device or emulator/simulator: iPhone 7 (real device)
* Appium CLI or Appium.app|exe: Tried on both

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by manoj0384** [comment]
Steps to reproduce, on iphone version > 6+ 
1. Enable assistive touch
2. keep the touch window over the time label in your in portrait mode
3. Launch any testable app through appium. Assistive touch window will be visible on top (coordinates on iphone plus y = 30, x = 207).
4. Try to tap on this coordinates through driver eg. iosdriver.Tap(1, 30, 207)
5. With appium 1.6.5 it opens the assitive touch window but with 1.7.1 it clicks on the element underneath.

So there is nothing noticeable in the log. I will try to provide you when I get a chance.
Thanks for looking in to the problem.

**Comment by mykola-mokhnach** [comment]
iosdriver.Tap(1, 30, 207) is deprecated. Try to perform the tap using TouchActions interface or [mobile gestures](https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios-xctest-mobile-gestures.md)

**Comment by mykola-mokhnach** [comment]
If it still does not work then please report the issue to https://github.com/facebook/WebDriverAgent/issues, because Appium itself only proxies commands to WDA, and the agent itself executes them on the device.

**Comment by manoj0384** [comment]
Issue raised on the web driver agent portal. 
Thanks for investigating
