### ISSUE TITLE
With 1.7.1 I am not able to see the elements of third party extensions like whatsapp in the page source

### ISSUE THREAD

**Issue by manoj0384** [appium/appium#9337]
## The problem

With 1.6.5 I was able to use appium to share to whatsapp and skype from my hybrid ios app. Appium was able to detect the page elements of both whatsapp and skype extensions. After upgrading to 1.7.1 my tests are failing to find the elements in the extension using xpath. Also the elements are not visible in the page source.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable): 1.6.5
* Desktop OS/version used to run Appium: McOSSierra
* Node.js version (unless using Appium.app|exe): v7.7.3
* Mobile platform/version under test: iOS 10.3
* Real device or emulator/simulator: iPhone 7 (real device)
* Appium CLI or Appium.app|exe: Tried on both

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Please report to https://github.com/facebook/WebDriverAgent/issues. There is nothing we can do in Appium to change this.
