### ISSUE TITLE
Bundle WinAppDriver v1.0 with Appium

### ISSUE THREAD

**Issue by sagaraghera** [appium/appium#9339]
## The problem
Current version of Appium is pointing to v0.9-beta for appium-windows driver. Can we please have v1.0-RC version for appium-windows driver (Windows Application Driver). It is stable and has multiple bug fixes (verified indepedently)
## Environment
* Appium version (or git revision) that exhibits the issue: v1.7.1
* Desktop OS/version used to run Appium: Windows 10 RS2 
* Node.js version (unless using Appium.app|exe): 
* Mobile platform/version under test: Windows 10 Desktop 
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: CLI

## Details
Windows Application Driver has many bug fixes with v1.0 RC update. 

## Link to Appium logs
N/A

## Code To Reproduce Issue [ Good To Have ]
Install appium v1.7.1 and check WinAppDriver version (its pointing to v0.9-beta)

**Comment by mykola-mokhnach** [comment]
@dpgraham FYI

**Comment by dpgraham** [comment]
We can do that. But can I just ask, if it's stable then why does it have the RC identifier?

**Comment by sagaraghera** [comment]
As per Microsoft, this will be the first release without the beta tag (all previous versions were beta versions)

**Comment by camillake** [comment]
@dpgraham  There is a v1.0 release few days ago, no RC, which supports launching application with arguments and some fixes.

**Comment by sagaraghera** [comment]
@camillake Thanks for pointing out. It will be ideal to have v1.0 release with latest appium release.

**Comment by yodurr** [comment]
I believe this issue is now fixed.
v1.7.2 of Appium which was just released is linked to WinAppDriver 1.0.
