### ISSUE TITLE
Add start/stop recording screen

### ISSUE THREAD

**Issue by dpgraham** [appium/appium#9340]
None of the clients have implemented [start recording screen](https://github.com/appium/appium-base-driver/blob/master/lib/mjsonwp/routes.js#L316)

Acceptance Criteria
* [x] Python client
* [x] Java client
* [x] WebdriverIO
* [x] WD
* [x] Ruby client
* [ ] PHP client
* [ ] .NET client
* [x] Add start/stop recording screen to commands documents

**Comment by KazuCocoa** [comment]
I can help adding commands for some clients, especially Ruby.
Please mention me if you create issues like this. 👍

**Comment by dpgraham** [comment]
Sure thing @KazuCocoa

**Comment by mayuayla** [comment]
Looking forward to this in Python.   Thank you!  Till then, I'll execute adb screenrecord from my tests.

**Comment by KazuCocoa** [comment]
You can create a PR for Python :)

**Comment by saikrishna321** [comment]
https://github.com/appium/java-client/pull/814

**Comment by dpgraham** [comment]
Closing this. PHP and .NET still need to be implemented but those will be part of a greater overhaul of PHP and .NET clients.
