### ISSUE TITLE
Appium exited with code 253 during installation

### ISSUE THREAD

**Issue by shrikanthkalluraya** [appium/appium#9341]
## The problem

We have a automation setup where we have around 15 testcases for iOS. After every testcase we reset the app(uninstall and reinstall). After certain testcases (its random) appium quits and give error 253 and my testsuite ends there without executing next testcases
## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Desktop OS/version used to run Appium: No desktop version
* Node.js version (unless using Appium.app|exe): v6.11.2
* Mobile platform/version under test: v 10.3.3
* Real device or emulator/simulator: iPhone 7 real device
* Appium CLI or Appium.app|exe: appium cli

## Details

For every testcase I have to do uninstall and install so I do reset of application.

## Link to Appium logs

 https://gist.github.com/shrikanthkalluraya/1416563c261ea94081ead1a8c3724895

**Comment by imurchie** [comment]
Please try upgrading to the latest Appium (1.7.1 as I write this). There have been changes to how app install is processed.

**Comment by shrikanthkalluraya** [comment]
I updated appium but still facing same issue

**Comment by mykola-mokhnach** [comment]
Please attach the updated log

**Comment by LukasLewandowski** [comment]
I have also encountered that issue and for me rebuilding and running app through Xcode helps.

**Comment by mykola-mokhnach** [comment]
Closed as inactive

**Comment by mukundPB** [comment]
An unknown server-side error occurred while processing the command. Original error: Could not install app: 'Command 'ios-deploy --id 202bc3b5a4c4571e98c08785b278002c7deed0f3 --bundle /var/folders/pt/21gmpq_s3cj3f1_y5p40wk_m0000gp/T/2018227-11503-1vurl2a.cw5x/Payload/Willow.app' exited with code 253' (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 19.68 seconds i just changed the Iphone and i am getting this issue please help
