### ISSUE TITLE
stuck in function self.driver.get_screenshot_as_file(str(file_name)) and throw exception 10min later

### ISSUE THREAD

**Issue by s-xq** [appium/appium#9342]
## The problem

When i was use `self.driver.get_screenshot_as_file(str(file_name))`to capture the screen in android system , this just stuck and never return until an exception occur (see it in the end of this log file
[appium_20170930093734_self.driver.get_screenshot_as_file(str(file_name))_1.txt](https://github.com/appium/appium/files/1346249/appium_20170930093734_self.driver.get_screenshot_as_file.str.file_name._1.txt)
). This problem happened quite a lot in these few days . Please tell me how can i solve this problem.
Thank you !

## Environment

* Appium version (or git revision) that exhibits the issue:Appium v1.6.4
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:OS X EI Capitan 10.11.6
* Node.js version (unless using Appium.app|exe):v7.10.0
* Mobile platform/version under test:Android7.0
* Real device or emulator/simulator:real device,device name is : Huawei Honor V9 DUK-AL20
* Appium CLI or Appium.app|exe:Appium CLI

## Details
Python verison : 2.7.10
```exception
2017-09-30 09:37:34:138 - [HTTP] --> GET /wd/hub/session/4bf3b6a4-2e6b-472f-b96f-f1fe883781b1/screenshot {}
2017-09-30 09:37:34:163 - [debug] [MJSONWP] Calling AppiumDriver.getScreenshot() with args: ["4bf3b6a4-2e6b-472f-b96f-f1fe883781b1"]
2017-09-30 09:47:20:079 - [HTTP] <-- GET /wd/hub/session/4bf3b6a4-2e6b-472f-b96f-f1fe883781b1/source - - ms - - 
Error: write EPIPE
    at exports._errnoException (util.js:1050:11)
    at WriteWrap.afterWrite (net.js:814:14)

```
## Link to Appium logs
This is the  Appium logs 
[Uploading appium_20170930093734_self.driver.get_screenshot_as_file(str(file_name))_1.txt…]()

## Code To Reproduce Issue [ Good To Have ]
```
cmd = "appium --log-level debug:error --log-timestamp --local-timezone --session-override -p %d -bp %d >> ./log/appium4.log" % (4723, 4724)
  self.appium_server_t = subprocess.Popen(cmd, stdout=subprocess.PIPE, shell=True)
```
```
self.driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)
```
```
self.driver.get_screenshot_as_file(str(file_name)) 
```

**Comment by mykola-mokhnach** [comment]
Try Appium 1.7.1 and UIAutomator2 as the backend.

**Comment by mykola-mokhnach** [comment]
The attached appium log link seems to be wrong

**Comment by s-xq** [comment]
What info do you need?  What's it mean ?『The attached appium log link seems to be wrong』

**Comment by mykola-mokhnach** [comment]
Found the log in the other ticket. It would be better to combine these into a single ticket.

**Comment by s-xq** [comment]
thanks ~

**Comment by prat3ik** [comment]
Hi @mykola-mokhnach , 
Any updates on this?

I am automating the messaging app, I can send a message to 1st person successfully(on messaging screen of 1st person) but when I navigate to 2nd person's messaging screen I am not able to access any elements which were previously accessible for 1st person's messaging screen.

When I execute `driver.page_source` on 1st person's messaging screen it is giving me the correct source info.
But on 2nd person's messaging screen it gets stuck.!

Does it have the problem with application ? or am I missing something?
Do you have any idea for this?

**Comment by mykola-mokhnach** [comment]
Screenshoting logic with UIA2 has been improved in the recent server releases.
