### ISSUE TITLE
appium 1.7.1 runs very slow iOS

### ISSUE THREAD

**Issue by alicenahkarakol** [appium/appium#9347]
## The problem

I was using appium 1.6.4 and I upgraded my Mac version, xcode, and appium to latest versions on last Friday 30 September. I run my scenarios again but it is very slow when I compare 1.7.1 to 1.6.4.

## Environment

mac ver : 10.12.6
appium 1.7.1
xcode: 9 
java client 5 beta 8 

I did not download wda new version since it seems like there is no update in 2 months.
I did not upgrade iOS version I run my scripts on iOS 10.2.3

## Details

Running my scripts takes 2-3 times more time than before. Is it known issue or do I have any problem with my setup.

**Comment by mykola-mokhnach** [comment]
Do you use xpath locators?

**Comment by alicenahkarakol** [comment]
@mykola-mokhnach  hi ,
Yes, I added some examples that I use always.

economyPromotionTextXpath=//XCUIElementTypeStaticText[@label='PROMOSYON']
economyFlexTextXpath=//XCUIElementTypeStaticText[@label='ESNEK']
selectAsFavorite=//XCUIElementTypeButton[@label='star empty']
follow=//XCUIElementTypeButton[@label='star empty']
followtext=//XCUIElementTypeStaticText[@value='TAK\u0130P ET' or @value='FOLLOW']
maxAirportXpath=//XCUIElementTypeStaticText[@label='Favori \u015Fehirlerinize en fazla 5 \u015Fehir ekleyebilirsiniz.']
exitButtonXpath=//XCUIElementTypeButton[@label='btn exit']

**Comment by mykola-mokhnach** [comment]
Then it's known WDAS/XCTest issue. Try replace these locators with faster ones to improve the perf as described in https://github.com/facebook/WebDriverAgent/wiki/How-To-Achieve-The-Best-Lookup-Performance

**Comment by alicenahkarakol** [comment]
@mykola-mokhnach ok thanks but these xpaths were fine.. What Is changed? Just to know it.

**Comment by mykola-mokhnach** [comment]
Apple has deprecated snapshoting since Xcode9.

**Comment by alicenahkarakol** [comment]
@mykola-mokhnach hi again. I know this is not totally relevant to bug but if can give a example in java it would be helpful for me and the people who checks this. 
How to change this xpath to the style that you mentioned in article.
//XCUIElementTypeStaticText[@Label='PROMOSYON']
I expect something like 
driver.findelement(by.classname "XCUIElementTypeStaticText" && by.label"promotion");

thanks in advance..
