### ISSUE TITLE
[1.7.0] [xcode 9] ERROR:Unable to boot device due to insufficient system resources

### ISSUE THREAD

**Issue by Tamikana** [appium/appium#9348]
## The problem

Appium doesn't start. It fails with ERROR: Unable to boot device due to insufficient system resources
![screen shot 2017-10-02 at 11 51 17 am](https://user-images.githubusercontent.com/18285183/31070705-067fd3ec-a76a-11e7-9c47-559ad5bbb675.png)

## Environment

* Appium version 1.7.0
* MacOS
* npm 4.1.2
* iOS 10.3, Xcode 9
* Simulator
* Appium CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/Tamikana/093691bd0c61ce4f1b793dfbf57344ce

**Comment by mykola-mokhnach** [comment]
It's OS-level limitation, that has nothing to do with Appium. Try https://blog.dekstroza.io/ulimit-shenanigans-on-osx-el-capitan/ to workaround it.
