### ISSUE TITLE
Error forwarding the new session 

### ISSUE THREAD

**Issue by fdPoornima** [appium/appium#9349]
## The problem

I have an automation framework on Android and IOS native apps using appium, which was running fine. Today, I am getting this error 

Error forwarding the new session Empty pool of VM for setup Capabilities [{app=/Users/T/fd/apk/test.apk, noReset=true, platformVersion=7.0, automationName=uiautomator2, udid=4ss343gg, platformName=Android, deviceName=SamsungGalaxyS7, resetKeyboard=true, systemPort=6973}]
Command duration or timeout: 151 milliseconds
Caused by: org.openqa.selenium.WebDriverException: 

The error is thrown when new AndroidDriver session is trying to be created.

## Environment

* Appium version (or git revision) that exhibits the issue: Appium v1.7.0
* Last Appium version that did not exhibit the issue (if applicable): Appium v1.7.0
* Desktop OS/version used to run Appium: Mac
* Node.js version (unless using Appium.app|exe): v6.11.1
* Mobile platform/version under test: Android 7.0
* Real device or emulator/simulator: Real Device

## Code To Reproduce Issue [ Good To Have ]

Code is as below.
File app = new File("apk/test.apk");
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability(MobileCapabilityType.APP, app.getAbsoluteFile());
        capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, browserName);
        capabilities.setCapability(MobileCapabilityType.UDID, udid);
        capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME,"uiautomator2");
        capabilities.setCapability(AndroidMobileCapabilityType.SYSTEM_PORT,system_port);
        capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, platformName);
        capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION,"7.0");
        capabilities.setCapability(MobileCapabilityType.NO_RESET, "true");
        capabilities.setCapability("resetKeyboard", true);
        return new AndroidDriver(hubUrl, capabilities);

**Comment by mykola-mokhnach** [comment]
Please attach the full server log.

This error is usually shown by selenium hub if there are no free nodes where the test with given capabilities can be executed. I don't think it has anything to do with Appium.

**Comment by fdPoornima** [comment]
I was trying to manually add the node through command prompt. See the below steps that I followed.

1)Started Selenium grid as java -jar lib/selenium-server-standalone-2.53.0.jar -role hub

Launching Selenium Grid hub
2017-10-02 15:17:48.295:INFO::main: Logging initialized @876ms
15:17:48.308 INFO - Will listen on 4444
15:17:48.359 INFO - Will listen on 4444
2017-10-02 15:17:48.362:INFO:osjs.Server:main: jetty-9.2.z-SNAPSHOT
2017-10-02 15:17:48.401:INFO:osjsh.ContextHandler:main: Started o.s.j.s.ServletContextHandler@52525845{/,null,AVAILABLE}
2017-10-02 15:17:48.445:INFO:osjs.ServerConnector:main: Started ServerConnector@275b1238{HTTP/1.1}{0.0.0.0:4444}
2017-10-02 15:17:48.448:INFO:osjs.Server:main: Started @1030ms
15:17:48.448 INFO - Nodes should register to http://192.168.2.144:4444/grid/register/
15:17:48.449 INFO - Selenium Grid hub is up and running

-->The grid was started and I can see the grid console at http://localhost:4444/grid/console

2)Trying to start the node by /usr/local/bin/appium --log appiumlog/ce11160bbbdf5c2d02.txt --nodeconfig appium/androidDevicesJson/ce11160bbbdf5c2d02.json --session-override -p 4866 -bp 2251
[Appium] Welcome to Appium v1.7.0
[Appium] Non-default server args:
[Appium]   port: 4866
[Appium]   bootstrapPort: 2251
[Appium]   sessionOverride: true
[Appium]   log: appiumlog/ce11160bbbdf5c2d02.txt
[Appium]   nodeconfig: appium/androidDevicesJson/ce11160bbbdf5c2d02.json
[debug] [Appium] No registration sent (true = false)
[Appium] Appium REST http interface listener started on 0.0.0.0:4866

I see the log that the appium has started. However, when I navigate to the grid console I do not see the node connected.

**Comment by mykola-mokhnach** [comment]
Probably because you use outdated hub version. For Appium 1.7 it should be 3.5+

**Comment by fdPoornima** [comment]
@mykola-mokhnach  : Thanks for your help. I found out the issue, it was because "clearSystemFiles" and "register" parameters in the json file was given as string "true". I changed them to boolean true and the error was gone.

**Comment by Shashank-Intelematics** [comment]
@fdPoornima :Hi can you please advice how you changed clearSystemFiles and register(can you please send Json snippett).
I am facing same issue
