### ISSUE TITLE
WebDriverAgent Crashing on iOS 11 simulator

### ISSUE THREAD

**Issue by shanthi2016** [appium/appium#9350]
WebDriverAgent gets crashed when trying to run the test on iOS 11.

The app gets installed and then the Webdriveragent is unable to install and it keeps on crashing.
Webdriveragent runner build was successful in xcode 9.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable): 1.6.4
* Desktop OS/version used to run Appium: Mac OS 10.12.6
* Node.js version (unless using Appium.app|exe):6.10.2
* Mobile platform/version under test: 11.0
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: Both 

Please find attached logs:
https://gist.github.com/shanthi2016/7a65f222465c255a4064f985194cb8fe

Could you please let me know where am I doing wrong

**Comment by mykola-mokhnach** [comment]
Set _showXcodeLog_ capability to true and attach the log again.

Have you tried to install run your application under test on Simulator manually? Did it work?

**Comment by shanthi2016** [comment]
Here are the logs: https://gist.github.com/shanthi2016/773f6c891cc83b44ff83431eadff337e
Yes,I checked the app installed with Appium on simulator and it works fine.

Here are the capabilities:

                DesiredCapabilities cap = new DesiredCapabilities();
		File app = new File(
				"Sample.app");
		cap.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone 8");
		cap.setCapability(MobileCapabilityType.PLATFORM_NAME, "iOS");
		cap.setCapability(MobileCapabilityType.PLATFORM_VERSION, "11.0");
		cap.setCapability(MobileCapabilityType.AUTOMATION_NAME,"XCUITest");
		cap.setCapability(MobileCapabilityType.APP, app.getAbsolutePath());
		cap.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, 120);
		cap.setCapability("showXcodeLog",true);
		cap.setCapability("useNewWDA",true);
		driver = new IOSDriver<WebElement>(new URL("http://127.0.0.1:4723/wd/hub"), cap);

**Comment by mykola-mokhnach** [comment]
> [Xcode] } (error = Error Domain=FBSOpenApplicationServiceErrorDomain Code=3 "The request to open "com.apple.test.WebDriverAgentRunner-Runner" failed." UserInfo={NSLocalizedFailureReason=The process did launch, but has since exited or crashed., BSErrorCodeDescription=ProcessExited, NSLocalizedDescription=The request to open "com.apple.test.WebDriverAgentRunner-Runner" failed.})

Yep, looks like WDA crashes. It would be good if you can find this crash stacktrace and also get the full Simulator logs.

**Comment by shanthi2016** [comment]
Could you please let me know where could I find the above said full logs or stacktrace.

**Comment by shanthi2016** [comment]
Here is the simulator system logs:
https://gist.github.com/shanthi2016/8a68e23a9be70430ac3194c61d215f59

**Comment by mykola-mokhnach** [comment]
Please report this issue to https://github.com/facebook/WebDriverAgent/issues and attach the log above there.

As a workaround, try to run the test on the other simulator or the other machine.
