### ISSUE TITLE
Appium 1.7.1Could not proxy command to remote server. Original error: Error: socket hang up"

### ISSUE THREAD

**Issue by stephenws** [appium/appium#9362]
## The problem
I am running one script that was working in appium 1.6.4 but i have updated appium to 1.7.1 while running i am getting Error 
"Encountered internal error running command: Error: Unable to start WebDriverAgent session because of xcodebuild failure: "Could not proxy command to remote server. Original error: Error: socket hang up". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device."

I have reboot the device but still it is not working

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable): 1.6.4
* Desktop OS/version used to run Appium: Mac OS Sierra Version 10.12.6
* Node.js version (unless using Appium.app|exe): v6.11.0
* Mobile platform/version under test: iOS 10.0.1
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

GIST link: https://gist.github.com/stephenws/a833aa73f4cf6d36daa123bff80e6b22

## Code To Reproduce Issue [ Good To Have ]

DesiredCapabilities cap = new DesiredCapabilities();
		cap.setCapability("platformName", "iOS");
		cap.setCapability("platformVersion", "10.0.1");
		cap.setCapability("deviceName", "Sports iPhone5s");
		cap.setCapability("udid", "3424303a92e8c4ce1ea5878d5bd012388c500f0e");
		cap.setCapability("noReset", true);
		cap.setCapability("useNewWDA", true);
		cap.setCapability("showXcodeLog", true);
		cap.setCapability(MobileCapabilityType.APP, "/Users/Mukesh/Desktop/TestApp/iOS/Stage_1.7.app");		
		Base.driver=new AppiumDriver(new URL("http://0.0.0.0:4723/wd/hub"), cap);
		Base.driver.manage().timeouts().implicitlyWait(60, TimeUnit.SECONDS);

**Comment by mykola-mokhnach** [comment]
Can you please attach the log with _showXcodeLog_ capability set to true?

**Comment by mykola-mokhnach** [comment]
Can you execute the `xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=3424303a92e8c4ce1ea5878d5bd012388c500f0e IPHONEOS_DEPLOYMENT_TARGET=10.0' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent` command from terminal and attach the output to the issue?

**Comment by stephenws** [comment]
Last login: Tue Oct  3 18:45:14 on ttys000
iMaheshwari-4:~ Mukesh$ cd /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
iMaheshwari-4:WebDriverAgent Mukesh$ xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=3424303a92e8c4ce1ea5878d5bd012388c500f0e IPHONEOS_DEPLOYMENT_TARGET=10.0
Build settings from command line:
    IPHONEOS_DEPLOYMENT_TARGET = 10.0

@mykola-mokhnach this is what i am getting

**Comment by mykola-mokhnach** [comment]
some internal Xcode stuff does not behave properly. Have you tried to reboot the computer?

**Comment by stephenws** [comment]
Hey it works after reboot the computer.
Thanks for help, closing issue
