### ISSUE TITLE
App is not running in Simulator by using Appium desktop

### ISSUE THREAD

**Issue by aki1888** [appium/appium#9363]
When I am running my app in the simulator, It's getting opened and closed. Also, Appium inspector got stuck.
Appium Version - 1.7.1
 "platformName": "iOS",
  "platformVersion": "10.3",
  "deviceName": "iPhone Simulator",
  "app": "/*******.app",
  "noReset": true

Logs
[info] [Appium] Welcome to Appium v1.7.1
[info] [Appium] Appium REST http interface listener started on 0.0.0.0:4723[info] [HTTP] --> GET /wd/hub/sessions {}
[debug] [MJSONWP] Calling AppiumDriver.getSessions() with args: []
[debug] [MJSONWP] Responding to client with driver.getSessions() result: []
[info] [HTTP] <-- GET /wd/hub/sessions 200 10 ms - 40 [info] [HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/ajaiswal/Desktop/Payload/ResidentPortal.app","deviceName":"iPhone Simulator","noReset":true,"platformName":"iOS","platformVersion":"10.3","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/ajaiswal/Desktop/Payload/ResidentPortal.app","deviceName":"iPhone Simulator","noReset":true,"platformName":"iOS","platformVersion":"10.3","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1507038818155 (19:23:38 GMT+0530 (IST))
[info] [Appium] Requested iOS support with version >= 10, using XCUITest driver instead of UIAutomation-based driver, since the latter is unsupported on iOS 10 and up.
[info] [Appium] Creating new XCUITestDriver (v2.51.1) session
[info] [Appium] Capabilities:
[info] [Appium]   app: '/Users/ajaiswal/Desktop/Payload/ResidentPortal.app'
[info] [Appium]   deviceName: 'iPhone Simulator'
[info] [Appium]   noReset: true
[info] [Appium]   platformName: 'iOS'
[info] [Appium]   platformVersion: '10.3'
[info] [Appium]   newCommandTimeout: 0
[info] [Appium]   connectHardwareKeyboard: true
[info] [BaseDriver] Session created with session id: 2140d359-0aed-4d00-885a-2749b7793013
[debug] [XCUITest] Xcode version set to '8.3.2' (tools v8.3.2.0.1.1492020469)
[debug] [XCUITest] iOS SDK Version set to '10.3'
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1507038818357 (19:23:38 GMT+0530 (IST))
[debug] [XCUITest] Changing deviceName from 'iPhone Simulator' to 'iPhone 6'[info] [iOSSim] Constructing iOS simulator for Xcode version 8.3.2 with udid 'AEFD9D9D-238A-49F7-9CD7-6477D081DDBF'
[info] [XCUITest] Determining device to run tests on: udid: 'AEFD9D9D-238A-49F7-9CD7-6477D081DDBF', real device: false
[info] [BaseDriver] Using local app '/Users/ajaiswal/Desktop/Payload/ResidentPortal.app'
[debug] [BaseDriver] Event 'appConfigured' logged at 1507038818624 (19:23:38 GMT+0530 (IST))
[debug] [XCUITest] Checking whether app '/Users/ajaiswal/Desktop/Payload/ResidentPortal.app' is actually present on file system
[debug] [XCUITest] App is present[debug] [iOS] Getting bundle ID from app '/Users/ajaiswal/Desktop/Payload/ResidentPortal.app': 'com.propertysolutions.residentportal'
[debug] [BaseDriver] Event 'resetStarted' logged at 1507038818636 (19:23:38 GMT+0530 (IST))
[debug] [XCUITest] Reset: noReset is on. Leaving simulator as is
[debug] [BaseDriver] Event 'resetComplete' logged at 1507038818637 (19:23:38 GMT+0530 (IST))
[debug] [iOSLog] Starting iOS 10.3 simulator log capture
[debug] [iOSLog] System log path: /Users/ajaiswal/Library/Logs/CoreSimulator/AEFD9D9D-238A-49F7-9CD7-6477D081DDBF/system.log
[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1507038818758 (19:23:38 GMT+0530 (IST))
[info] [XCUITest] Setting up simulator
[debug] [iOS] No reason to set locale
[debug] [iOS] No iOS / app preferences to set[debug] [iOSSim] The count of running Simulator UI client instances is 1
[info] [iOSSim] Both Simulator with UDID AEFD9D9D-238A-49F7-9CD7-6477D081DDBF and the UI client are currently running
[debug] [BaseDriver] Event 'simStarted' logged at 1507038819081 (19:23:39 GMT+0530 (IST))[debug] [XCUITest] App 'com.propertysolutions.residentportal' is already installed. No need to reinstall.
[debug] [BaseDriver] Event 'appInstalled' logged at 1507038819186 (19:23:39 GMT+0530 (IST))
[info] [XCUITest] Using WDA path: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[info] [XCUITest] Using WDA agent: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[debug] [XCUITest] Capability 'useNewWDA' set to false, so trying to reuse currently running WDA instance at 'http://localhost:8100/'
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body[debug] [XCUITest] WDA is not listening at 'http://localhost:8100/'. Rebuilding...
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1507038822211 (19:23:42 GMT+0530 (IST))
[info] [XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'
[debug] [XCUITest] Killing running processes 'xcodebuild.*AEFD9D9D-238A-49F7-9CD7-6477D081DDBF, iproxy 8100, AEFD9D9D-238A-49F7-9CD7-6477D081DDBF.*XCTRunner' for the device AEFD9D9D-238A-49F7-9CD7-6477D081DDBF...[debug] [XCUITest] 'pgrep -nif xcodebuild.*AEFD9D9D-238A-49F7-9CD7-6477D081DDBF' didn't detect any matching processes. Return code: 1
[debug] [XCUITest] 'pgrep -nif iproxy 8100' didn't detect any matching processes. Return code: 1[debug] [XCUITest] 'pgrep -nif AEFD9D9D-238A-49F7-9CD7-6477D081DDBF.*XCTRunner' didn't detect any matching processes. Return code: 1
[debug] [XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=AEFD9D9D-238A-49F7-9CD7-6477D081DDBF IPHONEOS_DEPLOYMENT_TARGET=10.3' in directory '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[debug] [XCUITest] Output from xcodebuild will not be logged. To see xcode logging, use 'showXcodeLog' desired capability[debug] [XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body[debug] [XCUITest] Log file for xcodebuild test: /Users/ajaiswal/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/16C44110-B4D3-485C-B642-7A531860AE5D/Session-WebDriverAgentRunner-2017-10-03_192344-SX1Sie.log[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"state\" : \"success\",\n    \"os\" : {\n      \"name\" : \"iOS\",\n      \"version\" : \"10.3\"\n    },\n    \"ios\" : {\n      \"simulatorVersion\" : \"10.3\",\n      \"ip\" : \"192.168.169.0\"\n    },\n    \"build\" : {\n      \"time\" : \"Oct  3 2017 17:23:13\"\n    }\n  },\n  \"sessionId\" : \"A7623AB0-994F-45C6-8A93-DADE1C3B334C\",\n  \"status\" : 0\n}"
[debug] [XCUITest] WebDriverAgent running on ip '192.168.169.0'
[debug] [XCUITest] WebDriverAgent successfully started after 9018ms
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1507038831701 (19:23:51 GMT+0530 (IST))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.propertysolutions.residentportal","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}

**Comment by mykola-mokhnach** [comment]
Have you tried to install and run the application manually on the Simulator?

**Comment by aki1888** [comment]
What do mean by manually? I passed the app path in appium inspector and try to run it by start session

**Comment by mykola-mokhnach** [comment]
Manually means using `xcrun simctl install` command line utility

**Comment by aki1888** [comment]
No no I used it through appium inspector with desired capability that i wrote on my issue

**Comment by mykola-mokhnach** [comment]
Try it then. Most likely your application build is invalid/corrupted and cannot be executed on Simulator at all.

**Comment by aki1888** [comment]
I don't think so it's corrupted because I am able to run same on simulator with the help of xcode

**Comment by aki1888** [comment]
I will check that tomorrow and will update you thanks

**Comment by aki1888** [comment]
Hello mykola-mokhnach 
My issue is resolved now. Actually I am using .ipa file in the place of .app file and also taking that file not from correct folder. I am taking that app file from device folder not from simulator.

Thanks
