### ISSUE TITLE
iDeviceInstaller gives Could not connect to lockdownd. Exiting

### ISSUE THREAD

**Issue by Rnij** [appium/appium#9364]
## The problem

On trying to install the app on the real device using following command 
ideviceinstaller -i /Users/rgupte/Downloads/DavitaRX_POD_DEV_AUTOMATION.ipa
it displays 
Could not connect to lockdownd. Exiting

## Environment

•Desktop OS/version used to run Appium: Mac OS Sierra 10.12.5
Node.js version (unless using Appium.app|exe):
Mobile platform/version under test:10.3.3
Real device or emulator/simulator:Real device iPad Pro 9.7 inch
Appium CLI or Appium.app|exe: 1.2.1

## Details

Not able to install the app using iDeviceInstaller.

**Comment by imurchie** [comment]
This generally means you need to get a more recent version of `libimobiledevice`. You can get the latest with `brew install libimobiledevice --HEAD`.

**Comment by Rnij** [comment]
Thanks imurchie. 
Does that mean I need to excute following commands:
brew uninstall libimobiledevice  
brew install libimobiledevice --HEAD 

Do I also need to uninstall and install ideviceinstaller with the follwoiung command before I uninstall libimobiledevice.
brew uninstall ideviceinstaller 
brew install ideviceinstaller

**Comment by imurchie** [comment]
Sorry, I think I misspoke. You should install the latest `ideviceinstaller`.

Can you post logs for the error? I did not think that Appium used `ideviceinstaller` anymore because of issues with iOS 10+.

**Comment by Rnij** [comment]
oh ok. Should I execute the following command for getting latest ideviceinstaller.
brew uninstall ideviceinstaller
brew install ideviceinstaller

I am not able to launch the app on real device using Appium as it gives me a warning device_id is not installed. Attached are the Appium logs. Hence I was trying to see if ideviceinstaller can directly install the app on my real device with the command 
ideviceinstaller -i /Users/rgupte/Downloads/DavitaRX_POD_DEV_AUTOMATION.ipa
it displays
Could not connect to lockdownd. Exiting

Attached is a screenshot for above too. Please let me know if any other information is needed. I have been stuck with this for a long time and would really appreciate if I get any help. Thanks.
[appium-server-logs.txt](https://github.com/appium/appium/files/1352884/appium-server-logs.txt)
![screen shot 2017-10-03 at 10 47 13 am](https://user-images.githubusercontent.com/31414829/31134671-6e63e8d6-a828-11e7-8319-9a84baceb283.png)

**Comment by Rnij** [comment]
After installing latest  ideviceinstaller I was able to install the app using the command ideviceinstaller -i /Users/rgupte/Downloads/DavitaRX_POD_DEV_AUTOMATION.ipa
But when I try to launch it through appium, it gives me a message The 'idevice_id' program is not installed. Error: Unknown device or simulator UDID.

**Comment by imurchie** [comment]
`idevice_id` is part of `libimobiledevice`. If you have the latter installed it ought to be available.

What happens when you run `idevice_id -l` manually?

**Comment by Rnij** [comment]
On running idevice_id -l manually, it displays the udid of the connected iPad.
![screen shot 2017-10-05 at 10 56 49 am](https://user-images.githubusercontent.com/31414829/31236716-8f87186a-a9ba-11e7-8250-969866180809.png)

**Comment by imurchie** [comment]
How are you launching appium? Does it have access to the PATH?

**Comment by Rnij** [comment]
I am using appium desktop app version 1.2.1 to start the server. How can I find out if appium has access to the PATH?

**Comment by saikrishna321** [comment]
@Rnij from the above comments i see you have lockdown issue when installing IPA. Please try the below and see if it solves

```
brew uninstall ideviceinstaller
brew uninstall --ignore-dependencies libimobiledevice
brew install --HEAD libimobiledevice
brew unlink libimobiledevice && brew link libimobiledevice
brew install --HEAD ideviceinstaller
brew unlink ideviceinstaller && brew link ideviceinstaller
```

**Comment by Rnij** [comment]
I will try that and let you know.

**Comment by Rnij** [comment]
@saikrishna321 I ran the commands that you had mentioned but it still gives lockdown error on trying to install using ideviceinstaller.

ideviceinstaller -i /Users/rgupte/Downloads/DavitaRX_POD_DEV_AUTOMATION.ipa
it displays
Could not connect to lockdownd. Exiting

I tried launching the app through Appium after running the commands you had mentioned and it gives a new error now. attached is the screenshot of the error.

[MJSONWP] Encountered internal error running command: Error: Could not install app: 'Command 'ios-deploy --id 21dbb46b868acba3a5bc53832e2b571f9611b547 --uninstall --bundle /var/folders/d4/jvmfnng92x12hpg4x82wslzsmk7fjt/T/201795-19163-1sgs5fe.e2l5ak0529/Payload/iOSTablet.app' exited with code null'

![screen shot 2017-10-05 at 4 38 47 pm](https://user-images.githubusercontent.com/31414829/31257831-930c8506-aa00-11e7-9985-693b55a4dd8f.png)
[appium-server-logs.txt](https://github.com/appium/appium/files/1361211/appium-server-logs.txt)

Can you advise what might be the problem? Thanks.

**Comment by Rnij** [comment]
@imurchie @saikrishna321 
Thanks a lot for all the help and suggestions. I was able to finally successfully launch and install the app on a real device.

**Comment by saikrishna321** [comment]
Closing as resolved 

@Rnij can you pls post your solution, would help someone hitting on this thread.

**Comment by polaris** [comment]
I had to run the following commands to make it work.

```
brew uninstall ideviceinstaller
brew uninstall libimobiledevice
brew uninstall usbmuxd
brew install usbmuxd --HEAD
brew install --HEAD libimobiledevice
brew unlink libimobiledevice && brew link libimobiledevice
brew install --HEAD ideviceinstaller
brew unlink ideviceinstaller && brew link ideviceinstaller
sudo chmod -R 777 /var/db/lockdown
```

Finally, I had to unplug my device once.
