### ISSUE TITLE
Implicit wait is set to 0 and all tests timeout before app is finished loading when using a cucumber.yml profile

### ISSUE THREAD

**Issue by fisharu** [appium/appium#9365]
## The problem

When I attempt to run a set of cucumber tests my test stops before it starts. ImplicitWait is being set to 0 and is not waiting for the app to be ready to receive commands.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable): 1.6.4 beta?
* Desktop OS/version used to run Appium: macOS 10.12.6
* Node.js version (unless using Appium.app|exe): 8.1.3
* Mobile platform/version under test: Android O
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: Both

## Details
Here are the capabilities I'm attempting to send to my Appium driver object:
  def caps
  { caps: { automationName: 'UiAutomator2',
            deviceName: '5554',
            platformName: 'Android',
            platformVersion: '8.0',
            avd: 'Pixel_API_26',
            app: '/Users/jessefish/Documents/Git Repositories/agent_android/CincAgent/app/prod/release/app-prod-release.apk',
            appPackage: 'appname_here',
            newCommandTimeout: 30,
            appActivity: 'appname_here.controllers.SplashActivity',
            appium_lib: { wait: 20, debug: false } } }
  end

Appium::Driver.new(caps)
Appium.promote_appium_methods Object

## Link to Appium logs

https://gist.github.com/fisharu/8e3784308df957872f011129ccfe97a7

Thank you for any help you can give me regarding this.

**Comment by mykola-mokhnach** [comment]
> [UiAutomator2] UiAutomator2 did not start the activity we were waiting for, 'com.commissionsinc.cincagent/com.commissionsinc.cincagent.controllers.SplashActivity'. Starting it ourselves

Are you sure the _appActivity_ value is correct?

**Comment by fisharu** [comment]
Yes, I confirmed with my devs I'm using the right activity. I updated my npm, appium, appium_lib gems as well and I'm still getting the same behavior. 

I adjusted the Appium driver call as per the instructions in my error messages: 
Appium::Driver.new(caps, true)

but that doesn't seem to do anything.

**Comment by mykola-mokhnach** [comment]
I'd try to adjust values for appActivity/appWaitActivity capabilities.

**Comment by fisharu** [comment]
That doesn't help. No matter what I do the timeout still occurs and calls the deleteSession method and ends the test.

[debug] [ADB] Possible activities, to be checked: 'com.commissionsinc.cincagent.controllers.account.LoginActivity'
[debug] [ADB] Getting focused package and activity
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/jessefish/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","dumpsys","window","windows"]
[debug] [ADB] Found package: 'com.commissionsinc.cincagent' and fully qualified activity name : 'com.commissionsinc.cincagent.controllers.account.LoginActivity'
[Appium] New AndroidDriver session created successfully, session f826c94e-0d81-4a3a-ad05-dbe2f97935b9 added to master session list
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1507048785466 (12:39:45 GMT-0400 (EDT))
[debug] [MJSONWP] Responding to client with driver.createSession() result: {"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"noSign":true,"deviceName":"5554","platformName":"Android","platformVersion":"7.1.1","avd":"Pixel_API_25","app":"/Users/jessefish/Documents/Git Repositories/agent_android/CincAgent/app/prod/release/app-prod-release.apk","appPackage":"com.commissionsinc.cincagent","newCommandTimeout":60,"implicitWait":60,"appWaitActivity":"com.commissionsinc.cincagent.controllers.account.LoginActivity","appiumLib":{"wait":20,"debug":false}},"noSign":true,"deviceName":"emulator-5554","platformName":"Android","platformVersion":"7.1.1","avd":"Pixel_API_25","app":"/Users/jessefish/Documents/Git Repositories/agent_android/CincAgent/app/prod/release/app-prod-release.apk","appPackage":"com.commissionsinc.cincagent","newCommandTimeout":60,"implicitWait":60,"appWaitActivity":"com.commissionsinc.cincagent.controllers.account.LoginA...
[HTTP] <-- POST /wd/hub/session 200 12087 ms - 1393 
[HTTP] --> GET /wd/hub/status {}
[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.7.1","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 32 ms - 83 
[HTTP] --> POST /wd/hub/session/f826c94e-0d81-4a3a-ad05-dbe2f97935b9/timeouts/implicit_wait {"ms":0}
[debug] [MJSONWP] Calling AppiumDriver.implicitWait() with args: [0,"f826c94e-0d81-4a3a-ad05-dbe2f97935b9"]
[debug] [BaseDriver] Set implicit wait to 0ms
[debug] [MJSONWP] Responding to client with driver.implicitWait() result: null
[HTTP] <-- POST /wd/hub/session/f826c94e-0d81-4a3a-ad05-dbe2f97935b9/timeouts/implicit_wait 200 32 ms - 76 
[HTTP] --> DELETE /wd/hub/session/f826c94e-0d81-4a3a-ad05-dbe2f97935b9 {}
[debug] [MJSONWP] Calling AppiumDriver.deleteSession() with args: ["f826c94e-0d81-4a3a-ad05-dbe2f97935b9"]
[debug] [BaseDriver] Event 'quitSessionRequested' logged at 1507048785677 (12:39:45 GMT-0400 (EDT))
[Appium] Removing session f826c94e-0d81-4a3a-ad05-dbe2f97935b9 from our master session list
[debug] [AndroidDriver] Shutting down Android driver

**Comment by mykola-mokhnach** [comment]
The recent log looks pretty good. Probably, you do something unexpected on the client side? 
@KazuCocoa Maybe you can take a look?

**Comment by fisharu** [comment]
I'm not sure what I could be doing that is so drastically strange. I don't even get to my cucumber scripts because the session ends before my test steps start being run.

I didn't make any changes to my hooks:
Before do
#start appium driver
  $driver.start_driver
end

After do |scenario|
#If the scenario failed take a screenshot, then quit appium driver

  if scenario.failed?
    timestamp = Time.now.strftime('%Y-%m-%d-%H:%M:%S').to_s
    screenshot_name = "screenshot-#{scenario.name}-#{timestamp}.png"
    $driver.screenshot("/Users/jessefish/Documents/Failed Automation Screenshots/#{screenshot_name}")
  end

  $driver.driver_quit
end

**Comment by fisharu** [comment]
Also I have tried without UIAutomator2 and I get the same problem.

**Comment by KazuCocoa** [comment]
I've checked the `ruby_lib` code and it's been set zero by default for a long time, e.g. [v9.6.1](https://github.com/appium/ruby_lib/blob/v9.6.1/lib/appium_lib/driver.rb#L460), and set the `implicitWait` with the value in `start_driver` method. [code](https://github.com/appium/ruby_lib/blob/v9.6.1/lib/appium_lib/driver.rb#L719)

If `appium_lib: { wait: 20, debug: false }` is set, I expect the default value is set as `20`. ( Because [test code](https://github.com/appium/ruby_lib/blob/master/ios_tests/lib/ios/specs/driver.rb#L57) works as expected since the configuration has `appium_lib: { wait: 30 }` .)

And according to `[HTTP] --> POST /wd/hub/session/f826c94e-0d81-4a3a-ad05-dbe2f97935b9/timeouts/implicit_wait {"ms":0}`, it looks the client side issue...

hm...

- Could you get the result of `driver_attributes`?
- And could you also tell me the client library version?
    - If you have both it works fine and the error happened helpful for me.

@fisharu thanks.

**Comment by fisharu** [comment]
@KazuCocoa I'm not really sure how to get the result of driver_attributes. Are you referring to the capabilities or something else?

By client library version do you mean the appium version, appium lib version, npm version? I'm not sure what you mean there. As soon as I know how to get you this info I'll have it asap.

**Comment by fisharu** [comment]
Ok, figured out how to get driver_attributes:

{:caps=>#<Selenium::WebDriver::Remote::W3C::Capabilities:0x007fe63c07f6f0 @capabilities={:automationName=>"UiAutomator2", :noSign=>true, :deviceName=>"5554", :platformName=>"Android", :platformVersion=>"7.1.1", :avd=>"Pixel_API_25", :app=>"/Users/jessefish/Documents/Git Repositories/agent_android/CincAgent/app/prod/release/app-prod-release.apk", :appPackage=>"com.commissionsinc.cincagent", :newCommandTimeout=>60, :implicitWait=>60, :appWaitActivity=>"com.commissionsinc.cincagent.controllers.account.LoginActivity", :autoLaunch=>true, :proxy=>nil}>, :automation_name=>:uiautomator2, :custom_url=>false, :export_session=>false, :default_wait=>0, :sauce_username=>nil, :sauce_access_key=>nil, :sauce_endpoint=>"ondemand.saucelabs.com:443/wd/hub", :port=>4723, :device=>:android, :debug=>true, :listener=>nil, :wait_timeout=>30, :wait_interval=>0.5}

**Comment by fisharu** [comment]
So I attempted to inspect my application and did not see the implicit wait be set to 0 in the appium desktop logs. When I tried to run my automation suite through appium desktop it again closed the app before tests began.

Here is the newest logfile from my most recent attempts to get a test to run:
https://gist.github.com/fisharu/7211462d42f853750431958133fe44cf

**Comment by fisharu** [comment]
Upon further experimentation it appears as though this issue only occurs when I attempt to use a cucumber.yml defined profile:
ex: cucumber -p android -t @regression_test

When I do not use a profile the app does not close before tests begin.

**Comment by KazuCocoa** [comment]
thanks!

- client version means `appium_lib` version you've installed with `Gemfile`
- `driver_attributes` is driver method. You can call the method with `@driver.driver_attributes` or `driver_attributes`.
    - http://www.rubydoc.info/github/appium/ruby_lib/master/Appium/Driver#driver_attributes-instance_method


Anyway, could you try the following capability? @fisharu 
I've changed the place of `appium_lib` as http://www.rubydoc.info/github/appium/ruby_lib/master/Appium%2FDriver:start_driver .

```
{ 
  caps: {
    automationName: 'UiAutomator2',
    deviceName: '5554',
    platformName: 'Android',
    platformVersion: '8.0',
    avd: 'Pixel_API_26',
    app: '/Users/jessefish/Documents/Git Repositories/agent_android/CincAgent/app/prod/release/app-prod-release.apk',
    appPackage: 'appname_here',
    newCommandTimeout: 30,
    appActivity: 'appname_here.controllers.SplashActivity'
  },
  appium_lib: {
    wait: 20,
    debug: false
  }
}
```

**Comment by fisharu** [comment]
I tried your method and I'm receiving the same problem. The appium_lib correction did set my implicit wait to the indicated number but the session was still immediately deleted after starting:

[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"a6aadfbf-c7b9-4d83-a0fe-81262221c323","status":0,"value":"Created Session"}
[UiAutomator2] UiAutomator2 did not start the activity we were waiting for, 'com.commissionsinc.cincagent/com.commissionsinc.cincagent.controllers.account.LoginActivity'. Starting it ourselves
[debug] [ADB] Device API level: 26
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/jessefish/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","am","start","-W","-n","com.commissionsinc.cincagent/com.commissionsinc.cincagent.controllers.SplashActivity","-S","-a","android.intent.action.MAIN","-c","android.intent.category.LAUNCHER","-f","0x10200000"]
[debug] [ADB] Waiting up to 20000ms for activity matching pkg: 'com.commissionsinc.cincagent' and activity: 'com.commissionsinc.cincagent.controllers.account.LoginActivity' to be focused
[debug] [ADB] Possible activities, to be checked: 'com.commissionsinc.cincagent.controllers.account.LoginActivity'
[debug] [ADB] Getting focused package and activity
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/jessefish/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","dumpsys","window","windows"]
[debug] [ADB] Found package: 'com.commissionsinc.cincagent' and fully qualified activity name : 'com.commissionsinc.cincagent.controllers.account.LoginActivity'
[Appium] New AndroidUiautomator2Driver session created successfully, session b83f1c38-1cc5-4679-bc9a-f07b08b6b417 added to master session list
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1507123732860 (09:28:52 GMT-0400 (EDT))
[debug] [MJSONWP] Responding to client with driver.createSession() result: {"automationName":"UiAutomator2","noSign":true,"deviceName":"5554","platformName":"Android","platformVersion":"8.0","avd":"Pixel_API_26","app":"/Users/jessefish/Documents/Git Repositories/agent_android/CincAgent/app/prod/release/app-prod-release.apk","appPackage":"com.commissionsinc.cincagent","appWaitActivity":"com.commissionsinc.cincagent.controllers.account.LoginActivity","autoLaunch":true,"appActivity":"com.commissionsinc.cincagent.controllers.SplashActivity"}
[HTTP] <-- POST /wd/hub/session 200 9694 ms - 540 
[HTTP] --> GET /wd/hub/status {}
[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.7.1","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 32 ms - 83 
[HTTP] --> POST /wd/hub/session/b83f1c38-1cc5-4679-bc9a-f07b08b6b417/timeouts/implicit_wait {"ms":30000}
[debug] [MJSONWP] Calling AppiumDriver.implicitWait() with args: [30000,"b83f1c38-1cc5-4679-bc9a-f07b08b6b417"]
[debug] [BaseDriver] Set implicit wait to 30000ms
[debug] [MJSONWP] Responding to client with driver.implicitWait() result: null
[HTTP] <-- POST /wd/hub/session/b83f1c38-1cc5-4679-bc9a-f07b08b6b417/timeouts/implicit_wait 200 4 ms - 76 
[HTTP] --> DELETE /wd/hub/session/b83f1c38-1cc5-4679-bc9a-f07b08b6b417 {}
[debug] [MJSONWP] Calling AppiumDriver.deleteSession() with args: ["b83f1c38-1cc5-4679-bc9a-f07b08b6b417"]
[debug] [BaseDriver] Event 'quitSessionRequested' logged at 1507123732941 (09:28:52 GMT-0400 (EDT))
[Appium] Removing session b83f1c38-1cc5-4679-bc9a-f07b08b6b417 from our master session list
[debug] [UiAutomator2] Deleting UiAutomator2 session
[debug] [UiAutomator2] Deleting UiAutomator2 server session
[debug] [JSONWP Proxy] Proxying [DELETE /] to [DELETE http://localhost:8201/wd/hub/session/a6aadfbf-c7b9-4d83-a0fe-81262221c323] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"a6aadfbf-c7b9-4d83-a0fe-81262221c323\",\"status\":0,\"value\":\"Session deleted\"}"
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/jessefish/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","am","force-stop","com.commissionsinc.cincagent"]
[debug] [Logcat] Stopping logcat capture
[debug] [ADB] Removing forwarded port socket connection: 8201 
[debug] [ADB] Running '/Users/jessefish/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","forward","--remove","tcp:8201"]
[debug] [BaseDriver] Event 'quitSessionFinished' logged at 1507123733325 (09:28:53 GMT-0400 (EDT))
[debug] [MJSONWP] Received response: null
[debug] [MJSONWP] But deleting session, so not returning
[debug] [MJSONWP] Responding to client with driver.deleteSession() result: null

**Comment by fisharu** [comment]
@KazuCocoa thank you so much for all of your help, I realize that this is almost entirely user error on my part. Closing.

Turns out my intern added a bunch of non-working code to our cucumber project and it was skipping the bad tests :-P
