### ISSUE TITLE
Appium 1.7.1 Automation is too slow

### ISSUE THREAD

**Issue by stephenws** [appium/appium#9366]
## The problem

I have updated Appium 1.7.1 from 1.6.4 and I observed that it is running too slow. 
for me it took more than 5 minutes to run Enter Username, Enter Password and click on Login button
It was working fine with proper speed in appium 1.6.4

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable): 1.6.4
* Desktop OS/version used to run Appium: MacOS Sierra 10.12.6
* Node.js version (unless using Appium.app|exe): v6.11.0
* Mobile platform/version under test: iOS 10.0.1
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/stephenws/a8ed795460d329af6fb95fc46c3def6e

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Please report to https://github.com/facebook/WebDriverAgent/issues
