### ISSUE TITLE
Integration of Tapster 2 to Appium

### ISSUE THREAD

**Issue by pylapp** [appium/appium#9367]
## The problem

It was possible to calibrate a Tapster 2 bot and make it tap on iOS apps with Appium 1.4
However with Appium 1.7, there is no code for Tapster ot. I can't run robot-moves from an Appium test case to an iOS app.

## Environment

* Appium version: 1.7
* Last Appium version that did not exhibit the issue (if applicable): 1.4
* Desktop OS/version used to run Appium: macOS Sierra
* Node.js version (unless using Appium.app|exe): 8.6.0 or 7.10.0
* Mobile platform/version under test: iOS 10.3
* Real device or emulator/simulator: iPhone 5C real device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

Arguments like --robot-address or robot-port (and desired capabilities) are not dealed by Appium.
Nothing about the bot in drivers.

## Link to Appium logs

No logs

## Code To Reproduce Issue [ Good To Have ]

No code

**Comment by pylapp** [comment]
Thank you @mykola-mokhnach  for the sorting.
I have create a thread in discuss.appium.io : [https://discuss.appium.io/t/integration-of-tapster-2-to-appium/19010]

**Comment by pylapp** [comment]
Hi folks,

For your information, a fork of the original Tapsterbot project has been made, with plenty of cool clients and fixes to improve the project and drive the robot!

It might be cool to add its integration in the milestones of the Appium project.

For people who want to use the robot, feel free to check at [this GitHub repo](https://github.com/pylapp/tapsterbot).

Cheers

**Comment by mykola-mokhnach** [comment]
We don't have resources that we could dedicate for this task, but it would always be possible to write a dedicated Appium2 driver with Tapster support
