### ISSUE TITLE
Appium 1.7.1 iOS Safari does not recoganize Dom elements

### ISSUE THREAD

**Issue by moibm** [appium/appium#9373]
So seems like if “appium.browserName = Safari” capability is set, the browser opens to the specified url but the dom elements are not recognized via appium/inspector. But if “appium.app=”some app" capability is set, the desired app is opened and the dom elements are recognized. 

Then when safari browser is manually opened from within the simulator, the dom elements are shown.

#Environment
Appium 1.7.1 
iOS 10.3
MacOS 10.12.6
Safari 11

**Comment by spandimu** [comment]
@moibm i hope you are starting your ioswebkitproxy before checking the dom in your device

**Comment by moibm** [comment]
Well I was actually using  "Appium iOS Inspector" to inspect elements during test debug. But after your suggestion, I'll install iosWebKitProxy server and and try to inspect the elements that away. 

Will keep updating as I make progress. 

Thanks for the quick response and suggestion.

**Comment by mykola-mokhnach** [comment]
The inspector is not designed to be used inside webviews. One should use remote debugging to work with safari/webviews and the inspector for the native context.
