### ISSUE TITLE
Failing to send iOS app to the background (v1.7.0)

### ISSUE THREAD

**Issue by jvillacorta** [appium/appium#9375]
## The problem

When sending the app to the background I get a WebDriver Exception (Details in gist)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MacOS Sierra 10.12.6
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: 7.8.0
* Real device or emulator/simulator: iPad Pro (iOS 11.0)
* Appium CLI or Appium.app|exe:

## Details

I am using the python client and the issue occurs when `driver.background_app(3)` is called.

## Code To Reproduce Issue [ Good To Have ]

`driver.background_app(3)`

**Comment by mykola-mokhnach** [comment]
Please report to https://github.com/facebook/WebDriverAgent/issues
