### ISSUE TITLE
iOS 11 displayed value returns false incorrectly for XCUIElementTypeImage 

### ISSUE THREAD

**Issue by rajfidel** [appium/appium#9377]
## The problem

We have an iOS test application.
When installed on a device with iOS 10.x, the displayed value for XCUIElementTypeImage elements is "true" (which is correct)
When installed on a device with iOS 11.0, the displayed value for XCUIElementTypeImage elements is "false" (incorrect)
This issue is only present on **XCUIElementTypeImage** elements.
I can see that the image is visible on the GUI on checking manually in both cases.

Both devices are iPhone 6s (same form factor),
Appium 1.7.0 + Xcode 9 is used in both cases above.
WebdriverAgent was removed and freshly installed on the iPhone in both cases.
There are no overlapping GUI components that overlap with the XCUIElementTypeImage element as per the page source (Not sure if it matters, but checked anyways, just in case)

**Also related question**: Which component of Appium is responsible for querying the "displayed" attribute value? Is it reliable to use "displayed" attribute value verification (at least for simple cases where the element is not part of a scrollable list and always within the current screen bounds)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.0
* Last Appium version that did not exhibit the issue (if applicable): n/a
* Desktop OS/version used to run Appium: mac OS 10.12.6
* Node.js version (unless using Appium.app|exe): 8.5.0
* Mobile platform/version under test: iOS 11.0
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

Got the displayed property and the Page source for the following configurations:

Appium 1.7.0 + iOS 10 + Xcode 9 --> Page source [here](https://gist.github.com/rajfidel/e633c1f7e0801c4dacb4585bcd9e05e7), Appium logs [here](https://gist.github.com/rajfidel/c35aae43d5359859340c10e1cb1e0233)
Appium 1.7.0 + iOS 11 + Xcode 9 --> Page source [here](https://gist.github.com/rajfidel/becbc6b523350be7aa216a1aa7c4cf0d), Appium logs [here](https://gist.github.com/rajfidel/aabe5ecd33434836c278af290b73f3e5).

The XCUIElementTypeImage element of interest is with name 'PairDevice_KeepImage'.
The 'x', 'y', 'width' attribute values are all same for iOS 10.x and 11.0
The displayed value is the only one that is different between 10.x and 11.0.

What am I missing here?

**Comment by mykola-mokhnach** [comment]
Visibility detection has nothing to do with Appium itself. This all is done on WDA side.

**Comment by JaniJegoroff** [comment]
@rajfidel I have seen similar issues with 1.7.0 beta and now even more test cases are failing with 1.7.2 beta. I'm going to stay with 1.6.5 as long as possible as it is working rock solid for me.

**Comment by uterator** [comment]
[WDA #746](https://github.com/facebook/WebDriverAgent/issues/746)
