### ISSUE TITLE
Error: Xcode version 9.0 is not yet supported

### ISSUE THREAD

**Issue by Logakarti** [appium/appium#9378]
## The problem

"Error: Xcode version 9.0 is not yet supported" error occurs while trying to run the app suites in iPhone x (11.0).  Use Xcode version 9

## Environment

* Appium version : 1.6.5
* Desktop OS/version used to run Appium:MAC(Sierra) 10.12.6 
* Mobile platform/version under test: iOS 11.0
* Real device or emulator/simulator: iPhone x (Simulator)

## Link to Appium logs
https://gist.github.com/Logakarti/13e44d297aca8f1868c83f1c56ecc801

## Code To Reproduce Issue [ Good To Have ]

File appdir = new File("/Users/apple/Desktop/ios-3.7.2 Production Build/build/emulator");
        File app = new File(appdir, "CK-12.app");
        DesiredCapabilities capabilities = new DesiredCapabilities();
        //capabilities.setCapability(CapabilityType.BROWSER_NAME, "iOS");
        capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, MobilePlatform.IOS);
        capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "11.0");
        capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone X");
        capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, "XCUITest");
        capabilities.setCapability("safariAllowPopups", true);
        capabilities.setCapability("newCommandTimeout", 120);
        capabilities.setCapability("safariOpenLinksInBackground", true);
        capabilities.setCapability("usePrebuiltWDA", true);
        capabilities.setCapability("useNewWDA", false);
        capabilities.setCapability("webviewConnectRetries", 25);
        capabilities.setCapability("app", app.getAbsolutePath());
        driver = new IOSDriver(new URL("http://127.0.0.1:4729/wd/hub"), capabilities);
        driver.manage().timeouts().implicitlyWait(60, TimeUnit.SECONDS);
        try {
            Thread.sleep(1500);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        return capabilities;
    }

Please anyone help me and how to resolve this issue.

**Comment by mykola-mokhnach** [comment]
You must use Appium 1.7.0+
Closed as duplicate

**Comment by Logakarti** [comment]
How to install appium 1.70? Could you know me and please guide.

**Comment by TuHuynhVan** [comment]
@Logakarti
```npm install appium -g @1.7.1```

**Comment by Logakarti** [comment]
Thanks @TuHuynhVan

**Comment by Logakarti** [comment]
Before install appium 1.7.1, is there any need to uninstall appium 1.6.5v?

**Comment by TuHuynhVan** [comment]
I think you better do that.

**Comment by TuHuynhVan** [comment]
The command was wrong, I was just daydreaming please use ```npm install -g appium@1.7.1```

**Comment by Logakarti** [comment]
Thanks @TuHuynhVan.
