### ISSUE TITLE
 Error: simctl error running 'install': An error was encountered processing the command (domain=IXErrorDomain, code=3):

### ISSUE THREAD

**Issue by Logakarti** [appium/appium#9379]
## The problem

 Error: simctl error running 'install': An error was encountered processing the command (domain=IXErrorDomain, code=3) error gets while running the app in iPhone X(11.0) after upgrade appium 1.7.1

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Desktop OS/version used to run Appium: MAC(Sierra)
* Mobile platform/version under test: iOS 11
* Real device or emulator/simulator: iPhone X

## Link to Appium logs

https://gist.github.com/Logakarti/cf82d48abae4e47d889737f9acf4637c

## Code To Reproduce Issue [ Good To Have ]
File appdir = new File("/Users/apple/Desktop/ios-3.7.2 Production Build/build/emulator");
        File app = new File(appdir, "CK-12.app");
        DesiredCapabilities capabilities = new DesiredCapabilities();
        //capabilities.setCapability(CapabilityType.BROWSER_NAME, "iOS");
        capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, MobilePlatform.IOS);
        capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "11.0");
        capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone X");
        capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, "XCUITest");
        capabilities.setCapability("safariAllowPopups", true);
        capabilities.setCapability("newCommandTimeout", 120);
        capabilities.setCapability("safariOpenLinksInBackground", true);
        capabilities.setCapability("usePrebuiltWDA", true);
        capabilities.setCapability("useNewWDA", false);
        capabilities.setCapability("webviewConnectRetries", 25);
        capabilities.setCapability("app", app.getAbsolutePath());
        driver = new IOSDriver(new URL("http://127.0.0.1:4729/wd/hub"), capabilities);
        driver.manage().timeouts().implicitlyWait(60, TimeUnit.SECONDS);
        try {
            Thread.sleep(1500);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        return capabilities;
    }

Please, anyone guide me to resolve the issue.

**Comment by mykola-mokhnach** [comment]
Do you get the same error if you try to install the app manually from command line on this simulator?

**Comment by Logakarti** [comment]
No, I'm not getting this error while installing the app manually in the simulator.

**Comment by mykola-mokhnach** [comment]
Try another simulator/another machine.

**Comment by vighneshpai-yml** [comment]
If i drag and drop the app to simulator it works fine. But, via appium it's throwing me this error.

**Comment by ManojKarthick1992** [comment]
Even I was facing this issue ,unable to install the app through appium or install command.but I was able to install the app by drag and drop.

@Logakarti,@vighneshpai-yml,whether the issue resolved for you guys. Need help in advance.

**Comment by ios-onix-systems** [comment]
After update Mac OS on version 10.13.4 
I have this problem
simctl error running 'install': An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2)

**Comment by ZlenkoValeriy** [comment]
After update Mac OS on version 10.13.4 
I see this problem
simctl error running 'install': An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2)

**Comment by BoazWarshawsky** [comment]
Hi @ZlenkoValeriy @mykola-mokhnach 
I started getting this error when running from CI.
It seems that the problem happens when Appium tries to install new app on top of valid one.

I have 10 tests in CI and only from the 2nd run I started seeing the issue.


Please advice, how did you solve it?

**Comment by ndeztea** [comment]
I have same issue @BoazWarshawsky after latest version appium is not working perfectly on CI (Android and IOS).. I hope someone can check this.

**Comment by ArathiSawai** [comment]
im getting below error unable to initiate the instance in latest Appium 
An unknown server-side error occurred while processing the command. Original error: simctl error running 'install': An error was encountered processing the command (domain=IXErrorDomain, code=5):

**Comment by cm-informatics** [comment]
I had the same issue. Just closing the iOS Simulator, and run my test script via Eclipse again worked for me. I could also start a session via appium desktop.
