### ISSUE TITLE
execute webdriverio appium test with node

### ISSUE THREAD

**Issue by malutanpetronel** [appium/appium#9380]
## The problem

I did installed appium and appium-doctor and webdriverio ! everything shows correctly 

## Environment

I am in the Android folder which is opened into Android Studio and I want to run the test created in a subfolder.

Appium is running but I have no clue how to 

execute webdriverio appium test with node !!!

Please help me

**Comment by malutanpetronel** [comment]
I should mention everything installed with npm install ?

**Comment by mykola-mokhnach** [comment]
Please use [Appium forum](http://forum.appium.io) to ask questions. We also have [sample code](https://github.com/appium/sample-code) repository.

**Comment by malutanpetronel** [comment]
http://forum.appium.io/ link you provided above is not opening and sample code does not explain either how to launch from comand prompt a single test inside a project so please be nice and provide me a single command line to start it ;) Thank you

**Comment by imurchie** [comment]
The forums are here: https://discuss.appium.io/

Webdriver.io has docs on getting started with that particular library: http://webdriver.io/guide.html
