### ISSUE TITLE
Windows driver doesn't find elements on Chrome window

### ISSUE THREAD

**Issue by iravasylyk** [appium/appium#9381]
Description

inspect.exe parsing elements on native Chrome elements on Desctop (url field, buttons, menu, toolbar)
browser is starting, but failing with exception element wasn't found
DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability("app", "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe");
driver = new WindowsDriver(new URL("http://127.0.0.1:4723"), capabilities);
driver .manage().timeouts().implicitlyWait(2, TimeUnit.SECONDS);
driver .findElementByName("Reload").click();

https://drive.google.com/open?id=0B-2ZhNxhgOzFOXFYZ0xid1Y5Snc screenshots

Environment

java client build version or git revision if you use some shapshot: 1.8
Appium server version or git revision if you use some shapshot:
Desktop OS/version used to run Appium if necessary: 10
Real device or emulator/simulator:desctop

**Comment by mykola-mokhnach** [comment]
Please attach full server log and an example of client code, that fails.

**Comment by iravasylyk** [comment]
log is on screenshot, no other information it doesn't show

**Comment by dpgraham** [comment]
Can you provide the logs as a gist instead of a screenshot? Also try calling driver.source before find element to inspect the source xml.

**Comment by iravasylyk** [comment]
Windows Application Driver listening for requests at: http://127.0.0.1:4723/
Press ENTER to exit.


==========================================
POST /session HTTP/1.1
Accept-Encoding: gzip,deflate
Connection: Keep-Alive
Content-Length: 318
Content-Type: application/json; charset=utf-8
Host: 127.0.0.1:4723
User-Agent: Apache-HttpClient/4.5.2 (Java/1.8.0_144)

{"capabilities":[{"desiredCapabilities":{"app":"C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe","platformName":"Windows"}},{"requiredCapabilities":{}}],"desiredCapabilities":{"app":"C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe","platformName":"Windows"},"requiredCapabilities":{}}
HTTP/1.1 200 OK
Content-Length: 171
Content-Type: application/json

{"sessionId":"DD74A241-9282-4E23-ABA8-C76873C27E40","status":0,"value":{"app":"C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe","platformName":"Windows"}}


==========================================
GET /session/DD74A241-9282-4E23-ABA8-C76873C27E40 HTTP/1.1
Accept-Encoding: gzip,deflate
Cache-Control: no-cache
Connection: Keep-Alive
Host: 127.0.0.1:4723
User-Agent: Apache-HttpClient/4.5.2 (Java/1.8.0_144)


HTTP/1.1 200 OK
Content-Length: 171
Content-Type: application/json

{"sessionId":"DD74A241-9282-4E23-ABA8-C76873C27E40","status":0,"value":{"app":"C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe","platformName":"Windows"}}


==========================================
GET /session/DD74A241-9282-4E23-ABA8-C76873C27E40 HTTP/1.1
Accept-Encoding: gzip,deflate
Cache-Control: no-cache
Connection: Keep-Alive
Host: 127.0.0.1:4723
User-Agent: Apache-HttpClient/4.5.2 (Java/1.8.0_144)


HTTP/1.1 200 OK
Content-Length: 171
Content-Type: application/json

{"sessionId":"DD74A241-9282-4E23-ABA8-C76873C27E40","status":0,"value":{"app":"C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe","platformName":"Windows"}}

==========================================
POST /session/DD74A241-9282-4E23-ABA8-C76873C27E40/timeouts HTTP/1.1
Accept-Encoding: gzip,deflate
Connection: Keep-Alive
Content-Length: 29
Content-Type: application/json; charset=utf-8
Host: 127.0.0.1:4723
User-Agent: Apache-HttpClient/4.5.2 (Java/1.8.0_144)



HTTP/1.1 200 OK
Content-Length: 63
Content-Type: application/json

{"sessionId":"DD74A241-9282-4E23-ABA8-C76873C27E40","status":0}


==========================================
POST /session/DD74A241-9282-4E23-ABA8-C76873C27E40/element HTTP/1.1
Accept-Encoding: gzip,deflate
Connection: Keep-Alive
Content-Length: 33
Content-Type: application/json; charset=utf-8
Host: 127.0.0.1:4723
User-Agent: Apache-HttpClient/4.5.2 (Java/1.8.0_144)


HTTP/1.1 404 Not Found
Content-Length: 139
Content-Type: application/json

{"status":7,"value":{"error":"no such element","message":"An element could not be located on the page using the given search parameters."}}

**Comment by iravasylyk** [comment]
please share more details for driver.source
