### ISSUE TITLE
TouchAction.tap with a count greater than 2 does not work on iOS

### ISSUE THREAD

**Issue by dkdodson3** [appium/appium#9384]
## TouchAction.tap with a count greater than 2 works on android but not iOS.

I need to quickly tap on a specific element to enable a special setting. With Android, using TouchAction.tap with a count of 10 works great, but it does not do anything on iOS. I end up having to do a for loop and tap as quckly as it will let me, which with some devices it is not quick enough.

## appium-xcuitest-driver
* Versions: appium@1.7.0-beta, appium-xcuitest-driver@2.51.1
* OSX
* Node.js version - v8.5.0
* iOS
* Real Device

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/dkdodson3/107ec8a9dfcfe0cda0f1f38306015fec

## Code To Reproduce Issue
self.touch_action.tap(element=element, x=1, y=1, count=10).perform()

I have tried to tap on the middle of the element as well.
size = element.rect
offset_x = size['width'] / 2
offset_y = size['height'] / 2

a tap with the count of 2 does a double tap just fine

**Comment by mykola-mokhnach** [comment]
There is no other way except of doing the stuff in a loop. However, you can improve single tap performance by providing _tapWithShortPressDuration_ capability. Or just invoike [mobile: touchAndHold](https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios-xctest-mobile-gestures.md) endpoint with short duration argument in the loop.

**Comment by dkdodson3** [comment]
So is this a bug with WebDriverAgent?

**Comment by mykola-mokhnach** [comment]
I wouldn't say it is a bug, but rather known limitation.

**Comment by dkdodson3** [comment]
I will try tapWithShortPressDuration.

That option should be added to the capabilities in: https://github.com/appium/appium-xcuitest-driver#desired-capabilities
