### ISSUE TITLE
Click command that trigger the alert is timed out on iOS9.3+ safari

### ISSUE THREAD

**Issue by asano-shinichi** [appium/appium#9385]
## The problem
When I tried to get text from alert on safari, I could get on iOS9.2 with XCode7.3.1 but I couldn't on iOS10.3 with XCode8.3.2.
I'm using php-client fot test.

## Environment

* Appium version: both 1.6.5 and 1.7.1
* Desktop OS/version used to run Appium: Mac OSX 10.12.5
* Node.js version: both 6.9.5 and 8.6.0
* Mobile platform/version under test: iOS9.3, iOS10.3
* Real device or emulator/simulator: both
* Appium CLI or Appium.app|exe: CLI

## Details

I thought it's same as #8582 but my problem is before the alert.
Time out is occured after click, so I can't use alert related methods.

Here is log of phpunit.
```
PHPUnit_Extensions_Selenium2TestCase_NoSeleniumException: Error connection[28] to http://localhost:4723/wd/hub/session/97c8615c-e82c-4400-b768-d943fe291b36/element/5676/click: Operation timedout after 60004 milliseconds with 0 bytes received

/mypath/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Driver.php:123
/mypath/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Driver.php:175
/mypath/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/CommandsHolder.php:100
/mypath/tests/FormTest.php:696
/mypath/tests/FormTest.php:696
/mypath/tests/FormTest.php:82
/mypath/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:348
/mypath/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:314
```

## Link to Appium logs

Here is appium log. `5676/click` is timed out.
```
[HTTP] --> POST /wd/hub/session/97c8615c-e82c-4400-b768-d943fe291b36/element/5669/click {}
[HTTP] <-- POST /wd/hub/session/97c8615c-e82c-4400-b768-d943fe291b36/element/5669/click 200 100 ms - 76
[HTTP] --> POST /wd/hub/session/97c8615c-e82c-4400-b768-d943fe291b36/element/5676/click {}
[HTTP] <-- POST /wd/hub/session/97c8615c-e82c-4400-b768-d943fe291b36/element/5676/click - - ms - -
```

## Code To Reproduce Issue [ Good To Have ]

Just click() the button on web page to get alert() by JavaScript.

```php
$button->click(); // -> timed out
$this->assertStringMatchesFormat('error on phone number.', $this->alertText());
$this->acceptAlert();
```

**Comment by mykola-mokhnach** [comment]
Please attach full server log

**Comment by asano-shinichi** [comment]
full log is below.
https://gist.github.com/asano-shinichi/b37b04b6d9db3cff9a93f1849b921406

**Comment by asano-shinichi** [comment]
I think it's similar to #9405.

**Comment by asano-shinichi** [comment]
Same thing occurs in the environment below.
- Appium version: 1.7.1
- Desktop OS/version used to run Appium: Mac OSX 10.12.6
- Node.js version: 8.6.0
- Mobile platform/version under test: **iOS11.0 (XCode9.0)**
- Real device or emulator/simulator: both
- Appium CLI or Appium.app|exe: CLI

**Comment by mykola-mokhnach** [comment]
Closed as duplicate
