### ISSUE TITLE
Cannot find xcodebuild's process id when launching appium ruby console

### ISSUE THREAD

**Issue by nairouz12** [appium/appium#9389]
## The problem

When I try to launch appium ruby console to check the elements of my screen, arc exists and it does not give me the hand to launch command "page" to see my elements.

## Environment

Appium 1.7.1
node: 6.11.4
npm: 5.4.2
appium_console: 2.5.0
appium_lib: 9.7.1

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
https://gist.github.com/nairouz12/0e0a5be5f0bcfea97c07ce2f7314f2eb

**Comment by mykola-mokhnach** [comment]
I don't see any issues in the attached log.

**Comment by nairouz12** [comment]
what about this:

`[debug] [XCUITest] Cannot find xcodebuild's process id, so unable to retrieve DerivedData folder path
[XCUITest] No WebDriverAgent derived data available, so unable to set permissions on WDA attachments folder
[debug] [BaseDriver] Event 'wdaPermsAdjusted' logged at 1507207953870 (14:52:33 GMT+0200 (CEST))
[debug] [XCUITest] 'pgrep -nif xcodebuild.*AA203E59-1EA7-487E-A5BF-F3DCE5B7C7F8' didn't detect any matching processes. Return code: 1
[debug] [XCUITest] Cannot find xcodebuild's process id, so unable to retrieve DerivedData folder path
[XCUITest] No WebDriverAgent derived data available, so unable to mark system files for cleanup`

**Comment by nairouz12** [comment]
@mykola-mokhnach 
issue happens when I have two simulators.
How can I avoid those kind of issues?

**Comment by KazuCocoa** [comment]
Sorry for my late reply.
Yes, the `ruby_console` use global scope driver. It means we can't manage multiple sessions in one process.

Would you like to manage multiple sessions from one shell?
What about launching `ruby_console` from different shells?

**Comment by KazuCocoa** [comment]
^ @nairouz12

**Comment by nairouz12** [comment]
I avoided the issue by making sure that I have only one simulator running on a time

**Comment by KazuCocoa** [comment]
thanks!
I've created an issue for this https://github.com/appium/ruby_console/issues/84 and close this.
