### ISSUE TITLE
forward --list adbExec fails

### ISSUE THREAD

**Issue by saikrishna321** [appium/appium#9392]
## The problem

Not able to run chrome browser tests on Android and this happens often on the CI, not always 

/Users/rakeshda/Library/Android/sdk/platform-tools/adb -P 5037 -s ce0916099b5b902802 forward --list' exited with code 1'; Stderr: 'error: protocol fault (couldn't read status message): Undefined error: 0'; Code: '1'

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: 
* Node.js version (unless using Appium.app|exe): 7.X
* Mobile platform/version under test:Android
* Real device or emulator/simulator:Real Device
* Appium CLI or Appium.app|exe:CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/saikrishna321/cabac1b462c6a8ea835f34af3b2f734e

**Comment by mykola-mokhnach** [comment]
Make sure you have the most recent version of developer tools installed

**Comment by saikrishna321** [comment]
let me update n give it a try

**Comment by imurchie** [comment]
This should not cause an error anymore, after https://github.com/appium/appium-chromedriver/commit/7d1d853b5363f90d658e39e2585f44f525c4df60
