### ISSUE TITLE
How to view chromedriver log?

### ISSUE THREAD

**Issue by xuanzhaopeng** [appium/appium#9396]
## The problem

To run mobile web test on android, the appium-android will start chromedriver with several args, https://github.com/appium/appium-android-driver/blob/56ebbb256d22b8aad3384fd0b7156060dca159ea/lib/commands/context.js#L210 

Appium-android will use verbose for the log for stating chromedriver, but however I cannot see the chromedriver's log from Appium server log. 

The question is how could we log/view the chromedriver log? Thanks

Or maybe should we add default chromedriver log path?

## Environment

Appium 1.6.5

**Comment by imurchie** [comment]
The latest version (unfortunately not Appium 1.6.5) has the desired capability `showChromedriverLog` which, when set to `true`, will bring the CD logs into the Appium logs.

**Comment by xuanzhaopeng** [comment]
Cool works for me! Thanks @imurchie  I just add this showChromedriverLog into default-capabilities in server side : https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/default-capabilities-arg.md
