### ISSUE TITLE
Verify new documentation site

### ISSUE THREAD

**Issue by dpgraham** [appium/appium#9400]
We are planning on launching a new https://appium.io/docs site that uses MkDocs instead of Slate and has a different style.

The big change, content-wise, is that recently @imurchie and myself made several pull requests into the main Appium repo that added documentation for all of the different (M)JSONWP commands. It lists things like: description, code samples, client support, driver support, http specs.

Before we go live with on appium.io, I'd like to have members of the community looks over the site and look for any errors/mistakes (especially under `commands` because all of that is new) or any style/css problems.

I've forked and hosted the site at my own personal GitHub pages repository, https://dpgraham.github.io/docs/en/about-appium/intro/ for you to look at before we migrate it over to https://appium.io

If you find any issues, or have any questions/comments, feel free to either:
* open an issue and paste a link to this issue
* comment on this ticket
* comment on the Slack channel (appium.slack.com)
* make a pull request (just remember, when making a PR for commands, edit the .yml file, not the .md file)

(cc: @SrinivasanTarget @vmaxim @KazuCocoa @mykola-mokhnach @TikhomirovSergey @imurchie @jlipps)

**Comment by mykola-mokhnach** [comment]
I'd prefer to have a separate bugtracker for the site to properly track each issue. By posting all the issue here we may create a big mess.

**Comment by mykola-mokhnach** [comment]
<img width="1197" alt="top_bar" src="https://user-images.githubusercontent.com/7767781/31306095-fac18b1c-ab48-11e7-9c03-fbeafb971e7b.png">

The top bar partially covers the content on Safari 11.0 (Firefox is on the left side of the screenshot)

**Comment by mykola-mokhnach** [comment]
It is not possible to scroll long menus if the desktop screen is too small to fit them:

<img width="452" alt="no_scroll" src="https://user-images.githubusercontent.com/7767781/31306111-52217d04-ab49-11e7-831f-e872ea3997d1.png">

**Comment by SrinivasanTarget** [comment]
<img width="664" alt="screen shot 2017-10-09 at 9 30 03 pm" src="https://user-images.githubusercontent.com/8896549/31347180-1882c34a-ad39-11e7-90c0-d9d4b7ebeeb3.png">

UIAutomation(IOS) - Duplicated

**Comment by imurchie** [comment]
If we want to keep this separate from the main issue tracker, issues can be opened on the appium.io repo at https://github.com/appium/appium.io/issues

**Comment by mykola-mokhnach** [comment]
I'd rather split drivers by supported  platform names/versions in the Drivers menu, like 
iOS -> UIAutomation (9.3 and older), XCUITest (9.3 and newer)
Android -> Selendroid (2.3 and newer), UIAutomation (4.0 and newer), UIAutomation2 (5.0 and newer)
etc...

**Comment by saikrishna321** [comment]
@dpgraham alignment issue 
<img width="906" alt="screen shot 2017-10-11 at 2 33 18 pm" src="https://user-images.githubusercontent.com/4045041/31431319-f3b76e0e-ae90-11e7-84c6-4e6812320676.png">

**Comment by imurchie** [comment]
@saikrishna321 What browser/architecture are you on? This is not universal (e.g., MacOS 10.12.6/Chrome doesn't do this).

**Comment by dpgraham** [comment]
Strikethrough not working:

![screen shot 2017-10-11 at 10 00 13 am](https://user-images.githubusercontent.com/852574/31454685-11ca0a80-ae6b-11e7-9d7c-6a9363088c7c.png)

**Comment by saikrishna321** [comment]
@imurchie i'm on MacOSX 10.12.6/chrome Version 61.0.3163.100

**Comment by kool79** [comment]
https://dpgraham.github.io/docs/en/advanced-concepts/grid/
Note about configuration file  for selenium grid:
  Starting from grid v3 (I'm not sure about exact version) they changed time unit for `timeout`, `browserTimeout` in json file from `msec` to `sec`. There are no public announcement about this. Also I dont know if they are going to change this back.
  Also please add note that you support  both v2.x and v.3.x json file format.
