### ISSUE TITLE
Cannot navigate to URl on iOS 10 real device

### ISSUE THREAD

**Issue by DewanshuAwasthi** [appium/appium#9401]
## The problem
 am trying to run test which has to render a page through URL in IOS app. But not able to set switch context to web view . can some one help ?
Also , I observed Safari application should be running in background to get any webView by appium after launching app. Is it mendate?
I feel i am misunderstanding the flow.

Can somebody please help  me ?

## Environment

* Appium version :1.6.5
* Desktop OS/version used to run Appium: IOS 10.3
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Iphone 7
* Real device or emulator/simulator: Real

## Details

Capabilities:
[Appium]   automationName: 'XCUITest'
[Appium]   useNewWDA: true
[Appium]   networkConnectionEnabled: true
[Appium]   xcodeConfigFile: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Configurations/ProjectSettings.xcconfig'
[Appium]   platformName: 'iOS'
[Appium]   deviceName: 'testDevice'
[Appium]   udid: 'bd658c58e71493fe919c043562f9b17e460bfee9'
[Appium]   fullReset: true

## Link to Appium logs

[Appium Logs](https://gist.github.com/DewanshuAwasthi/e50525d292ae32e0d50304985daf0db9) 

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
The log shows, that switching to web view context was successful, but the server has failed to execute getUrl command.

**Comment by MAHAJAN-SAHIL** [comment]
Even I want to know the solution for this. I am facing the same issue, where switching from native to Webview fails. It successfully opens the home page of the app, but while opening a URL switching to webview is required which fails. Surprisingly, It works fine if we manually launch the safari app while the test is in progress and putting the test on sleep where i perform manual safari launch.

**Comment by MaxDomash** [comment]
Facing the same issue. Simulators works fine. Appium able to udentify WebView on real device only if I manually launch device Safari before script run.

**Comment by MaxDomash** [comment]
Also having issue when try to find element after switching to webView.
iPhone 7 iOS 10.3.3
Appium 1.7.1

Appium logs:

[debug] [XCUITest] Executing command 'getCurrentContext'
[debug] [MJSONWP] Responding to client with driver.getCurrentContext() result: "NATIVE_APP"
[HTTP] <-- GET /wd/hub/session/be94e92c-e099-430f-928c-408463593e5d/context 200 2 ms - 84 
[HTTP] --> POST /wd/hub/session/be94e92c-e099-430f-928c-408463593e5d/context {"name":"WEBVIEW_2"}
[debug] [MJSONWP] Calling AppiumDriver.setContext() with args: ["WEBVIEW_2","be94e92c-e099-430f-928c-408463593e5d"]
[debug] [XCUITest] Executing command 'setContext'
[debug] [iOS] Attempting to set context to 'WEBVIEW_2'
[debug] [RemoteDebugger] WebKit debugger web socket connected to url: ws://localhost:27753/devtools/page/2
[debug] [MJSONWP] Responding to client with driver.setContext() result: null
[HTTP] <-- POST /wd/hub/session/be94e92c-e099-430f-928c-408463593e5d/context 200 16 ms - 76 
[HTTP] --> POST /wd/hub/session/be94e92c-e099-430f-928c-408463593e5d/timeouts {"type":"implicit","ms":0}
[debug] [MJSONWP] Calling AppiumDriver.timeouts() with args: ["implicit",0,"be94e92c-e099-430f-928c-408463593e5d"]
[debug] [XCUITest] Executing command 'timeouts'
[debug] [BaseDriver] Set implicit wait to 0ms
[debug] [MJSONWP] Responding to client with driver.timeouts() result: null
[HTTP] <-- POST /wd/hub/session/be94e92c-e099-430f-928c-408463593e5d/timeouts 200 2 ms - 76 
[HTTP] --> GET /wd/hub/session/be94e92c-e099-430f-928c-408463593e5d/context {}
[debug] [MJSONWP] Calling AppiumDriver.getCurrentContext() with args: ["be94e92c-e099-430f-928c-408463593e5d"]
[debug] [XCUITest] Executing command 'getCurrentContext'
[debug] [MJSONWP] Responding to client with driver.getCurrentContext() result: "WEBVIEW_2"
[HTTP] <-- GET /wd/hub/session/be94e92c-e099-430f-928c-408463593e5d/context 200 2 ms - 83 
[HTTP] --> POST /wd/hub/session/be94e92c-e099-430f-928c-408463593e5d/elements {"using":"xpath","value":"//input[@id='ap_password']"}
[debug] [MJSONWP] Calling AppiumDriver.findElements() with args: ["xpath","//input[@id='ap_password']","be94e92c-e099-430f-928c-408463593e5d"]
[debug] [XCUITest] Executing command 'findElements'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [RemoteDebugger] Executing 'find_elements' atom in default context
[debug] [RemoteDebugger] Sending javascript command (function(){return function(){var k=this;functi...
[debug] [RemoteDebugger] Sending WebKit data: {"method":"Runtime.evaluate","params":{"objectGroup":"console","includeCommandLineAPI":true,"doNotPauseOnExceptionsAndMuteConsole":true,"expression":"(function(){return function(){var k=this;functi...
[debug] [RemoteDebugger] Webkit response timeout: 70000
[debug] [XCUITest] Connection to WDA timed out
[debug] [iProxy] recv failed: Operation not permitted
[MJSONWP] Encountered internal error running command: Error: Error while executing atom: operation timed out
    at XCUITestDriver.callee$0$0$ (../../../lib/commands/web.js:199:11)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)

**Comment by MaxDomash** [comment]
Any update on it? Very need the fix, please help.

**Comment by DewanshuAwasthi** [comment]
Still not able to resolve the issue. Waiting for the solution badly. 
though we unblocked ourself by running at remote location. but that gives pain :(

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
