### ISSUE TITLE
sendKeys() command enters text in wrong text field

### ISSUE THREAD

**Issue by KrazySush** [appium/appium#9403]
## The problem

I am working on hybrid app automation project. My issue is that, on iOS devices, sendKeys() command enters value in wrong text field present on the same screen. Most probably it enters value in the text field which is displayed just above the keyboard(when keyboard is invoked by clicking intended text field). My scripts were working fine till iOS 10.3.3 using appium 1.6.5, Xcode 8.3.3. 
Can anybody help me out of this ?

## Environment

* Appium version (or git revision) that exhibits the issue: Appium 1.7.0, 1.7.1
* Last Appium version that did not exhibit the issue (if applicable): Appium 1.6.5
* Desktop OS/version used to run Appium: Mac OS 10.13
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS 10, 11
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

**Comment by KrazySush** [comment]
@imurchie, @SrinivasanTarget,
Any idea to tackle the issue?

**Comment by mykola-mokhnach** [comment]
Please attach a screenshot and the output of getPageSource command

**Comment by KrazySush** [comment]
@mykola-mokhnach,
Actually I am working on banking application. So due to restrictions, I can not share the screenshot or getPageSource output.
Sorry for it.
What should I do now?

**Comment by KrazySush** [comment]
@mykola-mokhnach,
I was monitoring execution activity and got to know that, when keyboard is invoked from the bottom (after tap on text field), it causes to scroll up the screen(which is not expected).
hence it is entering text in below text field.

**Comment by mykola-mokhnach** [comment]
Then it's very old mobile WebKit bug %/

You can try to hide the keyboard to workaround it.

**Comment by KrazySush** [comment]
@mykola-mokhnach,
But why to hide the keyboard? Because I want to enter text to text field using keyboard only.

**Comment by mykola-mokhnach** [comment]
The other option is to report the bug to Apple and wait until it's fixed
