### ISSUE TITLE
Question: Android custom view not visible and not automate-able in Appium inspector/UIAutomator. Is there any official documentation explaining this?

### ISSUE THREAD

**Issue by qual** [appium/appium#9404]
## The problem
I have Android application (Binary not source code) which has several custom views. I am trying to automate this app using Appium. It looks like some of the controls/views are displayed on UI but not able to locate them in hierarchy in Appium inspector and UIAutomatorViewer. I have read that this has to do something with Android's Accessibility.

What could be the possible solution for this. Does app developer need to make any code change to make custom views visible automate-able ? I was wondering whether there is **any official documentation** by Appium/Google which can explain the limitations of UIAutomator for custom views. 

## Environment
* Appium Desktop 1.2.3 (Appium server 1.7), UIAutomator

**Comment by qual** [comment]
@imurchie @jlipps: Could you throw some light on this ? Thanks!

**Comment by JaniJegoroff** [comment]
Google is your friend: https://developer.android.com/guide/topics/ui/accessibility/custom-views.html

**Comment by mykola-mokhnach** [comment]
Try to set _ignoreUnimportantViews_ capability to false
