### ISSUE TITLE
Clicking an Element that results in Javascript alert causes the webdriver to hang

### ISSUE THREAD

**Issue by richlanc** [appium/appium#9405]
## The problem
Clicking an Element that results in Javascript alert causes the webdriver to hang. 

You can see in the example below, Chrome+Selenium immediately continues after clicking the said element, whereas Appium hangs until the script eventually times out. 

## Environment

* Appium version: 1.7.1
* Last Appium version that did not exhibit the issue: N/A
* Desktop OS/version: OSX 10.13
* Node.js version: v8.5.0
* Mobile platform/version under test: iOS 11
* Real device or emulator/simulator: iOS Simulator (Xcode version 9.0)
* Appium CLI or Appium.app|exe: CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
https://gist.github.com/richlanc/822a684271c5e9dbf9eed41ef43a3082

## Code To Reproduce Issue [ Good To Have ]
```python
import sys
import time

from appium import webdriver
from selenium import webdriver as swebdriver


if __name__ == "__main__":
    if "chrome" in sys.argv:
        driver = swebdriver.Chrome("<< Path to ChromeDriver >>")

    else:
        capabilities = {
            "automationName": "XCUITest",
            "browserName": "Safari",
            "deviceName": "iPhone2017-B",
            "platformName": "iOS",
            "platformVersion": "11.0",
            "newCommandTimeout": 0
        }

        driver = webdriver.Remote(
            "http://localhost:4723/wd/hub", capabilities
        )
    driver.get("https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_confirm")
    driver.switch_to.frame("iframeResult")

    beforeTime = time.time()
    print("Clicking button, currentTime: %s" % beforeTime)
    element = driver.find_element_by_xpath("//button")
    element.click()
    print("Waited %s seconds" % (time.time() - beforeTime))
```

## Example Output:
Linux + Selenium + Chrome, no hanging:
```
+(svMonitorInjectorV2_2016-12-21_10-08-32-008887)0 ✓ richard@starbug ~ $ python /tmp/appium_ios_alert_bug.py chrome
Clicking button, currentTime: 1507539451.53
Waited 0.105967998505 seconds
+(svMonitorInjectorV2_2016-12-21_10-08-32-008887)0 ✓ richard@starbug ~ $ 
```

OSX + iOS11 Simulator, hanging:
```
(svMonitorInjectorV2_2017-09-14_15-56-17-525067)pinhead:~ scivisum$ gtimeout --foreground  150 python /tmp/appium_ios_alert_bug.py 
Clicking button, currentTime: 1507541168.47
(svMonitorInjectorV2_2017-09-14_15-56-17-525067)pinhead:~ scivisum$ echo $?
124 # means it was a timeout
(svMonitorInjectorV2_2017-09-14_15-56-17-525067)pinhead:~ scivisum$ 
```

**Comment by mykola-mokhnach** [comment]
@imurchie FYI

**Comment by mykola-mokhnach** [comment]
This might work in recent releases if the alert is accepted from native context

**Comment by deividfortuna** [comment]
Hi,
I know that the issue was closed by duplication but I looked into the related issues and none had a solution for this issue. I'm having the same issue, some how the WebDriver is hang after a javascript confirmation dialog is shown.

I have tried before several solution mention in other issues and forums like `driver.switchTo.alert().accept();` but that code seems to be never executed and eventually the script times out.

**Environment:**
Appium version: Appium v1.16.0
Last Appium version that did not exhibit the issue: N/A
Desktop OS/version: OSX 10.15.3
Node.js version: v12.8.1
Mobile platform/version under test: iOS 13.3
Real device or emulator/simulator: Real device

**Comment by mykola-mokhnach** [comment]
Try to accept the alert being in native context rather than in web context

**Comment by deividfortuna** [comment]
Thanks for reply @mykola-mokhnach. But after I click this button that have an alert to confirm the action, none of the follow lines are being executed like for example changing the context to native 😞

**Comment by imurchie** [comment]
@deividfortuna Can you post the Appium server logs, as a link to a [gist](https://gist.github.com)? This all works perfectly well for me.

A minimal reproducing example would be useful, too. Thanks!
