### ISSUE TITLE
Unable to launch WebDriverAgent because of xcodebuild failure: "Command 'Scripts/bootstrap.sh -d' exited with code 1"

### ISSUE THREAD

**Issue by sagarsheth27** [appium/appium#9406]
Settled up everything still this kind of error occurred. Bootstrap dependancies added through Root user. 

dc.setCapability("automationName", "XCUITest");
        dc.setCapability("reportDirectory", reportDirectory);
        dc.setCapability("reportFormat", reportFormat);
        dc.setCapability("testName", testName);
        dc.setCapability("deviceName","Qa");
        dc.setCapability("platformName", "ios");
        dc.setCapability("version","9.3.1");

**Comment by TuHuynhVan** [comment]
@sagarsheth27 
Seems duplicates with https://github.com/appium/appium/issues/9344

**Comment by mykola-mokhnach** [comment]
Closing as duplicate. Please look through existing issues history.
