### ISSUE TITLE
Using application with WKWebView elements are missing from PageSource

### ISSUE THREAD

**Issue by NagyRobertt** [appium/appium#9408]
## The problem

Using application with WKWebView elements are missing from PageSource.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Desktop OS/version used to run Appium: Sierra 10.12.6
* Node.js version (unless using Appium.app|exe): 6.9.1
* Mobile platform/version under test: iOS 11.0.2
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: cli

## Details

We just recently started to support WKWebView and when i started the application with appium the page source got truncated and elements are not visible.
Before we were using UIWebview.

Attached screenshots of Inspector:
![wkwebview](https://user-images.githubusercontent.com/22910131/31343085-e9fb181c-ad0e-11e7-88f8-54e1f0370349.png)
![uiwebview](https://user-images.githubusercontent.com/22910131/31343090-ee6b9804-ad0e-11e7-994b-8bc96243d605.png)

## Link to Appium logs

In the log there were no errors visible. It says it got the page source. Simply the end result is incomplete.

Regards,
Robert

**Comment by mykola-mokhnach** [comment]
Appium desktop won't show webview content in scope of native context. You need to use the standard Apple's remote debugger feature to debug such views.

**Comment by NagyRobertt** [comment]
Okay thank you.

Although i would like to clarify something. When i downloaded xcode 8 and plugged in a ios 10 device. The page source showed every element fine using either WKWebview or UiWebView. When i use xcode 9 and ios 11 i can only get the elements using page source with UiWebView. Does this have to do with the deprecation of Snapshot in Xcode? Is this going to mean from Xcode 9 i have to do somekind of workaround to get/call the elements using WKWebview?

**Comment by mykola-mokhnach** [comment]
This happened due to some changes Apple did there in Xcode9 SDK. Try to reach their engineers if you want to know more details.

**Comment by NagyRobertt** [comment]
Never mind seems like our app had a bug, now it is fine. Sorry about that

**Comment by lokeshvunnam1989** [comment]
@NagyRobertt I'm facing same issue. Not able to find WebElement. Can you help me how you are doing this?

**Comment by chandrajeetvedadri** [comment]
Hi,
Im also facing the same issue while trying to identify the wkWebview elements in an ios app.
We are not able to identify these elements. Is there any workaround for this?
Any other solution please.. I'm currently stuck with my work here.. Need help..!!

Please note: 
iOS Hybrid app, Xcode 9.2, iOS 11.2 version.
