### ISSUE TITLE
iOS 11 - Wait for 20 minutes to find an object

### ISSUE THREAD

**Issue by appiumnovice** [appium/appium#9409]
## The problem

For some UI objects, the server takes 20 minutes to return a result on a findElementByXpath on iOS 11.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable): n/a
* Desktop OS/version used to run Appium: Mac OSX 10.12.6
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iPhone 6 / iOS 11
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs

https://gist.github.com/appiumnovice/dd8165273ec43d7b69dd6d21f4a250b0#file-server-log

**Comment by mykola-mokhnach** [comment]
This a known issue with WDA. I've created a tutorial about how locators can be optimised: https://github.com/facebook/WebDriverAgent/wiki/How-To-Achieve-The-Best-Lookup-Performance
