### ISSUE TITLE
[iOS][1.7.1] Tests run 3x slower on iOS 10.2 compared to iOS 10.3.2

### ISSUE THREAD

**Issue by welnanick** [appium/appium#9411]
## The problem

I have been writing my tests using an iPhone SE running iOS 10.3.2, and everything has been fine. On that device the tests take about 30 minutes to run. I recently ran my tests against an iPhone 7+ running iOS 10.2 and they took 2 hours. Nothing has changed with my capability set or with the tests between the two devices. I have confirmed that this seems to happen with all devices running 10.2, not just the iPhone 7+. I have tried swapping the cords and the USB ports being used, but the 10.3.2 device always takes about 30 minutes and the 10.2 devices always take about 2 hours.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS Sierra 10.12.6
* Node.js version (unless using Appium.app|exe): 8.5.0
* Mobile platform/version under test: iOS 10.2 and iOS 10.3.2
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: CLI

**Comment by rajfidel** [comment]
@welnanick Do you have Appium logs for a problematic test run (on iOS 10.2) vs test run on non-iOS 10.2 phone ?

**Comment by mykola-mokhnach** [comment]
Can you try to do more precise comparison? Which exact commands/WDA calls take more time on 10.2 in comparison to 10.3? Are there any special cases?

**Comment by welnanick** [comment]
@rajfidel I'll pull logs for on of my shorter test runs here in a second. Still gonna take me close to an hour to run both though :/

@mykola-mokhnach I'll try to pull something together. 90% of the commands my tests run are lookups, clicks, and isDisplayed() commands with the occasional .getText(). One thing I can remember off the top of my head (and maybe this is contributing the most of the time, I don't know) is the time it takes to start the app in-between tests is very long.

I'll also give a rundown of how I have my tests written, as I suppose there might be an issue there causing slowness as well.

**Comment by welnanick** [comment]
Unfortunately the iOS dev team I am working with is having issues with the app certification at the moment, and I am unable to use iOS 10.2 devices. I will update with the requested information as soon as I can.

**Comment by welnanick** [comment]
So I haven't gotten any logs or anything yet because I was fixing other issues in my tests, however now I am convinced all the extra time is coming from the downtime in between the tests. I was watching the tests while running and none of the actions are noticeably slower, but the downtime between tests is.

Currently I am running my tests such that each test is its own session, meaning I create a new driver before each test, and close the driver at the end of each test. So I think there is some slowdown coming from launching the app that isn't happening on 10.3 or above.

**Comment by welnanick** [comment]
In fact, when examining the output from TestNG, the tests on average are running 10 seconds faster on iOS 10.2. I have the driver creation in a Before Method and the closing in an After Method, so they are not counted in the testing time. This further confirms that its an issue with the launching of the app in between tests.

**Comment by rajfidel** [comment]
Sounds like it is related to #8083. But not sure why this would be an OS specific issue. I restart the appium server programatically before every test.

**Comment by welnanick** [comment]
@rajfidel except its not like the tests on iOS 10.2 start out with a reasonable downtime and degrade, the time to launch the app is 2-3x slower from the get go compared to iOS 10.3.2.

Also restarting the appium server between each test is not an option because of how many tests I am running. Not to mention I think in my case it would just compound the issue and make the runtime of my tests even slower.

**Comment by welnanick** [comment]
Running with 1.7.2@beta on iOS 10.2 right now. Early results are not positive, still looks like its going to be a while. I'll update when it is done.

Is there anything specific I can provide to help track down the issue?

**Comment by welnanick** [comment]
@mykola-mokhnach @rajfidel So I just finished a full run of my tests on iOS 10.2 using appium 1.7.2@beta. It was better, ran about 15 minutes faster than before, but that's still coming in at 1 hour 45 minutes compared to iOS's 30 minutes on 1.7.2@beta. So tests on iOS 10.2 are running 3.5x slower than when they are on iOS 10.3.

Are there any specific logs you would like me to collect to help track down what the issue is?

**Comment by mykola-mokhnach** [comment]
You could compare the logs yourself. There should be a bottleneck somewhere: some method(s) call, which takes a lot of time and has significant difference in perf on different platform versions.

**Comment by welnanick** [comment]
Alright. If I have some time in the next few days I'll see if there is anything apparent in the logs coming out of appium.
