### ISSUE TITLE
[UIAutomator2] Disconnecting a device from a computer while test is being run leaves server running on device

### ISSUE THREAD

**Issue by tslape** [appium/appium#9412]
## The problem

When running a test and the device is disconnected from the computer, the server on the device does not shutdown and continually drains the battery

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.0
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): 8.1.4
* Mobile platform/version under test: Android Nexus 6P running 7.1.2 (also have noticed this on a Nexus 9 running 7.1.1
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: CLI

## Details

When disconnecting a device that is running an automated test to use the device for a separate manual test results in the server never shutting off and continually draining the battery. The battery drains about twice as fast if not more. 

Can be worked around by not unplugging it while a test is running or remembering to shut off the server, but it would be nice if there was a timeout on the server if it does not receive any commands for a certain period of time.

## Link to Appium logs

The logs from the command prompt when you disconnect the device 
https://gist.github.com/tslape/1ddbe78d40be3fc029e58f735eb980f6

**Comment by tslape** [comment]
![batterydrain](https://user-images.githubusercontent.com/13459643/31357060-65897498-ad0e-11e7-95ab-fd330e9ffd49.PNG)

**Comment by welnanick** [comment]
I've noticed this on my android device too. Samsung Galaxy S7 Edge running Android 6.0.1

**Comment by dpgraham** [comment]
I'll look into this. I think what's probably happening is that there isn't a timeout that kills the server on the app.

**Comment by mykola-mokhnach** [comment]
Closed as fixed
