### ISSUE TITLE
Rewrite strategy does not work for 'UIAElement' class

### ISSUE THREAD

**Issue by navnathkarche** [appium/appium#9413]
## The problem

When I use Xpath strategy to find element in iOS 10 with appium version 1.7.1 it failed to get element handle.
e.g Xpath is: '//UIAElement[contains(@name, "myDataContainer")]'

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Desktop OS/version used to run Appium: Mac OS sierra 10.12.4
* Node.js version (unless using Appium.app|exe): 7.10.1
* Mobile platform/version under test: iOS 10 (iPhone 6)
* Real device or emulator/simulator: Simulator

## Details
While using Xpath strategy our 'appium-xcuitest-driver' rewrite the xpath by replacing the 'UIA' text to 'XCUIElementType', but this is not working for 'UIAElement'.

It seems like 'UIAElement' is replace by 'XCUIElementTypeElement' this causes failure.
The 'UIAElement' should be replace by 'XCUIElementTypeOther' according to [this](http://developers.perfectomobile.com/display/TT/Migrating+iOS+test+scripts+to+XCUITest-based+automation+infrastructure) UI Object tree  
## Link to Appium logs

```
[HTTP] --> POST /wd/hub/session/e9fc5939-3bc3-42ea-840f-a37fef050d61/elements {"using":"xpath","value":"//UIAElement[contains(@name, \"myDataContainer\")]"}
[debug] [MJSONWP] Calling AppiumDriver.findElements() with args: ["xpath","//UIAElement[contains(@name, \"myDataContainer\")]","e9fc5939-3bc3-42ea-840f-a37fef050d61"]
[debug] [XCUITest] Executing command 'findElements'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[XCUITest] Rewrote incoming selector from '//UIAElement[contains(@name, "myDataContainer")]' to '//XCUIElementTypeElement[contains(@name, "myDataContainer")]' to match XCUI type. You should consider updating your tests to use the new selectors directly
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8100/session/E4625C92-9D10-4F38-89F4-00FBFA5665A6/elements] with body: {"using":"xpath","value":"//XCUIElementTypeElement[contains(@name, \"myDataContainer\")]"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":[],"sessionId":"E4625C92-9D10-4F38-89F4-00FBFA5665A6","status":0}
[debug] [MJSONWP] Responding to client with driver.findElements() result: []
[HTTP] <-- POST /wd/hub/session/e9fc5939-3bc3-42ea-840f-a37fef050d61/elements 200 1419 ms - 74
```

## Code To Reproduce Issue

 

- Start appium(with mentioned environment) session.
-  Find element using Xpath like:   '//UIAElement[contains(@name, "myDataContainer")]'
-  Observe the appium log (Rewrite strategy)

**Comment by imurchie** [comment]
The re-writing is there as a stop-gap measure. It should not be relied upon. Instead, you should change your Xpath expressions to handle the hierarchy for iOS 10+.
