### ISSUE TITLE
Error: Could not detect Mac OS X Version from sw_vers output: '10.13'

### ISSUE THREAD

**Issue by caunem** [appium/appium#9415]
## The problem

I am having issues with running iOS tests since upgrade to HighSierra + Xcode 9, and I suspect that this is the source of the problem. 

## Environment

* Appium version: 1.7.1
* Desktop OS/version: MacOS 10.13
* Node.js version: 7.10.0
* Mobile platform/version under test: iOS 10.3 or 11
* Real device or emulator/simulator: Simulator
* Appium.app

## Additional details

![screen shot 2017-10-10 at 09 12 18](https://user-images.githubusercontent.com/11677773/31372307-cbd66b40-ad9d-11e7-9bc8-1380b7fb87c2.png)

## Link to Appium logs

https://gist.github.com/caunem/4861e2a6fbf8dce9f042faf34106532e

**Comment by caunem** [comment]
Ok, managed to get the tests running, but the Appium Doctor issue persists.

**Comment by imurchie** [comment]
Re-openeing because this is a real issue. Thanks!

**Comment by neogeek13** [comment]
Having same issue but with 10.13.3... 
Appium version: 1.7.2
Desktop OS/version: MacOS 10.13.3

**Comment by imurchie** [comment]
@neogeek13 Please provide the full Appium server log output as a link to a [gist](https://gist.github.com). There is nothing that can been done without it.
