### ISSUE TITLE
Not able to switch between windows for Android during parallel execution using Appium 1.7.0

### ISSUE THREAD

**Issue by Dineshk1** [appium/appium#9416]
## The problem

I am testing is hybrid app, which contains both native and webview part, plus webview has multiple windows (around 8 to 10). I want to switch between these windows.

## Environment

* Appium version : 1.7.1 and 1.7.0
* Last Appium version that did not exhibit the issue (if applicable): 1.6.5
* Desktop OS/version used to run Appium: 10.12(sierra)
* Mobile platform/version under test: Android 8.0, 7.0 and 6.0
* Real device or emulator/simulator:Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

While execution we are unable to switch to different windows(if there are multiple windows). If there is a single window, then it is working fine. I did not face this issue in Appium version 1.6.5. After upgrading to Appium 1.7.0 this problem occurred. Tried replacing latest chromedriver, but it did not solve the issue.

I face this issue only while executing on multiple devices.When i execute on single device, i am able to switch between windows.

I am able to execute scripts belongs to native and webview part of app parallelly on multiple android devices Simultaneously.(but not able to switch between windows)

## Link to Appium logs

https://gist.github.com/Dineshk1/456dc853b2ab461b1b4fe2c34df69e96

## Code To Reproduce Issue [ Good To Have ]

Set<String> contextNames = null;
        try {
            contextNames = driver.getContextHandles();

            for (String contextName : contextNames) {
                if (contextName.contains("WEBVIEW_")) {
                    driver.context(contextName);
                    log.info("switched to webview");
                    break;
                }

            }
        } catch (Exception e) {
            log.info("No Contexts");
        }

        Set<String> windoowsInCurrentPage = driver.getWindowHandles();
        for (String window : windoowsInCurrentPage) {
            try {
                driver.switchTo().window(window);
                if (driver.findElement(By.id("submitMyForm")).isDisplayed()) {
                    log.info("switched to window");
                    break;
                }

            } catch (NoSuchWindowException e1) {
                log.info("No Such window");

            }

            catch (Exception e) {
                log.info("Window not found");
            }
        }

**Comment by saikrishna321** [comment]
@Dineshk1 pls provide entire log as gist
