### ISSUE TITLE
Application start faces issues in Nexus 5 device

### ISSUE THREAD

**Issue by mekxtari** [appium/appium#9417]
## The problem

We have issues running automation scripts on Nexus 5 device. Other devices are working fine. Application won't event start and causes error.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable): 1.6.6
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: 5.1.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:

## Link to Appium logs

https://gist.github.com/mekxtari/0c72ccdc6e08ea0bc385a741edaebbb3

**Comment by saikrishna321** [comment]
please update your build-tools to latest and try

**Comment by mekxtari** [comment]
Actually real device had some issues and now it seems that everything is working nicely. Closing this issue.
