### ISSUE TITLE
iOS 11 : Unable to retrieve element properties for elements within webViews for Hybrid apps

### ISSUE THREAD

**Issue by poorvikamahesh** [appium/appium#9419]
The elements within webviews in hybrid app are not 'Visible' to appium

Appium Server Version : 1.7.1
XCode Version : 9.0
iOS : 11.0
Mac OS : 10.12.6

Please refer screenshot of the Appium inspector

<img width="1034" alt="screen shot 2017-10-10 at 4 26 37 pm" src="https://user-images.githubusercontent.com/10269471/31383008-20fb0336-add7-11e7-8b3a-d2bacc8b7916.png">

Below is the XML file returned with getPageSource(). The elements within the webView is not displayed in the XML file as well.
[page.txt](https://github.com/appium/appium/files/1371571/page.txt)

**Comment by imurchie** [comment]
Apple in Xcode 9 no longer reports the elements inside a Webview, unfortunately. There is nothing that can be done about this.
