### ISSUE TITLE
Using `hide_keyboard` on an iOS Simulator in landscape orientation results in an "Enable Dictation?" alert dialog

### ISSUE THREAD

**Issue by richlanc** [appium/appium#9420]
## The problem
Using `hide_keyboard` on an iOS Simulator in landscape orientation results in an "Enable Dictation?" alert dialog. 

I haven't witnessed when the simulator is portrait. 

## Environment
* Appium version: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: OSX 10.13
* Node.js version: v8.5.0
* Mobile platform/version under test: iOS11
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: CLI

## Details
![appium_landscape_hide_keyboard_bug](https://user-images.githubusercontent.com/2140010/31382992-5afefcac-adb1-11e7-9b2e-a405201323eb.gif)

## Link to Appium logs
https://gist.github.com/richlanc/ce445d56d855e38208d7cb6f691a582b

## Code To Reproduce Issue [ Good To Have ]
```python
import sys
import threading
import time

from appium import webdriver
from selenium import webdriver as swebdriver

from BaseHTTPServer import BaseHTTPRequestHandler, HTTPServer


class Handler(BaseHTTPRequestHandler):

    def _set_headers(self):
        self.send_response(200)
        self.send_header('Content-type', 'text/html')
        self.end_headers()

    def do_GET(self):
        self._set_headers()
        self.wfile.write("<html><body><input type='text' id='text' style='width: 100%; height: 600px'></body></html>")


def test():
    if "chrome" in sys.argv:
        driver = swebdriver.Chrome("<< path to chrome driver >>")

    else:
        capabilities = {
            "automationName": "XCUITest",
            "browserName": "Safari",
            "deviceName": "iPhone2017-B",
            "platformName": "iOS",
            "platformVersion": "11.0",
            "newCommandTimeout": 0
        }

        driver = webdriver.Remote(
            "http://localhost:4723/wd/hub", capabilities
        )

    driver.get("http://127.0.0.1:6543/")

    print("Rotating")
    driver.orientation = "LANDSCAPE"
    time.sleep(2)

    print("Opening keyboard")
    driver.execute_script("mobile: tap", {"x": 200, "y": 200})
    time.sleep(2)

    print("Attempting to hide the keyboard")
    driver.hide_keyboard()

    raw_input(">>>")


if __name__ == "__main__":
    http = HTTPServer(("127.0.0.1", 6543), Handler)
    httpThread = threading.Thread(target=http.serve_forever)

    try:
        httpThread.start()
        time.sleep(1)

        test()

    finally:
        http.shutdown()
        httpThread.join()
```

**Comment by imurchie** [comment]
Do you have some special keyboard? I cannot catch what the keyboard looks like in the animated gif you posted. Can you post a screenshot of the simulator with the keyboard up?

**Comment by mykola-mokhnach** [comment]
The hideKeyboard logic is simple - it tries to call hideKeyboard method from XCTest and click a button at the bottom right of the on-screen keyboard if the keyboard is still visible. In case this button is something different from Hide Keyboard (which is, usually, the case when you're not on iPad) then the issue above might happen. 

Unfortunately Apple's XCTest does not provide any built-in feature, which guarantees the keyboard is hidden even after hideKeyboard method is called. So, I'd rather try to simulate the set of actions, that the application user is supposed to execute in order to hide it.

**Comment by richlanc** [comment]
Thanks for responding. I don't believe there is anything special about the keyboard. 

![keyboard](https://user-images.githubusercontent.com/2140010/31395148-f9ecb50e-add7-11e7-8e98-d10fc14e99a8.png)

**Comment by imurchie** [comment]
For iPhone WDA's method never works.

**Comment by imurchie** [comment]
Since there is a `Done` button, try using the python method
```python
driver.hide_keyboard(key_name='Done')
```

**Comment by imurchie** [comment]
Closing as inactive.
