### ISSUE TITLE
testng suites are not executing parallel on android device/simulator

### ISSUE THREAD

**Issue by pranaybiswas2611** [appium/appium#9422]
## The problem

Steps : 
1. Created to testng suites with different 'port' of appium as parameter
2. As testng doesn't run parallel on suite level, so used maven-surefire-plugin
    plugin details in pom.xml is mentioned in below gist url.
       			
3. ran 2 instances of appium server on 4723 and 4725 ports
4. executing   mvn clean test

Excepted : Both the testng suite run parallely on device/emulator.

Actual : Initial command is running on both devices/emulator but after some time client request is going to different instance/port.

please help.
appium log and testng xmls gist are mentioned below.

## Environment

* Appium version : 1.7.1
* Desktop OS/version used to run Appium: macOS Sierra version 10.12.5
* Mobile platform/version under test: Android 6.0
* Real device or emulator/simulator: Both
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs and testng xml

https://gist.github.com/pranaybiswas2611/9727b190b5cb07cfae161958f1c1d44e

**Comment by TuHuynhVan** [comment]
@pranaybiswas2611 
I'm not sure why this should be a bug for Appium! Why don't you drop a question here first?
https://gitter.im/appium/appium

**Comment by pranaybiswas2611** [comment]
@TuHuynhVan  i referred some of the discussion related to this even asked this question on gitter as well.
If you could check quickly in logs because in one of the port, session is closed but open in other one.

**Comment by TuHuynhVan** [comment]
@pranaybiswas2611 
Theses lines show that it stopped by the test of not finding out the element.
https://gist.github.com/pranaybiswas2611/9727b190b5cb07cfae161958f1c1d44e#file-appium-4723-log-L1633-L1720

But why after that it call to different port as you described, you need to debug the "element not found" first and check a gain the way you start test and related things, I think.

**Comment by mykola-mokhnach** [comment]
Is there any reason not to use **avd** capability to init the emulator?

**Comment by pranaybiswas2611** [comment]
@TuHuynhVan  Its because .. After 'com.unacademyapp:id/email_confirm_button' , 'com.unacademyapp:id/password' is expected but
https://gist.github.com/pranaybiswas2611/9727b190b5cb07cfae161958f1c1d44e#file-appium-4723-log-L307-L340
there is some different behavior thats why rest of the elements not found, even though its not found port 4723 shut down in the end of almost last element
but port 4725 execution stopped at one point while swipe, looks like request after swipe went to port 4723 (just guessing), unable to understand that whats happening.

@mykola-mokhnach I am running script on device as well.

and my test suite is working for single device/emulator.

**Comment by pranaybiswas2611** [comment]
@TuHuynhVan @mykola-mokhnach  Its working now. Reason was that android driver was static for all threads.
You can close this issue. Thanks :)
