### ISSUE TITLE
XCUITest Problem

### ISSUE THREAD

**Issue by WRWRuggiaman** [appium/appium#9424]
## The problem
When i start appium for web application test i have this problem
## Environment

Appium version: v1.7.1
macOS High Sierra 10.13
node v6.11.4
iOS 10.0.2
iPhone 5s

## Link to Appium logs

https://gist.github.com/WRWRuggiaman/b2b49bb9b7d94519ebfc4ff5c177b16b

**Comment by imurchie** [comment]
Are you running Appium.app from the DMG, without installing it? It looks like you are running within a readonly private partition.

**Comment by WRWRuggiaman** [comment]
I downloaded "appium-desktop-1.2.3-mac.zip" and I started it.

**Comment by imurchie** [comment]
You need to move `appium.app` from the mounted drive into your `Applications` folder.

**Comment by WRWRuggiaman** [comment]
I moved appium.app to the Applications folder, and now I have the following logs

https://gist.github.com/WRWRuggiaman/ce14724c9fc0556e47f38e29a06b3a01

**Comment by imurchie** [comment]
This is now a signing issue. Please see https://github.com/appium/appium/blob/master/docs/en/drivers/ios-xcuitest-real-devices.md and look around at the issues that already exist.
