### ISSUE TITLE
Apple in XCode 9 is unable to report the elements inside a Webview.

### ISSUE THREAD

**Issue by rajeev2** [appium/appium#9425]
The elements within webviews in hybrid app are not 'Visible' to appium

Appium Server Version : 1.7.1
XCode Version : 9.0
iOS : 11.0
Mac OS : 10.12.6

Please refer screenshot of the Appium inspector
![ios 11 issue](https://user-images.githubusercontent.com/20370232/31399353-a67d0d06-ae09-11e7-9504-5d9b9d24777c.png)

Is there any other way to resolve this issue? Please give a resolution.

**Comment by mykola-mokhnach** [comment]
Sorry, but Appium Desktop is designed to debug native source only. Please use the standard remote debugging feature for webviews.

**Comment by imurchie** [comment]
Xcode 8 translated web elements into native element counterparts, so they were visible. Xcode 9 removed that functionality. There is nothing Appium can do.

**Comment by rafael-chavez** [comment]
@imurchie Do you know if Apple officially disclosed this? Or they just removed that translation from under the hood?

**Comment by imurchie** [comment]
It has started to come back for some webviews in Xcode 9.0.1 (build 9A1004). Not sure why it was removed but I would guess it was a mistake/oversight.

**Comment by rafael-chavez** [comment]
🎉  Thanks @imurchie !!!

**Comment by masoodmd0786** [comment]
@imurchie does below issue related to this issue?

https://discuss.appium.io/t/unable-to-find-webview-in-ios-hybrid-app-xcode9-appium1-7-1-ios10-3-3-and-above/19068

**Comment by rafael-chavez** [comment]
I actually still see the issue in Xcode 9.0.1 patch. What do you mean when you say it started to come back for some webviews @imurchie ?
