### ISSUE TITLE
iOS 11 getPageSource() hangs

### ISSUE THREAD

**Issue by VTINFOJames** [appium/appium#9426]
I'm running Appium 1.7.1 and testing iOS 11. The command getPageSource() just hangs. The command was submitted over 10 minutes ago and Appium isn't updating at all. I can run the same test code on the same Appium server against iOS 10.3 and it works. Has anyone else had this issue with iOS 11?

Appium 1.7.1
Node.js v8.5.0
iOS 11 Real Device - Native Application
Appium CLI

This is the third attempt to get beyond this issue with iOS 11 and I've just killed the session on previous attempts. I will let this one run it's course as I need to head home for the day anyway. It is still hung up after 45 minutes now. I will try to get some logs and upload them here tomorrow morning.

**Comment by dpgraham** [comment]
On iOS Devices for version < 11 does it work okay?

**Comment by mykola-mokhnach** [comment]
It's anyway on WDA side, for example https://github.com/facebook/WebDriverAgent/issues/744, https://github.com/facebook/WebDriverAgent/issues/730

**Comment by mykola-mokhnach** [comment]
Closing as known WDA bug

**Comment by VTINFOJames** [comment]
Thank you for the links to the WebDriverAgent issues @mykola-mokhnach.

**Comment by masoodmd0786** [comment]
Hi @James, 

Can you please provide list of below softwares, I need to test iOS hybrid App on real device with version 11

Xcode
Java client
Selenium 
Any other software if I am missing.

Currently I am struck to find a webView in iOS hybrid App.

Created support/issue tickets but I am not receiving any response.

Thanks 
Masood

**Comment by VTINFOJames** [comment]
@masoodmd0786 

Xcode 9.1
Java 1.8
Appium-Desktop 1.2.6
iOS 11.1
