### ISSUE TITLE
[UiAutomator 2][Request] Document ranking the speed of different lookup methods

### ISSUE THREAD

**Issue by welnanick** [appium/appium#9427]
If possible could there be a document like the following for the UiAutomator2 driver?: https://github.com/facebook/WebDriverAgent/wiki/How-To-Achieve-The-Best-Lookup-Performance

I am trying to optimize the lookup speed in my tests and would like to know what the fastest methods are and what-not. If a document like this already exists for UiAutomator2 I am sorry, I did a quick search and couldn't find anything.

Thank you!

**Comment by dpgraham** [comment]
That's a good idea. In the past I've discussed adding a document to the Appium site that explains all of the selectors in detail with performance info. Selector performance is a pain point for many of our users.

**Comment by mykola-mokhnach** [comment]
this was fixed
