### ISSUE TITLE
no such window: window was already closed

### ISSUE THREAD

**Issue by Sahara-ws** [appium/appium#9429]
## The problem
my problem:  tatal two loop, first loop is ok ,second is error.  every loop contains from native switchto h5.

Keyword 'Capture Page Screenshot' could not be run on failure: NoSuchWindowException: Message: no such window: window was already closed
  (Session info: webview=30.0.0.0)
  (Driver info: chromedriver=2.30.477700 (0057494ad8732195794a7b32078424f92a5fce41),platform=Windows NT 6.1.7601 SP1 x86_64)
## Environment
* Appium 1.6.5
* emulator:Nox3.8.2.0
* robotframework

## Details

![image](https://user-images.githubusercontent.com/32695912/31423956-33b90c26-ae8a-11e7-9c1f-c96003bb06c3.png)

## Link to Appium logs

[debug] [AndroidDriver] Returning process name: 'com.vphone.launcher'
[debug] [AndroidDriver] Found webviews: ["WEBVIEW_com.yidai.bbqb.app","WEBVIEW_com.estrongs.android.pop","WEBVIEW_com.vphone.launcher"]
[debug] [AndroidDriver] Available contexts: ["NATIVE_APP","WEBVIEW_com.yidai.bbqb.app","WEBVIEW_com.estrongs.android.pop","WEBVIEW_com.vphone.launcher"]
[debug] [AndroidDriver] Connecting to chrome-backed webview context 'WEBVIEW_com.yidai.bbqb.app'
[debug] [AndroidDriver] Found existing Chromedriver for context 'WEBVIEW_com.yidai.bbqb.app'. Using it.
[debug] [JSONWP Proxy] Proxying [GET /url] to [GET http://127.0.0.1:8000/wd/hub/session/e601cb1b8763daf62afaf854fba3e4cb/url] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"e601cb1b8763daf62afaf854fba3e4cb\",\"status\":23,\"value\":{\"message\":\"no such window: window was already closed\\n  (Session info: webview=30.0.0.0)\\n  (Driver info: chromedriver=2.30.477700 (0057494ad8732195794a7b32078424f92a5fce41),platform=Windows NT 6.1.7601 SP1 x86_64)\"}}"
[debug] [MJSONWP] Responding to client with driver.setContext() result: null
[HTTP] <-- POST /wd/hub/session/f22baf5d-14b3-4583-8d63-00d642c3706f/context 200 1244 ms - 76 
[HTTP] --> POST /wd/hub/session/f22baf5d-14b3-4583-8d63-00d642c3706f/elements {"using":"xpath","sessionId":"f22baf5d-14b3-4583-8d63-00d642c3706f","value":"//a[contains(.,\"零钱罐\")]"}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [JSONWP Proxy] Proxying [POST /wd/hub/session/f22baf5d-14b3-4583-8d63-00d642c3706f/elements] to [POST http://127.0.0.1:8000/wd/hub/session/e601cb1b8763daf62afaf854fba3e4cb/elements] with body: {"using":"xpath","sessionId":"f22baf5d-14b3-4583-8d63-00d642c3706f","value":"//a[contains(.,\"零钱罐\")]"}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"e601cb1b8763daf62afaf854fba3e4cb","status":23,"value":{"message":"no such window: window was already closed\n  (Session info: webview=30.0.0.0)\n  (Driver info: chromedriver=2.30.477700 (0057494ad8732195794a7b32078424f92a5fce41),platform=Windows NT 6.1.7601 SP1 x86_64)"}}
[JSONWP Proxy] Replacing sessionId e601cb1b8763daf62afaf854fba3e4cb with f22baf5d-14b3-4583-8d63-00d642c3706f
[HTTP] <-- POST /wd/hub/session/f22baf5d-14b3-4583-8d63-00d642c3706f/elements 200 1026 ms - 290 
[HTTP] --> GET /wd/hub/session/f22baf5d-14b3-4583-8d63-00d642c3706f/screenshot {}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/f22baf5d-14b3-4583-8d63-00d642c3706f/screenshot] to [GET http://127.0.0.1:8000/wd/hub/session/e601cb1b8763daf62afaf854fba3e4cb/screenshot] with body: {}

**Comment by mykola-mokhnach** [comment]
Do you get the same error with Appium 1.7?

**Comment by mykola-mokhnach** [comment]
This might be chromedriver bug: https://bugs.chromium.org/p/chromedriver/issues/detail?id=346

**Comment by Sahara-ws** [comment]
@mykola-mokhnach only 1.6.5

**Comment by Sahara-ws** [comment]
@mykola-mokhnach oh,thank you
