### ISSUE TITLE
[Appium 1.7.1][XCUITest] - Performance issues due to multiple WDA GET Session Calls

### ISSUE THREAD

**Issue by cosminstirbu** [appium/appium#9430]
## The problem

Since upgrading from Appium 1.6.4 and Xcode 8.3.2 to Appium 1.7.1 and Xcode 9 there's a visible performance issue in the speed that our tests run with.

Having a closer look a the logs I've noticed that the WDA Get Session call is made really often between other calls that are actually performed by my tests (such as element lookup or element interaction).

I'm not sure if this is the root cause of the performance issue, but the frequency that this call is made with is definitely suspicious.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable): probably 1.6.4
* Desktop OS/version used to run Appium: mac OS 10.12.6
* Node.js version (unless using Appium.app|exe): 8.6.0
* Mobile platform/version under test: iOS 11 & iOS 10
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs

https://gist.github.com/cosminstirbu/ab76638e2ab6b78cbfa353741692eb4d

You can do a search after - `GET http://localhost:6789/session/A8896F8A-6183-4282-AFB3-1E3BE652A54B`

**Comment by imurchie** [comment]
Those calls are performed by your test runner, or the grid code if you are in a Selenium grid. They shouldn't affect things very much.

Xcode 9's simulators are slower than Xcode 8's, which is largely the problem. Unfortunately.

**Comment by mykola-mokhnach** [comment]
Yep, it seems like it's Selenium Grid, who does these requests. They are cheap, since WDA is not affected by any of them.

**Comment by saif1670** [comment]
I am facing the same issue on Real device also
