### ISSUE TITLE
Assert and Explicit Wait is not Working for an Element But For same Element Click action is Worked

### ISSUE THREAD

**Issue by stephenws** [appium/appium#9431]
## The problem
I have updated mac oS from 10.12.4 to 10.12.6 also updated node version and I am using Appium 1.6.4
Before Update my script was running properly but after macOS updation Explicit wait and Assertion script stoped working.
I have Used Assertion and Explicit wait for one Element  and that is not working whereas same element is working for Click action
Please Note: Same Assertion and Explicit Wait function is working on Android but getting issue in IOS

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Last Appium version that did not exhibit the issue (if applicable): 1.6.4
* Desktop OS/version used to run Appium: Mac OS 10.12.6
* Node.js version (unless using Appium.app|exe): v6.11.0
* Mobile platform/version under test: 10.0.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

Same function is working in android but not in IOS 

## Link to Appium logs
Explicit wait and Assert Not working:
https://gist.github.com/stephenws/43f8b2ed8debd825cf8abbdacdb93c7d

Explicit wait not working and Click Working
https://gist.github.com/stephenws/33925388a0051d86c2b6efa7e056cea3

## Code To Reproduce Issue [ Good To Have ]
Explicit Wait function:
public void waitToload(MobileElement locator, int timeout) throws Exception{
       
 	try{
              
 		MobileElement element = null;
 		WebDriverWait wait = new WebDriverWait(driver, timeout);
 		element = (MobileElement) wait.until(ExpectedConditions.elementToBeClickable(locator));
 	       
 	}catch(Exception e){
 	   System.out.println(e.getMessage());
 	}
        finally {
        	
            Thread.sleep(5000);
       }
}

Assertion function
public void verifyElementIsDisplayed(MobileElement element) {
		try {
			
			Assert.assertTrue(element.isDisplayed());
			System.out.println(element + "is displayed");

		} catch (Exception e) {

			Assert.fail("Element is not displayed || locator has changed -- FAIL");

		}
	}

**Comment by mykola-mokhnach** [comment]
Closed as obsolete
