### ISSUE TITLE
Device orientation changes the page alone not the device

### ISSUE THREAD

**Issue by DeepikaThiru** [appium/appium#9432]
## The problem

With the latest release say from 1.6.5 could see that driver.rotate(ScreenOrientation.LANDSCAPE) is rotating the page alone.

## Environment

Appium version : 1.7.1
Desktop OS/version used to run Appium: MacOS 10.12.6 Sierra
Appium Desktop Version :Version 1.2.3 (1.2.3)
Carthage Version :0.25.0
XCode version :9

## Details

When device orientation is performed with later version of appium (i.e before 1.6.5) could see that device rotates but know the page rotates.

Expected:
<img width="880" alt="screen shot 2017-10-11 at 5 21 45 pm" src="https://user-images.githubusercontent.com/17921976/31439329-62f1a8bc-aea9-11e7-86d6-224c050ec8e0.png">

 Actual:
<img width="688" alt="screen shot 2017-10-11 at 5 21 31 pm" src="https://user-images.githubusercontent.com/17921976/31439341-6c29da3a-aea9-11e7-8da4-8a0cb03ee2f8.png">

**Comment by mykola-mokhnach** [comment]
This is known XCTest issue. Nothing we can do on Appium side, that can fix it.
