### ISSUE TITLE
xCode Build Failed - Code 65

### ISSUE THREAD

**Issue by Elangopalakrishnan** [appium/appium#9437]
## The problem

I have built successfully all apps like webdriveragent and integration apps in xcode.
Integration app running in iphone.
But i'm getting xcode failure code 65 error when i try to launch the safari browser in iPhone.
Please review my logs and help me.

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac Sierra 10.12.6
* Mobile platform/version under test: iOS 11.0 and 11.0.2
* Real device or emulator/simulator: Real Device

## Details

I have built successfully all apps like webdriveragent and integration apps in xcode.
Integration app running in iphone.
But i'm getting xcode failure code 65 error when i try to launch the safari browser in iPhone.
Please review my logs and help me.

## Code:

var capabilities = new DesiredCapabilities();
                    capabilities.SetCapability(CapabilityType.BrowserName, "Safari");
                    capabilities.SetCapability("automationName", "XCUITest");
                    capabilities.SetCapability(MobileCapabilityType.DeviceName, "iPhone 6s");
                    capabilities.SetCapability(MobileCapabilityType.PlatformName, "iOS");
                    //capabilities.SetCapability("bundleId", "com.marykay.IntegrationApp");
                    //capabilities.SetCapability("bundleId", "com.marykay.WebDriverAgentRunner");
                    capabilities.SetCapability("bundleId", "com.apple.mobilesafari");
                    capabilities.SetCapability(MobileCapabilityType.PlatformVersion, "11.0.2");
                    capabilities.SetCapability("realDeviceLogger", "/usr/local/lib/node_modules/deviceconsole/deviceconsole");
                    capabilities.SetCapability("wdaLocalPort", "8200");
                    capabilities.SetCapability("udid", "2293f9b8XXXXXd3d9f6652929fbc9adf78324");  
                    mkConstants.AppDriver = new IOSDriver<AppiumWebElement>(new Uri("http://11.9.27.51:4723/wd/hub"), capabilities, TimeSpan.FromSeconds(600));

## Link to Appium logs
https://gist.github.com/Elangopalakrishnan/d5582765c8d97847f75629ea62997644

**Comment by welnanick** [comment]
Follow this: https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md

**Comment by Elangopalakrishnan** [comment]
@welnanick  Thanks! I did all changes and lauched the safari browser in my iPhone.
But after that appium logging below error msg:

[debug] [iOS] No web frames found.
[debug] [iOS] Retrieving contexts and views
[debug] [iOS] Selecting by url: true (expected url: 'http://appium.io')
[debug] [RemoteDebugger] Getting WebKitRemoteDebugger pageArray: localhost, 27753
[debug] [RemoteDebugger] Sending request to: http://localhost:27753/json
[iOS] Attempted to get a list of webview contexts but could not connect to ios-webkit-debug-proxy. If you expect to find webviews, please ensure that the proxy is running and accessible

My command for webkit proxy:
ios_webkit_debug_proxy -c 2293f9b82XXXXXd9e3XXXX29fbc9adf78324:27753 -d

wdaLocalPort - 8100

Thanks!
Elango

**Comment by Elangopalakrishnan** [comment]
updated webkit proxy, now it is working fine, Closing the issue 
:)
Thanks for all your support:)
