### ISSUE TITLE
Xcode build failed with code 65

### ISSUE THREAD

**Issue by Elangopalakrishnan** [appium/appium#9438]
## The problem

I have built successfully the all apps like webdriveragent and integration app in xcode.
Integration app is launched in ios devices.

But i'm getting the Xcode build failed with code 65 when i try to launch the safari browser in iPhone.
Please review my code and logs and help me ....
## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1 and 1.7.0
* Desktop OS/version used to run Appium: mac sierra 10.12.6
* Mobile platform/version under test: 11.0 and 11.0.2 
* Real device or emulator/simulator: Real Devices

## Details

Code:
var capabilities = new DesiredCapabilities();
                    capabilities.SetCapability(CapabilityType.BrowserName, "Safari");
                    capabilities.SetCapability("automationName", "XCUITest");
                    capabilities.SetCapability(MobileCapabilityType.DeviceName, "iPhone 6s");
                    capabilities.SetCapability(MobileCapabilityType.PlatformName, "iOS");
                    //capabilities.SetCapability("bundleId", "com.marykay.IntegrationApp");
                    //capabilities.SetCapability("bundleId", "com.marykay.WebDriverAgentRunner");
                    capabilities.SetCapability("bundleId", "com.apple.mobilesafari");
                    capabilities.SetCapability(MobileCapabilityType.PlatformVersion, "10.3.3");
                    capabilities.SetCapability("realDeviceLogger", "/usr/local/lib/node_modules/deviceconsole/deviceconsole");
                    capabilities.SetCapability("wdaLocalPort", "8200");
                    capabilities.SetCapability("udid", "2293f9b82093ad3d9e3f6652929fbc9adf78324");  
                    mkConstants.AppDriver = new IOSDriver<AppiumWebElement>(new Uri("http://102.9.27.51:4723/wd/hub"), capabilities, TimeSpan.FromSeconds(600));

## Link to Appium logs
https://gist.github.com/Elangopalakrishnan/d5582765c8d97847f75629ea62997644

Thanks in advance!
Elango

**Comment by dpgraham** [comment]
Closing as a duplicate
