### ISSUE TITLE
[XCUITest] Error: Could not find app at

### ISSUE THREAD

**Issue by tarunsujit** [appium/appium#9442]
## The problem
Unable to install the app.
If it is preinstalled I am able to launch it by giving buildid

## Environment
* Appium version - 1.7.1
* Desktop OS/version used to run Appium - mac 10.12.6
* Mobile platform/version under test: iOS 10.3.1
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: app

## Details

It used to work with previous build of the app, with new build I got this error. Not sure what is the issue, If it is a appium issue or app issue.

## Link to Appium logs

https://gist.github.com/tarunsujit/1db2bd7e0195cfbeb8fc0aa552217321

**Comment by mykola-mokhnach** [comment]
Please attach the log properly formatted. It's not possible to read the current one

**Comment by welnanick** [comment]
Just delete the .js off the end of the url and you'll get it properly formatted.

**Comment by mykola-mokhnach** [comment]
Thanks @welnanick , now I have the log. The problem is, that there are some unicode chars in the app name and zip utility cannot decode them properly while doing extraction. Unpack you .app from .ipa package manually and give it a name, which does not contain unicode chars, to workaround the issue.

**Comment by saikrishna321** [comment]
@tarunsujit ping, does this still exists ?
