### ISSUE TITLE
Not able to locate the element even the element is present on the page

### ISSUE THREAD

**Issue by akhand-pratap2807** [appium/appium#9443]
I am automation an iOS app. I need to click on an element Id. I had written the below code for the same which is running perfectly on iPad 11.0.1 but when I tried to run on iPad(10.3) then getting exception NoSuchElementException.  

The code I am using:
if(driver.isElementDisplayed("Next",35)){
}

## Environment

* Appium version: 1.7.1
* Last Appium version : 1.6.4
* Desktop OS/version used to run Appium: 10.12.6
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
* Real device or emulator/simulator: Real device on Ipad(10.3+)
* Appium CLI or Appium.app|exe:

**Comment by mykola-mokhnach** [comment]
Please attach the output of getPageSource command and full server log

**Comment by akhand-pratap2807** [comment]
I tried to get all element details of the page through getPageSource method but it is throwing an exception too and getting the crash. Unable to run getPageSource method

**Comment by mykola-mokhnach** [comment]
Then it's a bug of WebDriverAgent itself. Try Appium beta, which has the most recent WDA version. If this still does not work then report the problem directly to https://github.com/facebook/WebDriverAgent/issues and provide all the necessary logs

**Comment by akhand-pratap2807** [comment]
Basically, I tried to click on Next button of Instagram but it is failing for ios 10+ devices. But able to share over on-device iOS11. Can you suggest the way?
