### ISSUE TITLE
IOS: Simulator: Driver failed to start with latest Appium

### ISSUE THREAD

**Issue by amedvedjev** [appium/appium#9444]
## The problem

IOSDriver failed to start. In logs we see that status is OK but next request to create session fails.

## Environment

* Appium version (or git revision) that exhibits the issue: v1.7.2-beta
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MAC
* Mobile platform/version under test: IOS
* Real device or emulator/simulator: Simulator

## Link to Appium logs

https://gist.github.com/amedvedjev/a57ff8206e3a28b09c40e8a6bbb85c2c

**Comment by imurchie** [comment]
Can you turn on iOS device logging (`showIOSLog` cap set to `true`) and post the logs? Does the app run manually?

**Comment by mykola-mokhnach** [comment]
It would also be useful to see the device log. WDA cannot init the session for some reason. Perhaps the app under test crashes or WDA fails to start it properly

**Comment by amedvedjev** [comment]
@imurchie @mykola-mokhnach by some reason today at Friday 13 all started work without any changes :-). will close if fail to reproduce....
