### ISSUE TITLE
Appium 1.7.0 and 1.7.1 Xpath Performance is low

### ISSUE THREAD

**Issue by stephenws** [appium/appium#9446]
## The problem

In Appium 1.7.0, Xpath performance is very slow. It takes more than 4 minutes to Assert Xpath Loactor

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.0,1.7.1
* Last Appium version that did not exhibit the issue (if applicable): 1.6.4
* Desktop OS/version used to run Appium: Mac OS 10.12.
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
It's known WDA issue.
Check https://github.com/facebook/WebDriverAgent/wiki/How-To-Achieve-The-Best-Lookup-Performance

Also, we did some improvements in the recent beta release for xpath perf. so you can test it.
