### ISSUE TITLE
Can't Take Screenshot on iOS 11 iPhone 7+ with Appium Desktop 1.2.3

### ISSUE THREAD

**Issue by sean-hotaling** [appium/appium#9447]
## The problem

With an iPhone 7+ running iOS 11.0.2 or 11.0.3, the inspector in Appium Desktop 1.2.3 can't take a screenshot.  The inspector under the same conditions (with obviously the deviceName and udid changed) will take a screenshot of an iPhone SE.

I did see issue #9259 but with 1.7.1 being bundled into this particular version of Appium Desktop, I should have the screenshot workaround.

![appium-inspector](https://user-images.githubusercontent.com/3628789/31519421-64668cd6-af70-11e7-827d-f31e7d0eca25.png)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: macOS 10.12.6
* Node.js version (unless using Appium.app|exe): N/A
* Mobile platform/version under test: iPhone 7+/11.0.3 (and 11.0.2)
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium.app/1.2.3

## Link to Appium logs

[https://gist.github.com/sean-hotaling/eae05d25ea038bd3ac7270015ce00601](https://gist.github.com/sean-hotaling/eae05d25ea038bd3ac7270015ce00601)

**Comment by saikrishna321** [comment]
@sean-hotaling  what happens when u execute the below command 

```
idevicescreenshot -u 5eb18c8d9e89341093829810f7f76c1922be4210 /var/folders/lr/6f0_hl717_j505r61hjpqprw0000gn/T/2017912-4265-14s91kp.iuump1fw29/screenshot-5eb18c8d9e89341093829810f7f76c1922be4210.tiff
```

**Comment by mykola-mokhnach** [comment]
In the logs I see the device itself just stopped responding to any commands. This must be some internal issue there. One can check the device log to get more information on it.

**Comment by sean-hotaling** [comment]
@saikrishna321,  I was getting a `ERROR: Could not connect to lockdownd, error code -21` which I was able to reproduce by simply calling `ideviceinfo -d`.  I uninstalled libimobiledevice and reinstalled to its --HEAD which allows me to not receive that error anymore and get the screenshot in the inspector.  Immediately thereafter, however, I get a `[XCUITest] xcodebuild exited with code '65' and signal 'null'`.  Please see the logs at https://gist.github.com/sean-hotaling/41490544e06be473b716ec38283cb66d.

@mykola-mokhnach, please see the device log at https://gist.github.com/sean-hotaling/f786356ca0bf7325e0bf5ff42d868179.  It does not help much.

**Comment by saikrishna321** [comment]
> xcodebuild exited with code '65'

is clearing a code-signing issue

**Comment by saikrishna321** [comment]
Usually, error 65 means WDA source is not signed properly. Make sure you follow real device setup procedure described here

**Comment by mykola-mokhnach** [comment]
closed the issue as fixed
