### ISSUE TITLE
Error: chrome not reachable ---Android 6.0, Appium1.7.2-beta

### ISSUE THREAD

**Issue by RealLau** [appium/appium#9448]
## The problem

Unable to switch to webview from native app.

## Environment

* Appium version (or git revision) that exhibits the issue:  Appium v1.7.2-beta
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows 7
* Node.js version (unless using Appium.app|exe): v6.10.3
* Mobile platform/version under test: Android 6.0
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: CLI

Other:
----I use Appium-Python-Client (0.24).

## Details

I have:
    1. set webView.setWebContentsDebuggingEnabled(true) in Android app source code;
    2. updated the newest Chrome browser(V: 61.0.3163.100) and ChromeDriver(2.33.506120);

## Link to Appium logs

https://gist.github.com/RealLau/a52d51dcef07683f308ea0eb41302b94

## Code To Reproduce Issue [ Good To Have ]

Key code:
//Appium can successfully find these contexts: ['NATIVE_APP', 'WEBVIEW_chrome', //'WEBVIEW_com.hongfans.rearview:web'], but failed to do switch to //"WEBVIEW_com.hongfans.rearview:web", which I can see is successfully open on mobile--Real device:

self.driver.switch_to.context("WEBVIEW_com.hongfans.rearview:web")

Any suggestion is much appreciated :)

**Comment by mykola-mokhnach** [comment]
WebView engine version might differ from the Chrome browser version. Check at which version the System WebView component is and provide the appropriate driver version.

**Comment by RealLau** [comment]
@mykola-mokhnach 
Check at which version the System WebView component is and provide the appropriate driver version
-------------I'm sorry but how to check the System Webview version? Would u please tell more detail?

**Comment by Freddy13F** [comment]
@RealLau 
Did you resolve the issue? I got the same issue. Please share with me once you resolve that.

**Comment by Louis-me** [comment]
maybe you can update: 
- phone webview: https://www.apkmirror.com/apk/google-inc/android-system-webview/ 
or 
- chromedriver: https://chromedriver.storage.googleapis.com/index.html

**Comment by pradeepta02** [comment]
I am also facing the same issue. Anyone else facing the same issue and have resolved it?

Chrome V62.0.3202.94 (Official Build) (64-bit)
Chromedriver V2.33.506092
Appium V1.7.1

[JSONWP Proxy] Got response with status 200: {"sessionId":"6f4f82363d9e40624032bd3c2b7d735d","status":100,"value":{"message":"chrome not reachable\n  (Driver info: chromedriver=2.33.506092 (733a02544d189eeb751fe0d7ddca79a0ee28cce4),platform=Linux 4.8.0-53-generic x86_64)"}}
[Chromedriver] Chromedriver exited unexpectedly with code null, signal SIGTERM
[Chromedriver] Changed state to 'stopped'
[Chromedriver] Error: chrome not reachable

**Comment by RealLau** [comment]
Update:
I've updated my android webview to latest via "https://play.google.com/store/apps/details?id=com.google.android.webview&rdid=com.google.android.webview"(62), and updated my chrome browser(not that which in computer, but the one in android device) to latest(62), and updated the newest chromedriver(2.33), BUT still got the same result:

2017-12-01 16:05:41:396 - [Chromedriver] Error: Failed to start Chromedriver session: An error occurred (Original error: chrome not reachable
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64))

hope someone can help me out. - -

**Comment by ruberzen** [comment]
The same problem that you have guys:

Chrome V62.0.3202.73
WebView V62.0.3202.73 
Chromedriver V2.33.506092
Appium V1.7.1
Emulator: Based on: Android API 27 Tag/ABI: google_apis/x86

And if I use another API, it only has the NATIVE_APP context and I need to use webview.

Somebody can resolve this?

**Comment by imurchie** [comment]
You can get more logging by using the `showChromedriverLog` capability (set to `true`) to get the CD logs. Something is happening on that side of things.

**Comment by chanugithub** [comment]
@ruberzen @RealLau @pradeepta02 I am also getting same problem and also tried with different chrome drivers 2.33, 2.32, 2.8 etc . but no luck, If you guys fixed the problem please let me know

**Comment by RealLau** [comment]
@pradeepta02 @chanugithub 
I now have a compromise solution, just verify webview(web page) is open with appium(e.g in python: driver.contexts, you can see at least 2 contexts, one is NATIVE_APP, the other is WEB_VIEW liked), and verify web page with Python **requests** and **bs4**, below is my code for ur reference:
       `soup = BeautifulSoup(page_source, "html.parser")
        dic = {}
        title = soup.title.string
        original_prices = [i.string.replace(" ","") for i in soup.select(".original")]
        pay_ways = [i.string for i in soup.select("label")]
        membership_out_date = soup.select("h4 span")[0].string
        member_nick_name = soup.select(".usernick")[0].string
        dic["title"] = title
        dic["original_prices"] = original_prices
        dic["pay_ways"] = pay_ways
        dic["membership_out_date"] = membership_out_date
        dic["member_nick_name"] = member_nick_name
        return dic`

**Comment by chanugithub** [comment]
@RealLau does this HTML page provide any info regarding webview? i do not get any clue how it would be useful, can you provide more info?

**Comment by RealLau** [comment]
@chanugithub 
I mean, to verify a webview page(actually it's a html page which shows up after button clicked or something liked triggered), there could be 2 steps as a compromise solution:
    1. only verify the webview is in contexts(call driver.contexts);
    2. verify the html page with http requests(not a front-end, but a back-end solution)

**Comment by kirillbilchenko** [comment]
any progress on this?

**Comment by J320** [comment]
So after reading almost every thread related to this issue, in the end what did it for me was locating elements using valid xPaths from the UiAutomator, other native or web locators didn't work. It's a weird workaround but there seems to be some issues with Chromedriver and this is the only one that worked for me.

I really hope it works for all of you!

**Comment by galenyjl** [comment]
Appium 1.7.2
Android 7.1.1
Chrome 61
ChromeWebdriver 2.32 (Tried several versions)
Still met the issue "chrome not reachable
(Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.6 x86_64))"

Can anyone help? Many thanks

**Comment by mykola-mokhnach** [comment]
Closed as duplicate

**Comment by galenyjl** [comment]
@mykola-mokhnach Hi, could you tell which issue is related to this one? Considering this issue is duplicated. Thanks a lot.

**Comment by AlexeyPaskhin** [comment]
@mykola-mokhnach , point please to the related isuue

**Comment by pjlosco** [comment]
https://github.com/appium/appium/issues/10970 looks to be related

**Comment by vanlong-nox** [comment]
Somebody can resolve this?
