### ISSUE TITLE
Moving mouse to element when testing UWP app with WinAppDriver

### ISSUE THREAD

**Issue by watarus-nt** [appium/appium#9449]
## The problem

As Appium now can use along with WinAppDriver to automate testing on UWP app, can we add a method to hover on the GUI element (move mouse)?

I don't see such type of method from Appium neither WinAppDriver. It will be great to have it, more stuff can be automated. For example, I can move the mouse to element A, then use another library to simulate mouse click (when Appium can't click to the element). Or I can calculate the relative coordinate of other element then click on it (when there's no method to locate that element).

Hence, could you please consider to add it it?
Thanks in advance!

## Environment

* Appium version (or git revision) that exhibits the issue: v1.7.1
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Windows 10

**Comment by reincore** [comment]
Yes, I am in the same need as the app I am currently testing was not initially written for automation testing and often I find myself needing to get mouse coordinates.

**Comment by yodurr** [comment]
Which test language and runner are you using?

Appium .Net Driver (C#) includes mouse move to a position.  WinAppDriver supports mouse move.

**Comment by mykola-mokhnach** [comment]
the recent version of Windows driver includes support of W3C actions
