### ISSUE TITLE
Mobile Automation test

### ISSUE THREAD

**Issue by SandeepK1992** [appium/appium#9450]
Hi everyone i could really use your help on this one, i've created an authomation project for android devices (using jsystem,applitools,and selenium,and<a href="https://tekslate.com/appium-training/"> appium</a>) - all worked very well, but when i've tried to build a similar project on iOS, i came across a lot of problems,

The primary one is that when i'm trying to switch (during the authomation test) between different apps, Appium get stuck, and i cannot continue the test (i'm using a mac) and my code is in JAVA.
Any suggestions how to do so? This is very important in my mobile authomation test, since the app i'm testing is opened from other apps.

The switch is fail once my app was opened via another app, for example clicking on file that was received in email, will initiate my app, and then appium get stuck

Thanks in advance.
Sandeep Kommineni

**Comment by mykola-mokhnach** [comment]
On iOS you cannot switch between apps. It's was an Apple limitation before Xcode9 SDK. Now it is possible, but is not supported by WebDriverAgent yet. So you can either automate the flow using "raw" XCTest or wait for a new Appium release where this feature is supported.
