### ISSUE TITLE
Unable to inspect element from iOS real devices.

### ISSUE THREAD

**Issue by Viral1010** [appium/appium#9452]
## The problem
I'm trying to automate the iOS application that is already installed on the iPad (Distributed by Catalog app (Similar like TestFlight)). I'm able to launch the application using bundleID and after the application launch, try to find the application element.but only getting only for the screen not the element inside the screen. 

I've tested it also one other application with similar condition and also faced this.

## Environment

* Appium version (or git revision) that exhibits the issue:
1.7.1
* Last Appium version that did not exhibit the issue (if applicable):
1.6.5,1.7.0
* Desktop OS/version used to run Appium:
Mac OS 10.12.6 (16G29)
* Node.js version (unless using Appium.app|exe):

* Mobile platform/version under test:
10.3.3 / 10.3.2 
* Real device or emulator/simulator:
iPad mini 4
* Appium CLI or Appium.app|exe:
Appium Desktop 1.2.3
## Link to Appium logs
https://gist.github.com/Viral1010/e1b1ea496c530b06a67e9441318c86b0

**Comment by imurchie** [comment]
Xcode does not seem to be able to find your device: "Unable to find device with identifier: 97f7deccd2969f4c83d1f888dd73cc46e7ba5951"

**Comment by mykola-mokhnach** [comment]
If the elements you are trying to locate are inside a webview then you must switch the context first. Check hybrid applications automation for more details.

Also, avoid using xpath locators with native context whenever possible. Check https://github.com/facebook/WebDriverAgent/wiki/How-To-Achieve-The-Best-Lookup-Performance fore more details.

**Comment by Viral1010** [comment]
@imurchie Sorry my bad, I have updated the gist, this is the new appium log where application is launched and appium desktop inspecteor as well.

**Comment by Viral1010** [comment]
@mykola-mokhnach I have checked that with following code 

  Set<String> contextNames = driver.getContextHandles();
	    System.out.println(contextNames.size());
	    for (String contextName : contextNames) {
	    	System.out.println(contextName);

and it will displayed me that app has only NATIVE_APP Context

**Comment by mykola-mokhnach** [comment]
If you know for sure, that it is still the native context then try to change your locator. And yes, there is a possibility to hide elements from being accessible programatically.

**Comment by Viral1010** [comment]
If you don't mind, If you known such case, or property  thenCan you share it,  that is required from developer side to run scripts or inspect element sucessfully ? it would be a great help for me.

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium/issues/6517
