### ISSUE TITLE
Appium Tapping by x and y coordinates in landscape mode lands a tap in wrong place

### ISSUE THREAD

**Issue by Faraen** [appium/appium#9453]
## The problem

Currently when tapping by x and y coordinates everything works fine for portrait mode, but when trying to tap in landscape application, taps occur in incorrect places. I have created a test app to get more information about this issue, and from it I have concluded that in landscape application appium still taps like in portrait mode but with origin moved from top left to top right. It's hard to explain so I will attach gifs from my app, that shows at which % of the screen the tap was requested and where it actually landed. Currently in order to do a workaround, I would have to provide negative y coordinates to appium to tap on the right side of the screen, restrict the x coordinate to not exceed the actual screen height and use top right corner as coordinates origin in my landscape apps.

## Environment

Appium 1.7.1
appium 1.6.5
Mac OS
Xcode 9.0

## Details

The **correct** Portrait mode:
https://drive.google.com/file/d/0Bw6TwgnL4URON1pBVkRrNnJ6Qlk/view?usp=sharing

the **problematic** Landscape mode, note that the bottom of the screen taps should be lower but they would than be out of the screen:
https://drive.google.com/file/d/0Bw6TwgnL4URObVNaMTBOY3VwY3M/view?usp=sharing

**Comment by mykola-mokhnach** [comment]
Try Appium@beta. This problem should be addressed there.

**Comment by mykola-mokhnach** [comment]
make sure the xcuitest driver component version is 2.54+

**Comment by Faraen** [comment]
thank you for quick reply, I will try and update if it fixed the problem, sadly I won't be able to do that till monday.

**Comment by Faraen** [comment]
I have checked the beta and newest 2.54.2 xcuitest driver and while somewhat it is better, it's still faulty. when I am supplementing the driver press Touch action with x,y coordinates based on the calculation (x%of the screen * driver.get_window_size()['width'] etc. than taps for the left side of the screen (below 50% of the screen width) are tapped correctly , while those above 50% mark are showing on the left screen side. The result of those taps you can see here(both left taps and the middle of the screen taps are ok, the 2 between them are supposed to be on the far right of the screen) :
https://drive.google.com/file/d/0Bw6TwgnL4UROb1U2RE5BeFNQU2s/view?usp=sharing
When I try to supplement the coordinates by multiplying x% by real screen width (because driver.get_window_size() returns half of the real device with and height values), than it starts to look better, but the tap that is supposed to be in top left corner is messed up:
https://drive.google.com/file/d/0Bw6TwgnL4UROYlYzNHRmQi1MQ2c/view?usp=sharing
The coordinates shown on the screenshoots are calculated from top left corner using the real device screen size. I have no idea where the problem lies, only a feeling that when tap occurs in the area of driver window size, it is somewhere multiplied by 2.

**Comment by mykola-mokhnach** [comment]
Try to rely on some element rather than on absolute screen coordinates while performing tap.

**Comment by Faraen** [comment]
unfortunately I can't do that, In my tests I can use only absolute coordinates.

**Comment by mykola-mokhnach** [comment]
Try the the first element of XCUIElementTypeWindow class. It usually represents the main application window..

**Comment by Faraen** [comment]
Didn't test your idea yet but as for now I made a workaround. In portrait mode applications i don't do any changes, as it works fine but for landscape applications i firstly use real device screen dimensions to calculate coordinates and if the coordinate is within driver.get_window_size bounds with x and y sizes swapped, because it seems that the area that creates the "doubling of the coordinates" is in "portrait" orientation, than I divide it by 2, and for now it works perfectly fine.

**Comment by mykola-mokhnach** [comment]
You probably got the same issue as described [here](https://github.com/mykola-mokhnach/Appium-iOS-Inspector/issues/26)
Send kudos to Apple for implementing landscape mode support so "nicely: in XCTest
