### ISSUE TITLE
The bundle “WebDriverAgentRunner” couldn’t be loaded because it is damaged or missing necessary resources. 

### ISSUE THREAD

**Issue by dmshantanu** [appium/appium#9455]
## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Last Appium version that did not exhibit the issue (if applicable): 1.6.4 on a different machine
* Desktop OS/version used to run Appium: Mac OS Sierra 10.12.6
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
* Real device or emulator/simulator:Real Device
* Appium CLI or Appium.app|exe: Appoum CLI

## Details
I tried following :
1. I uninstalled and reinstalled appium 1.6.4 multiple times. 
2. Uninstalled and reinstalled xcode 8.3.2
3. rm -rf ~/Library/Developer/Xcode/DerivedData/WebDriverAgent-*
4. Download dependencies  ./Script/bootstrap -d

Still I am getting this error. 

## Link to Appium logs

https://gist.github.com/dmshantanu/4e79e2cc91f74712ac6dc28947f60a44

**Comment by mykola-mokhnach** [comment]
error code 65 usually means problems with code signing. Make sure you follow https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md

**Comment by dmshantanu** [comment]
I have followed all these steps. I have 2 setups on 2 different machines working using these steps.
This is the 3rd setup I am trying to work on and seeing this issue. I see in the logs that "Reason: no suitable image found."  Looks like some resource is missing

**Comment by mykola-mokhnach** [comment]
I assume in this case it cannot sign the third-party framework and complains about this framework cannot be included into the WDA build

**Comment by dmshantanu** [comment]
I am not sure why this is happening only on my current setup and not on other 2 working setups which I created using the same set of instructions.

**Comment by dmshantanu** [comment]
I built the WDA using xcode and installed it on the iPhone using my current setup. Then I triggered my tests by connecting the iphone to the already working setup.
It just works fine. It is only when I connect the iphone to my current setup I get this error. This is forcing me to think that something is wrong with current setup in spite of following the instructions. I would greatly appreciate your help here.

**Comment by saikrishna321** [comment]
Closing as user-side issue

**Comment by Muggle-Du** [comment]
have you worked out the solution? I have met the same problem as you.

**Comment by dmshantanu** [comment]
I upgraded to latest version appium.
