### ISSUE TITLE
Unable to switch ios chrome native_app context to Webview context

### ISSUE THREAD

**Issue by Elangopalakrishnan** [appium/appium#9456]
## The problem

I launched chrome ios app as native_app after that i couldn't able to switch the context

`var capabilities = new DesiredCapabilities();
                    capabilities.SetCapability(CapabilityType.BrowserName, "Chrome");
                    capabilities.SetCapability("automationName", "XCUITest");
                    capabilities.SetCapability(MobileCapabilityType.DeviceName, "iPhone 6s");
                    capabilities.SetCapability(MobileCapabilityType.PlatformName, "iOS");
                   
                    capabilities.SetCapability("bundleId", "com.google.chrome.ios");
                    capabilities.SetCapability(MobileCapabilityType.PlatformVersion, "11.0.2");
                    capabilities.SetCapability("realDeviceLogger", "/usr/local/lib/node_modules/deviceconsole/deviceconsole");
                    capabilities.SetCapability("wdaLocalPort", "8100");
                    capabilities.SetCapability("udid", "<udid>"); 
                    capabilities.SetCapability("newCommandTimeout","120000");
                    mkConstants.AppDriver = new IOSDriver<AppiumWebElement>(new Uri("http://127.0.0.1:4723/wd/hub"), capabilities, TimeSpan.FromSeconds(600));
 `

Switch to Context View:
`foreach (var c in mkConstants.AppDriver.Contexts)
                        {
 
                            if (c.Contains("WEBVIEW"))
                            {
                                mkConstants.AppDriver.Context = c.ToString();
                            }
                        }`

## Environment

Appium 1.7.1
Visual c#

## Details

I started ios-webkit-debug-proxy

**Comment by mykola-mokhnach** [comment]
Please attach the server log
