### ISSUE TITLE
"requires 1 parameters but 0 were supplied in the @Test annotation" exception gets while running the app suite in AWS device farm

### ISSUE THREAD

**Issue by Logakarti** [appium/appium#9457]
## The problem
The error gets "requires 1 parameters but 0 were supplied in the @Test annotation" while running the app suites in AWS device farm. How to resolve this error?  

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Mobile platform/version under test: 6.0
* Real device or emulator/simulator: LG Nexus 5

## Link to Appium logs
https://gist.github.com/Logakarti/6c88ca8849be9df577e888790a081092

## Code To Reproduce Issue [ Good To Have ]

@SeleniumTest(assertion= SeleniumTest.AssertionType.HARD, driver= SeleniumTest.DriverType.APPIUMDRIVER)
    @Test(groups = {"LaunchApp", "PracticeApp", "PracticeAppSmoke"}, priority = 0)
    public void verifyAppInstalled(Map<String, String> map)
    {
        assertThat(appium.isAppInstalled("org.ck12.app.practice")).as("verify app is installed").isTrue();
    }

@SeleniumTest(assertion= SeleniumTest.AssertionType.HARD, driver= SeleniumTest.DriverType.APPIUMDRIVER)
    @Test(groups = {"LaunchApp", "PracticeApp", "PracticeAppSmoke"}, priority = 3)
    public void verifyJoinWithGoogleID(Map<String, String> map)
    {
        assertThat(landingPage.openPage().selectJoin().openPage().signUpWithEmail("Practice Test", "create_new", "true").openPage()).
                as("verify join with google id").isInstanceOf(HomePage.class);
        homePage.getHeader().selectRightMenu().openPage().performSignOut();
    }

**Comment by mykola-mokhnach** [comment]
Closed as server unrelated. If you think this is an issue in java lib then please report it to https://github.com/appium/java-client/issues
