### ISSUE TITLE
[appium1.7.1][android 7.1]- Testing run is blocked due to reinstall io.appium.settings

### ISSUE THREAD

**Issue by lavi-xu** [appium/appium#9458]
## The problem

On RedMi Note 5A (android 7.1), there always is an alert to user on install apk over usb(cannot be disabled).  To a workaround we have to install apks before run testing manually. 

Now appium will do uninstall/install io.appium.settings each session:
    adb.installOrUpgrade(_ioAppiumSettings.path, SETTINGS_HELPER_PKG_ID, true)

This blocks our testing because there is no way to dismiss that alert (a workaround is remove "true" option).

I would like to have a new cap for this kind of "force upgrade xxxx".

Thanks.

**Comment by mykola-mokhnach** [comment]
@imurchie FYI

**Comment by mykola-mokhnach** [comment]
Also the reinstall before each session adds a significant delay while executing multiple tests.

**Comment by lavi-xu** [comment]
@mykola-mokhnach 

Yes, it spends 20s before, now it normal takes 35s to launch apk.

**Comment by imurchie** [comment]
The latest code ought to be fixed.

**Comment by mvanini** [comment]
@mykola-mokhnach, it would be nice to achieve your suggestion: we have more than 250 tests on same devices in our suite and much time will be lost in reinstall same utility-app installed few minutes before. 
Will that tracked by this issue or in a new one? 
Thanks
