### ISSUE TITLE
Appium Inspector. No ability to switch between native view and webview

### ISSUE THREAD

**Issue by kdthomas2121** [appium/appium#9459]
## The problem

When testing hybrid apps, the inspector is almost useless, as all it returns is "AX error -25205" for every element. If there was a way we could run driver.set_context from the inspector it would be so much more useful. 

Environment
iOS 
Appium 1.7.1

**Comment by mykola-mokhnach** [comment]
"AX error" is the [known](https://github.com/facebook/WebDriverAgent/issues/703) WebDriverAgent issue.

If you'd like to create a feature request for Appium Desktop then please do it in https://github.com/appium/appium-desktop/issues
