### ISSUE TITLE
 simctl error running 'uninstall'

### ISSUE THREAD

**Issue by reach2jeyan** [appium/appium#9461]
I am trying to run 5 simulators in parallel using multiple appium ports and wdalocalport. I am encountering this error below in all my simulators except 1

The last time I had bypassed this error by launching the webdriver agent manually by launching a session in the appium GUI and then running my suite. Is this error because of appium unable to find the `webdriver` agent on session launch?

I am using `Appium 1.7.0` and `Xcode9`

`Encountered internal error running command: Error: simctl error running 'uninstall': An error was encountered processing the command (domain=LSApplicationWorkspaceErrorDomain, code=111):`

**Comment by mykola-mokhnach** [comment]
Please provide the full server log and proper steps to reproduce the issue.

**Comment by reach2jeyan** [comment]
@mykola-mokhnach 

PFA the[ logs](
https://gist.github.com/reach2jeyan/c78831a2c6bb88f075abbc22ceb6f07b)

**Comment by mykola-mokhnach** [comment]
Try to set useNewWDA capability to _false_

**Comment by reach2jeyan** [comment]
Ahhhh! Yes! I just saw it ...! Damn!

**Comment by mykola-mokhnach** [comment]
The fix has been merged to master and will be available in the next beta
