### ISSUE TITLE
iOS real device unable to see web views using newest versions of iOS, Xcode and Appium.

### ISSUE THREAD

**Issue by srigney** [appium/appium#9463]
## The problem
I recently received a new Mac and now the iOS automation can no longer see web views on the iPhone.

## Environment

* Appium version (or git revision) that exhibits the issue: **1.7.1**
* Last Appium version that did not exhibit the issue (if applicable): **1.6.4**
* Desktop OS/version used to run Appium: **iOS 10.12.6**
* Node.js version (unless using Appium.app|exe): **6.10.3**
* Mobile platform/version under test: **11.0**
* Real device or emulator/simulator: **Real device**
* Appium CLI or Appium.app|exe: **CLI**

## Details

Our iOS automation has been running fine for the past year. We recently received a new Mac laptop with newer versions of iOS and Xcode. So I also had to update our iPhone 6 to iOS 11. Once this was all done I am no longer able to see web views. I do have the iOS-webkit-debug-proxy running also.

The app is launched successfully but fails when no webviews are found.

## Link to Appium logs

https://gist.github.com/srigney/4eb055ad5115b4e27a384a6a1cb01b69

## Code To Reproduce Issue [ Good To Have ]

Caps:
DeviceName           iPhone 6
PlatformName        iOS
PlatformVersion     11.0
automationName   XCUITest
REMOTE_URL        http://localhost:4723/wd/hub
UDID                      59c540e7e9c8d630c0f240bee7305cc82e70ace0
autoWebview        True (I didn't used to have this set, but some of the discussions said to try this)

I'm also sending the xcodeOrgId and the xcodeSigningId

**Comment by mykola-mokhnach** [comment]
Try to update the webkit debuggerto the most recent version

**Comment by srigney** [comment]
I did that...
Pouring ios-webkit-debug-proxy-1.8.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/ios-webkit-debug-proxy/1.8: 13 files, 328.8KB

Same result - no web views.

**Comment by mykola-mokhnach** [comment]
Appium itself is just a client and cannot do much if IWDP does not return anything

**Comment by srigney** [comment]
so do I need to log an issue in the IWDP project?

**Comment by mykola-mokhnach** [comment]
Yep, I'd try to figure our why IWDP does return an empty array.

**Comment by srigney** [comment]
ok, thanks! I will add the issue to that project.
