### ISSUE TITLE
Cannot access iframe content on iOS test due to same-origin policy

### ISSUE THREAD

**Issue by daisy1754** [appium/appium#9464]
## The problem

I have a test that verify if iframe content from server A is properly loaded on website B (A and B have a different domain). We run this test across browsers and environments provided by https://www.browserstack.com and it only fails on iOS. According to browserstack support

> For iOS emulators, there is a issue interacting with elements when switching to an iframe with cross origin. As Appium uses javascript for most commands it will fail for cross origin request. Here, the ios_webkit_proxy throws an error when you try to execute some javascript. Currently, there is no workaround to the issue.

Minimum reproducible pseudo code is like below

```
browser.frame(nameOfFrame)
browser.click(selector) // this fails since it's inside iFrame
```

I realize similar issues have been reported in the past ( #5560 #5553 #5832 ) but all are closed now so opening a new issue here, hoping if someone in the team can take another look. 
I also contacted apple support team and told below:

> You seem to be filing a bug about Appium’s 3rd party WebDriver support for iOS. Apple does not maintain this software. Apple’s 1st party support for WebDriver only extends to Mac Safari, not iOS Safari. Please file an issue on their project’s bug tracker:
> https://github.com/appium/appium/issues

## Environment

We run test with webdriverio
- WebDriverIO 4.6.2
- iPhone 7 (Real device)

Please let me know any other information is needed. Thanks!

**Comment by mykola-mokhnach** [comment]
@jlipps shall we keep the issue opened?

**Comment by imurchie** [comment]
This is a restriction from Apple. There is nothing that Appium can do. The only workaround we've found: https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/cross-domain-iframes.md
