### ISSUE TITLE
Can find element by inspector but not able to find though Java code

### ISSUE THREAD

**Issue by niu0220** [appium/appium#9466]
## The problem
there is no problem to use inspector to find the button and tap, but it won't work if using 

WebElement btn = driverWait.until(ExpectedConditions.elementToBeClickable(MobileBy.AccessibilityId(id)));
btn.click();

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:   10.12.6
* Node.js version (unless using Appium.app|exe): v8.6.0
* Mobile platform/version under test: simulator iphone 5s 10.3.1
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: appium desktop
[appium-log.txt](https://github.com/appium/appium/files/1389499/appium-log.txt)

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

WebElement btn = driverWait.until(ExpectedConditions.elementToBeClickable(MobileBy.AccessibilityId(id)));
btn.click();

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by Brad19** [comment]
I'm also facing a very similar issue. Can someone pls advise

**Comment by saikrishna321** [comment]
@niu0220 pls post complete logs as gist

**Comment by mykola-mokhnach** [comment]
Try to print the page source before/after the explicit wait to check if the element is there and it is visible. The "dynamic' UI state during the test is running might be different from what you see in the inspector. Also, there might be some other element with duplicated id.

**Comment by niu0220** [comment]
@saikrishna321 Here are the logs with inspector & running Java code
**inspector**
[appium-inspector-logs.txt](https://github.com/appium/appium/files/1392753/appium-inspector-logs.txt)
**Java code**
[appium-server-logs.txt](https://github.com/appium/appium/files/1392752/appium-server-logs.txt)

Hi @mykola-mokhnach, I have am sure the element shows, but I am not able to find it through Java code no matter I am using ExpectedConditions.elementToBeClickable, or findElementByAccessibilityId(i). I also tried xpath but not no luck.

Thanks

**Comment by mykola-mokhnach** [comment]
Please attach the page source and the mention which id you are trying to locate.

**Comment by niu0220** [comment]
Hi @mykola-mokhnach, attached page resource, and I do see the button "camera_timeline" in page and it should be visible, but in log visible="false". 

[getPageResource.txt](https://github.com/appium/appium/files/1396648/getPageResource.txt)

**Comment by mykola-mokhnach** [comment]
Visibility value is defined by your app and returned by WebDriverAgent. There is nothing we can change there on Appium side.

**Comment by niu0220** [comment]
Hi @Mykola-mokhnach

I have another example:
in app, if user click 'type="XCUIElementTypeStaticText" value="Take snapshot"', and radio button status is changed like ''<XCUIElementTypeButton type="XCUIElementTypeButton" name="radiobox selected"' or "<XCUIElementTypeButton type="XCUIElementTypeButton" name="radiobox selected"

The wired thing is  appium finds ID and perform "click", but there is no changed on radio button.

attached page-resource, and appium log
[appium-log.txt](https://github.com/appium/appium/files/1436098/appium-log.txt)
[page-resource.txt](https://github.com/appium/appium/files/1436099/page-resource.txt)

Thanks
