### ISSUE TITLE
Tests are not running on simulators after upgrading Appium to 1.7.1 

### ISSUE THREAD

**Issue by LoveleenSaini** [appium/appium#9467]
## The problem
After upgrading Appium to 1.7.1 I tried running tests on 2 versions of simulators (iOS 11.0 and 9.3) but they failed on both simulators with different issues.

- Simulator on iOS 11.0 - Appium gets stuck at _[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body:_
[Appium Log](https://gist.github.com/LoveleenSaini/9598e57301c56cf4393b591f9db0e0b0)
- Simulator on iOS 9.3 - Tests fail with error _[XCUITest] xcodebuild exited with code '65' and signal 'null'_
[Appium Log](https://gist.github.com/LoveleenSaini/445d32082fb2b305da79cabec8600d96)

## Environment
* Appium version: 1.7.1
* Desktop OS/version used to run Appium: mac
* Mobile platform/version under test: iOS 11.0 / 9.3
* Real device or emulator/simulator: simulator

**Comment by mykola-mokhnach** [comment]
set different _wdaLocalPort_ values if you run tests on the same machine with different simulators.

**Comment by deedora** [comment]
I get the first one often. Test does starts after few minutes (like 5-10) but that shouldn't happen.

**Comment by LoveleenSaini** [comment]
Just to make it clear, this is what I am doing: 
Start Appium server > initialise driver and run tests on simulator 1 (iOS 11.0) > quit driver > create a new driver instance and run tests on simulator 2 (iOS 9.3) > quit driver > stop server

@mykola-mokhnach I have set different wdaLocalPort values but the first issue is still there. Appium gets stuck at this step for 5-10 minutes when running tests on simulator running  on iOS 11.0
`[JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"nz.co.vista.MobileCinema.ABC","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}` 

And on simulator running on iOS 9.3 it fails with error 
`null value in entry: browserName=null`

**Comment by mykola-mokhnach** [comment]
These are different problems then. Don't mix them all into the single issue description and describe a separate issue for each problem (+ provide all the necessary info/logs)

Closed as fixed.

**Comment by LoveleenSaini** [comment]
Thanks for looking into the issues. Will log them separately later.
We have reverted Appium to 1.6.5, our last stable version before upgrading.

**Comment by alvy54** [comment]
Try setting waitForQuiescence to false.

**Comment by Amittallewar** [comment]
Hey,
