### ISSUE TITLE
Not able to switch to WEBVIEW_chrome  from a native app

### ISSUE THREAD

**Issue by abisekkachroo** [appium/appium#9469]
## The problem
I have a native android app and I am getting the error after swicthing the context to the webView 

## Environment
Appium 1.7.1 ,Selenium StandAlone Jar, Android 6.0.1

## Details
I am getting this error message 
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: chrome not reachable
Do I need to install something else

## Link to Appium logs
Link of gist for my appium logs
https://gist.github.com/abisekkachroo/42b6cd36e533071a3dbe605e426cc915

## Code To Reproduce Issue 
Here is  the code of my capabilities class 

public class BaseTestForFaceBookLogin {
	static AndroidDriver<AndroidElement> driver =null;
	static DesiredCapabilities cap;
	
	@BeforeTest
	public static AndroidDriver<AndroidElement> SetUpForDriver() throws MalformedURLException{
		System.out.println("creating device for faceBookLogin");
			if(driver == null){
			synchronized(BaseTest.class){
				cap = new DesiredCapabilities();
				cap.setCapability(MobileCapabilityType.PLATFORM_NAME, "Android");
				cap.setCapability(MobileCapabilityType.PLATFORM_VERSION, "6.0.1"); 
				cap.setCapability(MobileCapabilityType.DEVICE_NAME, "45fc7067ce40");  
				cap.setCapability("appPackage", "com.edmobilelabs.sling.beta");     
				cap.setCapability("appActivity", "com.edmobilelabs.sling.ui.ScrSplash"); 
				cap.setCapability("setWebContentsDebuggingEnabled", "true");
				driver = new AndroidDriver<AndroidElement>(new URL("http://127.0.0.1:4723/wd/hub"), cap);
			}
		}
		return driver;
	}

After clicking on button App launches the webView where I have to click on "Continue"  button 
My driver is not able to find the id of the element or Xpath
Set<String> contextNames2 = driver.getContextHandles();
		for(String s: contextNames2){
			System.out.println("Contexts are "+s);
			if(s !="NATIVE_APP"){
				driver.context(s); // My code get stucked here 
![switchingcontexts](https://user-images.githubusercontent.com/22616085/31655222-dda286c6-b345-11e7-99bc-254c8a8377e8.png)

			}
		}

**Comment by mykola-mokhnach** [comment]
Make sure you use correct chromedriver binary. Read https://github.com/appium/appium/blob/aa9711817436cb0bd7962c3f85db6efe2c9c8d02/docs/en/writing-running-appium/web/chromedriver.md for more details

**Comment by abisekkachroo** [comment]
@mykola-mokhnach 
Are there different versions for different api Level of android ?
If it is Can u please tell where to find the correct version of chrome driver for Android 6.0.1(Api level 23)
And one more thing are my capabilities correct or is there something more to add

**Comment by mykola-mokhnach** [comment]
chromdriver version does not depend on OS version, but rather on browser/webview component version bundled with it.

**Comment by abisekkachroo** [comment]
I used npm install appium --chromedriver_version="2.16"
and then again after running the testcase 
in the logs I am getting 
[Chromedriver] Set chromedriver binary as: /tmp/.mount_iyenBP/usr/bin/resources/app/node_modules/appium/node_modules/appium-chromedriver/chromedriver/linux/chromedriver_64
[Chromedriver] Killing any old chromedrivers, running: pkill -15 -f "/tmp/.mount_iyenBP/usr/bin/resources/app/node_modules/appium/node_modules/appium-chromedriver/chromedriver/linux/chromedriver_64.*--port=8000"
[Chromedriver] No old chromedrivers seemed to exist
What should I do exactly , I am not able to get that

**Comment by dineshchakravarthy5** [comment]
@abisekkachroo 
I am also unable to switch to webview , did you find any solution or work around for this?
Thanks in advance.

**Comment by kommuswamy** [comment]
Hi @mykola-mokhnach ,

I have a little bit confused here, I am opening the web application inside the emulator and I have wrot the XPath by using Emulator inspector,  Here my question is the XPath is native or web?

Ex: '//android.webkit.WebView[@content-desc="App Login"]//android.widget.EditText'

When I wrote the above XPath, am not able to get the reference in protractor


Thanks :)

**Comment by abisekkachroo** [comment]
I have found a workaround it will work on Android versions lower than 7

**Comment by thedefside** [comment]
Having the same issue. test fails at driver.context("WEBVIEW_chrome");

Appium 1.7.1
Android 7.0
ChromeDriver 2.33

With error io.appium.java_client.NoSuchContextException: An unknown server-side error occurred while processing the command. Original error: chrome not reachable

@abisekkachroo did you find a workaround?  Mind sharing it?

**Comment by hansjoergkeser** [comment]
@thedefside sounds like the desired context wasn't available. Check the appium log for these entries
[AndroidDriver] Found webviews: ["WEBVIEW_tld.yourapp.android","WEBVIEW_chrome"]
[debug] [AndroidDriver] 
Available contexts:["NATIVE_APP","WEBVIEW_tld.yourapp.android","WEBVIEW_chrome"]

if WEBVIEW_chrome is missing the browser was not opened. Maybe a different browser was opened instead?

**Comment by vijenkamboj** [comment]
@hansjoergkeser :-could you post then how to proceed as I am also seeing only two contexts
AppLogin() :: driver.start() executed
Total No of Context Found Before reaching WebView = 2
Context Name is [NATIVE_APP, WEBVIEW_com.ecifm.otgservices]

**Comment by vijenkamboj** [comment]
Thanks I will respond

**Comment by vijenkamboj** [comment]
Let me check once again I saw one chrome browser opened in the back ground
sometimes will give u full scenario thanks

**Comment by cuhavp** [comment]
I have the same issue:
Appium 1.7.2
Chrome Android: 66
chromedriver=2.38.552518 
Error: Failed to start Chromedriver session: An unknown server-side error occurred while processing the command. (Original error: unknown error: Failed to get sockets matching: @webview_devtools_remote_.*4531
  (make sure the app has its WebView configured for debugging)
  (Driver info: chromedriver=2.38.552518 (183d19265345f54ce39cbb94cf81ba5f15905011),platform=Mac OS X 10.12.6 x86_64))
    at Object.wrappedLogger.errorAndThrow (/usr/local/lib/node_modules/appium/node_modules/appium-support/lib/logging.js:69:13)
    at Chromedriver.callee$2$0$ (/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/lib/chromedriver.js:217:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>

Caused by: io.appium.java_client.NoSuchContextException: An unknown server-side error occurred while processing the command. Original error: Failed to start Chromedriver session: An unknown server-side error occurred while processing the command. (Original error: unknown error: Failed to get sockets matching: @webview_devtools_remote_.*4531
  (make sure the app has its WebView configured for debugging)
  (Driver info: chromedriver=2.38.552518 (183d19265345f54ce39cbb94cf81ba5f15905011),platform=Mac OS X 10.12.6 x86_64)) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.7.1', revision: '8a0099a', time: '2017-11-06T21:01:39.354Z'
System info: host: 'LVNHCMAC0000140', ip: '169.254.70.14', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_131'
Driver info: io.appium.java_client.AppiumDriver

**Comment by hansjoergkeser** [comment]
@cuhavp I noticed the line
"(make sure the app has its WebView configured for debugging)"
Does your app open a webview/custom tab? If yes, make sure debugging is enabled. E.g. on Android see answer
"The solution is to turn on debuggable flag (debuggable true) in application's gradle file:"
https://stackoverflow.com/questions/26593927/android-studio-no-debuggable-applications

**Comment by hansjoergkeser** [comment]
@abisekkachroo yes, this is possible. But the webview context grants you different selectors to identify browser elements easier (by all the tags and their properties).

**Comment by cuhavp** [comment]
@hansjoergkeser,

When i tried to click on Support button on my app, then Chrome browser opened support page,
This issue happen when I using driver.context("WEBVIEW_Chrome") to switch to browser and verify support URL.

**Comment by hansjoergkeser** [comment]
then it is outside your app the chrome browser itself? in the appium log where you try to switch the context, what does it say about available contexts and found webviews? (see my comment above for an example)

**Comment by hansjoergkeser** [comment]
In your log if find 
Available contexts: ["NATIVE_APP","WEBVIEW_chrome"]
so your code driver.context("WEBVIEW_Chrome") is correct. 
But the information about the webview version is missing.
During my tests i see s.th. like this one or two line above the "Got response with status 200 ..." and the error message following:
[debug] [Chromedriver] Webview version: 'Chrome/66.0.3359.126'

Make sure the chrome webview version is suitable to the chromedriver version (should be 64, 65 or 66), see
http://chromedriver.storage.googleapis.com/2.38/notes.txt

Unfortunately switching the context does also not work in my tests:
https://github.com/appium/appium/issues/10203

Guess we have to wait until a solution there is found.

**Comment by cuhavp** [comment]
@hansjoergkeser 

I did that, I'a using latest chrome driver as-well.

**Comment by cuhavp** [comment]
@hansjoergkeser 

I found a solution for this case, Chrome is like a native app so I used
driver.findElement(By.id("com.android.chrome:id/url_bar")).text command to get current URL

**Comment by hansjoergkeser** [comment]
yes that works but grants you less possibilites to identify elements in the browser

**Comment by hansjoergkeser** [comment]
no idea why this ticket is closed, it still doesn't work as supposed. But maybe this new appium 1.9.0 feature helps:
"New desired capabilities:
    chromedriverUseSystemExecutable - boolean flag to use the default Chromedriver
    installed with Appium, avoiding any attempt to find correct Chromedriver."
https://discuss.appium.io/t/appium-1-9-0-released/23346
Will try that soon.

**Comment by ashishyadav2020** [comment]
@mykola-mokhnach  getting same error that @martinschneider had.

Appium version:  Appium 1.7 (desktop)
Chromedriver: 2.41
Chrome: 69

Cordova used withing my App, any suggestion?

**Comment by aliser** [comment]
the same things here ...
"unknown error: Failed to get sockets matching: @webview_devtools_remote_.*18903\n  (make sure the app has its WebView configured for debugging)\n  (Driver info: chromedriver=2.42.591059 (a3d9684d10d61aa0c45f6723b327283be1ebaad8),platform=Mac OS X 10.13.6 x86_64)"}}

**Comment by ashishyadav2020** [comment]
@mykola-mokhnach any resolution will really help us.

**Comment by tumilover** [comment]
I am also experiencing the same issue. Please help

**Comment by nghiadhd** [comment]
I think we should change the code in app to turn on debugging mode for WebView

https://developers.google.com/web/tools/chrome-devtools/remote-debugging/webviews

**Comment by vanlong-nox** [comment]
Sorry, this problem has been solved or not.
