### ISSUE TITLE
Appium crashes often

### ISSUE THREAD

**Issue by McMagnus** [appium/appium#9470]
## The problem

When running my tests, Appium often crashes after a while. It might be connected to the frequent push_file/pull_file I'm doing in the tests, but I haven't really verified this.

The crash is caused by an attempt to access address 0x00000000.

## Environment

* Appium version 1.7.1
* Also crashed on 1.7.0 and some version before that. Haven't tried a version where it didn't crash.
* Windows 7
* using Appium.exe
* Running two Android phones. OnePlus5 7.1.1 and Samsung S5 6.0.1

## Link to Appium logs

Unable to gen logs. When trying to start Appium with logging (by pressing Advanced in the Appium desktop and enter a logfile name, it just fails to start)

**Comment by mykola-mokhnach** [comment]
Can you describe what exactly crashes - Appium Desktop application or the appium server process? Do you have any screenshots or [event logs](https://kb.acronis.com/content/8859)?

**Comment by McMagnus** [comment]
Thanks for quick reply. I'll install VS and try to get some more info. Will post a screenshot at the next crash.

**Comment by McMagnus** [comment]
Found the log files in AppData\Local\Temp, two (probably more) similar endings seems to indicate the pull_file function:

[debug] [ADB] Running 'C:\Programs\Android\AndroidStudioSDK\platform-tools\adb.exe' with args: ["-P",5037,"-s","279e4a5e","pull","/sdcard/dirname/dirname/dirname/File11.txt","C:\\Users\\Magnus\\AppData\\Local\\Temp\\appium117917-7924-es9wuk.55lui8uxr.tmp"][debug] [MJSONWP] Responding to client with driver.pullFile() result: "AAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8gISIjJCUmJygpKissLS4vMDEyMzQ1Njc4OTo7PD0+P0BBQkNERUZHSElKS0xNTk9QUVJTVFVWV1hZWltcXV5fYGFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6e3x9fn+AgYKDhIWGh4iJiouMjY6PkJGSk5SVlpeYmZqbnJ2en6ChoqOkpaanqKmqq6ytrq+wsbKztLW2t7i5uru8vb6/wMHCw8TFxsfIycrLzM3Oz9DR0tPU1dbX2Nna29zd3t/g4eLj5OXm5+jp6uvs7e7v8PHy8/T19vf4+fr7/P3+AAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8gISIjJCUmJygpKissLS4vMDEyMzQ1Njc4OTo7PD0+P0BBQkNERUZHSElKS0xNTk9QUVJTVFVWV1hZWltcXV5fYGFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6e3x9fn+AgYKDhIWGh4iJiouMjY6PkJGSk5SVlpeYmZqbnJ2en6ChoqOkpaanqKmqq6ytrq+wsbKztLW2t7i5uru8vb6/wMHCw8TFxsfIycrLzM3Oz9DR0tPU1dbX2Nna29zd3t/g4eLj5OXm5+jp6uvs7e7v8PHy8/T19vf4+fr7/P3+AAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8gISIjJCUmJygpKissLS4vMDEyMzQ1Njc4OTo7PD0+P0BBQkNERUZHSElKS0xNTk9QUVJTVFVWV1hZWltcXV5fYGFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6e3x9fn+AgYKDhIWGh4iJiouMjY6PkJGSk5SVlpeYmZqbnJ2en6ChoqOkpaanqKmqq6ytrq+wsbKztLW2t7i5uru8vb6/wMHCw8TFxsfIycrLzM3Oz9DR0tPU1dbX2Nna29zd3t/g4eLj5OXm5+jp6uvs7e7v8PHy8/T19vf4+fr7/P3+...
[info] [HTTP] <-- POST /wd/hub/session/a1ca76cd-bbd0-4eb9-a157-4c38fb757b8a/appium/device/pull_file 200 548 ms - 1399566

**Comment by mykola-mokhnach** [comment]
I assume https://github.com/appium/appium-desktop/issues will be a better place to report this issue. 
Also, make sure your Android SDK is up to date

**Comment by McMagnus** [comment]
No, I now run appium in a console and get out of memory after just pushing 2 160MB files.

And yes I know that's rather large files, but why can it handle one but now the 2nd (when the memory for the first should have been unallocated?)

[debug] [MJSONWP] Calling AppiumDriver.pushFile() with args: ["/sdcard/<dir>/File00.txt","AAECAwQFBgcICQoLDA0ODxAREhMUF
RYXGBkaGxwdHh8gISIjJCUmJygpKissLS4vMDEyMzQ1Njc4\nOTo7PD0+P0BBQkNERUZHSElKS0xNTk9QUVJTVFVWV1hZWltcXV5fYGFiY2RlZmdoaWprbG1ub3Bx\ncnN0dXZ3
eHl6e3x9fn+AgYKDhIWGh4iJiouMjY6PkJGSk5SVlpeYmZqbnJ2en6ChoqOkpaanqKmq\nq6ytrq+wsbKztLW2t7i5uru8vb6/wMHCw8TFxsfIycrLzM3Oz9DR0tPU1dbX2Nna2
9zd3t/g4eLj\n5OXm5+jp6uvs7e7v8PHy8/T19vf4+fr7/P3+AAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwd\nHh8gISIjJCUmJygpKissLS4vMDEyMzQ1Njc4OTo7PD0+
P0BBQkNERUZHSElKS0xNTk9QUVJTVFVW\nV1hZWltcXV5fYGFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6e3x9fn+AgYKDhIWGh4iJiouMjY6P\nkJGSk5SVlpeYmZqbnJ2en6C
hoqOkpaanqKmqq6ytrq+wsbKztLW2t7i5uru8vb6/wMHCw8TFxsfI\nycrLzM3Oz9DR0tPU1dbX2Nna29zd3t/g4eLj5OXm5+jp6uvs7e7v8PHy8/T19vf4+fr7/P3+AAEC\nAw
QFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8gISIjJCUmJygpKissLS4vMDEyMzQ1Njc4OTo7\nPD0+P0BBQkNERUZHSElKS0xNTk9QUVJTVFVWV1hZWltcXV5fYGFiY2RlZmd
oaWprbG1ub3BxcnN0\ndXZ3eHl6e3x9fn+AgYKDhIWGh4iJiouMjY6PkJGSk5SVlpeYmZqbnJ2en6ChoqOkpaanqKmqq6yt\nrq+wsbKztLW2t7i5uru8vb6/wMHCw8TFxsfIyc
rL...
[debug] [ADB] Running 'C:\Programs\Android\AndroidStudioSDK\platform-tools\adb.exe' with args: ["-P",5037,"-s","6f90b03b","push","C:\\U
sers\\Magnus\\AppData\\Local\\Temp\\appium117931-7108-1o13wps.57cbfyldi.tmp","/sdcard/<dir>/File00.txt"]
[debug] [MJSONWP] Responding to client with driver.pushFile() result: null
[HTTP] <-- POST /wd/hub/session/04273b9a-2ad9-4b62-aab3-7050920d8f60/appium/device/push_file 200 22326 ms - 76

<--- Last few GCs --->

  349792 ms: Mark-sweep 1269.9 (1386.9) -> 1269.8 (1318.9) MB, 72.0 / 0.0 ms [allocation failure] [GC in old space requested].
  349858 ms: Mark-sweep 1269.8 (1318.9) -> 1269.3 (1318.9) MB, 65.7 / 0.0 ms [allocation failure] [GC in old space requested].
  349954 ms: Mark-sweep 1269.3 (1318.9) -> 1269.1 (1282.9) MB, 95.1 / 0.0 ms [last resort gc].
  350012 ms: Mark-sweep 1269.1 (1282.9) -> 1269.1 (1282.9) MB, 58.6 / 0.0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 00000188850CF791 <JS Object>
    1: parse [native json.js:~61] [pc=000003B18E385B84] (this=00000188850C92B1 <a JSON with map 0000030649C09B09>,C=00000162C6254E69 <V
ery long string[229807301]>,w=0000018885004381 <undefined>)
    2: parse(aka parse) [C:\Users\Magnus\AppData\Roaming\npm\node_modules\appium\node_modules\body-parser\lib\types\json.js:89] [pc=000
003B18E2D8F80] (this=0000018885004381 <undefined>,body=00000162C6...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

**Comment by mykola-mokhnach** [comment]
We've made a small investigation on the problem and the [fix](https://github.com/appium/appium-support/pull/55) is coming soon. This memory leak is caused by a known bug/feature in NodeJS.
