### ISSUE TITLE
Cannot evaluate results for XPath expression 

### ISSUE THREAD

**Issue by avrahamShutterFly** [appium/appium#9471]
## The problem

App launch, execute login on app, and after that I print the page source, and I see my image element that I want to click on it, the test check if the image element is displayed  click and if not scroll down until you find this image. 

XPATH:
//XCUIElementTypeApplication[1]/XCUIElementTypeWindow[1]/XCUIElementTypeOther[3]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeCollectionView[1]/XCUIElementTypeCell[contains(@name,'Photo 0-1')]

There is a failure not error

## Environment
* Appium version (or git revision) that exhibits the issue:  1.7.1
* Last Appium version that did not exhibit the issue (if applicable): 1.6.5-beta
* Desktop OS/version used to run Appium: java eclipse
* Node.js version (unless using Appium.app|exe): 
* Mobile platform/version under test: V6.9.4
* Real device or emulator/simulator: simulator  iOS 11.0
## Details

 log:  
java.util.FormatFlagsConversionMismatchException: Conversion = b, Flags = 
at java.util.Formatter$FormatSpecifier.failMismatch(Formatter.java:4298)
at java.util.Formatter$FormatSpecifier.checkBadFlags(Formatter.java:2997)
at java.util.Formatter$FormatSpecifier.checkGeneral(Formatter.java:2955)
at java.util.Formatter$FormatSpecifier.(Formatter.java:2725)
at java.util.Formatter.parse(Formatter.java:2560)
at java.util.Formatter.format(Formatter.java:2501)
at java.util.Formatter.format(Formatter.java:2455)
at java.lang.String.format(String.java:2940)

appium log:
with body: {"using":"xpath","value":"//XCUIElementTypeApplication[1]/XCUIElementTypeWindow[1]/XCUIElementTypeOther[3]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeCollectionView[1]/XCUIElementTypeCell[contains(@name,'Photo 0-1']"}
07:01:49 Appium Output>[debug] [JSONWP Proxy] Got response with status 200: {"value":"Cannot evaluate results for XPath expression \"/XCUIElementTypeApplication[1]/XCUIElementTypeWindow[1]/XCUIElementTypeOther[3]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeCollectionView[1]/XCUIElementTypeCell[contains(@name,'Photo 0-1')]\"\n\n(\n\t0   CoreFoundation                      0x0000000107d331cb __exceptionPreprocess + 171\n\t1   libobjc.A.dylib                     0x0000000107695f41 objc_exception_throw + 48\n\t2   WebDriverAgentLib                   0x00000001222f70de +[FBXPath throwException:forQuery:] + 222\n\t3   WebDriverAgentLib                   0x00000001222f73f8 +[FBXPath findMatchesIn:xpathQuery:] + 504\n\t4   WebDriverAgentLib                   0x0000000122325b6a -[XCElementSnapshot(FBHelpers) fb_descendantsMatchingXPathQuery:] + 74\n\t5   WebDriverAgentLib                   0x0000000122301b83 -[XCUIElement(FBFind) getMatchedSnapshotsByXPathQuery:] + 179\n\t6   WebDriverAgentLib                   0x0000000122301c2f -[XCUIElement(FBFi...

**Comment by mykola-mokhnach** [comment]
Try [not to use xpath](https://github.com/facebook/WebDriverAgent/wiki/How-To-Achieve-The-Best-Lookup-Performance) locators at all. They are slow and suboptimal.

Regarding the exception itself - it happens inside WebDriverAgent and has nothing to do with Appium server itself. Please report it along with the device log (to have the full stacktrace) into https://github.com/facebook/WebDriverAgent/issues
