### ISSUE TITLE
Question: need to reboot mac to restart testing 

### ISSUE THREAD

**Issue by niu0220** [appium/appium#9479]
Hi everyone, 
Appium 1.7.1  (1.7.0 has same issue) is no response after running ~100 test cases (no logs, nothing displayed), and there is no use to restart Appium (kill process and restart appium). I have to reboot my mac to restart testing.  Does any one face the same issue as me??? not sure why...

**Comment by saikrishna321** [comment]
@niu0220 i have tested appium 1.7.X by running close to 250 TC with single server session and  works absolutely fine.

**Comment by mykola-mokhnach** [comment]
What is "no response"? Can you attach the logs?
It might be that XCTest creates huge amount of logs in temp folder, so your system is running out of space. Rebooting the computer resets these temp files automatically. Try to install Appium@beta and enable _clearSystemFiles_ capability to workaround that.

**Comment by niu0220** [comment]
Hi @saikrishna321, I am running my test cases ~9-10 hours, kill Appium process, and restart Appium  and running other set of test cases. If I want to restart my 2nd set of test cases I need to restart my mac.

HI my @mykola-mokhnach , I will have a try your way to see if I can avoid this issue. Attached the log when I started 2nd set of test cases.  
[appium-log.txt](https://github.com/appium/appium/files/1395457/appium-log.txt)

Thanks

**Comment by niu0220** [comment]
hi @mykola-mokhnach, the problem is not resolved when enabled clearSystemFiles capability... 
caps.setCapability("clearSystemFiles", true);

Appium is stopped... attached part of appium-log

[appium-log.txt](https://github.com/appium/appium/files/1424414/appium-log.txt)

**Comment by mykola-mokhnach** [comment]
> [HTTP] <-- GET /wd/hub/session/28134ba2-edfb-4b85-8c7c-5b656ffaa9c6/element/35A2867C-6D02-446F-A404-A4E08566F48B/displayed 200 156 ms - 76
> [HTTP] --> DELETE /wd/hub/session/28134ba2-edfb-4b85-8c7c-5b656ffaa9c6 {}
> [debug] [MJSONWP] Calling AppiumDriver.deleteSession() with args: ["28134ba2-edfb-4b85-8c7c-5b656ffaa9c6"]
> [debug] [BaseDriver] Event 'quitSessionRequested' logged at 1509190326920 (04:32:06 GMT-0700 (PDT))

What is wrong in this log? I see there was session deletion request from the client. Nothing unusual.
