### ISSUE TITLE
Appium gets stuck at [JSONWP Proxy] Proxying [POST /session]...

### ISSUE THREAD

**Issue by deedora** [appium/appium#9482]
iOS, simulator
Appium version 1.7.1
Xcode version 9.0.1
Language: Java

I have a problem that started occurring after update to new (1.7.0) Appium. When I start test form Intellij, app will start on simulator and then Appium will get stuck on this line :
`[JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.****.*****","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}`

Sometimes the test will start after few minutes, but most of the times nothing happens for very long time so I just quit everything. Sometimes I even have to restart mac for next test to run.
I'm not 100% sure but I think that happens when test ran before did not finish (fail/pass) but I stopped it manually from Intellij.

Here are the full logs https://gist.github.com/deedora/43b5e939e086461745336b993ca00e89

**Comment by mykola-mokhnach** [comment]
Please attach the Simulator log as well

**Comment by shane51** [comment]
me, too, it start to run script after 2~3 mins

**Comment by olyv** [comment]
I am having quite the same issue when I try to connect to session with Appium Inspector

`[debug] [JSONWP Proxy] Proxying [GET /source] to [GET http://localhost:8100/session/3C342061-E37B-457E-BDD4-0D34B146C218/source] with no body`

**Comment by deedora** [comment]
Simulator logs :
https://gist.github.com/deedora/1377317ba9f6b16149ca182d6015868f

After test later started (and passed) this was added
`Oct 18 13:20:33 users-Mac-mini com.apple.CoreSimulator.SimDevice.F64D9812-98B8-45D9-8867-5DE47B3A12B4[649] (UIKitApplication:com.appNameinc.appNameFDA[0x447e][678][5473]): Service exited due to signal: Killed: 9 sent by testmanagerd[5241]`

**Comment by imurchie** [comment]
The logs indicate that the system found a running WDA server on the device (https://gist.github.com/deedora/43b5e939e086461745336b993ca00e89#file-gistfile1-txt-L33-L36). Can you try setting the `useNewWDA` capability to `true` so that it begins anew?

**Comment by deedora** [comment]
I think it's working. Haven't had a problem all day. Thanks 👍

**Comment by imurchie** [comment]
Excellent!

**Comment by ellnika** [comment]
I have the same issue. How did you get it work :)

**Comment by deedora** [comment]
Set useNewWDA capability to true.

**Comment by deedora** [comment]
I've spoken too soon. It's still happening.

**Comment by ellnika** [comment]
it looks like it is not available in Appium 1.7? When I am trying to use it I get Unrecognized arguments: --useNewWDA true. How do you pass it to Appium?

**Comment by deedora** [comment]
capabilities.setCapability("waitForQuiescence", "false");
But I still have to wait for 5 minutes sometimes.

**Comment by ellnika** [comment]
So do I need to add those both?
capabilities.setCapability("useNewWDA", "true");
capabilities.setCapability("waitForQuiescence", "false");

I keep on getting I keep on getting [debug] [XCUITest] Capability 'useNewWDA' set to false, so trying to reuse currently running WDA instance at 'http://localhost:8100/'.

**Comment by ellnika** [comment]
I am really stuck with it and nothing seems to be working.
If anyone can help me out I would greatly appreciate :-(

**Comment by deedora** [comment]
Somebody suggested using waitForQuiescence but it is not working for me since it makes test to run before app sometimes even starts. I only use capabilities.setCapability("useNewWDA", "true") but even that is not helping always. Just have to sit and wait 5 minutes for something to happen.

**Comment by shane51** [comment]
Yes, I have exactly same issue, can @deedora  reopen the issue?

**Comment by uLucasFraga** [comment]
Hey, any solution with this problem? Thx.

**Comment by createdon2003** [comment]
Facing this issue as well. Tried with useNewWDA but no luck. Will try debugging by adding showXcodeLog flag.

**Comment by aaleksandroff** [comment]
@imurchie I'm facing the same issue with appium 1.8.0-beta5 and Xcode 9, is there any solution yet?

**Comment by aaleksandroff** [comment]
@imurchie Actually, I've managed to fix it by settings up those capabilities:

**Comment by harshali-weboniselab** [comment]
Hi all,
I am still facing the same issue with appium 1.8.0 and xcode 9.1.3.
I tried with above capabilities but still it is not working...
App is getting installed but not launched.

Appium logs shows following message -
[XCUITest] Failed to create WDA session. Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1526554713232 (16:28:33 GMT+0530 (IST))
[XCUITest] Sending createSession command to WDA

**Comment by viveksoundar** [comment]
I am also facing this same issue. please help me out.

**Comment by aljones15** [comment]
still getting this with:

            ```
            caps.setCapability("app", appPath.toString());
            caps.setCapability("launchTimeout", 820000);
            caps.setCapability("platformName", "iOS");
            caps.setCapability("platformVersion", "11.0");
            caps.setCapability("deviceName", "iPhone 8");
            // apple no longer supports the older test standard so we use XCUITest
            caps.setCapability("automationName", "XCUITest");
            caps.setCapability("fullReset", true);
            caps.setCapability("orientation", "PORTRAIT");
            caps.setCapability("keepKeyChains", false);
	   caps.setCapability("shouldUseSingletonTestManager", false);
	  caps.setCapability("useNewWDA", true);
          caps.setCapability("clearSystemFiles", true);
	  caps.setCapability("shouldWaitForQuiescence", false);

```

**Comment by saigovindu** [comment]
Hi all,

I am still facing this same issue with appium 1.9.0 and xcode 8.1. 
I tried with above capabilities but still it is not working as expected. I am trying to do performance test on modified appium so created a tool that help us to create session->run tests->quit continenously. For first 50+ test executing within 20 seconds afterwards test cases taking long time because of WDA session creation taking long time.

**Comment by Marrowbones** [comment]
In case anyone is still having the same problem, try upgrading everything (NPM, Appium, etc); I know it sounds obvious, but what's probably happened is that you've installed an OS upgrade that's not compatible with some component of the Appium/WebDriver setup.  For me, the problem was carthage (brew update carthage) - an easy one to overlook. Hope this helps.
