### ISSUE TITLE
[iOS] [XCUITest] Is it possible to make multi tap?

### ISSUE THREAD

**Issue by shynkevich-alex** [appium/appium#9483]
## The problem
I tried use multi touch action but it is does not work:

        TouchAction action0 = new TouchAction(iosDriver).tap(50, 50).release();
        TouchAction action1 = new TouchAction(iosDriver).tap(100, 100).release();;
        MultiTouchAction mAction = new MultiTouchAction(iosDriver);

        mAction.add(action0).add(action1).perform();

> Support for this multi-action is not implemented. Try to use "mobile: *" interface to workaround the issue.

But I could not find the same multi tap action  in https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios-xctest-mobile-gestures.md

## Environment

* 1.7.2-beta
* iOS
* Java client 5.0.4
* Xcode 9

**Comment by mykola-mokhnach** [comment]
Unfortunately it's impossible with the recent Appium version. I hope this feature will be available in the next minor beta release.
