### ISSUE TITLE
appium desktop: tap,sendkeys,clear buttons are disable for every element in my App

### ISSUE THREAD

**Issue by Shahunks** [appium/appium#9484]
![screen shot 2017-10-18 at 3 32 43 pm](https://user-images.githubusercontent.com/25055088/31713301-7f475800-b41b-11e7-949d-dcb2360a216f.png)
## The problem
appium desktop: tap,sendkeys,clear buttons are disable for every element in my App

## Environment

* Appium version (or git revision) that exhibits the issue:1.6.5
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MAC OS
* Node.js version (unless using Appium.app|exe):6.10.1
* Mobile platform/version under test: 8.0.0
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: appium.app

**Comment by mykola-mokhnach** [comment]
Please report to https://github.com/appium/appium-desktop/issues
