### ISSUE TITLE
Unable to start WebDriverAgent session with Xcode 9.0.1

### ISSUE THREAD

**Issue by JaniJegoroff** [appium/appium#9485]
## The problem

I'm unable to launch tests due to an error
```
[XCUITest] Error: Unable to start WebDriverAgent session because of xcodebuild failure: "Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8100".
```

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable): 1.6.5
* Desktop OS/version used to run Appium: Mac OS High Sierra 10.13
* Node.js version (unless using Appium.app|exe): v7.2.0
* Mobile platform/version under test: iOS 11.0
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: CLI

## Details

I have been able to run tests with Xcode 9.0 / Appium 1.7.1

## Link to Appium logs

https://gist.github.com/JaniJegoroff/f63c7b4822f74738745bd0b98ae22cb0

**Comment by mykola-mokhnach** [comment]
Try to reset the target Simulator.

**Comment by JaniJegoroff** [comment]
Reseting simulator does not help.

**Comment by JaniJegoroff** [comment]
@mykola-mokhnach Latest Appium beta seems to be working fine. Do you know when version 1.7.2 is about to be released?

**Comment by kommuswamy** [comment]
@mykola-mokhnach , When we expect the stable version of Xcode 9.1 and appium 1.7.2?

We are eagerly waiting for the stable version to use instead of beta versions.

**Comment by mykola-mokhnach** [comment]
It's usually released as soon as we see there are no new major issues and the features we planned for it are merged and working. No precise dates though.
