### ISSUE TITLE
Appium 1.7.1 + iOS: Cannot interact with elements in an external Safari page

### ISSUE THREAD

**Issue by jarmy** [appium/appium#9486]
## The problem
When Safari is opened from our application, Appium cannot interact with any of the elements. findElement returns null results yet getPageSource reveals elements. The XCUIElementTypeButton element with name="Open" is marked with visible = true in the pageSource. However, the Appium desktop cannot interact with any of the elements (Tap, Send Keys, Clear buttons are all disabled).
   
Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version:  Appium v1.7.1 (REV 6c00766de3cd4c9ab4de78f1e2ee846509b88002)
* Last Appium version that did not exhibit the issue (if applicable): 1.6.5
* Desktop OS/version used to run Appium: 1.2.4
* Node.js version (unless using Appium.app|exe): v6.11.0
* Mobile platform/version under test: iPhone 7 + iOS 10.3 + Xcode 9.0 + MacOS Sierra 10.12.6 
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: CLI & Appium Desktop

## Details
When searching for certain stations in our Pandora app, an external browser (Safari) will open. With Appium 1.7.1, we're unable to detect or interact with any of the elements in this page.  This issue is not symptomatic with Appium 1.6.5. We are using v4.1.2 io.appium java-client and v3.0.1 selenium-java.

I'm also attaching a screenshot from Appium Desktop v1.2.4 with the problematic page which illustrates the XCUIElementTypeButton "Open" element marked with visible = false. Also note the Top, Send Keys, and Clear buttons disabled when the element is selected.

## Link to Appium logs
https://gist.github.com/jarmy/b4238159ce5269412aeb4f976b95b0ee

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
This is known WebDriverAgent limitation. For now there is no way to workaround it

**Comment by jarmy** [comment]
I presume this is the issue? https://github.com/facebook/WebDriverAgent/issues/708

**Comment by masoodmd0786** [comment]
@mkyola-mokhnach does below issue related to this issue?

https://discuss.appium.io/t/unable-to-find-webview-in-ios-hybrid-app-xcode9-appium1-7-1-ios10-3-3-and-above/19068
