### ISSUE TITLE
Can appium use an adb server that is not running on the default port 5037?

### ISSUE THREAD

**Issue by AllanMNoguera** [appium/appium#9488]
## The problem

I am trying to run a test on a remote server, using Jenkins to start the tests; but the adb does not take the default port, it usually takes a port around 5800. But appium is not able to find the device because it forces to look an adb running on the default port.

## Environment

* Appium version 1.6.5
* Desktop OS CentOS

## Details

I have looked into the code, and could not find where the port number is set, I see is requested from the environment; but do not where.

**Comment by dpgraham** [comment]
Yes. There's a desired capability called `adbPort`.
