### ISSUE TITLE
driver.execute_script 'mobile: scroll', toVisible: 'true' ,:element => find_element(:xpath,watchlistXpath).ref function is not working 

### ISSUE THREAD

**Issue by kommuswamy** [appium/appium#9489]
## The problem

driver.execute_script 'mobile: scroll', toVisible: 'true' ,:element => find_element(:xpath,watchlistXpath).ref function is not working in appium 1.7.2-beta , when i excute this, it scrolls the page to down.
## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2-beta
* Last Appium version that did not exhibit the issue (if applicable): 1.6.5
* Desktop OS/version used to run Appium: 10.12.6
* Node.js version (unless using Appium.app|exe): 7
* Mobile platform/version under test: 11.1
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe:

**Comment by mykola-mokhnach** [comment]
The scrolling is executed on WebDriverAgent side. There is nothing we can change there for Appium.
