### ISSUE TITLE
Appium Version: 1.7.1 .Process State is Returned as Process Name while trying to set context of WEBVIEW. EX: Returning Process Name : 'S'

### ISSUE THREAD

**Issue by SYNY2588** [appium/appium#9490]
## The problem
Hi,
I am trying to automate Hybrid app. While trying to set context to the relevant WEBVIEW, I see that WEBVIEWS  are having PROCESS STATE instead of PACKAGE NAME.

EX: WEBVIEW_S and WEBVIEW_R

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows 7
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Android 7.0
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
```
[debug] [MJSONWP] Calling AppiumDriver.getContexts() with args: ["ada721b1-ba9a-4216-b8e1-7217811c2ffb"]
[debug] [AndroidDriver] Getting a list of available webviews
[debug] [ADB] Getting connected devices...[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\********\********\*******\*******\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","354d5df9","shell","cat","/proc/net/unix"][debug] [AndroidDriver] WEBVIEW_22727 mapped to pid 22727
[debug] [AndroidDriver] Getting process name for webview
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running ' C:\********\********\*******\*******\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","354d5df9","shell","ps"][debug] [AndroidDriver] Parsed pid: '22727' pkg: 'S' from
[debug] [AndroidDriver]     USER      PID   PPID  VSIZE  RSS   WCHAN              PC  NAME
[debug] [AndroidDriver]     u0_a256   22727 914   1608016 258076 SyS_epoll_ 0000000000 S com.******.*****.****
[debug] [AndroidDriver] Returning process name: 'S'
[debug] [AndroidDriver] Found webviews: ["WEBVIEW_S"]
[debug] [AndroidDriver] Available contexts: ["NATIVE_APP","WEBVIEW_S"]
[debug] [MJSONWP] Responding to client with driver.getContexts() result: ["NATIVE_APP","WEBVIEW_S"]
```

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
@imurchie FYI

**Comment by imurchie** [comment]
Can you provide the full logs? Or at least the version of the driver being used? This is not enough information to go on.

**Comment by SYNY2588** [comment]
I can't provide the full logs. Which driver version do you need?

**Comment by SYNY2588** [comment]
Chromedriver-2.33 and ADB version is 1.0.39.

**Comment by imurchie** [comment]
There should be a line near the beginning of the create session call that says something like `Creating new XXX (vYYY) session`

**Comment by SYNY2588** [comment]
AndroidDriver (v1.26.5)

**Comment by SYNY2588** [comment]
@imurchie
 [info] [Appium] Creating new AndroidDriver (v1.26.5) session

**Comment by imurchie** [comment]
So you are running Appium 1.7.0 not 1.7.1?

**Comment by SYNY2588** [comment]
My bad. Yes it is 1.7.0

**Comment by imurchie** [comment]
Upgrading to Appium 1.7.1 will fix this issue, which was fixed in the AndroidDriver v1.27.0.

**Comment by SYNY2588** [comment]
@imurchie 
Thanks. I just did it and it's working

**Comment by imurchie** [comment]
Excellent!
