### ISSUE TITLE
unlock_apk-debug.apk [INSTALL_FAILED_VERSION_DOWNGRADE] after upgraded to 1.7.1

### ISSUE THREAD

**Issue by oldstone** [appium/appium#9497]
## The problem
We recently upgraded to Appium 1.7.1 from 1.6.6-beta.4. After the upgrade, every tests failed with this error:
`2017-10-20 12:13:42:312 - error: [MJSONWP] Encountered internal error running command: Error: Error executing adbExec. Original error: 'Command '/opt/android-sdk-linux/platform-tools/adb -P 5037 -s f15aeffe install /opt/myTest/adbservice/node_modules/appium/node_modules/appium-unlock/bin/unlock_apk-debug.apk' exited with code 1'; Stderr: 'Failed to install /opt/myTest/adbservice/node_modules/appium/node_modules/appium-unlock/bin/unlock_apk-debug.apk: Failure [INSTALL_FAILED_VERSION_DOWNGRADE]'; Code: '1'
    at ADB.execFunc$ (../../../lib/tools/system-calls.js:317:13)
    at tryCatch (/opt/myTest/adbservice/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/opt/myTest/adbservice/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/opt/myTest/adbservice/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/opt/myTest/adbservice/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
`

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable): 1.6.6-beta.4
* Desktop OS/version used to run Appium: centos-release-7-3.1611.el7.centos.x86_64
* Node.js version (unless using Appium.app|exe): v6.11.2
* Mobile platform/version under test: Android 7.0
* Real device or emulator/simulator: Real device (Samsung S7)
* Appium CLI or Appium.app|exe:

## Details
So is Appium 1.7.1 really trying to install an older version of unlock_apk-debug.apk? By the way, why does Appium still trying to install unlock_apk-debug.apk every time when I have capability skipUnlock=true? Does this app also do other tasks other than unlock the screen?

## Link to Appium logs
https://gist.github.com/oldstone/b60e3e9d6b0e288c9a0ad36dcd7ae032

**Comment by saikrishna321** [comment]
@oldstone this PR has the fix. Can you please update to latest beta and try

npm uninstall -g appium 
npm install -g appium@beta

**Comment by mykola-mokhnach** [comment]
Closed as duplicate

**Comment by vighneshpai-yml** [comment]
Instead of uninstalling all together, a simple but manual workaround is, uninstall the app 'Unlock' from your device and then try again.

**Comment by anantgoldie** [comment]
@vighneshpai-yml  thanks for the suggestion. it works.

**Comment by RawatH** [comment]
> Instead of uninstalling all together, a simple but manual workaround is, uninstall the app 'Unlock' from your device and then try again.

It worked :)
