### ISSUE TITLE
Activity never started although it's the one found by ADB

### ISSUE THREAD

**Issue by sher04lock** [appium/appium#9498]
## The problem

App can start with two different activities: one with login screen, the second with main screen when logged in. I've set these two activities in `appWaitActivity` capability, but connection is established only for login activity - the later is said not to be started, although Appium finds exactly the same name of activity.

## Environment

* Appium version: v1.7.1
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): 6.11.0
* Mobile platform/version under test: Android 7.1
* Real device or emulator/simulator: Android Emulator
* Appium CLI or Appium.app|exe: CLI

## Details

The error is:
`[ADB] Error: Error occured while starting App. Original error: 
'com.company.app.activities.main.mainActivity' or 'com.company.commons.datainterface.accountmanager.LoginActivity' never started`

But earlier in logs you can find:

`[debug] [ADB] Found package: 'com.company.app.beta' and fully qualified activity name : 'com.company.app.activities.main.MainActivity'`

I can see that the app is launched and running `adb shell dumpsys window windows | grep -E 'mCurrentFocus|mFocusedApp'` also finds correct activity. 

I just thought it might be the [snackbar](https://developer.android.com/training/snackbar/action.html) preventing it from being fully connected, but even if I close it as soon as it pops out after app has launched, Appium still can't connect to the correct activity.
## Link to Appium logs

[https://gist.github.com/sher04lock/11a066279805a66d842046d4c3716da4](https://gist.github.com/sher04lock/11a066279805a66d842046d4c3716da4)

**Comment by mykola-mokhnach** [comment]
You must also provide _appActivity_ capability

**Comment by sher04lock** [comment]
@mykola-mokhnach 
I didn't have to use appActivity before, appWaitActivity was enough. But why Appium can't run application which appWaitActivity contains exactly the same activity that ADB has found?
