### ISSUE TITLE
I can find toast element by xpath , but  getPageSource result not contain this element

### ISSUE THREAD

**Issue by levinzhang1981** [appium/appium#9503]
## The problem

I use UIAutomator2 to start driver, in my code  I can find Toast Element by xpath , I can even get the text of my  Toast
But ,when i  call getPageSource(), the returned result doesn't contain Toast information

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:Mac OS 10.11
* Node.js version (unless using Appium.app|exe):7.0.0
* Mobile platform/version under test:Android 7.0
* Real device or emulator/simulator:Real device
* Appium CLI or Appium.app|exe:Appium CLI

## Details

No

## Link to Appium logs

No

## Code To Reproduce Issue [ Good To Have ]

         File classpathRoot = new File(System.getProperty("user.dir"));

        File appDir = new File(classpathRoot, "apps/toast");

        File app = new File(appDir, "test.apk");

        DesiredCapabilities capabilities = new DesiredCapabilities();

       capabilities.setCapability("deviceName","Android");

       capabilities.setCapability("platformVersion", "7.0");

      capabilities.setCapability("app", app.getAbsolutePath());

      capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.ANDROID_UIAUTOMATOR2);

    driver = new AndroidDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);`

      String toast = "This is a test";

       //I can find element here

         WebElement el2 =driver.findElement(By.xpath(".//*[contains(@text,'"+ toast + "')]"));

           System.out.println(el2.getAttribute("text"));

          //the page source  doesn't contain Toast information

         System.out.println(driver.getPageSource());

**Comment by coolbirda** [comment]
Same issue +1

**Comment by mirro0707** [comment]
Same issue +1

**Comment by Louis-me** [comment]
```
wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath(".//*[contains(@text, '1111111')]")))
```

**Comment by andrewleo** [comment]
Same issue +1, anyone can help?

**Comment by Gennadiii** [comment]
Same issue +1

**Comment by mykola-mokhnach** [comment]
The stuff should work better now in Appium 1.10.0+
