### ISSUE TITLE
Did swipe method for iOS stop working in Appium 1.7.1/1.7.2?

### ISSUE THREAD

**Issue by LukasLewandowski** [appium/appium#9504]
## The problem

No effect after using:

"action.press(el, start_x, start_y).wait(100).move_to(el, end_x, end_y).release().perform()" or
"self.driver.swipe(start_x=width_center, start_y=0, end_x=width_center, end_y=height_max, duration=800)"

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1/1.7.2
* Last Appium version that did not exhibit the issue (if applicable): 1.6.5
* Desktop OS/version used to run Appium: OSX 10.12.6
* Node.js version (unless using Appium.app|exe): 8.7
* Mobile platform/version under test: iOS 10
* Real device or emulator/simulator: both
* Appium CLI or Appium.app|exe: CLI

Log:

[HTTP] --> GET /wd/hub/session/7df4b1f2-38dd-4fd9-82c5-6ff5ca86893a/window/current/size {}
[debug] [MJSONWP] Calling AppiumDriver.getWindowSize() with args: ["current","7df4b1f2-38dd-4fd9-82c5-6ff5ca86893a"]
[debug] [XCUITest] Executing command 'getWindowSize'
[debug] [JSONWP Proxy] Proxying [GET /window/size] to [GET http://localhost:8100/session/C37EED63-A1A5-449C-872E-DBA69156008B/window/size] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"width\" : 375,\n    \"height\" : 667\n  },\n  \"sessionId\" : \"C37EED63-A1A5-449C-872E-DBA69156008B\",\n  \"status\" : 0\n}"
[debug] [MJSONWP] Responding to client with driver.getWindowSize() result: {"width":375,"height":667}
[HTTP] <-- GET /wd/hub/session/7df4b1f2-38dd-4fd9-82c5-6ff5ca86893a/window/current/size 200 619 ms - 98
[HTTP] --> POST /wd/hub/session/7df4b1f2-38dd-4fd9-82c5-6ff5ca86893a/element {"using":"class name","value":"XCUIElementTypeScrollView","sessionId":"7df4b1f2-38dd-4fd9-82c5-6ff5ca86893a"}
[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["class name","XCUIElementTypeScrollView","7df4b1f2-38dd-4fd9-82c5-6ff5ca86893a"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 6000 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/C37EED63-A1A5-449C-872E-DBA69156008B/element] with body: {"using":"class name","value":"XCUIElementTypeScrollView"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"ELEMENT":"55922AEE-5232-4D5F-923C-670A6FED3526"},"sessionId":"C37EED63-A1A5-449C-872E-DBA69156008B","status":0}
[debug] [MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"55922AEE-5232-4D5F-923C-670A6FED3526"}
[HTTP] <-- POST /wd/hub/session/7df4b1f2-38dd-4fd9-82c5-6ff5ca86893a/element 200 897 ms - 122
[HTTP] --> POST /wd/hub/session/7df4b1f2-38dd-4fd9-82c5-6ff5ca86893a/touch/perform {"actions":[{"action":"press","options":{"element":"55922AEE-5232-4D5F-923C-670A6FED3526","x":187.5,"y":667}},{"action":"wait","options":{"ms":100}},{"action":"moveTo","options":{"element":"55922AEE-5232-4D5F-923C-670A6FED3526","x":187.5,"y":333.5}},{"action":"release","options":{}}],"sessionId":"7df4b1f2-38dd-4fd9-82c5-6ff5ca86893a"}
[debug] [MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"element":"55922AEE-5232-4D5F-923C-670A6FED3526","x":187.5,"y":667}},{"action":"wait","options":{"ms":100}},{"action":"moveTo","options":{"element":"55922AEE-5232-4D5F-923C-670A6FED3526","x":187.5,"y":333.5}},{"action":"release","options":{}}],"7df4b1f2-38dd-4fd9-82c5-6ff5ca86893a"]
[debug] [XCUITest] Executing command 'performTouch'
[debug] [XCUITest] Received the following touch action: press(options={"element":"55922AEE-5232-4D5F-923C-670A6FED3526","x":187.5,"y":667})-wait(options={"ms":100})-moveTo(options={"element":"55922AEE-5232-4D5F-923C-670A6FED3526","x":187.5,"y":333.5})-release(options={})
[debug] [XCUITest] Found matching gesture: drag
[debug] [JSONWP Proxy] Proxying [GET /element/55922AEE-5232-4D5F-923C-670A6FED3526/rect] to [GET http://localhost:8100/session/C37EED63-A1A5-449C-872E-DBA69156008B/element/55922AEE-5232-4D5F-923C-670A6FED3526/rect] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"y\" : 0,\n    \"x\" : 0,\n    \"width\" : 375,\n    \"height\" : 667\n  },\n  \"sessionId\" : \"C37EED63-A1A5-449C-872E-DBA69156008B\",\n  \"status\" : 0\n}"
[debug] [JSONWP Proxy] Proxying [GET /element/55922AEE-5232-4D5F-923C-670A6FED3526/rect] to [GET http://localhost:8100/session/C37EED63-A1A5-449C-872E-DBA69156008B/element/55922AEE-5232-4D5F-923C-670A6FED3526/rect] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"y\" : 0,\n    \"x\" : 0,\n    \"width\" : 375,\n    \"height\" : 667\n  },\n  \"sessionId\" : \"C37EED63-A1A5-449C-872E-DBA69156008B\",\n  \"status\" : 0\n}"
[debug] [JSONWP Proxy] Proxying [POST /wda/dragfromtoforduration] to [POST http://localhost:8100/session/C37EED63-A1A5-449C-872E-DBA69156008B/wda/dragfromtoforduration] with body: {"fromX":187.5,"fromY":667,"toX":187.5,"toY":333.5,"duration":0.1}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"C37EED63-A1A5-449C-872E-DBA69156008B","status":0}
[debug] [MJSONWP] Responding to client with driver.performTouch() result: null
[HTTP] <-- POST /wd/hub/session/7df4b1f2-38dd-4fd9-82c5-6ff5ca86893a/touch/perform 200 3028 ms - 76
[HTTP] --> POST /wd/hub/session/7df4b1f2-38dd-4fd9-82c5-6ff5ca86893a/element {"using":"accessibility id","value":"Airplane Mode","sessionId":"7df4b1f2-38dd-4fd9-82c5-6ff5ca86893a"}
[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["accessibility id","Airplane Mode","7df4b1f2-38dd-4fd9-82c5-6ff5ca86893a"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 6000 ms for condition

**Comment by mykola-mokhnach** [comment]
Nothing was changes there so far.

Make sure you perform swipe on the correct element and use relative coordinates instead of absolute in move_to method.

**Comment by LukasLewandowski** [comment]
I don't know why it stopped working, I have rewritten my method and it looks like swipe is behaving differently for iOS real device and iOS simulator.

**Comment by shaunsun** [comment]
same issue for me,  super: no superclass method `swipe' for #<Pages::Ios::
appium 1.7
iOS 11 real device iphone 7

**Comment by bnoel77** [comment]
I'm having the same issue using this:
            Dimension size= PrepareDevice.driver.manage().window().getSize();
            int starty=(int)(size.height*0.80);
            int endy=(int)(size.height*0.20);
            int startx=size.width/2;
            PrepareDevice.driver.swipe(startx, endy, startx, starty, 3000);

This was working fine and then stopped when I upgraded to 1.7.1.

**Comment by jgannaway** [comment]
I'm noticing a difference as well.  I have a test that swipes left through a set of onboarding/welcome screens.  On each screen, the test attempts to swipe left across the entire width of the screen.  For example,

```csharp
int height = driver.Manage().Window.Size.Height;
int width = driver.Manage().Window.Size.Width;
driver.Swipe(width, height / 2, 0, height / 2, 250);  
```
The code above now only swipes about half-way across the screen (not enough to advance to the next screen) when run on an iPhone 6 simulator running iOS 11.1.  I tried adjusting the duration, but it didn't make a difference.  If I multiply the width by 2 it works, but that feels like a hack (since I'm specifying coordinates that are off the screen).

As a workaround, I'm using the **mobile: swipe** API, which works fine for me:

```csharp
var d = new Dictionary<string, string> { { "direction", "left" } };
driver.ExecuteScript("mobile: swipe", d);
```

**Comment by ngoccuong11789** [comment]
Try this code : 

new TouchAction(driver).press(PointOption.point(500, 596)).waitAction(WaitOptions.waitOptions(Duration.ofMillis(1000))).
	  moveTo(PointOption.point(518, 478)).release().perform();
