### ISSUE TITLE
Appium 1.7.1/1.7.2 stopped distinguish iOS emulator from real device

### ISSUE THREAD

**Issue by LukasLewandowski** [appium/appium#9505]
## The problem

Despite desire capabilities, Appium is confusing booted iOS emulator with real device

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1/1.7.2
* Last Appium version that did not exhibit the issue (if applicable): 1.6.5
* Desktop OS/version used to run Appium: osx 10.12.6
* Node.js version (unless using Appium.app|exe): 8.7.0
* Mobile platform/version under test: iOS 10
* Real device or emulator/simulator: both
* Appium CLI or Appium.app|exe: cli

Log:
- There are two runs of the same test. First, on an emulator which was started correctly on specified emulator and the second one, that should run on a real device instead it also launched on a booted emulator.

https://gist.github.com/LukasLewandowski/88a06acad43f449e8f3dbe525b67cb9c

**Comment by mykola-mokhnach** [comment]
It's by design that Appium tries to reuse running session to save the initialisation time for the next session. Set the different value for wdaLocalPort capability for each device you have.
