### ISSUE TITLE
Appium times out after 60 seconds, way to pass launcher as main activity or w/o activity?

### ISSUE THREAD

**Issue by gamesguru** [appium/appium#9508]
## The problem
Appium gets stuck in a loop, not getting approval or not opening the app.  See my other posts from today:
https://github.com/appium/appium/issues/9499#issuecomment-338455347
https://github.com/appium/appium/issues/1050#issuecomment-338751658

(EDIT: the timeout problem is still happening even with using the mainactivity/launcher screen.  Do I have any options besides an older version of appium?)

Is there any easy way to use the home activity when your physical device is variable?  
The activity and package name changes with the device, e.g.

- com.sec.android.app.launcher/com.sec.android.app.launcher.activities.LauncherActivity
- com.sec.android.app.launcher/com.android.launcher2.Launcher
- com.lge.launcher3/com.lge.launcher3.LauncherExtension

I can pass this to adb in one of two ways.  This is the easy way, but it only works on one specified device, and it still requires some Regex, string formatting, etc etc.  No need for keyevent 26 or 86, or for anything with a launcher.package name.
```
1) shell am start -a android.intent.action.MAIN -c android.intent.category.HOME
2) shell dumpsys window windows | grep -E 'mCurrentFocus|mFocusedApp'
3) some processing
```
The other way just requires more processing
```
1) shell dumpsys window windows
2) lots of processing
```

I'm working on the first approach, unless someone has an easier way?  It would be nice if the appActivity and stuff was optional because the core Appium engine works very well, besides the initial connection.  I have tried newCommandTimeout and many other capabilities (C#) to no avail.

**Comment by mykola-mokhnach** [comment]
You can use asterisk character ('*') in activity name to match multiple activities

**Comment by saikrishna321** [comment]
Closing as question answered
