### ISSUE TITLE
Unable to set "webview" and app launch get fails in iOS 11(Using Xcode 9)

### ISSUE THREAD

**Issue by Logakarti** [appium/appium#9511]
## The problem
"Webview" context not showing in my hybrid app and also app get closing it after launching when automating the suite in iPhone 8 Plus simulator(using Xcode 9). Please anyone help me to solve this issue.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Desktop OS/version used to run Appium: MAC
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: iPhone 8 Plus(Simulator)

## Link to Appium logs
https://gist.github.com/Logakarti/f921acfc50620aef4814481aa857afe7

## Code To Reproduce Issue [ Good To Have ]

File appdir = new File ( "/Users/apple/Downloads/Flexbook iOS Xcode Build/ios 3 - Gamma/build/emulator" );
        File app = new File ( appdir, "FlexBook.app" );
        DesiredCapabilities capabilities = new DesiredCapabilities ( );
        capabilities.setCapability (MobileCapabilityType.PLATFORM_NAME, MobilePlatform.IOS );
        capabilities.setCapability (MobileCapabilityType.PLATFORM_VERSION, "11.0" );
        capabilities.setCapability (MobileCapabilityType.DEVICE_NAME, "iPhone 8 Plus" );
        // capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, "XCUITest");
        capabilities.setCapability ( "safariAllowPopups", true );
        capabilities.setCapability ( "newCommandTimeout", 120 );
        capabilities.setCapability ( "safariOpenLinksInBackground", true );
        capabilities.setCapability ( "usePrebuiltWDA", true );
        capabilities.setCapability ( "useNewWDA", false );
        capabilities.setCapability ( "webviewConnectRetries", 25 );
        capabilities.setCapability ( "app", app.getAbsolutePath ( ) );
        driver = new IOSDriver ( new URL ( "http://127.0.0.1:4729/wd/hub" ), capabilities );
        driver.manage ( ).timeouts ( ).implicitlyWait ( 80, TimeUnit.SECONDS );
        try {
            Thread.sleep(15000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        Set<String> contextNames = driver.getContextHandles();
        for (String contextName : contextNames) {
            System.out.println(contextName); //prints out something like [NATIVE_APP, WEBVIEW_<APP_PKG_NAME>
            if(contextName.contains("WEBVIEW")){
                driver.context(contextName);
                System.out.println("Switched to: "+contextName);
            }
        }
        try {
            Thread.sleep(1500);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        return capabilities;
    }

**Comment by mykola-mokhnach** [comment]
Is this web context visible to Remote Safari debugger if the application is stared manually?

**Comment by Logakarti** [comment]
Let me check it and get back from the status.

**Comment by Logakarti** [comment]
Web context is visible in safari debugger while launching the app manually.

**Comment by mykola-mokhnach** [comment]
Which component your developers use to show the web content? Perhaps SafariWebView?

**Comment by Logakarti** [comment]
They use "Safariviewcontroller" to show the web content in app

**Comment by mykola-mokhnach** [comment]
Unfortunately, Safari controller is not supported. See https://github.com/appium/appium/blob/764bdd61fd0ea3d0373e12168e2a7ee39a7afac1/docs/en/writing-running-appium/web/hybrid.md for the reference.
