### ISSUE TITLE
Unable to click on content-desc attribute value.

### ISSUE THREAD

**Issue by sagarsheth27** [appium/appium#9516]
Tried so many ways. As far still, saw so many issues regarding this. But it is not helpful to me.
It is an Ionic calendar, which is by default provided by ionic itself. I just want to pass date as format mm/yyyy using send keys or just click on done button.
Thanks in advance if anyone has idea, how to resolve it.
![2017-10-24_161157](https://user-images.githubusercontent.com/32329719/31938782-1bff533c-b8d6-11e7-8700-21fd40dcd052.png)

**Comment by sagarsheth27** [comment]
I am running it with uiautomator2 on android 7.1 ,appium version is 1.7.0

**Comment by dpgraham** [comment]
This UI is no longer supported.

Can you try with [Appium Desktop](https://github.com/appium/appium-desktop/releases/latest)

**Comment by tfcardoso** [comment]
@dpgraham What do you mean with this UI is no longer supported? Thats uiautomatorviewer. The Done button can be easily identified with the content description, apparently he just needs to get the element and click on it.

What am I seeing wrong?

**Comment by dpgraham** [comment]
I thought it was the old Appium UI my mistake

If it's an Ionic app then that would be  web view and you need to change the context to the WebView and run selenium commands to locate the button and then click it.

**Comment by dpgraham** [comment]
I recommend setting the `autoWebView` capability to `true` and then it will automatically set the context to your Ionic webview.

**Comment by sagarsheth27** [comment]
No its not running. @dpgraham

**Comment by sagarsheth27** [comment]
PFA for log.
[appium-server-logs.txt](https://github.com/appium/appium/files/1413481/appium-server-logs.txt)

**Comment by dpgraham** [comment]
There was a typo in my previous comment. It's actually `autoWebview`.

And when the context changes to the webview, you'll be dealing with ChromeDriver and will want to use HTML selectors.

**Comment by sagarsheth27** [comment]
I used autoWebview as you said. But its just now opening the application. But nothing will happen. 
Can you please guide how to use autoWebview capability and which attributes i have to use to run automation. Here i am using name,findaccessibilityid,xpath,linktext etc attributes to click on **enroll
![untitled](https://user-images.githubusercontent.com/32329719/32037278-3eea1540-ba42-11e7-9772-0d11d2292029.png)
**. But unable to click on it. Without autoWebview capability its working fine, till the Ionic calendar functionality.
So which thing i did wrong please tell and how to use autoWebview capability with appium and uiautomator2. PFB Server log for same and also find attachment.

[info] [HTTP] <-- POST /wd/hub/session - - ms - - 
[debug] [AndroidDriver] Getting a list of available webviews
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'D:\AndroidSDK\platform-tools\adb.exe' with args: ["-P",5037,"-s","HT6A40205681","shell","cat","/proc/net/unix"]
[debug] [AndroidDriver] WEBVIEW_15967 mapped to pid 15967
[debug] [AndroidDriver] Getting process name for webview
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'D:\AndroidSDK\platform-tools\adb.exe' with args: ["-P",5037,"-s","HT6A40205681","shell","ps"]
[debug] [AndroidDriver] Parsed pid: '15967' pkg: 'S' from
[debug] [AndroidDriver]     USER      PID   PPID  VSIZE  RSS   WCHAN              PC  NAME
[debug] [AndroidDriver]     u0_a197   15967 565   1407644 156644 SyS_epoll_ 0000000000 S xxxxx
[debug] [AndroidDriver] Returning process name: 'S'
[debug] [AndroidDriver] Found webviews: ["WEBVIEW_S"]
[debug] [AndroidDriver] Available contexts: ["NATIVE_APP","WEBVIEW_S"]
[debug] [AndroidDriver] Getting a list of available webviews
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'D:\AndroidSDK\platform-tools\adb.exe' with args: ["-P",5037,"-s","HT6A40205681","shell","cat","/proc/net/unix"]
[debug] [AndroidDriver] WEBVIEW_15967 mapped to pid 15967
[debug] [AndroidDriver] Getting process name for webview
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'D:\AndroidSDK\platform-tools\adb.exe' with args: ["-P",5037,"-s","HT6A40205681","shell","ps"]
[debug] [AndroidDriver] Parsed pid: '15967' pkg: 'S' from
[debug] [AndroidDriver]     USER      PID   PPID  VSIZE  RSS   WCHAN              PC  NAME
[debug] [AndroidDriver]     u0_a197   15967 565   1407644 156644 SyS_epoll_ 0000000000 S xxxxx
[debug] [AndroidDriver] Returning process name: 'S'
[debug] [AndroidDriver] Found webviews: ["WEBVIEW_S"]
[debug] [AndroidDriver] Available contexts: ["NATIVE_APP","WEBVIEW_S"]
[debug] [AndroidDriver] Getting a list of available webviews
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'D:\AndroidSDK\platform-tools\adb.exe' with args: ["-P",5037,"-s","HT6A40205681","shell","cat","/proc/net/unix"]
[debug] [AndroidDriver] WEBVIEW_15967 mapped to pid 15967
[debug] [AndroidDriver] Getting process name for webview
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'D:\AndroidSDK\platform-tools\adb.exe' with args: ["-P",5037,"-s","HT6A40205681","shell","ps"]
[debug] [AndroidDriver] Parsed pid: '15967' pkg: 'S' from
[debug] [AndroidDriver]     USER      PID   PPID  VSIZE  RSS   WCHAN              PC  NAME
[debug] [AndroidDriver]     u0_a197   15967 565   1407644 156644 SyS_epoll_ 0000000000 S xxxxx
[debug] [AndroidDriver] Returning process name: 'S'
[debug] [AndroidDriver] Found webviews: ["WEBVIEW_S"]
[debug] [AndroidDriver] Available contexts: ["NATIVE_APP","WEBVIEW_S"]
[debug] [AndroidDriver] Getting a list of available webviews
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'D:\AndroidSDK\platform-tools\adb.exe' with args: ["-P",5037,"-s","HT6A40205681","shell","cat","/proc/net/unix"]
[debug] [AndroidDriver] WEBVIEW_15967 mapped to pid 15967
[debug] [AndroidDriver] Getting process name for webview
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'D:\AndroidSDK\platform-tools\adb.exe' with args: ["-P",5037,"-s","HT6A40205681","shell","ps"]
[debug] [AndroidDriver] Parsed pid: '15967' pkg: 'S' from
[debug] [AndroidDriver]     USER      PID   PPID  VSIZE  RSS   WCHAN              PC  NAME
[debug] [AndroidDriver]     u0_a197   15967 565   1407644 156644 SyS_epoll_ 0000000000 S xxxxx
[debug] [AndroidDriver] Returning process name: 'S'
[debug] [AndroidDriver] Found webviews: ["WEBVIEW_S"]
[debug] [AndroidDriver] Available contexts: ["NATIVE_APP","WEBVIEW_S"]
[debug] [AndroidDriver] Getting a list of available webviews
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'D:\AndroidSDK\platform-tools\adb.exe' with args: ["-P",5037,"-s","HT6A40205681","shell","cat","/proc/net/unix"]
[debug] [AndroidDriver] WEBVIEW_15967 mapped to pid 15967
[debug] [AndroidDriver] Getting process name for webview
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'D:\AndroidSDK\platform-tools\adb.exe' with args: ["-P",5037,"-s","HT6A40205681","shell","ps"]
[debug] [AndroidDriver] Parsed pid: '15967' pkg: 'S' from
[debug] [AndroidDriver]     USER      PID   PPID  VSIZE  RSS   WCHAN              PC  NAME
[debug] [AndroidDriver]     u0_a197   15967 565   1407644 156644 SyS_epoll_ 0000000000 S xxxxx
[debug] [AndroidDriver] Returning process name: 'S'
[debug] [AndroidDriver] Found webviews: ["WEBVIEW_S"]
[debug] [AndroidDriver] Available contexts: ["NATIVE_APP","WEBVIEW_S"]
[debug] [UiAutomator2] Deleting UiAutomator2 session
[debug] [UiAutomator2] Deleting UiAutomator2 server session
[debug] [JSONWP Proxy] Proxying [DELETE /] to [DELETE http://localhost:8200/wd/hub/session/352d3535-304a-4e07-9911-bedfafc0e218] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"352d3535-304a-4e07-9911-bedfafc0e218\",\"status\":0,\"value\":\"Session deleted\"}"
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'D:\AndroidSDK\platform-tools\adb.exe' with args: ["-P",5037,"-s","HT6A40205681","shell","am","force-stop","xxxxx"]
[debug] [Logcat] Stopping logcat capture
[debug] [ADB] Removing forwarded port socket connection: 8200 
[debug] [ADB] Running 'D:\AndroidSDK\platform-tools\adb.exe' with args: ["-P",5037,"-s","HT6A40205681","forward","--remove","tcp:8200"]
[debug] [UiAutomator2] [UIAutomator2] io.appium.uiautomator2.server.test.AppiumUiAutomator2Server:.
[debug] [UiAutomator2] [UIAutomator2] Time: 51.035
[debug] [UiAutomator2] [UIAutomator2] OK (1 test)
[info] [Appium] Welcome to Appium v1.7.0
[info] [Appium] Non-default server args:
[info] [Appium]   address: 127.0.0.1
[info] [Appium] Appium REST http interface listener started on 127.0.0.1:4723

**Comment by dpgraham** [comment]
Ionic apps are WebView apps. Because it's web, Appium proxies it's commands through Selenium (Chromedriver specifically). You'll want to look at Selenium documentation on how to write tests.

**Comment by dpgraham** [comment]
Ionic apps are WebView apps. Because it's web, Appium proxies it's commands through Selenium (Chromedriver specifically). You'll want to look at Selenium documentation on how to write tests.

**Comment by tfcardoso** [comment]
@sagarsheth27 Maybe you can ask this kind of questions on forum http://discuss.appium.io/ ?

**Comment by sagarsheth27** [comment]
As you suggested @dpgraham . I am unable to run it.
PFA for logs.
[appium-server-logs.txt](https://github.com/appium/appium/files/1417696/appium-server-logs.txt)

**Comment by LukasLewandowski** [comment]
Did You try to use some XPath to click on "Done" button?

for example:

DONE = (MobileBy.XPATH, '//android.widget.Button[@content-desc[contains(., "DONE")]]')

**Comment by sagarsheth27** [comment]
No its not working.@lukas

**Comment by LukasLewandowski** [comment]
I would try Appium inspector to check if Appium sees that content-desc for DONE button, I'm still using appium 1.5.3 desktop app for inspecting elements. 

Another option is to switch to webview and locate that button using some css selector. 

This is hybrid app yes? 

btw I' m using fixed chromedriver to access webview in cordova hybrid app because standard chromedrive from google is not working for me.

Have You tried switching contexts?

contexts = self.driver.contexts
self.driver.switch_to.context(contexts[1])

**Comment by sagarsheth27** [comment]
Can you please give exact switching contexts code. Because i am unable to understand it. And how to use it?
Should i have to downgrade Appium or not?
@LukasLewandowski

**Comment by LukasLewandowski** [comment]
You can download appium desktop app and install it as a second one. (if You are using CLI appium right now, just install desktop app or if You are using latest Appium desktop app, You can change its name and then install the second one). 

https://bitbucket.org/appium/appium.app/downloads/

Python code for switching context:
contexts = self.driver.contexts`
self.driver.switch_to.context(contexts[1]) `  

first line: "Returns the contexts within the current session." and second is performing switch action from current context to context with index 1, if first line gives You some name of the context You can use it instead index.

**Comment by sagarsheth27** [comment]
# **I did as you said. But still not success. PFB my code for same.**

Set contextName = driver.getContextHandles();
		System.out.println(contextName);
		for (Object o  : contextName) {
			String data=o.toString();
			System.out.println(data);
		if (data.contains("NATIVE_APP")) {
		System.out.println("Show me:" + data);
		Thread.sleep(1500);
		driver.context("NATIVE_APP");
		driver.findElement(By.xpath("//android.widget.Button[@content-desc='DONE ']")).click();
		}
		if (data.contains("WEBVIEW_S")) {
		driver.context("WEBVIEW_S");
		driver.findElement(By.name("DONE")).click();
		//driver.findElement(By.xpath("//android.widget.Button[@content-desc='DONE ']")).click();
		}
		}
# **Console Output from eclipse is as below:**

[NATIVE_APP, WEBVIEW_S]
NATIVE_APP
Show me:NATIVE_APP
FAILED: Enroll
org.openqa.selenium.NoSuchElementException: An element could not be located on the page using the given search parameters. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 30.33 seconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.48.2', revision: '41bccdd', time: '2015-10-09 19:55:52'
System info: host: 'sagar-laps', ip: '192.168.10.156', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_144'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities [{appPackage=com.pscu.emf.dev, appActivity=xxxxxxxxxx.MainActivity, automationName=uiautomator2, platformName=Android, deviceName=Nexus, version=7.0, platform=ANY}]
Session ID: 0c130645-266e-4a03-8501-9a89b537a58b
*** Element info: {Using=xpath, value=//android.widget.Button[@content-desc='DONE ']}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAcces

# **PFA for server log.**
[appium-server-logs.txt](https://github.com/appium/appium/files/1421093/appium-server-logs.txt)

**Comment by sagarsheth27** [comment]
# **Also tried with below code also.**

Set contextNames = driver.getContextHandles();
		for (Object o : contextNames ) {
			String data= o.toString();
			      System.out.println(data);
			  }
		driver.context("WEBVIEW_S");
		driver.findElement(By.name("DONE ")).click();
		
		driver.findElement(MobileBy.AccessibilityId("DONE ")).click();

# **But in appium server log found error as below:**

[AndroidDriver] Parsed pid: '26091' pkg: 'S' from
[AndroidDriver]     USER      PID   PPID  VSIZE  RSS   WCHAN              PC  NAME
[AndroidDriver]     u0_a198   26091 565   1526920 170856 SyS_epoll_ 0000000000 S com.pscu.emf.dev
[AndroidDriver] Returning process name: 'S'
[AndroidDriver] Found webviews: ["WEBVIEW_S"]
[AndroidDriver] Available contexts: ["NATIVE_APP","WEBVIEW_S"]
[AndroidDriver] Connecting to chrome-backed webview context 'WEBVIEW_S'
[AndroidDriver] A port was not given, using random port: 8000
[Chromedriver] Changed state to 'starting'
[Chromedriver] Set chromedriver binary as: C:\Users\Sagar\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-chromedriver\chromedriver\win\chromedriver.exe
[Chromedriver] Killing any old chromedrivers, running: FOR /F "usebackq tokens=5" %a in (`netstat -nao ^| findstr /R /C:"8000 "`) do (FOR /F "usebackq" %b in (`TASKLIST /FI "PID eq %a" ^| findstr /I chromedriver.exe`) do (IF NOT %b=="" TASKKILL /F /PID %a))
[Chromedriver] No old chromedrivers seemed to exist
[Chromedriver] Cleaning any old adb forwarded port socket connections
[ADB] List forwarding ports
[ADB] Running 'D:\AndroidSDK\platform-tools\adb.exe' with args: ["-P",5037,"-s","HT6A40205681","forward","--list"]
[ADB] Removing forwarded port socket connection: 12238 
[ADB] Running 'D:\AndroidSDK\platform-tools\adb.exe' with args: ["-P",5037,"-s","HT6A40205681","forward","--remove","tcp:12238"]
[Chromedriver] Spawning chromedriver with: C:\Users\Sagar\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-chromedriver\chromedriver\win\chromedriver.exe --url-base=wd/hub --port=8000 --adb-port=5037 --verbose
[JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8000/wd/hub/status] with no body
[JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"\",\"status\":0,\"value\":{\"build\":{\"version\":\"alpha\"},\"os\":{\"arch\":\"x86_64\",\"name\":\"Windows NT\",\"version\":\"6.1.7601 SP1\"}}}"
[JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8000/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.pscu.emf.dev","androidUseRunningApp":true,"androidDeviceSerial":"HT6A40205681"}}}
[Chromedriver] Webview version: 'Chrome/61.0.3163.98'
[JSONWP Proxy] Got response with status 200: {"sessionId":"520c7063c5cb3abf380f3a3483a75052","status":0,"value":{"acceptSslCerts":true,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"browserName":"chrome","chrome":{"chromedriverVersion":"2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f)"},"cssSelectorsEnabled":true,"databaseEnabled":false,"handlesAlerts":true,"hasTouchScreen":true,"javascriptEnabled":true,"locationContextEnabled":true,"mobileEmulationEnabled":false,"nativeEvents":true,"pageLoadStrategy":"normal","platform":"ANDROID","rotatable":false,"setWindowRect":false,"takesHeapSnapshot":true,"takesScreenshot":true,"unexpectedAlertBehaviour":"","version":"61.0.3163.98","webStorageEnabled":true}}
[Chromedriver] Changed state to 'online'
[MJSONWP] Responding to client with driver.setContext() result: null
[HTTP] <-- POST /wd/hub/session/28160fb2-588e-4855-b87d-ff83052bf941/context 200 3506 ms - 76 
[HTTP] --> POST /wd/hub/session/28160fb2-588e-4855-b87d-ff83052bf941/element {"using":"name","value":"DONE "}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[JSONWP Proxy] Proxying [POST /wd/hub/session/28160fb2-588e-4855-b87d-ff83052bf941/element] to [POST http://127.0.0.1:8000/wd/hub/session/520c7063c5cb3abf380f3a3483a75052/element] with body: {"using":"name","value":"DONE "}
[JSONWP Proxy] Got response with status 200: {"sessionId":"520c7063c5cb3abf380f3a3483a75052","status":7,"value":{"message":"no such element: Unable to locate element: {\"method\":\"name\",\"selector\":\"DONE \"}\n  (Session info: chrome=61.0.3163.98)\n  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)"}}
[JSONWP Proxy] Replacing sessionId 520c7063c5cb3abf380f3a3483a75052 with 28160fb2-588e-4855-b87d-ff83052bf941
[HTTP] <-- POST /wd/hub/session/28160fb2-588e-4855-b87d-ff83052bf941/element 200 203 ms - 338 
[HTTP] --> DELETE /wd/hub/session/28160fb2-588e-4855-b87d-ff83052bf941 {}
[MJSONWP] Calling AppiumDriver.deleteSession() with args: ["28160fb2-588e-4855-b87d-ff83052bf941"]
[BaseDriver] Event 'quitSessionRequested' logged at 1509089065095 (12:54:25 GMT+0530 (India Standard Time))
[Appium] Removing session 28160fb2-588e-4855-b87d-ff83052bf941 from our master session list
[UiAutomator2] Deleting UiAutomator2 session
[AndroidDriver] Stopping chromedriver for context WEBVIEW_S
[Chromedriver] Changed state to 'stopping'
[JSONWP Proxy] Proxying [DELETE /] to [DELETE http://127.0.0.1:8000/wd/hub/session/520c7063c5cb3abf380f3a3483a75052] with no body
[JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"520c7063c5cb3abf380f3a3483a75052\",\"status\":0,\"value\":null}"
[Chromedriver] Changed state to 'stopped'
[UiAutomator2] Deleting UiAutomator2 server session
[JSONWP Proxy] Proxying [DELETE /] to [DELETE http://localhost:8200/wd/hub/session/2acb2d9d-4402-41d3-bec3-d00de874affd] with no body
[JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"2acb2d9d-4402-41d3-bec3-d00de874affd\",\"status\":0,\"value\":\"Session deleted\"}"
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'D:\AndroidSDK\platform-tools\adb.exe' with args: ["-P",5037,"-s","HT6A40205681","shell","am","force-stop","com.pscu.emf.dev"]
[Logcat] Stopping logcat capture
[ADB] Removing forwarded port socket connection: 8200 
[ADB] Running 'D:\AndroidSDK\platform-tools\adb.exe' with args: ["-P",5037,"-s","HT6A40205681","forward","--remove","tcp:8200"]
[BaseDriver] Event 'quitSessionFinished' logged at 1509089065664 (12:54:25 GMT+0530 (India Standard Time))
[MJSONWP] Received response: null
[MJSONWP] But deleting session, so not returning
[MJSONWP] Responding to client with driver.deleteSession() result: null
[HTTP] <-- DELETE /wd/hub/session/28160fb2-588e-4855-b87d-ff83052bf941 200 570 ms - 76 
[UiAutomator2] [UIAutomator2] io.appium.uiautomator2.server.test.AppiumUiAutomator2Server:.
[UiAutomator2] [UIAutomator2] Time: 81.042
[UiAutomator2] [UIAutomator2] OK (1 test)

**Comment by LukasLewandowski** [comment]
You have space after 'DONE ' in Your xpath. Are You sure it's correct? 

I thought that:

driver.findElement(MobileBy.xpath("//android.widget.Button[@content-desc='DONE']")).click()

will work.


Btw I am not using this: capabilities.setCapability("autoWebview","true"); and my previous post about fixed version of chromedriver release to crosswalk plugin for cordova based hybrid apps.

https://github.com/piotrekkmt/chromedriver-appium

But if You can switch to webview that means You don't need this, just use regular chromedrive from google.

**Comment by sagarsheth27** [comment]
No i am just switching as you said.
But earlier i also tried for capabilities.setCapability("autoWebview","true"), its also not working.
And yes there is a space in **DONE value, thus i passed space**. But with space or without space its not working.

**Comment by LukasLewandowski** [comment]
Have You tied using Appium inspector to locate that element? (Any inspector from any version of Appium desktop app)

**Comment by sagarsheth27** [comment]
Thank you so much @LukasLewandowski 

Its working now. :+1:  Sup Up job.
I used below code to do this.

Set contextName = driver.getContextHandles();
		System.out.println(contextName);
		for (Object o  : contextName) {
			String data=o.toString();
			System.out.println(data);
		if (data.contains("NATIVE_APP")) {
		System.out.println("Show me:" + data);
		Thread.sleep(1500);
		driver.context("NATIVE_APP");
		driver.findElement(MobileBy.AccessibilityId("DONE ")).click();//("//android.widget.Button[@content-desc='DONE ']")).click();
		}
		if (data.contains("WEBVIEW_chrome")) {
		driver.context("WEBVIEW_chrome");
		//driver.findElement(By.name("DONE")).click();
		driver.findElement(By.xpath("/html/body/ion-app/ion-picker-cmp/div/div[1]/div[2]/button/span")).click();
		}
		}
		driver.context("NATIVE_APP");

**Comment by dpgraham** [comment]
@sagarsheth27 You shouldn't have needed to change the driver context if you set `autoWebview` to `true`.

**Comment by sagarsheth27** [comment]
No its not working. I tried as you said. Thus we have to use driver context concept.
PFA log for same. @dpgraham 
[appium-server-logs.txt](https://github.com/appium/appium/files/1426105/appium-server-logs.txt)
