### ISSUE TITLE
Unable to find elements in XCUIElementTypeCollectionView in iOS 11

### ISSUE THREAD

**Issue by mauriparra** [appium/appium#9517]
## The problem

In iOS 11, all the elements that are in a XCUIElementTypeCollectionView, I can found it with appium if the element is showed in the screen. This problem not happens in iOS 10.3 using the same appium version

## iOS 10.3.1
![ios 10_3](https://user-images.githubusercontent.com/24278482/31946321-246b4c0e-b897-11e7-9485-7f033d098cc3.png)

## iOS 11
![ios 11](https://user-images.githubusercontent.com/24278482/31946337-2dd2643a-b897-11e7-9b51-5d3ff832a2f8.png)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Desktop OS/version used to run Appium: Mac OS Sierra 10.12.6
* Node.js version (unless using Appium.app|exe): 4.1.2
* Mobile platform/version under test: iOS 11
* Real device or emulator/simulator: Iphone 6 simulator 
* Appium CLI or Appium.app|exe: both

**Comment by mykola-mokhnach** [comment]
Elements tree is returned by [WebDriverAgent](https://github.com/facebook/WebDriverAgent) component. Appium cannot change anything there.
