### ISSUE TITLE
iOS - Page Source Returns Different Source for Same Elements on Page

### ISSUE THREAD

**Issue by HenryLecobee** [appium/appium#9520]
## The problem

I'm trying to run automation on:

iPhone SE iOS 11.0.3
iPhone 6S iOS 11.0

Page source returns different source for the same elements for on a native page

## Environment

* Appium 1.6.5
* iOS 11.0+
* Real Device

## Link to Appium logs

iPhone 6S iOS 11.0
https://gist.github.com/HenryLecobee/b3b5bf70a78fbb96f6c208355ff8d49b

iPhone SE iOS 11.0.3
https://gist.github.com/HenryLecobee/733d999b6b7b419757635dca7aa01f47

Any idea what is causing this difference?

**Comment by mykola-mokhnach** [comment]
We just show what WebDriverAgent returns to us. Please report to https://github.com/facebook/WebDriverAgent/issues
