### ISSUE TITLE
Authorize-ios not working

### ISSUE THREAD

**Issue by DarkSoully** [appium/appium#9521]
## The problem

When trying to run sudo authorize-ios. i recieve 2 erros. 

I have tried many thing but i cant find the solution.

## Environment

* Appium version 1.7.1
* Node.js version 6.11.1
* Xcode 9.0

## Code To Reproduce Issue [ Good To Have ]

```
info AuthorizeIOS Enabling DevToolsSecurity
info AuthorizeIOS Updating security db for developer access
info AuthorizeIOS Granting access to built-in simulator apps
info AuthorizeIOS The xcode directory is : /Applications/Xcode.app/Contents/Developer
info AuthorizeIOS Changing ownership to 'dylangomes' on directories: 
ERR! AuthorizeIOS Encountered an issue changing user priveledges for iOS sim app dirs: 
ERR! AuthorizeIOS Error was: Command 'chown -R dylangomes\:' exited with code 1
```

**Comment by hpCrowe** [comment]
I was experiencing the same problem, but I uninstalled Xcode 9 and installed Xcode 8.3.3 from [https://developer.apple.com/download/more/](url) and the problem went away. The rest of my environment is:

-Appium 1.7.1
-node.js 8.7.0
- High Sierra

**Comment by imurchie** [comment]
I don't think you need to run `authorize-ios` for most simulators anymore.

**Comment by Xiaoyuan1123** [comment]
i met the same problem, and did you resolve these 2 errors?

**Comment by imurchie** [comment]
Running this program is only necessary for Instruments-based automation. This means that is stopped being necessary for any Xcode above 7.3, when Instruments was removed. If you are testing using XCUITest, don't run this.

**Comment by imurchie** [comment]
Experimented a little. For reasons unclear to me, running `authorize-ios` and entering the password through the resulting popup does not work. But running `sudo authorize-ios` and entering the password through the command line works.

**Comment by sluthra-globallogic** [comment]
hey i am facing this issue can u please help me

**Comment by jpita** [comment]
> Running this program is only necessary for Instruments-based automation. This means that is stopped being necessary for any Xcode above 7.3, when Instruments was removed. If you are testing using XCUITest, don't run this.

@imurchie is this still accurate?

**Comment by mykola-mokhnach** [comment]
Closed as inactive
