### ISSUE TITLE
Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65".

### ISSUE THREAD

**Issue by karnakarg50** [appium/appium#9523]
An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 25.06 seconds

**Comment by mykola-mokhnach** [comment]
Please fill out the default issue reporting form.

Did you follow the instructions provided by that link?

**Comment by karnakarg50** [comment]
Yes i followed the all the instruction still its displaying same thing.

**Comment by mykola-mokhnach** [comment]
Are you able to build WebDriverAgent manually from Xcode?

**Comment by karnakarg50** [comment]
Am very new to the appium.
Can you please tell me the procedure with the screen shots ..

**Comment by mykola-mokhnach** [comment]
Sorry, we don't provide any support here, but solve issues. Please ask your questions on discuss.appium.io

**Comment by funkyvisions** [comment]
I am experiencing the same thing.  But only for a real iOS 11.1 device.  My iOS 10.3 device works fine.  My log is

[appium.log](https://github.com/appium/appium/files/1458140/appium.log)
