### ISSUE TITLE
Appium - retrieving value of SeekBar?

### ISSUE THREAD

**Issue by PaulinkaS** [appium/appium#9524]
## The problem
Impossible to retrieve value of SeekBars on Android

## Environment
* Appium version: 1.7.1
* Desktop OS/version used to run Appium: Windows 10
* Mobile platform/version under test: Android 7.0
* Real device or emulator/simulator: real devices
* Appium CLI or Appium.app|exe: CLI

## Details
We are struggling with getting the value set on the SeekBar in Android using .net driver. While this time setting the value is not a problem, it is impossible to verify if the action was performed successfully on the SeekBar itself. GetText() method is returning always empty string.

**Comment by mykola-mokhnach** [comment]
Try getValue()

**Comment by GrzegorzSidwa** [comment]
@mykola-mokhnach  we are using .NET driver. There is not Value/GetValue method on . When we're try to getAttribute value it's not possible (checked on AndroidBoottrap and there is no Value attribute indeed).

**Comment by mykola-mokhnach** [comment]
@TikhomirovSergey Is there any method in c sharp driver to read the value?

**Comment by mykola-mokhnach** [comment]
Can you attach the page source? There it should be visible which attributes are available.

**Comment by GrzegorzSidwa** [comment]
Basically I've checked page source when value of slider was 0 and when it was changed. In both cases page source of Seekbar looked exactly like below: 

`<android.widget.SeekBar index="1" text="" class="android.widget.SeekBar" package="com.tricentis.mobile" content-desc="DamageInsuranceSlider" checkable="false" checked="false" clickable="false" enabled="true" focusable="true" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[820,488][1419,547]" resource-id="com.tricentis.mobile:id/insuranceSumSlider" instance="0"/>`

**Comment by mykola-mokhnach** [comment]
Do you get the same output for UIAutomation2 driver?

**Comment by GrzegorzSidwa** [comment]
I've just checked it. Executed test with desired capability automationName 'UiAutomator2' but results look exactly the same.

`<android.widget.SeekBar index="1" text="" class="android.widget.SeekBar" package="com.tricentis.mobile" content-desc="DamageInsuranceSlider" checkable="false" checked="false" clickable="false" enabled="true" focusable="true" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[820,488][1419,547]" resource-id="com.tricentis.mobile:id/insuranceSumSlider" instance="0"/>`

**Comment by mykola-mokhnach** [comment]
OK, I'll check if anything can be done there.

**Comment by GrzegorzSidwa** [comment]
@mykola-mokhnach  just to clarify. Is there a big difference using UIAutomator2 instead of connecting to appium without AutomationName? Cause as I can see you flagged ticket like UIAutomator2 so in our case it will require switching to new automation as I understand.

**Comment by mykola-mokhnach** [comment]
Yep, UAAutomation1 is not supported by Google anymore, so it is a good idea to switch to the next version especially if you want to automate newer Android versions.

**Comment by mykola-mokhnach** [comment]
The fix has been merged to the recent Appium beta, uiautomation2 driver
