### ISSUE TITLE
VS2017 enters break mode during test execution

### ISSUE THREAD

**Issue by smoeller-liveid** [appium/appium#9525]
When running my tests in debug mode, VS2017 suddenly enters break mode, although I did not set any break points. And because it obviously didn't break in my code, it does not show any source code. I can continue, and it typically works, but sometimes this break mode comes right in the middle of an selection or similar, which then fails the whole test.

I'm experiencing this with Appium version v1.7.1 (installed via node.js 6.11.5) on Windows 10 (1709).
My application under test is a Windows WPF / C# application. The Appium.WebDriver is version 3.0.0.2, MSTest.TestAdapter is 1.2.0, Selenium.WebDriver is 3.6.0

It looks to me as if this happens always after the same time, not depending on the test itself. On my PC, it happens after approx. 1 minute, regardless of what test is running. Even if I defer some execution in one test (i.e. Thread.Sleep(20000), it still happens after 1 minute, so it looks to me as if it would be independent from the actual test code.
I asked colleagues to test, and the basically support my findings, but with different times (colleague A around 2:20min, colleague B around 3:50).

I'm not even sure if this is the right place to post, so any idea is highly appreciated.

**Comment by mykola-mokhnach** [comment]
I don't understand how the issue is related to Appium server. If this is a problem with [C# client](https://github.com/appium/appium-dotnet-driver) then please report it there.

**Comment by smoeller-liveid** [comment]
Sorry, I'm new to appium and did not fully comprehend the structure yet. Will re-post on client project. Thanks.
