### ISSUE TITLE
Failed to run python test using Appium with real iOS device

### ISSUE THREAD

**Issue by BoazWarshawsky** [appium/appium#9526]
## The problem
I am getting the following error when trying to launch a simple test against appium CLI server:
Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.

## Environment

Appium version  - 1.7.1
Last Appium version - first time I am using Appium
Desktop OS/version used to run Appium: Mac sierra 10.12.6
Node.js version - v6.11.4
Mobile platform/version under test - iOS 11.0.3
Real device or emulator/simulator - Real device, with simulator I don't see a problem.
Appium CLI or Appium.app|exe - Appium CLI

## Details
I am trying to run an iOS test.

## Link to Appium logs
https://github.com/BoazWarshawsky/iOSAutomationAgent/blob/master/appium.log

## Code To Reproduce Issue [ Good To Have ]
1. Launching Appium server successfully.
2. from MAc terminal running the following python script:
=========================================================
from appium import webdriver

PLATFORM_NAME = "platformName"
PLATFORM_VERSION = 'platformVersion'
DEVICE_NAME = "deviceName"
SHOW_IOS_LOGS = 'showIOSLog'
APP_PATH = 'app'
DEVICE_ORIENTATION = "portrait"
BROWSER_NAME = "browserName"
APPLICATION_FILE_PATH = "app_file_path"
CONFIGURATION_FILE = "configuration.json"
BUNDLE_ID = "bundleId"
UDID = "udid"

desired_caps = {
    PLATFORM_NAME: 'iOS',
    PLATFORM_VERSION: "11.0",#self.configuration.platform_version,
    DEVICE_NAME: "iPhone 6",#self.configuration.device_name,
    SHOW_IOS_LOGS: 'true',
    BUNDLE_ID: "Applicaster-LTD.AutomationExampleApp",#self.configuration.bundle_id,
    DEVICE_ORIENTATION: "portrait",
    UDID:"bda3cf30fd1e434c11afff0df5392bdc6529b70c",
}

driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)
driver.launch_app()

driver.close()
==============================================================

**Comment by mykola-mokhnach** [comment]
Did you follow that tutorial? Are you able to build WDA manually from Xcode?

**Comment by BoazWarshawsky** [comment]
Which tutorial exactly? I followed several ones, the one it referring me in the error appium raised? 

Regarding the WDA, which target should be build?
Because of provisioning matter, Can I edit the app bundle identifier in order to succeed building?

**Comment by mykola-mokhnach** [comment]
> https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md

The one that is explicitly mentioned in the error message

**Comment by BoazWarshawsky** [comment]
thanks, I will follow it,
Can you please answer to my other questions:
 
Regarding the WDA, which target should be build?
Because of provisioning matter, Can I edit the app bundle identifier in order to succeed building?

Thanks,

**Comment by BoazWarshawsky** [comment]
**## Problem solved** after doing the following actions:
Building WDA successfully !
Adding xcodeConfig.xcconfig under WDA workspace
Using iPhone Developer as the CODE_SIGN_IDENTITY
