### ISSUE TITLE
How can I swipe with no release() until need to release the element

### ISSUE THREAD

**Issue by lubshilk** [appium/appium#9527]
Hi,

Developing automation for IOS application that knows to send SMS. Chat of SMS messages looks exactly as standard IOS SMS chat (if you want to check the time of a message you need to swipe the message, otherwise timestamp is hidden)

So I need to swipe aside an element to get timestamp of SMS message 
I tried to use the solution described here #6257:
_Point p1=lastMsg.getLocation();
Dimension d1 = lastMsg.getSize();
int len = d1.getWidth(); 
TouchAction swipe = new TouchAction(driver);
//press-moveTo-release
swipe.press(lastMsg).moveTo(p1.getX() - len, p1.getY()).release().perform();_
Swipe works perfectly, the only problem, when i release, the screen goes back to original position, so all timestamps are hidden again

When I tried to remove release() and run  
_swipe.press(lastMsg).moveTo(p1.getX() - len, p1.getY()).perform();_
I receive exception
_Support for press(options={"element":"2F3DB122-011E-4A02-8102-4E3D091185C9"})-moveTo(options={"x":-320,"y":185}) gesture is not implemented. Try to use "mobile: *" interface to workaround the issue. Only these gestures are supported:
	doubleTap: 		doubletap
		tap(options={"count":2})
	tap: 		tap
		tap-release
		press-release
	longPress: 		longpress
		longpress-release
		press-wait-release
	drag: 		press-wait-moveTo-release
		longpress-moveTo-release
	scroll: 		press-moveTo-release
 (WARNING: The server did not provide any stacktrace information)_

Please, advice how can I catch timestamp?

**Comment by mykola-mokhnach** [comment]
Unfortunately this is not possible now.

**Comment by lubshilk** [comment]
Thanks for fast reply
Is it planned to make it possible?

**Comment by mykola-mokhnach** [comment]
Complex gestures support will be implemented, but I have doubts, that your scenario is going to work. The problem is, that XCTest blocks the client from sending further actions until the current one is completed.
