### ISSUE TITLE
Appium can't find Accessibility ID after scroll in iOS App

### ISSUE THREAD

**Issue by Seijan** [appium/appium#9528]
## The problem
I run into the problem that I have to scroll down on a page and after I did that I want to click on the new items that appeared, but instead of finding those elements by the accessibility ID I don't find them at all. I looked at it via the Appium Desktop and they are there if I scroll down beforehand, but not if I load the page initially and refresh after scrolling down in the app. 

<img width="1035" alt="screen shot 2017-10-25 at 16 39 33" src="https://user-images.githubusercontent.com/9142695/32005019-829baa8c-b9a3-11e7-946c-a62e5a5b9231.png">

Here you can see the existing Accessiblity Id for the field, now I scroll down a little and refresh the screen: 

<img width="1054" alt="screen shot 2017-10-25 at 16 44 13" src="https://user-images.githubusercontent.com/9142695/32005119-cb174f00-b9a3-11e7-8077-9708c6203a94.png">

Now the accessiblity ID is not there for the selected element, there are just three elements. None of them has accessibility ID's even after refreshing the page again. The only way to get the accessibility ID's for those fields is that you go to the page before and go again to this page and scroll down beforehand. This applies also when I'm executing the test via Intellij. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2-beta, but is the same on 1.7.1 as this appears in Appium Desktop as well
* Last Appium version that did not exhibit the issue (if applicable): 1.6.4
* Desktop OS/version used to run Appium: macOS Sierra 10.12.6
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS 11.0.1
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: Appium.app

## Link to Appium logs

https://gist.github.com/Seijan/fe5df3d17dfc9ec162a32053d9fb47ed

**Comment by mykola-mokhnach** [comment]
We get page source from [WebDriverAgent](https://github.com/facebook/WebDriverAgent/issues). Please report your issue there.

**Comment by Seijan** [comment]
Thanks, opened it in the WebDriverAgent GitHub. Hopefully they can resolve this issue.
