### ISSUE TITLE
Unlock capabilities failing with Samsung S8 running 7.0.0

### ISSUE THREAD

**Issue by sahilx13** [appium/appium#9530]
## The problem

Unlock capabilities are failing with Samsung S8 running 7.0.0. The error I am getting is "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Screen did not unlock successfully, retrying". When the unlock code will load, the lock screen will pop up but will fail right after that(seems like input numbers/elements are not recognized by the code.). Attaching the server side log.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Windows
* Node.js version (unless using Appium.app|exe): 6.9.1
* Mobile platform/version under test: Android 7.0.0
* Real device or emulator/simulator: Real device (Samsung S8)
* Appium CLI or Appium.app|exe: Appium.app
[appium-server-logs.txt](https://github.com/appium/appium/files/1417026/appium-server-logs.txt)

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
It is a known issue, that unlock utility is not compatible with Samsung devices. You could create a PR to fix it or set _skipUnlock_ capability to true if you don't need to unlock the device (only available with UIAutomation2 backend).
