### ISSUE TITLE
[Appium 1.7.1][Android]UiAutomator2 sendKeys to picker not working

### ISSUE THREAD

**Issue by Denny-Dong** [appium/appium#9532]
## The problem

UiAutomator2 sendKeys to picker not working ,When Using : 
capabilities.setCapability("automationName", "UIAutomator2");

But it's working when Using:
capabilities.setCapability("automationName", "Appium");

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable): Sorry I don't know
* Desktop OS/version used to run Appium: macOS Sierra 10.12.6
* Node.js version (unless using Appium.app|exe): 8.7.0
* Mobile platform/version under test: Android API 27 (I tried API 25-27 , all of them exhibited this issue)
* Real device or emulator/simulator: Android emulator
* Appium CLI or Appium.app|exe: Appium CLI 

## Details And Appium logs : 

**UiAutomator2 , Not Working log:**
[HTTP] --> POST /wd/hub/session/bf006170-6781-4c11-a136-459b6227d96a/element/33066837-4c00-4e0e-ac42-3958ac2e5e6a/value {"value":["杭州市"]}
[MJSONWP] Calling AppiumDriver.setValue() with args: [["杭州市"],"33066837-4c00-4e0e-ac42-3958ac2e5e6a","bf006170-6781-4c11-a136-459b6227d96a"]
[JSONWP Proxy] Proxying [POST /element/33066837-4c00-4e0e-ac42-3958ac2e5e6a/value] to [POST http://localhost:8200/wd/hub/session/0e504151-696f-4d4a-9eb6-82e9602acb2f/element/33066837-4c00-4e0e-ac42-3958ac2e5e6a/value] with body: {"elementId":"33066837-4c00-4e0e-ac42-3958ac2e5e6a","text":"杭州市","replace":false,"unicodeKeyboard":true}
[JSONWP Proxy] Got response with status 200: {"sessionId":"0e504151-696f-4d4a-9eb6-82e9602acb2f","status":0,"value":""}
[MJSONWP] Responding to client with driver.setValue() result: ""
[HTTP] <-- POST /wd/hub/session/bf006170-6781-4c11-a136-459b6227d96a/element/33066837-4c00-4e0e-ac42-3958ac2e5e6a/value 200 22 ms - 74 
[HTTP] --> GET /wd/hub/session/bf006170-6781-4c11-a136-459b6227d96a/source {}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[JSONWP Proxy] Proxying [GET /wd/hub/session/bf006170-6781-4c11-a136-459b6227d96a/source] to [GET http://localhost:8200/wd/hub/session/0e504151-696f-4d4a-9eb6-82e9602acb2f/source] with body: {}
[JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"0e504151-696f-4d4a-9eb6-82e9602acb2f\",\"status\":0,\"value\":\"
[JSONWP Proxy] Replacing sessionId 0e504151-696f-4d4a-9eb6-82e9602acb2f with bf006170-6781-4c11-a136-459b6227d96a
[HTTP] <-- GET /wd/hub/session/bf006170-6781-4c11-a136-459b6227d96a/source 200 50 ms - 21234 

**Appium , Working log :**
[HTTP] --> POST /wd/hub/session/fb976a55-7db0-4cb0-81a8-83ea681aaa80/element/1/value {"value":["杭州市"]}
[MJSONWP] Calling AppiumDriver.setValue() with args: [["杭州市"],"1","fb976a55-7db0-4cb0-81a8-83ea681aaa80"]
[AndroidBootstrap] Sending command to android: {"cmd":"action","action":"element:setText","params":{"elementId":"1","text":"杭州市","replace":false,"unicodeKeyboard":true}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:setText","params":{"elementId":"1","text":"杭州市","replace":false,"unicodeKeyboard":true}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: setText
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using element passed in: 1
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Attempting to clear using UiObject.clearText().
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Sending Unicode text to element: 杭州市
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Encoded text: &Z21d3l4C-
[AndroidBootstrap] Received command result from bootstrap
[MJSONWP] Responding to client with driver.setValue() result: true
[HTTP] <-- POST /wd/hub/session/fb976a55-7db0-4cb0-81a8-83ea681aaa80/element/1/value 200 5104 ms - 76 

## Code To Reproduce Issue [ Good To Have ]

public void elementSendText(final UIElement element, final String text) {
		By by = getBy(element.locator);
		this.driver.findElement(by).clear();
		this.driver.findElement(by).click();
		this.driver.findElement(by).sendKeys(text);
	}

**Comment by mykola-mokhnach** [comment]
@vmaxim Can you please take a look?

**Comment by nairouz12** [comment]
have the same issue. It works with Appium and not UIAutomator2

**Comment by vmaxim** [comment]
@mykola-mokhnach I'll take a look at next week. As a workaround we use [```replaceValue```](https://github.com/appium/java-client/blob/ab2ff11ae5cbce566a2e4bb3c65c457026d6b63a/src/main/java/io/appium/java_client/android/AndroidElement.java#L31) instead ```sendKeys``` - it works fine with NumberPicker and UiAutomator2.

**Comment by enguyen1967** [comment]
I have the same issue that can't set value for picker wheel on iOS. I can see the API sendKey() but can't see replaceValue(). Please tell me how to use it? I am using appium 1.7.1 and Xcode 8.3.3
Client.Driver.FindElementByXPath("myPath").sendKey("myvalue");
this work well in 1.5.3

**Comment by vmaxim** [comment]
I able to set value in `picker` with some reasonable extra steps for both `uia` and `uia2`. We can add tests against `pickers` when appium/android-apidemos#28 will be merged.

**Comment by mykola-mokhnach** [comment]
I've compared the current setText implementation of UIA1 and UIA2 and they look pretty the same. Also one can move the inout focus to the picker by clicking it and then decrease/increase its value by sending KEYCODE_DPAD_DOWN/KEYCODE_DPAD_UP keys to it

**Comment by mykola-mokhnach** [comment]
Looking at the current source there is nothing more to do for us on this topic. Also, interactions with different control types should be implemented better by Espresso driver, since it has direct access to them.
