### ISSUE TITLE
[Xcode] Code Signing Error: Signing for "WebDriverAgentRunner" requires a development team. Select a development team in the project editor.

### ISSUE THREAD

**Issue by showtime25st** [appium/appium#9533]
Hello, everyone!

## The problem

I followed instruction https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md

But the problem still exist

  "platformName": "iOS",
  "platformVersion": "11.0.3",
  "deviceName": "iPhone (Sergey)",
  "bundleId": "ru.ideast.tb-epato",
  "autoGrantPermissions": true,
  "noReset": true,
  "udid": "e1c050bf11503c92dae20b1f2ff3d75250c74346",
  "showXcodeLog": true

## Environment

* Appium version-1.7.1
* Desktop OS/version used to run Appium: yes
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS 
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: app

## Details

When I run Appium, it follows with: [MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device. 

## Link to Appium logs

log in attachment 
[appium-server-logs.txt](https://github.com/appium/appium/files/1417564/appium-server-logs.txt)

**Comment by mykola-mokhnach** [comment]
You are probably trying to use an enterprise signature to sign WDA source. This won't work.

**Comment by showtime25st** [comment]
Sorry, can you look at my screens, there are to many signatures. Where is mistake?  

https://monosnap.com/file/thvWFTFL4LsOR75XFNDDOuJzGi7Q05
https://monosnap.com/file/CX0qBdfbk8jv2qVVu3wbSgWlkJzYwN
https://monosnap.com/file/PtUoLaZfzeFGYMgNU1YOvoyMNLMPTT

**Comment by showtime25st** [comment]
Should I have payed developer account?

**Comment by dazhenseu** [comment]
I also get stuck in the same problem, and I am sure I use personal signature.

**Comment by dazhenseu** [comment]
You should refer to this part carefully: https://github.com/appium/appium/blob/master/docs/en/drivers/ios-xcuitest-real-devices.md#full-manual-configuration
"Xcode may fail to create a provisioning profile for the WebDriverAgentRunner target" ----this is why you encountered the building failed problem!

**Comment by saikrishna321** [comment]
Closing as user-side issue.

**Comment by radiobrain77** [comment]
I am experiencing the same problem. As far as I can see, it is not a user-side issue. In the WebDriverAgent, project, when I tick 'automatically manage signing' and then select my development team, the following is set:

Provisioning Profile = None Required
Signing Certificate = Don't Code Sign

I have built other apps in XCode and they have been signed.

I have followed the instructions in the docs. XCode is not failing to create a provisioning profile, it is not bothering to do so.

Is there something else that should be done?

**Comment by lodizn** [comment]
> I am experiencing the same problem. As far as I can see, it is not a user-side issue. In the WebDriverAgent, project, when I tick 'automatically manage signing' and then select my development team, the following is set:
> 
> Provisioning Profile = None Required
> Signing Certificate = Don't Code Sign
> 
> I have built other apps in XCode and they have been signed.
> 
> I have followed the instructions in the docs. XCode is not failing to create a provisioning profile, it is not bothering to do so.
> 
> Is there something else that should be done?

I'm also facing the same issue.
