### ISSUE TITLE
appium-xcuitest-driver not compatible with x-code 9.1:  Invalid device type: iPhone2017-C'

### ISSUE THREAD

**Issue by JonathanWylie** [appium/appium#9534]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Desktop OS/version used to run Appium: OSX High Sierra
* Node.js version (unless using Appium.app|exe): 8.6.0
* Mobile platform/version under test: 11.0.1
* Real device or emulator/simulator: simulator
* XCode version: 9.1
* Appium CLI or Appium.app|exe: Appium.app

## Details

After upgrading from X-code 9.0 to 9.1 I started seeing this error.
It looks like valid device type names have changed.
Unfortunately appium-xcuitest-driver translates the device types, so if I pass a now valid device type "iPhone X" then it translates it to "iPhone2017-C" which is not valid. 

## Link to Appium logs
` Appium | [simctl] Error: Could not create simulator with name 'appiumTest-17e71d87-af20-402e-a852-354b69758f07', device type id 'iPhone2017-C' and runtime id '11.0.1'. Reason: 'simctl error running 'create': Invalid device type: iPhone2017-C'`

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Try Appium 1.7.2-beta

**Comment by JonathanWylie** [comment]
Thankyou, that's fine.
