### ISSUE TITLE
Appium installing new app on real Android device broken

### ISSUE THREAD

**Issue by laurainwebo** [appium/appium#9535]
## The problem

I am trying to use Appium to install an Android application on a real device. If I configure Appium with the capability 'fullReset:true' the application does not install correctly, it shows an error upon startup (appName has stopped). However if I use Appium with fullReset:false and I pre-install my app via Android studio all works ok. This is problematic as I want my tests to be able to re-install the application each time. 

## Environment

* Appium version 1.7.1
* Desktop OS/version used to run Appium: Windows 10 Pro
* Mobile platform/version under test: Andoid 7.0
* Real device or emulator/simulator: Samsung Galaxy A5 (Samsung Experience Version 8.1)
* Appium CLI or Appium.app|exe: appium.exe
[appium-server-logs.txt](https://github.com/appium/appium/files/1417666/appium-server-logs.txt)

**Comment by mykola-mokhnach** [comment]
> [debug] [ADB] Getting connected devices...[debug] [ADB] Running 'C:\Users\laura\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","52100a8efc8224d7","shell","am","start","-W","-n","com.inwebo.pprauthenticator/com.inwebo.authenticator.viewSplash","-S"][error] [ADB] Error: Error occured while starting App. Original error: Error executing adbExec. Original error: 'Command 'C\:\\Users\\laura\\AppData\\Local\\Android\\sdk\\platform-tools\\adb.exe -P 5037 -s 52100a8efc8224d7 shell am start -W -n com.inwebo.pprauthenticator/com.inwebo.authenticator.viewSplash -S' timed out after 20000ms'; Stderr: ''; Code: 'null'

this means you provide incorrect values for appActivity/appWaitActivity capabilities

**Comment by saikrishna321** [comment]
@laurainwebo pls provide capability _androidInstallTimeout_ (Timeout in milliseconds used to wait for an apk to install to the device. Defaults to 90000)

@mykola-mokhnach app capability alone is provided. So i see adb fails on timeout for installation

**Comment by mykola-mokhnach** [comment]
Closed because of missing activity
