### ISSUE TITLE
Appium test, can not actually operate app,appium error is as follows

### ISSUE THREAD

**Issue by sun01girl** [appium/appium#9537]
info: [debug] Sent shutdown command, waiting for UiAutomator to stop...
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"shutdown"}
> info: [debug] [BOOTSTRAP] [debug] Got command of type SHUTDOWN
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":"OK, shutting down"}
> info: [debug] [UIAUTOMATOR STDOUT] close [socket][/127.0.0.1:4724]
> info: [debug] [BOOTSTRAP] [debug] Closed client connection
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=.
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServe
> info: [debug] [UIAUTOMATOR STDOUT] r
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 0
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
> info: [debug] [UIAUTOMATOR STDOUT] Test results for WatcherResultPrinter=.
> info: [debug] [UIAUTOMATOR STDOUT] Time: 78.492
> info: [debug] [UIAUTOMATOR STDOUT] OK (1 test)
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: -1
> info: [debug] UiAutomator shut down normally
> info: [debug] Cleaning up android objects
> info: [debug] Cleaning up appium session
> info: [debug] We shut down because no new commands came in

**Comment by mykola-mokhnach** [comment]
Please provide full server log and fill out the issue reporting form

**Comment by sun01girl** [comment]
I mean, there's a click in my code, but when I run the script, it doesn't click on the corresponding location on the APP, and the code doesn't go wrong, and I don't know why.  The server log is as follows.
nfo: [debug] Pushing command to appium work queue: ["element:click",{"elementId":"1"}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:click","params":{"elementId":"1"}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: click
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":true}
> info: [debug] Responding to client with success: {"status":0,"value":true,"sessionId":"3f753665-8f9e-44e8-a5b6-855936f73001"}
> info: <-- POST /wd/hub/session/3f753665-8f9e-44e8-a5b6-855936f73001/element/1/click 200 34.162 ms - 76 {"status":0,"value":true,"sessionId":"3f753665-8f9e-44e8-a5b6-855936f73001"}
> info: [debug] Didn't get a new command in 60 secs, shutting down...
> info: Shutting down appium session
> info: [debug] Pressing the HOME button
> info: [debug] executing cmd: D:\360瀹夊叏娴忚鍣ㄤ笅杞絓adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe -s 8DVWBMKBORT87D4D shell "input keyevent 3"
> info: [debug] Stopping logcat capture
> info: [debug] Logcat terminated with code null, signal SIGTERM
> info: [debug] Sent shutdown command, waiting for UiAutomator to stop...
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"shutdown"}
> info: [debug] [BOOTSTRAP] [debug] Got command of type SHUTDOWN
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":"OK, shutting down"}
> info: [debug] [UIAUTOMATOR STDOUT] close [socket][/127.0.0.1:4724]
> info: [debug] [BOOTSTRAP] [debug] Closed client connection
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=.
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServe
> info: [debug] [UIAUTOMATOR STDOUT] r
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 0
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
> info: [debug] [UIAUTOMATOR STDOUT] Test results for WatcherResultPrinter=.
> info: [debug] [UIAUTOMATOR STDOUT] Time: 78.492
> info: [debug] [UIAUTOMATOR STDOUT] OK (1 test)
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: -1
> info: [debug] UiAutomator shut down normally
> info: [debug] Cleaning up android objects
> info: [debug] Cleaning up appium session
> info: [debug] We shut down because no new commands came in

**Comment by mykola-mokhnach** [comment]
> D:\360瀹夊叏娴忚鍣ㄤ笅杞絓adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe -s 8DVWBMKBORT87D4D shell "input keyevent 3"

What is the output of this command being executed from terminal?
I assume the problem lies in Chinese characters, which are present in folder path.

**Comment by mykola-mokhnach** [comment]
>  info: [debug] Didn't get a new command in 60 secs, shutting down...

Also this line says the driver was automatically shut down because of the timeout while waiting for a new command.

**Comment by sun01girl** [comment]
my code  is very simple,as follows 
desired_caps={}
desired_caps[ 'platformName']='Android'
desired_caps['deviceName']='8DVWBMKBORT87D4D'
desired_caps['platformVersion']='6.0'
#apk包名
desired_caps['appPackage']='com.doshow'
#apk的launcherActivity
desired_caps['appActivity']='com.doshow.audio.bbs.activity.WelcomeActivity'

driver=webdriver.Remote('http://127.0.0.1:4723/wd/hub',desired_caps)
time.sleep(15)
driver.find_element_by_id("com.doshow:id/search").click()

**Comment by sun01girl** [comment]
When executing click operation, apppium log is as follows:  But there's no click on the search button on my phone
 info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: find
> info: [debug] [BOOTSTRAP] [debug] Finding com.doshow:id/search using ID with the contextId:  multiple: false
> info: [debug] [BOOTSTRAP] [debug] Using: UiSelector[INSTANCE=0, RESOURCE_ID=com.doshow:id/search]
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":{"ELEMENT":"1"}}
> info: [debug] Responding to client with success: {"status":0,"value":{"ELEMENT":"1"},"sessionId":"d087afe7-b9d3-4281-b154-360a1db9ddde"}
> info: <-- POST /wd/hub/session/d087afe7-b9d3-4281-b154-360a1db9ddde/element 200 31.304 ms - 87 {"status":0,"value":{"ELEMENT":"1"},"sessionId":"d087afe7-b9d3-4281-b154-360a1db9ddde"}
> info: --> POST /wd/hub/session/d087afe7-b9d3-4281-b154-360a1db9ddde/element/1/click {"id":"1","sessionId":"d087afe7-b9d3-4281-b154-360a1db9ddde"}
> info: [debug] Pushing command to appium work queue: ["element:click",{"elementId":"1"}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:click","params":{"elementId":"1"}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: click
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":true}
> info: [debug] Responding to client with success: {"status":0,"value":true,"sessionId":"d087afe7-b9d3-4281-b154-360a1db9ddde"}
> info: <-- POST /wd/hub/session/d087afe7-b9d3-4281-b154-360a1db9ddde/element/1/click 200 62.983 ms - 76 {"status":0,"value":true,"sessionId":"d087afe7-b9d3-4281-b154-360a1db9ddde"}
> info: [debug] Didn't get a new command in 60 secs, shutting down...
> info: Shutting down appium session
> info: [debug] Pressing the HOME button
> info: [debug] executing cmd: D:\360Download\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe -s 8DVWBMKBORT87D4D shell "input keyevent 3"
> info: [debug] Stopping logcat capture
> info: [debug] Logcat terminated with code null, signal SIGTERM
> info: [debug] Sent shutdown command, waiting for UiAutomator to stop...

**Comment by mykola-mokhnach** [comment]
Maybe there is some other element with the same id on this page. Also, you can try to calculate coordinates of this button and then perform click by coordinates.
