### ISSUE TITLE
appium runs webdriveragentrunner open app and closes

### ISSUE THREAD

**Issue by showtime25st** [appium/appium#9539]
## The problem

Appium runs webDriverAgentRunner open app and closes momently. And I can't open it on emulator by hand, it opens and closes 

[appium-server-logs.txt](https://github.com/appium/appium/files/1418473/appium-server-logs.txt)

caps:

  "platformName": "iOS",
  "platformVersion": "11.0",
  "deviceName": "iPhone 8",
  "app": "/Users/admin/Desktop/ВТБ_ЕПАМАВТО.app",
  "noReset": true,
  "showXcodeLog": true,
  "autoAcceptAlerts": true,
  "showIOSLog": true

Environment

Appium version-1.7.1
Desktop OS/version used to run Appium: yes
Node.js version (unless using Appium.app|exe):
Mobile platform/version under test: iOS
Real device or emulator/simulator: emulator
Appium CLI or Appium.app|exe: app

## Details

After closing app, 1 minutes later, webDriverAgentRunner reinstall and try open app again and no failures

**Comment by mykola-mokhnach** [comment]
> [info] [iOSLog] [IOS_SYSLOG_ROW] Oct 26 15:38:44 EPRUMOSW0707 com.apple.CoreSimulator.SimDevice.09476081-9596-43DA-B786-D682B086ECD4[11906] (UIKitApplication:ru.ideast.vtb-epamauto[0x5d9c][11935][12349]): Program specified by service does not contain any valid architectures for this system.

This is a problem with the application itself. Ask your developers to fix the build for Simulators
