### ISSUE TITLE
UiAutomator2 fails to run, changes appium-uiautomator2-server-v0.1.8.apk to 0mb

### ISSUE THREAD

**Issue by justintoth** [appium/appium#9541]
## The problem

I'm attempting to update my Appium project to leverage uiautomator2, as I'm having issues finding elements on newer versions of Android with the original uiautomator. When I switch to using uiautomator2 and try to run a test case, it errors about not being able to sign with default certificate. When this happens, the appium-uiautomator2-server-v0.1.8.apk file gets overwritten with a 0mb version, so I then need to copy down the original version again. What could be causing the signing error? Is JDK v9 not supported?

## Environment

* Appium version (or git revision) that exhibits the issue: Latest, just downloaded it today
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): Latest, just downloaded today
* Mobile platform/version under test: Android 8.0.0
* Real device or emulator/simulator: Nexus 6P
* Appium CLI or Appium.app|exe:

## Link to Appium logs

https://gist.github.com/justintoth/99161dac7cfa2a16ee402e5400948764

**Comment by mykola-mokhnach** [comment]
> Is JDK v9 not supported?

Yes this is correct guess. JDK 9 is not supported by the signing tool. It is known issue

**Comment by mykola-mokhnach** [comment]
@imurchie  FYI

**Comment by justintoth** [comment]
@mykola-mokhnach Thanks, switching to JDK 8 fixed the issue. Not sure if you guys manage appium-doctor or if it's a 3rd party dev, but it'd be useful if that checked the java version since it told me my setup was correct!
