### ISSUE TITLE
Element search strategy is case-sensitive in XCUITest

### ISSUE THREAD

**Issue by navnathkarche** [appium/appium#9545]
## The problem

When we find the element using Xpath or accessibility-id it not working for case-insensitive id or name in Xpath. 

## Environment

* Appium version (or git revision) that exhibits the issue: 7.1
* Desktop OS/version used to run Appium: MAC OS Sierra 10.12.4
* Node.js version (unless using Appium.app|exe): 7.10.1
* Mobile platform/version under test: iOS 10 (XCUITest)
* Real device or emulator/simulator: emulator

## Details

When we find the element using Xpath or accessibility-id it not working for case-insensitive id or name in Xpath.
e.g. element name is: 'Test'
     `Xpath= '//*[@name="test"]'`
      the above xpath not working in XCUITest,
      if we write xpath case-sensitive like `Xpath= '//*[@name="Test"]' ` it's working fine.

NOTE: The case insensitive searching is working with iOS 9.

**Comment by mykola-mokhnach** [comment]
It's by design. xpath search should be case sensitive and the previous functionality had a bug.

BTW, it is not recommended to use xpath location with xcuidriver, since its slow. Read https://github.com/facebook/WebDriverAgent/wiki/How-To-Achieve-The-Best-Lookup-Performance for more details

**Comment by navnathkarche** [comment]
@mykola-mokhnach is this also applicable for findByAccessibilityId?

**Comment by SatishGhuge** [comment]
@mykola-mokhnach If I have to find elements with dynamic values which keeps on changing to either case (lower/upper/camel). 
Can you please suggest me feasible solution for searching such elements.

Thanks

**Comment by mykola-mokhnach** [comment]
You could use predicate locators and explicitly ignore the case, for example:

```
"name =[c] 'blabla'"
```

will match the elements with accessibility id 'BLaBla' and 'blabla'.
