### ISSUE TITLE
Element events are not triggerd in WebView

### ISSUE THREAD

**Issue by alexcomsa** [appium/appium#9546]
## The problem

When testing applications that conain webviews  events are not triggerd on input fields. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1 
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium:  macOS 10.13 High Sierra
* Node.js version (unless using Appium.app|exe): 7.7.1
* Mobile platform/version under test: iOS 10.3.3 
* Real device or emulator/simulator: Real Device iPhone 6 
* Appium CLI or Appium.app|exe: appium CLI 

## Details

If you have an input field  in a webview that has an on blur action (Angular 1.6.2) after you use the sendKeys or setValue method a change event is not dispached to the DOM. This issue blocks actions that would be triggerd by the change event leading to test failures.

## Link to Appium logs
NA

## Code To Reproduce Issue [ Good To Have ]
```java
String url = "http://localhost:4444/wd/hub";
DesiredCapabilities desiredCapabilities=  new DesiredCapabilities();

desiredCapabilities.setCapability(MobileCapabilityType.BROWSER_NAME, "");
desiredCapabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, iosPlatformVersion);
desiredCapabilities.setCapability(MobileCapabilityType.DEVICE_NAME, iosDeviceName);
desiredCapabilities.setCapability(MobileCapabilityType.APP, homeBankApp.getAbsolutePath());
desiredCapabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, XCUI_TEST);
desiredCapabilities.setCapability(MobileCapabilityType.UDID, deviceUDID);
desiredCapabilities.setCapability(BUNDLE_ID, iosBundleID);

WebDriver driver = new  IosDriver<MobileElement>(url,desiredCapabilities);
driver.context("WebView");

WebElement input =  driver.findElement(By.xpath('//input[@id='myId']'));
input.sendKeys("MyString");
WebElement elementTriggerdByInputChange = driver.findElement(By.xpath('//div[@id='newElement']));
```

**Comment by mikea** [comment]
seems to be a dup of https://github.com/appium/appium/issues/9002

**Comment by mykola-mokhnach** [comment]
Closed as inactive
