### ISSUE TITLE
Appium 1.7.1, WDA ServerURLHere->http://[...]:0<-ServerURLHere

### ISSUE THREAD

**Issue by FrankThonig** [appium/appium#9547]
## The problem

WDA can generally be started via xcodebuild.

This works with the WDA:
- standalone version (from https://github.com/facebook/WebDriverAgent)
- coming with Appium 1.6.5

From Log:
ServerURLHere->http://[...]:8100<-ServerURLHere

It does not work with the WDA:
- coming with Appium 1.7.1

From Log:
ServerURLHere->http://[...]:0<-ServerURLHere

With Appium 1.7.1, the WDA does when being started by Appium when instantiating the Remote Webdriver in code without the desired_capabilities["webDriverAgentUrl"] being set.
However, going into the Appium log, copying the exact command line which is written there (used here in the "Details" section), and executing that command leads to the issue named above.

So, apparently, the call of the xcodebuild is not executed in exactly the same way for both:
- by Appium during instantiation of Remote Webdriver
- manually in shell

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1 (also 1.6.6-beta)
* Last Appium version that did not exhibit the issue (if applicable): 1.6.5
* Desktop OS/version used to run Appium: macOS Sierra version 10.12.6
* Node.js version (unless using Appium.app|exe): v8.3.0
* Mobile platform/version under test: iOS 10.3
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: Appium CLI

## Details

Command line, copied from Appium log and executed separately in shell:

`xcodebuild build-for-testing test-without-building -project [...]/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=[...] IPHONEOS_DEPLOYMENT_TARGET=10.3 > "[...]/stdout.txt" 2> "[...]/stderr.txt"`

Same issue occurrs when calling the build/test from Xcode GUI.

## Link to Appium logs

Listing also WDA logs, because the issue is related to the specific WDA coming with Appium.

With issue for WDA in Appium 1.7.1, when using xcodebuild:

 stdout_1_7_1.txt: https://gist.github.com/FrankThonig/141b7ba87b9b85e67974172129706779
 stderr_1_7_1.txt: https://gist.github.com/FrankThonig/113b45c17858ee431d9cc527ad7d8acf
 xcode_1_7_1.txt: https://gist.github.com/FrankThonig/6e2dfbd3efdb59710340d27ba38c8e0f

Without issue for WDA in Appium 1.7.1, when being started by Appium without desired_capabilities["webDriverAgentUrl"] being set:

 appium_1_7_1.txt: https://gist.github.com/FrankThonig/0d90f9ab993084a51de3e4d8ccb8c65b

Without issue for WDA in Appium 1.6.5, when using xcodebuild:

 stdout_1_6_5.txt: https://gist.github.com/FrankThonig/65901607854f709ed3c35fab1906857c
 stderr_1_6_5.txt: https://gist.github.com/FrankThonig/ea7913aa5c3ec3bebe1173f2cdf1cfd0
 xcode_1_6_5.txt: https://gist.github.com/FrankThonig/62c622841f7f189254bc928f64c71628

**Comment by mykola-mokhnach** [comment]
add USE_PORT=8100 at the beginning of xcodebuild execution command

**Comment by FrankThonig** [comment]
@mykola-mokhnach 
this is exactly what i was looking for. i did not find any documentation on how to do this.
WDA now runs as expected on the given port.
thank you very much.

**Comment by mykola-mokhnach** [comment]
this document might be useful
https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/wda-custom-server.md

**Comment by FrankThonig** [comment]
thank you very much for that info

**Comment by FrankThonig** [comment]
thank you very much for that information
