### ISSUE TITLE
Unable to inspect paypal webview

### ISSUE THREAD

**Issue by rgupta7888** [appium/appium#9548]
Hi Team, 

I am trying to automate PayPal webview where I need to inspect email & password text field but I am not getting any details while inspection as I could see only XCUIElementTypeWebView class name with empty data. Even I checked appium logs it does not have any details about paypal webview.

So, I am unable to inspect further.Please help!

**Comment by mykola-mokhnach** [comment]
You need to switch to webview in order to inspect the content there. It is not available in native context since Xcode9, due to some internal changes that Apple did there.

**Comment by rgupta7888** [comment]
I am inspecting the iOS mobile element with the below  
 https://github.com/mykola-mokhnach/appium-iOS-inspector 

So, I cannot see any option which switches the context to webview. I tried using appium GUI version but I am automating the test flight build directly so while starting a new session I am getting bad app name because I am entering only app name which is installed on the device.

Please help!

**Comment by mykola-mokhnach** [comment]
Appium inspector is only usable to inspect native context. For webviews one can use the standard remote debugging feature available in Safari.

**Comment by rgupta7888** [comment]
Did you mean turning on the web inspector under Setting < Safari < Advanced < Web inspector.I tried it by turn it on but still, i am unable to get the PayPal webview mobile Elements.
Please guide me if I am missing something.

**Comment by rgupta7888** [comment]
@mykola-mokhnach @sah @tanob @hugs 
I am using right dev provisioning profile but still, I am unable to inspect Paypal webview. When I use the appium ios inspector I could see only XCUIElementTypeWebView of PayPal screen with no textField in it. So, basically I am clueless here.

Please suggest someone how to get rid of one :(

**Comment by deepakkg88** [comment]
@rgupta7888 I am also facing same issue.Did you get any work around for this?

Thanks in advance,
Deepak

**Comment by rgupta7888** [comment]
@deepakkg88 

Nope dude still I am not getting the right solution for that. I tried it in another way around by using Xcode accessibility inspector coz it shows PayPal webviews but the problem is using that is appium can not simulate the keyboard. It identifies the webview. You can try it out using Xcode accessibility inspector.
