### ISSUE TITLE
NameError: name 'TouchAction' is not defined

### ISSUE THREAD

**Issue by lundstrj** [appium/appium#9552]
## The problem

When running python code generated by the Appium app recorder it throws a:

> NameError: name 'TouchAction' is not defined

## Environment

* Appium version (or git revision) that exhibits the issue: Version 1.2.6 (1.2.6)
* Last Appium version that did not exhibit the issue (if applicable): None
* Desktop OS/version used to run Appium: macOS Sierra 10.12.6 (16G29)
* Node.js version (unless using Appium.app|exe): v6.11.5
* Mobile platform/version under test: Android 8.0.0
* Real device or emulator/simulator: Nexus 5X
* Appium CLI or Appium.app|exe: Welcome to Appium v1.7.1

## Details

None

## Link to Appium logs

None

## Code To Reproduce Issue [ Good To Have ]

```
from appium import webdriver

caps = {}
caps["deviceName"] = "foo"
caps["platformName"] = "Android"
caps["app"] = <YOUR APK PATH>
driver = webdriver.Remote("http://localhost:4723/wd/hub", caps)
driver.implicitly_wait(5)

TouchAction(driver).tap([(200, 381)]).perform()
```

## Suggested fix
add `from appium.webdriver.common.touch_action import TouchAction` to boilerplate.

**Comment by mykola-mokhnach** [comment]
Please report to https://github.com/appium/appium-desktop/issues
