### ISSUE TITLE
Send keys error in Appium Inspector

### ISSUE THREAD

**Issue by bobcheng-huafu** [appium/appium#9554]
## The problem

Error while clicking [Send Keys] command in Appium Inspector

## Environment

* Appium Desktop 1.2.6
* MacOS Sierra 10.12.6
* Node.js version v8.8.0
* Android emulator BlueStacks 0.9.30
* this test apk https://github.com/appium/sample-code/blob/master/sample-code/apps/ApiDemos/bin/ApiDemos-debug.apk

## Details

* Launch Appium Desktop
* Start Inspector Session with:
{
  "platformName": "Android",
  "platformVersion": "4.4.2",
  "deviceName": "emulator-5554",
  "app": "/Users/bob/test/ApiDemos-debug.apk",
  "automationName": "UiAutomator2"
}
* Click 'App' in BlueStacks
* Click 'Alert Dialogs' in BlueStacks
* Click 'Text Entry dialog' in BlueStacks
* Click 'Refresh Source & Screenshot' icon on top of Inspector window
* Click Name Text Field so <android.widget.EditText resource-id="io.appium.android.apis:id/username_edit"> is highlighted
* Click 'Send Keys' button under Selected Element, enter some test data like 1234, click blue 'Send Keys' button
* Error is shown: Error [element.sendKeys("1234")] Error response status: 13, UnknownError - An unknown server-side error occurred while processing the command. 

## Link to Appium logs

https://gist.github.com/bobcheng-huafu/fdefa9676b4cf00a225102f1fc52df46

## Code To Reproduce Issue [ Good To Have ]

https://gist.github.com/bobcheng-huafu/7f34c7dcba8bc08d0888b27551b3d097

**Comment by mykola-mokhnach** [comment]
Is the matched element really a text field? What is the result of getText call on it?

**Comment by mykola-mokhnach** [comment]
UIA2 cannot be used with Android OS lower than 5.0

**Comment by bobcheng-huafu** [comment]
@mykola-mokhnach I do not see any references about this (UIA2 requires Android 5.0 or later) in Appium documentation. If this is true, could you log warning messsage in next Appium release?

**Comment by bobcheng-huafu** [comment]
@mykola-mokhnach I just find a real device with Android 7.1.1 and test code works fine. Thanks for your help.

**Comment by mykola-mokhnach** [comment]
It is a good idea to add such verification into UIA2 driver. Will do it after https://github.com/appium/appium-adb/pull/269is merged
