### ISSUE TITLE
[Appium 1.7.1] org.openqa.selenium.WebDriverException: disconnected: unable to connect to renderer

### ISSUE THREAD

**Issue by cuong6690** [appium/appium#9555]
## The problem
I am testing hybrid app, which has native and webview part, plus webview has multiple windows (around 8 to 10). I want to switch between these windows.

I am executing parallelly on multiple android devices with Appium Server running on different ports for each device.

But i am getting following error ,While switching between windows :
org.openqa.selenium.WebDriverException: disconnected: unable to connect to renderer
  (Session info: chrome=61.0.3163.98)
  (Driver info: chromedriver=2.30.477700 (0057494ad8732195794a7b32078424f92a5fce41),platform=Windows NT 6.1.7601 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 4.04 seconds
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'CPP00082434B', ip: '192.168.254.2', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_31'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities [{appPackage=apptest.mobile.v2, app=D:/Git repo/apptest-real-project/src/main/resources/apk/apptest-android-m-full-debug_20170926.apk, deviceName=Android, platform=ANY, --override-session=true, appActivity=apptest.mobile.v2.intro.IntroActivity, newCommandTimeout=7200, platformVersion=null, automationName=Uiautomator2, unicodeKeyboard=true, udid=330071a3d722a309, platformName=Android, resetKeyboard=true, systemPort=60888}]
Session ID: 66fa67b5-6f59-4109-9ecd-b6c979c3ae3a

I face this issue only while executing on multiple devices.
When i execute on single device, i am able to switch between windows.

I am able to execute scripts belongs to native and webview part of app parallelly on multiple android devices Simultaneously.(but not able to switch between windows)

I was not facing above mentioned issues on Appium 1.6.5.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable): 1.6.5
* Desktop OS/version used to run Appium: Windows
* Mobile platform/version under test: Android
* Real device or emulator/simulator: multiple android devices (like 7.0 and 6.0).

I am using following code to launch start appium server for each device (android):
AppiumDriverLocalService service = AppiumDriverLocalService.buildService(new AppiumServiceBuilder().usingPort(port)
** .withArgument(AndroidServerFlag.BOOTSTRAP_PORT_NUMBER, chromePort)**
** .withArgument(GeneralServerFlag.SESSION_OVERRIDE)**
** .withArgument(AndroidServerFlag.CHROME_DRIVER_PORT, bootstrapPort));**

** service.start();**

**Comment by mykola-mokhnach** [comment]
Try to use newer chromedriver version

**Comment by cuong6690** [comment]
Hi @mykola-mokhnach I have tried it with latest chrome version (2.33) but still getting this issue

**Comment by cuong6690** [comment]
Hi @mykola-mokhnach , Have this issue solved ?

**Comment by mykola-mokhnach** [comment]
Closed as chromedriver issue

**Comment by Sankeerth315** [comment]
WebDriverException: Connection refused :Connect 
Iam getting this error when iam launching the appium server ?
