### ISSUE TITLE
Scroll to element does not work when keyboard is open in XCUITest

### ISSUE THREAD

**Issue by navnathkarche** [appium/appium#9557]
## The problem

When keyboard is open in app and we use scroll to element it throws the error.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Desktop OS/version used to run Appium: Mac OS sierra 10.12.4
* Node.js version (unless using Appium.app|exe): 7.10.1
* Mobile platform/version under test: iOS 10
* Real device or emulator/simulator: Simulator

## Details
When keyboard is open in app and we use scroll to element it throws the error.
For scroll to element I am using 
`driver.execute_script('mobile: scroll', { element: "079E792C-4481-49A1-AFC4-7AE445175AFB", 'toVisible': 'true'})` referred from [this](https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios/ios-xctest-mobile-gestures.md#mobile-scroll).

**Error throw by appium** `"Error Domain=com.facebook.WebDriverAgent Code=1 \"Failed to find scrollable visible parent with 2 visible children\" UserInfo={NSLocalizedDescription=Failed to find scrollable visible parent with 2 visible children}"`

## Link to Appium logs

https://gist.github.com/navnathkarche/2a94abd502c1ecded99dbc940f3db3a0

## Code To Reproduce Issue 

1. pen keyboard in your app
2. Use scroll to element method
3. Observe the appium log.

**Comment by mykola-mokhnach** [comment]
Please report to https://github.com/facebook/WebDriverAgent/issues
