### ISSUE TITLE
iOS - Clicking element within IFrame executes, but nothing happens within app

### ISSUE THREAD

**Issue by siggerzz** [appium/appium#9560]
## The problem

I'm trying to click an element within an IFrame on iOS. If I switch to the IFrame, and then attempt to click the element. Appium executes the click, however nothing happens within my app. I'm using the exact same code for my Android test, and it's working as expected.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable): Unable to test in earlier versions, as IFrame switching was being ignored.
* Desktop OS/version used to run Appium: MacOS
* Node.js version (unless using Appium.app|exe): 6.10.3
* Mobile platform/version under test: iOS 11.0.3
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs

[Appium Log](https://gist.github.com/siggerzz/7348b6f2ee08c10f75d2abba6efa2245) - Attempting to click the element found on line 32.

## Code To Reproduce Issue [ Good To Have ]

Switch to  IFrame using:
`
driver.SwitchTo().Frame(iframeElement);
`

Find Element within IFrame.
Click said element.

**Comment by shane51** [comment]
I have similiar issue.
Currently, I used tap with coordinates to solve it, but it is only a workaround.

```
 protected  void tapOnCoordinates(final double x, final double y) {
        switchToNativeView();
        Driver.executeScript("mobile: tap", new HashMap<String, Double>() {
            {
                put("tapCount", (double) 1);
                put("touchCount", (double) 1);
                put("duration", 0.5);
                put("x", (double) x);
                put("y", (double) y);
            }
        });
    }
```

**Comment by siggerzz** [comment]
Any update on this? I'm currently unable to run 1/3 of my test suite on iOS because of this.

**Comment by tatianetosta** [comment]
Hello. I have the same issue. The sendkeys to a element in iFrame also does not work.

**Environment:**

* Appium version (or git revision) that exhibits the issue: 1.8.2-beta
* Desktop OS/version used to run Appium: MacOS
* Node.js version (unless using Appium.app|exe): 10.4.1
* Mobile platform/version under test: iOS 11.4
* Real device or emulator/simulator: Real Device

**Comment by umanjuna** [comment]
I have the same issue with send keys method not working within an iFrame.

Environment:

Appium version (or git revision) that exhibits the issue: 1.8.1
Desktop OS/version used to run Appium: MacOS
Node.js version (unless using Appium.app|exe): 10.5.0
Mobile platform/version under test: iOS 11.3
Real device or emulator/simulator: IOS Simulator - iPhone 8 plus

**Comment by mykola-mokhnach** [comment]
Closed as third party issue.
Read https://appiumpro.com/editions/36 for more details
