### ISSUE TITLE
Inconsistent text value return in Android N vs Android M when allAllCaps value is defined

### ISSUE THREAD

**Issue by namlegt** [appium/appium#9562]
## The problem

If a text that has textAllCaps value defined as true,
`strings.xml: <string name="hello">Hello</string>`

on a view:  
`<TextView text="Hello" android:textAllCaps="true" />`

```
Appium getText() returns:
	Android N, O:  "HELLO" 
	Android M:      "Hello" 

```
## Environment

* Appium 1.6.5
* Android M, N, O

## Details

Now if I run my tests on Android N device, the tests fail, but same tests will pass on an Android M device because I reference the text value to the same string ID of "hello"(=Hello) as the expected result. How should I handle the case? 

Current appium doesn't support the detection of textAllCaps value either. 

if textAllCaps could be detected, something like this could be done: 

pseudo code: 
if allTextValue == true: assertEquals( getString(stringID).UPPERCASE, actualString)
if allTextValue == false: assertEquals( getString(stringID), actualString)

Enhancement? Thanks!

**Comment by mykola-mokhnach** [comment]
Which automation backend fo you use?

**Comment by tfcardoso** [comment]
This behavior can be seen directly in uiautomatorviewer, so I think the "problem" is before appium.

I just adapted by code to handle it depending on the Android version I'm connected to.

Android 5:
[https://i.imgtc.com/7VK5Can.png](url)

Android 7:
[https://i.imgtc.com/46Rei4N.png](url)

**Comment by namlegt** [comment]
@tfcardoso yes it can be detected in uiautomatorviewer. So I doubt that it's appium's fault. But if appium can make textallCaps detectable, that would help for testing purposes. 

Because depending on different view or different scenarios, a text can be rendered/formatted differently!

**Comment by tfcardoso** [comment]
@namlegt That would be great, but I highly doubt its possible to know if one element text has the attribute textAllCaps in strings.xml. They would have to decode the apk and then find a relation between the style and the element under analyses.

**Comment by mykola-mokhnach** [comment]
@vmaxim How do you think, is it theoretically possible to implement this enhancement with UIA2 or not?

**Comment by namlegt** [comment]
@tfcardoso absolutely textAllCaps is not defined in strings.xml. It's more the style layout under each particular view. Depending on design, a text referenced from strings.xml can be formatted differently on different views, so I think it's more likely defined in page source? just throw out some ideas here..

**Comment by vmaxim** [comment]
@mykola-mokhnach I can't see any way to get original text without formatting.

**Comment by mykola-mokhnach** [comment]
Yep, I had the same doubts. @namlegt You could pop a PR if you have any ideas on how the feature can be implemented.
