### ISSUE TITLE
Appium can't sendKey to the field but can tap the button[AXValidations] UIAccessibility Error adding -[CAMLightingControl accessibilityLabel]

### ISSUE THREAD

**Issue by showtime25st** [appium/appium#9563]
## The problem

I can tab buttons, but can't make sendKey

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Desktop OS/version used to run Appium: desktop
* Node.js version (unless using Appium.app|exe): Appium.app
* Mobile platform/version under test: iOS - 11.0.3
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: Appium.app

## Link to Appium logs

[Untitled.txt](https://github.com/appium/appium/files/1430219/Untitled.txt)

## Code To Reproduce Issue [ Good To Have ]

"platformName": "iOS",
  "platformVersion": "11.0.3",
  "deviceName": "Phone (Sergey)",
  "app": "/Users/admin/Desktop/testApp/ABC.app",
  "autoGrantPermissions": true,
  "noReset": true,
  "udid": "e1c050bf11503c92dae20b1fxxxxxxxxxxxxx",
  "showXcodeLog": "true"

**Comment by mykola-mokhnach** [comment]
Please report to https://github.com/facebook/WebDriverAgent/issues
