### ISSUE TITLE
Question - iOS - Does Appium support apps installed via Testflight?

### ISSUE THREAD

**Issue by siggerzz** [appium/appium#9564]
## The problem 
Currently I'm installing a new IPA every time our iOS app is updated. I was wondering if Appium supports the ability to use apps that've been installed via Testflight, allowing you to refer to the bundleID, rather than the IPA.

The problem I have, is that when I've tried this in the past, my app (hybrid) launches, however nothing happens once the app has launched. However if I install the IPA manually, my tests run fine.

If I could get some clarification on this, it'd be appreciated!

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2-beta
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Mac OS
* Node.js version (unless using Appium.app|exe): 6.10.3
* Mobile platform/version under test: iOS 11.0.3
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: CLI

**Comment by dpgraham** [comment]
You can yes. See https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/caps.md#ios-only

**Comment by siggerzz** [comment]
@dpgraham Any idea what might be causing my issue of nothing happening once my app (installed via testflight) has been opened?

Tests run fine if I provide the IPA. I can provided Appium logs if needed.

**Comment by dpgraham** [comment]
Yeah if you can provide the logs that would be helpful.

**Comment by siggerzz** [comment]
@dpgraham No worries! I just tried tried to run via Testflight again and it seems to be working now :D
