### ISSUE TITLE
Appium 1.7.1+ /wda/dragfromtoforduration doesn't do anything for right to left swiping on iOS 10.3

### ISSUE THREAD

**Issue by cosminstirbu** [appium/appium#9565]
## The problem

Right to left swiping doesn't work on iOS 10.3, but it does on iOS 11 (on my UITableView rows)

## Environment

* Appium version (or git revision) that exhibits the issue:1.7.1 and 1.7.2 beta
* Last Appium version that did not exhibit the issue (if applicable): :-?
* Desktop OS/version used to run Appium: macOS 10.12.6
* Node.js version (unless using Appium.app|exe): v8.6.0
* Mobile platform/version under test: iOS 10.3 and iOS 11
* Real device or emulator/simulator: iPhone 5s Simulator
* Appium CLI or Appium.app|exe: CLI

## Code To Reproduce Issue

Right to left swiping (nothing happens on the UI on iOS 10.3, works on iOS 11)
```
POST /session/27338D52-9798-4FB4-9EE0-D2FC9DE62A97/wda/dragfromtoforduration HTTP/1.1
Host: localhost:57753

{"fromX":300,"fromY":469,"toX":100,"toY":469,"duration":0.200}
```

vs

Left to right swiping (works on both iOS 10 and 11)
```
POST /session/27338D52-9798-4FB4-9EE0-D2FC9DE62A97/wda/dragfromtoforduration HTTP/1.1
Host: localhost:57753

{"fromX":0,"fromY":469,"toX":100,"toY":469,"duration":0.200}
```

**Comment by mykola-mokhnach** [comment]
Perhaps you just use the wrong method. Try "mobile: swipe"

**Comment by mykola-mokhnach** [comment]
Anyway, if there is a problem there then it's for sure on WebDriverAgent side and should be reported there.

**Comment by cosminstirbu** [comment]
Do you have a snippet of how "mobile: swipe" would look using Java Client?

Also, wouldn't "mobile: swipe" be resolved to /wda/dragfromtoforduration in the end?

I'll clone the issue on WebDriverAgent as well though.

**Comment by cosminstirbu** [comment]
Created https://github.com/facebook/WebDriverAgent/issues/772

**Comment by mykola-mokhnach** [comment]
nope, there is a separate endpoint fro swipe, which is mapped to https://developer.apple.com/documentation/xctest/xcuielement/1618674-swiperight, etc. element methods. Here is the doc: https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios/ios-xctest-mobile-gestures.md

**Comment by cosminstirbu** [comment]
Works well on both iOS 10.x and iOS 11.x

Thank you.

I'll leave the WDA issue open though.
