### ISSUE TITLE
Call running on mobile vs skype-like solution : mobile app reboots after some time

### ISSUE THREAD

**Issue by mars-tial** [appium/appium#9566]
## The problem

Hi there,
I am currently using Appium on a automated test bench using in combination with Robot Framework and Selenium. In my tests plans there are several long tests  such as one where the goal is to assert a communication between a mobile (Android 7.1.1) and a distant viewer in a chrome interface stands for one hour. You can see the solution as a skype like system. When I operate the said test, everything works fine for a time but after 51 minutes (tested several times on different computers) the mobile soft-reboots (the solution uses a webview and only the webview reboots, no "hard"-reboot).
Investigating the problem I suspect there might be a memory leak somewhere which I'd like to shut down.
The same problem several months ago on a tests where (still using appium) the mobile was supposed to take 50 pictures, the exact same thing happened but time passed by and I couldn't find time to invesigate.
Bear in mind that both these tests works fine when operated by hand

Can someone help me out finding the leak and closing it ?
Regards

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3 and 1.7.1
* Last Appium version that did not exhibit the issue (if applicable): None
* Desktop OS/version used to run Appium: Ubuntu 16.04
* Node.js version (unless using Appium.app|exe): v8.8.1 (and v4.*.* before that)
* Mobile platform/version under test: Android 7.1.1
* Real device or emulator/simulator: Google Pixel
* Appium CLI or Appium.app|exe: 

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Just waiting for my mobile to charge, I'll transmit them as soon as I have ran the test again

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

[one_hour_call_test.txt](https://github.com/appium/appium/files/1431127/one_hour_call_test.txt)

**Comment by mykola-mokhnach** [comment]
Does the leak happen in Appium or in the application under test? Are there any logs/error stacktraces?

**Comment by mars-tial** [comment]
Hi,
Thanks for the answer, no I think the leak happens in Appium perhaps in the ressources accumulated either on the mobile or the PC. I forgot to mention that wile observing NodeJS occupation of the memory I observed a continuous and regular augmentation of the memory allocated, and everytime it seems to cut the mobile when reaching the same limit.

As for logs my mobile is currently charging, I'll soon be able to launch the test, record logs and provide them to you. Will the --log-timestamp option do the trick ?

Regards

**Comment by mykola-mokhnach** [comment]
It could be related to https://github.com/appium/appium-support/pull/55
This fix will be merged soon

**Comment by mars-tial** [comment]
Yes I saw and read this thread before, perhaps it might be it only time will tell.
Can you keep this topic open just for a while so that I can make sure this will correct my issue ?

**Comment by mykola-mokhnach** [comment]
Please update Appium to the recent beta version and try again. The issue should be addressed there.

**Comment by mars-tial** [comment]
Hi all,
I tried updating to the latest beta version (1.7.2) and it didn't work, I couldn't even unroll my test till the point i used to bug.
I've got an error : 
"Message: An unknown server-side error occurred while processing the command. Original error: A new session could not be created. (Original error: session not created exception: Chrome version must be >= 60.0.3112.0
  (Driver info: chromedriver=2.33.506092 (733a02544d189eeb751fe0d7ddca79a0ee28cce4),platform=Linux 4.4.0-98-generic x86_64))"

I then switched back to appium regular 1.7.1 and everything worked fine. Well, the test was launched but it still ended at 51 minutes as it used to. Is there a specific option to specify in order to use appium beta ?

Subsidiary, I was wondering if appium used RAM space on the phone maybe ?

Regards

**Comment by mykola-mokhnach** [comment]
Newer Appium contains newer chromedriver version and this needs to be adjusted with your current chrome version.

https://github.com/appium/appium/blob/aa9711817436cb0bd7962c3f85db6efe2c9c8d02/docs/en/writing-running-appium/web/chromedriver.md

**Comment by mars-tial** [comment]
Hi, thanks for the answer but I am currently running Chromedriver latest's version (2.33) and appium latests beta version (1.7.2-beta) and Chrome 62.0.3202.75 and I still get the same error asking for me to use a higher version of chrome.
Can you reopen please ?

**Comment by mykola-mokhnach** [comment]
Are you sure it is Chrome and not a system webview?
