### ISSUE TITLE
Not able to click button at runtime

### ISSUE THREAD

**Issue by CharanpreetHora** [appium/appium#9571]
## The problem

Not able to click button at runtime. Able to see properties manually. Seems properties not loading at runtime. Spoken to developer seems it is a webview container and that might be the reason. 
Not sure how to proceed from here. If I do context switch also but properties are not getting loaded. So button will not be clicked. Any suggestions.

## Environment

* Appium version 1.6.5
* Real device Android 7.0

## Details

Not able to click button at runtime. Able to see properties manually. Seems properties not loading at runtime. Spoken to developer seems it is a webview container and that might be the reason. 
Not sure how to proceed from here. If I do context switch also but properties are not getting loaded. So button will not be clicked. Any suggestions.

class | android.widget.Button
content-desc | BUY NOW

**Comment by mykola-mokhnach** [comment]
Any more details? Logs, screenshots, code examples?

**Comment by CharanpreetHora** [comment]
OpenQA.Selenium.NoSuchElementException: An element could not be located on the page using the given search parameters. at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse) at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters) at OpenQA.Selenium.Appium.AppiumDriver`1.Execute(String driverCommandToExecute, Dictionary`2 parameters) at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(String mechanism, String value) at OpenQA.Selenium.Remote.RemoteWebDriver.FindElementByXPath(String xpath) at OpenQA.Selenium.By.<>c__DisplayClasse.b__c(ISearchContext context) at OpenQA.Selenium.By.FindElement(ISearchContext context) at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(By by) at OpenQA.Selenium.Appium.AppiumDriver`1.FindElement(By by) at xxxx.PageObject.xxApp.xxPage.pp_purchaseVerification()

//String buyNowButton = "//*[@content-desc='BUY NOW']";
String buyNowButton = "//android.widget.Button[@content-desc='BUY NOW']";
AppDriver.FindElement(By.XPath(buyNowButton)).Click();

**Comment by mykola-mokhnach** [comment]
What is the output of getPageSource ?

**Comment by CharanpreetHora** [comment]
How do I get this as I am not able to find any property like this when I am doing AppDriver. ?

**Comment by CharanpreetHora** [comment]
I am working on native App.

**Comment by CharanpreetHora** [comment]
How to retrieve context in C#. I am trying with multiple codes so that I can get the page source but some how there is no method with Driver having getContextHandles.

**Comment by CharanpreetHora** [comment]
wow all the issues are resolved now. Able to get the context, pagesource, click on button as well and switch back to native app. following is the code snippet:-
var contexts = AppDriver.Contexts;
                    foreach (string context in contexts)
                    {
                        Report.UpdateTestLog("Direct Buy", "contextName " + context, Status.DONE);
                        if (context.Contains("WEBVIEW"))
                        {
                            AppDriver.Context = context;
                            break;
                        }
                    }
                    //String pages = (AppDriver.PageSource).ToString();
                    //Report.UpdateTestLog("Direct Buy", "pages " + pages, Status.DONE);
