### ISSUE TITLE
Unable to run sample protractor E2E test on Windows app in Windows 10 (HPRP9)- Getting error: Unexpected token C in JSON at position 0

### ISSUE THREAD

**Issue by nmane047** [appium/appium#9576]
## Unable to run sample protractor E2E test on Windows app in Windows 10 (HPRP9) - Getting error -Unexpected token C in JSON at position 0

I have created a ionic 2 sample app and generated windows binaries and installed the app in Windows 10 HPRP9 machined. The app launches well, having functionality just clicking a button changes its BG color to red. I want to automate this simple testing using protractor code. Getting error while executing script

## Environment

* Appium version- 1.6.0
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): 6.10.2
* Mobile platform/version under test: Windows desktop HPRP9

## Details

Test 1: Launching in browser works fine
1. Command prompt => webdriver-manager start
2. New prompt => protractor protractor.config.test.js 
Launches in browser well and protractor script executes fine automatically clicking button and changing color to red.

Test 2: Launching as Windows app 
1. Command prompt =>appium
2. New prompt => protractor protractor.config.test.js 
Windows app launches fine. After some time,
When the script tries to access the DOM element button with id as "clickme", it throws error as below

## Error:
  WebDriverError: An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: Unexpected token C in JSON at position 0

File1: **protractor.conf.test.js**

`exports.config = {
   
  seleniumAddress: 'http://localhost:4723/wd/hub',  //Appium
  specs:['sample-spec.js'],
  useAllAngular2AppRoots: true,

  getPageTimeout: 21000, 
  framework: 'jasmine2', 
  jasmineNodeOpts: {
    isVerbose: false,
    showColors: true,
    includeStackTrace: true,
    defaultTimeoutInterval: 21000
  },
   
    capabilities: {
           platformName: 'Windows',
 	  deviceName: 'WindowsPC',
           browserName: "",
	 app:'com.ionicframework.sampleapp909969_bzbj8h50hftv4!com.ionicframework.sampleapp909969',
    }

};`

File 2: **sample-spec.js**

`describe("Sample app testing",function() {
   it("sample first test to check...", function () {
     browser.sleep(5000);
	 element(by.id("clickme")).click();
   });
});`

`HTML file
<ion-content padding>
  <button id="clickme" (click)="onClickingBtn()" [class.bgColor]="changeColor">click me</button>
</ion-content>

TS file
onClickingBtn(){
	  this.changeColor = true;
  }
  
CSS file
.bgColor{
	background-color:red
}
`
![app_image](https://user-images.githubusercontent.com/33222353/32369182-50bf6636-c0ae-11e7-9d50-d1a7e00d82d9.PNG)
![error_image](https://user-images.githubusercontent.com/33222353/32369187-53d647ea-c0ae-11e7-8ed0-fa0f4905cd44.PNG)

**Comment by mykola-mokhnach** [comment]
1.6.0 is very-very old Appium version. Try 1.7.1 or 1.7.2-beta

**Comment by nmane047** [comment]
Tried with version 1.7.2-beta. Getting the below error.

 An unknown server-side error occurred while processing the command. Original error: Could not verify WinAppDriver install; re-run install
[19:54:57] E/launcher - WebDriverError: An unknown server-side error occurred while processing the command. Original error: Could not verify WinAppDriver install; re-run install
![error2](https://user-images.githubusercontent.com/33222353/32378604-2e51dade-c0d1-11e7-8cf7-f06f70a1bf83.PNG)

**Comment by mykola-mokhnach** [comment]
@nmane047 Please create a new issue if it is still the case
