### ISSUE TITLE
Appium v1.7.1 WebDriverAgentRunner-Runner.app couldn't be opened and getting error

### ISSUE THREAD

**Issue by rajareddy2007** [appium/appium#9577]
Environment:

Appium- 1.7.1
xcode-9.1
device- ipad mac mini2

While trying to run through webdriver agent getting below error.

 WebDriverAgent hodor$ xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=‘d1860fdc97010d0e5e3753e024fc2b977d84460c’ test
2017-11-03 18:09:29.975 xcodebuild[9095:1262893]  DTDeviceKit: deviceType from d1860fdc97010d0e5e3753e024fc2b977d84460c was NULL
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
		{ id:‘d1860fdc97010d0e5e3753e024fc2b977d84460c’ }

	Unsupported device specifier option.
	The device “My Mac” does not support the following options: id
	Please supply only supported device specifier options.

	Available destinations for the "WebDriverAgentRunner" scheme:
		{ platform:iOS, id:d1860fdc97010d0e5e3753e024fc2b977d84460c, name:866593kah }
		{ platform:iOS Simulator, id:50B4EFA1-FE32-4950-BFF8-4198A7CB1938, OS:11.1, name:iPad (5th generation) }
		{ platform:iOS Simulator, id:459F9A56-1487-45BD-A887-43D469178A3A, OS:11.1, name:iPad Air }
		{ platform:iOS Simulator, id:9ACD79B4-6E2C-44BD-B512-5F786C47C8B6, OS:11.1, name:iPad Air 2 }
		{ platform:iOS Simulator, id:1A250753-EADB-491E-A800-3805B321D538, OS:11.1, name:iPad Pro (9.7-inch) }
		{ platform:iOS Simulator, id:B49AB661-1BFF-45E8-A103-B3938D5B5EDF, OS:11.1, name:iPad Pro (10.5-inch) }
		{ platform:iOS Simulator, id:9ACF6A0D-6B04-4C7A-897A-723760113E14, OS:11.1, name:iPad Pro (12.9-inch) }
		{ platform:iOS Simulator, id:B2A45038-64DC-43FD-A207-4CCD399A8509, OS:11.1, name:iPad Pro (12.9-inch) (2nd generation) }
		{ platform:iOS Simulator, id:08E5C5E0-242E-4748-8164-6EFAB053B222, OS:11.1, name:iPhone 5s }
		{ platform:iOS Simulator, id:0F331476-1983-4311-A8E1-29F5892EBE25, OS:11.1, name:iPhone 6 }
		{ platform:iOS Simulator, id:C8EC4302-0751-4BBE-870C-565D40AEF2E5, OS:11.1, name:iPhone 6 Plus }
		{ platform:iOS Simulator, id:C24614DB-0024-4903-A13A-6C82A952D5C8, OS:11.1, name:iPhone 6s }
		{ platform:iOS Simulator, id:D45DAA49-E1BD-4E97-A19D-69EBAD603F1C, OS:11.1, name:iPhone 6s Plus }
		{ platform:iOS Simulator, id:CCA4F5C5-AF2C-4AD4-8B07-5654379618D8, OS:11.1, name:iPhone 7 }
		{ platform:iOS Simulator, id:FDB290BF-9667-435D-9C0E-7ADD8CF44608, OS:11.1, name:iPhone 7 Plus }
		{ platform:iOS Simulator, id:43A5694C-4BD0-495F-ACA5-C6AFB31A182A, OS:11.1, name:iPhone 8 }
		{ platform:iOS Simulator, id:1BD3C29F-8C04-4BF8-9D25-2CBB68DE271E, OS:11.1, name:iPhone 8 Plus }
		{ platform:iOS Simulator, id:BE19B17C-71A1-455B-B0EE-BCC4D1476493, OS:11.1, name:iPhone SE }
		{ platform:iOS Simulator, id:BC7153EF-E2EA-4355-9DDD-E8C43F87B28E, OS:11.1, name:iPhone X }

	Ineligible destinations for the "WebDriverAgentRunner" scheme:
		{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Generic iOS Device }
		{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Generic iOS Simulator Device }

Please help me how to resolve above issue, tried many troubleshooting it didnt work.

**Comment by mykola-mokhnach** [comment]
Please provide the full server log

**Comment by gigilamorose** [comment]
Is your ipad mac mini2 running on iOS 11 ?

**Comment by sivavardhan** [comment]
what was the solution for this, i am also getting the same.. Can you please share solution
