### ISSUE TITLE
Appium launches application even when autoLaunch flag is set to False 

### ISSUE THREAD

**Issue by BoazWarshawsky** [appium/appium#9582]
## The problem
When setting in desired capabilities the field of "autoLaunch" to be false even though the application launches and does not waiting for driver.launch_app() to occur. 

## Environment
Using Python as testing environment.
appium version - 1.7.1
Mac, Sierra, 10.12.6
node js version v6.11.4
Mobile os 11.0, **real device** 
Real Device
appium cli (launching device with appium command only)

## Details
My purpose on  this issue reporting to be able to launch the app myself, with driver.launch_app()

## Link to Appium logs
https://github.com/BoazWarshawsky/iOSAutomationAgent/blob/master/appium.log

## Code To Reproduce Issue
I am using the following desired capabilities:
desired_caps = {
    PLATFORM_NAME: 'iOS',
    PLATFORM_VERSION: "11.0",
    DEVICE_NAME: device,
    SHOW_IOS_LOGS: 'true',
    BUNDLE_ID: "**********",
    DEVICE_ORIENTATION: "portrait",
    UDID: "*******",
    XCODE_ORG_ID: "**********",
    XCODE_SIGNING_ID: "iPhone Developer",
    "autoAcceptAlerts": True,
    "autoLaunch": False
}

**Comment by mykola-mokhnach** [comment]
setting _autoLaunch_ to _false_ means that application install will not be performed. But the app is still executed if it is already installed on the device:

```js
  async installApp () {
    if (this.isSafari()) {
      return;
    }
    // if user has passed in desiredCaps.autoLaunch = false
    // meaning they will manage app install / launching
    if (this.opts.autoLaunch === false) {
      return;
    }
```

**Comment by BoazWarshawsky** [comment]
If we cannot avoid appium from launching the app automatically what is **driver.launch_app()** for?

**Comment by mykola-mokhnach** [comment]
I'd say this is legacy stuff, which is not recommended for real life usage.

**Comment by BoazWarshawsky** [comment]
Thanks for the assist.

**Comment by risinek** [comment]
Name of this desired capability is misleading. Doesn't say anything about installation until you check the code.
