### ISSUE TITLE
Unable to take screenshots on real iOS device

### ISSUE THREAD

**Issue by guruprasadsr** [appium/appium#9583]
We are unable to take the screenshot of a real iOS device. When we try to take the screenshot, we get the following error:

[MJSONWP] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: Error: socket hang up

    at JWProxy.proxy$ (../../../lib/jsonwp-proxy/proxy.js:152:13)

    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)

    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)

    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)

    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)

    at <anonymous>

org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up (WARNING: The server did not provide any stacktrace information)

When we manually run the command "idevicescreenshot -u UDID temp.tiff" (where UDID is the UDID of the device), we are able to capture the screenshot.

## Environment

* Appium version that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Mac OS Sierra, 10.12.6
* Node.js version (unless using Appium.app|exe): 8.8.1
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: N/A

## Link to Appium logs
https://gist.github.com/guruprasadsr/ea28da5dec7d91131a30589fb0810e7f

**Comment by mykola-mokhnach** [comment]
This error is caused by a known XCTest issue. You can either use have your imobiledevicelib up to date, so then Appium can take screenshots using idevicescreenshot tool as a workaround, or wait for newer Appium release, which includes the necessary fix on WDA side: https://github.com/facebook/WebDriverAgent/pull/766

**Comment by jamesvanhorn** [comment]
@mykola-mokhnach I can't seem to work around this problem, any ideas? I have an iPhone 7 Plus running iOS 11.0.3 (so it follows that i should see the crash). 

Appium updated to 1.7.2-beta5 (so XCUITestDriver (v2.62.0)), and libimobiledevice installed/updated to latest. Logs indicate we are trying XCTest screenshot first, crashing WDA and preventing anything after from working. 

```
09:57:39 [HTTP] --> GET /wd/hub/session/e2739c43-9031-4711-96c8-31e95442467b/screenshot {}
09:57:39 [debug] [MJSONWP] Calling AppiumDriver.getScreenshot() with args: ["e2739c43-9031-4711-96c8-31e95442467b"]
09:57:39 [debug] [XCUITest] Executing command 'getScreenshot'
09:57:39 [debug] [XCUITest] Taking screenshot with WDA
09:57:39 [debug] [XCUITest] Setting custom timeout to 180000 ms for "getScreenshot" command
[XCUITest] Error getting screenshot: Could not proxy command to remote server. Original error: Error: socket hang up
09:57:47 [debug] [XCUITest] Taking screenshot with 'idevicescreenshot'
09:57:47 [debug] [XCUITest] Setting custom timeout to 180000 ms for "getOrientation" command
09:57:47 [debug] [JSONWP Proxy] Proxying [GET /orientation] to [GET http://localhost:8100/session/54FA9A1F-5A0E-405E-974F-4B3290BD177B/orientation] with no body
09:57:47 [debug] [iProxy] Error connecting to device!
09:57:47 [XCUITest] Error getting screenshot through 'idevicescreenshot': Could not proxy command to remote server. Original error: Error: read ECONNRESET
09:57:47 [debug] [XCUITest] Retrying screenshot through WDA
09:57:47 [debug] [XCUITest] Setting custom timeout to 180000 ms for "getScreenshot" command
09:57:47 [debug] [JSONWP Proxy] Proxying [GET /screenshot] to [GET http://localhost:8100/session/54FA9A1F-5A0E-405E-974F-4B3290BD177B/screenshot] with no body
```

idevicescreenshot works fine when i invoke manually from command line, and it should pass `isIdevicescreenshotAvailable` ->
```
which idevicescreenshot
/usr/local/bin/idevicescreenshot
```

Is there a capability associated im missing to prefer idevicescreenshot over WDA screenshot? Looking at https://github.com/appium/appium-xcuitest-driver/pull/553, it *should* try  idevicescreenshot first. Only other guess is the java binding, so maybe that's directly invoking the "bad" screenshot call? We just use `final File snap = (takeSnap).getScreenshotAs(OutputType.FILE);`

**Comment by mykola-mokhnach** [comment]
@jamesvanhorn Try to get the device log. Also make sure WebDriverAgent module on the device is up to date. Simply uninstall it manually and let Appium to perform the deployment after a new session is started.

**Comment by jamesvanhorn** [comment]
@mykola-mokhnach It looks like there have been further commits to screenshots.js, reverting back to trying WDA first. See https://github.com/appium/appium-xcuitest-driver/commit/e86af8bb6d102f673d3568ecaf658383203f1430#diff-52f04141487fd31e7ade5d5c5f465639. Seems to try `getScreenshotFromWDA()` first again,
 without a real device or simulator check. Unless im reading the code wrong, which is entirely possible since i dont know JS.
