### ISSUE TITLE
Appium does not locates elements in Mobile app

### ISSUE THREAD

**Issue by akshaypanambur** [appium/appium#9584]
Appium does not find element even if the page element is correct.Tried with explicit wait and all other available waits. Appium works normally in many cases,but some pages I face this issue.

I'm using POM as my framework and working on a mobile application.

Using UI Automator to locate elements.

Is this issue related to application ?

**Comment by mykola-mokhnach** [comment]
Please fill out the issue reporting form (versions, system info) and provide the system log as well as page source snapshot and the example of the client code.

**Comment by akshaypanambur** [comment]
Issue was due to Nougat verision..Had to use driver.runAppInBackGround() to solve this issue.
