### ISSUE TITLE
Can't find elements after the splashscreen

### ISSUE THREAD

**Issue by mahomahoxd** [appium/appium#9585]
## The problem

When I try to test (like a simple test of seeing if everything is launched correctly and such) it wont get past the splashscreen, this might not be an issue directly with appium however the app does start its way through the app. Its mainly just the splashscreen that is covering it all and wont "go away", but the app does load. If there are any suggestions, I'd gladly try them out, I've already put a sleep function between the splashscreen and afterwards.

## Environment

* Appium version 1.7.1
* Runs on Linux (Ubuntu) 
* Node version 7.10.0
* Mobile phone is running android 7.0.0
* Appium CLI

## Details

The splashscreen is a library I use that implements it also in android natively. This library is in here https://github.com/crazycodeboy/react-native-splash-screen. 

## Link to Appium logs
https://gist.github.com/mahomahoxd/31a5da7f4c4eb3b75403207cd23ac135

## Code To Reproduce Issue [ Good To Have ]
This is taken from my project, this is just a test in the __tests__ directory. 
> import wd from 'wd';
> 
> const PORT = 4723;
> const config = {
>   platformName: 'Android',
>   deviceName: 'Android device',
>   app: './android/app/build/outputs/apk/app-debug.apk',
> };
> const driver = wd.promiseChainRemote('localhost', PORT);
> jasmine.DEFAULT_TIMEOUT_INTERVAL = 60000;
> 
> const sleep = ms => new Promise(resolve => setTimeout(resolve, ms));
> 
> describe('Simple Appium test', () => {
>   beforeAll(async () => await driver.init(config));
>   afterAll(async () => await driver.quit());
> 
>   it('appium renders', async() => {
>     // const elementsList = driver.FindElementsByXPath('//*');
>     // console.log(elementsList);
>     expect(await driver.hasElementByAccessibilityId('logo')).toBe(true); // <--- this is found
>     await sleep(5000);
>     expect(await driver.hasElementByAccessibilityId('abc')).toBe(true); // <--- after the splashscreen, this should work
>     expect(await driver.hasElementByAccessibilityId('notthere')).toBe(false);
>   });
> });

**Comment by mykola-mokhnach** [comment]
Perhaps you need to change the context from native to web first and only after that try to locate elements.

**Comment by mahomahoxd** [comment]
How should you do that? I'm only using jest's presets of being react-native.

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium/blob/9dc7027fda61920228e49b9f93a5a8c6b8996733/docs/en/commands/context/set-context.md

**Comment by mahomahoxd** [comment]
Okay so I've added these 3 lines : 

>     const contexts = await driver.contexts();
>     await driver.context(contexts[1]);
>     await driver.context('NATIVE_APP');
From what I understood, you need to change the context to web. I've plowed out the documentation of wd but could not really find which parameters are accepted on the .context function. Do I need to replace "native_app" with something similar to "browser"?

**Comment by mykola-mokhnach** [comment]
Check hybrid apps automation with Appium topic if you need a comprehensive tutorial, for example https://www.ideas2it.com/blog/appium-hybrid-app-automation/

**Comment by mahomahoxd** [comment]
In this case, if I use await driver.contexts() and I console.log print them, I only have NATIVE_APP. I don't get the same things as in the tutorial.

**Comment by mahomahoxd** [comment]
The library I use seems to just use a different XML layout to display both screens. Therefore somehow the XML would always stay in front of everything. If you coded in such a way that the splash screen is a separate screen I think a timeout would fix the issue. There is a great example of how to make a timeout on Google. 
Anyways, thanks

**Comment by DusanDimitric** [comment]
@mahomahoxd 
Hey man, could you explain in more detail how you solved this? I didn't quite get it.

I'm experiencing the same problem where I can't test my apps if `react-native-splash-screen` is used in them.

**Comment by mahomahoxd** [comment]
@DusanDimitric It's been a while but I think I solved it by just disabling the react-native-splash-screen component, the splash screen seemed to be only somewhat transparent, not completely hidden. To appium it looked like a neverending loading splash screen. So I disabled the splash screen when testing, and re-enabled it for production/further development.

**Comment by DusanDimitric** [comment]
Thanks, I've tried disabling `react-native-splash-screen` by just commenting out the `SplashScreen.show(this);` line in `MainActivity.java` and then **Appium** started to work normally.

The problem is - this is not good enough for a CI/CD pipeline, where one of the tasks is to run Appium tests on a real device farm.

If I find a sensible solution I will post here...

**Comment by simonDominos** [comment]
has a solution been found for this? it's killing us...

**Comment by degamer106** [comment]
Still getting stuck on Splash Screen intermittently on my Expo app :(

**Comment by bobankamenarac** [comment]
Hello, 
For me problem was that splash screen was loading to long (more then 3 secunds), so when i changed Thread.Sleep(3000) to Thread.Sleep(5000) problem was solved. 
Hope this help.

**Comment by asingh139** [comment]
Hi Everyone,

After 2 sleepless nights I was able to find the solution to the issue related to Splash Screen being stuck and not going to the second screen using script/appium but manually it was working fine.
The issue is something related to INTENT Activity
Solution:
I added some extra line of code to script/capabilities to appium and it worked fine.
Try using these lines in capabilities for the apps that have splash screen issue.

capabilities.setCapability("androidCoverage","com.my.Pkg/com.my.Pkg.instrumentation.MyInstrumentation");
		capabilities.setCapability("androidCoverageEndIntent","com.example.pkg.END_EMMA");
		capabilities.setCapability("intentAction","android.intent.action.MAIN");
		capabilities.setCapability("intentCategory","android.intent.category.LAUNCHER");
		capabilities.setCapability("intentFlags","0x10200000");

Please Let me know if it worked for you also?

**Comment by AshuSingh07** [comment]
I am getting the same issue in hybrid (android). Screen gets struck at splash screen and unable to load next page in appium. When i disable to splash screen from cordova-plugin-splashscreen then appium loads other screens seamlessly. 
Application works as expected but when it comes to appium , the screen is struct at splashscreen.

**Comment by AshuSingh07** [comment]
> Thanks, I've tried disabling `react-native-splash-screen` by just commenting out the `SplashScreen.show(this);` line in `MainActivity.java` and then **Appium** started to work normally.
> 
> The problem is - this is not good enough for a CI/CD pipeline, where one of the tasks is to run Appium tests on a real device farm.
> 
> If I find a sensible solution I will post here...

I have the same issue and still looking for solution

**Comment by AshuSingh07** [comment]
Hello Everyone,
The above issue of not loading application after my splash screen is fixed now. 
I put my full effort for more than a week , analyzed and made all different changes for executing my app using Appium desktop but that never worked. Finally , i updated my Appium version from 1.13.1 to 1.17.1-1 (latest as of today) and it worked like charm. So the problem was not with my application code rather with Appium version.

**Comment by AshuSingh07** [comment]
> has a solution been found for this?

Yes. Please try to update your Appium version to latest (1.17.1-1) and it should work. It worked for me

**Comment by AshuSingh07** [comment]
> Still getting stuck on Splash Screen intermittently on my Expo app :(

I found the solution . Please try to update your Appium version to latest (1.17.1-1) and it should work. It worked for me

**Comment by phcbarros** [comment]
Hi everyone!

We solve this problem as follows:

android: {
    platformName: 'Android',
    deviceName: 'Android_E2E',
    app: './android/app/build/outputs/apk/app-debug.apk',
    automationName: 'UiAutomator2',
    appPackage: 'myAppPackage',
    appActivity: 'myAppPackage.MainActivity',
}

We put appPackage and appActivity in our capabilities and it works fine
