### ISSUE TITLE
Appium: Unable to launch web app in second emulator(GenyMotion)

### ISSUE THREAD

**Issue by anishqa** [appium/appium#9586]
Hello Everyone,

I am trying to launch web application in 2 emulators at the same time using TestNG parallel execution.

below is my testng xml file content:

![image](https://user-images.githubusercontent.com/8328587/32436165-22e3428e-c309-11e7-82db-7c24b2b7e4a1.png)

and below is the code:
private AppiumDriver<WebElement> driver;
	
	@BeforeTest(alwaysRun=true)
	@Parameters({"device","port"})
	public void setup1(String device, String port) throws MalformedURLException, InterruptedException{
		DesiredCapabilities capabilities = new DesiredCapabilities().android();
		capabilities.setCapability("browserName","Chrome");
		capabilities.setCapability("device","android");
		capabilities.setCapability("deviceName",device);
		capabilities.setCapability("platformVersion","6.0");
		capabilities.setCapability("platformName","Android");
		capabilities.setCapability("appPackage","com.android.chrome");
		capabilities.setCapability("appActivity","com.google.android.apps.chrome.Main");
		System.out.println(port);
		driver=new AndroidDriver<WebElement>(new URL(port), capabilities);

I am launching 2 appium servers i.e. 192.168.18.102:5555 and 192.168.18.101:5555.
I am using genymotion emulator.

below is the error I am getting from the server for which app is not getting launched in emulator:
> info: Client User-Agent string: Apache-HttpClient/4.5.2 (Java/1.8.0_121)
> info: Found an existing session to clobber, shutting it down first...
> info: Shutting down appium session
> info: Chromedriver: Changed state to 'stopping'
> error: Chromedriver: Error: Trying to proxy a session command without session id
>     at JWProxy.getUrlForProxy (lib/proxy.js:63:13)
>     at JWProxy.proxy$ (lib/proxy.js:81:25)
>     at tryCatch (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\appium-jsonwp-proxy\node_modules\babel-runtime\regenerator\runtime.js:67:40)
>     at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\appium-jsonwp-proxy\node_modules\babel-runtime\regenerator\runtime.js:315:22)
>     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\appium-jsonwp-proxy\node_modules\babel-runtime\regenerator\runtime.js:100:21)
>     at invoke (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\appium-jsonwp-proxy\node_modules\babel-runtime\regenerator\runtime.js:136:37)
>     at bound (domain.js:284:14)
>     at runBound (domain.js:297:12)
>     at enqueueResult (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\appium-jsonwp-proxy\node_modules\babel-runtime\regenerator\runtime.js:185:17)
>     at new Promise (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\appium-jsonwp-proxy\node_modules\babel-runtime\node_modules\core-js\library\modules\es6.promise.js:182:7)
>     at AsyncIterator.enqueue (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\appium-jsonwp-proxy\node_modules\babel-runtime\regenerator\runtime.js:184:16)
>     at AsyncIterator.prototype.(anonymous function) [as next] (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\appium-jsonwp-proxy\node_modules\babel-runtime\regenerator\runtime.js:100:21)
>     at Object.runtime.async (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\appium-jsonwp-proxy\node_modules\babel-runtime\regenerator\runtime.js:209:12)
>     at JWProxy.proxy (lib/proxy.js:96:21)
>     at JWProxy.command$ (lib/proxy.js:116:42)
>     at tryCatch (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\appium-jsonwp-proxy\node_modules\babel-runtime\regenerator\runtime.js:67:40)
>     at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\appium-jsonwp-proxy\node_modules\babel-runtime\regenerator\runtime.js:315:22)
>     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\appium-jsonwp-proxy\node_modules\babel-runtime\regenerator\runtime.js:100:21)
>     at invoke (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\appium-jsonwp-proxy\node_modules\babel-runtime\regenerator\runtime.js:136:37)
>     at bound (domain.js:284:14)
>     at runBound (domain.js:297:12)
>     at enqueueResult (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\appium-jsonwp-proxy\node_modules\babel-runtime\regenerator\runtime.js:185:17)
>     at new Promise (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\appium-jsonwp-proxy\node_modules\babel-runtime\node_modules\core-js\library\modules\es6.promise.js:182:7)
>     at AsyncIterator.enqueue (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\appium-jsonwp-proxy\node_modules\babel-runtime\regenerator\runtime.js:184:16)
>     at AsyncIterator.prototype.(anonymous function) [as next] (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\appium-jsonwp-proxy\node_modules\babel-runtime\regenerator\runtime.js:100:21)
>     at Object.runtime.async (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\appium-jsonwp-proxy\node_modules\babel-runtime\regenerator\runtime.js:209:12)
>     at JWProxy.command (lib/proxy.js:133:12)
>     at Chromedriver.stop$ (lib/chromedriver.js:152:26)
>     at tryCatch (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\babel-runtime\regenerator\runtime.js:67:40)
>     at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\babel-runtime\regenerator\runtime.js:294:22)
>     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\babel-runtime\regenerator\runtime.js:100:21)
>     at invoke (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\babel-runtime\regenerator\runtime.js:136:37)
>     at bound (domain.js:284:14)
>     at runBound (domain.js:297:12)
>     at enqueueResult (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\babel-runtime\regenerator\runtime.js:167:17)
>     at new Promise (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\babel-runtime\node_modules\core-js\library\modules\es6.promise.js:182:7)
>     at AsyncIterator.enqueue (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\babel-runtime\regenerator\runtime.js:166:16)
>     at AsyncIterator.prototype.(anonymous function) [as next] (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\babel-runtime\regenerator\runtime.js:100:21)
>     at Object.runtime.async (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\babel-runtime\regenerator\runtime.js:192:12)
>     at Chromedriver.stop (lib/chromedriver.js:147:32)
>     at [object Object].ChromeAndroid.stop (C:\Program Files (x86)\Appium\node_modules\appium\lib\devices\android\chrome.js:168:21)
>     at [object Object].Appium.stop (C:\Program Files (x86)\Appium\node_modules\appium\lib\appium.js:375:15)
>     at [object Object].Appium.start (C:\Program Files (x86)\Appium\node_modules\appium\lib\appium.js:133:10)
>     at exports.createSession (C:\Program Files (x86)\Appium\node_modules\appium\lib\server\controller.js:188:16)
>     at Layer.handle [as handle_request] (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\express\lib\router\layer.js:82:5)
>     at next (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\express\lib\router\route.js:110:13)
>     at Route.dispatch (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\express\lib\router\route.js:91:3)
>     at Layer.handle [as handle_request] (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\express\lib\router\layer.js:82:5)
>     at C:\Program Files (x86)\Appium\node_modules\appium\node_modules\express\lib\router\index.js:267:22
>     at Function.proto.process_params (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\express\lib\router\index.js:321:12)
>     at next (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\express\lib\router\index.js:261:10)
>     at next (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\express\lib\router\route.js:100:14)
>     at next (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
>     at next (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
>     at next (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
>     at next (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
>     at next (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
>     at next (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
>     at next (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
>     at next (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
>     at next (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
>     at next (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
>     at C:\Program Files (x86)\Appium\node_modules\appium\lib\server\controller.js:39:7
>     at Layer.handle [as handle_request] (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\express\lib\router\layer.js:82:5)
>  [Error: Trying to proxy a session command without session id]
> info: [debug] Cleaning up appium session
> info: Old session shut down OK, proceeding to new session
> info: [debug] The following desired capabilities were provided, but not recognized by appium. They will be passed on to any other services running on this server. : version, device, platform
> info: Set mode: Proxying straight through to Chromedriver
> info: [debug] Looks like we want chrome on android
> info: [debug] Creating new appium session 4eda9c31-8df3-4440-869b-ba806c23dc04
> info: [debug] Checking whether adb is present
> info: [debug] Using adb from C:\android-sdk-windows\platform-tools\adb.exe
> info: [debug] Using fast reset? false
> info: [debug] Preparing device for session
> info: [debug] Not checking whether app is present since we are assuming it's already on the device
> info: Retrieving device
> info: [debug] Trying to find a connected android device
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: C:\android-sdk-windows\platform-tools\adb.exe devices
> info: [debug] 2 device(s) connected
> info: Found device 192.168.18.102:5555
> info: [debug] Setting device id to 192.168.18.102:5555
> info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
> info: [debug] executing cmd: C:\android-sdk-windows\platform-tools\adb.exe -s 192.168.18.102:5555 wait-for-device
> info: [debug] executing cmd: C:\android-sdk-windows\platform-tools\adb.exe -s 192.168.18.102:5555 shell "echo 'ready'"
> info: [debug] Starting logcat capture
> info: [debug] Pushing unlock helper app to device...
> info: [debug] executing cmd: C:\android-sdk-windows\platform-tools\adb.exe -s 192.168.18.102:5555 install "C:\Program Files (x86)\Appium\node_modules\appium\build\unlock_apk\unlock_apk-debug.apk"
> info: [debug] executing cmd: C:\android-sdk-windows\platform-tools\adb.exe -s 192.168.18.102:5555 shell "dumpsys window"
> info: [debug] Screen already unlocked, continuing.
> info: [debug] Forwarding system:4724 to device:4724
> info: [debug] executing cmd: C:\android-sdk-windows\platform-tools\adb.exe -s 192.168.18.102:5555 forward tcp:4724 tcp:4724
> info: [debug] Pushing appium bootstrap to device...
> info: [debug] executing cmd: C:\android-sdk-windows\platform-tools\adb.exe -s 192.168.18.102:5555 push "C:\\Program Files (x86)\\Appium\\node_modules\\appium\\build\\android_bootstrap\\AppiumBootstrap.jar" /data/local/tmp/
> info: Starting App
> info: [debug] Attempting to kill all 'uiautomator' processes
> info: [debug] Getting all processes with 'uiautomator'
> info: [debug] executing cmd: C:\android-sdk-windows\platform-tools\adb.exe -s 192.168.18.102:5555 shell "ps 'uiautomator'"
> info: [debug] No matching processes found
> info: [debug] Running bootstrap
> info: [debug] spawning: C:\android-sdk-windows\platform-tools\adb.exe -s 192.168.18.102:5555 shell uiautomator runtest AppiumBootstrap.jar -c io.appium.android.bootstrap.Bootstrap -e pkg com.android.chrome -e disableAndroidWatchers false
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_RESULT: shortMsg=java.lang.IllegalStateException
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_RESULT: longMsg=UiAutomationService android.accessibilityservice.IAccessibilityServiceClient$Stub$Proxy@385f7b2already registered!
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_CODE: 0
> info: [debug] UiAutomator exited
> info: [debug] executing cmd: C:\android-sdk-windows\platform-tools\adb.exe -s 192.168.18.102:5555 shell "echo 'ping'"
> info: [debug] Attempting to uninstall app
> info: [debug] Not uninstalling app since server not started with --full-reset
> info: [debug] Cleaning up android objects
> error: UiAutomator quit before it successfully launched
		

++++++++++++++++++++++

Thanks in advance for any help/clue.

**Comment by mykola-mokhnach** [comment]
- Follow https://github.com/appium/appium/blob/55760b7b9e1c494c6a1f22d152f0bd1fe676dae7/docs/en/advanced-concepts/parallel-tests.md
- It is not allowed to set both _browserName_ and _appPackage_/_appActivity_ capabilities. Only one of these has to be set at the same time.

**Comment by saikrishna321** [comment]
@anishqa make sure you provide unique _chromeDriverPort_ and _systemPort_ capabilities.

**Comment by mykola-mokhnach** [comment]
Closed because of missing activity
