### ISSUE TITLE
Application not launching when performing webdriver.Remote()

### ISSUE THREAD

**Issue by BoazWarshawsky** [appium/appium#9587]
## The problem
I am filling in correctly (seems to be) the desire capabilities  but the application actually not launching. 

## Environment

Appium version - 1.7.1
Desktop OS - Mac Sierra 10.12.6
Node.js version - v6.11.4
Mobile platform/version under test - iPhone 5s, iOS 11.0
Real device
Appium CLI

## Details
I verified that the bundleId that defined in desired capabilities really exits when looking at: "ios-deploy -B"

Problem reproducing on wither real device or Simulator.

## Link to Appium logs
https://github.com/BoazWarshawsky/iOSAutomationAgent/blob/master/appium.log

## Code To Reproduce Issue 
Just do:
driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)

But app won't launch.

**Comment by mykola-mokhnach** [comment]
Did you try to execute your test with another simulator/device already? Set different values for _wdaLocalPort_ capability for each of the devices, because Appium caches previous sessions in order to speed up the initialisation.

**Comment by BoazWarshawsky** [comment]
Trying with other simulator did not help.
Well, I rebooted my MAC which solved the problem.

For further problem that will raise can you please details more what do you mean: "Set different values for wdaLocalPort capability"? 
you mean use different port when calling webdriver.Remote(...:4327) ?

**Comment by mykola-mokhnach** [comment]
Would it be more clear if you see the following log message?

https://github.com/appium/appium-xcuitest-driver/pull/560/files

**Comment by BoazWarshawsky** [comment]
As far as I understand, during test run the WDA is something that I don't really control or need. 
Am I missing something?

**Comment by mykola-mokhnach** [comment]
Not really. WebDriverAgent is the main commands execution server for the corresponding iOS device/simulator. Appium is just proxying commands to it and compiles/deploys/initialises its binary when/if necessary.

**Comment by BoazWarshawsky** [comment]
I understand this, but in general my tests interacting with Appium services only.
