### ISSUE TITLE
iOS - Send UTF-8 characters with more than 1 unicode character

### ISSUE THREAD

**Issue by tfcardoso** [appium/appium#9588]
## Versions:
* Appium version that exhibits the issue: v1.7.1
* Desktop OS/version used to run Appium: MAC Sierra 10.12.6
* Mobile platform/version under test: iOS10.3.3
* Real device or emulator/simulator: iPhone5S

## Problem:

it seems its not possible to send unicode characters in iOS that contains more than 1 unicode character.

For example sending:

    .sendKeys("😀")
or

    .sendKeys("\uD83D\uDE00");

The iOS keyboard shows two ??

## Logs:
https://gist.github.com/tfcardoso/162b298c038b68736471d3f9522c4a5b

If I send one "simple" character with 1 unicode character, it works properly:
    
    .sendKeys("☺") 
    .sendKeys("\u263A")

Is this something that will going to be possible?

**Comment by chanugithub** [comment]
yes unable to write unicode characters in element ids...any update on this issue? can we expect in next appium beta version?

**Comment by mykola-mokhnach** [comment]
@tfcardoso Try to copy the string into the clipboard using the recently added [interfaces](https://github.com/appium/java-client/pull/855) and then paste it instead of typing

**Comment by tfcardoso** [comment]
Hi @mykola-mokhnach,

that approach works 👍 

There are some challenges to paste characters that are present inside a long text to be sent, but I'll try to make it work. 

Thanks

**Comment by mykola-mokhnach** [comment]
I've just saw you presentation at the conf. Nicely done. Looking forward to see PRs from you.

**Comment by mykola-mokhnach** [comment]
Just start with something small. We are always happy to advice.

**Comment by kanu1713** [comment]
Telmo_Cardoso
Oct '17
Hi,

I need to send all type of unicode characters. In Android I can use the unicodeKeyboard. But in iOS when I send single characters like

sendKeys("ウ") or equivalent .sendKeys("\u30A6")
sendKeys("☺") or equivalent .sendKeys("\u263A")
it works normally. But when I send one character that is composed of two codes, like:

.sendKeys("😀") or equivalent .sendKeys("\uD83D\uDE00");

**Comment by kanu1713** [comment]
Hi,

I need to send all type of unicode characters. In Android I can use the unicodeKeyboard. But in iOS when I send single characters like

sendKeys("ウ") or equivalent .sendKeys("\u30A6")
sendKeys("☺") or equivalent .sendKeys("\u263A")
it works normally. But when I send one character that is composed of two codes, like:

.sendKeys("😀") or equivalent .sendKeys("\uD83D\uDE00");

Then I end with two ?? in the ios keyboard inputfield. Any solution to send more complex characters?

**Comment by mykola-mokhnach** [comment]
Closed as fixed
