### ISSUE TITLE
Udpate Parallel Android Tests chapter documentation in appium.io

### ISSUE THREAD

**Issue by aaltat** [appium/appium#9589]
## The problem

Update http://appium.io/slate/en/master/?python#parallel-android-tests documentation to contains information about the `systemPort`. The `systemPort` is explained in [different documentation](https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/parallel-tests.md) and it would be nice if the appium.io documentation would mention the port and point to the correct documentation. 

Also it would be good if the [appium server capabilities](http://appium.io/slate/en/master/?python#appium-server-capabilities) would also mention the port.

**Comment by aaltat** [comment]
I think the documentation is incorrectly fixed and issue should not be closed. I think system port default is 8200 and not 4724 as is stated #9806

**Comment by KazuCocoa** [comment]
Ah, the range is 8200 to 8299 and the server select 8200 first.

https://github.com/appium/appium-uiautomator2-driver/blob/f651819a04c41840ac67dc2e675653394106dc34/lib/driver.js#L18

**Comment by aaltat** [comment]
Thanks for the quick fix.
