### ISSUE TITLE
Alert send_keys() not working

### ISSUE THREAD

**Issue by jplegorburu** [appium/appium#9590]
## The problem

Im trying to fill the password of an Alert using send_keys but it gives me an error.

## Environment

Versions: appium@1.7.2-beta
OSX
Node.js version - v8.6.0
iOS
Real Device

## Link to Appium logs

https://gist.github.com/jplegorburu/b1ae377e096dabfcbb034e1d22a8ab43

## Code To Reproduce Issue [ Good To Have ]

Basically this is what im doing

`browser = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)`
`alert = browser.switch_to_alert()`
`alert.text`
this returns: u'Sign-In Required\nIf you have an Apple ID and password, enter them here. If you've used the iTunes Store or iCloud, for example, you have an Apple ID.'
`alert.send_keys("password")
#selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: An error occurred`

Attached is the alert that im trying to complete.
![alert](https://user-images.githubusercontent.com/5282112/32454308-a24f2a94-c2fd-11e7-9532-ea52e66fa633.png)

Thanks!

**Comment by imurchie** [comment]
What are the details of the device you are trying to automate? iOS version? Anything?

Currently iOS 11.1 has problems with typing into alerts. I'm not aware of other issues. But the information you've provided is not enough to go on.

**Comment by jplegorburu** [comment]
Hi, im using an IPhone 6 with iOS 10.3.3. Let me know if you need more information.

**Comment by imurchie** [comment]
Can you get the source, and post it as a link to a [gist](https://gist.github.com), right before you try to set the text on the alert? Appium does a best-guess at what the structure is and where the element should be.

**Comment by jplegorburu** [comment]
This is the source that i got right before trying to set the text

https://gist.github.com/jplegorburu/56493407d58c5ea20d48415be00eba98

**Comment by imurchie** [comment]
I will look into this. In the meantime, the easiest way to get this working would be to look for the alert (by class name, find `XCUIElementTypeAlert`) and then within that, find the password field (by class name, within the alert, find `XCUIElementTypeSecureTextField`). You can probably skip the alert part, if there are no other `XCUIElementTypeSecureTextField`s. 

Then type into that element.

**Comment by jplegorburu** [comment]
Thanks! I've tried that but i was not able to find the element. It always returns None.

**Comment by imurchie** [comment]
Weird. Do you have logs for that?

**Comment by jplegorburu** [comment]
https://gist.github.com/jplegorburu/f5ab15b3507424e51ed7e44488759c0c

Ive tried in different ways with the same result.

**Comment by imurchie** [comment]
Have you tried using class name instead of xpath?

**Comment by jplegorburu** [comment]
That worked great! Thanks!!

**Comment by imurchie** [comment]
Awesome! I also have a PR in to make the normal way work. https://github.com/appium/appium-xcuitest-driver/pull/562

**Comment by felyppers** [comment]
@imurchie I'm having this same issue and the solution proposed above do not seems to work for me. I'm using rubylib and I'm able to dismiss and accept alerts with switch_to.alert.accept and switch_to.alert.dismiss. However, while a native alert is active, I'm not able to find any elements, so I can't handle textfield on alerts like the example above. I've already updated to appium 1.7.1 and the most recent version of appium-xcuitest-driver and libimobiledevice as well. The only element I'm able to find while the alert is active is an element of type 'XCUIElementTypeAny' which is also returned if I filter for the type 'XCUIElementTypeApplication'. Below you can the appium log while the alert is active.

`2017-12-12 20:59:49:888 - [debug] [BaseDriver] Waiting up to 0 ms for condition
2017-12-12 20:59:49:890 - [debug] [XCUITest] Setting custom timeout to 1000000 ms for "findElements" command
2017-12-12 20:59:49:890 - [debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:4706/session/170543A9-B78E-4053-A2E2-0A09A0C96DCF/elements] with body: {"using":"predicate string","value":"type!=nil"}
2017-12-12 20:59:50:010 - [debug] [JSONWP Proxy] Got response with status 200: {"value":[{"ELEMENT":"79574A89-856F-4139-8110-1B3DABB12328"}],"sessionId":"170543A9-B78E-4053-A2E2-0A09A0C96DCF","status":0}
2017-12-12 20:59:50:012 - [debug] [MJSONWP] Responding to client with driver.findElements() result: [{"ELEMENT":"79574A89-856F-4139-8110-1B3DABB12328"}]
2017-12-12 20:59:50:015 - [HTTP] <-- POST /wd/hub/session/8266da7a-3988-4b41-b11a-5f90359bd03f/elements 200 128 ms - 124 `
