### ISSUE TITLE
Capability locale/language being ignored on subsequent test runs

### ISSUE THREAD

**Issue by timyhou** [appium/appium#9592]
## The problem

When I used the desired capabilities `language` and `locale` my Android Emulator does not always respect the set language on restart. 

## Environment

* Appium version: 1.7.1 w/ chromedriver 2.20 override
* Desktop OS/version used to run Appium: Ubuntu 16.04
* Node.js version (unless using Appium.app|exe): 6.3.1
* Mobile platform/version under test: Android Google API Emulator 7.0
* Appium CLI or Appium.app|exe: Appium CLI
* Python 3.6.2, Appium client 0.24

## Details

I have a test which is meant to run the App in multiple language locales. At the beginning of each test, it instantiates the driver with extra desired capabilities `language` and `locale`. 

At first I noticed it was not working at all and the emulator was always in en_US. I ran `adb root` after restarting the emulator and during the test, the first locale/language was set properly. However, the subsequent ones were not. I have tried adding `fullReset=True` but that doesn't seem to make a difference. The first language is always set, but the next tests which use different desired capabilities do not get their expected locale set on the emulator. 

## Link to Appium logs

[Gist](https://gist.github.com/timyhou/1442c612dca3107b0ed11532722aab4f)

In the log I can see `persist.sys.locale` being set. I also saw `Device requires adb to be running as root in order to reboot. Restarting daemon` which suggests it Appium handled getting root control. 

## Watered down example
```
from appium import webdriver


desired_caps = {}
desired_caps['platformName'] = 'Android'
desired_caps['platformVersion'] = '7.0'
desired_caps['deviceName'] = 'Android GoogleAPI Emulator'
desired_caps['browserName'] = 'Chrome'

lang_locale = ['zh_CN', 'en_US', 'de_DE']

for combo in lang_locale:
    try:
        desired_caps['language'] = combo.split('_')[0]
        desired_caps['locale'] = combo.split('_')[1]
        driver = webdriver.Remote(
            command_executor='http://0.0.0.0:4723/wd/hub',
            desired_capabilities=desired_caps
        )
        driver.get('https://www.google.com')
    finally:
        driver.quit()

```

**Comment by nairouz12** [comment]
I'm facing the same issue. 
Can anyone help please?

**Comment by nairouz12** [comment]
@mykola-mokhnach can you help on this please. It is failing a big part of my tests

**Comment by mykola-mokhnach** [comment]
Linking to https://github.com/appium/appium/issues/9619

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium/issues/9619#issuecomment-350728029
