### ISSUE TITLE
AppiumDriver.findElement() keeps retrying even after a 200 response code

### ISSUE THREAD

**Issue by ADYASHA-PADHI** [appium/appium#9593]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable): 1.6.5
* Desktop OS/version used to run Appium: macOS Sierra 10.12.6
* Mobile platform/version under test: 11.0
* Real device or emulator/simulator: simulator(iPad (5th generation)) , seen on iPad Air 2 and iPad Air also
* iPad orientation : LANDSCAPE

## Details

We are trying to click on an element with accessibility Id "Settings". Appium keeps responding with a 200 but does does not find the element.

## Link to Appium logs

https://gist.github.com/ADYASHA-PADHI/914b76b3f023bdc5eceadd69751716b9

**Comment by saikrishna321** [comment]
@ADYASHA-PADHI i see request from client is done and server response correctly. Can you please post your client code

**Comment by ADYASHA-PADHI** [comment]
waitForElementToBeDisplayed(Settings);

public Boolean waitForElementToBeDisplayed(WebElement webElement) throws Exception {


       LOGGER.info("============== ELEMENT ==================");
       LOGGER.info("waiting for element to be displayed");
        boolean isDisplayed = waitAndPollForElementToBeDisplayed(webElement);
        if (isDisplayed) {
            LOGGER.debug("Is Element Displayed Status : " + isDisplayed);
        }
        Assert.assertTrue(isDisplayed); //fail if not found
        return isDisplayed;
    }

**Comment by ADYASHA-PADHI** [comment]
Its gets stuck in the polling cycle.

**Comment by saikrishna321** [comment]
what does this method do 'waitAndPollForElementToBeDisplayed'

**Comment by ADYASHA-PADHI** [comment]
private Boolean waitAndPollForElementToBeDisplayed(WebElement element) throws Exception {
        boolean found = false;
        try {
            RetryTillPass rtp = new RetryTillPass("com.adyasha.bjetf.mobile.base.MobileUIBase");
            Class[] signature = new Class[]{WebElement.class};
            Object result = rtp.waitForCodeToPassUtil("isElementDisplayed", true, signature, BrowserConfig.getElementMaxTimeout(), element);
            if (result instanceof Boolean) {
                found = (Boolean) result;
            } else if (result instanceof Integer) {
                found = false;
            }
        } catch (Exception e) {
            LOGGER.error("Error in waitForElementToBeDisplayed: " + e);
        }
        return found;
    }




It basically polls for an element in 60 secs interval.

**Comment by saikrishna321** [comment]
Looks like your code issue, you need to debug at your end

**Comment by ADYASHA-PADHI** [comment]
The same code is able to find other elements in the previous test steps. 
It is a problem with the right half of the screen in landscape mode. 
If we reset the button location to the left half, everything works fine.

**Comment by ADYASHA-PADHI** [comment]
When we try with portrait mode, these are the appium logs with a click request

[debug] [MJSONWP] Responding to client with driver.getCurrentContext() result: "NATIVE_APP"
[HTTP] <-- GET /wd/hub/session/f1bc3aca-a96b-4ae0-865d-00f34e0aab06/context 200 8 ms - 84
[HTTP] --> POST /wd/hub/session/f1bc3aca-a96b-4ae0-865d-00f34e0aab06/elements {"using":"accessibility id","value":"Settings"}
[debug] [MJSONWP] Calling AppiumDriver.findElements() with args: ["accessibility id","Settings","f1bc3aca-a96b-4ae0-865d-00f34e0aab06"]
[debug] [XCUITest] Executing command 'findElements'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8100/session/50838366-4FC4-4A65-9311-1D1F3498EFF7/elements] with body: {"using":"accessibility id","value":"Settings"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":[{"ELEMENT":"8A85ED6A-C14E-47D3-98A3-FF6D7680FC42"}],"sessionId":"50838366-4FC4-4A65-9311-1D1F3498EFF7","status":0}
[debug] [MJSONWP] Responding to client with driver.findElements() result: [{"ELEMENT":"8A85ED6A-C14E-47D3-98A3-FF6D7680FC42"}]
[HTTP] <-- POST /wd/hub/session/f1bc3aca-a96b-4ae0-865d-00f34e0aab06/elements 200 144 ms - 124
[HTTP] --> POST /wd/hub/session/f1bc3aca-a96b-4ae0-865d-00f34e0aab06/timeouts {"type":"implicit","ms":1000}
[debug] [MJSONWP] Calling AppiumDriver.timeouts() with args: ["implicit",1000,"f1bc3aca-a96b-4ae0-865d-00f34e0aab06"]
[debug] [XCUITest] Executing command 'timeouts'
[debug] [BaseDriver] Set implicit wait to 1000ms
[debug] [MJSONWP] Responding to client with driver.timeouts() result: null
[HTTP] <-- POST /wd/hub/session/f1bc3aca-a96b-4ae0-865d-00f34e0aab06/timeouts 200 2 ms - 76
[HTTP] --> POST /wd/hub/session/f1bc3aca-a96b-4ae0-865d-00f34e0aab06/element/8A85ED6A-C14E-47D3-98A3-FF6D7680FC42/click {"id":"8A85ED6A-C14E-47D3-98A3-FF6D7680FC42"}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [XCUITest] Executing command 'proxyReqRes'
[debug] [JSONWP Proxy] Proxying [POST /wd/hub/session/f1bc3aca-a96b-4ae0-865d-00f34e0aab06/element/8A85ED6A-C14E-47D3-98A3-FF6D7680FC42/click] to [POST http://localhost:8100/session/50838366-4FC4-4A65-9311-1D1F3498EFF7/element/8A85ED6A-C14E-47D3-98A3-FF6D7680FC42/click] with body: {"id":"8A85ED6A-C14E-47D3-98A3-FF6D7680FC42"}
[debug] [JSONWP Proxy] Got response with status 200: {"status":0,"id":"8A85ED6A-C14E-47D3-98A3-FF6D7680FC42","value":"","sessionId":"50838366-4FC4-4A65-9311-1D1F3498EFF7"}
[JSONWP Proxy] Replacing sessionId 50838366-4FC4-4A65-9311-1D1F3498EFF7 with f1bc3aca-a96b-4ae0-865d-00f34e0aab06
[HTTP] <-- POST /wd/hub/session/f1bc3aca-a96b-4ae0-865d-00f34e0aab06/element/8A85ED6A-C14E-47D3-98A3-FF6D7680FC42/click 200 624 ms - 118


You can compare both the logs.

**Comment by ADYASHA-PADHI** [comment]
If you see the code from line 100-125 in the gist file, you will see a get request getting generated more than once.

**Comment by mykola-mokhnach** [comment]
There might be a problem with landscape visibility detection in WebDriverAgent. Try to apply the patch from https://github.com/facebook/WebDriverAgent/pull/783 locally and report the problem into https://github.com/facebook/WebDriverAgent/issues if that still does not work.

**Comment by RizwanEbrahim** [comment]
i have the same issue.The web element returns a 200 in log but cant select it for a click() or sendKeys()
