### ISSUE TITLE
iOS platform:  Screenshots are not honored in landscape mode

### ISSUE THREAD

**Issue by SatishCigniti** [appium/appium#9594]
For iOS 10.2 device, the screenshots are not capturing in landscape mode. By default they honored in Portrait mode even after setting the capability to landscape.  

Environment:

Appium Version: Appium v1.7.2-beta
MacOS : 10.13.2
Xcode: 8.3
Device: iPad Pro
iOS: 10.2
JavaClient:  5.0.4

Capabilities Used: 
```
 DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability("preventWDAAttachments", false);
        capabilities.setCapability("platformName", "ios");
        capabilities.setCapability("automationName", "XCUITest");
        capabilities.setCapability("realDeviceLogger", "idevicesyslog");
        capabilities.setCapability("platformVersion", "10.2");
        capabilities.setCapability("fullReset", false);
        capabilities.setCapability("useNewWDA", true);
        capabilities.setCapability("noReset", true);
        capabilities.setCapability("clearSystemFiles", true);
        capabilities.setCapability("xcodeOrgId", "xxxxxxxxx");
        capabilities.setCapability("xcodeSigningId", "iPhone Developer");
        capabilities.setCapability("deviceName", "xxxx iPad");
        capabilities.setCapability("deviceOrientation","landscape")
        capabilities.setCapability("newCommandTimeout", 100);
        capabilities.setCapability("udid", "bbbb");
        capabilities.setCapability("app", "/Users/ctl-user/Downloads/xxxxxx.ipa");
        println("Creating local iOS driver")
        return capabilities


Screenshotcode: 

BufferedImage takeScreenshot() 
{ 
     BufferedImage bufferedImage = null 
     Debug.setDebugLevel(3) 
      if (driver != null) { 
       File scrFile = driver.getScreenshotAs(OutputType.FILE) 
   try { 
       bufferedImage = ImageIO.read(scrFile) 
    } 
   catch (IOException e) 
  { 
       e.printStackTrace() 
} 
} 
  else 
{ 
  throw new ElementNotVisibleException("Element not found - ") 
} 
return bufferedImage 
}
```
My automation is completely based up on comparing the screens i.e Base  VS target .
 For android platform it is working as expected. I am completely blocked due to this behavior.

**Comment by mykola-mokhnach** [comment]
Can you please attach the server log?

**Comment by SatishCigniti** [comment]
@mykola-mokhnach : please find below server logs

https://gist.github.com/SatishCigniti/4a4042982a7e6de0db707555da58b171

**Comment by mykola-mokhnach** [comment]
@imurchie It looks like idevicescreenshot does not respect the orientation. should we revert the previous approach to take the screenshot with WDA first or stick with the current one?

**Comment by imurchie** [comment]
I don't understand what "honored" means. 

With `idevicescreenshot` I get:
![2](https://user-images.githubusercontent.com/2614354/32510741-96dee682-c3bf-11e7-9f9b-468985590c31.png)
And with WDA I get:
<img width="375" alt="3" src="https://user-images.githubusercontent.com/2614354/32510752-9cf1a320-c3bf-11e7-9f3f-32bd08e09305.png">

**Comment by SatishCigniti** [comment]
@imurchie  i tried to take the screenshot in landscape mode , instead it is giving in portrait mode. 
Let mw know fpr any other info

**Comment by imurchie** [comment]
I still do not understand what you mean by "giving in portrait mode". Does that mean the image is like the first I posted above? Or the app goes into portrait mode and the screenshot is taken? Is this just a rotation issue?

**Comment by SatishCigniti** [comment]
@imurchie , the second screenshot you provided with the WDA is the intended behaviour.

**Comment by imurchie** [comment]
Why? That seems like the worst of all options.

**Comment by mykola-mokhnach** [comment]
@imurchie how about https://github.com/appium/appium-xcuitest-driver/pull/565 ?

**Comment by mykola-mokhnach** [comment]
@imurchie Also https://github.com/facebook/WebDriverAgent/pull/783

**Comment by SatishCigniti** [comment]
@imurchie finally i am able to convey the issue :).  
"worst of all options":  you mean to use the screenshots method using WDA or comparing the screens , well we didn't have other option. 

Suggest your best approach of the all the available options.

**Comment by mykola-mokhnach** [comment]
@SatishCigniti Reinstall your appium@beta to upgrade xcuitest driver to version 2.58.1+, which includes rotation fix

**Comment by SatishCigniti** [comment]
@mykola-mokhnach thank you for fixing the issue. I will update the appium@beta version and share you the results

**Comment by SatishCigniti** [comment]
@mykola-mokhnach I verified the fix and is working as intended .

Thank you for the quick help @mykola-mokhnach , @imurchie

**Comment by shynkevich-alex** [comment]
@mykola-mokhnach it reproduces if I relaunch app after rotation:
1. rotate app
2. close app
3. launch app
4. take screenshot

Could you fix it too?

**Comment by mykola-mokhnach** [comment]
@shynkevich-alex you can report a bug to Apple ;)

**Comment by shynkevich-alex** [comment]
So, no way to fix it in appium?

**Comment by shynkevich-alex** [comment]
@mykola-mokhnach  I think [XCUIDevice sharedDevice].orientation returns landscape orientation after relaunch it and in this case we can use wda for taking screenshot.

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium-xcuitest-driver/pull/570

**Comment by shynkevich-alex** [comment]
@mykola-mokhnach I have updated appium and appium-xcuitest-driver but still have issue with screenshot after relaunch app.
