### ISSUE TITLE
Appium 1.7.2Beta and Xcode 9 makes XCUIElementTypeWebView not debuggable

### ISSUE THREAD

**Issue by DanielPradoPino** [appium/appium#9596]
Hi guys,

## The problem

I am automating an hybrid app and I found I am not able to see XCUIElementTypeWebView content or access it from a native context . I can switch to it without any issue but I need to access it from Native Context because I need to interact with an iframe (and appium is not switching to iframes while in iOS as far as I know).

Everything is working fine while using xcode 8 but not xcode 9, even I am using macaca inspector in both xcode 8 and 9 and I can inspect everything (webview content included) in 8 but not in 9. 

I was wondering if any of you had this issue and was able to fix it, maybe I am missing something, WDA update or anything else.

Can you please help me with this?

Thanks in advance.

This is how a getPageSource is looking while in Xcode 9:

`<?xml version="1.0" encoding="UTF-8"?><AppiumAUT><XCUIElementTypeApplication type="XCUIElementTypeApplication" name="CoralDbg" label="CoralDbg" enabled="true" visible="true" x="0" y="0" width="375" height="667">
  <XCUIElementTypeWindow type="XCUIElementTypeWindow" enabled="true" visible="true" x="0" y="0" width="375" height="667">
    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="375" height="667">
      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="20" width="375" height="647">
        <XCUIElementTypeWebView type="XCUIElementTypeWebView" enabled="true" visible="true" x="0" y="20" width="375" height="647">
          <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="20" width="375" height="1276">
            <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="0" height="0"/>
          </XCUIElementTypeOther>
        </XCUIElementTypeWebView>
      </XCUIElementTypeOther>
    </XCUIElementTypeOther>
  </XCUIElementTypeWindow>
  <XCUIElementTypeWindow type="XCUIElementTypeWindow" enabled="true" visible="false" x="0" y="0" width="375" height="667">
    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="375" height="667"/>
  </XCUIElementTypeWindow>
  <XCUIElementTypeWindow type="XCUIElementTypeWindow" enabled="true" visible="true" x="0" y="0" width="375" height="667">
    <XCUIElementTypeStatusBar type="XCUIElementTypeStatusBar" enabled="true" visible="true" x="0" y="0" width="375" height="20">
      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="375" height="20"/>
      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="375" height="20">
        <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="6" y="0" width="39" height="20"/>
        <XCUIElementTypeOther type="XCUIElementTypeOther" value="SSID" name="3 of 3 Wi-Fi bars" label="3 of 3 Wi-Fi bars" enabled="true" visible="true" x="50" y="0" width="13" height="20"/>
        <XCUIElementTypeOther type="XCUIElementTypeOther" name="4:28 PM" label="4:28 PM" enabled="true" visible="true" x="164" y="0" width="50" height="20"/>
        <XCUIElementTypeOther type="XCUIElementTypeOther" name="-100% battery power" label="-100% battery power" enabled="true" visible="true" x="345" y="0" width="25" height="20"/>
      </XCUIElementTypeOther>
    </XCUIElementTypeStatusBar>
  </XCUIElementTypeWindow>
</XCUIElementTypeApplication></AppiumAUT>`

As you can see nothing is visible inside webview...

**Comment by mykola-mokhnach** [comment]
This is XCTest behaviour, which cannot be changed on our side. Please report to Apple.

**Comment by imurchie** [comment]
This changes from Xcode release to Xcode release, unfortunately. Seems to usually be broken on major and minor releases, and patches fix it.
