### ISSUE TITLE
iOS-HybridApp-WEBVIEW: Appium does not detect webView on real device while it is there

### ISSUE THREAD

**Issue by MaxDomash** [appium/appium#9599]
## The problem

     On real device when I do "driver.getContextHandles();" I can see NATIVE_APP only, while webView is there. If while test I manually background the app, launch device Safari browser and foreground the app then I can see NATIVE_APP and WEBVIEW but still can not locate web elements having([MJSONWP] Encountered internal error running command: Error: Error while executing atom: operation timed out). Tried Appium 1.6.5,  1.7.1 and 1.7.2-beta as well.

## Environment

* Appium version (or git revision) that exhibits the issue:    1.6.5,  1.7.1 and v1.7.2-beta
* Last Appium version that did not exhibit the issue (if applicable):  -
* Desktop OS/version used to run Appium:  MacBook Pro (Retina, 13-inch, Early 2015), Processor 2.7 GHz Intel Core i5, Memory 8 GB 1867 MHz DDR3
* Node.js version (unless using Appium.app|exe): v6.11.3
* Mobile platform/version under test: iPhone 7 iOS 10.3.3
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI
* Xcode version set to '9.1'

## Link to Appium logs

Appium logs: https://gist.github.com/MaxDomash/d8d346e67931b6db0089f38244346781

## Code To Reproduce Issue [ Good To Have ]

DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "iOS");
        capabilities.setCapability(MobileCapabilityType.BROWSER_NAME, "");
        capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone");
        capabilities.setCapability(MobileCapabilityType.UDID, "auto");
        capabilities.setCapability("app", "/Users/user/app.ipa");
        capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.IOS_XCUI_TEST);
        capabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, 50000);
        capabilities.setCapability("startIWDP", true);                                  
        capabilities.setCapability("webkitResponseTimeout", "70000");
        driver = new IOSDriver<IOSElement>(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
        driver.manage().timeouts().implicitlyWait(80, TimeUnit.SECONDS); 
        
        driver.findElementById("US").click();
        driver.findElementById("ID").sendKeys("name");
        driver.findElementById("ID").sendKeys("pwd");
        driver.findElementById("LoginBtn").click();

         Set<String> contextHandles = driver.getContextHandles();
         String context = driver.getContext();
         log.info("Current context: " + context);

          int i = 0;
          for (String s : contextHandles) {
            i++;
            log.info("Context " + i + " : " + s);
          }

Outout: 
>Current context: NATIVE_APP
>Context 1 : NATIVE_APP

**Comment by mykola-mokhnach** [comment]
On which iOS component is your webview based? SafariViewController?

**Comment by MaxDomash** [comment]
We have UIWebView

**Comment by mykola-mokhnach** [comment]
Perhaps, it's some problem with IWDP. Have you checked if you can connect to IWDP session manually after it is started? Is its binary up to date?

**Comment by MaxDomash** [comment]
Yes, I did try and it got connected. The IWDP is the latest release.

**Comment by masoodmd0786** [comment]
Hi @maxDomash any luck, I am facing similar issue.

Posted a Support ticket on Appium discussion I didn’t receive any response yet

https://discuss.appium.io/t/unable-to-find-webview-in-ios-hybrid-app-xcode9-appium1-7-1/19046

Something interesting in your ticket is manually  you were able to find webview on real device with xCode-9. can you please share the steps you followed.

**Comment by MaxDomash** [comment]
No luck so far, still waiting for response from supporters. 

I able to detect WEBVIEW with the following steps:
1. completely close safari browser on your device
2. run the app
3. end up on screen which has WEBVIEW
4. make your script sleep for 20 sec. Java -> (Thread.sleep(20000)) 
5. while app on sleep manually background the app
6. manually start safari browser
7. front ground the app
8. try to look for available views
At this point I am able to see WEBVIEW 7 of of 10 attempts.

        BUT!!!

Even if I switch to WEBVIEW by the steps but I have error when I am trying to look for web elements
([MJSONWP] Encountered internal error running command: Error: Error while executing atom: operation timed out)
So it does not work as work around.

**Comment by MaxDomash** [comment]
@mykola-mokhnach any update on it? Very need the fix.

**Comment by mykola-mokhnach** [comment]
> iOS 11 support (libimobiledevice v1.2.1 required)

Install libimobiledevice with `--HEAD` option to have the latest version

**Comment by MaxDomash** [comment]
Now all is up to date:
ios_webkit_debug_proxy 1.8
Built with libimobiledevice v1.2.1, libplist v2.0.0

but still facing the same issue

**Comment by joe-mcg** [comment]
I'm seeing the exact same issue. Xcode 9.2, appium 1.7.1.

**Comment by MaxDomash** [comment]
Take a look on it as well:
https://github.com/google/ios-webkit-debug-proxy/issues/199

**Comment by lgxqf** [comment]
I'm facing the same issue, so painful... any update about this?

**Comment by fdPoornima** [comment]
I am facing same issue as well. 
         Xcode 9.2
         appium 1.7.2
Not able to identify the UIWebView objects. Only the Native_App handle is returned

**Comment by fabrice31** [comment]
Hello, same here : 
* appium 1.7.2
* ios_webkit_debug_proxy 1.8
* real device : iphone 6, iOS 10.3.3
* Context list

The workaround from Max allow to manually pass this point during the test. But too many tests, not a durable solution.

Any idea someone ?

**Comment by VinayakSS** [comment]
For iOS:

use latest beta version of Appium(1.8.2 beta)
Uninstall the appium if u already installed.Using the bellow command
   >    npm uninstall -g appium

Install beta release using bello\w command             
   >    npm install -g appium@beta --no-shrinkwrap

and set following capabilities:
capabilities.setCapability("xcodeOrgId", "<your xcode developer id(10 digit)>");
capabilities.setCapability("xcodeSigningId", "iPhone Developer");



And let me know if it works out.

**Comment by mykola-mokhnach** [comment]
Web view detection is performed by IWDP. Unfortunately there is nothing that can be done here on appium side

**Comment by csharsha** [comment]
@MaxDomash : Did you issue get solved?
