### ISSUE TITLE
TouchAction doesn't work

### ISSUE THREAD

**Issue by sevarudakov** [appium/appium#9600]
## The problem

When I try to use Appium::TouchAction.new.tap(x: 45, y: 110, duration: 1000).release.perform
or any other methods like swipe, press etc I am geting this error:

  NoMethodError:
       undefined method `touch_actions' for nil:NilClass

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable): 1.7.0
* Desktop OS/version used to run Appium: macOS Sierra v. 10.12.6
* Node.js version (unless using Appium.app|exe): I use desktop version, but the error is still the same when I use npm version
* Real device or emulator/simulator: iOS Simulator (Xcode9)
* Appium CLI or Appium.app|exe: 1.2.6

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/sevarudakov/cfb65eecca8c57575a281afc32bd7a6f

**Comment by mykola-mokhnach** [comment]
Please report to https://github.com/appium/ruby_lib/issues
@KazuCocoa FYI

**Comment by KazuCocoa** [comment]
thanks👍 > Please report to https://github.com/appium/ruby_lib/issues

BTW, If you don't use global scope driver(`$driver`), you need to pass the instance when you initialize the touch action.

```ruby
@driver =  Appium::Driver.new(opts, false).start_driver
Appium::TouchAction.new(@driver).tap(x: 45, y: 110, duration: 1000).release.perform
```
