### ISSUE TITLE
Got response with status 200: {"value":"Failed to open url","sessionId":"id","status":13 on real device

### ISSUE THREAD

**Issue by maggie5750** [appium/appium#9601]
## The problem

I try to call appiumdriver.get(url) to open a url on Safari but error occurs on real device. It is OK on Simulator.

## Environment

* Appium version: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: OS X 10.12.6 Sierra
* Node.js version (unless using Appium.app|exe): v7.7.2
* Mobile platform/version under test: iPhone 8, iOS 11.0
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI
## Details
appium-xcuitest-driver@2.54.2
appium-ios-driver@1.27.4

## Link to Appium logs
https://gist.github.com/maggie5750/6c39ce1c086ec20a2f532f837e7a35fe

## Code To Reproduce Issue [ Good To Have ]
driver.get(url)

**Comment by maggie5750** [comment]
appium-xcuitest-driver@2.54.2

**Comment by mykola-mokhnach** [comment]
This endpoint does not work properly on real devices due to known XCTest limitations.

**Comment by maggie5750** [comment]
@mykola-mokhnach Thanks for your reply.

**Comment by CPPAlien** [comment]
if this endpoint is not working, is there any other endpoints working for iOS? @mykola-mokhnach Thank you

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios/ios-xctest-mobile-gestures.md

**Comment by mykola-mokhnach** [comment]
Try the latest appium@beta

**Comment by CPPAlien** [comment]
but the beta version of appium is not support "tap" as I mentioned before
https://github.com/facebook/WebDriverAgent/issues/890

**Comment by mykola-mokhnach** [comment]
Got tap you can still use the corresponding `mobile:` endpoint
