### ISSUE TITLE
iOS 11 [debug] [iProxy] Error connecting to device!   Could not proxy. Proxy error: Could not proxy command to remote server. Original error: Error: socket hang up 

### ISSUE THREAD

**Issue by Kitty2014** [appium/appium#9604]
## The problem

 Could not proxy. Proxy error: Could not proxy command to remote server. Original error: Error: socket hang up
    at doJwpProxy$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/mjsonwp/mjsonwp.js:384:13)
    at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session/d78f0928-32c2-4075-9e28-7a4c5f381882/element/DCAB96C9-7368-4EBE-943B-4A69BA63BADA/click 500 16780 ms - 280 
[XCUITest] Log file for xcodebuild test: /var/folders/c2/cllky7gs5mg0n8rbz8jygwz40000gn/T/com.apple.dt.XCTest/IDETestRunSession-A3AC7259-F48E-492A-A74E-2561BAAE3D44/WebDriverAgentRunner-39F6CED5-E4C8-4C02-8DF2-342B94FAF1DF/Session-WebDriverAgentRunner-2017-11-08_173621-rFMkFM.log
[XCUITest] xcodebuild exited with code '65' and signal 'null'

## Environment

Environment

Appium version (or git revision) that exhibits the issue:  v1.7.2-beta
Last Appium version that did not exhibit the issue (if applicable): -
Desktop OS/version used to run Appium: 10.12.6 (16G1023)
Node.js version (unless using Appium.app|exe): v8.4.0
Mobile platform/version under test: iPhone X  iOS 11.0.1   and  11.2
Real device or emulator/simulator: Real Device
Appium CLI or Appium.app|exe: Appium CLI
Xcode version set to 'Version 9.2 beta (9C32c)'

## Details

Test APP  run in background and pops up   Original error: Error: socket hang up  
[debug] [iProxy] Error connecting to device!

## Link to Appium logs

[info] [Appium] Welcome to Appium v1.7.1
[info] [Appium] Appium REST http interface listener started on 0.0.0.0:4723[info] [HTTP] --> POST /wd/hub/session {"capabilities":[{"desiredCapabilities":{"noReset":true,"clearSystemFiles":true,"xcodeOrgId":"9H4SUA4596","bundleId":"com.youxinpai.yxused","--session-override":true,"deviceName":"iPhone","launchTimeout":60000,"xcodeSigningId":"iPhone Developer","wdaLocalPort":"8100","newCommandTimeout":0,"platformVersion":"11.0.1","automationName":"XCUITest","platformName":"iOS","udid":"b8cf8bea07d2b25bf3b0ae8a129a5718f9c29c0c"}},{"requiredCapabilities":{}}],"desiredCapabilities":{"noReset":true,"clearSystemFiles":true,"xcodeOrgId":"9H4SUA4596","bundleId":"com.youxinpai.yxused","--session-override":true,"deviceName":"iPhone","launchTimeout":60000,"xcodeSigningId":"iPhone Developer","wdaLocalPort":"8100","newCommandTimeout":0,"platformVersion":"11.0.1","automationName":"XCUITest","platformName":"iOS","udid":"b8cf8bea07d2b25bf3b0ae8a129a5718f9c29c0c"},"requiredCapabilities":{}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"noReset":true,"clearSystemFiles":true,"xcodeOrgId":"9H4SUA4596","bundleId":"com.youxinpai.yxused","--session-override":true,"deviceName":"iPhone","launchTimeout":60000,"xcodeSigningId":"iPhone Developer","wdaLocalPort":"8100","newCommandTimeout":0,"platformVersion":"11.0.1","automationName":"XCUITest","platformName":"iOS","udid":"b8cf8bea07d2b25bf3b0ae8a129a5718f9c29c0c"},{},[{"desiredCapabilities":{"noReset":true,"clearSystemFiles":true,"xcodeOrgId":"9H4SUA4596","bundleId":"com.youxinpai.yxused","--session-override":true,"deviceName":"iPhone","launchTimeout":60000,"xcodeSigningId":"iPhone Developer","wdaLocalPort":"8100","newCommandTimeout":0,"platformVersion":"11.0.1","automationName":"XCUITest","platformName":"iOS","udid":"b8cf8bea07d2b25bf3b0ae8a129a5718f9c29c0c"}},{"requiredCapabilities":{}}]]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1510132546158 (17:15:46 GMT+0800 (CST))
[info] [Appium] Creating new XCUITestDriver (v2.51.1) session
[info] [Appium] Capabilities:
[info] [Appium]   noReset: true
[info] [Appium]   clearSystemFiles: true
[info] [Appium]   xcodeOrgId: '9H4SUA4596'
[info] [Appium]   bundleId: 'com.youxinpai.yxused'
[info] [Appium]   --session-override: true
[info] [Appium]   deviceName: 'iPhone'
[info] [Appium]   launchTimeout: 60000
[info] [Appium]   xcodeSigningId: 'iPhone Developer'
[info] [Appium]   wdaLocalPort: '8100'
[info] [Appium]   newCommandTimeout: 0
[info] [Appium]   platformVersion: '11.0.1'
[info] [Appium]   automationName: 'XCUITest'
[info] [Appium]   platformName: 'iOS'
[info] [Appium]   udid: 'b8cf8bea07d2b25bf3b0ae8a129a5718f9c29c0c'
[warn] [BaseDriver] Capability 'wdaLocalPort' changed from string ('8100') to integer (8100). This may cause unexpected behavior
[warn] [BaseDriver] The following capabilities were provided, but are not recognized by appium: --session-override.
[info] [BaseDriver] Session created with session id: 610b7609-f8f9-4fdb-b886-07542b894483[debug] [XCUITest] Xcode version set to '9.2' 
[debug] [XCUITest] iOS SDK Version set to '11.2'
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1510132546423 (17:15:46 GMT+0800 (CST))[debug] [XCUITest] Available devices: b8cf8bea07d2b25bf3b0ae8a129a5718f9c29c0c
[debug] [XCUITest] Creating iDevice object with udid 'b8cf8bea07d2b25bf3b0ae8a129a5718f9c29c0c'
[info] [XCUITest] Determining device to run tests on: udid: 'b8cf8bea07d2b25bf3b0ae8a129a5718f9c29c0c', real device: true
[debug] [BaseDriver] Event 'appConfigured' logged at 1510132546566 (17:15:46 GMT+0800 (CST))
[debug] [BaseDriver] Event 'resetStarted' logged at 1510132546566 (17:15:46 GMT+0800 (CST))
[debug] [XCUITest] Reset: fullReset not set. Leaving as is
[debug] [BaseDriver] Event 'resetComplete' logged at 1510132546567 (17:15:46 GMT+0800 (CST))
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Starting iOS device log capture with: 'idevicesyslog'
[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1510132546661 (17:15:46 GMT+0800 (CST))
[info] [XCUITest] Setting up real device[info] [XCUITest] Using WDA path: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[info] [XCUITest] Using WDA agent: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[debug] [XCUITest] Capability 'useNewWDA' set to false, so trying to reuse currently running WDA instance at 'http://localhost:8100/'
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [XCUITest] WDA is not listening at 'http://localhost:8100/'. Rebuilding...
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1510132546820 (17:15:46 GMT+0800 (CST))
[info] [XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'

**Comment by Kitty2014** [comment]
![20171107-222139](https://user-images.githubusercontent.com/7512412/32542069-1e8a5126-c437-11e7-92dd-3d9324558e2c.jpg)
![x](https://user-images.githubusercontent.com/7512412/32542171-6432cc4e-c437-11e7-84d7-637865e629f2.jpg)
![x2](https://user-images.githubusercontent.com/7512412/32542173-645d866e-c437-11e7-966e-8b8fbf483986.jpg)

**Comment by mykola-mokhnach** [comment]
this error means the WebDriverAgent is not listening on the device under test. Do you follow https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md ? Have you tried to deploy it manually from Xcode?

**Comment by Kitty2014** [comment]
[iProxy] Error connecting to device! shown and APP  run in bg modle even  manual launch app, Unable to resume previous session  @mykola-mokhnach

**Comment by Kitty2014** [comment]
@mykola-mokhnach  iOS  10.3.3 All versions script  run OK, but iOS 11 and iPhoneX  occurs these issue

**Comment by Kitty2014** [comment]
@mykola-mokhnach 
Strictly follow the configuration
https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md ? Have deploy it manually from Xcode

**Comment by dpgraham** [comment]
Sorry for the late reply on this. Is this still an issue @Kitty2014?
