### ISSUE TITLE
Android -Error occured while starting App. Original error: 'com......Activity' never started

### ISSUE THREAD

**Issue by ashwinibaisutrave** [appium/appium#9605]
## The problem
Error -[MJSONWP] Encountered internal error running command: Error: Error occured while starting App. Original error: 'com......Activity' never started

I have given the right appActivity and appActivity and tried all combination but still it fails to start a activity .
and i have observed it to be inconsistent .if i run my appium scripts 5 times ,1 time it will execute and rest 4 times it fails to start the activity via appium client.

And via appium app it gives the above error as activity failed to start.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable):1.7.1
* Desktop OS/version used to run Appium:MAC OS Sierra
* Mobile platform/version under test:Android all OS
* Real device or emulator/simulator:Simulator and Real device samsung
* Appium CLI or Appium.app|exe:Client and app

## Details

Activity has never started ,i am facing this error inconsistently when i tried to luanch app via appium app or run the scripts via command line 

## Link to Appium logs

<script src="https://gist.github.com/ashwinibaisutrave/020f9b103008bace637f8d19781b3b04.js"></script>

  "platformName": "android",
  "platformVersion": "6.0",
  "deviceName": "Nexus6_23",
  "app": "/*/*/*/app613185.apk",
  "appActivity": "com.XXX.XXX.XX.OnboardingActivity",
  "appWaitActivity": "com.XX.XX.splash.AppLoaderActivity"

**Comment by mykola-mokhnach** [comment]
One reason for that might be that app crashes on startup.
the other reason might be there is some more complicated algorithm for app startup, so more than one activity can be started depending on some conditions. In such case you might use wildcard `*` in activity names.

**Comment by ashwinibaisutrave** [comment]
Ok is it someting like -com.bskyb.skyapp.* ?
Which can take any activities

**Comment by ashwinibaisutrave** [comment]
@mykola-mokhnach thanks its working now with wildcards.

**Comment by codewarior** [comment]
The addition of * at the package end did the trick. Wonderful.
com.mycompany.*

**Comment by bkapilg** [comment]
i am using ride framework 
*** Settings ***
Library           AppiumLibrary

*** Variables ***
${server}         http://127.0.0.1:4723/wd/hub
${platformName}    Android
${platformversion}    4.4.4
${deviceName}     "1cd04d33"
${appPackage}     com.livmor
${app Activity}    com.livmor.setup.SplashSCreen

*** Test Cases ***
run_testoid
    Open Application    ${server}    platformName=Android    platformVersion=4.4.4    deviceName=1cd04d33    appPackage=${appPackage}    appActivity=${app Activity}
    sleep    5s
    Click Element    xpath=android.widget.EditText[@text='Username']
I am getting this error
*** Settings ***
Library           AppiumLibrary

*** Variables ***
${server}         http://127.0.0.1:4723/wd/hub
${platformName}    Android
${platformversion}    4.4.4
${deviceName}     "1cd04d33"
${appPackage}     com.livmor
${app Activity}    com.livmor.setup.SplashSCreen

*** Test Cases ***
run_testoid
    Open Application    ${server}    platformName=Android    platformVersion=4.4.4    deviceName=1cd04d33    appPackage=${appPackage}    appActivity=${app Activity}
    *** Settings ***
Library           AppiumLibrary

*** Variables ***
${server}         http://127.0.0.1:4723/wd/hub
${platformName}    Android
${platformversion}    4.4.4
${deviceName}     "1cd04d33"
${appPackage}     com.livmor
${app Activity}    com.livmor.setup.SplashSCreen

*** Test Cases ***
run_testoid
    Open Application    ${server}    platformName=Android    platformVersion=4.4.4    deviceName=1cd04d33    appPackage=${appPackage}    appActivity=${app Activity}
    sleep    5s
    Click Element    xpath=android.widget.EditText[@text='Username']
Original error: Activity used to start app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity)
please check this
