### ISSUE TITLE
UIAutomator2 fails to unlock screen

### ISSUE THREAD

**Issue by aaltat** [appium/appium#9606]
## The problem

When my screen lock type is set to pattern or a pin then the Appium is not able to unlock the screen. 

## Environment

* Appium version: 1.7.1
* Windows 7:
* Node.js version: v6.9.2
* Mobile platform/version: Android 7.0
* Real device: Samsung J5 2017 model

## Link to Appium logs
https://gist.github.com/aaltat/1a825d83aa3343607c53bef56621a182

## Details
When running the code below, I see this error: 
```
Traceback (most recent call last):
  File "tmp.py", line 12, in <module>
    driver1 = webdriver.Remote(url, caps)
  File "C:\PYTHON27\lib\site-packages\appium\webdriver\webdriver.py", line 36, in __init__

    super(WebDriver, self).__init__(command_executor, desired_capabilities, browser_profil
e, proxy, keep_alive)
  File "C:\PYTHON27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 151, i
n __init__
    self.start_session(desired_capabilities, browser_profile)
  File "C:\PYTHON27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 240, i
n start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\PYTHON27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, i
n execute
    self.error_handler.check_response(response)
  File "C:\PYTHON27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194
, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Trying to proxy a session command without session id
```

## Code To Reproduce Issue [ Good To Have ]
```
import time
from appium import webdriver

url = 'http://localhost:4723/wd/hub'
caps = {"platformVersion": "7.0.0",
        "appPackage": "com.android.settings",
        "platformName": "android",
        "appActivity": ".Settings",
        "deviceName": "Samsung_J5",
        "unlockType": "pattern",
        "unlockKey": "1236"}
driver1 = webdriver.Remote(url, caps)
print driver1.session_id
driver1.quit()
```

**Comment by mykola-mokhnach** [comment]
@vrunoa FYI

**Comment by vrunoa** [comment]
@mykola-mokhnach i'll try to take a look this week.

**Comment by mykola-mokhnach** [comment]
thanks @vrunoa

**Comment by dmshantanu** [comment]
I am also facing the same issue

**Comment by jamesvanhorn** [comment]
I have this issue, but only in the following scenarios:
1. The device is already unlocked and screen is on
2. The device's screen is off, but its unlocked due to something like smart lock

My logs look the same, but my guess is the unlock fails and that's being treated as bad/cause for termination. Wonder if another capability is needed when its ok if it doesnt unlock because its already unlocked.

**Comment by abotalov** [comment]
I also face this issue and see the following in Appium server log:
> [BaseDriver] The following capabilities were provided, but are not recognized by appium: unlockType, unlockKey.

**Comment by KazuCocoa** [comment]
With the master, it worked and no basedriver error.
https://github.com/appium/appium/issues/9606#issuecomment-349413051 also work on my device. (with pin)
