### ISSUE TITLE
Appium 1.6.5 server occassionally does not respond to applium client requests and gets stuck

### ISSUE THREAD

**Issue by dmshantanu** [appium/appium#9608]
## The problem

I have sometimes seen appium server not responding to appium client's requests.
I can see appium server receiving the request and then it does not do anything with it. It is stuck there. There are no logs beyond that point.

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: 1.6.5
* Node.js version (unless using Appium.app|exe): 8.7.0
* Mobile platform/version under test: Android 7.0
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/dmshantanu/a8abab626ad8a8a83e7472a831746c4a

At the end appium gets stuck and does not respond. I have to put the app in background and bring back to foreground for the appium to start responding again. But I have to do that manually. Appium does not recover from this by itself.

After this i see following in  the logs and appium continues its normal execution:
[HTTP] --> GET /wd/hub/session/d3524098-bdac-42c5-a1e6-4a3f41ebc153/context {}
[debug] [MJSONWP] Calling AppiumDriver.getCurrentContext() with args: ["d3524098-bdac-42c5-a1e6-4a3f41ebc153"]
[debug] [MJSONWP] Responding to client with driver.getCurrentContext() result: "NATIVE_APP"
[HTTP] <-- GET /wd/hub/session/d3524098-bdac-42c5-a1e6-4a3f41ebc153/context 200 2 ms - 84 
[HTTP] --> GET /wd/hub/session/d3524098-bdac-42c5-a1e6-4a3f41ebc153/context {}
[debug] [MJSONWP] Calling AppiumDriver.getCurrentContext() with args: ["d3524098-bdac-42c5-a1e6-4a3f41ebc153"]
[debug] [MJSONWP] Responding to client with driver.getCurrentContext() result: "NATIVE_APP"
[HTTP] <-- GET /wd/hub/session/d3524098-bdac-42c5-a1e6-4a3f41ebc153/context 200 6 ms - 84 
[HTTP] --> POST /wd/hub/session/d3524098-bdac-42c5-a1e6-4a3f41ebc153/timeouts {"type":"implicit","ms":5000}
[debug] [MJSONWP] Calling AppiumDriver.timeouts() with args: ["implicit",5000,"d3524098-bdac-42c5-a1e6-4a3f41ebc153"]
[debug] [BaseDriver] Set implicit wait to 5000ms
[debug] [MJSONWP] Responding to client with driver.timeouts() result: null
[HTTP] <-- POST /wd/hub/session/d3524098-bdac-42c5-a1e6-4a3f41ebc153/timeouts 200 3 ms - 76 
[HTTP] --> GET /wd/hub/session/d3524098-bdac-42c5-a1e6-4a3f41ebc153/context {}
[debug] [MJSONWP] Calling AppiumDriver.getCurrentContext() with args: ["d3524098-bdac-42c5-a1e6-4a3f41ebc153"]
[debug] [MJSONWP] Responding to client with driver.getCurrentContext() result: "NATIVE_APP"
[HTTP] <-- GET /wd/hub/session/d3524098-bdac-42c5-a1e6-4a3f41ebc153/context 200 3 ms - 84 
[HTTP] --> GET /wd/hub/session/d3524098-bdac-42c5-a1e6-4a3f41ebc153/context {}
[debug] [MJSONWP] Calling AppiumDriver.getCurrentContext() with args: ["d3524098-bdac-42c5-a1e6-4a3f41ebc153"]
[debug] [MJSONWP] Responding to client with driver.getCurrentContext() result: "NATIVE_APP"
[HTTP] <-- GET /wd/hub/session/d3524098-bdac-42c5-a1e6-4a3f41ebc153/context 200 3 ms - 84 
[HTTP] --> GET /wd/hub/session/d3524098-bdac-42c5-a1e6-4a3f41ebc153/context {}
[debug] [MJSONWP] Calling AppiumDriver.getCurrentContext() with args: ["d3524098-bdac-42c5-a1e6-4a3f41ebc153"]
[debug] [MJSONWP] Responding to client with driver.getCurrentContext() result: "NATIVE_APP"
[HTTP] <-- GET /wd/hub/session/d3524098-bdac-42c5-a1e6-4a3f41ebc153/context 200 5 ms - 84

**Comment by dmshantanu** [comment]
@imurchie  Can you please help with this?

**Comment by mykola-mokhnach** [comment]
Switch to UIAutomator2 and update Appium to 1.7.1
