### ISSUE TITLE
Automate Android Emulator Power Level?

### ISSUE THREAD

**Issue by bootstraponline** [appium/appium#961]
It'd be nice to set the Android [emulator power level](http://dfme.wordpress.com/2011/10/09/changing-power-level-in-an-android-emulator/) via appium. I think there's already some telnet code for a different feature.

**Comment by jlipps** [comment]
there is some work underway for this, though it will require new endpoints. discussion here: https://github.com/SeleniumHQ/mobile-spec/pull/6/files

**Comment by xuru** [comment]
Wow, a blast from the past!  Hope everything is going well for you @jlipps and @bootstraponline.  I don't have the access that I use too, but if there is anything I can do, let me know.

BTW, saw you guys at pycon this year.  Was great seeing you guys there.

**Comment by vrunoa** [comment]
This was implemented on Appium 1.7.1
