### ISSUE TITLE
Unable to click on alert box of Ionic Application

### ISSUE THREAD

**Issue by sagarsheth27** [appium/appium#9610]
I tried with multiple ways. But not succeed for same. Here i want to click on OK button. But unable to do it.
Approaches as below which i was tried:
1. xpath
2. Accessibilityid
3. Mobileby
4. Driver.presskeycode(66).
5. Change context view

Use appium version as 1.7.0 with uiautomator2.
All above approaches tried by me. So please anyone can suggest what to do for same?
![2017-11-09_152109](https://user-images.githubusercontent.com/32329719/32599153-aa88b9da-c561-11e7-9904-28511a6afcac.png)

**Comment by sagarsheth27** [comment]
Also use **driver.switch.alert.accept.** 

So except all above approaches. If anyone has idea what to do for same then please suggest.

**Comment by mykola-mokhnach** [comment]
please attach full server log and the output of getPageSource

**Comment by mykola-mokhnach** [comment]
Also, it might be some legacy UIA issue. In such case try to switch automation backend to UIAutomator2

**Comment by dpgraham** [comment]
Ionic apps are WebView apps. You'll want to switch the context to WebView by setting the capability `autoWebview=true`

**Comment by dpgraham** [comment]
What happens when you switch context and call get source?

**Comment by sagarsheth27** [comment]
I tried capability autoWebview=true, but it was not working. Not a single click. It is not working for me.
When Ok button comes at that time context view is WebView_S, to click on enroll button. After that this scenario is coming. I switched it to NatvieApp to click on OK button again but it was not working.
Following are the capabilities which i defined.:

DesiredCapabilities capabilities = new DesiredCapabilities();
		// Set device name using capabilities
		capabilities.setCapability("deviceName", "Nexus");
		//capabilities.setCapability("deviceName", "AndroidNew");
		test.log(LogStatus.PASS,"Phone Application Started");
		// Set capability as browser name here ,it is Android
		//capabilities.setCapability(CapabilityType.BROWSER_NAME, "Android");
		// Set capability of Android version number
		capabilities.setCapability(CapabilityType.VERSION, "7.0");
		//capabilities.setCapability(CapabilityType.VERSION, "7.1");
		// Set Android platform name as here in our case it is Android
		capabilities.setCapability("platformName", "Android");
		test.log(LogStatus.PASS, "Load Application");
		// Set android app package capability names
		capabilities.setCapability("appPackage", "xxxxxxxx");
		//com.pscu.mobile
		capabilities.setCapability("automationName", "uiautomator2"); 

Following is my code.:

driver.context("WEBVIEW_S");
		driver.findElement(By.xpath("/html/body/ion-app/ng-component/ion-nav/page-login/ion-footer/ion-buttons[2]/button[2]/span")).click();
		//driver.findElement(MobileBy.xpath("//android.widget.Button['@content-desc='ENROLL ']")).click();
		test.log(LogStatus.PASS,"Click on enroll button to complete the process");
		s.getscreenshot(driver);
		Thread.sleep(2000);
		driver.context("NATIVE_APP");
		/*Alert alert = driver.switchTo().alert();
		alert.accept();
		Thread.sleep(2000);*/
		//driver.findElement(By.xpath("/html/body/ion-app/ion-alert/div/div[3]")).click();
		//html/body/ion-app/ion-alert/div/div[3]/button/span
		//html/body/ion-app/ion-alert/div/div[3]/button
		//driver.findElement(By.xpath("/html/body/ion-app/ion-alert/div/div[3]/button/span")).click();
		/*driver.context("NATIVE_APP");
		//Thread.sleep(1000);
		driver.findElement(By.xpath("//android.widget.Button[@content-desc='OK ']")).click();*/

**Comment by sagarsheth27** [comment]
[appium-server-logs.txt](https://github.com/appium/appium/files/1460281/appium-server-logs.txt)

PFA of Appium server log. Server stacked, didn't throw any error. I have to kill it manually to stop it.
By driver.getPageSource(), nothing is coming.

**Comment by mykola-mokhnach** [comment]
Like I mentioned before this is most likely legacy UIAutomation issue. Change the automation backend to UIAutomation2

**Comment by sagarsheth27** [comment]
How to change automation backend UIAutomation2. 
I already defined capability as **capabilities.setCapability("automationName", "uiautomator2");**.
Which i already mentioned in above comments.
