### ISSUE TITLE
Seekbar on Android not steerable via sendkeys()

### ISSUE THREAD

**Issue by GrzegorzSidwa** [appium/appium#9611]
## The problem

We got problems with Android Seekbars. Executing sendKeys() on this element is not working (no restults at all). Same command on iOS UISlider works correctly. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Desktop OS/version used to run Appium: MacOS Sierra
* Node.js version (unless using Appium.app|exe): 7.7.3
* Mobile platform/version under test: Android 6.0
* Real device or emulator/simulator: Huawei P9Lite/Samsung Galaxy S Tab2
* Appium CLI or Appium.app|exe: CLI

## Details

We got problems with Android Seekbars. Executing sendKeys() on this element is not working (no restults at all). Same command on iOS UISlider works correctly. It doesn't matter if we use in sendKeys values 0.5 or 0,5 or 5, every time there is no action from slider side (beside focusing touch on slider's toggle). Values are not changing at all.

## Link to Appium logs

https://gist.github.com/GrzegorzSidwa/a22b50c884490990eb11163537869473

## Code To Reproduce Issue [ Good To Have ]

The easiest way to reproduce case is creating sample android app with only 2 sliders. 
[appZip.zip](https://github.com/appium/appium/files/1457355/appZip.zip)

**Comment by mykola-mokhnach** [comment]
I assume UIAutomator framework does not  provide any methods to change such values. You can only change slider position using TouchAction. Am I right @vmaxim  ?

**Comment by vmaxim** [comment]
@mykola-mokhnach This can be done with [ACTION_SET_PROGRESS](https://developer.android.com/reference/android/view/accessibility/AccessibilityNodeInfo.AccessibilityAction.html#ACTION_SET_PROGRESS) accessbility action for API>=24

**Comment by mykola-mokhnach** [comment]
@vmaxim  Can you propose a PR when you have time?

**Comment by GrzegorzSidwa** [comment]
Would it be possible to have solution for lower APIs also ?

**Comment by vmaxim** [comment]
@GrzegorzSidwa I dont think  that's possible. You can use touch actions and [`getText()`](https://github.com/appium/appium-uiautomator2-server/commit/71f1e14745db3df4ffe817d17f49f866e772b4fe) to find desired position on seek bar.

**Comment by saikrishna321** [comment]
Closing as it works 👍 

https://github.com/appium/appium-uiautomator2-server/pull/96
