### ISSUE TITLE
Unable to launch .app on simulator. 

### ISSUE THREAD

**Issue by padmakarsrinivas** [appium/appium#9612]
## The problem

The application flashes and closes in a sec

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Desktop OS/version used to run Appium: MAC V10.12.6
* Mobile platform/version under test: iPhone 6 iOS 11.1
* Real device or emulator/simulator: Simulator

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/padmakarsrinivas/122cb4d5158b6b89c51fe349398b05b0

## Code To Reproduce Issue [ Good To Have ]

Capabilities are 

DesiredCapabilities capabilities = new DesiredCapabilities();
		File appDir = new File("/Users/srinivasp/Desktop");
		File app = new File(appDir, "XXXX.app");
		capabilities.setCapability(MobileCapabilityType.BROWSER_NAME, "");
		capabilities.setCapability(MobileCapabilityType.APPIUM_VERSION, "1.7");
		capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "11.1");
		capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone 6");
		capabilities.setCapability(MobileCapabilityType.APP, app.getAbsolutePath());
		capabilities.setCapability("newCommandTimeout", 2000);
		mobiledriver = new IOSDriver<>(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);

Application fails to launch at 
[debug] [XCUITest] WebDriverAgent running on ip '172.16.48.248'
[debug] [XCUITest] WebDriverAgent successfully started after 24564ms
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1510232939823 (18:38:59 GMT+0530 (IST))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"net.XXXX.XXXX","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}

**Comment by mykola-mokhnach** [comment]
> [error] [XCUITest] Error: The desired capabilities must include either an app or a bundleId for iOS

Closed as not an issue

**Comment by padmakarsrinivas** [comment]
Still Unable to launch the application on simulator even after mentioning app and bundleId

Updates gist https://gist.github.com/padmakarsrinivas/122cb4d5158b6b89c51fe349398b05b0

**Comment by imurchie** [comment]
Is the app launchable manually?

Can you add the `showIOSLog` capability (set to `true`) so the device logs are visible?
