### ISSUE TITLE
Can`t Parallel Android Tests with AppiumServiceBuilder

### ISSUE THREAD

**Issue by smallsharp** [appium/appium#9615]
## The problem
i want to use AppiumServiceBuilder  to build multiple AppiumServer,

**AppiumServiceBuilder builder = new AppiumServiceBuilder()
builder.withIPAddress(ipAddress);
builder.usingPort(port);
builder.withUdid(udid);**

but there is no method like **builder.withUdid(udid)** to use.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Java Client version: 5.0.4
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: 
* Node.js version (unless using Appium.app|exe): 5.4.2
* Mobile platform/version under test:
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Here we can find args like "udid"
https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/default-capabilities-arg.md

## Code To Reproduce Issue [ Good To Have ]
goto The problem above

**Comment by saikrishna321** [comment]
@smallsharp  Pls look at this 

https://github.com/saikrishna321/AppiumTestDistribution/blob/master/src/main/java/com/appium/manager/AppiumServerManager.java#L57-L70

You can provide the udid in capabilities when your running in parallel 

https://github.com/saikrishna321/AppiumTestDistribution/blob/master/src/main/java/com/appium/utils/DesiredCapabilityBuilder.java#L124

**Comment by smallsharp** [comment]
@saikrishna321 
I know "You can provide the udid in capabilities when your running in parallel"
like this:dc.
**setCapability("deviceName", deviceName);**
**but i want to build the server, not the driver.**

**Comment by vjmaiky** [comment]
The important flags for automating multiple Android sessions are:

-p the main Appium port
-U the device id
-bp the Appium bootstrap port
--chromedriver-port the chromedriver port (if using webviews or chrome)
--selendroid-port the selendroid port (if using selendroid)
More information on these flags can be found here.

If we had two devices with the ID’s 43364 and 32456, we would start two different Appium servers with the following commands:

node . -p 4492 -bp 2251 -U 32456

node . -p 4491 -bp 2252 -U 43364

**Comment by vjmaiky** [comment]
second option you can start appium from code but you need jason files for each device to pass the ip, port, udid, etc

**Comment by mykola-mokhnach** [comment]
@smallsharp AppiumServiceBuilder class is a part of java client and issues about is should be reported to https://github.com/appium/java-client/issues

**Comment by smallsharp** [comment]
I don`t think the problem is solved .

**Comment by saikrishna321** [comment]
@vjmaiky with latest appium, you can have single appium server session and create multiple drivers
