### ISSUE TITLE
Simulator quiz unexpectedly while running app suite in iPhone X simulator

### ISSUE THREAD

**Issue by Logakarti** [appium/appium#9616]
## The problem

Simulator quiz unexpectedly while running app suite on iPhone X simulator. How to resolve this issue. The Same issue gets while launching the app manually in iPhone X simulator through Xcode 9
## Environment
Appium version : 1.7.1
Desktop OS/version used to run Appium:MAC(Sierra) 10.12.6
Mobile platform/version under test: iOS 11.0
Real device or emulator/simulator: iPhone x (Simulator)

## Link to Appium logs

https://gist.github.com/Logakarti/2db06e6db7735bbc29ef8884a3898d40

**Comment by mykola-mokhnach** [comment]
this looks like a bug in Apple Simulator itself. Try to update your Xcode SDK to the latest version and report the issue to Apple if it still there.
