### ISSUE TITLE
Windows Application Driver appium is not detecting element of one windows application developed using Delphi (Embarcadero)

### ISSUE THREAD

**Issue by Subhacse17** [appium/appium#9617]
## The problem
Appium could not find element in a windows application developed using Delphi (Embarcadero).
When it tried to click on any element of the form the error message is like that 
"An element could not be located on the page using the given search parameters."
Inside the PageSource of the session there is also not sufficient element present in the xml.
I am using win 10 and visual studio 2015(c#). appium driver can locate other application like calculator, notepad etc but when  I am using different windows form application developed by Delphi appium can not locate any element. 
N.B: inspect.exe and VisualUIAVerifyNative.exe can locate all element of the form easily. 
 

## Environment
 * Visual Studio 2015(C#) 
 * Appium version : 3.0.0.2
* Desktop OS/version used to run Appium: Windows 10
* Node.js version :8.9.0
* Appium CLI or Appium.app|exe: Windows Application Driver

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

POST /session/F5F05B32-4F56-4F9B-955A-3DAC285239FF/element HTTP/1.1
Accept: application/json, image/png
Content-Length: 29
Content-Type: application/json;charset=utf-8
Host: 127.0.0.1:4723

{"using":"name","value":"Launch"}
HTTP/1.1 404 Not Found
Content-Length: 139
Content-Type: application/json

{"status":7,"value":{"error":"no such element","message":"An element could not be located on the page using the given search parameters."}}

## Code To Reproduce Issue [ Good To Have ]

                DesiredCapabilities appCapabilities = new DesiredCapabilities();
                appCapabilities.SetCapability("app", AdminExePath);
                appCapabilities.SetCapability("deviceName", "WindowsPC");
                appCapabilities.SetCapability("browserName", "Chrome");
                Uri uri = new Uri(WindowsApplicationDriverUrl);
                session = new WindowsDriver<WindowsElement>(uri, appCapabilities);
                session.Manage().Timeouts().ImplicitlyWait(TimeSpan.FromSeconds(1.5));

**Comment by mykola-mokhnach** [comment]
Can you also attach the output of getPageSource?

**Comment by Subhacse17** [comment]
Dear mykola-mokhnach,
This is the PageSource : I suppose to click on a button named Launch.(got the name using Inspect.exe). But in Page Source There is nothing like this.
##Page Source 
<?xml version="1.0" encoding="utf-16"?><Window AcceleratorKey="" AccessKey="" AutomationId="" ClassName="TApplication" FrameworkId="Win32" HasKeyboardFocus="False" HelpText="" IsContentElement="True" IsControlElement="True" IsEnabled="True" IsKeyboardFocusable="True" IsOffscreen="True" IsPassword="False" IsRequiredForForm="False" ItemStatus="" ItemType="" LocalizedControlType="window" Name="Txupgrade" Orientation="None" ProcessId="13124" RuntimeId="42.68392" x="0" y="0" width="156" height="27" CanMaximize="False" CanMinimize="True" IsModal="False" WindowVisualState="Minimized" WindowInteractionState="ReadyForUserInteraction" IsTopmost="False" CanRotate="False" CanResize="False" CanMove="False" IsAvailable="True" />

**Comment by pablotdv** [comment]
I have the same problem.
Is any solution?

**Comment by Subhacse17** [comment]
Dear @pablotdv, Unfortunately no. I am still stuck with this problem. It may be a bug of Appium.

**Comment by Subhacse17** [comment]
Please I really need to fix this issue very quickly, if you can kindly help me, I will be gratefull to you. @mykola-mokhnach

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
