### ISSUE TITLE
iOS platform: Touch Actions tap gesture is not Working

### ISSUE THREAD

**Issue by SatishCigniti** [appium/appium#9618]
The problem: 

I am trying to make a tap gesture using coordinates available, in TouchActions class for iOS  on real device,  The tap gesture just creates no effect. 

Environment:

Appium Version: Appium v1.7.2-beta
MacOS : 10.13.2
Xcode: 8.3
Device: iPad Pro
iOS: 10.2
JavaClient: 5.0.4

Capabilities Used:

        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability("preventWDAAttachments", false);
        capabilities.setCapability("platformName", "ios");
        capabilities.setCapability("automationName", "XCUITest");
        capabilities.setCapability("realDeviceLogger", "idevicesyslog");
        capabilities.setCapability("platformVersion", "10.2");
        capabilities.setCapability("fullReset", false);
        capabilities.setCapability("useNewWDA", true);
        capabilities.setCapability("noReset", true);
        capabilities.setCapability("clearSystemFiles", true);
        capabilities.setCapability("xcodeOrgId", "xxxxxxxxx");
        capabilities.setCapability("xcodeSigningId", "iPhone Developer");
        capabilities.setCapability("deviceName", "xxxx iPad");
        capabilities.setCapability("deviceOrientation","landscape")
        capabilities.setCapability("newCommandTimeout", 100);
        capabilities.setCapability("udid", "bbbb");
        capabilities.setCapability("app", "/Users/ctl-user/Downloads/xxxxxx.ipa");
        println("Creating local iOS driver")
        return capabilities

    @Override
    public ImageElement tap() {
        driver.tap(1, x + width / 2, y + height / 2, 100);
        try {
            waitAfterClick();
        } catch (InterruptedException e) {
        }
        return this;
    }

The similar tap gestures are working for Android platform and not for iOS.

The Server logs canbe found at https://gist.github.com/SatishCigniti/103dbdb70b5c6f29841b82fd1fd51216

**Comment by SatishCigniti** [comment]
https://gist.github.com/SatishCigniti/103dbdb70b5c6f29841b82fd1fd51216

**Comment by mykola-mokhnach** [comment]
1. `driver.tap` is deprecated. Use TouchAction instead
2. There is a known problem with XCTest and landscape orientation. Try to click by element offset instead of providing generic coordinates

**Comment by SatishCigniti** [comment]
Dear @mykola-mokhnach, 
By accidently i posted the wrong method  for tapping , below is the actual method we are using.
boolean tapOnImage(String targetImgPath) {
        Point2D coords = getCoords(takeScreenshot(), targetImgPath)
        println("Click X: " + coords.getX() + " Y: " + coords.getY())
        if ((coords.getX() >= 0) && (coords.getY() >= 0)) {
            new TouchAction(driver).tap((int) coords.getX(), (int) coords.getY()).perform()
            //driver.tap(1, (int) coords.getX(), (int) coords.getY(), 500)
            return true
        }
        throw new ElementNotVisibleException("Element not found - " + targetImgPath)
    }
