### ISSUE TITLE
Change locale cause appium to crash in Android N and O

### ISSUE THREAD

**Issue by navnathkarche** [appium/appium#9619]
## The problem

I am trying to set different locale using desired capability 'locale: fr_CA' through my script. This cause appium to crash.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.0 beta
* Desktop OS/version used to run Appium: mac os El capitan
* Node.js version (unless using Appium.app|exe): v6.11.0
* Mobile platform/version under test: Android N and O 
* Real device or emulator/simulator: emulator + real device

## Details
Whenever I try locale set different locale (anything other that existing locale of my device) appium crashes at : `shell stop' exited with code 1'; Stderr: 'stop: must be root'; Code: '1'`,

Since android N adb does not have root access. And appium uses `persist.sys.locale` property to change device locale after that device must be rebooted, so appium need adb to run as root for executing `adb stop` and `adb start` commands.

NOTE: This was not observed in Android M and below because adb has a root access

**Comment by KazuCocoa** [comment]
Fixed. We can set `locale` with the following versions.

- https://github.com/appium/appium-uiautomator2-driver `0.7.6`
- https://github.com/appium/appium-android-driver `1.35.0`
- https://github.com/appium/appium-adb `5.3.1`

**Comment by KazuCocoa** [comment]
Fix for ^

**Comment by navnathkarche** [comment]
@KazuCocoa I have reinstall the appium to update the above packages version, but these packages are not updated on my machine, so the it still give same error.
Can you please help on this? How to update above dependancy.

**Comment by KazuCocoa** [comment]
I guess 1.7.2-beta2 and the above can install the version but beta3 and beta 4 has an issue for createSession.
So, if you can use the master's latest version, you can use the latest packages.
@navnathkarche

**Comment by navnathkarche** [comment]
1.7.2-beta and 1.7.2-beta2 also has an issue with createSession, so currently I can't change the locale using these version and 1.7.1 could not update the required dependancy for change locale.
