### ISSUE TITLE
KeepAliveFailure Exception, Server killing connection

### ISSUE THREAD

**Issue by mwschmitt** [appium/appium#9620]
## The problem

I am running automated testing for iOS and an issue that persists is the KeepAliveFailure Exception.

![image](https://user-images.githubusercontent.com/33554087/32670692-34cb70d0-c60a-11e7-8de6-554410c15ca7.png)

The server consistently kills the connection after the JavaScript line is executed

![image](https://user-images.githubusercontent.com/33554087/32670723-4800addc-c60a-11e7-92b7-0c865ad17ddc.png)

After research and investigation, I have concluded that the problem comes from the server. I have found that when the scroll concludes, the line (4th up from the below image that begins with [HTTP]) only has a single <-- POST, instead of the usual <-- and --> that exists every where else in the server log.

![image](https://user-images.githubusercontent.com/33554087/32670777-6a618054-c60a-11e7-83e5-d034e8458e9d.png)

Is the server connection the problem? And if so why is the server continually killing the connection and what is the solution?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Desktop OS/version used to run Appium: MacOS Sierra 1012.6
* Mobile platform/version under test: iOS 10.3
* Real device or emulator/simulator: Xcode simulator iPhone 7
* Appium server startup line in terminal: appium --address MYADDRESS --port MYPORT --platform-name iOS --native-instruments-lib

## Details

* This only occurs when the Appium server is started from terminal on a remote machine. It works fine from the Appium Desktop App, but I need to use the terminal.
* If stepped through, step by step in the debugger, the exception does not appear.

**Comment by mykola-mokhnach** [comment]
Can you please attach the full server log?

**Comment by mwschmitt** [comment]
The full server log is quite long and contains sensitive information. I can provide more of the log but not all of it.

**Comment by ochubey** [comment]
use https://gist.github.com/ to do it correctly (you can remove sensitive info replacing it)
