### ISSUE TITLE
How to accept "Permit drawing over app" on Android?

### ISSUE THREAD

**Issue by tastafur** [appium/appium#9624]
## The problem

i am triying tap in permits "Permit drawing over app", i don't know how to do it

<img width="461" alt="captura de pantalla 2017-11-12 a las 19 09 34" src="https://user-images.githubusercontent.com/11853181/32701872-7c672f9a-c7dd-11e7-8a0c-adb82a7a215a.png">

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Desktop OS/version used to run Appium: macOS Sierra, 10.12.6
* Node.js version (unless using Appium.app|exe): 7.10.0
* Mobile platform/version under test: 6.0
* Real device or emulator/simulator: Genymotion
* Appium CLI or Appium.app|exe: appium CLI

## Link to Appium logs

https://gist.github.com/tastafur/3f1b95bdb873340f9c4b1e00d9346c25

**Comment by KazuCocoa** [comment]
The log said failed to launch the activity.

> 2017-11-12 17:47:20:880 - error: [ADB] Error: com.android.settings.Settings$AppDrawOverlaySettingsActivity or com.globalengapp.com.android.settings.Settings$AppDrawOverlaySettingsActivity never started

Before getting a page source, could you check `appWaitActivity` is correct and try to set `appActivity` capability to establish connection? And could you try it with Appium 1.7?

**Comment by mykola-mokhnach** [comment]
Have you also tried to set _autoGrantPermissions_ to true?

**Comment by tastafur** [comment]
yes, i will trying autoGrantPermission to true and i not work me.
I have managed to make it work with this capabilities.
`    "appWaitActivity": "com.android.settings.Settings$AppDrawOverlaySettingsActivity, com.globalengapp.MainActivity",
    "appWaitPackage": "com.android.settings, com.globalengapp",`

 but now I need to click on the physical back button but I do not know how

**Comment by mykola-mokhnach** [comment]
in java client there is navigate().back() method for this purpose.

**Comment by tastafur** [comment]
I am using client webdriverio and back protocol http://webdriver.io/api/protocol/back.html working me, thank you very much for your attention

**Comment by valerybugakov** [comment]
@tastafur capabilities helped me solve similar issue, thanks!

**Comment by SnehaPolaki** [comment]
Even after using the same capabilities  as mentioned above, I am not grant permission for the app.

**Comment by pritamkarmakar** [comment]
I have 'autoGrantPermissions' set to true and it worked fine for Android 7.0 and 8.0. But With Android 6.0 I'm still getting the permission issue 'Permit drawing over other apps'. I have tried with the above-mentioned capabilities but didn't solve my problem.

Workaround for me, I run adb command before starting Appium test, and this fixed the problem with Android 6.0

`adb -s emulator-5558 shell 'appops set <your app package>  SYSTEM_ALERT_WINDOW allow'`
