### ISSUE TITLE
 waiting for connection [debug] [iProxy] Number of available devices == 1 [debug] [iProxy] Requesting connecion to device handle == 1 (serial: 6b5dc9ce1d3846893ff756459eb2b7133938bbcb), port 8100

### ISSUE THREAD

**Issue by Kitty2014** [appium/appium#9626]
## The problem

 waiting for connection
[debug] [iProxy] Number of available devices == 1
[debug] [iProxy] Requesting connecion to device handle == 1 (serial: 6b5dc9ce1d3846893ff756459eb2b7133938bbcb), port 8100 shown   when running iOS11
## Environment

Appium version (or git revision) that exhibits the issue: v1.7.2-beta
Last Appium version that did not exhibit the issue (if applicable): -
Desktop OS/version used to run Appium: 10.12.6 (16G1023)
Node.js version (unless using Appium.app|exe): v8.4.0
Mobile platform/version under test: iPhone X iOS 11.0.1 and 11.2
Real device or emulator/simulator: Real Device
Appium CLI or Appium.app|exe: Appium CLI
Xcode version set to 'Version 9.2 beta (9C32c)'

## Details

iOS10.3.3  normally  but fail  with `iOS11`
## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by Kitty2014** [comment]
![wechatimg351](https://user-images.githubusercontent.com/7512412/32717329-df46bdba-c81e-11e7-8b1f-264a69ff8ee2.jpeg)
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [XCUITest] Executing command 'proxyReqRes'
[debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/5c2ea059-7fb7-4de1-a1bd-a64b3025f006/element/94FF62BB-765A-4D78-A657-9A909C4E5757/enabled] to [GET http://localhost:8600/session/6ABF55B8-2AAA-4075-8087-F86F2D74B717/element/94FF62BB-765A-4D78-A657-9A909C4E5757/enabled] with body: {}
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : true,\n  \"sessionId\" : \"6ABF55B8-2AAA-4075-8087-F86F2D74B717\",\n  \"status\" : 0\n}"
[JSONWP Proxy] Replacing sessionId 6ABF55B8-2AAA-4075-8087-F86F2D74B717 with 5c2ea059-7fb7-4de1-a1bd-a64b3025f006
[HTTP] <-- GET /wd/hub/session/5c2ea059-7fb7-4de1-a1bd-a64b3025f006/element/94FF62BB-765A-4D78-A657-9A909C4E5757/enabled 200 206 ms - 76 
[HTTP] --> POST /wd/hub/session/5c2ea059-7fb7-4de1-a1bd-a64b3025f006/element {"using":"name","value":"品牌 "}
[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["name","品牌 ","5c2ea059-7fb7-4de1-a1bd-a64b3025f006"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 5000 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8600/session/6ABF55B8-2AAA-4075-8087-F86F2D74B717/element] with body: {"using":"name","value":"品牌 "}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"ELEMENT":"F84B804F-8D73-4DA1-95D0-E673590FDE55"},"sessionId":"6ABF55B8-2AAA-4075-8087-F86F2D74B717","status":0}
[debug] [MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"F84B804F-8D73-4DA1-95D0-E673590FDE55"}
[HTTP] <-- POST /wd/hub/session/5c2ea059-7fb7-4de1-a1bd-a64b3025f006/element 200 241 ms - 122 
[HTTP] --> POST /wd/hub/session/5c2ea059-7fb7-4de1-a1bd-a64b3025f006/element/F84B804F-8D73-4DA1-95D0-E673590FDE55/click {"id":"F84B804F-8D73-4DA1-95D0-E673590FDE55"}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [XCUITest] Executing command 'proxyReqRes'
[debug] [JSONWP Proxy] Proxying [POST /wd/hub/session/5c2ea059-7fb7-4de1-a1bd-a64b3025f006/element/F84B804F-8D73-4DA1-95D0-E673590FDE55/click] to [POST http://localhost:8600/session/6ABF55B8-2AAA-4075-8087-F86F2D74B717/element/F84B804F-8D73-4DA1-95D0-E673590FDE55/click] with body: {"id":"F84B804F-8D73-4DA1-95D0-E673590FDE55"}
[debug] [JSONWP Proxy] Got response with status 200: {"status":0,"id":"F84B804F-8D73-4DA1-95D0-E673590FDE55","value":"","sessionId":"6ABF55B8-2AAA-4075-8087-F86F2D74B717"}
[JSONWP Proxy] Replacing sessionId 6ABF55B8-2AAA-4075-8087-F86F2D74B717 with 5c2ea059-7fb7-4de1-a1bd-a64b3025f006
[HTTP] <-- POST /wd/hub/session/5c2ea059-7fb7-4de1-a1bd-a64b3025f006/element/F84B804F-8D73-4DA1-95D0-E673590FDE55/click 200 1129 ms - 118 
[HTTP] --> POST /wd/hub/session/5c2ea059-7fb7-4de1-a1bd-a64b3025f006/elements {"using":"name","value":"奥迪"}
[debug] [MJSONWP] Calling AppiumDriver.findElements() with args: ["name","奥迪","5c2ea059-7fb7-4de1-a1bd-a64b3025f006"]
[debug] [XCUITest] Executing command 'findElements'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 5000 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8600/session/6ABF55B8-2AAA-4075-8087-F86F2D74B717/elements] with body: {"using":"name","value":"奥迪"}
[debug] [XCUITest] Connection to WDA timed out
[debug] [iProxy] recv failed: Operation not permitted
[debug] [MJSONWP] Responding to client with driver.findElements() result: []
[HTTP] <-- POST /wd/hub/session/5c2ea059-7fb7-4de1-a1bd-a64b3025f006/elements 200 11769 ms - 74 
[debug] [XCUITest] Log file for xcodebuild test: /var/folders/c2/cllky7gs5mg0n8rbz8jygwz40000gn/T/com.apple.dt.XCTest/IDETestRunSession-B70941EE-BB6A-43E9-89E8-AFCC4F2FB66D/WebDriverAgentRunner-54DA2FE9-8A78-4A6D-87B4-78BDA71943D4/Session-WebDriverAgentRunner-2017-11-13_165602-ilwWtU.log
[HTTP] --> POST /wd/hub/session/5c2ea059-7fb7-4de1-a1bd-a64b3025f006/elements {"using":"name","value":"奥迪"}
[debug] [MJSONWP] Calling AppiumDriver.findElements() with args: ["name","奥迪","5c2ea059-7fb7-4de1-a1bd-a64b3025f006"]
[debug] [XCUITest] Executing command 'findElements'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 5000 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8600/session/6ABF55B8-2AAA-4075-8087-F86F2D74B717/elements] with body: {"using":"name","value":"奥迪"}
[debug] [iProxy] Error connecting to device!
[debug] [BaseDriver] Waited for 106 ms so far
[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8600/session/6ABF55B8-2AAA-4075-8087-F86F2D74B717/elements] with body: {"using":"name","value":"奥迪"}
[debug] [iProxy] Error connecting to device!
[debug] [BaseDriver] Waited for 719 ms so far
[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8600/session/6ABF55B8-2AAA-4075-8087-F86F2D74B717/elements] with body: {"using":"name","value":"奥迪"}
[debug] [iProxy] Error connecting to device!
[debug] [BaseDriver] Waited for 1347 ms so far
[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8600/session/6ABF55B8-2AAA-4075-8087-F86F2D74B717/elements] with body: {"using":"name","value":"奥迪"}
[debug] [iProxy] Error connecting to device!
[debug] [BaseDriver] Waited for 1963 ms so far
[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8600/session/6ABF55B8-2AAA-4075-8087-F86F2D74B717/elements] with body: {"using":"name","value":"奥迪"}
[debug] [iProxy] Error connecting to device!
[debug] [BaseDriver] Waited for 2574 ms so far
[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8600/session/6ABF55B8-2AAA-4075-8087-F86F2D74B717/elements] with body: {"using":"name","value":"奥迪"}
[debug] [iProxy] Error connecting to device!
[debug] [BaseDriver] Waited for 3184 ms so far
[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8600/session/6ABF55B8-2AAA-4075-8087-F86F2D74B717/elements] with body: {"using":"name","value":"奥迪"}
[debug] [iProxy] Error connecting to device!
[debug] [BaseDriver] Waited for 3798 ms so far
[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8600/session/6ABF55B8-2AAA-4075-8087-F86F2D74B717/elements] with body: {"using":"name","value":"奥迪"}
[debug] [iProxy] Error connecting to device!
[debug] [BaseDriver] Waited for 4415 ms so far
[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8600/session/6ABF55B8-2AAA-4075-8087-F86F2D74B717/elements] with body: {"using":"name","value":"奥迪"}
[debug] [iProxy] Error connecting to device!
[debug] [MJSONWP] Responding to client with driver.findElements() result: []
[HTTP] <-- POST /wd/hub/session/5c2ea059-7fb7-4de1-a1bd-a64b3025f006/elements 200 5027 ms - 74 
[XCUITest] xcodebuild exited with code '65' and signal 'null'
[HTTP] --> POST /wd/hub/session/5c2ea059-7fb7-4de1-a1bd-a64b3025f006/elements {"using":"name","value":"奥迪"}
[debug] [MJSONWP] Calling AppiumDriver.findElements() with args: ["name","奥迪","5c2ea059-7fb7-4de1-a1bd-a64b3025f006"]
[debug] [XCUITest] Executing command 'findElements'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 5000 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8600/session/6ABF55B8-2AAA-4075-8087-F86F2D74B717/elements] with body: {"using":"name","value":"奥迪"}
[debug] [iProxy] Error connecting to device!
[debug] [BaseDriver] Waited for 114 ms so far
[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8600/session/6ABF55B8-2AAA-4075-8087-F86F2D74B717/elements] with body: {"using":"name","value":"奥迪"}
[debug] [iProxy] Error connecting to device!
[debug] [BaseDriver] Waited for 775 ms so far
[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8600/session/6ABF55B8-2AAA-4075-8087-F86F2D74B717/elements] with body: {"using":"name","value":"奥迪"}
[debug] [iProxy] Error connecting to device!
[debug] [BaseDriver] Waited for 1382 ms so far
[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8600/session/6ABF55B8-2AAA-4075-8087-F86F2D74B717/elements] with body: {"using":"name","value":"奥迪"}
[debug] [iProxy] Error connecting to device!
[debug] [BaseDriver] Waited for 1992 ms so far
[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8600/session/6ABF55B8-2AAA-4075-8087-F86F2D74B717/elements] with body: {"using":"name","value":"奥迪"}
[debug] [iProxy] Error connecting to device!
[debug] [BaseDriver] Waited for 2604 ms so far
[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8600/session/6ABF55B8-2AAA-4075-8087-F86F2D74B717/elements] with body: {"using":"name","value":"奥迪"}
[debug] [iProxy] Error connecting to device!
[debug] [BaseDriver] Waited for 3215 ms so far
[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8600/session/6ABF55B8-2AAA-4075-8087-F86F2D74B717/elements] with body: {"using":"name","value":"奥迪"}
[debug] [iProxy] Error connecting to device!
[debug] [BaseDriver] Waited for 3823 ms so far
[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8600/session/6ABF55B8-2AAA-4075-8087-F86F2D74B717/elements] with body: {"using":"name","value":"奥迪"}
[debug] [iProxy] Error connecting to device!
[debug] [BaseDriver] Waited for 4434 ms so far
[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8600/session/6ABF55B8-2AAA-4075-8087-F86F2D74B717/elements] with body: {"using":"name","value":"奥迪"}
[debug] [iProxy] Error connecting to device!
[debug] [MJSONWP] Responding to client with driver.findElements() result: []
[HTTP] <-- POST /wd/hub/session/5c2ea059-7fb7-4de1-a1bd-a64b3025f006/elements 200 5047 ms - 74 
[HTTP] --> POST /wd/hub/session/5c2ea059-7fb7-4de1-a1bd-a64b3025f006/elements {"using":"name","value":"奥迪"}
[debug] [MJSONWP] Calling AppiumDriver.findElements() with args: ["name","奥迪","5c2ea059-7fb7-4de1-a1bd-a64b3025f006"]
[debug] [XCUITest] Executing command 'findElements'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 5000 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8600/session/6ABF55B8-2AAA-4075-8087-F86F2D74B717/elements] with body: {"using":"name","value":"奥迪"}
[debug] [iProxy] Error connecting to device!
[debug] [BaseDriver] Waited for 109 ms so far
[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8600/session/6ABF55B8-2AAA-4075-8087-F86F2D74B717/elements] with body: {"using":"name","value":"奥迪"}
[debug] [iProxy] Error connecting to device!
[debug] [BaseDriver] Waited for 720 ms so far
[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8600/session/6ABF55B8-2AAA-4075-8087-F86F2D74B717/elements] with body: {"using":"name","value":"奥迪"}
[debug] [iProxy] Error connecting to device!
[debug] [BaseDriver] Waited for 1331 ms so far
[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8600/session/6ABF55B8-2AAA-4075-8087-F86F2D74B717/elements] with body: {"using":"name","value":"奥迪"}
[debug] [iProxy] Error connecting to device!
[debug] [BaseDriver] Waited for 1948 ms so far
[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8600/session/6ABF55B8-2AAA-4075-8087-F86F2D74B717/elements] with body: {"using":"name","value":"奥迪"}
[debug] [iProxy] Error connecting to device!
[debug] [BaseDriver] Waited for 2561 ms so far
[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8600/session/6ABF55B8-2AAA-4075-8087-F86F2D74B717/elements] with body: {"using":"name","value":"奥迪"}
[debug] [iProxy] Error connecting to device!
[debug] [BaseDriver] Waited for 3173 ms so far
[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8600/session/6ABF55B8-2AAA-4075-8087-F86F2D74B717/elements] with body: {"using":"name","value":"奥迪"}
[debug] [iProxy] Error connecting to device!
[debug] [BaseDriver] Waited for 3786 ms so far
[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8600/session/6ABF55B8-2AAA-4075-8087-F86F2D74B717/elements] with body: {"using":"name","value":"奥迪"}
[debug] [iProxy] Error connecting to device!
[debug] [BaseDriver] Waited for 4399 ms so far
[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8600/session/6ABF55B8-2AAA-4075-8087-F86F2D74B717/elements] with body: {"using":"name","value":"奥迪"}
[debug] [iProxy] Error connecting to device!
[debug] [MJSONWP] Responding to client with driver.findElements() result: []
[HTTP] <-- POST /wd/hub/session/5c2ea059-7fb7-4de1-a1bd-a64b3025f006/elements 200 5010 ms - 74 
[HTTP] --> POST /wd/hub/session/5c2ea059-7fb7-4de1-a1bd-a64b3025f006/elements {"using":"name","value":"奥迪"}
[debug] [MJSONWP] Calling AppiumDriver.findElements() with args: ["name","奥迪","5c2ea059-7fb7-4de1-a1bd-a64b3025f006"]
[debug] [XCUITest] Executing command 'findElements'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 5000 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8600/session/6ABF55B8-2AAA-4075-8087-F86F2D74B717/elements] with body: {"using":"name","value":"奥迪"}
[debug] [iProxy] Error connecting to device!
[debug] [BaseDriver] Waited for 107 ms so far
[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8600/session/6ABF55B8-2AAA-4075-8087-F86F2D74B717/elements] with body: {"using":"name","value":"奥迪"}
[debug] [iProxy] Error connecting to device!
[debug] [BaseDriver] Waited for 717 ms so far
[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8600/session/6ABF55B8-2AAA-4075-8087-F86F2D74B717/elements] with body: {"using":"name","value":"奥迪"}
[debug] [iProxy] waiting for connection
[debug] [iProxy] accepted connection, fd = 4
[debug] [iProxy] waiting for connection
[debug] [iProxy] Number of available devices == 1
[debug] [iProxy] Requesting connecion to device handle == 1 (serial: 6b5dc9ce1d3846893ff756459eb2b7133938bbcb), port 8100
[debug] [iProxy] accepted connection, fd = 4
[debug] [iProxy] waiting for connection
[debug] [iProxy] Number of available devices == 1
[debug] [iProxy] Requesting connecion to device handle == 1 (serial: 6b5dc9ce1d3846893ff756459eb2b7133938bbcb), port 8100
[debug] [iProxy] accepted connection, fd = 4
[debug] [iProxy] waiting for connection
[debug] [iProxy] Number of available devices == 1
[debug] [iProxy] Requesting connecion to device handle == 1 (serial: 6b5dc9ce1d3846893ff756459eb2b7133938bbcb), port 8100
[debug] [iProxy] accepted connection, fd = 4
[debug] [iProxy] waiting for connection
[debug] [iProxy] Number of available devices == 1
[debug] [iProxy] Requesting connecion to device handle == 1 (serial: 6b5dc9ce1d3846893ff756459eb2b7133938bbcb), port 8100
[debug] [iProxy] accepted connection, fd = 4
[debug] [iProxy] waiting for connection
[debug] [iProxy] Number of available devices == 1
[debug] [iProxy] Requesting connecion to device handle == 1 (serial: 6b5dc9ce1d3846893ff756459eb2b7133938bbcb), port 8100
[debug] [iProxy] accepted connection, fd = 4
[debug] [iProxy] waiting for connection
[debug] [iProxy] Number of available devices == 1
[debug] [iProxy] Requesting connecion to device handle == 1 (serial: 6b5dc9ce1d3846893ff756459eb2b7133938bbcb), port 8100
[debug] [iProxy] accepted connection, fd = 4
[debug] [iProxy] waiting for connection
[debug] [iProxy] Number of available devices == 1
[debug] [iProxy] Requesting connecion to device handle == 1 (serial: 6b5dc9ce1d3846893ff756459eb2b7133938bbcb), port 8100
[debug] [iProxy] accepted connection, fd = 4
[debug] [iProxy] waiting for connection
[debug] [iProxy] Number of available devices == 1
[debug] [iProxy] Requesting connecion to device handle == 1 (serial: 6b5dc9ce1d3846893ff756459eb2b7133938bbcb), port 8100
[debug] [iProxy] accepted connection, fd = 4
[debug] [iProxy] waiting for connection
[debug] [iProxy] Number of available devices == 1
[debug] [iProxy] Requesting connecion to device handle == 1 (serial: 6b5dc9ce1d3846893ff756459eb2b7133938bbcb), port 8100
[debug] [iProxy] accepted connection, fd = 4
[debug] [iProxy] waiting for connection
[debug] [iProxy] Number of available devices == 1
[debug] [iProxy] Requesting connecion to device handle == 1 (serial: 6b5dc9ce1d3846893ff756459eb2b7133938bbcb), port 8100
[debug] [iProxy] accepted connection, fd = 4
[debug] [iProxy] waiting for connection
[debug] [iProxy] Number of available devices == 1
[debug] [iProxy] Requesting connecion to device handle == 1 (serial: 6b5dc9ce1d3846893ff756459eb2b7133938bbcb), port 8100
[debug] [iProxy] accepted connection, fd = 4
[debug] [iProxy] waiting for connection
[debug] [iProxy] Number of available devices == 1
[debug] [iProxy] Requesting connecion to device handle == 1 (serial: 6b5dc9ce1d3846893ff756459eb2b7133938bbcb), port 8100
[debug] [iProxy] accepted connection, fd = 4
[debug] [iProxy] waiting for connection
[debug] [iProxy] Number of available devices == 1
[debug] [iProxy] Requesting connecion to device handle == 1 (serial: 6b5dc9ce1d3846893ff756459eb2b7133938bbcb), port 8100
[debug] [iProxy] run_ctos_loop: fd = 4
[debug] [iProxy] run_stoc_loop: fd = 4
[debug] [iProxy] accepted connection, fd = 4
[debug] [iProxy] waiting for connection
[debug] [iProxy] Number of available devices == 1
[debug] [iProxy] Requesting connecion to device handle == 1 (serial: 6b5dc9ce1d3846893ff756459eb2b7133938bbcb), port 8100
[debug] [iProxy] accepted connection, fd = 4
[debug] [iProxy] waiting for connection
[debug] [iProxy] Number of available devices == 1
[debug] [iProxy] Requesting connecion to device handle == 1 (serial: 6b5dc9ce1d3846893ff756459eb2b7133938bbcb), port 8100
[debug] [iProxy] accepted connection, fd = 4
[debug] [iProxy] waiting for connection
[debug] [iProxy] Number of available devices == 1
[debug] [iProxy] Requesting connecion to device handle == 1 (serial: 6b5dc9ce1d3846893ff756459eb2b7133938bbcb), port 8100
[debug] [iProxy] accepted connection, fd = 4
[debug] [iProxy] waiting for connection
[debug] [iProxy] Number of available devices == 1
[debug] [iProxy] Requesting connecion to device handle == 1 (serial: 6b5dc9ce1d3846893ff756459eb2b7133938bbcb), port 8100
[debug] [iProxy] accepted connection, fd = 4
[debug] [iProxy] waiting for connection
[debug] [iProxy] Number of available devices == 1
[debug] [iProxy] Requesting connecion to device handle == 1 (serial: 6b5dc9ce1d3846893ff756459eb2b7133938bbcb), port 8100
[debug] [iProxy] accepted connection, fd = 4
[debug] [iProxy] waiting for connection
[debug] [iProxy] Number of available devices == 1
[debug] [iProxy] Requesting connecion to device handle == 1 (serial: 6b5dc9ce1d3846893ff756459eb2b7133938bbcb), port 8100
[debug] [iProxy] accepted connection, fd = 4
[debug] [iProxy] waiting for connection
[debug] [iProxy] Number of available devices == 1
[debug] [iProxy] Requesting connecion to device handle == 1 (serial: 6b5dc9ce1d3846893ff756459eb2b7133938bbcb), port 8100
[debug] [iProxy] accepted connection, fd = 4
[debug] [iProxy] waiting for connection
[debug] [iProxy] Number of available devices == 1
[debug] [iProxy] Requesting connecion to device handle == 1 (serial: 6b5dc9ce1d3846893ff756459eb2b7133938bbcb), port 8100
[debug] [iProxy] accepted connection, fd = 4
[debug] [iProxy] waiting for connection
[debug] [iProxy] Number of available devices == 1
[debug] [iProxy] Requesting connecion to device handle == 1 (serial: 6b5dc9ce1d3846893ff756459eb2b7133938bbcb), port 8100
[debug] [iProxy] accepted connection, fd = 4
[debug] [iProxy] waiting for connection
[debug] [iProxy] Number of available devices == 1
[debug] [iProxy] Requesting connecion to device handle == 1 (serial: 6b5dc9ce1d3846893ff756459eb2b7133938bbcb), port 8100
[debug] [iProxy] accepted connection, fd = 4
[debug] [iProxy] waiting for connection
[debug] [iProxy] Number of available devices == 1
[debug] [iProxy] Requesting connecion to device handle == 1 (serial: 6b5dc9ce1d3846893ff756459eb2b7133938bbcb), port 8100
[debug] [iProxy] accepted connection, fd = 4
[debug] [iProxy] waiting for connection
[debug] [iProxy] Number of available devices == 1
[debug] [iProxy] Requesting connecion to device handle == 1 (serial: 6b5dc9ce1d3846893ff756459eb2b7133938bbcb), port 8100
[debug] [iProxy] accepted connection, fd = 4
[debug] [iProxy] waiting for connection
[debug] [iProxy] Number of available devices == 1
[debug] [iProxy] Requesting connecion to device handle == 1 (serial: 6b5dc9ce1

**Comment by felyppers** [comment]
Having the same issue with an iPad Mini 2 - iOS 11.1. Any news on this?

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
