### ISSUE TITLE
The application flashes and closes in a sec

### ISSUE THREAD

**Issue by padmakarsrinivas** [appium/appium#9627]
## The problem

The application flashes and closes in a sec

## Environment

- Appium version (or git revision) that exhibits the issue: 1.7.1
- Desktop OS/version used to run Appium: MAC V10.12.6
- Mobile platform/version under test: iPhone 6 iOS 11.1
- Real device or emulator/simulator: Simulator

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/padmakarsrinivas/122cb4d5158b6b89c51fe349398b05b0

## Code To Reproduce Issue [ Good To Have ]

[Appium] Creating new XCUITestDriver (v2.51.1) session
[Appium] Capabilities:
[Appium]   app: '/Users/srinivasp/Desktop/XXXX.app'
[Appium]   automationName: 'XCUITest'
[Appium]   bundleId: 'net.XXYY.XXXYYY'
[Appium]   deviceName: 'iPhone Simulator'
[Appium]   fullReset: true
[Appium]   platformName: 'iOS'
[Appium]   platformVersion: '11.1'

**Comment by mykola-mokhnach** [comment]
Most likely the app crashes. Do you see the same behaviour if it is executed manually?

**Comment by padmakarsrinivas** [comment]
I am using the .ipa of the same application on the real device and it is working fine.  I was able to run the scripts on iOS 10.3.3 but with 11 i get these problems.

**Comment by mykola-mokhnach** [comment]
the fact that it works on real device does not mean it's going to work on Simulator. Please answer my question above.

**Comment by padmakarsrinivas** [comment]
Let me check once and reply sir

**Comment by padmakarsrinivas** [comment]
App does not launch even when i manual launch. Below are the iOS logs.

[iOSLog] [IOS_SYSLOG_ROW] Nov 13 16:06:12 com.apple.CoreSimulator.SimDevice.84ECC81A-37F1-4230-BDAB-D84140B98136[7772] (UIKitApplication:net.XXXX.XXXYYY[0xad9f][7802][7932]): Program specified by service does not contain any valid architectures for this system.
[iOSLog] [IOS_SYSLOG_ROW] Nov 13 16:06:12 launchd_sim[7772]: BUG in libdispatch client: kevent[mach_recv] monitored resource vanished before the source cancel handler was invoked

**Comment by mykola-mokhnach** [comment]
This means you got a wrong build and should solve it with your developers.
Closed as not an issue.
