### ISSUE TITLE
iOS hybrid App webview pages can't be inspect

### ISSUE THREAD

**Issue by darkmanno6** [appium/appium#9628]
## The problem

iOS hybrid App webview pages can't be inspect, and the iwdp server http://localhost:27753/json returns "[]"

## Environment

* Appium version : `v1.7.1`
* iwdp version: `ios_webkit_debug_proxy 1.8,Built with libimobiledevice v1.2.1, libplist v2.0.0`
* Desktop OS/version used to run Appium:`Mac 10.12.6 `
* Node.js version: `v6.11.4`
* Mobile platform/version under test: `iPhone 6sp iOS 11.0.3`
* Real device or emulator/simulator: ` Real device`
* Appium CLI or Appium.app|exe: `Appium CLI `

## Details
I have tested hybrid app on iOS real device.
I set capabilities to init iwdp automatically :
```java
capabilities.setCapability("startIWDP", true);
```
then I start testing  and navigate to the webview pages，the method `getContextHandles()` returns just 1 context `NATIVE_APP`, and Sending request to: `http://localhost:27753/json` returns `[]`.
I also try the google tools [`remotedebug-ios-webkit-adapter`](https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter) to inspect the webview pages, it also returns no deviceList.

Hope someone can help me.
 
## Link to Appium logs
There's logs link: https://gist.github.com/darkmanno6/2cc3d53a883c4d02f7ade4204ffab2c6

**Comment by mykola-mokhnach** [comment]
I don't think that anything could be done on Appium side if IWDP does not return anything.

**Comment by mykola-mokhnach** [comment]
Perhaps you didn't set the webview as debuggable in your code.

**Comment by darkmanno6** [comment]
@mykola-mokhnach 
How can I set the webview as debuggable in my code?
I have already opened the web-inpector on my device.
