### ISSUE TITLE
Unable to click on floating action "+" button using appium

### ISSUE THREAD

**Issue by prajaktatotre** [appium/appium#9630]
I want to click on floating action "+" button but when tried following code
driver.findElementByXPath("//android.widget.Button[@content-desc='closeadd']").click()

appium doesnot give me any error but not perform the click on "+" button even.
The app I am using is hybrid(Apache cordova,ionic framework). The information in UiAutoamatorViewer is 
Class: android.widget.Button , content-desc: closeadd . I can click on any other tab in my app.

## Environment

*Appium version (or git revision) that exhibits the issue: v1.7.1
* Desktop OS/version used to run Appium: Ubuntu 17.04
* Real device or emulator/simulator: emulator

![dump_3595610209565453360](https://user-images.githubusercontent.com/33454012/32722247-5191c69c-c88f-11e7-8f71-299082b70207.png)

code for reference:
[Jedi.txt](https://github.com/appium/appium/files/1466518/Jedi.txt)
[JediBase.txt](https://github.com/appium/appium/files/1466519/JediBase.txt)

**Comment by KazuCocoa** [comment]
How about the result of `getPageSource`?

You can also find the element with uiautomator. How about the following?

```java
driver.findElementByAndroidUIAutomator(":uiautomator, new UiSelector().className(\"android.widget.Button\").description(\"closeadd\");")
```

**Comment by prajaktatotre** [comment]
Thank you. I tried above code But giving me error in appium log.
[log.txt](https://github.com/appium/appium/files/1469634/log.txt)

**Comment by KazuCocoa** [comment]
Oops, sorry. `:uiautomator, ` was wrong.
The following is correct.

```java
driver.findElementByAndroidUIAutomator("new UiSelector().className(\"android.widget.Button\").description(\"closeadd\");")
```

@prajaktatotre

**Comment by prajaktatotre** [comment]
After trying above code, no error in appium log but not performed click on "+" button.  When I inspect that floating action button ("+") using appium inspector "Could not find the element. Try refreshing." message is displayed. I can inspect same using UiAutomatorViewer.

**Comment by McMagnus** [comment]
I gave my floating plus button the id "Plus"

  android:contentDescription="Plus"

then I can find it using (in Python):

find_element_by_accessibility_id("Plus")

**Comment by mykola-mokhnach** [comment]
Most likely the issue happens because you are not in the webview context. Closed as not an issue.
