### ISSUE TITLE
Unable to start session to get inspector running to view elements

### ISSUE THREAD

**Issue by Katipalli** [appium/appium#9632]
The problem:

Facing error while trying to bring up inspector using start session on Appium desktop.

 Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium:MACOS Sierra 10.12.6
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS 10.3
* Real device or emulator/simulator:Real device
* Appium CLI or Appium.app|exe: Appium desktop 1.2.6

 Details:

Error message in Appium logs: 

[MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.

I have tried rebooting device, but no luck, please help.

**Comment by mykola-mokhnach** [comment]
Error 65 means WDA source are not signed properly and thus the tool cannot be compiled. Make sure you configured it properly and can build and deploy WebDriverAgent manually from Xcode.

Closing as duplicate.
