### ISSUE TITLE
Error when toggling WiFi Android 7.1.1

### ISSUE THREAD

**Issue by glovertd** [appium/appium#9634]
## The problem

Encountered internal error running command: Error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: 404 - undefined

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable): Unknown
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe): Windows7 and Mac Sierra
* Mobile platform/version under test: Android 7.1.1
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: 

## Details
Package.json file dependencies
"dependencies": {
    "appium": "^1.6.5",
    "blink-diff": "^1.0.13",
    "chai": "^4.0.2",
    "cucumber": "^2.3.1",
    "lodash": "^4.17.4",
    "moment": "^2.19.1",
    "node-rest-client": "~3.1.0",
    "request": "^2.81.0",
    "request-promise": "^4.2.1",
    "wdio-appium-service": "^0.2.3",
    "wdio-cucumber-framework": "^0.3.1",
    "wdio-junit-reporter": "^0.3.0",
    "wdio-sauce-service": "^0.4.0",
    "wdio-spec-reporter": "^0.1.0",
    "webdriverio": "^4.8.0",
    "inquirer": "^3.3.0"
  }

## Link to Appium logs
[appium.log](https://github.com/appium/appium/files/1468310/appium.log)

## Code To Reproduce Issue [ Good To Have ]
Using WebDriverIO:
  this.When (/^I toggle wifi$/, () => {

    // toggle wifi on/off
    browser.toggleWiFi ();
  });

**Comment by mykola-mokhnach** [comment]
I assume this endpoint is not implemented for UIA2 driver. The name of the endpoint, which should work, is _setNetworkConnection_ (`/session/:sessionId/network_connection`)

**Comment by glovertd** [comment]
Thanks.
