### ISSUE TITLE
Unable to get text in ViewGroup

### ISSUE THREAD

**Issue by liuxuan30** [appium/appium#9635]
## The problem

Unable to get text in ViewGroup, it seems a bug, becaues using uiautomatorviewer GUI can see the text, however, appium always return ""

but button text can be read

## Environment

* Appium version (or git revision) that exhibits the issue:v1.7.2-beta 
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:

## Details

Unable to get text in ViewGroup, it seems a bug, becaues using uiautomatorviewer GUI can see the text, however, appium always return ""

but button text can be read

For example, Facebook app, using uiautomatorviewer:
![image](https://user-images.githubusercontent.com/4375169/32767004-7be8a588-c94c-11e7-93ae-d6a6d75b4996.png)

but using appium, even print out the entire xml, the same android.view.ViewGroup's text is always ""

><android.view.ViewGroup index="0" text="" class="android.view.ViewGroup" package="com.facebook.katana" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[36,507][930,564]" resource-id="" instance="8" />

**Comment by mykola-mokhnach** [comment]
This is the designed behaviour. We don't calculate the label for the group, since it's not always clear what rules should be applied in order to display it if the group has multiple descendants.

**Comment by liuxuan30** [comment]
is it possible we can have a switch to enable dig deeper? thank you

**Comment by mykola-mokhnach** [comment]
You can always propose a PR if you know how to implement this functionality in the right way
