### ISSUE TITLE
Appium Android, while entering text using sendkeys, ("HSR"), it took 'r' only, appium version -1.7.1 , android - 6.0 lava

### ISSUE THREAD

**Issue by LucySwain** [appium/appium#9636]
Appium Android, while entering text using sendkeys, ("HSR"), it took 'r' only, appium version -1.7.1 , android - 6.0 lava, please help me to resolve this.

- In a substitution i tried this code
WebElement send =driver.findElement(MobileBy.id("com.theporter.android.customerapp:id/autoSuggest_searchET"));
		((JavascriptExecutor)driver).executeAsyncScript("arguments[0].value='HSR'", send);

But it throughs -
org.openqa.selenium.WebDriverException: Method has not yet been implemented

**Comment by mykola-mokhnach** [comment]
Try UIAutomation2 as the backend
