### ISSUE TITLE
Activity Never started issue - Is this permission issue?

### ISSUE THREAD

**Issue by sbabupresidency1** [appium/appium#9638]
## The problem

Getting activity not started error after app launched in the real device. Kindly some one take a look at this.

## Environment

* Appium version :  1.2.6
* Desktop OS/version used to run Appium: Win 10 64bit, 8gb ram, Dell e5430
* Mobile platform/version under test: Android 7.1.1 nubia UI
* Real device or emulator/simulator: Real device, Nubia Z11
* Selenium and Appium combined framework
Connected via USB.

Android Capabilities setup:
 public static AndroidDriver adriver;
	 public static AndroidDriver getDriver() {
	  File appDir = new File(Directory.MOBILE_APPPATH);
	  File app = new File(appDir, Directory.MOBILEAPP_APK_NAME);	  
	  DesiredCapabilities capabilities = new DesiredCapabilities();
	  capabilities.setCapability("platformName", "Android");
	  capabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT,"30" );
	  capabilities.setCapability("deviceName",Directory.MOBILE_DEVICE_NAME);
	  capabilities.setCapability("platformVersion", Directory.MOBILE_DEVICE_VERSION);
	  
	 capabilities.setCapability("appActivity", "com.ifttt.ifttt.intropager.IntroActivity");
	  capabilities.setCapability("appWaitActivity", "com.ifttt.ifttt.intropager.IntroActivity");
	  
	  if(Directory.MOBILE_APP_TYPE.equalsIgnoreCase("Web")) {
	  capabilities.setCapability(CapabilityType.BROWSER_NAME, Directory.MOBILE_WEB_BROWSER_NAME); }
	  else {
	  capabilities.setCapability("app", app.getAbsolutePath());
	 capabilities.setCapability("appPackage", Directory.MOBILE_APK_APPPACKAGE); 
	  }
	  try {
	   adriver = new AndroidDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
	  } catch (MalformedURLException e) {
	   e.printStackTrace();
	  } 
	  return adriver;
	 }

## Details

Getting Activity never started error in the log. App launched but no selenium or appium commands executed. Before that got the error like the below
"org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Error occured while starting App. Original error: Error executing adbExec. Original error: 'Command 'C\:\\Users\\AppData\\Local\\Android\\sdk\\platform-tools\\adb.exe -P 5037 -s 9261d534 shell am start -W -n com.test.test/.intropager.IntroActivity -S' exited with code 1'; Stderr: **'java.lang.SecurityException: Permission Denial:** starting Intent { flg=0x10000000 cmp=com.test.test/.intropager.IntroActivity } from null (pid=6753, uid=2000) not exported from uid 10259"

## Link to Appium logs
https://gist.github.com/sbabupresidency1/3d31e2778e3b2a2f638b523615ac9167

**Comment by mykola-mokhnach** [comment]
Yes it might be. Set _autoGrantPermissions_ capability to true

**Comment by mykola-mokhnach** [comment]
closed because of missing activity

**Comment by sahuparveen** [comment]
> autoGrantPermissions

Thanks:)
