### ISSUE TITLE
Element is not visible on iOS11 with Appium 1.7.2-beta

### ISSUE THREAD

**Issue by ptthuong** [appium/appium#9639]
## The problem 
Element is not visible on iOS11 with Appium 1.7.2-beta

## Environment
* Appium version (or git revision) that exhibits the issue: 1.7.2-beta
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MAC High Sierra v10.13.1
* Node.js version (unless using Appium.app|exe): 6.11.4
* Mobile platform/version under test: iOS11.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:

## Details
I test the same scenario for native app on iOS10.3 and iOS11.1, using XCUITest and XCode9.1, Appium1.7.2-beta.
On iOS10.3, element is enable and visible.
On iOS11.1, element is enable, NOT visible.
Even if I inspect that element by Appium Desktop, the issue can be shown.

## Link to Appium logs
You can see image from Appium Desktop instead.
<img width="546" alt="ios10 3" src="https://user-images.githubusercontent.com/9816732/32790292-a34b8cdc-c990-11e7-8eea-d1bdcb329c1a.png">
![ios11 1](https://user-images.githubusercontent.com/9816732/32790294-a37ddcaa-c990-11e7-8bbd-8a3669e131d5.png)

**Comment by mykola-mokhnach** [comment]
Please report to https://github.com/facebook/WebDriverAgent/issues
