### ISSUE TITLE
Appium1.7.1 does not work with DEVELOPER_DIR.

### ISSUE THREAD

**Issue by JoannaCode** [appium/appium#9640]
## The problem

I have a question about new Appium1.7.1. I have 3 Xcode in my remote VM. And I used DEVELOPER_DIR =/Applications/Xcode8.3 for Appium 1.6.4 which works fine. Now I used 1.7.1. It does not work when I set DEVELOPER_DIR (xcodebuild exit with code 1), but it works fine if I used xcode-select.
The problem is that I can not use 'sudo' to set xcode-select becuase of CI.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable): 1.6.4
* Desktop OS/version used to run Appium:10.12.6
* Node.js version (unless using Appium.app|exe):7.9
* Mobile platform/version under test: IOS
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

xcodebuild exit with code 1.

## Code To Reproduce Issue [ Good To Have ]

1. Install 2 or 3 Xcodes version
2. Run Appium with DEVELOPER_DIR=*** instead of 'sudo xcode-select=***'

**Comment by imurchie** [comment]
Can you try Appium 1.7.2-beta? I don't know why it would have worked on earlier versions, but provision `DEVELOPER_DIR` was added recently (see https://github.com/appium/appium-xcuitest-driver/pull/564).

**Comment by JoannaCode** [comment]
Works! Thanks!
