### ISSUE TITLE
Get Background color from a Native App

### ISSUE THREAD

**Issue by eduarte** [appium/appium#9644]
## The problem
I am trying to automate an app that draw over other app showing a message when a precondition happens.
For example:
If I got a call from a suspect number it should block the call and display a message with an specific color in the background.

I need to validate if the background color is the expected inf the scenario. 

I want to highlight that the app is Native not hybrid nor web so I wont' be able to use the get the css value of that item 

## Environment
* Appium version 1.7.1
* Desktop OS/version used to run Appium: Windows
* Node.js version (unless using Appium.app|exe): 6.11.1
* Mobile platform/version under test: Android
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: Appium CLI

**Comment by mykola-mokhnach** [comment]
The only possibility would be to use screenshots comparison.
