### ISSUE TITLE
unlock on android fails with UIAutomator2 and appium1.7.1

### ISSUE THREAD

**Issue by dmshantanu** [appium/appium#9646]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable): 1.6.5
* Desktop OS/version used to run Appium: MAC OS Sierra 10.12.6
* Node.js version (unless using Appium.app|exe): v8.7.0
* Mobile platform/version under test:7.x
* Real device or emulator/simulator:Real device
* Appium CLI or Appium.app|exe: CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/dmshantanu/a0a71478756d047e03fb38f113a5f8dc
.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by dmshantanu** [comment]
I had to uninstall unlock and appium settings and unlock apps from the phone to recover from this.
Appium reinstalls the apps when next run is started.

**Comment by mykola-mokhnach** [comment]
Set **skipUnlock** capability to _true_

**Comment by dmshantanu** [comment]
@mykola-mokhnach This worked when phone is already unlocked. But now when android phone is locked appium does not automatically unlock it and my test run fails.

**Comment by mykola-mokhnach** [comment]
You can always push a PR for the unlock application to make it work for your phone. It's [open source](https://github.com/appium/unlock_apk).

**Comment by dmshantanu** [comment]
@mykola-mokhnach  Did anything change in the way appium 1.7.1 ? My phone was getting unlocked properly untill 1.6.5  I upgraded to 1.7.1 and this problem started happening.

**Comment by dmshantanu** [comment]
I got around this by going to "Lock Screen and Security" ---> "Screen lock type" set to None.
So now my android device is always unlocked

**Comment by tfcardoso** [comment]
@dmshantanu It may still fail if you let your device go to sleep. For now a quick fix is before establishing a driver session run the following command:
 
    adb shell input keyevent 224

https://developer.android.com/reference/android/view/KeyEvent.html#KEYCODE_WAKEUP

Note: This command will fail on KitKat devices. Use it for Android 7 and above (those are the ones having the issue)

**Comment by dmshantanu** [comment]
@tfcardoso My appium servers are remote. i.e Automation code is running on a separate machine than where appium server is running. Devices are connected to the machine where appium server is running.

**Comment by tfcardoso** [comment]
Then the only solution for you currently its enabling option "Stay Awake" under developer options until there is a fix. This will "kill" you battery way quicker.

You can make a PR with the KEYCODE_WAKEUP method or just change your local copy of appium to do it before establishing a session .
