### ISSUE TITLE
Android test on real device too slow - 3s delay when clicking an element

### ISSUE THREAD

**Issue by horsefeatherses** [appium/appium#9647]
## The problem

I have just started a project with Appium. It runs well, but the problem is that there's a delay whenever an element is clicked. This makes the test that I wrote too slow. It approximately takes 3-4s to click an element.

## Environment

* Appium version (or git revision) that exhibits the issue: 5.0.2
* Last Appium version that did not exhibit the issue (if applicable): tried 4.1.2 as well, the issue was the same
* Desktop OS/version used to run Appium: Windows 10 Enterprise
* Node.js version (unless using Appium.app|exe): v6.11.4
* Mobile platform/version under test: Android 6.0.1
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: 1.4.16.1

## Link to Appium logs

https://gist.github.com/horsefeatherses/ecccb039e5d5531a6bcb6e3b5ae32468

## Code To Reproduce Issue [ Good To Have ]

`DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability("automationName", "uiautomator2");
        capabilities.setCapability("no", true);
        capabilities.setCapability("newCommandTimeout", 100000);
        capabilities.setCapability("noReset", true);
        capabilities.setCapability(CapabilityType.PLATFORM, "Android");
        capabilities.setCapability(CapabilityType.VERSION, "6.0.1");
        capabilities.setCapability("deviceName", "device");
        capabilities.setCapability("appPackage", "com.sec.android.app.popupcalculator");
        capabilities.setCapability("appActivity", "com.sec.android.app.popupcalculator.Calculator");
        capabilities.setCapability("noRest", true);
        driver = new AndroidDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);`

`@Test
    public void set() {
        WebElement one = driver.findElementById("com.sec.android.app.popupcalculator:id/bt_01");
        WebElement two = driver.findElementById("com.sec.android.app.popupcalculator:id/bt_02");
        driver.findElementById("com.sec.android.app.popupcalculator:id/bt_09").click();
        two.click();
        one.click();`

Tried it also using the sample code you provided, but the issue is the same. There's that delay when clicking, which makes the test super slow.

Tried it also without capabilities.setCapability("automationName", "uiautomator2");

**Comment by tfcardoso** [comment]
You should update your appium (https://github.com/appium/appium/releases). Maybe you using old GUI, so if you want to keep using GUI, use appium desktop (https://github.com/appium/appium-desktop/releases)

**Comment by mykola-mokhnach** [comment]
Yes, Appium version 1.4 (like 1.5 and even 1.6) is old and outdated. closed as not an issue.

**Comment by horsefeatherses** [comment]
Aha, didn't realise that Appium would be the problem. Thanks!
