### ISSUE TITLE
Appium v1.7.1 Error parsing launchActivity from android manifest (launch activity is using activity-alias) 

### ISSUE THREAD

**Issue by dc-ikozlov** [appium/appium#9648]
## The problem

Test run fails while parsing android app manifest.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable): - 
* Desktop OS/version used to run Appium: macOS 10.12.6 
* Node.js version (unless using Appium.app|exe): v6.8.1
* Mobile platform/version under test: Android 4.4.2, Android 5.0
* Real device or emulator/simulator: real devices
* Appium CLI or Appium.app|exe: CLI

## Details

The issue first appeared when activity-alias for launch activity was used. It looks like this:
```
        <activity-alias android:name="Launcher"
            android:targetActivity="com.deliveryclub.businesslayer.activities.SplashActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity-alias>
```

## Link to Appium logs
https://gist.github.com/dc-ikozlov/3f8e3574a61b676214c5519f92d542fa

**Comment by mykola-mokhnach** [comment]
You can set _appActivity_ name manually in capabilities

**Comment by dc-ikozlov** [comment]
@mykola-mokhnach 
Yep, it works fine with explicit appActivity. Just thought you might want to improve parsing mechanism in future builds or something.

**Comment by mykola-mokhnach** [comment]
You can always push a PR yourself

**Comment by imurchie** [comment]
Parsing is done with Android's tools (`aapt` [specifically](https://github.com/appium/appium-adb/blob/ac2eaddaeaaca154804e1a18427ed3a9c62ee78a/lib/tools/android-manifest.js#L70-L106)) so there is not much we can do if they can't figure it out.

**Comment by saikrishna321** [comment]
Closing as per issac comments.
