### ISSUE TITLE
Appium 1.7.1/Xcode 9.1 launches multiple simulators and binds to wrong one

### ISSUE THREAD

**Issue by jarmy** [appium/appium#9651]
## The problem

When running the same test against a different simulator, both the newly targeted simulator and previous version are launched and Appium binds to the wrong one. After running a test on a iPhone X/11.1 simulator, 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable): 1.6.5
* Desktop OS/version used to run Appium: N/A
* Node.js version (unless using Appium.app|exe): v6.11.0
* Mobile platform/version under test: iOS 11.1 & macOS Sierra v10.12.6
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: CLI

## Details
1. Launch test on iPhone X + OS 11.1 and wait to finish
2. Launch same test on iPhone 8 + iOS 11.1
3. Set up runs "killall -9 Simulator" & "killall \"com.apple.CoreSimulator.CoreSimulatorService\", successfully killing the first simulator
4. When the iPhone 8 client connects to the server, iPhone X is also launched. Appium appears to bind to iPhone X rather than iPhone 8 while WDA doesn't appear to be installed on iPhone 8.   

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/jarmy/5206bef34bd7dc8d7fc7d16fcc19a5d3

## Code To Reproduce Issue [ Good To Have ]
I don't think this is a coding issue but a tooling or capabilities issue.

**Comment by imurchie** [comment]
Yes, the new multiple simulator thing from Apple makes it fun. The launching of the old simulator is Xcode. We're still working out the issues with that. But in the meantime, you will need, when switching sims, to use the `wdaLocalPort` capability to change what port to talk through. Or use `useNewWDA` to force the destruction of the old running server on the device.

**Comment by mykola-mokhnach** [comment]
+1 for setting unique `wdaLocalPort` for each simulator. Closed as not an issue.

**Comment by jarmy** [comment]
Ok, good to know. I'll implement `wdaLocalPort` logic on our side

**Comment by mykola-mokhnach** [comment]
We've also changed the log message in the recent beta to make it more clear: https://github.com/appium/appium-xcuitest-driver/pull/560/files
