### ISSUE TITLE
Appium crashes/hangs on re-opening safari on iOS

### ISSUE THREAD

**Issue by ballwood** [appium/appium#9652]
## The problem

Appium crashes/hangs on re-opening safari on iOS

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: MacOSX
* Node.js version (unless using Appium.app|exe): N/A
* Mobile platform/version under test: iOS 11
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: Appium.app
* Using webdriver.io 4.6.2 to control appium

## Details

Using appium with the iOS simulator with about 7 scenarios and around 60 tests. After each scenario safari on iOS is closed down and then reopened with a new url. What seems to happen is randomly safari crashes when this operation happens and then then appium fails to start a new instance of safari, leaving the tests hanging. 

Sometimes we don't get a crash and all the tests pass. But most of the time one of the scenarios this happens and fails.

## Link to Appium logs

iOS logs also in here

[https://gist.github.com/ballwood/c97eff03654318b3ac819ff6d70daf4d](https://gist.github.com/ballwood/c97eff03654318b3ac819ff6d70daf4d)

## Code To Reproduce Issue [ Good To Have ]

Unfortunately I can't provide this as my employer wouldn't want it being posted on the internet.

**Comment by mykola-mokhnach** [comment]
Please attach server logs

**Comment by ballwood** [comment]
@mykola-mokhnach in the gist here https://gist.github.com/ballwood/c97eff03654318b3ac819ff6d70daf4d

**Comment by mykola-mokhnach** [comment]
It would be good to see the full log, especially the part before Safari crashes and after it when Appium tries to start a new session and fails.

**Comment by ballwood** [comment]
@mykola-mokhnach I don't know if it crashes or closes and can't be reopened. Appium seems to just loop on the last commands indefinitely whilst wdio sits there and then eventually exits. The error seems to be coming up a lot as well.

Encountered internal error running command: Error: Error while executing atom: appIdKey

**Comment by saikrishna321** [comment]
@ballwood does this issue still exists ?

**Comment by ballwood** [comment]
@saikrishna321 I narrowed it down to it occurring when we were getting 'A problem occurred with this webpage so it was reloaded' so maybe appium loses track of the browser session?

**Comment by mykola-mokhnach** [comment]
Closed as inactive. I would assume it is a third party issue
