### ISSUE TITLE
Touchaction Press-moveTo-wait-release gesture is not implemented on IOS platform

### ISSUE THREAD

**Issue by xlving** [appium/appium#9655]
## The problem
when trying to run below java code , the exception throw out;
TouchAction touchAction = new TouchAction(driver);
touchAction.press(x,starty).moveTo(x-x, endy-starty).waitAction(Duration.ofMillis(500)).release().perform;

Exception:
org.openqa.selenium.WebDriverException: Support for press(options={"x":187,"y":500})-moveTo(options={"x":0,"y":-333})-wait(options={"ms":3000})-release(options={}) gesture is not implemented. Try to use "mobile: *" interface to workaround the issue. Only these gestures are supported:
doubleTap: doubletap
tap(options={"count":2})
tap: tap
tap-release
press-release
longPress: longpress
longpress-release
press-wait-release
drag: press-wait-moveTo-release
longpress-moveTo-release
scroll: press-moveTo-release
(WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T15:28:36.4Z'
System info: host: 'xiongleideMac.local', ip: 'fe80:0:0:0:14b8:fdbb:b57c:8d22%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_40'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities [{networkConnectionEnabled=false, bundleId=com.quarkfinance.qone, databaseEnabled=false, deviceName=iPhone 6s, platform=MAC, newCommandTimeout=300, platformVersion=11.1, webStorageEnabled=false, locationContextEnabled=false, automationName=XCuiTest, browserName=, takesScreenshot=true, javascriptEnabled=true, udid=c7fef4614d38f2ddedd8e195278f27f62777f472, platformName=MAC}]
Session ID: 85bc92bf-5cb0-404e-a2d5-d8e53038e6ba

## Environment

* Appium version :Server 1.7.1 , java client 5.0.4
* Last Appium version that did not exhibit the issue (if applicable): server 1.6.4 , java client 5.0.0-BETA5
* Desktop OS/version used to run Appium:MacOS 10.12.6
* Node.js version (unless using Appium.app|exe):  9.2.0
* Mobile platform/version under test: IOS 11.1.1
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe:

Hope someone could help me. I have tried many ways ,but still cannot swipe the screen.

**Comment by mykola-mokhnach** [comment]
1. Update Appium to 1.7.1
2. Use press-wait-moveTo-release instead

**Comment by yizhixiaoxiaogou** [comment]
I  want    press-wait-moveTo-moveTo-moveTo-moveTo-release .  the apppium 1.7.1 support?
