### ISSUE TITLE
Japanese text not sent properly with sendKeys [randomly]

### ISSUE THREAD

**Issue by tfcardoso** [appium/appium#9656]
## The problem

Hi,

I have tests where I need to send text in japonese. For that I use Appium Keyboard. Most of the times everything works great, but sometimes instead of sending proper text, it sends other ser of characters.

In this example that I'm posting here it should have sent こんにちは and ended up sending &MFMwkzBrMGEwbw-

## Environment

* Appium version (or git revision) that exhibits the issue: v1.7.1
* Desktop OS/version used to run Appium: OS 10.12.6
* Mobile platform/version under test: Android 5 Real device
* Java Client: v5.0.4

## Details

From the log lines:
2017-11-16 20:52:16:022 - [debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Sending Unicode text to element: こんにちは
2017-11-16 20:52:16:024 - [debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Encoded text: &MFMwkzBrMGEwbw-

We see that it sent the "encoded text" instead of the suppose text.

I'm using automator on devices below Android 6 and I know the advice will be to use automator2. Wont that cause me issues with KitKat for example (that I still need to support)?

## Appium logs

https://gist.github.com/tfcardoso/d7f81b8555080800926a6851798bc964

**Comment by imurchie** [comment]
The "encoded text" is correct. It seems that the keyboard is not set on the device. Appium encodes the text as an ASCII-based string so it can get through Android, and then on the device decodes it to the correct value. If you look at a successful run you'll see the same:
```
dbug AndroidBootstrap [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:setText","params":{"elementId":"60","text":"परीक्षा-परीक्षण","replace":false,"unicodeKeyboard":true}}
dbug AndroidBootstrap [BOOTSTRAP LOG] [debug] Got command of type ACTION
dbug AndroidBootstrap [BOOTSTRAP LOG] [debug] Got command action: setText
dbug AndroidBootstrap [BOOTSTRAP LOG] [debug] Using element passed in: 60
dbug AndroidBootstrap [BOOTSTRAP LOG] [debug] Attempting to clear using UiObject.clearText().
dbug AndroidBootstrap [BOOTSTRAP LOG] [debug] Sending Unicode text to element: परीक्षा-परीक्षण
dbug AndroidBootstrap [BOOTSTRAP LOG] [debug] Encoded text: &CSoJMAlACRUJTQk3CT4--&CSoJMAlACRUJTQk3CSM-
dbug AndroidBootstrap [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":true}
dbug AndroidBootstrap Received command result from bootstrap
```

Do you have the full logs? The configuration of the system is in session start, so there is nothing diagnostic in the snippet provided.

**Comment by tfcardoso** [comment]
I have... that's the entire run :) as backup device, so 93k lines

https://gist.github.com/tfcardoso/49c6605a1da3fd9d590402d930d27b4e

During that run, many similar texts were sent successfully. As I mentioned this happens randomly and very rarely, but its enough to break validations.

Thanks

**Comment by tfcardoso** [comment]
> Wont that cause me issues with KitKat for example (that I still need to support)?

Like I suspected, the KitKat doesn't send texts properly with automator2.

**Comment by tfcardoso** [comment]
@imurchie I made some tests with https://github.com/senzhk/ADBKeyBoard and I think it will work for KitKat to send unicode symbols.

Since no fix will probably be done in uiautomator I think you can close.

Thanks
