### ISSUE TITLE
Android - Control basic bluetooth settings(ON/OFF) using Java code.

### ISSUE THREAD

**Issue by MaddySinghMaddy** [appium/appium#9658]
## The problem

Is it possible to control bluetooth setting(ON/OFF) on real Android device using Appium Java code?

**Comment by mykola-mokhnach** [comment]
No, there is no such possibility for now. However, you could create a PR and add it

**Comment by MaddySinghMaddy** [comment]
Does it apply to Wifi(On/Off) settings as well?

**Comment by mykola-mokhnach** [comment]
No, WiFi state can be controlled

**Comment by MaddySinghMaddy** [comment]
Thanks. Can you please provide java code for the wifi(On/Off) settings?
