### ISSUE TITLE
Launching apps with options 

### ISSUE THREAD

**Issue by ali-mirza786** [appium/appium#9659]
## The problem

I have an .ipa file that I’m trying to launch via the xcuitest driver. I want to launch the app with certain arguments passed upon launch. I have an environmental variable which is present in the xcode project called “GE_VERBOSE 1”

When this environmental variable is activated when running the app in **xcode**, it disables an overlay screen that pops up when the app launches. 

How can I do the same with appium? How can I pass this argument on launch using the inspector session or command line (xcuitest)? I tried using the “processArguments” = GE_VERBOSE 1 in the desired capabilities but it didn’t like the format I gave it.

The goal is to have a way to launch the app for automated testing by successfully bypassing the obstructive overlay screen with launches when the app is installed freshly. 

## Environment

* Appium version (or git revision) that exhibits the issue: v1.6.5
* Desktop OS/version used to run Appium: MacOS 10.12.6
* Mobile platform/version under test: ios 10.3
* Real device or emulator/simulator: iPhone 6

## Details
Need a way to launch an app with certain options.

**Comment by imurchie** [comment]
Process arguments (the `processArguments` capability) get sent in as an object, with the properties `args` and/or `env`. `args` is an array of arguments to be passed to the app. `env` is an object with key-value pairs to set the environment.

In the abstract it will look something like
```json
{"args": ["a", "b", "c"], "env": { "a": "b", "c": "d" }}
```
You should try:
```json
{"env": {"GE_VERBOSE": 1}}
```

**Comment by mykola-mokhnach** [comment]
```java
        final List<String> processArgs = new ArrayList<>(Arrays.asList(
                "--debug-log-network"
                , "-com.apple.CoreData.ConcurrencyDebug", "1"
        ));
        final Map<String, Object> processEnv = new HashMap<>();
        processEnv.put("key", "value");
        final JSONObject argsValue = new JSONObject();
        argsValue.put("args", processArgs);
        argsValue.put("env", processEnv);
        capabilities.setCapability("processArguments", argsValue.toString());
```

**Comment by fdPoornima** [comment]
@mykola-mokhnach @imurchie  : is there a similar solution for android apps as well which enables passing arguments

**Comment by Sridhar2127** [comment]
Start activity would help in android
