### ISSUE TITLE
Appium 1.7.1 can not get the value of attribute "content-desc" in android

### ISSUE THREAD

**Issue by dmshantanu** [appium/appium#9660]
<android.view.ViewGroup index="6" text="" class="android.view.ViewGroup" content-desc="Nov. 17, 2017 1:51 PM" checkable="false" checked="false" clickable="false" enabled="true" focusable="true" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[48,1176][1020,1223]" resource-id="" instance="21">

For above element following command works with appium 1.6.5 and returns the value of content-desc. But with appium 1.7.1 it returns an empty string
driver.findElemenByXpath(<xpath>).getAttribute("name")

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable): 1.6.5
* Desktop OS/version used to run Appium:  MAC OS 10.12.6
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: 7.0
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: CLI

 Following is the apium log excerpt for above command

Calling AppiumDriver.findElement() with args: ["xpath","//android.widget.ScrollView//android.widget.TextView[contains(@text,'AM') or contains(@text,'PM')]/..","f6c8b26c-ed1c-45b9-a523-4117a966a3ee"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [BaseDriver] Waiting up to 5000 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8200/wd/hub/session/1d794992-6189-4308-b1db-597b79dcdc06/element] with body: {"strategy":"xpath","selector":"//android.widget.ScrollView//android.widget.TextView[contains(@text,'AM') or contains(@text,'PM')]/..","context":"","multiple":false}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"1d794992-6189-4308-b1db-597b79dcdc06","status":0,"value":{"ELEMENT":"f150cc3e-1646-4c5f-8978-f02d8f2f5f99"}}
[debug] [MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"f150cc3e-1646-4c5f-8978-f02d8f2f5f99"}
[HTTP] <-- POST /wd/hub/session/f6c8b26c-ed1c-45b9-a523-4117a966a3ee/element 200 134 ms - 122 
[HTTP] --> GET /wd/hub/session/f6c8b26c-ed1c-45b9-a523-4117a966a3ee/element/f150cc3e-1646-4c5f-8978-f02d8f2f5f99/attribute/name {}
[debug] [MJSONWP] Calling AppiumDriver.getAttribute() with args: ["name","f150cc3e-1646-4c5f-8978-f02d8f2f5f99","f6c8b26c-ed1c-45b9-a523-4117a966a3ee"]
[debug] [JSONWP Proxy] Proxying [GET /element/f150cc3e-1646-4c5f-8978-f02d8f2f5f99/attribute/name] to [GET http://localhost:8200/wd/hub/session/1d794992-6189-4308-b1db-597b79dcdc06/element/f150cc3e-1646-4c5f-8978-f02d8f2f5f99/attribute/name] with body: {}
[debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"1d794992-6189-4308-b1db-597b79dcdc06\",\"status\":0,\"value\":\"\"}"
[debug] [MJSONWP] Responding to client with driver.getAttribute() result: ""

**Comment by dmshantanu** [comment]
@imurchie   Can you help please?

**Comment by mykola-mokhnach** [comment]
Why do you search by text in your xpath and then try to get the `name` attribute?

**Comment by dmshantanu** [comment]
Here is the actual xpath --> "//android.widget.ScrollView//android.widget.TextView[contains(@text,'AM') or contains(@text,'PM')]/.."

I am searching for a parent element of an element whose @text contains either AM or PM.
The content-desc (@name) is dynamically generated and hence I dont know its value. 
I am trying to get its value using @name attribute

**Comment by mykola-mokhnach** [comment]
Perhaps its not set at that time when the element is found. Try to print the source immediately after the match is found to make sure that correct element is matched and its content description is up to date.

**Comment by dmshantanu** [comment]
I double checked. The element is there and has the correct value set. But when I try to get that value using .getAttribute("name") I get an empty string "".  This happening with appium 1.7.1

Same command works correctly with appium 1.6.5 returning the value of content-desc

**Comment by tfcardoso** [comment]
proper command is 
  
     element.getAttribute("contentDescription")

The getAttribute("name") worked in uiautomator only, and you probably using uiautomator2 to automate that Android 7.

You could have searched in forum:
http://discuss.appium.io/t/get-value-of-content-desc/2486/13

**Comment by dmshantanu** [comment]
Thanks for providing that @tfcardoso ! Not sure how I missed that.

**Comment by jpita** [comment]
Thanks @tfcardoso just arrived here after losing almost 1h fighting with `getAttribute("content-desc")` 😭 

I was going to ask 

> is it possible to change this? because it is misleading (since both onuiautomatorviewer and appium-desktop the attribute is content-desc)

but then I saw this is only for android 7+ ...
Is there any workaround for this?
Mainly so it doesn't happen to new users....

Thanks!
