### ISSUE TITLE
Unable to find the UDID of connected device using Java

### ISSUE THREAD

**Issue by pavanbachu0604** [appium/appium#9661]
## The problem
Unable to find the UDID of connected device  using java, please find the `code[](https://gist.github.com/pavanbachu0604/0e3d9f6a06fe455bea403e9f04cda2db)` , I am able to pull the UDID using the command  '"system_profiler SPUSBDataType | sed -n -E -e '/(iPhone|iPad|iPod)/"   + ",/Serial/s/ *Serial Number: *(.+)/\\1/p'"', but not able to pull the UDID using "idevice_id -l"

but while appium is running it internally uses idevice_id -l to list the device UDID

**Comment by mykola-mokhnach** [comment]
Perhaps you libmobiledevice insyalltion is out of date. Closed as non server-related.

**Comment by pavanbachu0604** [comment]
@mykola-mokhnach I have installed  brew install -g libimobiledevice --HEAD, this style
