### ISSUE TITLE
Issue with  https://github.com/saikrishna321/PageObjectPatternAppium

### ISSUE THREAD

**Issue by PratapSingh09** [appium/appium#9663]
This framework [(https://github.com/saikrishna321/PageObjectPatternAppium)] does not work on windows 7 right??
iOS and Android both are not running parallelly on Windows 7 with below configuration:
appium version: 1.7.1
java: 1.8

Please let me know,How to run this framework and on which platform/OS

**Comment by mykola-mokhnach** [comment]
Please report the issue to the appropriate repository. Closed as server-unrelated.
