### ISSUE TITLE
Appium inspector 1.2.6 cannot refresh after clicking alertdialog

### ISSUE THREAD

**Issue by JimClermonts** [appium/appium#9667]
## The problem

Consider below code:

```
class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        show(this, "someTitle", "testing")
    }

    fun show(context: Context, title: String, message: String) {
        AlertDialog.Builder(context, R.style.Theme_AppCompat_DayNight_Dialog)
                .setTitle(title)
                .setMessage(message)
                .setPositiveButton(android.R.string.ok, { dialog, _ ->
                    dialog.dismiss()
                })
                .setCancelable(false)
                .show()
    }
}
```

When launching Appium Inspector, and pressing refresh, everything works:

![1](https://user-images.githubusercontent.com/1337452/33008374-23d98296-cdd3-11e7-9fd0-9b65d0f8eacc.png)

After clicking "OK" and pressing refresh, Appium cannot refresh the page anymore and keeps loading. If I would execute tests it would say "can not find element with ID x":

![3](https://user-images.githubusercontent.com/1337452/33008381-2c77cc64-cdd3-11e7-90f2-61c26b6bb246.png)

## Environment

* Appium version 1.2.6
* Desktop OS/version used to run Appium: Mac OS X
* Real device or emulator/simulator: Android Nexus 5X API 26

## Link to Appium logs
As you can see in the logs, the getPageSource() simply hangs and doesn't return the page anymore.
https://gist.github.com/JimClermonts/77500ecdd9fdeb35a7c913601c657891

**Comment by mykola-mokhnach** [comment]
This is known bug in UIAutomation compatibility with newer Android versions. Switch to UIAutomator2.
