### ISSUE TITLE
Can't get page sources using "useJSONSource": "true" on iOS 10

### ISSUE THREAD

**Issue by shynkevich-alex** [appium/appium#9668]
## Environment

* 1.7.2-beta
* iOS 10.3
* Real device iPad
* xCode 9.1

## Appium logs

`[debug] [JSONWP Proxy] Proxying [GET /source?format=json] to [GET http://localhost:8100/session/1A33D969-E53D-4CE9-9C3D-06D8B76FE806/source?format=json] with no body
[HTTP] <-- GET /wd/hub/session/96e52a87-47ef-4153-adcb-e4acfa23fae6/source - - ms - -
[HTTP] --> GET /wd/hub/session/96e52a87-47ef-4153-adcb-e4acfa23fae6/source {}
[debug] [MJSONWP] Calling AppiumDriver.getPageSource() with args: ["96e52a87-47ef-4153-adcb-e4acfa23fae6"]
[debug] [XCUITest] Executing command 'getPageSource'
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"Invalid number value (infinite) in JSON write\\n\\n(\\n\\t0   CoreFoundation                      0x000000018af2eff8 <redacted> + 148\\n\\t1   libobjc.A.dylib                     0x0000000189990538 objc_exception_throw + 56\\n\\t2   CoreFoundation                      0x000000018af2ef28 <redacted> + 0\\n\\t3   Foundation                          0x000000018baab514 <redacted> + 404\\n\\t4   Foundation                          0x000000018baaa080 <redacted> + 480\\n\\t5   Foundation                          0x000000018baac29c <redacted> + 236\\n\\t6   CoreFoundation                      0x000000018ae76b68 <redacted> + 104\\n\\t7   CoreFoundation                      0x000000018ae65290 <redacted> + 176\\n\\t8   Foundation                          0x000000018baaba08 <redacted> + 336\\n\\t9   Foundation                          0x000000018baaa028 <redacted> + 392\\n\\t10  Foundation                          0x000000018baac29c <redacted> + 236\\n\\t11  CoreFoundation                      0x000...
[debug] [JSONWP Proxy] Proxying [GET /source?format=json] to [GET http://localhost:8100/session/1A33D969-E53D-4CE9-9C3D-06D8B76FE806/source?format=json] with no body
[MJSONWP] Encountered internal error running command: Error: An unknown server-side error occurred while processing the command.
    at JWProxy.command$ (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:176:15)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
`

**Comment by mykola-mokhnach** [comment]
Please report to https://github.com/facebook/WebDriverAgent/issues

**Comment by shynkevich-alex** [comment]
I moved it to https://github.com/facebook/WebDriverAgent/issues/797
