### ISSUE TITLE
Ios 11.0.3 -Music app - Airplay selection popup

### ISSUE THREAD

**Issue by maulik-shah-einfochips** [appium/appium#9669]
I am not able to find page source or popup handling of Music App using Appium for ios 11.0.3

steps to reproduce

Open music app
Select song
Click on Select airplay device
Challenge:

I am not able capture page source of element of popup
Approach:
tried to capture page source but popup source not listed.

Please help.

**Comment by mykola-mokhnach** [comment]
If this popup is initiated by some app/service, which is different from your application under test then it is not going to be visible. This is XCTest limitation and it can be potentially workarounded by switching application under test, which is not currently supported by WebDriverAgent.
