### ISSUE TITLE
[XCUITest] Failed to create WDA session. Retrying...

### ISSUE THREAD

**Issue by zusmani-mbo-com** [appium/appium#9671]
Hi All, 
I am getting similar error when trying to launch the app, even though I have not specified the bundle ID.I am running this on bitrise mac. box
Also , I have attached the ios logs 

https://gist.github.com/zusmani-mbo-com/3dd2f3069ecfa0137bdbbc02f7fbedae
I have also looked at this issue, can not get it working still 
https://github.com/appium/appium/issues/8373

* Appium version 1.7.1
* Desktop OS IOS:
* Mobile platform/version under test:
* emulator/simulator:
* Appium CLI :

**Comment by mykola-mokhnach** [comment]
> [debug] [JSONWP Proxy] Got response with status 200: {"value":"Failed to launch com.mbopartners.MBOMobile.Debug application","sessionId":"3E4BD114-BC20-41B3-8B6B-05984BF5A938","status":13}

Are you able to execute the app manually on the device?

**Comment by zusmani-mbo-com** [comment]
I can run the app manually

**Comment by mykola-mokhnach** [comment]
> [iOSLog] [IOS_SYSLOG_ROW] Nov 20 09:48:08 controlosxprodc2bhostondemandosx135 assertiond[1593]: Unable to get pid for 'UIKitApplication:com.mbopartners.MBOMobile.Debug[0x3bb9][1593]': No such process (3)

It's something inside WebDriverAgent. Please report directly to https://github.com/facebook/WebDriverAgent/issues
