### ISSUE TITLE
 Testing mobile app and passing test data between test automation and test app

### ISSUE THREAD

**Issue by asoneji** [appium/appium#9672]
## The problem

I have mobile test app and Appium test automation. I want to pass data between the test automation and test app for test validation how can I do it?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MacOS 10.13.1
* Node.js version (unless using Appium.app|exe): 6.12.0
* Mobile platform/version under test: iOS and Android
* Real device or emulator/simulator: Both
* Appium CLI or Appium.app|exe:

## Details

I want send some data between the test automation and test app. So If I need to provide some dynamic value to test app from test automation how can I do this?

**Comment by mykola-mokhnach** [comment]
You can pass command line arguments and environment variables to the application under test. Also, in Android it is possible to push a file to the device. See https://github.com/appium/appium/issues/9659, for example.

**Comment by asoneji** [comment]
How can I use command line arguments and environment variables to the application under test? Also of I want it some fields that keep changing during the test the command line arguments and environment variables would not work.

We were using pushFile for iOS (Simulator) and Android (Emulator) but this does not work on iOS real device so we are looking for an alternative.

Can I make a feature request to support pushFile for iOS real device? (as this will fix the issue for us)

**Comment by mykola-mokhnach** [comment]
There is no way to push a file on iOS real device, because Apple does not provide any APIs to make it possible. You can try to put your data into some storage, which is accessible within your local network and get it from there.

**Comment by asoneji** [comment]
We are putting the data on storage and accessing from it but we need to some unique id so we can track different test run/test cases.

https://github.com/libimobiledevice - What about integrating something like this to pushFile to iOS device? Pushing in the media folder or other folder where iOS allows sending files.

If we use processArguments on capability how do we access that data from the iOS app and Android App?

**Comment by mykola-mokhnach** [comment]
We are already using libimobiledevice there. Regarding the access to the file system - we can consider support of https://github.com/libimobiledevice/ifuse, however it might not be always stable, especially after Apple releases a new iOS version. You could create a feature request though.

**Comment by asoneji** [comment]
I would like to make a feature request for considering  support of https://github.com/libimobiledevice/ifuse to pushFile to iOS real device

**Comment by asoneji** [comment]
If we use processArguments on capability how do we access that data from the iOS app and Android App?

**Comment by mykola-mokhnach** [comment]
> I would like to make a feature request for considering support of https://github.com/libimobiledevice/ifuse to pushFile to iOS real device

I've checked this repository and I see the recent changes have been done more than year ago, which means that current iOS versions (10 and above) are not supported. You are welcome to propose other alternatives.

**Comment by mykola-mokhnach** [comment]
> If we use processArguments on capability how do we access that data from the iOS app and Android App?

Please use Appium forum to ask questions. This is the place for server issues

**Comment by asoneji** [comment]
We have used https://github.com/libimobiledevice/ifuse manually to pushFile to iOS device with iOS 10. It still works.

**Comment by asoneji** [comment]
https://discuss.appium.io/t/how-to-access-args-on-mobile-that-were-passed-in-processarguments/19750 - posted the question here on the forum.

**Comment by mykola-mokhnach** [comment]
@asoneji Please try appium beta with xctest driver version 2.60.0+. [This PR](https://github.com/appium/appium-xcuitest-driver/pull/574) should now support file upload and download via sshd filesystem on real devices. Also, it is now possible to upload and download files from application containers.
