### ISSUE TITLE
Log to console is disappear with /source?json call

### ISSUE THREAD

**Issue by lavi-xu** [appium/appium#9675]
## The problem

Appium is launched in terminal/ssh. When do normal page source calling, it 's okay for output of logging:
curl -X GET $JSON_HEADER "$DEVICE_URL/source"

However, I ran this command and appium log is disappear 4ever.
curl -X GET $JSON_HEADER "$DEVICE_URL/source?json"

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Desktop OS/version used to run Appium: macos 10.12.6
* Real device or emulator/simulator: ios 10.3.3

**Comment by mykola-mokhnach** [comment]
The request is not correct. It should be changed to `curl -X GET $JSON_HEADER "$DEVICE_URL/source?format=json"`

**Comment by lavi-xu** [comment]
Before I commit this CR, I already know the right command from #9668, just inform that there was an log issue that calling source with wrong url :)

**Comment by mykola-mokhnach** [comment]
It's anyway on WebDriverAgent side or you think it has something to do with appium code?

**Comment by lavi-xu** [comment]
I have no idea. I just see this issue.
