### ISSUE TITLE
Appium takes more than 20 minutes to create a new page when element is in the bottom of the page and sometimes in ended with throwing org.openqa.selenium.remote.SessionNotFoundException: A session is either terminated or not started in a middle of a scenario

### ISSUE THREAD

**Issue by badrAkermouch** [appium/appium#9677]
## The problem

I have a page in IOS that contains a fixed menu in the bottom and also not visible elements in the bottom. 

the problem is that Appium takes more than 20 minutes to create a new page when elements are in the bottom of the page and sometimes in ended with throwing org.openqa.selenium.remote.SessionNotFoundException: A session is either terminated or not started in a middle of my scenario.
 
When i scroll to the bottom of the page the problem is resolved and appium detect the elements in the page.

## Environment

* Appium version : 1.7.2 && 1.7.2-beta2
* java client version : 5.0.4
* IOS 11
* iPhone 7 (real device)

**Comment by mykola-mokhnach** [comment]
Please attach full server log

**Comment by badrAkermouch** [comment]
https://gist.github.com/badrAkermouch/4ca5005fc9b98fc1e33553307488a3ab

**Comment by mykola-mokhnach** [comment]
I don't see anything suspicious in the attached log (perhaps because it's not full). Try to get the log from the device itself when the delay happens and check if there are any errors/exceptions.

Also, try to debug your code to figure out which block of code is causing the delay.

**Comment by badrAkermouch** [comment]
I updated the attached log.

The log contains now the date indicator.

It taked 6 min today.

**Comment by krantos** [comment]
Hello all, well I have this issue too, but after test with another iPhone number, it took less time (normal time less than a minute). Can you try with iPhone 6 and iPhone 8? maybe there is something wrong with iPhone 7

**Comment by romainlouvet** [comment]
up ?
