### ISSUE TITLE
Request: Please add an option to appium for simpleIsVisibleCheck

### ISSUE THREAD

**Issue by lavi-xu** [appium/appium#9678]
Hi Team,

Since the original method for checking visible for ios10 is kinda crazy us, could you please add an option to appium to turn on simpleIsVisibleCheck?

Look like the following way should okay for us:
desired_caps['shouldUseTestManagerForVisibilityDetection'] = True 

BR.

**Comment by mykola-mokhnach** [comment]
There is `simpleIsVisibleCheck` capability. What else is needed?
