### ISSUE TITLE
Would like to know ApplePay can be automated using Selenium ?

### ISSUE THREAD

**Issue by NeelSM** [appium/appium#9679]
I got a requirement to automate ApplePay implementation, intended to run in safari mobile [iPhone 7] browsers both in IPhone, IPad and MAC Safari. I am in search for a way to automate the apple pay integration using selenium. We will have an option from e-comm page to choose Apple pay, Then a ApplePay overlay panel is displayed which have options to select the saved credit card, addresses in the mobile phone (we call this as apple payment sheet). These informations are prefilled but user can change this. I believe this is some kind of native code which displays this panel above the safari.

Would like to know whether this can be automated using Selenium?. Since those elements of ApplyPay is Secure Elements and not able to inspect them over Desktop Appium, IOS inspector or some other tools.

I am new to this, hence some one please suggest me on this.

![image](https://user-images.githubusercontent.com/33837519/33077417-cb71484a-cef5-11e7-8e15-9f4c81ff55a8.png)

**Comment by mykola-mokhnach** [comment]
If it is not possible to access these controls via XCTest then you won't be able to do it via Appium as well.

**Comment by KabiiRanga** [comment]
@NeelSM Could you able to automate this feature? I have this issue in my app.

**Comment by NeelSM** [comment]
@KabiiRanga Nope, I am not able to identify the elements of applePay.

**Comment by isnifer** [comment]
@NeelSM @KabiiRanga At tipsi we are successfully automate tests for Apple Pay payments

**Comment by dpgraham** [comment]
@isnifer How were you able to do it?

**Comment by FuzzyBuckBeak** [comment]
Even we are just stuck here. How do we achieve this?

**Comment by qakart** [comment]
@isnifer please let us know did you used https://github.com/tipsi/tipsi-stripe to achieve this or any other workaround will be much appreciated 
thanks in advance
