### ISSUE TITLE
Can't perform any gestures using TouchAction class

### ISSUE THREAD

**Issue by sevarudakov** [appium/appium#9680]
## The problem
I am trying to perform swipe action using I have tried the following commands:

Appium::TouchAction.new(driver).press(x: 50, y: 200).move_to(x: 300, y: 200)

Appium::TouchAction.new(driver).press(x: 50, y: 200).wait(7000).move_to(x: 300, y: 200).release

Appium::TouchAction.new(driver).swipe(start_x: 50, start_y: 300, offset_x: 300, offset_y: 300, duration: 3000).perform

Appium::TouchAction.new(driver).swipe_coordinates(start_x: 50, start_y: 300, offset_x: 300, offset_y: 300)

Appium::TouchAction.new(driver).swipe_coordinates(start_x: 50, start_y: 200, offset_x: 300, offset_y: 200)

So, none of them worked for me, it doesn't perform swipe and I get no errors.

## Environment

* Appium version (or git revision) that exhibits the issue: 9.7.5
* Last Appium version that did not exhibit the issue (if applicable): 1.7.1
* Desktop OS/version used to run Appium: Mac OS Sierra 10.12.6 
* Real device or emulator/simulator: XCODE 9

## Link to Appium logs
https://gist.github.com/sevarudakov/757684efa1c63d6eb2af150e6d44f970

## Code To Reproduce Issue [ Good To Have ]
driver = Appium::Driver.new({
                                      caps: {
                                          platformName: :ios,
                                          app: 'path to *.app',
                                          device_name: 'iPhone X',
                                          platform_version: '11.0',
                                          automation_name: 'XCUITest'
                                      },
                                      appium_lib: {
                                          wait_timeout: 30,
                                          wait_interval: 1
                                      }
                                  }, false).start_driver

**Comment by KazuCocoa** [comment]
How about using mobile gestures for XCUITest?

- https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios/ios-xctest-mobile-gestures.md
    - https://github.com/appium/ruby_lib/blob/master/docs/ios_xcuitest.md#gesture
- http://www.rubydoc.info/github/appium/ruby_lib/Appium/Ios/Xcuitest/Gesture

**Comment by sevarudakov** [comment]
I was using Ruby,  so I was trying to perform the following:

execute_script 'mobile: scroll', direction: 'left'

I saw how it was actually trying to swipe as at least it started to move
but it didn't performed swipe till the end so the screen didn't change.

**Comment by KazuCocoa** [comment]
How about `scroll` or `dragFromToForDuration` as workarounds?
The behaviour depends on WebDriverAgent side. After introducing _gesture chains_, we can define actions more flexible, though.

Anyway, TouchAction itself doesn't work for xcuitest automation name and we need to use `mobile:` gesture instead so far.
