### ISSUE TITLE
3.7.0 : Error send_keys(str)

### ISSUE THREAD

**Issue by langme** [appium/appium#9681]
## The problem

Don t arrive using send_keys(_str) with version +3.5.0 until 3.7.0

## Environment

* Appium version (or git revision) that exhibits the issue: 3.5.0
* Last Appium version that did not exhibit the issue (if applicable):3.0.0
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): v9.1.0
* Mobile platform/version under test: android 5.1.1
* Real device or emulator/simulator: no
* Appium CLI or Appium.app|exe:

## Details
i use go_keyboard in my script and try to use send_key()
but i have this error 

## Link to Appium logs
Error : Message: Parameters were incorrect. We wanted {"required":["value"]} and you sent ["text","value","id","sessionId"]

search_input.send_keys(word_to_search)
......\appdata\local\programs\python\python36-32\lib\site-packages\selenium\webdriver\remote\webelement.py:349: in send_keys
'value': keys_to_typing(value)})
......\appdata\local\programs\python\python36-32\lib\site-packages\selenium\webdriver\remote\webelement.py:493: in _execute
return self._parent.execute(command, params)
......\appdata\local\programs\python\python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py:249: in execute
self.error_handler.check_response(response)
......\appdata\local\programs\python\python36-32\lib\site-packages\appium\webdriver\errorhandler.py:29: in check_response
raise wde
......\appdata\local\programs\python\python36-32\lib\site-packages\appium\webdriver\errorhandler.py:24: in check_response
super(MobileErrorHandler, self).check_response(response)

**Comment by mykola-mokhnach** [comment]
Update Appium to the most recent version (1.7.1 for now)

**Comment by langme** [comment]
i have the same error
