### ISSUE TITLE
resetKeyboard does not reset appium unicode keyboard

### ISSUE THREAD

**Issue by mekxtari** [appium/appium#9682]
## The problem

Server capability resetKeyboard does not work when appium unicode keyboard is used.
Unicode keyboard stays as default in real device.

This should have been already fixed but the fix did not work:
https://github.com/appium/appium/issues/8755

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: Mac OSx El Capitan
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: 6.0.1/7.1.1
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe:

## Link to Appium logs
https://gist.github.com/mekxtari/723933a7317c7c8363d6ee7a21a2ca39

**Comment by tfcardoso** [comment]
Apparently when you started the test, your default keyboard was already the appium one:

     [debug] [ADB] Running '/Users/xxx/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","3300507723c1a2cb","shell","settings","get","secure","default_input_method"]
     [debug] [AndroidDriver] Unsetting previous IME io.appium.android.ime/.UnicodeIME
     [debug] [AndroidDriver] Setting IME to 'io.appium.android.ime/.UnicodeIME'

So in the end of test it tries to set the default again:

     [debug] [UiAutomator2] Resetting IME to 'io.appium.android.ime/.UnicodeIME

For my tests I made a custom method that if the default one is the appium one, it sets another random keyboard from the list returned (ime list-s) removing appium and voicesearch keyboards from that list.
Don't know if appium should attempt something similar.

**Comment by mekxtari** [comment]
hi @tfcardoso,

a very good point! Once i had something else than appium unicode as default, resetKeyboard did work.
Maybe the approach you mentioned can be something that should be implemented also in appium side. 

Anyhow, thank you very much for pointing this out!
