### ISSUE TITLE
Can we have explicit wait time to load the .APk in Android Emultor by using Nightwatch JS?

### ISSUE THREAD

**Issue by kommuswamy** [appium/appium#9683]
Hi ,
 I am working on Automating the Android App by using Nightwatch js. I am seeing an issue  **"Socket Hang up"** while launching the emulator. So can we have any explicit wait time to load the emulator and launch .apk file?

Thanks,
Swamy.

**Comment by kommuswamy** [comment]
[Appium] Creating new AndroidUiautomator2Driver (v0.6.5) session
[Appium] Capabilities:
[Appium]   browserName: 'FcatSet'
[Appium]   javascriptEnabled: true
[Appium]   acceptSslCerts: true
[Appium]   platform: 'Windows'
[Appium]   browserVersion: '59'
[Appium]   appium-version: '1.2.6'
[Appium]   platformName: 'Android'
[Appium]   platformVersion: '7.1'
[Appium]   deviceName: 'Nexus6'
[Appium]   newCommandTimeout: 30000
[Appium]   avd: 'Nexus6'
[Appium]   app: 'C:/Users/skommu/Desktop/mobileapk/mobile3.0-release.apk'
[Appium]   appPackage: 'com.factset.mobile3.prod'
[Appium]   appActivity: 'com.factset.mobile3.SplashActivity'
[Appium]   appMainActivity: 'com.factset.mobile3.MainActivity'
[Appium]   automationName: 'UIAutomator2'
[Appium]   appWaitDuration: 30000
[Appium]   androidDeviceReadyTimeout: 40
[Appium]   androidInstallTimeout: 30000
[Appium]   deviceReadyTimeout: 40
[Appium]   name: 'Android Portfolio'
[BaseDriver] The following capabilities were provided, but are not recognized by appium: javascriptEnabled, acceptSslCerts, platform, browserVersion, appium-version, appMainActivity, name.
[BaseDriver] Session created with session id: e9dc82d5-08cb-4b05-b95f-6638e0425d9b
[BaseDriver] Using local app 'C:/Users/skommu/Desktop/mobileapk/mobile3.0-release.apk'
[UiAutomator2] Checking whether app is actually present
[AndroidDriver] Getting Java version
[AndroidDriver] Java version is: 1.8.0_111
[ADB] Checking whether adb is present
[ADB] Using adb.exe from C:\Users\skommu\AppData\Local\Android\sdk\platform-tools\adb.exe
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] 0 emulator(s) connected
[ADB] Emulator Nexus6 not running
[ADB] Launching Emulator with AVD Nexus6, launchTimeout60000 ms and readyTimeout 60000 ms
[ADB] Checking whether emulator is present
[ADB] Using emulator.exe from C:\Users\skommu\AppData\Local\Android\sdk\emulator\emulator.exe
[ADB] Checking whether emulator is present
[ADB] Using emulator.exe from C:\Users\skommu\AppData\Local\Android\sdk\emulator\emulator.exe
[ADB] Running 'C:\Users\skommu\AppData\Local\Android\sdk\emulator\emulator.exe' with args: ["-avd","Nexus6"]
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] 0 emulator(s) connected
[ADB] Emulator Nexus6 not running
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] 0 emulator(s) connected
[ADB] Emulator Nexus6 not running
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] 0 emulator(s) connected
[ADB] Emulator Nexus6 not running
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] 0 emulator(s) connected
[ADB] Emulator Nexus6 not running
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] 0 emulator(s) connected
[ADB] Emulator Nexus6 not running
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] 0 emulator(s) connected
[ADB] Emulator Nexus6 not running
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] 0 emulator(s) connected
[ADB] Emulator Nexus6 not running
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] 0 emulator(s) connected
[ADB] Emulator Nexus6 not running
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] 0 emulator(s) connected
[ADB] Emulator Nexus6 not running
[ADB] [AVD OUTPUT] Hax is enabled
[ADB] [AVD OUTPUT] Hax ram_size 0x60000000
[ADB] [AVD OUTPUT] HAX is working and emulator runs in fast virt mode.
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] 0 emulator(s) connected
[ADB] Emulator Nexus6 not running
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] 0 emulator(s) connected
[ADB] Emulator Nexus6 not running
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] 0 emulator(s) connected
[ADB] Emulator Nexus6 not running
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] 0 emulator(s) connected
[ADB] Emulator Nexus6 not running
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] 0 emulator(s) connected
[ADB] Emulator Nexus6 not running
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] 0 emulator(s) connected
[ADB] Emulator Nexus6 not running
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] 0 emulator(s) connected
[ADB] Emulator Nexus6 not running
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] 0 emulator(s) connected
[ADB] Emulator Nexus6 not running
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] 0 emulator(s) connected
[ADB] Emulator Nexus6 not running
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] 0 emulator(s) connected
[ADB] Emulator Nexus6 not running
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] 0 emulator(s) connected
[ADB] Emulator Nexus6 not running
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] 0 emulator(s) connected
[ADB] Emulator Nexus6 not running
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] 0 emulator(s) connected
[ADB] Emulator Nexus6 not running
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] 0 emulator(s) connected
[ADB] Emulator Nexus6 not running
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] 0 emulator(s) connected
[ADB] Emulator Nexus6 not running
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] 0 emulator(s) connected
[ADB] Emulator Nexus6 not running
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] 0 emulator(s) connected
[ADB] Emulator Nexus6 not running
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] 0 emulator(s) connected
[ADB] Emulator Nexus6 not running
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] 0 emulator(s) connected
[ADB] Emulator Nexus6 not running
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] 0 emulator(s) connected
[ADB] Emulator Nexus6 not running
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] 0 emulator(s) connected
[ADB] Emulator Nexus6 not running
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] 0 emulator(s) connected
[ADB] Emulator Nexus6 not running
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] 0 emulator(s) connected
[ADB] Emulator Nexus6 not running
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] 0 emulator(s) connected
[ADB] Emulator Nexus6 not running
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] 0 emulator(s) connected
[ADB] Emulator Nexus6 not running
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] 0 emulator(s) connected
[ADB] Emulator Nexus6 not running
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] 0 emulator(s) connected
[ADB] Emulator Nexus6 not running
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] 0 emulator(s) connected
[ADB] Emulator Nexus6 not running
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] 0 emulator(s) connected
[ADB] Emulator Nexus6 not running
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] 0 emulator(s) connected
[ADB] Emulator Nexus6 not running
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] 0 emulator(s) connected
[ADB] Emulator Nexus6 not running
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] 0 emulator(s) connected
[ADB] Emulator Nexus6 not running
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] 0 emulator(s) connected
[ADB] Emulator Nexus6 not running
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] 0 emulator(s) connected
[ADB] Emulator Nexus6 not running
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] 0 emulator(s) connected
[ADB] Emulator Nexus6 not running
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] 0 emulator(s) connected
[ADB] Emulator Nexus6 not running
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] [AVD OUTPUT] Your emulator is out of date, please update by launching Android Studio:
[ADB] [AVD OUTPUT]  - Start Android Studio
[ADB] [AVD OUTPUT]  - Select menu "Tools > Android > SDK Manager"
[ADB] [AVD OUTPUT]  - Click "SDK Tools" tab
[ADB] [AVD OUTPUT]  - Check "Android Emulator" checkbox
[ADB] [AVD OUTPUT]  - Click "OK"
[ADB] [AVD OUTPUT] 
[ADB] 0 device(s) connected
[ADB] 0 emulator(s) connected
[ADB] Emulator Nexus6 not running
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] 0 emulator(s) connected
[ADB] Emulator Nexus6 not running
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] 0 emulator(s) connected
[ADB] Emulator Nexus6 not running
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] 0 emulator(s) connected
[ADB] Emulator Nexus6 not running
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] 0 emulator(s) connected
[ADB] Emulator Nexus6 not running
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] 0 emulator(s) connected
[ADB] Emulator Nexus6 not running
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] 0 emulator(s) connected
[ADB] Emulator Nexus6 not running
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] 0 emulator(s) connected
[ADB] Emulator Nexus6 not running
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] 0 emulator(s) connected
[ADB] Emulator Nexus6 not running
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] 0 emulator(s) connected
[ADB] Emulator Nexus6 not running
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] 0 emulator(s) connected
[ADB] Emulator Nexus6 not running
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] 0 emulator(s) connected
[ADB] Emulator Nexus6 not running
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] 0 emulator(s) connected
[ADB] Emulator Nexus6 not running
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] 0 emulator(s) connected
[ADB] Emulator Nexus6 not running
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] 0 emulator(s) connected
[ADB] Emulator Nexus6 not running
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] 0 emulator(s) connected
[ADB] Emulator Nexus6 not running
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] 0 emulator(s) connected
[ADB] Emulator Nexus6 not running
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] 0 emulator(s) connected
[ADB] Emulator Nexus6 not running
[ADB] Trying to find Nexus6 emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] 1 emulator(s) connected
[ADB] Sending telnet command to device: avd name
[ADB] Getting running emulator port
[ADB] Socket connection to device created
[ADB] Socket connection to device ready
[ADB] Telnet command got response: Nexus6
[ADB] Found emulator Nexus6 in port 5554
[ADB] Setting device id to emulator-5554
[ADB] Waiting until emulator is ready
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'C:\Users\skommu\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","getprop","init.svc.bootanim"]
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'C:\Users\skommu\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","getprop","init.svc.bootanim"]
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'C:\Users\skommu\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","getprop","init.svc.bootanim"]
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'C:\Users\skommu\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","getprop","init.svc.bootanim"]
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'C:\Users\skommu\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","getprop","init.svc.bootanim"]
[AndroidDriver] Using device: emulator-5554
[ADB] Checking whether adb is present
[ADB] Using adb.exe from C:\Users\skommu\AppData\Local\Android\sdk\platform-tools\adb.exe
[ADB] Setting device id to emulator-5554
[ADB] Getting device platform version
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'C:\Users\skommu\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","getprop","ro.build.version.release"]
[ADB] Current device property 'ro.build.version.release': 7.1.1
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'C:\Users\skommu\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","wm","size"]
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'C:\Users\skommu\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","getprop","ro.product.model"]
[ADB] Current device property 'ro.product.model': Android SDK built for x86
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'C:\Users\skommu\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","getprop","ro.product.manufacturer"]
[ADB] Current device property 'ro.product.manufacturer': unknown
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'C:\Users\skommu\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","am","force-stop","io.appium.uiautomator2.server"]
[ADB] Checking whether aapt is present
[ADB] Using aapt.exe from C:\Users\skommu\AppData\Local\Android\sdk\build-tools\25.0.3\aapt.exe
[ADB] Getting install status for io.appium.uiautomator2.server
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'C:\Users\skommu\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","pm","list","packages","io.appium.uiautomator2.server"]
[ADB] App is installed
[ADB] Getting install status for io.appium.uiautomator2.server.test
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'C:\Users\skommu\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","pm","list","packages","io.appium.uiautomator2.server.test"]
[ADB] App is installed
[ADB] Getting package info for io.appium.uiautomator2.server
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'C:\Users\skommu\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","dumpsys","package","io.appium.uiautomator2.server"]
[UiAutomator2] Waiting up to 20000ms for instrumentation 'io.appium.uiautomator2.server.test/android.support.test.runner.AndroidJUnitRunner' to be available
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'C:\Users\skommu\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","pm","list","instrumentation"]
[UiAutomator2] Instrumentation 'io.appium.uiautomator2.server.test/android.support.test.runner.AndroidJUnitRunner' available
[ADB] Running 'C:\Users\skommu\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","wait-for-device"]
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'C:\Users\skommu\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","echo","ping"]
[Logcat] Starting logcat capture
[AndroidDriver] Pushing unlock helper app to device...
[ADB] Running 'C:\Users\skommu\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","install","C:\\Users\\skommu\\AppData\\Local\\Programs\\appium-desktop\\resources\\app\\node_modules\\appium\\node_modules\\appium-unlock\\bin\\unlock_apk-debug.apk"]
[ADB] Running 'C:\Users\skommu\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","install","C:\\Users\\skommu\\AppData\\Local\\Programs\\appium-desktop\\resources\\app\\node_modules\\appium\\node_modules\\appium-unlock\\bin\\unlock_apk-debug.apk"]
[ADB] Application 'C:\Users\skommu\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-unlock\bin\unlock_apk-debug.apk' already installed. Continuing.
[UiAutomator2] Forwarding UiAutomator2 Server port 6790 to 8200
[ADB] Forwarding system: 8200 to device: 6790
[ADB] Running 'C:\Users\skommu\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","forward","tcp:8200","tcp:6790"]
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'C:\Users\skommu\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","dumpsys","window"]
[AndroidDriver] Screen already unlocked, doing nothing
[AndroidDriver] Extracting strings from apk C:/Users/skommu/Desktop/mobileapk/mobile3.0-release.apk undefined C:\Users\skommu\AppData\Local\Temp\com.factset.mobile3.prod
[ADB] Extracting strings for language: default
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'C:\Users\skommu\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","getprop","ro.build.version.sdk"]
[ADB] Current device property 'ro.build.version.sdk': 25
[ADB] Device API level: 25
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'C:\Users\skommu\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","getprop","persist.sys.locale"]
[ADB] Current device property 'persist.sys.locale': 
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'C:\Users\skommu\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","getprop","ro.product.locale"]
[ADB] Current device property 'ro.product.locale': en-US
[ADB] No strings.xml for language 'en', getting default strings.xml
[ADB] Reading strings from converted strings.json
[ADB] Running 'C:\Users\skommu\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","push","C:\\Users\\skommu\\AppData\\Local\\Temp\\com.factset.mobile3.prod\\strings.json","/data/local/tmp"]
[ADB] Checking app cert for C:/Users/skommu/Desktop/mobileapk/mobile3.0-release.apk.
[ADB] App already signed.
[ADB] Zip-aligning 'C:/Users/skommu/Desktop/mobileapk/mobile3.0-release.apk'
[ADB] Checking whether zipalign is present
[ADB] Using zipalign.exe from C:\Users\skommu\AppData\Local\Android\sdk\build-tools\25.0.3\zipalign.exe
[ADB] Zip-aligning apk.
[AndroidDriver] Remote apk path is /data/local/tmp/ad97b9ef5e998d0fcfc73fc9270e64ae.apk
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'C:\Users\skommu\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","ls","/data/local/tmp/ad97b9ef5e998d0fcfc73fc9270e64ae.apk"]
[AndroidDriver] Checking if app is installed
[ADB] Getting install status for com.factset.mobile3.prod
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'C:\Users\skommu\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","pm","list","packages","com.factset.mobile3.prod"]
[ADB] App is installed
[AndroidDriver] Apk is already on remote and installed, resetting
[AndroidDriver] Running fast reset (stop and clear)
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'C:\Users\skommu\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","am","force-stop","com.factset.mobile3.prod"]
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'C:\Users\skommu\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","pm","clear","com.factset.mobile3.prod"]
[HTTP] <-- POST /wd/hub/session - - ms - - 
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'C:\Users\skommu\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","am","force-stop","io.appium.uiautomator2.server"]
[UiAutomator2] Starting uiautomator2 server v0.1.8
[UiAutomator2] Running command: 'adb -s emulator-5554 shell am instrument -w io.appium.uiautomator2.server.test/android.support.test.runner.AndroidJUnitRunner'
[UiAutomator2] Waiting up to 20000ms for UiAutomator2 to be online...
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"SESSIONID\",\"status\":0,\"value\":\"Status Invoked\"}"
[JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8200/wd/hub/session] with body: {"desiredCapabilities":{"platform":"Windows","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"browserName":"FcatSet","javascriptEnabled":true,"acceptSslCerts":true,"platform":"Windows","browserVersion":"59","appium-version":"1.2.6","platformName":"Android","platformVersion":"7.1","deviceName":"Nexus6","newCommandTimeout":30000,"avd":"Nexus6","app":"C:/Users/skommu/Desktop/mobileapk/mobile3.0-release.apk","appPackage":"com.factset.mobile3.prod","appActivity":"com.factset.mobile3.SplashActivity","appMainActivity":"com.factset.mobile3.MainActivity","automationName":"UIAutomator2","appWaitDuration":30000,"androidDeviceReadyTimeout":40,"androidInstallTimeout":30000,"deviceReadyTimeout":40,"name":"Android Portfolio"},"browserName":"FcatSet","acceptSslCerts":true,"browserVersion":"59","appium-version":"1.2.6","platformName":"Android","platformVersion":"7.1.1","deviceName":"emul...
[JSONWP Proxy] Got response with status 200: {"sessionId":"c6fbcf61-8a43-4d67-b1e1-ad9687f3baee","status":0,"value":"Created Session"}
[UiAutomator2] UiAutomator2 did not start the activity we were waiting for, 'com.factset.mobile3.prod/com.factset.mobile3.SplashActivity'. Starting it ourselves
[ADB] Device API level: 25
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'C:\Users\skommu\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","am","start","-W","-n","com.factset.mobile3.prod/com.factset.mobile3.SplashActivity","-S"]
[Appium] New AndroidUiautomator2Driver session created successfully, session e9dc82d5-08cb-4b05-b95f-6638e0425d9b added to master session list
[BaseDriver] Event 'newSessionStarted' logged at 1511359542743 (19:35:42 GMT+0530 (India Standard Time))
[MJSONWP] Responding to client with driver.createSession() result: {"browserName":"FcatSet","javascriptEnabled":true,"acceptSslCerts":true,"platform":"Windows","browserVersion":"59","appium-version":"1.2.6","platformName":"Android","platformVersion":"7.1","deviceName":"Nexus6","newCommandTimeout":30000,"avd":"Nexus6","app":"C:/Users/skommu/Desktop/mobileapk/mobile3.0-release.apk","appPackage":"com.factset.mobile3.prod","appActivity":"com.factset.mobile3.SplashActivity","appMainActivity":"com.factset.mobile3.MainActivity","automationName":"UIAutomator2","appWaitDuration":30000,"androidDeviceReadyTimeout":40,"androidInstallTimeout":30000,"deviceReadyTimeout":40,"name":"Android Portfolio"}

**Comment by kommuswamy** [comment]
here is appium logs, https://gist.github.com/kommuswamy/acdd8552fcd10ca0d1bf6c943c192fb3 ,
and I am seeing an error message in cmd is,
Error retrieving a new session from the selenium server

Connection refused! Is selenium server started?
{ Error: socket hang up
    at createHangUpError (_http_client.js:254:15)
    at Socket.socketCloseListener (_http_client.js:286:23)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12) code: 'ECONNRESET' }

**Comment by mykola-mokhnach** [comment]
> [UiAutomator2] UiAutomator2 did not start the activity we were waiting for, 'com.factset.mobile3.prod/com.factset.mobile3.SplashActivity'. Starting it ourselves

It looks like the activity name(s) you provide in `appActivity`/`appWaitActvity` capabilities are incorrect
