### ISSUE TITLE
Clipboard popup on SendKeys in Android

### ISSUE THREAD

**Issue by PaulinkaS** [appium/appium#9684]
## The problem

At the moment whenever using SendKeys on TextBox on Android a small popup indicating usage of clipboard appears. 
It seems that every SendKeys starts with LongClick and only after that the intended action is happening.
Is there a way to remove the Clipboard popup or change LongClick to Click at the beginning? 

## Environment

* Appium version: 1.7.1
* Desktop OS/version used to run Appium: Windows 10 x64
* Mobile platform/version under test: Android 5 -7 
* Real device or emulator/simulator: both
* Appium CLI or Appium.app|exe: CLI

## Details
[Same issue on Appium discuss](https://discuss.appium.io/t/is-there-any-way-to-not-show-clipboard-button-during-sendkeys-action/19549/6)
This Clipboard popup is extremely annoying when showing tests to customers - they always ask if it means that we are just pasting the predefined values into the fields and why we are not doing what real user would do - input letter by letter.
It would be great if with Appium we could somehow eliminate this LongClick on each SendKeys.

**Comment by mykola-mokhnach** [comment]
Do you use UIA1 or UIA2?

**Comment by mykola-mokhnach** [comment]
A short movie/screenshot, which demonstrates the issue would be appreciates

**Comment by PaulinkaS** [comment]
Below you can find a video of SendKeys action to some native android application. 
![image](https://user-images.githubusercontent.com/19324095/33163143-3cb146d0-d02d-11e7-872b-ee446eed0d17.png)
[Clipboard Issue.zip](https://github.com/appium/appium/files/1498343/Clipboard.Issue.zip)

**Comment by mykola-mokhnach** [comment]
> Do you use UIA1 or UIA2 as automation backend?

**Comment by PaulinkaS** [comment]
UIA1 atm but we are about to switch to UIA2 soon.

**Comment by mykola-mokhnach** [comment]
Then just do it. We are not very keen to do improvements for UIA1, since it is anyway deprecated in newer Android versions.

**Comment by PaulinkaS** [comment]
Does it mean that this issue does not occur in UIA1?
