### ISSUE TITLE
Error "The target server failed to respond" appears sometimes on iOS Driver

### ISSUE THREAD

**Issue by shynkevich-alex** [appium/appium#9685]
## The problem
I often see error when launch my tests. 
It happens after few hours of running tests.

`Nov 22, 2017 5:04:04 PM org.apache.http.impl.execchain.RetryExec execute
    INFO: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://127.0.0.1:38812: The target server failed to respond
    Nov 22, 2017 5:04:04 PM org.apache.http.impl.execchain.RetryExec execute
    INFO: Retrying request to {}->http://127.0.0.1:38812`

I was looking for the same issue in github but not found it.
So no idea why it happens.

## Environment

* 1.7.2-beta
* Mac OS 10.12.6
* Real iphone  iOS 11.0.3
* xCode 9.1
* Java client 5.0.4

## Details
* I start server programmatically:

       AppiumServiceBuilder builder = new AppiumServiceBuilder();

        builder.usingAnyFreePort();
        builder.withIPAddress("127.0.0.1");
        builder.withArgument(GeneralServerFlag.SESSION_OVERRIDE);
        builder.withArgument(GeneralServerFlag.LOG_LEVEL, "warn");
        builder.withArgument(GeneralServerFlag.LOG_LEVEL, "info");

        service = builder.build();
        service.start();

* My capabilities:

```
DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability(MobileCapabilityType.PLATFORM, MobilePlatform.IOS);
        capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, iosRealDevice.getOsVersion());
        capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, iosRealDevice.getName());
        capabilities.setCapability(MobileCapabilityType.UDID, iosRealDevice.getId());
        capabilities.setCapability(MobileCapabilityType.APP, testHelper.getAppPath());
        capabilities.setCapability(IOSMobileCapabilityType.XCODE_ORG_ID, "H93M8946AV");
        capabilities.setCapability(IOSMobileCapabilityType.XCODE_SIGNING_ID, "iPhone Developer");
        capabilities.setCapability(IOSMobileCapabilityType.USE_NEW_WDA, true);
        capabilities.setCapability("useJSONSource", true);
        capabilities.setCapability(MobileCapabilityType.NO_RESET, true);
        capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, "XCUITest");
        capabilities.setCapability(MobileCapabilityType.CLEAR_SYSTEM_FILES, true);
```

**Comment by mykola-mokhnach** [comment]
Perhaps WebDriverAgents just stops responding to requests. This happens if you redeploy it too often on real device (I see you have `IOSMobileCapabilityType.USE_NEW_WDA` parameter set to` true`). Read https://github.com/facebook/WebDriverAgent/issues/507 for more details.

**Comment by shynkevich-alex** [comment]
@mykola-mokhnach I create driver once before class.
I create driver approximately 9 times, It seems not often.
New WDA will be built with new driver. Am I right?

But I close and launch app in every test and after launch I see  in appium logs.
> [XCUITest] Launching WebDriverAgent on the device

Does it mean I redeploy WDA every launch?

**Comment by mykola-mokhnach** [comment]
Yes it does.`closeApp/launchApp` practically does the same as driver.quit/driver.start and therefore is not recommended to use

**Comment by shynkevich-alex** [comment]
I got it, but I use closeApp/launchApp because sometimes runAppInBackround fails.
Will runAppInBackround redeploy WDA?

**Comment by mykola-mokhnach** [comment]
> Will runAppInBackround redeploy WDA?

no

**Comment by shynkevich-alex** [comment]
Thank you for help!
I set `USE_NEW_WDA to FALSE` and changed `closeApp/launchApp` to `runAppInBackground`.
If issue will not reproduce I will close it.

**Comment by o-kramar** [comment]
Also reproduce this issue. Became reproducible after updating to MacOS High Sierra 10.13.1 and XCode 9.1. Use Appium  1.7.2-beta, USE_NEW_WDA to FALSE, iPhone 7 Plus simulator with iOS 10.3
