### ISSUE TITLE
UIAutomator2 pageSource Exception

### ISSUE THREAD

**Issue by mstrelex** [appium/appium#9686]
## The problem

Trying to use pageSource() on Facebook app results in org.w3c.dom.DOMException

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.6
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: OSX
* Node.js version (unless using Appium.app|exe): 7
* Real device or emulator/simulator: Device
* Appium CLI or Appium.app|exe: CLI
* AUT - Facebook 151.0.0.44.205

## Details

Running pageSource() while in some specific activity in Facebook trows exception and returns status 500. But when using UIAutomator Viewer directly - DOM returns fine.

The activity is:

- Open Facebook main activity
- Tap on 'More' icon (burger)
- Tap 'View your profile'
- Tap 'Edit' (camera icon) on the cover image
- Tap 'Select photo on Facebook'
- Tap 'Uploads'
- Run pageSource() command

## Link to Appium logs

`org.w3c.dom.DOMException: at org.apache.harmony.xml.dom.NodeImpl.setNameNS(NodeImpl.java:241)at org.apache.harmony.xml.dom.DocumentImpl.renameNode(DocumentImpl.java:318)at io.appium.uiautomator2.utils.XMLHierarchy.visitNode(XMLHierarchy.java:131)at io.appium.uiautomator2.utils.XMLHierarchy.annotateNodes(XMLHierarchy.java:96)at io.appium.uiautomator2.utils.XMLHierarchy.annotateNodes(XMLHierarchy.java:97)`

**Comment by mykola-mokhnach** [comment]
Can you please attach full stack trace and also the output, that you get from UIA1?

**Comment by mstrelex** [comment]
Writing "UIAutomator Viewer", I refer to the executable coming with Android SDK...
Here's the full log & stack trace:
https://gist.github.com/mstrelex/4e6e01248cb9e0d4af989d405b6ed25f
Many thanks.

**Comment by mykola-mokhnach** [comment]
Please check if the patch from https://github.com/appium/appium-uiautomator2-server/pull/93 works for you

**Comment by mstrelex** [comment]
Unfortunately it doesn't, still the same exception.

**Comment by mykola-mokhnach** [comment]
Have you built the server jar yourself, because this change has not been published yet

**Comment by mstrelex** [comment]
Yes, I built master repo where you merged this change 2 days ago

**Comment by mstrelex** [comment]
Logcat shows the same exception:

`11-30 00:25:50.459 29494 29566 E appium  : Exception while handling action in: io.appium.uiautomator2.handler.Source
11-30 00:25:50.459 29494 29566 E appium  : org.w3c.dom.DOMException:
11-30 00:25:50.459 29494 29566 E appium  : 	at org.apache.harmony.xml.dom.NodeImpl.setNameNS(NodeImpl.java:241)
11-30 00:25:50.459 29494 29566 E appium  : 	at org.apache.harmony.xml.dom.DocumentImpl.renameNode(DocumentImpl.java:318)
11-30 00:25:50.459 29494 29566 E appium  : 	at io.appium.uiautomator2.utils.XMLHierarchy.visitNode(XMLHierarchy.java:134)
11-30 00:25:50.459 29494 29566 E appium  : 	at io.appium.uiautomator2.utils.XMLHierarchy.annotateNodes(XMLHierarchy.java:99)
11-30 00:25:50.459 29494 29566 E appium  : 	at io.appium.uiautomator2.utils.XMLHierarchy.annotateNodes(XMLHierarchy.java:100)
11-30 00:25:50.459 29494 29566 E appium  : 	at io.appium.uiautomator2.utils.XMLHierarchy.annotateNodes(XMLHierarchy.java:100)
11-30 00:25:50.459 29494 29566 E appium  : 	at io.appium.uiautomator2.utils.XMLHierarchy.annotateNodes(XMLHierarchy.java:100)
11-30 00:25:50.459 29494 29566 E appium  : 	at io.appium.uiautomator2.utils.XMLHierarchy.annotateNodes(XMLHierarchy.java:100)
11-30 00:25:50.459 29494 29566 E appium  : 	at io.appium.uiautomator2.utils.XMLHierarchy.annotateNodes(XMLHierarchy.java:100)
11-30 00:25:50.459 29494 29566 E appium  : 	at io.appium.uiautomator2.utils.XMLHierarchy.annotateNodes(XMLHierarchy.java:100)
11-30 00:25:50.459 29494 29566 E appium  : 	at io.appium.uiautomator2.utils.XMLHierarchy.annotateNodes(XMLHierarchy.java:100)
11-30 00:25:50.459 29494 29566 E appium  : 	at io.appium.uiautomator2.utils.XMLHierarchy.annotateNodes(XMLHierarchy.java:100)
11-30 00:25:50.459 29494 29566 E appium  : 	at io.appium.uiautomator2.utils.XMLHierarchy.annotateNodes(XMLHierarchy.java:100)
11-30 00:25:50.459 29494 29566 E appium  : 	at io.appium.uiautomator2.utils.XMLHierarchy.annotateNodes(XMLHierarchy.java:100)
11-30 00:25:50.459 29494 29566 E appium  : 	at io.appium.uiautomator2.utils.XMLHierarchy.annotateNodes(XMLHierarchy.java:100)
11-30 00:25:50.459 29494 29566 E appium  : 	at io.appium.uiautomator2.utils.XMLHierarchy.annotateNodes(XMLHierarchy.java:100)
11-30 00:25:50.459 29494 29566 E appium  : 	at io.appium.uiautomator2.utils.XMLHierarchy.formatXMLInput(XMLHierarchy.java:89)
11-30 00:25:50.459 29494 29566 E appium  : 	at io.appium.uiautomator2.utils.XMLHierarchy.getFormattedXMLDoc(XMLHierarchy.java:71)
11-30 00:25:50.459 29494 29566 E appium  : 	at io.appium.uiautomator2.handler.Source.safeHandle(Source.java:37)
11-30 00:25:50.459 29494 29566 E appium  : 	at io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:56)
11-30 00:25:50.459 29494 29566 E appium  : 	at io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:204)
11-30 00:25:50.459 29494 29566 E appium  : 	at io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:195)
11-30 00:25:50.459 29494 29566 E appium  : 	at io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:44)
11-30 00:25:50.459 29494 29566 E appium  : 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
11-30 00:25:50.459 29494 29566 E appium  : 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
11-30 00:25:50.459 29494 29566 E appium  : 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
11-30 00:25:50.459 29494 29566 E appium  : 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
11-30 00:25:50.459 29494 29566 E appium  : 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
11-30 00:25:50.459 29494 29566 E appium  : 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
11-30 00:25:50.459 29494 29566 E appium  : 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
11-30 00:25:50.459 29494 29566 E appium  : 	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)
11-30 00:25:50.459 29494 29566 E appium  : 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
11-30 00:25:50.459 29494 29566 E appium  : 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
11-30 00:25:50.459 29494 29566 E appium  : 	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)
11-30 00:25:50.459 29494 29566 E appium  : 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
11-30 00:25:50.459 29494 29566 E appium  : 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
11-30 00:25:50.459 29494 29566 E appium  : 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
11-30 00:25:50.459 29494 29566 E appium  : 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
11-30 00:25:50.459 29494 29566 E appium  : 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
11-30 00:25:50.459 29494 29566 E appium  : 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
11-30 00:25:50.459 29494 29566 E appium  : 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
11-30 00:25:50.459 29494 29566 E appium  : 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
11-30 00:25:50.459 29494 29566 E appium  : 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(Nio
11-30 00:25:50.461 29494 29566 I appium  : AppiumResponse: {"sessionId":"fc85c042-fa80-488e-a5c8-c5347a1b8751","status":13,"value":"org.w3c.dom.DOMException: \n\tat org.apache.harmony.xml.dom.NodeImpl.setNameNS(NodeImpl.java:241)\n\tat org.apache.harmony.xml.dom.DocumentImpl.renameNode(DocumentImpl.java:318)\n\tat io.appium.uiautomator2.utils.XMLHierarchy.visitNode(XMLHierarchy.java:134)\n\tat io.appium.uiautomator2.utils.XMLHierarchy.annotateNodes(XMLHierarchy.java:99)\n\tat io.appium.uiautomator2.utils.XMLHierarchy.annotateNodes(XMLHierarchy.java:100)\n\tat io.appium.uiautomator2.utils.XMLHierarchy.annotateNodes(XMLHierarchy.java:100)\n\tat io.appium.uiautomator2.utils.XMLHierarchy.annotateNodes(XMLHierarchy.java:100)\n\tat io.appium.uiautomator2.utils.XMLHierarchy.annotateNodes(XMLHierarchy.java:100)\n\tat io.appium.uiautomator2.utils.XMLHierarchy.annotateNodes(XMLHierarchy.java:100)\n\tat io.appium.uiautomator2.utils.XMLHierarchy.annotateNodes(XMLHierarchy.java:100)\n\tat io.appium.uiautomator2.utils.XMLHierarchy.annotateNodes(XMLHierarchy.java:100)\n\tat io.appium.uiautomator2.utils.XMLHierarchy.annotateNodes(XMLHierarchy.java:100)\n\tat io.appium.uiautomator2.utils.XMLHierarchy.annotateNodes(XMLHierarchy.java:100)\n\tat io.appium.uiautomator2.utils.XMLHierarchy.annotateNodes(XMLHierarchy.java:100)\n\tat io.appium.uiautomator2.utils.XMLHierarchy.annotateNodes(XMLHierarchy.java:100)\n\tat io.appium.uiautomator2.utils.XMLHierarchy.annotateNodes(XMLHierarchy.java:100)\n\tat io.appium.uiautomator2.utils.XMLHierarchy.formatXMLInput(XMLHierarchy.java:89)\n\tat io.appium.uiautomator2.utils.XMLHierarchy.getFormattedXMLDoc(XMLHierarchy.java:71)\n\tat io.appium.uiautomator2.handler.Source.safeHandle(Source.java:37)\n\tat io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:56)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:204)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:195)\n\tat io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:44)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)\n\tat io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)\n\tat io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)\n\tat io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)\n\tat io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)\n\tat io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)\n\tat io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)\n\tat io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe`

**Comment by mykola-mokhnach** [comment]
Perhaps you can help us to find the cause of the problem. Just add a log to record class names, which are passed to the `renameNode` method (file `XMLHierarchy.java`, log `androidClass` before the line `doc.renameNode(node, node.getNamespaceURI(), androidClass);`). So then we can find out which particular class name causes the crash inside apache lib.

**Comment by mykola-mokhnach** [comment]
Would you mind to create a PR?

**Comment by mstrelex** [comment]
Done, thanks.
