### ISSUE TITLE
chromeOption 'prefs' is not work

### ISSUE THREAD

**Issue by FuckyouBB** [appium/appium#9689]
## The problem

chromeOption contains a prefs can modify preference,but when i use ,it doesn't work.

## Environment

* Appium version (or git revision) that exhibits the issue:v1.7.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:Mac OS 10.12.6
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:Android 5.1
* Real device or emulator/simulator:Andorid
* chomeDrive :v2.30
* language: python 3.5

## Details

chromeOption contains a prefs can modify preference,but when i use ,it doesn't work.
but args in example is work.

## Link to Appium logs

[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8000/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.chrome","prefs":{"translate":{"enabled":false}},"androidDeviceSerial":"NX508J"}}}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"fda3ee97f9712868b3577888a6941a9a","status":13,"value":{"message":"unknown error: cannot parse capability: chromeOptions\nfrom unknown error: unrecognized chrome option: prefs\n  (Driver info: chromedriver=2.30.477690 (c53f4ad87510ee97b5c3425a14c0e79780cdf262),platform=Mac OS X 10.12.6 x86_64)"}}
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8000/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.chrome","prefs":{"translate":{"enabled":false}},"androidDeviceSerial":"NX508J"}}}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"660342f2d50b477f33275a269bd0ed7f","status":13,"value":{"message":"unknown error: cannot parse capability: chromeOptions\nfrom unknown error: unrecognized chrome option: prefs\n  (Driver info: chromedriver=2.30.477690 (c53f4ad87510ee97b5c3425a14c0e79780cdf262),platform=Mac OS X 10.12.6 x86_64)"}}
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8000/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.chrome","prefs":{"translate":{"enabled":false}},"androidDeviceSerial":"NX508J"}}}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"7429403705147d6a2e0bc63143faceda","status":13,"value":{"message":"unknown error: cannot parse capability: chromeOptions\nfrom unknown error: unrecognized chrome option: prefs\n  (Driver info: chromedriver=2.30.477690 (c53f4ad87510ee97b5c3425a14c0e79780cdf262),platform=Mac OS X 10.12.6 x86_64)"}}
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8000/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.chrome","prefs":{"translate":{"enabled":false}},"androidDeviceSerial":"NX508J"}}}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"1fec92bfb5ed89d4e1fc250971b2fbb5","status":13,"value":{"message":"unknown error: cannot parse capability: chromeOptions\nfrom unknown error: unrecognized chrome option: prefs\n  (Driver info: chromedriver=2.30.477690 (c53f4ad87510ee97b5c3425a14c0e79780cdf262),platform=Mac OS X 10.12.6 x86_64)"}}

## Code To Reproduce Issue [ Good To Have ]

desired_caps = {
            'platformName': 'Android',
            'deviceName': 'Android Emulator',
            'browserName': 'Chrome',
            'chromeOptions':{"prefs":{"translate":{"enabled":False}}},
            #'chromeOptions':  {'args': ['user-data-dir=/Users/ctwl/Documents/workspace/web_appium/userdata']},
            "newCommandTimeout": 300
        }

**Comment by mykola-mokhnach** [comment]
This error is thrown by chromedriver itself, which means it either does not support this option or requires it to be passed in some different format. I'd rather check it on Google forums.

**Comment by kool79** [comment]
@FuckyouBB , 
Chrome has different set of recognized options for different modes. `prefs` is valid but not for 'Android' mode. Details [here](https://github.com/bayandin/chromedriver/blob/8aaeb7bac05377ca635052cc42d80ab79223976c/capabilities.cc#L432)
