### ISSUE TITLE
how locate elemento by index de app in android 

### ISSUE THREAD

**Issue by wilkin07** [appium/appium#9691]
hello I'm having trouble locating an item by index of an android app, since this app does not contain id, I'm trying to use xpath but it gives me an error

since the app does not have id and all the elements have the same class.

driver.find_element_by_xpath("//android.view.ViewGroup[@index='2']")

selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.

I hope you can help me, I have been investigating for hours and I can not find anything

**Comment by vjmaiky** [comment]
make a list will all classes and after that get the index you want

**Comment by mykola-mokhnach** [comment]
Please use Appium forum to ask questions.
