### ISSUE TITLE
Scrolling method not yet implemented - android 

### ISSUE THREAD

**Issue by Sandarekha** [appium/appium#9692]
## The problem
I try to use scroll method to android app.But it gives error as method has not yet implemented. 
java-client-5.0.4

## Environment

* Appium version (or git revision) that exhibits the issue: 1.2.7
* Desktop OS/version used to run Appium: Windows 7
* Mobile platform/version under test: Android 5
* Real device or emulator/simulator: real device - Micromax E485

## Details
TestNG error trace 
org.openqa.selenium.WebDriverException: Method has not yet been implemented (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.7.1', revision: '8a0099a', time: '2017-11-06T21:07:36.161Z'
System info: host: 'LAPTOP-ITD170', ip: '10.194.169.198', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_111'
Driver info: io.appium.java_client.AppiumDriver
Capabilities {app: C:\Users\Sandarekha\Documen..., appActivity: ui.ActSplashScreen, appPackage: com.ipay.mobile, appium-version: 1.2.7, appwaitDuration: 30000, automationName: Appium, databaseEnabled: false, desired: {app: C:\Users\Sandarekha\Documen..., appActivity: ui.ActSplashScreen, appPackage: com.ipay.mobile, appium-version: 1.2.7, appwaitDuration: 30000, automationName: Appium, deviceName: Micromax E485, platformName: Android, platformVersion: 5, resetKeyboard: true, unicodeKeyboard: true}, deviceManufacturer: Micromax, deviceModel: Micromax E485, deviceName: V02755160490036173, deviceScreenSize: 1080x1920, deviceUDID: V02755160490036173, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: true, platform: LINUX, platformName: LINUX, platformVersion: 5.1, resetKeyboard: true, takesScreenshot: true, unicodeKeyboard: true, warnings: {}, webStorageEnabled: false}

## Link to Appium logs

https://gist.github.com/Sandarekha/0dba50c775e781703b9b5f5b78616896

## Code To Reproduce Issue [ Good To Have ]
Basesetup
https://gist.github.com/Sandarekha/ce4e2b0eb48155631bf60546df42314c

Testcase
https://gist.github.com/Sandarekha/98fde59226f722cfd5e89bf56f6c2be6

**Comment by mykola-mokhnach** [comment]
This method is only available in xctestdriver. For Android one must use TouchAction interface.
