### ISSUE TITLE
Scroll is not working in pop over

### ISSUE THREAD

**Issue by sebinjqburst** [appium/appium#9694]
## The problem

Scroll to the elements inside a pop up is not working. 
I tap on an element so that a pop up will appear and I want to scroll to an element at the bottom of the pop up which is currently hidden. When I look at the logs, the scroll is initiated but is not successful. Please help me to figure out the issue.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: MacOS Sierra 10.12.6
* Node.js version (unless using Appium.app|exe): 
* Mobile platform/version under test: iOS 10.3.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

debug] [XCUITest] Found matching gesture: scroll
[debug] [JSONWP Proxy] Proxying [POST /wda/dragfromtoforduration] to [POST http://localhost:8100/session/77EA10FC-47F0-4633-8854-509C605FF3CD/wda/dragfromtoforduration] with body: {"fromX":400,"fromY":350,"toX":400,"toY":-50,"duration":0}
[debug] [MJSONWP] Responding to client with driver.performTouch() result: null
[HTTP] <-- POST /wd/hub/session/d9e4fe3a-8242-46f0-9dd4-503d17c7417d/touch/perform - - ms - - 
[debug] [JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"77EA10FC-47F0-4633-8854-509C605FF3CD","status":0}
[debug] [MJSONWP] Responding to client with driver.performTouch() result: null
[debug] [XCUITest] Connection to WDA timed out
[debug] [iProxy] recv failed: Operation not permitted
[HTTP] --> POST /wd/hub/session/d9e4fe3a-8242-46f0-9dd4-503d17c7417d/timeouts {"type":"implicit","ms":0}
[debug] [MJSONWP] Calling AppiumDriver.timeouts() with args: 

## Code To Reproduce Issue [ Good To Have ]
Code used for scroll is the following:

Date start = new Date();
		Date end = new Date();
		long startTime = start.getTime();
		long endTime = end.getTime();
		while(!element.isDisplayed() && ((endTime-startTime) <60000)) {
			TouchAction ta1 = new TouchAction(driver);
			ta1.press(400, 350).moveTo(0,-400).release().perform();
			end = new Date();
			endTime = end.getTime();
			LOGGER.info("Scrolled for "+(endTime-startTime));
		}
		if(element.isDisplayed()) {
			LOGGER.info("Element found on scroll");
			return true;
		} else {
			LOGGER.info("Element is available, but has issues with visibility");
			return false;
		}

**Comment by mykola-mokhnach** [comment]
Please report the issue directly to https://github.com/facebook/WebDriverAgent/issues as it has nothing to do with Appium.
