### ISSUE TITLE
SetValue fails after typing the very first letter

### ISSUE THREAD

**Issue by sebinjqburst** [appium/appium#9695]
## The problem

When I try to type some text, the same is hanged after typing the first letter.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2-beta 2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MacOS Sierra 10.12
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iPad iOS 10.3.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

[debug] [MJSONWP] Calling AppiumDriver.setValueImmediate() with args: ["Encounter for prophylactic fluoride administration","912F5E5F-9E04-4794-A44B-7A8AA30477D2","7b27e490-84b6-40f6-9606-920df1a2ac0b"]
[debug] [XCUITest] Executing command 'setValueImmediate'
[XCUITest] There is currently no way to bypass typing using XCUITest. Setting value through keyboard
[debug] [JSONWP Proxy] Proxying [POST /element/912F5E5F-9E04-4794-A44B-7A8AA30477D2/value] to [POST http://localhost:8100/session/2C1B0B1D-5C49-47BD-AD2F-9A89E3118455/element/912F5E5F-9E04-4794-A44B-7A8AA30477D2/value] with body: {"value":["E","n","c","o","u","n","t","e","r"," ","f","o","r"," ","p","r","o","p","h","y","l","a","c","t","i","c"," ","f","l","u","o","r","i","d","e"," ","a","d","m","i","n","i","s","t","r","a","t","i","o","n"]}

[Xcode]     t =  1631.54s     Find: Element at index 0
[Xcode]     t =  1631.54s     Find the "Search all Diagnoses" SearchField
[Xcode]     t =  1631.54s         Use cached accessibility hierarchy for com.napa.tbar-staging
[Xcode]     t =  1631.54s         Find: Descendants matching type Any
[Xcode]     t =  1631.54s         Find: Elements matching predicate '"Search all Diagnoses" IN identifiers'
[Xcode]     t =  1631.55s         Find: Element at index 0
[Xcode]     t =  1632.01s     Find the Application "com.napa.tbar-staging" 0x1740b58a0
[Xcode]     t =  1632.01s         Snapshot accessibility hierarchy for com.napa.tbar-staging
[Xcode]     t =  1632.29s     Use cached accessibility hierarchy for com.napa.tbar-staging
[Xcode]     t =  1632.29s     Find: Descendants matching type Keyboard
[Xcode]     t =  1632.40s     Find the Keyboard
[Xcode]     t =  1632.40s         Snapshot accessibility hierarchy for com.napa.tbar-staging
[Xcode]     t =  1632.65s         Find: Descendants matching type Keyboard
[Xcode]     t =  1632.65s         Find: Element at index 0
[Xcode]     t =  1632.65s     Use cached accessibility hierarchy for com.napa.tbar-staging
[Xcode]     t =  1632.66s     Find: Descendants matching type Keyboard
[Xcode]     t =  1632.66s     Find: Element at index 0
[Xcode]     t =  1632.66s     Find the Keyboard
[Xcode]     t =  1632.66s         Use cached accessibility hierarchy for com.napa.tbar-staging
[Xcode]     t =  1632.66s         Find: Descendants matching type Keyboard
[Xcode]     t =  1632.67s         Find: Element at index 0
[Xcode]     t =  1632.67s     Use cached accessibility hierarchy for com.napa.tbar-staging
[Xcode]     t =  1632.67s     Find: Descendants matching type Keyboard
[Xcode]     t =  1632.67s     Find: Element at index 0
[Xcode]     t =  1632.67s     Find the Keyboard
[Xcode]     t =  1632.67s         Use cached accessibility hierarchy for com.napa.tbar-staging
[Xcode]     t =  1632.67s         Find: Descendants ma
[debug] [JSONWP Proxy] Got response with status 200: {"value":"Error Domain=XCTDaemonErrorDomain Code=14 \"Timed out waiting for key event to complete\" UserInfo={NSLocalizedDescription=Timed out waiting for key event to complete}","sessionId":"2C1B0B1D-5C49-47BD-AD2F-9A89E3118455","status":13}
[debug] [JSONWP Proxy] Proxying [GET /element/912F5E5F-9E04-4794-A44B-7A8AA30477D2/attribute/type] to [GET http://localhost:8100/session/2C1B0B1D-5C49-47BD-AD2F-9A89E3118455/element/912F5E5F-9E04-4794-A44B-7A8AA30477D2/attribute/type] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"XCUIElementTypeOther\",\n  \"sessionId\" : \"2C1B0B1D-5C49-47BD-AD2F-9A89E3118455\",\n  \"status\" : 0\n}"
[MJSONWP] Encountered internal error running command: Error: An unknown server-side error occurred while processing the command.
    at JWProxy.command$ (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:176:15)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
[HTTP] <-- POST /wd/hub/session/7b27e490-84b6-40f6-9606-920df1a2ac0b/appium/element/912F5E5F-9E04-4794-A44B-7A8AA30477D2/value 500 65905 ms - 238

**Comment by mykola-mokhnach** [comment]
Please report the issue directly to https://github.com/facebook/WebDriverAgent/issues, because it's not possible to change anything there from Appium.
