### ISSUE TITLE
element found through appium inspector but  getting error"No such element found" when the code runs

### ISSUE THREAD

**Issue by snehabadlani** [appium/appium#9696]
## The problem

There is a "+" button that I want to tap. Appium inspector could locate the element through -xpath("//android.view.View[@resource-id='btnAdd1']") , when I use the same locator strategy in my code(see below) it is giving me error-"No such element found"
 WebElement s1=driver.findElement(By.xpath("//android.view.View[@resource-id='btnAdd1']"));
TouchAction Shirt=new TouchAction((PerformsTouchActions) driver);
Shirt.tap(s1).perform();

## Environment

* Appium version (or git revision) that exhibits the issue:  v1.7.1
* Last Appium version that did not exhibit the issue (if applicable):N/A
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Android 5.1
* Real device or emulator/simulator:Real device-Lenovo
* Appium CLI or Appium.app|exe: 
*Java- client- 5.0.4.jar
*Selenium-Selenium 3.7.1

## Link to Appium logs

https://gist.github.com/snehabadlani/53c6bdaf78a9b354b64a4ca5e7253e44

**Comment by mykola-mokhnach** [comment]
Perhaps, the element is really not there. Try to print the page source right before touch action execution to see what is present on the page.

**Comment by snehabadlani** [comment]
You were right, the element that I was trying to search was hidden.
