### ISSUE TITLE
How to get Device's Network Provider Name in Android and iOS

### ISSUE THREAD

**Issue by Elangopalakrishnan** [appium/appium#9698]
Platform: Android and iOS
Real devices

**Question:**
I need to print mobile internet provider name in my test report.
Does appium provides any capability to get device internet providers name?

Please let me know if any solution ??

Thanks in advance!

**Comment by mykola-mokhnach** [comment]
Currently Appium does not provide any API to get such information

**Comment by Elangopalakrishnan** [comment]
Hi @mykola-mokhnach mykola ,

or at least can we get name of wifi network where the device connected?

Thanks!
