### ISSUE TITLE
Right-hand side of the screen is inaccessible (iOS, XCode 9)

### ISSUE THREAD

**Issue by rg-software** [appium/appium#9700]
## The problem
It is impossible to tap near the right-hand side of the device in landscape orientation. Taps are simply ignored.

## Environment

* Appium 1.7.1 (also tested with 1.7.2b)
* MacOS, Xcode 9+ (tested with 9.0.1 and 9.1) 
* The issue does not appear with Xcode 8.
* iOS 10, iOS 11 (real device)

**Comment by mykola-mokhnach** [comment]
Please provide the example of your client code, server logs and a screenshot.

**Comment by rg-software** [comment]
OK, I will try to collect them, but I am pretty sure that the inaccessible screen area is between "portrait width" and "landscape width". I tried to tap the screen location with x = 950 or so.

**Comment by rg-software** [comment]
Here we go. The app I am testing is a full-screen Unity program. [Here is the screen](https://www.dropbox.com/s/sjgsbickiklcvg8/screenshot-small.png?dl=0) I am interested in. Note that I scaled it to 50% of the original size to match tap coordinates (the original is 2048x1536). In the top of the screen there is the main menu, and I am clicking on all items with this code:

`for x in [100, 200, 300, 420, 530, 650, 760, 880, 990]:`
&nbsp;&nbsp;&nbsp;&nbsp;`driver.tap([(x, 30)])`

What I see is that it taps all the buttons till "Friends", but cannot tap on "Help" and on the gear icon. Instead, the last tap is equivalent to the tap on the "Club" button!

[Appium log](https://www.dropbox.com/s/xtav3huxhav86sd/Appiumlog.txt?dl=0) seems to be fine.

**Comment by mykola-mokhnach** [comment]
Try to tap an element instead of absolute coordinates to workaround that. It's known XCTest bug

**Comment by rg-software** [comment]
Unfortunately, it is impossible: there are no "elements", it is a flat drawing surface with hand-drawn GUI.

**Comment by mykola-mokhnach** [comment]
There should be an element, which represents the surface itself. Try it

**Comment by rg-software** [comment]
Err... how? :) How does it called?

**Comment by rg-software** [comment]
Well, I used Appium iOS inspector to find out that the class I need is `/AppiumAUT/XCUIElementTypeApplication`. 
The main window is already wrong!

![clipboard02](https://user-images.githubusercontent.com/13718460/33303341-fc035aa2-d445-11e7-9c81-c358ac2e50eb.png)

![clipboard01](https://user-images.githubusercontent.com/13718460/33303340-fbde4294-d445-11e7-9308-3d7ff1861bbf.png)

```
screen = driver.find_element_by_class_name("XCUIElementTypeApplication")
action = TouchAction(driver)
action.tap(screen, x, y).perform()
```

seems to work correctly.

**Comment by mykola-mokhnach** [comment]
yep, you see now how broken XCTest is.
