### ISSUE TITLE
My ios app crashes on startup using appium desktop

### ISSUE THREAD

**Issue by Dadddddy** [appium/appium#9701]
## The problem
I'm using appium desktop for ios automation. I have configured the desired capabilities and my app gets installed on the simulator successfully, but on the startup as soon as the splash screen of the app shows up, it crashes. I don't think if there is any problem with my configuration since I have tested appium using a mini ios project cloned from the repository below: 
https://github.com/appium/ios-uicatalog
And I had been able to successfully run the appium inspector with this mini app.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1

* Desktop OS/version used to run Appium: macOS High Sierra version 10.13
* Mobile platform/version under test: ios
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: appium desktop

## Details
I have also enabled the ShowXcodeLog capability  in my logs.

## Link to Appium logs

https://gist.github.com/Dadddddy/adcae1a6cfa2ee917599655245749628

**Comment by mykola-mokhnach** [comment]
Does the same happen if the app is executed manually? Can you also attach simulator logs?

**Comment by Dadddddy** [comment]
Mmmm by executing manually, did U mean running the app on a real device ? 
If so, yes I have tested the app on both real device and Xcode Simulator and it works properly. 
I also hope by simulator logs, U meant the showIOSLog capability, which I have enabled in the logs below:
https://gist.github.com/Dadddddy/434952efe036462bf1ff2ffde7ab55f0

**Comment by mykola-mokhnach** [comment]
> [info] [iOSLog] [IOS_SYSLOG_ROW] Nov 28 15:46:02 Mohammads-MacBook-Pro com.apple.CoreSimulator.SimDevice.9DDCBBAC-39BF-439F-9665-1A95FE5E4B29[63980] (UIKitApplication:ir.snapp.passenger[0x3cd2][64007][64105]): Program specified by service does not contain any valid architectures for this system.[info] [iOSLog] [IOS_SYSLOG_ROW] Nov 28 15:46:02 Mohammads-MacBook-Pro com.apple.CoreSimulator.SimDevice.9DDCBBAC-39BF-439F-9665-1A95FE5E4B29[63980] (UIKitApplication:ir.snapp.passenger[0x4cb][64007][64107]): Program specified by service does not contain any valid architectures for this system.

You need to fix the build for the application under test
