### ISSUE TITLE
[XCUITest] Error: Could not determine iOS SDK version: Command 'xcrun' not found. Is it installed?

### ISSUE THREAD

**Issue by sanatzzz** [appium/appium#9702]
Trying to run Automation in Safari iOS using Safari Launcher and Appium.

Environment
Appium version 1.7.1
Desktop OS/version used to run Appium: macOS High Sierra
Node.js version (unless using Appium.app|exe): v8.9.1
Mobile platform/version under test: iOS 11.1.2
Real device or emulator/simulator: Real Device

Details
xcode-select -p = /Applications/Xcode.app/Contents/Developer
xcrun also runs properly
I have ios_webkit_debug_proxy installed and running on port 27753
Given following environment variables in Eclipse : 
DEVELOPER_DIR = /Applications/Xcode.app/Contents/Developer
PATH = /usr/local/Cellar/libimobiledevice/HEAD-9df4e69/bin

Appium Doctor says Everything Looks good, bye.

Safari Launcher has been built in Xcode signed with iPhone Developer ID and installed on device successfully
 
Link to Appium logs
https://gist.github.com/sanatzzz/1019335406131d0e9e584cababc73855#file-gistfile1-txt

Code To Reproduce Issue :
DesiredCapabilities capabilities = new DesiredCapabilities();
		capabilities.setCapability("platformName", "iOS");
		capabilities.setCapability("platformVersion", "11.1");
		capabilities.setCapability("sdk", "iphoneos11.1");
		capabilities.setCapability("deviceName", "iPhone 6 Plus");
		capabilities.setCapability("termTimeout", 30000);
		capabilities.setCapability("newCommandTimeout", 60);
		capabilities.setCapability("launchTimeout", 180000);
		capabilities.setCapability("udid", "f3123c934dad6b5b326dff90fb05ab6b9d9e6e86");
		capabilities.setCapability("automationName", "XCUITest");
		capabilities.setCapability("browserName", "Safari");
                driver = new RemoteWebDriver(new URL("http://127.0.0.1:4725/wd/hub"), capabilities);

**Comment by ochubey** [comment]
@sanatzzz could you try running xcode-select with sudo:
`sudo /usr/bin/xcode-select -switch /Applications/Xcode.app/Contents/Developer`
One more question: are you running tests from the same Terminal or, for example, from Jenkins job?
May it be that environment from where you running tests is not configured properly? The reason I'm asking - `xcode-select` is also not found according to logs you have provided.

**Comment by mykola-mokhnach** [comment]
Make sure xcrun utility is available in PATH environment variable, which is passed to Appium process.
Closed as not an issue

**Comment by sanatzzz** [comment]
Can you tell how to do it exactly? i am doing this in eclipse

**Comment by sanatzzz** [comment]
I am doing this eclipse and yes I have run that command but no result

**Comment by sanatzzz** [comment]
Also I cannot find xcrun anywhere
