### ISSUE TITLE
Replacement for By.name in android Appium 1.7

### ISSUE THREAD

**Issue by PrasadMadge** [appium/appium#9703]
## The problem

I am having more than 200 test cases running on Appium 1.4.16.
In most of the scripts we have used **By.name** locator extensively as it was working for "**text**" or "**content-desc**".

By.name locator for android was deprecated in Appium 1.5.

I want my existing scripts to work on Appium 1.7 , but By.name is now working as it was removed , which used to work earlier for text or content-desc.

For new version of Appium 1.7
for text:

- driver.findElement(MobileBy.AndroidUIAutomator("new UiSelector().text(\"MY TEXT")")); works fine.

For Content-desc:

- driver.findElementByAccessibilityId("My content desc");

The above two code works fine , but my problem is there any generic method in Appium 1.7 which will work both for text and content-desc as it was working earlier with By.name for text and content-desc ?

Because if I need to migrate my 200 test cases from Appium 1.4 to Appium 1.7 , I need to manually check for each By.name object again whether it was text or content-desc and change accordingly.

Any suggestions or help would be highly appreciated.

## Environment

* Appium version (1.7.1) :
* Last Appium version that did not exhibit the issue (1.4.16):
* Windows 7
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version : Android 7 , 6 for native application.
* Real device.

**Comment by mykola-mokhnach** [comment]
Unfortunately there is no universal method. You have to think about moving out from locators of type _AndroidUIAutomator_, since UIObject does not work well with never Android versions.

**Comment by PrasadMadge** [comment]
So how can we locate an element having text without xpath in newer versions ?

For resource-id there is By.id
For content-desc there is By.accessibilityId
For text ? without AndroidUIAutomator ?
