### ISSUE TITLE
background_app not working when start_activity is used

### ISSUE THREAD

**Issue by yahman72** [appium/appium#9704]
## The problem
This sequence breaks appium:
1. launch App --> "main" App is started
2. start activity from another app --> 2nd App is started
3. background_app --> FAIL (wrong app in focus)

## Environment

* Appium version (or git revision) that exhibits the issue: v1.6.5
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): v6.11.1
* Mobile platform/version under test: Android 5.0
* Real device or emulator/simulator: Real device (Huawei Y5 II)
* Appium CLI or Appium.app|exe: CLI

## Details

The problem clearly visible in the logs:
1. launch phone app --> "com.android.contacts/.activities.DialtactsActivity" is started
2. start activity e.g. clock app --> "com.android.deskclock/.AlarmsMainActivity" is started
3. background_app --> Things go wrong here
   - the app is put into background ("keycode BACK") - correct
   - putting the app back to foreground fails completely:
     + appium refocuses the "com.android.contacts/.activities.DialtactsActivity"
     + but fails, because it's waiting for the "com.android.deskclock/.AlarmsMainActivity" to get the focus, 
<pre>
2017-11-27 10:42:24:730 - [debug] [ADB] Running 'c:\ta\droid\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","HMNBBCB681926996","shell","am","start","-W","-n","com.android.contacts/.activities.DialtactsActivity","-a","android.intent.action.DIAL","-c","android.intent.category.LAUNCHER","-f","0x10200000","-W"]
2017-11-27 10:42:25:664 - [debug] [ADB] Waiting for activity matching pkg: 'com.android.deskclock' and activity: '.AlarmsMainActivity' to be focused
2017-11-27 10:42:25:668 - [debug] [ADB] Possible activities, to be checked: com.android.deskclock.AlarmsMainActivity
</pre>

Expected behaviour is:
PREFERRED - do this with the currently active app
   - put app into background ("keycode BACK")
   - get the correct app back to foreground:
     + refocus the "com.android.deskclock/.AlarmsMainActivity"
     + and waiting for the "com.android.deskclock/.AlarmsMainActivity" to get the focus, 

OR - do this with "original" app i.e. the one from the original DC:
   - put app into background ("keycode BACK")
   - get the correct app back to foreground:
     + refocus the "com.android.contacts/.activities.DialtactsActivity"
     + and waiting for the "com.android.contacts/.activities.DialtactsActivity" to get the focus, 

## Link to Appium logs
Full log: https://gist.github.com/yahman72/42f74f170097a01b4e8396fb97de1b61

## Code To Reproduce Issue [ Good To Have ]

```
from appium import webdriver as appium_webdriver
from appium.webdriver.mobilecommand import MobileCommand as Command
import time


APPIUM_URL = 'http://localhost:4724/wd/hub'

dc_clock = {
    'appPackage': 'com.android.deskclock',
    'appActivity': '.AlarmsMainActivity',
    'optionalIntentArguments': "-W"
    }

dc_phone = {
    'dontStopAppOnReset': False,
    'alias': u'Dummy',
    'browserName': '',
    'udid': u'HMNBBCB681926996',
    'deviceName': u'Dummy',
    'appPackage': 'com.android.contacts',
    'platformName': 'Android',
    'appActivity': '.activities.DialtactsActivity',
    'noReset': True,
    'intentAction': 'android.intent.action.DIAL',
    'optionalIntentArguments': "-W"
    }

def open_session():
    driver = appium_webdriver.Remote(APPIUM_URL, dc_phone)
    time.sleep(1)
    driver.execute(Command.START_ACTIVITY, dc_clock)
    time.sleep(1)
    driver.background_app(1)

open_session()
```

**Comment by imurchie** [comment]
Yes, the current situation is odd. It assumes you don't leave the original app.

I will look into this.

**Comment by yahman72** [comment]
FYI: I was playing with the phone/dialler app to test this - when initiating a call the dialer app opens a "inCallUI" app i.e. I end up in the same situation without `start_activity` because the `background_app` puts the dialer/phone app in the background, not the inCallUI app ---> It would be best if the `background_app` figures out which app is in foreground and background that one.

PS. 
this might produce odd behaviour also with `close_app()` - I'd assume that `close_app` after `start_activity` would close the started activity.

**Comment by mykola-mokhnach** [comment]
This should be addressed in appium@beta
