### ISSUE TITLE
[iOS11.1] [Xcode 9.1] Attempted to get a list of webview contexts but could not connect to ios-webkit-debug-proxy.If you expect to find webviews, please ensure that the proxy is running and accessible

### ISSUE THREAD

**Issue by anshu1987** [appium/appium#9706]
## The problem
I am trying to Run Mobile Web Based version of my application on Safari with iOS 11.1 and X Code 9.1.
I have done all configuration required to run on iOS 11.1 as mentioned in other blog post.When I trigger the test I am able to navigate to appium.io site but after that it doesn't navigate to desired URL.
Successfully able to execute test on simulator.

I am attaching the full copy of logs but major highlights but providing some lines that can help to get the issue resolution faster:

**[debug] [iOS] No web frames found.
[debug] [iOS] Retrieving contexts and views
[debug] [iOS] Selecting by url: true (expected url: 'http://appium.io')
[debug] [RemoteDebugger] Getting WebKitRemoteDebugger pageArray: localhost, 27753
[debug] [RemoteDebugger] Sending request to: http://localhost:27753/json
[iOS] Attempted to get a list of webview contexts but could not connect to ios-webkit-debug-proxy. If you expect to find webviews, please ensure that the proxy is running and accessible**

## Environment

* Appium version (or git revision) that exhibits the issue:1.7
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS (10.12.1)
* Node.js version (unless using Appium.app|exe):
 npm -v
5.5.1
node -v
v9.2.0
nvm --version
0.33.6

* Mobile platform/version under test: iOS 11.1 
* Real device or emulator/simulator: iPhone 7
* Appium CLI or Appium.app|exe:

## Details
I have browsed to following link but not able to get thru the issue.
https://github.com/google/ios-webkit-debug-proxy/issues/181
https://github.com/libimobiledevice/ideviceinstaller/issues/47
https://github.com/libimobiledevice/libimobiledevice/issues/510
https://github.com/appium/appium/issues/6970

Also I am attaching two Snap Shot of Web Kit Proxy:
<img width="772" alt="web kit proxy on 9222" src="https://user-images.githubusercontent.com/4101167/33266119-4a234294-d39a-11e7-9378-e93122b19eae.png">
<img width="760" alt="web kit proxy on 27753" src="https://user-images.githubusercontent.com/4101167/33266121-4ab1dfea-d39a-11e7-8cfc-f960b65c69b9.png">

Once i tried command : 
**ios_webkit_debug_proxy -c UID:9222 -d**
It gives following output:
ss.add_fd(3)
ss.recv fd=3 len=294
ss.recv fd=3 len=684
ss.add_server_fd(4)
ss.add_fd(6)
wi.send_packet[174]:
 00 00 00 AA 62 70 6C 69 73 74 30 30 D2 01 03 02 04 5A 5F  ....bplist00.....Z_
 5F 73 65 6C 65 63 74 6F 72 5F 10 16 5F 72 70 63 5F 72 65  _selector_.._rpc_re
 70 6F 72 74 49 64 65 6E 74 69 66 69 65 72 3A 5A 5F 5F 61  portIdentifier:Z__a
 72 67 75 6D 65 6E 74 D1 05 06 5F 10 1A 57 49 52 43 6F 6E  rgument..._..WIRCon
 6E 65 63 74 69 6F 6E 49 64 65 6E 74 69 66 69 65 72 4B 65  nectionIdentifierKe
 79 5F 10 24 35 30 30 30 44 34 32 33 2D 31 39 30 43 2D 34  y_.$5000D423-190C-4
 42 44 41 2D 42 31 41 31 2D 34 34 31 46 38 36 41 43 45 44  BDA-B1A1-441F86ACED
 37 35 08 0D 18 31 3C 3F 5C 00 00 00 00 00 00 01 01 00 00  75...1<?\..........
 00 00 00 00 00 07 00 00 00 00 00 00 00 00 00 00 00 00 00  ...................
 00 00 83                                                  ...
ss.recv fd=6 len=554
wi.recv[554]:

When I tried following command
**ios_webkit_debug_proxy -c UID:27753 -d**
I got the following output:
ss.add_fd(3)
ss.recv fd=3 len=294
ss.recv fd=3 len=684
ss.add_server_fd(4)
Could not connect to lockdownd. Exiting.: Resource temporarily unavailable
ss.remove_server_fd(4)
Unable to attach e4beabe07ecb36592a4173b724ca64b4b2c24789 inspector

## Link to Appium logs

Link to Appium Logs : https://gist.github.com/anshu1987/319c75dae7b16362ecad3e1d54ad0064

@imurchie @Nikias Bassen

**Comment by mykola-mokhnach** [comment]
> ios_webkit_debug_proxy -c UID:27753 -d
> I got the following output:
> ss.add_fd(3)
> ss.recv fd=3 len=294
> ss.recv fd=3 len=684
> ss.add_server_fd(4)
> Could not connect to lockdownd. Exiting.: Resource temporarily unavailable
> ss.remove_server_fd(4)
> Unable to attach e4beabe07ecb36592a4173b724ca64b4b2c24789 inspector

This is the problem with webkit proxy itself. It cannot gain access to lockdown socket. Try to look for a solution on their forum.

Closed as non Appium-related.

**Comment by anshu1987** [comment]
Thanks for the update @mykola-mokhnach  , the issue get resolved.

**Comment by MathuMarques** [comment]
How did you solved the case @anshu1987 ?
