### ISSUE TITLE
Android 5.1.1 Click on webpage, but nothing happened after successful click

### ISSUE THREAD

**Issue by isnifer** [appium/appium#9707]
## The problem
![android_5_stripe_site](https://user-images.githubusercontent.com/1788245/33266332-3d2ca0c6-d386-11e7-8300-f886a02fa12b.gif)

## Environment

* Appium version (or git revision) that exhibits the issue: >= 1.6.4
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS Sierra 10.12.6
* Node.js version (unless using Appium.app|exe): v8.6.0
* Mobile platform/version under test: Android 5.1.1
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: CLI

**Comment by isnifer** [comment]
Looks like similar https://github.com/appium/appium/issues/8637

**Comment by mykola-mokhnach** [comment]
Perhaps the automated click does not trigger some event, which is expected by the particular page. I'd  connect to the page with an external javascript debugger to compare the events chain generated after manual and automated click to find differences.

**Comment by isnifer** [comment]
@mykola-mokhnach on iOS everything is fine :)

**[Appium Log for Android](https://gist.github.com/isnifer/096b60893e61e0dd8027eb5a1a3660f8)**

**Comment by isnifer** [comment]
@mykola-mokhnach cause It's only test payments - get [link](https://stripe.com/sources/test_source?amount=50&currency=eur&livemode=false&return_url=https%3A%2F%2Fhooks.stripe.com%2Fadapter%2Falipay%2Fredirect%2Fcomplete%2Fsrc_1BSmTUI5NuVQgnjeQ3ERgTS6%2Fsrc_client_secret_BqTQYwd0VTwsFyDAD1Xh5i6d&source=src_1BSmTUI5NuVQgnjeQ3ERgTS6&type=alipay&usage=single_use) for the page

**Comment by isnifer** [comment]
Just tested on Android 7, it works:
![android_7_stripe_site_log](https://user-images.githubusercontent.com/1788245/33270169-2663cb5e-d394-11e7-84cd-c3af3f31cef8.gif)

**Comment by julia0423** [comment]
does it can click element in chrome browser? now in Android 7 with uiautomator2 can not find element in chrome browser

**Comment by Joskony** [comment]
> Perhaps the automated click does not trigger some event (...)

@mykola-mokhnach Is something like that possible? Because I have a similar issue where I click a button which triggers other buttons to appear but they don't. But when I do it manually it works. On desktop with Selenium everything works fine, but it doesn't with Appium.

**Comment by isnifer** [comment]
@julia0423 I don't have Chrome on 5.1.1 emulator, can't answer to your question

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
