### ISSUE TITLE
Installation problem - ANDROID_HOME  is not set

### ISSUE THREAD

**Issue by idan72** [appium/appium#9708]
Hi,

I am trying to set up appium on windows 10.
When I run appium-doctor I go the below.
When I try to start the session  with this configuration I am getting error.
Also when try to run test from eclipse.

Thanks

{
  "platformName": "Android",
  "deviceName": "Android Emulator",
  "app": "C:\\Users\\idan.shay\\Downloads\\ApiDemos-debug.apk"
}

Error :
An unknown server-side error occurred while processing the command. Original error: Could not find adb Please set the ANDROID_HOME environment variable with the Android SDK root directory path.

C:\>appium-doctor --android
info AppiumDoctor Appium Doctor v.1.4.3
info AppiumDoctor ### Diagnostic starting ###
info AppiumDoctor  ✔ The Node.js binary was found at: C:\Program Files\nodejs\node.exe
info AppiumDoctor  ✔ Node version is 6.9.0
info AppiumDoctor  ✔ ANDROID_HOME is set to: C:\Users\idan.shay\AppData\Local\Android\Sdk
info AppiumDoctor  ✔ JAVA_HOME is set to: C:\Program Files\Java\jdk1.8.0_77
info AppiumDoctor  ✔ adb exists at: C:\Users\idan.shay\AppData\Local\Android\Sdk\platform-tools\adb.exe
info AppiumDoctor  ✔ android exists at: C:\Users\idan.shay\AppData\Local\Android\Sdk\tools\android.bat
info AppiumDoctor  ✔ emulator exists at: C:\Users\idan.shay\AppData\Local\Android\Sdk\tools\emulator.exe
info AppiumDoctor  ✔ Bin directory of %JAVA_HOME% is set
info AppiumDoctor ### Diagnostic completed, no fix needed. ###
info AppiumDoctor
info AppiumDoctor Everything looks good, bye!
info AppiumDoctor

![image](https://user-images.githubusercontent.com/228691/33270254-16180b1e-d38c-11e7-8fbe-7803fcabdf68.png)

![image](https://user-images.githubusercontent.com/228691/33270247-0eb35dc4-d38c-11e7-8191-baf13380c5ad.png)

**Comment by mykola-mokhnach** [comment]
https://stackoverflow.com/questions/23042638/how-do-i-set-android-sdk-home-environment-variable

**Comment by idan72** [comment]
According to the appium-doctor it is set correctly.
I add also ANDROID_SDK_HOME but it stll not working

**Comment by mykola-mokhnach** [comment]
Then it is not picked up by Appium server for some reason. Or adb binary itself is missing by that path.

**Comment by idan72** [comment]
When I run the sdkmanager I got :
C:\Users\idan.shay\AppData\Local\Android\Sdk\tools\bin>sdkmanager.bat
Warning: File C:\Users\idan.shay\.android\repositories.cfg could not be loaded.
[=======================================] 100% Computing updates...

I try to install from https://saucelabs.com/resources/articles/appium-bootcamp-chapter-1
but it is not clear how to install on windows.
