### ISSUE TITLE
Unable to create WDA session with iOS real device

### ISSUE THREAD

**Issue by vighneshpai-yml** [appium/appium#9709]
## The problem
I'm not able to run the scripts via command line, however, I'm able to set few desired capabilities in appium tool and successfully rin it from there!

## Environment
* Appium version: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: Version 1.2.7 (1.2.7)
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium.app (on mac High Sierra 10.13.1)

##Details
 1. I tried restarting the device, appium and system as well. But no luck.
2. I have generated that build myself, so its not a simulator build or something. It's a properly signed build.
3. The device is in provision profile, so it's not the issue.
4. I checked if any other process is using the port or something but it's not.

## Link to Appium logs
Link to appium logs gist: https://gist.github.com/vighneshpai-yml/be331f43c8640ee2626c80a85537c199

##Capabilities i'm setting:
def start_app(device_name, wdalocalport, device_udid,localport, filename)
  caps_config = {
      platformName: "iOS",
      deviceName: device_name, #update device as per your need
      app: (File.join(File.dirname(__FILE__), filename)),
      bundleId: "com.ymedialabs.devteam", #Mention the bundleid of your application
      automationName: "XCUITest",
      xcodeOrgId: "849UP4BSN8",
      xcodeSigningId: "iPhone Developer",
      Runner: "Distribute",
      noReset: "false",
      fullReset: "true",
      showIOSLog: "true",
      autoAcceptAlerts: "true",
      showXcodeLog: "true",
      useNewWDA: "false",
      resetOnSessionStartOnly: "true",
      timeout: "30000",
      udid: device_udid,
      webDriverAgentUrl: wdalocalport }
  appium_lib_config = {port: localport}
  $opts={ caps: caps_config, appium_lib: appium_lib_config}
  setup
end

Any help solving this problem will be appreciated.

**Comment by mykola-mokhnach** [comment]
There is a mess in capabilities. webDriverAgentUrl if provided should contain full address of running WebDriverAgent server

**Comment by ochubey** [comment]
I believe the following capability might case an issue: "webDriverAgentUrl":"8200"
You providing port number, but expected url

**Comment by vighneshpai-yml** [comment]
@mykola-mokhnach & @ochubey thanks for the info. I got it corrected and it's working now.
