### ISSUE TITLE
UI Automator Viewer showing incorrect position of the button, Unable to Click on popup button.

### ISSUE THREAD

**Issue by Farazhasan** [appium/appium#9710]
I need to click on Ok button which came after Registration, when i try to find ok button in UI Automator Viewer it gives me incorrect button position.. (Screenshot attached) for UI Automator Viewer

_Driver.findElement(By.id("confirm_button")).click();_

When i try to run the above command, It click on the **Tick Icon** showing in screenshot. instead of clicking Ok button. 
please help in this regards.
Thanks
![image](https://user-images.githubusercontent.com/34036624/33282452-923b34e4-d3ca-11e7-9a12-8393b6fdd425.png)

**Comment by mykola-mokhnach** [comment]
Please report this issue to Google. UIAutomationViewer is not part of Appium.
