### ISSUE TITLE
ClearText is not clearing the complete text field in specific Android versions

### ISSUE THREAD

**Issue by VinnieM** [appium/appium#9713]
## The problem
I am using webDriver.io, and the clearElement() function to clear the text of a prefilled textField does not work on all platforms of Android. The function does not clear the complete text. At first it seems the complete text is erased, but a part of the text is preserved and the preserved part gets appended to the end of the new text which is being entered.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7, using webdriver.io 4.9.8
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: Mac OS High Sierra
* Node.js version (unless using Appium.app|exe): 6.11.4
* Mobile platform/version under test: Android 6 (Moto X) and 8 (Google Pixel 1) (Working fine on the Samsung Galaxy S8)
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: CLI

## Details
I am using webDriver to automate Android and iOS devices. I am using actual non-rooted devices for testing the apps. The issue was spotted on Moto X Phones running Android 6 and Pixel Phones Running Android 8. The same issue is not happening on Samsung Galaxy S8 phones.

PS: This is what the webdriver folks had to say https://github.com/webdriverio/webdriverio/issues/2485#issuecomment-347638768

## Link to Appium logs
Please let me know what kind of logs you would need and I would be happy to provide them.

## Code To Reproduce Issue [ Good To Have ]

I shall try to make a hello world sorta application and give you the link.

**Comment by mykola-mokhnach** [comment]
Switch to UIAutomator2 backend if you still use UIA1

**Comment by imurchie** [comment]
Can you provide the full server logs as a link to a [gist](https://gist.github.com) so that we might be able to determine what is going on?

**Comment by VinnieM** [comment]
Will try with UIAutomator2 and shall provide the server logs as well by tomorrow.

**Comment by VinnieM** [comment]
Tried with UIAutomator2, still the same behavior. I have the the logs, let me know if you need any more details.

https://gist.github.com/VinnieM/b84c7da3ffc0e10a0b2510f8636db466

**Comment by mykola-mokhnach** [comment]
It might be you trying to clear some wrong element. Make sure your locator matches a text edit and not its container view.

**Comment by VinnieM** [comment]
@mykola-mokhnach It does clear the entire text. But after the text is cleared, and the new text is entered, a part of the old text is being appended at the end to the text which is being entered, so it's unlikely it's trying to clear the wrong element.

**Comment by VinnieM** [comment]
I have got an update. The clearText is clearing the entire content. But the actual problem seems to be with setImmediateValue(). The setValue() is setting the new text properly. Is this a known issue?

**Comment by mykola-mokhnach** [comment]
Closed as inactive
