### ISSUE TITLE
problem sending data in android app native

### ISSUE THREAD

**Issue by JhonShell** [appium/appium#9714]
## The problem
hi guys, some of here to used appium I am having problem with the change of pointer in android app native, I send the mail but when I try to send and work correctly, but when I try to send the password and the mail, only the mail is written, the password, and already check the time.sleep () but the problem continues

the elements are located correctly, but when trying to send password an email, I only manage to send with send_keys the mail, the password only locates and the keyboard appears. and not send the password

regards

desired_caps = {}
	desired_caps['platformName'] = 'Android'
	desired_caps['platformVersion'] = '6.0.1'
	desired_caps['deviceName'] = 'Android Emulator'
	#desired_caps['app'] = PATH('../../Desktop/appium/my.apk')
	desired_caps['appPackage'] = 'com.pachages'
'
	desired_caps['appActivity'] = 'com.activi''
	
	driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)
	time.sleep(20)
	el1 = driver.find_element_by_xpath("/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup[3]").send_keys("p@mail.com")
	time.sleep(5)
	
	el2 = driver.find_element_by_xpath("/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup[5]").send_keys("password")
	
	time.sleep(60)
	
	driver.quit()

[~/Desktop/appium]
└──╼ $app
apparmor_parser     appletviewer
apparmor_status     applygnupgdefaults
appium              appres
appium-doctor       
[~/Desktop/appium]
└──╼ $app
apparmor_parser     appletviewer
apparmor_status     applygnupgdefaults
appium              appres
appium-doctor       
┌─ktop/appium]
└──╼ $app
apparmor_parser     appletviewer
apparmor_status     applygnupgdefaults
appium              appres
appium-doctor       
┌─
└──╼ $appium
[Appium] Welcome to Appium v1.7.1
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"capabilities":{"alwaysMatch":{"platformName":"Android"},"firstMatch":[{}]},"desiredCapabilities":{"platformVersion":"6.0","deviceName":"Android Emulator","platformName":"Android","appActivity":"","appPackage":""}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformVersion":"6.0","deviceName":"Android Emulator","platformName":"Android","appActivity":","appPackage":""},null,{"alwaysMatch":{"platformName":"Android"},"firstMatch":[{}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1511916017156 (20:40:17 GMT-0400 (AST))
[Appium] Creating new AndroidDriver (v1.28.1) session
[Appium] Capabilities:
[Appium]   platformVersion: '6.0'
[Appium]   deviceName: 'Android Emulator'
[Appium]   platformName: 'Android'
[Appium]   appActivity: 'com.facebook.lite.MainActivity'
[Appium]   appPackage: 'com.facebook.lite'
[BaseDriver] Session created with session id: 4992d863-965f-4152-a27e-9ff2b0cb799b
[debug] [AndroidDriver] Getting Java version
[AndroidDriver] Java version is: 1.8.0_144
[ADB] Checking whether adb is present
[ADB] Using adb from /usr/share/android-sdk/platform-tools/adb
[AndroidDriver] Retrieving device list
[debug] [ADB] Trying to find a connected android device
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[AndroidDriver] Looking for a device with Android '6.0'
[debug] [ADB] Setting device id to 192.168.56.101:5555
[ADB] Getting device platform version
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/usr/share/android-sdk/platform-tools/adb' with args: ["-P",5037,"-s","192.168.56.101:5555","shell","getprop","ro.build.version.release"]
[debug] [ADB] Current device property 'ro.build.version.release': 6.0
[AndroidDriver] Using device: 192.168.56.101:5555
[ADB] Checking whether adb is present
[ADB] Using adb from /usr/share/android-sdk/platform-tools/adb
[debug] [ADB] Setting device id to 192.168.56.101:5555
[AndroidDriver] App file was not listed, instead we're going to run com.facebook.lite directly on the device
[debug] [AndroidDriver] Checking whether package is present on the device
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/usr/share/android-sdk/platform-tools/adb' with args: ["-P",5037,"-s","192.168.56.101:5555","shell","pm","list","packages",""]
[AndroidDriver] Starting Android session
[debug] [ADB] Running '/usr/share/android-sdk/platform-tools/adb' with args: ["-P",5037,"-s","192.168.56.101:5555","wait-for-device"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/usr/share/android-sdk/platform-tools/adb' with args: ["-P",5037,"-s","192.168.56.101:5555","shell","echo","ping"]
[debug] [Logcat] Starting logcat capture
[debug] [AndroidDriver] Pushing settings apk to device...
[debug] [ADB] Uninstalling and re-installing 'io.appium.settings'
[debug] [ADB] Uninstalling io.appium.settings
[debug] [ADB] Getting install status for io.appium.settings
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/usr/share/android-sdk/platform-tools/adb' with args: ["-P",5037,"-s","192.168.56.101:5555","shell","pm","list","packages","io.appium.settings"]
[debug] [ADB] App is installed
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/usr/share/android-sdk/platform-tools/adb' with args: ["-P",5037,"-s","192.168.56.101:5555","shell","am","force-stop","io.appium.settings"]
[debug] [ADB] Running '/usr/share/android-sdk/platform-tools/adb' with args: ["-P",5037,"-s","192.168.56.101:5555","uninstall","io.appium.settings"]
[debug] [ADB] ADB command output: Success
[ADB] io.appium.settings was successfully uninstalled
[debug] [ADB] Getting install status for io.appium.settings
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/usr/share/android-sdk/platform-tools/adb' with args: ["-P",5037,"-s","192.168.56.101:5555","shell","pm","list","packages","io.appium.settings"]
[debug] [ADB] App is not installed
[debug] [ADB] App '/usr/lib/node_modules/appium/node_modules/io.appium.settings/app/build/outputs/apk/settings_apk-debug.apk' not installed. Installing
[debug] [ADB] Running '/usr/share/android-sdk/platform-tools/adb' with args: ["-P",5037,"-s","192.168.56.101:5555","install","/usr/lib/node_modules/appium/node_modules/io.appium.settings/app/build/outputs/apk/settings_apk-debug.apk"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/usr/share/android-sdk/platform-tools/adb' with args: ["-P",5037,"-s","192.168.56.101:5555","shell","getprop","ro.build.version.sdk"]
[debug] [ADB] Current device property 'ro.build.version.sdk': 23
[debug] [ADB] Device API level: 23
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/usr/share/android-sdk/platform-tools/adb' with args: ["-P",5037,"-s","192.168.56.101:5555","shell","dumpsys","package","io.appium.settings"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/usr/share/android-sdk/platform-tools/adb' with args: ["-P",5037,"-s","192.168.56.101:5555","shell","pm","dump","io.appium.settings"]
[debug] [ADB] Got the following command chunks to execute: pm,grant,io.appium.settings,android.permission.CHANGE_NETWORK_STATE,;,pm,grant,io.appium.settings,android.permission.READ_PHONE_STATE,;,pm,grant,io.appium.settings,android.permission.WRITE_SETTINGS,;,pm,grant,io.appium.settings,android.permission.ACCESS_FINE_LOCATION,;,pm,grant,io.appium.settings,android.permission.ACCESS_COARSE_LOCATION,;,pm,grant,io.appium.settings,android.permission.ACCESS_MOCK_LOCATION,;,pm,grant,io.appium.settings,android.permission.SET_ANIMATION_SCALE,;
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/usr/share/android-sdk/platform-tools/adb' with args: ["-P",5037,"-s","192.168.56.101:5555","shell","pm","grant","io.appium.settings","android.permission.CHANGE_NETWORK_STATE",";","pm","grant","io.appium.settings","android.permission.READ_PHONE_STATE",";","pm","grant","io.appium.settings","android.permission.WRITE_SETTINGS",";","pm","grant","io.appium.settings","android.permission.ACCESS_FINE_LOCATION",";","pm","grant","io.appium.settings","android.permission.ACCESS_COARSE_LOCATION",";","pm","grant","io.appium.settings","android.permission.ACCESS_MOCK_LOCATION",";","pm","grant","io.appium.settings","android.permission.SET_ANIMATION_SCALE",";"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/usr/share/android-sdk/platform-tools/adb' with args: ["-P",5037,"-s","192.168.56.101:5555","shell","ps"]
[debug] [ADB] Device API level: 23
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/usr/share/android-sdk/platform-tools/adb' with args: ["-P",5037,"-s","192.168.56.101:5555","shell","am","start","-W","-n","io.appium.settings/.Settings","-a","android.intent.action.MAIN","-c","android.intent.category.LAUNCHER","-f","0x10200000"]
[debug] [ADB] Device API level: 23
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/usr/share/android-sdk/platform-tools/adb' with args: ["-P",5037,"-s","192.168.56.101:5555","shell","appops","set","io.appium.settings","android:mock_location","allow"]
[debug] [AndroidDriver] Pushing unlock helper app to device...
[debug] [ADB] Running '/usr/share/android-sdk/platform-tools/adb' with args: ["-P",5037,"-s","192.168.56.101:5555","install","/usr/lib/node_modules/appium/node_modules/appium-unlock/bin/unlock_apk-debug.apk"]
[ADB] Getting device platform version
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/usr/share/android-sdk/platform-tools/adb' with args: ["-P",5037,"-s","192.168.56.101:5555","shell","getprop","ro.build.version.release"]
[debug] [ADB] Current device property 'ro.build.version.release': 6.0
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/usr/share/android-sdk/platform-tools/adb' with args: ["-P",5037,"-s","192.168.56.101:5555","shell","wm","size"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/usr/share/android-sdk/platform-tools/adb' with args: ["-P",5037,"-s","192.168.56.101:5555","shell","getprop","ro.product.model"]
[debug] [ADB] Current device property 'ro.product.model': Samsung Galaxy S6 - 6.0.0 - API 23 - 1440x2560
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/usr/share/android-sdk/platform-tools/adb' with args: ["-P",5037,"-s","192.168.56.101:5555","shell","getprop","ro.product.manufacturer"]
[debug] [ADB] Current device property 'ro.product.manufacturer': Genymotion
[AndroidDriver] No app sent in, not parsing package/activity
[debug] [AndroidDriver] No app capability. Assuming it is already on the device
[debug] [AndroidDriver] Running fast reset (stop and clear)
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/usr/share/android-sdk/platform-tools/adb' with args: ["-P",5037,"-s","192.168.56.101:5555","shell","am","force-stop","com.facebook.lite"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/usr/share/android-sdk/platform-tools/adb' with args: ["-P",5037,"-s","192.168.56.101:5555","shell","pm","clear","com.facebook.lite"]
[debug] [AndroidBootstrap] Watching for bootstrap disconnect
[debug] [ADB] Forwarding system: 4724 to device: 4724
[debug] [ADB] Running '/usr/share/android-sdk/platform-tools/adb' with args: ["-P",5037,"-s","192.168.56.101:5555","forward","tcp:4724","tcp:4724"]
[debug] [UiAutomator] Starting UiAutomator
[debug] [UiAutomator] Moving to state 'starting'
[debug] [UiAutomator] Parsing uiautomator jar
[debug] [UiAutomator] Found jar name: 'AppiumBootstrap.jar'
[debug] [ADB] Running '/usr/share/android-sdk/platform-tools/adb' with args: ["-P",5037,"-s","192.168.56.101:5555","push","/usr/lib/node_modules/appium/node_modules/appium-android-bootstrap/bootstrap/bin/AppiumBootstrap.jar","/data/local/tmp/"]
[debug] [ADB] Attempting to kill all uiautomator processes
[debug] [ADB] Getting all processes with uiautomator
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/usr/share/android-sdk/platform-tools/adb' with args: ["-P",5037,"-s","192.168.56.101:5555","shell","ps"]
[ADB] No uiautomator process found to kill, continuing...
[debug] [UiAutomator] Starting UIAutomator
[debug] [ADB] Creating ADB subprocess with args: ["-P",5037,"-s","192.168.56.101:5555","shell","uiautomator","runtest","AppiumBootstrap.jar","-c","io.appium.android.bootstrap.Bootstrap","-e","pkg","","-e","disableAndroidWatchers",false,"-e","acceptSslCerts",false]
[debug] [UiAutomator] Moving to state 'online'
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Loading json...
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] json loading complete.
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Registered crash watchers.
[AndroidBootstrap] Android bootstrap socket is now connected
[debug] [ADB] Getting connected devices...
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Client connected
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/usr/share/android-sdk/platform-tools/adb' with args: ["-P",5037,"-s","192.168.56.101:5555","shell","dumpsys","window"]
[AndroidDriver] Screen already unlocked, doing nothing
[debug] [ADB] Device API level: 23
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/usr/share/android-sdk/platform-tools/adb' with args: ["-P",5037,"-s","192.168.56.101:5555","shell","am","start","-W","-n","","-S","-a","android.intent.action.MAIN","-c","android.intent.category.LAUNCHER","-f","0x10200000"]
[Appium] New AndroidDriver session created successfully, session 4992d863-965f-4152-a27e-9ff2b0cb799b added to master session list
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1511916035822 (20:40:35 GMT-0400 (AST))
[debug] [MJSONWP] Responding to client with driver.createSession() result: {"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"platformVersion":"6.0","deviceName":"Android Emulator","platformName":"Android","appActivity":"","appPackage":""},"platformVersion":"6.0","deviceName":"192.168.56.101:5555","platformName":"Android","appActivity":"ge":"","deviceUDID":"192.168.56.101:5555","deviceScreenSize":"1440x2560","deviceModel":"Samsung Galaxy S6 - 6.0.0 - API 23 - 1440x2560","deviceManufacturer":"Genymotion"}
[HTTP] <-- POST /wd/hub/session 200 18689 ms - 767 
[HTTP] --> POST /wd/hub/session/4992d863-965f-4152-a27e-9ff2b0cb799b/element {"using":"xpath","sessionId":"4992d863-965f-4152-a27e-9ff2b0cb799b","value":"/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup[3]"}
[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["xpath","/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup[3]","4992d863-965f-4152-a27e-9ff2b0cb799b"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup[3]","context":"","multiple":false}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup[3]","context":"","multiple":false}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: find
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding '/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup[3]' using 'XPATH' with the contextId: '' multiple: false
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[CLASS=android.view.ViewGroup, INSTANCE=3]
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":{"ELEMENT":"1"}}
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"1"}
[HTTP] <-- POST /wd/hub/session/4992d863-965f-4152-a27e-9ff2b0cb799b/element 200 98 ms - 87 
[HTTP] --> POST /wd/hub/session/4992d863-965f-4152-a27e-9ff2b0cb799b/element/1/value {"text":"p@mail.com","sessionId":"4992d863-965f-4152-a27e-9ff2b0cb799b","id":"1","value":["p","@","m","a","i","l",".","c","o","m"]}
[debug] [MJSONWP] Calling AppiumDriver.setValue() with args: [["p","@","m","a","i","l",".","c","o","m"],"1","4992d863-965f-4152-a27e-9ff2b0cb799b"]
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"element:setText","params":{"elementId":"1","text":"p@mail.com","replace":false}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:setText","params":{"elementId":"1","text":"p@mail.com","replace":false}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: setText
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using element passed in: 1
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Attempting to clear using UiObject.clearText().
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Sending plain text to element: p@mail.com
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":true}
[debug] [MJSONWP] Responding to client with driver.setValue() result: true
[HTTP] <-- POST /wd/hub/session/4992d863-965f-4152-a27e-9ff2b0cb799b/element/1/value 200 10483 ms - 76 
[HTTP] --> POST /wd/hub/session/4992d863-965f-4152-a27e-9ff2b0cb799b/element {"using":"xpath","sessionId":"4992d863-965f-4152-a27e-9ff2b0cb799b","value":"/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup[5]"}
[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["xpath","/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup[5]","4992d863-965f-4152-a27e-9ff2b0cb799b"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup[5]","context":"","multiple":false}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup[5]","context":"","multiple":false}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: find
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding '/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup[5]' using 'XPATH' with the contextId: '' multiple: false
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[CLASS=android.view.ViewGroup, INSTANCE=5]
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"2"}
[HTTP] <-- POST /wd/hub/session/4992d863-965f-4152-a27e-9ff2b0cb799b/element 200 70 ms - 87 
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":{"ELEMENT":"2"}}
[HTTP] --> POST /wd/hub/session/4992d863-965f-4152-a27e-9ff2b0cb799b/element/2/value {"text":"password","sessionId":"4992d863-965f-4152-a27e-9ff2b0cb799b","id":"2","value":["p","a","s","s","w","o","r","d"]}
[debug] [MJSONWP] Calling AppiumDriver.setValue() with args: [["p","a","s","s","w","o","r","d"],"2","4992d863-965f-4152-a27e-9ff2b0cb799b"]
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"element:setText","params":{"elementId":"2","text":"password","replace":false}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:setText","params":{"elementId":"2","text":"password","replace":false}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: setText
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using element passed in: 2
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Attempting to clear using UiObject.clearText().
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Sending plain text to element: password
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":true}
[debug] [MJSONWP] Responding to client with driver.setValue() result: true
[HTTP] <-- POST /wd/hub/session/4992d863-965f-4152-a27e-9ff2b0cb799b/element/2/value 200 6749 ms - 76 
[BaseDriver] Shutting down because we waited 60 seconds for a command
[debug] [AndroidDriver] Shutting down Android driver
[Appium] Closing session, cause was 'New Command Timeout of 60 seconds expired. Try customizing the timeout using the 'newCommandTimeout' desired capability'
[Appium] Removing session 4992d863-965f-4152-a27e-9ff2b0cb799b from our master session list
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/usr/share/android-sdk/platform-tools/adb' with args: ["-P",5037,"-s","192.168.56.101:5555","shell","am","force-stop","com.facebook.lite"]
[HTTP] --> DELETE /wd/hub/session/4992d863-965f-4152-a27e-9ff2b0cb799b {}
[HTTP] <-- DELETE /wd/hub/session/4992d863-965f-4152-a27e-9ff2b0cb799b 404 3 ms - 131 
[debug] [ADB] Pressing the HOME button
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/usr/share/android-sdk/platform-tools/adb' with args: ["-P",5037,"-s","192.168.56.101:5555","shell","input","keyevent",3]
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"shutdown"}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"shutdown"}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type SHUTDOWN
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [UiAutomator] Shutting down UiAutomator
[debug] [UiAutomator] Moving to state 'stopping'
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":"OK, shutting down"}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Closed client connection
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: numtests=1
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: stream=.
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: current=1
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS_CODE: 0
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: stream=
[debug] [AndroidBootstrap] [UIAUTO STDOUT] Test results for WatcherResultPrinter=.
[debug] [AndroidBootstrap] [UIAUTO STDOUT] Time: 106.81
[debug] [AndroidBootstrap] [UIAUTO STDOUT] OK (1 test)
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS_CODE: -1
[debug] [UiAutomator] UiAutomator shut down normally
[debug] [UiAutomator] Moving to state 'stopped'
[debug] [ADB] Attempting to kill all uiautomator processes
[debug] [ADB] Getting all processes with uiautomator
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/usr/share/android-sdk/platform-tools/adb' with args: ["-P",5037,"-s","192.168.56.101:5555","shell","ps"]
[ADB] No uiautomator process found to kill, continuing...
[debug] [UiAutomator] Moving to state 'stopped'
[debug] [Logcat] Stopping logcat capture
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/usr/share/android-sdk/platform-tools/adb' with args: ["-P",5037,"-s","192.168.56.101:5555","shell","am","force-stop","io.appium.unlock"]
[debug] [AndroidDriver] Not cleaning generated files. Add `clearSystemFiles` capability if wanted.

**Comment by mykola-mokhnach** [comment]
![i-hear-you-but-still-dont-understand](https://user-images.githubusercontent.com/7767781/33368192-47b9474e-d4f1-11e7-9497-0e35c8d57049.jpg)

**Comment by ochubey** [comment]
@mykola-mokhnach looks like he trying to enter password into password field, but fails :)
@wilkin07 could you, please, provide:
1. code of your test where you trying to type email and password;
2. page structure of the login page of your application (`System.out.println(driver().getPageSource());`) ans provide it as a [gist](https://gist.github.com/).

**Comment by wilkin07** [comment]
I solved it just by clicking on another element and then on the corresponding item that the send_keys wanted to do. and it works well

**Comment by saikrishna321** [comment]
Closing as per @JhonShell previous comment.
