### ISSUE TITLE
 Encountered internal error running command: Error: '10.1.1' does not exist in the list of simctl SDKs. Only the following Simulator SDK versions are available on your system: 11.1,10.

### ISSUE THREAD

**Issue by testertiwari** [appium/appium#9716]
Here's what I am using as my desired capabilities -

public IOSDriver driver;
        @BeforeTest
        public void setup() throws MalformedURLException {
            String appPath = "//Users/rohittiwari/IdeaProjects/myapp/app/myappDev.ipa";
            DesiredCapabilities capabilities = new DesiredCapabilities();
            capabilities.setCapability("platformName", "iOS");
          capabilities.setCapability("deviceName", "iphone 6");
            capabilities.setCapability("platformVersion", "10.1.1");
            capabilities.setCapability("app", appPath);
            capabilities.setCapability("automationName", "XCUITest");
            capabilities.setCapability("appPackage", "com.package.name");

**Comment by mykola-mokhnach** [comment]
> capabilities.setCapability("platformVersion", "10.1.1");

You must provide simulator version, which exists on your system (literally select any from the list you got in the error message)

**Comment by testertiwari** [comment]
Thank you!
