### ISSUE TITLE
Waiting for initial webview - browser is opened on second device 

### ISSUE THREAD

**Issue by SQSTest** [appium/appium#9718]
## The problem

We have an environment with 6 devices, since the update from 1.6.5 to 1.7.1 due to the integration of iOS11 devices and the upgrade to Xcode 9.1 we can't run tests on different devices. Only one device always works if we execute the test on the second device, e. g. the browser in device one is opened. As soon as we delete the WDA on device one, we can run the tests on device two, but the game starts again with every other device.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version did not exhibit the issue (if applicable): 1.6.5
* Desktop OS/version used to run Appium: MacOS 10.12.6
* Node.js version (unless using Appium.app|exe): 8.9.1
* Mobile platform/version under test: iOS 10.3.3 iOS 11.0.3
* Real device or emulator/simulator: Real device for example - iPhone8, iPhone6, iPhone5s, iPhone6s
* 

## Details

Let me briefly recapitulate the problems.

Prerequisite: no tests have been performed, no device has WebDriverAgent installed on it.

1. test execution on device one - all passed
2. Test execution on device 2 - failed - Stockbrowser opens on device 1
3. test execution on device 2 - previously the WDA was deleted on device one - passed
4. Test execution on device 1 - failed - Stockbrowser is opened on device 2

and so one

## Link to Appium logs

https://gist.github.com/SQSTest/729f678470fb2f8bd13946d8a097c21e

**Comment by imurchie** [comment]
When switching devices you need to provide a different port in the `wdaLocalPort ` capability

**Comment by SQSTest** [comment]
@imurchie  Six instances of the appium server are currently running, each with its own WDA and appium port assigned to it.

for example :
node /usr/local/bin/appium --address 192.168.254.34 --port 6981 --debug-log-spacing --device-name iPhone8 --default-capabilities \{"xcodeOrgId":"AABB","xcodeSigningId":"iPhone Developer"\} --webkit-debug-proxy-port 7981\
}

**Comment by imurchie** [comment]
Nothing in that is the `wdaLocalPort`. You can add it to your default capabilities if you'd like. But what is happening is that all six instances of Appium are talking to a single device. The `wdaLocalPort` allows you to specify a different location for each device to be talked to.

**Comment by SQSTest** [comment]
@imurchie Sorry for the late reply. The mentioned solution brought the desired success, thank you again.
