### ISSUE TITLE
UiAutomator2 fails to start when executed from Jenkins

### ISSUE THREAD

**Issue by rpjesivac** [appium/appium#9719]
## The problem

My setup: Jenkins Server kicks off a task on Jenkins node (Appium is installed on the node) and this tasks executes android tests on Android tablet that is connected to the node via USB.

When I kick off execution of the tests manually from the Jenkins node everything works OK but when I kick off execution via Jenkins UiAutomator2 reports this error (full logs are attached)

[UiAutomator2] Starting uiautomator2 server v0.1.8
[UiAutomator2] Running command: 'adb -s 6116e25aeb822cd0 shell am instrument -w io.appium.uiautomator2.server.test/android.support.test.runner.AndroidJUnitRunner'
[UiAutomator2] Waiting up to 20000ms for UiAutomator2 to be online...
[UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error was: Error: Trying to proxy a session command without session id

I tried this against appium versions 1.6.5, 1.7.0, and 1.7.1 with the same results (installed via npm v5.5.1)
I made sure that Jenkins is using the same user as the user that installed appium, that env variables are set so these are also included in the jenkinsLog attachment.

Any ideas on how to fix this issue? I been stuck on it for awhile now 

[appiumFail_ExecutedFromJenkins.log](https://github.com/appium/appium/files/1514268/appiumFail_ExecutedFromJenkins.log)
[appiumGOOD_ManualExecutionFromJenkinsNode.log](https://github.com/appium/appium/files/1514269/appiumGOOD_ManualExecutionFromJenkinsNode.log)
[jenkinsLog_withEnvVariables.txt](https://github.com/appium/appium/files/1514270/jenkinsLog_withEnvVariables.txt)

 

## Environment

* Appium version (or git revision) that exhibits the issue: v1.6.5, v1.7.0, v1.7.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):v8.9.1
* Mobile platform/version under test: Android 7.0
* Real device or emulator/simulator: Samsung Galaxy Tab S2
* Appium CLI or Appium.app|exe:

**Comment by ochubey** [comment]
@rpjesivac are you sure that issue is not related to Katalon Studio?

**Comment by rpjesivac** [comment]
I am not 100% sure but I don't see how Katalon Studio would cause this issue?

**Comment by rpjesivac** [comment]
Any suggestions here?
Thanks!

**Comment by rpjesivac** [comment]
Hi @sravanmedarapu  can you look into this issue? you were very helpful for others with the similar issue (but these workarounds didn't work for me)
Thanks!

**Comment by mykola-mokhnach** [comment]
Closed as obsolete
