### ISSUE TITLE
501 implementation error with windowHandle() and windowHandles()

### ISSUE THREAD

**Issue by kortegel** [appium/appium#9720]
## The problem

Appium is giving a 501 implementation error with windowHandle() and windowHandles().
This is with a react native app being created for android and iOS.  When I run the script with android I do not need to the the windowHandle() because the focus automatically goes to the overlaying menu, but with iOS it is not automatic so I was attempting to do windowHandle() or windHandles() to get the handle in order to switch to the overlaying menu.  When attempted to do this I get the 501 error.

## Environment

Appium version 1.7.1
wd version 1.4.1
iOS version 11.1

## Link to Appium logs

[debug] [MJSONWP] Calling AppiumDriver.getWindowHandle() with args: ["796676f6-4a9a-4421bf0a-0c8a4a4daaf2"]
[debug] [XCUITest] Executing command 'getWindowHandle'
[HTTP] <-- GET /wd/hub/session/796676f6-4a9a-4421-bf0a-0c8a4a4daaf2/window_handle 501 1ms - 112
[HTTP] --> DELETE /wd/hub/session/796676f6-4a9a-4421-bf0a-0c8a4a4daaf2 {}

## Code To Reproduce Issue [ Good To Have ]

var handle = await webDriver.windowHandle()

**Comment by imurchie** [comment]
Getting window handles only works in the webview context. In the native context it is not implemented (and you get a 501 error).

The menu ought to be available through the normal means of finding elements within the native context.

**Comment by kortegel** [comment]
Then I guess the issue is actually that I am unable to access the menu through the normal finding elements when i am in an iOS environment.

**Comment by imurchie** [comment]
What is the source when the menu is opened?

**Comment by kortegel** [comment]
It doesn't recognize the menu.  When the menu is open the source shows the page that the menu opens over.

**Comment by imurchie** [comment]
Unfortunately that means that Apple's XCTest does not recognize it. There is not much Appium can do at that point.

**Comment by kortegel** [comment]
Okay.  Thanks.  I appreciate your time in trying to help me out with this.

**Comment by saikrishna321** [comment]
Closing as non-appium issue
