### ISSUE TITLE
Locators not found while testing on iOS 11 for App which is built using Xcode 8

### ISSUE THREAD

**Issue by VenkateshPS** [appium/appium#9721]
## The problem

Locators not found while testing on iOS 11 for App which is built using Xcode 8, is this a known issue.

On iOS 11 label="Compose New Message" is not shown, when I do driver.getPageSource, though the Image is present on UI.

## Environment

* Appium version (or git revision) that exhibits the issue: Appium 1.7.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS 11
* Real device or emulator/simulator:Real device
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium 
https://gist.github.com/VenkateshPS/
locatorsourcecomparison.txt

[<script src="https://gist.github.com/VenkateshPS/ec79c4e12326892170eb2845ac0d1b70.js"></script>](url)

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Appium only displays what is returned by WebDriverAgent. Which means if some element is not visible then then it is also not visible for XCTest in general.
