### ISSUE TITLE
Cannot find subsequent elements after locating first element

### ISSUE THREAD

**Issue by ali-mirza786** [appium/appium#9725]
## The problem

When I run tests on my iOS app using the XCUITEST driver, after locating the initial element (and manipulating it such as entering text into a field) attempts to locate a subsequent element fail. 

## Environment

Appium version (or git revision) that exhibits the issue: v1.6.5
Desktop OS/version used to run Appium: MacOS 10.12.6
Mobile platform/version under test: ios 10.3
Real device or emulator/simulator: iPhone 6

## Details

All of my elements have access IDs. I have also looked into it and it doesn't seem like it would be a wait statement issue, because in all cases the page is already loaded and the first element has been successfully located/accessed. My only other conclusion is that some error occurs when trying to move from one element to the next. 

I have also launched the inspector to make sure the access IDs are correct. 

## Link to Appium logs

https://gist.github.com/ali-mirza786/276883c1eadc74d641cc7ae33522f039

## Code To Reproduce Issue [ Good To Have ]

**see response back in my terminal**

1795447-C07TL2G7G1HW:Appium appium$ python -m unittest testcbyge.Account.test_a7_a
E

ERROR: test_a7_a (testcbyge.Account)
data validation error for unacceptable email field input

Traceback (most recent call last):
  File "testcbyge.py", line 106, in test_a7_a
    controller.select_element("create_account", "email_field").send_keys("bademailaddress")
  File "controller.py", line 93, in select_element
    return driver.find_element_by_id(path)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 271, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 756, in find_element
    'value': value})['value']
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 238, in execute
    self.error_handler.check_response(response)
  File "/Library/Python/2.7/site-packages/appium/webdriver/errorhandler.py", line 29, in check_response
    raise wde
NoSuchElementException: Message: An element could not be located on the page using the given search parameters.

----------------------------------------------------------------------
Ran 1 test in 39.092s

FAILED (errors=1)

**Comment by mykola-mokhnach** [comment]
Try to print the page source right before trying to find the element to make sure it's there.

**Comment by ali-mirza786** [comment]
@mykola-mokhnach what do you mean by "print the page source"?
