### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by ledniy** [appium/appium#9727]
## The problem

When i run my tests for long time appium crashes with out of memory
<img width="1503" alt="screen shot 2017-12-01 at 01 35 21" src="https://user-images.githubusercontent.com/1562848/33460760-5e9882f2-d638-11e7-8ee9-be1562b5d718.png">
[Heap-20171201T013623.heaptimeline.zip](https://github.com/appium/appium/files/1519866/Heap-20171201T013623.heaptimeline.zip)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2-beta2
* Last Appium version that did not exhibit the issue (if applicable): -
* Desktop OS/version used to run Appium: Ubuntu 17.04/ macOS 10.13.1 
* Node.js version (unless using Appium.app|exe): 8.9.1
* Mobile platform/version under test: Android 5/6/7
* Real device or emulator/simulator: Real
* Appium CLI or Appium.app|exe: cli

## Code To Reproduce Issue [ Good To Have ]

Simple script for reproduce https://gist.github.com/ledniy/8b3c9c620b4a252862a7baf762162b97
[selendroid-test-app-0.17.0.apk](http://search.maven.org/remotecontent?filepath=io/selendroid/selendroid-test-app/0.17.0/selendroid-test-app-0.17.0.apk)

**Comment by mykola-mokhnach** [comment]
I don't observe any serious leaks there. There are two larger arrays of strings, which act as log buffers. But the other stuff does not look suspicious at all.

**Comment by ledniy** [comment]
Those strings becoming huge problem when i run test for 10 devices, even if i set log-level to error.
Also in screen not actual allocation, because when i run appium with --inspect, test working slow, so actual allocation just about x10

**Comment by ledniy** [comment]
Another example, comparison of 2 snapshots (10 devices) with a difference of 5 minutes:
<img width="1708" alt="screen shot 2017-12-02 at 00 37 22" src="https://user-images.githubusercontent.com/1562848/33506562-09fd15fc-d6f9-11e7-89ba-1ed07de4ba03.png">

**Comment by mykola-mokhnach** [comment]
I'll check what can be done. I can already see some redundancy there

**Comment by mykola-mokhnach** [comment]
The fix has been published in the recent appium beta
