### ISSUE TITLE
Appium 1.7.0 - iOS 10.3.3 Real Device - Safari - Cant click on a link that opens up a new tab

### ISSUE THREAD

**Issue by mike-malandra** [appium/appium#9730]
## The problem
Mouse clicks for links that open new tabs don't work for iOS Safari browsers. Appium can detect the element fine, but when it clicks on it, nothing happens. Clicking on the button manually works. This issue cant be replicated on other browsers.

## Environment

Appium version (or git revision) that exhibits the issue: 1.7.0
Desktop OS/version used to run Appium: Mac OSX Sierra
Node.js version (unless using Appium.app|exe): 8.6.0
Mobile platform/version under test: iOS Safari
Real device or emulator/simulator: iPhone 7 Plus Real device

## Details

Same issue as closed bug : https://github.com/appium/appium/issues/9015

## Link to Appium logs

N/A (Waiting on browserstack)

## Code To Reproduce Issue [ Good To Have ]

webDriver.FindElement(By.XPath("xpath")).Click();

**Comment by mykola-mokhnach** [comment]
Closed as inactive
