### ISSUE TITLE
Feature request: always retrieve CSS-width/height of screen | retrieve pixel ratio of a device

### ISSUE THREAD

**Issue by wswebcreation** [appium/appium#9734]
## My setup
- I use Webdriver.io to automate my Android and iOS native app.
- In my problem I refer to swiping which I implemented with [this method](http://webdriver.io/api/mobile/touchPerform.html) wrapper to
- **Appium:** `1.7.1`
- **NodeJS:** `8.9.1`

## The problem

When I try to automate swipes on devices and I want to make them generic I see a difference between iOS and Android. I use the screensize of the devices to determine the `x` and `y` coordinate on the screen. I have a method that needs the coordinates in percentages. The method will retrieve the screensize and based on the percentage and the screensize I can swipe from `x` to `y` on the *same* coordinates on all the different devices, not matter what the screensize is, at least, that was what I had in mind.

This method will work on iOS because I get the CSS-width and CSS-height back. The swipe command needs the CSS-coordinates. When I use Android I get back the physical-width and height. When I then calculate the coordinates based on percentages the swipe coordinates are bigger then the CSS-width and CSS-height.

## Workaround
I now use the pixel ratio from this [site](https://mydevice.io/devices/) and add this as a custom capability for Android. In my code (see below) I use this pixel ratio to determine the coordinate for Android.
Or is there an other workaround, because I couldn't find it on Google, different fora's and so on.

## Feature request
It would be nice that we don't need to add this in a custom capability but would be able to:

- or always (also) retrieve the CSS-width and -height of a screen on Android and iOS
- or retrieve the pixel ratio of a device

The problem is only that I don't know if this is possible and I hope the info is enough, if not, please let me know.

Tnx in advance

## my code

```js
//my capabilities
config.capabilities = [
  {
    platformName,
    platformVersion: device.platformVersion,
    deviceName: device.deviceName,
    orientation: 'PORTRAIT',
    app: ANDROID_APP_PATH,
    noReset: true,
    maxInstances: 1,
    customCapabilities: {
      pixelRatio: device.pixelRatio,
    },
  },
];
```

```js
// my code
/**
 * Swipe from or and element to given coordinates or from coordinates (from) to the new
 * coordinates (to). The given coordinates are percentages of the screen.
 * @param {string | object} from a selector like '~test-home' | { x: 50, y: 50 }
 * @param {object} to { x: 25, y: 25 }
 * @example
 * <pre>
 *   // This is a swipe to the left
 *   const from = { x: 50, y:50 }
 *   const to = { x: 25, y:50 }
 *   // OR swipe from a given element to a given position
 *   const from = '~test-home'
 *   const to = { x: 25, y:50 }
 * </pre>
 */
export function swipe(from, to) {
  const screenSize = device.windowHandleSize().value;
  let pressOptions = {};

  if (typeof from === 'object' && typeof to === 'object') {
    /**
     * command starts at a particular coordinate on the screen
     */
    pressOptions = getDeviceScreenCoordinates(screenSize, from);
  } else {
    /**
     * command starts at a particular element location on the screen
     */
    const elementID = $(from).value.ELEMENT.toString();
    if (!elementID) {
      throw new Error(`Element with selector '${from}' could not be found`);
    }
    pressOptions.element = elementID;
    pressOptions.x = 1;
    pressOptions.y = 1;
  }

  device.touchPerform([{
    action: 'press',
    options: pressOptions,
  }, {
    action: 'moveTo',
    options: getDeviceScreenCoordinates(screenSize, to),
  }, {
    action: 'release',
  }]);
}

/**
 * Get the screen coordinates based on a device his screensize
 * @param {number} screenSize the size of the screen
 * @param {object} coordinates like { x: 50, y: 50 }
 * @return {{x: number, y: number}}
 */
function getDeviceScreenCoordinates(screenSize, coordinates) {
  let height = screenSize.height;
  let width = screenSize.width;
  if (device.isAndroid) {
    height /= device.desiredCapabilities.customCapabilities.pixelRatio;
    width /= device.desiredCapabilities.customCapabilities.pixelRatio;
  }
  return {
    x: Math.round(width * (coordinates.x / 100)),
    y: Math.round(height * (coordinates.y / 100)),
  };
}
```

**Comment by mykola-mokhnach** [comment]
Both xctest and UIA2 driver have endpoints now to get the pixel ratio: `commands.getDevicePixelRatio`
