### ISSUE TITLE
Wrong coordinates with Appium 1.7.1 - IOS 

### ISSUE THREAD

**Issue by BlayerB** [appium/appium#9735]
## The problem

After I open a picker-wheel that contains a list within it, with the items:
"itemA"
"itemB"
"itemC"
I try to locate some item (e.g. "itemB") with driver.findElement(By.id("itemB")) in order to click on it, but it clicks on different item in the list.
Then I tried to look at the coordinates of the items (they are ordered from top to bottom just like I wrote them) and got:
driver.findElement(By.id("itemA")).getLocation().getY() = 222
driver.findElement(By.id("itemB")).getLocation().getY() = 258
driver.findElement(By.id("itemC")).getLocation().getY() = 186

I got back to Appium 1.6.5 and it didn't reproduce.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable): 1.6.5
* Desktop OS/version used to run Appium: 11.1 / 9.1 / 8.3.2
* Node.js version (unless using Appium.app|exe): 7.3.0
* Mobile platform/version under test: iPhone 6s 
* Real device or emulator/simulator: Simulator

## Link to Appium logs

[https://gist.github.com/BlayerB/8f57f1772bb25ca25bf0147419e890e3](url)

Thanks all.

**Comment by mykola-mokhnach** [comment]
It's an XCTest issue. Check https://github.com/appium/appium/issues/9700 for more details.
