### ISSUE TITLE
Error: ESOCKETTIMEDOUT (Appium  v1.7.1)

### ISSUE THREAD

**Issue by rspatil89** [appium/appium#9736]
## The problem

When runAppinBackground command send to real device. Connection to WDA timed out
and throws Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: Error: ESOCKETTIMEDOUT

## Environment

* Appium version (or git revision) that exhibits the issue : Appium  v1.7.1
* Desktop OS/version used to run Appium : macOS High Sierra 10.13.1
* Node.js version (unless using Appium.app|exe) : v8.6.0
* Npm Version : 5.5.1
* Mobile platform/version under test : iOS 10.3.2
* Real device or emulator/simulator: iPhone 6 Plus (Real Device)
* Java Version : 1.8.0_20
* java-client : 5.0.3

## Details

After taking app to background play and coming back to app getting error as Connection to WDA timed out.

## Link to Appium logs

[MJSONWP] Calling AppiumDriver.background() with args: [{"timeout":5000},"f16006cf-bb91-4755-a0eb-30ececa0556c"]
[debug] [XCUITest] Executing command 'background'
[debug] [JSONWP Proxy] Proxying [POST /wda/deactivateApp] to [POST http://localhost:8100/session/7D8BC319-B8C6-4CFF-BAA3-4E26D55F62D5/wda/deactivateApp] with body: {"duration":5}
[debug] [XCUITest] Connection to WDA timed out
[MJSONWP] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: Error: ESOCKETTIMEDOUT
    at JWProxy.proxy$ (../../../lib/jsonwp-proxy/proxy.js:152:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
[HTTP] <-- POST /wd/hub/session/f16006cf-bb91-4755-a0eb-30ececa0556c/appium/app/background 500 10049 ms - 251 
[HTTP] --> POST /wd/hub/session/f16006cf-bb91-4755-a0eb-30ececa0556c/element {"using":"xpath","value":"//XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeTextView"}

**Comment by mykola-mokhnach** [comment]
This error means that webdriveragent stopped responding to Appium requests. Please report the issue directly to https://github.com/facebook/WebDriverAgent/issues
