### ISSUE TITLE
Using app unlock, this is going to be deprecated![Android][AndroidDriver]

### ISSUE THREAD

**Issue by sgupta3112** [appium/appium#9737]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

*Appium version (or git revision) that exhibits the issue : Appium v1.7.1
Desktop OS/version used to run Appium : macOS High Sierra 10.13.1
Node.js version (unless using Appium.app|exe) : v8.6.0
Npm Version : 5.5.1
Mobile platform/version under test : Android 8
Real device or emulator/simulator:Nexus6p
Java Version : 1.8.0_20
java-client : 5.0.3

## Details

When I am trying to unlock the screen that time getting this msg in appium logs. if it is going to be deprecated then what's new ?
## Link to Appium logs

Screen is locked, trying to unlock
[AndroidDriver] Using app unlock, this is going to be deprecated!
[AndroidDriver] Unlocking screen
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/FTT/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","84B7N15A20002020","shell","am","force-stop","io.appium.unlock"]
[debug] [ADB] Device API level: 26
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/FTT/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","84B7N15A20002020","shell","am","start","-W","-n","io.appium.unlock/.Unlock","-a","android.intent.action.MAIN","-c","android.intent.category.LAUNCHER","-f","0x10200000"]
[debug] [ADB] Running '/Users/FTT/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","84B7N15A20002020","shell","am","start","-W","-n","io.appium.unlock/.Unlock","-a","android.intent.action.MAIN","-c","android.intent.category.LAUNCHER","-f","0x10200000"]

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
It will be replaced with more specialised [unlock methods](https://github.com/appium/appium-android-driver/blob/9a9ee19a71ba106d5afdfd3d98731881b7571b44/docs/UNLOCK.md) for different screen lock types.
