### ISSUE TITLE
Programmatically Open Appium & ios webkit debug proxy in Mac for iOS device testing

### ISSUE THREAD

**Issue by prateekchawla** [appium/appium#9738]
There is no code for this but I need to find out how to create bash script for opening appium,webkit debug proxy and how to hit this using code in windows machine. 

I might be asking this at the wrong forum, Please guide me to the right discussion place if so.

**Comment by mykola-mokhnach** [comment]
> I might be asking this at the wrong forum, Please guide me to the right discussion place if so.
discuss.appium.io

**Comment by ochubey** [comment]
@prateekchawla - if you want to run it on Windows machine with iOS device connected to it - not possible.
If you need to run it on Mac machine with iOS device connected to it, but trigger it from Windows machine:
- to run [appium](https://appium.io/slate/en/master/?java#ios-only) - use `appium --webkit-debug-proxy-port {wdp_port}`;
- to run [webkit debug proxy](https://appium.readthedocs.io/en/stable/en/advanced-concepts/ios-webkit-debug-proxy/) - use `ios_webkit_debug_proxy -c {ios_udid}:{wdp_port}`.
Be sure that ports are the same ;)

**Comment by prateekchawla** [comment]
@ochubey I need to do this pro grammatically and not manually i.e triggering it from windows machine when my iOS device is connected to Mac machine

**Comment by prateekchawla** [comment]
@ochubey  Thanks. I tried this.
My iPhone is connected on Mac and i am triggering from windows to start appium on Mac.
When i use the C# code(not java) for AppiumLocalService giving the  .withIPAddress(ipAddress) as IP address of Mac.  It looks for that Appium Js files on windows itself. 
Is it possible?

**Comment by ochubey** [comment]
@prateekchawla to simplify requirements - you can initiate AppiumDriver from any machine, but Appium Server must be executed on Mac machine with iPhone connected to it.

**Comment by prateekchawla** [comment]
@ochubey  Yes, that makes sense. The problem i am facing is to initiate Appium Driver on Mac using code on Windows machine 
`AppiumServiceBuilder service2 = new AppiumServiceBuilder().UsingDriverExecutable(new FileInfo("/usr/local/bin/node")).WithAppiumJS(new FileInfo("/usr/local/lib/node_modules/appium/bin/appium.js")).WithIPAddress("10.140.3.13").UsingPort(4723);` where IP is of Mac machine.
Am I doing something wrong here?

**Comment by ochubey** [comment]
@prateekchawla Yes. You confused Driver with Server/Service. AppiumDrive initiates this way: `new IOSDriver({ip of the Mac machine where AppiumService initialized goes here}, desiredCapabilities)` and it can be run from any machine.
AppiumServer (AppiumService) must be initiated on Mac machine in your case (because you want to run iOS tests). `WithIPAddress({your local/external IP of the Mac machine})`
