### ISSUE TITLE
,appium version 1.2.7, serverV1.7.1 is force closing, kindly give the solution or ways to fix it

### ISSUE THREAD

**Issue by VegetaSama26** [appium/appium#9740]
## The problem

I was trying to start the appium serverV1.7.1 and the moment i click on start server, appium GUI crashes every time but if i use older version say 1.4 it works fine 

## Environment

* Appium version (or git revision) that exhibits the issue: V1.7.1
* Last Appium version that did not exhibit the issue (if applicable): version 1.4.16.1 
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): 8.9.1
* Mobile platform/version under test: Android 6.0
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: via CLI also installed on system but facing issue on Appium.exe

## Details

After clicking on start server even without changing any setting appium is force closing

## Link to Appium logs

as appium is not starting so not able to catch the logs

## Code To Reproduce Issue [ Good To Have ]

no code, just click on start server its crashing, kindly let me know if u need more details

**Comment by VegetaSama26** [comment]
moment i click on START server it is force closing, please provide solution, anyone

**Comment by mykola-mokhnach** [comment]
Please carefully fill out the issue reporting form and provide all the necessary data

**Comment by VegetaSama26** [comment]
@mykola-mokhnach hi kindly check and kindly revert as above problem is blocker

**Comment by mykola-mokhnach** [comment]
Capabilities list and a screenshot might help.

**Comment by VegetaSama26** [comment]
capability list 
DesiredCapabilities cap=new DesiredCapabilities();
        cap.setCapability("deviceName", "Fever 4G");
        cap.setCapability("platformVersion", "6.0");
        cap.setCapability("platformName", "Android");
        cap.setCapability("appPackage", "com.vector.guru99");
        cap.setCapability("appActivity", "com.vector.guru99.BaseActivity");
        driver =new RemoteWebDriver(new URL("http://127.0.0.1:4723/wd/hub"), cap);

and for appium server the moment i click on start server : appium stopped working, windows pop up comes

**Comment by VegetaSama26** [comment]
![untitled](https://user-images.githubusercontent.com/34246012/33620082-e09e24aa-da0c-11e7-8272-65ee187f2bac.png)
![untitled1](https://user-images.githubusercontent.com/34246012/33620084-e0d833f2-da0c-11e7-8764-36ecfad14fe8.png)
@mykola-mokhnach kindly check the screenshot

**Comment by mykola-mokhnach** [comment]
I assume the issue has nothing to do with the server itself and should be reported to https://github.com/appium/appium-desktop/issues

**Comment by VegetaSama26** [comment]
@mykola-mokhnach but its getting closed whenever i am clicking on latest version 1.7.1 but working fine on the last version 1.4.
