### ISSUE TITLE
driver().launchApp() uninstalls application in iOS Simulator

### ISSUE THREAD

**Issue by jmehtaebates** [appium/appium#9742]
## The problem

The application gets deleted after call to method driver().launchApp()

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1 and desktop version 1.2.6
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: 10.12.6
* Node.js version (unless using Appium.app|exe): v8.9.0
* Mobile platform/version under test: iOS 11.0
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: BOTH

## Details

I am trying to close and re-launch the app after each test via AfterMethod and BeforeMethod. Every time the code calls driver.launchApp(); it un-installs and re-installs the app. 

## Link to Appium logs

N/A Not sure what to include here

## Code To Reproduce Issue [ Good To Have ]

	@BeforeMethod
	public void OpenApp(){
		driver.launchApp();
	}

**Comment by jmehtaebates** [comment]
@imurchie I saw a previous year old thread on this but that did not seem to work
#6274

**Comment by mykola-mokhnach** [comment]
This won't work. `launchApp` basically does the same as new session creation. Try to quit and start the session with noReset capability set to `true` instead.

**Comment by jmehtaebates** [comment]
@mykola-mokhnach  thank you for your suggestion. Wouldn't that do the same thing i.e uninstall and re-install the app? I am trying to avoid that and want to mimic app close and app open scenario without having to un-install.

**Comment by mykola-mokhnach** [comment]
uninstall will never be performed with `noReset` set to `true`

**Comment by jmehtaebates** [comment]
Will give it a shot. thank you @mykola-mokhnach

**Comment by saikrishna321** [comment]
Closing as InActive
