### ISSUE TITLE
npm install -g appium ,but when run appium -v , it prompts command not found

### ISSUE THREAD

**Issue by 888niannianwang** [appium/appium#9743]
## The problem

AslandeMac-mini:~ qa$ node -v
v8.9.1
AslandeMac-mini:~ qa$ npm -v
4.2.0
AslandeMac-mini:~ qa$ npm install -g appium
/usr/local/Cellar/node/8.9.1/bin/appium -> /usr/local/Cellar/node/8.9.1/lib/node_modules/appium/build/lib/main.js
/usr/local/Cellar/node/8.9.1/lib
`-- appium@1.7.1

You have new mail in /var/mail/qa
AslandeMac-mini:~ qa$ appium -v
-bash: appium: command not found
AslandeMac-mini:~ qa$

**Comment by mykola-mokhnach** [comment]
most likely you don't have all the necessary directories enumerated in PATH environment variable.
Closed as non-Appium issue

**Comment by 888niannianwang** [comment]
I don't know what is wrong with my environment. Is there someone have the same problem with me ? Or,if you can support me ?Thanks
