### ISSUE TITLE
Cannot locate indexed element when the first tree view does not have such element.

### ISSUE THREAD

**Issue by lavi-xu** [appium/appium#9744]
## The problem

Here it's tree view:
XCUIElementTypeScrollView
-> XCUIElementTypeTable (1)
--> XCUIElementTypeCell
---> XCUIElementTypeStaticText [1]
---> XCUIElementTypeStaticText [2]
-> XCUIElementTypeTable (2)
--> XCUIElementTypeCell
---> XCUIElementTypeStaticText [1]
---> XCUIElementTypeStaticText [2]
---> XCUIElementTypeStaticText [3]

It cannot locate element with xpath like "//XCUIElementTypeStaticText[3]".

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Desktop OS/version used to run Appium: 10.12.6 / xocde 8.3.3
* Node.js version (unless using Appium.app|exe): v8.9.1
* Real device or emulator/simulator: ipad 10.3.3

ref: https://github.com/facebook/WebDriverAgent/issues/812

**Comment by mykola-mokhnach** [comment]
Use the following locator to locate the third static text in the second table:
`By.classChain("**/XCUIElementTypeTable[2]/XCUIElementTypeCell/XCUIElementTypeStaticText[3]")`

the issue has nothing to do with Appium itself, since locators matching happens on WebDriverAgent side
