### ISSUE TITLE
Unable to install the .app file on simulator via appium

### ISSUE THREAD

**Issue by vighneshpai-yml** [appium/appium#9745]
## The problem
I'm trying to install an app via appium but, it's throwing me an error. However, I'm able to install the app via terminal using command xcrun simctl install booted </path/to/the/app/file>. So, I suspect, something with the configuration I'm messing up. Any help will be appreciated.

## Environment
* Appium version (or git revision) that exhibits the issue: v1.7.1
* Last Appium version that did not exhibit the issue (if applicable): Not applicable
* Desktop OS/version used to run Appium: 10.13.1 macos high sierra
* Node.js version (unless using Appium.app|exe): Not applicable.
* Mobile platform/version under test: 11.1
* Real device or emulator/simulator: Simulator.
* Appium CLI or Appium.app|exe: Appium app on mac os.

## Details
I'm writing cucumber, gherkin and ruby scripts.
Then I'm passing the capabilities to the appium driver and starting the appium with those desired capabilities.

## Link to Appium logs
https://gist.github.com/vighneshpai-yml/91526a887c7d623973520a09fc208b25

## Code To Reproduce Issue [ Good To Have ]
Gherkin step:
`    Given I launch the application "Myapp.app" in device "iPhone Simulator" with udid "7D185DAA-86D2-4423-BC4B-1156671D7DEA"
`
Capabilities:
`def start_app(filename, device_name, device_udid)
  caps_config = {
      platformName: "iOS",
      deviceName: device_name, #passing this as an argument
      app: (File.join(File.dirname(__FILE__), filename)), #passing this as an argument
      bundleId: "com.ymedialabs.devteam", 
      automationName: "XCUITest",
      xcodeOrgId: "#####",
      xcodeSigningId: "#####",
      Runner: "Distribute",
      noReset: "true",
      fullReset: "false",
      showIOSLog: "true",
      autoAcceptAlerts: "true",
      showXcodeLog: "true",
      useNewWDA: "false",
      resetOnSessionStartOnly: "true",
      timeout: "30000",
      udid: device_udid, } #passing this as an argument
  $opts={ caps: caps_config}
  setup
end`

Starting the webdriver:
`def setup
  Appium::Driver.new($opts)
  Appium.promote_appium_methods Object
  $driver.start_driver
end`

**Comment by mykola-mokhnach** [comment]
> An application bundle was not found at the provided path.
 
The error says that the path to the app you provide in capabilities is wrong or not accessible.

**Comment by vighneshpai-yml** [comment]
But I have kept it in the project folder itself.

**Comment by imurchie** [comment]
The app is on the file system (see https://gist.github.com/vighneshpai-yml/91526a887c7d623973520a09fc208b25#file-gistfile1-txt-L55-L56). 

What happens when you run, manually, 
```
xcrun simctl install 7B185DAA-86D2-4423-BC4B-1156671D7DEA /Volumes/Jerry/Project/compass_automation/features/Support/Compass.app
```

**Comment by jargot** [comment]
I had exactly the same issue using a relative path to app like so:
`../../ios/build/Build/Products/Debug-iphonesimulator/test.app`

Here's parts of the log, tell me if you want more:

`[debug] [XCUITest] Checking whether app '../../ios/build/Build/Products/Debug-iphonesimulator/test.app' is actually present on file system`
`[debug] [XCUITest] App is present`

But also further down:

`[simctl] Error: simctl error running 'install': An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):`
`Failed to install the requested application`
`An application bundle was not found at the provided path.`
`Provide a valid path to the desired application bundle.`


But I switched to an absolute path and it works just fine, you might want to try that :)
@vighneshpai-yml
