### ISSUE TITLE
IOS 11: appium unable show notification elements

### ISSUE THREAD

**Issue by rutin31** [appium/appium#9747]
## The problem
Hi
I have to get OTP code
In device IOS 10 I get it with swipe function and read OTP from XCUIElementTypeCell element
After upgrade to IOS11 appium don't see any element after swipe
Is there any way to get OTP in IOS 11

I use latest appium desktop version 1.2.37

**Comment by mykola-mokhnach** [comment]
There is nothing Appium ca do about this. The change has been made on Apple's XCTest side.
