### ISSUE TITLE
getting error while instantiating Appium Service Builder - "The given nodeJS file doesn't exist. Given path E:\usr\local\bin\node"

### ISSUE THREAD

**Issue by prateekchawla** [appium/appium#9748]
## The problem

I want to run appium on mac triggering it from my windows machine using the Appium Service Builder
where IP address is of the Mac machine which is on the same network.

## Environment

* Appium version (or git revision) that exhibits the issue:NA
* Last Appium version that did not exhibit the issue (if applicable):NA
* Desktop OS/version used to run Appium:NA
* Node.js version (unless using Appium.app|exe):NA
* Mobile platform/version under test: NA
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

The exception I am getting is "The given nodeJS file doesn't exist. Given path E:\usr\local\bin\node" which indicates that it is finding nodeJS on the windows itself as it is giving a path on E drive. 

## Link to Appium logs

NA

## Code To Reproduce Issue [ Good To Have ]

`AppiumServiceBuilder service = new AppiumServiceBuilder().WithIPAddress("10.140.3.13").UsingDriverExecutable(new FileInfo("/usr/local/bin/node")).WithAppiumJS(new FileInfo("/usr/local/bin/appium/appium.js"));`

**Comment by mykola-mokhnach** [comment]
The error has nothing to do with Appium server. Please report to https://github.com/appium/java-client/issues
