### ISSUE TITLE
building bootstrap project

### ISSUE THREAD

**Issue by bd9142** [appium/appium#9749]
## The problem

I want to build bootstrap project in android-bootstrap/bootstrap module. I added new maven dependency however ant build fails. it cannot find the added dependency.

## Environment

* Appium version 1.7.0

--ant build logs:
`C:\Users\mobinavel\Documents\appium-1.7.0\node_modules\appium-android-driver\node_modules\appium-android-bootstrap\bootstrap\build.xml
help:
     [echo] Android Ant Build. Available targets:
     [echo]    help:      Displays this help.
     [echo]    clean:     Removes output files created by other targets.
     [echo]    build:     Builds the test library.
     [echo]    install:   Installs the library on a connected device or
     [echo]               emulator.
     [echo]    test:      Runs the tests.
     [echo] It is possible to mix targets. For instance:
     [echo]    ant build install test
     [echo] This will build, install and run the test in a single command.
-check-env:
 [checkenv] Android SDK Tools Revision 25.2.3
 [checkenv] Installed at C:\Users\mobinavel\AppData\Local\Android\sdk
-pre-clean:
-check-env:
 [checkenv] Android SDK Tools Revision 25.2.3
 [checkenv] Installed at C:\Users\mobinavel\AppData\Local\Android\sdk
-pre-clean:
clean:
   [delete] Deleting directory C:\Users\mobinavel\Documents\appium-1.7.0\node_modules\appium-android-driver\node_modules\appium-android-bootstrap\bootstrap\bin
-check-env:
 [checkenv] Android SDK Tools Revision 25.2.3
 [checkenv] Installed at C:\Users\mobinavel\AppData\Local\Android\sdk
-build-setup:
[getbuildtools] Using latest Build Tools: 27.0.1
     [echo] Resolving Build Target for AppiumBootstrap...
[getuitarget] Project Target:   Android 4.4.2
[getuitarget] API level:        19
     [echo] ----------
     [echo] Creating output directories if needed...
    [mkdir] Created dir: C:\Users\mobinavel\Documents\appium-1.7.0\node_modules\appium-android-driver\node_modules\appium-android-bootstrap\bootstrap\bin
    [mkdir] Created dir: C:\Users\mobinavel\Documents\appium-1.7.0\node_modules\appium-android-driver\node_modules\appium-android-bootstrap\bootstrap\bin\classes
-pre-compile:
-check-env:
 [checkenv] Android SDK Tools Revision 25.2.3
 [checkenv] Installed at C:\Users\mobinavel\AppData\Local\Android\sdk
-build-setup:
[getbuildtools] Using latest Build Tools: 27.0.1
     [echo] Resolving Build Target for AppiumBootstrap...
[getuitarget] Project Target:   Android 4.4.2
[getuitarget] API level:        19
     [echo] ----------
     [echo] Creating output directories if needed...
-pre-compile:
compile:
    [javac] Compiling 79 source files to C:\Users\mobinavel\Documents\appium-1.7.0\node_modules\appium-android-driver\node_modules\appium-android-bootstrap\bootstrap\bin\classes
    [javac] C:\Users\mobinavel\Documents\appium-1.7.0\node_modules\appium-android-driver\node_modules\appium-android-bootstrap\bootstrap\src\io\appium\android\bootstrap\handler\GetAttribute.java:24: error: package com.google.gson does not exist
    [javac] import com.google.gson.Gson;
    [javac]                       ^
    [javac] C:\Users\mobinavel\Documents\appium-1.7.0\node_modules\appium-android-driver\node_modules\appium-android-bootstrap\bootstrap\src\io\appium\android\bootstrap\handler\GetAttribute.java:79: error: cannot find symbol
    [javac]           final String result = new Gson().toJson(crawlerElementArrayList);
    [javac]                                     ^
    [javac]   symbol:   class Gson
    [javac]   location: class GetAttribute
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 2 errors

BUILD FAILED
C:\Users\mobinavel\AppData\Local\Android\sdk\tools\ant\uibuild.xml:183: Compile failed; see the compiler error output for details.
`

## Code To Reproduce Issue [ Good To Have ]

Adding gson dependency to pom.xml in bootstrap module.

**Comment by bd9142** [comment]
is there anybody knows how to build bootstrap project ?

**Comment by imurchie** [comment]
You need to get the tools version 22, and use them.

**Comment by bd9142** [comment]
project.properties has target=19. do i have to change it also ?

**Comment by imurchie** [comment]
No. You shouldn't need to do anything to the project. It just doesn't build with the newer tools. Running `npm install` will build it.
