### ISSUE TITLE
Unable to run any tests after upgrade to XCode9 with iOS 11

### ISSUE THREAD

**Issue by jbhandari** [appium/appium#9751]
## The problem

I was able to use appium on Xcode version 8.3.3 covering devices that run iOS 10.x.x without any issues.

Since upgrading to Xcode 9.1 and using iOS 11.x or iOS 10.x.x nothing is working. From what I see, it seems no url is being set when the WDA is being set. 

## Environment

* Appium Version: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable):1.7.0
* Desktop OS/version used to run Appium: macOS High Sierra 10.13.1
* Node.js version (unless using Appium.app|exe): 8.9.1
* Mobile platform/version under test: ios11.1 / ios 10.0.2
* Real device or emulator/simulator: iPhone 7s / iPhone 5s
* Using Ruby

## Link to Appium logs

- iOS 11
  - [wda](https://gist.github.com/jbhandari/f9726e687fd404f354a30c75f2fde386)
  - [appium](https://gist.github.com/jbhandari/38b1548379326119bab3ee882abf55e0)

- iOS 10
  - [wda](https://gist.github.com/jbhandari/4274f45411a00e7cc85ae4a64f9185ef)
  - [appium](https://gist.github.com/jbhandari/42829637daa8c70ce0f35732bdc43c4f)

## Xcode Screenshots

<img width="1680" alt="webdriveragent xcodeproj 2017-12-05 13-47-39" src="https://user-images.githubusercontent.com/6493672/33625130-a0477d72-d9c4-11e7-91cc-a49603b4bd45.png">

<img width="1680" alt="webdriveragent xcodeproj 2017-12-05 14-01-10" src="https://user-images.githubusercontent.com/6493672/33625205-d5eeb666-d9c4-11e7-8784-5214e58aa870.png">

Thanks for taking the time to read this. Any help is much appreciated!

**Comment by mykola-mokhnach** [comment]
Can you try to explicitly set `wdaLocalPort` capability to 8100 ?

**Comment by jbhandari** [comment]
Thanks for getting back to me @mykola-mokhnach :

I set the capability as requested. There was no change although the port was transferred to 8100. It remained hanging at the same spot as the logs with the change of wda port: 

`Proxying [POST /session] to [POST http://localhost:8100/session] with body{...}`

**Comment by mykola-mokhnach** [comment]
Can you also attach real device logs for this time period?

**Comment by mykola-mokhnach** [comment]
Perhaps all you need is to just reboot the device

**Comment by jbhandari** [comment]
@mykola-mokhnach  ios logs are [here](https://gist.github.com/jbhandari/bbf59df0d6ad73c2a312dfa3eb7ff779) .

Line: 566 and 567 is where it hangs


I reset devices multiple times, have tried re-doing the wda install with accepting permissions etc. many times. My setup flow has not changed at all, and I was successfully working with iOS 10 in Xcode 8.3.3 for many months. 

Thanks for the help!

**Comment by jbhandari** [comment]
@mykola-mokhnach   My workflow and requirements involve doing a fresh app install every time I run a test. I noticed that every time a fresh install is performed the trusting of the app developer no longer carries over to the new install. Previously I would only have to trust once and never worry about it. Hope that can provide some help?

**Comment by mykola-mokhnach** [comment]
> I noticed that every time a fresh install is performed the trusting of the app developer no longer carries over to the new install

Do you use enterprise signature?

**Comment by jbhandari** [comment]
@mykola-mokhnach 

Yes the app carries an enterprise signature that differs from the WDA signature which is a default personal team / iPhone Developer Signing Certificate (unpaid option that expires after a certain amount of time)

**Comment by mykola-mokhnach** [comment]
You must use the developer signature. Closed as not an issue

**Comment by jbhandari** [comment]
@mykola-mokhnach my apologies, I believe it is the developer signature:

![img_7e5bf3f20ebc-1 jpeg 2017-12-13 11-18-31](https://user-images.githubusercontent.com/6493672/33949514-ce568382-dff7-11e7-9841-71965ff02392.png)

**Comment by mykola-mokhnach** [comment]
No it is not. You should compile the app in debug mode and sign it with development signature (the device under test should be already in your developer profile), so   it is executed  you don't need to confirm/trust anything.

**Comment by jbhandari** [comment]
@mykola-mokhnach I get what you are saying however, we test apps that are in production. We are not the app developers. We never had this issue prior to Xcode 9 / iOS 11.

**Comment by ochubey** [comment]
@jbhandari in this case (you have no ability to build an app with dev profile) you can try to use application's `bundleId` instead of `app` capability and make sure that app installed on the device and trusted before the test.
The list of the applications with their bundle ids could be found by running following command in terminal `ideviceinstaller -l` or `ideviceinstaller -l -u {device udid}` if you have more than one device connected.

**Comment by auto-mator** [comment]
I am experiencing this same issue. 

iOS 11.2.1 real device.
Xcode 9.2
Appium 1.7.2-beta5

Just like the op, I need to be able to do a fresh install of the app every run, however when noReset = false, the application is not automatically Trusted and thus it never launches. However, if I set noReset = true, the application is able to launch and I can select elements etc. Doing as @ochubey suggested works fine, but this does not solve the problem that we both need a new install every run.

**Comment by jbhandari** [comment]
@mykola-mokhnach this should not be closed .... its still persistent

**Comment by mykola-mokhnach** [comment]
It's not an appium issue. However you could try https://github.com/appium/appium/issues/9883 as a workaround

**Comment by auto-mator** [comment]
Workaround is not valid for multiple clean installs, i.e I'd have to be near the phones every time my script calls for a fresh install. If this isn't an Appium issue, whose is it?

**Comment by mykola-mokhnach** [comment]
Apple of course

**Comment by auto-mator** [comment]
@jbhandari I had the same problem as you. I found a work-around that works sufficiently well -- Just keep two applications with the same bundle-id on your device when you go to do the uninstall/re-install of your app. If you do that, the 'Trust' will be maintained. Hope this helps.

**Comment by jbhandari** [comment]
@auto-mator thanks will try and let you know...been away from iOS Automation for a while
