### ISSUE TITLE
Appium 1.7.1/Xcode 9.1 clear function is not working anymore

### ISSUE THREAD

**Issue by rakeshsukla53** [appium/appium#9752]
## The problem

I was able to use appium on Xcode version 8.3.3 covering devices that run iOS 10.x.x without any issues. Since upgrading to Xcode 9.1 and using iOS 11.x or iOS 10.x.x, the `clear` function is not working anymore. The `clear` function basically deletes all the text present in the `iOS` `Textfield`. 
`send_keys` is working fine but not the `clear` function.

```
def clear_text(driver, locator, idx=None):
    try:
        if idx:
            find_elements(driver, locator)[idx].clear()
        else:
            find_element(driver, locator).clear()
    except NoSuchElementException:
        raise  # Make sure if the element isn't there we don't hide it.
    except WebDriverException:
        pass  # Ignore bizarre can't clear text errors.
```

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1 
* Last Appium version that did not exhibit the issue (if applicable): 1.6.5
* Desktop OS/version used to run Appium: `OS 11` current simulator version is 11
* Mobile platform/version under test: `iOS`
* Real device or emulator/simulator: `Simulator`
* Appium CLI or Appium.app|exe: `Appium CLI`

## Details 

```
>>> el = find_element(driver, GuestbookView.search_list)
[12/05/2017 14:30:04] Find element Search
>>> el
<appium.webdriver.webelement.WebElement (session="9de50f6c-60eb-4714-b648-6894772e0716",
 element="47175C61-5D2D-49A5-AAD4-D101F1EE7881")>
>>> el.clear()
<appium.webdriver.webelement.WebElement (session="9de50f6c-60eb-4714-b648-6894772e0716",
 element="47175C61-5D2D-49A5-AAD4-D101F1EE7881")>
>>>
```
the `clear` function just returns an `webelement` object but doesn't delete anything.

EDIT: 

Those who are facing the same issue can try with `el.send_keys(Keys.DELETE)`. This works so far.

**Comment by Praney** [comment]
Is there any update?
Clear() not working for me as well on IOS native app

**Comment by mykola-mokhnach** [comment]
Closed as third party issue.

**Comment by vikramvi** [comment]
3rd party issue can be tracked under https://github.com/facebook/WebDriverAgent/issues/603

**Comment by LayMuiToh** [comment]
Hi
is this issue resolved?
I send this 2 commands, the textfield didn't get cleared
await driver.elementByAccessibilityId('textUserName').click();
await driver.elementByAccessibilityId('textUserName').clear();
I notice the cursor is at the end of the current text instead of place at the beginning.
how to place the cursor to the beginning of the text field so I can replace the existing text with the new text value.
any workaround or any plan to fix this?
thanks
