### ISSUE TITLE
Could not navigate to webview on React Native app

### ISSUE THREAD

**Issue by mgthor** [appium/appium#9753]
## The problem

I have upgraded the test framework from 1.6.4 to 1.7.1
the app has first page ( sign in page) in webview. App is in ReactNative.
When I run the test script, I am not able to detect the webview.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable): 1.6.4
* Desktop OS/version used to run Appium: Mac OS 10.12.3
* Node.js version (unless using Appium.app|exe): 6.2.0
* Mobile platform/version under test: iPhone 7 and iOS 10
* Appium CLI or Appium.app|exe:

## Link to Appium logs
https://gist.github.com/mgthor/47061a4fa3a5e48b14402ab5d2ba6229

**Comment by mykola-mokhnach** [comment]
It is most likely an issue with the remote web debugger. Make sure it is up to date and it can get the list of available webviews when executed manually.

**Comment by mgthor** [comment]
thanks @mykola-mokhnach  how do I check that?

**Comment by djwgit** [comment]
my iOS app, has a screen with embedded oauth webview, 
xpath query was find with 1.6.5
after updated to 1.7.1,  could not use xpath query against the webview elements anymore.
still could use id, text, but need xpath...
thinking many apps could have embedded webview, hope this issue could be addressed soon, 
@mykola-mokhnach @jlipps   thanks

**Comment by gvozdeva-ira** [comment]
I have the same issue with react-native app on Android - in real device no WEBVIEW is detected. (I've tried run the same build in Nexus 9 emulator - webview is detected, can switch and run commands),
Lenovo tablet with Android 5.0.1 - no webview found.

**Comment by jdougit** [comment]
@gvozdeva-ira 
a workaround, explicitly switch the context to webview, then switch it back to NATIVE_APP view once done with webview.  
related functions:
- current_context
- set_context
- available_contexts

**Comment by djwgit** [comment]
a workaround, explicitly switch the context to webview, then switch it back to NATIVE_APP view once done with webview.  
related functions:
- current_context
- set_context
- available_contexts

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
