### ISSUE TITLE
iOS，speed up self.driver.tap() function

### ISSUE THREAD

**Issue by wangtao169447** [appium/appium#9754]
## The problem
when i run self.driver.tap(x=poi_x,y=poi_y) function, it tooks about 2 seconds to execute this kind of command。 

i also try to execute this kind of function:
        t_action = TouchAction(self.driver)
        t_action.long_press(x=poi_x, y=poi_y, duration=100).perform()
or

self.driver.swipe(poi_x, poi_y, 0, 0, 100)

however,all functions above, spend more than 1 senconds to execute this kind of command.

## Environment

* Appium version (or git revision) that exhibits the issue:1.7.1
* Last Appium version that did not exhibit the issue (if applicable):NO
* Desktop OS/version used to run Appium:MAC OS
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:10.1.1
* Real device or emulator/simulator:Real device
* Appium CLI or Appium.app|exe:CLI

**Comment by mykola-mokhnach** [comment]
The tap happens on WebDriverAgent side. There is nothing we can do about it in Appium.

**Comment by wangtao169447** [comment]
@mykola-mokhnach you mean , wda can help me?
i read wda source code, found that, wda use eventgenerator(a private api) to achieve it。

however, it is still slow.

**Comment by mykola-mokhnach** [comment]
Appium itself does not perform any clicks. We just proxy this command to webdriver agent, which executes it using XCTest primitives

**Comment by wangtao169447** [comment]
OK，thanks！
@mykola-mokhnach 
if i want modify wda and appium, to speed up tap function, Do you have any Suggestions？

**Comment by mykola-mokhnach** [comment]
Try to merge https://github.com/facebook/WebDriverAgent/pull/740 locally and then do it via W3C actions interface. I hope we'll release this feature in beta soon

**Comment by wangtao169447** [comment]
ok,thanks.

**Comment by Ghost2016** [comment]
@wangtao169447 Is that work fine?
