### ISSUE TITLE
iOS Element is missing when testing with appium-xcuitest-driver

### ISSUE THREAD

**Issue by Siko91** [appium/appium#9756]
## The problem

Hi.
When testing the iOS app XProtect Mobile with Appium and the xcuitest driver, I noticed that some elements don't appear in Appium. I investigated with the inspector, and even read the whole XML (from driver.PageSource) and verified that the element (and it's whole container) is really missing.

> ***Due to company policy, I can not show you the code of neither the application, the tests, the XML from driver.PageSource or even the appium logs.***
You will have to trust me that the elements are really missing.
I am allowed to tell you the name of the app (it's previous release is publicly available in the iOS Store) and to give you screenshots that (kind of) explain what happened.

## Environment

* Appium version (or git revision) that exhibits the issue: **1.6.5**
* Desktop OS used to run Appium: **OS X**
* Node.js version (unless using Appium.app|exe): **8.3.0**
* Mobile platform/version under test: **iOS 10.3**
* Real device or emulator/simulator: **Simulator**
* Appium CLI or Appium.app|exe: **CLI**

## Details

I am allowed to show you these screenshots.
These screenshots are sequential (and show parts of the application that are not related to new features and are available in the already released free application).

In the first screenshot you'll get some idea about what the test is doing.
- In picture 1 it is in search mode (searching 'All cameras')
- In picture 2 it closed the search window.
- in picture 3 and 4 it searched for some mocked camera ('ZZZ')
- in pictures 5 and 6 it tried to find the element "RECENT HISTORY" and fails

![](https://s8.postimg.org/782zhj3d1/screenshots1.jpg)
Now look at the second picture:
![](https://s8.postimg.org/mgswvahlx/screenshots2.jpg)

- The elements marked with green are all found successfully
- The element marked with red is missing. (It's container is also missing.)

it is obvious that the element is present in the app, but even so, this check fails:
> driver.PageSource.ToLower().Contains("history")

In the code of the app, all table groups (the ones marked witth green and the one marked with red) are declared in the same manner.
I went to an iOS developer from the company and he showed me with the inspection tool from XCode that the element really exists.
The only other option I could think of is if the element is being filtered out by either Appium or XCUITest

## Link to Appium logs
// Not available due to company policy

## Code To Reproduce Issue [ Good To Have ]
// Not available due to company policy

**Comment by mykola-mokhnach** [comment]
Unfortunately we cannot advice much if no data can be provided. Make sure the accessibility properties are properly set for the corresponding UI elements in the source code of your application under test. Check https://github.com/appium/appium/issues/6517 for the reference.
