### ISSUE TITLE
appium does not stop iOS simulator

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [appium/appium#9757]
## The problem

According to what I read in the appium forums (http://discuss.appium.io/t/how-to-close-ios-simulator-after-running-the-test/5828) the ios simulator should close if I call `driver.quit()` (using appium python client).

## Environment

* Appium version 1.7.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS High Sierre 10.13.1
* Node.js version (unless using Appium.app|exe): v7.7.1
* Mobile platform/version under test: iOS 11.2
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: cli

## Details

I am running appium tests on a remote server. I use many different simulators (iPad, iPad Pro, iPhone 5-7 etc.).
Because the simulators do not quit, after the tests all of them are open.

**Comment by mykola-mokhnach** [comment]
Simulators are not closed because of performance reasons. It would be too expensive to restart them for each new session.

**Comment by msan0217** [comment]
driver.quit is not working for me either. Appium 1.7.1 / iOS 11.1

This used to work before I upgraded my dependencies to support iOS11 testing
