### ISSUE TITLE
Appium1.7.1 - Webdriver agent is not installing on ipad through Xcode during code signing process

### ISSUE THREAD

**Issue by amitwagle** [appium/appium#9759]
**Problem**
 Webdriver agent is not installing on ipad through Xcode during code signing process. However, In Xcode it’s giving successfully installed message.

**Details**
I recently upgrade version of Xcode , Appium, iPAD OS and Mac OS and after that facing code signing issue on iPAD. Before that it was working properly.

I followed instruction https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md

Currently on Simulator its working properly however on ipad facing issue.

**Environment**
Appium version : 1.7.1
iPAD OS : 11.0.3.
Appium : 1.7.1 
Mac OS : 10.12.6
Node version : v8.2.1
Appium Desktop : 1.2.7

**Link to Appium logs after trying to open through Appium**

**Comment by amitwagle** [comment]
When I try to do Product->Test in XCode, I am able to run Webdriver Agent on iPad
However when I try to open the application through Appium it’s not opening.

[AppiumLogs1.txt](https://github.com/appium/appium/files/1540597/AppiumLogs1.txt)
 I am attaching log after keeping showXcodeLog = true

**Comment by imurchie** [comment]
```
Code Signing Error: No profiles for 'com.facebook.WebDriverAgentRunner' were found:  Xcode couldn't find any iOS App Development provisioning profiles matching 'com.facebook.WebDriverAgentRunner'.
```

You need either a wildcard provisioning profile, or change the bundle identifier for the project and pass in the changed id to Appium using the `updatedWDABundleId` capability. Please see https://github.com/appium/appium/blob/master/docs/en/drivers/ios-xcuitest-real-devices.md

**Comment by amitwagle** [comment]
Thanks for the reply.
I tried to follow the steps mention by you however no success.
I tried using wild card provisional profile but same error.
Also tried changing the bundle identifier and pass in the changed id to Appium using the updatedWDABundleId capability but getting same error. Attaching appium logs.
[AppiumLog2.txt](https://github.com/appium/appium/files/1554204/AppiumLog2.txt)

**Comment by amitwagle** [comment]
Since i am facing some other issue after today's upgrade i am closing the issue.
