### ISSUE TITLE
Am unable to inspect the elements with latest version of appium,

### ISSUE THREAD

**Issue by amitvinutha** [appium/appium#9760]
## The problem

I wanted to know how to take the xpath in new version of appium
## Environment

* Appium version (or git revision) that exhibits the issue:1.6.5
* Last Appium version that did not exhibit the issue (if applicable):1.4.16.1
* Desktop OS/version used to run Appium: Windows 8
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:Vivo
* Real device or emulator/simulator:Real Device
* Appium CLI or Appium.app|exe:Appium

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Please ask questions on Appium forum.
