### ISSUE TITLE
Android: when using tap(WebElement el, int x, int y), it always touches the center of the element

### ISSUE THREAD

**Issue by dustinchen48** [appium/appium#9761]
## The problem

When I'm using this method "TouchAction tap(WebElement el, int x, int y)", it always clicks the center of the element, no matter what  coordinates I have set.

## Environment

* Desktop Appium: 1.5.3
* io.appium.java-client: 4.1.2
* Selenium: 2.5.3
* Real device: Android 6.0.1
* Mac OS: 10.12.6

## Details

Coordinates in the command send to the device was correct, but when performing, the coordinates changes to the center of the element automatically.

new TouchAction(driver).tap(driver.findElementByXPath("xxxxxxx"), 480, 160).perform();

## Link to Appium logs

[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"element:touchDown","params":{"elementId":"7","x":726,"y":1472}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:touchDown","params":{"elementId":"7","x":726,"y":1472}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: touchDown
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Performing TouchDown using element? true x: 480, y: 1384

**Comment by mykola-mokhnach** [comment]
Appium 1.5.3 is oudated and is not supported anymore. Please use the most recent version (1.7.1)
