### ISSUE TITLE
Appium fails to start test then remains "busy" in selenium grid

### ISSUE THREAD

**Issue by tomljones** [appium/appium#9763]
## The problem

I have appium running in a selenium grid environment. There are 8 appium nodes connected to physical iPads. Each node will be able to run several tests in a row with no problem. Eventually, after several tests, the appium node will be idle but grid will think that it is still in use.

## Environment

* Appium version 1.7.1
* ios_webkit_debug_proxy 1.8
Built with libimobiledevice v1.2.0, libplist v2.0.0

* Last Appium version that did not exhibit the issue (if applicable): n/a
* Desktop OS/version used to run Appium: Appium is running on a MacBook Pro running 10.1.3.1
* Node.js version (unless using Appium.app|exe):Node v8.9.1
* Mobile platform/version under test: Physical iPad 5 and iPad Pros running various flavors of iOS 11
* Real device or emulator/simulator: Real iPads. 5th Generation and iPad Pro 9.7"
* Appium CLI or Appium.app|exe: running CLI

## Details

Selenium grid is running and shows the appium servers as nodes.
Tests are running fine.
Start a test running
While it is running, go to the selenium grid console and see that the appium node is shown as in use. Wait for the test to complete by watching the ipad.
When a test completes, we use an Xcode unit test to automatically wipe the Safari cache.
Go back to the selenium grid console and verify that the appium node shows that is is now idle.

Repeat this process a few times and eventually the appium node will be shown as always in use. The only solution is to manually restart the appium process.

## Link to Appium logs

It looks like we tried to start a new test at around line 307.
Apparently, the browser wouldn't load that page ... I'm not sure what failed here.
See line 422 for the last failure.
Right now, the node is marked as busy in selenium grid and has been this way for several hours.

https://gist.github.com/tomljones/79973701db147e9f022d16055cdd7046

Here is the appium nodeConfig.
https://gist.github.com/tomljones/95718bd69df2946147eee9a9dfa9dbdd

I'm running appium like this:
./bin/ios-webkit-debug-proxy-launcher.js -c null:27756,4903f2a18515b0f7c72fb41f96fa93f7637ab9e4:27757

appium --nodeconfig ~/appium_run/nodeConfigLFW1324.json -p 4724 --webkit-debug-proxy-port 27756 --webdriveragent-port 8101 --safari -g appium4724.out

It would be nifty to figure out why the test could not start successfully, I suspect there is a problem with ios_web_debug_proxy. However, I would be happy to get the node back available in selenium grid.

## Code To Reproduce Issue [ Good To Have ]

Sorry, not sure how to make this reproducible short of replicating the entire environment!

**Comment by ochubey** [comment]
@tomljones are you sure, that test, after completion has driver.quit()?

**Comment by tomljones** [comment]
I definitely have the call to quit in the tests. It is possible that the test is crashing and not calling quit. I will investigate that. If I still think there is a problem then I'll use the appium sample code and setup a way to reproduce the problem.

**Comment by tomljones** [comment]
I think I have found the problem. Today, my webapp was running very slow because it was waiting on an external resource. Appium eventually recycled and was ready for the next test, but selenium grid and the selenium test still thinks it is in-use.

Here are the appium logs https://gist.github.com/tomljones/94cfcdf955d08f04b573e9910126a4f5

Here are the logs from my selenium run. I _think_ that the selenium log line 16 roughly matches with the appium log around line 444.
https://gist.github.com/tomljones/e1226608c054df202248effe50c67eb1

Any idea what is going wrong here? Originally I thought it was something related to the newCommandTimeout but I don't see that mentioned in the appium logs.

**Comment by tomljones** [comment]
It is still happening to me, the log from today is in the gist below. The problem seems to center around a timeout?
Encountered internal error running command: TimeoutError: operation timed out
https://gist.github.com/tomljones/4ea7b8c4637343cebb4c91319b72b46f
Any ideas for me?

**Comment by mykola-mokhnach** [comment]
Closed as inactive
