### ISSUE TITLE
Element location is incorrect in Appium

### ISSUE THREAD

**Issue by BenAychh** [appium/appium#9764]
## The problem

My clicks are not working because some of my elements are getting incorrect locations in iOS (both in tests and in inspector)

## Environment

* Appium version (or git revision) that exhibits the issue: Appium Desktop 1.2.7
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Mac (Sierra)
* Mobile platform/version under test: iOS 11.1
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: Appium.app

## Details

As you can see from the picture below, some of my elements are not in the correct location. The "Length: 30 minutes" appears to be selected but if you look at the details you can see it is actually the line above it that is supposed to be selected.
<img width="1077" alt="image" src="https://user-images.githubusercontent.com/16299846/33736556-4a8516fa-db50-11e7-8cec-3a9d178bc399.png">

## Link to Appium logs
N/A (I don't think, this is from the inspector)

## Code To Reproduce Issue [ Good To Have ]
You can use these desired capabilities to see it in action:

```
{
  "platformName": "iOS",
  "platformVersion": "11.1",
  "deviceName": "iPhone 7",
  "app": "https://s3.amazonaws.com/bookit-mobile-artifacts/local-testing.ipa"
}
```

**Comment by mykola-mokhnach** [comment]
is frame value returned for the selected element is sync with the highlighted area?

**Comment by BenAychh** [comment]
Are you talking about the attributes? If so, then yes, the attributes x and y match the highlighted area. If there is some other concept of a frame value, then I am sorry, I just started using Appium yesterday and I am not sure where to find the frame value.

**Comment by mykola-mokhnach** [comment]
If the element frame matches to the selected area then is has nothing to do with Appium. It's either XCTest or [WebDriverAgent](https://github.com/facebook/WebDriverAgent/issues) issue.
