### ISSUE TITLE
Need info: Double two finder tap on iOS mobile

### ISSUE THREAD

**Issue by uarlouski** [appium/appium#9767]
## The question
Is it possible to execute double two finger tap on iOS device? Maybe is it possible to run executeScript mobile: twoFingerTap as multi action?
I have tried to use: 
- mobile: twoFingerTap but as it turned out it takes only element as param and no count number for taps.
- Any attempts to emulate it with MultiTouchAction led to "Support for this multi-action is not implemented. Try to use "mobile: *"" and as I understood only swipe/pinch sequences are supported
If there are any tips please let me know

**Comment by mykola-mokhnach** [comment]
Better support of touch actions along with partial support of W3C actions is coming into Appium beta. We'd be happy if you want to join the testing team.

**Comment by uarlouski** [comment]
Thanks for answer, but which appium beta version did you mean?

**Comment by mykola-mokhnach** [comment]
It is not available yet. The code didn't pass the alpha stage yet.

**Comment by ManningZhang** [comment]
@mykola-mokhnach @uarlouski do you have any suggestion about how to apply double two finder tap on iOS mobile ？？thanks a lot
