### ISSUE TITLE
driver.setUrl not working on ios Real device

### ISSUE THREAD

**Issue by UtsavSaha** [appium/appium#9773]
## The problem

driver.seturl api fails in ios real device with error 

> "value":"Failed to open

## Environment

* Appium version : 1.7.1. 
* OS : MacOS High Sierra 10.13.1 
* Node.js version : v8.6.0
* Mobile platform/version under test: iphone 5s . iOS : 11.1
* **Real device**
* Appium desktop version : 1.2.6

## Note

The same code and config is working on simulator.

## Link to Appium logs

Appium logs can be found [here](https://gist.github.com/UtsavSaha/0d39f54eb9cd0a4d0e155ba4f8902c0f)

Client logs marks the error as following : 
 _**Error: [get("http://www.google.co.in")] Error response status: 13, UnknownError - An unknown server-side error occurred while processing the command. Selenium error: An unknown server-side error occurred while processing the command. Original error: Failed to open http://www.google.co.in**_

## Code To Reproduce Issue [ Good To Have ]

javascript webdriver is being used to connect to the appium server.

`driver = wd.promiseChainRemote(serverConfig); driver.init(desired).backgroundApp(0).get("http://www.google.co.in");
`

**Comment by mykola-mokhnach** [comment]
You should be in web context in order to use this endpoint. The fact that it does not work from native context on real devices is know XCTest limitation and it cannot be workarounded.

**Comment by UtsavSaha** [comment]
Great that sorts out the issue.
Could you suggest a way on how open url test cases can be executed in appium? I have few use cases where my mobile app needs to be launched via url and would perform subsequent actions on app,can they be tested using appium?

**Comment by mykola-mokhnach** [comment]
Test it on simulator

**Comment by UtsavSaha** [comment]
@mykola-mokhnach  Will this issue be true in case of android as well?
