### ISSUE TITLE
Unable to find exact element from screen, Instead of it, Uiautomator2 identifying behind page element

### ISSUE THREAD

**Issue by sagarsheth27** [appium/appium#9776]
When i want to recognize element value of a page, Uiautomator identifying behind page element. So what i have to do for same?.
Scenario is like below.
whenever user installed app first time in mobile ,he/ she has to must agree terms and agreement of an 
![ss1](https://user-images.githubusercontent.com/32329719/33830524-986ef410-de9a-11e7-8241-19f9637d1171.png)
app. But when i called it through automation it is every time displayed and do not recognize properly by Uiautomator. So what to do, to click on AGREE?

**Comment by sagarsheth27** [comment]
Behind screen SS.
![ss2](https://user-images.githubusercontent.com/32329719/33830585-cb40f9d8-de9a-11e7-99c7-e8ccbfa8b758.png)

**Comment by vjmaiky** [comment]
is terns of use present in a web page?

**Comment by sagarsheth27** [comment]
I tried it. But it's not working. Sometime context view appeared or
sometime not. Whenever context view appeared at that time I was also unable
to click on it.

**Comment by Corji** [comment]
Propably its somewhere in the tree on the right. In my case the pop ups are listet below in the tree and i cant click them directly on the screen in ui automator viewer. Just expand the whole tree and search there for your element.

**Comment by sagarsheth27** [comment]
Thanks @Corji 
Its working now
