### ISSUE TITLE
Appium lost connection to simulator on iOS

### ISSUE THREAD

**Issue by viktorkalmus** [appium/appium#9778]
## The problem
Looks like appium lost connection to appium-server during tests on iOS simulator.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Desktop OS/version used to run Appium: MacOS 10.13.1
* Node.js version (unless using Appium.app|exe): 7.3.0
* Mobile platform/version under test: iOS Simulator 10.3.1 iPhoneSE
* Real device or emulator/simulator: simulator

## Details

During tests, appium has stuck for 20 minutes without any info, and according to log it has lost connection to simulator. It is not reproducing every time and not always on same test. 

## Link to Appium logs

11:48:38.628 [Test worker] DEBUG (BaseWait.java:304): Success in 1534 ms: ByWait
    	- Object:   [By.className: XCUIElementTypeCell]
    	- From:     [Method [waitForScreen] in .(MyProjectActions.java:119)]
    	- Action:   [check if element is displayed]
    12:28:42.914 [Test worker] ERROR (CustomTestListener.java:44): Test [MyProjectTests.checkFavoriteTrips] failed: org.apache.http.NoHttpResponseException: 127.0.0.1:35709 failed to respond
    Build info: version: ‘3.5.3’, revision: ‘a88d25fe6b’, time: ‘2017-08-29T12:42:44.417Z’
    System info: host: ‘administrators-Mac-mini.local’, ip: ‘fe80:0:0:0:100c:b061:772e:4a6d%en0’, os.name: ‘Mac OS X’, os.arch: ‘x86_64’, os.version: ‘10.13.1’, java.version: ‘1.8.0_111’
    Driver info: driver.version: IOSDriver
    	Stacktrace:io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:104)
    	org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:646)
    	io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
    	io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
    	io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
    	org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions$RemoteTimeouts.implicitlyWait(RemoteWebDriver.java:877)
    	io.appium.java_client.pagefactory.AppiumElementLocator.changeImplicitlyWaitTimeOut(AppiumElementLocator.java:80)
    	io.appium.java_client.pagefactory.AppiumElementLocator.waitFor(AppiumElementLocator.java:98)
    	io.appium.java_client.pagefactory.AppiumElementLocator.findElements(AppiumElementLocator.java:132)
    	io.appium.java_client.pagefactory.interceptors.InterceptorOfAListOfElements.intercept(InterceptorOfAListOfElements.java:50)
    	$java.util.ArrayList$$EnhancerByCGLIB$$b5855c01.iterator(<generated>)
    	com.techery.dtat.actions.MyProjectActions.getTripNamesFromLoadedTrips(MyProjectActions.java:62)
    	com.techery.dtat.steps.MyProjectSteps.assertThatAllTripNamesMatchedExpectedTripNames(MyProjectSteps.java:190)
    	com.techery.dtat.tests.MyProjectTests.checkFavoriteTrips(MyProjectTests.java:151)
    	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	java.lang.reflect.Method.invoke(Method.java:498)
    	org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
    	org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
    	org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
    	org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
    	org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
    	org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
    	org.testng.TestRunner.privateRun(TestRunner.java:776)
    	org.testng.TestRunner.run(TestRunner.java:634)
    	org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
    	org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
    	org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
    	org.testng.SuiteRunner.run(SuiteRunner.java:334)
    	org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
    	org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
    	org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
    	org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
    	org.testng.TestNG.runSuites(TestNG.java:1161)
    	org.testng.TestNG.run(TestNG.java:1129)
    	org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.runTests(TestNGTestClassProcessor.java:129)
    	org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.stop(TestNGTestClassProcessor.java:88)
    	org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
    	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	java.lang.reflect.Method.invoke(Method.java:498)
    	org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    	org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    	org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
    	org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
    	com.sun.proxy.$Proxy2.stop(Unknown Source)
    	org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:120)
    	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	java.lang.reflect.Method.invoke(Method.java:498)
    	org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    	org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    	org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:147)
    	org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:129)
    	org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
    	org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
    	org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
    	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    	java.lang.Thread.run(Thread.java:745)
    12:28:42.921 [Test worker] INFO  (AllureHelper.java:40): Saving screenshot to Allure report: Screenshot on test failure

All tests > All Tests > com.techery.dtat.tests.MyProjectTests.checkFavoriteTrips STANDARD_ERROR
    Dec 11, 2017 12:38:42 PM org.apache.http.impl.execchain.RetryExec execute
    INFO: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://127.0.0.1:35709: The target server failed to respond
    Dec 11, 2017 12:38:42 PM org.apache.http.impl.execchain.RetryExec execute
    INFO: Retrying request to {}->http://127.0.0.1:35709
    Dec 11, 2017 12:48:43 PM org.apache.http.impl.execchain.RetryExec execute
    INFO: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://127.0.0.1:35709: The target server failed to respond
    Dec 11, 2017 12:48:43 PM org.apache.http.impl.execchain.RetryExec execute
    INFO: Retrying request to {}->http://127.0.0.1:35709
    Dec 11, 2017 12:58:43 PM org.apache.http.impl.execchain.RetryExec execute
    INFO: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://127.0.0.1:35709: The target server failed to respond
    Dec 11, 2017 12:58:43 PM org.apache.http.impl.execchain.RetryExec execute
    INFO: Retrying request to {}->http://127.0.0.1:35709
    Dec 11, 2017 1:18:45 PM org.apache.http.impl.execchain.RetryExec execute
    INFO: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://127.0.0.1:35709: The target server failed to respond
    Dec 11, 2017 1:18:45 PM org.apache.http.impl.execchain.RetryExec execute
    INFO: Retrying request to {}->http://127.0.0.1:35709
    Dec 11, 2017 1:28:45 PM org.apache.http.impl.execchain.RetryExec execute
    INFO: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://127.0.0.1:35709: The target server failed to respond
    Dec 11, 2017 1:28:45 PM org.apache.http.impl.execchain.RetryExec execute
    INFO: Retrying request to {}->http://127.0.0.1:35709

**Comment by mykola-mokhnach** [comment]
I cannot help without having the server log. also the simulator might be useful.

**Comment by viktorkalmus** [comment]
@mykola-mokhnach Thanks, I'll try to get those logs, but its really looks like this issue:
https://github.com/facebook/WebDriverAgent/issues/507
Symptoms looks similar. I will try your fix, if it wouldn't help, then I will search for logs

**Comment by mykola-mokhnach** [comment]
If it is that issue then there is nothing we can do from Appium side. Just try not to redeploy WDA on the device for as long as possible
