### ISSUE TITLE
error in launching Appium on mac using SSH on windows

### ISSUE THREAD

**Issue by prateekchawla** [appium/appium#9781]
## The problem

Using putty, on ssh port I am executing the command "Appium" but since it is not a recognized command. I want to navigate to the the appium path as i need to give it to my putty in cli. 
My appium in installed at path "/usr/local/lib/node_modules/appium/build/lib/main.js"

## Details

When  I run the command "Appium" using putty it gives an error but since it is a environment variable that is used to launch appium on mac CLI.

**Comment by prateekchawla** [comment]
I am using CLI appium on my mac

**Comment by mykola-mokhnach** [comment]
The issue happens because of local env configuration and has nothing to do with Appium itself
