### ISSUE TITLE
Fix TestObject chromedriver issue

### ISSUE THREAD

**Issue by dpgraham** [appium/appium#9782]
TestObject WebView test is failing. Cannot find Chromedriver binary (see https://ci.appveyor.com/project/dpgraham/appium-uiautomator2-driver/build/1.0.194/job/q851hjkb61wqv36r)

This test is being skipped for now but should be fixed because it's important to test WebViews on real devices.

**Comment by imurchie** [comment]
Is the CD binary being downloaded when the bundle that gets run on TO gets built?

**Comment by mykola-mokhnach** [comment]
@dpgraham is this issue still relevant?
