### ISSUE TITLE
get server-side error after upgrade xCode to 9.2 while running ios10.x simulator

### ISSUE THREAD

**Issue by niu0220** [appium/appium#9784]
## The problem

I have trouble to run testing on iOS 10.x simulator after upgrade xCode to  9.2, and getting server-side error occurred while processing the command, but I am able to run the testing on iOS 11.2 simulator.
any idea how to avoid this problem???

<img width="443" alt="screen shot 2017-12-12 at 12 25 46 pm" src="https://user-images.githubusercontent.com/31452800/33908481-64d93892-df3d-11e7-8227-7008699c917b.png">

## Environment

* Appium version (or git revision) that exhibits the issue: Appium v1.7.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS High Sierra
* Node.js version (unless using Appium.app|exe): 8.6.0
* Mobile platform/version under test: Sim 10.3.1 (not working), Sim 11.2 (working)
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: appium-desktop

## Link to Appium logs

iOS 10.3: 
[ios10.3.1.txt](https://github.com/appium/appium/files/1553269/ios10.3.1.txt)

iOS 11.2:  
[ios11.2.txt](https://github.com/appium/appium/files/1553271/ios11.2.txt)

**Comment by mykola-mokhnach** [comment]
Try Appium@beta. If this still does not work then report an issue into https://github.com/facebook/WebDriverAgent/issues along with device logs.
