### ISSUE TITLE
W3C prefixing and validation

### ISSUE THREAD

**Issue by dpgraham** [appium/appium#9785]
Still a couple more issues to resolve before we can call Appium W3C compliant

* Need to accept prefixed capabilities (e.g.: `appium:platformVersion`)
* Needs to parse capabilities inside of Appium and not just Appium Base Driver (W3C session requests won't pass https://github.com/appium/appium/blob/3d7dd1e857ddd64eb310d89b44b75d62208dadfe/lib/appium.js#L64 because caps.platformName is undefined)

Acceptance criteria
* [ ] Passes unit tests that supply `appium:` prefixes in W3C sessions
* [ ] Passes unit tests that supply W3C capabilities to appium (and not just appium-base-driver)
* [ ] Can successfully create session with following W3C capabilities ```curl -X POST http://ondemand.saucelabs.com/wd/hub/session -d '{"capabilities": {"alwaysMatch": {"sauce:_enforceProtocol": "w3c", "sauce:username": "...", "browserName": "chrome", "appium:deviceName": "Android Emulator", "sauce:accessKey": "...", "platformName": "Android", "platformVersion": "6.0", "sauce:appiumVersion": "1.7.1"}, "firstMatch": [{}]}}' -L -D -```

**Comment by sah** [comment]
I suspect these keys will need to be under the `appium:` prefix:

    'app',
    'deviceName',
    'locale',
    'language',

I suspect these keys will be unprefixed:

    'acceptInsecureCerts',
    'browserName',
    'browserVersion',
    'platformName',
    'pageLoadStrategy',
    'proxy',
    'setWindowRect',
    'timeouts',
    'unhandledPromptBehavior',

I don't know about these:

    'automationName',
    'platformVersion',

**Comment by dpgraham** [comment]
@sah For now we'll just accept non standard caps, with or without the prefix
