### ISSUE TITLE
Starting Java Appium error (java -version exited code 1)

### ISSUE THREAD

**Issue by rido-ramadan** [appium/appium#9787]
## The problem

Trying to run Appium 1.7.1 in Windows 10 x64 with Run As Administrator permission to test my Android app. The automation test is written in python with Appium python client 0.25. When I run

`python android-test.py`

Appium server return this error:

`[MJSONWP] Encountered internal error running command: Error: Command 'java -version' exited with code 1 at ChildProcess.<anonymous> (../../lib/teen_process.js:92:19)`

## Environment

* Appium server version: 1.7.1
* Local OS Server: Windows 10 x64 Fall Creators Update 1709
* Node.js version: 8.4.0
* NPM version: 5.3.0
* Mobile platform/version under test: Android
* Device: Real Asus Zenfone 5 T00J
* Appium CLI

## Link to Appium logs

Appium Log [see here](https://gist.github.com/rido-ramadan/1533eb68403a32b318ecbd3bc93797b9)

## Code To Reproduce Issue

Appium Test Suite [see here](https://gist.github.com/rido-ramadan/8e5ff8dda2224e29374425a5d3197cd4)

**Comment by mykola-mokhnach** [comment]
UIAutomater2 is only compatible to Android 5.0+
Also, make sure that java binary is in PATYH and is visible to Appium process

**Comment by rido-ramadan** [comment]
Unfortunately, no, it is still the same. I've changed the device to Lollipop and the APK is clearly there in the specified directory, still error `Command 'java -version' exited with code 1`

**Comment by rido-ramadan** [comment]
For the error above, it is already solved. Java is error due to upgrade to Windows 10 1709 and java doesn't work correctly.

Well, next question then.  `Error: The file at path C:\Users\Edgar Drake\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-driver\uiautomator2\appium-uiautomator2-server-v0.1.8.apk does not exist or is not accessible`

The problem is, after installing the appium-uiautomator2-driver, the APK version is 0.2.0. How to fix that? Change the file name? Or which component do I need to update?

**Comment by mykola-mokhnach** [comment]
Most likely you have problems with permissions in that folder. Closed as not an issue.
