### ISSUE TITLE
Error: Could not proxy

### ISSUE THREAD

**Issue by JanePes** [appium/appium#9789]
## The problem

I get an error 
"Top level suite
    × Non-spec failure
      - WebDriverError: An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: Error: ESOCKETTIMEDOUT" 
when running simple test for Hybrid application on real Android device

## Environment

* Appium version (or git revision): 1.7.1
* Desktop OS/version used to run Appium: Win 8x64
* Node.js version: 6.9.2
* Npm version: 3.10.9
* Mobile platform/version under test: Android 7.1.1
* Real device or emulator/simulator: Real device, Nexus 9
* Appium CLI or Appium.app|exe: Appium Desktop
* framework: 'jasmine2'

## Details

The application is installed on a real device. Tests simply start the application, check the presence of the element. Then you receive an error message.
I found https://github.com/appium/appium/issues/7063 but I still don't know how to solve the problem.

## Link to Appium logs

https://gist.github.com/JanePes/733d5bbe34c49975ef2210d10621dc45

## Code To Reproduce Issue [ Good To Have ]

Part of 'config.js':
  ```
beforeLaunch: function () {
        return new Promise(function (resolve) {
            reporter.beforeLaunch(resolve);

            if (fs.existsSync('jasmine-results.json.lock')) {
                fs.unlinkSync('jasmine-results.json.lock');
            }
            if (fs.existsSync('jasmine-results.json')) {
                fs.unlink('jasmine-results.json');
            }
        });
    },
    onPrepare: function () {

        wdBridge.initFromProtractor(exports.config);
        jasmine.getEnv().addReporter(reporter);
        var SpecReporter = require('jasmine-spec-reporter').SpecReporter;
        jasmine.getEnv().addReporter(new SpecReporter({displayStacktrace: 'all'}));

        browser.ignoreSynchronization = true;
    },

```

**Comment by mykola-mokhnach** [comment]
I see there was a problem while getting a screenshot from the device
> [debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/58b6ee22-f2ae-4d19-96b2-147699b13b09/screenshot] to [GET http://127.0.0.1:8000/wd/hub/session/9427e5d02af47f3f231db06736c712fb/screenshot] with body: {}[error] [MJSONWP] Encountered internal error running command: Error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: Error: ESOCKETTIMEDOUT

Do you see any errors in logcat output when this error happens?

**Comment by VenkateshPS** [comment]
I have seen this error several times and there was no code in script to take screenshot. 
My guess is Appium tries taking screen shot when failure happens. At times Appium hangs while entering text in text field and in failure exception you can see that take screenshot was called.

**Comment by JanePes** [comment]
Here Logcat output https://gist.github.com/JanePes/c33133e128f0cb41620aa0cea3a405fb , I don't see any errors. And there are no failures in the test.
I just open the app and type text in console 
```
 it("Get Login page", function () {
        console.log('Get Login page');
    });
```
and after that the error occurs.

**Comment by JanePes** [comment]
I tried to run this simple test in project for another app (that works really fine). I just changed the appPackage. And as I see I received the same problem 
```
[HTTP] <-- POST /wd/hub/session/72be8501-d00e-4635-a242-711aa1a46cdc/elements 500 240029 ms - 281 
[HTTP] --> GET /wd/hub/session/72be8501-d00e-4635-a242-711aa1a46cdc/screenshot {}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[JSONWP Proxy] Proxying [GET /wd/hub/session/72be8501-d00e-4635-a242-711aa1a46cdc/screenshot] to [GET http://127.0.0.1:8000/wd/hub/session/53f586e35c0aefdd48947531de444b72/screenshot] with body: {}
[MJSONWP] Encountered internal error running command: Error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: Error: ESOCKETTIMEDOUT
    at doJwpProxy$ (C:\Users\ypastukhova\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\mjsonwp\mjsonwp.js:384:13)
    at tryCatch (C:\Users\ypastukhova\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\ypastukhova\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\ypastukhova\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\ypastukhova\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[HTTP] <-- GET /wd/hub/session/72be8501-d00e-4635-a242-711aa1a46cdc/screenshot 500 240023 ms - 281 
```
 So maybe smth wrong with the app?

**Comment by VenkateshPS** [comment]
can you try killing iProxy and re run your test.

**Comment by JanePes** [comment]
@VenkateshPS sorry, can you explain how to do this? thank you!

**Comment by VenkateshPS** [comment]
Get process id of iProxy and kill the iProxy process.
Getting pid on mac: brew install pidof, pidof gives process id of an Application.

**Comment by JanePes** [comment]
@VenkateshPS On Windows I don't see such process

**Comment by VenkateshPS** [comment]
Sorry that is not applicable for Windows.

**Comment by JanePes** [comment]
I found a solution. 
I added 
```
nativeWebScreenshot: true,
androidScreenshotPath: 'target/screenshots',
```
in capabilities and now all works fine

**Comment by praveenbaliga** [comment]
> I found a solution.
> I added
> 
> ```
> nativeWebScreenshot: true,
> androidScreenshotPath: 'target/screenshots',
> ```
> in capabilities and now all works fine

Thanks @JanePes , I spent almost 2 days without any solution. Just added 2 lines mentioned by you and it worked like a charm!!!

**Comment by jenhbo** [comment]
I use browserstack to run all scripts, my scripts failed at the same issue,  no ways to add the parameters. are there any other solutions ?

**Comment by Arav4prot** [comment]
> I found a solution.
> I added
> 
> ```
> nativeWebScreenshot: true,
> androidScreenshotPath: 'target/screenshots',
> ```
> in capabilities and now all works fine

Thanks a lot it worked for me!

**Comment by abhisqa** [comment]
@mykola-mokhnach 
Original error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: Error: ESOCKETTIMEDOUT
I am getting similar error while trying to switch to alert in real android device. this alertview consist multiple 'FrameLayout' and than there is i  button inside where i need to click. but when i reach this alert pop up window execution seems halted for almost 8-10 minutes and than it throws this error.

I am using appium desktop version 1.16 now. 
I also can attach the appium logs if required.


[Logs.txt](https://github.com/appium/appium/files/4197220/Logs.txt)

**Comment by abhisqa** [comment]
@mykola-mokhnach I am facing similar issue 
(Could not proxy. Proxy error: Could not proxy command to remote server. Original error: Error: ESOCKETTIMEDOUT)
When try to switch to a alert pop up which consist multiple 'FarmeLayout' and than i need to tap on a button inside this pop up. in my case execution is halted for 8-10 minutes and than this error occurred.
I am using Appium desktop 1.16 and attaching the appium logs for reference.

[Logs.txt](https://github.com/appium/appium/files/4197479/Logs.txt)
