### ISSUE TITLE
Stackoverflow error when trying to run rspec tests

### ISSUE THREAD

**Issue by mcking49** [appium/appium#9792]
## The problem

I am running the command ```bundle exec rspec``` to run my rspec tests on an appium server. I am getting the error ```RangeError: Maximum call stack size exceeded``` and all my tests fail to run. I have tried googling for this issue and haven't found any solutions. I am using Selenium.

## Environment

* Appium version: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable): 1.7.1
* Desktop OS/version used to run Appium: macOS 10.13.2
* Node.js version (unless using Appium.app|exe): v6.11.5
* Mobile platform/version under test: iOS 11.1
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: --
* Xcode version: 9.1 (tools v9.2.0.0.1.1510905681)

## Details

Please refer to gist of the issue.

## Link to Appium logs
https://gist.github.com/mcking49/6560514948532196cac62e38b79087bd

**Comment by mykola-mokhnach** [comment]
It looks like your Simulator config file is corrupted. Try to delete it by path `~/Library/Preferences/com.apple.iphonesimulator.plist` and restart the test
