### ISSUE TITLE
Device is not online

### ISSUE THREAD

**Issue by maloz** [appium/appium#9794]
## The problem

When I want to run some tests on my hybrid app (Make on Cordova), I can only access the Native element. When I’m trying to switch to Webview, I get "Device XXXXXXX is not online", even if the device is connected and I can see it using `adb devices`

## Environment

* Appium version 1.7.1
* Windows 10
* Android 7.0
* Device: Samsung S7 Edge
* Appium CLI
* Chromedriver 2.9.248315

## Link to Appium logs

Appium logs:  [https://gist.github.com/maloz/0145e5c4645ce105c24ef7392acd7458]( https://gist.github.com/maloz/0145e5c4645ce105c24ef7392acd7458)

## Code To Reproduce Issue [ Good To Have ]

```
  ` public void setupTest() {
    DesiredCapabilities capabilities = new DesiredCapabilities();
    capabilities.setCapability("app", "C:/APKs/myStart_2.0.7.apk");
    capabilities.setCapability("deviceName", "9885b6514930495a35");
    capabilities.setCapability("platformName", "Android");
    capabilities.setCapability("platformVersion", "7.0");

    URL serverAddress = null;
    try {
        serverAddress = new URL("http://0.0.0.0:4723/wd/hub");
    } catch (MalformedURLException e) {
        e.printStackTrace();
    }
    driver = new AndroidDriver<WebElement>(serverAddress, capabilities);
    driver.manage().timeouts().implicitlyWait(60, TimeUnit.SECONDS);

}

@Test
public void myTest() {

    System.out.println("AppLogin() :: driver.start() executed");
    WebDriverWait wait = new WebDriverWait(driver,15000);
    Set<String> availableContexts1 = driver.getContextHandles();
    System.out.println("Total No of Context Found Before reaching WebView = "+ availableContexts1.size());
    System.out.println("Context Name is "+ availableContexts1);

    driver.findElement(By.xpath("//android.widget.FrameLayout[contains(@resource-id,'android:id/content')]")).click(); //WORK

    Set<String> availableContexts = driver.getContextHandles();
    System.out.println("Total No of Context Found After we reach to WebView = "+ availableContexts.size());
    for(String context : availableContexts) {
        if(context.contains("WEBVIEW")){
            System.out.println("Context Name is " + context);
            driver.context(context); //Crash here
            break;
        }
    }

    //Never work neither
    WebElement spinner = driver.findElement(By.xpath("//android.widget.Spinner[@index='0']"));
    spinner.click();

}`
```

**Comment by mykola-mokhnach** [comment]
Use the chromedriver version, which matches to the webview version: https://github.com/appium/appium/blob/aa9711817436cb0bd7962c3f85db6efe2c9c8d02/docs/en/writing-running-appium/web/chromedriver.md

**Comment by maloz** [comment]
Right, thanks, I had not the good one. But now, still getting an error:

> [debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"f1be702cf8f52ce5a4064df529b97f4b","status":13,"value":{"message":"unknown error: unable to discover open pages\n  (Driver info: chromedriver=2.31.488763 (092de99f48a300323ecf8c2a4e2e7cab51de5ba8),platform=Windows NT 10.0.16299 x86_64)"}}

One I already get sometimes. Any idea on this one ?

**Comment by mykola-mokhnach** [comment]
Perhaps it is still not the correct one. Try 2.32 or 2.33

**Comment by maloz** [comment]
The thing is I can go on chrome://inspect/#devices and see my device and event play with the Chrome App.
Would you say, knowing this, that my problem come all from the app I try to debug ?
If yes, what do I have to change (Cordova app with Crosswalk webview)

**Comment by chandrasekharmelam** [comment]
Please provide server logs?
How you are starting the Appium?
If you are starting from command, please provide the command?

**Comment by chandrasekharmelam** [comment]
Please try this
https://github.com/appium/appium/issues/5616

**Comment by chandrasekharmelam** [comment]
It seems like below issue:

https://github.com/appium/appium/issues/5616

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
