### ISSUE TITLE
runAppInBackground returns "Timeout waiting until SpringBoard is visible" error for iOS 11

### ISSUE THREAD

**Issue by korenevichev** [appium/appium#9795]
## The problem

runAppInBackground method returns error for iOS 11: 
ERROR - An unknown server-side error occurred while processing the command. Original error: Error Domain=com.facebook.WebDriverAgent Code=1 "Timeout waiting until SpringBoard is visible" UserInfo={NSLocalizedDescription=Timeout waiting until SpringBoard is visible}
Btw the method works fine with iOS 10. 

## Environment

Appium version (or git revision) that exhibits the issue:1.7.1
Desktop OS/version used to run Appium: Mac OS Siera 10.12.6
Node.js version (unless using Appium.app|exe):v7.2.1
Mobile platform/version under test: 11
Real device or emulator/simulator: Real Device
Appium CLI or Appium.app|exe:Appium CLI

## Link to Appium logs

https://gist.github.com/korenevichev/b96a01f2a46c17f0262a5428a277587c

## Code To Reproduce Issue [ Good To Have ]

appiumDriver().runAppInBackground(Duration.ofSeconds(3))

**Comment by mykola-mokhnach** [comment]
this is an issue on WebDriverAgent side. Try the recent Appium beta. Perhaps there it works better
