### ISSUE TITLE
uninstall and re-install io.appium.settings

### ISSUE THREAD

**Issue by jerem0808** [appium/appium#9797]
## The problem

Each time I am using Open Application Keyword with Robot Framework, appium is checking, removing and installing the setting apk. It takes a lot of time and I don't understand why it does this. Is it possible to disable these actions ? If yes how.

## Environment

* Appium version (or git revision) that exhibits the issue: Appium 1.7.1
* Desktop OS/version used to run Appium: Ubuntu 16.04 LTS  64 bits
* Node.js version (unless using Appium.app|exe): 5.5.1
* Mobile platform/version under test: Android 7.1.2
* Real device: Nexus 5 - LineageOS
* Appium CLI

## Link to Appium logs

> [debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/usr/bin/adb' with args: ["-P",5037,"-s","02b3626708e6be2a","shell","pm","list","packages","io.appium.settings"]
[debug] [ADB] App is installed
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/usr/bin/adb' with args: ["-P",5037,"-s","02b3626708e6be2a","shell","am","force-stop","io.appium.settings"]
[debug] [ADB] Running '/usr/bin/adb' with args: ["-P",5037,"-s","02b3626708e6be2a","uninstall","io.appium.settings"]
[debug] [ADB] ADB command output: Success
[ADB] io.appium.settings was successfully uninstalled
[debug] [ADB] Getting install status for io.appium.settings
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/usr/bin/adb' with args: ["-P",5037,"-s","02b3626708e6be2a","shell","pm","list","packages","io.appium.settings"]
[debug] [ADB] App is not installed
[debug] [ADB] App '/usr/local/lib/node_modules/appium/node_modules/io.appium.settings/app/build/outputs/apk/settings_apk-debug.apk' not installed. Installing
[debug] [ADB] Running '/usr/bin/adb' with args: ["-P",5037,"-s","02b3626708e6be2a","install","/usr/local/lib/node_modules/appium/node_modules/io.appium.settings/app/build/outputs/apk/settings_apk-debug.apk"]

Thank you

**Comment by mykola-mokhnach** [comment]
this has been already fixed in beta
