### ISSUE TITLE
StaleObjectException when clicking an element in native Android application

### ISSUE THREAD

**Issue by lepadellec** [appium/appium#9798]
## The problem

I am testing a native Android application using Appium, I am using the PHP client. I locate an element and then less than 1 second later send a click to that element and am informed that I have a StaleObjectException, my screenshot shows that the element is still present. 

## Environment

* Appium version 1.7.1
* running in docker (runs Ubuntu 16)
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Android 7.1.1
* Real device or emulator/simulator: emulator

## Link to Appium logs

attached
[appiumLog.txt](https://github.com/appium/appium/files/1560066/appiumLog.txt)

## Code To Reproduce Issue [ Good To Have ]

$button = $I->getAppiumDriver()->byId('com.toto.toto:id/toto_button');
$button->click();

**Comment by mykola-mokhnach** [comment]
Try to locate the button at the same time when click is performed (e.g. eliminate the `button` variable)
