### ISSUE TITLE
appium does not register correctly with selenium grid 3.8.1

### ISSUE THREAD

**Issue by simbas** [appium/appium#9802]
## The problem

I was trying to register an appium node with android capabilities to a selenium hub. But Appium 1.7.1 doesn't register correctly with selenium grid 3.8.1, the capabilities are not displayed in the grid interface. However it seems to work with selenium grid 3.7.1.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable): -
* Desktop OS/version used to run Appium: -
* Node.js version (unless using Appium.app|exe): v8.6.0
* Mobile platform/version under test: android
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: Appium CLI 

### appium

```json
{
	"capabilities": [
		{
		      "browserName":"Chrome",
		      "deviceName":"samsungs6",
		      "version":"7.0",
		      "maxInstances":1,
		      "platformName":"Android",
		      "platform":"Android",
		      "platformVersion":"7.0"
		}
	],
	"configuration": {
		"cleanUpCycle":2000,
		"timeout":30000,
		"proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
		"url":"http://10.10.12.154:5556/wd/hub",
		"host": "10.10.12.154",
		"port": 5556,
		"maxSession": 1,
		"register": true,
		"registerCycle": 5000,
		"hubPort": 80,
		"hubHost": "localhost"
	}
}
```

```bash
appium --nodeconfig nodeconfig.json -a 10.10.12.154 -p 5556
```

### with selenium 3.7.1

```bash
docker run -p 80:4444 selenium/hub:3.7
```

![grid371](https://user-images.githubusercontent.com/1901675/34035755-64601ab4-e183-11e7-9c24-02fe994f3640.png)

![grid371config](https://user-images.githubusercontent.com/1901675/34035892-bf8e7462-e183-11e7-8792-8d38ea7a5e06.png)

### with selenium 3.8.1

```bash
docker run -p 80:4444 selenium/hub:3.8
```
![grid381](https://user-images.githubusercontent.com/1901675/34035760-669dd424-e183-11e7-987a-8b9828207afd.png)

![grid381config](https://user-images.githubusercontent.com/1901675/34035894-c251c05a-e183-11e7-8526-a31432b96a4c.png)

## Link to Appium logs

There is nothing significant in appium and selenium logs.

**Comment by mykola-mokhnach** [comment]
@dpgraham FYI

**Comment by dpgraham** [comment]
I suspect that Selenium 3.8 probably requires Appium to be W3C compliant (https://github.com/jlipps/simple-wd-spec).

We have made changes that make Appium W3C compliant and our upcoming release (1.7.2) will have these. @simbas are you able to test with the latest Appium from master to see if it's still happening on master?

You can run it by cloning the appium repo and then from the Appium path running:

```
rm -rf node_modules
npm install
node .
```

**Comment by simbas** [comment]
Thank you for your fast replies!

I have the same behaviour with master:
<img width="602" alt="master" src="https://user-images.githubusercontent.com/1901675/34068711-9efe07d6-e240-11e7-8b48-4f7e83af2f00.png">

<img width="606" alt="masterconfig" src="https://user-images.githubusercontent.com/1901675/34068712-a33bab78-e240-11e7-8e63-294e3b534387.png">

Master works as expected with selenium 3.7.1.

**Comment by kool79** [comment]
It is bug in selenium v3.8.1
https://github.com/SeleniumHQ/selenium/issues/5163

**Comment by kool79** [comment]
@simbas BTW: in selenium 3.x (unlike to selenium v2.x) the parameters `timeout`, `browserTimeout`  should be in seconds both in command-line AND in json file (at least until v3.8.1).

**Comment by swtestacademy** [comment]
I have same problems :(

**Comment by dpgraham** [comment]
Sounds like a Selenium Grid error. Closing.

**Comment by swtestacademy** [comment]
For 3.8.1 problem exists. I will use 3.7.1 until it will be fixed. Thanks.
