### ISSUE TITLE
Process arguments for Appium iOS is not working as expected

### ISSUE THREAD

**Issue by anusharao008** [appium/appium#9804]
Hi @jlipps, @imurchie ,
I am using Appium v1.7.1
Language: Python
I am trying to pass process arguments which can skip authentication before launching app.
{'appium_port': '4723',
               'appium_host': 'http://0.0.0.0',
               'app_id': 'xxx.xxx.xxx.xxx',
               'app_payload_name': 'xxx.app',
               'should_resign_app':False,
               'app_name': 'xxx',
               'processArguments': {"args": ["-xxxxxx 1"]},
               'dev_id': 'xxxx',
               'driver_directory': os.path.dirname(__file__)}
Using this process arguments I am not able to achieve what ever I want.Am I doing any mistake?. Can anyone please help me with this

**Comment by mykola-mokhnach** [comment]
Here is an example of passing args: https://github.com/appium/appium/issues/9659
I'd create an additional logger in the application under test and check whether the passed arguments are received and handled properly there.
