### ISSUE TITLE
Android Driver error Cannot stop and clear [app_package] Original error: Error executing adbExec. SecurityException

### ISSUE THREAD

**Issue by blackmenthor** [appium/appium#9807]
Hello guys, i'm having a problem using appium on android. so i keep getting the SecurityException whenever i start the appium server with capabilities. It says the error was because i'm not getting the permission to CLEAR_APP_USER_DATA and i have no idea why. maybe appium settings app require that permission but haven't added that yet?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Ubuntu 17.10
* Node.js version (unless using Appium.app|exe): Node v9.2.1
* Mobile platform/version under test: Android 7.1.2
* Real device or emulator/simulator: Xiaomi Redmi Note 5a
* Appium CLI or Appium.app|exe: appium cli

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
https://gist.github.com/blackmenthor/2b34ae87959dcfa1c2e9144a97451f6f

## Code To Reproduce Issue [ Good To Have ]

public class LoginTest {

    static AndroidDriver driver;

    @Before
    public void setUp() throws Exception {
        // set up appium against a local application
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability(CapabilityType.BROWSER_NAME, "");
        capabilities.setCapability("deviceName", "ec8c4df");
        capabilities.setCapability("platformVersion", "7.1.2");
        capabilities.setCapability("platformName", "Android");
        capabilities.setCapability("deviceOrientation", "portrait");
        capabilities.setCapability("appiumVersion", "1.7.1");
        capabilities.setCapability("fullReset", "false");
        capabilities.setCapability("appPackage", "com.sample.test");
        capabilities.setCapability("appActivity", "com.sample.activities.LoginActivity");

        //create a RemoteWebDriver, the default port for Appium is 4723
        driver = new AndroidDriver<>(new URL("http://0.0.0.0:4723/wd/hub"), capabilities);
        System.out.println("MC session was successfully created [Android Device]");
    }

    @Test
    public void clickLoginTest(){
        WebElement login = driver.findElementById("com.sample.test:id/button");
        login.click();
        WebElement username = driver.findElementById("com.sample.test:id/txtUsername");
        System.out.println(username.getText());
    }

    @AfterClass
    public static void tearDown(){
        driver.quit();
    }

}

**Comment by mykola-mokhnach** [comment]
which output do you get if `adb -P 5037 -s ec8c4df shell pm clear com.trimegah.trima.debug` is executed from the command line?

**Comment by blackmenthor** [comment]
The same one as i get from the android studio.

It says, 

Stderr: 'Error: java.lang.SecurityException: PID 22126 does not have permission android.permission.CLEAR_APP_USER_DATA to clear data of package com.trimegah.trima.debug'; Code: '1'

**Comment by mykola-mokhnach** [comment]
then it's rather a problem with your device under test, which does not allow to clear application data from the shell console

**Comment by blackmenthor** [comment]
Hi @renanantunes  ,
Yes i do find the solution to my problem. in my Xiaomi Redmi Note 5a the Install via USB, and USB debugging is disabled so the appium process can't freely access the data needed thus i need to enable it first.

**Comment by renanantunes** [comment]
Thank you @blackmenthor

**Comment by szee45** [comment]
Hi, I am using Oppo f7 and in that phone there is no setting as Install via USB.  I am using vncviewer so USB debugging is always enabled and I am facing the same problem. Any solution?

**Comment by lhx405171358** [comment]
Same problem with oppo R15( Android 8.1), any solution ?

**Comment by blackmenthor** [comment]
@szee45 @lhx405171358 

Hi, maybe the problem is the manufacturer itself didn't allow the user to do this kind of automation on those devices. Maybe you could try to use it with emulator or other device.

Thanks.

**Comment by rashmitparida** [comment]
@blackmenthor 

Hello, Actually i am too facing the same error and having 'Redmi Note 4'. I checked 'Install via USB', and 'USB debugging' are already enabled for me. Still getting this error and unable to figure out. Could you or someone else please help me out here! 

Thanks.

**Comment by liuhui1234561** [comment]
> 与oppo R15（Android 8.1）相同的问题，任何解决方案？

请问你的问题解决了吗？我也遇到了

**Comment by lucas-porto1** [comment]
I have the same problem. Any solution?
