### ISSUE TITLE
Getting error ->[MJSONWP] Encountered internal error running command: Error: We already have a chromedriver instance running

### ISSUE THREAD

**Issue by shubhamj-cuelogic** [appium/appium#9808]
## The problem

I am automating a hybrid app of android in mac OS My script run first correctly.

I have checked and this issue is also replecating in windows also.

But after that it showing error like:

Encountered internal error running command: Error: We already have a chromedriver instance running

I have tried every option suggested like:

replacing new chromedriver file in node_module folder of appium
setting cap as
capabilities.setCapability(“recreateChromeDriverSessions”, true);
But nothing is working for me

Getting Below error:

[MJSONWP] Encountered internal error running command: Error: We already have a chromedriver instance running at AndroidDriver.callee$0$0$ (…/…/…/lib/commands/context.js:104:11) at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40) at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22) at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21) at invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37) at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17) at new Promise () at new F (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36) at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12) at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21) at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12) at AndroidDriver.callee$0$0 [as startChromedriverProxy] (…/…/…/lib/commands/context.js:118:25) at AndroidDriver.callee$0$0$ (…/…/…/lib/commands/context.js:63:16) at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40) at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22) at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21) at invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37) at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17) at new Promise () at new F (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36) at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12) at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21) at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12) at AndroidDriver.callee$0$0 [as switchContext] (…/…/…/lib/commands/context.js:58:45) at AndroidDriver.callee$0$0$ (…/…/…/lib/commands/context.js:54:14) at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40) at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22) at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21) at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37) at.io!

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable): don't know
* Desktop OS/version used to run Appium: MAC OS and window 10 OS
* Node.js version (unless using Appium.app|exe): 6.11.0
* Mobile platform/version under test: Android/IOS both
* Real device or emulator/simulator: Nexus 6 - Real and Nexus 5 emulator
* Appium CLI or Appium.app|exe: I have tried in CLI of both windows and mac os and desktop version of mac

Screenshot:

![chrome_appium](https://user-images.githubusercontent.com/6291660/34094181-1a7f4368-e3f2-11e7-8113-510399acc935.png)

**Comment by mykola-mokhnach** [comment]
Closed as inactive
