### ISSUE TITLE
xcodebuild exited with code '65' and signal 'null'

### ISSUE THREAD

**Issue by pankajpat2014** [appium/appium#9811]
## The problem
I am trying to execute test script on sample test app provided by appium.
I have successfully installed everything which is required.
I am trying to launch the automation script in eclipse and it is giving me the error message as below.

org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial

I went into the Xcode project of WebDriver agent, I have checked everything over there, there are no errors, I have also set proper team id and bundle id and clicked on Product --> Test (for WebDriverRunner) it is successfully able to install the WebDriverAgent into my iPhone.
Now I am again running my automation scripts from eclipse IDE, but still facing the same issue ""xcodebuild failed with code 65"

## Environment
Appium version : 1.7.1
Xcode version : 8.2

## Please find below appium console logs
[Appium] Welcome to Appium v1.7.1
[Appium] Non-default server args:
[Appium]   address: 127.0.0.1
[Appium] Appium REST http interface listener started on 127.0.0.1:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/mobile.testing.test/Desktop/Pankaj/AppiumProjectData/TestApp.app","browserName":"","deviceName":"iPhone","platform":"IOS","platformName":"iOS","platformVersion":"10.1.1","udid":"f85d36bcfaab830b01e1c8070e6f54628afe1234","version":""},"capabilities":{"desiredCapabilities":{"app":"/Users/mobile.testing.test/Desktop/Pankaj/AppiumProjectData/TestApp.app","browserName":"","deviceName":"iPhone","platform":"IOS","platformName":"iOS","platformVersion":"10.1.1","udid":"f85d36bcfaab830b01e1c8070e6f54628afe1234","version":""},"firstMatch":[{"browserName":"","platformName":"ios"}]}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/mobile.testing.test/Desktop/Pankaj/AppiumProjectData/TestApp.app","browserName":"","deviceName":"iPhone","platform":"IOS","platformName":"iOS","platformVersion":"10.1.1","udid":"f85d36bcfaab830b01e1c8070e6f54628afe1234","version":""},null,{"desiredCapabilities":{"app":"/Users/mobile.testing.test/Desktop/Pankaj/AppiumProjectData/TestApp.app","browserName":"","deviceName":"iPhone","platform":"IOS","platformName":"iOS","platformVersion":"10.1.1","udid":"f851234cfa52830b01e1c8070e6f54628afe7624","version":""},"firstMatch":[{"browserName":"","platformName":"ios"}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1513598480259 (17:31:20 GMT+0530 (IST))
[Appium] Requested iOS support with version >= 10, using XCUITest driver instead of UIAutomation-based driver, since the latter is unsupported on iOS 10 and up.
[Appium] Creating new XCUITestDriver (v2.51.1) session
[Appium] Capabilities:
[Appium]   app: '/Users/mobile.testing.test/Desktop/Pankaj/AppiumProjectData/TestApp.app'
[Appium]   browserName: ''
[Appium]   deviceName: 'iPhone'
[Appium]   platform: 'IOS'
[Appium]   platformName: 'iOS'
[Appium]   platformVersion: '10.1.1'
[Appium]   udid: 'f85d36bcfaab830b01e1c8070e6f54628afe1234'
[Appium]   version: ''
[BaseDriver] The following capabilities were provided, but are not recognized by appium: platform, version.
[BaseDriver] Session created with session id: b93a73f0-e672-4375-8636-287c94222b5c
[debug] [XCUITest] Xcode version set to '8.2.1' (tools v8.2.0.0.1.1480973914)
[debug] [XCUITest] iOS SDK Version set to '10.2'
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1513598481144 (17:31:21 GMT+0530 (IST))
[debug] [XCUITest] Available devices: f85d36bcfaab830b01e1c8070e6f54628afe1234
[debug] [XCUITest] Creating iDevice object with udid 'f85d36bcfaab830b01e1c8070e6f54628afe1234'
[XCUITest] Determining device to run tests on: udid: 'f85d36bcfaab830b01e1c8070e6f54628afe1234', real device: true
[BaseDriver] Using local app '/Users/mobile.testing.test/Desktop/Pankaj/AppiumProjectData/TestApp.app'
[debug] [BaseDriver] Event 'appConfigured' logged at 1513598481721 (17:31:21 GMT+0530 (IST))
[debug] [XCUITest] Checking whether app '/Users/mobile.testing.test/Desktop/Pankaj/AppiumProjectData/TestApp.app' is actually present on file system
[debug] [XCUITest] App is present
[debug] [iOS] Getting bundle ID from app '/Users/mobile.testing.test/Desktop/Pankaj/AppiumProjectData/TestApp.app': 'io.appium.TestAppspankaj'
[debug] [BaseDriver] Event 'resetStarted' logged at 1513598481747 (17:31:21 GMT+0530 (IST))
[debug] [XCUITest] Reset: running ios real device reset flow
[debug] [BaseDriver] Event 'resetComplete' logged at 1513598481749 (17:31:21 GMT+0530 (IST))
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Starting iOS device log capture with: 'idevicesyslog'
[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1513598481933 (17:31:21 GMT+0530 (IST))
[XCUITest] Setting up real device
[debug] [XCUITest] Reset requested. Removing app with id 'io.appium.TestAppspankaj' from the device
[debug] [XCUITest] Installing '/Users/mobile.testing.test/Desktop/Pankaj/AppiumProjectData/TestApp.app' on device with UUID 'f85d36bcfaab830b01e1c8070e6f54628afe1234'...
[debug] [XCUITest] The app has been installed successfully.
[debug] [BaseDriver] Event 'appInstalled' logged at 1513598483160 (17:31:23 GMT+0530 (IST))
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[debug] [XCUITest] Capability 'useNewWDA' set to false, so trying to reuse currently running WDA instance at 'http://localhost:8100/'
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [XCUITest] WDA is not listening at 'http://localhost:8100/'. Rebuilding...
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1513598483203 (17:31:23 GMT+0530 (IST))
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'
[debug] [XCUITest] Killing running processes 'xcodebuild.*f85d36bcfaab830b01e1c8070e6f54628afe1234, iproxy 8100' for the device f85d36bcfaab830b01e1c8070e6f54628afe1234...
[debug] [XCUITest] 'pgrep -nif xcodebuild.*f85d36bcfaab830b01e1c8070e6f54628afe1234' didn't detect any matching processes. Return code: 1
[debug] [XCUITest] 'pgrep -nif iproxy 8100' didn't detect any matching processes. Return code: 1
[debug] [XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[debug] [XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=f85d36bcfaab830b01e1c8070e6f54628afe1234 IPHONEOS_DEPLOYMENT_TARGET=10.1' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[debug] [XCUITest] Output from xcodebuild will not be logged. To see xcode logging, use 'showXcodeLog' desired capability
[debug] [XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [XCUITest] Log file for xcodebuild test: /Users/mobile.testing.test/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/DC2854F4-C3E8-4168-9E21-FD25E93963E8/Session-WebDriverAgentRunner-2017-12-18_173136-bDDhh9.log
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[Xcode] 2017-12-18 17:31:45.789 xcodebuild[6415:73640] Error Domain=com.apple.platform.iphoneos Code=-12 "Unable to launch com.apple.test.WebDriverAgentRunner-Runner" UserInfo={NSLocalizedDescription=Unable to launch com.apple.test.WebDriverAgentRunner-Runner, NSUnderlyingError=0x7ff2566da290 {Error Domain=DTXMessage Code=1 "(null)" UserInfo={DTXExceptionKey=The operation couldn’t be completed. Unable to launch com.apple.test.WebDriverAgentRunner-Runner because it has an invalid code signature, inadequate entitlements or its profile has not been explicitly trusted by the user. : Failed to launch process with bundle identifier 'com.apple.test.WebDriverAgentRunner-Runner'}}}
[Xcode] 2017-12-18 17:31:45.789 xcodebuild[6415:73640] Error Domain=IDETestOperationsObserverErrorDomain Code=5 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
[Xcode] 
[Xcode] ** TEST EXECUTE FAILED **
[Xcode] 
[Xcode] 
[XCUITest] xcodebuild exited with code '65' and signal 'null'
[debug] [BaseDriver] Event 'wdaStartFailed' logged at 1513598505811 (17:31:45 GMT+0530 (IST))
[debug] [XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
[debug] [XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down iproxy process (pid 6414)
[debug] [XCUITest] iproxy exited with code 'null'
[debug] [XCUITest] Removing WDA application from device
[XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:381:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
 Error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:381:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[debug] [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:381:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session 500 35310 ms - 470 

Please suggest, how to resolve this issue

**Comment by mykola-mokhnach** [comment]
Do you follow https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md ? Have you verified that WDA source is signed properly?

**Comment by imurchie** [comment]
It is probably not explicitly trusting the developers on the device. https://support.apple.com/en-us/HT204460

**Comment by pankajpat2014** [comment]
@mykola-mokhnach I have visited the link you have mentioned.
Followed all the steps in there, everything seems to be good, but when I execute below command on terminal it is giving me an error message

xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=<udid>' test

Error I am getting as below : 
Check dependencies

=== BUILD TARGET WebDriverAgentRunner OF PROJECT WebDriverAgent WITH CONFIGURATION Debug ===

Check dependencies

writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/hx/xs_809hx7ls6mmg503swnn9h0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/0e8dc5396104e8c0fda593c7c2a7c96f/f85d353cfa52830b01e1c8070e6f54628afe7624/ManifestCache.plist
2017-12-19 15:17:00.353 xcodebuild[1059:27763] Error Domain=com.apple.platform.iphoneos Code=-12 "Unable to launch com.apple.test.WebDriverAgentRunner-Runner" UserInfo={NSLocalizedDescription=Unable to launch com.apple.test.WebDriverAgentRunner-Runner, NSUnderlyingError=0x7fa1b42e2af0 {Error Domain=DTXMessage Code=1 "(null)" UserInfo={DTXExceptionKey=The operation couldn’t be completed. Unable to launch com.apple.test.WebDriverAgentRunner-Runner because it has an invalid code signature, inadequate entitlements or its profile has not been explicitly trusted by the user. : Failed to launch process with bundle identifier 'com.apple.test.WebDriverAgentRunner-Runner'}}}
2017-12-19 15:17:00.353 xcodebuild[1059:27763] Error Domain=IDETestOperationsObserverErrorDomain Code=5 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}

Testing failed:
	Test target WebDriverAgentRunner encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted)
** TEST FAILED **

However, I can't see any error coming in my WebDriverAgent Xcode project, everything seems to be fine over there.

Also, with the above command execution, webDriverAgent got installed in my iPhone.

**Comment by pankajpat2014** [comment]
@imurchie , I have already explicitly trusted the WebDriverAgent application in my iPhone
Whenever I am running my automation script, the already installed WebDriverAgent gets removed from the iPhone and still giving the sam error "xcodebuild exited with code '65' and signal 'null"

**Comment by mykola-mokhnach** [comment]
>  I have already explicitly trusted the WebDriverAgent application in my iPhone

You must use development signature for WDA, which does not require to be trusted if the device id is added to the profile. Enterprise signature won't work.

**Comment by pankajpat2014** [comment]
@mykola-mokhnach How to add device id to profile ? 
Please suggest

**Comment by saikrishna321** [comment]
Closing as User-Side issue. @pankajpat2014 if your still facing issue. Please raise in discuss.appium.io

**Comment by ifti1234** [comment]
@saikrishna321 @mykola-mokhnach 
Hi guys.. 
I m also facing the same issue as I cannot launch the webDriverAgent on device 
Everytime it closes after launching and while running the test cases I am facing "xcode failed with code 65" error 
please help me out to solve this issue 
Thanks

**Comment by haseebzagir** [comment]
My solution was to navigate to the WebDriveragent.xcodeproj which is in the path your_username/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent and update the project to the recommended settings.
