### ISSUE TITLE
Appium stops during test execution.

### ISSUE THREAD

**Issue by HPramesh** [appium/appium#9812]
## The problem
Hi,

Am running my scripts on Windows 7 machine with Appium V 1.7.1 on multiple devices sequentially, during my test runs after some test cases execution, execution stops while executing on Moto G device with Android version 5.1. Test scripts do not fail but stop as if waiting for some command.

Could someone please check this and update,

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: Windows 7 with Service Pack 1
* Node.js version (unless using Appium.app|exe): v6.9.4
* Mobile platform/version under test: Moto G/Android 5.1v
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: NA

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
https://gist.github.com/HPramesh/090cf7c9964aac4555af95e8683a5062.js

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
The attached log is impossible to read. Usually such freezes mean that adb server stopped responding  to external commands due to high load and/or internal phone issues.
