### ISSUE TITLE
Appium just opening and closing the app

### ISSUE THREAD

**Issue by Arthuxr** [appium/appium#9814]
## The problem

While trying to launch my app from Script the webdriver app is opening, then my app is opening for a moment and then closing, but I can launch and navigate my app muanually.

## Environment

* Appium version (or git revision) that exhibits the issue: v1.7.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac Os Sierra
* Node.js version (unless using Appium.app|exe): v9.3.0
* Mobile platform/version under test:  IOS 11.2
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: Appium.app

## Details

If I launch my app manually everything works perfectly....

## Link to Appium logs

https://gist.github.com/Arthuxr/df0d6c2e17d9e7dfbe46afe822a1202c

## Code To Reproduce Issue [ Good To Have ]

        caps.setCapability(“platformName”, “iOS”);
        caps.setCapability(“platformVersion”, “11.2");
        caps.setCapability(“deviceName”, “iPhone 6s”);
        caps.setCapability(“app”, “/Users/arturosanchez/Downloads/Perumin.app”); 
        caps.setCapability(“showXcodeLog”, “true”);
        caps.setCapability(“clearSystemFiles”, “true”);
        caps.setCapability(“launchTimeout”, “30000");
        driver = new IOSDriver(new URL(“http://0.0.0.0:4723/wd/hub”), caps);

**Comment by Arthuxr** [comment]
@mykola-mokhnach  hi any suggestions please?

**Comment by mykola-mokhnach** [comment]
Attach the device log. I think it might be a problem in XCTest itself.

**Comment by Arthuxr** [comment]
thanks, how do i get the device log??

**Comment by Arthuxr** [comment]
Im facing exactly the same issue please respond #8161

**Comment by Kitty2014** [comment]
with iOS11 same issue met

**Comment by mykola-mokhnach** [comment]
Try to enable the `showIOSLog` capability, which includes device logs into server logs to see what is really happening there.
