### ISSUE TITLE
Am unable to launch an activity from appium

### ISSUE THREAD

**Issue by amitvinutha** [appium/appium#9817]
Hi, I am using android studio 3.0.1, but am unable to launch the activity from the appium, it just displays hello world...
I am writing my test script with JunitLaunch Test() with the desired capabilities and package name what is prescribed in the environment set up, I am having a doubt as we are not suppose to change anything in the manifest file or do we need to add it in the manifest file...
## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

it is displaying just "Hello world"

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Please use Appium forum to ask questions.
