### ISSUE TITLE
Appium failed to create new session

### ISSUE THREAD

**Issue by clark-zhao-hs** [appium/appium#9818]
## The problem

Appium failed to create new session after 1.7.2@beta3 with desired caps working on 1.7.2@beta2

## Environment
* Appium version (or git revision) that exhibits the issue:
v1.7.2@beta3
* Last Appium version that did not exhibit the issue (if applicable):
v1.7.2@beta2
* Desktop OS/version used to run Appium:
Mac os sierra
* Node.js version (unless using Appium.app|exe):
6.10.1
* iPhone 6
* simulator:
* Appium.app|exe:

## Details

Appium failed to create session per start. 
If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/clark-zhao-hs/700b413794104c378671609a3bacc261

**Comment by KazuCocoa** [comment]
What client do you use?
We chatted a bit about the issue today for Java client.

related commit: a8911ba51c7f471014d0a81d7c1f1ee96af4342c

**Comment by clark-zhao-hs** [comment]
thanks, python.

**Comment by KazuCocoa** [comment]
Ah, thank for your quick response.
And also, could you put the webdriver's version here to investigate it? @clark-zhao-hs

**Comment by mykola-mokhnach** [comment]
@clark-zhao-hs Please fill out the issue reporting form and attach the full server log.

**Comment by clark-zhao-hs** [comment]
Updated server log.

**Comment by mykola-mokhnach** [comment]
Can you try to update selenium module to the last available version (`pip install --upgrade selenium`)?

**Comment by igalep** [comment]
Same issue as well
I've tried to execute new session with **Appium 1.7.2-beta4** , Running on Android , but getting the same error

**Comment by KazuCocoa** [comment]
📝 
Merge W3C caps into JSONWP desiredCapabilities #9824

**Comment by mykola-mokhnach** [comment]
@clark-zhao-hs all the necessary changes have been merged recently. Can you please try now?

**Comment by clark-zhao-hs** [comment]
Ran the latest 1.7.2 and issue can't be reproduced. Thanks.
