### ISSUE TITLE
Error occurs after Set<String> contextNames = driver.getContextHandles();  [MJSONWP] Encountered internal error running command: Error: Could not connect to a valid app after 20 tries.

### ISSUE THREAD

**Issue by TestimonyNL** [appium/appium#9823]
## The problem
I am trying to automate a hybrid app with Appium 1.7.1 and Java, iOS simulator.So far I was able to launch the app and remove the notifications pop up but when trying to get the contexts an error is thrown and web view is not selected.

## Environment
* Appium version 1.7.1 that exhibits the issue:
* Desktop OS/version used to run Appium:Mac OSX
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS 10.3
* Real device or emulator/simulator:Simulator
* Appium CLI or Appium.app|exe:Appium desktop

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/TestimonyNL/4916f7fefd855ca6d81d26c5b3dc23fb

## Code To Reproduce Issue [ Good To Have ]

package XYZ;

import io.appium.java_client.AppiumDriver;
import io.appium.java_client.MobileElement;
import io.appium.java_client.ios.IOSDriver;
import io.appium.java_client.remote.MobileCapabilityType;
import jdk.internal.instrumentation.Logger;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.remote.DesiredCapabilities;
import java.net.URL;
import java.util.Set;

/**
 * Created by on 28/11/2017.
 */
public class AppSimulatorLaunch {

    public AppiumDriver<MobileElement> driver;

    @Before
    public void setup() throws Exception {
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "iPad Air 2");
        capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "iOS");
        capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "10.3");
        capabilities.setCapability("nativeWebTap", true);
        capabilities.setCapability("automationName", "XCUITest");
        capabilities.setCapability("xcodeOrgId", "xyz");
        capabilities.setCapability("xcodeSigningId", "iPhone Developer");
        capabilities.setCapability("newCommandTimeout", "120");
        capabilities.setCapability(MobileCapabilityType.APP, "/Users/adibenarieh/Documents/xyz.app");

        driver = new IOSDriver<>(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);

        driver.switchTo().alert().accept();

    }

    @After
    public void tearDown() {

      // driver.quit();
    }

    @Test
    public void testCheckWebsite() throws InterruptedException {
        Thread.sleep(5000);
        Set<String> contextNames = driver.getContextHandles();
        System.out.println("about to print the context list");
        System.out.println(contextNames);
       
         driver.context((String) contextNames.toArray()[1]);

        driver.findElement(By.xpath("//*[@id=\"USER\"]")).sendKeys("t334658");
        driver.findElement(By.xpath("//*[@id=\"PASSWORD\"]")).sendKeys("geenidee01");
        driver.findElement(By.xpath("//*[@id=\"bouton1\"]")).click();

    }

}

**Comment by mykola-mokhnach** [comment]
Which controller is used to display the webview? does it have debugging option enabled?

**Comment by TestimonyNL** [comment]
Hi mykola, 
If I understand correctly, then safari view controller or do you mean something else?
How can I check if it has debugging option enabled?

Thanks

**Comment by mykola-mokhnach** [comment]
Unfortunately Safari view controller is not supported by Appium.

**Comment by TestimonyNL** [comment]
Seems to work, the problem apparently was running the script with Xcode 8.3 and Appium 1.7.1.
With Xcode 9 it seems to work.
Do you mean its not supported formally or its not suppose to work at all @mykola-mokhnach mykola-mokhnach

**Comment by mykola-mokhnach** [comment]
I meant https://github.com/appium/appium/blob/764bdd61fd0ea3d0373e12168e2a7ee39a7afac1/docs/en/writing-running-appium/web/hybrid.md

> To interact with a web view Appium establishes a connection using a custom remote debugger. When executing against a simulator this connection is established directly as the simulator and the Appium server are on the same machine. Appium can automate WkWebView and UIWebView elements. Unfortunately, it is not currently able to handle SafariViewController elements.
