### ISSUE TITLE
Unable to start ios_webkit_debug_proxy on simulator on port 27753

### ISSUE THREAD

**Issue by SophieDePaula** [appium/appium#9825]
Hi,

I hope this is the right place to ask this.
I was wondering how to start ios_webkit_debug_proxy on a simulator with port 27753.
I was successful starting the webkit with it's default port and on a real device with 27753 port, but not a simulator with 27753 port.

This is the Error I am getting:
ss.add_server_fd(3)
Listing devices on :27753
ss.add_fd(4)
Unable to bind SIMULATOR on port 27753-27753
ss.recv fd=4 len=294

Thanks!
## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS 10.12.6
* Node.js version (unless using Appium.app|exe):9.2.0
* Mobile platform/version under test: IOS simulator version 11.2 (iPhone 7)
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: CLI

**Comment by mykola-mokhnach** [comment]
ios_webkit_debug_proxy is only needed to interact with webviews on real devices. For Simulators it should not be provided.
