### ISSUE TITLE
Appium Inspector is not opening for real device

### ISSUE THREAD

**Issue by amitwagle** [appium/appium#9826]
# Details #
When I try to open application from appium inspector it is giving following message

An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.

Appium logs
[Appiumlogs.txt](https://github.com/appium/appium/files/1574048/Appiumlogs.txt)

I had followed the below instruction and aware of it
https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md

Strangely I am able to run the automation script on iPAD with same capabilities however it's is running quite slow.
[Appiumlog_IntelliJ.txt](https://github.com/appium/appium/files/1574049/Appiumlog_IntelliJ.txt)

Also I am able to open inspector with Simulator properly and able to execute scripts properly on simulator.

# Environment #

Appium version : 1.7.1
XCode : 9.2 
iPAD OS : 11.2.1
Mac OS : 10.13.1 (Mac OS High Sierra)
Node version : v9.3.0
Appium Desktop : 1.2.7

**Comment by mykola-mokhnach** [comment]
There are compilation errors is the log:

> [Xcode] error: Could not read profile /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/OptimizationProfiles/WebDriverAgent.profdata: No such file or directory

The issue must be related to Appium Desktop - perhaps there were some installation issues. Try to reinstall the app and then make sure you can build and deploy `/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/` manually from Xcode

**Comment by amitwagle** [comment]
Thanks for the reply. I will re-install Appium Desktop and will try to build and deploy app and webdriver.

**Comment by amitwagle** [comment]
After reinstalling Appium Desktop and Appium 1.7.1 , I could resolve the issue. Thanks a lot.
