### ISSUE TITLE
pushFile Api not working on ios real device

### ISSUE THREAD

**Issue by UtsavSaha** [appium/appium#9827]
## The problem

driver.pushFile api fails in ios real device with error 

> Unsupported: cannot write files to physical device

## Environment

* Appium version : 1.7.1. 
* OS : MacOS High Sierra 10.13.1 
* Node.js version : v8.6.0
* Mobile platform/version under test: iphone 5s . iOS : 11.1
* **Real device**
* Appium desktop version : 1.2.6

## Link to Appium logs

Appium logs can be found [here](https://gist.github.com/UtsavSaha/20e11b407651dfc31e50c21d4212e8ba)

Client logs marks the error as following : 
 _**Error: [pushFile("","cGVyY2VwdGl2ZTovL3BjcCNjYXB0dXJlL2ltYWdlc2V0cy9FaWdodCxRcXFkciw1MjI3NjM1Nz91c2VyPWEmcGFzc3dvcmQ9YUAxJmxhdW5jaHNjcmVlbj1jYW1lcmFyb2xsJndlYmFwcHVybD1odHRwczovLzE3Mi4yNi45MC43OTo4NDQzL1BDRTY5MiZiYWNrdXJsPWh0dHA6Ly93d3cuZ29vZ2xlLmNvbSZrZWVwc2Vzc2lvbj10cnVl")] Error response status: 13, UnknownError - An unknown server-side error occurred while processing the command. Selenium error: Method has not yet been implemented**_

## Code To Reproduce Issue [ Good To Have ]

javascript webdriver is being used to connect to the appium server.

`driver = wd.promiseChainRemote(serverConfig); driver.init(desired).backgroundApp(0).pushFile(devicePath,data);
`

**Comment by mykola-mokhnach** [comment]
This is by design. You could try the stuff on 1.7.2-beta, where this stuff has been implemented, however you need to make sure that your server environment is ready for real device file transfer. Check https://github.com/appium/appium-xcuitest-driver/pull/574 for more details.

**Comment by UtsavSaha** [comment]
@mykola-mokhnach that's weird.

The [changelog](https://github.com/appium/appium/blob/master/CHANGELOG.md) suggests this was present [ CHANGES IN VERSION 1.2.1 (from 1.2.0)]. 

>  implement pushFile for ios

Also the API page speaks of this as a capability.
Is this removed in recent times?

**Comment by mykola-mokhnach** [comment]
It's correct. The API was only implemented for Simulator at that time.
