### ISSUE TITLE
Hybrid app - can't detect webviews 

### ISSUE THREAD

**Issue by SergiyBeno** [appium/appium#9828]
Hello guys.
Currently I am writing automated tests for an app where some screens are embedded web views. While I was working with Xcode 8.3.3 / iOS SDK 10.0 everything was ok - I had ability to detect web view and interact with it using different locator strategies and queries. 
Recently I jumped to the Xcode 9 / iOS SDK 11.0 and now I can't detect/parse elements on web views. 
Even when I add simulators with lower platform version (for example 10.3) it still doesn't help:
- Xcode 8.3.3 / iPhone 7 / iOS 10.3 - everything is ok
- Xcode 9.1 & 9.2 /  iPhone 7 / iOS 10.3 - can't access web views

Also tried arc (appium ruby console) - but result is the same.
Just for the reference I attached screenshots of Appium's inspector for both cases (Xcode 8.3.3 and 9.1) - you might find them below.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.2.7 (1.7.1)
* Last Appium version that did not exhibit the issue (if applicable): -
* Desktop OS/version used to run Appium: macOS Sierra 10.12.6
* Node.js version (unless using Appium.app|exe): v9.3.0
* Mobile platform/version under test: iOS 11.X
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: both

## Details

Screenshot for Xcode 8.3.3
https://www.dropbox.com/s/ergjeyl49m0ofjv/xCode8.3.3.png?dl=0

Screenshot for Xcode 9.1
https://www.dropbox.com/s/7h77d1hlxl1by6g/XCODE9.1.png?dl=0

## Link to Appium logs
https://gist.github.com/SergiyBeno/3c31c08081c56752fda6138b96a180e2

**Comment by mykola-mokhnach** [comment]
You must switch to webview, otherwise the content won't be visible. This is known XCTest limitation since Xcode9

**Comment by mykola-mokhnach** [comment]
Good news - we've found a workaround for this issue. It will be available in Appium beta since https://github.com/appium/WebDriverAgent/pull/31 is merged and deployed

**Comment by SergiyBeno** [comment]
Wohoo! That's awesome! Thank you for notification - highly appreciated 🙇
