### ISSUE TITLE
WDA/iProxy don't respond: Connection to WDA timed out / recv failed: Operation not permitted

### ISSUE THREAD

**Issue by felyppers** [appium/appium#9830]
## The problem

WDA not able to connect to device (iOS 11.1). Using the same app and capabilities, other devices (ios 9.3 until 10.3.3) are able to connect. All info I could collect if down below, but please let me know if anything else is necessary.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2-beta2
* Desktop OS/version used to run Appium: MacOS Sierra 10.12.16
* Node.js version (unless using Appium.app|exe): 7.4.0
* Mobile platform/version under test: iPad Mini 2 - iOS 11.1 (Xcode 9.2)
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium Ruby Lib

## Details

Starting tests on an iPad Mini 2 (iOS 11.1) results in WDA not being able to connect to the device. All other devices in our farm (all between iOS 9.3 and 10.3.3) connect without a problem. Basically the WDA opens, the application is launched, but in the log we can already see the connection issue. If we try to call any WDA method, the app gets closed.

## Link to Appium logs

[Appium Log](https://gist.github.com/felyppers/e9d4ffab01a816722c9b2cfe09e49ae3): Until row 148 no method was called, I just started the appium driver. The application launched correctly. Beyond this point, I called findElements, resulting in the application being closed.

[XCodeBuild Log](https://gist.github.com/felyppers/d6775ae1de77175b34e49c42ff5f6700): Log generated by xcodebuild after the issue.

## Additional Info

- Just after the application launch, if I call findElements while the native Apple Notification Alert is visible in the screen, WDA works ok. After accepting the alert, if I try to call findElements again, the app gets closed as always.

- If after the app being closed, I try to restart the appium driver, it gets trapped in the routine of trying to reconnect and never succeed.

**Comment by mykola-mokhnach** [comment]
This error means that WebDriverAgents stops responding to requests proxied by Appium. Attach the device log to see more details.

**Comment by felyppers** [comment]
@mykola-mokhnach here follows the [device log](https://gist.github.com/felyppers/8f811eef21a3f36f55a578157bcfe00b)

**Comment by mykola-mokhnach** [comment]
> 2017-12-20 15:55:21.448651-0200 WebDriverAgentRunner-Runner[448:26204] Running tests...
> 2017-12-20 15:55:22.117620-0200 WebDriverAgentRunner-Runner[448:26204] refreshPreferences: HangTracerEnabled: 0
> 2017-12-20 15:55:22.117752-0200 WebDriverAgentRunner-Runner[448:26204] refreshPreferences: HangTracerDuration: 500
> 2017-12-20 15:55:22.117799-0200 WebDriverAgentRunner-Runner[448:26204] refreshPreferences: ActivationLoggingEnabled: 0 ActivationLoggingTaskedOffByDA:0
> 2017-12-20 15:55:24.158631-0200 WebDriverAgentRunner-Runner[448:26204] [AXValidations] UIAccessibility Error adding -[PHAsset accessibilityLabel]
> 2017-12-20 15:55:24.158841-0200 WebDriverAgentRunner-Runner[448:26204] [AXValidations] UIAccessibility Error adding -[PHAsset accessibilityValue]
> 2017-12-20 15:55:24.158933-0200 WebDriverAgentRunner-Runner[448:26204] [AXValidations] UIAccessibility Error adding -[PHAsset accessibilityTraits]
> 2017-12-20 15:55:24.159021-0200 WebDriverAgentRunner-Runner[448:26204] [AXValidations] UIAccessibility Error adding -[PHAsset _accessibilitySavePhotoLabel:]
> 2017-12-20 15:55:24.159144-0200 WebDriverAgentRunner-Runner[448:26204] [AXValidations] UIAccessibility Error adding +[PHAsset safeCategoryBaseClass]
> 2017-12-20 15:55:24.320781-0200 WebDriverAgentRunner-Runner[448:26204] Continuing to run tests in the background with task ID 1
> 
> Restarting after unexpected exit or crash in UITestingUITests/testRunner; summary will include totals from previous launches.

I don't see anything useful in the attached device log, but the xcodebuild log says that WDA unexpectedly crashes. There is anyway nothing we can do about that in Appium. Try to look for answers on Apple or WebDriverAgent forums.

**Comment by felyppers** [comment]
Ok, I will give it a try.

**Comment by deepikashekar37** [comment]
I am  facing same issue.

Environment
Appium - 1.8.1
xcode - 9.4
real iOS device version - 11.4

**Appium logs **

Responding to client with driver.getContexts() result: ["NATIVE_APP","WEBVIEW_1"]
[HTTP] <-- GET /wd/hub/session/eee59416-4df8-4cd9-8986-41571c960409/contexts 200 9 ms - 36
[HTTP]
[HTTP] --> POST /wd/hub/session/eee59416-4df8-4cd9-8986-41571c960409/context
[HTTP] {"name":"WEBVIEW_1"}
[debug] [W3C] Calling AppiumDriver.setContext() with args: ["WEBVIEW_1","eee59416-4df8-4cd9-8986-41571c960409"]
[debug] [XCUITest] Executing command 'setContext'
[debug] [iOS] Attempting to set context to 'WEBVIEW_1'
[debug] [RemoteDebugger] WebKit debugger web socket connected to url: ws://localhost:27753/devtools/page/1
[debug] [RemoteDebugger] Starting to listen for JavaScript console
[debug] [RemoteDebugger] Sending WebKit data: {"method":"Console.enable","params":{"objectGroup":"console","includeCommandLineAPI":true,"doNotPauseOnExceptionsAndMuteConsole":true}}
[debug] [RemoteDebugger] Webkit response timeout: 50000
[debug] [RemoteDebugger] Receiving WebKit data: '{"result":{},"id":1}'
[debug] [RemoteDebugger] Found handler for message '1'
[debug] [RemoteDebugger] WebKit debugger got a message for 'Console.enable' and have no handler, doing nothing.
[debug] [XCUITest] Connection to WDA timed out
[debug] [iProxy] recv failed: Operation not permitted
[W3C] Encountered internal error running command: TimeoutError: operation timed out
[W3C] at afterTimeout (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/release/timers.js:46:19)
[W3C] at Timeout.timeoutTimeout [as _onTimeout] (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/release/timers.js:76:13)
[W3C] at ontimeout (timers.js:466:11)
[W3C] at tryOnTimeout (timers.js:304:5)
[W3C] at Timer.listOnTimeout (timers.js:267:5)

Can anyone please help on this ?
