### ISSUE TITLE
select_picker_wheel Crash - iOS 11

### ISSUE THREAD

**Issue by Mcfli** [appium/appium#9832]
## The problem

When a country picker is shown on screen, clicking any button (Done, Cancel, Confirm) will crash the app if you click it via a command.  Clicking it manually does not crash the app, but any command on a device on iOS 11 + 11.1 will crash it.  Worked fine on iOS 10.3.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: OS X 10.12.6
* Node.js version (unless using Appium.app|exe): 7.10.0
* Mobile platform/version under test: iOS 11, 11.1, 10.3
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: Appium CLI

## Details

I'm not 100% sure if this is an Apple or an Appium issue, but it used to work fine pre-iOS 11.

## Link to Appium logs

[Appium Log](https://gist.github.com/Mcfli/e0d0c41040a467ff6597b0775b003971)
[iOS Crash Log](https://gist.github.com/Mcfli/87a176c907c6cb4fded1924eee3fe66d)

## Code To Reproduce Issue

Ran this during appium ruby console (arc):
`wheel = find_element(:class, 'XCUIElementTypePickerWheel')`
  `select_picker_wheel(element:wheel, order:'next', offset:0.15)`
   `id('Confirm').click`

**Comment by mykola-mokhnach** [comment]
This issue has nothing to do with Appium. I'd try to report it to https://github.com/facebook/WebDriverAgent/issues, but the stack trace shows, that the crash anyway happens somewhere inside XCTest internals.
