### ISSUE TITLE
Drag and drop is not working in webview of hybrid app

### ISSUE THREAD

**Issue by anjanabendre** [appium/appium#9836]
## The problem
We have hybrid app, developed using ionic cordova platform. Most of the pages are in webview and tap/touch and drag and drop is required for all elements. Now its not working.
So our automation for this application is completely on hold.
Appreciate quick fix on these issues especially 'Drag and Drop'.

Thanks,
 Anjana Bendre

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: Windows-7 (64 bit)
* Node.js version (unless using Appium.app|exe): Node v6.11.4
* Mobile platform/version under test: Android 6.0.1, 6.2
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:  Both

## Details

If necessary, describe the problem you have been experiencing in more detail.
Drag and drop is not working. We have written code as below:
It is able to find the elements, location etc...but nothing happens at drag and drop. This code works fine on native app.

I am using Touch action with LonPress, Wait and MoveTo.  
It doesn't do anything after 10 minutes, script finishes with error' Encountered internal error running command: Error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: Error: ESOCKETTIMEDOU' . 

Sc
[appium_log_dragNdrop.txt](https://github.com/appium/appium/files/1579358/appium_log_dragNdrop.txt)
reenshot is not taken,

drag_and_drop(self, source_locator, target_locator):
        """ Drag and drop source element to target elemement"""
        self._info("Dragging element (%s, %s)" % (source_locator, target_locator))
        driver = self._current_application()
        el1 = self._element_find(source_locator, True, True)
        el2 = self._element_find(target_locator, True, True)
        # dnd is stimulated by longpress-move_to-release
        action = TouchAction(driver)
        action.long_press(el1).wait(2000).move_to(el2).release().perform()

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
drag and drop is only available in native context. Also, one can set `nativeWebScreenshot` capability to `true` in order to workaround screenshoting issue.
