### ISSUE TITLE
Can not set 16 digit number using send-keys 

### ISSUE THREAD

**Issue by kirishmani** [appium/appium#9839]
## The problem

Check with Android real device and Emulator device.
Send keys does not work correctly when i send value is : 3434 5677 5556 6757 but instead of send like this 3443 5677 5556 6757.
I facing problem list down below:
1.One number type twice at time
2.Enter less input value compare with what i set input value
3.Enter more input value compare with what i gave input value

## Environment
Appium 1.7.1
Selenium with java
Hybrid framework

**Comment by mykola-mokhnach** [comment]
Please provide full server log

**Comment by kirishmani** [comment]
Hi



I had solved that above mention problem.



Thanks
Manikandan
