### ISSUE TITLE
iOS and Android native build in apps Automation

### ISSUE THREAD

**Issue by Gnanaraj-S** [appium/appium#9840]
I am currently automating mobile app on iOS and Android. Here is some insights on my iOS/android app 

Once installed the app in the mobile device, I goes to Photos(iOS and Android built in native app), selects a photo, clicks on Print(Air Print in terms of iOS), chooses the printer(The app will act as a printer, internal functionality of the app) and clicks on Print.

The same steps I will be testing out from Gmail, Notes, any documents from the mobile ...
I'm not able to interact with Photos but I can with Settings. I feel like this feature is not existing so far. If so, it would be great if we can get this feature added for iOS and Android.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: iOS
* Node.js version (unless using Appium.app|exe): using Appium APP
* Mobile platform/version under test: iOS 11.2 & Oreo
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium.app

**Comment by mykola-mokhnach** [comment]
For iOS there is some stuff available in appium@beta since Xcode9: https://github.com/mykola-mokhnach/appium/blob/cc5dd06829c5972cd7fbd62584c16f77583c7a73/docs/en/writing-running-appium/ios/ios-xctest-mobile-apps-management.md

Not sure about Android though.

**Comment by KazuCocoa** [comment]
Android also can connect to an installed apps and manage it.
The key is whether set `app` in desired capability. Without the `app` and with `appActivity` and `appWaitActivity`, Appium can launch the app and manage it.

For example, the following is an example to manage installed app.
https://github.com/appium/python-client/issues/184#issuecomment-335008549

----

Also, the install app method also works for Android.

http://www.rubydoc.info/github/appium/ruby_lib_core/Appium/Core/Device#install_app-instance_method

**Comment by Gnanaraj-S** [comment]
Thanks for looking into this.

I'm currently experimenting on iOS 10.3.3  iPhone 5s.

When I set the desired capabilities like,

  "deviceName": "iPhone 5S",
  "platformName": "iOS",
  "platformVersion": "10.3.3",
  **"app": "Settings",**
  "automationName": "XCUITest",
  "udid": <Valid UDID>

I can able to get the Settings in built app up and running and I can able to interact with it.

But my requirement is to deal with Photos, So I went ahead and changed the above desired capability. I replaced the app to Photos,

  "deviceName": "iPhone 5S",
  "platformName": "iOS",
  "platformVersion": "10.3.3",
  **"app": "Photos",**
  "automationName": "XCUITest",
  "udid": <Valid UDID>

It just threw me 

 Encountered internal error running command: Error: Bad app: Photos. App paths need to be absolute, or relative to the appium server install dir, or a URL to compressed file, or a special app name.


Please let me know whether Appium has the capability for automating the in build apps like Photos, Notes, Mail in iOS

**Comment by KazuCocoa** [comment]
What about using `bundleId` instead of `app` as mentioned https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/caps.md#ios-only ?

**Comment by Gnanaraj-S** [comment]
That works like a Charm! Thank you so much!!

For those who face the same issue, use the bundleId over app. You can get the iOS bundle Id for the default apps from here

**iOS 10:**
https://emm.how/t/ios-10-list-of-default-apps-and-bundle-ids/361
**iOS 11:**
https://emm.how/t/ios-11-list-of-default-apps-and-bundle-id-s/465

I confirm, I can automate iOS default Apps.

Now looking for the possibilities of automating Android default Apps.

**Comment by KazuCocoa** [comment]
For Android, the followings will help you, I believe.

- https://github.com/appium/appium/issues/9840#issuecomment-353759733
- https://github.com/appium/python-client/issues/184#issuecomment-333538371
- https://github.com/appium/appium/blob/master/docs/en/commands/device/app/launch-app.md

**Comment by SamyQAZ** [comment]
@Gnanaraj-S Were you able to accomplish testing iOS mail app.

In my test I need to switch from my.app to mail.app, open email and click on a reset password and confirm email url one by one.

Spent couple of days still no luck. 
It would be really if you could share your experience on testing third party apps. 
I am using Appium.app - 1.3.0 (1.3.0), CLI - 1.7.2, python, robot framework

**Comment by LeSamerian** [comment]
@SamyQAZ I'm having the exact same problem. I'm also totally new to Appium ,So it doesn't help. How do you go about automating opening the email app then open an attached document into my.app for example ?

I'm using Appium 1.7.2, Lettuce, Python

**Comment by SamyQAZ** [comment]
@LeSamerian I am using Appium 1.7.2, Robot framework for native app testing. I am using Appium since past 2.5 years. Yes there are few things which are really unpredictable but the community is really helpful in resolving and helping out.

I haven't achieved success in redirection from MY.app to Mail.app yet. Once its achieved I can try to see if document can be opened.

**Comment by LeSamerian** [comment]
Thank you so much @SamyQAZ !
@Gnanaraj-S or anyone else would you kindly share your capability configuration ? Mine keeps failing With com.apple.mobilemail not found

{
  "platformName": "iOS",
  "platformVersion": "11.2",
  "deviceName": "iPhone 6",
  "bundleId": "com.apple.mobilemail",
  "automationName": "XCUITest",
  "uuid": "[XYZ]"
}

**Comment by Alya96** [comment]
@Gnanaraj-S or anyone, I use "bundleId": "com.apple.mobilemail" for opening mail, but something went wrong. The mail screen is opened without any issue on device, but in Appium Desktop elements screen -  doesn't. What can bring it about? Besides, when mail is opened on real device that screen becomes freezed for some seconds(like it checks for updates) and after it error message is appeared on Appium Desktop. This issue is only with "com.apple.mobilemail" bundleId. The others work well. 
iOS version - 11.1.2, Appium version - 1.7.2, Xcode version - 9.2

**Comment by KazuCocoa** [comment]
> With com.apple.mobilemail not found

Could you find the bundle id on your device using the below?
https://github.com/phonegap/ios-deploy

@Alya96 also.
What about other OS versions?
In many cases, it depends on iOS.
I experienced some OS versions work, but one OS version doesn't, iPhone works but iPad doesn't.

So, could you try other versions once?

> it error message is appeared on Appium Desktop

If you could attach the log, it helpful to image the behaviour, btw.
