### ISSUE TITLE
Not able to use FIND ELEMENT by Name, AndroidUIAutomator 

### ISSUE THREAD

**Issue by VegetaSama26** [appium/appium#9845]
## The problem

I am using appium java client version v-5.0.4 and appium v-1.7.1, whenever i am trying to find an element on the device using text or using AndroidUiAutomator, appium showing error that both have been depreciated in this version. 
As i was trying to create a framework need to know what items and how to use. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows
* Node.js version (unless using Appium.app|exe): v8.9.1
* Mobile platform/version under test: Android 6.0
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium on CMD

## Details

appium showing error that both have been depreciated in this version, i am trying below code
1.driver.findElementByAndroidUIAutomator("new UiSelector().resourceid(\"com.vector.guru99:id/lblListHeader\")").click();
2. driver.findElement(By.name("Course Category")).click();

## Link to Appium logs
WebElement cannot be find 

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
It is the expected behaviour. `By.id` or `MobileBy.AccessibilityId` locator should be used instead.
