### ISSUE TITLE
Issue with ios-deploy 

### ISSUE THREAD

**Issue by SaptakBagchi** [appium/appium#9847]
## Details
I have installed ios deploy i.e. npm install -g ios-deploy (via Terminal) but still getting below error after starting the session in Appium desktop.

[MJSONWP] Encountered internal error running command: Error: Could not install app: 'Command 'ios-deploy --id 2897b65c1a1d82dfe230aeb11764ec28b143d955 --bundle /var/folders/z9/h7lbry753r328684zrgqg_0w0000gp/T/20171122-10299-kefvlf.qaskr6yldi/Payload/MoPo.app' exited with code 253'

## Environment
  "platformName": "iOS",
  "platformVersion": "11.1.2",
  "deviceName": "administrator’s iPad",
  "udid": "Provided",
  "app": "Provided"

## Link to Appium logs

https://gist.github.com/SaptakBagchi/5307b227d98ad3d1f98f03d5be1351a3

**Comment by mykola-mokhnach** [comment]
Are you able to install the application under test manually? Is it properly signed with development signature and built in debug mode?

Also, the attach gist does not contain valid server logs.
