### ISSUE TITLE
Driver cannot start on iPhone due security pop-up

### ISSUE THREAD

**Issue by lubshilk** [appium/appium#9850]
Hi,

Automation fails with "[XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65" almost every night run. Always when automation fails security pop-up shown on iPhone (like "allow iMessage...)

After accepting pop-up manually  or re-start of the iPhone tester without any other changes driver connects to tester with no problem.

Is there possibility to overcome the problem?

## Environment

* Appium server 1.7.0
* Mac OS 10.12.6
* IPhone : IOS 11
* Real device

## Link to Appium logs
https://gist.github.com/lubshilk/a77b630406e8c04d0df5d4027deaa0c5

**Comment by mykola-mokhnach** [comment]
This is known XCTest limitation. Please report a feature request to Apple.
