### ISSUE TITLE
[IOS] Cannot accept/decline IOS alert after click a link

### ISSUE THREAD

**Issue by By-ivan** [appium/appium#9852]
## The problem

After clicking on social share button (e.g. share on Facebook, Twitter etc.) that should open in new window IOS system alert appears (Allow or not to open link in new window) and test is freezing (no response from driver with click result). So as result there is no possibility to handle alert after click such button. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable): not recognized
* Desktop OS/version used to run Appium: 10.12.6
* Node.js version (unless using Appium.app|exe):9.2.1
* Mobile platform/version under test: IOS 10.3
* Real device or emulator/simulator:simulator
* Appium CLI or Appium.app|exe: appium cli

## Details

The core issue is that I cannot interact with driver after clicking such button to decline or dismiss alert. So this is just a deadend of the test.

## Link to Appium logs
https://gist.github.com/By-ivan/4be7eb858734ac9a4718c9da92f451c2

## Code To Reproduce Issue
Test project to reproduce issue can be found here https://github.com/By-ivan/appium-test
To run please follow readme.

**Comment by mykola-mokhnach** [comment]
XCTest cannot handle alerts created by third-party components. This is known limitation from Apple and there is no way to workaround it for now.

**Comment by By-ivan** [comment]
Hi, Mykola @mykola-mokhnach .
Could you please provide some details.
Have you noticed that  as i mentioned before: **"After clicking on social share button ... test is freezing (no response from driver with click result)"**.  Simple code snippet below:
1 `driver.get("http://m.bbc.com/sport/rugby-league/39829001");`
2 `driver.findElement(By.xpath("//*[@id='sb-1']/span[1]/i")).click();`
3 `driver.findElement(By.xpath("//*[@id='sb-1-panel']/ul/li[2]/a")).click();`
4` System.out.println("Never will be reached");`
After line's 3 click driver will stuck.
Is this expected behavior and known limitation? 
If so could you please provide some link to the issue or any related information that will help track issue status/progress.
Thank you in advance

**Comment by mykola-mokhnach** [comment]
I'd try switching to native context in order to accept the alert. Otherwise no more suggestions.

**Comment by By-ivan** [comment]
@mykola-mokhnach  

> I'd try switching to native context in order to accept the alert. 
But as i said before driver cannot finish click on the element and cannot be interacted with until the click command finished.

**Comment by By-ivan** [comment]
@mykola-mokhnach Could you please clarify is that expected behavior - driver freezing after such button click.
And if so, since you are closing the issue if its possible could you please advice the way i can track the issue progress? 
Thank you in advance

**Comment by mykola-mokhnach** [comment]
> Could you please clarify is that expected behavior - driver freezing after such button click.

Of course it's not, but we don't have control over this and are totally dependent on third-party implementations (XCTest/WebDriverAgent/IWDP). I'd rather track such issues where they originally come from.
