### ISSUE TITLE
Entering Shift and Left Arrow keys shows emojis instead of using those keys action (highlighting)

### ISSUE THREAD

**Issue by smccarthy** [appium/appium#9853]
## The problem

I want to highlight certain text in my mobile web page. On desktop browsers (and android), I am using the keys JSONWP to send Shift + Left Arrow (or Right Arrow). For desktop + android, it highlights the correct text. On iOS, it inputs emojis (camera for shift, and raising hand for left arrow). For Shift, I am using `\uE008` , for Left Arrow I am using `\uE012`.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable): Don't know
* Desktop OS/version used to run Appium: SauceLabs
* Node.js version (unless using Appium.app|exe): SauceLabs
* Mobile platform/version under test: iOS 11.0
* Real device or emulator/simulator: iOS Simulator
* Appium CLI or Appium.app|exe: SauceLabs

Webdriver.io bindings

## Details

I created this forum post, https://discuss.appium.io/t/entering-shift-left-arrow/20262 , but not sure if its better as a github issue. I am using the keys mentioned here : https://www.w3.org/TR/webdriver/#keyboard-actions . I assumed they would work since I see some tests using backspace and delete keys : https://github.com/appium/appium-xcuitest-driver/blob/master/test/functional/basic/element-e2e-specs.js#L274

## Link to Appium logs

Appium Logs : https://gist.github.com/smccarthy/5327420192a0147146f42e7b656ec42c
Appium Server Logs : https://gist.github.com/smccarthy/f2b22c5c4dfa015a2061e7e6f0b449e9

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by smccarthy** [comment]
@mykola-mokhnach I don't think this is a question. I think its more of a bug, right? Shouldn't the keys work instead of inputting emojis ?

**Comment by mykola-mokhnach** [comment]
even if there issues then it has nothing to do with Appium itself, since it is just a proxy. All sendKeys actions are executed by WebDriverAgent/XCTest. You could check https://github.com/facebook/WebDriverAgent/blob/4576e9e9147c4cb8573421361effdf8de1046638/WebDriverAgentLib/Utilities/FBKeyboard.mr in order to understand how the stuff works under the hood.

**Comment by smccarthy** [comment]
@mykola-mokhnach Awesome, thank you! I'll check there.
