### ISSUE TITLE
how to reset  ImplicitlyWaitTimeOut when using PageFactory?

### ISSUE THREAD

**Issue by daisychainsaw00** [appium/appium#9855]
sorry...seems I shoud move this issue to "java-client"?

## The problem

when using pageFactory for pageObject model, I will new a appiumFieldDecorator instance like this 
`        AppiumFieldDecorator appiumFieldDecorator =
                new AppiumFieldDecorator(context, 20000, TimeUnit.MILLISECONDS);`
which I pass a timeout param to the constractor.  then it seems like there is no way to update the ImplicitlyWaitTimeOut of this instance

I also found out that in previous version of java-client e.g. v2.2.0,there is a "resetImplicitlyWaitTimeOut" method that can update the timeout ,but after v3.0.0 this method seems to be removed. and the timeout variable of AppiumFieldDecorator is a constant now

so is there anyway to update  timeout  when using pageFactory after v3.0.0? 

## Environment

* Appium version : 1.6.5
* java-client version :3.4.1
* Desktop OS/version used to run Appium: mac os
* Mobile platform/version under test: Android

**Comment by mykola-mokhnach** [comment]
> sorry...seems I shoud move this issue to "java-client"?

exactly
