### ISSUE TITLE
Appium 1.7.1 uiautomator2 find_element by id need exact package name

### ISSUE THREAD

**Issue by julia0423** [appium/appium#9856]
## The problem
release version is: find_element(id:'com.baidu:id/button')
debug version is : find_element(id:'com.baidu.debug:id/button')
## Environment

* Appium version (or git revision) that exhibits the issue:1.7.1
* Last Appium version that did not exhibit the issue (if applicable):1.6.4
* Desktop OS/version used to run Appium:mac
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:Android 7.0
* Real device or emulator/simulator:both
* Appium CLI or Appium.app|exe:CLI

## Details
in previous both the android apk release and debug version can run, after upgrade appium to 1.7.1 with uiautomator2, my code is "find_element(id:'com.baidu:id/button')" which only can run release version, if run debug version need to modify to " find_element(id:'com.baidu.debug:id/button')".

**Comment by mykola-mokhnach** [comment]
have you tried to drop the prefix at all: `find_element(id:'button')`?

**Comment by julia0423** [comment]
@mykola-mokhnach yes, i tried this and it worked, if remove the package name can support both release and debug version, but i am a little confused why previous it can work, and is there any problem after remove the package name?

**Comment by julia0423** [comment]
btw i see this sentence 
"Appium only knows about the package used to start the session and the default android package. If you have multiple packages within a session, then you'd still need the fully qualified id." of this issue https://github.com/appium/appium/issues/4416
i did not understand yet

**Comment by mykola-mokhnach** [comment]
Please use Appium forum to ask questions
