### ISSUE TITLE
I want to use some mobile phones or examples

### ISSUE THREAD

**Issue by namexiaohuihui** [appium/appium#9857]
## The problem

Is there a use manual for the appium1.2.7 version?

Every time I connect to Android 7.1, I say I can't create a new connection.

## Environment

windows 10
appnium 1.2.7
python 3.6.4

## Details

I want to use this tool to run the specified app for a test, but you can't start app every time.

After running the tool, you will install two tools on your cell phone.　　Unlock  and Appnium Settings

**Comment by mykola-mokhnach** [comment]
Please use Appium forum to ask questions. 
Code examples one can find at https://github.com/appium/sample-code
Documentation: https://github.com/appium/appium/tree/master/docs

**Comment by namexiaohuihui** [comment]
Thank you for your advice.

Next time I'll go to the Appium forum to ask questions.
