### ISSUE TITLE
Appium and emulator connection issue

### ISSUE THREAD

**Issue by gauravshridhar92** [appium/appium#9860]
I am able to connect emulator and appium if i am using both of them on same machines(Ubuntu 16.x) , Appium is unable to recognize or find the device to connect if both of them are on different machines , As both the machines are on same network still i am facing this issue. Kindly help .

**Comment by mykola-mokhnach** [comment]
Please fill out the issue reporting form and provide all the data asked there. Otherwise the current issue description in not sufficient to make any conclusions.

**Comment by selfoptima** [comment]
What other info do you need from my end ..Kindly specify

**Comment by gauravshridhar92** [comment]
* Appium version (or git revision) that exhibits the issue:  v8.9.3
* Desktop OS/version used to run Appium: Ubuntu  16.04
* Node.js version (unless using Appium.app|exe):1.7.1
* Mobile platform/version under test: Emulator with API level 24
* Real device or emulator/simulator:Emulator

Kindly let me know if you need any other info from my end

**Comment by KazuCocoa** [comment]
You can see template when you create a new issue via https://github.com/appium/appium/issues/new and it requires logs you can get from the Appium server.

BTW, can you see the target device via `adb devices` command on the machine which running Appium server on?
