### ISSUE TITLE
I cannot understand the documentation for appium.

### ISSUE THREAD

**Issue by staplesj** [appium/appium#9861]
## The problem

I am trying to install and use appium for the first time, but cannot understand the documentation. The article 'Getting Started' (http://appium.io/docs/en/about-appium/getting-started/?lang=en) refers to this page on the UIAutomator2: http://appium.io/docs/en/drivers/android-uiautomator2/index.html#TODO
Links I have tried to follow on this page do not work, or just loop back to the same page.
i.e New to Appium? Read our introduction to Appium drivers - points straight back to the same page.
The paragraph on Usage makes no sense at all.

"The way to start a session using the UiAutomator2 driver is to include the automationName **capability** (link does not work) in your **new session request** (link does not work), with the value UiAutomator2. Of course, you must also include appropriate platformName (=Android), platformVersion, deviceName, and app capabilities, at a minimum.

It is highly recommended to also set the appPackage and appActivity capabilities in order to let Appium know exactly which package and activity should be launched for your application. Otherwise, Appium will try to determine these automatically from your app manifest."

Most crucially further down, there is the instruction Install the Android SDK. Again, the link does not work. _What Android SDK is being referred to here?_

**Comment by staplesj** [comment]
There is more - on the Getting Started page:

Session Initialization
Now we can create our test file (name it whatever you like) and initialize the client object:

// javascript
const wdio = require('webdriverio');

How are we meant to create this test file? 

These instructions really need improving!

**Comment by dpgraham** [comment]
Thanks for reporting this. There seems to be a problem with the links.

The test file is just a file you create like any other file on your Operating System. You create the file and then run it from your command line.

**Comment by dpgraham** [comment]
@jlipps A few of the links on the [UiAutomator2 Driver](https://github.com/appium/appium/edit/master/docs/en/drivers/android-uiautomator2.md) page have links to `#TODO`. Do you know if those documents have been created yet?
