### ISSUE TITLE
Setting MAC for ios real device 

### ISSUE THREAD

**Issue by michaazran** [appium/appium#9862]
## The problem

i am trying to run appium on my iPhone , i am running the appium GUI on MAC and connecting it from other PC using visual studio as remote, i got the following error

error: Failed to start an Appium session, err was: Error: Unable to install [/var/folders/z3/6sp0jp_s1_9fs2ryq44r9y_m0000gn/T/1171127-12607-126nawd/submodules/SafariLauncher/build/Release-iphoneos/SafariLauncher.app] to device with id [a85976035c6dc2c15e7df2d164b65fb1161c3311]. Error [Error: Command failed: /bin/sh: /Applications/Appium: No such file or directory

]
info: [debug] Error: Unable to install [/var/folders/z3/6sp0jp_s1_9fs2ryq44r9y_m0000gn/T/1171127-12607-126nawd/submodules/SafariLauncher/build/Release-iphoneos/SafariLauncher.app] to device with id [a85976035c6dc2c15e7df2d164b65fb1161c3311]. Error [Error: Command failed: /bin/sh: /Applications/Appium: No such file or directory]
at /Applications/Appium 1.3.4.app/Contents/Resources/node_modules/appium/lib/devices/common.js:147:10
at ChildProcess.exithandler (child_process.js:662:7)
at ChildProcess.emit (events.js:98:17)
at maybeClose (child_process.js:766:16)
at Socket. (child_process.js:979:11)
at Socket.emit (events.js:95:17)
at Pipe.close (net.js:466:12)

info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Unable to install [/var/folders/z3/6sp0jp_s1_9fs2ryq44r9y_m0000gn/T/1171127-12607-126nawd/submodules/SafariLauncher/build/Release-iphoneos/SafariLauncher.app] to device with id [a85976035c6dc2c15e7df2d164b65fb1161c3311]. Error [Error: Command failed: /bin/sh: /Applications/Appium: No such file or directory\n])","origValue":"Unable to install [/var/folders/z3/6sp0jp_s1_9fs2ryq44r9y_m0000gn/T/1171127-12607-126nawd/submodules/SafariLauncher/build/Release-iphoneos/SafariLauncher.app] to device with id [a85976035c6dc2c15e7df2d164b65fb1161c3311]. Error [Error: Command failed: /bin/sh: /Applications/Appium: No such file or directory\n]"},"sessionId":null}
info: <-- POST /wd/hub/session 500 5242.685 ms - 742

## Environment

my iPhone is 6S with ios 11.0.3
MAC os is 10.8.5
xCode 5.1.1
real device

## Details

i do not have the developer option exist under iphone - options, when i tried to check the developer options to mark the UIAutomator i got an error from xCode that it is tool old for my iPhone version

i also tried to run the new appium 1.2.7 but i got an error that 10.8.5 is too old and i need at least 10.9
when i ran an old version of appium 1.3.4 it opened successfully
can someone advice what si the shortest way that i can start running appium on that device using my MAC ?

**Comment by saikrishna321** [comment]
Please raise in https://discuss.appium.io/ this place is to track issue related to appium.

> my iPhone is 6S with ios 11.0.3 

You need to have iOS 9.X, you current are working on very old version 5.1.1
