### ISSUE TITLE
Appium testing - error 'getting badging info'

### ISSUE THREAD

**Issue by staplesj** [appium/appium#9865]
## The problem

Trying to run the example from the Appium - Getting Started guide:

http://appium.io/docs/en/about-appium/getting-started/?lang=en

I am getting the following error: 

`Error "Command 'C\:\\Users\\SStaple\\AppData\\Local\\Android\\Sdk\\build-tools\\26.0.2\\aapt.exe d badging C\:\\Users\\SStaple\\AppData\\Local\\Programs\\appium-desktop\\resources\\app\\node_modules\\appium\\node_modules\\appium-uiautomator2-driver\\uiautomator2\\appium-uiautomator2-server-v0.1.8.apk' exited with code 1" while getting badging info`

**The package exists at the address specified!!!**

How is this fixed?

note: https://discuss.appium.io website is not working. Have tried to Sign up, but no activation email was ever received.

## Environment

* Appium version (or git revision) that exhibits the issue: Appium v1.7.1
* Last Appium version that did not exhibit the issue (if applicable): n/a
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): Node.js 8.9.3
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

Full output:

## Link to Appium logs

https://gist.github.com/staplesj/5b2b2adec8b23fdc46b06752a769393d

## Code To Reproduce Issue [ Good To Have ]

    const wdio = require('webdriverio');

    const opts = {
      port: 4723,
      desiredCapabilities: {
        platformName: "Android",
        platformVersion: "8.0",
        deviceName: "Android Emulator",
        app: "C:/Users/SStaple/AppData/Local/Android/Sdk/ApiDemos-debug.apk",
        automationName: "UiAutomator2"
      }
    };

    const client = wdio.remote(opts);

    console.log( 'Hello, world!' );

    client
      .init()
      .click("~App")
      .click("~Alert Dialogs")
      .back()
      .back()
      .end();
  
      console.log( 'End of code reached!' );

**Comment by KazuCocoa** [comment]
> note: https://discuss.appium.io website is not working. Have tried to Sign up, but no activation email was ever received.

cc @jlipps @imurchie @dpgraham 

----

> [UiAutomator2] Unable to remove port forward 'Error executing adbExec. Original error: 'Command 'C\:\\Users\\SStaple\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s emulator-5554 forward --remove tcp\:8200' exited with code 1'; Stderr: 'error: listener 'tcp:8200' not found'; Code: '1''
[MJSONWP] Encountered internal error running command: Error: Cannot read manifest information from 'C:\Users\SStaple\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-uiautomator2-driver\uiautomator2\appium-uiautomator2-server-v0.1.8.apk'. Does the package exist and is accessible?
    at UiAutomator2Server.installServerApk$ (C:\Users\SStaple\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-uiautomator2-driver\lib\uiautomator2.js:40:13)
    at tryCatch (C:\Users\SStaple\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\SStaple\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\SStaple\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\SStaple\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)

Could you try `adb` and `aapt` commands like the above by manual? @staplesj

**Comment by mykola-mokhnach** [comment]
Usually such stacktrace is thrown when the server .apk file is not accessible/does not exist on the local file system. Make sure the Appium process has access to the path above.

Closed as non Appium-related issue.

**Comment by staplesj** [comment]
There were a number of issues.

First, the device name needed to match the name given to my emulator device in Android studio. I stuck with defaults: deviceName: "Pixel_API_26",

Secondly, the file queried in the original post - appium-uiautomator2-server-v0.1.8.apk - was 0Kb in size! I downloaded the apk file from https://github.com/appium/appium-uiautomator2-server/releases and used that instead. This one is 1,518 KB in size. (Apparently there is some problem with npm not putting that apk file into the right place while beta is installed.)

So yes - this is an Appium issue.

**Comment by mykola-mokhnach** [comment]
Server version in the recent beta is 0.2.1, it cannot be 0.1.8
I've also seen similar reports before and they all only happen on Windows, which means that `npm` does not properly adjust fs permissions on the folder, where packages are downloaded/installed, and it is sometimes needed to fix the stuff manually.

**Comment by staplesj** [comment]
That appium-uiautomator2-server-v0.1.8.apk file keeps disappearing.  It is back to 0 KB again?
Something keeps overwriting this file?
