### ISSUE TITLE
Appium Installation Issue in MAC

### ISSUE THREAD

**Issue by MBalasubramanian** [appium/appium#9867]
Hi Team,

We are facing issue while installing Appium in our MAC environment(Sierra OS in specific), pfa the logs and error screenshot for your reference, pls suggest on this issue.

We referred few open forum suggestions and tried using Sudo and regular way and also tried using chmod 777 also, but none of the options worked for us.

Regards,
Bala[
[Logs.zip](https://github.com/appium/appium/files/1589564/Logs.zip)
<img width="773" alt="install_error" src="https://user-images.githubusercontent.com/2011216/34388845-c0754000-eafb-11e7-8cf9-be66646ed663.png">
<img width="777" alt="npmrc_file" src="https://user-images.githubusercontent.com/2011216/34388846-c0838ac0-eafb-11e7-83e6-e3ecb06fb8d1.png">

](url)

**Comment by mykola-mokhnach** [comment]
Make sure that npm and node are at the most recent version

**Comment by MBalasubramanian** [comment]
Hi Mykola, checked and found as follows, are they fine ?
PerfTest-Hotspot:~ perftest$ npm -v
5.6.0

PerfTest-Hotspot:~ perftest$ node -v

v7.9.0
Thanks, Bala 

    On Wednesday, December 27, 2017, 12:05:08 PM CST, Mykola Mokhnach <notifications@github.com> wrote:  
 
 
Make sure that npm and node are at the most recent version

**Comment by MBalasubramanian** [comment]
Anyhow just upgrade the node version to latest, but npm version got downgraded, let me try Appium installation now.
PerfTest-Hotspot:~ perftest$ node -v
v8.9.3
PerfTest-Hotspot:~ perftest$ npm -v
5.5.1

**Comment by MBalasubramanian** [comment]
Still no luck, got the attached Chrome Driver error :( Please help
<img width="491" alt="appium_chromdriver_error" src="https://user-images.githubusercontent.com/2011216/34389692-ccac8d1a-eb00-11e7-94ec-0a16647decb5.png">

**Comment by mykola-mokhnach** [comment]
One should not install Appium as root. Also, make sure you have proxy server configured properly if the machine is behind corporate firewall.

**Comment by imurchie** [comment]
Do you have permission to write to that directory?

Also, can you try installing without `sudo`? Doing so is generally a bad idea.

**Comment by MBalasubramanian** [comment]
Thanks both, tried setting the proxy and also without sudo, still it does not work, pls check the .npmrc file screenshot attached earlier.

**Comment by mykola-mokhnach** [comment]
cleanup the leftovers from the previous installation to fix permissions issues and try again until it succeeds. Otherwise try on the other machine. 

Closed as not an issue.
