### ISSUE TITLE
Could not proxy command to remote server. Original error: Error: socket hang up

### ISSUE THREAD

**Issue by amitwagle** [appium/appium#9868]
Problem
I am getting below error intermittently while running my automation script or opening app through appium inspector for a particular scenario.

"Could not proxy command to remote server. Original error: Error: socket hang up"

I have test cases automated to validate functionality when the device is offline. 
For this I am swiping through co-ordinates and clicking on wifi button and making the device offline through automation

After clicking on wifi button it's throwing me error "Could not proxy command to remote server. Original error: Error: socket hang up"
However this is not happening always sometimes it is working. 
Sometimes after proceeding further (i.e. after making device offline) it is throwing above error while performing action on application.
Some time test script is running properly till end without any issue.

Attaching screenshot of error while working with appium inspector
<img width="1261" alt="appium-wifi-screenshot" src="https://user-images.githubusercontent.com/29560985/34391310-613566ba-eb0a-11e7-8d53-ec5aed3e1680.png">

Attaching Appium logs
[Appium log.txt](https://github.com/appium/appium/files/1589715/Appium.log.txt)

 
Attaching IntelliJ console logs when the error occur.
[IntelliJ console.txt](https://github.com/appium/appium/files/1589717/IntelliJ.console.txt)

Earlier for iOS 10.2.1 - Xcode 8.3.2 - Appium 1.6.5 , scripts were working properly with no issues.

 
Environment
Appium version : 1.7.2-beta2
XCode : 9.2 
iPAD OS : 11.2.1
Mac OS : 10.13.1 (Mac OS High Sierra)
Node version : v9.3.0
Appium Desktop : 1.2.7

**Comment by mykola-mokhnach** [comment]
I don't think anything can be done on Appium side  in order to resolve such issues. `Error: socket hang up` means that WebDriversAgents stops responding to proxied commands. I'd try to report the problem to https://github.com/facebook/WebDriverAgent/issues
