### ISSUE TITLE
Appium server got stuck, not showing any progress.

### ISSUE THREAD

**Issue by shubhamagarwal007** [appium/appium#9870]
Appium server got stuck- running from terminal

Please refer to below log details of terminal
```
ebsd91:~ ebsadmin$ [Appium] Welcome to Appium v1.7.1
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
```
after that nothing happens in terminal
waited for 30 mins but not showing any progress, same thing happening in desktop Appium application.

NOTE :Runs the appium doctor in terminal, as per Appium doctor everything is OK 
info **AppiumDoctor Everything looks good, bye!**

## Environment

* Appium version (or git revision) that exhibits the issue:1.7.1
* Desktop OS/version used to run Appium: macOS High Sierra /10.13
* Node.js version (unless using Appium.app|exe): 5.6.0

Please refer to screenshot
![screen shot 2017-12-28 at 12 44 15 pm](https://user-images.githubusercontent.com/7900462/34403197-dc21c2f2-ebcc-11e7-9c26-f26dca2b23b2.png)

To install the Appium I have followed the steps given in GitHub site-
https://github.com/isonic1/appium-workshop/blob/master/Appium%20Mac%20Installation%20Instructions.md

Except : **Create Android Emulator steps**, I have covered all the steps mention on site

**Comment by dpgraham** [comment]
Appium is a server process and runs permanently on localhost at port 4723. Once the server is running, the next step is to write scripts that make HTTP calls to the server to perform test automation.

I would consult [this document](http://appium.io/docs/en/about-appium/getting-started/) and go to the 'Running your first test' section to write your first test script.

The important thing to understand is that the Appium server is supposed to run in the background permanently and that you need to write scripts that make calls to the Appium server to run the app automation.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
