### ISSUE TITLE
Appium test throws error 'Could not sign with default certificate'.

### ISSUE THREAD

**Issue by staplesj** [appium/appium#9872]
## The problem

I am trying to run the demo code given in the Getting Started with Appium documentation: http://appium.io/docs/en/about-appium/getting-started/?lang=en

The appium server is throwing a number of errors, the first of which says:

`[ADB] Error: Could not sign with default certificate. Original error Command ''C:\\Program Files\\Java\\jdk-9.0.1\\bin\\java.exe' -jar C\:\\Users\\SStaple\\AppData\\Local\\Programs\\appium-desktop\\resources\\app\\node_modules\\appium\\node_modules\\appium-adb\\jars\\sign.jar C\:\\Users\\SStaple\\AppData\\Local\\Programs\\appium-desktop\\resources\\app\\node_modules\\appium\\node_modules\\appium-uiautomator2-driver\\uiautomator2\\appium-uiautomator2-server-v0.1.8.apk --override' exited with code 1`

I have tried this code on it's own in the Command Prompt: 

`'C:\Program Files\Java\jdk-9.0.1\bin\java.exe' -jar C\:\Users\SStaple\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-adb\jars\sign.jar C\:\Users\SStaple\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-uiautomator2-driver\uiautomator2\appium-uiautomator2-server-v0.1.8.apk --override`

It responds with:

`The filename, directory name, or volume label syntax is incorrect.`

## Environment

* Appium version (or git revision) that exhibits the issue: Appium Server v1.7.1
* Last Appium version that did not exhibit the issue (if applicable): n/a
* Desktop OS/version used to run Appium: Windows 10 Pro for Workstations.
* Node.js version (unless using Appium.app|exe): Node.js 8.9.3
* Mobile platform/version under test: as documentation 'Getting Started' http://appium.io/docs/en/about-appium/getting-started/?lang=en
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: ?

## Details

See gist log for more detail.

## Link to Appium logs

https://gist.github.com/staplesj/d959026623807f11ed17e191dc90c1af

```
## Code To Reproduce Issue [ Good To Have ]

`
console.log( 'appiumTest starting...' );
const wdio = require('webdriverio');

const opts = {
  port: 4723,
  desiredCapabilities: {
    platformName: "Android",
    platformVersion: "8.0",
    deviceName: "Pixel_API_26",
    app: "C:/Users/SStaple/AppData/Local/Android/Sdk/ApiDemos-debug.apk",
    automationName: "UiAutomator2"
  }
};



const client = wdio.remote(opts);



client
  .init()
  .click("~App")
  .click("~Alert Dialogs")
  .back()
  .back()
  .end();
  
  console.log( 'appiumTest finished. See Appium server for output.' );`
```

**Comment by mykola-mokhnach** [comment]
Try to downgrade Java to 1.8

**Comment by staplesj** [comment]
Where do I need to downgrade Java?

`java -version
java version "9.0.1"
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)`

Also have installed:

Java 8 Update 151
Java(TM) SE Development Kit 9.01 (64-bit)

**Comment by staplesj** [comment]
Thanks for your help.
I have uninstalled all the Java 9.01 stuff & replaced it with Java 8. (I had not realized that Java 8 & Java 1.8 were the same thing)
Also recopied that appium-uiautomator2-server-v0.1.8.apk file that keeps disappearing.
Had to update JAVA_HOME, and now the whole demo works!

**Comment by Alwirasheikh** [comment]
i have java 8 installed still i am getting the same error. please help me to solve.
