### ISSUE TITLE
parallel execution issue  

### ISSUE THREAD

**Issue by rameshkvv6231** [appium/appium#9873]
Hi Team getting issue with parallel execution. I am using testNG for this, I created a class and in the beforeclass i passed all the capabilities(I am passing parameter by using testng.xml)

I created 3 @test in this class file and I am passing them in testng.xml both the instance are started uto 3 times execution on both the devices working after that 1 instance went to after test but it is closing the 2 open Why I dont no 

Please find the below code:
@aftertest
public void aftertest(){
driver.closeApp();
driver.launchApp();
}
 @paramater({"udid","bundleID", "platform","server"})
@BeforeClass
public AppiumDriver<MobileElement> start(String udid, String bundleID, OperatingSystem platform, String server) throws Exception {
 switch (platform) {
 case IOS: 
capabilities = new DesiredCapabilities();
 capabilities.setCapability("deviceConnectUserName", username); capabilities.setCapability("deviceConnectApiKey", apiToken);
 capabilities.setCapability("udid", udid); 
capabilities.setCapability("platformName", platform);
 capabilities.setCapability("bundleID", bundleID); 
capabilities.setCapability("automationName", "XCUITest"); 
driver = new IOSDriver<MobileElement>(new URL(server), capabilities); driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS); 
Thread.sleep(10000);
}

!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >
<suite name="Test" parallel="tests" thread-count="2">
	<test name="BillPay_iphone7">
		<parameter name="udid" value="" />
		<parameter name="bundleID" value="aaa"/>
		<parameter name="platform" value="IOS" />
		<parameter name="server" value="" />
		<classes>
			<class name="BillPaymentsTest">
				<methods>
					<include name="cccc" />
				</methods>
			</class>
		</classes>
	</test>
	<test name="dsdsd">
		<parameter name="udid" value="xxxx" />
		<parameter name="bundleID" value="xxx" />
		<parameter name="platform" value="IOS" />
		<parameter name="server" value="" />
		<classes>
			<class name="BillPaymentsTest">
				<methods>
				  <include name="XXXX" />
				  <include name="CCXXX" />
				</methods>
			</class>
		</classes>
	</test>

Can you reply ASAP

**Comment by mykola-mokhnach** [comment]
Unfortunately I am unable to understand what the problem is. Please fill out the issue reporting form and provide detailed problem description along with the full server log.

**Comment by rameshkvv6231** [comment]
While executing parallel executio

**Comment by rameshkvv6231** [comment]
I am getting issue with parallel execution... 2 instances running... In the middle of the execution second device is executing the 1 code. 
This is before class method

capabilities = new DesiredCapabilities();
capabilities.setCapability("deviceConnectUserName", username); capabilities.setCapability("deviceConnectApiKey", apiToken);
capabilities.setCapability("udid", udid);
capabilities.setCapability("platformName", platform);
capabilities.setCapability("bundleID", bundleID);
capabilities.setCapability("automationName", "XCUITest");
driver = new IOSDriver(new URL(server), capabilities);

**Comment by imurchie** [comment]
You need to specify a different WDA port for each running instance, or else they will all be sent to the same device. Please see http://appium.io/docs/en/advanced-concepts/parallel-tests/
