### ISSUE TITLE
Uiautomator2 click NosuchElementException issue

### ISSUE THREAD

**Issue by cloudyhuang** [appium/appium#9875]
appium version:1.6.5
jdk :1.8.0_51
android device:5.0
java-client:5.0.0
selenium-java:3.5.2
----------------------------------
when I switch driver to Uiautomator2,I found that some element can't be clicked,and throw NoSuchElementException.These elements attribute  'clickble' are false,like this pic:

![91cd7846-850f-4dd4-8067-c5408502a20c](https://user-images.githubusercontent.com/28583179/34428940-c9dc2dce-ec8c-11e7-9c4f-e124afdb0073.png)

Here is my appium log（I set 30s implicit wait ,many wait logs be deleted）:
......
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8200/wd/hub/session/a2a21814-79d4-4e37-b326-a92a8d2b74b8/element] with body: {"strategy":"id","selector":"view_user_photo","context":"","multiple":false}
[HTTP] <-- POST /wd/hub/session/bafec51c-c330-4144-af69-793ae9815d7a/element 500 10 ms - 164 
[HTTP] --> POST /wd/hub/session/bafec51c-c330-4144-af69-793ae9815d7a/element {"using":"id","value":"view_user_photo"}
[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["id","view_user_photo","bafec51c-c330-4144-af69-793ae9815d7a"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8200/wd/hub/session/a2a21814-79d4-4e37-b326-a92a8d2b74b8/element] with body: {"strategy":"id","selector":"view_user_photo","context":"","multiple":false}
[HTTP] <-- POST /wd/hub/session/bafec51c-c330-4144-af69-793ae9815d7a/element 500 11 ms - 164 
[HTTP] --> POST /wd/hub/session/bafec51c-c330-4144-af69-793ae9815d7a/timeouts {"type":"implicit","ms":30000}
[debug] [MJSONWP] Calling AppiumDriver.timeouts() with args: ["implicit",30000,"bafec51c-c330-4144-af69-793ae9815d7a"]
[debug] [BaseDriver] Set implicit wait to 30000ms
[debug] [MJSONWP] Responding to client with driver.timeouts() result: null
[HTTP] <-- POST /wd/hub/session/bafec51c-c330-4144-af69-793ae9815d7a/timeouts 200 1 ms - 76 
[BaseDriver] Shutting down because we waited 600 seconds for a command
[debug] [UiAutomator2] Deleting UiAutomator2 session
[Appium] Closing session, cause was 'New Command Timeout of 600 seconds expired. Try customizing the timeout using the 'newCommandTimeout' desired capability'
[Appium] Removing session bafec51c-c330-4144-af69-793ae9815d7a from our master session list
[debug] [UiAutomator2] Deleting UiAutomator2 server session
[debug] [JSONWP Proxy] Proxying [DELETE /] to [DELETE http://localhost:8200/wd/hub/session/a2a21814-79d4-4e37-b326-a92a8d2b74b8] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"a2a21814-79d4-4e37-b326-a92a8d2b74b8\",\"status\":0,\"value\":\"Session deleted\"}"
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/master/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","192.168.56.101:5555","shell","am","force-stop","com.evergrande.eif.android.hengjiaosuo"]
[debug] [Logcat] Stopping logcat capture
[debug] [ADB] Removing forwarded port socket connection: 8200 
[debug] [ADB] Running '/Users/master/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","192.168.56.101:5555","forward","--remove","tcp:8200"]

But this element can be clicked at Uiautomator,not add  this capabilities`capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.ANDROID_UIAUTOMATOR2);` No exception,click normal.Is that Uiautomator2 bug?What should I do ?

**Comment by mykola-mokhnach** [comment]
Try to click by coordinates instead. We cannot change the way UIA2 determines whether an element is clickable or not.

**Comment by cloudyhuang** [comment]
coordinates is not a good solution em...But why UiAutomator can click these clickable false element ?my code just  :
@AndroidFindBy(id="xxx")
private AndroidElement ae
....
ae.click();

**Comment by mykola-mokhnach** [comment]
Then the only solution for you would be to create an issue report to Google about you cannot click an element, which is not-clickable.
