### ISSUE TITLE
Calender picker elements of iOS cannot recognized in appium inspector

### ISSUE THREAD

**Issue by sudarshanjan** [appium/appium#9876]
![calenderpickerios](https://user-images.githubusercontent.com/17067372/34431239-799f6824-ec93-11e7-9761-0911f4426614.jpeg)
## The problem

Hi all,
Elements are not recognised in calender picker of iOS application, how can we select the birthday date from calender picker as shown below, can any one please guide me on these.......

## Environment

* Appium version 1.6.5
* Xcode Version 8.3.3 
![calenderpickerios](https://user-images.githubusercontent.com/17067372/34431233-6dc3ca9a-ec93-11e7-81fe-9205debf88d3.jpeg)

* iOS version 10.3

**Comment by mykola-mokhnach** [comment]
This version of Appium inspector is not supported anymore. You must use https://github.com/appium/appium-desktop/releases

**Comment by sudarshanjan** [comment]
Hi mykola, thank you for your reply. In appium-desktop 1.2.7 also the calender picker elements are not visible in appium inspector. Can you please tell me how to solve this issue.
![screen shot 2018-01-02 at 12 53 01 pm](https://user-images.githubusercontent.com/17067372/34477049-6b1f7cc2-efbc-11e7-9fe3-9659f0f160ea.png)

**Comment by mykola-mokhnach** [comment]
Appium simply displays the stuff returned by XCTest. If the page cannot be shown then it must be an issue of XCTest framework itself. I'd also try with Xcode9.
