### ISSUE TITLE
android send_keys sometimes does not work

### ISSUE THREAD

**Issue by yizhixiaoxiaogou** [appium/appium#9879]
## The problem

use the code:
                         String xpaht ="//*[@content-desc='xxxx']";
			 AndroidElement ae =	driver.findElementByXPath(xpaht);
			 ae.click();
			 ae.sendKeys("44444");

## Environment

Appium v1.7.1
appium-desk 1.2.7
macOS 10.13.2
Mobile platform/version under test: android 7

## Details
the method  'sendKeys'   sometimes  work  well,sometimes does not work
I printed the page source and I am seeing the element. page source are diffrent some times

<android.widget.EditText index="1" ................. **resource-id="phonenum"**  instance="0" />
it does work by send_keys
<android.widget.EditText index="1" .................  instance="0" />
it  work well by send_keys

The difference between the two  is  "resource-id="phonenum"

i want to know why ? What should I do;

**Comment by yizhixiaoxiaogou** [comment]
driver.pressKeyCode(xxx) is wok well

**Comment by mykola-mokhnach** [comment]
Switch to UIAutomator2 backend
