### ISSUE TITLE
Application not launching when device is in stand by mode

### ISSUE THREAD

**Issue by BoazWarshawsky** [appium/appium#9880]
## The problem
I am running test against real iOS device and I see a problem that the test not starting and the applicaiton not even launching when the device state is in Stand by mode ("Stand by" means when you pressing the device top right button, on its right side)

## Environment
* Appium version : v1.7.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iPhone 6,  iOS 11.2.1
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs
https://github.com/BoazWarshawsky/iOSAutomationAgent/blob/master/appium.log

## Code To Reproduce Issue 
Just start any basic test.

**Comment by mykola-mokhnach** [comment]
This is known XCTest limitation. Nothing we can do about it.

**Comment by BoazWarshawsky** [comment]
Thanks,
Where I can find all your known issues?
We are about to work against AWS, do you might know my tests will run?

**Comment by mykola-mokhnach** [comment]
All issues are here. Just use search.

> We are about to work against AWS, do you might know my tests will run?

No idea
