### ISSUE TITLE
org.openqa.selenium.WebDriverException:  An unknown server-side error occurred while processing the command. Original error: Error executing adbExec

### ISSUE THREAD

**Issue by avanishf** [appium/appium#9881]
## The problem

Trying to run an appium test in CI tool bitrise and seems to be throwing an issue : 
org.openqa.selenium.WebDriverException: 
An unknown server-side error occurred while processing the command. Original error: Error executing adbExec

## Environment

* Appium version (or git revision) that exhibits the issue: will always use the latest appium version (command in script is : npm install -g appium)
* Desktop OS/version used to run Appium: MacOS Sierra
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Android 8.0
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: CLI

## Details
------------------------------------------------------------------------------------
Following is the script in Bitrise which will try to run a sample UI test : 

    #!/bin/bash

    find / -name *.apk

    set -ex
    npm install -g npm@4.0.5
    npm install -g appium
    appium &>/dev/null &

    mvn -v

    adb devices

    sudo cp /bitrise/deploy/app-local* app/src/test/sniip-testing.apk
    sudo cp app/src/pom.xml /bitrise/src/pom.xml

    mvn test
--------------------------------------------------------------------------------------
But its fails giving an issue saying :  
org.openqa.selenium.WebDriverException: 
An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command '/opt/android-sdk-linux/platform-tools/adb -P 5037 -s emulator-5554 install /usr/lib/node_modules/appium/node_modules/appium-unlock/bin/unlock_apk-debug.apk' exited with code 1'; Stderr: 'adb: failed to install /usr/lib/node_modules/appium/node_modules/appium-unlock/bin/unlock_apk-debug.apk: cmd: Can't find service: package'; Code: '1' (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 1.53 seconds
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T18:33:54.468Z'
System info: host: 't20180102031245-br-cont-prod-c2-x--host-preboot-android-003', ip: '10.240.0.11', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-57-generic', java.version: '1.8.0_151'
Driver info: driver.version: AndroidDriver
	at com.sniip.androidapp.testCases.UX107Logout.userStory209LogoutTest.beforeMethod(userStory209LogoutTest.java:14)

## Link to Appium logs
https://gist.github.com/avanishf/612b6b899e0610d8cf909e234de58af9

## Code To Reproduce Issue [ Good To Have ]
As per the forums, I have set the capability "skipUnlock" to true but still didn't work

Code sample : 

    case "Android":
	try {
		DesiredCapabilities capabilities = new DesiredCapabilities();
		capabilities.setCapability("deviceName", "emulator-5554");
		capabilities.setCapability("platformVersion", "8.0");
		capabilities.setCapability("platformName", "Android");
		capabilities.setCapability("app", Paths.get(".").toAbsolutePath().normalize().toString() + apkPath);
		capabilities.setCapability("appPackage", "com.sniip.androidapp." + getAndroidEnvironmentProperties().replaceAll("\\s", ""));
		capabilities.setCapability("appActivity", "com.sniip.androidapp.activities.HomeActivity");
		capabilities.setCapability("noReset", true);
		capabilities.setCapability("skipUnlock", true);

		driver = new AndroidDriver<MobileElement>(new URL("http://0.0.0.0:4723/wd/hub"), capabilities);
		}

	catch (NoSuchElementException nse) {
		System.out.println("<<--APP NOT FOUND-->>" + nse.getMessage());
	}
		break;

**Comment by KazuCocoa** [comment]
@avanishf 

Could you check `/usr/lib/node_modules/appium/node_modules/appium-unlock/bin/unlock_apk-debug.apk` is exist correctly?

> + adb devices
> List of devices attached
> emulator-5554	device

We can see the above list in your attached log. So, the apk exists correctly, we can install it to the device, I think.

**Comment by avanishf** [comment]
Sry how do i check? bcos Bitrise will start its own Emulator in the CI environment?

**Comment by KazuCocoa** [comment]
How about running CI again and check the path with ls command, simply?

Sent from Astro <https://www.helloastro.com> for iOS


On Jan 2, 2018 at 14:26, avanishf <notifications@github.com> wrote:


Sry how do i check? bcos Bitrise will start its own Emulator in the CI
environment?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/appium/appium/issues/9881#issuecomment-354705099>, or mute
the thread

**Comment by mykola-mokhnach** [comment]
`skipUnlock` capability only works in the recent beta.

**Comment by avanishf** [comment]
ok this error seems to be solved on its own but now facing another issue -> #9898
