### ISSUE TITLE
using multiple sessions/drivers in parallel returns session does not exist

### ISSUE THREAD

**Issue by UtsavSaha** [appium/appium#9884]
I have this requirement where i need to launch my app in real device through a Url. 
Since get API does not work in iOS real device, i am trying to launch my app via another app which tries to launch the url.

Doing so requires two different sessions to maintain.
I install testApp . save its driver object and sessionID . 
Then install helperApp, launch it ,click on a button of the helper app using the current driver which launches my testApp. 
Then i try to click my testApp using previously saved driver object.
This returns session does not exist all though i can see the session presents in the /Sessions  API.

What can be a way forward to this?

**Comment by mykola-mokhnach** [comment]
You cannot have two sessions on a single device, but it is possible to have multiple applications in scope of a single session. Check https://github.com/appium/appium/issues/9883 for more details.
