### ISSUE TITLE
Final W3C Session Handling

### ISSUE THREAD

**Issue by imurchie** [appium/appium#9886]
Get appium/appium working with MJSONWP and W3C, once 1.7.2 is released.

**Comment by dpgraham** [comment]
Acceptance Criteria

* [ ] Publish W3C remediated appium-base-driver
* [ ] Test Appium locally with cURL/POSTMAN to verify that the W3C requests/responses are correct
* [ ] Publish W3C remediated Appium with W3C endpoint tests
