### ISSUE TITLE
WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not install app: 'Command 'ios-deploy --id

### ISSUE THREAD

**Issue by bbaitikova** [appium/appium#9900]
## The problem
I am not able to run IOS test: app is not installing on real device. When i just hit start test, it si failing with error: WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not install app: 'Command 'ios-deploy --id 480aee678e695b8624a0fa65cd68ff7d3ea4f7a3 --bundle /var/folders/6t/vcb74l411xn0st5x7xznjqrr009bn8/T/201802-559-1og5ncy.d3eh281tt9/Payload/test.app' exited with code 253'

I have installed latest Xcode. 

## Environment

* Appium version (or git revision) that exhibits the issue: Version 1.2.7 (1.2.7)
* Last Appium version that did not exhibit the issue (if applicable): it is first version i try to run test 
* Desktop OS/version used to run Appium: Mac Sierra 10.12.6 (16G29)
* Node.js version (unless using Appium.app|exe): v9.3.0
* Mobile platform/version under test: IOS 11
* Real device or emulator/simulator: Iphone X
* Appium CLI or Appium.app|exe:

ng in more detail.

## Link to Appium logs

Gist: <script src="https://gist.github.com/bbaitikova/b72ebe157eddafe5134eff73514ae038.js"></script>

    ```
```
def setUp(self):
        desired_caps = {
            'platformName': 'iOS',
            'platformVersion\n': "11.0.1",
            'deviceName': "iPhone X",
            'automationName': 'XCUITest',
            'app': self.mobile_app_md,
            'newCommandTimeout': 180,
            "autoGrantPermissions": True,
            "bundleId": "com.test.mushroom",
            # 'no-reset': False,
            'udid': '480aee678e695b8624a0fa65cd68ff7d3ea4f7a3'
```

        }

        self.driver = webdriver.Remote('http://127.0.0.1:4723/wd/hub', desired_caps)
        self.driver.implicitly_wait(100)

```

**Comment by mykola-mokhnach** [comment]
What is the output if you try to install the app manually using the command above? Have you tried to upgrade `ios-deploy` utility itself?

**Comment by bbaitikova** [comment]
i have latest version - 1.9.2
@mykola-mokhnach not clearly understand you by manually install app? can you please clarify ? i can install app from TestFlight

**Comment by bbaitikova** [comment]
I pre-installed app using TestFlight. Then run appium and it uninstalled my app from phone, then can not install. On simulator works fine, appium can install it. Am i missing something?

**Comment by bbaitikova** [comment]
@mykola-mokhnach  i uderstand what did you mean. I run command from Terminal and output is: ios-deploy[17839:193935] [ !! ] Error 0xe8008015: A valid provisioning profile for this executable was not found. AMDeviceSecureInstallApplication(0, device, url, options, install_callback, 0)

So, do you what is it?

**Comment by bbaitikova** [comment]
So well, i resolved my issue:
brew doctor and resolved all issues doctor listed. I had to brew link <package name>. 
And, app is installed. Appium is still failing, but it is different bug. 
Thanks. I am closing this one.
