### ISSUE TITLE
Calling AppiumDriver.findElements() not working on Appium beta 5

### ISSUE THREAD

**Issue by vjmaiky** [appium/appium#9902]
## The problem
Appium find element command is no longer working with beta5

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2 - beta5
* Last Appium version that did not exhibit the issue (if applicable): 1.7.2 - beta2
* Desktop OS/version used to run Appium: MacOS 10.12.6 (sierra)
* Node.js version (unless using Appium.app|exe): 8.5.0
* Mobile platform/version under test: iOS 10.3.3
* Real device or emulator/simulator: iPhone 6+

## Details
On appium find element (Calling AppiumDriver.findElements()) - element is no longer found 

## Link to Appium logs
[HTTP] --> POST /wd/hub/session/bb4c09a7-633c-4dc0-856d-7a54797ac745/elements {"value":"#Setup\\ Later","using":"css selector"}
[debug] [MJSONWP] Calling AppiumDriver.findElements() with args: ["css selector","#Setup\\ Later","bb4c09a7-633c-4dc0-856d-7a54797ac745"]
[debug] [XCUITest] Executing command 'findElements'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[HTTP] <-- POST /wd/hub/session/bb4c09a7-633c-4dc0-856d-7a54797ac745/elements 400 8 ms - 65 

## Code To Reproduce Issue [ Good To Have ]

```
 public void clickOn(By element) {
        try {
            waithelper.waitForElementVIsibilityIOS(element);
        } catch (WebDriverException e) {
            MyLogger.log.info(element + " element was not visible and wait command ran out of time");
        }

        Android.driverIos.findElement(element).click();
    }
```
```
    public void waitForElementVIsibilityIOS(By element) {
        FluentWait<IOSDriver> wait = new FluentWait<IOSDriver>(Android.driverIos).withTimeout(20, TimeUnit.SECONDS).ignoring(NoSuchElementException.class);
        wait.until(ExpectedConditions.visibilityOfElementLocated(element));
    }
```

**Comment by mykola-mokhnach** [comment]
Have you tried the recent java client (6.0.0-BETA2)?

**Comment by vjmaiky** [comment]
I'm using : compile group: 'io.appium', name: 'java-client', version: '6.0.0-BETA2'

Still not working.

**Comment by mykola-mokhnach** [comment]
Make sure that selenium API dependency is at 3.7.1+

**Comment by vjmaiky** [comment]
Somehow my gradle didn't built the new selenium. Closed.
