### ISSUE TITLE
Trying to interact iOS 11.X picker view with lots of items in it with Appium, crashes the app

### ISSUE THREAD

**Issue by tommirit** [appium/appium#9903]
## The problem

- Have a picker (UIPickerView) in view with lots of items in it, for example 400 items.
- Picker element can be found but if you try to interact with it, testable app crashes. 
- For example:
    ... setup driver ...
    iOSElement testPicker = driver.findElementById("testPicker");
    testPicker.click();
     ---> app crashes

- Can't be reproduced  with manual testing or if tested directly with xcode and xctest.
- Started to reproduce after updating devices to iOS 11.X.
- Doesn't reproduce if picker only has few items e.g 20.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Java-client 5.0.4
* Selenium-remote-driver 3.6.0
* Last Appium version that did not exhibit the issue (if applicable): -
* Desktop OS/version used to run Appium: OSX High Sierra 10.13.2 (17C88)
* Node.js version (unless using Appium.app|exe): v8.4.0
* Mobile platform/version under test: iOS 11.2.1
* Real device or emulator/simulator: iPhone 7 plus
* Appium CLI or Appium.app|exe:

## Link to Appium logs

Appium logs: https://gist.github.com/tommirit/bdec14703c5f9f55746916f6782d533b
App crash log:  https://gist.github.com/tommirit/05a39967ac7963b8308f49388e9f251d

## Code To Reproduce Issue [ Good To Have ]

- Test app can be any app with UIPickerView, viewcontroller example:  https://gist.github.com/tommirit/8741dcbebeec63092950bfa7f853f8df
- Java test example: https://gist.github.com/tommirit/18af3df056ad01b41c95ffc4d2525ca8
- When picker view is shown with lots of items in it, you just basically:
    driver = new IOSDriver<IOSElement>(new URL("http://0.0.0.0:4723/wd/hub"), capabilities); 
    iOSElement testPicker = driver.findElementById("testPicker");
   testPicker.click();

**Comment by mykola-mokhnach** [comment]
Please report to https://github.com/facebook/WebDriverAgent/issues
