### ISSUE TITLE
issue : An element could not be located on the page using the given search parameters

### ISSUE THREAD

**Issue by android1005** [appium/appium#9904]
## The problem

 An element could not be located on the page using the given search parameters

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Android
* Appium CLI or Appium.app|exe:

## Details
![2](https://user-images.githubusercontent.com/35072924/34529179-81591452-f0ee-11e7-83fd-10c781b89ff3.jpg)

i wanna click "전체 백업" but it doesn't works 

let me know what the problem is T ^ T

1. is there any wrong code?
2. should i use swicth kind of window_handler[] ?.......(it looks can't read the page where is now)

## Link to Appium logs
.................

## Code To Reproduce Issue [ Good To Have ]
here is Python code  

tc8 = driver.find_elements_by_class_name('android.widget.TextView')                   <--# it works 
    for elem in tc8:
        if elem.text == '대화 백업':
            elem.click()   

# but after click "대화백업" 
'전체 백업' doesn't works

tc9 = driver.find_elements_by_class_name('android.widget.Button')       
 for elem1 in tc9:
        if elem1.text == '전체 백업':
            elem1.click()

**Comment by mykola-mokhnach** [comment]
can you attach the output of page_source?

**Comment by android1005** [comment]
here is output one (but it's not a web)
i should have explained more detail sorry T ^ T

![1](https://user-images.githubusercontent.com/35072924/34547268-4ff2217a-f13d-11e7-91ea-9a451f9f985d.jpg)

**Comment by ochubey** [comment]
@android1005 why not to click on element found by id "common_setting_button_container"?

**Comment by android1005** [comment]
i solved it.  there was wrong thing

tc8 = driver.find_elements_by_class_name('android.widget.TextView') <--# it works
 for elem in tc8:
 if elem.text == '대화 백업':
elem.click()
break <---- i found that can't escape this logic so i use "break" 

then fine.......

thx for you guys favor
