### ISSUE TITLE
Appium gui TouchAction in ruby

### ISSUE THREAD

**Issue by matanmoda** [appium/appium#9905]
## The problem

When working with the inspector and recording actions, trying to swipe by coordinates preforms a swipe but the recording is wrong.
* When copying the code the TouchAction needs to be recorded as Appium::TouchAction and not just TouchAction.
* In ruby the correct way to perform the moveTo action is with .move_to  and not .moveTo
* The coordinates in .move_to should be recorded like this .move_to({x:0 , y: 0}) and not as sym vars.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.2.7
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac 10.13.2 High 
* Node.js version (unless using Appium.app|exe): 9.0.0
* Mobile platform/version under test: iPhone 8 Plus 11.2
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe: .app

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Please report to https://github.com/appium/appium-desktop/issues
