### ISSUE TITLE
Appium gui records ruby with find_elements and not find_element

### ISSUE THREAD

**Issue by matanmoda** [appium/appium#9906]
## The problem
When using the appium inspector and recording actions, all elements recorded are added as driver.find_elements(some element). This creates a bug since all actions can only target one element. 
This is resolved only by adding [0] to each element of removing the 's' so I get only the first element found.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.2.7
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: 10.3.2 High
* Node.js version (unless using Appium.app|exe): 9.0.0
* Mobile platform/version under test: iPhone 8 Plus v 11.2
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe: .app

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Please report to https://github.com/appium/appium-desktop/issues
