### ISSUE TITLE
Tapping by coordinates not working correctly

### ISSUE THREAD

**Issue by BoazWarshawsky** [appium/appium#9908]
## The problem
I am trying to perform very simple tap action by coordinates. 
The api that I am using for that is: 
self.driver.tap([(0, 32)], duration)

You can assume that in the **absolute** position of (0, 32) there is a button that once I trigger it with my finger something happens. 

## Environment

* Appium version: v1.7.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS High Sierra.
* Node.js version (unless using Appium.app|exe):v6.11.4
* Mobile platform/version under test: iOS 11.1.2
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs
https://github.com/BoazWarshawsky/iOSAutomationAgent/blob/master/appium.log

## Code To Reproduce Issue 
self.driver.tap([(0, 32)], duration)

**Comment by mykola-mokhnach** [comment]
I don't see any problems in the log. Try to change the coordinates or use relative coordinates instead of absolute.
