### ISSUE TITLE
The element is visual in NATIVE_APP context, but can not be found using any locator strategies，please help me.

### ISSUE THREAD

**Issue by WenRui13** [appium/appium#9909]
## The problem
Hi,
The element is visual in NATIVE_APP context, but can not be found using any locator strategies，please help me.
Condition failed with Exception:

wait.until(ExpectedConditions.presenceOfElementLocated(MobileBy.id("com.jd.oa:id/iv_shake_icon")))
|    |                        |                                 |
|    |                        |                                 By.id: com.jd.oa:id/iv_shake_icon
|    |                        presence of element located by: By.id: com.jd.oa:id/iv_shake_icon
|    org.openqa.selenium.TimeoutException: Timed out after 5 seconds waiting for presence of element located by: By.id: com.jd.oa:id/iv_shake_icon

## Environment
Capabilities [{appPackage=com.jd.oa, noReset=true, deviceName=5LM0216117013394, uuid=5LM0216117013394, ignoreUnimportantViews=true, platform=LINUX, deviceUDID=5LM0216117013394, desired={appPackage=com.jd.oa, noReset=true, deviceName=Mate8, uuid=5LM0216117013394, ignoreUnimportantViews=true, appActivity=com.jd.oa.StartupActivity, newCommandTimeout=10, platformVersion=7.0, browserName=, autoGrantPermissions=true, unicodeKeyboard=true, platformName=Android, resetKeyboard=true}, newCommandTimeout=10, platformVersion=7.0, webStorageEnabled=false, takesScreenshot=true, browserName=, javascriptEnabled=true, unicodeKeyboard=true, platformName=Android, deviceManufacturer=HUAWEI, resetKeyboard=true, deviceScreenSize=1080x1920, networkConnectionEnabled=true, warnings={}, databaseEnabled=false, appActivity=com.jd.oa.StartupActivity, locationContextEnabled=false, autoGrantPermissions=true, deviceModel=HUAWEI NXT-AL10}]

info AppiumDoctor Appium Doctor v.1.4.3
info AppiumDoctor ### Diagnostic starting ###
info AppiumDoctor  ✔ The Node.js binary was found at: C:\Program Files\nodejs\no
de.exe
info AppiumDoctor  ✔ Node version is 8.9.1
info AppiumDoctor  ✔ ANDROID_HOME is set to: D:\android-sdk\sdk
info AppiumDoctor  ✔ JAVA_HOME is set to: C:\Program Files\Java\jdk1.8.0_102
info AppiumDoctor  ✔ adb exists at: D:\android-sdk\sdk\platform-tools\adb.exe
info AppiumDoctor  ✔ android exists at: D:\android-sdk\sdk\tools\android.bat
info AppiumDoctor  ✔ emulator exists at: D:\android-sdk\sdk\tools\emulator.exe
info AppiumDoctor  ✔ Bin directory of %JAVA_HOME% is set
info AppiumDoctor ### Diagnostic completed, no fix needed. ###
info AppiumDoctor
info AppiumDoctor Everything looks good, bye!
info AppiumDoctor

my code is：
       given:
        def width = driver.findElementById("lock_pattern").size.width
        def height = driver.findElementById("lock_pattern").size.height

        def x = driver.findElementById("lock_pattern").center.x
        def y = driver.findElementById("lock_pattern").center.y

        def multiTouchAction = new MultiTouchAction(driver)
        def touchAction = new TouchAction(driver)
                .press(ri(x - width / 3), y)
                .moveTo(ri(width / 3), 0)
                .moveTo(ri(width / 3), 0)
                .moveTo(ri(-width * 2 / 3), ri(height / 3))
                .release()
        when:
        multiTouchAction.add(touchAction).perform()
        then:
        driver.findElementById("signin").isDisplayed()
        driver.findElementByAndroidUIAutomator("""new UiSelector().text("应用")""").click()
        driver.findElementByAndroidUIAutomator("""new UiSelector().text("会议室")""").click()

        wait.until(ExpectedConditions.presenceOfElementLocated(MobileBy.id("com.jd.oa:id/iv_shake_icon")))
//        driver.contextHandles.each { println it}

        driver.findElementById("com.jd.oa:id/search_button").isDisplayed()
        driver.findElementByAndroidUIAutomator("""new UiSelector().text("我的关注")""").isDisplayed()

**Comment by mykola-mokhnach** [comment]
Please provide full server log and the output of page source command

**Comment by WenRui13** [comment]
appium log：
[HTTP] --> POST /wd/hub/session/a03d2a43-ba17-46da-916e-1f535e25d5c9/element {"u
sing":"id","value":"com.jd.oa:id/iv_shake_icon"}
[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["id","com.jd.oa
:id/iv_shake_icon","a03d2a43-ba17-46da-916e-1f535e25d5c9"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class
 name, accessibility id, -android uiautomator
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class
 name, accessibility id, -android uiautomator
[debug] [BaseDriver] Waiting up to 5000 ms for condition
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":
"find","params":{"strategy":"id","selector":"com.jd.oa:id/iv_shake_icon","contex
t":"","multiple":false}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":
"action","action":"find","params":{"strategy":"id","selector":"com.jd.oa:id/iv_s
hake_icon","context":"","multiple":false}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: find
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding 'com.jd.oa:id/iv_shak
e_icon' using 'ID' with the contextId: '' multiple: false
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[INSTANCE=0,
 RESOURCE_ID=com.jd.oa:id/iv_shake_icon]
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Failed to locate element. Cle
aring Accessibility cache and retrying.
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding 'com.jd.oa:id/iv_shak
e_icon' using 'ID' with the contextId: '' multiple: false
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[INSTANCE=0,
 RESOURCE_ID=com.jd.oa:id/iv_shake_icon]
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":7
,"value":"No element found"}
[debug] [AndroidBootstrap] Received command result from bootstrap
[HTTP] <-- POST /wd/hub/session/a03d2a43-ba17-46da-916e-1f535e25d5c9/element 500
 9095 ms - 164
[HTTP] --> DELETE /wd/hub/session/a03d2a43-ba17-46da-916e-1f535e25d5c9 {}
[debug] [MJSONWP] Calling AppiumDriver.deleteSession() with args: ["a03d2a43-ba1
7-46da-916e-1f535e25d5c9"]
[debug] [BaseDriver] Event 'quitSessionRequested' logged at 1515058996731 (17:43
:16 GMT+0800 (中国标准时间))
[Appium] Removing session a03d2a43-ba17-46da-916e-1f535e25d5c9 from our master s
ession list
[debug] [AndroidDriver] Shutting down Android driver

**Comment by KazuCocoa** [comment]
- What about the result of `getPageSource`?
- What about using `automationName="uiautomator2"`?

**Comment by WenRui13** [comment]
@See("https://appium.readthedocs.io/en/stable/en/writing-running-appium/caps/")
    private void completeAppCaps(DesiredCapabilities caps, String appPackage, String appActivity) {
        caps.setCapability("appPackage", appPackage)
        caps.setCapability("appActivity", appActivity)
        caps.setCapability("automationName", "UiAutomator2")
        caps.setCapability("ignoreUnimportantViews", "true")
        caps.setCapability("autoGrantPermissions", "true")
        caps.setCapability("unicodeKeyboard", "true")
        caps.setCapability("resetKeyboard", "true")
        caps.setCapability("noReset", "true")
        caps.setCapability("newCommandTimeout", "10")
    }

automationName="uiautomator2" is ok
