### ISSUE TITLE
Not able to locate UI elements in CI

### ISSUE THREAD

**Issue by avanishf** [appium/appium#9911]
## The problem
After integrating appium tests in CI (after encountering plenty of issues) , i was able to run a sample login test but the problem is that the test fails bcos its not able to find the password field to enter the password (the test runs absolutely fine locally). I tried putting some sleep() between username & password field commands and also tried to get the pagesource (driver.getPageSource()) and it seems that the UI element is pretty much present in the XML but is not able to locate the element.
Here is the test what its trying to do : 
a. click on login button (works)
b. enter username field (works)
c. doesn't find password field 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2-beta2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MacOS Sierra
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Android 5.1
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: CLI

## Details
After some trial & error : 
1. It seems it is able to interact with button elements but when it comes to text element (like password field), it doesn't seem to identify  (except the username , maybe bcos the cursor is present in the username by default).
2. also i don't think the android sim keyboard is hiding the view of the password as the bottom login button which validate the login credentials is also displayed (tried isDisplayed()). 

## Link to Appium logs
[Appium logs](https://gist.github.com/avanishf/20f18da389313aa7c437fc1f27697631)

## Code To Reproduce Issue [ Good To Have ]

Sample test code to test : 
    
    @Test
    public void validLogout() throws Exception {
        LoginScreen loginScreen = new LoginScreen(driver);
        loginScreen.loginButton.click();
        loginScreen.loginWithMobileOrEmail.click();  
        loginScreen.username.sendKeys("abc@abc.com");
        loginScreen.password.sendKeys("Aa1234");  // Doesn't locate the respective element
     }

UI locator for the password field is : `com.sniip.androidapp.local2:id/et_log_in_pw`

Locator definition :

    public final static String ENV_PACKAGE = "com.sniip.androidapp";
    
    @AndroidFindAll({ 
    @AndroidBy(id = ENV_PACKAGE + ".local2:id/tv_log_in"),
    @AndroidBy(id = ENV_PACKAGE + ".uat2:id/tv_log_in") 
    })
    public MobileElement loginButton;

    @AndroidFindAll({
    @AndroidBy(id = ENV_PACKAGE + ".local2:id/et_email_or_mobile_number"),
    @AndroidBy(id = ENV_PACKAGE + ".uat2:id/et_email_or_mobile_number")
    })
    public MobileElement username;

    @AndroidFindAll({
    @AndroidBy(id = ENV_PACKAGE + ".local2:id/et_log_in_pw"),
    @AndroidBy(id = ENV_PACKAGE + ".uat2:id/et_log_in_pw")
    })
    public MobileElement password;
  
Snapshot of the above Appium logs : 
    Not able to locate element, returns with status 7 , saying no element found

    Finding 'com.sniip.androidapp.local2:id/et_log_in_pw' using 'ID' with the contextId: '' multiple: 
    false
    [debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[INSTANCE=0, 
    RESOURCE_ID=com.sniip.androidapp.local2:id/et_log_in_pw]
    [debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Failed to locate element. Clearing 
    Accessibility cache and retrying.
    [debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding 
    'com.sniip.androidapp.local2:id/et_log_in_pw' using 'ID' with the contextId: '' multiple: false
    [debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[INSTANCE=0, 
    RESOURCE_ID=com.sniip.androidapp.local2:id/et_log_in_pw]
    [debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":7,"value":"No 
    element found"}

**Comment by mykola-mokhnach** [comment]
The attached log is pretty useless. 
Regarding the problem - try to print the page source exactly at the same moment when you try to locate the field to make sure it's there. Also, you could  try to switch the backend to uiautomator2.

**Comment by avanishf** [comment]
I tried running a pageSource() on the same page after entering the username : 
Make sure its on the same app page its trying to access the pagesource -
1. enter username
2. pageSource command
3. enter password . --> script fails here

so this way, you get the pageSource in console before the script fails on 3rd step.

After following ur suggesstion, i set the `automationName` desiredCapability to  `uiautomator2` and after running 3 builds in CI , i got ranging issues.
1st & 3rd build gave the same issue -> [log](https://gist.github.com/avanishf/c5f5e795e3fb75e26a04ae8eba38a009 ) . <appium issue?>
2nd build couldn't find the button element but was able to locate the same element earlier before setting the `automationName` ([build 2 log](https://gist.github.com/avanishf/a5514c967cbf402922d5f6e445b6318b)) :
      
    loginScreen.loginButton.click();
    loginScreen.loginWithMobileOrEmail.click();  //Fails here after setting automationName cap
    loginScreen.username.sendKeys("0478732847");
    loginScreen.password.sendKeys("Sniip1412");

**Comment by mykola-mokhnach** [comment]
like I said above these logs are pointless, since they don't contain the actual server output

**Comment by avanishf** [comment]
not sure why you say that, i believe these are the server logs from appium (ran a latest CI build, i have trimmed down the logs to only which is relevant) : [Appium server log](https://gist.github.com/avanishf/75e7fbfd0d6bad6c0b0f58028cd8c9a9)

**Comment by avanishf** [comment]
Ok seems the above issue is also solved now but again not able to find password field element : [Appium server log only](https://gist.github.com/avanishf/d057e32f209f07568ac6f9e35d30f71f)

**Comment by mykola-mokhnach** [comment]
Can you also attach the output of getPageSource command before locating the element? Perhaps, it's just not there?

**Comment by avanishf** [comment]
Check line no. 443 , cope paste in your notepad and find with a substring saying `et_log_in_pw`

**Comment by mykola-mokhnach** [comment]
```xml
<?xml version="1.0" encoding="UTF-8"?><hierarchy rotation="0"><android.widget.FrameLayout index="0" text="" class="android.widget.FrameLayout" package="com.sniip.androidapp.local2" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][240,390]" resource-id="" instance="0"><android.widget.LinearLayout index="0" text="" class="android.widget.LinearLayout" package="com.sniip.androidapp.local2" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][240,390]" resource-id="" instance="0"><android.widget.FrameLayout index="0" text="" class="android.widget.FrameLayout" package="com.sniip.androidapp.local2" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,19][240,205]" resource-id="" instance="1"><android.widget.LinearLayout index="0" text="" class="android.widget.LinearLayout" package="com.sniip.androidapp.local2" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,19][240,205]" resource-id="com.sniip.androidapp.local2:id/action_bar_root" instance="1"><android.widget.FrameLayout index="0" text="" class="android.widget.FrameLayout" package="com.sniip.androidapp.local2" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,19][240,205]" resource-id="android:id/content" instance="2"><android.view.View index="0" text="" class="android.view.View" package="com.sniip.androidapp.local2" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,19][240,205]" resource-id="" instance="0"><android.widget.TextView index="0" text="Cancel" class="android.widget.TextView" package="com.sniip.androidapp.local2" content-desc="" checkable="false" checked="false" clickable="true" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[12,31][46,46]" resource-id="com.sniip.androidapp.local2:id/tv_cancel_log_in_email_or_mobile_number" instance="0"/><android.widget.ScrollView index="1" text="" class="android.widget.ScrollView" package="com.sniip.androidapp.local2" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="true" focused="false" scrollable="true" long-clickable="false" password="false" selected="false" bounds="[0,46][240,175]" resource-id="" instance="0"><android.view.View index="0" text="" class="android.view.View" package="com.sniip.androidapp.local2" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[12,46][228,175]" resource-id="com.sniip.androidapp.local2:id/lo_body" instance="1"><android.widget.TextView index="0" text="Log in" class="android.widget.TextView" package="com.sniip.androidapp.local2" content-desc="" checkable="false" checked="false" clickable="true" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[12,58][46,76]" resource-id="com.sniip.androidapp.local2:id/tv_title_log_in" instance="1"/><android.widget.LinearLayout index="1" text="Email or mobile number" class="android.widget.LinearLayout" package="com.sniip.androidapp.local2" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[12,112][228,154]" resource-id="com.sniip.androidapp.local2:id/til_email_or_mobile_number" instance="2"><android.widget.FrameLayout index="0" text="" class="android.widget.FrameLayout" package="com.sniip.androidapp.local2" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[12,122][228,154]" resource-id="" instance="3"><android.widget.EditText index="0" text="0478732847" class="android.widget.EditText" package="com.sniip.androidapp.local2" content-desc="" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="true" scrollable="false" long-clickable="true" password="false" selected="false" bounds="[12,122][228,154]" resource-id="com.sniip.androidapp.local2:id/et_email_or_mobile_number" instance="0"/></android.widget.FrameLayout></android.widget.LinearLayout></android.view.View></android.widget.ScrollView><android.widget.TextView index="2" text="Log In" class="android.widget.TextView" package="com.sniip.androidapp.local2" content-desc="" checkable="false" checked="false" clickable="true" enabled="false" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,175][240,205]" resource-id="com.sniip.androidapp.local2:id/tv_log_in" instance="2"/></android.view.View></android.widget.FrameLayout></android.widget.LinearLayout></android.widget.FrameLayout></android.widget.LinearLayout></android.widget.FrameLayout></hierarchy>
```

This is what in the string and I am unable to find the substring `et_log_in_pw` there

**Comment by avanishf** [comment]
yes, i am sorry dude.  I had to take my statement back. I m not sure but it seems i was referring to the wrong XML structure and based on that i said that the element is present in the structure but obviously the one u posted above is correct, i fetched the same pageSource output and i agree the element is not present which explains the problem! Thank you , i think if i had debugged properly this would have saved your & mine time. But now i need to talk to the team as why the element is not detected. Anyways thanks
