### ISSUE TITLE
1.7.2 is over 300MB larger than 1.7.1

### ISSUE THREAD

**Issue by tonyhignett** [appium/appium#9912]
## The problem

`npm install appium@1.7.2` results in 682MB of stuff, compared to 368MB for 1.7.1. This is quite inconvenient for distributing appium to many servers

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable): 1.7.1
* Desktop OS/version used to run Appium: macOS 10.13
* Node.js version (unless using Appium.app|exe): 9.3.0
* Mobile platform/version under test: iOS 11
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: CLI

## Details

The increase is mostly accounted for by about 50 copies of `core-js` inside various `babel-*` packages.

I'm not sure whether this qualifies as an issue, but maybe something's gone wrong with the build process?

## Link to Appium logs

N/A

## Code To Reproduce Issue [ Good To Have ]

N/A

**Comment by imurchie** [comment]
Hmmm. I will take a look. We had made a concerted effort to go the other direction!

**Comment by imurchie** [comment]
Unfortunately, the problem is with the dependencies. We use npm shrinkwrap to lock dependencies, and npm now rewrites that file during local install. So when it was published, unbeknownst to us, all the development dependencies got in.

**Luckily**, you can use the `--production` flag to skip those.
```
$ npm install appium@1.7.2
$ cd node_modules
$ du -hs * | gsort -h                                                                                                          6.12.0
476K	nan
9.9M	fsevents
680M	appium
```
```
$ npm install appium@1.7.2 --production
$ cd node_modules
$ du -hs * | gsort -h 
476K	nan
9.9M	fsevents
188M	appium
```

**Comment by tonyhignett** [comment]
Thanks for the quick response.

Mysteriously, if I run `npm install appium@1.7.2 --production` with npm 5.6.0 (the latest version, and the version I want to use), I get no reduction in size. I do get the reduction with npm 3.10.10. Maybe npm changed something; I'll investigate.

**Comment by imurchie** [comment]
Not sure why npm 5 does this. Argh.

Are you installing once, bundling, and then moving the bundle around? If so the following works

```
$ node --version
v8.9.3
$ npm --version
5.6.0
$ npm install appium @1.7.2
// lots of output
$ cd node_modules/appium
$ npm prune --production

> pre-commit@1.2.2 uninstall node_modules/pre-commit
> node uninstall.js

removed 843 packages in 34.346s
$ cd ..
$ du -hs * | gsort -h
476K	nan
9.4M	fsevents
184M	appium
```

**Comment by tonyhignett** [comment]
Seems `npm install` is not very functional in version 5. There are all sorts of issues about various flags not working. I've found that passing `--no-shrinkwrap` as well as `--production` is also a workaround.

**Comment by imurchie** [comment]
Yes, it seems so.

The problem with using `--no-shrinkwrap` is that any changes to dependencies that are within SemVer will be used. This should not actually be a problem unless someone published a package badly (e.g., with a breaking change in a patch release or something).

**Comment by imurchie** [comment]
1.7.2:
677M	node_modules

1.8.0:
176M	node_modules
