### ISSUE TITLE
Unable to start WebDriverAgent session because of xcodebuild failure: "Cannot read property 'push' of undefined"

### ISSUE THREAD

**Issue by waynema** [appium/appium#9917]
## The problem

[MJSONWP] Encountered internal error running command: Error: Unable to start WebDriverAgent session because of xcodebuild failure: "Cannot read property 'push' of undefined". when starting my ruby appium tests

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable): 1.7.1
* Desktop OS/version used to run Appium: MacOS 10.13.2
* Node.js version (unless using Appium.app|exe): v9.3.0
* Mobile platform/version under test: iOS 11.0
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: CLI

## Details
I am stuck with this Unable to start WebDriverAgent session because of xcodebuild failure: "Cannot read property 'push' of undefined". error and cannot proceed further after upgrading to 1.7.2

## Link to Appium logs

https://gist.github.com/waynema/495a320b14d12143e56c8f3472321874

**Comment by dpgraham** [comment]
Looks like a JS error. It's parsing `processArguments` incorrectly and is 'pushing' variables to an empty array.

See `args.push` below:

```javascript
// driver.js
 async startWdaSession (bundleId, processArguments) {
    let args = processArguments ? processArguments.args : [];
    let env = processArguments ? processArguments.env : {};

    let shouldWaitForQuiescence = util.hasValue(this.opts.waitForQuiescence) ? this.opts.waitForQuiescence : true;
    let maxTypingFrequency = util.hasValue(this.opts.maxTypingFrequency) ? this.opts.maxTypingFrequency : 60;
    let shouldUseSingletonTestManager = util.hasValue(this.opts.shouldUseSingletonTestManager) ? this.opts.shouldUseSingletonTestManager : true;
    let shouldUseTestManagerForVisibilityDetection = false;
    if (util.hasValue(this.opts.simpleIsVisibleCheck)) {
      shouldUseTestManagerForVisibilityDetection = this.opts.simpleIsVisibleCheck;
    }
    if (!isNaN(parseFloat(this.opts.platformVersion)) && parseFloat(this.opts.platformVersion).toFixed(1) === '9.3') {
      log.info(`Forcing shouldUseSingletonTestManager capability value to true, because of known XCTest issues under 9.3 platform version`);
      shouldUseTestManagerForVisibilityDetection = true;
    }
    if (util.hasValue(this.opts.language)) {
      args.push('-AppleLanguages', `(${this.opts.language})`);
      args.push('-NSLanguages', `(${this.opts.language})`);
    }

    if (util.hasValue(this.opts.locale)) {
      args.push('-AppleLocale', this.opts.locale);
    }

    let desired = {
      desiredCapabilities: {
        bundleId,
        arguments: args,
        environment: env,
        shouldWaitForQuiescence,
        shouldUseTestManagerForVisibilityDetection,
        maxTypingFrequency,
        shouldUseSingletonTestManager,
      }
    };

    await this.proxyCommand('/session', 'POST', desired);
  }
```

This would happen if `processArguments` had a`.arg` property that was 'truthy' and isn't an array.

@waynema What capabilities are you setting? Is `processArguments` one of those capabilities?

**Comment by waynema** [comment]
yes,  I did define this in the env.rb file
caps[:caps][:processArguments] = '{ "env": { "UITestingMode": "true", "UITestingLocaleIdentifier": "' + lang_env + '" }}'

**Comment by dpgraham** [comment]
As a workaround, can you try setting it to:

```python
caps[:caps][:processArguments] = '{ "args": [], "env": { "UITestingMode": "true", "UITestingLocaleIdentifier": "' + lang_env + '" }}'
```

...and see if that fixes it?

**Comment by waynema** [comment]
Not quite working.  It just timeout and fails.  Logs says it failed to create WDA session. Retrying...,  though I don't see the original error anymore.

**Comment by dpgraham** [comment]
What's the new error?

Also, can you see what happens if you exclude `processArguments`?

**Comment by waynema** [comment]
@dpgraham ,  the workaround did seem to work. ( I probably have another simulator running thus failing the first time).

**Comment by dpgraham** [comment]
Okay great.

I'm still going to leave this  issue open because I'd still like to patch it so that we don't have to provide `"args": []` in the `processArguments`.

**Comment by mykola-mokhnach** [comment]
It is a simple fix, I'll take care about it.
