### ISSUE TITLE
Error when calling get_window_rect on iOS real device with XCUITest Driver

### ISSUE THREAD

**Issue by bubblegreen** [appium/appium#9919]
## The problem

When calling get_window_rect method, it raise "WebDriverException: Message: Method has not yet been implemented".
Dose XCUITest support this method? Or I miss something?

## Environment

* Appium version : 1.7.1
* Desktop OS/version used to run Appium: macOS High Sierra 10.13.2
* Node.js version : 9.3.0
* Mobile platform/version under test: iOS 11.2.1
* Real device: iPhone 6
* Appium CLI

## part of desired_capabilities
platformName = iOS
automationName = XCUITest
platformVersion = 11.2
deviceName = iPhone 6
newCommandTimeout = 60

## Appium logs

[debug] [MJSONWP] Calling AppiumDriver.getWindowRect() with args: ["861b352c-ce0e-4214-a94b-40b7af9fbd0f"]
[debug] [XCUITest] Executing command 'getWindowRect'
[HTTP] <-- GET /wd/hub/session/861b352c-ce0e-4214-a94b-40b7af9fbd0f/window/rect 400 2 ms - 35 
[debug] [XCUITest] Connection to WDA timed out
[debug] [iProxy] recv failed: Operation not permitted

## Code To Reproduce Issue 
driver = webdriver.Remote(command_executor='http://0.0.0.0:4723/wd/hub', desired_capabilities=config)
driver.get_window_rect()

**Comment by mykola-mokhnach** [comment]
yep, this method is not supported. However one can use `driver.manage.window.size()` endpoint to get screen dimensions.

**Comment by bubblegreen** [comment]
@mykola-mokhnach 
I use python, and the WebDriver has no attribute 'manage'.
Is there any other solution?
thank you.

**Comment by mykola-mokhnach** [comment]
I don't know the exact name of the python endpoint. Try to ask on Appium forum
