### ISSUE TITLE
Unable to install peertalk dependency via carthage using bootstrap.sh

### ISSUE THREAD

**Issue by asnaith** [appium/appium#9920]
## The problem

I'm using Appium 1.72 and I am getting Xcode build 65 errors when Appium tries to build and install WDA. 

I wanted to see if I could build the webdriver agent via xcode to rule it being a provisioning profile error but I can't even get that far. 

However, when I tried to run the boostrap.sh file I see the following error when trying to download peertalk

`./Scripts/bootstrap.sh -d
Fetching dependencies
*** Downloading RoutingHTTPServer.framework binary at "v1.0.1"
*** Checking out peertalk at "v1.0"
*** Fetching peertalk
A shell task (/usr/bin/env git fetch --prune --quiet https://github.com/marekcirkos/peertalk.git refs/tags/*:refs/tags/* +refs/heads/*:refs/heads/* (launched in /Users/qa_auto/Library/Caches/org.carthage.CarthageKit/dependencies/peertalk)) failed with exit code 128:
fatal: could not read Username for 'https://github.com': terminal prompts disabled`

I looked at the Cartfile and it seems as if it's having a problem with this part

`# Used for USBOverHTTP
github "marekcirkos/peertalk"`

(FWIW if looks like that user doesn't have a public repo under that name, so not sure if this is the real issue)? 

I was using Carthage version 0.27 but I also tried 0.26 and 0.25 with no luck too. 

## Environment

* Using the bootstrap.sh file that comes with Appium 1.72
* Desktop OS/version used to run Appium:
MacOS Sierra
* Node.js version (unless using Appium.app|exe):
v6.11.3

* Mobile platform/version under test:
iOS (10.3.3)

* Real device or emulator/simulator:
Real device
* Appium CLI or Appium.app|exe:
CLI

## Link to Appium logs

Here's the log with xcodeShowLog turned on, I'm assuming that ultimately the WDA installation is only failing because of it not being able to run the bootstrap script?  

https://gist.github.com/asnaith/f0a922ff6df6b534d8d1cec45ce6161f

**Comment by mykola-mokhnach** [comment]
Peertalk dependency has been excluded from WebDriverAgent a while ago. Make sure that WDA sources are updated properly after new Appium version is installed. You could reboot the computer, uninstall Appium completely and only after that install the new version to make sure there are no leftovers..

**Comment by asnaith** [comment]
@mykola-mokhnach Thanks for the reply, I did a fresh installation on a new machine and noticed the cartfile was only containing one dependency. I completely cleaned my old installation and this time I got the new cartfile without the peertalk dependency and after that I could build and deploy WDA
