### ISSUE TITLE
Application Installation fail in appium  1.7 version

### ISSUE THREAD

**Issue by Amittallewar** [appium/appium#9922]
Required capabilities are set with respect to Android.
## Link to Appium logs
https://gist.github.com/Amittallewar/3b04bf32d0edf7e82af9a371a3000ab2
 
I have also tried after uninstalling the application from the device but facing the same issue.

please let me know if you need more information

**Comment by imurchie** [comment]
You have uninstalled the unlock app and this continues?

**Comment by Amittallewar** [comment]
yes it is continue after the unlock
