### ISSUE TITLE
URL did not map to a valid JSONWP resource

### ISSUE THREAD

**Issue by Amittallewar** [appium/appium#9923]
## The problem
when I try to access 127.0.0.1/wd/hub output is below and doesn't make sense - have tried changing ports as well and same results
URL did not map to a valid JSONWP resource

when I try to access 127.0.0.1/wd/hub/status the output is below and seems to be ok
{"status":0,"value":{"build":{"version":"1.2.4","revision":"71584425ecf777349e3215f0f18e71e7782acfb6"}}}

when I try to access 127.0.0.1/wd/hub/session the output is below and makes sense as no capability is set
{"status":13,"value":"ERROR running Appium command: Cannot read property 'capabilities' of null"}

Any ideas on how to resolve this or is it a bug/issue??

Thanks

**Comment by imurchie** [comment]
* `127.0.0.1/wd/hub` - Appium doesn't do anything for this url. The output is indicating a 404 error, essentially.
* `127.0.0.1/wd/hub/status` - this is a valid url, giving the server's status
* `127.0.0.1/wd/hub/session` (GET) - this is not a valid url. Appium doesn't do anything for this.
* `127.0.0.1/wd/hub/session` (POST) - this creates a session. Appium expects `capabilities` to be part of the payload.

For the routes that Appium handles, and the parameters expected, you can check out https://github.com/appium/appium-base-driver/blob/master/lib/mjsonwp/routes.js

**Comment by Amittallewar** [comment]
Thanks
