### ISSUE TITLE
TouchAction  chaining can not work in uiautomator2

### ISSUE THREAD

**Issue by WenRui13** [appium/appium#9924]
## The problem

TouchAction  chaining can not work in uiautomator2

## Environment
[{appPackage=com.jd.oa, noReset=true, deviceName=Mate8, uuid=5LM0216117013394, ignoreUnimportantViews=true, platform=ANY, appActivity=com.jd.oa.StartupActivity, newCommandTimeout=10, platformVersion=7.0, automationName=uiautomator2, browserName=, autoGrantPermissions=true, unicodeKeyboard=true, platformName=Android, resetKeyboard=true}]

info AppiumDoctor Appium Doctor v.1.4.3
info AppiumDoctor ### Diagnostic starting ###
info AppiumDoctor  ✔ The Node.js binary was found at: C:\Program Files\nodejs\no
de.exe
info AppiumDoctor  ✔ Node version is 8.9.1
info AppiumDoctor  ✔ ANDROID_HOME is set to: D:\android-sdk\sdk
info AppiumDoctor  ✔ JAVA_HOME is set to: C:\Program Files\Java\jdk1.8.0_102
info AppiumDoctor  ✔ adb exists at: D:\android-sdk\sdk\platform-tools\adb.exe
info AppiumDoctor  ✔ android exists at: D:\android-sdk\sdk\tools\android.bat
info AppiumDoctor  ✔ emulator exists at: D:\android-sdk\sdk\tools\emulator.exe
info AppiumDoctor  ✔ Bin directory of %JAVA_HOME% is set
info AppiumDoctor ### Diagnostic completed, no fix needed. ###
info AppiumDoctor
info AppiumDoctor Everything looks good, bye!
info AppiumDoctor

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

omator","new UiSelector().text(\"会议室\")","5febcf18-2b96-4ca9-9330-5bbce34f80d
c"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class
 name, accessibility id, -android uiautomator
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class
 name, accessibility id, -android uiautomator
[debug] [BaseDriver] Waiting up to 5000 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8202/w
d/hub/session/4f2f518c-ca6f-4ada-84be-fdfddc15a863/element] with body: {"strateg
y":"-android uiautomator","selector":"new UiSelector().text(\"会议室\")","contex
t":"","multiple":false}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"4f2f518c-ca6f
-4ada-84be-fdfddc15a863","status":0,"value":{"ELEMENT":"4b2f2ab2-e594-4ea9-b769-
d0c284822018"}}
[debug] [MJSONWP] Responding to client with driver.findElement() result: {"ELEME
NT":"4b2f2ab2-e594-4ea9-b769-d0c284822018"}
[HTTP] <-- POST /wd/hub/session/5febcf18-2b96-4ca9-9330-5bbce34f80dc/element 200
 124 ms - 122
[HTTP] --> POST /wd/hub/session/5febcf18-2b96-4ca9-9330-5bbce34f80dc/element/4b2
f2ab2-e594-4ea9-b769-d0c284822018/click {"id":"4b2f2ab2-e594-4ea9-b769-d0c284822
018"}
[debug] [MJSONWP] Calling AppiumDriver.click() with args: ["4b2f2ab2-e594-4ea9-b
769-d0c284822018","5febcf18-2b96-4ca9-9330-5bbce34f80dc"]
[debug] [JSONWP Proxy] Proxying [POST /element/4b2f2ab2-e594-4ea9-b769-d0c284822
018/click] to [POST http://localhost:8202/wd/hub/session/4f2f518c-ca6f-4ada-84be
-fdfddc15a863/element/4b2f2ab2-e594-4ea9-b769-d0c284822018/click] with body: {"e
lement":"4b2f2ab2-e594-4ea9-b769-d0c284822018"}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"4f2f518c-ca6f
-4ada-84be-fdfddc15a863","status":0,"value":true}
[debug] [MJSONWP] Responding to client with driver.click() result: true
[HTTP] <-- POST /wd/hub/session/5febcf18-2b96-4ca9-9330-5bbce34f80dc/element/4b2
f2ab2-e594-4ea9-b769-d0c284822018/click 200 1787 ms - 76
[HTTP] --> POST /wd/hub/session/5febcf18-2b96-4ca9-9330-5bbce34f80dc/element {"u
sing":"id","value":"com.jd.oa:id/iv_shake_icon"}
[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["id","com.jd.oa
:id/iv_shake_icon","5febcf18-2b96-4ca9-9330-5bbce34f80dc"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class
 name, accessibility id, -android uiautomator
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class
 name, accessibility id, -android uiautomator
[debug] [BaseDriver] Waiting up to 5000 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8202/w
d/hub/session/4f2f518c-ca6f-4ada-84be-fdfddc15a863/element] with body: {"strateg
y":"id","selector":"com.jd.oa:id/iv_shake_icon","context":"","multiple":false}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"4f2f518c-ca6f
-4ada-84be-fdfddc15a863","status":0,"value":{"ELEMENT":"9e8a5cc8-3712-4d46-9100-
e0ec03ba53d7"}}
[debug] [MJSONWP] Responding to client with driver.findElement() result: {"ELEME
NT":"9e8a5cc8-3712-4d46-9100-e0ec03ba53d7"}
[HTTP] <-- POST /wd/hub/session/5febcf18-2b96-4ca9-9330-5bbce34f80dc/element 200
 85 ms - 122
[HTTP] --> POST /wd/hub/session/5febcf18-2b96-4ca9-9330-5bbce34f80dc/element {"u
sing":"id","value":"com.jd.oa:id/search_button"}
[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["id","com.jd.oa
:id/search_button","5febcf18-2b96-4ca9-9330-5bbce34f80dc"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class
 name, accessibility id, -android uiautomator
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class
 name, accessibility id, -android uiautomator
[debug] [BaseDriver] Waiting up to 5000 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8202/w
d/hub/session/4f2f518c-ca6f-4ada-84be-fdfddc15a863/element] with body: {"strateg
y":"id","selector":"com.jd.oa:id/search_button","context":"","multiple":false}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"4f2f518c-ca6f
-4ada-84be-fdfddc15a863","status":0,"value":{"ELEMENT":"28451736-6a2e-4ed6-b348-
7a969b6d7e86"}}
[debug] [MJSONWP] Responding to client with driver.findElement() result: {"ELEME
NT":"28451736-6a2e-4ed6-b348-7a969b6d7e86"}
[HTTP] <-- POST /wd/hub/session/5febcf18-2b96-4ca9-9330-5bbce34f80dc/element 200
 31 ms - 122
[HTTP] --> GET /wd/hub/session/5febcf18-2b96-4ca9-9330-5bbce34f80dc/element/2845
1736-6a2e-4ed6-b348-7a969b6d7e86/displayed {}
[debug] [MJSONWP] Calling AppiumDriver.elementDisplayed() with args: ["28451736-
6a2e-4ed6-b348-7a969b6d7e86","5febcf18-2b96-4ca9-9330-5bbce34f80dc"]
[debug] [JSONWP Proxy] Proxying [GET /element/28451736-6a2e-4ed6-b348-7a969b6d7e
86/attribute/displayed] to [GET http://localhost:8202/wd/hub/session/4f2f518c-ca
6f-4ada-84be-fdfddc15a863/element/28451736-6a2e-4ed6-b348-7a969b6d7e86/attribute
/displayed] with body: {}
[debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"4f2f518c-
ca6f-4ada-84be-fdfddc15a863\",\"status\":0,\"value\":\"true\"}"
[debug] [MJSONWP] Responding to client with driver.elementDisplayed() result: tr
ue
[HTTP] <-- GET /wd/hub/session/5febcf18-2b96-4ca9-9330-5bbce34f80dc/element/2845
1736-6a2e-4ed6-b348-7a969b6d7e86/displayed 200 21 ms - 76
[HTTP] --> POST /wd/hub/session/5febcf18-2b96-4ca9-9330-5bbce34f80dc/element {"u
sing":"-android uiautomator","value":"new UiSelector().text(\"我的关注\")"}
[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["-android uiaut
omator","new UiSelector().text(\"我的关注\")","5febcf18-2b96-4ca9-9330-5bbce34f8
0dc"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class
 name, accessibility id, -android uiautomator
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class
 name, accessibility id, -android uiautomator
[debug] [BaseDriver] Waiting up to 5000 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8202/w
d/hub/session/4f2f518c-ca6f-4ada-84be-fdfddc15a863/element] with body: {"strateg
y":"-android uiautomator","selector":"new UiSelector().text(\"我的关注\")","cont
ext":"","multiple":false}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"4f2f518c-ca6f
-4ada-84be-fdfddc15a863","status":0,"value":{"ELEMENT":"3643f05b-b4ed-4cb5-890e-
c5848dbc58ca"}}
[debug] [MJSONWP] Responding to client with driver.findElement() result: {"ELEME
NT":"3643f05b-b4ed-4cb5-890e-c5848dbc58ca"}
[HTTP] <-- POST /wd/hub/session/5febcf18-2b96-4ca9-9330-5bbce34f80dc/element 200
 36 ms - 122
[HTTP] --> GET /wd/hub/session/5febcf18-2b96-4ca9-9330-5bbce34f80dc/element/3643
f05b-b4ed-4cb5-890e-c5848dbc58ca/displayed {}
[debug] [MJSONWP] Calling AppiumDriver.elementDisplayed() with args: ["3643f05b-
b4ed-4cb5-890e-c5848dbc58ca","5febcf18-2b96-4ca9-9330-5bbce34f80dc"]
[debug] [JSONWP Proxy] Proxying [GET /element/3643f05b-b4ed-4cb5-890e-c5848dbc58
ca/attribute/displayed] to [GET http://localhost:8202/wd/hub/session/4f2f518c-ca
6f-4ada-84be-fdfddc15a863/element/3643f05b-b4ed-4cb5-890e-c5848dbc58ca/attribute
/displayed] with body: {}
[debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"4f2f518c-
ca6f-4ada-84be-fdfddc15a863\",\"status\":0,\"value\":\"true\"}"
[debug] [MJSONWP] Responding to client with driver.elementDisplayed() result: tr
ue
[HTTP] <-- GET /wd/hub/session/5febcf18-2b96-4ca9-9330-5bbce34f80dc/element/3643
f05b-b4ed-4cb5-890e-c5848dbc58ca/displayed 200 28 ms - 76
[HTTP] --> POST /wd/hub/session/5febcf18-2b96-4ca9-9330-5bbce34f80dc/element {"u
sing":"-android uiautomator","value":"new UiSelector().text(\"我的关注\")"}
[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["-android uiaut
omator","new UiSelector().text(\"我的关注\")","5febcf18-2b96-4ca9-9330-5bbce34f8
0dc"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class
 name, accessibility id, -android uiautomator
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class
 name, accessibility id, -android uiautomator
[debug] [BaseDriver] Waiting up to 5000 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8202/w
d/hub/session/4f2f518c-ca6f-4ada-84be-fdfddc15a863/element] with body: {"strateg
y":"-android uiautomator","selector":"new UiSelector().text(\"我的关注\")","cont
ext":"","multiple":false}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"4f2f518c-ca6f
-4ada-84be-fdfddc15a863","status":0,"value":{"ELEMENT":"6bffb9a1-de48-4557-be35-
ebe60514b66d"}}
[debug] [MJSONWP] Responding to client with driver.findElement() result: {"ELEME
NT":"6bffb9a1-de48-4557-be35-ebe60514b66d"}
[HTTP] <-- POST /wd/hub/session/5febcf18-2b96-4ca9-9330-5bbce34f80dc/element 200
 29 ms - 122
[HTTP] --> POST /wd/hub/session/5febcf18-2b96-4ca9-9330-5bbce34f80dc/element/6bf
fb9a1-de48-4557-be35-ebe60514b66d/click {"id":"6bffb9a1-de48-4557-be35-ebe60514b
66d"}
[debug] [MJSONWP] Calling AppiumDriver.click() with args: ["6bffb9a1-de48-4557-b
e35-ebe60514b66d","5febcf18-2b96-4ca9-9330-5bbce34f80dc"]
[debug] [JSONWP Proxy] Proxying [POST /element/6bffb9a1-de48-4557-be35-ebe60514b
66d/click] to [POST http://localhost:8202/wd/hub/session/4f2f518c-ca6f-4ada-84be
-fdfddc15a863/element/6bffb9a1-de48-4557-be35-ebe60514b66d/click] with body: {"e
lement":"6bffb9a1-de48-4557-be35-ebe60514b66d"}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"4f2f518c-ca6f
-4ada-84be-fdfddc15a863","status":0,"value":true}
[debug] [MJSONWP] Responding to client with driver.click() result: true
[HTTP] <-- POST /wd/hub/session/5febcf18-2b96-4ca9-9330-5bbce34f80dc/element/6bf
fb9a1-de48-4557-be35-ebe60514b66d/click 200 1183 ms - 76
[HTTP] --> POST /wd/hub/session/5febcf18-2b96-4ca9-9330-5bbce34f80dc/element {"u
sing":"-android uiautomator","value":"new UiSelector().text(\"香港\")"}
[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["-android uiaut
omator","new UiSelector().text(\"香港\")","5febcf18-2b96-4ca9-9330-5bbce34f80dc"
]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class
 name, accessibility id, -android uiautomator
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class
 name, accessibility id, -android uiautomator
[debug] [BaseDriver] Waiting up to 5000 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8202/w
d/hub/session/4f2f518c-ca6f-4ada-84be-fdfddc15a863/element] with body: {"strateg
y":"-android uiautomator","selector":"new UiSelector().text(\"香港\")","context"
:"","multiple":false}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"4f2f518c-ca6f
-4ada-84be-fdfddc15a863","status":0,"value":{"ELEMENT":"8ecbd59d-47c6-4349-a8ee-
b10114558df6"}}
[debug] [MJSONWP] Responding to client with driver.findElement() result: {"ELEME
NT":"8ecbd59d-47c6-4349-a8ee-b10114558df6"}
[HTTP] <-- POST /wd/hub/session/5febcf18-2b96-4ca9-9330-5bbce34f80dc/element 200
 28 ms - 122
[HTTP] --> POST /wd/hub/session/5febcf18-2b96-4ca9-9330-5bbce34f80dc/element/8ec
bd59d-47c6-4349-a8ee-b10114558df6/click {"id":"8ecbd59d-47c6-4349-a8ee-b10114558
df6"}
[debug] [MJSONWP] Calling AppiumDriver.click() with args: ["8ecbd59d-47c6-4349-a
8ee-b10114558df6","5febcf18-2b96-4ca9-9330-5bbce34f80dc"]
[debug] [JSONWP Proxy] Proxying [POST /element/8ecbd59d-47c6-4349-a8ee-b10114558
df6/click] to [POST http://localhost:8202/wd/hub/session/4f2f518c-ca6f-4ada-84be
-fdfddc15a863/element/8ecbd59d-47c6-4349-a8ee-b10114558df6/click] with body: {"e
lement":"8ecbd59d-47c6-4349-a8ee-b10114558df6"}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"4f2f518c-ca6f
-4ada-84be-fdfddc15a863","status":0,"value":true}
[debug] [MJSONWP] Responding to client with driver.click() result: true
[HTTP] <-- POST /wd/hub/session/5febcf18-2b96-4ca9-9330-5bbce34f80dc/element/8ec
bd59d-47c6-4349-a8ee-b10114558df6/click 200 1192 ms - 76
[HTTP] --> POST /wd/hub/session/5febcf18-2b96-4ca9-9330-5bbce34f80dc/element {"u
sing":"-android uiautomator","value":"new UiSelector().textContains(\"周日\")"}
[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["-android uiaut
omator","new UiSelector().textContains(\"周日\")","5febcf18-2b96-4ca9-9330-5bbce
34f80dc"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class
 name, accessibility id, -android uiautomator
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class
 name, accessibility id, -android uiautomator
[debug] [BaseDriver] Waiting up to 5000 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8202/w
d/hub/session/4f2f518c-ca6f-4ada-84be-fdfddc15a863/element] with body: {"strateg
y":"-android uiautomator","selector":"new UiSelector().textContains(\"周日\")","
context":"","multiple":false}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"4f2f518c-ca6f
-4ada-84be-fdfddc15a863","status":0,"value":{"ELEMENT":"b7b2126e-c8c0-447b-8b23-
8dd9bbb9dfb3"}}
[debug] [MJSONWP] Responding to client with driver.findElement() result: {"ELEME
NT":"b7b2126e-c8c0-447b-8b23-8dd9bbb9dfb3"}
[HTTP] <-- POST /wd/hub/session/5febcf18-2b96-4ca9-9330-5bbce34f80dc/element 200
 33 ms - 122
[HTTP] --> POST /wd/hub/session/5febcf18-2b96-4ca9-9330-5bbce34f80dc/element/b7b
2126e-c8c0-447b-8b23-8dd9bbb9dfb3/click {"id":"b7b2126e-c8c0-447b-8b23-8dd9bbb9d
fb3"}
[debug] [MJSONWP] Calling AppiumDriver.click() with args: ["b7b2126e-c8c0-447b-8
b23-8dd9bbb9dfb3","5febcf18-2b96-4ca9-9330-5bbce34f80dc"]
[debug] [JSONWP Proxy] Proxying [POST /element/b7b2126e-c8c0-447b-8b23-8dd9bbb9d
fb3/click] to [POST http://localhost:8202/wd/hub/session/4f2f518c-ca6f-4ada-84be
-fdfddc15a863/element/b7b2126e-c8c0-447b-8b23-8dd9bbb9dfb3/click] with body: {"e
lement":"b7b2126e-c8c0-447b-8b23-8dd9bbb9dfb3"}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"4f2f518c-ca6f
-4ada-84be-fdfddc15a863","status":0,"value":true}
[debug] [MJSONWP] Responding to client with driver.click() result: true
[HTTP] <-- POST /wd/hub/session/5febcf18-2b96-4ca9-9330-5bbce34f80dc/element/b7b
2126e-c8c0-447b-8b23-8dd9bbb9dfb3/click 200 1094 ms - 76
[HTTP] --> POST /wd/hub/session/5febcf18-2b96-4ca9-9330-5bbce34f80dc/touch/perfo
rm {"actions":[{"action":"tap","options":{"x":748,"y":977}},{"action":"longPress
","options":{"x":850,"y":1000,"duration":1000}},{"action":"wait","options":{"ms"
:1000}},{"action":"moveTo","options":{"x":30,"y":188}},{"action":"release","opti
ons":{}}]}
[debug] [MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"ta
p","options":{"x":748,"y":977}},{"action":"longPress","options":{"x":850,"y":100
0,"duration":1000}},{"action":"wait","options":{"ms":1000}},{"action":"moveTo","
options":{"x":30,"y":188}},{"action":"release","options":{}}],"5febcf18-2b96-4ca
9-9330-5bbce34f80dc"]
[debug] [JSONWP Proxy] Proxying [POST /appium/tap] to [POST http://localhost:820
2/wd/hub/session/4f2f518c-ca6f-4ada-84be-fdfddc15a863/appium/tap] with body: {"x
":748,"y":977}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"4f2f518c-ca6f
-4ada-84be-fdfddc15a863","status":0,"value":true}
[debug] [JSONWP Proxy] Proxying [POST /touch/longclick] to [POST http://localhos
t:8202/wd/hub/session/4f2f518c-ca6f-4ada-84be-fdfddc15a863/touch/longclick] with
 body: {"params":{"x":1598,"y":1977,"duration":1000}}
[MJSONWP] Encountered internal error running command:  {"jsonwp":{"sessionId":"4
f2f518c-ca6f-4ada-84be-fdfddc15a863","status":13,"value":false}} ProxyRequestErr
or: Could not proxy command to remote server. Original error: 500 - {"sessionId"
:"4f2f518c-ca6f-4ada-84be-fdfddc15a863","status":13,"value":false}
    at JWProxy.proxy$ (../../../lib/jsonwp-proxy/proxy.js:152:13)
    at tryCatch (C:\Users\yfxuxiaojun\AppData\Roaming\npm\node_modules\appium\no
de_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\yfxuxiaojun\AppD
ata\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runti
me.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\
Users\yfxuxiaojun\AppData\Roaming\npm\node_modules\appium\node_modules\babel-run
time\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\yfxuxiaojun\AppData\Roaming\n
pm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)

    at <anonymous>
[HTTP] <-- POST /wd/hub/session/5febcf18-2b96-4ca9-9330-5bbce34f80dc/touch/perfo
rm 500 154 ms - 154
[HTTP] --> DELETE /wd/hub/session/5febcf18-2b96-4ca9-9330-5bbce34f80dc {}
[debug] [MJSONWP] Calling AppiumDriver.deleteSession() with args: ["5febcf18-2b9
6-4ca9-9330-5bbce34f80dc"]
[debug] [BaseDriver] Event 'quitSessionRequested' logged at 1515163143556 (22:39
:03 GMT+0800 (中国标准时间))
[Appium] Removing session 5febcf18-2b96-4ca9-9330-5bbce34f80dc from our master s
ession list
[debug] [UiAutomator2] Deleting UiAutomator2 session
[debug] [UiAutomator2] Deleting UiAutomator2 server session
[debug] [JSONWP Proxy] Proxying [DELETE /] to [DELETE http://localhost:8202/wd/h
ub/session/4f2f518c-ca6f-4ada-84be-fdfddc15a863] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"4f2f518c-
ca6f-4ada-84be-fdfddc15a863\",\"status\":0,\"value\":\"Session deleted\"}"
[debug] [UiAutomator2] Resetting IME to 'io.appium.android.ime/.UnicodeIME'
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'D:\android-sdk\sdk\platform-tools\adb.exe' with args: ["-
P",5037,"-s","5LM0216117013394","shell","ime","set","io.appium.android.ime/.Unic
odeIME"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'D:\android-sdk\sdk\platform-tools\adb.exe' with args: ["-
P",5037,"-s","5LM0216117013394","shell","am","force-stop","com.jd.oa"]
[debug] [UiAutomator2] [UIAutomator2] io.appium.uiautomator2.server.test.AppiumU
iAutomator2Server:.
[debug] [UiAutomator2] [UIAutomator2] Time: 17.014
[debug] [UiAutomator2] [UIAutomator2] OK (1 test)
[debug] [Logcat] Stopping logcat capture
[debug] [ADB] Removing forwarded port socket connection: 8202
[debug] [ADB] Running 'D:\android-sdk\sdk\platform-tools\adb.exe' with args: ["-
P",5037,"-s","5LM0216117013394","forward","--remove","tcp:8202"]
[debug] [BaseDriver] Event 'quitSessionFinished' logged at 1515163144653 (22:39:
04 GMT+0800 (中国标准时间))
[debug] [MJSONWP] Received response: null
[debug] [MJSONWP] But deleting session, so not returning
[debug] [MJSONWP] Responding to client with driver.deleteSession() result: null
[HTTP] <-- DELETE /wd/hub/session/5febcf18-2b96-4ca9-9330-5bbce34f80dc 200 1103
ms - 76

## Code To Reproduce Issue [ Good To Have ]
        new TouchAction(driver).tap(748, 977).longPress(850, 1000,1000).waitAction(1000).moveTo(880 - 850, 1188 - 1000).release().perform()

**Comment by mykola-mokhnach** [comment]
what are you trying to do there? for a simple swipe it's enough to create press-wait-moveTo-release chain.

**Comment by WenRui13** [comment]
I want to tap a point to trigger a selector bar，then do draging from start point to end point.

**Comment by mykola-mokhnach** [comment]
replace longPress with press-wait

**Comment by WenRui13** [comment]
new TouchAction(driver)
                .tap(748, 977)
                .press(850, 1000).waitAction(1000)
                .moveTo(880 - 850, 1188 - 1000).release().perform()

is that right?

**Comment by WenRui13** [comment]
still can not work
