### ISSUE TITLE
Cannot start session Ruby

### ISSUE THREAD

**Issue by ppotanin** [appium/appium#9925]
Cannot start session

Testing started at 23:38 ...
C:\Ruby24-x64\bin\ruby.exe -EUTF-8 -e $stdout.sync=true;$stderr.sync=true;load($0=ARGV.shift) C:\Ruby24-x64\bin/cucumber C:/Users/ppota/RubymineProjects/sample-code/sample-code/examples/ruby/cucumber_android/features/settings.feature --format Teamcity::Cucumber::Formatter --expand --color -r features
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/appium_lib_core-1.2.4/lib/appium_lib_core/common/base/bridge/w3c.rb:8: warning: already initialized constant Selenium::WebDriver::PointerActions::DEFAULT_MOVE_DURATION
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/common/interactions/pointer_actions.rb:21: warning: previous definition of DEFAULT_MOVE_DURATION was here
cannot load such file -- cucumber/ast (LoadError)
C:/Ruby24-x64/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:135:in `require'
C:/Ruby24-x64/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
C:/Ruby24-x64/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:40:in `require'
C:/Users/ppota/RubymineProjects/sample-code/sample-code/examples/ruby/cucumber_android/features/support/env.rb:9:in `<top (required)>'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-3.1.0/lib/cucumber/glue/registry_and_more.rb:106:in `load'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-3.1.0/lib/cucumber/glue/registry_and_more.rb:106:in `load_code_file'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-3.1.0/lib/cucumber/runtime/support_code.rb:147:in `load_file'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-3.1.0/lib/cucumber/runtime/support_code.rb:88:in `block in load_files!'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-3.1.0/lib/cucumber/runtime/support_code.rb:87:in `each'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-3.1.0/lib/cucumber/runtime/support_code.rb:87:in `load_files!'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-3.1.0/lib/cucumber/runtime.rb:270:in `load_step_definitions'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-3.1.0/lib/cucumber/runtime.rb:67:in `run!'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-3.1.0/lib/cucumber/cli/main.rb:33:in `execute!'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cucumber-3.1.0/bin/cucumber:9:in `<top (required)>'
C:/Ruby24-x64/bin/cucumber:23:in `load'
C:/Ruby24-x64/bin/cucumber:23:in `<top (required)>'
-e:1:in `load'
-e:1:in `<main>'

Process finished with exit code 2

**Comment by KazuCocoa** [comment]
It's cucumber gem's loading file issue.

If you tried to the below sample app, please run the command with `bundle exec` commands since the sample app specifies the version, ` 'cucumber', '~> 2.4.0'`.

https://github.com/appium/sample-code/tree/master/sample-code/examples/ruby

@ppotanin
