### ISSUE TITLE
Test fail as Unable to locate elements in Appium in Edit Page

### ISSUE THREAD

**Issue by dilugit** [appium/appium#9929]
## The problem
In Application same id/xpath/class is there for 'Name' text field in both 'Create' & 'Edit' Page. Even though test gets pass in 'Create' page, it gets fail as unable to find the element when run the same code in 'Edit' Page.
If I use the coordination (X,Y) to click that text field in Edit Page, then it works by clicking.
Can any one give me a solution for this test fail or else a way of proceeding by clearing the existing value & enter new value after click the element via coordination (X,Y)?

## Environment

* Appium version - 1.7.1
* Desktop OS/version used to run Appium: Windows 8.1

**.========Code part========.**
......................
//....Enter Values in Create Media............//
MediaPageObjects.mediaNameTextBox(driver).click();
MediaPageObjects.mediaNameTextBox(driver).sendKeys(onscreenmedname);
MediaPageObjects.mediaSaveButton(driver).click();
Thread.sleep(4000);
MediaPageObjects.mediaNameText(driver).click();
Thread.sleep(2000);
//....Select Edit Icon............//
TouchAction selectEdit = new TouchAction(driver);
selectEdit.tap(970, 39).perform();
Thread.sleep(5000);
//....Edit Values............//
MediaPageObjects.mediaNameTextBox(driver).click();

Final Step ' MediaPageObjects.mediaNameTextBox(driver).click();' is failing with below error.Same locator is given when creating the Media (1st step above) and it's passing with no errors.But the issue is when try to select the same text box in Edit Page.

====Error in Idea=========
org.openqa.selenium.NoSuchElementException: An element could not be located on the page using the given search parameters. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 73.13 seconds

## Link to Appium logs

{"strategy":"id","selector":"com.verifone.android.umsmediaapp:id/fragmentCreateMediaPackageFragment_nameEditText","context":"","multiple":false}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"id","selector":"com.verifone.android.umsmediaapp:id/fragmentCreateMediaPackageFragment_nameEditText","context":"","multiple":false}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: find
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding 'com.verifone.android.umsmediaapp:id/fragmentCreateMediaPackageFragment_nameEditText' using 'ID' with the contextId: '' multiple: false
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[INSTANCE=0, RESOURCE_ID=com.verifone.android.umsmediaapp:id/fragmentCreateMediaPackageFragment_nameEditText]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Failed to locate element. Clearing Accessibility cache and retrying.
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding 'com.verifone.android.umsmediaapp:id/fragmentCreateMediaPackageFragment_nameEditText' using 'ID' with the contextId: '' multiple: false
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[INSTANCE=0, RESOURCE_ID=com.verifone.android.umsmediaapp:id/fragmentCreateMediaPackageFragment_nameEditText]
[AndroidBootstrap] Received command result from bootstrap
[HTTP] <-- POST /wd/hub/session/28711219-c74d-42e4-8d71-ddb8193b2c16/element 500 13427 ms - 164 
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":7,"value":"No element found"}

**Comment by mykola-mokhnach** [comment]
Can you attach the output of getPageSource command before locating the element?

**Comment by dilugit** [comment]
@mykola-mokhnach 
Could you please explain more what is getPageSource command?
Code is working fine until load the 'Edit' Page. Issue is in select the 'Name' text Box within the 'Edit' Page.Non of the fine elements (id, xpath, class) is working for this and only X,Y Coordination is working.
Have a doubt on y is that.

**Comment by mykola-mokhnach** [comment]
> Could you please explain more what is getPageSource command?

I assume you could get an answer on Appium forum or after some googling
