### ISSUE TITLE
Open URL schema verification using appium in iOS

### ISSUE THREAD

**Issue by bhanuneeli** [appium/appium#9930]
HI, 
I have a scenario where I need to verify that in the app under test, there are list of other native apps. I need to validate whether those apps are installed on the device under test.

**Comment by mykola-mokhnach** [comment]
Upgrade to Appium 1.7.2 and use https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios/ios-xctest-mobile-apps-management.md
