### ISSUE TITLE
Not able to test android application on android 7.0 Error executing adbExec. 

### ISSUE THREAD

**Issue by Praney** [appium/appium#9932]
Initializing...
[Appium] Welcome to Appium v1.7.1
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"requiredCapabilities":{},"desiredCapabilities":{"deviceName":"Nexus_5X_API_24:5554","platformName":"Android","platformVersion":"7.0","app":"/home/tap/APK/app-develop-debug.apk","automationName":"UiAutomator2"}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"deviceName":"Nexus_5X_API_24:5554","platformName":"Android","platformVersion":"7.0","app":"/home/tap/APK/app-develop-debug.apk","automationName":"UiAutomator2"},{},null]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1515392032754 (06:13:52 GMT+0000 (Asia))
[Appium] Creating new AndroidUiautomator2Driver (v0.6.5) session
[Appium] Capabilities:
[Appium]   deviceName: 'Nexus_5X_API_24:5554'
[Appium]   platformName: 'Android'
[Appium]   platformVersion: '7.0'
[Appium]   app: '/home/tap/APK/app-develop-debug.apk'
[Appium]   automationName: 'UiAutomator2'
[BaseDriver] Session created with session id: 5478f2b0-4811-4acd-99e8-f242ca358f53
[BaseDriver] Using local app '/home/tap/APK/app-develop-debug.apk'
[debug] [UiAutomator2] Checking whether app is actually present
[debug] [AndroidDriver] Getting Java version
[AndroidDriver] Java version is: 1.8.0_151
[ADB] Checking whether adb is present
[ADB] Using adb from /opt/android-sdk/platform-tools/adb
[AndroidDriver] Retrieving device list
[debug] [ADB] Trying to find a connected android device
[debug] [ADB] Getting connected devices...
[debug] [ADB] 0 device(s) connected
[debug] [ADB] Could not find devices, restarting adb server...
[debug] [ADB] Restarting adb
[debug] [ADB] Killing adb server on port 5037
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[AndroidDriver] Looking for a device with Android '7.0'
[debug] [ADB] Setting device id to emulator-5554
[ADB] Getting device platform version
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
***********************
[debug] [ADB] Running '/opt/android-sdk/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","getprop","ro.build.version.release"]
[debug] [ADB] Current device property 'ro.build.version.release': 7.0
[AndroidDriver] Using device: emulator-5554
[ADB] Checking whether adb is present
[ADB] Using adb from /opt/android-sdk/platform-tools/adb
[debug] [ADB] Setting device id to emulator-5554
[debug] [AndroidDriver] Parsing package and activity from app manifest
[ADB] Checking whether aapt is present
[ADB] Using aapt from /opt/android-sdk/build-tools/27.0.0/aapt
[ADB] Extracting package and launch activity from manifest
[debug] [ADB] badging package: in.burgerkingindia.android
[debug] [ADB] badging act: limetray.com.tap.splash.activity.SplashActivity
[debug] [AndroidDriver] Parsed package and activity are: in.burgerkingindia.android/limetray.com.tap.splash.activity.SplashActivity
[ADB] Getting device platform version
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
***********************
[debug] [ADB] Running '/opt/android-sdk/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","getprop","ro.build.version.release"]
[debug] [ADB] Current device property 'ro.build.version.release': 7.0
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
***********************
[debug] [ADB] Running '/opt/android-sdk/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","wm","size"]
[debug] [ADB] Running '/opt/android-sdk/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","wm","size"]
[debug] [UiAutomator2] Deleting UiAutomator2 session
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
***********************
[debug] [ADB] Running '/opt/android-sdk/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","am","force-stop","in.burgerkingindia.android"]
[debug] [ADB] Running '/opt/android-sdk/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","am","force-stop","in.burgerkingindia.android"]
[UiAutomator2] Unable to force stop app: Error executing adbExec. Original error: 'Command '/opt/android-sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am force-stop in.burgerkingindia.android' timed out after 120000ms'; Stderr: ''; Code: 'null'
[debug] [ADB] Removing forwarded port socket connection: 8200 
***********************
[debug] [ADB] Running '/opt/android-sdk/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","forward","--remove","tcp:8200"]
[debug] [ADB] Running '/opt/android-sdk/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","forward","--remove","tcp:8200"]
[UiAutomator2] Unable to remove port forward 'Error executing adbExec. Original error: 'Command '/opt/android-sdk/platform-tools/adb -P 5037 -s emulator-5554 forward --remove tcp\:8200' exited with code 1'; Stderr: 'error: listener 'tcp:8200' not found'; Code: '1''
[HTTP] <-- POST /wd/hub/session 500 489973 ms - 315 
-------------------------------------------------------------------------------------------------------------- Captured stderr ---------------------------------------------------------------------------------------------------------------
[MJSONWP] Encountered internal error running command: Error: Error executing adbExec. Original error: 'Command '/opt/android-sdk/platform-tools/adb -P 5037 -s emulator-5554 shell wm size' timed out after 120000ms'; Stderr: ''; Code: 'null'
    at ADB.execFunc$ (/usr/lib/node_modules/appium/node_modules/appium-adb/build/lib/tools/system-calls.js:758:39)
    at tryCatch (/usr/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)

**Comment by mykola-mokhnach** [comment]
Use `avd` capability instead of `deviceName`to set emulator name.

**Comment by ayarema** [comment]
@mykola-mokhnach nope
if I remove from setting of capability property "deviceName" I get error:

```[Appium] Creating new AndroidUiautomator2Driver (v0.11.0) session
[Appium] Capabilities:
[Appium]   app: /Users/usr/project/Mob-Automation/applications/qaLive-debug.apk
[Appium]   platformVersion: 7.1.1
[Appium]   automationName: UIAutomator2
[Appium]   platformName: Android
[Appium]   avd: Nexus_6_API_25
[BaseDriver] SessionNotCreatedError: A new session could not be created. Details: The desiredCapabilities object was not valid for the following reason(s):  deviceName can't be blank,
    at AndroidUiautomator2Driver.validateDesiredCaps (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:184:25)```
