### ISSUE TITLE
error:org.w3c.dom.DOMException: android.support.v7.app.ActionBar.ˊ

### ISSUE THREAD

**Issue by NozomiIto** [appium/appium#9934]
## The problem

I found page source command for Japanese Yahoo transit app top page caused Appium server error `Command returned error:org.w3c.dom.DOMException: android.support.v7.app.ActionBar.ˊ`

This error seems similar to https://github.com/appium/appium/issues/9686, and I'm afraid the strange character `ˊ` causes this problem.

I'm not sure why this app uses such a character for the class name, since it is not my app.

## Environment

* Appium1.7.2
* Mac OS X 10.13.2
* Node.js v7.9.0
* Android OS 6.0
* Android Real Device
* Appium CLI server and python client

## Appium logs

[Server log]
https://gist.github.com/NozomiIto/27bba17436e02c662aa113f18bc33181

[Client stacktrace]
```
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    print(driver.page_source)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 573, in page_source
    return self.execute(Command.GET_PAGE_SOURCE)['value']
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 297, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/appium/webdriver/errorhandler.py", line 29, in check_response
    raise wde
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command.
```
## Code To Reproduce Issue

1. Install Japanese Yahoo transit app (https://play.google.com/store/apps/details?id=jp.co.yahoo.android.apps.transit&hl=ja )
2. Run the following with Python

```
from appium import webdriver

desired_caps = {}
desired_caps['platformName'] = 'Android'
desired_caps['deviceName'] = 'Android'
desired_caps['automatonName'] = 'uiautomator2'
desired_caps['appPackage'] = 'jp.co.yahoo.android.apps.transit'
desired_caps['appActivity'] = '.Transit'
driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)
print(driver.page_source)
```

**Comment by mykola-mokhnach** [comment]
Can you please attach the logcat output as well?

**Comment by mykola-mokhnach** [comment]
> [BaseDriver] The following capabilities were provided, but are not recognized by appium: automatonName.

Also are you sure that UIA2 is used? It seems like you have a typo in capability name. :-P

**Comment by NozomiIto** [comment]
Sorry for typo :sweat:
First, the following is the Appium server log and client stack trace after fixing typo:

### Server log 
https://gist.github.com/NozomiIto/d8ee0ddeecbd1534336f27903f8c8136

### Client log

```
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    print(driver.page_source)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 573, in page_source
    return self.execute(Command.GET_PAGE_SOURCE)['value']
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 297, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/appium/webdriver/errorhandler.py", line 29, in check_response
    raise wde
selenium.common.exceptions.WebDriverException: <exception str() failed>
```

**Comment by NozomiIto** [comment]
[logcat.txt](https://github.com/appium/appium/files/1611010/logcat.txt)

The above attached file is `adb logcat` command output during this test.

**Comment by mykola-mokhnach** [comment]
Can you please try to patch the local uia2 server with https://github.com/appium/appium-uiautomator2-server/pull/105 and check if it helps?

**Comment by NozomiIto** [comment]
Thanks for your quick fix!
I applied this fix under `/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/app` and tried `gradle clean assembleServerDebug assembleServerDebugAndroidTest` to recompile the project, following https://github.com/appium/appium-uiautomator2-server.
But now I encountered the following error and have difficulty to try your patch..

```
A problem occurred evaluating root project 'appium-uiautomator2-server'.
> Could not find method google() for arguments [] on repository container.
```

**Comment by mykola-mokhnach** [comment]
You gradle version is probably outdated. Make sure it is at 4.0+ or just download the most recent version of Android Studio

**Comment by NozomiIto** [comment]
Thanks! I finally succeeded to apply your patch and encountered a little different error `Original error: org.w3c.dom.DOMException: android.support.v7.app.ActionBar.?`.

### Server log

https://gist.github.com/NozomiIto/4df253bc984f37e4976ae99f7bd9d117

### Client stack trace

https://gist.github.com/NozomiIto/2ada51bc3a4c10a3f698075f5af35353

### logcat output

[logcat.txt](https://github.com/appium/appium/files/1611644/logcat.txt)

### How I applied your patch

1. Apply your patch to /usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server
2. `gradle clean assembleServerDebug assembleServerDebugAndroidTest` under appium-uiautomator2-server.
3. Copy generated apk files to `/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-driver/uiautomator2`.

**Comment by mykola-mokhnach** [comment]
This is strange...
Can you try now? I replace the backtick with an empty char.

**Comment by NozomiIto** [comment]
Thanks! The fixed one worked well and the XML source is successfully retrieved!

> This is strange...

Maybe `org.apache.harmony.xml.dom.NodeImpl.setNameNS`, which is used by io.appium.uiautomator2, does not accept `?` character. 

https://android.googlesource.com/platform/libcore-snapshot/+/ics-mr1/luni/src/main/java/org/apache/harmony/xml/dom/NodeImpl.java#241
https://android.googlesource.com/platform/libcore-snapshot/+/ics-mr1/luni/src/main/java/org/apache/harmony/xml/dom/DocumentImpl.java#96

(And https://github.com/mykola-mokhnach/appium-uiautomator2-server/blob/master/app/src/main/java/io/appium/uiautomator2/utils/XMLHierarchy.java#L154 also seems to replace the invalid character with `?`. So I'm afraid this also causes the same `?` related potential problem..)

**Comment by mykola-mokhnach** [comment]
yep, it might be the case. I'll replace ? with empty char

**Comment by mykola-mokhnach** [comment]
Ok, I did final fixes, can you please try now?

**Comment by NozomiIto** [comment]
> Ok, I did final fixes, can you please try now?

This also worked well on my environment.

**Comment by mykola-mokhnach** [comment]
Ok, perfect. Thanks for the help
