### ISSUE TITLE
unable to launch ios application  with appium 1.7.2

### ISSUE THREAD

**Issue by Amittallewar** [appium/appium#9935]
## The problem
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.***.****","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}

Also tried with the capabilities waitforquicscence = false

**Comment by mykola-mokhnach** [comment]
Please attach the full log with `showIOSLog` and `showXcodeLog` capabilities set to `true`
