### ISSUE TITLE
Error in appium desktop while creating a session , simulator is terminating.

### ISSUE THREAD

**Issue by sjdptn** [appium/appium#9936]
I'm getting following error:
An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: "EROFS: read-only file system, mkdir '/private/var/folders/5d/m1b_30697m3dz3d4__4q_50c0000gn/T/AppTranslocation/32437266-384A-439E-852F-D74CADD41000/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Resources'".

Also while trying to change the write permission for the target folder, after going into "AppTranslocation" folder, not able to find further folders "32437266-384A-439E-852F-D74CADD41000/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Resources"

How to solve this issue or how to change the target folder?

**Comment by mykola-mokhnach** [comment]
Appium desktop must be installed into `/Applications` folder. 
Closed as non server-related issue.
