### ISSUE TITLE
WebDriver.quit() not closing tabs on mobile safari (real device)

### ISSUE THREAD

**Issue by milenyordanov** [appium/appium#9938]
## The problem

I run automated tests on mobile Safari. The tests leave many open tabs on the mobile Safari. 

## Environment

* Appium version: 1.7.2
* Desktop OS/version used to run Appium: OSX 10.13.2
* Node.js version: v8.1.4
* Mobile platform/version under test: iOS: 11.2.1 
* Real device: iPhone 5s
* selenium-webdriver 3.6.0

## Details
This code can be used to reproduce the problem.

    async function testCloseTab() {
        let safari_iOS_capabilities = {
            'automationName': 'XCUITest',
            'platformName': 'iOS', 
            'browserName': 'safari',
            'safariInitialUrl': 'about:blank',
            'deviceName': 'mydevice',
            'startIWDP': true,
            'safariOpenLinksInBackground': false,
            'webkitResponseTimeout': 60000
        };

        for(let i = 0; i < 3; i++){
            let driver = await (new webdriver.Builder()
                .usingServer('http://localhost:4723/wd/hub')
                .withCapabilities(safari_iOS_capabilities)
                .build());

            await driver.get('https://en.wikipedia.org/wiki/Special:Random');
            await driver.sleep(1000);
            await driver.get('https://en.wikipedia.org/wiki/Special:Random');
            await driver.sleep(1000);
            await driver.get('https://en.wikipedia.org/wiki/Special:Random');
            await driver.sleep(1000);

            await driver.quit();
        }
    }

    function sleep(ms) {
      return new Promise(resolve => setTimeout(resolve, ms));
    }

Running the above code once causes 3 open tabs. 
Running the above code twice causes 6 open tabs.
..... 

I have a large number of tests and that's why it is very important each test to clean up the used resources. 

I tied to replace the driver.quit() with

    await driver.close();
    await driver.quit();

It helped a bit. But it still does not close 100% if the tabs in my case.

I then added a sleep(1000) between the calls driver.close() and driver.quit()

    await driver.close();
    await sleep(1000);
    await driver.quit();

Now this closes all tabs in my case. It is a temporary workaround. 

What is the 'official' and 'correct' way to close the tab when the test is done?

**Comment by kool79** [comment]
@milenyordanov, Try to remove capability 
'safariInitialUrl': 'about:blank' 
or use any other lighweight url. (Once removed appium will use http://appium.io for real devices or hosted page for simulators). 
  AFAIK appium (or WDA?) use this url to detect/search for  correct webview after safari startup. Maybe your device has more than one  (hidden) webview with such title and appium attachs to wrong webview/application

**Comment by chakradharpm** [comment]
Hi @milenyordanov 
Did you managed to close the tabs while executing tests by any chance. 
I am struck with the same issue, this issue is happening in both IPhone and IPad. I am using the below capabilities 
cap.setCapability("autoAcceptAlerts", true);
cap.setCapability(MobileCapabilityType.DEVICE_NAME, deviceNameIn); 
cap.setCapability(MobileCapabilityType.PLATFORM_NAME, MobilePlatform.IOS); 
cap.setCapability("automationName","XCUITest");
cap.setCapability(MobileCapabilityType.BROWSER_NAME, "safari");
cap.setCapability(MobileCapabilityType.PLATFORM_VERSION, "11.1.1"); 
cap.setCapability(MobileCapabilityType.UDID, deviceIdIn);
cap.setCapability(MobileCapabilityType.SUPPORTS_JAVASCRIPT,"true");

also I am using 
driver.close();
driver.quit();

Please let me know if you have fixed this issue.

**Comment by milenyordanov** [comment]
Hi @chakradharpm,
I have not modified our automated tests setup in the last two months, but it closes the tabs on mobile Safari. The 'solution' in my case was to use:

    await driver.close();
    await sleep(1000);
    await driver.quit();

Without the sleep(1000) it does not work in my case.

**Comment by chakradharpm** [comment]
@milenyordanov Thank you very much for your update
like you mentioned above, i have used the wait time between close() and quit() which is closing the tabs in IPad but not in IPhone.

Anyway once again thank for your help, please give me an update if you came to know anyother solution and I will do the same :+1:

**Comment by mykola-mokhnach** [comment]
Closed as third party issue. There is nothing more to be fixed on Appium side
