### ISSUE TITLE
Accessibility Id: AX error -25205 displayed 

### ISSUE THREAD

**Issue by rahulkulkarniyahoo** [appium/appium#9939]
## The problem

Accessibility Id: AX error -25205 displayed 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7
* Last Appium version that did not exhibit the issue (if applicable): 1.6.5
* Desktop OS/version used to run Appium: 1.2.4 / 1.2.7
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS 10.2
* Real device or emulator/simulator: Real
* Appium CLI or Appium.app|exe: CLI and Appium.app

## Details

Hello, After I came back from the winter vacation, i am see that I am getting the above mentioned error. 
Appium Verion:
Appium 1.6.5 and Appium 1.7
I have also tried Appium Desktop Version 1.2.4 and 1.2.7 using XCUITest. I get the same results. 
![ios appium inspector](https://user-images.githubusercontent.com/12827411/34674346-7bca49b0-f47d-11e7-8e24-09b41731fbec.png)

This was not happening before the December 22 nd 2017 when I last used it. 
I know this may not be related to Appium-iOS-Inspector, but I am unable to resolve it at the moment.

I am not sure if its Appium issue at the moment, but I cannot see anywhere that anyone has had this issue before and hence please let me know where the issue lies.

**Comment by levyshachar2** [comment]
Known issue see https://github.com/facebook/WebDriverAgent/issues/703
