### ISSUE TITLE
isAppInstalled & removeApp commands not working as expected

### ISSUE THREAD

**Issue by vjmaiky** [appium/appium#9940]
## The problem
isAppInstalled it is always returning false even if app is installed, and on removeApp is executed ok but app is still installed on device

Note:
- i mocked bundle id to post it here
- other commands like terminate, launch are working as expected

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable): n/a
* Desktop OS/version used to run Appium: mac OS 10.12.6
* Node.js version (unless using Appium.app|exe): 8.5.0
* Mobile platform/version under test: ios 10.3.3
* Real device or emulator/simulator: iPhone 6+
* Appium CLI or Appium.app|exe:

## Link to Appium logs

HTTP] <-- POST /wd/hub/session/6617aeb0-6ad7-4c65-96e1-f0dbb6143896/element/D03621C4-4946-4CB0-A522-010EEE1BB381/click 200 1206 ms - 118
[HTTP] --> POST /wd/hub/session/6617aeb0-6ad7-4c65-96e1-f0dbb6143896/execute {"script":"mobile: isAppInstalled","args":[{"bundleId":"bundleid"}]}
[debug] [MJSONWP] Calling AppiumDriver.execute() with args: ["mobile: isAppInstalled",[{"bundleId":"bundleid"}],"6617aeb0-6ad7-4c65-96e1-f0dbb6143896"]
[debug] [XCUITest] Executing command 'execute'
[debug] [XCUITest] Error checking install status: 'Cannot read property 'replace' of undefined'
[debug] [MJSONWP] Responding to client with driver.execute() result: false

removeApp:
01-08-2018 16:51:36 - [core.helpers.Helpers / uninstallApp][INFO ] - Uninstalling the app: bundleid
[HTTP] --> POST /wd/hub/session/6617aeb0-6ad7-4c65-96e1-f0dbb6143896/execute {"script":"mobile: removeApp","args":[{"bundleId":"bundleid"}]}
[debug] [MJSONWP] Calling AppiumDriver.execute() with args: ["mobile: removeApp",[{"bundleId":"bundleid"}],"6617aeb0-6ad7-4c65-96e1-f0dbb6143896"]
[debug] [XCUITest] Executing command 'execute'
[XCUITest] Uninstalling the application with bundle identifier 'bundleid' from the real device with UDID 2ccf30dd21fa31a77967a66580e6c7ee62ecce88
[XCUITest] Removal of 'bundleid' succeeded
[debug] [MJSONWP] Responding to client with driver.execute() result: null

**Comment by tfcardoso** [comment]
Your app bundleId is called: bundleId ??

**Comment by vjmaiky** [comment]
of course not :) i just changed it to post it here

**Comment by tfcardoso** [comment]
ah ah. I though you might have done that :)

**Comment by imurchie** [comment]
The full logs are helpful, yes.

Is this a real device? Or a simulated one?

**Comment by imurchie** [comment]
This is reproducible. I have a fix and will submit soon.
