### ISSUE TITLE
iOS Keyboard not showing when doing click() or send_key

### ISSUE THREAD

**Issue by fiuzaB** [appium/appium#9941]
## The problem

I'm building a ionic app, which uses the webview of android and iOS. My team has chosen Appium along with Python to write the tests, because this configuration allows us to run the tests on aws device farm.
My problem is that when I click or write something in the iOS textfields the keyboard is not being enabled. This behaviour occurs on Android (I have to get the element and do a click() so the keyboard appears ) but for some reason, on iOS it just doesn't work.

And I can't use the Native context, because I can't find the elements ( it's a webview ).
 
## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable): -
* Desktop OS/version used to run Appium: macOS Sierra  version 10.12.6
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS 11.2 running on a iPhone 5s
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: Appium CLI

**Comment by mykola-mokhnach** [comment]
Is the same problem reproducible manually?

**Comment by fiuzaB** [comment]
Nope. Manually the keyboard appears.

**Comment by mykola-mokhnach** [comment]
Try to disable "Connect Hardware Keyboard" option

**Comment by fiuzaB** [comment]
I did. All my attempts were with the hardware keyboard disabled. This is unusual ?

**Comment by mykola-mokhnach** [comment]
Try to reset the simulator/use another Simulator/another machine

**Comment by fiuzaB** [comment]
iPhone 6 - 11.2 - AutomationName: Appium
iPhone 6 Plus - 9.3 - AutomationName: XCUITest
iPhone 6s - 10.3 - AutomationName: XCUITest
iPhone 6s - 10.3 - AutomationName: Appium
iPhone 5s - 11.2 - AutomationName: Appium

No luck.

**Comment by pyrophos** [comment]
+1 I'm also encountering this problem but I'm testing a native iOS app

# Environment
- Appium version (or git revision) that exhibits the issue: 1.7.2
- Appium Desktop version: 1.3.1 
- iOS Simulator Version 10.0 (SimulatorApp-835.5 CoreSimulator-494.33)
- Last Appium version that did not exhibit the issue (if applicable): -
- Desktop OS/version used to run Appium: macOS Sierra version 10.13.2
- Node.js version (unless using Appium.app|exe): 5.6.0
- Mobile platform/version under test: iOS 11.2 running on a iPhone 6
- Real device or emulator/simulator: Simulator
- Appium CLI or Appium.app|exe: Appium CLI

# Capabilities
```
    DesiredCapabilities capabilities = new DesiredCapabilities();
    capabilities.setCapability(MobileCapabilityType.APP, app.getAbsolutePath());
    capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, "XCUITest");
    capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone Simulator");
    capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "ios");
    capabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, NEW_COMMAND_TIMEOUT);
    capabilities.setCapability(MobileCapabilityType.FULL_RESET, true);
    capabilities.setCapability("connectHardwareKeyboard", false);
    capabilities.setCapability("xcodeConfigFile",
        new File(new File(System.getProperty("user.dir")), ".xcconfig").getAbsolutePath());
    capabilities.setCapability("clearSystemFiles", false);
```

Within Appium Desktop I've narrowed the problem down to retrieving the page model while the keyboard is displayed. The problem appears to happen right after I click on a form field, the keyboard is displayed, and then I refresh the page view; then Appium crashes.  The same problem happens when running my test through the command line. 

Simulator log:
```
Jan 16 16:31:14 A-Macbook-Pro LocalStorageFileProvider[24280]: BUG in libdispatch client: kevent[mach_recv] monitored resource vanished before the source cancel handler was invoked
Jan 16 16:31:31 A-Macbook-Pro com.apple.CoreSimulator.SimDevice.D472E2F5-3554-4CCD-B90D-6CAC89BAFCBA[24051] (UIKitApplication:org.cocoapods.demo.AppName-Example[0x5043][24077][24303]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]```

Appium Log:
```
[Xcode] 2018-01-16 16:32:23.047683-0600 WebDriverAgentRunner-Runner[24301:205905] Enqueue Failure: Failure fetching attributes for element  pid: 24303, elementOrHash.elementID: 140497688780960.70: Error Domain=XCTDaemonErrorDomain Code=12 "Failed to copy attributes after 30 retries: kAXErrorServerNotFound (see )" UserInfo={NSLocalizedDescription=Failed to copy attributes after 30 retries: kAXErrorServerNotFound (see )} /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
```

**Comment by mykola-mokhnach** [comment]
This looks more like XCTest or Application under test issue. I don't think we can change anything in Appium to fix it.

**Comment by mohan1412** [comment]
Any fix the issue, I'm also seeing the same problem with Appium 1.4.1
>> [JSONWP Proxy] Got response with status 200: {"value":"Error Domain=com.facebook.WebDriverAgent Code=1 \"Keyboard is not present\" UserInfo={NSLocalizedDescription=Keyboard is not present}","sessionId":"D1CB06FF-946D-4A05-B9D1-6CDDA583C0D4","status":13}

**Comment by larajones** [comment]
I'm seeing the same problem on native iOS apps. 

Appium version (or git revision) that exhibits the issue:  1.8.1
Appium Desktop version: 1.6.2
Simulator: Version 10.0 (SimulatorApp-851.2 CoreSimulator-559
Mobile Platform: 10.3.1 (iPhone 6+)
MacOS: 10.13.5
Mobile platform/version under test: iOS 10.3.1 (iPhone 6+)
Real device or emulator/simulator: Simulator
Appium CLI or Appium.app|exe: Appium.app

Original error: Error Domain=com.facebook.WebDriverAgent Code=1 "Keyboard is not present" UserInfo={NSLocalizedDescription=Keyboard is not present}
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z'

**Comment by romansvesh** [comment]
I have the save problem: connectHardwareKeyboard not work. Sendkeys work only If I uncheck "Simulator -> Hardware -> Keyboard -> Connect Hardware Keyboard" 
Appium version: 1.8.1

**Comment by larajones** [comment]
@romansvesh  Thanks!

I have tried using  capabilities.setCapability("connectHardwareKeyboard", false);
and verifying that "Simulator -> Hardware -> Keyboard -> Connect Hardware Keyboard" is unchecked. 

It still does not work.

**Comment by Amar-Incture** [comment]
I think by default, connectHrdwareKeyboard capability is set to false. So, mentioning it separately won't help. I am facing the same issue but intermittently. Sometimes it works and sometimes it doesn't.

**Comment by burakson** [comment]
Solved it via https://stackoverflow.com/a/44522688

```
- Open your Simulator
- Select Hardware
- Select 'Toggle Software Keyboard'
```

**Comment by hadrianjmnz90** [comment]
This worked for me, it looks like it is an ios simulator issue not appium, try these steps:
1. Open terminal and type $ xcrun simctl list  to get the list of simulators and copy the UDID of your simulator.
2. Navigate to Library/Preferences (Make sure the simulator, xcode, appium, are closed.)
3. Type on the terminal $ open com.apple.iphonesimulator.plist (you can command + f, to make sure the .plist file exists) after typing and hitting enter, a window will open.
4. Click Devices and locate the UDID of your device.
![Screen Shot 2019-09-25 at 5 29 17 PM](https://user-images.githubusercontent.com/52982608/65645062-b7615b00-dfbb-11e9-964f-ca912c00ef24.png)
5. Click on the arrow of your device to see the options, there should be an option called 'CaptureKeyboardInput' if it is not there, just click the '+' icon and type it yourself.
6. Choose Boolean type and set the value to TRUE.
Thats it, the keyboard should be enabled by default always
![Screen Shot 2019-09-25 at 5 31 41 PM](https://user-images.githubusercontent.com/52982608/65645095-d06a0c00-dfbb-11e9-945b-c69f7861ca30.png)

**Comment by RakeshSamal37** [comment]
Still getting this issue on iOS real device the number keypad is not launching, tried a lot but still getting the issue keyboard not present.

**Comment by olubukolaaborode** [comment]
I am having the same issue on a real iOS device :(

**Comment by RakeshSamal37** [comment]
> I am having the same issue on a real iOS device :(

I don't know how  its started working for me on real devices....
Can you please once check it after disabling the password autofill from setting. I do that & its working for me now... But I am not sure whether it will work for you.
