### ISSUE TITLE
Unhandled error: TypeError: undefined is not a function while running tests : appium 1.7.2

### ISSUE THREAD

**Issue by Viterzgir666** [appium/appium#9945]
## The problem

Trying to start automated tests for Android 8.1.0 (Nexus 6P), getting 'Unhandled error: TypeError: undefined is not a function' error after "...\adb.exe -s ENU5T********* wait-for-device" execution

## Environment

* Appium version: 1.7.2
* Desktop OS/version used to run Appium: Win10
* Node.js version (unless using Appium.app|exe): 6.10.0 (updated to 8.9.4 - didn't help)
* Mobile platform/version under test: Android 8.1.0
* Real device or emulator/simulator: Real device - Nexus 6P

## Link to Appium logs
[Logs](https://gist.github.com/Viterzgir666/a68373f51a07a0d4ea29232883ad003e)

**Comment by imurchie** [comment]
Please upgrade Appium, or provide the correct logs. The logs say this is Appium v1.4.16, which was released more than two years ago.

**Comment by Viterzgir666** [comment]
that's weird. I re-installed Appium today. 
They way I did it: 
npm uninstall -g appium
npm install -g appium

Thanks. Gonna try to delete older version.

**Comment by Viterzgir666** [comment]
Indeed. 
Fixed by deleting super old version :) 

Thanks!

**Comment by imurchie** [comment]
Excellent! Glad it worked out.
