### ISSUE TITLE
"java.lang.IllegalThreadStateException: Thread already started" errors when running multiple appium test runs on two different physical android devices in parallel

### ISSUE THREAD

**Issue by r4mz0r** [appium/appium#9946]
## The problem

When running autotests (JAVA, Appium JAVA client version 5.0.4 ) with multiple appium test runs on two different physical android devices I have a error "java.lang.IllegalThreadStateException: Thread already started".

Sometimes one (random) device runs successfully, but the second always falls off.

Ports and UDID for both appium servers are unique (added in desiredCapabilities)

## Environment

* Appium 1.7.2
* MacOS 10.13.2 (Sierra)
* Node.js version 6.11.3
* Mobile platform/version under test: Android (version doesn't matter)
* Real device or emulator/simulator: Real devices
* Appium CLI or Appium.app|exe: Java Client 5.0.4

## Link to Appium logs
https://gist.github.com/r4mz0r/9116261c08ab508a402769578c21bad3

**Comment by saikrishna321** [comment]
sorry, I can't understand the logs .. can u pls tell what are the ports u added ?

**Comment by r4mz0r** [comment]
Hello!
4732 and 4725 for two appium servers.
Different android devices must work on different appium servers.

**Comment by mykola-mokhnach** [comment]
Please attach the full server log. Also, have you eventually seen https://github.com/appium/appium/blob/55760b7b9e1c494c6a1f22d152f0bd1fe676dae7/docs/en/advanced-concepts/parallel-tests.md ?

**Comment by saikrishna321** [comment]
@r4mz0r your missing unique System_Port caps, pls follow the link @mykola-mokhnach has given

**Comment by r4mz0r** [comment]
Thx, guys!
