### ISSUE TITLE
xpath not working on appium 1.7.2

### ISSUE THREAD

**Issue by binubeee** [appium/appium#9947]
I am having trouble using xpaths after upgrading to appium 1.7.2. The step worked fine when I used id instead of xpath for locating the same object.

**My current version:**
Appium- 1.7.2
appium-java - 5.0.4

Capabilities:
capabilities.setCapability("platformName", "android");
capabilities.setCapability("platformVersion","6.0.1");
capabilities.setCapability("deviceName", "Android");
capabilities.setCapability("udid", deviceID);
capabilities.setCapability("appPackage", pack);
capabilities.setCapability("appActivity",act);
capabilities.setCapability("clearSystemFiles", true);

Error:

> 
> [HTTP] --> POST /wd/hub/session/baf37912-e5ce-4d2c-97db-a179ea8552a9/element {"using":"xpath","value":"//*[@resource-id='com.abc.app:id/install_button']"}
> [debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["xpath","//*[@resource-id='com.abc.app:id/install_button']","baf37912-e5ce-4d2c-97db-a179ea8552a9"]
> [debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
> [debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
> [debug] [BaseDriver] Waiting up to 0 ms for condition
> [debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"//*[@resource-id='com.abc.app:id/install_button']","context":"","multiple":false}}
> [debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"//*[@resource-id='com.abc.app:id/install_button']","context":"","multiple":false}}
> [debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
> [debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: find
> [debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding '//*[@resource-id='com.abc.app:id/install_button']' using 'XPATH' with the contextId: '' multiple: false
> [debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Command returned error:java.lang.RuntimeException: Could not read xml hierarchy: org.xml.sax.SAXParseException: Unexpected EOF (position:START_TAG <node index='2' text='My Apps' class='android.widget.Button' package='com.abc.app' content-desc='' checkable='false' checked='false' clickable='true' enabled='true' focusable='true' focused='false' scrollable='false' long-clickable='false' password='false' selected='false' bounds='[648,3][1280,103]' resource-id='com.abc.app:id/'>@1:4097 in java.io.FileReader@ae7b834)
> [debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":13,"value":"Could not read xml hierarchy: org.xml.sax.SAXParseException: Unexpected EOF (position:START_TAG <node index='2' text='My Apps' class='android.widget.Button' package='com.abc.app' content-desc='' checkable='false' checked='false' clickable='true' enabled='true' focusable='true' focused='false' scrollable='false' long-clickable='false' password='false' selected='false' bounds='[648,3][1280,103]' resource-id='com.abc.app:id\/'>@1:4097 in java.io.FileReader@ae7b834) "}
> [debug] [AndroidBootstrap] Received command result from bootstrap
> [HTTP] <-- POST /wd/hub/session/baf37912-e5ce-4d2c-97db-a179ea8552a9/element 500 115 ms - 154 
> [HTTP] --> DELETE /wd/hub/session/baf37912-e5ce-4d2c-97db-a179ea8552a9 {}
> [debug] [MJSONWP] Calling AppiumDriver.deleteSession() with args: ["baf37912-e5ce-4d2c-97db-a179ea8552a9"]
> [debug] [BaseDriver] Event 'quitSessionRequested' logged at 1515512550132 (10:42:30 GMT-0500 (EST))
> [Appium] Removing session baf37912-e5ce-4d2c-97db-a179ea8552a9 from our master session list
> [debug] [AndroidDriver] Shutting down Android driver
> 

Can you please tell me what am I doing wrong. This was working fine before update.
Previous versions were:
Appium- 1.7.1
Java client - 4.1.2

**Comment by mykola-mokhnach** [comment]
Use UIAutomation2 backend for Android 6+

**Comment by binubeee** [comment]
Issue magically disappeared after blocking me for almost a day. Now xpath works fine with both uiautomator and uiautomator2 capabilities.
