### ISSUE TITLE
System service (accessibility) is switched on when appium is running

### ISSUE THREAD

**Issue by krzysztofbalana** [appium/appium#9948]
Hi,

I have problem with latest appium(1.7.1) version for android. Whenever I've try to launch appium, it sets 
ACCESSIBILITY_SERVICE to true (despite it's being turned off). It's a little bit of a problem, because there is a dedicated dialog launched for talkback users, every time. 

Is there a way to switch it off on start?

**Comment by mykola-mokhnach** [comment]
I assume the accessibility must be turned on, otherwise the whole automation won't work. It's, actually, based on accessibility properties.

**Comment by krzysztofbalana** [comment]
Oh, it make sense. Thank you!
