### ISSUE TITLE
Hangs with infinite loop when running hybrid app on Android

### ISSUE THREAD

**Issue by dpa99c** [appium/appium#9949]
## The problem

I've previously been successfully running with my test environment for months but suddenly encountered this issue. 
Not sure what has changed: maybe updating the Android SDK? 

I now get the same result on Android devices and emulators: the app installs and runs but after that the Android/Chrome Driver gets stuck in an  infinite loop so the tests never run. I can't see any errors so unsure what the problem is.

Previously I was running Appium 1.6.4 with Chromedriver v2.20 on Android emulator API 23/6.0.

I've tried updating to Appium 1.7.2 with Chomedriver v2.33 and running on both Android emulator API 26/8.0 and Nexus 6P running Android 8.1 but the result it the same:

	[debug] [ADB] Getting connected devices...
	[debug] [ADB] 1 device(s) connected
	[debug] [ADB] Running 'G:\Users\User\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","CVH7N16219000075","shell","cat","/proc/net/unix"]
	[debug] [AndroidDriver] WEBVIEW_3969 mapped to pid 3969
	[debug] [AndroidDriver] Getting process name for webview
	[debug] [ADB] Getting connected devices...
	[debug] [ADB] 1 device(s) connected
	[debug] [ADB] Running 'G:\Users\User\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","CVH7N16219000075","shell","ps"]
	[debug] [AndroidDriver] Parsed pid: '3969' pkg: 'com.myapp' from
	[debug] [AndroidDriver]     USER           PID  PPID     VSZ    RSS WCHAN            ADDR S NAME
	[debug] [AndroidDriver]     u0_a330       3969   756 1869512 117180                     0 R com.myapp
	[debug] [AndroidDriver] Returning process name: 'com.myapp'
	[debug] [AndroidDriver] Found webviews: ["WEBVIEW_chrome","WEBVIEW_com.myapp"]
	[debug] [AndroidDriver] Available contexts: ["NATIVE_APP","WEBVIEW_chrome","WEBVIEW_com.myapp"]
	[debug] [AndroidDriver] Connecting to chrome-backed webview context 'WEBVIEW_com.myapp'
	[debug] [AndroidDriver] A port was not given, using random port: 8000
	[debug] [Chromedriver] Changed state to 'starting'
	[Chromedriver] Set chromedriver binary as: D:\app\chromedriver\chromedriver.v2.33.exe
	[debug] [Chromedriver] Killing any old chromedrivers, running: FOR /F "usebackq tokens=5" %a in (`netstat -nao ^| findstr /R /C:"8000 "`) do (FOR /F "usebackq" %b in (`TASKLIST /FI "PID eq %a" ^| findstr /I chromedriver.exe`) do (IF NOT %b=="" TASKKILL /F /PID %a))
	[Chromedriver] No old chromedrivers seemed to exist
	[debug] [Chromedriver] Cleaning any old adb forwarded port socket connections
	[debug] [ADB] List forwarding ports
	[debug] [ADB] Running 'G:\Users\User\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","CVH7N16219000075","forward","--list"]
	[Chromedriver] Spawning chromedriver with: D:\app\chromedriver\chromedriver.v2.33.exe --url-base=wd/hub --port=8000 --adb-port=5037 --verbose
	[debug] [AndroidDriver] Getting a list of available webviews
	...repeat...

## Environment

* Appium version that exhibits the issue: 1.7.2 (and 1.6.4)
* Last Appium version that did not exhibit the issue: 1.6.4
* Desktop OS/version used to run Appium: Windows 10 64-bit [Version 10.0.15063]
* Node.js version: 7.10.0
* Mobile platform/version under test: Android 8.1
* Real device or emulator/simulator: Android emulator and Nexus 6P
* Appium CLI

## Link to Appium logs

https://gist.github.com/dpa99c/9f6709e95b1f48741a81691046e5142b

**Comment by mykola-mokhnach** [comment]
the chromedriver version must match the webview version in your app. Which means if you use the older engine there then chromedriver binary itself must be downgraded as well. See https://github.com/appium/appium/blob/aa9711817436cb0bd7962c3f85db6efe2c9c8d02/docs/en/writing-running-appium/web/chromedriver.md for more details.

**Comment by dpa99c** [comment]
@mykola-mokhnach according to the compatibility list you've linked to, my Chromedriver vs Chrome versions should then be correct:

The Nexus 6P used to generate the logs is running Chrome 63.0.3239.111 and is used with Chromedriver v2.33.
Previously I was using Chromedriver v2.20 with Android 6.0 emulator running Android System WebView (Chrome) 44.0.2430.119.

| Version  | Minimum Chrome Version |
| ------------- | ------------- |
| 2.33  | 60.0.3112.0  |
| 2.20  | 43.0.2357.0  |

Yet the issue persists.

**Comment by mykola-mokhnach** [comment]
try chromedriver 2.34. It has been also recently included into the beta version of Appium

**Comment by dpa99c** [comment]
@mykola-mokhnach In the meantime, I've setup the development environment on a new machine and it works fine, so it must be caused by something specific to the original development machine. Thanks for your help.
