### ISSUE TITLE
How to write xpath or any other attribute click event for play button in android automation.

### ISSUE THREAD

**Issue by sagarsheth27** [appium/appium#9950]
I tried multiple ways. But unable to **click on Play button**. Changed context view, still not success.
Please suggest what to do for same. My appium version is 1.7.1.
How to write exactly for same? 
Here i attached SS for same also.
![untitled](https://user-images.githubusercontent.com/32329719/34772919-d1ab13d8-f62f-11e7-8d2d-cd16027f0b88.png)
![untitled1](https://user-images.githubusercontent.com/32329719/34772920-d1edebb8-f62f-11e7-85ed-2139d209d982.png)

**Comment by sagarsheth27** [comment]
Also how to click on non identified elements. Otherwise unable to do other tasks.
Here i want o click on highlighted blank element, which i attached here as SSs.
Uiautomator is unable to identify. Same ways unable to identify via chrome inspect dev tools.
Please suggest what action i have to do for same.?


![barcode](https://user-images.githubusercontent.com/32329719/34773604-509ad6f4-f632-11e7-9b75-840f02275ccd.png)
![qr code](https://user-images.githubusercontent.com/32329719/34773606-50dcb34e-f632-11e7-88ef-a3da5f855c24.png)

**Comment by dpgraham** [comment]
Because it's a Web Context, you can use CSS Selectors.

Since this isn't an issue with Appium, I'm closing this. discuss.appium.io is where you can get help with Appium.
