### ISSUE TITLE
Python - 'WebDriver' object has no attribute 'unlock'

### ISSUE THREAD

**Issue by mayuayla** [appium/appium#9951]
## The problem

According to http://appium.io/docs/en/commands/device/interactions/unlock/, the method unlock() seems to exist.  

If I try, I get the following error. 

`>       driver.unlock()`
`E       AttributeError: 'WebDriver' object has no attribute 'unlock'`

I am using Appium 1.7.2

**Comment by mykola-mokhnach** [comment]
yes, The PR is still in pending state: https://github.com/appium/python-client/pull/84

@imurchie would you like to check it?

**Comment by mykola-mokhnach** [comment]
Closed as server-unrelated.
