### ISSUE TITLE
Upgraded to Mac Desktop 1.3.0 - Does not work gives ENOENT error

### ISSUE THREAD

**Issue by LokeshGangaiah** [appium/appium#9953]
## The problem

Was using 1.2.7 got a popup to upgrade to 1.3.0 and i wasted my 2hr of time
When upgraded to 1.3.0 getting the below error, my appium inspector does not work.

## Environment

* Appium version 1.3.0 Mac Desktop
* Last Appium version that did not exhibit the issue (if applicable):1.2.7
* Desktop OS/version used to run Appium:1.3.0 Mac
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:iOS
* Real device or emulator/simulator:Real Device
* Appium CLI or Appium.app|exe:

## Details

Error:
An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: "ENOENT: no such file or directory, open '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/PrivateHeaders/XCTest/XCUICoordinate.h'". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Some precesses were probably locking some files there. Try to delete the application completely and install the new version manually.

There is a separate repository for Appium Desktop-related issues. Closing this non server-related issue.

**Comment by imurchie** [comment]
This was fixed in 1.3.1 https://github.com/appium/appium-desktop/releases/tag/v1.3.1
