### ISSUE TITLE
Unrecognized platform: iOS

### ISSUE THREAD

**Issue by guowang94** [appium/appium#9955]
## The problem
Unable to find element with iOSDriver

org.openqa.selenium.WebDriverException: Unrecognized platform: iOS
Build info: version: '3.5.2', revision: '10229a9', time: '2017-08-21T17:29:55.15Z'
System info: host: 'Guo-Wangs-MacBook-Pro.local', ip: 'fe80:0:0:0:1c8a:a991:76ed:7228%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.1', java.version: '1.8.0_131'
Driver info: driver.version: IOSDriver

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.0-beta1
* Desktop OS/version used to run Appium: 10.13.1
* Node.js version (unless using Appium.app|exe): 
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium.app

## Link to Appium logs

[link for appium log](https://gist.github.com/guowang94/08b436750b447e2f0e8f8ed37fea5e9e)

## Code To Reproduce Issue [ Good To Have ]

`IOSElement username = (IOSElement) iosDriver.findElementByXPath("//XCUIElementTypeApplication[1]/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeTextField[1]");`

**Comment by mykola-mokhnach** [comment]
>Appium version (or git revision) that exhibits the issue: 1.6.0-beta1

This version is outdated. Try Appium 1.7.2. Also the java client must be up to date.
