### ISSUE TITLE
Unable to switch into iframe Appium/Ruby/Cucumber/Android

### ISSUE THREAD

**Issue by carduelis24** [appium/appium#9958]
Hi,

I'm new with Appium/Cucumber on Ruby and I would like some help with the following issue :

I work with a hybrid Android App and I'm not able to **switch into an iFrame** to interact with its content (clicking and submitting)
 
I'm however able to extract the HTML inside the iFrame with : _iframeSourceCode = $driver.execute_script("return document.getElementsByTagName('iframe')[0].contentWindow.document.body.outerHTML")_

When I check the available methods with "_puts $driver.methods_" I don't find any "switching to iframe" method available. I've tried 3 syntax : _$driver.switchToFrame(), $driver.switch_to.frame()
, $driver.switch_to_frame 

## Environment
- The Ruby version 2.3.3p222
- The test engin version is Cucumber 3.0.2
- The Driver version is Appium 1.7.2 (CLI) => same issue with Appium 1.7.1
- The client version is Android 6.0.1 on a real device : Samsung Galaxy Tab S2 9.7”
- The OS is Windows 10 Entreprise

The capabilities are :
desired_caps = {      
caps:{             
platformName:'Android',
deviceName: 'Samsung Galaxy S2',
app:(File.join(File.dirname(__FILE__), "MyApp.apk")),
name:'My app',
newCommandTimeout:"3600",
:javascript_enabled    => true,
:takes_screenshot  => true,
automationName:'UiAutomator2'
}
  
}
I start the driver with the code : 
_$driver = Appium::Driver.new(desired_caps, true) 
$driver.start_driver_

Here is the [Gemfile.lock ](https://gist.github.com/carduelis24/be8e8bfc7467bb418fe0a9441552b9b6)
Here is the error message :   **undefined method `switch_to' for #<Appium::Driver:0x58659d8> (NoMethodError)
      ./features/step_definitions/home_steps.rb:325**

Here is the list of available method I got with : [ puts $driver.methods](https://gist.github.com/carduelis24/8063af84ec13bde5aadf82bb4ea72f7c)

Here is the [Link to Appium logs ](https://gist.github.com/carduelis24/d9cd0d0d660bc6f1da071fdf8601d1fa)

FYI, working with native view is not possible in my case for the following reasons :

- I work with multilingual app
- The XPath with UiAutomator are too long
- The XPaths with UiAutomator have the same "package" & "class" and has no Content-desc, only TEXT (unfortunately it changes with each language)
- The Xpaths are very long and change frequently

Don't hesitate to ask for any additional details.

Many thanks in advance !

Regards,

**Comment by mykola-mokhnach** [comment]
Please report the issue into https://github.com/appium/ruby_lib/issues

@KazuCocoa FYI

**Comment by carduelis24** [comment]
Hi mykola-mokhnach,

Done, please cf. https://github.com/appium/ruby_lib/issues/745

Regards,
