### ISSUE TITLE
Issues running the Cucumber Android test

### ISSUE THREAD

**Issue by marcaractac** [appium/appium#9959]
I am currently trying to get the cucumber tests in this repo working as a way to get familiar with Appium before starting to write my own tests. I have been able to run the iOS cucumber test just fine, however, I'm running into issues trying to run the one for Android. 

## Environment

* Appium version (or git revision) that exhibits the issue: 9.7.5
* Desktop OS/version used to run Appium: OSX Sierra 10.12.6
* Node.js version (unless using Appium.app|exe): 9.3.0
* Mobile platform/version under test: using exactly what is outlined in appium.txt
I'm also using the Gemfile included in the repo, just trying to get these tests working as is before I start to work on my own. 

This is what I get when trying to run the test:

parse error on value "rspec/expectations" (STRING_LITERAL) (Tomlrb::ParseError)
/Users/test/.rvm/gems/ruby-2.3.1@global/gems/tomlrb-1.2.6/lib/tomlrb.rb:25:in `rescue in parse'
/Users/test/.rvm/gems/ruby-2.3.1@global/gems/tomlrb-1.2.6/lib/tomlrb.rb:22:in `parse'
/Users/test/.rvm/gems/ruby-2.3.1@global/gems/tomlrb-1.2.6/lib/tomlrb.rb:42:in `load_file'
/Users/test/.rvm/gems/ruby-2.3.1/gems/appium_lib-9.7.5/lib/appium_lib/appium.rb:63:in `load_settings'
/Users/test/workspace/sample-code/examples/ruby/cucumber_android/features/support/env.rb:17:in `<top (required)>'
/Users/test/.rvm/gems/ruby-2.3.1/gems/cucumber-2.4.0/lib/cucumber/rb_support/rb_language.rb:96:in `load'
/Users/test/.rvm/gems/ruby-2.3.1/gems/cucumber-2.4.0/lib/cucumber/rb_support/rb_language.rb:96:in `load_code_file'
/Users/test/.rvm/gems/ruby-2.3.1/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:142:in `load_file'
/Users/test/.rvm/gems/ruby-2.3.1/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:84:in `block in load_files!'
/Users/test/.rvm/gems/ruby-2.3.1/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:83:in `each'
/Users/test/.rvm/gems/ruby-2.3.1/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:83:in `load_files!'
/Users/test/.rvm/gems/ruby-2.3.1/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:253:in `load_step_definitions'
/Users/test/.rvm/gems/ruby-2.3.1/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:61:in `run!'
/Users/test/.rvm/gems/ruby-2.3.1/gems/cucumber-2.4.0/lib/cucumber/cli/main.rb:32:in `execute!'
/Users/test/.rvm/gems/ruby-2.3.1/gems/cucumber-2.4.0/bin/cucumber:8:in `<top (required)>'
/Users/test/.rvm/gems/ruby-2.3.1/bin/cucumber:23:in `load'
/Users/test/.rvm/gems/ruby-2.3.1/bin/cucumber:23:in `<main>'
/Users/test/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/Users/test/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'

**Comment by mykola-mokhnach** [comment]
Please report the issue into https://github.com/appium/ruby_lib/issues
