### ISSUE TITLE
adb command hangs - execute_script("mobile: shell", args)

### ISSUE THREAD

**Issue by mayuayla** [appium/appium#9961]
## Appium Python code :

`args = {"command": "logcat"}`
`output = get_driver.execute_script("mobile: shell", args)`
`print(output)`

I tried other adb shell commands.  Same issue.

## Error: 
shell logcat' timed out after 20000ms'; Stderr: ''; Code: 'null'

## Log: 
`[debug] [ADB] Running '/Users/mkataoka/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","FA6A80307030","shell","logcat"]
[MJSONWP] Encountered internal error running command: Error: Error executing adbExec. Original error: 'Command '/Users/mkataoka/Library/Android/sdk/platform-tools/adb -P 5037 -s FA6A80307030 **shell logcat' timed out after 20000ms'; Stderr: ''; Code: 'null'**
    at ADB.execFunc$ (/usr/local/lib/node_modules/appium/node_modules/appium-adb/lib/tools/system-calls.js:321:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>`

## Appium server run command  :
` appium --session-override --relaxed-security` 

## Environment

My phone (Pixel, os - 8.1.0 ) is unlocked from the Settings. 

`$ appium --version`
`1.7.2`

**Comment by mykola-mokhnach** [comment]
This is not going to work since `adb logcat` does not return immediately after being called, but rather keep running and printing collected logs into stdout. Use the built-in logging interface in order to collect phone logs.

**Comment by mayuayla** [comment]
@mykola-mokhnach     
Thanks.  I was experimenting with logcat.  But what I really want to do is adb screenrecord.   Any idea to get the following working from the tests without the command hanging? 

`args = {"command": "screenrecord", "args": "/sdcard/test.mp4"}`
`output = get_driver.execute_script("mobile: shell", args)`

**Comment by mykola-mokhnach** [comment]
Any command, which does not return the control to shell immediately, is going to fail with the same error. 

Regarding screen record - there are primitives for it in the driver, however I don't see them to be exposed via the API. I'll create a PR to make them available via `mobile:` endpoint in android driver

**Comment by mayuayla** [comment]
Thank you for helping the community :)

**Comment by mykola-mokhnach** [comment]
Linking https://github.com/appium/appium-android-driver/pull/303

**Comment by mayuayla** [comment]
Awesomeness. Thx.
