### ISSUE TITLE
On Android, one `WebElement` fails to see that another `WebElement` refers to the same actual UI element

### ISSUE THREAD

**Issue by neboskreb** [appium/appium#9962]
## The problem

On Android, one `WebElement` fails to see that another `WebElement` refers to the same actual UI element.

## Environment

~* Appium version (or git revision) that exhibits the issue:~
~* Last Appium version that did not exhibit the issue (if applicable):~
~* Desktop OS/version used to run Appium:~
~* Node.js version (unless using Appium.app|exe):~
~* Mobile platform/version under test:~
~* Real device or emulator/simulator:~
~* Appium CLI or Appium.app|exe:~

```
        <dependency>
            <groupId>io.appium</groupId>
            <artifactId>java-client</artifactId>
            <version>3.4.1</version>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>2.47.1</version>
        </dependency>

```

## Details
See section Code.

## Link to Appium logs
No logs needed.

## Code To Reproduce Issue [ Good To Have ]
```
/* GIVEN */
DesiredCapabilities capabilities = new DesiredCapabilities();
AppiumDriver driver = new AndroidDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);

/* WHEN */
WebElement ref1 = driver.findElementById("select_dialog_listview");
WebElement ref2 = driver.findElementById("select_dialog_listview");

/* THEN */
assertEquals("Otherwise the whole idea is screwed", ref1, ref2);
```

**Comment by mykola-mokhnach** [comment]
Please report to https://github.com/appium/java-client

**Comment by neboskreb** [comment]
@mykola-mokhnach, thank you very much.

@others with the same problem:
Raised new ticket there: https://github.com/appium/java-client/issues/804
Similar ticket discussing the underlying problem: https://github.com/appium/java-client/issues/227
