### ISSUE TITLE
uiautomator2 tap with coordinates not working

### ISSUE THREAD

**Issue by drhoet** [appium/appium#9969]
## The problem

touch().tap( element, x, y ) taps in the middle of the element instead of at coordinates x,y.

## Environment
* Appium version (or git revision) that exhibits the issue: Appium 1.7.1 with uiautomator2 driver.
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Windows 7
* Node.js version (unless using Appium.app|exe): v6.9.1
* Mobile platform/version under test: Android (all versions)
* Real device or emulator/simulator: tested with simulator
* Appium CLI or Appium.app|exe: Appium java client

## Details

I believe the cause is in https://github.com/appium/appium-uiautomator2-driver/blob/f651819a04c41840ac67dc2e675653394106dc34/lib/commands/element.js#L82-L83
The x and y that are written in the params object should be at keys "x" and "y" and not at x and y. This is also reflected in the following log snippet:

`2018-01-12 15:37:34:662 - info: [debug] [JSONWP Proxy] Proxying [POST /element/a0e8e521-94f2-47b6-817c-896985cc4f07/click] to [POST http://localhost:8200/wd/hub/session/d5f58680-c907-4c09-b5c5-bf02e4f95dd0/element/a0e8e521-94f2-47b6-817c-896985cc4f07/click] with body: {"151":151,"308":308,"element":"a0e8e521-94f2-47b6-817c-896985cc4f07"}`

The body contains no x and y keys but instead the x and y values as keys.

## Link to Appium logs

https://gist.github.com/drhoet/10c7bc1149fc92d78319c2af63dfe0a1

## Code To Reproduce Issue [ Good To Have ]

```java
import static org.openqa.selenium.By.className;
import static org.openqa.selenium.By.xpath;
import static org.openqa.selenium.support.ui.ExpectedConditions.elementToBeClickable;

import java.net.MalformedURLException;
import java.net.URL;

import io.appium.java_client.AppiumFluentWait;
import io.appium.java_client.TouchAction;
import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.remote.MobileCapabilityType;
import io.appium.java_client.remote.MobilePlatform;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.NoSuchElementException;
import org.openqa.selenium.StaleElementReferenceException;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.support.ui.FluentWait;

public class TapTest
{
   private AndroidDriver driver;

   @Before
   public void setup() throws MalformedURLException
   {
      final DesiredCapabilities capabilities = new DesiredCapabilities();
      capabilities.setCapability( MobileCapabilityType.AUTOMATION_NAME, "uiautomator2" );
      capabilities.setCapability( MobileCapabilityType.PLATFORM_NAME, MobilePlatform.ANDROID );
      capabilities.setCapability( MobileCapabilityType.DEVICE_NAME, "Nexus_5X_API_23" );
      capabilities.setCapability( MobileCapabilityType.APP,
         "C:\\Projekte\\ReproduceIssue\\sample-code\\sample-code\\apps\\VodQA.apk" );

      capabilities.setCapability( MobileCapabilityType.LANGUAGE, "fr" );
      capabilities.setCapability( MobileCapabilityType.LOCALE, "CA" );

      driver = new AndroidDriver<>( new URL( "http://127.0.0.1:4723/wd/hub" ), capabilities );
   }

   @Test
   public void testTap()
   {
      fluentWait().until( elementToBeClickable( className( "android.widget.Button" ) ) ).click();
      fluentWait().until( elementToBeClickable( xpath( "//android.view.ViewGroup[@content-desc=\"slider1\"]" ) ) )
         .click();

      final WebElement slider = fluentWait().until( elementToBeClickable( className( "android.widget.SeekBar" ) ) );
      new TouchAction( driver )
         .tap( slider, 20, 10 )
         .perform();

      // the slider is now at the middle value. It should be somewhere near the beginning...
   }

   private FluentWait<AndroidDriver> fluentWait()
   {
      return new AppiumFluentWait<>( driver )
         .ignoring( NoSuchElementException.class )
         .ignoring( StaleElementReferenceException.class );
   }
}
```

**Comment by drhoet** [comment]
Same happens with the press method, but I didn't find the location in the code where it goes wrong.

```java
      new TouchAction( driver )
         .press( slider, 500, 10 )
         .release()
         .perform();
```

When adding a `waitAction()` directly after the `press` it seems to work correctly.

**Comment by mykola-mokhnach** [comment]
Thanks for pointing it out. Will be fixed in the next beta
