### ISSUE TITLE
Takes 1 minute to init() 

### ISSUE THREAD

**Issue by trix0** [appium/appium#9970]
## The problem

Hey
I have a small problem It takes around 1 minute to start the app on my phone. On emulator it takes around 10 seconds.
Is it normal or is there some kind of issue ?

Node.js
```js
const opts = {
port: 4723,
desiredCapabilities: {
platformName: “Android”,
platformVersion:“6.0”,
deviceName: “Android”,
appPackage:“appPackage”, // not an issue
appActivity:“com.unity3d.player.UnityPlayerActivity”,
automationName: “uiautomator2”,
udid:“cd21ccc5”, //cd21ccc5 emulator-5554
fullReset:false,
noReset:true

}
};
const client = wdio.remote(opts);
```

#Emulator

Label	Interval	Total	Recorded
node init	---	---	Fri, 12 Jan 2018, 10:49:38.833
1	loading time	00:00:12.624	00:00:12.624	Fri, 12 Jan 2018, 10:49:51.457
2	test completed	00:00:39.403	00:00:52.027	Fri, 12 Jan 2018, 10:50:30.860

#Real Device

Label	Interval	Total	Recorded
node init	---	---	Fri, 12 Jan 2018, 10:51:26.137
1	loading time	00:01:23.239	00:01:23.239	Fri, 12 Jan 2018, 10:52:49.376 8x slower than emulator
2	test completed	00:01:36.671	00:02:59.910	Fri, 12 Jan 2018, 10:54:26.047	2.5x slower than emulator //(understandable)//

## Environment

* Appium version (or git revision) that exhibits the issue:1.7.1,1.7.2
* Last Appium version that did not exhibit the issue (if applicable):-
* Desktop OS/version used to run Appium:win 10
* Node.js version (unless using Appium.app|exe):8.9.3, as well exe
* Mobile platform/version under test: Real 6.0.1 samsung A3
* Real device or emulator/simulator: Real
* Appium CLI or Appium.app|exe: both

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
Log
https://pastebin.com/nZnkxLCb

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]
```js
const fs=require("fs");
const wdio = require('webdriverio');
const cv = require('opencv4nodejs');
//var sizeOf = require('image-size');

const opts = {
  port: 4723,
  desiredCapabilities: {
    platformName: "Android",
    platformVersion:"6.0.1",
    deviceName: "Android",
    appPackage:"com.app", // not mistake here
    appActivity:"com.unity3d.player.UnityPlayerActivity",
    automationName: "uiautomator2",
    udid:"emulator-5554", //cd21ccc5 emulator-5554
    fullReset:false,
    noReset:false,
    autoGrantPermissions:true,
    skipUnlock:true

  }
};
const client = wdio.remote(opts);

fnInit()
.catch((err)=>{
  throw err;
});





async function fnInit(){
  try{
    const init=await client.init();
    const loading=await fnLoading(40);
    const fnTest=await fnLoginTest();

  }
  catch(err){
    throw(err);
  }

};
```

**Comment by imurchie** [comment]
In 1.7.1 the settings app is force uninstalled and then reinstalled. This will not happen in 1.7.2. This is the longest operation I see in the logs.

**Comment by imurchie** [comment]
It could be.

I just tried on a Nexus 6 (with Android 7.0). If none of the supporting apps were on the device, it took around 60s to initialize. The next time it took about 30s, when the files were all there.

**Comment by trix0** [comment]
Guys, please share ur knowledge ;) I am just not sure if I am doing somethin wrong or its how is it suppose to work. I was told that it should be around 15sec to init on real device ... what is true for emulator in my case.

Thx @imurchie for ur feedback

**Comment by trix0** [comment]
It takes around 17 seconds to give permission to appium app is there a way to go around this somehow ?  :)

2018-01-22 13:46:59:338 - info: [debug] [ADB] Running '/home/trixo/Android/Sdk/platform-tools/adb' with args: ["-P",5037,"-s","localhost:7425","shell","pm","grant","io.appium.settings","android.permission.INTERNET",";","pm","grant","io.appium.settings","android.permission.CHANGE_NETWORK_STATE",";","pm","grant","io.appium.settings","android.permission.ACCESS_NETWORK_STATE",";","pm","grant","io.appium.settings","android.permission.READ_PHONE_STATE",";","pm","grant","io.appium.settings","android.permission.WRITE_SETTINGS",";","pm","grant","io.appium.settings","android.permission.CHANGE_WIFI_STATE",";","pm","grant","io.appium.settings","android.permission.ACCESS_WIFI_STATE",";","pm","grant","io.appium.settings","android.permission.ACCESS_FINE_LOCATION",";","pm","grant","io.appium.settings","android.permission.ACCESS_COARSE_LOCATION",";","pm","grant","io.appium.settings","android.permission.ACCESS_MOCK_LOCATION",";","pm","grant","io.appium.settings","android.permission.SET_ANIMATION_SCALE",";","pm","grant","io.appium.settings","android.permission.CHANGE_CONFIGURATION",";"]

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium/issues/10070
