### ISSUE TITLE
iOS Real Device - Interacting with multiple Apps in a Appium single session

### ISSUE THREAD

**Issue by Gnanaraj-S** [appium/appium#9971]
I am currently automating mobile app on iOS and Android. Here is some insights on my issue.

Once installed the app on the real mobile device, clicking on a button in my mobile app launches certain  URL in the Safari browser, then I have to actually interact with the Safari browser in the same session. Currently I don't see a possibility for accomplishing this. In appium inspector when I try doing the same on real device, I observed, once I navigate to Safari browser from my mobile app then interacting with any Mobile elements in Safari is not possible

 I feel like this feature is not existing so far. If so, it would be great if we can get this feature added for iOS/ some work around(if exists).

In terms of Android, I can interact with multiple apps in a single test session.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.1
* Desktop OS/version used to run Appium: iOS
* Node.js version (unless using Appium.app|exe): using Appium APP
* Mobile platform/version under test: iOS 10.3.3
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium.app

**Comment by mykola-mokhnach** [comment]
This should be addresses in the upcoming beta release

**Comment by mykola-mokhnach** [comment]
Also these commands might be useful while dealing with multiple apps (all is available since iOS11): https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios/ios-xctest-mobile-apps-management.md

**Comment by Gnanaraj-S** [comment]
Any idea when can we expect the beta release?
