### ISSUE TITLE
iOS Appium, unable to .click(), .sendKeys(), ANY touch actions, it will not touch the keyboard

### ISSUE THREAD

**Issue by pringles8709** [appium/appium#9973]
iOS Appium, unable to .click(), .sendKeys(), ANY touch actions, it will not touch the keyboard

I have had a lot of issues with Appium and iOS for the quite a bit now. And most recently the newest update of appium seems to have broken our automation for iOS. For example the code below used to work perfectly without any issue.

try{
WebElement companySearch = apple_driver.findElementByName("Company Search");
companySearch.sendKeys(company);
}
catch(Exception e){
System.out.println("unable to find company");
}
Now this is not working at all with iOS.

## Environment

* 1.7.2
* 1.7.0
* Max OSX High Sierra 
* iOS 11.2.2:
* Real device
* Appium.app

## Details

Since updating to the newest desktop application I am still able to find the element just fine. The issue is the .sendKeys() or  .click() does not work anymore. Even if I try to do touch actions it wont work. Here are the things I have tried.

try{
WebElement companySearch = apple_driver.findElementByName("Company Search");
companySearch.click(); // goes from here straight to the exception
companySearch.sendKeys(company);
}
catch(Exception e){
System.out.println("unable to find company");
}

try{
TouchAction apple = new TouchAction(apple_driver);
WebElement companySearch = apple_driver.findElementByName("Company Search");
apple.tap(companySearch).perform(); // goes from here straight to the exception
apple_driver.sendKeys(company);
apple_driver.hideKeyboard();
}
catch(Exception e){
System.out.println("unable to find company");
}

I have tried to set the following capability. And I have turned it false as well and repeated the same steps.

set capabilities.setCapability("nativeWebTap", true);

APPIUM LOGS

Here is the link to the logs. https://gist.github.com/pringles8709/67be3d982f019a60de5998f8b9ed7055

## Code To Reproduce Issue [ Good To Have ]

package library;

import static org.testng.Assert.assertTrue;

import java.awt.AWTException;
import java.io.File;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.HashMap;
import java.util.List;
import java.util.concurrent.TimeUnit;
//import javax.imageio.ImageIO;
import org.apache.commons.io.FileUtils;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import org.openqa.selenium.NoAlertPresentException;
import org.openqa.selenium.OutputType;
//import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebElement;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.Assert;
import io.appium.java_client.AppiumDriver;
import io.appium.java_client.MobileBy;
import io.appium.java_client.MobileDriver;
import io.appium.java_client.MobileElement;
import io.appium.java_client.TouchAction;
import io.appium.java_client.ios.IOSDeviceActionShortcuts;
import io.appium.java_client.ios.IOSDriver;
import io.appium.java_client.ios.IOSElement;
import io.appium.java_client.ios.internal.*;
import io.appium.java_client.ios.IOSTouchAction;
import io.appium.java_client.remote.HideKeyboardStrategy;
import io.appium.java_client.remote.MobileCapabilityType;
import io.appium.java_client.remote.MobilePlatform;
import page_objects.page_object_constants;
import testDirectory.Constants;

public class apple {
public String deviceName = "";
public String deviceVersion = "";
public String node_url = "";
WebDriver WEBDR1VER2;
	
@SuppressWarnings("rawtypes")
public AppiumDriver set_up(String deviceUDID, String deviceVersion, String company_code,
String deviceName, AppiumDriver<WebElement> apple_driver) throws InterruptedException{
//Create object for  DesiredCapabilities class
DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability("automationName", "XCUITest");
capabilities.setCapability("xcodeOrgId", "2MK8BE2LMJ");
capabilities.setCapability("xcodeSigningId", "iPhone Developer");
capabilities.setCapability("newCommandTimeout", 0);
capabilities.setCapability("autoGrantPermissions", true);
capabilities.setCapability("autoAcceptAlerts", true);
capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, deviceName);
capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, deviceVersion);
capabilities.setCapability(MobileCapabilityType.UDID, deviceUDID);
capabilities.setCapability("noReset", true);
capabilities.setCapability("clearSystemFiles", true);
capabilities.setCapability("platformName", "iOS");
capabilities.setCapability("nativeWebTap", true);

try{
WebElement companySearch = apple_driver.findElementByName("Company Search");
companySearch.sendKeys(company);
}
catch(Exception e){
System.out.println("unable to find company");
}

**Comment by KazuCocoa** [comment]
What about the difference of `pageSource`?

**Comment by mykola-mokhnach** [comment]
I don't observe any errors in the attached log

**Comment by pringles8709** [comment]
Also here are the ID's that I get when inspecting through Safari. 
<input id="information_POP_search_term" type="text" onkeyup="validateCompanyID();" onblur="input_on_blur(this);"> 
<label for="information_POP_search_term"><span>Company Search</span>

**Comment by pringles8709** [comment]
mykola-mokhnach, there are no errors because Appium doesn't display any. That is part of the issue I am having.

**Comment by mykola-mokhnach** [comment]
but I also don't see any calls to `/click` or `/perform` endpoint

**Comment by KazuCocoa** [comment]
Thanks! and could you also put the previous, which works well, `pageSouce`?
https://github.com/appium/appium/issues/9973#issuecomment-357469593

If this issue's main problem is _can't find particular elements, not `sendKeys` itself_, I expect we can see some diffs between them.

**Comment by pringles8709** [comment]
Well so far what it will do is that if I run in it in debug mode, when I get to the part where it needs to find the ID it will think for a second and then the arrow will move on to the sendKeys part. But after I step into the sendKeys to goes straight to my catch. The same thing happens with .click().

**Comment by pringles8709** [comment]
Mykola-mokhnach, maybe we are misunderstanding each other. If you look at my description you can see the things that I have tried to do to fix the issue. .click() doesn't need another action to perform it. Are you talking about looking at the appium logs to see if there are any places that call for a click?

**Comment by pringles8709** [comment]
KazuCocoa, what do you mean by "put the previous"?

**Comment by KazuCocoa** [comment]
I meant Appium `1.7.0`'s result since you `Last Appium version that did not exhibit the issue` section as 1.7.0.
If we can see the diff the results of `pageSource`, we can understand what elements Appium can't find and fail to `.click()`.

**Comment by pringles8709** [comment]
Alright I just sent the pagesource for the the version of appium that did work previously. https://gist.github.com/pringles8709/a591ff3166c3e7049cfe795d61abee9e I didn't see any differences between the two, but will probably see something I something I don't.

**Comment by pringles8709** [comment]
I have found a temporary solution. It's not ideal and its something that should be addressed so that it makes it easier to interact with an element. What I have found is that if I do a touchAction with x,y coordinates it will work. But since we are using different devices that range in size it will be difficult to rearrange all of our code for it to be worth while.

**Comment by mykola-mokhnach** [comment]
Closing it as non Appium server-related
