### ISSUE TITLE
session-less /source WDA endpoint is not supported anymore?

### ISSUE THREAD

**Issue by NozomiIto** [appium/appium#9974]
## The problem

According to [endpoints-wda.md](https://github.com/appium/appium-xcuitest-driver/blob/master/docs/endpoints-wda.md), WebDriverAgent endpoint accepts session-less /source command like http://localhost:8100/source, and Appium1.7.1 actually accepts this session-less endpoint well.

But since 1.7.2, this endpoint returns the following JSON, and cannot get source without session anymore.

```
{
  "value" : "Cannot get 'xml' source of the current application",
  "sessionId" : "E208A1D4-1412-42B9-9869-A6EEBC068ED9",
  "status" : 13
}
```

I confirmed the latest [facebook/WebDriverAgent](https://github.com/facebook/WebDriverAgent) still accepts session-less source command, so I think it is [appium/WebDriverAgent](https://github.com/appium/WebDriverAgent) problem.

I loved WDA session-less /source and /screenshot endpoint very much since I can easily query useful debug information without knowing session detail, and even I use these endpoints for my tool for my business.

I know this end point is not so important for the Appium core feature, but I'm very very glad if you continue to support this endpoint 😣 

## Environment

* Appium version that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue: 1.7.1
* Mac OS X 10.13.2
* Node v7.9.0
* XCode9.2
* iOS simulator for iOS11.2 and iPhone8
* Appium CLI

## Link to Appium logs

[Appium server log](https://gist.github.com/NozomiIto/86f9bfc38f8d4d36355de60f12c1179b).

Files under `/var/folders/5j/86p6_7p53x92gs6w30cxy3_w0000gn/T/com.apple.dt.XCTest/IDETestRunSession-E81D68F9-6211-495C-A640-736923FF0072/WebDriverAgentRunner-4F8923F7-BD17-4A11-8F5E-5FBDAFB501DF`

[StandardOutputAndStandardError.txt](https://gist.github.com/NozomiIto/ae085a91e64f653edd3ae093f410792d).

[Session-WebDriverAgentRunner-2018-01-13_141137-AJHbOq](https://gist.github.com/NozomiIto/faec385cd9d9355ba0e47612ea09b5a4)

## Code To Reproduce Issue

Run the following Python code. It sleeps very long after staring session.

```python
from appium import webdriver
import time

desired_caps = {}
desired_caps['platformName'] = 'iOS'
desired_caps['platformVersion'] = '11.2'
desired_caps['deviceName'] = 'iPhone 8'
desired_caps['automationName'] = 'XCUITest'
desired_caps['app'] = 'com.apple.camera'
desired_caps['showXcodeLog'] = 'true'
driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)
time.sleep(3000)
```

Then visit http://localhost:8100/source from the web browser.

**Comment by KazuCocoa** [comment]
I've created a PR to solve this.
BTW, you can get source `http://localhost:8100/session/E208A1D4-1412-42B9-9869-A6EEBC068ED9/source` as a hot fix.

**Comment by NozomiIto** [comment]
@KazuCocoa Oh, thank you so much! It is very helpful PR!!!
Using session-less source command is the easiest way for me. So I will apply your change to my local Appium code base for hot fix if necessary!
