### ISSUE TITLE
While Connecting Appium Server and starting a New Session,getting ECONNRESET Issue.

### ISSUE THREAD

**Issue by AnubhavGitHub** [appium/appium#9975]
![appium issue](https://user-images.githubusercontent.com/25146950/34903350-4cc47e8e-f855-11e7-9761-fa11b90884ea.PNG)

![appium issue1](https://user-images.githubusercontent.com/25146950/34903343-249488be-f855-11e7-9451-fd7abce56113.PNG)
## The problem

While Connecting Appium Server and starting a New Session,getting ECONNRESET Issue

## Environment

* Appium version (or git revision) that exhibits the issue:1.3.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Mi A1 Android 8.0
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Started Appium Server with New Session Window and Desires Capabilities Mentioned
{
  "BROWSER_NAME": "chrome",
  "platformname": "android",
  "devicename": "Mi A1",
  "appPackage": "in.amazon.mShop.android.shopping",
  "appActivity": "com.amazon.mShop.home.HomeActivity",
  "noReset": "false"
}
![appium issue1](https://user-images.githubusercontent.com/25146950/34903341-1dbfdafc-f855-11e7-9721-7e3f575fdef8.PNG)

**Comment by mykola-mokhnach** [comment]
Please report to https://github.com/appium/appium-desktop/issues

BTW, is the server really running? Do you see it is listening on the selected system port?
