### ISSUE TITLE
Appium doesn't find a element in iOS modal window 

### ISSUE THREAD

**Issue by DiogoMiranda** [appium/appium#9977]
I am having an issue while automating iOS app via appium. The problem I am facing is our app has modal window comes up on clicking some link in app, and I need to tap on some element inside that modal window. But I haven’t been successful.  Basically, my suspicion is previous window before modal window is blocking to interact with modal window. If some one can suggest on how to switch to interact with that modal window, it would be really helpful.

**Comment by mykola-mokhnach** [comment]
Sorry, but no one will be able to help unless you provide the necessary information, like server info, logs, code examples and page source.

**Comment by IsaiaSilva** [comment]
Mesma situação.
