### ISSUE TITLE
[Android] Unable to switch into native context after reset/restart app

### ISSUE THREAD

**Issue by vmaxim** [appium/appium#9978]
## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable): 1.7.1
* Desktop OS/version used to run Appium: Mac|Win
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Both
* Appium CLI or Appium.app|exe: CLI

## Details

1. Create new session
2. Reset app
3. Switch to Native context

After app reset ```curContext``` becomes ```null```  (appium/appium-android-driver#302) and ```switchContext``` throws NPE at [context.js#L66](https://github.com/appium/appium-android-driver/blob/ab98f6faecb27a67b543a9be25cef650fb536063/lib/commands/context.js#L66)

## Link to Appium logs

```
[HTTP] <-- POST /wd/hub/session/2c3b17ab-d78d-4ee1-8ce5-a5c98d4cef3f/appium/app/reset 200 2636 ms - 76 
[HTTP] --> POST /wd/hub/session/2c3b17ab-d78d-4ee1-8ce5-a5c98d4cef3f/context {"name":"NATIVE_APP"}
[debug] [MJSONWP] Calling AppiumDriver.setContext() with args: ["NATIVE_APP","2c3b17ab-d78d-4ee1-8ce5-a5c98d4cef3f"]
...
[MJSONWP] Encountered internal error running command: TypeError: Cannot read property 'indexOf' of null
    at AndroidUiautomator2Driver.helpers.isChromedriverContext (/Users/jenkins/npm/lib/node_modules/appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/context.js:183:18)
    at AndroidUiautomator2Driver.callee$0$0$ (/Users/jenkins/npm/lib/node_modules/appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/context.js:66:19)
```

**Comment by mykola-mokhnach** [comment]
thanks for the report. This is an easy one.

**Comment by vmaxim** [comment]
```[debug] [AndroidDriver] Available contexts: ["NATIVE_APP","WEBVIEW_com.kronos.mobile.android"]
[MJSONWP] Encountered internal error running command: Error: Didn't know how to handle switching to context 'NATIVE_APP'
    at AndroidUiautomator2Driver.callee$0$0$ (/Users/jenkins/npm/lib/node_modules/appium/node_modules/appium-android-driver/lib/commands/context.js:78:11)
```

**Comment by vmaxim** [comment]
@mykola-mokhnach Why did you close it?

**Comment by mykola-mokhnach** [comment]
because the change is merged

**Comment by vmaxim** [comment]
It seems you miss my post with the next exception after this changes.

**Comment by mykola-mokhnach** [comment]
don't mix different issues together. If there is still a problem in an another place then create a new issue for it.

**Comment by vmaxim** [comment]
Ok. Let's clone this one - #10046.
