### ISSUE TITLE
appium server does not return all available WebViews Android testing

### ISSUE THREAD

**Issue by orevron** [appium/appium#9980]
i have an android app with 1 webview:
 `['NATIVE_APP', 'WEBVIEW_com.capriza.enterprise.dev']`
for couple of months now that i'm using this apk on 2 different machines:
(1) macbook pro OS High Sierra:
    appium version 1.7.1
(2) and desktop that runs linux ubuntu 16.04:
    appium version 1.6.1

recently when i try to test the android application on the macbook (1), after loading the application, i try to switch context (from the native_app to the webview).

but when i try the request
`http://127.0.0.1/wd/hub/session/:sessionId/contexts`
the response i get is only the native_app context (although i can clearly see the webview on the emulator)

but when i try it on my desktop (2), it all works just fine and the contexts i get in response to the request is an array with 2 contexts as expected.

- apk is the same on both machines
- the macbook runs newer version of appium as i work with xcode 9.
- the code is the same on both machines:
1. start session with the following desiredCapabilities: 
 https://127.0.0.1/wd/hub/session
 POST
`{
  "desiredCapabilities": {
    "platformName": "Android",
    "deviceName": "nexus1",
    "platformVersion": "7.1.1",
    "automationName": "appium",
    "app": "/data/capriza/app/Capriza-Release.apk",
    "appActivity": ".CaprizaActivity",
    "newCommandTimeout": 60000
     }
}
`
2. try to switch to the wanted Webview:
 https://127.0.0.1/wd/hub/session/:sessionId/context
POST
`{
"name": "WEBVIEW_com.capriza.enterprise.dev"
}`

attached log file of the appium server when i start the session and asking for available contexts (and expect to see 2 contexts)
also attached screenshot of the emulator with the webview and postman with the response...

[log.log](https://github.com/appium/appium/files/1629311/log.log)

![image](https://user-images.githubusercontent.com/20145882/34915854-174010d4-f936-11e7-8ac6-e0473aff37cb.png)

**Comment by mykola-mokhnach** [comment]
Is the webview visible if you try to connect to it using Chrome remote debugger?

**Comment by mykola-mokhnach** [comment]
Closed as inactive
