### ISSUE TITLE
Webdriver cann't use set_page_load_timeout when using appium1.7.

### ISSUE THREAD

**Issue by HeartIsBeat** [appium/appium#9982]
## The problem
I use appium1.7 to open app's chrome browser.Then open a url.
![image](https://user-images.githubusercontent.com/20472976/34929705-6ceb242c-fa00-11e7-9bc9-be1cc71d287d.png)
![image](https://user-images.githubusercontent.com/20472976/34929682-5510aeee-fa00-11e7-9ea5-3fc66fdf6c43.png)
![image](https://user-images.githubusercontent.com/20472976/34929539-68eace50-f9ff-11e7-8362-22a79bab574c.png)

When I use set_page_load_timeout in appium1.4, it's ok!

## Environment
linux or windows10, python2.7, appium1.7
* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details
![image](https://user-images.githubusercontent.com/20472976/34929563-8a864c24-f9ff-11e7-885f-f6b2348e208f.png)

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!
![image](https://user-images.githubusercontent.com/20472976/34929618-d6c4093c-f9ff-11e7-99c8-ae4787554335.png)

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
WebDriverAgent does not support setting of page load time. This error is expected.
