### ISSUE TITLE
Appium Desktop 1.3.1 (1.7.2): Failed to launch Android app using driver.get(deeplinkurl), it was working on v1.2.6 (1.7.1)

### ISSUE THREAD

**Issue by Pankajshuklaqa** [appium/appium#9983]
## The problem
Appium Desktop 1.3.1 (1.7.2): Failed to launch Android app using driver.get(deeplinkurl), it was working on v1.2.6 (1.7.1)

Raised ticket to Appium Desktop : https://github.com/appium/appium-desktop/issues/383#issuecomment-357296992

Dan Graham Comments:
The version of Appium that's being used was bumped up for 1.7.1 to 1.7.2
Can you try your test with Appium 1.7.1 from the command line to see if that fixes the problem?
If it does fix the problem, then open an issue at https://github.com/appium/appium/issues
If it does not fix the problem, then we can leave this issue open and I can look for a fix
I strongly suspect it's an Appium issue though.

My comments:-
@dpgraham, to check, I already upgraded my Appium(command line one, not desktop) to v1.7.2 from v1.7.1. After having your comment, I downgraded Appium to v1.7.1. Try to run but no luck, same issue with v1.7.1

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable): 1.7.1
* Desktop OS/version used to run Appium: MacOS Sierra v10.12.6
* Node.js version (unless using Appium.app|exe): 4.1.2
* Mobile platform/version under test: 
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: both

## Link to Appium logs

https://gist.github.com/Pankajshuklaqa/3e426b185162fd71053634055ff56d18

## Code To Reproduce Issue
driver.get(deeplinkurl)

**Comment by mykola-mokhnach** [comment]
I see that the server call is working properly:

> [debug] [ADB] Running '/Users/pankajshukla/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","c98146af0487a20e","shell","am","start","-W","-a","android.intent.action.VIEW","-d","surveymonkey://open?token=jCKdHaIBCj7uAWdMUJomqVULaEzM5t4YeX7t625i5NIMNmMF882v.z19gysCOlfIy9kd0pwtbbKR0RvswQtUwGVpRUmIXxfmDcesPyRdjDiFDWFrg8NvRo7JbrazPcrfhqGkJh6jzN.s-2YtCceWcw==\\&key=mobilemobilemobilemobile\\&deviceid=1f436b9f-9621-4124-80e6-d81d886c62c1","com.surveymonkey"]


Are you sure the provided parameters are valid? Have you tried to invoke that manually via the adb command line?

**Comment by Pankajshuklaqa** [comment]
@mykola-mokhnach Yes, provided parameters are valid, it's working find with same parameters and setup on other machine having Appium Desktop v1.2.6 (1.7.2)

Yes, I tried to invoke with adb, it's working manually, here is the command & output details:-

$ adb shell am start -a "android.intent.action.VIEW" -d "surveymonkey://open?token=VtUuawx74hMJ9BiGEmI-DdGKmpx5JlC9O0JtFmJMo20Xd1cpFqx5eqiT8zJtk7Fs7oj23lFn9BI7f1ozEH3RFVL8ApVTZz09NaYzkU8iLmXIoXX47sq2b7pTyp5Qy4LHkemzKmQ9yfFTS4x3Vh3VMg==\&key=mobilemobilemobilemobile\&deviceid=5da8206b-41dd-4cb8-81eb-f57c4a1797d9"

Starting: Intent { act=android.intent.action.VIEW dat=surveymonkey://open?token=VtUuawx74hMJ9BiGEmI-DdGKmpx5JlC9O0JtFmJMo20Xd1cpFqx5eqiT8zJtk7Fs7oj23lFn9BI7f1ozEH3RFVL8ApVTZz09NaYzkU8iLmXIoXX47sq2b7pTyp5Qy4LHkemzKmQ9yfFTS4x3Vh3VMg==&key=mobilemobilemobilemobile&deviceid=5da8206b-41dd-4cb8-81eb-f57c4a1797d9 launchParam=MultiScreenLaunchParams { mDisplayId=0 mFlags=0 } }

**Comment by mykola-mokhnach** [comment]
>  Yes, provided parameters are valid, it's working fine with same parameters and setup on other machine having Appium Desktop v1.2.6 (1.7.2)

Perhaps, this is a problem with the connected device itself?

**Comment by Pankajshuklaqa** [comment]
@mykola-mokhnach if it's issue at Appium end, then let me debug it at my end, give me some, will let you know shortly.

**Comment by Pankajshuklaqa** [comment]
@mykola-mokhnach, I didn't find any issue with the device, script code and system. From my point of view, the issue is Appium v1.7.2 only, because I cleanly uninstalled Appium v1.7.2 and reinstalled v1.7.1. Now, the app is started getting launched and login with deeplink. 

For your reference, please find [logs](https://gist.github.com/Pankajshuklaqa/4fde6198351dadadac7393283490fdbd) of freshly installed Appium v1.7.1 which executed deeplink successfully.

**Comment by mykola-mokhnach** [comment]
Try the `mobile: deepLink` feature, which has been added to UiAutomator2 in Appium v1.8.0

**Comment by dpgraham** [comment]
http://appium.io/docs/en/commands/mobile-command/#android-uiautomator2-only

**Comment by Pankajshuklaqa** [comment]
@mykola-mokhnach, thanks for implementing mobile: deepLink feature.  Currently, busy with other assignments. You may close this issue. I will definitely try this and share the result.
