### ISSUE TITLE
Type/Sendkeys issue on iOS Devices

### ISSUE THREAD

**Issue by ppanuganti** [appium/appium#9988]
## Details

Device : Mobile Phones
OS : iOS
Appium Version : 1.7.1
Browser : Safari

## The problem

We are seeing type/Sendkeys issue on iOS Devices - with versions 10 and above 
In the automation, the value is getting typed but once the control comes out of that particular text field ,the value is getting cleared in that respective field

This is the link to the site
https://www.staples.com/ (username and password fields of login page)
Please suggest Is there a way to handle this issue

Thanks,

**Comment by mykola-mokhnach** [comment]
> In the automation, the value is getting typed but once the control comes out of that particular text field ,the value is getting cleared in that respective field

We don't do any extra actions after the the value is typed into the field. Try to connect javascript debugging listener to your page element(s) to see which events are happening on the particular text field while the automation is in progress.

**Comment by goloroden** [comment]
We have that very same problem, too, with Appium 1.8.1 on BrowserStack.

**Comment by davidamplify** [comment]
anyone find a solution to this? mine was previously working with an xpath but a later build no longer works with this so trying to find a more general solution and this keeps failing.
