### ISSUE TITLE
UiAutomator Shutdown unexpectedly 

### ISSUE THREAD

**Issue by srapriya** [appium/appium#9992]
The problem

“UiAutomator exited unexpectedly with code 0, signal null” 

Getting above error while running selenium script on a remote device.

Environment
Android Studio - 1.6.5
Selenium - 3.8.1
TestNG - 6.9.10
Appium - 1.6.4
OS- Windows
Platform - Android

Details

We have remote devices which are getting connected as a local device with our system and reflecting in adb. When we are running selenium script on these devices then we are getting the exception “UiAutomator exited unexpectedly with code 0, signal null” . Code is running successfully on local device but not able to perform the same on remote device.
[AppiumIssue.txt](https://github.com/appium/appium/files/1634173/AppiumIssue.txt)

**Comment by mykola-mokhnach** [comment]
Use UIAutomator2 with newer android versions

**Comment by srapriya** [comment]
Tried with UIAutomator2 as well but getting the same error. 

Thanks

**Comment by mykola-mokhnach** [comment]
Sorry, unable to help without logs
