### ISSUE TITLE
Appium Desktop v1.2.6: ESOCKETTIMEDOUT after executing 120 test case on Android App.

### ISSUE THREAD

**Issue by Pankajshuklaqa** [appium/appium#9993]
## Description
Android test suite has 140+ test cases, every I add new test cases in this test suite and run the test suite. Appium throws error ESOCKETTIMEDOUT after executing 120 test case.

## Environment
* java client build version : 4.1.2
* Appium server version : 1.7.1
* Desktop OS/version used to run Appium: 1.2.6
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:
* Mobile platform/version under test: Android v5.1.1
* Real device or emulator/simulator: Real device - Samsung Galaxy S6

## Code To Reproduce Issue 
Appium throws error ESOCKETTIMEDOUT at
scrFile = ((TakesScreenshot)driver).getScreenshotAs(OutputType.FILE);
Above code worked for many times during execution during test suite execution.

## Exception stack traces

Please find [Stack traces_ESOCKETTIMEDOUT](https://gist.github.com/Pankajshuklaqa/87580e7ba82b2567f95d4f13dc761cce) exception thrown by java.

## Link to Appium logs

 Please find [AppiumLogs_ESOCKETTIMEDOUT](https://gist.github.com/Pankajshuklaqa/ecd9506b3594efaa99c319ed6e2c5c8c)

**Comment by mykola-mokhnach** [comment]
this error means that the server did not send the response within the given timeout. It might be that the machine experiences performance issues or memory/resource leaks. Usually it hardly possible to catch or resolve such problems in the lab. I'd try to reboot/reset the test env after several amount of tests is executed.

**Comment by trix0** [comment]
@Pankajshuklaqa i would like to ask you how long does it take your phone to start a session ? #9970
