### ISSUE TITLE
Tow activity,Switch to context error,(cannot activate web view)

### ISSUE THREAD

**Issue by longzhao** [appium/appium#9995]
Hi:

Hava tow activity and two webview,I can use switch to context get webview context on first activity , 
Go to second activity use switch to context  webview context  error,
RIDE show error message:
 could not be run on failure: WebDriverException: Message: unknown error: cannot activate web view
  (Session info: webview=33.0.0.0)

Thank you

**Comment by mykola-mokhnach** [comment]
Please fill out the issue reporting form properly. The information provided in the report is not enough
