### ISSUE TITLE
Inspector has input keyboard display, refresh browser, prompt Internal Server Error.

### ISSUE THREAD

**Issue by fangyt** [appium/appium#9996]
## Environment

* Appium version :1.7.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:Mac 10.13.2 (17C88)
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
* Real device or emulator/simulator:iPhone6s，iOS 11.1
* Appium CLI or Appium.app|exe:
*xcodeVersion: 9.2 (9C40b)
## Details

I tried to use the inspection to get the page element, when the page has input keyboard, I refresh the browser page, the browser prompts Internal Server Error, but it is normal to not enter the keyboard.

## Link to Appium logs

~ app-inspector -u '04dc89aab59129dd435bbef665a00545011c7762' --verbose
              
              >> server.js:16:12 [master] pid:2584 server start with config:
              { port: 5678,
              verbose: true,
              udid: '04dc89aab59129dd435bbef665a00545011c7762',
              ip: '10.9.159.240',
              host: 'fangyongtengs-MacBook-Air.local',
                  loaded_time: '2018-01-16 19:19:03' }
              >> app-inspector.js:43:12 [master] pid:2584 server start at: http://10.9.159.240:5678
              >> xctest-client.js:56:14 [master] pid:2584 project path: /usr/local/lib/node_modules/app-inspector/node_modules/_xctestwd@1.3.12@xctestwd/XCTestWD/XCTestWD.xcodeproj
              >> xctest-client.js:242:14 [master] pid:2584 xcode version: 9.2
              >> XCTestWD version: 1.3.12
              >> xctest-client.js:190:18 [master] pid:2584 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/_xctestwd@1.3.12@xctestwd/XCTestWD/XCTestWD.xcodeproj
              >> xctest-client.js:190:18 [master] pid:2584 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/_xctestwd@1.3.12@xctestwd/XCTestWD/XCTestWD.xcodeproj
              >> xctestwd start with port: 8001
              >> proxy.js:55:14 [master] pid:2584 Proxy: /wd/hub/session:POST to http://localhost:8001/wd/hub/session:POST with body: {"desiredCapabilities":{}}
              >> proxy.js:85:20 [master] pid:2584 Got response with status 200: {"sessionId":null,"status":0,"value":{"sessionId":"D7F66904-D64F-4441-9195-2C00A72215B2","capabilities":{"browserName":" ","device":"iphone","sdkVersion":"11.1","CFBundleIdentifier":"com.apple.spri...
    >> iOS device started: 04dc89aab59129dd435bbef665a00545011c7762
    >> inspector start at: http://10.9.159.240:5678
    <-- GET /
    >> xctest-client.js:190:18 [master] pid:2584 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/_xctestwd@1.3.12@xctestwd/XCTestWD/XCTestWD.xcodeproj
    >> xctest-client.js:190:18 [master] pid:2584 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/_xctestwd@1.3.12@xctestwd/XCTestWD/XCTestWD.xcodeproj
    >> ios.js:67:10 [master] pid:2584 Dump iOS XML success, save to /usr/local/lib/node_modules/app-inspector/.temp/ios.json
    --> GET / 200
    <-- GET /
    >> xctest-client.js:190:18 [master] pid:2584 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/_xctestwd@1.3.12@xctestwd/XCTestWD/XCTestWD.xcodeproj
    >> xctest-client.js:190:18 [master] pid:2584 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/_xctestwd@1.3.12@xctestwd/XCTestWD/XCTestWD.xcodeproj
    >> ios.js:67:10 [master] pid:2584 Dump iOS XML success, save to /usr/local/lib/node_modules/app-inspector/.temp/ios.json
    --> GET / 200
    <-- GET /
    >> helper.js:94:16 [master] pid:2584 xctest client proxy error with: Error: socket hang up
    
Error: socket hang up
    at createHangUpError (_http_client.js:330:15)
    at Socket.socketOnEnd (_http_client.js:423:23)
    at Socket.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1062:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
    
    >> xctest-client.js:190:18 [master] pid:2584 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/_xctestwd@1.3.12@xctestwd/XCTestWD/XCTestWD.xcodeproj
    >> xctest-client.js:190:18 [master] pid:2584 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/_xctestwd@1.3.12@xctestwd/XCTestWD/XCTestWD.xcodeproj
    >> xctest-client.js:190:18 [master] pid:2584 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/_xctestwd@1.3.12@xctestwd/XCTestWD/XCTestWD.xcodeproj
    >> xctest-client.js:190:18 [master] pid:2584 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/_xctestwd@1.3.12@xctestwd/XCTestWD/XCTestWD.xcodeproj
    >> xctest-client.js:190:18 [master] pid:2584 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/_xctestwd@1.3.12@xctestwd/XCTestWD/XCTestWD.xcodeproj
    >> xctest-client.js:190:18 [master] pid:2584 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/_xctestwd@1.3.12@xctestwd/XCTestWD/XCTestWD.xcodeproj
    >> xctest-client.js:190:18 [master] pid:2584 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/_xctestwd@1.3.12@xctestwd/XCTestWD/XCTestWD.xcodeproj
    >> xctest-client.js:276:14 [master] pid:2584 killing deviceLogProc pid: 2594
    >> xctest-client.js:281:14 [master] pid:2584 killing runnerProc pid: 2587
    >> xctest-client.js:287:14 [master] pid:2584 killing iproxyProc pid: 2735
    >> xctest-client.js:201:16 [master] pid:2584 xctest client exit with code: 65, signal: null
    >> xctest-client.js:231:14 [master] pid:2584 iproxy exit with code: null, signal: SIGKILL
    >> xctest-client.js:155:16 [master] pid:2584 devicelog exit with code: null, signal: SIGKILL

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Can you provide the full server log?

**Comment by fangyt** [comment]
[appium-server-logs.zip](https://github.com/appium/appium/files/1635093/appium-server-logs.zip)
@mykola-mokhnach With the input keyboard display, the refresh page gets the control information, and wda prompts me to request a timeout.

**Comment by mykola-mokhnach** [comment]
It is the problem with WebDriverAgent itself. It has just frozen and stopped responding to Appium commands. Please report your issue to https://github.com/facebook/WebDriverAgent/issues
