### ISSUE TITLE
How to set xpath for button 

### ISSUE THREAD

**Issue by kamola** [appium/appium#9997]
The button doesn't have id. How can I set xpath to android.support.v7.widget.AppCompatButton

**Comment by tfcardoso** [comment]
Please use the forum for questions:

http://discuss.appium.io/

**Comment by kamola** [comment]
@tfcardoso  @imurchie cannot signup in discuss.appium.io neither with Google,Yahoo,Github nor with creating new account(not getting activation link).

**Comment by tfcardoso** [comment]
@kamola Maybe you inputting wrong email. Anyway, try to contact them:

_Contact Us
In the event of a critical issue or urgent matter affecting this site, please contact us at appium-discourse@js.foundation._

**Comment by kamola** [comment]
tried with several emails, it didn't work.
