### ISSUE TITLE
How to call Javascript command With appium.

### ISSUE THREAD

**Issue by sagarsheth27** [appium/appium#9998]
I am running one javascript command in Chrome inspect tool is like below:
**"$("#b9d25147-9456-4561-8e6f-bb35f8916b0f").click()**
in console. It will directly open Barcode scanner from app. I want to use this command in my selenium script. How to do this?
I was tried Javascript Executor, AutoIT and WebElement click element. Still i am failed. 
Please help me out for same. In spite of it if there is any other way then let me know please.
Appium version is 1.7.2. 
I am unable to login on discuss.appium.io.
I did forgot password. But didn't got any mail for same. Every time successfully mail sent pop up came. But didn't receive. 
My Mail id is sheth.sagar453@gmail.com

**Comment by imurchie** [comment]
There is little that can be said without the server logs from the attempts made. In general, the operation you want to do would be done with the JavaScript executor (along the lines of https://www.guru99.com/execute-javascript-selenium-webdriver.html).

**Comment by sagarsheth27** [comment]
Hi @imurchie 
PFA of appium server log. Here i also listed my code as well.
JavascriptExecutor js = (JavascriptExecutor)driver;
	       //String Script="$"+(("#b9d25147-9456-4561-8e6f-bb35f8916b0f").click();
		    js.executeAsyncScript("$"+("#b9d25147-9456-4561-8e6f-bb35f8916b0f")+".click()");
[appium-server-logs.txt](https://github.com/appium/appium/files/1637999/appium-server-logs.txt)

**Comment by imurchie** [comment]
The problem is that your Chrome version on the device is too low. 
```
[error] [Chromedriver] Error: Failed to start Chromedriver session: A new session could not be created. (Original error: session not created exception: Chrome version must be >= 60.0.3112.0
```

Please see the documentation here: http://appium.io/docs/en/writing-running-appium/web/chromedriver/#chromedriverchrome-compatibility
